### ISSUE TITLE
PrivacyStake (PIVS) Listning

### ISSUE THREAD

**Issue by PrivacyStake** [forkdelta/tokenbase#1000]
Contract address: 0x04ac42ce41f0f9831347bdf74fab03c828173e18

Issuer's official website: http://privacystake.com/

Description:  PrivacyStake is an anonymous staking platform. Current phase: ICO. We wanna get PIVS listed on many exchanges and we think we can bring in a big volume of buyers to ForkDelta.

Official contract address confirmation: http://privacystake.com/address.html

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://www.youtube.com/watch?v=0IpWLKhukvA&t=1753s
https://www.youtube.com/watch?v=Z_zw5QZ_IwE&t=17s
https://www.youtube.com/watch?v=kNlvPvo1gws&t=20s
https://www.youtube.com/watch?v=t3EcxLhKa5c&t=10s
https://www.youtube.com/watch?v=vXVXhCB06WM&t=51s
+tens more on YouTube to find

Thank you

**Comment by Kryptoniq** [comment]
Contract address not verified on etherscan. Please do so.

**Comment by PrivacyStake** [comment]
Hello,

Fixed.

Thanks

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically, links must be of at least 2 different kinds: eg., you have YouTube video links, please add a review article or other.

**Comment by PrivacyStake** [comment]
Contract address: 0x04ac42ce41f0f9831347bdf74fab03c828173e18

Issuer's official website: http://privacystake.com/

Description: PrivacyStake is an anonymous staking platform. Current phase: ICO. We wanna get PIVS listed on many exchanges and we think we can bring in a big volume of buyers to ForkDelta.

Official contract address confirmation: http://privacystake.com/address.html

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://www.youtube.com/watch?v=0IpWLKhukvA&t=1753s
https://www.youtube.com/watch?v=Z_zw5QZ_IwE&t=17s
https://www.youtube.com/watch?v=kNlvPvo1gws&t=20s
https://www.youtube.com/watch?v=t3EcxLhKa5c&t=10s
https://www.youtube.com/watch?v=vXVXhCB06WM&t=51s
+tens more on YouTube to find

https://nz.trustpilot.com/review/privacystake.com
https://bitcoinexchangeguide.com/privacystake-ico/
https://bitcoinexchangeguide.com/privacystake-ico/

Thank you

**Comment by freeatnet** [comment]
@PrivacyStake Can't seem to find any evidence of team or advisors, technical roadmap, or legal details of the ICO. https://nz.trustpilot.com/review/privacystake.com does not contain any meaningful review of the project, and https://bitcoinexchangeguide.com/privacystake-ico/ is extremely thin on information.

**Comment by PrivacyStake** [comment]
@freeatnet 
It is pretty normal these days that lending/staking programs do not provide team information. 
Mostly because for example: BitConnect & Davor have been shutdown.

Our website/staking program is hosted on offshore servers. We pay out interest (profits) using privacy coins. Our main goal is to be an anonymous staking platform (as stated on the website). Would be pretty weird to show the team behind it, we think it is a good thing to now show our faces, and our investors think the same!

Take a look at the review of J has & Gary Morgan, they go more in detail (Trustpilot).

About the whitepaper: Give us a opportunity to pay out those guaranteed profits :). We can only start our staking plan as soon as we are listed on an exchange.

I could not find any more reviews. There are some negative reviews but this is normal for lending/staking platforms, even if there platforms succeeds.

Hopefully you can give us a opportunity so we can proof our staking program is a way to build daily income. If not, we would already left the building and not ever bothered to apply to different exchanges.

Thank you!
