### ISSUE TITLE
Requesting of YAK Coin listing

### ISSUE THREAD

**Issue by yakcoin** [forkdelta/tokenbase#1001]
Contract address: 0x9D5E22B6599c426B453De4a43Df8a0Cb4de061b1
Decimals: 18
Name: YAK Coin
Symbol: YAK
Standard: ERC20 standard Ethereum Token 
Platform: Ethereum

Issuer's official website: http://www.yakcoin.net/

Description: YAK Coin (YAK) is the is a new standard ERC20 token on the Ethereum network. Our main goal is to make instant, private, payments online or in-store using secure open-source platform that will be hosted by thousands of users around the world and trade in most of the popular exchanges so anyone can easily exchange in YAK COIN. 

Official contract address confirmation: https://www.yakcoin.net/contract/

Links:
1. BitcoinTalk Forum: https://bitcointalk.org/index.php?topic=2931123.msg30108109
2. Telegram: https://t.me/joinchat/Hs5hVxDK8bb5v9AgXag62w
3. Twitter: https://twitter.com/YAKCoin
4.  Facebook: https://www.facebook.com/YAK.COIN.Crypto
5. Reddit: https://www.reddit.com/user/yakcoin
6. Email: info@yakcoin.net
7. Github: https://github.com/yakcoin/yakcoin
8. https://www.trendsmap.com/twitter/tweet/964706564845092865
9. https://etherscan.io/token/0x9d5e22b6599c426b453de4a43df8a0cb4de061b1
10. https://www.youtube.com/watch?v=jM9MDmKO-ZY
11. https://medium.com/@yakcoin/yak-coin-the-next-cryptocurrency-in-the-world-2e0a4bfd219

**Comment by yakcoin** [comment]
https://medium.com/@yakcoin/yak-coin-the-next-cryptocurrency-in-the-world-2e0a4bfd219

**Comment by yakcoin** [comment]
Re: new bitcoin talk forum thread: https://bitcointalk.org/index.php?topic=3435958

**Comment by yakcoin** [comment]
Dear ForDelta Team,

We will like to remind you that we are still waiting for us to be listed on
your exchange.

Please, kindly let us hear from you.

Regards,
YAK Coin

**Comment by Kryptoniq** [comment]
Your announcement thread and website doesn't tell what your project is all about. It only talks about airdrop /token distribution.
Care to provide more info?

**Comment by yakcoin** [comment]
Please check for more info.
https://www.yakcoin.net/what-is-the-use-of-yak-coin/

**Use of YAK Coin**
PAYMENT GATEWAY
We intend to integrate your YAK Coin for payment in day to day. You will receive your own customised VISA/ MasterCard number that you can use online for payment. In future, offline payments will also be supported. YAK Coin have plan to make WordPress payment plugin, Magento , Joomla and Opencart payment addons for YAK Coin payment method.


INTEGRATED EXCHANGE
Seamless and decentralised exchange would be setup that would enable 0% commission on BTC-ETH-YAK transactions and a minimal commission on other crypto.

 
DISCOUNT COUPON ISSUE
YAK COIN DISCOUNT COUPON CARDS will be issue with your desire YAK Coin. By default it will have 5 YAK Coin and you can add YAK Coin easily by sending unique number of discount card and it will be automatically deducted by converting current YAK Coin vale rate.

 
PARTNERSHIP INITIATION
YAK COIN will initiate to partnership with different companies, ecommerce platforms to implement and acceptance of YAK Coin payment method.
 

SMART CONTRACTS ENABLER
We will work with organisations or government to create and implement blockchain powered solutions such as digital identity, supply chain, etc. Invoice will be paid in YAK tokens

https://www.yakcoin.net/what-is-the-use-of-yak-coin/

**Comment by Kryptoniq** [comment]
Your token use case page is blatantly copied from http://ibtctoken.com/ (http://archive.is/Wg4RL).
https://www.yakcoin.net/what-is-the-use-of-yak-coin/ (http://archive.is/f5D4W).
We have a strong stance against plagiarism and will not be listing your token.
If you believe this decision was made in error kindly contest the decision on this issue by providing objective facts such as accomplished road maps, delivered products and steps you have taken to remedy the issue.
