### ISSUE TITLE
RAREToken listing

### ISSUE THREAD

**Issue by raretoken** [forkdelta/tokenbase#1002]
Contract address: 0x89eabf14687cf22d170be29a920a6bad38ded732

Issuer's official website: https://raretoken.io

Description: RareToken is a crypto currency token that is very rare in supply – just like gold is. The RareToken’s volume is limited to only 20,000 tokens, each having 2 decimal places only, like the real world currencies you are accustomed to, making it a very rare and scarce crypto currency. In fact it is much rarer than gold itself.

Official contract address confirmation: https://raretoken.io/terms.html

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://bitcointalk.org/index.php?topic=3169383.0
2. https://steemit.com/cryptocurrency/@s-h-d-p/raretoken-ico-the-mother-of-all-shitcoins-honest-unpaid-unbiased-review

**Comment by Kryptoniq** [comment]
This is an ICO-only project speculating on price projection.
Sorry, we can't list your token at this time.
