### ISSUE TITLE
RPCH Listing Request

### ISSUE THREAD

**Issue by RippleCash** [forkdelta/tokenbase#1005]
Contract address: 0x6F0a7aa19425752ff39d9f568C9d930eF30997eD

Issuer's official website: https://www.ripple-cash.technology

Description: Ripple Cash is designed to be the next generation payment system. This is a real-time, instant, secure and scalable payment system built on top of Ethereum network.Ripple Cash is an easy to use payment system that can be used by one and all, across industries. It would have its own platform with a simplistic UI to cater to the entire world.

Official contract address confirmation:  https://www.ripple-cash.technology/about-us

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1.  https://bitcointalk.org/index.php?topic=3077127.msg31723923#msg31723923 
2.  twitter.com/cash_ripple

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews. Please provide link to a third-party review of your token other than bitcointalk.org.

**Comment by RippleCash** [comment]
Dear Team,
 
Thanks for putting your reservations forward. We have an online upvote Campaign going for dontsoshi exchange. Additionally  senior pros of bitcoin talk have agreed to write reviews for us.
 
What will you accept as legit please let us know.
 
We have airdropped  to approx 1.6 k users and our community is growing. If you want reviews on the bitcoin org thread will be there. We can forgo our first month collections in case you so desire. But yes we have a strong community.
 
Kind regards,
Team Ripple Cash
 
 
 
 
--------- Original Message --------- Subject: Re: [forkdelta/tokenbase] RPCH Listing Request (#1005)

**Comment by RippleCash** [comment]
Can you please check now:

https://bitcointalk.org/index.php?topic=3077127.msg31723923#msg31723923
https://dontoshi.featureupvote.com/suggestions/9209/ripple-cash-listing
https://t.me/ripplecash
https://t.me/ripple_cash_community

**Comment by RippleCash** [comment]
Can you please check now:

https://bitcointalk.org/index.php?topic=3077127.msg31723923#msg31723923
https://twitter.com/cash_ripple
https://dontoshi.featureupvote.com/suggestions/9209/ripple-cash-listing
https://t.me/ripple_cash_community

**Comment by Kryptoniq** [comment]
Generic response doesn't help the situation.

**Comment by RippleCash** [comment]
Dear Sir,
 
We just updated the link of our twitter handle in the list of updated community threads that you had asked for as we had missed providing it to you earlier.
 
Thank you.
 
 
--------- Original Message --------- Subject: Re: [forkdelta/tokenbase] RPCH Listing Request (#1005)
