### ISSUE TITLE
listing request

### ISSUE THREAD

**Issue by Vestarin** [forkdelta/tokenbase#1007]
Hello         team,
My name is Jane, I’m from Vestarin team. 
This is a listing request, we want to have our VST token listed on your exchange.

Contract address: 0x552Ed8253f341fb770E8BAdff5A0E0Ee2fd57B43

Issuer's official website: https://www.vestarin.io

Description: We are crypto start-up, creating a marketplace for users to pay for goods and services with crypto.
We have just finished our ICO. Collected 5000 ETH. Around 16 million VST tokens in total. Over 20 000 token holders.
Our project is on development, however we already have an MVP on AppStore (https://itunes.apple.com/us/app/vestarin/id1335369168?l=ru&ls=1&mt=8) and Google Play (https://play.google.com/store/apps/details?id=com.ab.vestarinapp). Also we already started to invite partners in our network to sell their goods and services for crypto as soon as the platform will launch. 

Official contract address confirmation: https://etherscan.io/address/0x552ed8253f341fb770e8badff5a0e0ee2fd57b43

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://medium.com/@vestarin
https://bitcointalk.org/index.php?topic=2701796
https://github.com/cromlehg/Vestarin

Our social media:
https://www.youtube.com/channel/UC0M-TJdBhwOaWMQ1rdJGwzw/featured
https://twitter.com/vestarin
https://www.facebook.com/vestarin.io
https://t.me/Vestarin

Please let us know what other information should we provide and what are the conditions on listing?

Thank you in advance

Regards,
Jane Alieva
Business Development
business@vestarin.io

**Comment by Kryptoniq** [comment]
Please make your contract address available on your website for confirmation.
