### ISSUE TITLE
Add ScarceCoinToken (SCO)

### ISSUE THREAD

**Issue by cdoffx** [forkdelta/tokenbase#1008]
Contract address: 0x0df600c873da796c3ef6d6a0472772eb954d6986

Issuer's official website: scarcecoin.co

Description:  ScarceCoin project is a decentralized ERC20 video game project that aims to make it possible for gamers to earn playing games. The scarcecoin token is the project currency that can be earned by gamer.

Official contract address confirmation:  www.scarcecoin.co. The contract address is on the homepage content . 0x0df600c873da796c3ef6d6a0472772eb954d6986

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=2885433
2. https://steemit.com/ico/@adoghame/scarcecoin-igrovaya-platforma-obzor

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews. Please provide links to at least two third-party reviews of your project.

**Comment by cdoffx** [comment]
Hello Kryptoniq, welldone for the great job you are doing. We sure have some good reviews from followers on twitter and facebook and a lot of thirdparty reviews on blogs. Added here are some thirdpary review links
https://golos.io/ico/@themichaelmatch/scarce-coin-the-decentralized-erc20-video-game-cryptocurrency,
https://www.bountyportals.com/blogs/scarce-coin/,
http://bitcoinmux.com/detailpost?post_id=91665084,
https://iconow.net/scarcecoin-ico-bounty/

**Comment by cdoffx** [comment]
Hello Forkdelta. I provided the  thridparty links as requested. Please kindly update on the listing process. Thanks

**Comment by cdoffx** [comment]
There is constant response to other listing request but none to ScarceCoin. Thirdparty links has been provided yet no response. Kindly update on the listing process. Thanks

**Comment by freeatnet** [comment]
@Kryptoniq ping?

**Comment by freeatnet** [comment]
I don't see any original third-party research into the project. The project is also missing any mention of the team. Roadmap is _scarce_ (pardon the pun).

**Comment by cdoffx** [comment]
https://golos.io/ico/@themichaelmatch/scarce-coin-the-decentralized-erc20-video-game-cryptocurrency,
https://www.bountyportals.com/blogs/scarce-coin/,
http://bitcoinmux.com/detailpost?post_id=91665084,
https://iconow.net/scarcecoin-ico-bounty/ these are some thirdparty links

**Comment by cdoffx** [comment]
https://medium.com/@besteico.com/scarcecoin-sco-detail-review-besteico-691a5b948552

**Comment by cdoffx** [comment]
A thirdparty youtube review https://m.youtube.com/watch?v=ZdVW6uLXL_E although not in English

**Comment by cdoffx** [comment]
https://uk.advfn.com/cryptocurrency/icolist/SCO

**Comment by cdoffx** [comment]
Are those not sufficient?

**Comment by cdoffx** [comment]
About the team. Link to my linkedin profile is on the website content first paragraph every other person on the project prefer to remain behind the curtain

**Comment by Kryptoniq** [comment]
@cdoffx Please make your response in one comment next time.

**Comment by cdoffx** [comment]
@Kryptoniq Alright i will take note of that but i hope you get the information i passed.

**Comment by Kryptoniq** [comment]
Hi @Cdoffx, i have looked through the new links provided but can't find an actual third-party review of your project.
You ran an ICO and if you are willing to receive people's funds then your team should also be willing to reveal their identities.
In addition, the last token transfer was 48 days ago.

**Comment by cdoffx** [comment]
Maybe i don't understand what you meant by thirdparty review. Those links are reviews done by people not associated with the project team so i assume that is the third party review you are asking for. 
ICO is already done with and since tokens were bought directly into investors ether wallets hence why there isnt any recent token transfer. We are currently in the phase of distributing bounty rewards through Bounty0x. As for the team info, what is the good of a photoshopped non existence team displayed on the project website to one with a Linkedin profile link to a core member of the project on the project website even though it's one?
