### ISSUE TITLE
Staticoin listing request

### ISSUE THREAD

**Issue by genkifs** [forkdelta/tokenbase#1009]
Hi forkdelta.  

Our tokens are already listed in your system from when it was forked from etherdelta, but for completeness our token information is included below. 

**Contract address**:  statiCoin/riskCoin has 10 ERC20 tokens:-
USD_S | https://etherscan.io/address/0x1daaf3d62582639c6a7eabb467e2db9b56fafbbd
EUR_S | https://etherscan.io/address/0x1831887fbabf783910db128e60c41bfa016059d8
GBP_S | https://etherscan.io/address/0xa9666166d3c7fd15e874801f99e9ad5bfb70c5cf
CAD_S | https://etherscan.io/address/0x1735fc2b89b80d1ae33c35dd55eae7fa7642f336
JPY_S | https://etherscan.io/address/0x5f54c1512d036a0dd92744ee0a55ed183dde0484
USD_R | https://etherscan.io/address/0xd0800859d6f4bc0210b7807e770bc44a9ece7372
EUR_R | https://etherscan.io/address/0xe5a219d4db92a701e79b6e548803c8ce55138686
GBP_R | https://etherscan.io/address/0xdfe2bd1d3dcbb97804acf3ee85230e832c4a7b5d
CAD_R | https://etherscan.io/address/0xf4522eda455814d43b003bc1c38501b04d65cc4a
JPY_R | https://etherscan.io/address/0x22a3d74c363379189b6cc059d8fbd888e98df5ec

Issuer's official website:  [staticoin.com](http://www.staticoin.com)

**Description**: StatiCoin provides a stablecoin solution for traders looking for safe haven investment and merchants looking for a non-volatile digital currency.   Potential volatility is offset to RiskCoin which investors purchase for the potential to gain large rewards from this leveraged asset.

Official contract address confirmation: [Website FAQ section](http://staticoin.com/faq/) has the full details, the [dApp interface](http://staticoin.com/dapp/) doesn't contain direct address information

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1.   [Medium](https://medium.com/@peter.cornforth/staticoin-a-stable-digital-currency-d52477f378de)
2.   [reddit.com/r/ethdev](https://www.reddit.com/r/ethdev/comments/78xg15/this_is_the_code_behind_staticoin_a_new_stable/)

email:  genkifs@gmail.com

**Comment by Kryptoniq** [comment]
Can you elaborate more on what this means?
