### ISSUE TITLE
Please add VALID CASH Token in Forkdelta

### ISSUE THREAD

**Issue by ikhub** [forkdelta/tokenbase#101]
Contract Address: 0x4794b28f59533c52d99028e06878ae7d1e4d1802
Official Website: https://www.valid.cash/
Contract address confirmation: https://ethplorer.io/address/0x4794b28f59533c52d99028e06878ae7d1e4d1802
Token discussion: https://bitcointalk.org/index.php?topic=2483329

**Comment by JonathonDunford** [comment]
0x4794b28f59533c52d99028e06878ae7d1e4d1802

Verified.

Can you please add a short description of your token? 1-3 sentences..

@ikhub

**Comment by ikhub** [comment]
Here it is @JonathonDunford 
_Valid Cash is a cryptocurrency based on the Ethereum ERC20 protocol with a limited supply driven by community and peer to peer acceptance._

**Comment by JonathonDunford** [comment]
#72
