### ISSUE TITLE
Add DunkPay (DNK) 

### ISSUE THREAD

**Issue by Dayyoung** [forkdelta/tokenbase#1010]
Contract address: https://etherscan.io/address/0x7b606bc8ce7ba370b14bf5b43d1987cbaadc8d6d

Issuer's official website: https://www.dunkpay.com/token

Description: DunkPay is currently in service as a billing system with Cryptocurrency. DunkPay can currently make payments using BTC, BCH, ETH Cryptocurrency. If the user makes a payment through DunkPay, a 1% fee will be charged. We have decided to sell token the right to get this fee. DunkPay is a running service. No specific sales terms or agreement. Refunds are also available at any time.

Official contract address confirmation: Click "Buy Token" in https://www.dunkpay.com/token or the 'QR code' section.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://bitcointalk.org/index.php?topic=3415660.msg35718609#msg35718609
2. https://steemit.com/announcements/@bitcoinyo/dunkpay-com-javascript-library-for-cryptocurrency-payment-ico-for-rise

Greg,

**Comment by Dayyoung** [comment]
Test : https://etherscan.io/tx/0xed79c6a5ff1e5db9e9273373b423579595081457f964fe96a884b065f3fbabd1 
It worked perfectly.

**Comment by Dayyoung** [comment]
Hi, any news on listing?
One month was passed :)

**Comment by freeatnet** [comment]
@Dayyoung I understand this is your own project. Is that correct? Are there any third-party reviews of it?
