### ISSUE TITLE
New Token Listing: Fitrova (FRV)

### ISSUE THREAD

**Issue by BLUCOIN** [forkdelta/tokenbase#1011]
Contract address: 0x48df4e0296f908ceab0428a5182d19b31fc037d6

Issuer's official website: https://www.fitrova.com

--

Description: 

The Fitrova (FRV) cryptocurrency is designed to primarily serve the Health & Fitness industry by way of providing a clear and concise payment system together with harnessing blockchain technology to maintain accurate billing and membership details aswell as logging user flow and sharing individual client goals and feedback amongst internally linked health & fitness clubs that are part of the branded network.

Official contract address confirmation: 

Official site homepage under 'token details' section.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.coinspeaker.com/2018/03/06/fitrova-wants-revolutionize-health-fitness-industry-using-blockchain-tech/
2. https://u.wn.com/2018/03/06/Billionaire_Sam_Zell_says_Fitrova_is_the_Next_Big_Thing/
3. http://betacash.org/why-investors-have-pounced-on-fitrova-frv-tokens/
4. https://www.minds.com/blog/view/817118777793835008
5. https://www.solaristechtips.com/fitrova-investment/
6. https://medium.com/@TwilxSEO/fitrova-review-the-best-ico-for-2018-a6590ca075cf
7. https://icodrip.com/ico/fitrova/

**Comment by Kryptoniq** [comment]
https://coinmarketcap.com/currencies/fitrova

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x48df4e0296f908ceab0428a5182d19b31fc037d6, https://www.fitrova.com

**Comment by freeatnet** [comment]
Appears that some new information has come out, see https://steemit.com/cryptocurrency/@creatovert/fitrova-scam-investigation-the-saga-reached-it-s-final-confirmation.

Need to double-check. Maybe https://github.com/ico-check/ico-check can help.
