### ISSUE TITLE
Token Listing GlobalLotteryToken

### ISSUE THREAD

**Issue by GlobalLotteryToken** [forkdelta/tokenbase#1012]
Contract address: 0x9B545759939D497cf8A61635aC82067cEc329Ed6

Issuer's official website: https://www.ethereumlotterytoken.com/

Description: 
-Lottery Token to entry the lottery we provide
-No adds,no faucets,no referrals
-Purpose : Global Cryptocurrency lottery providing this in every language.

Official contract address confirmation:  0x28a0c8c9c72ac2146a813e6a5afc224285ce5f274351ff2b0bcc5a7b73f52a7a

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. -https://twitter.com/GLT_Team
2. -https://www.facebook.com/GlobalLotteryToken/
3.-https://bitcointalk.org/index.php?topic=3310769.msg34565173#msg34565173
4.-https://www.youtube.com/channel/UC2ONy3r1Y_5ezd2Q4BN0lUA
![c973f277-0315-4222-87e9-3d46a24ab5e8](https://user-images.githubusercontent.com/38164567/39393481-03fdba4e-4ac6-11e8-8e70-f9c94c1b2ac5.png)
![knipsel](https://user-images.githubusercontent.com/38164567/39393484-085c026c-4ac6-11e8-8de7-9f0117d279b9.JPG)
![35 35globallotterytoken](https://user-images.githubusercontent.com/38164567/39393485-13446d9a-4ac6-11e8-91c7-0c23cc491058.jpg)

**Comment by Kryptoniq** [comment]
#890 #931

**Comment by Kryptoniq** [comment]
Stop spamming.

**Comment by GlobalLotteryToken** [comment]
Ok sorry.
Do my Token still get list? 
Or not anymore now?

Kind regards.

GLT
