### ISSUE TITLE
CPL Token 

### ISSUE THREAD

**Issue by bearchik** [forkdelta/tokenbase#1013]
Dear ForkDelta Support, we want to add CPL token on your exchange after the end of the ICO (20 May). It is very important for us. We hope for your support.

Token address: 0x4b3c89e986b12f83eed896f02410429a7289526e
Crowdsale contract address: 0x36995d4e1ab6ee76aa55f16736fc85ec6e7b6c1d
Confirmation: http://puu.sh/AbXU5/5a0a686b1f.jpg

CoinPlace is the first P2P platform for trading ICO tokens and cryptocurrencies. The main goal of the service is to make the crypto and ICO market available to people all over the world. The purpose of the platform is to enable any person to purchase ICO tokens and cryptocurrencies for fiat money quickly and effortlessly. We have an MVP (https://coinplace.pro). Today users of the coinplace.pro platform have the possibility to buy and sell crypto assets with fiat in more than 150 countries all over the world.
The CoinPlace community has about 10 thousands people. We have more than 10k registered users on the ICO site and coinplace.pro (MVP site). More than 5k people participated in bounty and airdrop campaigns. Also we have more than 25k reads on bitcointalk.

Site: https://coinplace.info
WP: https://coinplace.info/files/WhitePaper_eng.pdf
Telegram channel: https://t.me/icocoinplace
Telegram chat: https://t.me/coinplace_eng
Twitter: https://twitter.com/CoinPlacePro
ANN thread: https://bitcointalk.org/index.php?topic=2302391
Bounty Campaign: https://bitcointalk.org/index.php?topic=2503658
AirDrop: https://bitcointalk.org/index.php?topic=2662841

Links to third-party reviews:
https://tokenmarket.net/blockchain/ethereum/assets/coinplace
https://blog.icoalert.com/coinplace-cpl-ico-alert-report-cc83bbb9e99f
https://www.cryptocompare.com/coins/cpl/overview

Contacts:
email: corp@coinplace.pro
telegram: @coinpIace

**Comment by Kryptoniq** [comment]
Please make your token address available on your website so that we can make our confirmations.

**Comment by bearchik** [comment]
Token address is available

**Comment by bearchik** [comment]
"Great! Thanks. So when CPL token will be listed?"
