### ISSUE TITLE
List Cryptobike Token Request

### ISSUE THREAD

**Issue by cryptobike** [forkdelta/tokenbase#1014]
Contract address: 0x833161e61337b6b6a4866cdffabaf20edf25ae77

Issuer's official website: https://www.cryptobike.co/

Description: Cryptobike is a decentralized, Blockchain powered bike sharing platform. The service enables users to rent out bikes on per hour basis. Unlike other bike rental facilities, Cryptobike’s decentralized nature makes usage and renting of bike more secure, fast and economical.

Official contract address confirmation: 

Youtube: https://www.youtube.com/channel/UCQpeHRpabfpaLAf6jWmoD8w
Instagram: https://www.instagram.com/cryptobike_cbs/
Reddit: https://www.reddit.com/user/cryptobike
Facebook: https://www.facebook.com/CryptoBikepage/
BitcoinTalk: https://bitcointalk.org/index.php?topic=3293613.0
Github: https://github.com/cryptobike

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. http://www.abnewswire.com/pressreleases/cryptobike-a-new-decentralized-platform-that-allows-the-users-to-rent-bikes-on-per-hour-basis_204932.html
2. http://www.digitaljournal.com/pr/3728533
3. https://icobench.com/ico/cryptobike

**Comment by Kryptoniq** [comment]
There are only 9 token holders ATM. Please make an initial token distribution .

**Comment by Kryptoniq** [comment]
Team members are stock images.
Sorry, we can't list your token. 
If you believe this decision was made in error, you can contest it on this issue by providing verifiable identity of all your team members.
https://www.cryptobike.co/team.html (http://archive.is/Kimag)
