### ISSUE TITLE
Shopiblock(SHB) token listing request

### ISSUE THREAD

**Issue by SHBrock** [forkdelta/tokenbase#1015]
Contract address: 0x9e2b71e87d9304c4773674584eb9d0c838643568

Issuer's official website: https://www.shopiblock.io/

Description:  The first decentralized shop software as a service on the cryptocurrency market. Use Shopiblock to create the ultimate decentralized business in your niche.

Official contract address confirmation: 
1) When you join official shopiblock ico telegram: https://t.me/shopiblock2018 and search as 'contract address',
2) You can find the address from admin just like below.
![image](https://user-images.githubusercontent.com/38833185/39405808-643462ba-4be7-11e8-9fbb-7db014459918.png)

Links to third-party reviews or discussion of the token, the project/product, or the token issuer: 

1. https://www.trackico.io/ico/shopiblock/
2. https://centralairdrop.com/shopiblock-move-your-whole-shop-to-the-blockchain-create-your-own-token

**Comment by Kryptoniq** [comment]
I can't proceed. Website is down ATM.
