### ISSUE TITLE
Token listing Request: NovaChain connected to cryptocurrency

### ISSUE THREAD

**Issue by Novachain** [forkdelta/tokenbase#1017]
Contract address:
0x1A231dF765d0F7674F55d20D022BCb38DA794501

Issuer's official website:
https://novachain.cc

Description: 

We are an ambitious team of highly skilled professionals. Our goal is promotion and popularization by strategic means to grow the Bitcoin and Crypto platform and community, which makes us a new generation of crypto-enthusiasts.
https://novachain.cc/wp_novalend.pdf

Official contract address confirmation: 
https://novachain.cc/#token-sale

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://forum.icoreview.site/t/novalend-ico-review-discussion/11548
2. https://www.youtube.com/watch?v=zUAneQOtgGk&t
3. https://t.me/novachain_community
4. https://twitter.com/novachainico?lang=de

we are currently trading under: 
https://forkdelta.github.io/#!/trade/0x1a231df765d0f7674f55d20d022bcb38da794501-ETH

**Comment by Kryptoniq** [comment]
Forum post link provided talks about "NovaLend" and "Lending platform" and your description says a different thing here.
Provide link to your bitcointalk announcement thread.
BTW, as stated on your website, Target price for for April is $10, July is $30 and October is $80. How do you plan to achieve this? I find this as a template used by various scam ICOs to lure unsuspecting individuals to invest in their scams.
Please provide details of goals and road map accomplished so far.
