### ISSUE TITLE
bitron token listing

### ISSUE THREAD

**Issue by horliquegold** [forkdelta/tokenbase#1018]
Contract address:

Issuer's official website: https://www.bitron.io

Description: BITRON IS AN OPEN SOURCE ETHEREUM BASED, PEER-TO-PEER CRYPTOCURRENCY EXCHANGE PLATFORM, CAREFULLY DEVELOPED BY INDUSTRY EXPERTS ALL BASED IN ESTONIA AND SWITZERLAND. BITRON IS A GLOBAL PAYMENT NETWORK THAT IS FULLY DECENTRALIZED WITHOUT ANY CENTRAL AUTHORITIES WHICH ENABLES PEOPLE TO STORE AND INVEST THEIR WEALTH IN A DIGITAL CURRENCY. BITRON COIN TOKENS ARE ERC-20 BASED CRYPTOCURRENCY THAT WILL BE USED AS ONE OF THE CRYPTOCURRENCY ON THE BITRON CRYPTOCURRENCY EXCHANGE PLATFORM.

Official contract address confirmation: the official smart contract address is: 
https://etherscan.io/address/0xa550a7980f856d5f9dd0a8c405e8736223f0b44a#code

here is the smart contract address: 
0xa550A7980f856D5F9Dd0a8c405e8736223f0b44a

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=2978698.msg30607608#msg30607608
2. https://web.facebook.com/BitronOfficial/

**Comment by horliquegold** [comment]
yes The Bitron smart contract address is correct..

**Comment by horliquegold** [comment]
yes The Bitron smart contract address is correct..

**Comment by Kryptoniq** [comment]
@horliquegold  Verify the contract's source code on etherscan.io

**Comment by horliquegold** [comment]
hi, here is our verified Bitron coin token:
https://etherscan.io/address/0xa550a7980f856d5f9dd0a8c405e8736223f0b44a#code
decimal : 9
symbol: BTO

**Comment by horliquegold** [comment]
hi, here is our verified Bitron coin token: https://etherscan.io/address/
0xa550a7980f856d5f9dd0a8c405e8736223f0b44a#code
decimal : 9
symbol: BTO
website: https://bitron.io
whitepaper: https://bitron.io/bitron-whitepaper.pdf
facebook: https://web.facebook.com/Bitron-188403898424492/
Smart contract address: 0xa550A7980f856D5F9Dd0a8c405e8736223f0b44a
Total supply: 50,000,000
