### ISSUE TITLE
Request for Listing of Lotus Token in FORKDELTA

### ISSUE THREAD

**Issue by zzlnc4** [forkdelta/tokenbase#102]
DEAR ForkDelta Admins/Team, 

GOOD DAY!!!

I would like to request for listing of Lotus Token in your ForkDelta DEX platform, details below:

Contract address:  
0xE2E5d0E1422e927AbaB19aD2067f802ad07Fb364 

Official website:     
https://lotus.sh

A link to an official page confirming the contract address:
https://etherscan.io/address/0xE2E5d0E1422e927AbaB19aD2067f802ad07Fb364#code

A link to a third-party review or discussion of the token, like an established ICO review blog:
https://icoguru.io/news/lotus-project-review/
https://bitcointalk.org/index.php?topic=2512733.0
https://bitcointalk.org/index.php?topic=2554825.220
https://medium.com/@ademolaof/lotus-token-the-future-of-global-travelers-bfc9fe826925
https://icobench.com/ico/lotus

Coin Ticker/Symbol:
LTO

Lotus Token Telegram:
https://www.t.me/lotustokeninc

Lotus Token Twitter:
https://twitter.com/lotustokenico?lang=en

Kindly let me know if you need more information.

Thanks so much for the help!

Regards,
Michael De Guzman

**Comment by zzlnc4** [comment]
Kindly let me know if you need further information :)

**Comment by JonathonDunford** [comment]
@zzlnc4 

Address verified: 0xe2e5d0e1422e927abab19ad2067f802ad07fb364

Can you please provide a short decsription of your token? 1-3 sentences.

And consider changing the token sale link to ForkDelta once we have you listed 😋

**Comment by zzlnc4** [comment]
Sure sir!  Here is the Lotus token description:

Lotus Token aims to decentralize the travel marketplace using blockchain technology to lower travel-related costs by eliminating costly overhead transaction fees of traditional booking systems.  We have recently signed a partnership with ORIGINPROTOCOL to improve and power-up the shared economy where decentralized systems act like a one-stop shop for common people to enjoy the freedom of enjoying reduced costs of decentralized services like travel, house/hotel bookings, etc.

**Comment by zzlnc4** [comment]
yup we will also update our token sale link to the Forkdelta shortcut ticker for Lotus :) once we are listed, cheers!!!

**Comment by zzlnc4** [comment]
+1

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
