### ISSUE TITLE
Listing VRS(Veros DH)

### ISSUE THREAD

**Issue by criptoredfox** [forkdelta/tokenbase#1020]
VEROS DIGITAL HEARTS - a fundraising unique platform for noncommercial organizations, companies, events and commercial projects aimed at improving of life and the environment using blockchain technologies.

Coin Name / Token Name: Veros
Ticker : VRS
Algo : Ethereum
Total Coins supply: 85 000 000
Max Coins supply: 100 000 000
Coin Type / Token Type: ERC20
Website : https://vedh.io  
Bitcointalk: https://bitcointalk.org/index.php?topic=3395510.0
Explorer : https://etherscan.io/token/0x92e78dae1315067a8819efd6dca432de9dcde2e9 
Сoinmarketcap: https://coinmarketcap.com/currencies/veros/
Source Link (github) : https://github.com/VerosDH 
Email : team@vedh.io 
Telegram :  https://t.me/veros_coin 
twitter: https://twitter.com/Veros_currency
facebook: https://facebook.com/verosDH

**Comment by Kryptoniq** [comment]
Please provide links to at least 2 third party reviews of Veros.

**Comment by criptoredfox** [comment]
What kind of reviews? Bitcointalk or magazine articles?



От: Krypton
Отправлено: 22 мая 2018 г. в 19:42
Кому: forkdelta/tokenbase
Копия: Nik Magnus; Author
Тема: Re: [forkdelta/tokenbase] Listing VRS(Veros DH) (#1020)

Please provide links to at least 2 third party reviews of Veros.

**Comment by freeatnet** [comment]
@criptoredfox We're looking for the project to have independent 3rd-party reviews, something like what hacked.com and cryptobriefing.com do.

**Comment by criptoredfox** [comment]
https://etherdelta.com/#VRS-ETH

**Comment by criptoredfox** [comment]
![image](https://user-images.githubusercontent.com/36786894/47152462-71007800-d2e5-11e8-8005-0f0e3eab6d67.png)

What token should be updated?

updated address

What about the token should be updated?

Ticker : VRS | Algo : Ethereum
Coin Type / Token Type: ERC20
Website : https://vedh.io
Coinmarketcap: https://coinmarketcap.com/currencies/veros/#markets
Explorer : https://etherscan.io/token/0x92e78dae1315067a8819efd6dca432de9dcde2e9
Source Link (github) : https://github.com/VerosDH
Email : team@vedh.io
Telegram : https://t.me/veros_coin
twitter: https://twitter.com/Veros_currency
facebook: https://facebook.com/verosDH
bitcointalk: https://bitcointalk.org/index.php?topic=3395510.msg46639340#msg46639340

**Comment by criptoredfox** [comment]
On what day can we announce the listing?

**Comment by criptoredfox** [comment]
When will we be added? We have a listing soon on IDAX. We are with you 1 month can not add support token?!!
