### ISSUE TITLE
KEA Coin listing Request

### ISSUE THREAD

**Issue by KEACoin** [forkdelta/tokenbase#1021]
KEA Coin (KEA) is the is a new Crypto Coin in the Cryptocurrency World. KEA Coin is released with the intention to use in E-Commerce and Digital Marketing with Reward System. The total supply of 1 billon KEA Coin generated with initial 3900 KEA Coin Airdrop through Easy, Trusted and Smart Contract based on deeply research.

WHAT IS KEA COIN?
For E-Commerce Ecosystem and Digital Marketing with Reward system.

KEA Coin is based on Ethereum platform for the improvement the market in E-Commerce and Digital Marketing that powering the new Ethereum blockchain through this crypto technology.

While existing solutions offer to solve just one problem at a time, our dedicated team is up to build a secure, useful, & easy-to-use product based on Ethereum blockchain. It will include easy cryptocurrency payments integration for different platform like KEA Payment extension and addon for Magneto, Shopify, Zen Cart, PrestaShop. WooCommerce. OpenCart, Symphony Commerce, BigCommerce platforms etc. It will help to do payment process through KEA Coin like normal USD payment.

Why KEA Coin?
KEA coin based on Ethereum Blockchain with smart contract. There are many plugin, extension will be release for easy cryptocurrency payments integration in different platform.

It will also enhanced in the Digital Marketing and web technology as well.

And Reward system you can earn for using  KEA Coin in E-Commerce Ecosystem and Digital Marketing.

Our aims to partnership with all companies, employees, and business assets to make  one blockchain ecosystem, which will make business truly efficient, transparent, and reliable.

Name: KEA Coin
Symbol: KEA
Standard: ERC20 standard Ethereum Token 
Platform: Ethereum
Decimals: 8
Contract Address: 0x390D6673c1FA9DBb8000dB1AE89252b7d531Ab75

Official website: https://www.keacoin.org/

Official contract address confirmation: https://www.keacoin.org/

Official Email: info@keacoin.org

Links:

BitcoinTalk Forum: https://bitcointalk.org/index.php?topic=3342572.msg34972856
Twitter: https://twitter.com/KEACoin
 Facebook: https://www.facebook.com/KEA-Coin-195092284432835/
Reddit: https://www.reddit.com/user/KEACoin/
Discord: https://discord.gg/c7GbJcB
Github: https://github.com/KEACoin/keacoin
https://steemit.com/airdrops/@qmm/airdrop-1-self-airdrop-600-kea-coin-3300-kea-coin-usd9-usd
https://medium.com/@KEA.Coin/kea-coin-kea-is-the-is-a-new-crypto-coin-in-the-cryptocurrency-world-3e91cff56ba7
https://keacoin.wordpress.com/
https://steemit.com/cryptocurrency/@qmm/kea-coin-the-power-of-kea-coin-in-the-crypto-world

**Comment by Kryptoniq** [comment]
Website contains only a Logo. 
Provide your contract address, description and link to a third-party review of your project.

**Comment by KEACoin** [comment]
Information Updated.

**Comment by KEACoin** [comment]
Hi,
Please check updated info and links. Thanks

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews. Please provide link to an alternate third party review of your project.

**Comment by KEACoin** [comment]
Please check other links
https://medium.com/@KEA.Coin
https://medium.com/@KEA.Coin/kea-coin-kea-is-the-is-a-new-crypto-coin-in-the-cryptocurrency-world-3e91cff56ba7
https://www.reddit.com/user/KEACoin/
https://cryptocurrencytalk.com/topic/104160-annlimited-saleairdrop-kea-coin-the-power-of-kea-coin-in-the-crypto-world/
https://twitter.com/KEACoin
https://allcryptotalk.com/index.php?/topic/8853-annlimited-saleairdrop-kea-coin-the-power-of-kea-coin-in-the-crypto-world/&tab=comments#comment-41837
https://steemit.com/cryptocurrency/@qmm/kea-coin-the-power-of-kea-coin-in-the-crypto-world

**Comment by KEACoin** [comment]
We reached 14995 Holders addresses

https://etherscan.io/token/0x390d6673c1fa9dbb8000db1ae89252b7d531ab75
<img width="1002" alt="screen shot 2018-05-25 at 7 46 45 pm" src="https://user-images.githubusercontent.com/38321104/40538213-6651d312-6054-11e8-8e6b-553e11e89514.png">

**Comment by KEACoin** [comment]
Any update Please.

**Comment by Kryptoniq** [comment]
@KEACOIN you are the same person as @YAKcoin.
Correct me if I'm wrong.

**Comment by KEACoin** [comment]
no. KEACoin is different from them.

**Comment by Kryptoniq** [comment]
Can you explain the attached  screenshots? 
You commented with the @YAKcoin account and then you deleted the comment and switched accounts. 
![img_20180529_151056_813](https://user-images.githubusercontent.com/16838612/40664320-998c8f0a-6352-11e8-8233-201c2634f967.JPG)
![img_20180529_151015_740](https://user-images.githubusercontent.com/16838612/40664322-9a2b0b62-6352-11e8-9010-434ae4d5f165.JPG)

**Comment by KEACoin** [comment]
We reached 21,210 holders now.
https://etherscan.io/token/0x390d6673c1fa9dbb8000db1ae89252b7d531ab75

Is there any update on listing of KEA Coin. White paper is on development process.

<img width="1197" alt="screen shot 2018-06-02 at 3 29 00 pm" src="https://user-images.githubusercontent.com/38321104/40871163-cbbd422e-6679-11e8-8cca-196f1edf361e.png">

**Comment by KEACoin** [comment]
Hello,
KEA Coin White Paper V.1.0 2018 Released. Please check it.
https://bitcointalk.org/index.php?topic=3342572.new#new
https://keacoin.files.wordpress.com/2018/06/kea-coin-whitepaper-2018.pdf

Is there any update on listing of KEA Coin?

Please

**Comment by KEACoin** [comment]
Just an update,
Telegram: https://t.me/KEACoin
Telegram Channel: https://t.me/KEACoinChannel
Skype: keacoin

Thanks

**Comment by KEACoin** [comment]
Updates. 
Listed in https://coincodex.com/crypto/kea-coin/

**Comment by Kryptoniq** [comment]
@KEACOIN, we do not receive payment for listing. Listing is **Free**.
You have to be patient until I get to your issue once again.

**Comment by KEACoin** [comment]
Thank you so much Kryptoniq .
we got a email for paid forkdelta listing. Just confusing. Is this forkdelta official email noreplaylist@forkdelta.github.io

**Comment by KEACoin** [comment]
Just an update, KEA Coin listed in https://etherc.io/#KEA-ETH

**Comment by listingfork** [comment]
please check
6579054##

**Comment by KEACoin** [comment]
Just an update, KEA Coin listed in another exchange too. Please check.
https://www.enclaves.io/trade/KEA

**Comment by Kryptoniq** [comment]
Again, we do not **charge** for listing. Listing is **free**.
We'll never mail you first.
noreplaylist@forkdelta.github.io is not our email. Beware of scammers.

**Comment by KEACoin** [comment]
Just an update, KEA Coin listed in https://cryptocoincharts.info/ico/keacoin

**Comment by Kryptoniq** [comment]
@KEACOIN, you are beginning to make this issue  spammy. 
We don't care about where your project gets listed, all we do is make our own due diligence.

**Comment by KEACoin** [comment]
ok. Any update.

**Comment by KEACoin** [comment]
Any update please.

**Comment by KEACoin** [comment]
Any update please.
