### ISSUE TITLE
Bronx (BRN) listing request

### ISSUE THREAD

**Issue by adetos** [forkdelta/tokenbase#1022]
Contract address: 0x1822f963bc5cd6683737e6befb1d0d695112bdcf
--

Issuer's official website: www.bronxbit.com

Description: 
Bronx is a decentralized platform created with the purpose of disrupting the real estate industry. Bronx revolutionises property holding and transaction in a tokenized form. Bronx provides direct public access to the most current and comprehensive listing of properties for sale using Bronx tokens.

By using blockchain based tokens, we are directly connecting investors with real estate market place. we make it easy to invest in Real Estate.

Official contract address confirmation: www.bronxbit.com
The contract address is at the bottom of the official website 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
-->
1. https://web.facebook.com/Bronxbit-181443542497199/
2. https://medium.com/@bronxbit/bronx-revolutionizing-real-estate-industry-1edb0131da2c

**Comment by Kryptoniq** [comment]
Fake team members.
Your CTO Louis Lee is actually Alexis Santos.
Images of others probably obfuscated to prevent image search. 
Bronxbit.com 
Website Archive: http://archive.li/ICFw4

We can't list your token.
