### ISSUE TITLE
BoatPilot NAVI listing

### ISSUE THREAD

**Issue by ivan-boatpilot** [forkdelta/tokenbase#1024]
Contract address: 0xc15A399c4eA7815fE36857C9E290EE452A5D6B21

Issuer's official website: https://boatpilot.io

Description: BoatPilot is a vendor of hardware navigation solution and a developer of the platform that combines navigation, booking, and advertising services for the private and charter yachting sectors. The NAVI token is used in the project’s eco-system.

Official contract address confirmation: https://boatpilot.io/#tge - under the token distribution chart

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://icorating.com/ico/boatpilot/ 
2. https://icobench.com/ico/boatpilot

**Comment by Kryptoniq** [comment]
Your token doesn't look fine on etherscan.io and your contract source code isn't verified. Please attend to this promptly. 
![img_20180504_192341_326](https://user-images.githubusercontent.com/16838612/39645624-e65795cc-4fd0-11e8-901a-5408420a191d.jpg)
