### ISSUE TITLE
Listing for KRL token

### ISSUE THREAD

**Issue by CryptenseDev** [forkdelta/tokenbase#1025]
Contract address: 0x464eBE77c293E473B48cFe96dDCf88fcF7bFDAC0

Issuer's official website: https://kryll.io

Description: 

Kryll.io is the first intuitive flow-based Crypto trading strategy definition platform.
The KRL tokens will be used to fuel the strategies execution.
The KRLs will be used as an internal currency to rent other people's strategies.

Official contract address confirmation: 

https://kryll.io bottom left of the site
https://github.com/Cryptense/KryllToken (Cryptense is the mother company of Kryll.io)

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://icoholder.com/en/kryll-io-17818
2. https://www.trackico.io/ico/kryll/
3. https://cointelegraph.com/news/bitcoin-growing-while-you-sleep-a-new-platform-introduces-automated-crypto-trading

Social links :

Twitter | https://twitter.com/kryll_io
Telegram | https://t.me/kryll_io
Medium | https://medium.com/@kryll_io
Facebook | https://www.facebook.com/kryll.io
Youtube | https://www.youtube.com/channel/UCET6DYvfwpIvmeY2x_VdHMQ
LinkedIn | https://www.linkedin.com/company/cryptense/
Reddit | https://www.reddit.com/r/Kryll_io/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x464ebe77c293e473b48cfe96ddcf88fcf7bfdac0,  https://kryll.io
