### ISSUE TITLE
Add Digital Fantasy Sports (DFS)

### ISSUE THREAD

**Issue by jpreimes** [forkdelta/tokenbase#1026]
Contract address: https://etherscan.io/token/0x45eD02e374Aef2e4b34c04e86AD9D45891d10751

Issuer's official website: http://www.DFStoken.com

Description: 
Digital Fantasy Sports is bringing a premium decentralized fantasy sports cryptocurrency arcade to the world.  Currently the crypto market is non-existent for dedicated fantasy sports platforms.  DFS is an elevated and new level of gaming to the fantasy sports industry. We are offering 10 different athletic sports/ arcade games to captivate audiences around the globe.  DFS has created an ERC20 token that allows for transparency in the fantasy sports industry.  We have a strong following of individuals who are looking to play and trade our token.   Our community is growing and our international reach is stronger than ever.  

We are shaking things up by offering new ways to play the fantasy games players love.  A majority of current fantasy players aren’t even aware of the crypto industry.  We are catering to a new breed of individuals.  We don’t plan on offering the same gameplay as FanDuel, DraftKings, Yahoo or the others- but a gameplay style thats enjoyable and challenging at the same time.  Check out our vision on MLB.  You play as a GM, and your fantasy score is based on your batting order.  I’m not calling it complex, but it fits perfectly within the crypto industry.  

Batting Order Baseball: http://www.battingorderbaseball.com

DFS is the first of its kind in the crypto world.  We' have made it extremely simple to sign up for our Digital Fantasy Sports arcade. One sign up is all you need- Just register for our online DFS WALLET www.dfswallet.com.  When you sign up for a DFS Wallet you are gaining access to all the #DigitalFantasySports Network has to offer. 

DFS Wallet = ERC20 Wallet Address & Private Key,DFS Arcade Username/PIN for current and future games, META MASK functionality to send tokens to exchanges, live TWITCH feed daily featuring game broadcast, and DISCORD chat built in for a universal DFS chatroom. www.dfswallet.com

Official contract address confirmation:  
https://bitcointalk.org/index.php?topic=2223626.0
Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://twitter.com/dfstoken
2. https://old.reddit.com/r/dfstoken/

**Comment by Kryptoniq** [comment]
Please make your contract address available on your website or social media handle.

**Comment by Kryptoniq** [comment]
Please make your contract address available on your website or social media handle.

**Comment by Kryptoniq** [comment]
Please make your contract address available on your website or social media handle.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by jpreimes** [comment]
Please find two links attached:

Article about the founder and fantasy sports: https://www.newyorker.com/magazine/2015/04/13/dream-teams

Team interview: https://www.youtube.com/watch?v=YXDuYHJcdNk

Thank you your replying. 

Please let us know if these work. 

Thanks,
Jeremy & the DFS Team

**Comment by SamuelLive** [comment]
Has DFS been added to the platform?

Can't see in the dropdown. 

If you need more info. Someone has curated a thread about the project here.
https://twitter.com/CoinChimps/status/1151023540293947394

Thanks
