### ISSUE TITLE
Add token: ELET (Elementeum)

### ISSUE THREAD

**Issue by Elementeum** [forkdelta/tokenbase#1027]
1. The contract address for ELET (Elementeum): 
0x719502D2755FcF269da27d9f07c96d68A2f3572a
Created by proxy to
0x6c37bf4f042712c978a73e3fd56d1f5738dd7c43
2. A link to the token issuer's official website. https://www.etherlegends.io
3. 1-3 sentences for the token's description: The Token, Elementeum (ELET) is the in game token for the Ethereum based collectible trading card game called Ether Legends. The currency lets players buy booster packs, digital character cards, and stake in tournament game play. Holders of Elementeum have the added benefit of in game crafted dividends. Additionally, Ether Legends offer physical trading cards that can be redeemed to the Blockchain and turned into unique digital assets (721 non-fungible). 
4. A link to an official page confirming the above contract address: https://etherlegends.io/faq 
5. Links to third-party reviews or discussion:

https://icomarks.com/ico/ether-legends

https://www.techbullion.com/top-10-features-ether-legends/

https://tokentops.com/ico/ether-legends/

https://www.coinannouncer.com/how-elet-token-will-benefit-gamers/

https://bitcoinexchangeguide.com/ether-legends/

https://icobench.com/ico/ether-legends

https://blockchaingamer.net/snax_item/3040/

**Comment by Kryptoniq** [comment]
Please verify your contract source code on etherscan.io. 
https://etherscan.io/address/0x6c37bf4f042712c978a73e3fd56d1f5738dd7c43#code

**Comment by Elementeum** [comment]
I can do that as well... can you just go to put github? 

https://github.com/etherlegends/elementeum-token-sale/blob/master/contracts/ElementeumToken.sol

**Comment by Kryptoniq** [comment]
Sorry, github doesn't qualify for contract code verification.

**Comment by Elementeum** [comment]
Okay. Will have my developer go do that- might take a day based on his availability, Bear with me.
Thanks
Curran

**Comment by Elementeum** [comment]
On Etherscan guidelines they do not currently support the following:

“4. We do not support contract verification for contracts created by another contract”

Our Elementeum contract was deployed through a different contract proxy based on our crowd sale parameters in which there is no way to post the source because it is unsupported by etherscan.

We could verify the token sale contract itself because it was not don’t by another proxy. Please advise an alternate way we can support this submission.

**Comment by Elementeum** [comment]
Kryptonic - is there an alternate method for source code that we can do based on the comment above?

**Comment by Elementeum** [comment]
https://etherscan.io/address/0x719502d2755fcf269da27d9f07c96d68a2f3572a#code

Here is the proxy to create the token and should be all set.

**Comment by Kryptoniq** [comment]
`0x719502d2755fcf269da27d9f07c96d68a2f3572a` is not a token address.

**Comment by Elementeum** [comment]
Did you happen to read the previous post? 

Etherscan DOES NOT support contract verifications created by another contract. As I mentioned 16 days ago, etherscan does not support the verification since our contract was designed and created by proxy. So we took the sale contract and verified it because it was NOT created by proxy. There is no way to do the etherscan verification on our contract address. What other means of verification do you recommend? Thanks!

**Comment by Elementeum** [comment]
Hey guys, some and targeted response would be appreciated... as well, read the issue at hand. You have to have an alternative method for verification.... please read the previous post... there is a limitation with etherscan...

**Comment by Kryptoniq** [comment]
Please be aware that for your project to stand a chance of getting listed, you must verify your contract address on etherscan.

**Comment by Elementeum** [comment]
etherscan does not support contracts done by proxy. There is no way for us to do that. It is a current limitation of etherscan.

**Comment by Elementeum** [comment]
Can we get this on there for trading? Altilly didn’t seem to have issues and read my posts and worked this out. It is out of my control when etherscan other supports select features... Thx 

https://www.altilly.com/market/ELET_ETH
