### ISSUE TITLE
Wemerge MRG

### ISSUE THREAD

**Issue by WemergeMRG** [forkdelta/tokenbase#1028]
Contract address: - 0xcbee6459728019cb1f2bb971dde2ee3271bc7617

Issuer's official website: http://www.wemerge.io/

Description: - 
- Our token acts primarily as a Right's utility, providing token holders the right to free airdrops from incubated projects based on the number of MRG tokens held. It also acts as a payment token for incubated services provided by Wemerge to projects and for education and activities provided to the community. 

Official contract address confirmation:  
- We are able to generate contract address from etherscan. There is no other link. 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=3383949.new#new

**Comment by Kryptoniq** [comment]
Contract address is not verified on etherscan.
No third-party reviews.
