### ISSUE TITLE
Listing request Obirum - OBR

### ISSUE THREAD

**Issue by obirumadmin** [forkdelta/tokenbase#1029]
Contract address: 0x69a605d3f74bb709a7e9f6f7b5e3337445fc93cc

Issuer's official website: https://ico.obirum.com/

Description:  Obirum is a browser that integrates the advantages of blockchain technology with the desire to become a most powerful and secure browser.

Official contract address confirmation:  
https://ddex.io/trade/OBR-ETH
https://ico.obirum.com/
https://steemit.com/obirum/@obirum/how-to-add-and-check-my-obr-token-on-myetherwallet

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. Telegram: https://t.me/obirum
2. Bitcointalk: https://bitcointalk.org/index.php?topic=2956329
3. icomarks: https://icomarks.com/ico/obirum
4. Email: hello@obirum.com
5. Whitepaper: https://ico.obirum.com/files/OBR-white-paper.pdf
6. DDEX exchange: https://ddex.io/trade/OBR-ETH

**Comment by Kryptoniq** [comment]
Project ended as a scam.
https://bitcointalk.org/index.php?topic=2956329.msg37907287#msg37907287
