### ISSUE TITLE
XCM X Coin Machine Listing

### ISSUE THREAD

**Issue by isysd** [forkdelta/tokenbase#103]
---
addr: '0xb9f0b7e1d518f0e213441a804fed84c2858c5d88'
decimals: 3
description: XCM are gift certificates redeemable for Blockchain integrated devices manufactured by TigoCTM.
name: X Coin Machines
symbol: XCM
links:
- Email: info@tigoctm.com
- Twitter: https://twitter.com/tigoctm
- Website: https://tigoctm.com/
- Whitepaper: https://tigoctm.com/static/docs/TigoCTM-Whitepaper.pdf

**Comment by JonathonDunford** [comment]
Closing this as it is here: #104
