### ISSUE TITLE
Modorr Token Listing

### ISSUE THREAD

**Issue by Modorr** [forkdelta/tokenbase#1030]
Contract address: 0xc6e4eeb03db05cf4d00acad04cf08b916186eaa5

Issuer's official website: https://modorr.io

Description:  Modorr goal is to create a decentralized blockchain gaming platform that will allow game developers to create simple arcade style games, Players and Developers are rewarded for their time and effort  in MDR token.

Official contract address confirmation: https://www.modorr.io/faq/#address

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=2794711.new#new
2. https://www.youtube.com/watch?v=unkoEcMV_CU
3. https://www.youtube.com/watch?v=7-sEpSKCN_o&t=3s
4. https://www.youtube.com/watch?v=2XKfrvrDtjU
5. https://coincodex.com/ico/modorr/
6. https://bitcoinexchangeguide.com/modorr-ico-mdr-token/
7. https://www.facebook.com/pg/modorr/reviews/
8. https://foundico.com/ico/modorr.html

**Comment by inama01** [comment]
Great project
https://member.modorr.io/ref/inama01/

**Comment by Kryptoniq** [comment]
Project director David Saville is actually Samuel Hinz.
Photo of Alan Johnson, your "Game developer" is a stock photo for templates.
We will not be listing your token. 
If you belive this decision was made in error, you can contest it on this issue by providing verifiable identity of all your team members.
Website: https://modorr.io
Archive: http://archive.is/YttPn

**Comment by Modorr** [comment]
Modorr project is community focused project and members are the one that run the project and make up the project team members are selected by completing an online form,  We are aware about the YouTube by David Saville in the name Samuel Hinze and asked him already and he claimed that is the new name. We will asked both of David and Alan Johnson to provide original picture otherwise they will be removed from the project

**Comment by Kryptoniq** [comment]
For Modorr to stand a chance of getting listed on forkdelta, you'll have to provide verifiable identity of "ALL" your team members as listed on your website.

**Comment by Modorr** [comment]
Please kindly provide us an email we can send this to as we can not share this with plublic github

**Comment by Modorr** [comment]
Please in the main time while we resolve all the listing issues can members trade with this link https://forkdelta.github.io/#!/trade/0xc6e4eeb03db05cf4d00acad04cf08b916186eaa5-ETH
