### ISSUE TITLE
Request to add EmClassic (EML)

### ISSUE THREAD

**Issue by LoopNewtorkInc** [forkdelta/tokenbase#1032]
Contract address: 0x754Cfea697ebDF4902f4597c69200eF469d7d466

Issuer's official website: https://emcoinclassic.com

Description: EmClassic was created as a local currency for an online e-commerce company EmMall to get into Blockchain industry and create opportunities in the Cryptocurrency eco space.
With the use of EmClassic users can make quick and secured transactions and pay for their purchases online cutting off the middle man. 
With the use of Ethereum Smart contract trust in purchase is 100% and that increase the reliablity in the use of e-commerce. 
EmClassic can also be exchanged to other currencies as well and can be used as a peer to peer payment system world wide.  

Official contract address confirmation: Contract address confirmation can be found on the homepage of our website https://emcoinclassic.com

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
Twitter: https://twitter.com/EmCoins Telegram: https://t.me/EmClassic
Note:
* We are looking for substance in reviews. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels do not count as third-party discussion).
-->
1. http://telegra.ph/EEMCLASSIC-EML-05-08
2. https://concourseq.io/Q/EM_Coin_Classic
3.https://www.minds.com/blog/view/840376544565633024
4. https://ion.community/topic/2012/empire-coin-classic
5.http://cryptoceria.blogspot.com.ng/2018/05/emclassic-token.html?m=1

**Comment by LoopNewtorkInc** [comment]
Updates link to reviews.

**Comment by Kryptoniq** [comment]
Provide link to your bitcointalk announcement thread.

**Comment by LoopNewtorkInc** [comment]
Good day,
Link to Ann Thread on Bitcoin talk. Thank you.
https://bitcointalk.org/index.php?topic=3513348.new#new

**Comment by freeatnet** [comment]
@LoopNewtorkInc Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. **Reviews must include original research on project vision, team, milestones, or existing product.**

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

/cc @Kryptoniq
