### ISSUE TITLE
Listing Request: Amon (AMN)

### ISSUE THREAD

**Issue by vexatuvex** [forkdelta/tokenbase#1033]
Contract address: 0x737f98ac8ca59f2c68ad658e3c3d8c8963e40a4c
Name: Amon
Decimals: 18
Symbol: AMN

Issuer's official website: https://amon.tech

Description: Amon is an every-day crypto Debit Card for everyone. It has a powerful multi-currency crypto wallet and state-of-the art artificial intelligence to provide the best value to the crypto holder in every-day purchases. Amon Card solves two existential problems with crypto spending: (1) Real time conversion, (2) Dealing with crypto volatility.

Official contract address confirmation: https://github.com/amontech/token-contract

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
Bitcointalk: https://bitcointalk.org/index.php?topic=2875733.0
Reddit: https://www.reddit.com/user/amon_card
Medium: https://medium.com/@amontech
Twitter: https://twitter.com/amonwallet
Facebook: https://www.facebook.com/amontechwallet
Youtube: https://www.youtube.com/channel/UCjKbM7nEvGVfUzbJ4iZEyCw
Telegram: https://t.me/amontech
Linkedin: https://www.linkedin.com/company/amon-tech
GitHub: https://github.com/amontech

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x737f98ac8ca59f2c68ad658e3c3d8c8963e40a4c, https://amon.tech

**Comment by freeatnet** [comment]
@Kryptoniq Where are the review links?

**Comment by vexatuvex** [comment]
: ) under "Links to third-party reviews or discussion of the token, the project/product, or the token issuer:"

**Comment by freeatnet** [comment]
@vexatuvex Are there any independent third-party reviews featuring original research into the project?

**Comment by vexatuvex** [comment]
Hi there, yes : ) 
https://icobench.com/ico/amon
https://www.trackico.io/ico/amon/#market
https://tokenmarket.net/blockchain/ethereum/assets/amon/
https://www.icotokennews.com/icos/amon/
https://icocoins.io/event/amon/
CMC: https://coinmarketcap.com/currencies/amon/
Markets: Bancor Network, Cryptopia, Exrates, Idex
Thanks.

**Comment by freeatnet** [comment]
@vexatuvex I think this just about works for a review: https://coinvigilance.com/amon-review-card-tokens-wallet/. Are there more like that, maybe ones that go a bit in depth on team, vision, product?
