### ISSUE TITLE
Token Listing Request: MOBILINK - MLK

### ISSUE THREAD

**Issue by tkdeveloper** [forkdelta/tokenbase#1034]
Contract address: https://etherscan.io/token/0xAF3709f737C2354de7a8d9f258e554C7c64A0386

Token Symbol: MLK

Token Name: Mobilink Token

Issuer's official website: https://www.mobilink.io/

Whitepaper: https://mobilink.io/whitepaper/Mobilink-WP-full-english.pdf

One Pager: https://mobilink.io/Mobilink-WP-short.pdf

Official contract address confirmation:

https://mobilink.io/verifycontract.php

A link to a third-party review or discussion of the token:

https://icomarks.com/ico/mobilinkcoin
https://icoholder.com/en/mobilink-coin-17227
https://icobench.com/ico/mobilinkcoin
https://bitcointalk.org/index.php?topic=2614818.msg26607277#msg26607277
https://www.facebook.com/MOBILINKICO/
https://vk.com/mobilinkcoin
https://twitter.com/mobilinkcoin
https://t.me/joinchat/HUJ5zRGLf8vlQ-wBpA-oGg
https://www.reddit.com/r/mobilinkcoin/
https://www.linkedin.com/company/mobilink-coin/
https://www.instagram.com/mobilinkcoin/
https://www.youtube.com/channel/UC5MFDfun9jkV5T_57pbPXkw
https://icomarks.com/ico/mobilinkcoin
http://www.digitaljournal.com/pr/3604284
https://arbolet.net/clanek/3792-zatim-nejvetsi-ico-mobilink-spusti-sve-ico-v-lednu-2018

Description:

MOBILINK-COIN ICO has partnered with Mobilink-Network to be the First Decentralized Mobile Telecom Company using blockchain technology. Digital monthly revenues based on Proof of Participation pay for all voice and data usage costs.

**Comment by Kryptoniq** [comment]
#949

**Comment by tkdeveloper** [comment]
We had to change the token name and reissue the token.

This can be verified on our website here:

Official contract address confirmation:

https://mobilink.io/verifycontract.php

Contract address: https://etherscan.io/token/0xAF3709f737C2354de7a8d9f258e554C7c64A0386

Token Symbol: MLK

Token Name: Mobilink Token

Issuer's official website: https://www.mobilink.io/

Whitepaper: https://mobilink.io/whitepaper/Mobilink-WP-full-english.pdf

One Pager: https://mobilink.io/Mobilink-WP-short.pdf

Official contract address confirmation:

https://mobilink.io/verifycontract.php

A link to a third-party review or discussion of the token:

https://icomarks.com/ico/mobilinkcoin
https://icoholder.com/en/mobilink-coin-17227
https://icobench.com/ico/mobilinkcoin
https://bitcointalk.org/index.php?topic=2614818.msg26607277#msg26607277
https://www.facebook.com/MOBILINKICO/
https://vk.com/mobilinkcoin
https://twitter.com/mobilinkcoin
https://t.me/joinchat/HUJ5zRGLf8vlQ-wBpA-oGg
https://www.reddit.com/r/mobilinkcoin/
https://www.linkedin.com/company/mobilink-coin/
https://www.instagram.com/mobilinkcoin/
https://www.youtube.com/channel/UC5MFDfun9jkV5T_57pbPXkw
https://icomarks.com/ico/mobilinkcoin
http://www.digitaljournal.com/pr/3604284
https://arbolet.net/clanek/3792-zatim-nejvetsi-ico-mobilink-spusti-sve-ico-v-lednu-2018

Description:

MOBILINK-COIN ICO has partnered with Mobilink-Network to be the First Decentralized Mobile Telecom Company using blockchain technology. Digital monthly revenues based on Proof of Participation pay for all voice and data usage costs.
