### ISSUE TITLE
List FOSHA

### ISSUE THREAD

**Issue by foshaorg** [forkdelta/tokenbase#1035]
Contract address: 0x61a541c78afd142f8e185142e2c4eb22639b310e

Issuer's official website: https://www.fosha.org/

Description: Fosha is a private blockchain node synced with popular decentralized networks. The node provides a fast, stable and secure access to decentralized networks and can be used by developers or traders to create contracts, sign transactions and call functions. Fosha API is scalable and fully compatible with JSON-RCP standards and web3 libraries.

Official contract address confirmation: https://github.com/foshaorg/contract/blob/master/contract

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. Bitcointalk: https://bitcointalk.org/index.php?topic=3308241
2. Medium: https://medium.com/@Fosha
3. Twitter: https://twitter.com/FoshaSupport
4. Telegram: http://t.me/foshaorg
5. GitHub: https://github.com/foshaorg

**Comment by Kryptoniq** [comment]
There are only 3 token holders.
Your bitcointalk thread has insufficient reviews. Provide link to a third-party review of your project.
