### ISSUE TITLE
WIKI token (WIKI)

### ISSUE THREAD

**Issue by wiki7711** [forkdelta/tokenbase#1037]
Contract address:
0x05aaa4d5663bcbef074927fe981f4a4b75b85b39

Issuer's official website:
https://wikitoken.bitcoinwiki.org/
Description:
BitcoinWiki.org announces the first ever Crypto University: an academy for the digital world. Students will access updated, reliable information about Bitcoin technology, blockchain, economy, world affairs, and more. Crypto University challenges traditional education, offering independent, free and impartial knowledge. 
The wiki token is an Ethereum-based, ERC-20 compatible token, which makes it easy to hold. The circulation of wiki tokens is the glue that brings all 3 layers of the Crypto University together.

Official contract address confirmation: 
https://wikitoken.bitcoinwiki.org/tokens/
https://etherscan.io/token/0x66bad545596fb17a0b4ebdc003a85def10e8f6ae

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://cointelegraph.com/press-releases/wiki-token-wiki-now-listed-on-hitbtccom
2. https://altcointoday.com/crypto-university-the-crypto-education-of-the-future/
3. https://www.cryptocoinupdates.com/crypto-university-the-crypto-education-of-the-future/
4. https://www.criptotendencias.com/blockchain/cripto-universidad-la-cripto-educacion-del-futuro/
5. http://infocoin.net/en/2018/04/13/discover-a-new-way-of-studying-bitcoin-wiki-cripto-university-online/
6. https://www.bestcoins.co/ico/wiki-token
7.  https://www.icochamps.com/ico/WIKIToken
8. https://icobuffer.com/projects/wiki_token

**Comment by wiki7711** [comment]
It is on the end of this page
https://en.m.bitcoinwiki.org/wiki/Main_Page

Here: "This Wiki collects all the information about Bitcoin and other cryptocurrencies. Join us, we need your help.
Follow us on Reddit
Support team: becky@bitcoinwiki.org
In cryptocurrency we trust!"

The screenshoot
http://res.cloudinary.com/dhwdvj8ka/image/upload/v1527592843/2018-05-29_14.19.00.png

**Comment by Kryptoniq** [comment]
The contract address is not on the page. Contract address starts with 0x.

**Comment by wiki7711** [comment]
I'm sorry. It's here.

Contract address:
0x05aaa4d5663bcbef074927fe981f4a4b75b85b39
Official contract address confirmation:
https://wikitoken.bitcoinwiki.org/tokens/
https://etherscan.io/token/0x66bad545596fb17a0b4ebdc003a85def10e8f6ae

**Comment by Kryptoniq** [comment]
This is getting pretty complicated.
The address `0x05aaa4d5663bcbef074927fe981f4a4b75b85b39` on your website isn't a token address.
And `0x66bad545596fb17a0b4ebdc003a85def10e8f6ae` which is the token's address is not found on your website.

**Comment by wiki7711** [comment]
I'm sorry, I didn't mean to complicate things.
Token's address (0x66bad545596fb17a0b4ebdc003a85def10e8f6ae) is here https://wikitoken.bitcoinwiki.org/tokens/

section F.A.Q. – Getting wiki tokens – "To get your wiki tokens, send the appropriate amount of ETH to our smart contract address: 0x66bad545596fb17a0b4ebdc003a85def10e8f6ae(e.g. Add Token in Metamask)"

Screenshoot –  http://res.cloudinary.com/dhwdvj8ka/image/upload/v1528454761/2018-06-08.png

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x66bad545596fb17a0b4ebdc003a85def10e8f6ae, https://wikitoken.bitcoinwiki.org/
