### ISSUE TITLE
Adding FUND Token  to Forkdelta 

### ISSUE THREAD

**Issue by fundchains** [forkdelta/tokenbase#1038]
FUNDChain: The Blockchain investment Economy.A Quality Token in Decentralized Blockchain Economy with Exponential Growth We Invest in Top Tokens and Make Profits You Invest in Fund Token and Get Rewards.

Contract address: 0xd20bcbd56d9d551cac10a6bc2a83635bfb72f3f4

Issuer's official website: www.fundchains.org

https://twitter.com/fundchains 

https://t.me/fundchains   10000 follows

fund@fundchains.org

https://bitcointalk.org/index.php?topic=3516165.0

https://etherscan.io/token/0xd20bcbd56d9d551cac10a6bc2a83635bfb72f3f4

Official contract address confirmation: www.fundchains.org

**Comment by Kryptoniq** [comment]
Please provide links to atleast two third-party reviews or discussion of your token. Your bitcointalk announcement thread has insufficient reviews.
