### ISSUE TITLE
NEXO

### ISSUE THREAD

**Issue by mikejankow** [forkdelta/tokenbase#1040]
Contract address: 0xB62132e35a6c13ee1EE0f84dC5d40bad8d815206

Issuer's official website: https://nexo.io

Description:  Nexo is delivering the first instant crypto backed loans with the first SEC compliant dividend token backing it. Backed by a leading, 10 year old European fintech company in Credissimo, Nexo officially launched their lending platform on 4/30/18 and is fully prepared to handle the over 1 billion in loan requests that it's already received.

Official contract address confirmation:  I'm not sure where to find it other than here: https://etherscan.io/token/0xb62132e35a6c13ee1ee0f84dc5d40bad8d815206#readContract

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.coindesk.com/arrington-backed-startup-launches-crypto-for-cash-credit-platform/
2. https://cointelegraph.com/explained/dividend-tokens-explained

**Comment by Kryptoniq** [comment]
https://coinmarketcap.com/currencies/nexo/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xb62132e35a6c13ee1ee0f84dc5d40bad8d815206, https://nexo.io/

**Comment by freeatnet** [comment]
@mikejankow Thank you for your request! Your token will be live on **Tuesday, June 26th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
