### ISSUE TITLE
Listing Request: Cider Token (ERC223)

### ISSUE THREAD

**Issue by montanachan** [forkdelta/tokenbase#1041]
Contract address: 0xe71c0f3930fD0B123A744dAD4f9A6b98a07Fe7D6
Name: Cider
Decimals: 8
Symbol: CIDER

Description: Cider is a cryptocurrency aimed at animal welfare. The goal is to build a matching site for animals and establish a gated community for all people. It is a Japanese ERC223 token project that emphasizes reliability and transparency.
We are hoping for a fair first sale to everyone without ICO. Thank you.

Official website: http://cider.starfree.jp/
Whitepaper: https://drive.google.com/open?id=19d1dzsHVWbG8Zmtgpfx80fo1xG-raWWt
Github: https://github.com/montanachan/cider/blob/master/cider.sol
Etherscan: https://etherscan.io/address/0xe71c0f3930fd0b123a744dad4f9a6b98a07fe7d6#code
Blog: http://yotsumao.hatenablog.com/entry/2018Reboot_New_CryptoCurrency_Cider_project_from_japan
Youtube: https://www.youtube.com/watch?v=OC4njaozbiM
Twitter: https://twitter.com/montamtaro

**Comment by Kryptoniq** [comment]
Zero token holder
No social media handle
No third party review.
