### ISSUE TITLE
Token Listing Request: MILE

### ISSUE THREAD

**Issue by snagride** [forkdelta/tokenbase#1042]
Dear ForkDelta,

We would like to list out token MILE on ForkDelta. Below is our token and company information. Thank you!

Token Symbol: MILE
Decimals: 18

Contract address:
0xa7fC9BeE18d65A7E6f9F8b52a8edADE5F681E961

Issuer's official website:
https://snagride.com/

Description:
MILE is a form of payment for rides on the SnagRide ride-sharing ecosystem. And a way to create smart contracts with rider information for our artificial intelligence bot "Miles".

Official contract address confirmation:
https://snagride.com/how-to-create-a-wallet.pdf

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://newswatchtv.com/2018/02/15/snagride-newswatch-review/
2. https://www.marketwatch.com/story/snagride-the-decentralized-ai-ridesharing-application-to-launch-mile-token-pre-sale-january-10-2018-2018-01-02
3. https://www.prnewswire.com/news-releases/snagride-building-on-origin--announcing-our-partnership-with-origin-protocol-300581860.html
4. https://bitcointalk.org/index.php?topic=2655106.0
5. https://topicolist.com/ico/snagride

Please let us know if there is any question or if you need more info. You may email directly to info@snagride.com also. Thank you again!

Best Regards,
The SnagRide Team

**Comment by snagride** [comment]
Our ICO went well and we have sold about 2.5 million MILE tokens. There were no token transfers last month because we are currently developing our platform for token rewards and will be launching very soon.

Please let us know if you need more information. Thanks!

**Comment by freeatnet** [comment]
@snagride Can't seem to find any original research or review of the company, team behind it, roadmap, existing products. Could you add those, please?

**Comment by snagride** [comment]
Dear FolkDelta,

Do you have any question on the information we provided above? We would like to have our token listed as soon as possible. We are looking forward to hearing good news from you. Thank you!

Best Regards,
The SnagRide Team

**Comment by snagride** [comment]
Dear FolkDelta,

We have recently rolled out our new website. Please visit https://www.snagride.com/ to see our new product. Also, for ICO related info, you may access them using https://www.snagride.com/ico/

Best Regards,
The SnagRide Team
