### ISSUE TITLE
Token Listing Request: KSYS ERC20 Token 

### ISSUE THREAD

**Issue by ksystemsio** [forkdelta/tokenbase#1043]
**Contract address:** 0xb09345CE9A795EfE675197838E5aCde392B71317

**Issuer's official website:** https://ico.ksystems.io and https://ksystems.io

**Description:** The KSYS Token is the K Systems LTD Token: Our company is a registered UK firm (#11291459, Unique Taxpayer Reference 765811430 A), building and deploying dApps for the Aerospace Industry (AS/EN 9100 Quality Standards) and providing ICO and security services for startups.
Our Global white paper is available here: https://github.com/ksystemsio/KSYS_Global_White_Paper/blob/master/KSYS_Global_White_Paper.pdf
The KSYS Token is an ERC20 Token.
ERC stands for Ethereum Request for Comments. This is an official protocol for proposing improvements to the Ethereum network. '20’ is the unique proposal ID number.
The KSYS Token is used in two ways:
a) our KSYS 1 (AS/EN 9100 Aerospace Compliant) dApp is using it to reward the worker/company/machine that delivers the required work (as per official work order, stored in our private blockchain and IPFS) within the time frame and at the quality level which was agreed in the proposal/order phase;
b) KSYS token holders can use the token to purchase services within our ecosystem, a "Galaxy" (https://ksystems.io) where users can rent out a planet, get their ICO setup, security audits for their Ethereum Smart Contracts, specific consultancy services or all of that;
The KSYS Token official contract address is: 0xb09345CE9A795EfE675197838E5aCde392B71317
The KSYS Token initial crowdsale contract address is: 0x7a30683E25c98cF6cf3306b2C41B743cb96c02c4
The source code of the contracts is published and verified on Etherscan and available on GitHub.
KSYS Tokens can be used by users to buy services within the K Systems LTD Galaxy (https://ksystems.io), including renting a planet in it.
The KSYS Token IS NOT A SECURITY NOR A SHARE OF K SYSTEMS LTD.

**Official contract address confirmation:** https://ico.ksystems.io/invest and https://github.com/ksystemsio/KSYS_Global_White_Paper/blob/master/KSYS_Global_White_Paper.pdf

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=3372774.msg35353614#msg35353614
2. https://www.listico.io/ico-calendar/ksys-token-pre-icos
3. https://bitcointalk.org/index.php?topic=3534671.new#new
4. https://bitcointalk.org/index.php?action=profile;u=1746369;sa=showPosts
5. https://www.stateofthedapps.com/dapps/ksys1-ipfs-dse
6. https://bitcointalk.org/index.php?topic=3494909.msg36497879#msg36497879

[K Systems DApps White Paper.pdf](https://github.com/forkdelta/tokenbase/files/1977223/K.Systems.DApps.White.Paper.pdf)
[KSYS Token White Paper.pdf](https://github.com/forkdelta/tokenbase/files/1977224/KSYS.Token.White.Paper.pdf)
[KSYS_Global_White_Paper.pdf](https://github.com/forkdelta/tokenbase/files/1993104/KSYS_Global_White_Paper.pdf)

**dApps:** https://ksystems.io/DApps/KSYS1_IPFS/

**Links:** 
ICO Site: https://ico.ksystems.io
K Systems Galaxy: https://ksystems.io
Telegram Channel: https://t.me/ksys1
Github: https://github.com/ksystemsio
Gitter Lobby: https://gitter.im/ksystemsio/Lobby
Twitter: https://twitter.com/ksystemsio
BitcoinTalk: ksystems77
Reddit: /u/turtle977
![cattura](https://user-images.githubusercontent.com/13600685/39965657-a18cd762-569d-11e8-8b01-1faadeb9bdce.PNG)

**Comment by freeatnet** [comment]
Thank you for your request, @ksystemsio! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- **Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md)** and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
