### ISSUE TITLE
Bazista Token Listing Request

### ISSUE THREAD

**Issue by BazistaPlatform** [forkdelta/tokenbase#1045]
Contract address: https://etherscan.io/address/0x37bda986671aa761dc4a1c532b18117ebf8879ee

Issuer's official website: https://bazista.io/en

Description: 
Bazista is an online marketplace which aims to bring down e-commerce barriers through deep integration of decentralized money as a payment instrument.
Bazista token is a loyalty token, which can be used as a currency for implementing payments on the platform. Bisedes, the token acts as a fuel for Bazista eco-system, providing: 
1. Lower platform commissions - down to 0% vs using other digital currencies.
2. Discounted sales of the most desired products for loyal BZS users.
3. Additional services for Bazista sellers to improve their performance will be available for BZS tokens only. 

MVP Launched: https://bazista.com/en

Official contract address confirmation: https://github.com/BazistaPlatform/BazistaTokenContract/blob/master/Contract 
previous (the link may also be found on the landing page https://bazista.io/en in the section "Role of Token")
*Please note that we have just created separate Bazista profile on Github, previously our Smart Contracts were uploaded here: https://github.com/indigoram89/bazista-contracts

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://cointelegraph.com/press-releases/bazista-simple-yet-incredible
2. https://cointelegraph.com/press-releases/bringing-decentralized-money-into-the-sunshine
3. https://thecoinshark.net/bazista-will-use-augmented-reality-and-3d-modeling
4. https://thebitcoinnews.com/bazista-platform-innovation-online-shopping/
5. https://www.techbullion.com/interview-ceo-bazista-bzs-token-sale/
6. https://www.chipin.com/bazista-ico-b2c-c2c-platform/
7. https://themerkle.com/bazista-is-looking-for-sellers-promoters-ahead-of-the-beta-launch/
8. https://coinjournal.net/pr-release/bazista-announces-pre-ico-stage-investors-e-commerce-users/
9. https://icobench.com/ico/bazista/team
10. https://icomarks.com/ico/bazista
11. https://icobazaar.com/v2/bazista

**Comment by BazistaPlatform** [comment]
Hello Forkdelta Team!

Please let us if there is any more info you would like us to provide?

Cheers!

**Comment by Kryptoniq** [comment]
Please make the contract address `0x37bda986671aa761dc4a1c532b18117ebf8879ee` available on your website.

**Comment by BazistaPlatform** [comment]
Sorry, our page on Github was blocked for some period of time
No the link is working fine again - you may find it in the 2nd block of the site under "the role of token" section

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x37bda986671aa761dc4a1c532b18117ebf8879ee,   https://bazista.io/en

**Comment by BazistaPlatform** [comment]
Sounds great! Thanks a lot!

**Comment by BazistaPlatform** [comment]
Hello! 

Please let me know if the token will be listed any time soon?

Cheers!

**Comment by BazistaPlatform** [comment]
@therealMikkoKoo, Hello!

Could you please help us to clarify why our token can't get listed yet?

Cheers!
