### ISSUE TITLE
SHC listing

### ISSUE THREAD

**Issue by spencermorgan** [forkdelta/tokenbase#1046]
Contract address: 0xb33d73a8aecb5a87173a27503507547752ed9310

Issuer's official website: http://www.shopcoin-offical.com/

Official contract address confirmation(The page 19): http://www.shopcoin-offical.com/Whitepaper/white-paper.pdf

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3152272.0

Description: ShopCoin is a global decentralized shopping and services platform,SHC platform is created to provide a secure and decentralized platform where sellers and buyers are able to meet and transact at lower costs without the need for middlemen.

**Comment by Kryptoniq** [comment]
Your advisory board looks suspicious. There is no mention of shopcoin on their LinkedIn.
If there are advisors, why are there not team members on your website?
Please provide explanations to these queries within the next five days.
 http://www.shopcoin-offical.com/(https://web.archive.org/web/20180606000343/http://www.shopcoin-offical.com/)
