### ISSUE TITLE
Token listing of GRE

### ISSUE THREAD

**Issue by zhang77xixi** [forkdelta/tokenbase#1049]
Contract address:0x4b04633ee658d83a24a91E3a1b244221800D89B4

Issuer's official website:https://www.gref.io

Description: 
Global Risk Exchange (or "GRE") is a blockchain based, decentralized risk contract exchange market, with the purpose of helping individuals, companies and organizations to better trade and manage their risks.
In GRE platform we use RISK token as transaction intermediary, a Ethereum smart contract based and ERC20 standard compliant token.
1.All risk management contract use RISK as transaction intermediary and all risk contract claim distribution will use RISK for settlement;
2.Users on GRE platform should buy RISK tokens to pay for transactions fees;
3.Any institutions and individuals could publish risk management contracts using GRE platform and will get volume based rewards in RISK tokens;
4.GRE community will reward developers with RISK tokens in light of their code contributions;
5.Any individuals and institutions can share risk mangement contracts in their social networks and attract more users to trade those contracts. They will be rewarded a portion of new transaction fees derived from those newly traded contracts;
6.GRE platform allows exchange dealers use RISK tokens as collaterals to issue market pegged stable coins; similar to BITCNY and BITUSD on Bitshares platform.

Official contract address confirmation: 
0x4b04633ee658d83a24a91E3a1b244221800D89B4

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?action=profile;u=1958758
2.https://www.digfingroup.com/gre/?from=groupmessage&isappinstalled=0

**Comment by Kryptoniq** [comment]
- Make your contract address available on your website
- Provide links to at least two third-party reviews of your project.
