### ISSUE TITLE
Listing Request - Enumivo

### ISSUE THREAD

**Issue by enumivo** [forkdelta/tokenbase#105]
Contract Address: 
0x275b69AA7c8C1d648A0557656bCe1C286e69a29d

Website: 
https://www.enumivo.org/

Contract Address Verification: 
https://www.enumivo.org/smart-contract-address

Third Party Review: 
http://somethingdecent.co.uk/crypto/crypto-chronicles/introducing-enumivo-social-justice-blockchain/

Description:
Enumivo is a blockchain based on EOS. Our flagship project will be a Decentralized Universal Basic Income Application to promote social justice for everyone.

**Comment by JonathonDunford** [comment]
Verified: 0x275b69AA7c8C1d648A0557656bCe1C286e69a29d

Can you please provide a short description of 1-3 sentences?

@enumivo

**Comment by enumivo** [comment]
Description added on the original post:

Description:
Enumivo is a blockchain based on EOS. Our flagship project will be a Decentralized Universal Basic Income Application to promote social justice for everyone.

**Comment by JonathonDunford** [comment]
#72
