### ISSUE TITLE
Token Listing Follow up

### ISSUE THREAD

**Issue by ugamoako** [forkdelta/tokenbase#1050]
Contract address: 0xa55fc2f935e5decd52685e28c9f1e94528f86c70

Issuer's official website: https://shift.cash

Description: The SHIFT.cash project is part of the global financial technology market. We help creditors, investors and borrowers to maximize the benefits of working with each other without geographical barriers and minimize risks of investments.

The basis of our platform is blockchain technology, collateral assets tokenization and extensive experience of our experts in the field of secured loans.

- More secure than ordinary Peer-to-Peer
- More scale than ordinary Car Title loans business

Official contract address confirmation: https://shift.cash/#faq. the contract address is available in this section of our website.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=2592700.0
2. https://icobench.com/ico/shift-cash/ratings

**Comment by Kryptoniq** [comment]
#862
