### ISSUE TITLE
SINERGIA BLOCKCHAIN

### ISSUE THREAD

**Issue by SinergiaBlockchain** [forkdelta/tokenbase#1053]
Contract address: 0xcFD6Ae8BF13f42DE14867351eAff7A8A3b9FbBe7

Issuer's official website: https://www.sinergiablockchain.org
                                      https://www.sinergiablockchain.org/_/index_en.html

Description: 

It is a Latin American organization, enthusiast of the Blockchain Technology, creators of SINERGIA (SNG), the first Colombian cryptoactive framed in an ecosystem of learning and culture of innovation, of generation of knowledge and improvement of the quality of life through technology.

SNG Token is created with the aim of promoting and spreading innovation and technological entrepreneurship, as an essential part of a learning and research community

Official contract address confirmation: 

  https://www.sinergiablockchain.org

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=2210037.0

2. https://www.facebook.com/SinergiaBlockchain/  https://t.me/ComunidadSinergiaBlockchain

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread does not contain substantial reviews. provide links to at least two third-party reviews of your project other than bitcointalk.
