### ISSUE TITLE
Blocksquare BST token listing

### ISSUE THREAD

**Issue by blocksquare** [forkdelta/tokenbase#1054]
Contract address: 0x509a38b7a1cc0dcd83aa9d06214663d9ec7c7f4a

Issuer's official website: https://blocksquare.io

Description: 
A blockchain-based plug & play system to power commercial real estate tokenization.
Blocksquare enables established real estate businesses to create and offer tokenized real estate investment deals directly on their website, opening the world of commercial real estate to anyone with an internet connection.
https://blocksquare.io/assets/pdf/Blocksquare-one-pager.pdf

Official contract address confirmation: https://blocksquare.io (footer, bottom left) 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://bitcointalk.org/index.php?topic=3215774.20
2. https://icobench.com/ico/blocksquare-io
3. https://cointelegraph.com/news/european-startup-to-enable-access-to-commercial-real-estate-for-small-investors
4. https://t.me/blocksquare

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
 https://blocksquare.io, 0x509a38b7a1cc0dcd83aa9d06214663d9ec7c7f4a

**Comment by blocksquare** [comment]
Hi, any news about BST token listing? I appreciate your feedback.

**Comment by marcguchte** [comment]
I would love to see BST listed! When is it coming?

**Comment by 0b0ne** [comment]
Can you please assist with listing BST. All help us greatly appreciated.

**Comment by gazmundo1987** [comment]
Please could you give a time frame for the bst listing the community is waiting for the update many thanks 😃

**Comment by ranikeys** [comment]
Hello Kryptoniq  the community would greatly appreciate you being able to create a BST | ETH pairing. Thanks again in advance.

**Comment by Vechainer** [comment]
Any news about the listing?

**Comment by blocksquare** [comment]
Hi there,
@Kryptoniq still no news regarding our token listing?

**Comment by 0b0ne** [comment]
@Kryptoniq keen to hear news please on the token listing. Appreciate your help.

**Comment by 0b0ne** [comment]
Any updates please.

**Comment by marcguchte** [comment]
@kryptoniq any update yet?

**Comment by blocksquare** [comment]
@freeatnet Hi there, when can we expect our BST token to be processed and officially listed at Forkdelta? Thank you.

**Comment by 0b0ne** [comment]
Hi again,

Can we please get a pairing for BST.

Thanx.

**Comment by 0b0ne** [comment]
Hello again,

When will you be able to make BST a standard trading pair?

Thanks.

**Comment by blocksquare** [comment]
Hi @freeatnet. It has been 4 months since our listing application was filed. Could you please let me know when can expect BST token to be listed? Thanks for the info!
