### ISSUE TITLE
GoldenChain ForkDelta Application

### ISSUE THREAD

**Issue by goldenchain** [forkdelta/tokenbase#1056]
Contract address: 0xb0bb3c7193fb9aea9d8c28200162264ff1800167

Issuer's official website: https://www.goldenchaintoken.org/

Description: 
GoldenChain's the main goal is to create a golden trading platform. Also GoldenChain is aiming to use GOLD Token on e-commerce websites both as payment method and as discount coupon.

Official contract address confirmation: 
https://www.goldenchaintoken.org/#about

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.atgnews.com/2018/04/gold-ico-information.html
2. https://bitcointalk.org/index.php?topic=3197446.0
2. https://t.me/goldenchain

**Comment by goldenchain** [comment]
Hello, are there any update? 

Regads, 
GoldenChain Team.

**Comment by Kryptoniq** [comment]
This is an ICO-only token without a project plan.
- No team information 
- No legal information 
- No whitepaper 
Roadmap map only talks about ICO, Airdrop, Exchange and wallets.   
```How it Works
GoldenChain makes easy to money tranfer and phisical golden purchases

Fast and Secure

Easy Mobile Solutions```
Based on these findings, we will not be listing this token.
If you believe live this decision was made in error kindly contest it by providing objectionable facts that supports the validity of the project on this issue. 
https://www.goldenchaintoken.org/
https://web.archive.org/web/20180606160838/https://www.goldenchaintoken.org
