### ISSUE TITLE
XCEL token listing 

### ISSUE THREAD

**Issue by xceltripofficial** [forkdelta/tokenbase#1057]
Contract address:   0xf6276830c265a779a2225b9d2fcbab790cbeb92b
https://etherscan.io/address/0xF6276830c265A779A2225B9d2FCbAb790CBEb92B#code
https://github.com/xceltripofficial/xceltoken/blob/master/audit-report/XCeltrip%20Audit.pdf

Issuer's official website:
https://xceltrip.com/
https://xceltoken.com/

Description: 

Xceltoken will function as a utility token on the https://xceltrip.com platform that provides services in travel and hospitality eco-system. We have embarked on a progressive decentralized roadmap. Initial utility of xceltoken will be that of a payment method. As the eco-system matures we will provide further utility such as contract based settlement to vendors, xceltoken as loyalty /rewards points, staking to participate in governance model etc. Instead of raising funds via ICO , we have decided to do public sale at market price and grow the eco-system based on product functionality. The platform provides everyday folks to turn into a travelpreneur and participate in the token economy to grow the platform.

More details can be found here - https://xceltoken.com/#whitePaper

Official contract address confirmation: 

https://xceltoken.com/SmartContract

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://www.inc.com/darren-heitner/this-blockchain-based-travel-ecosystem-has-been-in-works-for-3-years.html
https://thecoinshark.net/one-of-a-kind-decentralized-travel-eco-system
https://www.ccn.com/xceltrip-announces-the-sale-of-xceltoken/
https://www.coinschedule.com/blog/blockchain-technology-business-avenues/

Twitter Links: 
XcelTrip Twitter: https://twitter.com/xceltrip
XcelToken Twitter: https://twitter.com/xceltoken

Facebook Pages:
XcelToken Page
https://www.facebook.com/XcelToken/
 XcelTrip Page:
 https://www.facebook.com/XcelTripGo/
 
 Medium: https://medium.com/@xceltokengo

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xf6276830c265a779a2225b9d2fcbab790cbeb92b, https://xceltoken.com/
