### ISSUE TITLE
Add ssocoin (SSO)

### ISSUE THREAD

**Issue by ssocoin** [forkdelta/tokenbase#1058]
Contract address: https://etherscan.io/token/0x8687502Bc1961E2E8edfCEa902598fc48Dcd4a9f

Issuer's official website: https://www.ssocoin.com/school

Official contract address confirmation: You can find the hyperlink of “CONTRACT ADDRESS” under the “TECHNOLOGY” column in the lower part of our homepage https://www.ssocoin.com .

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2817945.0

Description:
Ssocoin, a decentralized and encrypted currency with unique value protection.

Dear Honored Leaders of ForkDelta,
Our electronic currency is named SSOCOIN, code SSO, which is an ERC20 token developed based on Ethereum smart contract technology. Our official website is https://www.ssocoin.com .
 
Our SsoCoins have a unique operation mode of value protection system, which can give customers good returns. Besides, we expand the market by providing commission for customers so that they may recommend our products to other potential buyers. As a result, our SsoCoins are easy to be accepted by the market.
 
You are welcome to refer to our promotion website http://www.ssocoin.com/school to learn about the operation of our SsoCoins.
Also, our website on reddit is offered for you: https://www.reddit.com/r/ssocoin/
You can also search us on bitcointalk:  https://bitcointalk.org/index.php?topic=2817945.0
 
We didn’t make an ICO, which is up to our unique operating mode. But it is precisely because we never make ICO that we can control the stability and rise of the price of Ssocoin to bring considerable profits to customers, so as to attract more customers and open the market effectively.
We are scheduled to promote on Twitter, Google and other major websites after the listing of SsoCoin,with the enough returns we provide to clients, we believe that the number of our customers will grow day by day.
Meanwhile, we sincerely hope that your esteemed company may grant us a chance to bring more customers to the trading platform of our company through our application, so as to achieve a win-win situation for both of us.
 
TECHNICAL DATA OF  SSOCOIN
COIN NAME: SSOCOIN
TICKER: SSO
ALGO: DPOS
TOTAL SUPPLY: 180M
PREMINE: 180M
DECIMALS: 8
CONFIRMATION:12
NUMBER OF BLOCKS: 25126
BlOCK TIME: 15S
DEV LANGUAGE: GOLANG
 
Your Sincerely
Best Regards 
SsoCoin Team

**Comment by ssocoin** [comment]
Hi:
Previously on May 9th, we applyed for a add token request ,here we need revised our data in Ssocoin which under Decimals is 18, NOT 8, hope to get your reply soon. 
Could you list our SsoCoin on Forkdelta please?
Thanks
Sincerely

DECIMALS: 18

**Comment by Kryptoniq** [comment]
There are only 16 token holders. 
Your bitcointalk announcement thread has insufficient reviews. Kindly provide links to at least  two third-party reviews or discussion of your project other than bitcointalk.

**Comment by Kryptoniq** [comment]
There are only 15 token holders and your bitcointalk thread contains insufficient information about your project.
Looking through your website, there are no team members and no links to third-party reviews. Your project only talks about wealth.
I'm sorry but your project does not our requirements and can not be listed at this time.
Thank you.
