### ISSUE TITLE
Listing Request 

### ISSUE THREAD

**Issue by Shane1271** [forkdelta/tokenbase#106]
I hope you guys get everything fixed. To advanced traders Etherdelta is everything. It's a brilliant contract Zack made. It just needs to get ironed out.
Our company already uses your exchange by manually imputing the address. But we are missing out on potential investors by not being in the dropdown box. 
Thanks

Heiss Shares 
Contract: 0x3f5BC4FC79B5f8b93ff4814cd9f9A281893D50c9
Symbol: HYS
Decimals:1

Heislerfinancial.com

Verify our contract address on the white paper

**Comment by JonathonDunford** [comment]
Verified: 0x3f5bc4fc79b5f8b93ff4814cd9f9a281893d50c9

|Can you please provide a 1-3 sentence description?

@Shane1271 

Thanks for your kind words!

**Comment by Shane1271** [comment]
We are a consultant firm that uses hys as a medium of Exchange. We only accept our own token in exchange for services. We burn half the fees we get and we've set aside a dividend reserve for holders. Please visit our website Heislerfinancial.com

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
