### ISSUE TITLE
Please list EGGtoken

### ISSUE THREAD

**Issue by JosephPitluck** [forkdelta/tokenbase#1060]
Contract address: 0x7c47318dd2d79976032951f535cb5a713bd53971

Issuer's official website: eggtokens.com

Description: Utility token for thisorthat.io, recently became #5 in daily active users on Dappradar.com, we have a listing agreement with Bancor

Official contract address confirmation: EGGtokens.com

Links to third-party reviews or discussion of the token, the project/product, or the token issuer: 
1. https://startengine.com/FRtoken
2. https://www.bizjournals.com/albuquerque/news/2018/04/18/four-new-mexico-startups-invited-to-summit-in.html

![dappradar5](https://user-images.githubusercontent.com/35241800/39782082-5f4a227e-52ce-11e8-8467-67003f21d615.png)

**Comment by robertdecrypto** [comment]
Very interesting project. Could you please give me the official twitter?

**Comment by RemyRooster** [comment]
Thanks,

Been using our original co-working space and my personal handle for twitter:

https://twitter.com/freerangespaces <https://twitter.com/freerangespaces>

https://twitter.com/JosephPitluck <https://twitter.com/JosephPitluck>

Joe

**Comment by azisjesika** [comment]
support all the way to freerange . best wishes to you
