### ISSUE TITLE
new coin request {inc}ognito

### ISSUE THREAD

**Issue by incognitocrypto** [forkdelta/tokenbase#1062]
Contract address: contact@incognitocurrency.com

Issuer's official website: inc.ognito.org

Description: 
{inc}ognito is a recently launched decentralized crypto currency project based on CryptoNote / Monero (private, secure, untraceable, fungible) and will introduce an enhanced anonymity layer though I2P in addition to mobile-centric development.

Official contract address confirmation: 
contact@incognitocurrency.com

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=3276900
2.

**Comment by Kryptoniq** [comment]
ForkDelta is a decentralized exchange for Ethereum tokens only.
Thank you.
