### ISSUE TITLE
Uniwothcoin (UNIX) Listing to forkdelta

### ISSUE THREAD

**Issue by qaismx** [forkdelta/tokenbase#1063]
Contract address:
0x36ec460817aA2FB8990B20DC58A7C6f86e7fC48d

Issuer's official website:
https://uniwoth.io

Description: 
Uniworth Coin (UNIX) is a secure, safe asset-backed cryptocurrency build on a multi-dimensional blockchain as a partially distributed ledger that is used for real-time payments. The underlying value of Uniworth Coin is established on a risk profile based user-defined allocation of a portfolio of asset classes. The Uniworth Coin (UNIX) wallet offers innovative features like Cross-Chain exchange for all forms of crypto currencies, micro-payments platform for internet transactions, person to person digital cash payments, Micro Investments and Smart Loans.

Official contract address confirmation: 
www.uniwoth.io

**Comment by Kryptoniq** [comment]
1. Your website uniwoth.io is down ATM.
2. Your contract address isn't verified on etherscan.io
3. Provide links to atleast 2 third-party reviews or discussion of your token.
