### ISSUE TITLE
Remove SCAM coin

### ISSUE THREAD

**Issue by batrinuvlad** [forkdelta/tokenbase#1064]
Hello,

I am Vlad, the Co-Founder of GoHelpFund. The team and the community would like to kindly request to remove the SCAM COPYCAT coin that doesn't have a project or a real team behind it, but is posing to be us.

Here's the scammer's contract: https://etherscan.io/token/0xe8c5e942b76099c0c6d78271bad3ca002fa7c531
Scammer's website: https://www.helpproject.info/

We're also kindly asking to remove the scammers ticker in order to use the HELP ticker, after finishing token distribution and being added on the exchange.

Proof that we are the real project:

Official website: https://gohelpfund.com
Official contract address: https://etherscan.io/address/0xbbc2045d335cb224228f1850b29173d9d7d7b989
Official contract address confirmation: https://tokensale.gohelpfund.com/home -> Token Tracker section in the top area.

Telegram: https://t.me/gohelpfund - 850+ members
Twitter: https://twitter.com/GoHelpFund_com - 2800+ followers

Facebook: https://www.facebook.com/gohelpfund/ - 800+ likes

Bitcointalk:  https://bitcointalk.org/index.php?topic=2160815.0 - 87+ pages

Press releases:

1. https://cointelegraph.com/news/romanian-startup-targets-400-bln-charity-fundraising-market-with-new-platform
2. https://themerkle.com/go-help-fund-connecting-people-with-blockchain-technology/
3. https://icomarks.com/ico/gohelpfund
4. https://icoholder.com/en/gohelpfund-17275
5. http://bitcoinist.com/go-help-fund-making-world-better-place-live/

**Comment by freeatnet** [comment]
Hi Vlad! Could you possibly split this issue up into two, one request to re-vet/remove 0xe8c5e942b76099c0c6d78271bad3ca002fa7c531 and one to list 0xbbc2045d335cb224228f1850b29173d9d7d7b989? The request to remove should come with more info on specific issues with the project / token.

**Comment by batrinuvlad** [comment]
@freeatnet sure, here is the request to remove, mentioning the specific issues with the project / token: https://github.com/forkdelta/tokenbase/issues/1128
