### ISSUE TITLE
Request to List NollyCoin on  ForkDelta

### ISSUE THREAD

**Issue by nollytainment** [forkdelta/tokenbase#1065]
Contract address: 0xb69096a89389638518725adfcf279f3f82efa2de

Issuer's official website: https://nollycoin.com

Description: A Decentralized Ecosystem For Movie Distribution and consumption In Developing Countries.

Official contract address confirmation: https://ico.nollycoin.com/Nollycoin-White-Paper.pdf
Contained within the official whitepaper

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://bitcointalk.org/index.php?topic=2995439.60
2. https://medium.com/@NOLLYCOIN
3. https://hype.codes/top-3-ongoing-ico-28-mar-4-apr-according-our-readers

**Comment by nollytainment** [comment]
Hello, 
Has there been any update on this issue?
Thanx.

**Comment by Kryptoniq** [comment]
I went through LinkedIn profiles of all your team members,   there  is no mention of "Nollycoin" except for the president's.

**Comment by cab8021** [comment]
Nollycoin has Been included the *linkedin*  profiles of the team members 
Thank You

**Comment by cab8021** [comment]
@Kryptoniq Pls Help Take a look at this. The profiles have been updated.
