### ISSUE TITLE
CatEther (0xCATE) Listing

### ISSUE THREAD

**Issue by F0lks** [forkdelta/tokenbase#1066]
Contract address: 0x8F7DbF90E71285552a687097220E1035C2e87639

Issuer's official website: https://www.catether.org

Description: CatEther is a mineable ERC20 token (EIP918 Standard) created by a student and his professor, from ESGI School, Paris. We aim at bringing free transfers on the Ethereum Platform for everyone, by minting one token for each and every transfer done. This token belongs to the transfer maker; there are no ICOs, just mining.

Official contract address confirmation: Just go on the official CatEther's website (catether.org), and scroll down just a bit. It's right there.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://www.reddit.com/r/ethereum/comments/8i1upy/more_erc_918_mineable_tokens/
A review talking about EIP918 Tokens, and, to a lesser extent, us (0xCATE). Good read ! 
2. https://bitcointalk.org/index.php?topic=3539559
Official BitcoinTalk thread

3 (bonus). https://longcatchain.com/ico/catether
We're registered on an ICO listing website, too

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews. Please provide links to atleast 2 third-party reviews of your token.

**Comment by F0lks** [comment]
Hi again ! 
We've got an article on Steemit (even though we didn't have had a lot of media coverage with it): https://steemit.com/news/@arantuil/a-mineable-token-the-new-dogecoin-how-to-mine-0xcate-token

Also, the Bitcointalk announcement is on multiple threads as the same time, since it's not just a token, it's a mineable token.
The link I've sent you above, is the announcement on the Token-Announcement section.
Here's the other thread, on the Altcoin-Announcement, with a significantly higher number of reviews : 
https://bitcointalk.org/index.php?topic=3540928

Some other Token-review website we're on : https://icopointer.com/catether

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x8f7dbf90e71285552a687097220e1035c2e87639, https://www.catether.org/
