### ISSUE TITLE
List request DAOstack GEN

### ISSUE THREAD

**Issue by leviadam** [forkdelta/tokenbase#1067]
Contract address: 0x543Ff227F64Aa17eA132Bf9886cAb5DB55DCAddf

Issuer's official website: https://daostack.io

Description: DAOstack is an operational stack for DAOs, a comprehensive toolkit for decentralized collaboration at scale. It provides the governance and economic framework needed for collectives to self-organize around shared goals and interests. DAOstack is based on a fully open, modular and upgradable architecture.

Official contract address confirmation: https://daostack.io (under the economy section)

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1.  https://finance.yahoo.com/news/solutions-emerge-replace-ethereum-premature-143111908.html?guccounter=1
2. https://e27.co/will-decentralised-governance-utopia-blockchain-applications-20180412/
3. https://www.forbes.com/sites/rogeraitken/2018/04/20/after-facebooks-data-blow-up-are-daos-leveraging-blockchain-the-future/#73c912343cef
4. https://themerkle.com/daos-dapps-and-stacks-a-decentralized-governance-system/
5. https://usethebitcoin.com/daostack-catalyzing-the-future-of-collaboration/
6. https://www.techworm.net/2018/04/daostack-building-a-framework-for-decentralized-organizational-structures.html

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.

---
Additional review: https://cryptobriefing.com/daostack-ico-review-gen-token-analysis/
Contract address confirmation: https://daostack.io/#economySection

0x543Ff227F64Aa17eA132Bf9886cAb5DB55DCAddf,https://daostack.io/

**Comment by freeatnet** [comment]
@leviadam Hey, DAOstack token symbol GEN appears to be in conflict with [Genesis (GEN)](https://etherscan.io/address/0x9dfe4643c04078a46803edcc30a3291b76d4c20c). Would you mind selecting a different symbol for the purposes of identification on FD?

**Comment by freeatnet** [comment]
@leviadam I've moved DAOstack to a separate PR, #1320. Let me know about the symbol.
