### ISSUE TITLE
PerksCoin Listing Request

### ISSUE THREAD

**Issue by danielcheine** [forkdelta/tokenbase#1070]
Contract address: 0x5ebE6a342a93102393EdD9D2e458C689e5aC0bb3
 
ticker; PCT
 
Decimals: 8
 
Issuer's official website: www.cannasos.com PerksCoin page; https://cannasos.com/crowdsale-ico

Description: CannaSOS is a social network for the health & wellness and cannabis industry and is the founder of the PerksCoin Token (PCT); an ERC-20 token developed on decentralized blockchain technology for the worldwide retail and cannabis industry. PerksCoin is being built into the PerksCoin Transaction Platform which will ensure transparency, quickness, and security of all financial transactions in the global retail industry. CannaSOS has been operating since 2014 and has over 325,000 members and over 1060 businesses using the platform.

Official contract address confirmation: 0x5ebE6a342a93102393EdD9D2e458C689e5aC0bb3 the contract address is not yet on our website. You can find it https://etherscan.io/address/0x5ebE6a342a93102393EdD9D2e458C689e5aC0bb3#code or 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
Bitcointalk; https://bitcointalk.org/index.php?topic=2403127.0
https://icobench.com/ico/perkscoin (this one has the CannaSOS logo instead of the PCT logo for some reason)
https://www.icotokennews.com/icos/perkscoin/
https://icomarks.com/ico/perkscoin (this one has the CannaSOS logo instead of the PCT logo for some reason)
https://www.nasdaq.com/press-release/perkscoin-coinpct-crowdsale-ico-accepts-additional-1500000-of-weed-coinweed-from-first-bitcoin-20180228-00221
http://torontosun.com/news/local-news/new-cryptocurrency-for-medical-cannabis-industry-still-hazy-economists
https://www.newsbtc.com/2018/01/19/cannasos-aims-cure-headaches-cannabis-dispensaries-blockchain-solution/
https://www.economist.com/news/finance-economics/21732080-cash-they-must-work-vulnerable-crooks-cops-and-even-combustion
https://midasletter.com/2017/11/video-cannasos-ceo-oleg-cheine-creating-digital-currency-cannabis-users/
https://www.newsbtc.com/2017/12/02/cannabis-blockchain-perfect-match/

**Comment by Kryptoniq** [comment]
Contract address can be found at https://cannasos.com/crowdsale-ico (`0x5ebE6a342a93102393EdD9D2e458C689e5aC0bb3`).

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x5ebe6a342a93102393edd9d2e458c689e5ac0bb3, https://cannasos.com/
