### ISSUE TITLE
XYO Network token add request

### ISSUE THREAD

**Issue by LazerPotatoe** [forkdelta/tokenbase#1071]
Contract address:
0x55296f69f40ea6d20e478533c15a6b08b654e758

Issuer's official website:
https://xyo.network/

Description: 
Blockchain's first crypto-location oracle network has arrived.  Enables smart contracts to interact with the real world as if it were an API.

Official contract address confirmation: 
Click "Token" at top of main webpage above
https://get.xyo.network/token-sale-economics/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://bitcointalk.org/index.php?topic=3040825.0
2. https://www.youtube.com/watch?v=A5VlG_KbmZ8

Thanks!

**Comment by Kryptoniq** [comment]
#839
