### ISSUE TITLE
Escarce token listing

### ISSUE THREAD

**Issue by EscarceTeam** [forkdelta/tokenbase#1072]
Contract address:
0x8db8ad2888b338dc8ad715347821c24bbbcac5b0

Issuer's official website:
http://escarcecoin.com

Description:
Ethereum based token with decreasing supply (buy back and burn)

Official contract address confirmation: 0x8db8ad2888b338dc8ad715347821c24bbbcac5b0 on our website (http://escarcecoin.com)

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://bitcointalk.org/index.php?topic=2322187.0
https://twitter.com/Escarceteam

Thank you !

**Comment by Kryptoniq** [comment]
ICO only website.
Roadmap ended December 2017.
Sorry, we can't list your token.
http://escarcecoin.com/
Archive: http://archive.is/LIA7z
