### ISSUE TITLE
MTC token listing request

### ISSUE THREAD

**Issue by chessdoc** [forkdelta/tokenbase#1073]
Contract address: 0x905E337c6c8645263D3521205Aa37bf4d034e745

Issuer's official website: https://ico.dopcademic.com

Description: 
MTC is a utility token to be used on a healthcare platform. It allows patients and doctors to interchange value on the information they generate and fuels a platform that allows institutions to get anonymized blockchain saved data for statistic and investigation purposes.

Official contract address confirmation:  ICO has ended and currently we dont show the token address on the website. It can be foubnd on our telegram group though. Its almost all the time on the pinned message. https://t.me/docademicofficial

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.ccn.com/why-john-mcafee-backed-docademics-ico-it-could-possibly-be-one-of-the-best-icos-of-all-time/
2. https://u.wn.com/2018/04/11/Meet_Docademic_The_John_McAfee_Backed_ICO/

**Comment by freeatnet** [comment]
@chessdoc Thank you for your request. Please find the issues with the request below:

Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* **Press releases or sponsored articles do not constitute third-party review.**
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
