### ISSUE TITLE
IvyKoin Public Network Tokens (IVY)

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#1074]
Contract address: 0xa4ea687a2a7f29cf2dc66b39c68e4411c0d00c49

Issuer's official website: https://www.ivykoin.com/

Description: 

> ivyKoin is a cryptocurrency on the blockchain that is designed to help business transactions. It specifically aims to help those who conduct business transactions over $10,000 since they need extensive verification as part of the international monetary system. ivyKoin delivers this necessary verification via an impressive number of Know Your Customer (KYC) and Know Your Transaction (KYT) information in every payment, much more than in any existing system today.
— https://blockonomi.com/ivykoin-guide/

Official contract address confirmation: 
https://medium.com/@ivykoin/ivy-token-generation-event-tge-faqs-5171057ce944 (via official website -> blog)

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://blockonomi.com/ivykoin-guide/
2. https://www.nextcrypto.com/new-cryptocurrency-building-improvements-leading-altcoin-ripple/

**Comment by freeatnet** [comment]
@Kryptoniq I can't really review my own request, can I.

**Comment by Kryptoniq** [comment]
The information provided is confirmed to be accurate and meets ForkDelta's listing requirements. 
0xa4ea687a2a7f29cf2dc66b39c68e4411c0d00c49, https://www.ivykoin.com/
