### ISSUE TITLE
PolicyPal Network (PAL)

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#1075]
Contract address: 0xfedae5642668f8636a11987ff386bfd215f942ee

Issuer's official website: https://www.policypal.network/

Description: 

> PolicyPal Network is a new generation of an insurance company. It would provide insurance for crypto assets and P2P Mutual Aid Products for Emerging Markets.

Official contract address confirmation: 
TBD

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://icobench.com/ico/policypal-network
2. https://hackernoon.com/policypal-network-a-fintech-startup-taking-insurance-to-a-new-level-of-accessibility-974df376192d
3. https://coinmarketcap.com/currencies/policypal-network/

(Labelled "high" for having 590 ETH in volume in the past 30 days)

**Comment by Kryptoniq** [comment]
The information provided is confirmed to be accurate and meets ForkDelta's listing requirements.
0xfedae5642668f8636a11987ff386bfd215f942ee, https://www.policypal.network/
