### ISSUE TITLE
LIST BKBK TOKEN

### ISSUE THREAD

**Issue by blockbroker** [forkdelta/tokenbase#1076]
Contract address: 0x3c9eef3e8cd28576b9be44363a61af83bb81f3fc

Issuer's official website: https://blockbroker.me/

Description: Block Broker is a ground breaking new ICO broker platform set to offer investors better than market deals on ICO’s and completely eliminate ICO fraud by creating a 100% safe investment environment. Block Broker is the world’s first decentralized ICO investment platform and it is going to change the way people invest in ICO’s forever. How does the project create value to the ecosystem and differs from competing projects: Block Broker is the first of its kind. We offer a truly unique solution to not only combat ICO frauds, but also providing an easy to use ICO broker platform.

Official contract address confirmation: https://blockbroker.me/token.html

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://bitcointalk.org/index.php?topic=3337417.0
2. https://icobench.com/ico/block-broker
3. https://www.youtube.com/watch?v=MTu4xCaAl-Y

**Comment by Kryptoniq** [comment]
Project ended as a scam and is not worthy of listing.
Reference: https://bitcointalk.org/index.php?topic=3337417.220

**Comment by freeatnet** [comment]
More specifically, https://cryptovest.com/news/blockbroker-ico-pulls-exit-scam-caught-with-faked-founder-photo/
