### ISSUE TITLE
Token Listing Request NitroCoin

### ISSUE THREAD

**Issue by NitroCoinOfficial** [forkdelta/tokenbase#1077]
IMPORTANT NOTICE : 
DEAR FORK DELTA WE SORRY TO SAY THAT YOU REJECT OUR TOKEN SEVEREL TIME BECAUSE OF ACTIVITY OF OUR TEAM MEMBER WHO NAME HUMAIR  AND CREATE A GITHUB RESPO IS NOT OUR TEAM MEMBER OR NO LONGER OUR DEVELOPER WE THROUGH OUT FROM OUR PROJECT THEY REQUEST YOU TOO MANY TIMES TO LIST TOKENS AND TRYING TO SCAM WITH OUT USERS AND TOKEN HOLDERS AND ALSO WITH US AND CHANGE SOME DEVELOPERS TEAM MEMBER DETAILS FROM OUR WEBSITE WE ARE APLOLIGZE FOR THIS IS BRCAUSE OF USE NOW EVERY THING  SETUP NOW 

PLEASE GIVE US ONE CHANCE MORE TO OUR USERS AND TOKEN HOLDERS TO TRADE EXPERIENCE IN FORKDELTA WE ARE VERY THANKSFULL TO YOU PLEASE STUDY OUR CAUSE AND INFORMATION OF TOKEN .

OUR USERS ALREADY TRADING NITRO COIN (NRC) TOKEN ON FORKDELTA TO ADD CONTRACT ADREASS IN SECTION AND BUY AND SELL TOKEN YOU CAN ALSO CHECK OUR TRADING VOLUME OF OUR TOKEN BY ADDING OUR ADREASS IN YOUR EXCHANGE 

CHECK THE TRADNG VOLUME 

https://forkdelta.github.io/#!/trade/0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99-ETH

---
addr: '0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99'
decimals: 0
symbol: NRC
name: Nitrocoin

description: >-
A global platform that empowers anyone to partake in the video-games economy. First blockchain-based open economy in the world to be backed by a publicly traded company  Supported by game industry.

Third Party Forum Discussion : 
https://www.cryptotalk.org/index.php?/topic/2528-nitro-coin-ico-airdrop-bounty-reward-ethereum-based-erc20-token-for-gaming-industry/

Third party about the ICO: https://cryptorated.com/ico-listing/nitro-coin/

Smart Contract address verify & found on website is https://thenitrocoin.org/#page2
Is 0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99

links:
- Medium: https://medium.com/@thenitrocoin/nitro-coin-ico-has-been-successfully-achieve-thier-goal-a225b6cd3281
- Twitter: https://twitter.com/NitrocoinNRC
- Telegram: https://t.me/joinchat/AAAAAEh18IxJp-_TmSRV4A
- Email: support@thenitrocoin.org
- Website: http://thenitrocoin.org/
- Whitepaper: https://thenitrocoin.org/whitepaper/Nitrocoin_whitepaper.pdf

**Comment by Kryptoniq** [comment]
My comment on Issue #437:  Your co-founder "Johsan Hater" is fake. The image used is that of a Brazilian man called Rafael. Archive: https://web.archive.org/web/20180313001211/https://thenitrocoin.org/
https://www.ecenglish.com/en/social/blog/montreal/2015/06/29/rafael-pileggi-calegarini-from-brazil-my-accommodation-in-my-homestay-was-really-good 

Lies and deception is not tolerated here at ForkDelta. 
You stated that Humairk is no longer part of your team but his name is  currently on your website as a team member. Archuve: https://web.archive.org/web/20180514063144/https://thenitrocoin.org
However, your project doesn't fit to be on ForkDelta due to it being an ICO-only project without values. 
Your roadmap for 2018 is only to be listed on exchanges.  
Sorry, we can't list your token. 
Thank you. 

Spam issues 
#437, #498, #480, #382, #499 and #482.

**Comment by NitroCoinOfficial** [comment]
IMPORTANT NOTICE : 
DEAR FORK DELTA WE SORRY TO SAY THAT YOU REJECT OUR TOKEN SEVEREL TIME BECAUSE OF ACTIVITY OF OUR TEAM MEMBER WHO NAME HUMAIR  AND CREATE A GITHUB RESPO IS NOT OUR TEAM MEMBER OR NO LONGER OUR DEVELOPER WE THROUGH OUT FROM OUR PROJECT THEY REQUEST YOU TOO MANY TIMES TO LIST TOKENS AND TRYING TO SCAM WITH OUT USERS AND TOKEN HOLDERS AND ALSO WITH US AND CHANGE SOME DEVELOPERS TEAM MEMBER DETAILS FROM OUR WEBSITE WE ARE APLOLIGZE FOR THIS IS BRCAUSE OF USE NOW EVERY THING  SETUP NOW 

PLEASE GIVE US ONE CHANCE MORE TO OUR USERS AND TOKEN HOLDERS TO TRADE EXPERIENCE IN FORKDELTA WE ARE VERY THANKSFULL TO YOU PLEASE STUDY OUR CAUSE AND INFORMATION OF TOKEN .

OUR USERS ALREADY TRADING NITRO COIN (NRC) TOKEN ON FORKDELTA TO ADD CONTRACT ADREASS IN SECTION AND BUY AND SELL TOKEN YOU CAN ALSO CHECK OUR TRADING VOLUME OF OUR TOKEN BY ADDING OUR ADREASS IN YOUR EXCHANGE 


CHECK THE TRADNG VOLUME 
https://image.ibb.co/dPcKfd/NRC_Fork_Delta.png


 ERC-20 token
>>
>>https://image.ibb.co/cWhKfd/team_nrc.png
>>real team : https://thenitrocoin.org/#page7
>> addr: '0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
>> decimals: 0
>> symbol: NRC
>> name: Nitrocoin
>>
>>
>>
>> description: >-
>> A global platform that empowers anyone to partake in the video-games
>> economy. First blockchain-based open economy in the world to be backed
>> by a publicly traded company Supported by game industry.
>>
>>
>> Smart Contract address verify & found on website is
>> https://thenitrocoin.org/#page2
;
>> Is 0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
>>
>>
>> lo Website: http://thenitrocoin.org/
;
>>
>>
>>
>> Email: support@thenitrocoin.org
>>
>>
>>
>>real team : https://thenitrocoin.org/#page7
;
>>
>> bitcointalk: https://bitcointalk.org/index.php?topic=3734467
;
>>
>>
>>
>> https://image.ibb.co/iaH1nH/nitrocoin_NRC_100_X100_pixel.jpg
;
>>
>>
>>
>>
>>
>> https://image.ibb.co/geqyZx/NRC_216_X216_sezi_pixel.jpg
;
>>
>>
>>
>>
>>
>> https://image.ibb.co/fHFbMc/nitrocoin_NRC_500_X500_pixel.jpg
;
