### ISSUE TITLE
BUNZ Token Listing

### ISSUE THREAD

**Issue by NetTrafficGroup** [forkdelta/tokenbase#1079]
Contract address: https://etherscan.io/address/0x4aadeb688a85d4828c682716626e1398c18aa616

Issuer's official website: https://www.bunzola.com

Description: Bunzola is the first Proof of Stake cryptocurrency dedicated to providing Food Aid around the World. As a BUNZ token holder not only will you have helped our Food Aid Programs but you will benefit by earning some extra tokens based on minimum coin age (the min coin age is 3 days)

Official contract address confirmation: https://www.bunzola.com/#tokendistribution

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.  https://medium.com/@sagarmhatre_25716/get-5000-bunz-tokens-free-in-airdrop-fb61405c7bd7
2.  https://plus.google.com/communities/100413429762839992648

**Comment by freeatnet** [comment]
@NetTrafficGroup One link is dead, one link goes to a spammy google plus group.

Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by freeatnet** [comment]
Closing in favour of #1309.
