### ISSUE TITLE
Token listing request: TRONCLASSIC (TRXC)

### ISSUE THREAD

**Issue by TronClassic-TRXC** [forkdelta/tokenbase#1080]
**Token address:**
0xad5fe5b0b8ec8ff4565204990e4405b2da117d8e

Token Name: TronClassic

Token Symbol: TRXC

Total Supply: 1,000,000,000,000 

**Issuer's official website:**
https://www.tronclassic.xyz/

**Description:** 
TRXC is an ERC20 token that serves as a digital currency. TronClassic  is a platform for the future of trading market and online wallet .

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xad5fe5b0b8ec8ff4565204990e4405b2da117d8e

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. Twitter: https://twitter.com/TronClassic
2. facbook group: https://www.facebook.com/groups/1853017211395204/
3. Bitcointalk: https://bitcointalk.org/index.php?topic=3829331
4. Telegram: https://t.me/ClassicTron
5. whitepaper:  https://www.tronclassic.xyz/whitepaper
6. youtube: https://www.youtube.com/channel/UCOwp1XMHOiLJ-meqNS4h8HQ
7. github: https://github.com/TronClassic-TRXC
8. Reddit: https://www.reddit.com/user/TRONCLASSIC

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* **Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.**

**Comment by TronClassic-TRXC** [comment]
A link to the official contract address confirmation: 
https://etherscan.io/token/0xad5fe5b0b8ec8ff4565204990e4405b2da117d8e

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=3829331
2. https://medium.com/@sherazshafaat/tronclassic-trxc-f1c739c81d7a
3. https://steemit.com/ethereum/@sherazk/tronclassic-trxc

**Comment by TronClassic-TRXC** [comment]
Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://icoholder.com/en/tronclassic-ico-22638
2. https://foundico.com/ico/tronclassic.html
