### ISSUE TITLE
List Agent Not Needed (ANN) Token

### ISSUE THREAD

**Issue by agentnotneeded** [forkdelta/tokenbase#1082]
Contract address:
0xe0e73e8fc3a0fa161695be1d75e1bc3e558957c4

Issuer's official website:
https://www.agentnotneeded.com

Description: 
Peer to peer property platform thats allows you to buy, sell or rent a property without an agent.

Official contract address confirmation: 
https://tokensale.agentnotneeded.com/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://icobench.com/ico/agent-not-needed
2. https://t.me/agentnotneededofficial/
3.https://bitcointalk.org/index.php?topic=3106993.msg32102174#msg32102174
4.https://www.youtube.com/results?search_query=agentnotneeded
5.http://www.propertyindustryeye.com/another-new-portal-thats-open-to-all-claims-to-have-the-agents-worried/

**Comment by freeatnet** [comment]
Relevant third-party review links:
1. http://www.propertyindustryeye.com/another-new-portal-thats-open-to-all-claims-to-have-the-agents-worried/
2. https://www.youtube.com/watch?v=Pw2LPFbq-hA

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.
