### ISSUE TITLE
LIST MYCHATCOIN [MIT] TOKEN 

### ISSUE THREAD

**Issue by mychatcoin** [forkdelta/tokenbase#1083]
Contract address: 0xad8dd4c725de1d31b9e8f8d146089e9dc6882093

Issuer's official website: https://mychatcoin.com

Description: 
 Mychatcoin is new revolutionary cryptocurrency and blockchain
platform leveraging on both the gaming and socail media industries
to connect everyone on the platform to be able to play games
and communicate with one another by socialization …

Official contract address confirmation:  https://mychatcoin.com/token-details

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=3570824.0
2. https://medium.com/@mychatcoin

        OTHER LINKS
  1.  https://mychatcoin.com/whitepaper
  2. https://t.me/mychatcoin
  3. https://twitter.com/mychatcoin

**Comment by freeatnet** [comment]
@mychatcoin Please provide at least 2 links to **third-party reviews** or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
