### ISSUE TITLE
Listing request - Yolocash (YLC) Token

### ISSUE THREAD

**Issue by YOLOCASH** [forkdelta/tokenbase#1085]
Request to list YOLOCASH Token

Contract address: 0x18367f4eca68f7f374f61784ba38bcec3fee77f8

Issuer's official website: https://www.yoloworld.org/

Description: YOLOCASH Token is use for tokenizing franchising model to and cashless payment. Designed with consumer safety, security and regulatory compliance in mind.

Official contract address confirmation: https://etherscan.io/token/0x18367f4eca68f7f374f61784ba38bcec3fee77f8

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.  https://www.prlog.org/12709179-yolocash-cryptocurrency-introduces-upcoming-mobile-app-partnerships-and-more.html
2.  https://twitter.com/staffprojects/status/965376179426357248
     https://www.youtube.com/watch?v=RU0KwUFwaJ8&t=13s
     https://bitcointalk.org/index.php?topic=3872774

**Comment by kiantots13** [comment]
Yolocash

**Comment by florence143** [comment]
please,include yolocash in your list
thank you

**Comment by dos05** [comment]
Include YLC please...

**Comment by janicefernandez** [comment]
YLC the best! It deserves to be listed your exchanger. God Bless! 🙂

**Comment by shairomil** [comment]
YLC FOR THE FUTURE 😇😇

**Comment by izzarain** [comment]
please,include yolocash in your list
thank you

**Comment by dorielbergado1996** [comment]
Hey There #Github,please list yolocash.. 
There are so many supporters in different country that really love to see YoloCash to be listed..
YoloCash has great project that would help everyone experience financial freedom. It has a great Team working on the development of Yolo. And we love this project!.
To God Be The Glory!

**Comment by Johnsparc** [comment]
Looking forward to see YOLOCASH (YLC) to be listed here. Great team, great community and great members. Thanks in advance. 😊

**Comment by teguhyuda** [comment]
Yolocash good project

**Comment by kiantots13** [comment]
Pls include yolocash (YLC)

**Comment by dk16halyn** [comment]
more great awesome projects to come..

#YLC
#YOLOCASH

**Comment by nicnic785** [comment]
❤ great project. 
#Proud y0locash holder

**Comment by aljuea1003** [comment]
Please include our YOLOCASH (YLC) in your listing. A great project to look forward to.

**Comment by CaptainWOLF-05** [comment]
Great PROJECT!

**Comment by nicnic785** [comment]
Please include our YOLOCASH (YLC) in your listing. A great project to look forward to.

**Comment by Jenerose** [comment]
Please list yolocash, we have a bright future to yolo. Great project yolocash to the moon

**Comment by Rhenz7** [comment]
Yes!  Add YOLOCASH (YLC)...😃

**Comment by skie1918** [comment]
please,include yolocash in your list

**Comment by nesbee** [comment]
One of the best project  I have seen this year with a great team.. please include this project in your list.

**Comment by nimcy** [comment]
Yolocash !AWESOME DEV TEAM with AWESOME COMMUNITY !

**Comment by rongelca** [comment]
Please include or list our YOLOCASH to be part in your fast growing community....

**Comment by Kryptoniq** [comment]
Please, refrain from posting comments. This is more of spam to us because we do not make it a requirement.

**Comment by kebzjogie** [comment]
Please include YLC yolocoins to your listing...

**Comment by joeysoria1281** [comment]
Please include yolocash in your list im a yolocash lover

**Comment by ryamnery** [comment]
looking forward to list YLC... absolutely the best!

**Comment by superrich01** [comment]
Wow yolocash to the moon big big community...a very good project...

**Comment by Kryptoniq** [comment]
Locking issue for spam. Will be reopened after i review the project.

**Comment by freeatnet** [comment]
@YOLOCASH Press releases do not qualify as third-party review. Aside from that, only the [staffprojects tweet](https://twitter.com/staffprojects/status/965376179426357248) link is still up.

Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by freeatnet** [comment]
⚠️ Note to the overly excited project supporters: do not spam the comments. Your comments WILL be deleted and it may negatively affect the outcome of the review. If you must, leave an emoji reaction on the initial request to show support for the project.
