### ISSUE TITLE
Token listing request: Co2Bit (CO2Bit)

### ISSUE THREAD

**Issue by pauloprea** [forkdelta/tokenbase#1086]
Contract address: 0x574b36bced443338875d171cc377e691f7d4f887

Issuer's official website: https://co2bit.com/

Description: CO2Bit Coin is a Secure Network Based Digital Asset created to efficiently finance carbon neutral energy generation and sequestration assets while enabling global participation in the benefits to our economy.

Official contract address confirmation: https://co2bit.com/ (footer)

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
The token won't have an ICO and is traded by the professional energy renewables network. Therefore, no public announcements to gather investors support were made since no crowdfunding is needed. 
See http://co2bit.com/co2bit-whitepaper/
Contract audit: https://quantstamp.com/public-reports/0x574b36bced443338875d171cc377e691f7d4f887

**Comment by freeatnet** [comment]
Thank you for your request, @pauloprea! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
