### ISSUE TITLE
Token listing request | Mijn Vastgoed™

### ISSUE THREAD

**Issue by JMastenbroek** [forkdelta/tokenbase#1087]
**Token listing request | Mijn Vastgoed™**

Contract address:
0x3fdd90ccdb7a430dac92580170a47f278322a9a0

Issuer's official website:
https://mijnvastgoed.nl

whitepaper link (english): 
https://mijnvastgoed.nl/wp-content/uploads/english-mijnvastgoed-whitepaper.pdf

Description: 

The token issuer:
Mijn Vastgoed™ is a dutch initiative, and only focus on the dutch market. We want to make it possible for every Dutchman to invest in real estate. That is why Mijn Vastgoed is developing an online platform where individual investment properties can be divided into blockchain tokens and offered. Platform users are therefore entitled to a part of the rental income and the surplus value when the property is sold. The blockchain tokens can be purchased and traded on the online platform, enabling customers to purchase and sell their real estate investments at lightning speed.

Token's purpose. 
The financing for the development of the online platform is done through the issuance of dividend tokens. These dividend tokens entitle the owner to a dividend from the company. By acquiring funds this way, Mijn Vastgoed makes it possible for everyone to invest in the start-up. The dividend tokens must not be confused with the later blockchain tokens that make it possible to invest in an investment property on the online platform.

Official contract address confirmation: 
The contract address can be found on in the footer of the website. Bottom left on https://mijnvastgoed.nl

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
We have specifically chosen to focus on the Dutch market and investors. For that reason we are not involved in ICO rating websites. We have recently started a reddit and a bitcointalk page. The developers of the TRIA token, which you have already listed, are involved in this project. 

As a Bitcointalk user stated: ' 
 "Mijn Vastgoed is a Dutch initiative, and it focuses only on the Dutch market." We want everyone to invest in real estate. " I believe that it is right to focus on the specific market of a particular country. This indicates the seriousness of intentions.

1. https://bitcointalk.org/index.php?topic=3830225.0
2. https://www.reddit.com/r/MijnVastgoed/
3. http://www.tradingcrypto.eu/blockchain/de-token-sale-van-mijn-vastgoed/
4. https://nl.cryptonews.com/news/investeren-in-vastgoed-met-revolutionair-blockchain-initiati-1399.htm

CEO Mijn Vastgoed
https://www.linkedin.com/in/hanjo-mastenbroek-4967b215a/

J. Mastenbroek

**Comment by freeatnet** [comment]
Thank you for your request, @JMastenbroek! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
