### ISSUE TITLE
Etheera (ETA) Token listing request 

### ISSUE THREAD

**Issue by Etheera** [forkdelta/tokenbase#1089]
Contract address: 0x9195E00402abe385f2D00A32Af40b271F2e87925

Official website: 
https://www.etheera.com

Description: 
First decentral global Real Estate Portal with All in One Software solution for the Agents.

Official contract address confirmation: 
Go to Etheera Mainsite www.etheera.com then click the ICO tab , the white Token Contract Link Button will confirm the etherscan link and address.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://www.trackico.io/ico/etheera/#rating
http://www.digitaljournal.com/pr/3616033
https://youtu.be/WVe94WV5y20
https://youtu.be/lY68eSsG4WE
https://youtu.be/Oza3yrA2VR4

ICO End: June 3rd 2018
Current ICO Price: 1 ETA = 0.000002 ETH

Availble Market on Exchange Start:
ETA tokens will be send on ICO end to all last phase Investors + to over 3k active bounty participants waiting to start sell and trade Etheera.

contact: support@etheera.com
Responsible / CEO: Alexandar Bojat

Thank you
Etheera

**Comment by Etheera** [comment]
Update: Agreement done. We are guaranted listed after ICO at Top 35 ranked exchange in coinmarketcap ''Exrates''

Please announce and let Etheera be a part of ForkDelta too.

Thank you

**Comment by freeatnet** [comment]
Thank you for your request, @Etheera! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Etheera** [comment]
Thank you for the update team.

**Comment by Etheera** [comment]
Dear Team,

Here some External third party reviews weve found:

https://thetechinsider.org/cryptocurrencies/etheera-ico-review-real-estate-decentralized/
https://medium.com/@creg.john2055/etheera-e050c3cc47bc
https://www.youtube.com/watch?v=q1cS_-IEJLY&t=41s
https://www.youtube.com/watch?v=Oza3yrA2VR4
https://www.youtube.com/watch?v=lY68eSsG4WE&t=51s

Thank you

**Comment by Etheera** [comment]
Hello team, any news about the listing?

Thank you

Etheera

**Comment by Etheera** [comment]
@therealMikkoK 

Hy Mikko :-)

Our Token distribution just happened and people started to create orderbooks and trades at https://forkdelta.app/#!/trade/0x9195e00402abe385f2d00a32af40b271f2e87925-ETH

I hope we can speed up with listing as we are in review since June 23, 2 months ago now.

Thank you very much in advance if that is possible :-)

Alexandar

**Comment by Etheera** [comment]
Hello @Kryptoniq @therealMikkoK 

We are now joined the Market Index at Coingecko https://www.coingecko.com/en/price_charts/etheera/eth

And are listed at TokenJar. Exchanges as DDEX and others will come live in teh next days.

As we see a great amount of orderbooks and trades on adresstrading at f^Forkdelta we would apprciate it to get officially live a as soon as we can :-)

Thank you
Etheera

**Comment by therealMikkoK** [comment]
@Etheera 
Hello,
I tried, but didn't manage to find the smart contract address on your website?
I did notice your TG group had mentions of a new contract address, from Feb. - March, so it is important to see the address on your website.
First glance at WP, no immediate red flags to me.
@bobbypaintsstuf

**Comment by Etheera** [comment]
Hello @therealMikkoK 

Thank you for the answer. the Smart Contract is since ever on our website www.etheera.com. Please click in the menu tab on top ''ICO'' and then you will find a button labeled ''SMART CONTRACT' which is directly link and open a new tab to our Etherscan adress 0x9195E00402abe385f2D00A32Af40b271F2e87925 but the adress is also written visible now in that section.

Thank you
Etheera

**Comment by therealMikkoK** [comment]
> Dear Team,
> 
> Here some External third party reviews weve found:
> 
> https://thetechinsider.org/cryptocurrencies/etheera-ico-review-real-estate-decentralized/
> https://medium.com/@creg.john2055/etheera-e050c3cc47bc
> https://www.youtube.com/watch?v=q1cS_-IEJLY&t=41s
> https://www.youtube.com/watch?v=Oza3yrA2VR4
> https://www.youtube.com/watch?v=lY68eSsG4WE&t=51s
> 
> Thank you

Hello again,
As @freeatnet stated, it is preferable that a credible outside party does analysis on the token.
I'm sure you wouldn't like to find out there's a flaw in your program, that causes the sending of your token to fail - or anything similar.

**Comment by Etheera** [comment]
Dear @freeatnet @therealMikkoK 

We understand your points and just like to share one feedback from ourself now. ETA Token will be as utility token usuable when software for the agents is programmed and has right now as we are not yet in that steps of DEV not that use. But regarding you as exchange like the other is ETA fully functional and works pretty fine, we have already tons of transaction even on your own exchange Forkdelta without beeing listed officially yet, see here https://forkdelta.app/#!/trade/0x9195e00402abe385f2d00a32af40b271f2e87925-ETH

and then we are also officially listed on TokenJar and Token Store which are exchanges listed in coingecko and coincap as you are.

TokenJar:
https://tokenjar.io/ETA

Token Store:
https://token.store/ETA

Token Store we just entered today and are live and officially announced and with both exchanges also synced to etherscan blockchain.

In that case we think there is no discuss needed regarding anything that can fail with ETA Token as trade, approve, deposit and withdraw functions all working very fine on DEX as Forkdelta is.

Can we agree on that point and close this open question or do you still need anything else?

Thank you
Etheera

**Comment by Etheera** [comment]
Dear @therealMikkoK @freeatnet 

Any update as no news since last 19 days and now 6 months in listing process already. We are unhappy to be open seeing you listed 10 new token that made requests months after us and are now up and we see trades are going on https://beta.forkdelta.app/#!/trade/0x9195e00402abe385f2d00a32af40b271f2e87925-ETH

I really hope we join you pretty soon as our community is also asking what happened with ETA at Forkdelta.

Thank you Guys
Alexandar

**Comment by Etheera** [comment]
Dear @therealMikkoK @freeatnet 

Etheera (ETA) is now listed at CMC https://coinmarketcap.com/currencies/etheera

Best
Etheera Team

**Comment by freeatnet** [comment]
> Etheera appears to be an ICO scam – or, at the very least, a dumb investment. The company has no product – not even an MVP or beta – available to the public. Despite the complete lack of any product or service, the company is launching a token sale with a ridiculous hard cap of $116 million USD.

— https://bitcoinexchangeguide.com/etheera-eta-ico/

**Comment by freeatnet** [comment]
Beyond that, the market trading by direct contract appears to be wash trading, with buyer and seller most frequently the same:

* https://etherscan.io/tx/0x1413b7b7cfd13c26ff459575d6795819ed9db456f5392bdccda55307c5cb813b#eventlog
* https://etherscan.io/tx/0x812a86394974818b49390240230585a52743c9e11599d00ba3f2a2d776d40332#eventlog
* https://etherscan.io/tx/0xda15992bdf04940e5a49744ecc3b917e23d86fa9ebf5cedee4eb09e2edaa6ff8#eventlog
* https://etherscan.io/tx/0xfbd8ce3a9d754c9ebe07af9025d32b9eeb032217452ca64019f7840f210159e6#eventlog
* https://etherscan.io/tx/0xb00032364c9a07667b49dc22b69cdda5189d550df30c7b33c3fbaf3d87e9bebd#eventlog
* & more

**Comment by onyamom** [comment]
whatever happened to being listed on forkdelta? i guess etheera couldn't prove they're innocence hence no listing
