### ISSUE TITLE
Horizon Communication

### ISSUE THREAD

**Issue by Kayeshlyn** [forkdelta/tokenbase#1090]
Token address: 0x19202b12bF9735DB1350C0110A71F2d70cD4cb7B

Issuer's official website: https://horizoncomm.co/

Description:  Horizon Communications is an upcoming fixed wireless internet and cellular service provider looking to provide services in Bermuda, the Caribbean, and Central America before expanding internationally. 

While utilizing 4th generation and soon 5th generation wireless technology, it will also heavily incorporate blockchain and cryptocurrency technology, one of the 1st ISP’s in the world to do so and the 1st to tokenize their services using an Initial Coin Offering (ICO).

The Horizon token is a unique, new Ethereum based token build on the blockchain. It is designed to be used to access services, and service discounts within the Horizon ecosystem.

Our service offering will include Internet speeds of up to 150 Mbps in 2018 and 300 Mbps and faster in late 2018/2019.

A link to the official contract address confirmation: https://etherscan.io/address/0x19202b12bF9735DB1350C0110A71F2d70cD4cb7B

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=2960817.0
2. https://icoholder.com/en/horizon-communications-19242

**Comment by Kayeshlyn** [comment]
You can reach us via email,
contact@horizoncomm.co

**Comment by Kayeshlyn** [comment]
@Kryptoniq Hello, any updates?

**Comment by freeatnet** [comment]
Thank you for your request, @Kayeshlyn! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.
