### ISSUE TITLE
Icoin

### ISSUE THREAD

**Issue by ArieNR** [forkdelta/tokenbase#1092]
late, see required items and comments . Please follow it if you are requesting a token listing.
Token listing guide: https://www.reddit.com/r/ForkDelta/comments/7tntnz/how_to_get_an_erc20_token_listed_on_forkdelta/
Got questions? Join Discord chat: https://discord.gg/mMnRq7m

If you are not requesting a token listing, feel free to delete this template
-->

Contract address: 0x648C66A11A7EF4e1A64BE7A92625b8A08eb8D202

Issuer's official website: https://icoin.com

Description:  Promotion & reference ICO listing

Official contract address confirmation: https://etherscan.io/address/0x648c66a11a7ef4e1a64be7a92625b8a08eb8d202 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.  https://t.me/icoincomm
2.  https://facebook.com/ICOIN-Listing-363750657469587
3. https://t.me/icoinofficial
4. https://mobile.twitter.com/IcoinCommunity

**Comment by ArieNR** [comment]
Done

**Comment by Kryptoniq** [comment]
1. Provide link to your website.
2. Provide links to atleast 2 third-party reviews or discussion of your project.

**Comment by ArieNR** [comment]
Update
