### ISSUE TITLE
Token Listing Request - VIX Coin

### ISSUE THREAD

**Issue by ethereumbroker** [forkdelta/tokenbase#1095]
**Token listing request | Ethereum Broker - VIX Coin**

VIX Coin is an utility token needed to pay Ethereum Broker product/services:

**Contract address:**
https://etherscan.io/token/0xb45893bd77830bec7c305aded041bd74f0343bd1

**Issuer's official website:**
https://ethereum.broker

**Exchange Integrator:**
https://market.ethereum.broker
user:partner@ethereum.broker
password:test

**Play Store App:**
https://play.google.com/store/apps/details?id=com.ethereum.broker

**Whitepaper link:**
https://ethereum.broker/Whitepaper_VIXcoins.pdf

**Social media profiles:**
Our website community is made up of over 3.000 subscribers. 
https://twitter.com/EthereumBroker
https://facebook.com/EthereumBroker
https://t.me/ethereumbroker

**Links to third-party reviews:**
Airdrop Alerts review:
https://www.youtube.com/watch?v=0Q1YOU5hib4
https://www.youtube.com/watch?v=p0Tc4mQ8voE
Bitcointalk:
https://bitcointalk.org/index.php?topic=2892687

**Founders:**
**Albert Domingo**
PhD MIT Telecommunication Engineering.
https://www.linkedin.com/in/albertdomingovilar/
**Sergio Medrano**
Blockchain Developer
https://www.linkedin.com/in/sergiomedranoguillaumon/

**contact:** 
partner@ethereum.broker

**Comment by freeatnet** [comment]
Thank you for your request, @ethereumbroker! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically, your initial request should not include unnecessary information like social media links, links to individual team members, etc. (this information should be publicly available on your website).

**Comment by ethereumbroker** [comment]
**Token address:**

https://etherscan.io/token/0xb45893bd77830bec7c305aded041bd74f0343bd1

**Issuer's official website:**

https://ethereum.broker

**Description:** 

VIX Coin is an utility token needed to pay Ethereum Broker products: Exchanges integrator, https://market.ethereum.broker, and Worldcup crypto trading.

**A link to the official contract address confirmation:** 
In home, VIX Coin block, below "Traded on"

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://www.youtube.com/watch?v=0Q1YOU5hib4
https://www.youtube.com/watch?v=p0Tc4mQ8voE
