### ISSUE TITLE
CargoCoin listing

### ISSUE THREAD

**Issue by thecargocoin** [forkdelta/tokenbase#1097]
**Token address:** 0xf49cdd50ad408d387d611f88a647179c3de3492b

**Issuer's official website:** https://thecargocoin.com

**Description:** CargoCoin is designed to be a smart contract, crypto currency platform, decentralising global trade and transport. The platform target is to facilitate and optimise the interaction amongst traders, freight forwarders, shipping lines, booking agents as well as all other parties involved in the international trade and transport of commodities and cargoes. The platform users experience outlines well-balanced ecosystem based on cutting edge crypto security and frictionless interaction. 

**A link to the official contract address confirmation:** https://thecargocoin.com

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://u.wn.com/2018/06/13/Blockchain_solution_for_the_global_transport_industry/
2. https://bitcoinexchangeguide.com/cargocoin-ico-crgo-token/
3. https://cryptoradar.org/thecargocoin-ico-launches-breakthrough-technology-transport-industry/
4. https://cryptocoin.news/icos/cargocoin-ico-review-decentralized-blockchain-platform-smart-contract-to-optimize-the-transport-industry-worldwide-10170/
5. https://cryptocentral.io/blockchain-solution-for-the-global-transport-industry/
6. https://steemit.com/cargocoin/@ukg/cargocoin-a-globat-trade-and-transportation-industry-disrupter
7. http://ftreporter.com/cargocoin-the-shipping-industry-game-changer/
8. https://cryptocoinpravda.com/cargocoin-crgo-token-ico-review-for-smart-investors-2.html
9. https://www.sankeibiz.jp/business/news/180525/prl1805251033027-n1.htm
10. https://coininfo.news/interview-with-bogomil-alexandrov-co-founder-and-lead-developer-of-cargocoin/
11. https://golos.io/ico/@brainerdpaul/cargocoin-ico-review

**Comment by freeatnet** [comment]
Thank you for your request, @thecargocoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically, your initial request must follow the format; additional links like social links or tracker links are not needed.

**Comment by thecargocoin** [comment]
The request has been updated according to your format. Sorry for the misrepresentation.

**Comment by freeatnet** [comment]
@thecargocoin Please clean up your links list. Here's the guidelines:

Provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews **must have original third-party research and include review of project vision, team, milestones, or existing product**.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* **Press releases or sponsored articles do not constitute third-party review.**
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by thecargocoin** [comment]
Links updated! Hope the list is of better quality now?
