### ISSUE TITLE
Request to list Carbon Dollar X (CDX) on ForkDelta

### ISSUE THREAD

**Issue by carbondollarx** [forkdelta/tokenbase#1099]
Dear ForkDelta Team,

we would like for our ERC20 Token to be listed on the ForkDelta Exchange.

1. Contract Address: 0x2cb101d7da0ebaa57d3f2fef46d7ffb7bb64592b
2. Website: https://www.carbondollarx.com
3. Description: Carbon Dollar X is a 100% asset-backed cryptocurrency, as is the ERC20 token (CDX) representing it during its development. With the initial hard asset value and carbon credits deriving from an old-growth standing forest in Fiji, Carbon Dollar X is initiating the first cryptocurrency that will be fully backed by hard assets and carbon credits. Once its cryptocurrency and blockchain are deployed, CDX token holders will exchange their CDX tokens for live Carbon Dollar X cryptocurrency, which may be exchanged for any other global currency or held on to for investment or everyday use.
4. Confirmation link: https://www.carbondollarx.com/tokeninfo/
5. Media links: (1) http://www.abnnewswire.net/press/en/93012/The-Lopez-Group-is-pleased-to-present-Carbon-Dollar-X-93012.html
(2) http://www.4-traders.com/news/The-Lopez-Group-is-pleased-to-present-Carbon-Dollar-X--26467795/
(3) https://youtu.be/0FjGaNZ5pLE

You can contact us via info@carbondollarx.com if any additional information is necessary.

Thank you.

**Comment by freeatnet** [comment]
Thank you for your request, @carbondollarx! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
@carbondollarx Please see criteria not fulfilled by the current request highlighted in bold below:

Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. **Reviews must have original third-party research** and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* **Press releases do not constitute third-party review.**
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
