### ISSUE TITLE
LISTING REQUEST: GASFILES

### ISSUE THREAD

**Issue by gasfiles** [forkdelta/tokenbase#110]
TICKER: GAS

NAME: Gas Files

TOKEN ADDRESS: 0x75c79b88face8892e7043797570c390bc2db52a7

CONTRACT ADDRESS: 0xa54a1b3a6203cef877b759b64c6d205421e9f86c

A link to an official page confirming the contract address: https://etherscan.io/address/0xa54a1b3a6203cef877b759b64c6d205421e9f86c

DECIMALS: 8

A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2814987.0

A link to the token issuer's official website: https://www.gasfiles.com

Whitepaper: https://www.gasfiles.com/wp.pdf

Email: admin@gasfiles.com

**Comment by JonathonDunford** [comment]
@gasfiles 

Please provide a link to something on your site that verifies the token address.
Also, please provide a short description of 1-3 sentences.

Once we get you listed, you may want to consider your exchanges links to point to us 😋

**Comment by gasfiles** [comment]
Link to token address: https://www.gasfiles.com/token.php

Description:
GAS is an ERC20 token used for the Gas Files decentralized file storage
platform. Gas Files offers privacy, security and a truly unlimited file
storage solution!

I have already linked you guys to our exchanges list to our site!

Thanks

**Comment by JonathonDunford** [comment]
0x75c79b88face8892e7043797570c390bc2db52a7 verified.

**Comment by JonathonDunford** [comment]
I am going to make your ticker GASF to avoid confusion with NEO / GAS

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
