### ISSUE TITLE
2GB - 2Gether Bounty Token - listing request

### ISSUE THREAD

**Issue by caa1982** [forkdelta/tokenbase#1102]
2Gether Bounty Token (2GB)
Website: https://www.2gether.global/

Links:
Email: info@2gether.global
Twitter: https://twitter.com/2gether_global
Facebook: https://www.facebook.com/2gether-480056032377263/
Telegram: https://t.me/community2gether
Website: https://www.2gether.global/
Name: 2GetherBounty 
Symbol: 2GB
Contract Address: 0x0bd344cade9a06d1798140023f56fb0f56d48afe
Decimals: 18

Description:
2Gether - The First Collaborative Bank
we are a global collaborative economic platform based on blockchain, AI, NLP, big data and machine learning. Read all about us here: https://2gether.global/. 

We enable:
Smart Liquidity Banking — every day banking in order to demonstrate that we can build a fully functioning bank with nascent technologies

Smart Contextual Banking — a financial marketplace from worldwide providers that allow you to get the best contextual (when you need it, where you need it) personalized product 

Smart Tokenization banking — to create a completely new financial system based on real assets that extend beyond FIAT Currencies.

Thanks

**Comment by IIyanam** [comment]
This is an excellent project. One of the few that actually see a problem and provide a solution and their progress is equally amazing. They should definitely get listed.. Fork delta would be a good stepping stone to the wonderful project.

**Comment by natgit555** [comment]
This is an amazing project. Their progress in reaching goals is impressive, and their goals represent a real transition in achieving a collaborative global economic platform.  Request Fork Delta add as a way for the community to support this project.

**Comment by Kryptoniq** [comment]
Please provide links to atleast two third-party reviews or discussion of your project.

**Comment by natgit555** [comment]
Please see some sources below that include third party review or discussion on the project. Thanks.

[https://bithub.pl/english/sundayinterview-foundations-for-the-new-banking/](url)

[https://www.bigdataspain.org/2017/talk/more-people-less-banking-blockchain/](url)

[https://www.bigdataspain.org/2017/talk/scaling-a-backend-for-a-big-data-and-blockchain-environment/](url)

[https://www.elespanol.com/economia/empresas/20180528/fintech-unconference-premia-mejores-startups-sector/310719090_0.html](url)

[https://www.criptonoticias.com/eventos/spanish-fintech-awards-premio-mejor-espana-tecnologias-financieras-blockchain/](url)

[https://mobilebusinessinsights.com/2017/12/top-7-financial-technology-predictions-for-2018-what-to-watch-for/](url)

**Comment by natgit555** [comment]
Hello, I have added appropriate hyperlinks as a comment. 
Thanks
Nathan

**Comment by natgit555** [comment]
Is this back under review now since missing information was linked? Thanks.

**Comment by caa1982** [comment]
one more source from Cinco Días

https://cincodias.elpais.com/cincodias/2018/06/15/companias/1529087433_052548.html
