### ISSUE TITLE
scam coin do not need to add

### ISSUE THREAD

**Issue by sawamawa** [forkdelta/tokenbase#1103]
scam coin aidcoin

**Comment by sawamawa** [comment]
1 | Ethfinex | AID/USD |
2 | Ethfinex | AID/BTC |
3 | Bancor Network | AID/BNT |
4 | Ethfinex AID/ETH

**Comment by sawamawa** [comment]
new exchange
IDEX

**Comment by freeatnet** [comment]
Thank you for your request, @sawamawa! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
@sawamawa Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by freeatnet** [comment]
Alright then.
