### ISSUE TITLE
HederaHashGraph

### ISSUE THREAD

**Issue by LegendaryBo** [forkdelta/tokenbase#1104]
The Hedera hashgraph platform provides a new form of distributed consensus; a way for people who don't know or trust each other to securely collaborate and transact online without the need for a trusted intermediary. The platform is lightning fast, secure, and fair, and, unlike some blockchain-based platforms, doesn’t require compute-heavy proof-of-work. Hedera enables and empowers developers to build an entirely new class of distributed applications never before possible.

Contract Address: 
0x549E31C12FC770a0d44ED4a003e7e3e1eB3C4831

**Comment by Kryptoniq** [comment]
Scam.
