### ISSUE TITLE
CAS - Casino Coin Token - listing request

### ISSUE THREAD

**Issue by ilvikingo** [forkdelta/tokenbase#1105]
**1. Contract address**: 0xbb1b3e8ddded8165d58b0c192d19cd360682b170
**2. Link to the official website**: http://www.casinocoin.it/
**3. Description**: Casino Coin is the smartest way to join online and live casinos. A Vip Store for players all around the world. You and Your money will be safier.
**4. Decimals**: 2
**5. Name**: Casino
**6. Symbol**: CAS
**7. Links to third-party reviews**:

- http://www.ilsole24ore.com/art/finanza-e-mercati/2018-02-07/criptovalute-selezione-darwiniana-vista-ecco-cosa-puo-accadere-180236.shtml?uuid=AEVxZ8vD

- http://www.monetavirtuale.info/etheruem/casino/casino-cas-il-token-di-ethereum-per-giocare-live-e-online/

**More Info:** 
- Email: info@casinocoin.it
- Telegram: https://telegram.me/CASINO_CAS
- Twitter: https://twitter.com/coin_casino
- Website: http://www.casinocoin.it/
- Whitepaper: http://www.casinocoin.it/whitepaper/

**Comment by freeatnet** [comment]
Thank you for your request, @ilvikingo! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
@ilvikingo The [first link](http://www.ilsole24ore.com/art/finanza-e-mercati/2018-02-07/criptovalute-selezione-darwiniana-vista-ecco-cosa-puo-accadere-180236.shtml?uuid=AEVxZ8vD), just barely makes a mention of a _Casinocoin_

> Bitcoin is the most significant example (alone it is worth 35% of the entire market) but it is not the only actor in the field. In the remaining 65% there is a bit of everything. There are objectively curious names like Sharkcoin (shark coin), PinkDog (pink dog), Casinocoin and even Ponzicoin.
> _(translated by Google Translate)_

The [second link](http://www.monetavirtuale.info/etheruem/casino/casino-cas-il-token-di-ethereum-per-giocare-live-e-online/) does not contain significant research into the project, either, aside from sounding approving of the project.

Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases do not constitute third-party review.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
