### ISSUE TITLE
Adding new token - COIN

### ISSUE THREAD

**Issue by ogrudko** [forkdelta/tokenbase#1106]
1. The contract address - 0x5e8f855966d638135a968861e80dda722291b06d 
2. A link to the token issuer's official website. - https://coinve.st.
3. Token's description: Coinvest is decentralized investment trading market for cryptocurrencies, where you can invest in cryptocurrencies and index funds with just one wallet and one token (COIN).
4. A link to an official page confirming the above contract address: this needs to be on the official domain of the token issuer: https://coinve.st/ - "Token details" section
5. Links to third-party reviews:
- https://foxico.io/project/coinvest
- http://www.kryptovergleich.org/ico/coinvest-ico/
- https://www.trackico.io/ico/coinvest/
- http://www.the-blockchain.com/2017/11/06/coinvest-aims-disrupt-cryptocurrency-investing-worlds-first-decentralized-stock-market-cryptonized-assets/
- https://blokt.com/icos/coinvest
- https://www.ccn.com/coinvest-project-microsoft-employees-announces-ico/
- https://www.youtube.com/watch?v=ZaJ2DHbvVac&t=2s
- https://bitsify.net/ico-list/coinvest-ico-report-decentralised-investment-platform/

**Comment by freeatnet** [comment]
Thank you for your request, @ogrudko! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Relevant reviews:
1. https://hacked.com/ico-analysis-coinvest/
2. https://bitcoinexchangeguide.com/coinvest/
3. http://www.the-blockchain.com/2017/11/06/coinvest-aims-disrupt-cryptocurrency-investing-worlds-first-decentralized-stock-market-cryptonized-assets/

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.

--
NOTE: contract address has changed to 0xe725ec30f2019771d4dabfa09890fc264ce79a8d. See [swap guide](https://docs.google.com/document/d/1CotMPhK26RSkzpz8LYr-n9jxemEYdNh980VUoPQQhFg/edit) as linked from the website header.

0xe725ec30f2019771d4dabfa09890fc264ce79a8d,https://coinve.st/
