### ISSUE TITLE
New/old token listing: Blocktrade (FKA Hedge)

### ISSUE THREAD

**Issue by kdekleva** [forkdelta/tokenbase#1107]
Dear Forkdelta team,

Blocktrade (FKA Hedge) is a soon to be launched crypto exchange, focusing on regulatory compliance (MiFID II), technical robustness and security. Our token, BTT, will be used for fees within the platform. Think BNB and similar. 

We rebranded a while back from Hedge, which was the name we used since the ICO in Sept till March. The concept is the same, as well as the people behind it. HDG was also trading on EF/FD.

We are in the process of token distribution. Though it hasnt yet finished, there are already standing limit orders.

Contract address 0xFA456Cf55250A839088b27EE32A424d7DAcB54Ff
https://blocktrade.com/; https://hedge-crypto.com/
Link for confirmation of the address: please go to hedge-crypto.com. On the sidebar select telegram channel, join the group and see the pinned msg. Link to official telegram: https://t.me/joinchat/F5fglQ7DVPV2wi4JK8Mw9A
Reviews:
https://twitter.com/BCloudUK/status/989829346163609600
https://twitter.com/AltcoinBubba/status/989723604211281920
There are plenty of Hedge Token reviews: 
https://crushcrypto.com/crusher-of-the-month-hedge-november-2017/

Should you have questions, contact me on kristjan.dekleva@blocktrade.com

Best,
Kristjan

**Comment by freeatnet** [comment]
Thank you for your request, @kdekleva! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
