### ISSUE TITLE
Requesting to be listed: Caviar

### ISSUE THREAD

**Issue by Zuizzi** [forkdelta/tokenbase#1108]
Hello, the the token information is the following:

1. Token information: 
Contract address: 0xf8e6bacd9298df8b0aba67ef2ef8348fabc5ae8a
Token Symbol: CAV
Decimals: 18

2. A link to the token issuer's official website: https://www.caviar.io

3. Token's description (issuer): "Caviar seeks to reduce investment volatility  (“beta”) while capturing higher than average rates of return (“alpha”). Caviar will achieve these goals by combining investments in fast-appreciating crypto-assets with income-generating short-term loans, backed by real estate."

3. Token's description (token role): "Profit Sharing -  Our token holders receive 75% of quarterly profits via smart contract."

A link to an official page confirming the above contract address: https://news.caviar.io/how-to-add-cav-tokens-665c737d64b4

Links to third-party reviews or discussion of the token: https://cryptosis.io/caviar-ico-review/, https://www.cryptpool.net/caviar-io-ico-review/, https://youtu.be/SU8hnEx3SrY, https://youtu.be/PyFG97asThs

Thank you for consideration.
Disclamer: Not a member of a team, just a community member.

**Comment by freeatnet** [comment]
Thank you for your request, @Zuizzi! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Zuizzi** [comment]
Thank you for the update, looking forward to review!

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xf8e6bacd9298df8b0aba67ef2ef8348fabc5ae8a, https://www.caviar.io/

**Comment by Zuizzi** [comment]
Hello, any new information about the listing? Thank you! :)
