### ISSUE TITLE
Duplicate Symbol/Ticker - BTA

### ISSUE THREAD

**Issue by BTA-BATA** [forkdelta/tokenbase#1109]
Please note that you have listed a token with am identical ticker to Bata (BTA)

https://coinmarketcap.com/currencies/bata/

The market listed on ForkDelta is appearing on:

https://www.coingecko.com/en/coins/bata/trading_exchanges#panel

Regards,
Peter Caruana
Bata Foundation Limited

**Comment by freeatnet** [comment]
Resolved.
