### ISSUE TITLE
Token Listing Request: (MMA)

### ISSUE THREAD

**Issue by etherbeats** [forkdelta/tokenbase#111]
Contract Address: [0x40B04166871D9956F5f261d76d349dA8d07f82C3](https://etherscan.io/address/0x40b04166871d9956f5f261d76d349da8d07f82c3)
Official Website: [mmasportstech.com](mmasportstech.com)
Verification of Contract Address: [mmasportstech.com](mmasportstech.com)(Shown on the homepage under the ABOUT US, MEDIA, and FAQs sections.)
Forum Discussion: https://bitcointalk.org/index.php?topic=2685920.0
Twitter: https://twitter.com/MMASportsTech?lang=en
Telegram: https://t.me/mmasportstech

**Comment by JonathonDunford** [comment]
Duplicate #54
