### ISSUE TITLE
LIST JOINT VENTURES [JOINT] TOKEN

### ISSUE THREAD

**Issue by EmreJoint** [forkdelta/tokenbase#1110]
**Token address:** 0x347C099f110Ca6761779329D2879957b606b6aCE

**Issuer's official website:** https://jointventures.io/

**Description:** 
Joint Ventures is building blockchain applications for leading online publishers. Our aim is to create an economy for online publishers that rewards every participant of the network, including authors, commenters and advertisers alike, and minimize third-party commissions. 

**A link to the official contract address confirmation:** 
https://medium.com/jointventures/how-to-participate-in-joints-ico-13d99e46612c

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=2940988.0
2. https://hacked.com/ico-analysis-joint-ventures/
3. https://www.wamda.com/2018/04/blockchain-improve-profitability-online-ads-turkish-startup-kicking
4. https://cryptovest.com/news/joint-ventures-builds-platform-uniting-commentators-publishers-and-advertisers/
5. https://thecoinshark.net/joint-venture-a-revolution-in-the-sphere-of-the-content-creating
6. https://bitcoinexchangeguide.com/joint-ventures-joint-ico/
7. https://www.icotokennews.com/icos/jointventures/

**Comment by freeatnet** [comment]
Marked as high priority because of trusted review source: "hacked.com".

NB: make sure trusted source review refers to the project requested.

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.

0x347C099f110Ca6761779329D2879957b606b6aCE,https://jointventures.io/
