### ISSUE TITLE
HELP token listing

### ISSUE THREAD

**Issue by batrinuvlad** [forkdelta/tokenbase#1111]
**Token address**: 0xbBc2045D335Cb224228f1850b29173d9d7D7b989

**Issuer's official website**: https://gohelpfund.com

**Token Symbol**: HELP

**Description**: GoHelpFund is a distributed platform powered by the Amazon Web Services infrastructure and Ethereum’s network which empowers people to:
 
- Donate for various charitable causes ranging from poverty to terrorism prevention, being focused on the concept of fundraising.
- Use the HELP token as the main currency for transactions, thus allowing increased growth and scalability with instant transfers compared to traditional currency.
Blockchain will be used in our donation system in order to provide transparency. Users will know where the money goes and they will be motivated to donate for humanitarian causes, having confidence that the money will not end up in the wrong hands.

**Token description**: Our ERC20 token will be used as the main currency of the platform. Users can donate via other cryptocurrency or FIAT, which will be converted to HELP token. It will be a core component of our Third Parties Hybrid API (Public + Private) in which we provide data to governments for tax deduction purposes, to developers for third party applications and to social media for social integration.

**A link to the official contract address confirmation**:  https://gohelpfund.com -> On front page, in the right area, under "Purchase HELP Tokens" and token sale statistics

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer**: 
1. https://w12.io/project-card/go-help-fund/ (check the comments)
2. https://icobench.com/ico/gohelpfund (third party research which includes review of project vision, and team )
3. https://startupcafe.ro/idei-si-antreprenori/programator-roman-startup-finantare-criptomonede.htm (Romanian article written by a news publication)
4. https://icomarks.com/ico/gohelpfund (third party research which includes review of project vision, and team )
5. https://icoholder.com/en/gohelpfund-17275 (third party research which includes review of project vision, and team )
6. https://www.youtube.com/watch?v=0p6AqhIl7pE 
7. https://www.youtube.com/watch?v=EDv-M7Go92o
8. https://www.youtube.com/watch?v=9VDqNDGNosA

**Comment by freeatnet** [comment]
@batrinuvlad Please see criteria not currently fulfilled by the request:

Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. **Reviews must have original third-party research** and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* **Press releases and sponsored articles do not constitute third-party review.**
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by batrinuvlad** [comment]
@freeatnet Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://startupcafe.ro/idei-si-antreprenori/programator-roman-startup-finantare-criptomonede.htm
