### ISSUE TITLE
The Holy Roger Token

### ISSUE THREAD

**Issue by Fiat2LTC** [forkdelta/tokenbase#1114]
**Token address:** 0x2ef0cf493eb5fa9bc41938ca9bb892fe7e9b7b76

**Issuer's official website:** https://theholyroger.com/

**Description:** The Holy Roger Token (ROGER) is 100% a Roger. It promises absolutely to guarantee you no returns. We are united against The Fake Roger to uncover all Rogers in crypto!

**A link to the official contract address confirmation:** https://theholyroger.com/Rogers:The_Holy_Roger_Token

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://twitter.com/TheHolyRoger
https://twitter.com/ecurrencyhodler/status/997180770195197952
https://twitter.com/Fiat2LTC/status/997533448230375424

**Comment by Kryptoniq** [comment]
Meme token qouta is filled up ATM.
We can't list your token at at this time.
