### ISSUE TITLE
List the pm7 token

### ISSUE THREAD

**Issue by oliver159** [forkdelta/tokenbase#1115]
1 The contract address.
0x75d77c58068ff812da4b59c3d6b9ab1689983f0d
2 A link to the token issuer's official website.
https://pm7.com/
3 1-3 sentences for the token's description: at least one on the token issuer (eg., the product they are building) and one on token role.
This innovative affiliate marketing platform promises to revolutionize the concept of advertising for online and offline projects, connecting the creators of the project directly with their clients, with no space for advertising, marketing and public relations agencies as intermediaries.
4 A link to an official page confirming the above contract address: this needs to be on the official domain of the token issuer.
https://etherscan.io/token/0x75d77c58068ff812da4b59c3d6b9ab1689983f0d
5 Links to third-party reviews or discussion of the token or the token issuer of at least two distinct kinds, including, but is not limited to: articles in the media, independent third party blogs, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments from high ranked users in BitcoinTalk, etc. These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels).
https://bitcointalk.org/index.php?topic=2511847
https://www.criptonoticias.com/aplicaciones/plataforma-pm7-aprovecha-tecnologia-blockchain-irrumpir-mundo-publicidad/

**Comment by Kryptoniq** [comment]
https://cryptocoin.news/icos/pm7-ico-review-introducing-affiliate-marketing-programs-through-the-blockchain-4789/

https://icobench.com/ico/pm7/ratings

**Comment by VictorE100** [comment]
Will this token be listed in EtherDelta?

**Comment by Kryptoniq** [comment]
Extract from your website:
```
Our ICO is finished!
Thank you for participating!
9 million tokens!
1388 token holders!
222 countries!
1,312,307 users```

but according to etherscan there are 248 token holders and 1,000,000,000 tokens. 

https://pm7.com
Archive: http://archive.is/SQsVX
