### ISSUE TITLE
Please list the token PM7 on ForkDelta

### ISSUE THREAD

**Issue by VictorE100** [forkdelta/tokenbase#1116]
1. Contract address: 0x75d77c58068ff812da4b59c3d6b9ab1689983f0d

2. Link to the token issuer's official website:  https://pm7.com/

3. 1-3 sentences for the token's description:

Our mission — is to help innovators, project developers, entrepreneurs and all creative
people to implement their ideas regardless of their location, origin or socio-economic
status.

Technologies based on intelligent contracts immediately provide compensation for all
bookings made through you: system referral links through blockchain will monitor every
order made by a short referral link of blogger, opinion leaders, and traffic provider.

4. A link to an official page confirming the above contract address: this needs to be on the official domain of the token issuer.

https://bitcointalk.org/index.php?topic=2511847.0

5.    Links to third-party reviews or discussion of the token or the token issuer of at least two distinct kinds, including, but is not limited to: articles in the media, independent third party blogs, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments from high ranked users in BitcoinTalk, etc.

https://cryptocoin.news/icos/pm7-ico-review-introducing-affiliate-marketing-programs-through-the-blockchain-4789/

https://icobench.com/ico/pm7/ratings

**Comment by Kryptoniq** [comment]
#1115
