### ISSUE TITLE
FuzeX Token (FXT)

### ISSUE THREAD

**Issue by lattedesu** [forkdelta/tokenbase#1117]
**Token address:** 0x1829aa045e21e0d59580024a951db48096e01782

**Issuer's official website:** https://www.fuzex.co/

**Description:** 

The Fuze Project & Team

FuzeX aims to revolutionise the way people pay. Our FuzeX Card, Wallet and Ecosystem allow for real-time cryptocurrency to fiat exchange which means that you can spend your cryptocurrency anytime, anywhere you like. Our team consists of a passionate group of blockchain professionals, payment specialists and business and marketing strategists, that are determined to make cryptocurrency easier to use and easier to spend.

The Fuze Card & Wallet

Store up to 15 cryptocurrency accounts, 10 credit or debit cards and 5 rewards cards all in one clever e-card. Real-time exchange also means that you can spend your cryptocurrency anytime and anywhere you like. It's also secure, two-factor authentication (PIN on card & password on app) for secure private key management.

**A link to the official contract address confirmation:** 

https://github.com/fuzex/smartcontract

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcoinexchangeguide.com/fuzex-fxt-token/
2. https://topicoreview.io/ico/fuzex-ico-review

Bitcointalk thread for presale: https://bitcointalk.org/index.php?topic=2776789.0

Tokens are distributed, and already being exchanged on [Forkdelta](https://forkdelta.github.io/#!/trade/0x1829aa045e21e0d59580024a951db48096e01782-ETH), so I'd appreciate if this could be added.

Thanks in advance!

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x1829aa045e21e0d59580024a951db48096e01782, https://www.fuzex.co/
