### ISSUE TITLE
Add walletours WTS

### ISSUE THREAD

**Issue by nuryana10** [forkdelta/tokenbase#1118]
Contract address: 0x357af180d6822ebcdc269ea147cd3d36ed971596

Issuer's official website: https://www.walletours.io

Description: Walletours is a decentralized cryptocurrency, created and directed for all of the tourist community, that make different trips worldwide with an end of needs from one place to another.

Today tourism is one of the most important industries worldwide and promotes trips of all kinds: For rest purposes, cultural reasons, social interest, business or simply for leisure

Official contract address confirmation: https://etherscan.io/token/0x357af180d6822ebcdc269ea147cd3d36ed971596

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:  https://bitcointalk.org/index.php?topic=3244489
              https://twitter.com/Walletours
              https://www.facebook.com/Walletours-779577622250729

**Comment by Kryptoniq** [comment]
Provide links to atleast two third-party reviews or discussion of your token other than bitcointalk.org.

**Comment by nuryana10** [comment]
telegram:

**Comment by nuryana10** [comment]
telegram: https://t.me/joinchat/Gdx44Q-FSxU5k24RYQe87Q
twitter: https://twitter.com/Walletours

**Comment by freeatnet** [comment]
@nuryana10 
Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases do not constitute third-party review.
* **Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.**

**Comment by hernanWTS** [comment]
Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

1. https://youtu.be/nKmykrdTlNM
2. https://request.coinpulse.io/suggestions/6672/walletours-wts

**Comment by freeatnet** [comment]
@hernanWTS #2 is not really a review of any sort.

@Kryptoniq is #1 a reasonable review or is it an explainer video?
