### ISSUE TITLE
Token Listing Request (Migration) - MyBit 

### ISSUE THREAD

**Issue by kyledewy** [forkdelta/tokenbase#1119]
**Token contract migration: MYB **

This is a token migration for MyBit, which is currently listed on forkdelta with the address of: [0x94298f1e0ab2dfad6eeffb1426846a3c29d98090](https://etherscan.io/address/0x94298f1e0ab2dfad6eeffb1426846a3c29d98090) 

New Contract address:
[0x5d60d8d7eF6d37E16EBABc324de3bE57f135e0BC](https://etherscan.io/address/0x5d60d8d7ef6d37e16ebabc324de3be57f135e0bc)

[Token Upgrade Announcement](https://medium.com/mybit-dapp/as-we-are-on-the-brink-of-entering-mybits-new-era-we-have-a-very-important-announcement-to-make-a4cda1cd6956)

Issuer's official website:
https://mybit.io

whitepaper link (english):
[whitepaper](https://files.mybit.io/files/MyBit_Whitepaper_v2.5.1.pdf)

Description:
MyBit is the world's most advanced IoT investment Ecosystem. Its two flagship products include a decentralised investment platform (MyBit DApp) and the world's first decentralised IoT asset exchange (MYDAX). Powered by Ethereum.

Contact: 
info@mybit.io 

[Blog](https://medium.com/mybit-dapp)

[Reddit](https://www.reddit.com/user/MyBit_DApp/)

[Discord](https://discordapp.com/invite/pfNkVkJ)

[Facebook](https://www.facebook.com/MyBitDApp/)

[Twitter](https://twitter.com/MyBit_DApp)

[Github](https://github.com/MyBitFoundation)

[CoinMarketCap](https://coinmarketcap.com/currencies/mybit-token/)

**Comment by freeatnet** [comment]
New token address confirmation is located in the site's footer, "Explorer" link.
