### ISSUE TITLE
List SeratioCoin on ForkDelta

### ISSUE THREAD

**Issue by ProphetDaniel** [forkdelta/tokenbase#112]
The contract address.
https://etherscan.io/address/0xB561fEF0d624C0826ff869946f6076B7c4f2ba42

A link to the token issuer's official website.
https://www.seratio-coins.world/

A link to an official page confirming the contract address
https://www.seratio-coins.world/ under SER logo

A link to a third-party review or discussion of the token, like an established ICO review blog.
https://cryptocoin.news/icos/seratio-icos-unique-value-proposition-its-personal-value-appreciation-evaluated-2939/

**Comment by JonathonDunford** [comment]
@ProphetDaniel 

I don't see the contract address on the site.
Also please provide a short desscription of 1-3 sentences.

**Comment by ProphetDaniel** [comment]
> I don't see the contract address on the site.

Under about CCEG section hover over SER logo at [Seratio-Coins website](https://www.seratio-coins.world/). We didn't want to state directly on the website the address because of the intrinsic risk ERC20 standard has of losing coins when some holders send to the coin smart contract address.

![](https://i.imgur.com/XHcOaIs.png)

> Also please provide a short desscription of 1-3 sentences.

Criptocurrencies with values. The unique feature of the Seratio token (SER) is the ability to capture the financial assets, microshares and provenance of transactions involving people, products, processes, projects and organisations.

**Comment by JonathonDunford** [comment]
Address verified: 0xB561fEF0d624C0826ff869946f6076B7c4f2ba42

**Comment by JonathonDunford** [comment]
#179
