### ISSUE TITLE
Coinberry (CBRY) listing

### ISSUE THREAD

**Issue by ordengord** [forkdelta/tokenbase#1122]
Hello!
On behalf of Coinberry, I am sending a request for listing our CBRY coin on Fork delta.

Coinberry (CBRY)
Web-site: https://preico-en.coinberry.pro/
ERC-20 address: 0x38d2eec0f2d25417cae0314ada53da1917b20248
Etherscan: https://etherscan.io/token/0x38d2eec0f2d25417cae0314ada53da1917b20248
BCT: https://bitcointalk.org/index.php?topic=2991342.80
https://bitcointalk.org/index.php?topic=2967350.260 (Russian thread)
Kickico: https://www.kickico.com/fr/campaigns/39218/mayning-i-vyraschivanie-klubniki-na-vie

BCT (full member and higher reviews):
https://bitcointalk.org/index.php?topic=2991342.msg31753079#msg31753079
https://bitcointalk.org/index.php?topic=2991342.msg32732733#msg32732733
https://bitcointalk.org/index.php?topic=2991342.msg36481970#msg36481970
https://bitcointalk.org/index.php?topic=2991342.msg30878660#msg30878660
https://bitcointalk.org/index.php?topic=2991342.msg30903368#msg30903368
https://bitcointalk.org/index.php?topic=2991342.msg30903871#msg30903871

Coinberry is Russian Far East project representing combination of block chain technologies, agricultural cultivation and solar energy. The general idea is usage of crypto mining farm’s extra heat for cultivation of strawberry in the greenhouse. Whitepaper contains economical explanation including project profitability and why cultivation of strawberry have been chosen for this region as well as solar energy benefits. The first such greenhouse (Russia FE, Primorskiy Krai) is planned to be constructed next year, but we already got our mining equipment which will be working very soon in a crypto mining hotel. CBRY token is designed for cloud mining and yields its owner some piece of its profit for six months. This model can be expanded around the world and fits for the cold regions especially. 
Though, we are just starting our international campaign, we had a great one in Russian media, and local government supports our project. 

I kindly ask you to consider our listing on Fork Delta.

Sincerely,
Sergei Zenkin
Coinberry Team
ordengord@gmail.com

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
