### ISSUE TITLE
Add Beonbox (BOX)

### ISSUE THREAD

**Issue by beonbox** [forkdelta/tokenbase#1125]
**Hi Forkdelta Team**
We are Official Representers of Beonbox Token and It will be really appreciated if you will add our token to your platform.

**Contract Details:**
0x01e579be97433f861340268521a7a2ab9829082c
Symbol: BOX
Decimals: 18

**Short Description:** Beonbox is Multifunctional Token for Shopping, Cashback Crediting, Gaming and Exchange.

**Beonbox Details:**
NAME: BEONBOX
CODE: BOX 
Country: Japan, Tokyo

**BeonBox Official sources:**
Site:http://www.beonbox.com
ICO page:http://www.beonbox.com/ico **(OFFICIAL PAGE CONFIRMING CONTRACT ADDRESS)**
Exchange page:http://www.beonbox.com/exchange
Store Beta page:http://www.store.beonbox.com/
Bounty Page:http://www.beonbox.com/bounty 
Twitter:https://www.twitter.com/beonbox
Telegram:https://www.t.me/beonbox
Instagram:https://www.instagram.com/beonboxtoken
Whitepaper:https://goo.gl/cFkKG7
https://drive.google.com/file/d/1zH85m8dWRhzYpLoEyk1MW_QqauDHWRow/view?usp=sharing
Bitcointalk:https://bitcointalk.org/index.php?topic=3063339.msg31556478#msg31556478
Bitcointalk (Bounty):https://bitcointalk.org/index.php?topic=3063911.msg31564727#msg31564727

**ARTICLES:**
https://steemit.com/beonbox/@den360/beonbox
https://steemit.com/cryptocurrency/@kylie-steem/ico-analysis-beonbox
https://steemkr.com/@beonbox
https://medium.com/@bhabyberna/beonbox-bounty-82622131466c
https://www.reddit.com/user/jakeshadows27/comments/8izsby/beonbox_bounty/?ref=share&ref_source=link
https://steemit.com/cryptocurrency/@paula2016/beonbox-bounty
https://web.facebook.com/jake.magturtor/posts/2472863946072540
https://www.linkedin.com/pulse/beonbox-bounty-program-berna-bulanon/?published=t
https://steemit.com/blockchain/@funkyies/beonbox-develops-the-ethereum-technology-platform
https://cryptocoinpravda.com/beonbox-develops-the-ethereum-technology-platform.html
https://medium.com/@babalolaolufunke33/beonbox-develops-the-ethereum-technology-platform-d537556c14fa
http://telegra.ph/BEONBOX-Develops-the-Ethereum-technology-platform-05-11
https://www.minds.com/blog/view/841672129368076288
https://bitcointalk.org/index.php?topic=3269881.0
https://www.altcoinstalks.com/index.php?topic=12638.msg63338
_(and more than + 70 articles on different social medias.)_ 

**ICO Reviews:** 
https://icosource.io/ico/beonbox/ 
https://betapage.co/startup/beonbox 
https://icoranker.com/ico/beonbox-ico/ 
https://www.bitcoinmarketjournal.com/icos/beonbox/ 
https://icolink.com/payments-ico-list/ad/beonbox,711.html 
https://www.coingecko.com/ico/beonbox 
https://coinclarity.com/ico-events/beonbox/ 
https://icotracker.net/listqueue 
https://golos.io/ico/@niksalt717/obzor-ico-beonbox 
https://icoholder.com/ru/beonbox-ico-19262 
https://icobench.com/ico/beonbox 
https://highcastle.co/marketplace/beonbox/ 
https://concourseq.io/Q/BeonBOX_ICO 
https://www.icodata.io/coin/beonbox 
https://cryptocoincharts.info/ico/beonbox-box 
https://thetokener.com/ico/beonbox 
https://www.trackico.io/ico/beonbox/ 
https://coindelite.com/ico-detail-beonbox 
https://bountylord.com/index.php?id=1085 
http://icodude.com/ico/337/beonbox 
https://foxico.io/project/beonbox 
https://www.bestcoins.co/ico/beonbox 
https://sangus.org/ico/1297 
http://icocra.com/hikashop-menu-for-products-listing/product/247-beonbox 
https://icoexpert.biz/icos/beonbox-ico/ 
https://cryptoslate.com/coins/beonbox/ 
https://coinclarity.com/ico-events/beonbox/ 
https://www.smithandcrown.com/sale/ 
https://www.coinjinja.com/ico/beonbox 
_(and also +20 reviews. Search beonbox ico on google)_

**Youtube:**
https://www.youtube.com/watch?v=6EvDlKk1M78&feature=youtu.be
https://www.youtube.com/watch?v=_OPy3LraOb4&feature=youtu.be
https://www.youtube.com/watch?v=6zmKKjQ050Y
https://www.youtube.com/watch?v=UFVUbrhsiw4
https://www.youtube.com/watch?v=G4RkwXvMFDs
https://www.youtube.com/watch?v=IAS9X1l8CLw
https://www.youtube.com/watch?v=0_zJrGQgpJE 
www.dailymotion.com/video/x6j5bg9
https://www.youtube.com/watch?v=uhDA1C5y9_A 
https://www.youtube.com/watch?v=jkFFtZMbkR4
_(And more than +30 videos Search beonbox on youtube.)_

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically, do not include social links etc that are not required (they should be present on your website).
