### ISSUE TITLE
List TRTK TravelToken on ForkDelta please!

### ISSUE THREAD

**Issue by AdminTRTK** [forkdelta/tokenbase#1126]
TravelToken brings the practicality and security of the blockchain system to the services of travel payments and touristic tours.

Site: https://trtk.online
Github: https://github.com/AdminTRTK/TRTK
ContractAddress: https://etherscan.io/token/0x281122bd473e24828506780961a8a31c3981d9fa

Best Regards!

**Comment by freeatnet** [comment]
Thank you for your request, @AdminTRTK! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by AdminTRTK** [comment]
Token address:  0x281122bd473e24828506780961a8a31c3981d9fa

Issuer's official website:

Description: TravelToken brings the practicality and security of the blockchain system to the services of travel payments and touristic tours.

A link to the official contract address confirmation: https://etherscan.io/token/0x281122bd473e24828506780961a8a31c3981d9fa

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=4145701
2. https://twitter.com/AdminTRTK

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases do not constitute third-party review.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
