### ISSUE TITLE
Listing MobilinkToken

### ISSUE THREAD

**Issue by mobilink-token** [forkdelta/tokenbase#1127]
This is the official request from Mobilink to list our token on forkdelta, please disregard any previous
requests or listings if any that may have been posted.  

The contract address:

Token Name: MobilinkToken
Token Ticker: MOLK

A link to the token issuer's official website.
mobilink.io

MOBILINK-COIN ICO has partnered with Mobilink-Network to be the First Decentralized Mobile Telecom Company using blockchain technology. Digital monthly revenues based on Proof of Participation pay for all voice and data usage costs. 

Here is the link to an official page confirming the above contract address: 
https://mobilink.io/token.php

Links about MobilinkToken and ICO
https://icomarks.com/ico/mobilinkcoin
https://www.reddit.com/r/mobilinkcoin/
https://bitcointalk.org/index.php?topic=2614818.msg26607277#msg26607277

**Comment by Kryptoniq** [comment]
Another mobilink address.
So far, we have gotten 3 requests with different contract addresses and we'll not be listing any until there is a proper confirmation.
#949 #1034 #1127
1. 0x8fbcb3f7a4c48dd9500ba20b5254c08d75403ba1
2. 0x97Cb5Cc1b2e10cC56DC16ab9179f06dfEDBe41A2
3. 0x83af51574de213db73e65c5fc67fe5c69305d896

**Comment by tkdeveloper** [comment]
Unfortunately our last token was audited and a vulnerability was found. We reissued the token one last time and distributed it.

https://etherscan.io/token/0x97cb5cc1b2e10cc56dc16ab9179f06dfedbe41a2

This is the official coin.

Contact:  contact@mobilink.io  to verify please

**Comment by mobilink-token** [comment]
Here is the correct contract address:
The contract address: 0x97cb5cc1b2e10cc56dc16ab9179f06dfedbe41a2 Token symbol: MOLK

This is to confirm that the proper request is #1127 confirming the contract address below:
0x97Cb5Cc1b2e10cC56DC16ab9179f06dfEDBe41A2

**Comment by Kryptoniq** [comment]
We had request from @mobilink-token and @Mobilinkadmin.
For confirmations, link the official Mobilink github account on the website. Thank you.
