### ISSUE TITLE
TDH Token Listing Request

### ISSUE THREAD

**Issue by nklansek** [forkdelta/tokenbase#1129]
Hello,

I would like to request to list TDH token on ForkDelta.

1. The contract address: 
0x2a1dbabe65c595b0022e75208c34014139d5d357

2. A link to the token issuer's official website: 
https://trustedhealth.io

3. Project Description:
TrustedHealth is a patient-led and doctor-guided cooperative focused on creating an ecosystem with Trustedoctor as a partner, in order to create an ecosystem of services, s.a. diagnostic labs, private clinics or surgery, insurance companies, pharmacies, patient organisations, research institutions, providers for patients to access.

4. A link to an official page confirming the above contract address: 
https://trustedhealth.io/token-sale

5. Links to third-party: 
https://icobench.com/ico/trustedhealth
https://bitcointalk.org/index.php?topic=2822113.0
https://www.reddit.com/r/TrustedHealth/

**Comment by freeatnet** [comment]
Thank you for your request, @nklansek! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
@nklansek Here are a couple reviews closer to what we're looking for:
1. https://hacked.com/ico-analysis-trustedhealth/
2. https://bitcoinexchangeguide.com/trustedhealth-tdh-ico/

FTFY. :)

Contract address verification seems to have moved to https://trustedhealth.io/token, too.

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.

---
0x2a1dbabe65c595b0022e75208c34014139d5d357,https://trustedhealth.io
