### ISSUE TITLE
ADD "ToThEMoon" (TTM) Token in ForkDelta

### ISSUE THREAD

**Issue by ToTheMoonToken** [forkdelta/tokenbase#113]
Hello, first of all, thank you very much for the work you are doing, congratulations.
We want to include our token in Forkdelta.
Let's see if we do it well ...
`---
addr: '0xbd35AefA375b57a801dDc87615aef1E9F353dF28'
decimals: 18
description: The crazy project of cryptoalchemy. "Poopy" to the moon!
links:
- Email: mailto:hello@tothemoontoken.com
- Facebook: https://www.facebook.com/tothemoontoken/
- Twitter: https://twitter.com/ToTheMoon_Token/
- Website: http://www.tothemoontoken.com/
name: ToTheMoon
symbol: TTM`

If they need something they just have to say it. Thank you very much

**Comment by JonathonDunford** [comment]
Address verified: 0xbd35AefA375b57a801dDc87615aef1E9F353dF28

Just a tip, use three of those ticks to signify a code block.

**Comment by JonathonDunford** [comment]
#72
