### ISSUE TITLE
Listing of Vega Token (VGA)

### ISSUE THREAD

**Issue by VEGAtoken** [forkdelta/tokenbase#1130]
Hi from https://vegatoken.org/

We, RX Vega miners, are in the middle of a quiet ITO and are using ForkDelta to conduct transactions with potential members here:
https://forkdelta.github.io/#!/trade/0x26b2b4952a10b1782827d339a02aecb008edb817-ETH
and would like to be officially listed on ForkDelta for now and in the future.

Vega Token (VGA) is the Worlds First community pool software development initiative to use the ERC20 token contract as proof of membership and real time pass to all VGA Dev. using as current and active proof, the VGA ITO launch software QMS v01.0.0 free to download from our servers with free4all functions as well as member only functions, download here:  
http://vgaserver.tech/file/QMS.zip

Anyone with 500VGA satoshi in their wallet gets instant 100% access to all our platforms now and in the future, thus you understand the importance of being able to trade such a commodity as Vega Token (VGA). I use that term because Vega Token (VGA) is actual proof of ownership and key to unlock full functions of VGA Dev. and not just another promissory moon coin.

Please visit this page on the site for coin info: 
https://vegatoken.org/tell-me-more

Thank you for the kind consideration.

ps, in the event of our listing, please rename us to VGA and not VEGA as a member already lost 0.5ETH trading the wrong token out of his own mistake, between (same as above) here:
https://forkdelta.github.io/#!/trade/0x26b2b4952a10b1782827d339a02aecb008edb817-ETH
and the unrelated to Vega Token (VGA)  listing here:
https://forkdelta.github.io/#!/trade/VEGA-ETH

Pan. K.
Vega Token (VGA)
Oslo, Norway

**Comment by freeatnet** [comment]
Thank you for your request, @VEGAtoken! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by VEGAtoken** [comment]
Thank you for the response, below are the details in the format you requested.

Token address: 0x26b2b4952A10b1782827D339a02aEcb008Edb817

Issuer's official website: https://vegatoken.org/

Description: Community funded AMD RX Vega Crypto mining R&D for development of Software, Mining OS, Drivers, Bios, and member specific requests  

A link to the official contract address confirmation: https://etherscan.io/tx/0x4f4277d23a9c929c1d5e21d14d46981d034c4f6366f1bd7a0c161df586a32cd3

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://bitcointalk.org/index.php?topic=3758309.new#new
https://join.slack.com/t/vegatoken/shared_invite/enQtMzY2NjE5ODE4ODY3LWYxNmVjMGNkODAxZThiNzk3ZjYyMzMxYjJhNWEyOTg0M2U4Y2FhMzFiYTE5ZjQ3NWU4ZGY2YWFhMTBlZjlhNjA

Note: Unlike 90% of all Coins and Tokens that offer only promises, Vega Token (VGA) has already produced software (QMS) that is currently in use by its members, in addition to current testing of the VGA 0fee mining pool http://93.72.84.78
By clicking the Slack link above you can witness real time discussion/requests by our members and non-members.
It is important for Vega Token (VGA) to be traded in the open markets as the Token itself acts as an instant password to unlock the full functions of VGA Tech, this is a World First and we anticipate this methodology to become widespread if not standard practice by other unrelated projects in the future. 

We really appreciate the fact that ForkDelta is one of the few Decentralised Exchanges and wish to conduct the majority of trades via your exchange. Thank you for the consideration.

**Comment by freeatnet** [comment]
@VEGAtoken Please see requirements not satisfied by your updated request below.

1. Please provide a link to the official contract address confirmation. Contract address confirmation MUST be linked from the official website and MUST be visible publicly. If the confirmation is not visible immediately, include an explanation of how to find it.
2. Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

    Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
    Note:
    * We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
    * Press releases do not constitute third-party review.
    * Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by VEGAtoken** [comment]
1. https://vegatoken.org/tell-me-more
scroll down under VGA TOKEN DATA
2.https://bitcointalk.org/index.php?topic=3758309.new#new
pg1 post#18
I am really satisfied with QMS! No more regedit, enable disable etc etc! 
BIG UPS PAL! Nicely done! 
Thamez
pg2 post#25
This allready looks good. Keep up the good work and the good communication.
Looking forward to get more and MOAR out of my vegas Wink
Thx for implementing differenet pp tables on each card individually that fast.
pg3post#37
Just to add to what others have said, the Vega Token (VGA) guys are amazing and QMS is already worth getting in on the ITO.  I regret not buying in pre-ITO stage as I could have gotten in much cheaper (work and other things delayed me getting started in time), but with the both the work they are doing to unlock the power of the Vegas and the responsiveness and helpfulness of the team and the community, the ITO cost is cheap and I predict many will be paying more in the future.  I'm generally a newbie in this space and ForkDelta is particularly frustrating to use (definitely send direct to avoid this) but any problems I e-mailed about were quickly responded to and they really want to build a community and software that provides value.
Get your token and join the community now if you have or are getting AMD Vega GPUs as you won't regret it.
JP
pg3post#40
Carlos, all I can say is I am who I am.  I only created an account to share my experience with the Vega Token (VGA) guys and if I have something of value to add to the community, will post that too but I have learned a lot from lurking here for several months.  I'm a newbie to mining, having started with NiceHash and a RX580 on my home server last fall and building a rig at the end of the year and populating it with Vegas as I could get my hands on them at less than retail prices.  It has been difficult to keep stable after 4 Vegas (ASUS 64s), and though I thought I might have more trouble going back to the blockchain driver (I was on more recent drivers before QMS), with QMS managing configurations and implementing quickly is easy and I expect the improvements to continue based on what I've seen in the short month or so that I've been watching the Vega Token group developments closely.  
I understand the skepticism, but they are improving mining for Vega owners faster than AMD is and if you just look at the website and posts here closely and try the software's free features, you'll possibly learn some things for free and if you think it is going in the right direction you can decide if the investment risk is worth it for you.  Depending on your scale and goals, I think you'll find that you could improve your mining results a minimum of 10-15% for very little work compared to working with existing tools and trial and error.  If that is worth it for you, then buy the token. If not, nobody is forcing you to. 
Good luck with your mining!
JP
pg2post#52
The devs has a lot of ground to cover, yes. It will take time to accomplish those speeds, i suggest you give them a chance to meet at least 50% of roadmap. Theyre currently at driver optimizations & OS bruh.
2. https://bitcointalk.org/index.php?topic=3659601.0
pg1post#3
Testing QMS on my 5 x Vega 64 rig, would say very comfortable utility. PowerPlay table, OC, monitoring cards, running and configuring miner and rest features from 1 place.
At this moment I'm using blockchain drivers, and it is a requirements for this utility. My personal issue with blockchain is a artifacts with xmr-stack miner so I mover to cast-xmr in order to testing this powerful util.
Nice support via chat. Ed (developer) and Moderator or chat, helps with different issues almost immediately.
Interesting to read other review from other tester.
pg1post#3
This program is the best thing that has ever come out for Vegas! So glad its finaly out bro! 
Bye bye regedit,overdrivent and device manager!!  Grin 
Thanks again!!
pg1post#11
Agreed, 1st you tried... you don't want to touch all these pieces any longer...
pg1post#15
Is there an Android telemetry monitor? Just wondering on what platform I'll monitor while away.
Web based monitor came online 1hour ago, Alert system on fail should be functional be the end of today, (yes we work on weekends too).
2.https://bitcointalk.org/index.php?topic=2549085.220
from pg12 onwards the VegaToken VGA idea was born, too many posts to list here.

The only other relevant 3rd party reviews can be found in our Slack channel, (link in previous post or direct from site) where daily open discussion with members/non members can be found readily, this is the best place to look if you want to determine whether we are legit or not.
 We are sorry if this is not acceptable but as mentioned above our quiet ITO started just over a month ago and will come to a close within 2 weeks thus independent media has not had the time to pick up on our project and we are not publicity whores as we are NOW servicing a small number of miners with our EXISTING software and aim for quality not quantity.

With the immense amount of coins and tokens listed on your exchange with NO SUBSTANCE or evolution it boggles our mind how its not possible for you to determine the validity of our mission and PROVEN achievements by simply clicking on the few links we supplied.

I understand your time is precious and you have too much to do, but please spend 7mins go through our site, links supplied and slack channel for a clear picture that you have not attained yet.

Hell, if you are VEGA miners we can supply test codes for our launch software QMS if you so require, to see for yourselves what we have already achieved leaving behind promises which consist the vast majority of the coins/tokens listed on your exchange at present.

Thanx
Pan. K.
Vega Token (VGA)
Oslo, Norway

**Comment by VEGAtoken** [comment]
hi, just wondering when we might have an answer?
its been a month and a half since last update

thnx
