### ISSUE TITLE
Request to list ScudoCash (SCH) token

### ISSUE THREAD

**Issue by scudocash** [forkdelta/tokenbase#1131]
Name : ScudoCash 
Symbol : SCH 
Token: ERC20
Contract address: 0xF463434733b26c6f5e79Eb9Dbde4b508DEDDA95c
https://etherscan.io/address/0xf463434733b26c6f5e79eb9dbde4b508dedda95c
Official Website: scudocash.com
Whitepaper: https://scudocash.com/white-paper/?lang=en
YouTube: https://www.youtube.com/watch?v=8YUSFnvzNC8
Twitter: https://twitter.com/scudocash
Telegram: https://t.me/scudocash
Telegram Channel 1: https://t.me/scudocashofficial
Telegram Channel 2: https://t.me/bitbazario
Description:
Decentralized free platform where users can buy and sell items among privates, everything using cryptocurrencies (BitCoin, Ethereum, Litecoin and ScudoCash) through Smart Contracts.
The final objective is to offer the easiest, fastest and most reliable crypto-based marketplace on the world. Our team wants to bring more and more people into the crypto-world to make it even bigger.
bitBazar.io wants to help both those who are getting in contact with cryptocurrencies for the first time and the most expert users to make great trades using this awesome technology based on money decentralization, without binding with institutions: cryptocurrencies.
We expect big results obtained from a user-friendly platform, a big offer with controlled contents to keep our users safe, realized by an awesome and unite team!
We are the pioneers in the sector of crypto-based marketplaces; our vision of trading is open to new technologies, to the decentralization of the market and of money.
Specifically in our case we have studied the perfect smart contract for exchanges including partial evasion of the smart contract itself in favor of the carrier that makes the delivery, even if the sale is not successful the carrier must be paid and therefore the smart contract must close the transaction even in this case.
Our business is given by advertising banner, by the percentages on the use of smartcontract and by payment options on the platform, payable with ScudoCash (SCH)
email: info@scudocash.com or info@bitbazar.io 
Thank you in advance.

**Comment by freeatnet** [comment]
Thank you for your request, @scudocash! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
