### ISSUE TITLE
Reques to list MOKEN

### ISSUE THREAD

**Issue by buzz555** [forkdelta/tokenbase#1132]
Token address: https://etherscan.io/address/0x4ef04af8fa2de2b71dd4472fd26926ff23d87f77

Issuer's official website: www.mokenex.com

Description 
Mokenex is on its way to become world's first decentralized multi cryptocurrency payment gateway and a token exchange platform.
Integrage Mokenex to your online shop, bill payment services and even blockchain systems. Accept major coins and all tokens. Pay smallest fee available in market. Moreover, users will directly exchange their tokens (All Ethereum and other blockchains) for no fees.

Mokens are 'money tokens' - universal cryptocurrency to using in various tokenized blockchain systems and marketplaces/gaming sites.

Public address
On www.mokenex.com (in ICO section)

A link to a third-party review or discussion of the token:
https://bitcoinexchangeguide.com/mokenex-monks-ico/

https://www.youtube.com/watch?v=sBWOgW_tUJU

https://www.youtube.com/watch?v=PSg1MOmBeM8

**Comment by freeatnet** [comment]
Thank you for your request, @buzz555! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by buzz555** [comment]
hi
We updated the thread with 3 links.

**Comment by freeatnet** [comment]
@buzz555 Information is a touch thin on this project. Are there any other third-party research&review articles?

**Comment by buzz555** [comment]
hello, any updates?

**Comment by buzz555** [comment]
Hello...Moken already has over 1700 holders. Sharply increased. Kindly list.
