### ISSUE TITLE
NCS Token Listing Request

### ISSUE THREAD

**Issue by tuminfei** [forkdelta/tokenbase#1133]
Hello,

I would like to request to list NCS token on ForkDelta.

1.The contract address:
0xa60354005b3897bC684244B593fA6F5F18ECd13e

2.A link to the token issuer's official website:
http://www.niucoin.cn

3.Project Description:
Niu Coin System(NCS) is an intelligent, credible and open value application platform platform based on  blockchain. Artificial Intelligence(AI) technology and blockchain technology are becoming the core drivers of business transformation in the digital age. However, most of the blockchain projects focus on blockchain technology innovation and technology platform development. There is also not many blockchain projects can bring real values to their users. 
Core teams of NCS are  from Wall Street and Silicon Valley in the United States. We already grasp the knowledge of securities knowledge graph, AI decision-making engines, customer value models, customer loyalty models and other core technologies, NCS will combine the technology of the blockchain and AI to build an knowledge cash out system and bring values to our customer.

4.A link to an official page confirming the above contract address:
http://www.niucoin.cn/#_2

5.Links to third-party:
https://twitter.com/NiuCoin_Info
https://www.reddit.com/user/niucoin/
https://t.me/niucoin2018

https://www.toutiao.com/i6568686247680672269/

**Comment by freeatnet** [comment]
Thank you for your request, @tuminfei! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by tuminfei** [comment]
Thank you @freeatnet

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically, third-party review links cannot be on resources controlled by the project.

**Comment by tuminfei** [comment]
third-party review links : https://www.toutiao.com/i6568686247680672269/

**Comment by tuminfei** [comment]
Please help you to reconfirm @freeatnet
