### ISSUE TITLE
Request for listing Friendz Coin (FDZ)

### ISSUE THREAD

**Issue by pi9x** [forkdelta/tokenbase#1134]
1. Contract address: 0x23352036e911a22cfc692b5e2e196692658aded9
Symbol: FDZ
Decimals: 18

2. Token issuer's official website: https://friendz.io/

3. Friendz is a tool that lets multinational companies involve a community of users on social networks for marketing purposes. The company has run in Italy and Spain for 2 years. Now they're integrating blockchain into their app and use the fund from ICO to expand to other areas as in their roadmap https://friendz.io/#roadmap

4. Confirmation of the contract address: https://blog.friendz.io/2018/03/01/how-to-add-friendz-token-to-myetherwallet/

5. Links to third-party reviews or discussion of the token:
- https://bitcointalk.org/index.php?topic=2815966.0
- https://icobench.com/ico/friendz
- https://www.youtube.com/watch?v=3Wrh27liCxc
- https://icorating.com/analytics/indepth/friendz-rating-review/

**Comment by freeatnet** [comment]
See also #1169 by @nigarchalabi:

> Dear team of ForkDelta,
> 
> My name is Nigar and I am representative for FriendZ project.
> 
> We would like to add FDZ token to ForkDelta
> 
> 1) The contract Address: 0x23352036e911a22cfc692b5e2e196692658aded9
> 2) Website: www.friendz.io
> 3) Description: Friendz is a working product with €1.5m in revenues, a team of 40 employees and a community of 250k users. Friendz platform connects companies to people willing to provide support in the generation of advertising contents directly posted on their personal social media profiles. Users involved in this peer-to-peer communication process get rewarded for their collaboration through our FDZ tokens. FDZ will be the standard token to manage and reward people for online activities.
> 
> WP: https://friendz.io/file/whitepaper_icofriendz.pdf
> 
> Social Media: 
> 
> - Telegram Group: 76,000 users
> - Telegram Channel: 57,000 users
> - Facebook page: 51,000 fan
> - Twitter: 56,000 follower
> - Instagram: 19,000 follower 
> 
> App download:
> 
> - Download: 247,000
> - Monthly Active Users: 43,000
> 
> 
> ICO results:
> 
> - 14,000 contributors
> - 21,000 holders
> - 31,000 ETH raised
> 
> 4) Link to etherscan: https://etherscan.io/token/0x23352036e911a22cfc692b5e2e196692658aded9#balances
> 
> 5) Review: https://icobench.com/ico/friendz ,  https://coinmarketcap.com/currencies/friends/, https://cryptobriefing.com/friendz-ico-review-fdz-token-rating/ , https://icocrunch.io/ico/friendz/
> --

**Comment by freeatnet** [comment]
Marked as high priority because of a trusted review source: cryptobriefing.com; and presence of CoinMarketCap.

NB: make sure trusted sources refer to the project requested.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x23352036e911a22cfc692b5e2e196692658aded9, https://friendz.io/
