### ISSUE TITLE
Please, Add LNP token 

### ISSUE THREAD

**Issue by linknaturepower** [forkdelta/tokenbase#1135]
Token address:  0xfdf12d6a60c78a5c791090d7838da4e3e7c31b8c

Issuer's official website: https://linknaturepower.com/

Description: We develop a blockchain ecosystem and a tool for the global marketplace of food manufacturing and agriculture products. 
Block chain Ecosystem uses LNP token, which is based on ERC 20 smart contract, to help farmers, food manufacturers, distributors, restaurants and consumers reduce transaction costs.

A link to the official contract address confirmation: https://linknaturepower.com/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:  
1.  https://bitcointalk.org/index.php?topic=3141056

**Comment by Kryptoniq** [comment]
There are only 12 token holders.
Your bitcointalk announcement barely contains information of what your project is all about.

**Comment by linknaturepower** [comment]
Thank you very much
We are real company, we don't ICO thus LNP token just share of company.
We will update bitcoin talk information soon.
Your sincerely

**Comment by freeatnet** [comment]
At least 2 third-party review links are required. Please see the required format for details: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
