### ISSUE TITLE
Request to List Hyperion Fund Token (IHF)

### ISSUE THREAD

**Issue by nialljenIT365** [forkdelta/tokenbase#1136]
1. contract address.
0xaF1250fa68D7DECD34fD75dE8742Bc03B29BD58e

2. Link to the token issuer's official website.
https://invictuscapital.com/

3. 1-3 sentences for the token's description: at least one on the token issuer (eg., the product they are building) and one on token role.

Invictus Capital is a team providing innovative investment products that cater directly to the needs of the independent investor
The Hyperion Fund (IHF Token)provides investors with diversified exposure to a portfolio of expertly-vetted early stage investments in the blockchain economy through simple agreements for future token (SAFTs), pre-sales and initial coin offerings (ICOs)

4. Link to an official page confirming the above contract address: this needs to be on the official domain of the token issuer.
https://app.invictuscapital.com/app/hyperion/invest

5. Links to third-party reviews or discussion of the token or the token issuer of at least two distinct kinds, including, but is not limited to: articles in the media, independent third party blogs, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments from high ranked users in BitcoinTalk, etc. These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels).

https://hacked.com/ico-analysis-hyperion/
https://bitcoinexchangeguide.com/invictus-hyperion-fund-ico-ihf-token/
https://www.icochamps.com/ico/InvictusHyperionFund

**Comment by freeatnet** [comment]
Thank you for your request, @nialljenIT365! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xaf1250fa68d7decd34fd75de8742bc03b29bd58e, https://invictuscapital.com/
