### ISSUE TITLE
Request to list FIXY NETWORK Token (FXY)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1138]
...

**Comment by fixynetwork** [comment]
When will it be listed? Tokens are unlocked shortly after 31.5.2018  18:00 UTC time

**Comment by fixynetwork** [comment]
Hello @freeatnet . Any update to this issues?
Regards,
CEO, fixyapp.io

**Comment by fixynetwork** [comment]
@freeatnet When it will be listed?

**Comment by freeatnet** [comment]
@fixynetwork You'll receive a notification once your request has been reviewed and another one a couple days before it goes live.

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases or sponsored articles do not constitute third-party review.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
