### ISSUE TITLE
proper confirmation of token

### ISSUE THREAD

**Issue by mobilink-token** [forkdelta/tokenbase#1139]
**What token should be updated?**
The contract address: 0x97cb5cc1b2e10cc56dc16ab9179f06dfedbe41a2  Token symbol: MOLK

**What about the token should be updated?**
this is to confirm that the proper request is #1127 confirming the contract address below:  
0x97Cb5Cc1b2e10cC56DC16ab9179f06dfEDBe41A2

**Comment by Kryptoniq** [comment]
Should be on #1127
