### ISSUE TITLE
Add Token JoshuaCoin

### ISSUE THREAD

**Issue by webupspa** [forkdelta/tokenbase#1140]
Request to list JSHCN JoshuaCoin

addr: 0x3D7c5223825cC58Bfa07B9484935Ad76e1741a2B
Decimals: 18
Description: 
Jspace JoshuaCoin gives you the possibility to purchase a disk storage on the first server in space. Benefits are countless: the more JoshuaCoin you purchase, the more disk space you will get.
Links:
    Website: https://jspace.io/
    Name: JoshuaCoin
    Symbol: JSHCN
![logo256x256](https://user-images.githubusercontent.com/39186068/40420035-561ed482-5e87-11e8-8521-977b76b5ea92.png)

**Comment by Kryptoniq** [comment]
How do we purchase a server in space with JoshuaCoin?
FYI, this ForkDelta.

**Comment by freeatnet** [comment]
Thank you for your request, @webupspa! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.
