### ISSUE TITLE
Vaynix Project Apply To Exchange

### ISSUE THREAD

**Issue by vaynix** [forkdelta/tokenbase#1144]
Hello sir.
Im Lucas Nilsen Project manager of Vaynix.

We want to apply to your exchange, our community vaynix grows every day. We will be honored to be accepted on your exchange.

Our pre-sale started on 2 April 2018 and ends on 05 June 2018.

We have the request if your team will accept us, to be listed on June 5, 2018.

Here are some details about our community and the traffic we currently have.

Global Rank (Worldwide): 480,867

Russia: 15.49%
United States: 10.73%
Ukraine: 8.89%
Vietnam: 8.54%
India : 5.34%

Source (Link) Link: https://www.similarweb.com/website/vaynix.com#overview

TRAFFIC
DAILY ESTIMATIONS
Unique Visitors: 722
Unique Pageviews: 1,117

MONTHLY ESTIMATIONS
Unique Visitors: 21,660
Unique Pageviews: 33,510

Source (Link): http://www.siteworthtraffic.com/report/vaynix.com

Telegram: 4600 Members
Source (Link): https://t.me/joinchat/ItCwUky56_sBsax1xLaIgQ

Twitter Followers: 2,684

Source (Link): https://twitter.com/VaynixVNX

Facebook Page: 1,186 likes

Source (Link): https://www.facebook.com/Vaynix-1048685878616337

https://bitcointalk.org/index.php?topic=3239397.0

##### Vaynix Information ###

Vaynix (VNX)

Contract Address: 0xbbf1885C21604Ef777009aCa8ff549EE96Bb3D7C
Total Supply: 10,000,000,000 VNX
Token Symbol: VNX
Token Decimals: 18

What is Vaynix ?

-Vaynix iѕ a financial system & crypto currency thаt ореrаtеѕ with borderless interaction аrоund the glоbе, оnсе уоu are соnnесtеd tо intеrnеt, nо matter thе geographical diѕtаnсе bеtwееn thе ѕеndеr and rесеivеr.
Is more than just a simple cryptocurrency it’s a tool that helps vendors, allow anonymous transaction focuses on privacy . Our vendors can sell their products, accept Vaynix through our platform,

ACCEPTED IN ENTIRE WORLD

-Our goal is to bring Vaynix to all users around the world . All user will be able to send, receive, withdraw Vaynix (VNX) at any time. Accepted by the vast majority of stores and vendors ,Vaynix will be privacy and all transactions will be anonymous.

VAYNIX VENDORS

-VAYNIX Marketplace will allow thousands of vendors around the world to get access to markets that they cannot afford now and will provide access to the audience of early adopters and technology fans Millions of customers will receive a unique range of one-of-a-kind products with no extra charges from intermediaries

PRIVACY

-Vaynix, a cryptocurrency that will focus on anonymity, Every users can use Vaynix as an anonymous payment method without anyone knowing who is behind that transaction, No one knows how much you sent or how much you received. No one knows how much money you have in your wallet. Secure your life with Vaynix

VAYNIX ATM

-In 2019 we will try to place our first ATMs in every capital of the world. Any user using our Vaynix platform will be able to withdraw real money using VNX

OUR FUTURE ?

-In 2019 we expect to see us on top 100 cryptocurrency Vaynix (VNX) being accepted by the greatest exchanges in the world Binance, Bittrex Cryptopia and many more. Vaynix will be able to be changed to BTC or ETH instant using our wallet. everyone will be able to withdraw Vaynix in FIAT using our own ATM placed around the world

DISTRIBUTION OF VAYNIX
-Investors 80%
-Team 15%
-Bounty 3%
-AirDrop 2%

OUR MAIN FOCUS
-vendors
-privacy
-own atm

RoadMap
April -> Involvement of advisors and financing for token sale
June  -> Accepted on major exchanges
July  -> Release Android Wallet
         Improve website
         Release Vendors Platform
August-> improve browser wallet
         Release own exchange for our wallets ( Exchange VNX/BTC, VNX/ETH ) instant using your wallet even on the phone wallet
September -> Release Desktop and Mac Wallets
October -> Release IOS Wallet

In 2019 Everyone will be able to withdraw Vaynix in FIAT using our own ATM placed around the world

Official Website: https://vaynix.com
Official Wallet: https://vaynix.com/wallet
Official Twitter: https://twitter.com/VaynixVNX
Official Facebook: https://www.facebook.com/Vaynix-1048685878616337
Telegram Group: https://t.me/joinchat/ItCwUky56_sBsax1xLaIgQ
Telegram Announcement: https://t.me/vaynix
Youtube Channel: https://www.youtube.com/channel/UC7DGeuCjTDZW933I5GrYxbQ
BitcoinTalk: https://bitcointalk.org/index.php?topic=3239397.20
GitHub: https://github.com/vaynix/vaynix
LOGO: https://postimg.cc/image/jok3lbmx3/

Support Contact
EMAIL: support@vaynix.com
OR
EMAIL: dexter@vaynix.com

**Comment by freeatnet** [comment]
See #1224.
