### ISSUE TITLE
Add DYCOIN (DYC)

### ISSUE THREAD

**Issue by vloskarjov** [forkdelta/tokenbase#1145]
Dear Team,

We would like to ask you to list our token on the Forkdelta token exchange. Here are the details: 

- The contract address: 0x2b27bf565593da4c3689207175e91b1c15e4792a

- A link to the token issuer's official website: https://ico.dylyver.com/ (main web page: http://dylyver.com/

- 1-3 sentences for the token's description: at least one on the token issuer (eg., the product they are building) and one on token role.
Dylyver is a technology corporation that creates innovative transportation and logistics solutions, taking advantage of advanced mobile and blockchain technologies. Together, our two proprietary mobile applications form one unique service and income system for users:  1) A ridesharing solution that enables drivers and riders to easily interact with each other. 2) A package delivery platform that connects and empowers senders, couriers, and recipients to collaborate and take full control of the package delivery process. The Dylyver token is designed to simplify the standard global use and payment of  rides and parcel delivery services, whereby providing security and safety of all transactions. 

- Links to third-party reviews or discussion of the token or the token issuer of at least two distinct kinds, including, but is not limited to: articles in the media, independent third party blogs, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments from high ranked users in BitcoinTalk, etc. These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels).  https://icobench.com/ico/dylyver, https://bitcoinexchangeguide.com/dylyver-ico-dyc-token/, https://www.trackico.io/ico/dylyver/

Best regards,
Vladimir Loskarjov
Founder and CEO
Dylyver Technologies

**Comment by freeatnet** [comment]
Thank you for your request, @vloskarjov! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
@vloskarjov Among your links https://bitcoinexchangeguide.com/dylyver-ico-dyc-token/ is the closest to what we're looking for. Are there other research&review articles you could provide?

Generally, we're looking reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

We're looking for articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases or sponsored articles do not constitute third-party review.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
