### ISSUE TITLE
Request to List XOXO Tokens

### ISSUE THREAD

**Issue by bitxoxo1** [forkdelta/tokenbase#1146]
1. The contract address - **0x222139425Bcb172721dd4c22c29DD841D4358f69**

2. A link to the token issuer's official website. - [https://www.bitxoxo.exchange](https://www.bitxoxo.exchange)

3. 1-3 sentences for the token's description: at least one on the token issuer (eg., the product they are building) and one on token role.

_Bitxoxo is India's Largest cryptocurrency exchange operating since 2016 with over 100,000+ customers. We provide our customers with fastest platform for trading. Bitxoxo is OTC Based exchange. Recently, we got incorporated in Australia and in a process to complete all the legal compliances and our Australian exchange will be operational by Q3 2018._

**Advisors:**

**Roger Ver**, CEO, Bitcoin.com
**Mate Tokay**, COO, Bitcoin.com
Janya Eighani, Managing Partner, Lehman Walsh Lawyers, Australia
Stephen Drew, Investment Banker in Wall Street
Sydney Ifergan, Online Marketing Expert with over 20+ year experience
Bruce Jeong, COO, New York Consulting Group
Laura Zaharia, International Relation Expert
Robby Schwertner, International Event Advisor
Boris Otonicar, Blockchain Specialist BVS

**Team** 

**Hesham Rehman**, CEO & Co-Founder Bitxoxo Bitcoins Online Pvt. Ltd.
**Mohammed Rezwan**, COO & Co-Founder Bitxoxo Bitcoins Online Pvt. Ltd.
Mohammed Sadiq, CTO
Archit Tyagi, Principal Partner
Salvina Samson, Certified Bitcoin Professional 
Tippu R., Blockchain Engineer
Sulabh Tyagi, Legal Head 
Annabelle Malhotra, Content & Media Planner 
Ruz Vasakovna, UI/UX designer, Digital Marketing Consultant
Palak Malik, Public Relations Manager

4. A link to an official page confirming the above contract address: this needs to be on the official domain of the token issuer. - [https://www.bitxoxo.exchange](https://www.bitxoxo.exchange)

5. Links to third-party reviews or discussion of the token or the token issuer of at least two distinct kinds, including, but is not limited to: articles in the media, independent third party blogs, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments from high ranked users in BitcoinTalk, etc. These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels).

a. [https://bitcoinexchangeguide.com/bitxoxo-cryptocurrency-exchange-ico-xoxo-token/](https://bitcoinexchangeguide.com/bitxoxo-cryptocurrency-exchange-ico-xoxo-token/)

b. [https://www.youtube.com/watch?v=o4afl_flsnE](https://www.youtube.com/watch?v=o4afl_flsnE)

c. [https://www.cryptocamacho.com/the-fastest-growing-crypto-exchange-could-bitxoxo-exchange-overtake-binance/](https://www.cryptocamacho.com/the-fastest-growing-crypto-exchange-could-bitxoxo-exchange-overtake-binance/)

d. [https://themerkle.com/indias-largest-crypto-exchange-bitxoxo-announces-tge/](https://themerkle.com/indias-largest-crypto-exchange-bitxoxo-announces-tge/)

**Comment by freeatnet** [comment]
Thank you for your request, @bitxoxo1! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please clean up your request so that it follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
