### ISSUE TITLE
Request to list Snowball Coin (SNBL)

### ISSUE THREAD

**Issue by gamelimited** [forkdelta/tokenbase#1147]
Token address:
0x198a87b3114143913d4229fb0f6d4bcb44aa8aff

Issuer's official website:
https://onlinegamecoin.com/

Description:

The Snowball coin(SNBL) is a token that we will issue on the Ethereum blockchain.
It is a crypto currency that will be able to be used for all kinds of entertainment.
To be specific, we plan to make the Snowball coin usable for online games, shopping, travel, concerts, events, sports watching, and asset management.

A link to the official contract address confirmation:

https://onlinegamecoin.com/about/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

Bitcointalk：https://bitcointalk.org/index.php?topic=3636991
Twitter：https://twitter.com/snowball_coin

**Comment by freeatnet** [comment]
Thank you for your request, @gamelimited! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by gamelimited** [comment]
Update comment.
