### ISSUE TITLE
Listing request for IMPs (Ether Kingdoms crypto-game)

### ISSUE THREAD

**Issue by VladGoldberg** [forkdelta/tokenbase#1148]
1. Token address: 0x48ff53777f747cfb694101222a944de070c15d36

2. Issuer's official website: https://imps.me

3. Description: 
Ether Kingdoms is a new crypto-game with own ERC20 token, IMP. The game makes it possible for the player to have constant profits, much like with POS coins – you can mine new IMPs in the Kingdoms mines. In order to raise their mining reward, players have to participate in PvP battles. There is no ICO for this game, fair airdrop distribution only.

4. A link to the official contract address confirmation: https://beta.imps.me/stats

5. Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
a. https://themerkle.com/ether-kingdoms-announce-airdrop-and-the-all-new-imp-token/ 
b. https://coinidol.com/ether-kingdom-game-announces-airdrop/
c. https://bitcointalk.org/index.php?topic=4087326.0
d. We also have pretty active community on Telegram chats: https://t.me/imptoken and https://t.me/imptoken_ru - most of community reviews are available there.

**Comment by freeatnet** [comment]
Thank you for your request, @VladGoldberg! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.
