### ISSUE TITLE
New Token Listing - YCC

### ISSUE THREAD

**Issue by OurnadHuan** [forkdelta/tokenbase#1149]
Hi ForkDelta Team,

This is Winnie from Yuan Chain (YCC) team. We are primarily focusing on using blockchain technology to support corporate-level clients with supply chain finance/management solutions, and we have done many related projects successfully. 

Our token - Yuan Chain Coin (YCC) has just listed on Hitbtc.com, and we are looking for listing on another influential crypto exchange. That's why I am reaching out to you and see if you would consider this. Please find more information about our projects at our official site: 
https://www.yuan.org/

I am looking forward to discussing our project with you and the possibility of YCC listing on your exchange, thank you!

Best regards,
Winnie
Yuan Chain team

**Comment by freeatnet** [comment]
Thank you for your request, @OurnadHuan! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
