### ISSUE TITLE
Add MBYZ Coin (MBYZ) 

### ISSUE THREAD

**Issue by MbyzCoins** [forkdelta/tokenbase#1151]
Contract address: 0x993890F752FD0F3D37c8bC5f3262C86b80d7c415

Issuer's official website: https://mbyz.io/eu.html

Description: We will give technological security support to help in the BlockChain technology and the issue of the Tokens, that does not permit us to make equivalences in our platform to unify criteria between users, We want to allow the common user to acquire goods and services directly with their currency. We would only be a means agreed between the parties to establish a price equivalence.
In summary, our differentiator, is a plan of income distribution among non-mining users, for the viralization of consumption.

Official contract address confirmation: 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
•	Blog link
o	http://mbyzico.blogspot.com/ 
•	BitcoinTalk announcement link
o	https://bitcointalk.org/index.php?action=profile;u=2085659
•	Reddit link
o	https://www.reddit.com/user/MBYZICO
•	Twitter profile
o	https://twitter.com/ByzCoins
•	Facebook product page
o	https://www.facebook.com/mbyzcoins/
•	Telegram channel or chat room link
o	t.me/mbyzcoin
•	Youtube intro video link
o	https://www.youtube.com/watch?v=qVfXpe7Esqg 
•	Youtube channel link
o	https://www.youtube.com/channel/UCBmJQEloAEV_C3uur8ho1LQ 
•	Instagram
o	https://www.instagram.com/mbyzcoin/
•	Initial Coin List
o	http://www.initialcoinlist.com/ico/mbyz/

**Comment by freeatnet** [comment]
Thank you for your request, @MbyzCoins! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
