### ISSUE TITLE
Listing VRS token

### ISSUE THREAD

**Issue by mars130** [forkdelta/tokenbase#1153]
1) The contract address: 

0x92e78dae1315067a8819efd6dca432de9dcde2e9
--

2) A link to the token issuer's official website: https://vedh.io/

3) Token's description:  VEROS DIGITAL HEARTS - a fundraising unique platform for noncommercial organizations, companies, events and commercial projects aimed at improving of life and the environment using blockchain technologies.

4) A link to an official page confirming the above contract address:  https://vedh.io/

5) https://bitcointalk.org/index.php?topic=3395510.0

Additional information:

Coinmarketcap: https://coinmarketcap.com/currencies/veros/#markets

Mail: tech@vedh.io and team@vedh.io

Explorer :https://etherscan.io/token/0x92e78dae1315067a8819efd6dca432de9dcde2e9

Telegram : https://t.me/veros_coin

Twitter: https://twitter.com/Veros_currency

Facebook: https://facebook.com/verosDH

**Comment by Kryptoniq** [comment]
#1020
