### ISSUE TITLE
MADToken

### ISSUE THREAD

**Issue by btclabs09** [forkdelta/tokenbase#1155]
1. Contract Address - 0x5b09a0371c1da44a8e24d36bf5deb1141a84d875

2. Token Website - https://madnetwork.io/

3. The purpose of MADToken is provide a universal medium of exchange to incentivize beneficial behavior. It allows actors in the privacy model to: send cryptographically secure, confidential micropayments between advertisers, agents and publishers; to stake real value behind the commitments which encourage the efficient collaboration within the network; and to reward experimentation which yields beneficial innovations for the network. MADToken's are the internal fuel of the MAD Network, a privacy-first protocol for the programmatic advertising industry. MAD Network is being built by an existing blockchain software company, MadHive. MadHive is headquartered in NYC.

4. Address Confirmation - https://madnetwork.io/token-faq

5. Helpful Links - https://www.nasdaq.com/article/walled-gardens-and-bad-neighbors-madhives-blockchain-based-ad-tech-solution-cm761324

https://www.adweek.com/digital/heres-what-facebook-might-be-exploring-when-it-comes-to-blockchain-technology/

https://www.forbes.com/sites/alanwolk/2018/05/23/adam-helfgott-wants-advertisers-to-stop-pushing-ads-onto-people/#34b724cd25aa

https://www.martechadvisor.com/articles/ads/the-end-of-an-era-say-goodbye-to-openrtb-its-time-to-burn-it-down/

**Comment by freeatnet** [comment]
Thank you for your request, @btclabs09! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.
