### ISSUE TITLE
MyBit (MYB) Listing Request

### ISSUE THREAD

**Issue by MyBitIO** [forkdelta/tokenbase#1158]
1. Contract Address: 0x5d60d8d7eF6d37E16EBABc324de3bE57f135e0BC
2. Official Website: [MyBit.io](https://mybit.io/)
3. MyBit is building an investment platform for IoT Assets that fully automates the investing process with smart contracts which creates a faster, cheaper, and more secure user experience. They are all building a Decentralised Asset Exchange for tokenising existing IoT assets such as solar farms, smart real estate, and various machines. The Token is used as an access layer and requires a small amount to be burnt for a user to gain access to the core features of the platform.
4. Here is our [github](https://github.com/MyBitFoundation/MyBitToken) which we verified proof through [Keybase](https://keybase.pub/mybit_dapp/) [here](https://twitter.com/MyBit_DApp/status/993879392433602560)
5. MEDIA
[Forbes](https://www.forbes.com/sites/omribarzilay/2017/08/14/why-blockchain-is-the-future-of-the-sharing-economy/#433958173342)
[NasDaq](https://www.nasdaq.com/g00/article/blockchain-technology-could-disrupt-and-reboot-the-sharing-economy-cm836757?i10c.encReferrer=&i10c.ua=1&i10c.dv=14)
[TNW](https://thenextweb.com/contributors/2017/09/21/blockchain-tech-missing-link-success-iot/)
[Express](https://www.express.co.uk/finance/city/915842/cryptocurrency-news-dow-jones-what-could-collapse-mean-bitcoin-ripple-ethereum)
[CCN](https://www.ccn.com/ground-success-story-mybit/)
[Dapp.tech](https://dapp.tech/best-undervalued-crypto-coins-tokens-feb-2018/)
[Analysis: Hacked](https://hacked.com/ico-analysis-mybit/)

**Comment by freeatnet** [comment]
@MyBitIO Thanks for your request Ian! Looks like @kyledewy beat you to it in #1119. The new contract address has gone live yesterday in #1222.
