### ISSUE TITLE
Listing Request for Bitcoin Crown Token 

### ISSUE THREAD

**Issue by Bitcoincrown** [forkdelta/tokenbase#1160]
**Token address:** https://etherscan.io/token/0xc0c05862cca68b0b4c806796a6e7d965a6f18095

**Issuer's official website:** https://www.bitcoincrowncoin.com/

**Description:**  Cryptocurrency for online game lovers. 

**A link to the official contract address confirmation:**  https://www.bitcoincrowncoin.com/Buytoken.html

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=3509873
2. https://www.facebook.com/BitCoinCrownofficial/reviews

**Comment by Kryptoniq** [comment]
#823
