### ISSUE TITLE
Bankera Token Listing

### ISSUE THREAD

**Issue by Stephen-Wisniewski** [forkdelta/tokenbase#1161]
Token address: 0xC80c5E40220172B36aDee2c951f26F2a577810C5

Issuer's official website: https://bankera.com/

Description: Bankera will be launching their own exchange. To provide utility for BNK (Bankera tokens), the trading of all pairs including BNK will be free on their exchange, i.e., it will be more cost efficient to buy BNK with BTC and then sell BNK for ETH, rather than buying ETH with BTC directly.

A link to the official contract address confirmation: https://blog.bankera.com/2018/05/25/now-you-can-withdraw-your-bnk-tokens/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1.  https://www.youtube.com/watch?v=h-IhwJErmig
2. https://www.youtube.com/watch?v=6g09zgutSKQ

**Comment by freeatnet** [comment]
Thank you for your request, @Stephen-Wisniewski ! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
https://coinmarketcap.com/currencies/bankera/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xc80c5e40220172b36adee2c951f26f2a577810c5,  https://bankera.com/

**Comment by therealMikkoK** [comment]
Token is in violation with terms of ForkDelta, VP of Business Development Craig Grant.
Craig Grant is a known scammer.
Token will not be on ForkDelta.

**Comment by therealMikkoK** [comment]
Opened issue, due diligence
