### ISSUE TITLE
add RichGold ( RIG )

### ISSUE THREAD

**Issue by yoshiekiura** [forkdelta/tokenbase#1163]
Name: RichGold
Symbol: RIG
Address: 0xe50d77286df6f530f678ede08d2e0d764c09a2c7
Decimals: 8
Email: contact@urichie.com
Website: https://urichie.com
Github: https://github.com/urichie-project/richgold

Description: URICHIEGOLD is a next generation crypto currency. It is a
tradeable ERC20 token that resides on the
Ethereum blockchain.

**Comment by Kryptoniq** [comment]
Token created 1 day ago.
Smart contract not verified. 
Tokens distributed to four addresses belonging to the owner. 
Starts ICO. 
No third party review. 
Sorry, we can't list your token at this time.
