### ISSUE TITLE
add UET

### ISSUE THREAD

**Issue by raymaker** [forkdelta/tokenbase#1164]
I would like to apply for USELESS ETHEREUM TOKEN. Currently traded in HITBTC

I would say, it is one of the Top 10 famous Tokens all time. If you search the Internet you will find tons of reviews and articles. 
https://www.google.de/search?q=useless+ethereum+tokens+news&oq=useless+ethereum+tokens+news&aqs=chrome..69i57.4837j0j4&sourceid=chrome&ie=UTF-8
No other tokens are mentioned so many times

Most importantly, it is the first token without any utilization, dev, team or whats ever. It has still has a quite of value. It will remain famous even in 10 Years

https://uetoken.com/
https://github.com/uetoken
https://www.reddit.com/domain/uetoken.com/
https://twitter.com/uetoken

Contract:
0x27f706edde3aD952EF647Dd67E24e38CD0803DD6

Decimals | 18
-- | --

**Comment by Kryptoniq** [comment]
The token's smart contract is vulnerable and we'll not be listing it until everything is resolved. 
https://medium.com/coinmonks/uselessethereumtoken-uet-erc20-token-allows-attackers-to-steal-all-victims-balances-543d42ac808e
