### ISSUE TITLE
Webcoin Token Listing

### ISSUE THREAD

**Issue by icocalendartoday** [forkdelta/tokenbase#1165]
**Token information:**
Name of the token: Webcoin
Symbol of the token : WEB
Precision (decimals) : 18
Token address: 0x840fe75abfadc0f2d54037829571b2782e919ce4
ENS address: webcointoken.eth
Algorithm: ethash 
Number of blocks: 5265492
Dev Language: solidity
Block time: 1521202649
Type: ERC20
secp256k1 ver: Yes
Source link(github): https://github.com/webcoinico/Webcoin-Digital-Marketing-2.0
Explorer: https://etherscan.io/address/0x840fe75abfadc0f2d54037829571b2782e919ce4

Issuer's official website: https:/webcoin.today

Description: Webcoin connects the worlds of digital marketing, blockchain technology and cryptocurrency. Webcoin is a utility ERC20 token based on the Ethereum blockchain and serves the purpose of a unified currency for buying and selling services within the Webhits.io platform.

A link to the official contract address confirmation: https://webcoin.today/#/ [under the Token section]

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://www.youtube.com/watch?v=i8J6IDP1cfY
https://www.ccn.com/webcoin-pioneers-the-technological-dawn-of-global-digital-marketing/
https://blockonomi.com/webcoin-ico/
https://www.fxempire.com/news/article/icobay-net-announces-the-launch-of-the-largest-icos-directory-rating-platforms-group-480549

**Comment by icocalendartoday** [comment]
Team,
We already successfully trading on IDEX and Token.Store:
https://token.store/trade/WEB
https://idex.market/eth/web

When can we expect a listing on ForkDelta?

**Comment by freeatnet** [comment]
Hi @icocalendartoday! Thanks for submitting a request to add a token. It looks like there's already a request for the same token here: #662. If you have additional information about this token, please post it in comments for #662. I'm closing this issue to keep all information about the same token in one place.

Thanks again!
