### ISSUE TITLE
Please list 42-coin

### ISSUE THREAD

**Issue by 42coin** [forkdelta/tokenbase#1166]
**Address:** 42coin.Business@gmail.com

**Website:** https://42-coin.org/

**Description:** 42-coin is the rarest cryptocurrency ever created with just 42 in circulation, making it very stable and great long term investment. Unlike other coins, 42-coin will never increase its supply, there will always be just 42 coins. 42-coin is an honest coin that was never pre-mined and did not have an ICO. It is an already established cryptocurrency that is listed on livecoin and had an article written on by businessinsider.com! 

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. http://www.businessinsider.com/introducing-42coin-2014-1
2. https://ghost.report/2017/06/07/what-is-42-coin-and-is-it-a-good-cryptocurrency-investment/

**Comment by freeatnet** [comment]
Thank you for your request, @42coin! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.
