### ISSUE TITLE
Abandoning old STAKE contract

### ISSUE THREAD

**Issue by StakeItToken** [forkdelta/tokenbase#1167]
Hi there,

StakeIt (STAKE) recently had a smart contract breach with over 70m+ tokens being stolen. Therefore, we have decided to abandon the old token contract. Would it be possible for you to rename the current STAKE as (STAKE OLD) and re-list STAKE to our new token contract?

Thank you.

New token contract address: 0x7d266ed871f24d7b47b5a8b80abb391178c48bac
Decimals: 8
Ticker: STAKE

Should you have any questions or doubts, please contact us at:
support@stake-it.com

**Comment by freeatnet** [comment]
Supporting info:
https://www.stake-it.com/ links to https://medium.com/@stakeit, which has the following posts: 

* https://medium.com/@stakeit/staking-smart-contract-breach-token-swap-information-136348732b26
* https://medium.com/@stakeit/how-to-stake-new-token-details-133c34fa5215

**Comment by StakeItToken** [comment]
Hi there,

Any updates to this issue? Thank you.
