### ISSUE TITLE
Add FriendZ token to ForkDelta

### ISSUE THREAD

**Issue by nigarchalabi** [forkdelta/tokenbase#1169]
Dear team of ForkDelta,

My name is Nigar and I am representative for FriendZ project.

We would like to add FDZ token to ForkDelta

1) The contract Address: 0x23352036e911a22cfc692b5e2e196692658aded9
2) Website: www.friendz.io
3) Description: Friendz is a working product with €1.5m in revenues, a team of 40 employees and a community of 250k users. Friendz platform connects companies to people willing to provide support in the generation of advertising contents directly posted on their personal social media profiles. Users involved in this peer-to-peer communication process get rewarded for their collaboration through our FDZ tokens. FDZ will be the standard token to manage and reward people for online activities.

WP: https://friendz.io/file/whitepaper_icofriendz.pdf

Social Media: 

- Telegram Group: 76,000 users
- Telegram Channel: 57,000 users
- Facebook page: 51,000 fan
- Twitter: 56,000 follower
- Instagram: 19,000 follower 

App download:

- Download: 247,000
- Monthly Active Users: 43,000

ICO results:

- 14,000 contributors
- 21,000 holders
- 31,000 ETH raised

4) Link to etherscan: https://etherscan.io/token/0x23352036e911a22cfc692b5e2e196692658aded9#balances

5) Review: https://icobench.com/ico/friendz ,  https://coinmarketcap.com/currencies/friends/, https://cryptobriefing.com/friendz-ico-review-fdz-token-rating/ , https://icocrunch.io/ico/friendz/
--

**Comment by freeatnet** [comment]
Thanks for your request, @nigarchalabi! Looks like there is already a request to add FDZ: #1134. I'm closing this issue to make sure all information is in one place.
