### ISSUE TITLE
List FOXT Token

### ISSUE THREAD

**Issue by foxglobaltrading** [forkdelta/tokenbase#1170]
Please, consider listing our FOXT Token. Find below all required details:

Token address: 0xFbe878CED08132bd8396988671b450793C44bC12

Issuer's official website: https://foxtrading.io/

Description: Fox Trading is limited, exclusive and easy to use trading signals service for Forex and Cryptocurrency. FOXT token will give investors direct access to future Fox Trading platform, and will be necessary to purchase products on it like indicators, robots, guides… or unlock features like Autotrading system.

Official contract address confirmation: https://foxtrading.io/#token

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.ccn.com/cryptocurrency-specialists-fox-trading-launch-exciting-ico-presale-via-smart-trading-platform/
2. https://icobench.com/ico/fox-trading
3. https://hype.codes/forex-and-crypto-trading-revolutionized-blockchain
4. https://blog.icoalert.com/ico-alert-report-fox-trading-e43f57b9bba4
5. https://www.trackico.io/ico/fox-trading/
6. https://bitcointalk.org/index.php?topic=2822026.0

**Comment by freeatnet** [comment]
Thank you for your request, @foxtrading! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by foxtrading** [comment]
Thanks for your reply @freeatnet! Will be waiting for further notifications.

**Comment by mariobag** [comment]
muy buen proyecto
