### ISSUE TITLE
Listing Clock Network 

### ISSUE THREAD

**Issue by bahira** [forkdelta/tokenbase#1174]
Contract address: 0xff73cec3e7c4498a2d6a080997335bdbaabb2b09

Issuer's official website: https://clock.network/

Official contract address confirmation: 0xff73cec3e7c4498a2d6a080997335bdbaabb2b09

A link to a third-party review or discussion of the token:
Bitcointalk: https://bitcointalk.org/index.php?topic=4328491.0
Telegram: https://t.me/clocknetwork
Description: Clock Network is a disruptive fast and secure ethereum token designed to revolutionize the entire blockchain market. Earning tokens by doing your daily entertaining activities. Our team are fond of the UBI model. Watch your favorites TVShows, Listen to music, Play and get some CLOCK

**Comment by freeatnet** [comment]
Thank you for your request, @bahira! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer.

Reviews must include review of project vision, team, milestones, or existing product.
Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
