### ISSUE TITLE
Please List Autralia token

### ISSUE THREAD

**Issue by master600** [forkdelta/tokenbase#1175]
Contract:0x7a1B6787b682CB38998924089039eeC19a5e8C0D
Website: www.australiatokens.com

Australia Token is an ecosystem intended to solve problem associated with traditional banking. It allows users to get rid of all the problems associated with traditional financial system by providing them with a decentralized exchange of digital data between its peers featuring an incorruptible ledger recording all transactions

Contract address: https://etherscan.io/address/0x7a1b6787b682cb38998924089039eec19a5e8c0d

https://bitcointalk.org/index.php?topic=3339086.0
https://bitcointalk.org/index.php?topic=3340011.msg34951851#msg34951851

*

**Comment by freeatnet** [comment]
Thank you for your request, @master600 ! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by master600** [comment]
Ok Thank you!

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
