### ISSUE TITLE
List of unique project - OMGCatCoin

### ISSUE THREAD

**Issue by arthur88** [forkdelta/tokenbase#1176]
**The contract address**: 0x37D82a4e03E93529c1A32429984E12e7875Ea1D8
**website**: http://omgcatcoin.com
**Description**:
Firstly OMGCatCoin was fun and friendly cryptocurrency. Lately it evolved into blockchain based homeless cat platform & digital currency where any user will be able to donate some amount of OMGCat Coins to cats or to shelters. 

**Whitepaper**: http://omgcatcoin.com/docs/omgcatcoin_whitepaper.pdf
**Social**:
https://bitcointalk.org/index.php?topic=3627706.0
https://www.facebook.com/OMGCatCoin-2019774848285879/
https://t.me/omgcatcoins
https://twitter.com/OMGCatCoin

**Contact**: hi@omgcatcoin.com

**Symbol**: OMGCAT
**Type**: ERC20
**Decimals**: 18
**Initial Value**: 1 ETH = 1,000 OMGCAT
**Token Supply Cap**: 100,000,000,000 OMGCAT
**EtherScan**: https://etherscan.io/address/0x37d82a4e03e93529c1a32429984e12e7875ea1d8

**Comment by freeatnet** [comment]
Thanks for submitting a request to add OMGCatCoin, @arthur88! Looks like there's an earlier request for OMGCatCoin here: #1100. I'm closing this request to keep all information in one place, and I kindly ask you to repost information in the original request's thread.

Thanks again!
