### ISSUE TITLE
MIO Token listing

### ISSUE THREAD

**Issue by geebe** [forkdelta/tokenbase#1177]
0x141044ccc363d6e8d92dd8983422775913e304ec

MIO ERC20 token

https://minerone.io/

Miner One is a cutting-edge, crowdfunded bitcoin mining operation built and managed by a team of data centre industry experts on behalf of the Miner One Community. Miner One Community Members contribute to building mining centres and share the output transparently using Ethereum-based “smart contracts”.

https://medium.com/@minerone.io

https://etherscan.io/address/0x141044ccc363d6e8d92dd8983422775913e304ec

**Comment by freeatnet** [comment]
Thank you for your request, @geebe! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
