### ISSUE TITLE
Confusion relating to PXBRL

### ISSUE THREAD

**Issue by nico1579** [forkdelta/tokenbase#1178]
Hi, 
I'm the founder and CEO of Populous World. Although we are extremely grateful for listing our PXT token, we are experiencing frustration amongst many members of our community who cannot find the correct PXT token. PXT is currently listed on ForkDelta under PXBRL, this I assume is because the current PXT listed before us once they knew our proposed ticker name. We find this strange and a deliberate attempt to misled those who wish to trade our true PXT token and therefore purchase the wrong PXT token on ForkDelta.

As you will see on Etherscan our ticker is the true PXT ticker with 9020 holders and trades actively.
https://etherscan.io/address/0xc14830e53aa344e8c14603a91229a0b925b0b262#code

ProsperipropToken listed on ForkDelta with only 128 members registered holders compared to our 9020 holders, currently does not display on their website any mention of PXT token or the ProsperipropToken white paper or patent. It currently redirects to https://www.dreamblock.com/ from https://prosperiprop.com/

Here is their ETH address 0xaf146fbd319ca7ae178caa2c9d80a2db6b944350 and their website address can be found on Forkdelta. 

I would now like to propose several options and hope we arrive at a solution that suits us all.

1. Rename our PXT token from PXBRL to PXT and rename ProsperipropToken PXT2 or another ticker.

2. Remove PXBRL from ForkDelta because we will never market our token as PXBRL and this will lead to continued confusion amongst our huge number of token holders and supporters. 

3. Rename the current PXT token allowing users of ForkDelta to clearly see that it is not our PXT token they wish to trade. 

4. Rename our token from PXBRL to PXTPopulous.

We are now seeking to list PXT on other exchanges under the ticker PXT and we hope that ForDelta will play a huge part in the growth of the PXT like ForkDelta & EtherDelta did for PPT and so many other cryptocurrency tokens that are now among the top tokens within our crypto space.

Best regards,

Steve Nico Williams

Founder & CEO

Populous World
https://populous.world

e: info@populous.co

**Comment by freeatnet** [comment]
@nico1579 Hello Steve. Indeed, the ticker was assigned because it was conflicting with an existing token. Before we continue, could you please verify your identity by signing a quick message like "Identity verification for issue Confusion relating to PXBRL #1178" with the token creator key (0x010549e5875e00af529edf814d37e31c1752ecbc)? The signature should be verifiable by https://etherscan.io/verifySig.

**Comment by nico1579** [comment]
I can send PXT from this address 0x010549e5875e00af529edf814d37e31c1752ecbc to verify who I am. Please provide an ETH address and I will do it now.

**Comment by nico1579** [comment]
Just managed to sign this message. https://etherscan.io/verifySig/1160

**Comment by freeatnet** [comment]
Signature checks out, thank you!

It's a tricky situation. The token currently occupying PXT was inherited from EtherDelta token list; plus, as you pointed out, the circumstances of the original project seem to have changed significantly. Let me reach out to the other project and see what their deal is. I'll get back to you within a couple days.


/remind me to get back to this June 1

**Comment by nico1579** [comment]
Hi, any update to this ticket?

**Comment by freeatnet** [comment]
@nico1579 I've contacted the other project. They've gone through an ownership change; however, they still plan on using the current token / symbol. I think the safest course of action would be renaming PXBRL -> PXTPopulous.

**Comment by nico1579** [comment]
Okay change it to PXTPopulous. Also would you mind looking at issue #1186 & #1187 and approving both those listing requests. Thanks

**Comment by freeatnet** [comment]
@nico1579 Sorry for the delay. The change will be rolled out on **Tuesday, June 26th**.
