### ISSUE TITLE
Add 	Stream Network Token (ST)

### ISSUE THREAD

**Issue by StreamNetwork** [forkdelta/tokenbase#1179]
Contract address: https://etherscan.io/token/0x873467738B5053F155639208B7495318FCEd5262
Symbol: ST
Decimal: 18
Issuer's official website: https://www.streamnetwork.net

Official contract address confirmation: https://www.streamnetwork.net

A link to a third-party review or discussion of the token:
https://fb.me/StreamNetworksSTRN
https://twitter.com/StreamNetworksc
https://t.me/joinchat/GEyeNw5hssJeywtzhL9iUQ
https://medium.com/@streamNetworks
https://www.reddit.com/user/streamnetworkscm

Description:
StreamNetwork builds an online video network that combines the best tools to create your own content. Live broadcast, record, publish, manage, and measure all from a single integrated platform. Produce live streaming and on-demand video that can be embedded on a website, hosted on an included channel page or shared over a social network for added engagement. Whether you’re streaming to social or producing an event streamed around the world, our hardware and software are designed to make you look like a pro.

Please list!

**Comment by freeatnet** [comment]
Thank you for your request, @StreamNetwork! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide links to at least independent 2 third-party reviews of your project.
