### ISSUE TITLE
Listing Accord on Forkdelta

### ISSUE THREAD

**Issue by accordtoken** [forkdelta/tokenbase#118]
Contract Adress : 0x75aa7b0d02532f3833b66c7f0ad35376d373ddf8
Website: https://accordtoken.com
Official confirmation : Source code is verified on etherscan.io with all official links to website and SM forums
https://etherscan.io/token/0x75aa7b0d02532f3833b66c7f0ad35376d373ddf8
Links to a third-party review or discussion of the token:
https://bitcoinexchangeguide.com/accord-ard-token-ico/
https://www.coinmarketplus.com/token/accord-token/
https://icobench.com/ico/accord-ico
https://icoholder.com/en/accord-ico-17774
Name: Accord
Symbol: ARD
Decimal: 18
Description:
Accord is a new digital currency on Ethereum blockchain, regulated by the ERC20 smart contract,
intended to use as primary currency on Accord hedging platform (AHP). AHP is aimed to mitigate the
risk available on digital currencies, by applying existing tools of financial market and to provide the
maximum trade profits on digital currency with controlled risk by providing traders with Hedging
Options.

**Comment by accordtoken** [comment]
Social links
Twitter: https://twitter.com/Accord_Token
Medium: https://medium.com/accord-ard   
Reddit: https://www.reddit.com/r/AccordToken/ 
Bitcointalk: https://bitcointalk.org/index.php?topic=2828435.msg28990035#msg28990035
Facebook: https://www.facebook.com/AccordToken/  
Telegram:  https:/t.me/AccordToken

**Comment by JonathonDunford** [comment]
DO you have any official documents showing or linking to the contract address? Etherscan doesn't count.

**Comment by accordtoken** [comment]
If you can provide us with your E-Mail, we will send you an email from website domain verifying contract address. 
Or you can check on bitcointalk thread. 
??

**Comment by accordtoken** [comment]
Contract address can also be verified on whitepaper (First page) 
https://accordtoken.com/Accord-white-paper-V1.0.3.pdf

**Comment by JonathonDunford** [comment]
Verified: 0x75aa7b0d02532f3833b66c7f0ad35376d373ddf8

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
