### ISSUE TITLE
Add Inspeer (INSP)

### ISSUE THREAD

**Issue by bg4erem** [forkdelta/tokenbase#1181]
Hi team!

Kindly review the INS token

1) Token contract: https://etherscan.io/token/0xe1a26d61f8ac0d22a355edbc5053f01c5992190c
2) https://inspeer.io/
3) Inspeer is a peer-to-peer lending service that works with cryptocurrency and fiat. Token represents the right to receive a part of Inspeer distributable profits.
4) Official Twitter: https://twitter.com/inspeer_io/status/929544273086775296?lang=bg
5) https://bitcoinexchangeguide.com/inspeer/
https://www.youtube.com/watch?v=wRnCJz1B950
https://www.youtube.com/watch?v=Tn9oJ_XKEas
https://tokenguru.net/ico/inspeer-ico-review/

**Comment by freeatnet** [comment]
Thank you for your request, @bg4erem! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Hi @Bg4erem, there are some concerns that are yet to be addressed by Inspeer https://bitcointalk.org/index.php?topic=2234122.640.
