### ISSUE TITLE
Add Sancoj (SANC)

### ISSUE THREAD

**Issue by NgoziEmeh** [forkdelta/tokenbase#1182]
Token address: https://etherscan.io/address/0x03eC7BB59be036870eF696A2abF124f496d6735A

Issuer's official website: https://www.sancoj.com/

Description: Sancoj is a platform that brings all opportunities like jobs, events,in one place and uses Artificial Intelligence to predict and suggest the most profitable opportunities to user.
Sancoj Token is an ECR20 token that will be used to buy,sell, get opportunities on the Sancoj platform.

A link to the official contract address confirmation: https://www.sancoj.com/tokensale

Links to third-party reviews or discussion of the token, the project/product, or the token issuer: 

https://cryptostocksreviews.org/sancoj-the-worlds-first-opportunity-supermarket/news/

http://foxicoreviews.blogspot.com/2018/03/sancoj-review-world-first-opportunity.html

https://www.misstech.xyz/sancoj-alpha-version-is-live/informatique/11950/14/05/2018/

**Comment by freeatnet** [comment]
Thank you for your request, @NgoziEmeh! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please clean up your request so that it follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by NgoziEmeh** [comment]
My request has been edited.

Thanks.

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. **Reviews must have original third-party research** and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* **We are looking for substance in reviews.** BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases or **sponsored articles do not constitute third-party review**.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by NgoziEmeh** [comment]
We have changed an updated the links.
