### ISSUE TITLE
Listing GBPp 'GBP Poken'

### ISSUE THREAD

**Issue by nico1579** [forkdelta/tokenbase#1186]
GBPp is the official Populous Platform GBP stable token. This is a stable GBP profit token given to those who profit from invoice trades on the Populous Invoice Platform. We officially request that it be listed on ForkDelta.

Name: GBP Poken
Symbol: GBPp
Contract adress: 0x509B4688407e2dD0A3Fc35E9E64fcC8a3Ec72ab7
Website: https://populous.world/invoice-finance.html
Team: https://populous.world/company.html
Twitter: https://twitter.com/bitpopulous
Reddit: https://www.reddit.com/r/populous_platform/
Email: info@populous.co
Slack: http://bitpopulous.slack.com/

You can verify this an original request by joining our official Slack channel and speaking to myself or member of our admin team via https://bitpopulous.herokuapp.com. 

You can also verify this request by DM on Twitter either on our official Twitter handle or my Twitter handle https://twitter.com/iamstevenico

Best regards,

Steve Nico Williams
CEO & Founder
Populous World

**Comment by Kryptoniq** [comment]
Your contract code isn't verified and there seems to be some issues with it.
The total supply showing is 0 GBP coupled with zero token holders and zero transfer. .  
https://etherscan.io/token/0x509B4688407e2dD0A3Fc35E9E64fcC8a3Ec72ab7
