### ISSUE TITLE
Listing of XAUp 'Gold Poken'

### ISSUE THREAD

**Issue by nico1579** [forkdelta/tokenbase#1187]
XAUp is the official Populous Platform Gold token. This is a Gold token pegged to the daily price of gold. We officially request that it be listed on ForkDelta.

Name: Gold Poken
Symbol: XAUp
Contract adress: 0x31edbd48ff46c40cdbe4fd1cf500b23eebd6f826
Website: https://populous.world/invoice-finance.html
Team: https://populous.world/company.html
Twitter: https://twitter.com/bitpopulous
Reddit: https://www.reddit.com/r/populous_platform/
Email: info@populous.co
Slack: http://bitpopulous.slack.com/

You can verify this an original request by joining our official Slack channel and speaking to myself or member of our admin team via https://bitpopulous.herokuapp.com. 

You can also verify this request by DM on Twitter either on our official Twitter handle or my Twitter handle https://twitter.com/iamstevenico

Best regards,

Steve Nico Williams
CEO & Founder
Populous World

**Comment by Kryptoniq** [comment]
There are zero supply and token holders.
Contract source code not verified.
https://etherscan.io/address/0x31edbd48ff46c40cdbe4fd1cf500b23eebd6f826
