### ISSUE TITLE
Request to add CodeMailStamp (STPZ)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1188]
Hello,
Request for new token listing:

**Name**: CodeMailStamp
**Symbol**: STPZ
**Address**: 0x526B065477d57C0eB9a1644110aD66B9fb23235b

**Website**: https://codemail.tech/
**Description**:
CodeMail is a secure, private, anonymous, decentralized communication network built on blockchain technology that allows people across the globe to interact freely without the threat of exposure or invasion of privacy.
Stamps are the credits used to micro-transact over the CodeMail network, therefore allowing network access and facilitating communication.
**Website Token Contract Link**: https://codemail.tech/sale/
**Whitepaper**: https://codemail.tech/static/base/resources/whitepaper.pdf
**Bitcointalk**: https://bitcointalk.org/index.php?topic=3341061
**Twitter**: https://twitter.com/CodeMailTech

Please let us know if you need any further information.
Best Regards,

**Comment by freeatnet** [comment]
Thank you for your request, @codemailtech! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Provide links to at least 2 independent third-party reviews of your project.

**Comment by codemailtech** [comment]
Hello and thank you.
Here's two review links as you requested:
https://www.popularico.com/2018/06/06/codemail-ico-a-global-decentralized-communication-network/
https://bitcoinexchangeguide.com/codemail-global-decentralized-blockchain-communication-network/
Please let us know if you need anything else.
Best regards,

**Comment by codemailtech** [comment]
Hello,
Just checking in to see if you need any further information in order to proceed with the listing on ForkDelta.

STPZ are also now listed on two other DEXs:
https://token.store/trade/STPZ
https://tokenjar.io/STPZ

You can also now contact us via Telegram:
CodeMailTech Group: https://t.me/CodeMailTech
Or PM directly: https://t.me/CodeMail

Best Regards.
