### ISSUE TITLE
Add $PPI to list

### ISSUE THREAD

**Issue by RealPiedPiperCoin** [forkdelta/tokenbase#1189]
Hi Forkdelta team,

$PPI PiedPiperCoin has been one of the most actively traded coins on your platform over the last few weeks. Please consider adding our ticker to your list.

https://etherscan.io/address/0x69c4bb240cf05d51eeab6985bab35527d04a8c64

**Comment by RealPiedPiperCoin** [comment]
Bitcointalk - https://bitcointalk.org/index.php?topic=3660872.120
Twitter - https://twitter.com/piedpipercoin
Data - https://www.coingecko.com/en/coins/piedpipercoin
Website - Piperchain.io

**Comment by freeatnet** [comment]
The contract address appears to belong to OPEN (OPEN) by https://www.openfuture.io/. This probably needs to be refiled.

**Comment by jaggedsoft** [comment]
PPI (Pied Piper Coin) is located here https://etherscan.io/address/0x5a3c9a1725aa82690ee0959c89abe96fd1b527ee
HLI (Hooli Coin Blockchain) is here: https://etherscan.io/address/0x6baf7fcea90b0968dc5ed7b8dcb76c986637ff55
