### ISSUE TITLE
Listing Kachingcoins (KAC) on Forkdelta

### ISSUE THREAD

**Issue by alicetheanalyst** [forkdelta/tokenbase#1190]
Dear Forkdelta team,

My name is Alice, advisor of an ICO project called Kachingcoins. We are offering a utilisable token which can use on our 4 platform (Kaching.global - the social trading platform, Kaching.market - the forex broker, Kaching.exchange - the cryptocurrency exchange, and Kaching academy - the financial academy). We have reached our soft cap of 2 millions tokens sold last April and now with the rising demand of trading our token from the community, we would like to endorse KAC to be listed on Forkdelta. Could you advise us the listing procedure on your exchange. 

We look forward to hearing from your team soon.

Best regards,

Alice

**Comment by freeatnet** [comment]
Hi Alice, please check out https://www.reddit.com/r/ForkDelta/comments/7tntnz/how_to_get_an_erc20_token_listed_on_forkdelta/. Thanks!
