### ISSUE TITLE
Add a New Token

### ISSUE THREAD

**Issue by stsdaniella** [forkdelta/tokenbase#1191]
**Token address:**  0xca3ea3061d638e02113aa960340c98343b5acd62
**Issuer's official website:** https://bittwatt.com/
**Description:** Bittwatt is a matchmaking platform that connects all energy market players (from DSOs to consumers) and provides a standardized blockchain protocol for sharing relevant business information. Our platform enables energy exchange, trading and payment and acts as a clearing house for contracts concluded between producers (or suppliers) and final consumers. 
**Contract address:** https://etherscan.io/address/0xca3ea3061d638e02113aa960340c98343b5acd62 
**Discussion Links:**
   https://icomarks.com/ico/bittwatt
   https://cointelegraph.com/ico-calendar/bittwatt 
   https://foundico.com/ico/bittwatt.html
   https://bitcointalk.org/index.php?topic=3098153
   https://www.youtube.com/channel/UChYWjiPk7lS6DBuaXgsIy4A 
   https://icobench.com/ico/bittwatt
   https://icobazaar.com/v2/bittwatt
   https://www.newsbtc.com/2018/04/18/bittwatt-launches-electricity-trading-blockchain-true-real-time-pricing/
   https://www.coinspeaker.com/2018/04/19/bittwatts-smart-energy-grid-makes-renewable-energy-cost-competitive/
   http://coinbrokr.com/2018/03/19/bittwatt-the-21st-century-decentralized-energy-platform/ 
   https://www.yours.org/content/bittwatt---energy-for-the-21st-century-a77eaa7fa42c
   https://coinclarity.com/ico-events/bittwatt/
   http://coinsviewer.com/bittwatt-as-a-solution-for-energy-sector/ 
   https://icostock24.com/projects/bittwatt/
   http://www.rttnews.com/2883835/bittwatt-launches-electricity-trading-platform-on-the-blockchain.aspx
   https://icoshrimp.com/bittwatt-letting-the-electricity-flow-seamlessly-through-the-boundaries/

Token Details:
Every Bittwatt (BWT) token is backed by one kWh energy.

**Comment by freeatnet** [comment]
Thank you for your request, @stsdaniella! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
@stsdaniella 
Please clean up your request so that it follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
