### ISSUE TITLE
Lisiting on ECX (ECOIN) token 

### ISSUE THREAD

**Issue by ecoin20** [forkdelta/tokenbase#1192]
1. The contract address. - 0xBc35790614c07EBde4fDC9f5A10E33d92FF48867

2. https://www.facebook.com/ecxtoken

3. This is an utility token that being issue for the future project development and investment that can be share among the community. As current being, the token can be used for mobile recharge, paying of local utilities bill, and buy of mobile devices.

4. As the project is just kick off we are currently using the facebook page and telegram (https://t.me/ecxtoken)  for the community discussion. Webpage will be launch in the coming future.

5. The ecx token is still new in the market, we are on progress on this item. 

6. The purpose of request of listing - setting up and easy for for our trader and investor to find out token rather then searching with the contract address. 

Thank you very much
Isaac

**Comment by Kryptoniq** [comment]
1. 6 token holders
2. No website
3. No announcement thread or project review
I'm sorry, we can't list your token at this time. Thank you.
