### ISSUE TITLE
Request to list TAGCASH Token

### ISSUE THREAD

**Issue by LouisW1** [forkdelta/tokenbase#1193]
1. 0x08999f1237dea81da49c86bdbd0a1e72f7960328

2. http://tagcash.com/

3.a Token description: Tagcash Token(TAG) is the "fuel" that enables decentralized trading, asset issuance and usage, coupons, ticket, loyalty redemptions, and writing data streams to the Tagcash chain. In addition, Tagcash Tokens will be used for micropayments for other apps and software developed by Tagcash.

3.b Tagcash: A Digital Bank for a modern world. Tokenize anything of value. Permissioned blockchains to create, use, and trade tokens representing fiat money, cryptocurrencies and other assets. 

3.c Tagcash Token role: "fuel" that enables decentralized trading, asset issuance and usage, coupons, ticket, loyalty redemptions, and writing data streams to the Tagcash chain.

4. http://tagcash.com/aboutus.php

5. https://cryptovest.com/news/exclusive-philippine-blockchaincrypto-group-paves-the-way-for-self-regulation/

Founder of Tagcash speaking on a summit: http://blockchainasiaforum.com/

http://fintechnews.sg/16374/blockchain/blockchain-startups-philippines/

https://www.huffingtonpost.com/entry/the-pryze-of-blockchain-industry_us_5a51c267e4b0cd114bdb3412

http://fintechnews.sg/18434/philippines/coins-tagcash-racing-to-launch-first-crypto-order-book-exchange-in-ph/

https://cryptopop.net/2018/05/24/mark-vernon-the-tokenizer/

http://padcdi.org.ph/ , where Tagcash is a member of the association.

http://fintechph.org/ , where Tagcash is a member of the association as well.

**Comment by freeatnet** [comment]
Thank you for your request, @LouisW1! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
