### ISSUE TITLE
PLEASE LIST MOONLITE (MNL) 

### ISSUE THREAD

**Issue by Moonlite-ICO** [forkdelta/tokenbase#1194]
Good day, 

Please can we have MoonLite listed on ForkDelta 

1. Website: www.moonlite.io 
2. Email: team@moonlite.io 
3. Contract Address: 0x0d62dc6Cd8C81dCA8cAADcCF01FfE7C1F31D9402 (can be seen in the 'about us' section on www.moonlite.io)
4. Description: The MoonLite Project is a large scale crypto-mining project, which is currently building its first 21MW data center in Iceland. 100% of the energy used is from clean & green sources. The MNL token allows holders to vote in corporate actions and receive regular profit distributions. 
5. Links to articles & reviews: https://www.newsbtc.com/2018/01/09/moonlite-offering-investors-slice-bitcoin-mining-pie/  ;  https://www.icoexaminer.com/ico-reviews/moonlite/  ; http://bitcoinist.com/benefits-investing-moonlite-ico/ ; https://icobench.com/ico/moonlite  ; https://bitcointalk.org/index.php?topic=2712054.0;all

We have been trading our address on FD here: https://forkdelta.github.io/#!/trade/0x0d62dc6cd8c81dca8caadccf01ffe7c1f31d9402-ETH

We can be contacted on team@moonlite.io if needed 

Hope to get listed. 

Regards,
MNL Team

**Comment by Kryptoniq** [comment]
#650
