### ISSUE TITLE
Swisscoin

### ISSUE THREAD

**Issue by renens** [forkdelta/tokenbase#1196]
Hello, I am Andrea Edelman, I work for Swisscoin (SCN) (www.swisscoinlab.ch) and we would like to be listed on ForkDelta please.

We are a Swiss based company (Swisscoin GmbH) registered with FINMA (underway, not finished). We aim to make a hybrid wallet that takes fiat via use of ERC-20 captive tokens exchanged on a 1 to 1 basis with our partner bank (AlpenRose in Switzerland). 

We will be fully audited and all our accounts will be fully public in order to show our respect for the 1 to 1 exhange rates and ability to carry it out durably. Swiss stability and regulations also adds to the safety of the users. 

Our team page isn't up yet but we have ppt with the entire team should you wish to have more info.

Best,
Andrea Edelman

Smart contract address: 0x3ff663f89631d3948f85ce1365da09910eaa013f

**Comment by Kryptoniq** [comment]
To avoid confusions with Swisscoin (swisscoin.eu),  we will not your token.

**Comment by renens** [comment]
Wait what ? Swisscoin.eu is a scam site... we're a legit company.

**Comment by renens** [comment]
Proven scam : https://news.bitcoin.com/dissecting-swisscoin-cryptocurrency-ponzi-horizon/ Please we wish to appeal. It can't be that your project wants to have a scam coin over a legit project.
