### ISSUE TITLE
ZCG Delisting

### ISSUE THREAD

**Issue by Zcgleaddev** [forkdelta/tokenbase#1197]
Hi Forkdelta team,

Zlancer (ZCG) is no longer active and no development is going to be done on the project. It is already delisted from Coinexchange - it's primary exchange.

I am from the ZCG team, the coin has now been swapped to a new token. We will work on listing this token at a future date with Forkdelta. 

ZCG has also been delisted from coinmarketcap. Can you please delist off Forkdelta?

Kind Regards,
Ravi Desai

**Comment by therealMikkoK** [comment]
@Zcgleaddev 
Hello Sir,
Please link or post screen capture that shows how you have notified token holders.
I suspect you have a way for the token holders, if any remain, to change to the new token?
Please provide link, with description how it works.

**Comment by Zcgleaddev** [comment]
Hi forkdelta team,

The fork was carried out on 31st May and holders were notified to move to
coinexchange. We aren't looking to get listed anywhere else currently.

Any ZCG held in other exchanges/wallets, will no longer be supported for
the swap. Development for ZCG was stopped in February. You are free to
delist it from your exchange if you wish.

Thanks,

**Comment by therealMikkoK** [comment]
Delist OK.
