### ISSUE TITLE
Akaiito Token ERC20

### ISSUE THREAD

**Issue by AkaiitoOfficial** [forkdelta/tokenbase#1200]
The contract address. - https://github.com/AkaiitoOfficial/AKAIITO
https://etherscan.io/address/0x7ca936344d234034cf6936472d6bedbe8ae6667f

A link to the token issuer's official website. - https://akaiito.io/home/

AKAIITO is P2P platform using C2C business model. Akaiito will unite 4 parts: Online Market, Rent (cars and apartments), Services and Online Map. Base for all the deals will be Smart Contract. Currency for payments on platform is AIC token.

https://akaiito.io/home/ down we have a picture with the contract and also url redirecting to it

https://bitcointalk.org/index.php?topic=2804929.0
https://medium.com/@akaiitotallinn
https://icobench.com/ico/akaiito
https://icomarks.com/ico/akaiito

**Comment by freeatnet** [comment]
Thank you for your request, @AkaiitoOfficial! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide links to at least 2 independent third-party reviews of your project.
