### ISSUE TITLE
New token submission - Krowns

### ISSUE THREAD

**Issue by kinguinlimited** [forkdelta/tokenbase#1201]
Hello.

We would like to submit new cryptocurrency into ForkDelta exchange - Kinguin Krowns, KRS.

Krowns are a utility token based on the ETH20 network that will be used on [www.kinguin.net](url) website. 
The website of the project is [www.kinguin.io](url).

Krowns will enable all Gamers to profit from their skills anywhere in the
marketplace. Gamers can use these emblems to buy digital games, items, and
services. That distribution of options includes the opportunity to buy extra
merchant services such as premium marketing spots and targeted sales
campaigns. All transactions on Kinguin.io will require Krowns.

Please reach us for more information.

Kinguin Limited
exchange@kinguin.io

[Kinguin.io_Whitepaper.pdf](https://github.com/forkdelta/tokenbase/files/2062066/Kinguin.io_Whitepaper.pdf)

**Comment by freeatnet** [comment]
Thank you for your request, @kinguinlimited! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
You can find more information here: https://www.reddit.com/r/ForkDelta/comments/7tntnz/how_to_get_an_erc20_token_listed_on_forkdelta/

To request addition, please open an issue through https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
