### ISSUE TITLE
DocTailor Token Listing

### ISSUE THREAD

**Issue by DominicDocTailor** [forkdelta/tokenbase#1203]
Hi, 
My name is Dominic Brown the COO of DocTailor and we would really like to have our DOCT tokens trading on ForkDelta. I have presented the information you require below. If you need anything from us do let me know.

Contract Adress: 0xef9598E5edA6Be42EE45485671f202cE8a524648

Official Website: www.doctailor.com

Token Description: DocTailor is a unique self-customizing smart legal contract platform, that allows, lawyers, individuals, and organizations to send and create legal tailor-made smart contracts and agreements on the blockchain without developer experience

DOCT tokens give users access to create smart tailor-made legal documents on the DocTailor platform. Every token provides users with "DocTime" which can be used to create contracts, agreements for use in over 100 different industries

Offical Contract Link: https://etherscan.io/token/0xef9598E5edA6Be42EE45485671f202cE8a524648

Links to third-party reviews: 
https://icobench.com/ico/doctailor
https://coinlauncher.io/doctailor-ico
https://www.tokendesk.io/ico/doctailor/

Thanks

**Comment by freeatnet** [comment]
Thank you for your request, @DominicDocTailor! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by zloadr** [comment]
Hi ForkDelta,

Dominic who had started this application was away.

I have started a new thread and provided the information required along with our new contract address and relevant details to move forward.

https://github.com/forkdelta/tokenbase/issues/2446

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://www.entrepreneur.com/article/313123
https://guardian.ng/business-services/sam-enrico-williams-from-london-to-the-world-of-blockchain/

Thank you so much!
