### ISSUE TITLE
Please List OBXcoin

### ISSUE THREAD

**Issue by OBXcoin** [forkdelta/tokenbase#1204]
Contract Address: 0xad29D26B081204Ba2D1Da9e86101DDa69ec835D5

Website: www.obxcoin.io

* OBXcoin will be able to be used universally in any Global market.

* OBXcoin will be available on multiple Crypto exchanges and from businesses around the world. 

* OBXcoin is also being launched on the most cutting edge decentralized blockchain application and app development platform on the planet. 

*OBXcoin is garnering interest from all sorts of industries and businesses from all over the world.

Contract Address on Webpage: https://obxcoin.io/contract-address

Reviews: https://coinreviews.io/obxcoin-review/
               https://coinalert.ly/reviews/obxcoin-review-cryptocurrency-that-works-as-currency/

**Comment by freeatnet** [comment]
Thank you for your request, @OBXcoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by OBXcoin** [comment]
So what is this?

**Comment by Kryptoniq** [comment]
https://coinalert.ly/reviews/obxcoin-review-cryptocurrency-that-works-as-currency/ is a copy of  https://coinreviews.io/obxcoin-review/. 
Provide link to another independent third-party review other than Coinalert.ly.

**Comment by OBXcoin** [comment]
Sir,

Thank you for the email. I’m writing and asking for your help and a huge favor.

My name is Charlie Vecchio and I’m one of the cofounders of OBXcoin. I have included Greg Haskell and Linwood Mann on this email as they are the other cofounders.

We applied for ForkDelta on the 2 of June. I got the information to do that on your Github page. When I put the information you requested, Greg received an email to a Telegram link to finish the process.

Here are the screenshots. I realize now that the scammer took the info from Github and sent my cofounder a link and pretended to be representing your company and took money from us.

The scammer asked for more volume and we got more volume. We have told investors we were being listed based on this scammer telling us that information.

Can you please do us a huge favor and get our coin listed ASAP. This has caused us great pain already and we don’t want to upset our investors moving forward.

Here is a link to another article like you requested: https://coinreviews.io/greg-haskell-obxcoin-omminni/ <https://coinreviews.io/greg-haskell-obxcoin-omminni/>

Greg is one of the cofounders mentioned in the article and included on this email.

I would really appreciate your help in getting this listed. We look forward to hearing from you! 


-Charlie Vecchio
OBXcoin team

**Comment by Kryptoniq** [comment]
@freeatnet you may want to look into this.

**Comment by OBXcoin** [comment]
Can I please get an update on this? We have higher trading then most coins on your site, we have given you everything you requested, we were scammed from the Reddit page, and we just need answers for our investors. Can you please let us know when $OBX will be officially listed on your exchange. We have been waiting very patiently and need some updates. Thank you so much for understanding. Please let me ya know if you have any questions. 

-OBXCoin Team
