### ISSUE TITLE
Please list RSCT

### ISSUE THREAD

**Issue by anwarsquarebiz** [forkdelta/tokenbase#1206]
Token address: 0x1f6b542993fa456747e7b11ddda7eae5c998dda0

Issuer's official website: https://rise-coin.com

Description: We are building platform where books and tutor services will be available. We are mostly going to concentrate on books which are required by students in schools and colleges. As their books are mostly available in physical format but we want to gain rights to such books and convert them to digital format for the students. The books and services will be bought through RiseCoinToken. 

A link to the official contract address confirmation: https://etherscan.io/address/0xc275865a6cce78398e94cb2af29fa0d787b7f7eb

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://bitcointalk.org/index.php?topic=4307671

**Comment by anwarsquarebiz** [comment]
Hi freeatnet,

My issue to list RSCT is added to Needs Review since 3 days. Please let me know if I need to take any action. If not what is needs review means. Thank you.

**Comment by freeatnet** [comment]
Thank you for your request, @anwarsquarebiz! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by anwarsquarebiz** [comment]
Changed the details as per required format.

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by anwarsquarebiz** [comment]
Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://investfuture.ru/ico/rating/risecointoken
https://icocheck.com/ico_listing/risecointoken-ico/

**Comment by anwarsquarebiz** [comment]
Any update here?

**Comment by anwarsquarebiz** [comment]
Hi Team,

We have deployed a new contract which is ERC20 standard. Please let us know about the listing status.

**Comment by anwarsquarebiz** [comment]
Below is the link to new address and also I have updated same above https://etherscan.io/address/0xc275865a6cce78398e94cb2af29fa0d787b7f7eb.
