### ISSUE TITLE
Listing our coin - XSH

### ISSUE THREAD

**Issue by shamcoin** [forkdelta/tokenbase#1207]
Hi, We are a group of researchers working on building platform to detect scam. We reward whistleblowers by giving them our token. 
Contract Address: https://etherscan.io/token/0x200f96afa416d6ad606e5f3953f287a7282b8551#balances
Ideal token would have been XSC. Since it's taken we don't mind XSH.
Wesbite: www.shamcoin.com
Please reach out to us on admin@shamcoin.com

**Comment by Kryptoniq** [comment]
Your website is a blog and doesn't say anything about your token. 
No links to third-party reviews.
