### ISSUE TITLE
FXY - FIXY NETWORK LISTING

### ISSUE THREAD

**Issue by fixynetwork** [forkdelta/tokenbase#1208]
Token address is verified:
https://etherscan.io/token/0xa024e8057eec474a9b2356833707dd0579e26ef3

Decimals: 18
Ticker: FXY
Name: FIXY NETWORK

Website:
https://fixyapp.io

FXY Tokens will be used as payment method for our services and also for 55% reward to community over games. Marketplace, OTC Exchange, Giftcards, Storefinder.

Articles:
https://medium.com/@fixynetwork

https://news.bitcoin.com/pr-with-mvp-and-partnership-in-hand-fixy-network-is-primed-to-launch-its-pre-ico/

https://www.ccn.com/fixy-ico-opportunity-last-call-before-exchange-listing-and-multiple-partnerships-announcement/

Telegram:
https://t.me/fixynetwork
https://t.me/fixyapp

Bitcointalk:
https://bitcointalk.org/index.php?topic=3084108.1500;topicseen

**Comment by fixynetwork** [comment]
Hello @freeatnet Arseniy.
Any update to this issue?
Regards,
CEO, fixyapp.io

**Comment by freeatnet** [comment]
Duplicate #1138.
