### ISSUE TITLE
Please list DREM

### ISSUE THREAD

**Issue by tory000999** [forkdelta/tokenbase#1209]
Please list Free Dream Token

This is a request to add a new token to tokenbase.
Token address:  0xc81774fd1b51bc7e26b2bad562dcdb0a2cbebaf2
Symbol :Drem
 
verifiable by logging into our website and selecting the withdrawal tab once logged into your account.
Issuer's official website:  http://www.dremtoken.com
Description: Free Dream Token (Symbol Drem ) is an EOS compatible blockchain. The vision of Drem is to develop an efficient and low-cost blockchain, and then develop a super gaming center based on the blockchain. The people who support Drem from the beginning will get rich returns ,and It will be available that all over the world Gambling enthusiasts can participate in the game without restriction. The initially airdropped Drem tokens are ERC 20 tokens on the Ethernet blockchain. After the release of the  source code of EOS, we will copy and modify it to form a simplified  system of EOS-blockchain, and exchange the ERC 20 Drem token held by users according to the ratio of 1: 1.

A link to the official contract address confirmation:  
 https://etherscan.io/token/0xc81774fd1b51bc7e26b2bad562dcdb0a2cbebaf2/

This contract address is linked from our website  http://www.dremtoken.com in the header buttons, contract.
Twitter articles and replies: https://twitter.com/freedremone
Reddit comments:  https://www.reddit.com/user/Freedreamtoken/

Contact

Email: freedremone@hotmail.com

telegram:https://t.me/FreeDreamToken

**Comment by freeatnet** [comment]
Thank you for your request, @tory000999! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
