### ISSUE TITLE
Listing of Tronic TRNC

### ISSUE THREAD

**Issue by Troniccoin** [forkdelta/tokenbase#1210]
**Token address:** : 
0x002c74b0cd9354ba5464db519cae76d7cfaa070a

**Issuer's official website:** 
http://troniccoin.online/

**Description:** 
Sector dedicated to great success, cryptocurrency have established in a market as demanding and delicate as finance. Our goal is to make TRONIC one of the most influential currencies in the world of cryptocurrency. The strength of TRONIC is its speed of execution of transactions but also and especially its suite of application that allow easy and daily use even for the most novice. TRONIC is a crypto-currency POW peer-to-peer and open source. It takes root on the structure of the Ethereum, completely anonymous, free and transparent.

**A link to the official contract address confirmation:** 
http://troniccoin.online/forkdelta

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://bitcointalk.org/index.php?topic=2982602.0

**Comment by Kryptoniq** [comment]
Certified scam project: https://bitcointalk.org/index.php?topic=2982602.420
Website only contains and image.
http://troniccoin.online (http://archive.is/3c5vP).
Sorry, we can't list your token on FD.
