### ISSUE TITLE
Please list Payiza (PYZ)

### ISSUE THREAD

**Issue by payizaexchange** [forkdelta/tokenbase#1211]
Project name* - Payiza
Project description* Payiza is a simple and innovative cryptocurrency exchange and functions as a safe and efficient trading platform for various cryptocurrencies. Our vision with Payiza is to implement the latest advancements in Blockchain technology and lucid software tools to offer a superior user experience backed by an additional layer of security, thus making transactions easier and faster. Payiza is ideal and reliable for both beginners and advanced users to help them to optimize their investment and trading strategies.
 token address : https://etherscan.io/token/0x7ec33fc1b5c4847cc665236296ddb160474a2a87
Token symbol* PYZ
Web Site URL* http://payiza.co/index.php
Link to Whitepaper* http://payiza.co/uploads/PAYIZA_WHITEPAPER.pdf
Contact person name* Arman
Link to Facebook https://www.facebook.com/payizaexchange/
Link to Twitter https://twitter.com/PayizaExchange
Link to BitcoinTalk https://bitcointalk.org/index.php?topic=4096414.msg38083596#msg38083596
Link to Reddit https://www.reddit.com/user/payiza
Link to Github https://github.com/payizaexchange/ico/blob/master/smartcontract.sol
Link to Slack
Link to Telegram https://t.me/payizaofficial

**Comment by freeatnet** [comment]
Please follow the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
