### ISSUE TITLE
Request to add DBT token

### ISSUE THREAD

**Issue by Datbit** [forkdelta/tokenbase#1212]
This is a request to add a new token to tokenbase. 

*Token Address:  0x0301256716f6A18666db5A6009C2BFf7c98fDde9

*Issuer's official website: https://datbit.org/

*Description: Decentralized network to turn every virtual data into a real commodity.
The Datbit network allows anyone to store structured data securely in a decentralized way on a smart contract blockchain. The DBT smart token enables optional selling and buying of stored data while enforcing data usage rules as set by the data owner.

*A link to the official contract address confirmation: https://datbit.org/tokenaddress.html 
& also token contract address and details available in https://datbit.org home page.

*Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
Bitcointalk: https://bitcointalk.org/index.php?topic=2637490

Datbit Token Specifications:

Specifications:
Token name: Datbit Token
Token ticker: DBT
Token type: ERC20
Token Address: 0x0301256716f6A18666db5A6009C2BFf7c98fDde9

RELEVANT DOCUMENTS:

GitHub : https://github.com/Datbit/Datbit-SmartContract
Privacy Policy: https://datbit.org/ICO_tokens_presale_privacy_policy_EN.pdf
Tokens Sale Privacy Policy : https://datbit.org/ICO_tokens_sale_policy_EN%20(1).pdf
General Terms & Conditions : https://datbit.org/ICO_presale_general_terms_&_conditions_EN.pdf
WEBSITE: https://datbit.org/
FACEBOOK: https://www.facebook.com/Datbit-147412289317030
TWITTER: https://twitter.com/datbit_org
TELEGRAM: http://t.me/datbit
WHITEPAPER : https://datbit.org/Datbit-WhitePaper.pdf
REDDIT: https://redd.it/7hj5jm
Bitcointalk: https://bitcointalk.org/index.php?topic=2637490

Contact Emails: jhon@datbit.org , admin@datbit.org, support@datbit.org

**Comment by freeatnet** [comment]
Thank you for your request, @Datbit! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Datbit** [comment]
Token Address: 0x0301256716f6A18666db5A6009C2BFf7c98fDde9

Issuer's official website: https://datbit.org/

Description: Decentralized network to turn every virtual data into a real commodity.
The Datbit network allows anyone to store structured data securely in a decentralized way on a smart contract blockchain. The DBT smart token enables optional selling and buying of stored data while enforcing data usage rules as set by the data owner.

A link to the official contract address confirmation: https://datbit.org/tokenaddress.html
Smart Contract Address : https://etherscan.io/address/0x0301256716f6a18666db5a6009c2bff7c98fdde9 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
  1. https://bitcointalk.org/index.php?topic=2637490
  2. https://redd.it/7hj5jm

**Comment by freeatnet** [comment]
Your [white paper](https://datbit.org/Datbit-WhitePaper.pdf) ([archived](http://archive.is/YG0Xc)) is largely plagiarized from Datum [white paper](https://datum.org/assets/Datum-WhitePaper.pdf) ([archived](http://archive.li/cfB6d)). Your request will not be granted.

If you believe this decision is in error, you may appeal it here in this thread.
