### ISSUE TITLE
Token listing Mechanix Token MMX

### ISSUE THREAD

**Issue by saintpeterpaul1** [forkdelta/tokenbase#1213]
Mechanix Token MMX
https://www.mechanixtoken.com

Source Code
https://etherscan.io/address/0xe7c33a0e04f2316bb321c4ad2976873d09538b56#code

Contract
https://etherscan.io/address/0xe7C33a0E04F2316Bb321C4AD2976873d09538B56

We are the first cryptocurrency for Automotive Repair Shops and Mechanic's. Our mission is to create the rewards and loyalty platform that will permeate the Automotive Repair Shop retailers of all shapes and sizes and connect them with their customers by  virtue of Mechanix MMX tokens.

Bitcointalk
https://bitcointalk.org/index.php?topic=4091345.0

Reddit
https://crypto.bi/z/threads/mechanix-token.7/

Telegram
https://t.me/mymechanix

Twitter
https://twitter.com/mechanixT

Victor Vigil
saintpeterpaul1@gmail.com
505-306-2255

**Comment by freeatnet** [comment]
Please follow required format provided: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
