### ISSUE TITLE
Mobilink ** OFFICIAL REQUEST ** MOLK

### ISSUE THREAD

**Issue by tkdeveloper** [forkdelta/tokenbase#1216]
This is the official request from Mobilink to list our token on forkdelta, please disregard any previous
requests or listings if any that may have been posted. My Github user account has been added to the official Mobilink Github as requested my your staff and we have updated our website with the final token.

Here is the link to an official page confirming the above contract address:
https://mobilink.io/token.php

Etherscan has verified the token as well:

https://etherscan.io/token/0x97cb5cc1b2e10cc56dc16ab9179f06dfedbe41a2

The contract address:
0x97cb5cc1b2e10cc56dc16ab9179f06dfedbe41a2

Token Name: MobilinkToken
Token Ticker: MOLK

A link to the token issuer's official website.
mobilink.io

MOBILINK-COIN ICO has partnered with Mobilink-Network to be the First Decentralized Mobile Telecom Company using blockchain technology. Digital monthly revenues based on Proof of Participation pay for all voice and data usage costs.

Links about MobilinkToken and ICO
https://icomarks.com/ico/mobilinkcoin
https://www.reddit.com/r/mobilinkcoin/
https://bitcointalk.org/index.php?topic=2614818.msg26607277#msg26607277

**Comment by Kryptoniq** [comment]
Creating multiple duplicate issues doesn't help.
