### ISSUE TITLE
MRN listing on Forkdelta 

### ISSUE THREAD

**Issue by marineproject** [forkdelta/tokenbase#1217]
Token Information 
Name: Marine
Ticker: MRN
Contract address: 0x6f2deef18421ba39065223b23ef38666b3052a46

Project Details
MARINE is the first ever blockchain project initiated to solve the ever demanding freight, logistics and supply chain of the world's waterways all in one project. This is a problem solving project that will breach the gap between the manufacturers, shipping managements and their clients. We are poised in making the channel through which goods and materials are transacted much more easier by improving the scalability and reducing the complexity of how manufacturers, shipping managements and their customers interact using an improved technology that will be launched during the execution of our plans in respect to the time specified.

Social Media
Website: marineproject.co
Telegram: t.me/marine_com
Twitter: www.twitter.com/marine_token

**Comment by freeatnet** [comment]
Thank you for your request, @marineproject ! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by marineproject** [comment]
Link to our Smart contract address: 
https://etherscan.io/address/0x6f2deef18421ba39065223b23ef38666b3052a46

**Comment by freeatnet** [comment]
1. Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

    Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
    Note:
    * We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
    * Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
2. The contract address confirmation must be linked from the official website (it can be on the website, eg., in the footer, on a FAQ page, or published in on your project's blog linked from the official website).

Thanks!
