### ISSUE TITLE
Add Parachute Token (PAR) to ForkDelta

### ISSUE THREAD

**Issue by acfmichelsen** [forkdelta/tokenbase#122]
---
addr: '0x1beef31946fbbb40b877a72e4ae04a8d1a5cee06'
decimals: 18
description: Community, Wallet and Exchange for free Airdrops; connecting projects to an amazing community
Name: Parachute Token
TOKEN: PAR

Token: PAR
Name: Parachute Token
Contract Address: 0x1beef31946fbbb40b877a72e4ae04a8d1a5cee06 
Website: www.parachutetoken.com 
telegram: https://t.me/parachutetokengroup
About parachute and Parachute token:
Parachute is a community engaged in helping early stage companies build their initial community through organized airdrops on the Parachute platform. In addition to launching a coin wallet for airdropped tokens, Parachute is developing an exchange platform to trade these newly minted tokens where PAR (Parachute Token) will serve as the medium of exchange. Additionally, the team envisions further utility and spend options with PAR, such as voting rights and profit sharing capabilities.

**Comment by JonathonDunford** [comment]
Lol'd at "beef" in the address.

verified: 0x1beef31946fbbb40b877a72e4ae04a8d1a5cee06

**Comment by acfmichelsen** [comment]
haha it's my favorite part of the contract... "where's the beef!"

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
