### ISSUE TITLE
Request for GimmerToken (GMR) listing

### ISSUE THREAD

**Issue by Flllexa** [forkdelta/tokenbase#1226]
Token address: 0x9b8d5f3402f74c7a61d9f09c32d3ca07b45c1466

Issuer's official website: https://gimmer.net

Description: Gimmer is designing the most sophisticated decentralized trading platform
available today, incorporating advanced trading indicators and Artificial
Intelligence (AI) decision-making tools in Gimmer auto trading bots. The platform
is quick and easy to use and accessible to all customers, no matter what their
background or level of trading experience.

A link to the official contract address confirmation: https://token.gimmer.net

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. Reddit:
https://www.reddit.com/r/IAmA/comments/7xqybu/gimmer_are_creating_an_ai_and_community_powered/

2. Github issues:
https://github.com/GimmerBot/Gimmer/issues

3. Github releases
https://github.com/GimmerBot/Gimmer/releases

4. Bitcoin Talk:
https://bitcointalk.org/index.php?topic=2760414.20

5. Icobench
https://icobench.com/ico/gimmer

**Comment by freeatnet** [comment]
Thank you for your request, @Flllexa! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Flllexa** [comment]
ok, thanks
