### ISSUE TITLE
Request for DAGT listing 

### ISSUE THREAD

**Issue by DAGTFLY** [forkdelta/tokenbase#1227]
addr: '0x56d1ae30c97288da4b58bc39f026091778e4e316'
decimals: 18
description: >-
DAGT is a leading decentralized platform which allows holders of blockchain assets to leverage their holdings as collateral for assets guarantee. Based on Ethereum and smart contract technologies, DAGT aims to utilize blockchain to build a transparent, efficient and distributed guarantee system which makes digital assets flow quickly.
links:

Email: mailto: market@dagt.io
Github: https://github.com/GRANDDREAM
Telegram: https://t.me/DAGTofficial
Twitter: https://twitter.com/DAGTofficial
Website: https://dagt.io/
Whitepaper: https://www.dagt.io/pdf/dagt_en.pdf
name: DAGT Crypto Platform
symbol: DAGT

（1） The contract address.
0x56d1ae30c97288da4b58bc39f026091778e4e316

(2) A link to the token issuer's official website.
https://www.dagt.io/?lang=en

(3) 1-3 sentences for the token's description: at least one on the token issuer (eg., the product they are building) and one on token role.
The Digital Asset Guarantee Token (DAGT) is a Chinese project that is incorporated in Singapore. 
They are building a fully decentralized loan platform that allows holders of cryptocurrencies to use that as collateral for fiat currency loans.
DAGT builds a link between businesses who want to loan money and crypto users who want to borrow money. 
The role of the DAGT token is used to pay for all the fees and transaction costs on the platform. 

(4) A link to an official page confirming the above contract address: this needs to be on the official domain of the token issuer.

https://www.dagt.io/?lang=en

(5) Links to third-party reviews or discussion of the token or the token issuer of at least two distinct kinds, including, but is not limited to: articles in the media, independent third party blogs, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments from high ranked users in BitcoinTalk, etc. These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels).

Positive feedback from the Bitcoin Exchange Guide “ https://bitcoinexchangeguide.com/dagt-ico/”
Steemit article with one of our followers with very positive comments https://steemit.com/dagt/@gbenga/dagt-using-blockchain-technology-to-create-world-s-first-digital-asset-credit-platform.
Listed on coinmarkets.net https://www.coinmarkets.net/stories/37769/project-introduction-ico-dagtio-dagt-token/
Positive YouTube review from our Russian Fans “https://www.youtube.com/watch?v=bjaklqIfgVI”

**Comment by freeatnet** [comment]
Thank you for your request, @DAGTFLY! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by DAGTFLY** [comment]
（1） The contract address.
0x56d1ae30c97288da4b58bc39f026091778e4e316

(2) A link to the token issuer's official website.
https://www.dagt.io/?lang=en

(3) 1-3 sentences for the token's description: at least one on the token issuer (eg., the product they are building) and one on token role.
The Digital Asset Guarantee Token (DAGT) is a Chinese project that is incorporated in Singapore.
They are building a fully decentralized loan platform that allows holders of cryptocurrencies to use that as collateral for fiat currency loans.
DAGT builds a link between businesses who want to loan money and crypto users who want to borrow money.
The role of the DAGT token is used to pay for all the fees and transaction costs on the platform.

(4) A link to an official page confirming the above contract address: this needs to be on the official domain of the token issuer.

https://www.dagt.io/?lang=en

(5) Links to third-party reviews or discussion of the token or the token issuer of at least two distinct kinds, including, but is not limited to: articles in the media, independent third party blogs, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments from high ranked users in BitcoinTalk, etc. These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels).

Positive feedback from the Bitcoin Exchange Guide “ https://bitcoinexchangeguide.com/dagt-ico/”
Steemit article with one of our followers with very positive comments https://steemit.com/dagt/@gbenga/dagt-using-blockchain-technology-to-create-world-s-first-digital-asset-credit-platform.
Listed on coinmarkets.net https://www.coinmarkets.net/stories/37769/project-introduction-ico-dagtio-dagt-token/
Positive YouTube review from our Russian Fans “https://www.youtube.com/watch?v=bjaklqIfgVI”

**Comment by trcream** [comment]
any update?

**Comment by DAGTFLY** [comment]
NO

**Comment by trcream** [comment]
@freeatnet Is there any updates on the DAGT project being listed? Almost been a month not. Loowing forward to your response.
