### ISSUE TITLE
Trend Network Token Listing

### ISSUE THREAD

**Issue by toyovoke** [forkdelta/tokenbase#1230]
Token Name: Tend Network (TRD)
Total Supply: 500 000 000
Symbol: TRD
Decimals: 0
Contract address: 0xC879041033702169164A967Ebf4d770cC5875a8b

Website: https://trendnetwork.online

Description: TREND NETORK is an anonymous, decentralized, people-oriented service showcasing and distribution platform. The platform is built over tried and tested Ethereum protocol and Inter-Planetary File System (IPFS).

Link: https://trendnetwork.online/token-spec

Bitcointalk ANN: https://bitcointalk.org/index.php?topic=4354866.msg38914990#msg38914990

Twitter: https://twitter.com/trendtoken

Telegram Channel: https://t.me/joinchat/AAAAAEaKzrNJV2HHeahCaA

**Comment by freeatnet** [comment]
Thank you for your request, @trendnetwork ! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by toyovoke** [comment]
We will be glad to get a timeous response and upodate from your team.

**Comment by Kryptoniq** [comment]
Website is a wholesale copy of Coinnec's whitepaper https://coinnec.com/Whitepaper-Coinnec.pdf.

`TREND NETORK is an anonymous, decentralized, people-oriented service showcasing and distribution platform.
The platform is built over tried and tested Ethereum protocol and Inter-Planetary File System (IPFS). Transactions on the platform are mostly handled using its own TREND NETORK tokens – an ERC20 based cryptocurrency which is now one of the most sought-after token creation standards.
Token works with every global cryptocurrency. Token is designed to be flexible to last hundred of years and to work with IoT whilst being compatible with any future system.`
COINNEC
`COINNEC is an anonymous, decentralized, people-oriented service showcasing and
distribution platform. The platform is built over tried and tested Ethereum protocol and
Inter-Planetary File System (IPFS). Transactions on the platform are mostly handled using its
own COINNEC tokens – an ERC20 based cryptocurrency which is now one of the most
sought-after token creation standards.`

We have a strong stance against plagiarism and will not be listing your token based on these grounds.
if you believe this decision was made in an error, provide objectionable facts regarding the validity of your project and steps you have taken to remedy the situation.
Thank you.


 https://trendnetwork.online (http://archive.is/gCeaS)
https://coinnec.com/Whitepaper-Coinnec.pdf. (http://archive.is/Paxlo)
