### ISSUE TITLE
Request for MORPH (morpheus.network) token listing

### ISSUE THREAD

**Issue by themobydick** [forkdelta/tokenbase#1231]
1. Contract Address: 0x7b0c06043468469967dba22d1af33d77d44056c8
Token Symbol: MORPH
Decimals: 4

2. Official website: https://morpheus.network/

3. The Morpheus.Network was designed in consultation with some of the world’s largest shipping, customs & banking firms to create a full-service, global, automated, supply chain platform with an integrated cryptocurrency payment system utilizing blockchain technology.

Their goal is to bring together leading companies in the freight technology industries that have a vested interest in the development of blockchain technology.

4. https://medium.com/@themorpheus/how-to-view-your-morph-tokens-on-myetherwallet-com-8159b570a421

5. https://steemit.com/ico/@valnd/morpheus-network-ico-review-automated-supply-chain-and-payments
https://bitcointalk.org/index.php?topic=2818233.0
https://www.nasdaq.com/press-release/former-ceo-of-dhl-roger-crook-joins-global-trade-blockchain-disruptor-morpheusnetwork-20180416-00386

**Comment by freeatnet** [comment]
Thank you for your request, @themobydick ! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
https://coinmarketcap.com/currencies/morpheus-network/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x2ef27bf41236bd859a95209e17a43fbd26851f92,  https://morpheus.network/

**Comment by therealMikkoK** [comment]
Changed to right contract address 0x7b0c06043468469967dba22d1af33d77d44056c8
