### ISSUE TITLE
Add Veroneum (VRN)

### ISSUE THREAD

**Issue by veroneum** [forkdelta/tokenbase#1233]
1. The contract address.

    The VERONEUM (VRN) token contract address is : 0x0f1c79cf0458160e2B41e94065a7dF9A452C6579

2. A link to the token issuer's official website. This MUST be in HTTPS.

    Website: https://www.veroneum.io

3. 1-3 sentences for the token's description.

      Veroneum or VRN is the lastest investment banking platform with investbox system.
    Why Investbox? Because the problem of paying interest on lending system that predicted coin cost in 
    market then bring money to ICO, cause it can't pay resonable interest.
    but our Investbox will deposit coin based on the coin as cost. 
    (e.g. you will buy 1000VRN, our system will calculate your coin with 1000VRN and it have 3% interest 
    per day [30VRN])
    This idea the Market price will not affect this deposit system. Because high price, it will be good 
     results. and system pay in VRN.
    That reason cause our system will be stable.

4. A link to an official page confirming the above contract address. This needs to be on the official 
    domain of the token issuer. Etherscan does not count as a confirmation.

    https://ethplorer.io/address/0x0f1c79cf0458160e2b41e94065a7df9a452c6579
    https://www.etherchain.org/account/0f1c79cf0458160e2b41e94065a7df9a452c6579

5. Links third-party review or discussion of at least two kinds.
   This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party 
   blogs, ICO ranking websites, established company partnerships, etc.

    https://bitcointalk.org/index.php?topic=3575196
    https://www.trackico.io/ico/veroneum/#financial
    https://findico.io/ico/veroneum/rating
    https://cryptorated.com/ico-listing/veroneum/
    https://www.youtube.com/watch?v=uKxsbPOB8uk
    https://www.youtube.com/channel/UCw1ls3H9hv5onlfiCI1AToA
    https://www.youtube.com/watch?v=sT863JkRr10
    https://youtu.be/27K4lOsxPvc
    https://youtu.be/aINu377DrpI

6. Well-defined channels of communication with the token issuer must be published on the website.
   This includes, but is not limited to: public social media, some form of instant messaging (Telegram, 
   Discord), email.

    Facebook: https://www.facebook.com/Veroneum
    Twitter: https://twitter.com/veroneum
    Telegram: https://t.me/joinchat/IEKdhRKScNoZBVp4vPCASw
    Email: info@veroneum.io
    Whitepaper: https://www.veroneum.io/content/site/whitepaper.pdf

    Name : Veroneum

**Comment by freeatnet** [comment]
Thank you for your request, @veroneum ! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by veroneum** [comment]
name:  Veroneum

Token address:   0x0f1c79cf0458160e2B41e94065a7dF9A452C6579

Issuer's official website:   https://www.veroneum.io

Description:   Veroneum or VRN is the lastest investment banking platform with investbox system.
 Why Investbox? Because the problem of paying interest on lending system that predicted coin cost in
 market then bring money to ICO, cause it can't pay resonable interest.
 but our Investbox will deposit coin based on the coin as cost.

A link to the official contract address confirmation: 
  https://ethplorer.io/address/0x0f1c79cf0458160e2b41e94065a7df9a452c6579
  https://www.etherchain.org/account/0f1c79cf0458160e2b41e94065a7df9a452c6579

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
 https://bitcointalk.org/index.php?topic=3575196
 https://www.trackico.io/ico/veroneum/#financial
 https://findico.io/ico/veroneum/rating
 https://cryptorated.com/ico-listing/veroneum/
 https://www.youtube.com/watch?v=uKxsbPOB8uk
 https://www.youtube.com/channel/UCw1ls3H9hv5onlfiCI1AToA
 https://www.youtube.com/watch?v=sT863JkRr10
 https://youtu.be/27K4lOsxPvc
 https://youtu.be/aINu377DrpI

**Comment by freeatnet** [comment]
Please clean up your request so that it follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically, 
1. Etherscan does not count as a contract address confirmation. Contract address confirmation MUST be linked from the official website and MUST be visible publicly.
2. Please select 2 links for third-party reviews.
