### ISSUE TITLE
add 	RichGoldToken ( RIG )

### ISSUE THREAD

**Issue by yoshiekiura** [forkdelta/tokenbase#1234]
Name: RichGoldToken
Symbol: RIG
Address: 0x3d4b0c39dd79f32fbf435b35fdeed567596bd341
Decimals: 18
Email: contact@rich-gold.com
Website: https://rich-gold.com
Github: https://github.com/urichie-project/richgold

Description: RICHGOLDTOKEN is a next generation crypto currency. It is a
tradeable ERC20 token that resides on the
Ethereum blockchain.

**Comment by freeatnet** [comment]
Thank you for your request, @yoshiekiura ! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by yoshiekiura** [comment]
okey, thank @freeatnet , RichGoldToken (RIG) is listing, at stock.exchange and token.store,

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically,
1. Include a link to the official contract address confirmation. Contract address confirmation MUST be linked from the official website and MUST be visible publicly. If the confirmation is not visible immediately, include an explanation of how to find it.
2. Provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer (see [the required format file](https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) for more information).

**Comment by yoshiekiura** [comment]
please chek 

http://rich-gold.com/
