### ISSUE TITLE
Add Banker Token (BNK)

### ISSUE THREAD

**Issue by bankertoken** [forkdelta/tokenbase#1235]
Name: Banker Token
Symbol:  BNK
Address: 0xc80c5e40220172b36adee2c951f26f2a577810c5
Decimals: 8
Email: info@bankera.com
Website: https://bankera.com/
link verify : https://blog.bankera.com/2018/05/25/now-you-can-withdraw-your-bnk-tokens/

https://bitcointalk.org/index.php?topic=2091093.0
https://twitter.com/Bankeracom

Description: BANKING FOR THE BLOCKCHAIN ERA

**Comment by freeatnet** [comment]
Duplicate of #1161.
