### ISSUE TITLE
Request to list DCNX tokens on Forkdelta

### ISSUE THREAD

**Issue by eldoncar** [forkdelta/tokenbase#1236]
Contract Address: 0xc08a04c0c47196bc63f883f4ea23aacc28158514

Token website: https://hirefreelancerz.com/doncoin/index

Description: DonCoin - Uniting freelancers and cryptocurrencies

FB page: https://www.facebook.com/Hirefreelancerz/
FB group: https://www.facebook.com/groups/430592587412718/
Twitter: https://twitter.com/hirefreelancer4
Bitcointalk: https://bitcointalk.org/index.php?topic=2799542.0

Other links:
https://cryptonext.com/ico/doincoin

Thank you

**Comment by eldoncar** [comment]
Thank you in advance guys

Hope to see DonCoin in your exchange soon.

**Comment by icccoin** [comment]
send email id

**Comment by eldoncar** [comment]
My email is: eldoncar@gmail.com

**Comment by freeatnet** [comment]
Thank you for your request, @bryan9819! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by eldoncar** [comment]
Great. Will keep an eye.

**Comment by eldoncar** [comment]
Hi there,

Just wondering whether there is a set time frame for the review process?
Members asking how long when dcnx will be listed :-)

Thank you

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically, provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by eldoncar** [comment]
Hi

Here are some past articles and reviews made by third parties.
Please note that we have made changes to the team an overall token sale structure so some info might not totally be up to date since some of the articles were written in early days of our tokens sales and some in recent days.
Hope this will be enough.

https://cryptocoinpravda.com/doncoin-dcnx-digital-currensu-2.html
https://www.minds.com/blog/view/843571876398096384
https://steemit.com/bitcoin/@brainerdpaul/doncoin-dcnx
https://www.minds.com/blog/view/842508473357553664
https://steemit.com/cryptocurrency/@temillion/doncoin-on-blockchain
https://steemit.com/blockchain/@jacobtemi10/join-the-the-moving-train-hirefreelancerz-don-coin

Thank you

**Comment by freeatnet** [comment]
@eldoncar The links you provided contain essentially the same article, which contains no original research.

**Comment by eldoncar** [comment]
@freeatnet
These are depressive news, I though with all the info I sent you would be enough to get us listed.
I will have to search the internet then for reviews.
I know recently people has been writing about our project...
Will get back.

Thanks
