### ISSUE TITLE
Requesting to be Listed (EXIMCHAIN) 

### ISSUE THREAD

**Issue by bryan9819** [forkdelta/tokenbase#1237]
Request to list EXC Token

Name: EXIMCHAIN 

Symbol: EXC

Token: ERC20

Contract address: 0x00c4b398500645eb5da00a1a379a88b11683ba01

Etherscan: https://etherscan.io/address/0x00c4b398500645eb5da00a1a379a88b11683ba01

Official website: https://www.eximchain.com

Whitepaper: https://www.eximchain.com/documents/Whitepaper%20-%20Eximchain.pdf

Link to Facebook:  https://www.facebook.com/eximchain/

Link to Twitter: https://twitter.com/eximchainexc

Link to Medium: https://medium.com/eximchain

Link to Linkedin: https://www.linkedin.com/company/11194001/

**Third-party source** 
Link to Youtube: https://www.youtube.com/watch?v=ApxbKzwB0CI 
Link to article 1: https://www.cnbc.com/2018/06/04/for-all-the-hype-blockchain-applications-are-still-years-even-decades-away.html 
Link to article 2: https://forbes.com/sites/shermanlee/2018/05/30/quadratic-voting-a-new-way-to-govern-blockchains-for-enterprises/#2238d61c52ff 

Description:

Eximchain enables businesses to connect, transact, and share information more efficiently and securely. Using blockchain technology, Eximchain eliminates traditional supply chain barriers and integrates actors big and small into an inclusive, transparent, and secure global network.

Email: hello@eximchain.com

Thank you!

**Comment by freeatnet** [comment]
Thank you for your request, @bryan9819! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x00c4b398500645eb5da00a1a379a88b11683ba01, https://www.eximchain.com
