### ISSUE TITLE
Listing Request - Digital Blockchain [DIGIBLOCK]

### ISSUE THREAD

**Issue by liandimia** [forkdelta/tokenbase#1238]
Contract address: 0xCdE21dA29E54E3b60A1aAacD1DCbDa76D8066aF1
Token Ticker : DBX

Issuer's official website: www.digiblock.org

Official contract address confirmation : https://medium.com/@digiblockmail/digiblock-airdrop-live-1fe73daffb75

A link to a third-party review or discussion of the token, like an established ICO review blog: https://medium.com/@digiblockmail/wellcome-holder-as-family-of-digiblock-b8cf23d26550

Description: Digital Blockchain Ecosystem , The revolution of digitalization

**Comment by freeatnet** [comment]
Thank you for your request, @liandimia! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
