### ISSUE TITLE
Request our IVI Token Listing

### ISSUE THREAD

**Issue by Otimoworld** [forkdelta/tokenbase#1239]
Dear Sir or Madam,

Request to list IVI - INOOVI Token
Name : INOOVI
Symbol : IVI

ETH Contract Address : 0xa91464abd4625a23ab719e3f0fce84dadd54e546

Decimals : 18

Description : 

This token is linked to all Football Clubs in the world using it to negociate FOOTBALL PLAYERS HUGE AMOUNTS OF TRANSFERS. Great deals just before Football World Cup 2018 in Russia.

Large Billions of USD of our token selling Contracts are already signed with Hugest Football Club in the world.

New Updated Website : https://infinivi.io

Bitcointalk : https://bitcointalk.org/index.php?topic=2787192.0
White paper in English : https://inoovi.io/en/white-paper/

Official TV and Medias announcements on the 21st of June in Brasil, Sao Paulo.

**Token address:**

**Issuer's official website:**

**Description:** 

**A link to the official contract address confirmation:** 

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by Kryptoniq** [comment]
Your token has already been marked as complete. Please wait for listing rather than creating duplicates.
