### ISSUE TITLE
Make Tokenbase data more accessible

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#124]
We need to have a more convinient way of getting tokenbase data into ForkDelta frontend and backend.

Frontend needs a list of listed tokens and, occasionally, details of the listed tokens. Frontend is not currently capable of parsing YAML.

Backend needs just a list of listed tokens. Backend is capable of parsing YAML and JSON equally well.

Here's an idea of how it could work:
1. Write a script that will run on Travis on master branch only, generating some files from repo contents.
2. Configure Travis to push build artefacts from that scripts to tokenbase's `gh-page` branch.

https://github.com/forkdelta/nextgen-ui/blob/master/.travis.yml uses a similar approach, though pushes to a different repo.

The script:
- Produces a short index file, potentially both in yaml and json format
- Produces a JSON file for every YAML file in tokens/

In fact, we can basically have a REST tokens API running off github, where:
- https://forkdelta.github.io/tokenbase/tokens.json and https://forkdelta.github.io/tokenbase/tokens.yaml return the index (with the basics of data: address, name, symbol, decimals) in desired formats;
- and https://forkdelta.github.io/tokenbase/tokens/0xTOKENADDR.yaml and https://forkdelta.github.io/tokenbase/tokens/0xTOKENADDR.json return token details in desired format

**Comment by JonathonDunford** [comment]
freeatnet - Today at 5:31 PM
We can probably do addr, decimals, symbol (rename name from current config file), maybe name as full token name; we should be able to change current frontend enough to handle a field rename and fetching a tokenbase-side file
