### ISSUE TITLE
Add DGX

### ISSUE THREAD

**Issue by pascalvanhecke** [forkdelta/tokenbase#1240]
**Token address:**
0x4f3afec4e5a3f2a6a1a411def7d7dfe50ee057bf

**Issuer's official website:**
https://digix.io/

**Description:** 

Gold Backed Tokens: each token represents 1gm of 99.99% LBMA standard gold and secured in safehouse vaults.

Its value should track the value of Gold, since it can be purchased at the price of Gold and redeemed for physical gold at the Digix Marketplace https://digix.global/app/

Not to be confused with DigixDAO (DGD) governance tokens, that entitle the holder to transaction fees incurred on the DGX tokens.

+links:

**A link to the official contract address confirmation:** 

https://medium.com/@Digix/digix-dev-update-22-may-2018-9345b6e7b1c9

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.   https://www.coindesk.com/tokens-crowdsales-startups/ ( mention in 2016! article on token mechanisms)
2. https://cryptoslate.com/introduction-to-digixdao-dgd-tokenized-gold-on-the-ethereum-blockchain/  (recent article on the launch of DGX tokens by Digix, the company)

**Comment by freeatnet** [comment]
Thank you for your request, @pascalvanhecke! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x4f3afec4e5a3f2a6a1a411def7d7dfe50ee057bf, https://digix.io/
