### ISSUE TITLE
Listing of CPPG Tokens

### ISSUE THREAD

**Issue by albertthomason** [forkdelta/tokenbase#1241]
Hello All,

We are interested to list our tokens Cross Platform Payment Gateway (CPPG) on ForkDelta.

We have initially gone for ICO but immediately stopped it and taken decision for distributing 70% tokens via community airdrop if different phases. Phase-1 is already completed and we are running phase-2 for airdrop which will finish soon.

About CPPG:
Cross Platform Payment Gateway(CPPG) is world's first payment gateway which will work on atomic swapping on blockchains and also public exchanges. CPPG will allow both merchant as well as buyer to select own choice of payment method(Fiat or Crypto). CPPG engine will take care of converting from one method to another by atomic swapping and public exchange integration.

We will be publishing white paper on 15 Jun 2018 and we want to list token before it. It will be good if you can help us.
Estimated time for working platform is 1.5 Year(Fully ready)

Community Details:
Website: http://www.cppg.io
Telegram: https://t.me/CPPGToken
Twitter: https://www.twitter.com/CPPGToken
Linked In: https://www.linkedin.com/in/cppgtoken/
Email Id: support@cppg.io
Reddit: https://www.reddit.com/user/Albert_Thomson_/comments/89qns3/free_cppg_tokens_distribution/
Bitcoin Talk: https://bitcointalk.org/index.php?topic=3232772.0
ICO Crunch: https://icocrunch.io/ico/cppg/
TDirectory: http://tdirectory.me/group/CPPG-Token--Cross-Platform-Payment-Gateway.dhtml

Token Contract Details:
Verified Contract: 0x345fD80105d95Fd8845d0E717B9590499b5756d0
Name: CPPG Token
Symbol: CPPG
Decimal: 0

Let us know in case you need any details.

Regards,
Albert Thomson
Team CPPG
support@cppg.io

**Comment by freeatnet** [comment]
Please follow the request form format here: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!

**Comment by freeatnet** [comment]
Replaced by #1242.
