### ISSUE TITLE
Listing of CPPG Token (Cross Platform Payment Gateway)

### ISSUE THREAD

**Issue by albertthomason** [forkdelta/tokenbase#1242]
**Token address:**
0x345fd80105d95fd8845d0e717b9590499b5756d0

**Issuer's official website:**
http://www.cppg.io

**Description:** 
Cross Platform Payment Gateway is world's first payment gateway which will work on atomic swap of blockchains. Cross Platform Payment Gateway will support both fiat as well as crypto currencies. Both merchant and buyer will able to select method of choice for initiating payment and CPPG Engine will take care of conversion using atomic swap and public exchange integration.

**A link to the official contract address confirmation:** 
http://www.cppg.io

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=3232772.0
2. https://www.reddit.com/user/Albert_Thomson_/comments/89qns3/free_cppg_tokens_distribution/
3. https://icocrunch.io/ico/cppg/

**Comment by freeatnet** [comment]
Continued from #1241.

**Comment by freeatnet** [comment]
Thank you for your request, @albertthomason! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: adding a token to ForkDelta Tokenbase is free, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.

**Comment by saurabhjainiitd** [comment]
Hello Everyone,

I wanted to let you know about the great project from the Croos Platform Payment Group team which will be a revolution in the fintech space in the coming year. The idea allows people to swap currencies between fiat and crypto and do transactions on the blockchain without hassle.

Once ready,  it can be not only accepted as payment gateway but can be used as crypto changer also(if they extend it).

Whitepaper is on the verge of coming out and should be available by 15 Jun 2018. The team is very professional and pro-active and have always been on time in all there commitments to date.

Requesting you to help them for listing in order to provide platform for development of new concept.

Thanks 
Saurabh Jain

**Comment by Parikshitbhosale** [comment]
Hey All,

Cross Platform Payment Gateway is a platform for processing payment in different medium including fiat and crypto currencies. CPPG Token will be used as fuel to process this transaction on CPPG MainNet.

Project looks really good and post completion surely can be used as payment gateway if all goes well.

The team is very good and have always lived up to their commitments.

Thanks.

**Comment by RanjoMc** [comment]
Hello ForkDelta,

I am one the member who followed them when community was below 200. I have registered their airdrop and I got more than 100000 CPPG Tokens + additional tokens for my twitter sharing work.

Community Manager Albert and Support Team is very helpful to explain project and they deliver whatever they said within timeline.

Hope this project will cut payment gateway charges fro 2% to 0.1% which is practically possible for crypto and 0.25% for crypto-fiat payment.

Concept looks good and if you will help them then it will be great.

**Comment by freeatnet** [comment]
https://twitter.com/CPPGToken/status/1004933276270641152?s=09

**Comment by Kryptoniq** [comment]
The photo of your **Co-Founder** "John Anderson" is that of a musician "Danny Gula".
The photo of your **Senior Blockchain Engineer** "Albert Thompson" was taken from Containex.com.

We have a strong stance against character impersonation and will not be listing your token based on this facts.
If you believe this decision was made in an error you can contest it on this issue by providing verifiable identities of all your team members.
Thank you.
