### ISSUE TITLE
MMS token listing

### ISSUE THREAD

**Issue by 3DMetamorphosis** [forkdelta/tokenbase#1244]
Contract address: 0xce0cd513a069e8ec9cb625fcdf6d5f29aa912dbc

Description: 3D Metamorphosis company uses blockchain technologies for holographic image interaction.

Official Site URL: https://3dmeta.io/

Official contract address confirmation:  https://3dmeta.io/  (after video section)

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://golos.io/ico/@ryabov-kozhushny/where-are-the-ico-companies-market-headedv-blockchain-in-the-real-sector-of-the-economy
2. https://golos.io/ico/@ryabov-kozhushny/outdoor-advertising-interactive-future-holographic-screens

**Comment by freeatnet** [comment]
Thank you for your request, @3DMetamorphosis! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by 3DMetamorphosis** [comment]
Hi ! 
 
Thank you for answer.  We are waiting your information about our token MMS !
 
---
 
Best regards

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
