### ISSUE TITLE
Vaynix (VNX) Listing on Exchange 

### ISSUE THREAD

**Issue by vaynix** [forkdelta/tokenbase#1245]
**Token address:** 

Contract Address: 0xbbf1885C21604Ef777009aCa8ff549EE96Bb3D7C 
Total Supply: 10,000,000,000 VNX 
Token Symbol: VNX 
Token Decimals: 18

**Issuer's official website:**

https://vaynix.com/

**Description:** 

Vaynix iѕ a financial system & crypto currency thаt ореrаtеѕ with borderless interaction аrоund the glоbе, оnсе уоu are соnnесtеd tо intеrnеt, nо matter thе geographical diѕtаnсе bеtwееn thе ѕеndеr and rесеivеr.
Is more than just a simple cryptocurrency it’s a tool that helps vendors, allow anonymous transaction focuses on privacy . Our vendors can sell their products, accept Vaynix through our platform,

**A link to the official contract address confirmation:** 

https://vaynix.com/ in the home page (index)  Under "Contract Information"

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://bitcointalk.org/index.php?topic=3239397.20

**Comment by freeatnet** [comment]
Thank you for your request, @vaynix! We'll review it as soon as we can. In the meanwhile, here's what to expect:
* Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
* Keep an eye on this issue. We will post all follow-up and additional questions here.
* You will receive a notification once your request has been reviewed for completeness and accepted.
* You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note: 
* Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
* We will not send or accept email or direct messages related to token addition requests.

**Comment by vaynix** [comment]
Thanks for fast answer, We are waiting your review

Cheers !

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by vaynix** [comment]
Here:

https://bitcoinexchangeguide.com/vaynix-ico-vnx-token/
https://coinworldstory.com/vaynix/
