### ISSUE TITLE
Listing Partial Basic (PB) token

### ISSUE THREAD

**Issue by shamelessuselessethereumtokencopy** [forkdelta/tokenbase#1249]
A token that is mined on the Ethereum blockchain by miners that are created by Ethereum transactions.

No premine or ICO, but a permissionless system where anyone can add a node/miner at anytime for just the gas cost + $0.5 worth of Ether.

Improves upon the 0xBTC system by also using a virtual PoW system to distribute tokens, but without wasting electricity.

Contract: 0x9081ceb359b6F42640651E11F5BFB4D4B84aA66F
Site: https://partialbasic.com/

**Comment by Kryptoniq** [comment]
Thank you for your request, @shamelessuselessethereumtokencopy  ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
Keep an eye on this issue. We will post all follow-up and additional questions here.
You will receive a notification once your request has been reviewed for completeness and accepted.
You will receive another notification when the token you requested is about to be added, along with the date when it is added.
Please note:

Adding a token to ForkDelta Tokenbase is **free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically,
1. Please provide a link to the official contract address confirmation. Contract address confirmation MUST be linked from the official website and MUST be visible publicly. If the confirmation is not visible immediately, include an explanation of how to find it.
2. Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

    Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
    Note:
    * We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
    * Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
