### ISSUE TITLE
CLN - Colu Local Network

### ISSUE THREAD

**Issue by jarmstrong** [forkdelta/tokenbase#125]
**The contract address.**
0x4162178b78d6985480a308b2190ee5517460406d

**A link to the token issuer's official website.**
https://cln.network

**A couple sentences for token description.**
The CLN is a payment network that aims to utilize the power of cryptocurrencies to create an open, better, more transparent infrastructure for processing payments, that can offer a competitive alternative to credit card companies and closed-network payment providers.

**A link to an official page confirming the contract address.**
https://intercom.help/colu_cln/cln-token/how-can-i-add-the-cln-token-to-my-ether-wallet (This FAQ page is linked from https://cln.network)

**A link to a third-party review or discussion of the token, like an established ICO review blog.**
https://icobench.com/ico/colu-local-network
https://www.inc.com/john-koetsier/this-ico-is-not-like-other-icos-colu-is-already-in-use-locally-with-62k-monthly-transactions.html
https://www.coindesk.com/blockchain-startup-colu-raises-14-5-million-new-funding/

**Comment by JonathonDunford** [comment]
#127
