### ISSUE TITLE
Add PCHAIN (PAI)

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#1252]
**Token address:**
0xb9bb08ab7e9fa0a1356bd4a39ec0ca267e03b0b3

**Issuer's official website:**
https://pchain.org/

**Description:** 

> The PChain ICO and PCH Token offer a multi-chain system designed to address the dual issues of scalability and interoperability. Toward the goal of maximizing versatility, the PChain protocol leverages features like side-chain architecture, cross-chain transactions and a smart contract data oracle. PChain is also the first multi-chain solution to be EVM-compatible.

**A link to the official contract address confirmation:** 
TODO

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://cryptobriefing.com/pchain-ico-review-pch-token-analysis/
2. https://hacked.com/ico-analysis-pchain/

**Comment by Kryptoniq** [comment]
Contract address can be found on CMC: https://coinmarketcap.com/currencies/pchain/.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xb9bb08ab7e9fa0a1356bd4a39ec0ca267e03b0b3, https://pchain.org/
