### ISSUE TITLE
Add Origami Network (ORI)

### ISSUE THREAD

**Issue by julienbruitteORI** [forkdelta/tokenbase#1253]
**Token address:**  0xd2fa8f92ea72abb35dbd6deca57173d22db2ba49

**Issuer's official website:** https://ori.network

**Description:** Origami Network is a protocol for building marketplace. Origami Network solves several existing problems related to online marketplace development and maintenance, escrow payments, and trusted reviews. ORI Token will be used to : 
- Purchase goods and services using Origami Payment
- Used to get more reviews, and as a rewards on the Origami Reviews.

**A link to the official contract address confirmation:** https://ori.network/contract-address/

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://cryptopotato.com/origami-network-decentralized-marketplace-protocol-payments-reviews/
2. https://icorating.com/analytics/indepth/origami-network-rating-review/
3. https://icobench.com/ico/origami-network
4. https://www.icotokennews.com/icos/origaminetwork/
5.  https://www.youtube.com/watch?v=Rux_FjzADx8
6. https://www.youtube.com/watch?v=3wvQ39mxBW4&t=293s

**Comment by freeatnet** [comment]
Thank you for your request, @julienbruitteORI! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
