### ISSUE TITLE
Wanna list foolcoin on forkdelta

### ISSUE THREAD

**Issue by loophe** [forkdelta/tokenbase#1256]
Wanna list foolcoin on forkdelta
Contract : 0x966EAbDE25c4821B05bE617db5884efC74F0347f

**Comment by Kryptoniq** [comment]
Thank you for your request, @loophe. 

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate.
