### ISSUE TITLE
Add CoxxxCoin (CXC)

### ISSUE THREAD

**Issue by ConorCoxxx** [forkdelta/tokenbase#1257]
Hello Fork Delta!
This is Conor from Coxxx Coin (CXC) www.coxxxcoin.com
Coxxx Coin is a private secure decentralized currency for the adult industry based on the Ethereum blockchain. 
In addition to fast transactions and low fees Coxxx Coin provides a solution to the monetary imperfections and financial discrimination of the adult industry specifically when it comes to billing and banking.
Since 2012 we have excelled at connecting the adult industry on a large scale nationwide through a successful reputable adult talent agency known as Coxxx Models www.coxxxmodels.com
We plan for Coxxx Coin to be widely used among producers, models, and many other types of adult businesses by providing our numerous connections within the adult industry this much improved financial alternative. There are many practical uses both for business to business transactions as well as business to consumer.
We noticed you are doing some great things with your exchange and we wanted to reach out to see what it would take to have Coxxx Coin listed?
Just let me know if you have any questions! And feel free to read more about Coxxx Coin here- http://coxxxcoin.com/Main/WhitePaper
Thank you!

**Comment by freeatnet** [comment]
Thank you for your request, @ConorCoxxx! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by ConorCoxxx** [comment]
---
name: Add a New Token
about: Request addition of a new token to tokenbase

---



**Token address: 0xaffd185f4e505904566cdc9677a5efc2e9875b8b **


**Issuer's official website: www.coxxxcoin.com**


**Description:** 


**A link to the official contract address confirmation:  https://etherscan.io/token/0x2134057c0b461f898d375cead652acae62b59541  **  This can be found on our website www.coxxxcoin.com by clicking the "Get Coxxx Coin" button in the middle of the screen and you will be directed to our Pastebin page. Once on the Pastebin page if you go to line 9 of the text you can find the link to our contract address.


**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://brokeassstuart.com/blog/2018/04/25/coxxx-coin-cryptocurrency-will-let-you-perverts-buy-porn-discreetly/

https://avn.com/business/press-release/technology/coxxx-models-launches-cryptocurrency-coxxx-coin-759392.html

https://www.xbiz.com/news/233225/coxxx-models-offers-coxxx-coin-ico

1. https://coxxxcoin.slack.com

2. https://github.com/coxxxcoin/smart_contract 

We have Reddit and Twitter and a few others but it seems you are saying those are "unacceptable". What would be helpful here are examples of what IS acceptable!

**Comment by freeatnet** [comment]
@ConorCoxxx We try to make sure there's a few independent sources of information and discussion of the token/project/token issuing entity for users to consider. E.g., https://www.finder.com.au/coxxx-coin-analysis poses some interesting questions for CXC.

For an example of a more serious review, see https://hacked.com/ico-analysis-destream/ or https://cryptobriefing.com/friendz-ico-review-fdz-token-rating/. Here's a source for fact-checking information: https://icocheck.io/

**Comment by ConorCoxxx** [comment]
Gotcha. Thanks for the info. That is a very ignorant article that doesn't understand what we are as a company whatsoever. We are one of the biggest adult talent agencies in the business and we have good relationships with hundreds of adult businesses and connections to thousands. It is going to take an entity like us to make cryptocurrency wide spread within the adult industry. Most the other adult industry coins are more tech people trying to wiggle their way in the adult industry. I know adult businesses and I do not see them getting involved with random tech companies but I could easily see them trusting us since they already do business with us. All of these questions are answered thoroughly in our white paper- http://coxxxcoin.com/Main/WhitePaper
As for the reviews. We will contact review companies soon and be back in touch.
One of our first steps was to get it on an exchange, we're now on (Cfinex) and we're about to really start marketing.
Thank you
