### ISSUE TITLE
Add Letsfair (LTF)

### ISSUE THREAD

**Issue by tiago-marques** [forkdelta/tokenbase#1258]
**Token address:**
0x411A81C8Cd604941be13dBBD33B54e6f25d84683

**Issuer's official website:**
https://letsfair.org/

**Description:** 
The goal of the Letsfair project is to build a shared economy network, which in practice, is a marketplace for many types of apps. Our biggest challenge is to promote a decentralized work organization.

**A link to the official contract address confirmation:** 
https://letsfair.org/investor/#tokens

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://medium.com/letsfair
2. https://bitcointalk.org/index.php?topic=4093639.0
3. https://www.youtube.com/channel/UCF2MkArjKSK0UYw952IwtHA
4. https://letsfair.com/pieceofcake (MVP)
5. https://play.google.com/store/apps/details?id=com.letsfair.pieceofcake
6. https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1382234154&mt=8

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
