### ISSUE TITLE
Add Falcon (FALC)

### ISSUE THREAD

**Issue by Qtdeejay** [forkdelta/tokenbase#1259]
The contract address.
0xfc5A50D9492066AB95d9fB732f3423dF71bfAA66

A link to the token issuer's official website.
Http://Falconpaymaster.com
Http://FALCONFUN.SLACK.COM. 

 token's description: Blockchain rewards and loyalty platform bringing security into business marketing and sport betting

A link to an official page confirming the above contract address:https://etherscan.io/address/0xfc5a50d9492066ab95d9fb732f3423df71bfaa66

Links to third-party reviews.
 Reddit:http:// reddit.com/user/falconfun
Steemit: http://steemit.com/falconfun
Slack: http://falconfun.slack.com
Http://twitter.com/Falcontoken

**Comment by freeatnet** [comment]
Thank you for your request, @Qtdeejay! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
