### ISSUE TITLE
Add Token AIRDROP

### ISSUE THREAD

**Issue by AirdropGift** [forkdelta/tokenbase#1261]
Token address:
0xba7435A4b4C747E0101780073eedA872a69Bdcd4

Issuer's official website:
http://airdrop.gift

Description:

AIRDROP (AirdropToken) is the world's first airdrop ecology public TOKEN, committed to establish future airdrop ecology with all holders. Airdrop "consensus groups" will be the basis for future "consensus consensus", and will also be the largest "consensus group". AIRDROP is not only an ecological public TOKEN but also has the function of airdrop targeting and parameterization. AirdropToken will also be most distinctive value flag TOKEN.

A link to the official contract address confirmation:

http://Airdrop.Gift/index.php

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

     JINSE: https://www.jinse.com/blockchain/196143.html
     QKW:http://www.qukuaiwang.com.cn/news/9316.html
     WEIXIN:https://mp.weixin.qq.com/s?__biz=MjM5NjA2MTA1Mg==&mid=2453337499&idx=3&sn=f76ab585d677be43570722b190088cbe&chksm=b1215f888656d69e23cdfd1d13816b87da3d2add5ae01c73550ff3fc1a7170751607b5d38431#rd

NOW TRADING:

     ETHERFLYER：https://www.etherflyer.com/trade.html?pairs=AIRDROP-ETH
     MEXC:https://www.mexc.io/trans/center?marketId=eth&vcoinId=91e412cb91444a1fb82c78f4ef2779e9
     DDEX:https://ddex.io/trade/AIRDROP-ETH

**Comment by freeatnet** [comment]
Thank you for your request, @AirdropGift! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
