### ISSUE TITLE
Add IADOWR Coin (IAD)

### ISSUE THREAD

**Issue by fantoniak** [forkdelta/tokenbase#1262]
**Token address:**
0xC1E2097d788d33701BA3Cc2773BF67155ec93FC4

**Issuer's official website:**
https://www.iadowrcoin.com

**Description:** 
IADOWR Coin is a ethereum block-chain based ERC20 token that is a platform to convert gaming tokens using our proprietary AI software to other currencies and a distribution system to directly fund charities through our unique interface.

**A link to the official contract address confirmation:** 
https://www.iadowrcoin.com/iad

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://finance.yahoo.com/news/newly-launched-iadowr-iad-coin-101600833.html
2. https://www.apnews.com/c471f6080a3bcb2aeafbdab9768f48b1
More on: https://www.iadowrcoin.com/resources

**Additional info**
Discord: https://discord.gg/drsAMrf
Email: admin@iadowrcoin.com
Facebook: https://www.facebook.com/iadowrcoin/
Github: https://github.com/IADOWR
Reddit: https://www.reddit.com/r/iadowrcoin/
Telegram: https://t.me/iadcoin
Twitter: https://twitter.com/iadowrcoin
Instagram: https://www.instagram.com/iadowrcoin/
Whitepaper: https://www.iadowrcoin.com/downloads/IADWhitePaper.pdf
Youtube: https://www.youtube.com/channel/UCErTZdtHI8ffuMK0p8Qh3wg

**Comment by freeatnet** [comment]
Thank you for your request, @fantoniak! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by fantoniak** [comment]
Hi, is there anything that we can do to support the review stage of this request?

Thanks
