### ISSUE TITLE
Why was WEB token listing request closed?

### ISSUE THREAD

**Issue by icocalendartoday** [forkdelta/tokenbase#1263]
Why do you keep on closing our requests for no reason and not replying?
Already closed 2 of them with no resolution:
#1165 & #662

Our token is already trading on 7 exchanges. Can we get an update on if and when will you list us on ForkDelta?

**Comment by freeatnet** [comment]
#662 is open, pending review. #1165 was closed as a duplicate.

**Comment by icocalendartoday** [comment]
All are closed, what is pending review or is a duplicate?

**Comment by icocalendartoday** [comment]
Are you closing the opened issue on purpose or what?

**Comment by freeatnet** [comment]
#662 is open:
![image](https://user-images.githubusercontent.com/138289/41192995-69cc1f36-6c0f-11e8-99c2-0b70530cf629.png)

We will review Webcoin (WEB) addition request it once the ICO closes, as per original request in #662.

#1165 was closed: only one request per token is allowed (comment on #662 if you want to add more info)
<img width="597" alt="screenshot 2" src="https://user-images.githubusercontent.com/138289/41193022-c9e77b72-6c0f-11e8-8988-fdc97ecb79af.png">
