### ISSUE TITLE
Add Aminacoin (AMK)

### ISSUE THREAD

**Issue by teamaminacoin** [forkdelta/tokenbase#1264]
**Token address:**
0xd0badc61104e66705d61dbd315fa67124369387f

**Issuer's official website:**
www.aminacoin.io

**Description:** 
The token is issued by the famous rappers Sido and Savas in Germany. It is a music coin.

**A link to the official contract address confirmation:** 
You can find it on the website under the button:
www.aminacoin.io

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.youtube.com/watch?v=UMZWrNbvg6Q
2. This is the official YouTube channel!

**Comment by freeatnet** [comment]
Thank you for your request, @teamaminacoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
- YouTube video provided is a music video and not a token review. 
- There are only 12 token holders and the last token transfer was 118 days ago. 
Is this project still alive?

**Comment by teamaminacoin** [comment]
We are NOT planning on doing an ICO - we have pre-allocated the tokens and are planning on doing some airdrops.

We have not done a token review as it will be a community project with the token being used as a utility token for us musicians. As you can see, the video, which features all famous artists in Germany, links to the token project.

The project is alive and will have lots of traction. We wanted to have the token on an exchange.

Is there anything else you would need to get listed?

Thank you
