### ISSUE TITLE
Add Diamond Horse Performance Token (DHP)

### ISSUE THREAD

**Issue by TPLivin** [forkdelta/tokenbase#1266]
**Token address:** 0x3E7Ed6BA88c4e44940612C76d5ABC973d153305b

**Issuer's official website:** http://diamondhorsegroup.net/

**Description:**  Diamond Horse Investment Group has created a crypto backed currency to allow for new investors coming into the crypto ecosystem the ability to diversify there portfolio with just one token. The Diamond Horse Performance Token (DHP) is a representation of the portfolio backing it giving the token holder indirect exposer to the underlying asset. 

**A link to the official contract address confirmation:**  http://diamondhorsegroup.net/  The token contract is not yet visible. It will be made available on the 16 June. Its place is being held by the beginning of the address. We do not want individuals accidentally sending any coins prior to release date so they don’t lose their ETH.

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://foundico.com/ico/diamond-horse-performance.html
2.https://bitcointalk.org/index.php?topic=3920908.msg39599610#msg39599610

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
