### ISSUE TITLE
Request to add The Tip Token (TTT)

### ISSUE THREAD

**Issue by justover** [forkdelta/tokenbase#1270]
**Token address:**
0x24358430f5b1f947B04D9d1a22bEb6De01CaBea2

**Decimals:** 
18

**Issuer's official website:**
https://thetiptoken.io

**Description:** 
TTT is an ERC20 token that aims to simplify the blockchain address system, facilitating the way people manage their wallets and revolutionizing the way they tip.
TTT allows every single ERC20 user to create one or more Short Address Name (SAN) directly linked to his wallet address.
Each SAN is an ERC721 token directly minted on our platform. The simple fact of holding this SAN in your wallet will automatically link it to your public key.
With this technology, services providers and content creators no longer need to share their Public Key to their customers : displaying their SAN will allow users to tip them in 1 click.

Moreover, several TTT based games are currently under development, the first one being CryptoRiddles:
http://www.cryptoriddles.com/
https://medium.com/@pr_43965/crypto-riddles-chapter-i-c351bfb4ea99

**A link to the official contract address confirmation:** 
https://thetiptoken.io/home/    In the FAQ at the bottom of our website
https://medium.com/@pr_43965/add-ttt-token-to-your-wallet-ddbf473022e1      In our official medium

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://smartoptions.io/ico-scoop-tip-token/
2. https://bitcointalk.org/index.php?topic=3195911
3. https://bitcoinexchangeguide.com/the-tip-token-ico-ttt-coin/

**A list of our partners:**
1. https://www.terawattled.com/
2. https://www.facebook.com/EDGESwm/
3. https://3des.network/
4. http://www.2seamdreamfoundation.org/
We are concluding 7 more partnerships as we speak, including a museum, a restaurant chain and several shops.

**Ongoing developments:**
https://medium.com/@pr_43965/the-tip-token-ttt-4-major-upcoming-developments-d85da7670718
1. The Webplatform & Marketplace
2. The Mobile App
3. The Website Widget
4. The TTT API

We already have a working beta platform, a functional API and we are working on the the mobile app and the website widget so our partners can start using TTT as soon as the ITO ends (Beginning of July).

**Token metrics and listings:**
We already have 3 exchange listings confirmed.

TTT Distribution:
- 65% of the tokens will be sold during the ITO phases.
- 15% of the tokens will be reserved for the ecosystem & airdrops.
- 20% of the tokens will be blocked for the team.

Raised Funds Allocation: 
- 40%  Product Development and Incubation for future ideas
- 25% Partnerships and interoperability with other platforms
- 25% Market and customer expansion focus
- 10% exchanges listings and advertising purposes

Moreover, I’ll add that we do not have a soft cap and we have already distributed more than 1 mil TTT during the pre ITO phases.
We believe the address system simplification is a revolution that will touch every single crypto user.
Tens of millions of ERC20 wallets are created every month, and even if only 1/1000 of them are willing to link it to a custom address name of their choice, that’s at least 500 000 TTT tokens being spent by customers just to create those custom addresse.

Regarding the unsold tokens :
- 10% will be airdropped to the Initial Token Offering participants
- 20% will be added to the tokens allocated to the ecosystem & airdrops
- 70% will be burnt

**Useful links:**
Our medium: https://medium.com/@pr_43965
Our twitter: https://twitter.com/TheTipToken
Our LinkedIn: https://www.linkedin.com/company/the-tip-token/
Our Facebook: www.facebook.com/thetiptoken
Our Telegram: https://t.me/thetiptoken

We have also been approached by several exchanges in order to discuss the implementation of the SAN technology on their platforms. If you are also interested, we would be pleased to work with you on it.

Thank you for considering our application, we are looking forward to trading TTT on ForkDelta.

**Comment by freeatnet** [comment]
Thank you for your request, @justover! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by justover** [comment]
Hello,

We would like to update the application with the following information : 
- The ITO is over and has been a success
- TTT is tradable on Etherdelta and will be added on NEXT.Exchange in July
- We are burning more than a third of the total supply

Looking forward to trading TTT on ForkDelta.

**Comment by justover** [comment]
Hello,

We would like to update this application with the following information :

The ITO is over and has been a success
TTT is tradable on Etherdelta and will be added on NEXT.Exchange in July
We are burning more than a third of the TTT total supply starting in August
Looking forward to trading TTT on ForkDelta.

**Comment by justover** [comment]
Hello,

Is there any missing information or document in our application?

Thank you by advance
