### ISSUE TITLE
List Conserve (UBI)

### ISSUE THREAD

**Issue by adfaous** [forkdelta/tokenbase#1271]
**Token address:** 0x93e99b0b5d8873bb1715812a6f2c5fc746855a23

**Issuer's official website:**
Conserve.io (under construction)

**Description:** The basic goals of the project is to provide basic income to all its holders, this will be a distribution of a million tokens monthly. And the total and maximum token will be finally capped @ a billion. 
When the website is live, holder's can buy  stuffs (books, foods, clothes etc) at affordable rate.  
This are just a drop of what was  in the whitepapers.

**A link to the official contract address confirmation:**  
https://mobile.twitter.com/ConserveUbi/status/1006075445832536064 (we are still constructing the website, the main reason of listing on forkdelta is to help those who didn't made the ICO to participate, we have our own target exchange)

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:** 
https://mobile.twitter.com/ConserveUbi

1. https://mobile.twitter.com/ConserveUbi/status/1005749176427216897
2.

**Comment by freeatnet** [comment]
Thank you for your request, @adfaous! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
