### ISSUE TITLE
PLCN - Fork PlusCoin

### ISSUE THREAD

**Issue by KristinaPlusCoin** [forkdelta/tokenbase#1272]
**Token address:** 0xcfc2437916a6df165235272dbfb116687bb1a00b

**Issuer's official website:** https://pluscoin.io/

**Description:** DS PLUS is a crypto cashback service for its users and a CPA platform for businesses in the whole world. It is based on a mobile app. PlusCoin is a cryptocurrency integrated in the mobile app and other DS PLUS platforms.

**A link to the official contract address confirmation:** https://pluscoin.io/ (PLCN contract address: 0xcfc2437916A6df165235272dbfb116687bb1A00b)

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://cryptellect.net/plcn-fork-tokena-pluscoin-vnutrennej-valyuty-platformy-ds-plus/
2. https://coinidol.com/blockchain-technology-in-marketing-pluscoin-introduce-crypto-cashback/

**Comment by freeatnet** [comment]
Thank you for your request, @KristinaPlusCoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by KristinaPlusCoin** [comment]
Thank you. We will await your questions and solutions.

**Comment by Kryptoniq** [comment]
Your roadmap ended may in May, 2018. Please provide a verifiable list of accomplished goals so far.

**Comment by KristinaPlusCoin** [comment]
Now we are preparing additions to White Paper. So far we have implemented points for the opening of the Marketplace, Exchange (the coin PLC had exchanges DDEX, IDEX, TIDEX, Etherdelta and Forkdelta). At the exchanges, we have now closed the auction so that people do not buy the old coin and are working to open new trades in the pair PLCN / ETH. Also, work is underway to open the P2P platform (we are developing a private Blockchain on Ethereum) and now we are conducting the latest tests of private Blockchain. This week we plan to open P2P for all tokenholders. Integration of Blockchain in the application will occur in August-September 2018, as we are developing a complex transaction system without commissions, so that transactions in the application are free and the user could receive coins without losses.

**Comment by KristinaPlusCoin** [comment]
Good afternoon! Sorry to trouble you. Wanted to clarify, can you approve our application for listing?

**Comment by therealMikkoK** [comment]
@KristinaPlusCoin hello, I'm in process of reviewing your token.
A few questions for the team:
1. Do you have presence in any social media, Telegram, Facebook?
2. Your road map indicates you have a working platform, have you any information on that?

**Comment by KristinaPlusCoin** [comment]
@therealMikkoK Did you receive information from me?

**Comment by therealMikkoK** [comment]
Hi @KristinaPlusCoin !
Can you provide links how you have informed your tokenholders of the coming change?
How will the people who don't make the change be affected, will the token be transferable after?
Will you have a desk where the old tokens can be changed for the new?
I see trades as recent as two hours ago with the old ticker, what will happen to these new token holders?

**Comment by KristinaPlusCoin** [comment]
**1. Can you provide any information about how you can get there?:**
https: //medium.com/@DsplusF/fork-pluscoin-the-launch-of-anti-crisis-measures-pluscoinnew-e824e426bd5f
+
Announcement in all our media:
1. All ICO participants will receive PLCN in the ratio 1 coin to 1 received PLC on May 10, 2018.
2. In case you've lost access to your wallet with, unfortunately, changing the wallet address is impossible. The accrual system works automatically.
3. If an ICO participant has additionally bought some coins after the ICO, he will be able to exchange these PLC by June 10, 2018 and later with a set ratio.
4. If an participant receives PLCN in the ratio 1 coin to 1 received PLC and then wants to exchange these PLCs (to deceive DS PLUS (PLCN)), such a request will be rejected.
5. Each exchange request before June 10, 2018 and further will be processed manually, in order to exclude the possibility of deception.
6. All PLC received after May 9, 2018 are not exchangeable.
Information on the ratio and the coefficients will be reported closer to June 10, 2018
If you were an ICO member, then new coins will be deposited into your wallet (Myetherwallet) automatically. If you received coins on Bounty, ICOBOX, exchange and in other ways, then you will need to apply for an exchange on the official website pluscoin.io (now this section is not on the site). All information on the exchange will be provided by June 10, 2018
+
https://youtu.be/emj84g98sAE
+
https://medium.com/@DsplusF/tidex-principle-of-work-with-new-plcn-token-3abf19ddec3a
+
https://medium.com/@DsplusF/the-ratio-for-exchange-of-plc-and-plcn-the-terms-of-pluscoin-fork-16b094b98488
+
https://medium.com/@DsplusF/working-day-of-the-team-ds-plus-pluscoin-23b830e9daab
These news have been posted for a very long time and all our tokenholders know about the innovations and Fork coins PlusCoin.

**2. How will the people who do not make the change be affected?**
Every person who is a coin holder PlusCoin can apply for a PLC exchange for PLCN. The exchange process is not limited by time limits. There is a very important condition that the team has established to exclude the possibility of exchanging coins for unscrupulous coin holders (the Leasing Company and one of the Funds that violated the terms of the contract). The exchange rule: "The Tokenholder can exchange all of his PLC coins for new PLCN coins, if he bought them before May 10, 2018". This rule did not affect the tokenholders, who had accounts on the TIDEX and IDEX exchanges, since these are centralized exchanges and we were able to close the auctions with a coin. Now we have already exchanged more than 2,500,000,000 PLCN for the holders and we continue to do this successfully.

**3. Will you have a desk where the old tokens can be changed for the new ?:**
Yes, the official website of the project contains all the necessary information for making a PLC exchange for a new coin PLCN: http://pluscoin.io/
There is also a special client portal where the tokenholder receives advice and assistance from moderators: https://dsplus.atlassian.net/servicedesk/customer/portal/1
The term of exchange is not limited. We will do the exchange as long as the applications are received.

**4. I see trades as recent as two hours ago with the old ticker, what will happen to these new tokens:**
Those people who buy coins PLC can not now get exchange for PLCN, as there are rules and they need to follow. But of course there are always exceptions, we try to be loyal to all token holders as much as possible. In any case, the coin will not be completely destroyed, since we have no right to do this. Bidding will continue if someone wants to buy PLC coins or sell, but the PlusCoin project will have absolutely nothing to do with it, since it does not support this coin. Specifically, to exclude the possibility of fraud, we transferred part of the PLC coins to a zero purse, which no one has access to: https://medium.com/@DsplusF/plc-burning-more-than-47-b8c807d6267f

**Comment by KristinaPlusCoin** [comment]
@therealMikkoK

**Comment by KristinaPlusCoin** [comment]
@therealMikkoK Did you receive information from me?

**Comment by therealMikkoK** [comment]
R1 (y)
looks like token holders are taken into consideration, and there is very little risk current token holders are unaware of the change.
I see no reason why the change should be halted.

**Comment by KristinaPlusCoin** [comment]
@therealMikkoK Please specify how long will the PLCN coin appear on Forkdelta? We are grateful to you for your prompt consideration and support!

**Comment by therealMikkoK** [comment]
@KristinaPlusCoin I've done what I can, and your issue appears to be quite high on the list. - I suspect not very much longer, but unfortunately I cannot give you an exact time. But much like everything else in cryptos, let´s say "soon". :)

**Comment by KristinaPlusCoin** [comment]
Thank you! We will look forward to the listing. Let's hope that the listing happens in the near future)
@therealMikkoK

**Comment by bobbypaintsstuf** [comment]
we are currently seeking some information please can you provide considered answers to the following 2 questions please.

1 - If I was to purchase PLC tokens today could I exchange them for PLCN through your swap system ? 

2 - If I purchased PLC token from an exchange in good faith and when I applied for the token swap and it became apparent to you that those tokens had originated from the entity that you refer too as being the catalyst for the token swap would my tokens still be swapped ?

thank you in advance

**Comment by KristinaPlusCoin** [comment]
Hello!
1. If you buy a PLC coin today, then you will not be able to exchange it, because there are exchange rules. All the tokenholders know about this rule. Bidding on centralized exchanges is closed. The only possibility of buying now is only on the Etherdelta or Fordelta, but there's no actual bidding. We do not support the PLC coin and its exchange trades.

2. Yes, you will in any case get an exchange, but we will warn you that you no longer need to buy coins there. We make an exchange for everyone who bought PLC coins before May 10, 2018.
@bobbypaintsstuf

**Comment by KristinaPlusCoin** [comment]
@therealMikkoK I hope that everything is fine with our application. Thank you.

**Comment by bobbypaintsstuf** [comment]
thank you for your previous answers - just 1 more question from me.

1 -  will your project swap the coins of all users who purchased coin on Forkdelta since 10 MAY 2018 ?

**Comment by KristinaPlusCoin** [comment]
@bobbypaintsstuf Coins purchased after May 10, 2018 have not yet been swap. However, we individually approach each tokenholder and solve complex issues through the client portal.

**Comment by KristinaPlusCoin** [comment]
Hello! I wanted to clarify the application for the listing is good? Can we give you some more information to speed up the process? @therealMikkoK @bobbypaintsstuf

**Comment by therealMikkoK** [comment]
@KristinaPlusCoin I agree there is no reason to keep the old token on FD. We want to be sure people who buy the new token will not suddenly realize that those tokens are worthless. I'm going to give this my approval.
@bobbypaintsstuf feel free to chime in. If it's OK with Bobby, he will close and comment and we go from there.

**Comment by bobbypaintsstuf** [comment]
I totally support the de-listing of the old coin @therealMikkoK

**Comment by bobbypaintsstuf** [comment]
also i have no objections to the listing of PLCN as the team indicates they will deal with users of the old coin PLC as fairly as possible - especially users who purchased on ForkDelta who were unaware of the swap and bought the old coin in good faith since their coin swap @therealMikkoK @freeatnet

**Comment by KristinaPlusCoin** [comment]
Thanks for your support. We hope that the coin's listing (PLCN) will be successful in the near future. We are waiting for listing on the exchange Forkdelta, which would stabilize the price on all exchanges. @therealMikkoK @bobbypaintsstuf

**Comment by KristinaPlusCoin** [comment]
Good afternoon! Wanted to specify where we are in the queue for listing? How long does it last? A large number of our tokenholders have been waiting for several months already for ForkDelta, and now, because of the lack of news, they are very hard on us psychologically. Help please understand this issue. @therealMikkoK @bobbypaintsstuf

**Comment by KristinaPlusCoin** [comment]
@therealMikkoK @bobbypaintsstuf Hello! It has been many days, and we never found out when about PLCN will be placed on Forkdelta. Can you help clarify the approximate timing of the shipment?

**Comment by bobbypaintsstuf** [comment]
You will be communicated with and told in advance when that part is about to be done 🤝

**Comment by KristinaPlusCoin** [comment]
@therealMikkoK Hello. We applied for the coin placement of the PPSN 3 months ago. Earlier, in 2017, the coins were listed for a couple of weeks on Etherdelta. Why does Forkdelta have such a long coin listing? I understand that a lot of coins want to be placed, but 3 months for listing is a very very long time. We are very worried. How can we speed up the process of listing a coin PLCN?

**Comment by therealMikkoK** [comment]
@KristinaPlusCoin 
Hey Kristina, You're my first customer when I get the get go from "The Man".
We're getting very close. Probably not over the weekend though.
Please have patience a little longer.
All the best to the team.

**Comment by KristinaPlusCoin** [comment]
@therealMikkoK Thank you so much! We'll wait.

**Comment by KristinaPlusCoin** [comment]
Thank you :-) I understand that today the PLCN coin will appear on Forkdelta, and we can already prepare joyful news for the tokenholders? ;) @freeatnet @therealMikkoK

**Comment by therealMikkoK** [comment]
@KristinaPlusCoin yes you can. The reason it has been on hold is the token file has been on the back burner due to metamask issues, that have now been repaired to my understanding.

**Comment by KristinaPlusCoin** [comment]
Good afternoon! We found errors in the work of the Forkdelta exchange. PLCN coins had large trading volumes yesterday, but they were not displayed in the "Volume" list. Coins need to display volumes, as this is required by Coinmarketcap in order for us to appear in their lists. Also our tokens holders were filled with the following situation:
There are 7 identical orders in the red zone, but with a different selling rate for the coin in the amount of 7071189.938 PLCN. We do not know who placed these orders. One of our token holders bought this order, but it does not disappear from the exchange for the third day and no one can buy it. It is impossible to buy any of these 7 orders. Help please understand @freeatnet @therealMikkoK
