### ISSUE TITLE
Add AUSCOIN COIN (AUSC)

### ISSUE THREAD

**Issue by samkazzauscoin** [forkdelta/tokenbase#1273]
https://etherscan.io/token/0x59f1b6d0f5105cf025a3de58858a9363f4fef084

http://auscoin.io

Our vision is to capitalise on the potential to integrate Bitcoin and cryptocurrency into daily life. This will completely change the way the world transacts; revolutionising conventional contracts between individuals, businesses, organisations and everyone in between through our network of 1200 Cryptocurrency ATMs.

https://www.auscoin.io/static/assets/documentation/AUSCOIN_FAQs.pdf

https://www.youtube.com/watch?v=x17sygzlU6I
https://www.youtube.com/watch?v=AlBf2-LV01k&t=14s
https://www.news.com.au/national/victoria/melbourne-mans-15m-bitcoin-gamble/news-story/cd76174f37e155eab65d02dd7017d3cd

**Comment by freeatnet** [comment]
Thank you for your request, @samkazzauscoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
@samkazzauscoin A request for Auscoin already exists here: #851, so I'm closing this as a duplicate. If you have additional information, please add it to the existing request. Thanks!

**Comment by samkazzauscoin** [comment]
I see. What was the verdict on that? A member of the community must have applied there.

I am the Founder.

**Comment by freeatnet** [comment]
@samkazzauscoin It is yet to be properly reviewed. It would help move things along if that request followed the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by samkazzauscoin** [comment]
Hello, 

I have updated everything as requested. Is there anything further you
require to be listed? 

This is the status of the post. Thank You so much! 

On 11/06/2018 20:44, Arseniy Ivanov wrote: 

> @samkazzauscoin [1] It is yet to be properly reviewed. It would help move things along if that request followed the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md [2] 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].

-- 

SAM KARAGIOZIS 

Director 
SK PROPERTY

E: sam_karagiozis@skproperty.com.au II W: www.samkaragiozis.com 

 

Links:
------
[1] https://github.com/samkazzauscoin
[2]
https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
[3]
https://github.com/forkdelta/tokenbase/issues/1273#issuecomment-396201196
[4]
