### ISSUE TITLE
Add MinerToken

### ISSUE THREAD

**Issue by AllForMiner** [forkdelta/tokenbase#1276]
Token address:
0xc45c684c404b2af48ca53229afdc56eb06139808

Official website:
https://forminerpro.com/en

Description: 
MinerToken  is a cryptocurrency that will be used to buy and sell cloud computing goods, as well as other AllForMiner services and future products. This currency will be used as a unit of account for all economic transactions in AllForMiner ecosystem and as a basis for interaction with other digital services.

A link to the official contract address confirmation: 
You can find it on the website in description "About the project"
https://forminerpro.com/en

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://www.altcoinstalks.com/index.php?topic=22550.0
https://bitcointalk.org/index.php?topic=4185508.20

**Comment by freeatnet** [comment]
Thank you for your request, @AllForMiner! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
- Only 7 token holders.

Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
