### ISSUE TITLE
Please add DALA to ForkDelta

### ISSUE THREAD

**Issue by kurtgrela** [forkdelta/tokenbase#1277]
**Token address:**  0xa87c3ec87eb802aad080df0adb331e504d327e5d
https://etherscan.io/token/0xa87c3ec87eb802aad080df0adb331e504d327e5d

**Issuer's official website:**
https://www.dala.org

**Description:** 

Enabling instant, borderless micropayments in Africa.  Wala is a financial platform; DALA is the utility token that can be exchanged for consumer products and services, such as purchasing airtime, data, paying electricity bills or kids' school fees.

**A link to the official contract address confirmation:** 

Not sure how to find this.  Your expertise would be appreciated.  

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.   Crypto Startup Wala Is Reaching Africans with Ethereum Micropayments, Coindesk June 11, 2018  https://www.coindesk.com/african-startup-ethereums-scaling-issues/

2.  Newtown Partners has invested in and companies that our partners, Vinny Lingham [CEO of Civic ($CVC)] and Llew Claasen [Executive Director of the Bitcoin Foundation], have personally invested in.        https://www.newtownpartners.com/about/portfolio-of-companies/

3.  Coin Center Travel Series: Cape Town, South Africa May 30, 2018 https://coincenter.org/entry/coin-center-travel-series-cape-town-south-africa 

4.  Wala Launches Zero-Fee Money Transfer App in Uganda, South Africa, and Zimbabwe April 28, 2018 http://bitcoinafrica.io/2018/04/28/wala-launches-zero-fee-money-transfer-app/

**Comment by freeatnet** [comment]
Thank you for your request, @kurtgrela! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
