### ISSUE TITLE
ADD VERDICT TOKEN

### ISSUE THREAD

**Issue by Qtdeejay** [forkdelta/tokenbase#1280]
Token address: 0x9073d050Fa90fe910B74E2B1Eb7EFE5A016EAa05
https://etherscan.io/token/0x9073d050Fa90fe910B74E2B1Eb7EFE5A016EAa05

Issuer's official website:
https://www.verdict.co.uk
Description:

Enabling instant, borderless micropayments . is a financial platform;  an utility token 

A link to the official contract address confirmation:

Not sure how to find this. Your expertise would be appreciated.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
Http://Twitter.com/Verdicttoken
Http://T.me/Verdicttoken

**Comment by freeatnet** [comment]
Thank you for your request, @Qtdeejay! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please note the following about third-party review links:
> Links should be of at least two disctinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments at length from high ranked users in BitcoinTalk.
> Note:
> * We are looking for substance in reviews. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
> * These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels do not count as third-party discussion).
