### ISSUE TITLE
Requesting to be Listed EPay (EPAY)

### ISSUE THREAD

**Issue by Etherpay** [forkdelta/tokenbase#1281]
**Request to list EPAY Token

Name: EPAY

Symbol: EPAY

Token: ERC20

Contract address: 0x61d900fffb8e8fe88f57f96c860ed94aa903e412

Etherscan: https://etherscan.io/token/0x61d900fffb8e8fe88f57f96c860ed94aa903e412

Official website: https://www.etherpaywallet.com/

Whitepaper: http://docdro.id/o6CYsXD

** Third-party source:

Link to Telegram: https://t.me/etherumpay_bounty

Link to Twitter: https://twitter.com/EthereumPay

Link to Facebook: https://www.facebook.com/EPayex/

Link to Bitcointalk: https://bitcointalk.org/index.php?topic=3195371

Link to Medium: https://medium.com/@ethereumpay.wallet

Link to Reddit: https://www.reddit.com/user/ethereumpay

Link to Steemit: https://steemit.com/@etherpaywallet

Link to Github: https://github.com/Etherpayex/EthereumPayToken

Description:

EPay is a platform for the future of trading market and online wallet 2.0

While existing solutions offer to solve just one problem at a time, our team is up to build a secure, useful, & easy-to-use product based on private blockchain. It will include easy cryptocurrency payments integration, and even a digital arbitration system.

​At the end, Our aims to integrate all into a unified blockchain ecosystem, which will help create a truly effective, transparent and reliable platform.

Email: contact@etherpaywallet.com

Thank you!

**Comment by freeatnet** [comment]
Thank you for your request, @Etherpay! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please note the following about third-party review links:
> Links should be of at least two disctinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments at length from high ranked users in BitcoinTalk.
> Note:
> * We are looking for substance in reviews. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
> * These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels do not count as third-party discussion).
