### ISSUE TITLE
Bowhead Health (AHT)

### ISSUE THREAD

**Issue by chet84** [forkdelta/tokenbase#1283]
**Token address:**
0x4cEf5a02C36253CFB06825acE2a356E78000145f

**Issuer's official website:**
https://www.bowheadhealth.com/

**Description:** 
The token has two purposes:
• Provides capital to the company via a tokensale in order to develop products and services
• Enables early tokensale buyers to receive payments from future anonymized health data
requests being completed by users
o Eventually, we expect the tokens to be used for products and services offered by
Bowhead

**A link to the official contract address confirmation:** 
https://medium.com/@bowheadhealth/official-bowhead-tokenswap-guide-8c7d7c940338

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://steemit.com/cryptocurrency/@aghunter/review-of-bowhead-health-aht-the-blockchain-s-most-ambitious-medical-project
2.https://www.forbes.com/sites/annabelacton/2017/07/14/the-future-of-health-its-in-your-hands/#730111b12af2

**Comment by Kryptoniq** [comment]
Please verify your contract source code on etherscan.
https://etherscan.io/address/0x4cEf5a02C36253CFB06825acE2a356E78000145f#code
