### ISSUE TITLE
HAC

### ISSUE THREAD

**Issue by kbgrfx** [forkdelta/tokenbase#1284]
**Token address:**
0x7ed172530f9822cd0573b895853e3f745f4108b4

**Issuer's official website:**
http://hadescoin.net/

**Description:** 
HadesCoin
Make money. Get paid. We show you HadesCoin, Change the world.

**A link to the official contract address confirmation:** 
https://etherscan.io/address/0x7ed172530f9822cd0573b895853e3f745f4108b4

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://bitcointalk.org/index.php?topic=4385724.0
2.  https://t.me/HadesCoinOfficalGroup

**Comment by freeatnet** [comment]
Please update your request with the following:

1. Please provide a link to the official contract address confirmation. Contract address confirmation MUST be linked from the official website and MUST be visible publicly. If the confirmation is not visible immediately, include an explanation of how to find it.
2. Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

    Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
    Note:
    * **We are looking for substance in reviews.** BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
    * **Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.**
