### ISSUE TITLE
Add NOBS

### ISSUE THREAD

**Issue by Ado808** [forkdelta/tokenbase#1285]
Contract address: 

0xf4faea455575354d2699bc209b0a65ca99f69982
--

Issuer's official website: https://nobscrypto.com

Official contract address confirmation: Email that was sent to every airdrop registrant https://imgur.com/a/xj05uYk

A link to a third-party review or discussion of the token:
No review/ discussion available unfortunately 

Description: Data-driven Altcoin Investing

Notice: All tokens were airdropped (no ICO planned atm) so there are no whales involved. Promoted by John Mcafee. Here is the link for his promotion of round 1 of airdrop: https://twitter.com/officialmcafee/status/992500439248711680 .I know he also tweeted about round 2 but I'm too lazy to find it

Links:
Web: https://nobscrypto.com/
Twitter: https://twitter.com/noBScrypto
facebook: https://www.facebook.com/noBScrypto/
telegram: http://bit.ly/noBSCtg
Email: support@noBscrypto.com

**Comment by freeatnet** [comment]
Thank you for your request, @Ado808! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please find a contract address confirmation. Thansk!

**Comment by Ado808** [comment]
@freeatnet I don't have any contract address confirmation besides that email. But you can ask admins in  telegram group whether the contract address is correct

**Comment by freeatnet** [comment]
@Ado808 We can work it like so:
* https://twitter.com/nobscrypto/status/992464885765287937, linked from https://twitter.com/noBScrypto
* https://twitter.com/noBScrypto is linked from the official website, https://nobscrypto.com/

**Comment by freeatnet** [comment]
The source of information for this token is largely https://s3-us-west-2.amazonaws.com/nbsc-image-hosting/no-bs-token-chart.jpg.

In this particular case, it seems that the name is fairly well-established and there's an understanding of what this is.

@Ado808 Thank you for your request. I have verified that it sufficiently fulfills the requirements. You will receive a notification a few days before the token is live.
