### ISSUE TITLE
Add MetaMorph (METM)

### ISSUE THREAD

**Issue by rtinedal** [forkdelta/tokenbase#1286]
**Token address:**
0xfef3884b603c33ef8ed4183346e093a173c94da6

**Issuer's official website:**
Https://metamorph.pro

**Description:** 

MetaMorph is an easy Coin Exchange interface that can switch digital currencies from one cryptocurrency to another. The coin switching which we call “Morph” combines the most popular cryptocurrencies on the market.

**A link to the official contract address confirmation:** 

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=3345564
2. https://www.reddit.com/user/MetamorphPro

**Comment by freeatnet** [comment]
Thank you for your request, @rtinedal! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
