### ISSUE TITLE
Add EIB Token

### ISSUE THREAD

**Issue by eibexchange** [forkdelta/tokenbase#1287]
Token address:
0x2f2540218770da363dd3320b107f38fbeaf62472

Issuer's official website: https://eib.ai/

Description:
The EIB is developed based on the Ethereum code ERC20/ERC223 and EIB runs on an Ethereum. It will be developed as a blockchain era bank.

A link to the official contract address confirmation:*
https://eib.ai/#eib_wallet

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://liveairdrops.co/airdrop/eib-ai/
2. https://bitcointalk.org/index.php?topic=4363233.0
3. https://youtu.be/QAcxljXp9sM
4. http://blog1122taufiq.blogspot.com/2018/06/eib-through-ico-with-resource-of.html

**Comment by freeatnet** [comment]
Thank you for your request, @eibexchange ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
