### ISSUE TITLE
TRXC Token listing Request

### ISSUE THREAD

**Issue by TronClassic-TRXC** [forkdelta/tokenbase#1288]
**Token address:**
0xad5fe5b0b8ec8ff4565204990e4405b2da117d8e

**Issuer's official website:**
https://www.tronclassic.xyz/

**Description:** 
TRXC is an ERC20 token that serves as a social digital currency with all major social network to make the process of sending and receiving money rewarding for everyone.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xad5fe5b0b8ec8ff4565204990e4405b2da117d8e

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://twitter.com/TronClassic
2. https://www.facebook.com/groups/1853017211395204/?ref=bookmarks

**Comment by Kryptoniq** [comment]
#1080
