### ISSUE TITLE
apply for TRXC token listing 

### ISSUE THREAD

**Issue by TronClassic-TRXC** [forkdelta/tokenbase#1289]
**Token address:**
0xad5fe5b0b8ec8ff4565204990e4405b2da117d8e

Token Name: TronClassic

Token Symbol: TRXC

Total Supply: 1,000,000,000,000 

**Issuer's official website:**
https://www.tronclassic.xyz/

**Description:** 
TRXC is an ERC20 token that serves as a social digital currency with all major social network to make the process of sending and receiving money rewarding for everyone.

**A link to the official contract address confirmation:** 
https://www.tronclassic.xyz/

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. Twitter: https://twitter.com/TronClassic
2. facbook group: https://www.facebook.com/groups/1853017211395204/
3. Bitcointalk: https://bitcointalk.org/index.php?topic=3829331
4. Telegram: https://t.me/ClassicTron
5. whitepaper:  https://drive.google.com/file/d/1_DpQVRTQbR8m3Qj4NGA70sjqhP7Qt_5w/view
6. youtube: https://www.youtube.com/channel/UCOwp1XMHOiLJ-meqNS4h8HQ
7. github: https://github.com/TronClassic-TRXC
8. Reddit: https://www.reddit.com/user/TRONCLASSIC

**Comment by Kryptoniq** [comment]
If you continue this way, you token may end up not getting reviewed. Stop creating new issues.

**Comment by TronClassic-TRXC** [comment]
ok but i want to know about my ticket status ...

**Comment by TronClassic-TRXC** [comment]
Atleast answer me if any issue how i resolve this .....

**Comment by GoldenDave** [comment]
Look at the website. Pretty obvious scamcoin.
