### ISSUE TITLE
Listing Request: POWE Token

### ISSUE THREAD

**Issue by powether** [forkdelta/tokenbase#129]
**Announcement:** https://bitcointalk.org/index.php?topic=2975189.msg30568161#msg30568161

**Official website:** poweth.org

**Contract address:** https://etherscan.io/address/0x2ee6d1a3ba4e80a61bdfb48a90d40a5cef455326
**Symbol:** POWE
**Full name:** PoWEth
**Type:** ERC20

**Comment by JonathonDunford** [comment]
#133
