### ISSUE TITLE
Request to list the FREE coin

### ISSUE THREAD

**Issue by TheFreeCoin** [forkdelta/tokenbase#1290]
**Token address:**       0x2f141ce366a2462f02cea3d12cf93e4dca49e4fd

**Issuer's official website:**   www.FREEcoin.technology

**Description:** 

Disruptive innovator offering a large amount of tokens at low price.  Target is to have a maximum number of people worldwide to start participating in the blockchain/cryptocurrency economy.

**A link to the official contract address confirmation:**  See our website : www.FREEcoin.technolgy

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1) discussion on Bitcointalk about our "announcement" https://bitcointalk.org/index.php?topic=3267883.msg34055291#msg34055291
2) discussion on bitcointalk about our bold ICO objectives : https://bitcointalk.org/index.php?topic=3622794.msg36603470#msg36603470
3) announcement on reddit : https://www.reddit.com/r/altcoin/comments/8q8ttu/monthly_ico_token_sale_jibba_jabba_june_11_2018/

All info and whitepaper can be found on www.FREEcoin.technology.

(edit by @freeatnet: removed unnecessary text)

**Comment by freeatnet** [comment]
Thank you for your request, @TheFreeCoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by TheFreeCoin** [comment]
I updated the orignal post with the missing information

kind regards,
Ben Bervoets

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by TheFreeCoin** [comment]
Discussion about purpose of project - this also include the names of the project members  : https://bitcointalk.org/index.php?topic=3267883.msg34055291#msg34055291


Discussion about our objective to become to crypto with the highest marketcap : https://bitcointalk.org/index.php?topic=3622794.msg36603470#msg36603470
By June 1st, 2018 the FREE coin will be the largest cryptocurrency on the market<https://bitcointalk.org/index.php?topic=3622794.msg36603470#msg36603470>
By June 1st, 2018 the FREE coin will be the largest cryptocurrency on the market
bitcointalk.org



________________________________
Van: Krypton <notifications@github.com>
Verzonden: zaterdag 23 juni 2018 23:14
Aan: forkdelta/tokenbase
CC: TheFreeCoin; State change
Onderwerp: Re: [forkdelta/tokenbase] Request to list the FREE coin (#1290)


Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

  *   We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
  *   Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by Kryptoniq** [comment]
Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by TheFreeCoin** [comment]
We submitted a press release to the major blogs this morning.

We hope that this will result in additional external reviews of our project.

________________________________
Van: Krypton <notifications@github.com>
Verzonden: maandag 25 juni 2018 19:55
Aan: forkdelta/tokenbase
CC: TheFreeCoin; State change
Onderwerp: Re: [forkdelta/tokenbase] Request to list the FREE coin (#1290)


Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

  *   We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
  *   Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by TheFreeCoin** [comment]
after our press release we got reactions from leading blogs such as cryptocoinsupdates and coinidol. The result is that blogs are willingly to write an article about a crypto, on the condition that they are paid for it (between 150 and 750 dollar). Is this kind of paid articles the stuff that Forkdelta is requiring ? 
In meantime our crypto increased with 1926 % (see EG transactions on token.store where we are listed since a couple of weeks).

**Comment by benbervoets** [comment]
check our Instagram (freecoin2018) : Vitalik Buterin himself did like our last Instagram posting about our project paving the way for a crypto-only future :)

what more review can you expect :) :)

**Comment by TheFreeCoin** [comment]
COINLIB.IO (a site to be compared with coinmarketcap.com) included our FREE coin in their review, including a technical analysis for interested buyers : [](https://coinlib.io/coin/FREE/FREE+coin)

**Comment by TheFreeCoin** [comment]
what does "decided" means ? Positive or negative decission to list ? 

Kind Regards,

Ben

**Comment by TheFreeCoin** [comment]
There is now a Technical Analysis available (on Coinlib.io) : https://coinlib.io/coin/FREE/FREE+coin#analysis
