### ISSUE TITLE
Requesting to list Musica (MST)

### ISSUE THREAD

**Issue by Alazar101** [forkdelta/tokenbase#1291]
Musica is a blockchain powered anonymous decentralized platform with personalized token based on Ethereum's smart contract ecosystem for transactions. MST Token is an innovative cryptocurrency powered solution for the music industry that allows anyone to monetize their work in a collaborative P2P marketplace. They can set a price for their works, provide free sample, create audience and seek support from users on the platform.

Website: https://musicatoken.yolasite.com/

Total supply: 100,000,000 MST

Token name: MST

Decimals: 18
Etherscan: https://etherscan.io/token/0x7816dfa7c3774b64363c256fa99d67b51591a838#balances

Contract address : 0x7816dfa7c3774b64363c256fa99d67b51591a838

Discord: https://discord.gg/qGyy8W

**Comment by freeatnet** [comment]
Thank you for your request, @Alazar101! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Large parts of your website and "white paper" are plagiarized.

In particular, the landing page ([archived](http://archive.is/n5CNn)) appears to have text from https://www.moosecoin.io and https://inmusik.co/artist-rewards.

Your "white paper" ([archived](http://archive.is/NyHV0)) is plagiarized from the abstract and the introduction of inmusik.co white paper: https://inmusik.co/wp-content/uploads/2018/05/inmusik-wp-v1.1.pdf.

Plagiarism is strictly forbidden. The token you requested will not be added to ForkDelta tokenbase.

If you believe this decision was made in error, you may appeal it by posting objective facts and supporting materials in comments below.
