### ISSUE TITLE
please take a look of  #833

### ISSUE THREAD

**Issue by jychenotcbtc** [forkdelta/tokenbase#1292]
https://github.com/forkdelta/tokenbase/issues/833

I'm Allen from JOYSO. I haven't seen our token listed on forkdelta.
In #833 , you say just few days. However, it has been few months.

Please take a look!

Thx

**Comment by freeatnet** [comment]
@jychenotcbtc Unfortunately, there's a bit of a backlog. You can see approximate progress on the backlog in the "Information Complete" column here: https://github.com/forkdelta/tokenbase/projects/4. You will receive a notification a couple days before your token is added.

**Comment by JYChen0129** [comment]
@freeatnet 
I know. But you can see what your member @Kryptoniq said in #833 

"Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do."

This msg was on 4/9. Please check that.

Thanks

**Comment by freeatnet** [comment]
@JYChen0129 Doing the best we can. My apologies for the delay.
