### ISSUE TITLE
Add Worldcoin1 (WRD1) by Worldcoin1.com

### ISSUE THREAD

**Issue by WorldCoin1** [forkdelta/tokenbase#1293]
**Token address:** 0xcFAa1833C92A0d6082A804496F4086fB73b74bEE

**Issuer's official website:** http://worldcoin1.com/

**Description:** WORLDCOIN1 (WRD1) is the cryptocurrency for the U-Caring community and public consumption. WRD1 can be used to purchase any product on E500Mall.com and used for other ecommerce store in future. 

**A link to the official contract address confirmation:** http://worldcoin1.com/contact/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. http://worldcoin1.com/team/
2. http://worldcoin1.com/company-activities/
3. http://www.ucaringholding.com/u-caring-timeline/
4. http://www.ucaringholding.com/company-profile/
5. https://www.e500mall.com/

**Comment by freeatnet** [comment]
Thank you for your request, @WorldCoin1! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by WorldCoin1** [comment]
hi, 
here is the chinese media report on the worldcoin1 company - U-Caring Holding Limited and the Founder - Dato Sri Steven Yong.

1. http://hn.ifeng.com/a/20171114/6144330_0.shtml
2. http://www.tclmagazine.com/%E9%A9%AC%E6%9D%A5%E8%A5%BF%E4%BA%9A20%E5%A4%A7%E6%A5%B7%E6%A8%A1%E4%BC%81%E4%B8%9A%E5%AE%B6-%E5%A4%A7%E6%A0%BC%E5%B1%80%E9%93%B8%E5%B0%B1%E8%BF%9C%E5%A4%A7%E6%9C%AA%E6%9D%A5-%E3%80%90%E6%8B%BF/

We hope this help. Hopefully we will get listed on the table asap. Thank you.

**Comment by WorldCoin1** [comment]
another 2 more media reports
3. http://www.newscd.cn/cdnw/201711/50250214.html
4. http://www.sohu.com/a/229018513_100036900

**Comment by WorldCoin1** [comment]
This is the email sent by forkdelta to us. 
![forkdelta2](https://user-images.githubusercontent.com/36604014/42198761-a7b80bf6-7ebc-11e8-994f-d9e7fbe702a1.JPG)

**Comment by freeatnet** [comment]
See initial comment. You are emailing with a scammer.

**Comment by WorldCoin1** [comment]
oops. this is terrible. May i know when will Worldcoin1 get listed on the listing table? Please kindly advice?

**Comment by WorldCoin1** [comment]
hi all, we have created a new contract for worldcoin1 - https://etherscan.io/address/0x512b4e460fc59123e334c9c74344c4e94dc6389d

Can you please kindly assist in changing this to above contract? 
https://forkdelta.github.io/#!/trade/0xcfaa1833c92a0d6082a804496f4086fb73b74bee-ETH

**Comment by WorldCoin1** [comment]
We change the contract because the scammer has stolen some of our WORLDCOIN1, so we have decided to create a new contract for this token. Please kindly approve the changes of WORLDCOIN1 to the new contract. Thank you.

**Comment by WorldCoin1** [comment]
Here is the new link: 
https://forkdelta.github.io/#!/trade/0x512b4e460fc59123e334c9c74344c4e94dc6389d-ETH

**Comment by WorldCoin1** [comment]
hi support. due to the scamming incident. We have create a new blockchain for our token WORLDCOIN1 (WRLD1). Here is our new contract address: 0xb6527cd9e5c0994f5feb19fbbda57d973e3399fa

https://etherscan.io/token/0xb6527cd9e5c0994f5feb19fbbda57d973e3399fa
https://forkdelta.github.io/#!/trade/0xb6527cd9e5c0994f5feb19fbbda57d973e3399fa-ETH

Please do kindly update us on the listing schedule. 
Thank you.

**Comment by WorldCoin1** [comment]
We have change the contract address. Please kindly contact us for details. Thank you.

**Comment by WorldCoin1** [comment]
hi all, here is the new contract address:

https://forkdelta.github.io/#!/trade/0xb6527cd9e5c0994f5feb19fbbda57d973e3399fa-ETH

Please kindly advice how is the revision of this token - Worldcoin1. When can we get it listed on the table. Thank you.
