### ISSUE TITLE
Apply for TRXC Token listing 

### ISSUE THREAD

**Issue by TronClassic-TRXC** [forkdelta/tokenbase#1296]
**Token address:**
0xad5fe5b0b8ec8ff4565204990e4405b2da117d8e

Token Name: TronClassic

Token Symbol: TRXC

Total Supply: 1,000,000,000,000 

**Issuer's official website:**
https://www.tronclassic.xyz/

**Description:** 
TRXC is an ERC20 token that serves as a digital currency. TronClassic  is a platform for the future of trading market and online wallet .

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xad5fe5b0b8ec8ff4565204990e4405b2da117d8e

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. Twitter: https://twitter.com/TronClassic
2. facbook group: https://www.facebook.com/groups/1853017211395204/
3. Bitcointalk: https://bitcointalk.org/index.php?topic=3829331
4. Telegram: https://t.me/ClassicTron
5. whitepaper:  https://www.tronclassic.xyz/whitepaper
6. youtube: https://www.youtube.com/channel/UCOwp1XMHOiLJ-meqNS4h8HQ
7. github: https://github.com/TronClassic-TRXC
8. Reddit: https://www.reddit.com/user/TRONCLASSIC

**Comment by freeatnet** [comment]
You've been warned against spamming the requests. You have spammed your request in #1080, #1288, #1289, and [here](https://github.com/forkdelta/tokenbase/pull/1220#issuecomment-396747094). Do not open any more requests. This is the last warning.

**Comment by TronClassic-TRXC** [comment]
ok
