### ISSUE TITLE
Addition: P4RTY Token

### ISSUE THREAD

**Issue by tonyoncrypto** [forkdelta/tokenbase#1297]
---
addr: '0x34837d9dd34008c0dd8edac6a9a4dcd42fbccc3e'
decimals: 18
description: >-
 P4RTY is an entertainment network that provides skill based games and various infotainment products powered by community participation and the Ethereum blockchain.

Our ultimate goal is to create network effects to drive the overall usability and user experience for Ethereum based dApps. We think gaming and entertainment in general is the best way to push the state of the art and provide value for our players on Ethereum.  
links:
- Blog: https://blog.p4rty.io
- Email: mailto:contact@p4rty.io
- Bitcointalk: https://bitcointalk.org/index.php?topic=4425821
- Twitter: https://twitter.com/p4rtyio
- Website: https://p4rty.io
name: P4RTY
symbol: P4RTY

**Comment by freeatnet** [comment]
Thank you for your request, @! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- **Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md)** and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by glowcoder** [comment]
Hello @Kryptoniq,

Thanks for the feedback.  Here are some recent videos and blogs put out by our community.

https://www.youtube.com/watch?v=2cC_7Y0YuZA (Full Review)
https://www.youtube.com/watch?v=jxXip5Ez6XI (Announcement for P4, our first game)

https://medium.com/@bungalogic/welcome-to-the-p4rty-are-you-ready-to-play-33ac882fb2fa (Full Review)

Thanks,

Tony

**Comment by glowcoder** [comment]
Also trading actively on TokenJar now:

https://tokenjar.io/P4RTY

Real apps, utility, and interest from investors.
