### ISSUE TITLE
Add NeoCash (NEOC)

### ISSUE THREAD

**Issue by neecash** [forkdelta/tokenbase#1299]
**Token address:** 0x91a6f588e5b99077da9c78667ab691564a8fa4dd
https://etherscan.io/address/0x91a6f588e5b99077da9c78667ab691564a8fa4dd

**Name**: NeoCash
**Symbol**: NEOC
**Decimals**: 8
 
Issuer's official **website:** https://neocash.cash
Our aim is to realize the full potential of NeoCcash technology by changing the way people think about money and value, ultimately empowering the individual and engineering the future of finance in the world.

A link to the official contract address confirmation: https://neocash.cash/#SPECIFICATIONS

A link to a third-party review or discussion of the token:
**bitcointalk**: https://bitcointalk.org/index.php?topic=4418531

# Links:
**website**: https://neocash.cash/
**bitcointalk**: https://bitcointalk.org/index.php?topic=4418531
**twitter**: https://twitter.com/NeoCashofficial
**telegram**: https://t.me/NeoCashofficial
**Whitepaper**: https://neocash.cash/downloads/NeoCash-Whitepaper-Rev.pdf.pdf

**Comment by freeatnet** [comment]
Thank you for your request, @neecash! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by neecash** [comment]
Hello,

Please give me any updates about listing.
