### ISSUE TITLE
Listing Request - Ethereum Meta

### ISSUE THREAD

**Issue by ethermeta** [forkdelta/tokenbase#130]
We are the team of the developers and the blockchain enthusiasts, we believe that distributed ledger technology will replace centralized solutions (like Uber, Amazon, Airbnb, etc. in the future). 

Right now, the most of the platforms can be build using smart contracts, but they will inherit the weakest problem of the distributed solutions - speed and scalability (i.e. speed of the blockchain synchronization) these problems will be solved soon with new solutions (lightening network, master nodes, staking etc.) 
Also, we believe 5G network will be an edge-breaking point for the distributed solutions as giving almost no lag synchronizations across the peers.

Ethereum Meta addresses a major weakness in Ethereum: the lack of privacy. Ethereum Meta enables smart contracts where no friend, family, nor foe can see what you bought or for how much. We are working on Smart Contract Mixer. After Ethereum platform implements Zero-Knowledge Snarks, we will add this feature to our system. Moreover, Ethereum Meta token is a foundation of the Anonymous E-Market Place that we are building to be accessible by Tor Browser and provide fully anonymous experience.

Ethereum Meta is ERC20 compatible token, we made that choice for the benefit of our users. We want to provide the easiest experience of adding Ethereum Meta to the wallets.

Ethereum Meta can be easily added to any ERC20 compatible wallets. simply by copying the information below: token address and symbol to the custom token tab. We believe everything has to be easy.

Contract address 0x56b6431f45d08eed55f34371386326c739eacbcc

Symbol ETHM

Decimals 18

Official Website: https://ethermeta.com/  
White Paper: https://ethermeta.com/pdfFiles/WhitePaper.pdf … …

We see your platform as a great opportunity for our project. And we want to bring success to you also.

We want to launch our ICO 8th of February and conduct it on your platform, leading all the potential buyers to your platform.

We are willing to promote your platform in the future as a thank you for your generosity.

Let's start our partnership with mutual trust and please let us know if you are interested to be our partner in our long and exciting journey.

Kindly,
Ethereum Meta Team

--

0x56b6431f45d08eed55f34371386326c739eacbcc
https://ethermeta.com/
Ethereum Meta addresses a major weakness in Ethereum: the lack of privacy. Ethereum Meta enables smart contracts where no friend, family, nor foe can see what you bought or for how much. We are working on Smart Contract Mixer. After Ethereum platform implements Zero-Knowledge Snarks, we will add this feature to our system. Moreover, Ethereum Meta token is a foundation of the Anonymous E-Market Place that we are building to be accessible by Tor Browser and provide fully anonymous experience.
https://ethermeta.com/ (Wallet Section)
https://bitcointalk.org/index.php?topic=2659058.0
Twitter: https://twitter.com/ForkDelta/status/965595930031460352
Facebook: https://www.facebook.com/ethereummeta
YouTube: https://www.youtube.com/watch?v=MoDP_YM_tFo
Reddit: https://www.reddit.com/r/CryptoCurrency/comments/7mj2gf/ethereum_meta_untraceable_transactions/?st=jbqrkf9c&sh=c8fd0713
Github: https://github.com/ethermeta/EtherMeta/blob/master/SmartContract
Telegram: https://t.me/ethereummeta
Decimals: 18
Ticker: ETHM

**Comment by JonathonDunford** [comment]
verified: 0x56b6431f45d08eed55f34371386326c739eacbcc

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
