### ISSUE TITLE
Listing request - VUZZBEE Token 

### ISSUE THREAD

**Issue by vuzzbee** [forkdelta/tokenbase#1300]
Contract address:
0x59a563d147b3cd059dc6acb570b506df9f04eb82

Issuer's official website:
https://vuzzbee.com/

Official contract address confirmation:
https://twitter.com/VuzzBee/status/962611244703330304

A link to a third-party review or discussion of the token:
https://cryptocurrencytalk.com/topic/98255-annreferral-program-pre-sale-live-vuzzbee-worlds-first-blockchain-link-sharing-reward-system/

Description:
VuzzBee is a decentralized link-sharing website which allows users to view and share a variety of content such as articles, images, videos and links -- and earn rewards! Whether you are a content creator or a content consumer, you will be rewarded for interacting with the website. Think of VuzzBee as “Reddit” but with a reward system that goes beyond just points.
In using VuzzBee, creators benefit by being rewarded for their own content and at the same time enabling them to give their supporters and fans the chance to earn.

Links

Web: https://vuzzbee.com/

Twitter: https://twitter.com/vuzzbee

Telegram: https://t.me/vuzzbee

Reddit: https://reddit.com/r/vuzzbee

Mail: info@vuzzbee.com

**Comment by freeatnet** [comment]
Thank you for your request, @vuzzbee! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
See previous discussion in #544.

**Comment by freeatnet** [comment]
@vuzzbee Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases or sponsored articles do not constitute third-party review.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by vuzzbee** [comment]
here are more source of reviews kindly consider us now
https://bitcoinexchangeguide.com/vuzzbee-ico/
https://icoholder.com/en/vuzzbee-20361
