### ISSUE TITLE
Add Jbox (JBX)

### ISSUE THREAD

**Issue by tonytone7** [forkdelta/tokenbase#1301]

**Comment by tonytone7** [comment]
Thanks forkdelta

**Comment by jboxproject** [comment]
....................................................................................
Contract Address: 0x884e3902c4d5cfa86de4ace7a96aa91ebc25c0ff
https://etherscan.io/token/0x884e3902c4d5cfa86de4ace7a96aa91ebc25c0ff

Website: https://jboxcoin.org/ https://jboxcoin.info/

Token Holders as of 06/14/2018: 4909 addresses https://ethplorer.io/address/0x884e3902c4d5cfa86de4ace7a96aa91ebc25c0ff#tab=tab-holders

Verification of the official contract address: can be found at the bottom of our webpage jboxcoin.org

Description: JBOX is a decentralized blockchain video streaming platform designed to provide customers with a huge sense of value for their leisure time via a well-augmented dual mining process (Proof of   Upload and Proof of
View). This program is designed to benefit token user for downloading and streaming videos of all varieties on the JBOX platforms.

Other Links:

Bitcointalk: https://bitcointalk.org/index.php?topic=2330794.0
Blog: https://medium.com/jboxcoin
Facebook: https://www.facebook.com/jboxcommunity 3 670 members
Telegram: https://t.me/jboxcoin 52 503 members
Twitter: https://twitter.com/jbox_coin 10 103 members
YouTube:https://www.youtube.com/results?search_query=jboxcoin
https://github.com/JBXCOIN/JBOXCOIN
Whitepaper: https://drive.google.com/file/d/0BxC2u6uHtVw_YXZ0Z3RrRnlQZ00/view
Token name: JBOX
Token symbol: JBX
Token decimal: 18

Third Party Verification
ICO reviews press release:

https://icobench.com/ico/jboxcoin
https://icomarks.com/ico/jboxcoin
https://icolistrating.com/l/jboxcoin
https://coincodex.com/crypto/jboxcoin/
https://icowatchlist.com/ico/jboxcoin
https://www.coingecko.com/en/ico/jboxcoin
https://www.coingecko.com/en/coins/jbox
https://bitcoinexchangeguide.com/jbox-coin/
https://news.bitcoin.com/pr-jboxcoin-a-blockchain-based-decentrlized-video-streaming-platform/
https://cryptosrus.com/jboxcoin-video-streaming-platform/
http://blocktribune.com/jbox-uses-blockchain-challenge-youtube-domination/
Channels of communication are defined in the "Other Links" section above.

Optional Questions
I am the CEO of jboxcoin universal limited and as such represent the jbox (JBX) token issuer.
The token was issued via private sale and crowdsale and will continue to be distributed via airdrop and bounty.

**Comment by freeatnet** [comment]
Thank you for your request, @tonytone7 ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- **Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md)** and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by jboxproject** [comment]
please, we love to know what the missing information is. so we can fix it immediately

**Comment by jboxproject** [comment]
Contract Address: 0x884e3902c4d5cfa86de4ace7a96aa91ebc25c0ff
https://etherscan.io/token/0x884e3902c4d5cfa86de4ace7a96aa91ebc25c0ff

Website: https://jboxcoin.org/ https://jboxcoin.info/


Verification of the official contract address: can be found at the bottom of our webpage jboxcoin.org

Description: JBOX is a decentralized blockchain video streaming platform designed to provide customers with a huge sense of value for their leisure time via a well-augmented dual mining process (Proof of Upload and Proof of
View). This program is designed to benefit token user for downloading and streaming videos of all varieties on the JBOX platforms.

Other Links:

Bitcointalk: https://bitcointalk.org/index.php?topic=2330794.0
Blog: https://medium.com/jboxcoin
Facebook: https://www.facebook.com/jboxcommunity 3 670 members
Telegram: https://t.me/jboxcoin 52 503 members
Twitter: https://twitter.com/jbox_coin 10 103 members
YouTube:https://www.youtube.com/results?search_query=jboxcoin
https://github.com/JBXCOIN/JBOXCOIN
https://coincodex.com/crypto/jboxcoin/
https://www.coingecko.com/en/coins/jbox
Whitepaper: https://drive.google.com/file/d/0BxC2u6uHtVw_YXZ0Z3RrRnlQZ00/view
Token name: JBOX
Token symbol: JBX
Token decimal: 18

Third Party Verification
 reviews:

(https://steemit.com/dtube/@bania/jbox-a-strong-potential-competitor-to-our-own-dtube-my-honest-review)
http://blocktribune.com/jbox-uses-blockchain-challenge-youtube-domination/
Channels of communication are defined in the "Other Links" section above.

**Comment by freeatnet** [comment]
@jboxproject please look at the format and follow it (you can copy and paste the contents of the file into a comment and fill out the details): https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by jjamani12** [comment]
Contract Address: 0x884e3902c4d5cfa86de4ace7a96aa91ebc25c0ff
https://etherscan.io/token/0x884e3902c4d5cfa86de4ace7a96aa91ebc25c0ff

Website: https://jboxcoin.org/ https://jboxcoin.info/

Verification of the official contract address: can be found at the bottom of our webpage jboxcoin.org

Description: JBOX is a decentralized blockchain video streaming platform designed to provide customers with a huge sense of value for their leisure time via a well-augmented dual mining process (Proof of Upload and Proof of View). This program is designed to benefit token user for downloading and streaming videos of all varieties on the JBOX platforms.

Other Links:

Bitcointalk: https://bitcointalk.org/index.php?topic=2330794.0
Blog: https://medium.com/jboxcoin
Facebook: https://www.facebook.com/jboxcommunity 3 670 members
Telegram: https://t.me/jboxcoin 52 503 members
Twitter: https://twitter.com/jbox_coin 10 103 members
YouTube:https://www.youtube.com/results?search_query=jboxcoin
https://github.com/JBXCOIN/JBOXCOIN
https://coincodex.com/crypto/jboxcoin/
https://www.coingecko.com/en/coins/jbox
Whitepaper: https://drive.google.com/file/d/0BxC2u6uHtVw_YXZ0Z3RrRnlQZ00/view
Token name: JBOX
Token symbol: JBX
Token decimal: 18

Third Party Verification
https://steemit.com/dtube/@bania/jbox-a-strong-potential-competitor-to-our-own-dtube-my-honest-review
http://blocktribune.com/jbox-uses-blockchain-challenge-youtube-domination/

ICO reviews:

https://icowatchlist.com/ico/jboxcoin
https://icomarks.com/ico/jboxcoin
hhttps://icobench.com/ico/jboxcoin
https://www.coingecko.com/en/coins/jbox/
Channels of communication are defined in the "Other Links" section above.

Optional Questions
My name is JULIUS JAMANI I'm the CEO of JBOX and as such represent the token issuer.
The token was issued via private and public sale and will continue to be distributed via airdrop.
