### ISSUE TITLE
Add VV Coin (VVI)

### ISSUE THREAD

**Issue by neroro-29** [forkdelta/tokenbase#1302]
Token Name: VVCoin
Token Symbol: VVI

Token address:
0x1f4215Fe007eE5B170391241656A28A8bd13826E

Issuer's official website:
https://www.vvcoin.io

Description: 
VVI is an utility token made to revolutionise tourism industry. With the help of blockchain technology & Artificial Intelligence technology, users will be able to utilise VVI to make payment booking hotel rooms, flight tickets and hire transport using VV Genie mobile app. VV Genie also consists of real-time A.I translator to help travelers remove the language barriers while traveling. VV Wallet is an erc-20 compatible wallet to store VVI and is currenly available through AppStore & PlayStore.

A link to the official contract address confirmation: 
https://www.vvcoin.io
https://etherscan.io/token/0x1f4215fe007ee5b170391241656a28a8bd13826e

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://bitcointalk.org/index.php?topic=2718634.0
https://www.cryptocompare.com/coins/vvi/overview
https://www.coingecko.com/zh/数字货币/vv-coin
https://chasing-coins.com/coin/VVI
https://awebanalysis.com/en/coin-details/vv-coin-vvi/
https://coinlib.io/coin/VVI/VV+Coin
https://coinranking.com/coin/vv-coin-vvi
https://www.reliablecoin.com/coin/vv-coin-vvi/
https://marketcoinprice.com/coin/VVI
https://www.criptomonitor.ro/coin/vvi
https://altcoinindex.com/coin/vvi
Telegram: https://t.me/VVcoin
Facebook Page: https://www.facebook.com/vvcoin/
Reddit : https://www.reddit.com/user/VVcoin/
Twitter: https://twitter.com/VVcoin
HD Teaser: http://vvcoin.io/vv-eng.mp4

**Comment by nero-san** [comment]
Thank you for the swift reply, @freeatnet! Looking forward to your update.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by neroro-29** [comment]
@freeatnet Thank for the reminder. The format has been updated as per your request. Thank you.

**Comment by nero-san** [comment]
@freeatnet hi, may I know a rough estimation on when will VVI be listed on forkdelta? You reply is greatly appreciated.

**Comment by nero-san** [comment]
@freeatnet hi, is there any updates on vvi listing? Appreciated.

**Comment by neroro-29** [comment]
Hi, is there any update on the coin listing on forkdelta?
