### ISSUE TITLE
Add DACPLAY Token (PLS)

### ISSUE THREAD

**Issue by janeisthebest15** [forkdelta/tokenbase#1303]
**Token address:**
0xe43ac1714f7394173b15e7cff31a63d523ce4fb9

**Issuer's official website:**
https://dacplay.org

**Description:** 

BitShares PLAY is an experiment to demonstrate and validate how a decentralized, autonomous game asset platform might be implemented. 
Shares of PLAY(PLS) are combined with all of the assets of both built­in and third party games form a free marketplace and exchange. Systems like this are also known as Decentralized Autonomous Companies (DAC).
PLAY shares (PLS) are the tokens of the system. PLS are designed first to be the shares of the PLAY System, and thus the unit in which dividends are paid to PLS holders and delegates of PLAY are paid for their contributions to the system. Secondly, PLS are the token with which users purchase game assets to play games. PLS provides an opportunity to expand the model of token distribution, and may explore models in which a game rewards winners with the tokens of the game system itself.

**A link to the official contract address confirmation:** 

https://dacplay.org/posts

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitsharestalk.org/index.php?topic=11406.0
2.https://bitsharestalk.org/index.php?board=52.0

**Comment by freeatnet** [comment]
Thank you for your request, @janeisthebest15! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by janeisthebest15** [comment]
Thank u.
