### ISSUE TITLE
Add ESTS (ESTS)

### ISSUE THREAD

**Issue by Dianeellulschranz** [forkdelta/tokenbase#1305]
**Token address:**

0x054Ad3Cd4A66F14bF5C0De2548A53BE66995A4f6

**Issuer's official website:**
www.ests.io

**Description:** 
ESTS is not your usual risky and uncertain start-up project. ESTS stands for E&S Tokenised Services and ties in with an established Legal, Corporate and Business Advisory organisation, with over 10 years’ experience, 30+ employees and a steady annual revenue stream of close to $5 Million.
The idea of ESTS was born as a ‘Proof of Work’ concept. What better way to prove to clients and the community that we can launch Initial Coin Offerings (ICO) and Token related services in ways never done before? Unlike most other industries that have developed over several years, this industry is developing at an incredibly fast pace. This is mainly because the industry was able to self-finance with the introduction of ICOs. To keep up with this ever-changing environment and remain at the forefront, as part of the ESTS Initiative, we have decided to launch our own Tokens, ESTS. Funds raised in our Private Placement will be utilised to expand our team, finance strategic acquisitions, and promote Blockchain and the crypto Economy in General.

**A link to the official contract address confirmation:** 
www.ests.io

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.timesofmalta.com/articles/view/20180317/local/maltese-firm-ventures-into-blockchain.673583
2. https://www.timesofmalta.com/articles/view/20180325/business-news/world-first-for-maltese-blockchain-firm.674439

**Comment by freeatnet** [comment]
Thank you for your request, @Dianeellulschranz! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
