### ISSUE TITLE
Listing Request: Fatcoin(FAT)

### ISSUE THREAD

**Issue by sadnessone** [forkdelta/tokenbase#1306]
1. The contract address:
**0x2eC95B8edA549B79a1248335A39d299d00Ed314C**

2. Issuer's official website:
 https://www.fatbtc.com/

3. Description:
Fatcoin is the exchange coin of FatBTC. lt can be used for consumption throughout the FatBTC ecosystem. And the total amount of FAT is 200 million, never more.

4. Name: Fatcoin

5. Symbol: FAT

6. Official contract address confirmation: 
https://fatbtc.com/news-detail-131.htm

7. A link to a third-party review or discussion of the token: 
https://www.jinse.com/news/blockchain/129448.html
https://www.aliyun.com/zixun/content/37_81_2038749.html
(Reviews are all in Chinese unfortunately, please use the translator.)

**Comment by freeatnet** [comment]
Thank you for your request, @sadnessone! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
