### ISSUE TITLE
LocalCoinSwap token listing

### ISSUE THREAD

**Issue by OptimusOpus** [forkdelta/tokenbase#1307]
**Token address:**
0xaa19961b6b858d9f18a115f25aa1d98abc1fdba8

**Issuer's official website:**
https://www.localcoinswap.com/

**Description:** 

LocalCoinSwap is building a P2P cryptocurrency exchange and launching an associated Cryptoshare ICO.

LocalCoinSwap features a completely decentralized peer-to-peer trading structure. There are no centralized bank accounts, no verification requirements, and no restrictions on trade.

Furthermore LocalCoinSwap distributes 100% of the sites profits to holders of Cryptoshares on a 1-to-1 basis, through a blockchain-based decentralized dividend application.

**A link to the official contract address confirmation:** 
https://www.localcoinswap.com/    (in the left of the site footer)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcoinexchangeguide.com/localcoinswap-lcs-ico/
2. https://www.newsbtc.com/press-releases/decentralization-is-the-future-for-crypto-exchanges-states-cto-of-localcoinswap/

**Comment by freeatnet** [comment]
Thank you for your request, @OptimusOpus! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
