### ISSUE TITLE
Listing new token (Jet7)

### ISSUE THREAD

**Issue by Jet7Coin** [forkdelta/tokenbase#1308]
**Token address:**

https://etherscan.io/token/0x52aaf0e5479e6cee87729a88c17aa4a83f25d9dc

**Issuer's official website:** 

http://jet7.org

**Description:** 

Jet7 - Luxury is Priceless.
Money, Fashion, Appearance, Extravagance
More than a social milieu, it refers rather to a way of living one's life as a show where the notions of taboo and bad taste are all relative.

**A link to the official contract address confirmation:**  

http://jet7.org/address

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=4311078
2. https://discord.gg/SRUvcRH

**Comment by freeatnet** [comment]
Thank you for your request, @Jet7Coin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases or sponsored articles do not constitute third-party review.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
