### ISSUE TITLE
Listing of Bunzola Token - BUNZ

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1309]
**Token address:** 0x3a2f46b0b0c187b152db0c658b27e693f0a273a1

**Issuer's official website:** https://www.bunzola.com

**Description:**  Bunzola is the first  Proof-of-Stake Cryptocurrency dedicated to helping people become free from hunger.

**A link to the official contract address confirmation:**  https://www.bunzola.com/#token

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcoinexchangeguide.com/bunzola-ico-bunz-token/
2. https://foundico.com/ico/bunzola.html
3. https://bitcointalk.org/index.php?topic=3595870

**Comment by freeatnet** [comment]
Thank you for your request, @Bunzola! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Bunzola** [comment]
Thanks, we'll await your update and if you need any info please let us know

**Comment by freeatnet** [comment]
Project shut down.
