### ISSUE TITLE
Add a New Token: MVL Chain (MVL)

### ISSUE THREAD

**Issue by Black-Rock** [forkdelta/tokenbase#1312]
**Request addition of a new token to tokenbase**

**The contract address:**
0xa849eaae994fb86afa73382e9bd88c2b6b18dc71

**Issuer's official website:**
https://mvlchain.io/

**Description:**
MVL Chain is a vehicle data collecting ecosystem based on blockchain technology. It is a blockchain-based ecosystem that connects all services, like the car dealer shops, mechanic shops and car rental companies, that touch your car to collect its lifetime data.

**Name:** MVL Chain

**Symbol:** MVL

**Official contract address confirmation:**
https://blog.mvlchain.io/2018/06/03/how-to-add-mvl-custom-token-in-metamask/
https://t.me/mvlchain_news_en

**A link to a third-party review or discussion of the token:**
https://icodrops.com/mvl-chain/
https://bitcointalk.org/index.php?topic=3277738.0

**Well-defined channels of communication with the token issuer:**
https://t.me/mvlchain_en
https://twitter.com/mvlchain

**Comment by freeatnet** [comment]
Thank you for your request, @Black-Rock! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
