### ISSUE TITLE
Please add SuccessLife (SXL)

### ISSUE THREAD

**Issue by BFSLife** [forkdelta/tokenbase#1316]
**Token address: 0x222eFe83d8cC48e422419d65Cf82D410A276499B

**Issuer's official website: https://successlife.com

**Description: SuccessLife Tokens (SXL) are a payment mechanism developed for the educational, personal and professional development industries. SuccessLife Tokens have been conceptualised by the Success Resources group of companies that has over the past 25 years, organized and promoted hundreds of seminars and workshops annually across 30 countries and over it’s lifetime has had over 10 million attendees. SXL will launch with an active international customer base in excess of 6 million persons who have a common interest and pre-existing relationship with an established and respected brand. We aim for SXL to empower seamless payments for the learning sector and this is driven by the SuccessLife Ecosystem.

**A link to the official contract address confirmation:** https://github.com/successlifegl/SuccessLifeToken

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icobench.com/ico/successlife/ratings
2. https://bitcoinexchangeguide.com/successlife-ico-slt-token/
3. https://icoguide.com/en/ico/successlife
4. https://icoholder.com/en/successlife-17860
5. https://queenwiki.com/blog/2018/01/successlife-tokensale-ico-robert-kiyosaki-tony-robbins-10million-customers/

Additional note: We have 2453 token holders and between them they have 36mil tokens. I believe we would be a valuable token to be listed.

**Comment by freeatnet** [comment]
Thank you for your request, @BFSLife! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
