### ISSUE TITLE
Add EtherByte (EBX)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1317]
Contract address: 0xba4725e435a287e28783886fcbcb339436a6ae66

Issuer's official website: https://www.etherbyte.center/

Description: Etherbyte will become the leading form of peer to peer payments in everyday life.

Name: EtherByte

Symbol: EBX

Official contract address confirmation:
1. https://www.etherbyte.center/etherbyte-1
2. https://medium.com/@ebxtoken/ann-etherbyte-the-future-of-rapid-low-cost-worldwide-payments-6fb05a7dd396

A link to a third-party review or discussion of the token:
1. https://bitcointalk.org/index.php?topic=2779774.msg28433866#msg28433866
2. https://medium.com/@iresignn/etherbyte-future-of-crypto-payments-airdropped-token-review-erc20-will-they-be-able-to-pull-ff716140dafc

Well-defined channels of communication with the token issuer:
Telegram: https://t.me/Etherbyte
Twitter: https://www.twitter.com/EtherByte

**Comment by freeatnet** [comment]
Thank you for your request, @EBXToken! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Note for review: previous requests here: https://github.com/forkdelta/tokenbase/search?q=0xba4725e435a287e28783886fcbcb339436a6ae66&type=Issues

**Comment by EBXToken** [comment]
@freeatnet
