### ISSUE TITLE
Please list ROPCOIN

### ISSUE THREAD

**Issue by sigonera** [forkdelta/tokenbase#1318]
**Token address:**
0xD2d95e0d8CEb1670D37878CEE784184b991d8509

**Issuer's official website:**
https://ropcoin-rpcn.com

**Description:** 

Our aim is to realize the full potential of Ropcoin technology by changing the way people think about money and value, ultimately empowering the individual and engineering the future of finance in the world.
**A link to the official contract address confirmation:** 

https://ropcoin-rpcn.com/token-information
**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=4485501.new#new
2. Not yet available

**Comment by freeatnet** [comment]
Thank you for your request, @sigonera! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by sigonera** [comment]
Thanks am waiting

**Comment by sigonera** [comment]
Please how long will it take to move this to preview other issues after this has moved to needs preview since 3 days pls look at this issue
