### ISSUE TITLE
Add ManitoSuper Token (ManitoS) 

### ISSUE THREAD

**Issue by ManitosuperToken** [forkdelta/tokenbase#1323]
Contract address:0xFaFaE755cBaF09Cff8f5B0a0f1E0A4A719a9C32a

Issuer's official website: http://manito.io/

Description: ManitoStoken is both a symbol of your identity and is your personal value highlights.

Name: ManitoSuperToken

Symbol: ManitoS

Official contract address confirmation:

http://manito.io/gettoken.html
A link to a third-party review or discussion of the token:

https://medium.com/@manitotoken_53719/what-is-the-manitostoken-5b4a9e689bda
Well-defined channels of communication with the token issuer:
Twitter: https://twitter.com/search?q=%40BitPopulous&src=typd
Facebook:https://www.facebook.com/ManitoSuperToken

**Comment by freeatnet** [comment]
Thank you for your request, @ManitosuperToken ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by ManitoSuper** [comment]
thanks

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
