### ISSUE TITLE
Bitball (BTB) Token Review for Listing 

### ISSUE THREAD

**Issue by BitballErc20** [forkdelta/tokenbase#1325]
Hi again, we checked the website again and fix the issues, please check it again and get back to us. I will put in another request after our first airdrop is finished and Bitball is in circulation. We are on one of the new exchanges, but would like to get on as many as we can. 
We are very happy to Announce that Bitball (BTB) is now listed on one of the best Exchange: ENCLAVES DEX .
Enclaves.io/trade/BTB
Contact address is:  0x382117315856a533549eA621542Ccce13E54aE82

Bitball (BTB) - A Social Media Based Decentralized Crypto Currency.

Website: https://bitball.site123.me 
Telegram: https://t.me/Bitball & https://t.me/BitballGroupChat
Twitter: https://twitter.com/BitBall_Erc20
Facebook: https://www.facebook.com/profile.php?id=100026538557513
GitHub: https://github.com/BitballErc20
Email us: Bitball@mail.com
ICO Listing Websites: https://www.initialcoinlist.com/ico/bitball/
BitcoinAnn: https://bitcointalk.org/index.php?topic=4421576.msg39423209#msg39423209
Bitcoin.com Forum: https://forum.bitcoin.com/alternative-cryptocurrencies-altcoins/bitball-btb-a-social-media-based-decentralized-crypto-currency-t89242.html
Thank you
Regards

**Comment by freeatnet** [comment]
Thank you for your request, @BitballErc20! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by BitballErc20** [comment]
We are very happy to Announce that Bitball (BTB) is now listed on one of the best upcoming Exchange: ENCLAVES DEX .

#Bitball #Btb #erc20 #Exchange #airdrop #free #trade #enclaves #enclavesdex #Bounty #SocialMedia #people #power #crypto #currency #BEST

Enclaves.io/trade/BTB

**Comment by Kryptoniq** [comment]
#1232
