### ISSUE TITLE
A listing request of Sharder

### ISSUE THREAD

**Issue by marsranger001** [forkdelta/tokenbase#1326]
**Token address:**
0xbbff862d906e348e9946bfb2132ecb157da3d4b4

**Issuer's official website:**
sharder.org

**Description:** 
Sharder (Hereinafter referred as SS) is the cryptocurrency embeded in Sharder Protocol.  As the incentives in Sharder ecosystem, SS is utilized to reward the nodes that contributes to the Sharder network and descourage the malicious nodes, and avoid the logic bomb. Additionally, SS also works as the anchoring token in the Sharder multiple-chain (or multiple-pool) architeture.   

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xbbff862d906e348e9946bfb2132ecb157da3d4b4

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://medium.com/@cryptowriteups/sharder-protocol-the-airbnb-of-blockchain-storage-8754120d6406
2.https://medium.com/@ryandonz/cryptocurrency-the-secret-to-profiting-from-the-most-volatile-market-in-the-world-via-asymmetric-3fd50e56405

**Comment by freeatnet** [comment]
Thank you for your request, @marsranger001! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
