### ISSUE TITLE
BrokerNeko NETWORK 

### ISSUE THREAD

**Issue by BrokerNekoNETWORK** [forkdelta/tokenbase#1330]
TOKEN ADRESS:  **0xDA80B20038BDF968C7307BB5907A469482CF6251**

Issuer's official website:  https://www.brokerneko.com/

Description: **We deployed BrokerNeko Network tokens for funding our project. We aiming to create a fast, reliable and cheaper way to transactions with crypto currencies.** 

A link to the official contract address confirmation:  https://www.brokerneko.com/   You can easily down when you scroll down to Home page. There is a ForkDelta logo and notice about it. Just click to forkdelta logo 

At Least two, Third Party Links
-->
1.  https://www.youtube.com/watch?v=htolP4zSTN8&t
2. https://bitcointalk.org/index.php?topic=4481864

**Comment by freeatnet** [comment]
Thank you for your request, @BrokerNekoNETWORK! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
