### ISSUE TITLE
Listing of TOKPIE (TKP) token

### ISSUE THREAD

**Issue by Zepelins** [forkdelta/tokenbase#1332]
The contract address:
https://etherscan.io/token/0xd31695a1d35e489252ce57b129fd4b1b05e6acac

A link to the token issuer's official website:
https://tokpie.io/

Official contract address confirmation:
https://github.com/Tokpie/tokpie-contract
https://ethplorer.io/address/0xd31695a1d35e489252ce57b129fd4b1b05e6acac

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3253647.msg40083343#msg40083343
https://bitcointalk.org/index.php?topic=3189988.msg33086920#msg33086920
https://bitcointalk.org/index.php?topic=3253647.msg33957012#msg33957012

Description: The aim of the project to make crypto assets available everywhere to everyone! 
TKP will be used for paying fees, add-ons, access to additional features and proof of membership.
TOKPIE is a unique peer-to-peer exchange where anyone, anywhere can buy and sell crypto assets for fiat money or cryptocurrency, safely and efficiently, through real-time auctions offering the best prices, using any payment method.

Please add ticket TKP to https://forkdelta.github.io/#!/trade/0xd31695a1d35e489252ce57b129fd4b1b05e6acac-ETH

**Comment by freeatnet** [comment]
Thank you for your request, @Zepelins ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Andrey4Dev** [comment]
Hey, admins! Why you have not listed TKP yet? 
Here are some recent news about Tokpie:

1) Tokpie platform is life and successfully working:  https://medium.com/@TokPie/tokpie-exchange-is-live-4e63c28fd092


2) Tokpie had contracted the world-known $ 57.5M-revenue IT company: https://medium.com/@kamagames/tokpie-appointed-by-kamagames-to-boost-the-kgt-bounty-campaign-800d051c6a95

3) Moreover, Tokpie launched a unique and highly demanded service: BOUNTY STAKES TRADING. Check the hottest discussion on bitcointalk: https://bitcointalk.org/index.php?topic=5039136.msg46233134#msg46233134

Pls list it as soon as possible.

**Comment by Vasilii79** [comment]
Hi admins!
I want to add additional links to the positive hype around TKP and its TOKPIE platform.

TOKPIE platform reviews and feedbacks from its growing community:
- ANN translated to many languages: https://bitcointalk.org/index.php?topic=5050817.0 
- Additional thread: https://bitcointalk.org/index.php?topic=5073932.0 

TKP token use cases: https://tokpie.io/fees

Pls, list TKP token as soon as possible. It has strong utility value.
Thanks!

**Comment by rartokens** [comment]
I could see that this still on the review list for the admin:
https://github.com/forkdelta/tokenbase/projects/4#card-10803345

You may contact freeatnet and to know the status.
Or post to https://www.reddit.com/r/ForkDelta/ and see any response

**Comment by Vasilii79** [comment]
> I could see that this still on the review list for the admin:
> https://github.com/forkdelta/tokenbase/projects/4#card-10803345
> 
> You may contact freeatnet and to know the status.
> Or post to https://www.reddit.com/r/ForkDelta/ and see any response

Have done that (hope that admins will not delete it) https://www.reddit.com/r/ForkDelta/comments/als6r9/a_working_platform_waits_for_token_listing_since/

Many thanks for your advice!

**Comment by Vasilii79** [comment]
TOKPIE exchange and its TKP token are now listed on Coinpaprika: 
TOKPIE exchange: https://coinpaprika.com/exchanges/tokpie/ 
TKP token: https://coinpaprika.com/coin/tkp-tokpie/

Would be great to see TKP listed on Forkdelta as well!

**Comment by Vasilii79** [comment]
Additional progress: TKP (TOKPIE) token is now listed on Token.Store: https://token.store/eth/trade/TKP

Still waiting for listing on Forkdelta (almost one year waiting!)

**Comment by Vasilii79** [comment]
One more listing! TOKPIE (TKP) token was listed on Coinlim exchange: https://www.coinlim.com/#/noticedetail/178

Tokpie is the first exchange in the world with Bounty Stakes Trading service.

The usage of TOKPIE (TKP) token allows:
* getting up to 500% trading fees discount
* decreasing withdrawal commissions by almost two times
* receiving up to 70% referral bonus and other premium tips
* purchasing IEO tokens in Tokpie Launchpad
* using TKP token as collateral for getting access to the Bounty Stakes Trading 2.0

ForkDelta admins where are you? Please list TKP.

**Comment by Vasilii79** [comment]
TKP token is now added on CoinGecko https://www.coingecko.com/en/coins/tokpie/ and it's price and market cap is visible on Etherscan: https://etherscan.io/token/0xd31695a1d35e489252ce57b129fd4b1b05e6acac

ForkDelta admins where are you? Please list TKP

**Comment by Vasilii79** [comment]
Tokpie exchange is listed on Coingecko: https://www.coingecko.com/en/exchanges/tokpie

ForkDelta admins where are you? Please list TKP

**Comment by Vasilii79** [comment]
Dear Forkdelta devs,

Tokpie team has made even more great progress for the recent months!

Here are TOKPIE (**TKP**) token new achievements:

- [ ] listed on CoinMarkerCap: https://coinmarketcap.com/currencies/tokpie/
- [ ] listed on third CMC exchange - VinDax: https://vindax.com/exchange-base.html?symbol=TKP_ETH
- [ ] listed on Blockfolio: https://tokpie.io/blog/tokpie-tkp-is-available-on-blockfolio/
- [ ] got Blue Checkmark on Etherscan: https://tokpie.io/blog/tag/blue-checkmark/

- [ ] got organic mentions about Tokpie on media: [hackernoon](https://hackernoon.com/top-7-services-for-earning-cryptocurrencies-a3ebd788abe4), [newsbtc](https://www.newsbtc.com/2019/06/26/ethereum-need-developers-now-than-never-eth-surging-up-32-1/), [nodesofvalue](https://nodesofvalue.com/tokpie/), [publish0x](https://www.publish0x.com/for-the-future/bounty-hunting-great-way-get-engaged-project-xwveog), and others. 


Kindly list TKP token on Forkdeelta. 

Thanks in advance!

**Comment by Vasilii79** [comment]
Hi Forkdelta devs,
Hope you are ok!

TOKPIE (TKP) is constantly making progress. 
New organic mention is here: https://nulltx.com/giants-like-kfc-are-looking-to-improve-advertising-transparency-with-blockchain-technology/
