### ISSUE TITLE
Request to add Latino Token in forkdelta

### ISSUE THREAD

**Issue by jabaco** [forkdelta/tokenbase#1333]
**Token address:**
https://etherscan.io/token/0x567287d4f42086beab4b36de9af21c70adec6760

**Issuer's official website:**
https://latinotoken.com/

**Description:** 
Latino Token is building a crypto-community in Latin America in which we are aiming to build a marketplace of goods and services and the token will be used as a payment form

**A link to the official contract address confirmation:** 
https://etherscan.io/address/0x567287d4f42086beab4b36de9af21c70adec6760

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

Information: Since Latino Token is a project for the spanish community, we do not have reviews in english speaking websites
1. https://criptotendencia.com/2017/11/12/latino-token-la-primera-criptomoneda-de-latinoamerica-lanza-su-preventa/
2. https://informacionbitcoin.com/que-es-pre-ico-de-latino-token/

**Comment by freeatnet** [comment]
Thank you for your request, @jabaco! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
