### ISSUE TITLE
RedBUX

### ISSUE THREAD

**Issue by Admin-redBUX** [forkdelta/tokenbase#1334]
**Token address:**
0x868c3ee9b6086458482422b6b37fa36649cd55bf

**Issuer's official website:**
https://www.red-bux.com/

**Description:** 
redBUX is designed as a ERC20 utility token and will be used as a guaranteed means of payment in the ecosystem of vrXcity. The vrXcity will be a photo-realistic ecosystem where the user can fully interact with 3D-versions of his favourite stars or/and other users and create own content to fulfil all possible fantasies.

**A link to the official contract address confirmation:** 
The Website is currently restructured after the ICO but the new one will feature the token address.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.wallstreet-online.de/nachricht/10299588-redbux-ico-jahres-deutschland
2.https://www.shareribs.com/technology/it-und-kommunikation/analyse/article/redbux_ico_vorverkauf_nach_wenigen_tagen_mehr_als_50_prozent_verkauft_id108101.html

**Comment by freeatnet** [comment]
Thank you for your request, @t-redbux! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
