### ISSUE TITLE
VITE Listing Request

### ISSUE THREAD

**Issue by zebracrossingblog** [forkdelta/tokenbase#1335]
Please add VITE.

https://www.vite.org/

0x1b793E49237758dBD8b752AFC9Eb4b329d5Da016

https://bitcointalk.org/index.php?topic=4438416

VITE is  Next Generation High-performance Decentralized Application Platform.
Vite is using Block Lattice DAG same as Nano but there are some security flaws in Block Lattice DAG. They'll be making a snapshot chain to remedy the security issues with Nano DAG. And you can make smart contracts on VITE with Solidity++ language (which is compatible to Solidity). There is not much difference in Solidity and Solidity++ that's why Ethereum apps are compatible with VITE. Vite's competitior is Fantom (DAG + Smart contract platform). But Fantom is using Scala language for smart contracts so Ethereum Dapps are not compatible with Fantom.

VITE Total supply 1,000,000,000 VITE vs FANTOM Total supply 3,175,000,000 FTM
VITE Hardcap $28.5m vs FANTOM $39.9m
VITE smart contract language Solidity++ vs FANTOM smart contract language SCALA
VITE investor BITMAIN vs FANTOM investor Blockwater Capital.

REVIEWS:
https://steemit.com/vite/@bitcoinstartrek/vite-ico-review
https://icodrops.com/vite/
https://icogens.com/vite-what-is-vite-will-it-be-the-next-generation-of-high-performance-decentralized-application-platform?lang=en

**Comment by freeatnet** [comment]
Thank you for your request, @zebracrossingblog ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by zebracrossingblog** [comment]
IDEX just listed VITE, also BILAXY.
https://idex.market/eth/vite

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
