### ISSUE TITLE
GMET

### ISSUE THREAD

**Issue by cchienm** [forkdelta/tokenbase#1338]
**Token address:**
0xC605a03a9a36717d8CFB9964Af0973DD1eda15fA

**Issuer's official website:**
gmefx.com

**Description:** 
The purpose of token is to determine the share of campany

**A link to the official contract address confirmation:** 
gmefx.com, it is on the How to buy our token section

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. It is a new erc20 token, please advice me what should i do
2.

**Comment by freeatnet** [comment]
Thank you for your request, @cchienm! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Literally every phrase on gmefx.com ([archived](http://archive.is/cdeyt)) is plagiarized.
* "While we are helping start-ups to raise the funds, we care about investors whose investments’ protection we wish to guarantee to the maximum extent.": [164 results](https://www.google.com/search?q=%22While+we+are+helping+start-ups+to+raise+the+funds%2C+we+care+about+investors+whose+investments%E2%80%99+protection+we+wish+to+guarantee+to+the+maximum+extent.%22) on Google
* "As we help other companies grow, she helps us grow. She handles all the internal work": [10,200 results](https://www.google.ru/search?q=%22As+we+help+other+companies+grow%2C+she+helps+us+grow.+She+handles+all+the+internal+work%22) on Google (perhaps this is from a design template?).

At this time, we will not be including your token in ForkDelta Tokenbase.
1. We have a strict no-plagiarism policy, which your project violated.
2. There are no third-party reviews.
3. No evidence of team or project.
