### ISSUE TITLE
Adding EtherStone (ETHS)

### ISSUE THREAD

**Issue by Mentors4EDU** [forkdelta/tokenbase#1339]
![e](https://user-images.githubusercontent.com/12502053/41872498-1d78f34c-7890-11e8-90d1-bcb911e2143e.jpg)
EtherStone is a project aimed to create a token that supports the Ethereum network by:

>> Being utilized as a decentralized payment gateway token
>> Being minted, and starting out as airdropped to a selective group
>> Having mining and hashing extensions to decentralize mining rewards more
>> Utilizing proper protocols to help lighten the network and lower gas fees

Hi, we are looking to add our EtherStone smart contract for listing:
https://etherscan.io/token/0xf5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59
https://forkdelta.github.io/#!/trade/0xf5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59-ETH
https://twitter.com/gamer456148/status/1009989681101012992
http://etherstone.org

[TokenJar](https://tokenjar.io/ETHS) | [Enclaves](https://enclaves.io/trade/ETHS) | [ CoinPayments](https://www.coinpayments.net/supported-coins-eth-tokens)

Telegram: t.me/etherstone

This project has been created by a high profile crypto influencer and blockchain architect as an initiative to support the Ethereum network.

Email: andrew@etherstone.org

[Bloxy Explorer](https://bloxy.info/address/0xf5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59) | [Amberdata](https://amberdata.io/addresses/0xf5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59) | [Transfers](https://www.rebellious.io/explorer/address/0xf5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59#tab=tab-transfers)

[Comment on Token](https://etherscan.io/token/0xf5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59#comments) | [Discuss on Etherchain](https://www.etherchain.org/account/f5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59#comments)  | [ CryptocurrencyTalk](https://cryptocurrencytalk.com/topic/106106-ann-etherstone/)
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">If you ever need to mine EtherStone, trying using Mvis Tokenminer and changing the contract address in the Tokenminer.ini file to EtherStone&#39;s contract address <a href="https://twitter.com/hashtag/Crypto?src=hash&amp;ref_src=twsrc%5Etfw">#Crypto</a> <a href="https://t.co/gT3ilRhqka">https://t.co/gT3ilRhqka</a> <a href="https://twitter.com/hashtag/EtherStone?src=hash&amp;ref_src=twsrc%5Etfw">#EtherStone</a> <a href="https://twitter.com/hashtag/Dev?src=hash&amp;ref_src=twsrc%5Etfw">#Dev</a> <a href="https://t.co/BTz8vj2FCv">pic.twitter.com/BTz8vj2FCv</a></p>&mdash; Andrew Kamal (@gamer456148) <a href="https://twitter.com/gamer456148/status/1011326931789369347?ref_src=twsrc%5Etfw">June 25, 2018</a></blockquote>

[Why I made EtherStone](https://www.digitalcpr.net/blog/2018/6/26/why-i-made-etherstone) | [Reddit Discussion and Review Request](https://www.reddit.com/user/EtherStone/comments/8u5a4x/discussing_etherstone_review_request/)

![dfha1fvw4aermag](https://user-images.githubusercontent.com/12502053/41792284-52be8024-7626-11e8-9834-d54be5699bd0.jpg)

**Comment by freeatnet** [comment]
Thank you for your request, @Mentors4EDU! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- **Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md)** and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Mentors4EDU** [comment]
Hi, hope it is fine I included a lot of extra information. I just wanted to make sure that all details were available upfront and as precise and accurate as possible.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by Mentors4EDU** [comment]
Token address: 0xf5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59

Issuer's official website: http://etherstone.org

Description: EtherStone is a project aimed to create a token that supports the Ethereum network by:
- Being utilized as a decentralized payment gateway token
- Being minted, and starting out as airdropped to a selective group
- Having mining and hashing extensions to decentralize mining rewards more
- Utilizing proper protocols to help lighten the network and lower gas fees

A link to the official contract address confirmation: https://etherscan.io/address/0xf5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://cryptocurrencytalk.com/topic/106106-ann-etherstone/
2. https://www.reddit.com/user/EtherStone/comments/8u5a4x/discussing_etherstone_review_request/
3. https://www.digitalcpr.net/blog/2018/6/26/why-i-made-etherstone
4. https://www.etherchain.org/account/f5ba8a8c87f976b79b17ccd25ee8dc2f8e82fb59#comments

**Comment by Mentors4EDU** [comment]
Hello, please kindly let me know if anything else is needed? Best regards, EtherStone team.

**Comment by Mentors4EDU** [comment]
@freeatnet Hi, I can't get many new miners or users if EtherStone isn't on an exchange. We added the required information and have been waiting for its ForkDelta listing for over 3 month. Please update us when you can?

**Comment by Mentors4EDU** [comment]
Hi, still want to add this if we can.
