### ISSUE TITLE
Fortknoxster

### ISSUE THREAD

**Issue by gfunksound** [forkdelta/tokenbase#134]
The contract address: 0x009e864923b49263c7f10d19b7f8ab7a9a5aad33

A link to the token issuer's official website: https://fortknoxster.com/

A couple sentences for token description: Fort Knoxster is an all in one encrypted messaging platform across multiple devices. The FKX token is used as a utility to power the platform's services. 

A link to an official page confirming the contract address: https://medium.com/fortknoxster/token-delivery-update-deefec19acee

A link to a third-party review or discussion of the token, like an established ICO review blog: https://icodrops.com/fortknoxster/

**Comment by Kryptoniq** [comment]
Verified: 0x009e864923b49263c7f10d19b7f8ab7a9a5aad33.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
