### ISSUE TITLE
List WavesPay 

### ISSUE THREAD

**Issue by puttu1442** [forkdelta/tokenbase#1341]
Hi, this is a request to list the WavesPay (WPAY) token.

1. Contract address: 0xf857007247b836152202a795eff0d04c585fcbcd

2. Official website: https://wavespay.info

3. WavesPay is a peer to peer de-centralized digital currency via Ethereum platform that will help the ecosystem of cryptocurrency to be used in the online stores as a payment token.

4. https://wavespay.info/#explorer

5. Third-party reviews and discussions of the project:
  
    https://bitcointalk.org/index.php?topic=4341724
    
    https://www.youtube.com/watch?v=A5viEytvy6U

   https://www.youtube.com/watch?v=661E86yWkZw&t=4s

Please let me know if you require any further information or articles, etc.

**Comment by freeatnet** [comment]
Thank you for your request, @puttu1442 ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
