### ISSUE TITLE
Listing ropcoin

### ISSUE THREAD

**Issue by sigonera** [forkdelta/tokenbase#1342]
Token address:
0xD2d95e0d8CEb1670D37878CEE784184b991d8509

Issuer's official website:
https://ropcoin-rpcn.com

Description:

Our aim is to realize the full potential of Ropcoin technology by changing the way people think about money and value, ultimately empowering the individual and engineering the future of finance in the world.
A link to the official contract address confirmation:

https://ropcoin-rpcn.com/token-information
At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://bitcointalk.org/index.php?topic=4485501.new#new
Not yet available

**Comment by sigonera** [comment]
I opened the 1st issue which is issue #1318 since 5 days ago but u forgot to add it to needs review, you jumped it so I have to close it and open this one, thanks, #1318

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by sigonera** [comment]
There is no link for that, what should I do now

**Comment by sigonera** [comment]
What are the missing information

**Comment by sigonera** [comment]
I think this will be useful
I just found it now 
http://www.jackobian.com/threads/ropcoin-reviews.96128/

**Comment by Kryptoniq** [comment]
@sigonera  please take your time to read my comment above.
