### ISSUE TITLE
Token Listing: 0xBitcoinCash

### ISSUE THREAD

**Issue by 0xbitcoincash** [forkdelta/tokenbase#1343]
**Token address:**

0xe5b9746dfcc2ef1054d47a451a77bb5f390c468d

**Issuer's official website:**

https://0xbitcoincash.io

**Description:** 

0xBitcoinCash is a mineable ERC20 Proof of Work Token. 0xBCH introduces a new way of token distribution by PoW which creates a fair way of users obtaining tokens by CPU/GPU mining. 0xBCH can be used as a digital currency on the Ethereum network and as a cryptocurrency.

**A link to the official contract address confirmation:** 

https://etherscan.io/address/0xe5b9746dfcc2ef1054d47a451a77bb5f390c468d#code

This can also be found on the website's navigation tab on our official website.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
