### ISSUE TITLE
Request to list eRupee (e₹)

### ISSUE THREAD

**Issue by erupeeCrypto** [forkdelta/tokenbase#1344]
**Token address:**
0xb67734521eAbBE9C773729dB73E16CC2dfb20A58

**Issuer's official website:**
https://erupee.wordpress.com

**Description:** 
eRupee (e₹) is First South Asian crypto-currency. Our Aim is to make blockchain technology accessible to every South Asian.

**A link to the official contract address confirmation:** 
https://erupee.wordpress.com/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=2839333.msg38277871#msg38277871
2. https://forumbitcoin.co.id/threads/ann-ico-zig-ecex-exchange-assignments-trading-platform.47587/page-4
3. https://trezor.io/coins/#E%E2%82%B9
4. https://www.reddit.com/r/eRupee/
5.  https://twitter.com/eRupeeCoin
6. https://www.facebook.com/ERupee-150258129035495/
7. https://bitcointalk.org/index.php?topic=2839333.new#new
8. t.me/eRupee
9. https://erupeecoin.slack.com/
10.  https://github.com/eRupee

**Comment by freeatnet** [comment]
Thank you for your request, @erupeeCrypto! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
