### ISSUE TITLE
Add Token (LAWN)  LawnCoin

### ISSUE THREAD

**Issue by comoxvalleylawncares** [forkdelta/tokenbase#1345]
0x1c73c298928ea77165330fe796c1f41a804d8d0b

http://www.comoxvalleylawncare.com/

Lawntoken is the intellectual property designed with a mission in mind and that's to create the best and most profitable bitcoin mining operation out there.  The Idea is to create mining contracts that may involve renting hashpower to generating it from acquiring the miners themselves.  This is just a fun project to mine as much crypto as possible nothing more simple than that.  Thanks for your interest in my project

[Official Contract Address](https://etherscan.io/token/0x1c73c298928ea77165330fe796c1f41a804d8d0b)

1.[Third Party Link](
https://www.icoexaminer.com/community/threads/comox-valley-lawncare-lawn-ico.965/)

2.[Next Third Party Link](https://forum.bitcoin.com/trading-discussion/new-ico-comox-valley-lawncare-t79656.html)

**Comment by freeatnet** [comment]
Thank you for your request, @comoxvalleylawncares! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
This an ICO-only project and will not be listed.
Nothing has changed after #919.

**Comment by comoxvalleylawncares** [comment]
I don't understand what you mean can you be more specific as to how I can meet the criteria to be listed on forkdelta?
