### ISSUE TITLE
UXM

### ISSUE THREAD

**Issue by tmediaJ** [forkdelta/tokenbase#1346]
**Token address:**
0xD6513C922d9bE2E26992D1FCd544E9BdD9d7b8E6

**Issuer's official website:**
https://www.theuxm.com

**Description:** 
The UXM – Optimizing the $79 trillion transactions market with blockchain driven technology while automatically generating income and wealth for individuals and businesses 24/7. Benefits all.  
UXM tokens help build the UXM blockchain marketplace platform. 

**A link to the official contract address confirmation:** 
https://www.theuxm.com/benefits/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://coindelite.com/ico-details-the-uxm
2. https://investfuture.ru/ico/the-uxm
3. https://icobench.com/ico/the-uxm
4. https://icoholder.com/en/the-uxm-ico-22520

**Comment by freeatnet** [comment]
Thank you for your request, @tmediaJ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
- Verify your contract source code on etherscan (https://etherscan.io/address/0xD6513C922d9bE2E26992D1FCd544E9BdD9d7b8E6#code).

Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
