### ISSUE TITLE
Request to Add C. 6-4 BC (C64)

### ISSUE THREAD

**Issue by CruzMolina** [forkdelta/tokenbase#1347]
**Token address:**
0x51CF271dEcEB13b1711A9B5108917F43EA65Fd05

**Issuer's official website:**
https://c64bc.om

**Description:** 
C. 6-4 BC is a decentralized Christian charity cryptocurrency, which offers a secure and safe environment for people of faith to communicate, transact, socialize, and grow together in the knowledge of Jesus. C. 6-4 BC seeks to rebuild dreams, repair lives, and revive homes of those people who are part of the community as well as those who are reached by the C. 6-4 BC community. 10% of funds are donated to non-profit organizations and charities, and more thousands of orphans are sponsored on a monthly basis. Our project rewards contributing computing power to cancer research, letters to orphans, and knowing more about Christianity. 

**A link to the official contract address confirmation:** 
https://c64bc.com/#data

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. http://www.nbc-2.com/story/38428377/a-team-of-blockchain-specialists-announces-the-ico-of-their-first-of-its-kind-decentralized-christian-charity-cryptocurrency-project-c-6-4-bc0
2. http://www.weny.com/story/38428377/a-team-of-blockchain-specialists-announces-the-ico-of-their-first-of-its-kind-decentralized-christian-charity-cryptocurrency-project-c-6-4-bc

**Comment by freeatnet** [comment]
Thank you for your request, @CruzMolina! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Your website https://www.c64bc.om/ is inaccessible ATM.

**Comment by CruzMolina** [comment]
Site should be back up now.
