### ISSUE TITLE
Edgecoin EDUX

### ISSUE THREAD

**Issue by edgecoinli** [forkdelta/tokenbase#1351]
**Token address:**
0x838df5c03147f0b038c24b18af5bb5dee1ffd446

**Issuer's official website:**
https://www.edgecoin.io/

**Description:** 
Edgecoin - The future of education is smart.
Edgecoin is the world´s first education and e-learning token built on the Ethereum Blockchain.
Beyond that it is addressing the multi-billion education industry with its unique B2B approach.
Blockchain as a Service for the education sector!

**A link to the official contract address confirmation:** 
https://www.edgecoin.io/edux-contract-address-verfication
https://etherscan.io/token/0x838df5c03147f0b038c24b18af5bb5dee1ffd446

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.coinschedule.com/blog/edgecoin-solution-educational-sector/
2. https://icomarks.com/ico/edgecoin
3. https://www.cryptomorrow.com/2018/04/12/how-cryptocurrencies-will-change-education/
4. https://bitcoinmagazine.com/articles/decentralizing-sharing-economy-blockchain-technology/

**Comment by freeatnet** [comment]
Thank you for your request, @edgecoinli! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
