### ISSUE TITLE
Add a New Token: STARBLOCK (STB)

### ISSUE THREAD

**Issue by starblockdevteam** [forkdelta/tokenbase#1352]
**Token address:**
0xc48b1ac1417db27c4e2c2ed3dae5a3d2fbb07dc5

**Issuer's official website:**
https://www.starblockofficial.io/

**Description:** 
The idea for StarBlock (STB) was born the creation of ‘HeroXchange’. Our development team had to register and integrate a dozen exchanges into our platform. Some exchanges required verification, and some did not even have API for all the currencies we wanted to incorporate into the exchanger. The creation of a blockchain based cryptocurrency exchange became our dream, and now we want it to make it come true.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xc48b1ac1417db27c4e2c2ed3dae5a3d2fbb07dc5

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.facebook.com/StarblockCoin
2. https://twitter.com/StarBlockCoin

**Comment by freeatnet** [comment]
Thank you for your request, @starblockdevteam! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
