### ISSUE TITLE
LISTING REQUEST FOR Fruition Token (FTT)

### ISSUE THREAD

**Issue by FruitionToken** [forkdelta/tokenbase#1353]
**Token address:** 0x3800e575cd4e197077f17F0f98b2F5AB892c2833

**Issuer's official website:** https://fruitiontoken.org/

**Description:** 
Fruition token introduces Agriculture into Blockchain based technology. FTT will give everyone an opportunity to invest in Agriculture from anywhere in the world, reducing complete dependence on the General Volatility of the Cryptocurrency market. Welcome to the First of its Kind finance system which combine real farm products with tokenized smart contract to create wealth for all.

**A link to the official contract address confirmation:** 
https://fruitiontoken.org/#features

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:** https://medium.com/@FruitionTokenx/fruitiontoken-ftt-agriculture-blockchain-moon-welcome-to-fruition-token-943a9ac4d85a
https://bitcointalk.org/index.php?topic=4478121.msg40206565#msg40206565

1. https://mobile.twitter.com/FruitionToken
2. https://t.me/joinchat/IlkR3A37WNJ0kz1YW-fP3Q

**Comment by freeatnet** [comment]
Thank you for your request, @FruitionToken! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by denisjames02** [comment]
@freeatnet

I want To also support the listing of FruitionToken by add this 3rd party review. 
https://foundico.com/ico/fruitiontoken.html

The project has cause our attention and we are committed to making sure it listed.

**Comment by FruitionToken** [comment]
@Kryptoniq 
???

**Comment by FruitionToken** [comment]
Fruitiontoken already trading on ecex.exchange https://ecex.exchange/portal/trading_erc20?m=ETH&t=FTT and little trades on FD via Contract address https://forkdelta.github.io/#!/trade/0x3800e575cd4e197077f17f0f98b2f5ab892c2833-ETH.

**Comment by FruitionToken** [comment]
@Kryptoniq  out token request has been neglected, its been long over due and even at that no review progress at all.
