### ISSUE TITLE
420X Listing Request

### ISSUE THREAD

**Issue by 420xlife** [forkdelta/tokenbase#1354]
https://t.me/group420X

**Token address:** 
0x064af935c8c26f124adafbdad6f6f1747f564617

**Issuer's official website:** 
https://420x.life

**Description:** 
A global Decentralized Social platform, and P2P Marketplace for Cannabis Culture accesories, Cultivation Equipment. We're putting a strong focus on green energy products for the Cannabis Industry. Offering all things Cannabis culture related on the Blockchain. Token is issued as a Currency to be used on the 420X platform and on other blockchain platforms that will be accepting the token as a payment method, and for Tips to other members of 420X platform. 

**A link to the official contract address confirmation:** 
https://etherscan.io/address/0x064af935c8c26f124adafbdad6f6f1747f564617#code
https://420x.life/token/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
 
1. https://steemit.com/cannabis/@cryptobubba/420x-life-cannabis-industry-supply-marketplace-and-social-platform
2.https://medium.com/@taimour.baig/global-cannabis-social-and-marketplace-ecosystem-coming-soon-to-blockchain-f384fc7bb97

**Comment by freeatnet** [comment]
Thank you for your request, @420xlife! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by 420xlife** [comment]
the links to missing reviews were corrected Thank you for your understanding. @Kryptoniq

**Comment by 420xlife** [comment]
@Kryptoniq any news on when we will be listed officially ?  Thanks
