### ISSUE TITLE
hello, can we enter our tokens into ForkDelta file?

### ISSUE THREAD

**Issue by firetoken** [forkdelta/tokenbase#1355]
Hello how are you, our team would like to be added into the main.json file, also it would be very helpful if we can be featured as default for a short time. Thank you very much team, have a great day.

"defaultPair": { "token": "FPWR", "base": "ETH" }

{ "addr": "0x18e4FD8B11dDcB27D39993A322f83FbB5f0a893F", "name": "FPWR", "fullName": "FireToken", "decimals": 18 },

**Comment by freeatnet** [comment]
Hello @firetoken! You should not edit the file. To be included on the list of recognized tokens on ForkDelta, please file a request here: https://github.com/forkdelta/tokenbase/issues/new/choose. Thanks!
