### ISSUE TITLE
Listing UBS Token on ForkDelta

### ISSUE THREAD

**Issue by UBSToken** [forkdelta/tokenbase#1358]
**Token address:**
0x55Bb6e6A27D3C36BCd8566a5345bB6BdEe30784A

**Issuer's official website:**
http://www.unifiedblockchainsolutions.com/

**Description:** 
Unified Blockchain Solutions launched UBS Token to provide 3rd generation hybrid crypto exchange CryptoX, Loan Lending Platform, Blockchain Based Lotto System and ICOCure Wallet(to prevent investors from ICO fraud).

**A link to the official contract address confirmation:** 
http://www.unifiedblockchainsolutions.com/Airdrop.aspx
http://www.unifiedblockchainsolutions.com/UBSToken-WhitePaper.pdf
Check Token Details Section of White Paper

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://bitcointalk.org/index.php?topic=4523195.0
2. https://www.reddit.com/user/UBSToken/comments/8sbv24/ubs_website_is_now_live/

**Comment by UBSToken** [comment]
More Details:

Website: http://www.unifiedblockchainsolutions.com/
White Paper: http://www.unifiedblockchainsolutions.com/
Telegram: https://t.me/UBSToken
Twitter: https://www.twitter.com/ubstoken
BitcoinTalk: https://bitcointalk.org/index.php?topic=4523195.0
Reddit: https://www.reddit.com/user/UBSToken/comments/8sbv24/ubs_website_is_now_live/
Medium: https://medium.com/@support_8958/unified-blockchain-solutions-introducing-ubs-token-erc-20-airdrop-5be7fe2e9b67
Steemit (UnOfficial-By Fan): https://steemit.com/crypto/@pareshdudhagra/ubs-unified-blockchain-solutions-airdrop-2500-ubs-coin-hurry-limited-spot

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by UBSToken** [comment]
Hello Admin,

SSL certificate installed on website to make it https enable.

https://unifiedblockchainsolutions.com
