### ISSUE TITLE
Listing T8EX

### ISSUE THREAD

**Issue by tramsdex** [forkdelta/tokenbase#1362]
**Token address:**
0x3E713B8eFBB62C214412aDF4aD950C385e0De0a8

**Issuer's official website:**
www.T8EX.com

**Description:** 
T8EX: World First Crypto-to-Crypto Exchange, a Wholesale Clearance Tool; T8EX empowers users with PrePaid Debit Cards, POS Machine, NFC Card & All-In-One App

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x3e713b8efbb62c214412adf4ad950c385e0de0a8

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://venturetimes.jp/cryptocurrency/ico-information/33799.html
2. https://venturetimes.jp/cryptocurrency/ico-information/34291.html
3. https://icobench.com/ico/t8ex
4. http://www.finreview.com/industry_articles/t8ex-world-first-purely-crypto-to-crypto-digital-exchange/
5. https://uk.advfn.com/stock-market/COIN/BTCUSD/share-news/T8EX-Roadshow-Part-2/77101128

**Comment by freeatnet** [comment]
Thank you for your request, @T8EX! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
