### ISSUE TITLE
QNT Quant Network

### ISSUE THREAD

**Issue by l999494** [forkdelta/tokenbase#1363]
**Token address:**
0x4a220e6096b25eadb88358cb44068a3248254675

**Issuer's official website:**
quant.network

**Description:** 
Quant Network is connecting blockchains with there product OverLedger. Overledger OS sits ontop of the blockchain layer in order to connect blockchains.

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://bitcoinmagazine.com/articles/quant-network-launches-overledger-cross-blockchain-data-interoperability/?utm_source=newmoney.tools
2. https://www.youtube.com/watch?v=i1B3h6Hh8WA&list=PLoDdBkccXSJEcFhhyACqQVKlJlH92ayO0&ab_channel=Integral
3. https://www.nasdaq.com/article/quant-network-launches-overledger-for-cross-blockchain-data-interoperability-cm888495

**Comment by freeatnet** [comment]
Thank you for your request, @l999494 ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
