### ISSUE TITLE
Add WEMcoin (WEMcoin)

### ISSUE THREAD

**Issue by WindEnergyMining** [forkdelta/tokenbase#1365]
Request to list Wind Energy Mining Coin

Name : WEMcoin
Symbol : WEMcoin
Token: ERC20
Contract address: 0x093af159e4b504fb0962e49260182768b8e54a4e
Etherscan: https://etherscan.io/token/0x093af159e4b504fb0962e49260182768b8e54a4e

Issuer's official website:
https://etb.lv/wemcoin/

Whitepapers:
https://etb.lv/pdf/Whitepaper_Wind_Energy_Mining_(en).pdf

Twitter: https://twitter.com/WindEnergyMine?lang=en
Telegram: https://t.me/WindEnergyMining
Facebook: https://www.facebook.com/windenergy.mining.1
Bitcointalk: https://bitcointalk.org/index.php?topic=3052839.0

Description:
As a part of the development of Wind Energy Mining project, the company has issued the second token – WEMcoin. WEMcoin is an ERC20 token on the Ethereum blockchain. WEMcoin is a functional token of the project and is intended to serve as:
a means of payment for renting a place for mining equipment;
a means of payment for electricity;
a medium of exchange when selling mined cryptocurrency

Email: wem@etb.lv

Thank you in advance.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by WindEnergyMining** [comment]
Hi, 
Thank you for your answer. Please check if it will be enough? 
https://www.linkedin.com/pulse/wind-energy-mining-project-update-wind-energy-mining-project/?published=t
https://bitcointalk.org/index.php?topic=3052839.msg36120821#msg36120821
http://rigacomm.com/en/cryptocurrency-mining-baltic-blockchain-landscape/
https://foxico.io/project/windenergymining
https://etherscan.io/token/0x093af159e4b504fb0962e49260182768b8e54a4e

**Comment by freeatnet** [comment]
@WindEnergyMining No. As noted above, all official communication related to your request will happen in this thread. We will not send private chat invitations to you. You can disregard anyone attempting to move discussion into private channels or ask for payment. Thanks for letting us know!

**Comment by WindEnergyMining** [comment]
Thank you for your replay! So, for now we can trade our token in Forkdelta using this link https://forkdelta.github.io/#!/trade/0x093af159e4b504fb0962e49260182768b8e54a4e-ETH
But when you will check our project our token will be in list. Right? 
How long can it takes?
