### ISSUE TITLE
Intent to delist: TWNKL

### ISSUE THREAD

**Issue by stephenhodgkiss** [forkdelta/tokenbase#1367]
@freeatnet 

I was the official person that requested the listing of the token. Please see the initial listing request if needed.

We are removing the TWNKL from all platforms where previously listed and this includes ForkDelta. Please let me know what sort of timeframe it can be delisted so we can communicate it to our token holders.

Regards
Stephen Hodgkiss

**Comment by freeatnet** [comment]
Hi @stephenhodgkiss! Is there a public announcement of you requesting TWNKL removal from platforms?

**Comment by stephenhodgkiss** [comment]
Please see https://www.rainbowcurrency.org/news and also https://www.rainbowcurrency.com where an official announcement has been made. A comment will also be added by myself on our bitcointalk discussion

**Comment by stephenhodgkiss** [comment]
@freeatnet 
Bitcointalk thread also has been updated. See [https://bitcointalk.org/index.php?topic=2735483.60]
