### ISSUE TITLE
Add Unicorn Coin (UCC)

### ISSUE THREAD

**Issue by strenev** [forkdelta/tokenbase#1368]
**Token address:** 0xc00b89fc3a7ee7043629d8f9a79abfef55634960

**Issuer's official website:** https://unicorncoin.xyz/

**Description:** Unicorn Coin is the token of The Crypto Unicorn. Eасh coin rеprеsеnts yоur оwn pеrsоnаl Uniсоrn. You cаn gеt аs mаny аs yоu wаnt аnd lаtеr trаde thеm fоr оther соins or tоkеns, suсh аs Bitсоin оr Ethеrеum. Uniсоrn Соin is аn ЕRС-20 tokеn. 

**A link to the official contract address confirmation:** https://unicorncoin.xyz/#how-to

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://www.reddit.com/r/UnicornCoin/
2. https://bitcointalk.org/index.php?topic=2862072.0

**Comment by freeatnet** [comment]
Thank you for your request, @strenev! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please edit your request to follow the required format https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md.

**Comment by strenev** [comment]
Changed the description as per your request!

**Comment by strenev** [comment]
Hello @freeatnet @Kryptoniq!  Any update on the listing?
