### ISSUE TITLE
Add ONEPAY (ONEPAY)

### ISSUE THREAD

**Issue by Onepaytoken** [forkdelta/tokenbase#1369]
hello we want to get listed in ForkDelta...
can you review our token?

Name Coin *
 Onepay

Short name of the coin *
 Onepay

Website *
 https://onepay-token.com

Contract address (For ethereum tokens) :
 https://etherscan.io/token/0xb2458f815aa3d0279f2bc456b7db95b13dfa5ed4

Description:
#Onepay (digital payment service and business)#
As digital payment service, onepay is digital payment asset with ethereum platform ERC20
Why Ethereum platform?
Ethereum the popular cryptocurrency and blockchain system, is based on the use of tokens which can be bought, sold, or traded.
Tokens, in this case, represent digital assets that can have a variety of values attached.
Our system using Ethereum network as a giant mass of nodes (computers) connected to one another. 
Everything recorded and updated in the biggest network in cryptocurrency to prevent any illegal activity from other eg hack, skimming, carding etc.
Onepay as business service,, our system to make any profit with shared terms..
And our system as the first masternode and stake system of token..
We give benefit and profit for investor and holder for loyalty program...
Our masternode and stake system implementation to reduce any cost for investor and holder,, we are different with other crypto,,, our transparant system will go public and make grow the network..

Everything with low cost and fee
Our future digital payment and business,,

business focus : Cloud mining, OnlineShop, Ticket Shop, Games Shop, and many Sponsoring in invasion For 15 years 
// we take all exchange in the world for one payment processor that's ONEPAY

FORUM:
1. https://bitcointalk.org/index.php?topic=4311374.0
2. https://bitcoingarden.org/forum/index.php?topic=38298.0

**Comment by freeatnet** [comment]
Thank you for your request, @Onepaytoken! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- **Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md)** and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
