### ISSUE TITLE
Listing Request: CEHH

### ISSUE THREAD

**Issue by OFRBG** [forkdelta/tokenbase#137]
We would like to kindly request CehhCoin to be listed. Here is the ANN thread: https://bitcointalk.org/index.php?topic=2954666

---

Here is the PPoW white paper: https://twitter.com/Cehhiro/status/965696520233390081
Here is the CehhCoin white paper: https://twitter.com/Cehhiro/status/964268225847529473

The token information is:
```
Address:   0x4F38f4229924bfa28D58eeda496Cc85e8016bCCC
Symbol:    CEHH
Decimals:  0
```

---

**Short description:**

CehhCoin is the first PPoW token. This means it is a mineable token with a new clever system. The coin is fully decentralized and will work as a founding stone for the PPoW shift.

If there are any questions or problems, please let me know.

**Comment by Kryptoniq** [comment]
1. Website is missing
2. No official link confirming contract address.

**Comment by OFRBG** [comment]
You can find the website at https://cehh.cash and the contract on that same page.

**Comment by Kryptoniq** [comment]
Verified: 0x4F38f4229924bfa28D58eeda496Cc85e8016bCCC.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
