### ISSUE TITLE
Add 	Peoplewave Token (PWV)

### ISSUE THREAD

**Issue by peoplewave** [forkdelta/tokenbase#1370]
**Token address:**

0x8f66a173696502a0ad280781c3e55928a06c1312

**Issuer's official website:**

www.peoplewaveico.io

**Description:** 

Peoplewave is revolutionizing HR through its Peoplewave token and has already established two products – First 100 Days and Performance Wave, and is working on our third product – HR Command Centre. You can find more information and register for a free trial of Performance Wave at www.peoplewave.co. The ICO funds raised will be used to build Wavebase, our blockchain-enabled solution, to provide an immutable database of accurate and verified performance and employment information. 

**A link to the official contract address confirmation:** 

https://etherscan.io/token/0x8f66a173696502a0ad280781c3e55928a06c1312

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjmnenxtfjbAhUbfCsKHWcyAGgQwqsBCCswAQ&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DFVqDovkrRG4&usg=AOvVaw2m66xIVzDxScAQoJZY3Ttq

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwjmnenxtfjbAhUbfCsKHWcyAGgQwqsBCDEwAw&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DIGEKEkTRkwY&usg=AOvVaw1mTasFYysAG1P-HbgWKsAN

1. 
2.

**Comment by freeatnet** [comment]
Thank you for your request, @peoplewave! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by peoplewave** [comment]
Here are 3 independent articles about the project. Will this do?

https://www.prnewswire.com/news-releases/peoplewave-to-launch-ico-on-quoines-ico-mission-control-platform-on-31-may-2018-300655375.html

https://www.the-blockchain.com/2018/05/29/peoplewave-lists-hr-blockchain-ico-on-quoine-platform/

https://www.businesstimes.com.sg/magazines/the-sme-magazine-marchapril-2018/managing-people-problems-with-technology
