### ISSUE TITLE
Add Blockonix (BDT)

### ISSUE THREAD

**Issue by n3wr1ch** [forkdelta/tokenbase#1371]
**Token address:**
0x741F58cd68D24f361Cc0ee0D3aaf7DF2bf16132E

**Issuer's official website:**
https://blockonix.com

**Description:** 
Blockonix is a decentralized cryptocurrency exchange platform different from the other centralized approaches a lot of other cryptocurrency exchanges uses.
We developed our own native BDT tokens which can be directly swapped from Blockonix website. We aim to make BDT token as transferable as possible by making it exchangeable for all of the major cryptocurrencies available on the market. Using our own native token on Blockonix makes it practicable for us to keep exchange rate variations to a low level making the tokens more useful and reliable.

**A link to the official contract address confirmation:** 
https://ethplorer.io/address/0x741f58cd68d24f361cc0ee0d3aaf7df2bf16132e

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://coinnounce.com/blockonix-becoming-global-cryptocurrency-exchange-platform/
2. https://hype.codes/blockonix-cooperate-coinhub-exchange

**Comment by freeatnet** [comment]
Thank you for your request, @n3wr1ch! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
