### ISSUE TITLE
Add AgesToken (AGSTN)

### ISSUE THREAD

**Issue by princeofetn** [forkdelta/tokenbase#1372]
I want to list a token.
Token name : AgesToken
Website : www.agestoken.com
Contract address : 0x7b01b46d606ebFd30CC1581E513d97423eA63F10
Symbol : Agstn
Decimal : 18
Etherscan link:https://etherscan.io/address/0x7b01b46d606ebfd30cc1581e513d97423ea63f10

**Comment by Kryptoniq** [comment]
Please edit your request to follow the required format https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md .
