### ISSUE TITLE
Add MUXE Token (MUXE)

### ISSUE THREAD

**Issue by vitor0102** [forkdelta/tokenbase#1373]
Token address:
0x515669d308f887fd83a471c7764f5d084886d34d

Issuer's official website:
https://www.muxe.io

Description:
MUXE is a one-stop platform that facilitates from buying your DREAM HOME, to getting RENTAL income from your extra space, inspired with latest INTERIOR DESIGNS tips, sourcing best MAINTENANCE contractors for your property to ordering HOME IMPROVEMENTS to spruce up your current pad.

A link to the official contract address confirmation:
https://www.muxe.io/compatible-wallets/

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://icoschedule.co.kr/2018/05/23/muxe/
2. https://icobench.com/ico/muxe

**Comment by Kryptoniq** [comment]
Please edit your request to follow the required format https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md .

**Comment by vitor0102** [comment]
why you do not remove this missing information topic
