### ISSUE TITLE
Add CryptoDrachme (DR)

### ISSUE THREAD

**Issue by CryptoDrachme** [forkdelta/tokenbase#1374]
**Token address:**
0x82f229654a77ddd0e5b3fdc6b987f799869691a6

**Issuer's official website:**
https://www.cryptodrachme.org

**Description:** 
The Drachme is the national currency of Greece and the idea of CryptoDrachme was devised in order to create a Greek cryptocurrency where it will address and will concern the Greek community and the Greeks in general as well as returning the coin to cryptocurrency.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x82f229654a77ddd0e5b3fdc6b987f799869691a6

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=4489647.0
2.https://t.me/joinchat/I3ruVAvi9hNN_tYgARGljA

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
