### ISSUE TITLE
change to Ankorus ( ANK )

### ISSUE THREAD

**Issue by bobbypaintsstuf** [forkdelta/tokenbase#1378]
https://forkdelta.github.io/#!/trade/ANK-ETH

the  website link used in the original listing application will now auto direct to

 https://ankotc.com

copy of original link https://www.ankorus.org/  copied from https://github.com/forkdelta/tokenbase/issues/403

The project will use this new site ( https://ankotc.com ) from now on and any traffic to the previous link will auto direct to this new one.

Ankorus ( ANK )

0xaa4ab1c817e4df7d25ce4d42352649d592a3bba0

**Comment by bobbypaintsstuf** [comment]
updated with the addition of copied links from original listing request issue to make it easy to check

**Comment by freeatnet** [comment]
Token file: https://github.com/forkdelta/tokenbase/blob/1a0cd63482fb4a89b9ec1997ce1d9cbda4197220/tokens/0xaa4ab1c817e4df7d25ce4d42352649d592a3bba0.yaml

**Comment by freeatnet** [comment]
Confirmed that ankorus.org redirects to https://ankotc.com.

**Comment by bobbypaintsstuf** [comment]
As additional information the following coin tracker has the new URL displayed 

https://www.coingecko.com/en/coins/ankorus-token

**Comment by bobbypaintsstuf** [comment]
and the first coin tracker featuring the token has now been updated with the new site link also

https://coinlib.io/coin/ANK/Ankorus+Token
