### ISSUE TITLE
Add Icoin Listing (Icoin)

### ISSUE THREAD

**Issue by aicgi** [forkdelta/tokenbase#1379]
Contract address: 0x648C66A11A7EF4e1A64BE7A92625b8A08eb8D202

Issuer's official website: https://icoin.com

Description:  Promotion & reference ICO listing

Official contract address confirmation: https://etherscan.io/address/0x648c66a11a7ef4e1a64be7a92625b8a08eb8d202 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.  https://t.me/icoincomm
2.  https://facebook.com/ICOIN-Listing-363750657469587
3. https://t.me/icoinofficial
4. https://mobile.twitter.com/IcoinCommunity

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by freeatnet** [comment]
Thank you for your request, @ArieNR! Here's what to expect:

- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by ArieNR** [comment]
Hi, thanks for support. How if Me no have Bitcointalk account, I wish there tolerance by ForkDelta. :)

**Comment by freeatnet** [comment]
@ArieNR You do not _need_ a bitcointalk thread, but it is one of the options. What we need is reasonably in-depth discussion of the project / product / token by an independent third party, at least 2 sources.

**Comment by RI91** [comment]
what about the coin? has any mandatory updates?
