### ISSUE TITLE
Listing request - UTT (United Traders Token)

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#138]
Announcement: https://bitcointalk.org/index.php?topic=2384512

Website: https://uttoken.io
Whitepaper: https://investment-prod.s3.amazonaws.com/whitepaper/Whitepaper_Full-version_en.pdf
Description: Token to be used in the UTEX (United Trader's Exchange) which can be found at https://unitedtraders.com. Trade on NYSE, CME and other stock markets from within our trading platform.

Contract address: https://etherscan.io/token/0x16f812be7fff02caf662b85d5d58a5da6572d4df
Symbol: UTT
Full Name: United Traders Token
Decimals: 8
Type: ERC20

**Comment by Kryptoniq** [comment]
Provide an official link that verifies the contract address.

**Comment by tradedbytony** [comment]
Contract address: https://etherscan.io/address/0x16f812be7fff02caf662b85d5d58a5da6572d4df

**Comment by tradedbytony** [comment]
Here you go, their official Medium account with instructions on how people can withdrawal the tokens to their ETH wallets: https://medium.com/@Uttoken.io/uttoken-ico-is-finished-af5bb24a24d

**Comment by Kryptoniq** [comment]
Verified 0x16f812be7fff02caf662b85d5d58a5da6572d4df.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
