### ISSUE TITLE
Add Firetoken (FPWR)

### ISSUE THREAD

**Issue by firetoken** [forkdelta/tokenbase#1380]
**token address:**
0x18e4fd8b11ddcb27d39993a322f83fbb5f0a893f

**Issuer's official website:**
https://firetoken.io

**Description:** 

FireToken is the first-of-its-kind democratic decentralized investment community. Members actively vote on weekly investments, share market data and combine volume to influence the market. FireToken Network also offers a wide array of services in their self-sustainable ecosystem, where FireTokens are the only currency accepted as payment for those services.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x18e4fd8b11ddcb27d39993a322f83fbb5f0a893f

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://wiserico.com/ico/firetoken
2. https://www.trackico.io/ico/firetoken/

**Comment by freeatnet** [comment]
Thank you for your request, @firetoken! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
