### ISSUE TITLE
TOKEN LIST

### ISSUE THREAD

**Issue by sameh01057** [forkdelta/tokenbase#1381]
I NEED YOUR SUPPORT TO LIST MY TOKEN
https://etherscan.io/token/0xd21b2971235a4aa47d18c44768882118a51190e7

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
