### ISSUE TITLE
Add VOXXO (VOXXO)

### ISSUE THREAD

**Issue by voxxomusic** [forkdelta/tokenbase#1382]
Token address:
0x3e02b51439cb90698d54aee36bb29ff8bb76b74d

Issuer's official website
https://voxxo.io

Description:
VOXXO is a promising concept for music. It combines Music Player, Concert Investments, and Music Licensing. VOXXO aims to be music cryptocurrency which gives power to VOXXO token holder community to define music value.

A link to the official contract address confirmation:
https://voxxo.io/#contact

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://cryptovest.com/news/voxxo-seeks-to-disrupt-digital-entertainment-industry-with-live-concert-events-platform/

https://www.cryptocrunch.io/voxxo-the-new-music-player-that-makes-use-of-cryptocurrency/

https://www.icodesk.io/2017/12/13/voxxo-futuristic-profitable-and-unrestricted-way-to-create-listen-and-sell-music/

http://icofriends.com/voxxo/

**Comment by freeatnet** [comment]
Thank you for your request, @voxxomusic! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kryptoniq** [comment]
Please provide at least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer. Reviews must include review of project vision, team, milestones, or existing product.
The links you provided does not qualify for a third-party review.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:

- We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
- Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by voxxomusic** [comment]
Here some others:

https://www.cryptocrunch.io/voxxo-the-new-music-player-that-makes-use-of-cryptocurrency/

http://icofriends.com/voxxo/

https://www.icodesk.io/2017/12/13/voxxo-futuristic-profitable-and-unrestricted-way-to-create-listen-and-sell-music/

**Comment by etherlife** [comment]
Let us now, if any further information is needed.

**Comment by voxxomusic** [comment]
Let us now, if any further information is needed.
