### ISSUE TITLE
Add MyFiChain (myfi)

### ISSUE THREAD

**Issue by OctaconDeveloper** [forkdelta/tokenbase#1384]
**Token address:** 0x0dfdd839cde95dabf56f0b5c5698e0159138930d

**Issuer's official website:**
https://www.myfichain.com

**Description:** 
MyFIchain is a global payment system built on the ethereum network. Myfichain is a low volatility crypto asset regulated by the token holders and integrated with methods proven in traditional financial markets. MyFIchain asset is a low volatility cryptocurrency with predictable and dirigible price  development. It may be employed both as a means of settlement and a means of saving. 

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x0dfdd839cde95dabf56f0b5c5698e0159138930d

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://t.me/joinchat/FThJxkVVjPxJxRVWLK0aMg
https://bitcointalk.org/index.php?topic=1662702.700

1. 
2.

**Comment by freeatnet** [comment]
Thank you for your request, @kaakadev! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
