### ISSUE TITLE
Add E-VERIFY (EVER)

### ISSUE THREAD

**Issue by E-Verify** [forkdelta/tokenbase#1387]
**1. The contract address:**  0xadb631167DdE6222efE66478ACD3Cd68e192a270

**2. A link to the token issuer's official website:**  https://e-ver.io/

**3. Token's description:** E-VERIFY is the first of its kind decentralized Identity verification and Information security technology project. Our technologies provide a fast, efficient, unalterable and dynamic alternatives to existing methods. 
The EVER token serves as a medium with which transaction is carried out and processed on the E-Verify ecosystem.

**4. A link to an official page confirming the above contract address:**  https://e-ver.io/

**5. Links to third-party reviews**

  https://bitcointalk.org/index.php?topic=4503061.0
                                                        https://wiserico.com/ico/e-verify
                                                       https://icoholder.com/en/e-verify-22629

**6. Well-defined channels of communication:**  

https://t.me/EverTokenGroup
                                                                              https://twitter.com/EverToken
                                                                              https://www.facebook.com/everify/

**7. Link to document (also on official website):** 

https://e-ver.io/assets/docs/E-Verify_Onepager.pdf

**8. Contact:** I represent the project. Email: info@E-Ver.io

**9. Token distribution:** Airdrop and sales

**10. Etherscan link for the token:**  https://etherscan.io/token/0xadb631167dde6222efe66478acd3cd68e192a270#balances

**Comment by freeatnet** [comment]
Thank you for your request, @E-Verify! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by E-Verify** [comment]
Okay, thank you!

**Comment by E-Verify** [comment]
Hello @freeatnet, We got an email that gave us a free listing link and says for full listing, we should go to https://t.me/Forkdelta_official_listing. Is it legit?

**Comment by Kryptoniq** [comment]
@E-Verify, please note that ForkDelta will never contact you first and we do not charge for listing. 
The telegram group does not belong to ForkDelta.

**Comment by E-Verify** [comment]
Okay, thank you. @Kryptoniq, how long does it take for a token to be added?
