### ISSUE TITLE
Update HDG to BTT

### ISSUE THREAD

**Issue by kdekleva** [forkdelta/tokenbase#1389]
Dear Forkdelta team,

Im from Blocktrade (FKA Hedge). We performed a token swap - swapping HDG for BTT. BTT has the same functionality as HDG, just a different name. See the info below:

HDG contract: https://etherscan.io/token/0xffe8196bc259e8dedc544d935786aa4709ec3e64

BTT contract: https://etherscan.io/token/0xfa456cf55250a839088b27ee32a424d7dacb54ff

A confirmation that BTT is a continuation of HDG can be found on the blocktrade.com (https://blocktrade.com/btt-token/), as well as on old Hedge social media, see for example https://twitter.com/hedgetoken, that are only forwarding/retweeting/liking Blocktrade content.

If you have any questions, feel free to reach me on kristjan.dekleva@blocktrade.com or kristjan@hedge-crypto.com

**Comment by freeatnet** [comment]
@kdekleva Thank you for letting us know! We'll deal with it as soon as possible.

**Comment by freeatnet** [comment]
Review notes:

HDG file: https://github.com/forkdelta/tokenbase/blob/4d831d607b45461043743389eab6cc643cff604c/tokens/0xffe8196bc259e8dedc544d935786aa4709ec3e64.yaml

Official HDG blog says "Hedge, now Blocktrade.com", see https://medium.com/hedge-token/dear-tokenholders-7329eb096420. 

https://blocktrade.com/btt-token/ is linked in the header of the website.

This resolves #731 too.
