### ISSUE TITLE
Listing request - VIO

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#139]
Announcement: https://bitcointalk.org/index.php?topic=2975545

Website: https://www.viome.io
Whitepaper: https://www.viome.io/resources/Vio%20Whitepaper.pdf
Description: The easiest way to send money to a Visa Card.

Contract address: https://etherscan.io/token/0x94ffb55ce68231c5966ea8dab16a8f066846513f
Symbol: VIO
Full Name: Vio
Decimals: 18
Type: ERC20

(Okay, the ICO just started today on this one but they send the tokens right away after the contribution. Plus, I don't know how long it'd take for a ForkDelta dev to consider an issue once posted here so I figured I got the headstart on this one)

**Comment by Kryptoniq** [comment]
Verified 0x94ffb55ce68231c5966ea8dab16a8f066846513f.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
