### ISSUE TITLE
New token 

### ISSUE THREAD

**Issue by usproperty** [forkdelta/tokenbase#1392]
The Virtual World TVW NOT LISTED IN TOKENS PLEASE UPDATE

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by freeatnet** [comment]
@usproperty Do note also that tokens can be traded by contract address, without appearing in the recognized token list. Required information to appear in the token list is described in the link above.
