### ISSUE TITLE
Add CYBERFM (CYFM) Mainstream for the Underground (MFTU)

### ISSUE THREAD

**Issue by Ejborja** [forkdelta/tokenbase#1393]
**Token address:**
Token Contract Address: 0x3f06B5D78406cD97bdf10f5C420B241D32759c80
Token Symbol: CYFM 
Decimals: 18
https://etherscan.io/token/0x3f06B5D78406cD97bdf10f5C420B241D32759c80

Token Contract Address: 0x05D412CE18F24040bB3Fa45CF2C69e506586D8e8
Token Symbol: MFTU 
Decimals: 18
https://etherscan.io/token/0x05d412ce18f24040bb3fa45cf2c69e506586d8e8

**Issuer's official website:**
https://www.mftu.net/

**Description:** 

**A link to the official contract address confirmation:**  
 https://www.mftu.net/  

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://steemit.com/eos/@globalgreg/crypto-sploring-cyberfm-and-mftu-building-a-music-lovers-artists-and-cryptocurrency-community
2. https://medium.com/@bellokingsley100/mainstream-for-the-underground-mftu-and-cyberfm-cyfm-two-tokens-to-watch-out-2018-2019-423701b5b866
3. https://www.linkedin.com/pulse/cyber-fm-mainstream-underground-levelling-playing-field-mina-down/
4. https://steemit.com/cyberfm/@brainz/introduction-to-cyberfm-cyfm-and-mainstream-for-the-underground-mftu

**Comment by freeatnet** [comment]
Thank you for your request, @Ejborja! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
