### ISSUE TITLE
Add BOSTOKEN (BOS)

### ISSUE THREAD

**Issue by cryptohny** [forkdelta/tokenbase#1395]
Token address:
0x3c0cac8290e2a6241814f812259278bea9050838 

Issuer's official website:
https://www.bostoken.co

Description: 
BOS Blockchain for Financial Services Bring trust, simplicity and efficiency to transactions through the establishment of new financial services infrastructure and processes with Ethereum Blockchain.

A link to the official contract address confirmation: 
https://etherscan.io/token/0x3c0cac8290e2a6241814f812259278bea9050838

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://icoholder.com/en/bostoken-23070
https://bitcointalk.org/index.php?topic=4586855

Sosial media

twitter :  https://twitter.com/bosblockchain
telegram :  https://t.me/bostokenofficial
github : https://github.com/bostoken
 facebook : https://www.facebook.com/BOS-Blockhain-439172769828110
reddit : https://www.reddit.com/r/bostoken
sslack : https://bostoken.slack.com
medium : https://medium.com/@bostoken

**Comment by freeatnet** [comment]
Thank you for your request, @Bostoken! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
