### ISSUE TITLE
Add Getseeds Token (GSD)

### ISSUE THREAD

**Issue by tevonline** [forkdelta/tokenbase#1396]
**Token address:**
0x2368056f36035d01e7c2aa2a15b87e47cc9d2d23

**Issuer's official website:**

https://www.getseeds.info
**Description:** 

Getseeds is a newly introduced cryptocurrency that operates through the Ethereum Decentralized Blockchain Network. Getseeds tokens will be used on the Dapp SeedersBlock; A pioneer in digital content rewards based on Proof of Creativity.
SeedersBlock is a decentralized social media platform based on Ethereum blockchain technology that supports community building and social interaction with cryptocurrency rewards. The blockchain system reward bloggers, artistes, artists, comedians and other creatives including the user base for using the platform to showcase their talents to the world.

**A link to the official contract address confirmation:** 

https://www.getseeds.info
can be found on the home page. under the Iho Progress.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=4372809.msg39012284#msg39012284
2. https://medium.com/@getseeds
https://twitter.com/GetseedsGSD

**Comment by freeatnet** [comment]
Thank you for your request, @tevonline! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by tevonline** [comment]
Looking forward to your review replies
