### ISSUE TITLE
BitUnits (UNITS) Listing request. 

### ISSUE THREAD

**Issue by iabcdigitals** [forkdelta/tokenbase#1398]
I would like to make a request to have my token listed. Here are some details of the token.

Name of ERC223 token: BitUnits (UNITS)
Total supply: 10,000,000 UNITS
Smart contract address: 0xD1c10d433C888E6d1841fF924d0CE45157f0d5Cd
Distribution method: Airdrops and Trading (No ICO)
Token type: Fast global Currency
Blockchain: Ethereum Classic
Website: www.BitUnits.club

**Comment by freeatnet** [comment]
Thank you for your request, @iabcdigitals! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
