### ISSUE TITLE
Remove/Block the selfdestructed 'MOAC' token

### ISSUE THREAD

**Issue by DeltaBalances** [forkdelta/tokenbase#1399]
**What token should be updated?**

Token address `0xf24057a3e7c0fa4b7d26ceebc8ed050582a61163`
Symbol `MOAC`
https://etherscan.io/token/0xcbce61316759d807c474441952ce41985bbc5a40

**What about the token should be updated?**

Token contract has been selfdestructed at tx `0xd397c5ef0dadfb9614130a304312c961c90baee4eefb5721492bae2ebd027955`
https://etherscan.io/tx/0xd397c5ef0dadfb9614130a304312c961c90baee4eefb5721492bae2ebd027955

No deposits or withdraws are ever possible again.

**Comment by freeatnet** [comment]
Thanks @DeltaBalances!

**Comment by therealMikkoK** [comment]
Remove Token as per request.

**Comment by freeatnet** [comment]
@therealmikkok closed by accident, reopening.

**Comment by therealMikkoK** [comment]
@freeatnet Please DM me on this when you have time to.
