### ISSUE TITLE
BCDT Token listing

### ISSUE THREAD

**Issue by VinceBCD** [forkdelta/tokenbase#14]
Here is informations about Blockchain Certified Data Token (BCDT)
Token contract address: 0xacfa209fb73bf3dd5bbfb1101b9bc999c49062a5
symbol: BCDT
decimal: 18
token description: BCDT is the token of the EvidenZ ecosystem, an open source framework designed for data certification. BCDiploma is its first use case and aims to become the standard for diploma certification worldwide.
Official Website: https://www.bcdiploma.com
Telegram: https://t.me/BCDiploma
Twitter: https://twitter.com/BCDiploma
Review 1: http://fliphodl.com/analysis-of-bcdiploma-ico/
Review 2: https://icobench.com/ico/bcdiploma

**Comment by freeatnet** [comment]
Thanks for the submission, @VinceBCD!

Contract address verified from: https://medium.com/bcdiploma/bcdiplomas-ico-is-live-hardcap-1-800-eth-a307b0cfa0d4

**Comment by freeatnet** [comment]
@VinceBCD The listing is ready. Please, look over it to confirm the details.

If there are no corrections, the token will be listed within 24 hours. You'll receive a github notification when that happens.

**Comment by VinceBCD** [comment]
@freeatnet, everything's OK
