### ISSUE TITLE
eBTCS Token  Listing

### ISSUE THREAD

**Issue by eBTCS** [forkdelta/tokenbase#140]
0xfd219686033da14219142504c7a63ae8a4912134
www.ebtcs.io

eBTCS is a tokenised version of BitcoinSilver. eBTCS is currently a store of value, but our 'eBTCS Elite' development team will be working directly with our community members to develop creative use cases for eBitcoinSilver in the coming months. Our goal is to make eBitcoinSilver a platform that is broadly utilised by many people, in many ways. We envision eBTCS to be the most utilised and accessible e-token on the cryptocurrency market.

https://etherscan.io/token/0xfd219686033da14219142504c7a63ae8a491213

-----

Additional Info:

GIT: https://github.com/Ejborja/eBitcoinSilver
Website: www.ebtcs.io
Etherscan: https://etherscan.io/token/0xfd219686033da14219142504c7a63ae8a4912134
Name: eBitcoinSilver
Symbol: EBTCS

Smart Contract: 0xfd219686033da14219142504c7a63ae8a4912134
Symbol: EBTCS
Decimal places: 18

We look forward to your response,

eBTCS Team

**Comment by Kryptoniq** [comment]
Please attach a link to a review or discussion of the token.

**Comment by eBTCS** [comment]
We are a community airdrop token, we have not paid or requested for any articles to be written on our project, quite frankly, we have not needed them. We do have a few articles on Steemit and a BitcoinTalk page, but we prefer to engage with our community via our social media channels.

https://steemit.com/ebtcs/@cryptolover01/ebtcs
https://bitcointalk.org/index.php?topic=2576178.msg26238907#msg26238907

We are currently listed on Token Store and we will be listed on Upcoin once it goes live, if we do not meet your requirements then we apologize for wasting your time.

Kind regards,

- eBTCS team

**Comment by freeatnet** [comment]
@eBTCS Thanks for your request! ebitcoinsilver token has been listed: https://forkdelta.github.io/#!/trade/eBTCS-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by eBTCS** [comment]
Much appreciated. One question, is there a reason why we are listed at the
bottom of the menu with a lowercase e? Our official token symbol is EBTCS.
Having it located at the bottom of the list is not very intuitive and makes
it harder for traders to locate.


Kind Regards,

- eBTCS Team

**Comment by freeatnet** [comment]
@eBTCS We used the official symbol as provided by the contract. The sorting is case-sensitive right now, but we'll likely be switching to case-insensitive in the future.

**Comment by eBTCS** [comment]
Ok thanks, if and when that happens it would be great if we can secure
EBTCS in the menu. Thanks again for the listing.


-eBTCS Team
