### ISSUE TITLE
Add Ethearnal Rep Token (ERT)

### ISSUE THREAD

**Issue by Ethearnal** [forkdelta/tokenbase#1400]
Hello,
my name is Rami Spasov (https://www.linkedin.com/in/rami-spasov-3b846a158/) and I am the COO of Ethearnal LLC. I would like to list our ERT (Ethearnal Rep Token) on Forkdelta. If there is any information missing or incomlepte you can also contact us on our official Mail: support@ethearnal.com.

**The contract address:** 0x8c78A83DE6FAa64B100B6055BDF3a1f0b445eFD2

**Token's description:** Ethearnal is a peer-to-peer freelance system and our Token represents the Reputation in any contract between an employer and a freelancer. When accepting a contract each side will stake a pre-defined ammount of tokens which will be used to compensate the losing side and/or the moderators in case a dispute arises.

**Link to the official page:** (the last question in our FAQs includes the contract address): https://ethearnal.com/#faq

**Links to third-party articles:** 
An article of an independant finance expert: https://medium.com/@hristovbz/valuing-a-token-economy-practical-case-b12019568013

**Our Youtube Channel:** https://www.youtube.com/channel/UC6DOpVCWsEXP8Scd6os7BdA?

**ICO Reviews:** 
https://icopointer.com/ethearnal
https://icorating.com/analytics/indepth/ethearnal/
https://thetechinsider.org/cryptocurrencies/ethearnal-ico-review-the-decentralized-freelance-network/

Additionally on our website, you'll find the links to all our social media channels that have combined more than 40k interactions. Have a nice day!

**Comment by freeatnet** [comment]
Thank you for your request, @Ethearnal ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Ethearnal** [comment]
Thank you for the listing! Just one thing our name is visible as "Ethearnal Re", which is uncomplete. The Symbol "_ERT_" or the full name "_Ethearnal Rep Token_" will be the best option. Thank you again!
