### ISSUE TITLE
Add Relex Life (RLXI)

### ISSUE THREAD

**Issue by jtoncic** [forkdelta/tokenbase#1401]
Hi, I'm requesting for Relex Life to be listed on ForkDelta. It already has some trading going on after it was air dropped over the last few days. 

Here is the etherscan: https://etherscan.io/token/0xd0a024e4b057024f941051dc19220a3bab4b5d45

This is the contract address: 0xd0a024e4b057024f941051dc19220a3bab4b5d45
18 Decimals
RLXI is the ticker symbol, and the token itself is called Relex Life.

life.relex.io is the website associated with it.

**Comment by freeatnet** [comment]
Thank you for your request, @jtoncic ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- **Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate.** This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
