### ISSUE TITLE
Add Horizon Token (HRZN)

### ISSUE THREAD

**Issue by Kayeshlyn** [forkdelta/tokenbase#1403]
Token address: 0x19202b12bF9735DB1350C0110A71F2d70cD4cb7B

Issuer's official website: https://horizoncomm.co/

Description: 
Horizon Communications is an upcoming fixed wireless internet and cellular service provider looking to provide services in Bermuda, the Caribbean, and Central America before expanding internationally. 

The Horizon token is a unique, new Ethereum based token build on the blockchain. It is designed to be used to access services, and service discounts within the Horizon ecosystem. 

Our service offering will include Internet speeds of up to 150 Mbps in 2018 and 300 Mbps and faster in late 2018/2019.

A link to the official contract address confirmation:  https://etherscan.io/token/0x19202b12bf9735db1350c0110a71f2d70cd4cb7b?a=0xba1f960303cdc6867fb9c037ae5a29d8bb4dcff9

https://horizoncomm.co/feast-content/uploads/Horizon-OnePager.pdf

Contract address official link can't be found in official website yet, since we're still having an pre-sale right now. We're planning to be listed in forkdelta, hopefully soon. Since community demands for it, as we prepared for tokens wall which could probably another way for conducting pre-sale as an ICO price. Hopefully we can discuss further business partnership with the team.

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://icobench.com/ico/horizon-communications
2. https://icoholder.com/en/horizon-communications-19242

Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.

Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
1. https://twitter.com/HorizonCoin
2. https://www.facebook.com/HRZNComm/
3. https://www.instagram.com/HorizonCommICO/
4. https://t.me/HorizonCommICO
5. https://bitcointalk.org/index.php?topic=2960817.0
6. https://www.linkedin.com/company/horizon-communications-bermuda/
7. https://medium.com/@artiedarrell

**Comment by freeatnet** [comment]
Thank you for your request, @Kayeshlyn! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Kayeshlyn** [comment]
Token address: https://etherscan.io/token/0x19202b12bf9735db1350c0110a71f2d70cd4cb7b?a=0xba1f960303cdc6867fb9c037ae5a29d8bb4dcff9

Issuer's official website: https://horizoncomm.co/

Description: Horizon Communications is an upcoming fixed wireless internet and cellular service provider looking to provide services in Bermuda, the Caribbean, and Central America before expanding internationally.

The Horizon token is a unique, new Ethereum based token build on the blockchain. It is designed to be used to access services, and service discounts within the Horizon ecosystem.

Our service offering will include Internet speeds of up to 150 Mbps in 2018 and 300 Mbps and faster in late 2018/2019.

A link to the official contract address confirmation: https://horizoncomm.co/feast-content/uploads/Horizon-OnePager.pdf

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://icobench.com/ico/horizon-communications
2. https://icoholder.com/en/horizon-communications-19242

**Comment by Kayeshlyn** [comment]
@freeatnet Hello, mate. Any updates?
