### ISSUE TITLE
Add CONNECT (CNCT)

### ISSUE THREAD

**Issue by Connecttoken** [forkdelta/tokenbase#1404]
Hi would you please consider adding CONNECT to you exchange please, this is not just a pump and dump token.
my website is https://www.connecttokenlimited.com/token

**Comment by freeatnet** [comment]
Thank you for your request, @Connecttoken! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by freeatnet** [comment]
Replaced by #1458.
