### ISSUE TITLE
Add Exceed (EXC)

### ISSUE THREAD

**Issue by ExceedToken** [forkdelta/tokenbase#1405]
Token address: 0x1eae15d9f4fa16f5278d02d2f8bda8b0dcd31f71

Token name: Exceed
Token ticker symbol: EXC

Block explorer: https://etherscan.io/token/0x1eae15d9f4fa16f5278d02d2f8bda8b0dcd31f71
Block explorer 2: https://ethplorer.io/address/0x1eae15d9f4fa16f5278d02d2f8bda8b0dcd31f71

Issuer's official website: http://www.exceed-io.com/

Description: Exceed IO is a decentralized data management platform powered by blockchain technology. The Exceed Token ecosystem facilitates and incentivizes collective data aggregation to create a safe and efficient information marketplace.

A link to the official contract address confirmation: https://www.exceed-io.com (you will see it next to "official exceed token contract address" under the token sale section. 

2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://www.trackico.io/ico/exceed-io/
2. https://coinlib.io/coin/EXC3/Exceed
3. https://cryptonext.com/ico/exceed-io

Twitter: @ExceedIOEXC

**Comment by freeatnet** [comment]
Thank you for your request, @ExceedToken! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
