### ISSUE TITLE
Replacing eDash (EDASH) to EtherByte (EBX)

### ISSUE THREAD

**Issue by FlamesEBX** [forkdelta/tokenbase#1407]
**What token should be updated?**
0x01a28adc0edd796b570ec4da734e1aa809f6f1fc
eDASH
https://forkdelta.github.io/#!/trade/EDASH-ETH

**What about the token should be updated?**
https://edashcurrency.wixsite.com/revamp
https://www.etherbyte.center/etherbyte-1
[BOTH ADDRESS CONFIRMING A CONTRACT UPDATE SWITCH]

We launched 'eDASH' last year. Once EtherDelta confirmed our request we figured that our smart contract had multiple errors, so we decided to discontinue the project and create a new token. We have sent multiple issues to this tokenbase, but we figured it would be easier to just update our old smart contract address. 

Twitter: https://www.twitter.com/eDashCurrency
Twitter: https://www.twitter.com/EtherByte

EtherByte is the token we will be updating this smart contract to: 
0xBa4725e435A287E28783886FCbcB339436A6ae66
Symbol: EBX
Decimals: 2
Website: etherbyte.center

**Comment by freeatnet** [comment]
Thanks for the heads-up @FlamesEBX!

**Comment by FlamesEBX** [comment]
Thanks for reviewing. By when should we expect the contract to be updated?

**Comment by FlamesEBX** [comment]
Thanks for reviewing. By when should we expect the contract to be updated? @freeatnet

**Comment by freeatnet** [comment]
EDASH [lists](https://github.com/forkdelta/tokenbase/blob/4d831d607b45461043743389eab6cc643cff604c/tokens/0x01a28adc0edd796b570ec4da734e1aa809f6f1fc.yaml) edashcoin.org as the official website (imported from EtherDelta lists); however, edashcoin.org is not inaccessible (domain does not resolve).

@FlamesEBX Can you confirm your identity for the update by signing a personified message with eDASH.owner account (0xdf39696e79cccca610269e9a70e6836fae2b51f0)? Signing something like this would work:
```
I am https://github.com/FlamesEBX. I ask to replace EDASH 0x01a28adc0edd796b570ec4da734e1aa809f6f1fc with EBX 0xBa4725e435A287E28783886FCbcB339436A6ae66. This message is signed for the update request at https://github.com/forkdelta/tokenbase/issues/1407 on July 22, 2018 and is valid indefinitely.
```

Signed messages must be verifiable with https://etherscan.io/verifySig or https://www.myetherwallet.com/signmsg.html.
