### ISSUE TITLE
Add Driveholic Token (DRVH)

### ISSUE THREAD

**Issue by driveholic** [forkdelta/tokenbase#1408]
**Token address:**
https://etherscan.io/token/0x62d4c04644314f35868ba4c65cc27a77681de7a9

**Issuer's official website:**
https://airdrop.driveholic.com/

**Description:** 
Blockchain based, peer-to-peer, Social Marketplace for vehicles. 

We are an existing social-media platform for vehicle enthusiasts. Due to popular demand from our members, we are introducing a blockchain based peer to peer marketplace for vehicles. 

**A link to the official contract address confirmation:** 

https://airdrop.driveholic.com/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://airdropsforeos.com/portfolio-items/2018-08-01-driveholic-com/

https://eosdrops.io/driveholic

https://steemit.com/bitcoin/@sadum87/driveholic-a-peer-to-peer-market-based-on-blockchain-for-cars

https://cryptocoinpravda.com/driveholic-blockchain-berdasarkan-peer-to-peer-social-marketplace-untuk-kendaraan.html

https://steemit.com/ico/@iamsediii/driveholic-blockchain-based-peer-to-peer-social-marketplace-for-vehicles

Social media channels ; 

https://twitter.com/driveholic
https://www.instagram.com/driveholicsite/

**Comment by driveholic** [comment]
@freeatnet @Kryptoniq

**Comment by freeatnet** [comment]
Thank you for your request, @driveholic! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by driveholic** [comment]
@freeatnet hi, we know you are busy, we are airdropping the tokens shortly. Is there anyway we can make the listing process faster ?
