### ISSUE TITLE
Add request Adelphoi (ADL)

### ISSUE THREAD

**Issue by R0bini0** [forkdelta/tokenbase#1409]
Updated info for: #811

Token address:
0x660e71483785f66133548B10f6926dC332b06e61

Issuer's official website:
https://adel.io/

Description:

Adel is a technology incubator for blockchain innovation. Our community collaborates on ideas, and uses the AdelWiki™ to collectively create business plans. Members vote on projects and can become profit participates when they are launched. Expertise within the community brings mentoring, learning, and employment opportunities. Successful projects are re-invested for further growth, or issued as rewards to members. Adel is blockchain agnostic.

▲ adelphoi | Digital Currency for Adel Ecosystem
The Adelphoi (ADL) coin uses a comprehensive process of Idea2Project incubation, to fuel its own ecosystem.

+links:

A link to the official contract address confirmation:

https://adel.io
https://bitcointalk.org/index.php?topic=2135312
https://coinlib.io/coin/ADL/Adelphoi

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://bitcointalk.org/index.php?topic=2135312
http://medium.com/adel
https://www.youtube.com/channel/AdelEcosystem

https://medium.com/@gomedici/20-blockchain-focused-startup-accelerators-as-unconventional-as-the-technology-1717166e7da9
https://coinspot.io/world/rastet-kolichestvo-startap-akseleratorov-napravlennyh-na-blokchejn-proekty/
https://www.crypto-roadmaps.com/single-post/2018/05/22/New-2018-Roadmap-from-Adel-ADL
https://adel.io/news

**Comment by freeatnet** [comment]
Thank you for your request, @R0bini0! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by R0bini0** [comment]
@freeatnet when will $ADL be added?
We were already in the to be added list #811 and this is out follow up issue.
Thanks

**Comment by R0bini0** [comment]
Any update on listing?
