### ISSUE TITLE
Add Quadrant Assets (QDA)

### ISSUE THREAD

**Issue by QuadrantAssets** [forkdelta/tokenbase#1410]
Token address: 0x3da6C7db68f17E72CE153E485E453922f46B1d4a

Issuer's official website: https://quadrantassets.solutions

Description: Open BlockChain Ecosystem for more effective interaction with the ICO with funds, investors, experts, and traders.

Token: One of the main purposes of the QDA tokens – the democratization of the process
of selecting a ICO-projects for the creation and curation. In fact, they provide an
opportunity to vote for the startups, which will then be run and supervised at the
platform QuadrantAssets. An important advantage is the ability to exchange tokens
QDA tokens for manufactured startups on the platform.

When a new project launches presales, a certain amount of his token is placed on
the platform QuadrantAssets where QDA token holders can redeem your tokens
QDA tokens for start-UPS, on average, at the rate of 1:4. In other words, holders of
tokens QDA tokens get new projects with 75% discount. 

A link to the official contract address confirmation:

https://bitcointalk.org/index.php?topic=4484677.0
https://www.coingecko.com/en/ico/quadrant-assets
https://www.stateofthedapps.com/dapps/quadrant-assets

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://www.coingecko.com/en/ico/quadrant-assets
https://www.airdropsmob.com/quadrant-assets-qda
https://somethingdecent.co.uk/crypto/airdrop-alerts/airdrop-alert-quadrant-assets-are-giving-250-tokens-to-all-participants/

**Comment by freeatnet** [comment]
Thank you for your request, @QuadrantAssets! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Harisa96** [comment]
Please help us
