### ISSUE TITLE
QSHUCOIN　(new ERC 20 compliant)

### ISSUE THREAD

**Issue by qshucoin** [forkdelta/tokenbase#1411]
**Token address:**
0x28be79bd9ac609876b03f692d8d85278d8cbc2f3

**Issuer's official website:**
https://qshucoin.com

**Description:** 
We provide disaster relief support, tourism support, expand regional revitalization support projects from the Kyushu region, and broaden the range of support.

It is a token that will revitalize the region centered on disaster relief support and sightseeing support by dispatching Kyushu district of Japan. In order to cooperate closely with the area, we have a goal to take root as a community-based type aiming for the distribution of tokens. For sightseeing support, we will act to support local tourism vigorously by issuing free papers in the area. In disaster relief support, we will strengthen closer cooperation with the community so that we can provide prompt support in the event of a disaster.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x28be79bd9ac609876b03f692d8d85278d8cbc2f3

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. http://www.freedomfreedom.shop
2.http://www.maromeru.com/archives/9984431.html
3.http://www.maromeru.com/archives/10332099.html
4.https://alis.to/nuis/articles/anL4NQOz4q8r
5.https://radhia.blog.fc2.com/blog-entry-3809.html

**Comment by qshucoin** [comment]
I made a token remake. It is ERC 20 compliant. I would like to list it. Thank you for your consideration.
qshucoin@qshucoin.com

**Comment by freeatnet** [comment]
Thank you for your request, @qshucoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
