### ISSUE TITLE
GBCoin

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1412]
**Token address:** https://etherscan.io/address/0x638abd6f39ff141b2117e40c0b928659d76d2d08

**Issuer's official website:** https://www.gb-coin.io/

**Description:**  
GBC is a token and is 100% decentralized. Our vision is that GBC becomes a currency in the whole of Europe, but our main goal is to become a global currency.
We hope to approve our project and start a new business together.

**A link to the official contract address confirmation:**  https://ethplorer.io/address/0x638abd6f39ff141b2117e40c0b928659d76d2d08

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  gb.coin.info@gmail.com
2.  gb.coin.team@gmail.com

**Comment by GBCoin1** [comment]
The website https://www.gb-coin.io/ is still under construction and will be online shortly.

**Comment by GBCoin1** [comment]
When do I get an answer?
I need more

**Comment by freeatnet** [comment]
Requester account removed, it seems.
