### ISSUE TITLE
New Coin Listing issues

### ISSUE THREAD

**Issue by btcsmartads** [forkdelta/tokenbase#1413]
Hello,
My Name is Nico, I'm representing BTC Smart Ads. Our company is a marketing and promotional partner, trusted by ICOs.

One of the services we offer is a submission of our customer's coin/token to cryptocurrency exchanges. Our team would be glad to provide your platform with new customers too.

I wonder if listing of a coin/token on your exchange is free or it require additional payment? If it requires, please provide details and if it is possible to pay with tokens.

Thank you!
Looking forward to your reply.

**Comment by freeatnet** [comment]
@btcsmartads Hi there! Thanks for reaching out. There is no fee to add a token. To request a token to be added to the officially recognized tokens list, you can submit requests here: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Providing complete and accurate information will significantly improve response times.

If you have any other questions, don't hesitate to let me know.
