### ISSUE TITLE
Add BMN (Batman)

### ISSUE THREAD

**Issue by investors18** [forkdelta/tokenbase#1414]
**Token address:**
0xafb4fe1315504c92c3ed3657cd600712a8938aac

**Issuer's official website:**
https://www.batmantoken.com/

**Description:** 
answer : The product that will be created is an online store and The purpose of creating the Token is to make it a payment method in our shop

**A link to the official contract address confirmation:** 
answer : https://www.batmantoken.com/BMN_white_paper.pdf

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. link twitter : https://twitter.com/TokenBatman
2. link page Facebook : https://www.facebook.com/BatmanToken/
3. link group on telegram : https://t.me/BatmanToken_community

**Comment by freeatnet** [comment]
Thank you for your request, @investors18! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
