### ISSUE TITLE
Add CryptoSoul Token (SOUL)

### ISSUE THREAD

**Issue by cryptosoulgame** [forkdelta/tokenbase#1415]
Token address: 0xc4bD6Fb29C171D2035a87b630EbD78d2a1BD2f48

Issuer's official website: https://cryptosoul.io/

Description: 
CryptoSoul is the first battle royale mining game in the world. You can change game currency to CryptoSoul. Just Play. Win. Earn.

A link to the official contract address confirmation: https://ethplorer.io/address/0xc4bd6fb29c171d2035a87b630ebd78d2a1bd2f48

 inks to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://t.me/CryptoSoulGame
https://www.reddit.com/user/CryptoSoul_/
https://medium.com/@cryptosoul/the-first-screenshot-81d6ae60c1f8
https://vk.com/crypto_soul
https://www.facebook.com/CryptoSoulGame/?modal=composer
https://twitter.com/CryptoSoul_?lang=ru
https://www.instagram.com/cryptosoul_/?hl=ru
https://www.quora.com/profile/Crypto-Soul

personal contact: gamedeveloplab@gmail.com

**Comment by freeatnet** [comment]
Thank you for your request, @cryptosoulgame! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
