### ISSUE TITLE
Add Request: EOS DRAM (DRAM)

### ISSUE THREAD

**Issue by eosdram** [forkdelta/tokenbase#1416]
Token Address: 0x9955808b5023d5d61dB86f505a09922fEFBD00C0

Issuer's official website: https://github.com/eosdram/EOSDRAM

Description:
DRAM is the derivative equivalent of EOS RAM on the Ethereum blockchain.

Links to the official contract address confirmation:
https://etherscan.io/address/0x9955808b5023d5d61db86f505a09922fefbd00c0
https://github.com/eosdram/EOSDRAM/blob/master/README.md

Third-party link:
https://www.reddit.com/r/eos/comments/8xd5de/eos_dram_has_been_distributed_equivalent_for_eos/

Thank you

**Comment by freeatnet** [comment]
Thank you for your request, @eosdram! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
