### ISSUE TITLE
Add Qompass (QPSE)

### ISSUE THREAD

**Issue by Qompass** [forkdelta/tokenbase#1417]
Contract Address -   0x19d10b9d52c0d747b220849f1facc33f382d35ec 
Webpage  -  https://qompass.io/

Qompass is trying to build decentralize applications for  enabling financial institutions to connect to blockchain

- https://qompass.io/
- https://etherscan.io/address/0x19d10b9d52c0d747b220849f1facc33f382d35ec
- https://sirfel.com/qompass-ico-review/
-  https://www.trackico.io/ico/qompass/
- https://bitcoinist.com/qompass-announces-airdrop-ahead-ico-pre-sale-setting-stage-buying-frenzy-launch-revolutionary-blockchain-applications-api-unique-user-benefits/
- https://wiserico.com/ico/qompass
- https://www.youtube.com/watch?v=iypIJeMimv0
- https://www.youtube.com/watch?v=kADTRuWzJMk

**Comment by freeatnet** [comment]
Thank you for your request, @Qompass! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
