### ISSUE TITLE
Add Mammoth (MMT)

### ISSUE THREAD

**Issue by MammothHub** [forkdelta/tokenbase#1418]
Hello!

Please add MMT token (Mammoth platform) to the exchange listing.

Information is provided below:
Token name - Mammoth
Token symbol - MMT
Website: https://mammothblockchain.org/
Announcement: https://bitcointalk.org/index.php?topic=3325562.0
Block Explorer:
https://etherscan.io/address/0xeb01fe453348e95e02ec06ec20f0b701971976fc
Email: info@mammothblockchain.org

Description:
Mammoth is an alternative to traditional banking with a better way to
spend, save and share your money, fee-free and straight from your mobile.
Unlike other crypto payment solutions, Mammoth also provides alternative
financial services in local currencies.
Our digital local currency account is a gateway to widespread
cryptocurrency adoption, pairing it with access to mainstream financial
services and smart new features on a simple, user-friendly platform.

Thank You!

**Comment by freeatnet** [comment]
Thank you for your request, @MammothHub! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
