### ISSUE TITLE
Change Countinghouse Fund listing to official ticker

### ISSUE THREAD

**Issue by Mike-Countinghouse** [forkdelta/tokenbase#1419]
Hi guys. Can you please update the listing: https://forkdelta.github.io/#!/trade/0x799d214d7143b766cdd4979cd0280939288ba931-ETH

The official ticker of our token is CHT, not Countinghous as currently listed.

Thanks, 

Mike Pomery
www.countinghousefund.com

**Comment by freeatnet** [comment]
@Mike-Countinghouse The UI displays the full name of the token when trading a token that is not officially recognized (by contract address). If you would like to add your token, please submit a request here: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md.

Thanks!
