### ISSUE TITLE
List token request BlackGarlic (BGL) 

### ISSUE THREAD

**Issue by blackgarlicbgl** [forkdelta/tokenbase#142]
BlackGarlic token 
1. Name : BlackGarlic
2. Token name : BGL
3. website : www.blackgarlic.io
4. Twitter : https://twitter.com/BlackgarlicB
5. Announcement : https://bitcointalk.org/index.php?topic=2864137.0
6. Contract address: 0x5FB05ffFe4Be327aB88DAcD6EE61E60dDC8958aE
Symbol: BGL
Full Name: BlackGarlic
Decimals: 18
Type: ERC20
Thank you
7. Black Garlic (BGL) is the token base on smart contract ERC20 use Blockchain technology to solve problem in agriculture sector. It allows farmers to sell better prices throughout the supply chain, while giving consumers trace exactly where produce they buy comes from.

**Comment by Kryptoniq** [comment]
Verified 0x5FB05ffFe4Be327aB88DAcD6EE61E60dDC8958aE.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
