### ISSUE TITLE
May I ask you something? 

### ISSUE THREAD

**Issue by mikugajapan777** [forkdelta/tokenbase#1420]
Mail | kyvalion@mikuga.co.jp
Name of the token | Kyvalion
Symbol of the token | KTC
Precision (decimals) | 8
Token address | 0x60DaEC030A5B76bfD4aAA6C0b2bf6d4b81C4a34E
Website of the token | https://kyvalion.io/

The Kyvalion Project
World`s First State-of-the-art Pratform
combining Bitcoin and Ethereum.

URL : https://kyvalion.io/
telegram : https://t.me/kyvalion_official
Facebook : https://www.facebook.com/mikuga.japan1/

Kyvalion is a previously unheard of revolutionary project
combining blockchain technology with AI.

A Cryptocurrency issuing platform with a focus on creating a well-balanced societal trade of 
value and improved societal interchange.

Kyvalion will Enrich Your Life in three ways.
1.Implementation of Rich Unsurpassed AI Which Understands the Human Condition
2.Creating the Possibility of the Future with the Fusion of BlockChain and AI
3.Even with the Astronomical Amount of Data in Our Society, AI will Support You

Automatic Approval and Execution of Contracts / Smart Contract Technology

Kyvallion Provides Transparent and Sound Data Analysis in three ways.
1.Program Based Automatic Contracting and Approval Functionality
2.Your Intentions Carried Out Faithfully with Smart Contracts
3.Security Exceeding that of Ethereum

Now the internet has become an indispensable part of society's infrastructure just as 
important as water or electricity. The internet has changed our society completely enriching 
and giving convenience to our daily lives. In addition, with the creation of blockchain and AI these two technologies are going to further change our lives. We have created Kyvalion, a new revolutionary social platform with the fusion of these two technologies. With the spread of Kyvalion throughout the world, not only will it bring convenience to peoples lives, we believe it will be the catalyst for melding of the goodwill of people leading to a better society as a whole. A revolutionary change came 
with the birth of the internet. Just as we look forward to seeing much more vast changes 
with you in the future, please look forward to the bright future we are creating with Kyvaliion.

**Comment by freeatnet** [comment]
@mikugajapan777 The title suggests you had a question, yet I couldn't find one in your post. Could you clarify, please?

**Comment by mikugajapan777** [comment]
dear　ForkDelta
