### ISSUE TITLE
Add Pointium (PNT)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1421]
**Token address:**
0xd009bfa851a31b08343a68d824107e2b813a0fb7

**Issuer's official website:**
https://www.pointium.org

**Description:** 

Being overwhelmed by the company's too many loyalty programs using points, we couldn't make good use of them. This resulted in direct asset damage to the users, and a poorly performed loyalty programs & an increase in the liabilities to the businesses. Pointium solves these current problems with a block-chain technology. With the lowest transaction fee and the safest way, Pointium integrates the points into Pointium tokens (PNT), and delivers the loyalty programs to the users

**A link to the official contract address confirmation:** 

https://medium.com/@POINTIUM_ICO/how-to-add-pnt-in-your-myetherwallet-31f5b6aa882f

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=3129448.0
2. https://bitcoinexchangeguide.com/pointium-ico-pnt-token/
3. https://wheretoinvest.money/pointium-ico-review/
4. https://en.coinjinja.com/ico/pointium
5. https://www.trackico.io/ico/pointium/

**Comment by freeatnet** [comment]
Thank you for your request, @pointium! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
