### ISSUE TITLE
Please Add New Token (Lawn)

### ISSUE THREAD

**Issue by comoxvalleylawncares** [forkdelta/tokenbase#1422]
Smart Contract: 0x1c73c298928ea77165330fe796c1f41a804d8d0b

Website: http://www.comoxvalleylawncare.com/

Thank you and please consider listing LawnToken under symbol (Lawn)

We are planing on increasing the speed and availability of cryptocurrency in the market.  The company strives to make its crypto available to everyone globally increasing the processing times of various cryptos on the market to ensure a fast transaction time.  The token issuer plans on expanding existing crypto mining operations that will increase the companies holdings as well proving a faster block time for future transactions.  The purpose of the token will be to speed up the current slow cryptocurrency market.

https://etherscan.io/address/0x1c73c298928ea77165330fe796c1f41a804d8d0b

Third Party Review Listings

1.https://www.icoexaminer.com/community/threads/comox-valley-lawncare-lawn-ico.965/
2.https://bitcointalk.org/index.php?topic=3491927.0
3.https://forum.bitcoin.com/viewtopic.php?t=79656&p=169889#p169889

**Comment by freeatnet** [comment]
See #1345.
