### ISSUE TITLE
Add Bastonet (BSN)

### ISSUE THREAD

**Issue by robsonmani** [forkdelta/tokenbase#1423]
Hello,

we are members of the fork delta community. we would like to list the bastonet project token

token name: Bastonet
Symbol: BSN
contract address: https://etherscan.io/token/0xbED6DaB1d94df80fF2517aC22a1217513167fD13

thanks.

**Comment by freeatnet** [comment]
Thank you for your request, @! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- **Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md)** and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by gmuchiri2002** [comment]
Hello, What happened to the listing of Bastonet? we are waiting.... The coin has alot of potential
