### ISSUE TITLE
Add QIUToken (QIU)

### ISSUE THREAD

**Issue by qiulot** [forkdelta/tokenbase#1424]
Hey,Guys:
Our QIUToken is erc20 token that supports users make predictions for football match in our MobileApp and metamask Website. Our website is: www.qiulot.io
Would you please add our token into the forkdelta token list?

QIUToken address:  0x37f387fe48c9569500b514a1c7e1f6b04be8d421

**Comment by freeatnet** [comment]
Thank you for your request, @qiulot! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
