### ISSUE TITLE
Add Doves (Dove)

### ISSUE THREAD

**Issue by happypelican18** [forkdelta/tokenbase#1427]
**Token address:**
0x8a63a921b5d678B4a27DC81e44321923E297B4Cf

**Issuer's official website:**
http://www.Doves.Cash

**Description:** 
Doves is a cryptocurrency that works to help solve student finance through incentivized scholarship rewards.

The Doves Scholarship program distributes and awards 79.9% of the Doves token supply through smart contracts over a 25-year period to students who meet scholarship requirements. Students, parents, businesses, and individuals can all participate in the Doves cryptocurrency network

**A link to the official contract address confirmation:** 
https://www.doves.cash/contract.html

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=4639329.new#new
2. https://medium.com/@doves

**Comment by freeatnet** [comment]
Thank you for your request, @happypelican18! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
