### ISSUE TITLE
List token request DATOCOIN (DTCN)

### ISSUE THREAD

**Issue by Datocoin** [forkdelta/tokenbase#143]
Name : Datocoin
Token name : DTCN
website : www.datocoin.biz
Twitter : https://twitter.com/Datosphere_News
Announcement : https://bitcointalk.org/index.php?topic=2774737.0
Contract address: 0x450711d5da9f7cadb0e4d3472be550328b37bdda
Smart contract verification: https://drive.google.com/file/d/1B-nvpeaXRN74muVvnK1uDFPCoh-HRL2Y/view
Symbol: DTCN
Full Name: Datocoin
Decimals: 4
Type: ERC20

Description:
DATOCOIN will create a revolution in payment solutions for social networks
and online entertainment. Datocoin works under the concept of "
multiconnected marketing " a series of decentralized online platforms where
you can  bet on your favorite team, play on online casinos, exchange
cryptocurrencies in our Exchange, exchange assets and services in our
Marketplace, we are also developing the BLOCK-U, an Online University where
we will teach Blockchain programming, creation of ICO, fundamental and
technical analysis, this set of decentralized platforms will be called
Datosphere and the official circulation token will be the DATOCOIN (DTCN).

**Comment by Kryptoniq** [comment]
1. Provide an official  link verifying your contract address.
2. Your description happens to be the same as Block Garlic.

**Comment by Datocoin** [comment]
Hi dear friend!

https://etherscan.io/token/0x450711d5da9f7cadb0e4d3472be550328b37bdda

DATOCOIN will create a revolution in payment solutions for social networks
and online entertainment. Datocoin works under the concept of "
multiconnected marketing " a series of decentralized online platforms where
you can  bet on your favorite team, play on online casinos, exchange
cryptocurrencies in our Exchange, exchange assets and services in our
Marketplace, we are also developing the BLOCK-U, an Online University where
we will teach Blockchain programming, creation of ICO, fundamental and
technical analysis, this set of decentralized platforms will be called
Datosphere and the official circulation token will be the DATOCOIN (DTCN)

**Comment by Kryptoniq** [comment]
Provide a link that verifies your contract address. E.g on your website or whitepaper.

**Comment by Datocoin** [comment]
https://datocoin.io/home

whitepaper:
https://drive.google.com/file/d/1B-nvpeaXRN74muVvnK1uDFPCoh-HRL2Y/view

**Comment by Kryptoniq** [comment]
Your original post has been updated with the whole information you provided.

**Comment by Kryptoniq** [comment]
Verified 0x450711d5da9f7cadb0e4d3472be550328b37bdda.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190

**Comment by Datocoin** [comment]
Hello, i have a question.... URL API for coinmarketcap.... i want see volume on 24 h

**Comment by Datocoin** [comment]
guys? what is url api for coinmarketcap? please help me

**Comment by Kryptoniq** [comment]
@Datocoin the API url is api.forkdelta.com.

**Comment by Datocoin** [comment]
404 not found

**Comment by Datocoin** [comment]
https://api.forkdelta.com/returnTicker
Thanks
