### ISSUE TITLE
Token Nitecoinpay (NTICP)

### ISSUE THREAD

**Issue by Nitecoinpay** [forkdelta/tokenbase#1430]
**Token address:**
0x798f81c00c0a1122370debc1e4df9567f3893e11

**Issuer's official website:**
https://www.nitecoin-pay.club/

**Description:** 

Nitecoin-pay  Is a new digital currency founded in late April 2018 using the Smart Contract ERC20
This coin was founded by the Team Nitecoinpay.
 This currency came to solve several problems, including:

- Add e-currency transfers and link e-banks with the entire digital currency community and enable them to convert their assets from Bitcoin-Etherum-Neo-Dash ... through our future platform through the main currency (Nitecoinpay). Get the digital currency. Our encryption system involves currency trading between all these currencies and electronic banks and creates a new kind of relationships and value added.

- The possibility of withdrawing money through the application of (Nitecin) to electronic banks such as   
 (Paypal .skrill.payza.payeer.advcash.perfect-money.cihbank morroco.visacard...)

- Buy from electronic stores such as (Ebay .banggod.ali baba.gearbest.igraal.trivago.sonny.samsung...) in the official currency Nitecoinpay

- Visa Nitecoin cards to withdraw funds

In addition to the many advantages we can not disclose under the non-disclosure of agreements

**A link to the official contract address confirmation:** 

https://etherscan.io/token/0x798f81c00c0a1122370debc1e4df9567f3893e11
https://www.rebellious.io/explorer/address/0x798f81c00c0a1122370debc1e4df9567f3893e11
https://ethplorer.io/address/0x798f81c00c0a1122370debc1e4df9567f3893e11

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=3694018.msg36821810#msg36821810
2.http://www.moowx.com/2018/05/nitecoinpay-ico-airdrop.html

**Comment by freeatnet** [comment]
Thank you for your request, @Nitecoinpay! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
