### ISSUE TITLE
Add LaszloCoin (LZL)

### ISSUE THREAD

**Issue by canibalbranco** [forkdelta/tokenbase#1433]
**Token address:**
 0x1C623FDa1631149e57a8FBffa2510B6274B542a5

**Issuer's official website:**
https://laszlocoin.org/

**Description:** 
Laszlo Coin. The pizza's coin!
Laszlo coin was created to honor the first crypto coins transaction in the world.

**A link to the official contract address confirmation:** 

https://laszlocoin.org/laszlo1.html

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=4146998
2. https://bitcointalk.org/index.php?topic=4150936

**Comment by freeatnet** [comment]
Thank you for your request, @canibalbranco! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
