### ISSUE TITLE
Eurno (ENO) Listing

### ISSUE THREAD

**Issue by sosolean** [forkdelta/tokenbase#1434]
Could you please look at our info and list our token our free airdrop will commence 15/07/2018

https://etherscan.io/address/eurnotoken.eth

Name : Eurno
Symbol : ENO
Contract Address: 0xcdc4423531df5f3f87d1ff54047c769fe488c49f
Decimals : 8
Description : Eurno is a directly democratic project which will use profits generated to complete charitable ventures which have been voted upon by the Eurno token holding community. Unlike traditional charities the Eurno project will use blockchain technology to ensure total transparency.

A link to the official contract address confirmation: https://www.eurno.org/

Website : https://www.eurno.org/
Whitepaper: https://eurno.org/wp-content/uploads/2018/06/Eurno-Whitepaper-1.0-English.pdf
Telegram: https://t.me/Eurno
Medium: https://medium.com/@eurno
Reddit: https://steemit.com/@eurno
Steemit: https://steemit.com/@eurno
Github: https://github.com/Eurno
Bitcointalk: https://bitcointalk.org/index.php?topic=4466190.0
Official email: admin@eurno.org

3rd party reviews

https://icoholder.com/en/eurno-22467

https://investfuture.ru/ico/eurno

Thanking you for your time

Nadim
Eurno

**Comment by freeatnet** [comment]
Thank you for your request, @sosolean! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by sosolean** [comment]
Added the 2nd 3rd party review
