### ISSUE TITLE
Add GBCoin (GBC)

### ISSUE THREAD

**Issue by GBCoin1** [forkdelta/tokenbase#1437]
**Token address:**

0x638abd6f39ff141b2117e40c0b928659d76d2d08
--

**Issuer's official website:**
https://gb-coin.io/

**Description:** 
 Our vision for GBCoin is to launch an excellent currency that will become globally recognized.

**A link to the official contract address confirmation:**  https://ethplorer.io/address/0x638abd6f39ff141b2117e40c0b928659d76d2d08
https://etherscan.io/token/0x638abd6f39ff141b2117e40c0b928659d76d2d08?a=0xf6c0c18977182fda87d71b0294e2e468a0da9cb4

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.   https://gb-coin.io/
2.   https://bitcointalk.org/ Coming soon

Greetings and thanks for your time.

**Comment by freeatnet** [comment]
Thank you for your request, @GBCoin1! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by GBCoin1** [comment]
Hello, I would ask for help. I wonder what exactly is missing in order to
add tokens to ForkDelta?

https://github.com/GBCoin1

Tnx

2018-07-12 11:08 GMT+02:00 Arseniy Ivanov <notifications@github.com>:
