### ISSUE TITLE
Request to add token (BLACK)

### ISSUE THREAD

**Issue by insvnx** [forkdelta/tokenbase#144]
Hi, Can you please add my token to your exchange?

Name:         Bitcoin Black
Symbol:       BLACK
Decimals:    18
Contract:     0xf7ae0daa230bf3fb3c0e5e01e7a6e0a142c6cf7e
Description: Bitcoin Black is a next generation crypto currency. It is a tradeable ERC20 token
  that resides on the Ethereum blockchain.
URL:             https://btcblack.org
Twitter:          https://twitter.com/btcblackdotorg
Github:          https://github.com/btcblack/

Thanks!

[0xf7ae0daa230bf3fb3c0e5e01e7a6e0a142c6cf7e.yaml.txt](https://github.com/forkdelta/tokenbase/files/1740442/0xf7ae0daa230bf3fb3c0e5e01e7a6e0a142c6cf7e.yaml.txt)

**Comment by Kryptoniq** [comment]
Provide a link to a third-party review or discussion of the token.

**Comment by Kryptoniq** [comment]
#147 duplicate.
