### ISSUE TITLE
Add Nolly Coin (NOLLY)

### ISSUE THREAD

**Issue by cab8021** [forkdelta/tokenbase#1440]
Contract address: 0xb69096a89389638518725adfcf279f3f82efa2de

Issuer's official website: https://nollycoin.com

Description: A Decentralized Ecosystem For Movie Distribution and consumption In Developing Countries.

Official contract address confirmation: https://ico.nollycoin.com/Nollycoin-White-Paper.pdf
Contained within the official whitepaper

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://bitcointalk.org/index.php?topic=2995439.60
https://medium.com/@NOLLYCOIN
https://hype.codes/top-3-ongoing-ico-28-mar-4-apr-according-our-readers

**Comment by freeatnet** [comment]
Thank you for your request, @cab8021 ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
