### ISSUE TITLE
Add Bitstarti (BTS)

### ISSUE THREAD

**Issue by bitstarti** [forkdelta/tokenbase#1441]
**Token address:** https://etherscan.io/token/0x0f81a937ce3e7bb95edb14b81951e93e68fcda50

**Issuer's official website:** https://bitstarti.org/

**Description:** Since the technology came along, the processes have never been the same. However, as the years go by, technology is also improving and becoming increasingly complex and complete. It is from it that the cryptocurrencies emerged.

**A link to the official contract address confirmation:** https://bitstarti.org/ (In community section)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://medium.com/bitstarti
2. https://bitcointalk.org/index.php?topic=2537664.0

**Comment by freeatnet** [comment]
Thank you for your request, @bitstarti! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
