### ISSUE TITLE
LondonCoin listing request

### ISSUE THREAD

**Issue by brianbkkim** [forkdelta/tokenbase#1442]
**Token address:**
0x50C1F6d905dd635D905aA37285216073855c6B8E

**Issuer's official website:**
www.londoncoin.io

**Description:** 
LondonCoin is issued by SSEN Corporation(www.ssencorp.com), which is the only value accumulating coin with fingerprint authenticated cold storage wallet.  LondonCoin will be used as a global payment when the 4th generation core is developed.

**A link to the official contract address confirmation:** 
http://londoncoin.io/?page_id=382

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://steemit.com/london/@ssen/londoncoin-ico
[LondonCoin presentation_2018 April_v1.4.pdf](https://github.com/forkdelta/tokenbase/files/2191397/LondonCoin.presentation_2018.April_v1.4.pdf)

2.https://steemit.com/advanced/@ssen/the-4th-generation-consensus-core-londoncoin-presentation

**Comment by freeatnet** [comment]
Thank you for your request, @brianbkkim! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by brianbkkim** [comment]
p {margin-top:0px;margin-bottom:0px;} 


	
	
Thank you Arseniy, and I hope we both succeed in the cryptocurrency business.Best Regards,BK Brian Kim--------- 원본 메일 ---------보낸사람: Arseniy Ivanov <notifications@github.com>받는사람 : forkdelta/tokenbase <tokenbase@noreply.github.com>참조 : brianbkkim <kolsii@hanmail.net>,Mention <mention@noreply.github.com>날짜: 2018년 7월 13일 금요일, 17시 16분 56초 +0900제목: Re: [forkdelta/tokenbase] LondonCoin listing request (#1442)

	
Thank you for your request, @brianbkkim! We'll review it as soon as we can. In the meanwhile, here's what to expect:

Please make sure your request follows the required format and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
Keep an eye on this issue. We will post all follow-up and additional questions here.
You will receive a notification once your request has been reviewed for completeness and accepted.
You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:

Adding a token to ForkDelta Tokenbase is free, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
We will not send or accept email or direct messages related to token addition requests.


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


		
p  {font-size:10pt ! important;font-family:돋움,'굴림',gulim,tahoma,sans-serif ! important;}

BK Brian KimCEOSsen Corporationwww.ssencorp.comwww.londoncoin.ioPhone: +82 010 5236 4680
