### ISSUE TITLE
Looking to get token listed

### ISSUE THREAD

**Issue by icroatt** [forkdelta/tokenbase#145]
Hello,

We are looking to get our token listed on forkdelta as we just successfully completed our ICO.

LION token

coinlion.com

Contract address: 0x2167fb82309cf76513e83b25123f8b0559d6b48f

Article about us for example: https://www.itsagadget.com/2018/02/coinlion-platform.html

**Comment by icroatt** [comment]
Symbol: LION
Decimals: 18
Name: Lion Coin

**Comment by icroatt** [comment]
Description: Lion Coin is an exchange based token, the ICO was performed to raise money to build both an exchange, research portal, and portfolio management system. More can be found on our website.

**Comment by Kryptoniq** [comment]
Verified 0x2167fb82309cf76513e83b25123f8b0559d6b48f.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
