### ISSUE TITLE
Adding DeltaChain Token (DELTA)

### ISSUE THREAD

**Issue by tonytone7** [forkdelta/tokenbase#1450]
**Token address:** 0xDE1E0AE6101b46520cF66fDC0B1059c5cC3d106c

**Issuer's official website:** https://deltachain.tech

**Description:** DeltaChain inherits and develops the Ethereum technology platform, with open source P2P accelerates all transactions quickly, minimises risk, enhances high security, and does not involve any third parties. DeltaChain has a clearly transparent development roadmap. All DeltaChain wallet versions will be fully up to date where customers can secure on wallets or trade seamlessly on the world exchange.

OFFICIAL WEBSITE : https://deltachain.tech
TELEGRAM GROUP  : https://t.me/deltachaingroup
TWITTER  : https://twitter.com/deltachain
FACEBOOK : https://facebook.com/deltachain
MEDIUM : https://medium.com/@deltachain
MAIL : team@deltachain.tech/ admin@deltachain.tech

**A link to the official contract address confirmation:** <https://etherscan.io/token/0xde1e0ae6101b46520cf66fdc0b1059c5cc3d106c>

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=4767803
2.https://icoholder.com/en/deltachain-23172
3. https://medium.com/@deltachain

**Comment by freeatnet** [comment]
Thank you for your request, @tonytone7! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by tonytone7** [comment]
Thank you Forkdelta
