### ISSUE TITLE
please add myfichain 

### ISSUE THREAD

**Issue by saveall4** [forkdelta/tokenbase#1454]
**Token address:**
 myfichain

**Issuer's official website:**
https://www.myfichain.com/

**Description:** 
MyFIchain is a global payment system built on the ethereum network , MyFichain is a low volatility cryptocurrency that brings sweeping changes to current payment systems. We connected the financial and blockchain worlds to create a unique solution to solve critical crypto-challenges. 

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x0dfdd839cde95dabf56f0b5c5698e0159138930d

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by freeatnet** [comment]
Hey @saveall4! Thanks for your request. There's already an existing request for MyFiChain at #1384. If you feel you can contribute information, please do so there. Thanks!
