### ISSUE TITLE
Fortecoin FOTC

### ISSUE THREAD

**Issue by kelvinlala** [forkdelta/tokenbase#1455]
**Token address:**
0xd9a1fe8b4d6de4f41c8a1b6ad3b6457916e546b4

**Issuer's official website:**
www.fortecoinbiz.com

**Description:** 
Fortecoin FOTC is a travellers token, Fortecoin is has an e-commerce site where Merchants globally can transact, Fortecoin is also a pension token.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xd9a1fe8b4d6de4f41c8a1b6ad3b6457916e546b4

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.
https://www.openpr.com/news/1120755.html

2.http://www.pressbox.co.uk/cgi-bin/links/page.cgi?g=2171554.html

**Comment by freeatnet** [comment]
Thank you for your request, @kelvinlala! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by kelvinlala** [comment]
Thank you for accepting our project.
