### ISSUE TITLE
Add ZeroChain Network (ZCHAIN)

### ISSUE THREAD

**Issue by ZChainN1** [forkdelta/tokenbase#1456]
Contract address: 0x4c7bc4d7c5e2ed2f14f8722b7ded6c615d578c1e

Issuer's official website: https://ZeroChain.network/

Official contract address confirmation (MUST be linked from official website): https://etherscan.io/token/0x4c7bc4d7c5e2ed2f14f8722b7ded6c615d578c1e

https://bitcointalk.org/index.php?topic=4576831.msg41268481#msg41268481

Description:
what is ZeroChain Network?

ZeroChain Network (ZCHAIN) is an Airdrop Platform,
The ZCHAIN platform will also allow companies to create Airdrop campaigns to gain new customers and reward existing customers, using ZCHAIN tokens. This will be facilitated via the ZCHAIN web and mobile apps.

Contact&information
Official site: https://ZeroChain.network/
Telegram Chat: https://t.me/joinchat/FmrvLkboky1QHLmBHOpupg
Telegram Channel: https://t.me/joinchat/AAAAAFNRxQzU7nM4KIoVxg
Twitter: https://twitter.com/ZchainN
GitHub: https://gist.github.com/ZChainN1
Ico info: https://www.coinschedule.com/ico/zerochain-network
icoholder.com/en/zchain-22579

Contact: Support@zerochain.network
CEO: jhontp@zerochain.network

**Comment by freeatnet** [comment]
Thank you for your request, @ZChainN1! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
