### ISSUE TITLE
Add Gnome (LEN)

### ISSUE THREAD

**Issue by gnomepay** [forkdelta/tokenbase#1457]
**Token address:**
0x9375f11e963d4177b2205c57f67cfcae14687ab9

**Issuer's official website:**
www.gnomepay.com

**Telegram channel:**
https://t.me/gnomepay

**Email:** 
GeorgeLee@gnomepay.com

**Description:**
Cryptocurrency  mobile-friendly payment application

**A link to the official contract address confirmation:**
https://etherscan.io/token/0x9375f11e963d4177b2205c57f67cfcae14687ab9

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://bitcointalk.org/index.php?topic=4518430.0
https://twitter.com/gnomepay

Thank You!

**Comment by freeatnet** [comment]
Thank you for your request, @gnomepay! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
