### ISSUE TITLE
CONNCT [CNCT] Listing 

### ISSUE THREAD

**Issue by Connecttoken** [forkdelta/tokenbase#1458]
**Token address:**
0x54a9ed327f2614316914c3f3a782a77d0aa47aee

**Issuer's official website:**
https://www.connecttokenlimited.com
also we have a new layout and platform in development

**Description:** 

To provide a platform what will allow people to advertise projects and allow investors to fund them all secured with escrow agreements.
token will be able to be used as a form of funding and as a donation to select charities with all donated tokens being burnt.

**A link to the official contract address confirmation:**  

https://etherscan.io/token/0x54a9ed327f2614316914c3f3a782a77d0aa47aee
link is on our website under token menu.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. We have had a couple of mentions but they have been media comments but through twitter and one through email from a company saying about a possibility of us working with each other but is still in confidentiality so can not reveal anymore than what I have
2

**Comment by freeatnet** [comment]
Thank you for your request, @Connecttoken! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
