### ISSUE TITLE
SimpleLife

### ISSUE THREAD

**Issue by mgkao** [forkdelta/tokenbase#1459]
name:SimpleLife (SLT)

about:We hope people could use blockchain technology easily in their daily life.

Token address:0xd6d62024D82B5bF4fe4A9E214991743d543F1673

Issuer's official website:http://simplelifetoken.com

Description:

A link to the official contract address confirmation:

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.https://etherscan.io/token/0xd6d62024d82b5bf4fe4a9e214991743d543f1673
2.https://bitcointalk.org/index.php?topic=4576777.0
3.https://t.me/simplelife_group

**Comment by freeatnet** [comment]
Thank you for your request, @mgkao! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by mgkao** [comment]
Thank you For your comment.
As you can see in our contract address, There are a lot accounts transfer from each other rightnow.
We think people like our project and will love to see it been list in this exchange.
Thank you for notice us.
