### ISSUE TITLE
Listing request - Bitlong BTL

### ISSUE THREAD

**Issue by btltoken** [forkdelta/tokenbase#146]
Hello! Fork Delta / EtherDelta we would be very pleased if you add our token on exchange.

Token Name: Bitlong BTL
Symbol: BTL

description：: Bitlong BTL is a project of the digital era with the evolutionary blockchain technology and a far-reaching mission, changing your life for the better. Bitlong BTL is a Future Digital Cash,a Payment Way You Can Spend Anytime Anywhere. Bitlong BTL is a project will develop for ten years. We will update twitter every day.It will be listed on more and more international Exchanges.

WEBSITE:
http://www.btltoken.com

Twitter:
https://twitter.com/btltoken   followers. 8000.

EXPLORER:
https://etherscan.io/token/0x5ecd84482176db90bb741ddc8c2f9ccc290e29ce

CONTRACT ADDRESS:
https://etherscan.io/address/0x5ecd84482176db90bb741ddc8c2f9ccc290e29ce

FORUM
https://bitcointalk.org/index.php?topic=2867052.0

Team:
https://etherscan.io/address/0xd4e89296f3041848ab2ce270da4fffbb04f3ec86

Link to download a 28x28png icon logo:
http://btltoken.com/btl/btl.png

Official Contact Email Address:
admin@btltoken.com

Link to blog (optional):
https://medium.com/@btltoken

Link to reddit (optional):
https://www.reddit.com/user/btltokencom

TOTAL COINS:
1,000,000,000 BTL

Thank you so much for your time
Have a nice day

Best regards

BTL DEVS

**Comment by btltoken** [comment]
+---
+addr: '0x5ecd84482176db90bb741ddc8c2f9ccc290e29ce'
+decimals: 6
+description: >-
+  "Bitlong BTL is a project of the digital era with the evolutionary blockchain technology and a far-reaching mission, changing your life for the better. Bitlong BTL is a Future Digital Cash,a Payment Way You Can Spend Anytime Anywhere. Bitlong BTL is a great project will develop for ten years. We will update twitter every day.It will be listed on more and more international Exchanges."
+links:
+- Bitcointalk: https://bitcointalk.org/index.php?topic=2867052.0
+- Github: https://github.com/btltoken
+- Reddit: https://www.reddit.com/user/btltokencom
+- Twitter: https://twitter.com/btltoken
+- Website: http://www.btltoken.com/
+name: Bitlong
+symbol: BTL

**Comment by btltoken** [comment]
+---
+addr: '0x5ecd84482176db90bb741ddc8c2f9ccc290e29ce'
+decimals: 6
+description: >-
 "Bitlong BTL is a project of the digital era with the evolutionary blockchain technology and a far-reaching mission, changing your life for the better. Bitlong BTL is a Future Digital Cash,a Payment Way You Can Spend Anytime Anywhere. Bitlong BTL is a great project will develop for ten years. We will update twitter every day.It will be listed on more and more international Exchanges."
+links:
+- Bitcointalk: https://bitcointalk.org/index.php?topic=2867052.0
+- Github: https://github.com/btltoken
+- Reddit: https://www.reddit.com/user/btltokencom
+- Twitter: https://twitter.com/btltoken
+- Website: http://www.btltoken.com/
+name: Bitlong
+symbol: BTL

**Comment by btltoken** [comment]
I will change from EtherDelta to ForkDelta on my  website after
you list my token on Forkdelta. Thanks

**Comment by Kryptoniq** [comment]
Looks good. Verified 0x5ecd84482176db90bb741ddc8c2f9ccc290e29ce.

**Comment by btltoken** [comment]
Our team wish donate 1ETH , I need the ETH address.

**Comment by Kryptoniq** [comment]
You can find the donation address here https://forkdelta.github.io/about/#donate.
Thank you.

**Comment by JonathonDunford** [comment]
A donation would be greatly appreciated. We will get your token listed in the next 24 hours. Thanks :)

**Comment by btltoken** [comment]
https://etherscan.io/tx/0xfb78a62e9ec3b2793d84975c1562d04fb15c99737ad6f6ee0889718bd5e31c88   Thank you

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
