### ISSUE TITLE
FrontierCoin (FRONT) Request

### ISSUE THREAD

**Issue by arinomuri** [forkdelta/tokenbase#1460]
**Token address:**
0xc8a074de1c6bf01a75cd29892c91b6c354200f75

**Issuer's official website:**
https://secret-everglades-97715.herokuapp.com/

**Description:**
FRONT is a base pair for tokenized securities on the Ethereum chain. The first of it's kind enabling tokenized securities on ethereum.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xc8a074de1c6bf01a75cd29892c91b6c354200f75#readContract

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1.  https://twitter.com/frontier_coin
2. https://t.me/frontiercoin
Note: Honestly just check the Telegram, lots of great folks involved there

**Comment by freeatnet** [comment]
Thank you for your request, @arinomuri! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
