### ISSUE TITLE
Request listing OZT (Flashmoni.io)

### ISSUE THREAD

**Issue by nolex25** [forkdelta/tokenbase#1461]
**Token address:**
0x9aa9bab278c0ed84c104915bce9b5a9c1b96c4bf

**Issuer's official website:**
www.flashmoni.io

**Description:** 
The goal is to build a financial ecosystem to fight against bank exclusion and offer an alternative to the existing banking system. Flashmoni aims and not limited to create payment card,ATM, data marketplace, bank, insurance, payment system. The roadmap and the information are available in the whitepaper (https://www.flashmoni.io/documents/whitepaper.pdf) and on https://blog.flashmoni.io

**A link to the official contract address confirmation:** 
The official website of flahsmoni is https://flashmoni.io

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://twitter.com/flashmoniltd
2. https://www.reddit.com/user/flashmoni_ltd
3. https://blog.flashmoni.io

**Comment by freeatnet** [comment]
Thank you for your request, @nolex25! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Sigri44** [comment]
> 
> 
> **Token address:**
> 0x9aa9bab278c0ed84c104915bce9b5a9c1b96c4bf
> 
> **Issuer's official website:**
> [www.flashmoni.io](http://www.flashmoni.io)
> 
> **Description:**
> The goal is to build a financial ecosystem to fight against bank exclusion and offer an alternative to the existing banking system. Flashmoni aims and not limited to create payment card,ATM, data marketplace, bank, insurance, payment system. The roadmap and the information are available in the whitepaper (https://www.flashmoni.io/documents/whitepaper.pdf) and on https://blog.flashmoni.io
> 
> **A link to the official contract address confirmation:**
> The official website of flahsmoni is https://flashmoni.io
> 
> **At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
> 
>     1. https://twitter.com/flashmoniltd
> 
>     2. https://www.reddit.com/user/flashmoni_ltd
> 
>     3. https://blog.flashmoni.io

Hello !

The whitepaper link is down ! Have you an another link to see this ?

Thank you.
