### ISSUE TITLE
Zenswap Network Token Listing Application

### ISSUE THREAD

**Issue by zenswapnetwork** [forkdelta/tokenbase#1463]
Token address:
0xE95990825AAB1a7f0Af4cc648f76a3Bcc99F25B2

Issuer's official website:
www.zenswapnetwork.info/

Description: 
Zenswap Network offers a new and practical cryptosphere for coin and token swap, cryptocurrency portfolio management, and crypto space reputation scores. ZNT is an ERC20 utility token that will be used as a discount for swap transactions, premium services and for casting reputation score/karma.

A link to the official contract address confirmation: 
It is published on the website. www.zenswapnetwork.info/
and also on Twitter. https://twitter.com/ZenswapNetwork/status/1018838012027797504

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://medium.com/@zenswapnetwork
https://www.minds.com/zenswapnetwork
https://www.reddit.com/r/ZenswapNetwork/
https://twitter.com/ZenswapNetwork
https://t.me/ZenswapNetwork
https://t.me/ZenswapNetworkChat
https://bitcointalk.org/index.php?topic=4688090

**Comment by freeatnet** [comment]
Thank you for your request, @zenswapnetwork! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by dann2017** [comment]
Looking forward to the official listing announcement of the token. 😀

**Comment by minhkhang7999** [comment]
Great! I follow you!
