### ISSUE TITLE
Add G-Mbel (GMBEL)

### ISSUE THREAD

**Issue by gmbelofficial** [forkdelta/tokenbase#1464]
**Token address:** 0xF3cFBCA4e083B1418F89545754C7dA90d2418B10

**Issuer's official website:** https://www.g-mbel.info/

**Description:** GMBEL is a project to help beginner traders to do trading activities with little capital. In order for beginner traders to gain new experience and low risk. Due to the rapid development of cryptocurrency and the highly fluctuating price of cryptocurrencies, it makes beginners traders face up to the risks they have never faced. To reduce such risks, we are here to create this project.

**A link to the official contract address confirmation:** https://www.g-mbel.info/#airdrop

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.facebook.com/GMbelOfficial
2. https://twitter.com/gmbel_official
3. https://t.me/gmbelofficial
4. https://medium.com/@GMbelOfficial

**Comment by gmbelofficial** [comment]
this is my pull request https://github.com/forkdelta/tokenbase/pull/1453

**Comment by freeatnet** [comment]
Thank you for your request, @gmbelofficial! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
