### ISSUE TITLE
Blockbid Token (BID)

### ISSUE THREAD

**Issue by scrypte** [forkdelta/tokenbase#1465]
**Token address:**
0xF1F64F6b8E17DD68c1DB10B0Eed3D2541A6c09AB

**Issuer's official website:**
Www.blockbid.io

**Description:** 
Token entitled holder to free trading on the Blockbid exchange 

**A link to the official contract address confirmation:** 

Scroll down website until you see it, www.blockbid.io

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.ccn.com/aussie-crypto-exchange-blockbid-partners-with-risk-management-giant-lexisnexis/

2. https://bitcoinexchangeguide.com/blockbid/

**Comment by freeatnet** [comment]
Thank you for your request, @scrypte! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by scrypte** [comment]
Hi, we have conducted a token swap.

Please update our contract name to Blockbid, and our number of decimals to 2. Our ticker code remains BID.

**Comment by scrypte** [comment]
Our new contract address is 0xdd5151da2ab25566e1d2a3c9a3e77396303f8a93

**Comment by scrypte** [comment]
Also please update Description: 
Utility token used by holders to access free trading on the Blockbid exchange
