### ISSUE TITLE
Add Pangea Arbitration Token (PAT)

### ISSUE THREAD

**Issue by ccmawo** [forkdelta/tokenbase#1466]
**Token address:**
0xbb1fa4fdeb3459733bf67ebc6f893003fa976a82

**Issuer's official website:**
https://bitnation.co
https://tse.bitnation.co (new token sale event website, will replace the old one soon)

**Description:** 
The Pangea Arbitration Token (XPAT) is an ERC20 compatible in-app token for the Pangea Jurisdiction. The XPAT token rewards good reputation and is issued on Pangea when Citizens accumulate non-tradable reputation tokens through creating a contract, successfully completing a contract or resolving a dispute attached to a contract. XPAT is an algorithmic reputation token, an arbitration currency based on performance rather than purchasing power, popularity or attention.

**A link to the official contract address confirmation:** 
https://bitnation.co/get-xpat/
https://tse.bitnation.co/getxpat/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.wired.com/2015/12/the-radical-politics-of-the-blockchain/
2. https://futurism.com/innovative-refugee-project-wins-major-award-for-its-blockchain-solution/
3. https://cointelegraph.com/news/bitnation-registers-first-refugees-on-the-blockchain
4. https://www.ccn.com/tag/bitnation/
5. yearly summary: https://steemit.com/bitnation/@bitnation/yearly-summary-2017-2018-the-most-productive-year-yet
6. In German http://www.faz.net/aktuell/feuilleton/debatten/die-digital-debatte/bitcoin-statt-bargeld-und-bitnation-statt-staat-regierung-14050237-p3.html
7. https://en.wikipedia.org/wiki/Bitnation
8. https://www.youtube.com/results?search_query=bitnation

**Comment by xsttx** [comment]
Yes, please!

**Comment by freeatnet** [comment]
Thank you for your request, @ccmawo! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
