### ISSUE TITLE
Request ToorCoin listing (TOOR)

### ISSUE THREAD

**Issue by mohammadkhalidtoor** [forkdelta/tokenbase#1467]
**Token address**: 0x8eb965ee9cCFBCE76c0a06264492c0afEfc2826d

**Issuer's official website**: https://toorcoin.com

**Description**: Toorcoin is an ERC-20 token facilitating specialized travel. Toorcoin’s mission is to become the number one specialized travel coin choice and a recognized brand within the travel industry. Toorcoin is meant for use within the Toorister platform, which will be a travel website providing amazing travel itineraries and city guides to top destinations of the world.

**A link to the official contract address confirmation**: https://toorcoin.com

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer**:
1. https://www.youtube.com/watch?v=TZNhlT6EJ3M&list=PL3A3xKUoQwGX1LYWUfIZASN5Jda3TlNd7&index=2
2. https://www.linkedin.com/pulse/toorcoin-1-coin-choice-specialized-travel-adeyinka-joshua/

**Comment by freeatnet** [comment]
Thank you for your request, @mohammadkhalidtoor! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
