### ISSUE TITLE
Add ETH.TOWN Token (ETIT)

### ISSUE THREAD

**Issue by ClapClap17** [forkdelta/tokenbase#1468]
**Token address:**
0x8fe19c447821b4cdcdd5012bca1b5469ca96d80d

**Issuer's official website:**
https://eth.town

**Description:**
ETH.TOWN is a new crypto gaming platform: collectibles, games, eco-system.
Game introduces an ETIT token, which is used for the gaming activities.

**A link to the official contract address confirmation:**
https://eth.town/
(click on "Your balance: X ETIT")

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://bitcoinexchangeguide.com/eth-town/
https://steemit.com/crypto-gaming/@am44/this-is-why-eth-town-will-be-the-leading-crypto-collectible
https://egamers.io/eth-town-the-new-must-in-crypto-gaming/
https://cryptocurrencyaus.com/2018/06/07/ethereum-erc721/

**Comment by freeatnet** [comment]
Thank you for your request, @ClapClap17! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
