### ISSUE TITLE
Bitball (BTB) Listing request 

### ISSUE THREAD

**Issue by BitballErc20** [forkdelta/tokenbase#1469]
Name of the Token- Bitball (Btb)
Details: All in One Crypto Currency Asset, #NoFakePromises

Token address: 0x382117315856a533549eA621542Ccce13E54aE82

Issuer's official website: https://www.bitball-btb.com/

Description:
One Crypto currency covering all Financial aspects of Digital Transactions build on Ethereum Blockchain. A Multipurpose Digital currency with Endless Possibilities and Rewards. #NoFakePromises.
Bitball is a Community/People Powered Crypto currency with no ICO (20% Airdropped). Nearly 60% - 600 million Tokens will be distributed for high circulation (200 million BTB, Airdropped in between 40000+ people in Phase 1.). We also Believe in rewarding our Community. More Bitballs will be Distributed in forms of Prizes, Rewards and Jackpots !
💠BitBall Treasure has also been forked to reward our Contributors.💠

Follow us for more Updates - Youtube, Github, Medium, Telegram, Pinterest
Twitter, Facebook, Instagram,Tumblr, Google+, Reddit, BitcoinTalk Ann and Many more to come!
NEW - PROGRESS MAP

Aug 28, 2018
Phase 1 - BTB Rewards Startup (After 200,000,000+ Bitballs free distribution)
Rewarding More people through our BTB rewards programs- attracting more and more people towards Bitball.

Oct 30, 2018
Phase 2 - Connecting Social Media through our Bitball Education Portal (Blog)
Plan to be announced after finishing our first bitball reward program. We will reveal our Plans after the previous Plans have finished. We want to be Unique and don't want to reveal our Plans till we are ready.

Dec 25, 2018
Phase 3 - Bitball = Everything Digital Currency
Digital Investment Asset, Listing on more Exchanges, Bitball Merchandise, Contacting Merchants to Adopt Bitball.

Mar 26, 2019
Phase 4 - MASTER GOALS
These are our Master Goals - Goals that will make us more unique than others ! These Goals will make bitball a forever usable cryptocurrency around the world.

Aug 15, 2019 Onwards
More Phases- More Development plans will be announced
We will always be working on developing more for Bitball. More to be announced as we grow.
A link to the official contract address confirmation: https://etherscan.io/address/0x382117315856a533549eA621542Ccce13E54aE82

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

Telegram: https://t.me/BitballGroupChat & https://t.me/Bitball
+SteemIt - https://steemit.com/cryptocurrency/@franzinatr/joining-bitball-btb-community-and-about-their-project
BitcoinTalk Ann Forum: https://bitcointalk.org/index.php?topic=4943502.new#new
Twitter: https://twitter.com/BitBall_Erc20
Facebook: https://www.facebook.com/profile.php?id=100026538557513
Reddit: https://www.reddit.com/u/Bitball/?st=JIVGSF3R&sh=763f4d33
Instagram: https://www.instagram.com/bitball_erc20/
Pinterest: https://www.pinterest.com.au/bitball/
ICO Listing Websites: https://www.initialcoinlist.com/ico/bitball/
GitHub: https://github.com/BitballErc20
Medium: https://medium.com/p/bitball-4a607c33ea78
We have also asked our Bitball Community to write reviews about bitball. We will update it soon
Thank you for your time.
Regards

**Comment by freeatnet** [comment]
Thank you for your request, @BitballErc20! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- **Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md)** and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by BitballErc20** [comment]
Hi again, we have updated the information, according to the required format, More Reviews coming soon through the Bitball community.
