### ISSUE TITLE
Request to add token (BLACK)

### ISSUE THREAD

**Issue by btcblack** [forkdelta/tokenbase#147]
Name:         Bitcoin Black
Symbol:       BLACK
Address:      0xf7ae0daa230bf3fb3c0e5e01e7a6e0a142c6cf7e
Decimals:    18
Email:          contact@btcblack.org
Website:      https://btcblack.org
Github:        https://github.com/btcblack
Twitter:        https://twitter.com/BTCBlackDotOrg
Description: Bitcoin Black is a next generation crypto currency. It is a 
                    tradeable ERC20 token that resides on the
                    Ethereum blockchain.

**Comment by Kryptoniq** [comment]
Provide a link to a third-party review or discussion of the token.

**Comment by btcblack** [comment]
Medium: https://medium.com/@bitcoinblack

**Comment by Kryptoniq** [comment]
A link from bitcointalk or any third-party review website is needed.

**Comment by btcblack** [comment]
Bitcoin Talk: https://bitcointalk.org/index.php?topic=3002401

**Comment by Kryptoniq** [comment]
0xf7ae0daa230bf3fb3c0e5e01e7a6e0a142c6cf7e, https://btcblack.org

**Comment by freeatnet** [comment]
@btcblack Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/BLACK-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
