### ISSUE TITLE
Add Tuurnt (TRT)

### ISSUE THREAD

**Issue by Burtonair720** [forkdelta/tokenbase#1470]
**Token address:**

0xee278a5a5a18fb31bbb4cbe3d4b2490d81cde907

**Issuer's official website:**

https://tuurnt.io

**Description:** 

Tuurnt.io is a social platform to Earn Tokens for Hosting & Attending Events. 

**A link to the official contract address confirmation:** 

https://tuurnt.io/#distribution

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://techcrunch.com/2017/11/01/tuurnt-lets-people-pay-you-to-party/
2. https://steemit.com/blockchain/@novikov433/ico-tuurnt-overview

**Comment by freeatnet** [comment]
Thank you for your request, @Burtonair720! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Burtonair720** [comment]
Hello Freeatnet, 

Thank you for reviewing Tuurnt's token request! Please let me know if you need any additional information to help facilitate listing. We are looking forward to being listed on ForkDelta as soon as possible!  =)
