### ISSUE TITLE
Add BCShop.io Token (BCS)

### ISSUE THREAD

**Issue by LawrenceLastra** [forkdelta/tokenbase#1471]
*Contract Address : https://etherscan.io/address/0x98bde3a768401260e7025faf9947ef1b81295519
*Website : https://bcshop.io/
*BCShop is e-commerce and e-payments platform of new generation, powered by blockchain technology. Sell or purchase good or services. Pay or get paid in ETH and Tokens using your favorite wallet. Worldwide. Start by visiting your dashboard.

*ICO Ratings/Reviews : https://icobench.com/ico/bcshop/ratings
                                     https://icoholder.com/en/bcshop-3495
                                     https://www.facebook.com/pg/BCShop.io/reviews/
                                     https://steemit.com/cryptocurrency/@outerground/bcshop-a-smart-contract-platform-for-vendors-of-digital-goods-and-services

*Social Media Pages :    https://www.facebook.com/BCShop.io/
                                      https://twitter.com/BCShop_io
                                      https://t.me/joinchat/FxGXTULeqJEx0BlrVb4bsQ
                                     

*Github :                        https://github.com/bcshop-io/bcshop.io

I am Lawrence Lastra Community Manager of BCSHOP and requesting to add our token to forkdelta . BCSHOP already launched it's main net . You can see our team also over here : https://www.coingecko.com/en/ico/bcshop ( RATING ) 

Please do not hesitate to contact me via email if there is a problem : markenzoayala@gmail.com

**Comment by freeatnet** [comment]
Thank you for your request, @LawrenceLastra! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
