### ISSUE TITLE
Add BitScreenerToken (BITX)

### ISSUE THREAD

**Issue by bitscreenergh** [forkdelta/tokenbase#1473]
Hello Team,
I am a user of BitScreener. Would you please list our token BITX?

1) Smart Contract Address: https://etherscan.io/address/0xff2b3353c3015e9f1fbf95b9bda23f58aa7ce007
2) Website: https://tokensale.bitscreener.com
3) Products: https://bitscreener.com
4) Media: https://www.entrepreneur.com/article/315434
and: https://bitcoinexchangeguide.com/bitscreener
5) Description:
BitScreener, one of the best real-time crypto-tracking platforms, has served more than 1,2 million traders and investors worldwide to track their investments since launch in 2017. It is now integrating crowdsourcing financial data and content ecosystem on blockchain through token BITX. BITX works as the payment method for financial traders and investors to buy advanced data services and the incentive method for the value contributors of the ecosystem. BitScreener will be a financial data marketplace for financial professionals and engineers to monetize their investment knowledge. The full ecosystem aims to track and analyze 100,000+ stocks worldwide together with existing 2000+ cryptos in a single platform.

Thank you very much!
BitScreener User

**Comment by freeatnet** [comment]
Thank you for your request, @bitscreenergh! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
