### ISSUE TITLE
TCASH smart contract update

### ISSUE THREAD

**Issue by redaready** [forkdelta/tokenbase#1474]
Hi all, we are planning update the smart contract of tcash to enforce contract security (https://etherscan.io/token/0xb8742486c723793cf5162bb5d3425ed9cd73d049), how we can do this?
**What token should be updated?**

**What about the token should be updated?**

**Comment by freeatnet** [comment]
From ForkDelta's side, you can open an issue that includes:
1. The old contract address
2. The new contract address
3. A link to the official announcement of the upgrade

From that issue, we will:
1. Deprecate the old contract address (typically by renaming it to X_OLD)
2. Add the new contract address

Let me know if this helps.

**Comment by redaready** [comment]
thank you for your response, here is the information necessary for delisting tcash

1. old contract address
0xB8742486C723793Cf5162bb5D3425ED9cD73D049

2.The new contract address
0x7051620d11042c4335069AaA4f10Cd3B4290C681

3.A link to the official announcement of the upgrade
https://www.etherflyer.com/home/TCASH_Contract_Update.html

**Comment by freeatnet** [comment]
@redaready Hmm. While this looks reasonable to me, would you mind signing a personified message to confirm your identity as the owner of 0xB8742486C723793Cf5162bb5D3425ED9cD73D049 (sign with owner account of 0x28b17ccf09d4dff97a63c921e4dcd9ba7c7d3317)?

Here's an example of the personified message:
```
We ask that TCASH symbol is reassigned from 0xB8742486C723793Cf5162bb5D3425ED9cD73D049 to 0x7051620d11042c4335069AaA4f10Cd3B4290C681. You can read more about the swap here: https://www.etherflyer.com/home/TCASH_Contract_Update.html. This message is signed for the request posted at https://github.com/forkdelta/tokenbase/issues/1474 on July 22, 2018 and cannot be reused after July 29, 2018.
```

Signature verification can be done with https://etherscan.io/verifySig or https://www.myetherwallet.com/signmsg.html.

**Comment by redaready** [comment]
@freeatnet hi freeatnet, here you are: 
https://etherscan.io/verifySig/1265

{ "address": "0x28b17ccf09d4dff97a63c921e4dcd9ba7c7d3317", "msg": "We ask that TCASH symbol is reassigned from 0xB8742486C723793Cf5162bb5D3425ED9cD73D049 to 0x7051620d11042c4335069AaA4f10Cd3B4290C681. You can read more about the swap here: https://www.etherflyer.com/home/TCASH_Contract_Update.html. This message is signed for the request posted at https://github.com/forkdelta/tokenbase/issues/1474 on July 22, 2018 and cannot be reused after July 29, 2018.", "sig": "0xdc87b8438cf53c0f2c8ada22ee24cbe10001067c215b9c927530e47dabe110c933f0a933816b10825ecd3243fead1f19eea61a6f2abf637ca14ac3d80e28e4411c", "version": "2" }

**Comment by redaready** [comment]
@freeatnet another question, for the old asset in the smart contact of exchange, can you do the automatic mapping to the new one?
