### ISSUE TITLE
Token Listing Request : EQUAL (EQL) Token

### ISSUE THREAD

**Issue by Crypto-Investor** [forkdelta/tokenbase#148]
Token Name: EQUAL
Symbol: EQL
Decimals: 18
Contract Address:
https://etherscan.io/token/0x47dd62d4d075dead71d0e00299fc56a2d747bebb

> Link to the EQUAL token website:
https://www.equaltoken.io/

> Link to an official page confirming the contract address:
https://www.equaltoken.io/ (below the EQUAL logo on Home page)

> A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2814625.0

`Short Description :`
A Self-deflationary, Fairly Distributed, Multiplatform Utility Token. 
EQUAL aim's to facilitate an ecosystem of products and services that are either powered, funded or incentivised through the EQUAL ERC-20 token. 
What makes EQUAL special is it's rapidly growing community, future seed offering program and it's unique self-deflationary token design.

`Detailed Desription :`
Read Whitepaper and Check Roadmap , available on website https://www.equaltoken.io/

**Other links related to this project :-**
> Discord: https://discord.gg/nCY5qgY 
> CMC: https://coinmarketcap.com/currencies/equal 
> Website: https://www.equaltoken.io 
> Telegram: https://t.me/joinchat/GtLjl1JMYiTHzhaQA5CGPw 
> Twitter: https://twitter.com/EqualToken 
> Facebook: https://www.facebook.com/equalnetwork 
> WeChat: https://t.me/EQUAL_OFFICIAL/94287 
> Reddit: https://www.reddit.com/r/EQUAL_Network 
> Medium: https://medium.com/@EqualToken 
> Whitepaper: https://www.equaltoken.io/whitepaper_v2.pdf

**Comment by Kryptoniq** [comment]
Verified: 0x47dd62d4d075dead71d0e00299fc56a2d747bebb.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
