### ISSUE TITLE
proposal for addition to the add a new token template

### ISSUE THREAD

**Issue by bobbypaintsstuf** [forkdelta/tokenbase#1481]
with regards to projects using the template 

https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md

i propose adding the addition of a section explaining how the donations to FD work. with the caveat that donations are only made after a coin is listed so as not to appear as if donations provide leverage and a speeding up of the listing process. i have lifted all bar the caveat  from the FD site " about ForkDelta " and feel it would be beneficial to FD for projects to know this info as in my chats with several teams it is evident many currently do not realise FD operates this way. Personally i would like to include a link to the  " public ledger of how the donations are distributed " if that can currently be provided. 
I propose the addition of the following - ( with the correction of the spelling of the word " utilising "

                                                 How to Donate to ForkDelta
ForkDelta currently interfaces with EtherDelta's original smart contract which allows ForkDelta users to trade utilising EtherDelta's volume. However, this means that the trading fees still go to EtherDelta and ForkDelta development costs come entirely out of our pockets. If you are interested in the ForkDelta project and would like to contribute to its future, please consider donating to the Ethereum address below. We would ask that any donations are made after listing of your token so as to provide transparency to the fact that donations will in no way influence the listing of a token nor speed up the process and that it is your choice to do so.

0x3a2aEdc3B54A99e429ae36637681d4560cE5C05b

As this is a project by the community, for the community, transactions to and from the donations address will be public and can be viewed on the blockchain. We will also keep a public ledger of how the donations are distributed. That way, donors can see exactly how their donations are helping!

**Comment by bobbypaintsstuf** [comment]
@freeatnet whats your instinct ?

**Comment by WorldLot** [comment]
Hi there, we have been informed by bobby that he wished to donate his winning BEAST token to FD,
Can you please confirm the the FD erc-20 address is:

0x3a2aEdc3B54A99e429ae36637681d4560cE5C05b

And we will send the tokens to you instead of him.

Many thanks Crypto Beast
