### ISSUE TITLE
Synthetics AI on ForkDelta

### ISSUE THREAD

**Issue by bogdanb9208** [forkdelta/tokenbase#1482]
Token Address: 0x68D3a1ecd63b4CC49548e5AF6922ECFE893176B4

Website: https://www.syntheticsai.com/

Synthetics AI is the first reports and due diligence platform for other ICOs. We think ICO projects are an incredible tool of crowdfunding and we know that clarity and transparency is key to presenting a great product to a global audience.

Our goal is to create an environment where project are easily deciphered and understood by the participants in order to empower them to make the best decisions.

Project reviews: https://cryptellect.net/synthetics-detsentralizovannaya-platforma-dlya-chat-botov/
https://medium.com/@stratafyre/synthetics-ai-a-new-dawn-for-machine-learning-bf99551ed53f
http://spotlightgrowth.com/index.php/2018/04/03/synthetics-ai-synt-is-an-artificial-intelligence-training-ground/

**The contract address is available on our main website in the Tokensale Stages & Bonuses section.

Thanks!

**Comment by freeatnet** [comment]
Thank you for your request, @bogdanb9208! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by bogdanb9208** [comment]
Hello, any updates?

**Comment by bogdanb9208** [comment]
Guys, 2 months have passed, are we missing something?

**Comment by bogdanb9208** [comment]
Hello, any updates for our request?
