### ISSUE TITLE
Changing or deleting element (EM) token contract address

### ISSUE THREAD

**Issue by ElementEM** [forkdelta/tokenbase#1483]
Contract address must be changed to 0xa0945daf5313e7878763598a7975e8a86c45b129.Now element EM token trading on dexdelta exchange - with this contract address.Old EM token traded on forkdelta exchange.
**What token should be updated?**
Contract address of Element token to 0xa0945daf5313e7878763598a7975e8a86c45b129.
Im not creator of EM token.

**What about the token should be updated?**
Contract address.

**Comment by mohamadsyawal7424** [comment]
0xa0945daf5313e7878763598a7975e8a86c45b129
