### ISSUE TITLE
BitcoinDiamondToken -BDT

### ISSUE THREAD

**Issue by BDTProject** [forkdelta/tokenbase#1484]
**Token address:**
https://etherscan.io/address/0xb22a0d3cc572f331d3fa368e4d8564684d929c5e

**Issuer's official website:**
https://bitcoindiamondtoken.com/

**Description:** 
BDT's goal is to make a cryptocurrency with no-cost transaction fee and instant receiving. We really hope this project will be one of the advancements in technology in the cryptocurrency world since it will be open for public. This way we will not be having transaction fees and transaction timeline to be sent or received and give miners a reasonable fee for confirming transactions.

**A link to the official contract address confirmation:** 
https://bitcoindiamondtoken.com/#howtobuy

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://bitcointalk.org/index.php?topic=4504406.0
1. https://bitcointalk.org/index.php?topic=4504406.msg40567441#msg40567441
2. https://bitcointalk.org/index.php?topic=4504406.msg41370573#msg41370573
3. https://bitcointalk.org/index.php?topic=4504406.msg41423151#msg41423151

**Comment by freeatnet** [comment]
Thank you for your request, @BDTProject! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
