### ISSUE TITLE
Add ORIUM (ORM) Token

### ISSUE THREAD

**Issue by OriumOfficial** [forkdelta/tokenbase#1485]
**Token address:**
0xd51e852630DeBC24E9e1041a03d80A0107F8Ef0C

**Issuer's official website:**
https://oriumcoin.com

**Description:** 
ORIUM based on Ethereum network and have the eco-system of fair P2P mobile game.Focus on entertainment and will develop dApps in near future.ORIUM is one of game unit for playing globally.

**A link to the official contract address confirmation:** 
https://oriumcoin.com/#testi

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=2851374.0
2.https://bitcointalk.org/index.php?topic=4705626.msg42476358#msg42476358
Ecosystem mobile app game will coming soon.After that we will release press and interview.
![20180722_123522](https://user-images.githubusercontent.com/32276282/43043905-718f9ecc-8dc6-11e8-96ca-14b1efcf612f.jpg)
![20180722_132721](https://user-images.githubusercontent.com/32276282/43043906-71d04e86-8dc6-11e8-8a01-30a35f25fb95.jpg)
![20180722_133012](https://user-images.githubusercontent.com/32276282/43043907-7201da78-8dc6-11e8-90d4-69f0d2d40d62.jpg)

I am ORIUM Advisor.
https://twitter.com/ORIUMAdvisor

**Comment by freeatnet** [comment]
Thank you for your request, @OriumOfficial! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by OriumOfficial** [comment]
ORIUM Token was already  listed on ETHERC Exchange JUNE 25 of 2018.

**Comment by OriumOfficial** [comment]
Hi admin 

Can you follow up the process of listing?
Thanks.

**Comment by OriumOfficial** [comment]
Hi Admin

Can you please follow up and process of listing????
