### ISSUE TITLE
Add RefugeCoin (RFG)

### ISSUE THREAD

**Issue by Refuge-Coin** [forkdelta/tokenbase#1486]
**Token address:**
https://etherscan.io/address/0x488678c730b9117f017d719624084894eb54700a

**Issuer's official website:**
https://refugecoin.com/

**Description:** 
The migratory problem is a global phenomenon.Over $1 trillion dollars are invested in managing and resolving it. Οur engagement has to do with the management. So the growth of our Token increases as the participants increase.

**A link to the official contract address confirmation:** 
https://refugecoin.com/dashboard/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcoiner.today/en/icos-social-refugecoin-change-the-world-now/
2.https://www.coinhills.com/ico/view/refugecoin/

**Comment by freeatnet** [comment]
Thank you for your request, @Refuge-Coin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
