### ISSUE TITLE
Add KNEKTED (KNT) CoinMarketCap

### ISSUE THREAD

**Issue by IramDelCastillo** [forkdelta/tokenbase#1488]
**Token address:**
0x7CC62d8E80Be9bEa3947F3443aD136f50f75b505
Name: Knekted
Ticker: KNT

**Issuer's official website:**
www.knekted.net

CoinMarketCap: https://coinmarketcap.com/currencies/knekted/

**Description:** 

$KNT Is a digital platform based on blockchain technology, through users of all the world will be able to upload original and exclusive material created by themselves, which could be acquired by large corporations, presses, governments and all kinds of organizations who base their business model on information.

Knekted is a platform for the future of information based on blockchain technology, revolutionizing the business of TRADING information, leaks, multimedia material and original content made by creators from all over the world.

Twitter: www.twitter.com/KNTBlockchain
Facebook: www.facebook.com/KNTBlockchain

CEO: 
www.twitter.com/IramDelCastillo
www.facebook.com/iramdelcastillo 

**A link to the official contract address confirmation:** 

https://knekted.net/
You can find contract address in the main page at the middle, the title is: How to Buy Our Tokens

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.- https://www.youtube.com/watch?v=cSB9SMkncGI&t=43s KNT Knekted Video Review By Martin Hacks

2. http://hidalgoenlared.com.mx/knekted-lanza-el-primer-proyecto-mexicano-basado-en-la-tecnologia-blockchain/

Hidalgo en la Red is a press in spanish with +than 48000 users on facebook
https://www.facebook.com/pg/HidalgoEnLaRed/

3. http://noticiascapital.com.mx/ico-review-knekted-knt-un-sistema-para-el-trading-de-informacion/
5 Stars ICO review by Noticias Capital (National México Press)

Noticias Capital has around 50k Followers on Facebook
https://www.facebook.com/NoticiasCapitalM/

- Extra: $KNT is listed on coinstats.app one of the best tools for the crypto world
https://twitter.com/KNTBlockchain/status/1020005303075696640
http://knekted.net/wp-content/uploads/2018/07/photo_2018-07-22_12-15-03.jpg

EXCHANGES:

LAToken/KNT Markets

https://wallet.latoken.com/market/Crypto/BTC/KNT-BTC

https://wallet.latoken.com/market/Crypto/BTC/KNT-ETH

https://wallet.latoken.com/market/Crypto/BTC/KNT-LA

https://wallet.latoken.com/market/Crypto/USDT/KNT-USDT

Bleutrade/KNT Markets

https://bleutrade.com/exchange/KNT/BTC

https://bleutrade.com/exchange/KNT/ETH

https://bleutrade.com/exchange/KNT/USDT

https://bleutrade.com/exchange/KNT/DOGE

CREX24/KNT Markets

https://crex24.com/exchange/KNT-BTC

https://crex24.com/exchange/KNT-ETH

https://crex24.com/exchange/KNT-USD

https://crex24.com/exchange/KNT-RUB

https://crex24.com/exchange/KNT-JPY

https://crex24.com/exchange/KNT-EUR

https://crex24.com/exchange/KNT-CNY

Tradesatoshi/KNT Markets

https://tradesatoshi.com/Exchange/?market=KNT_BTC

https://tradesatoshi.com/Exchange/?market=KNT_ETH

https://tradesatoshi.com/Exchange/?market=KNT_LTC

https://tradesatoshi.com/Exchange/?market=KNT_BCH

https://tradesatoshi.com/Exchange/?market=KNT_USDT

https://tradesatoshi.com/Exchange/?market=KNT_DOGE

TokenStore/KNT Markets

https://token.store/trade/KNT

- Extra: Video Introduction KNT The Power Of Information
https://www.facebook.com/KNTBlockchain/videos/435185603632410/
- Extra: BitcoinTalk Thread:
https://bitcointalk.org/index.php?topic=4739221.0
- Extra: Reddit: https://www.reddit.com/r/KNTBlockchain/

**Comment by freeatnet** [comment]
Thank you for your request, @IramDelCastillo! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by ShemiHazah** [comment]
Thanks for the Information, we have a amazing team of young and hardworking people, we hope we can get listed soon, thanks in advance, blessings.

**Comment by IramDelCastillo** [comment]
Thanks for the information, we have an amazing team with young and hardworking people, we hope we can get listed soon, thanks in advance, blessings.
