### ISSUE TITLE
Add 3DESNetwork (3DES)

### ISSUE THREAD

**Issue by 3desproject** [forkdelta/tokenbase#1492]
**Token address:**
0x115E7B7eCdd9792d6995CB426B2Ef4D6119682A7

**Issuer's official website:**
https://3des.network/

**Description:** 
3DES is decentralized computing capacities exchange for slicing tasks. We have issued a futures token and will swap all existing tokens to this.

**A link to the official contract address confirmation:**
https://3des.network/static/smartcontract.txt

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://cointelegraph.com/press-releases/3des-blockchain-for-the-sake-of-3d-printing-not-the-blockchain-itself
2. https://invest4all.ru/obzory-i-otchyoty/obzory-kraudsejlov-ico/3des-ico-kraudsejl-sistemy-optimizatsii-oblachnoj-3d-pechati
3. https://www.youtube.com/watch?v=8M6RpQVAqDM
4. https://www.youtube.com/watch?v=BlhoL5_2sio

**Comment by freeatnet** [comment]
Thank you for your request, @3desproject! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
