### ISSUE TITLE
Add Mingocoin XMC

### ISSUE THREAD

**Issue by Bavaras** [forkdelta/tokenbase#1493]
**Token address:**

0xaa3f6003d72fb579f29a91742cf3cefea83cebba
--

**Issuer's official website:**

https://mingocoin.com/
**Description:** 
Mingo is an instant messenger aggregation app that supports Facebook, Twitter, Steam, Discord, Slack, Skype and IRC Cloud. 

A mobile wallet that is seamlessly integrated with Mingo Chat; allowing users to manage and transact cryptocurrency within the messenger.

Casual eSports for the masses. Play with friends, strangers, or in micro-tournaments to win crypto through games of skill...but casually of course.

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. Mingo to build on hashgraph technology
https://medium.com/@jilliangodsil/mingo-to-build-on-hashgraph-technology-a168c2a2d607

2. Exclusive with the CEO of Mingo talking MingoCoin and crypto!
https://www.youtube.com/watch?v=7vTq7B-OHQU

3. Hashgraph and Mingocoin
https://steemit.com/airdrop/@bitkat/hashgraph-and-mingocoin

**Comment by freeatnet** [comment]
Thank you for your request, @Bavaras! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
