### ISSUE TITLE
Add moolyacoin (moolya)

### ISSUE THREAD

**Issue by moolyacoin** [forkdelta/tokenbase#1494]
**Token address:**
https://etherscan.io/token/0x2a47f802064caf5a5e78ee193723dc2c7cfc06e9

**Issuer's official website:**
www.moolyacoin.io

**Description:** 
'moolya.global' is the 'World's 1st LIVE and Comprehensive Global Digital Startup Ecosystem' which is a culmination of an interaction network, marketplace and on-demand service platform for the startup ecosystem community. It comprises of the 6 vital communities: Institutions, Ideators, Startups, Investors, Companies, Service Providers and various other enablers. moolyacoin is an ERC20 token of a patent pending innovative SaaS platform - moolya.global, which is a culmination of an interaction network, marketplace and on-demand service platforms offering services using the Ethereum blockchain framework and moolyacoin as its preferred mode to access and conduct transactions.

**A link to the official contract address confirmation:** 
Crowdsale contract details and Token contract details are mentioned in the home page of our website: www.moolyacoin.io
and here: https://www.moolyacoin.io/terms_and_conditions/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://medium.com/@iob/from-rhode-island-to-hyderabad-b6da68d39d9
2.https://www.youtube.com/watch?v=ElZ8B1tC2O8
3. https://www.youtube.com/watch?v=eU3EVLtNUT4
4. https://www.youtube.com/watch?v=eAc4ejNOXyc
5. https://www.youtube.com/watch?v=vjSvfr4aLlE
6. https://icobench.com/ico/moolyacoin/ratings#r-15099

[moolyacoin_whitepaper_Ver5.5.pdf](https://github.com/forkdelta/tokenbase/files/2222713/moolyacoin_whitepaper_Ver5.5.pdf)

[Lite_paper_moolyacoin_Ver3.3.pdf](https://github.com/forkdelta/tokenbase/files/2222715/Lite_paper_moolyacoin_Ver3.3.pdf)

**Comment by freeatnet** [comment]
Thank you for your request, @moolyacoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
