### ISSUE TITLE
Add 	vertcoin cash (VTCH)

### ISSUE THREAD

**Issue by miitguy** [forkdelta/tokenbase#1495]
Name: Vertcoincash (VTCH)
Contract address: 0x881e1344eee25ce7de2f4857ba86b04df8f77bea
website: vtch.info
projects: We intends to build a decentralized/ effortless digital campaign and business management market place, morealso, A freelancing/ skills rending hydro-secured software
link1: https://ethplorer.io/address/0x881e1344eee25ce7de2f4857ba86b04df8f77bea
Link2: https://bitcointalk.org/index.php?topic=3279292.msg34187443#msg34187443

**Token address:**

**Issuer's official website:**

**Description:** 

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by freeatnet** [comment]
Thank you for your request, @miitguy! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
