### ISSUE TITLE
Add Letsfair (LTF)

### ISSUE THREAD

**Issue by tiago-marques** [forkdelta/tokenbase#1497]
Token address:
0x411A81C8Cd604941be13dBBD33B54e6f25d84683

Issuer's official website:
https://letsfair.org/

Description: 
The goal of the Letsfair project is to build a shared economy network, which in practice, is a marketplace for many types of apps. Our biggest challenge is to promote a decentralized work organization.

A link to the official contract address confirmation: 
https://letsfair.org/investor/#tokens

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://icobench.com/ico/letsfair
2. https://www.icoalert.com/?q=letsfair
3. https://icorating.com/ico/letsfair-ltf/
4. https://www.trackico.io/ico/letsfair/
5. https://icobazaar.com/v2/letsfair
6. https://icoranker.com/ico/letsfair
7. https://foundico.com/ico/letsfair.html
8. https://coindelite.com/ico-details-letsfair
9. https://findico.io/ico/letsfair
10. https://cointobuy.io/icos/letsfair
11. https://cryptonext.com/ico/letsfair
12. https://icosbull.com/eng/ico/letsfair
13. https://ico.coincheckup.com/Letsfair/
14. https://coinews.net/ico/letsfair
15. http://whatcoindaily.com/ico/letsfair/
16. https://besteico.com/ico/letsfair/
17. https://letsfair.com/pieceofcake (MVP)
18. https://portaldobitcoin.com/startup-brasileira-vai-criar-shopping-center-digital-de-servicos-de-economia-compartilhada/ (local media)

**Comment by freeatnet** [comment]
Thank you for your request, @tiago-marques! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
