### ISSUE TITLE
Please add CPEX (Coinpulse Token)

### ISSUE THREAD

**Issue by FungieD** [forkdelta/tokenbase#1498]
**Token address:**0xb787d4eac8899730bb8c57fc3c998c49c5244ec0

**Issuer's official website:**https://www.coinpulse.io

**Description:** CPEX is an Coinpulse centralized exchange native token used for fees discount, also use of special events run on the exchange 

**A link to the official contract address confirmation:** As there is no contract address of CPEX token on the exchange Coinpulse visible, I have attached a screenshot from Coinpulse telegram group, where admin posted etherscan http address https://etherscan.io/token/0xb787d4eac8899730bb8c57fc3c998c49c5244ec0#comments
![screenshot 133](https://user-images.githubusercontent.com/35142787/43164166-5aab3f5e-8f88-11e8-86d8-145bfb4f71e8.png)

Also you can see the contract address here on bitcointalk post:
https://bitcointalk.org/index.php?topic=3252372.0

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.coindiary.net/get-ready-for-coinpulse-io-the-most-anticipated-crypto-exchange-of-2018/
2.https://seekingalpha.com/instablog/22912651-daniel-jennings/5156898-coinpulse-2018-s-anticipated-cryptocurrency-exchange-platform
3.https://bitcointalk.org/index.php?topic=3252372.0

**Comment by freeatnet** [comment]
Replaced by #1499.
