### ISSUE TITLE
Please add CPEX (Coinpulse Token) (updated links)

### ISSUE THREAD

**Issue by FungieD** [forkdelta/tokenbase#1499]
**Token address:**0xb787d4eac8899730bb8c57fc3c998c49c5244ec0

**Issuer's official website:**https://www.coinpulse.io

**Description:** CPEX is an Coinpulse centralized exchange native token used for fees discount, also use of special events run on the exchange 

**A link to the official contract address confirmation:** As there is no contract address of CPEX token on the exchange Coinpulse visible, I have attached a screenshot from Coinpulse telegram group, where admin posted etherscan http address https://etherscan.io/token/0xb787d4eac8899730bb8c57fc3c998c49c5244ec0#comments
![screenshot 133](https://user-images.githubusercontent.com/35142787/43164166-5aab3f5e-8f88-11e8-86d8-145bfb4f71e8.png)

Also you can see the contract address here on bitcointalk post:
https://bitcointalk.org/index.php?topic=3252372.0

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**https://t.me/CoinPulseEx
              https://twitter.com/CoinPulseEx
       
Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
-->
1. https://www.coindiary.net/get-ready-for-coinpulse-io-the-most-anticipated-crypto-exchange-of-2018/
2.https://seekingalpha.com/instablog/22912651-daniel-jennings/5156898-coinpulse-2018-s-anticipated-cryptocurrency-exchange-platform
3.https://bitcointalk.org/index.php?topic=3252372.0

**Comment by freeatnet** [comment]
Thank you for your request, @FungieD! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by CoinPulse** [comment]
Hi
Any progress on adding CPEX? Its been moved on Add or Update Token on July 26. If you need any additional information, please let us know. This is our project.
