### ISSUE TITLE
Apply for listing LiteCoinW Plus token

### ISSUE THREAD

**Issue by litecoinwplus** [forkdelta/tokenbase#150]
Dear Forkdelta team:
I would like to know the requirements and instructions for listing our token: LiteCoinW Plus. My name is Alejandro Fernández I am the founder and development manager. I would also like to know the listing price.
Below I have included the specifications and a short description of LiteCoinW Plus. If you require further information, please do not hesitate to contact me.
I look forward to receiving your reply.
Yours faithfully,
Alejandro Fernandez
Dev Manager of LiteCoinW Plus
Short Description 
LiteCoinW Plus (LCWP) is a multipurpose cryptocurrency designed to meet the needs of various types of users, it has a green-marked verified Contract (ERC20). Due to its optimized code, free of bugs and warnings, LCWP has very low fees and very fast transactions. LCWP Features and capabilities as well as the code are available for consultation on Etherscan: https://etherscan.io/address/0xe8fc7e1973496848fcb486c5bb880f68487ea0bb#code
Specifications and Social
Name: LiteCoinW Plus
Symbol: LCWP
Decimals: 8
Total Supply: 84.000.000
Contract erc20: 0xe8fc7e1973496848fcb486c5bb880f68487ea0bb
Website: https://litecoinwplus.com/
WhitePaper 1.0:  http://litecoinwplus.com/downloads/LiteCoinwPlus-Whitepaper-Rev1.pdf
ANN (by Full Member):  https://bitcointalk.org/index.php?topic=2271631.0
Twitter (with 8k followers): https://twitter.com/LiteCoinW
Telegram Group: https://t.me/joinchat/G9zlzBIfc72mKF69f4OJ_A
Link to code: https://etherscan.io/address/0xe8fc7e1973496848fcb486c5bb880f68487ea0bb#code
Email: info@litecoinwplus.com
Link to download Logo: https://k50.kn3.net/2/F/0/9/5/2/7DC.png
Dev´s Telegram https://t.me/LiteCoinW
Facebook link: https://www.facebook.com/litecoinw
Reddit: https://www.reddit.com/user/LiteCoinW/

**Comment by Kryptoniq** [comment]
Verified: 0xe8fc7e1973496848fcb486c5bb880f68487ea0bb.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
