### ISSUE TITLE
Add SaveToken (SAVE)

### ISSUE THREAD

**Issue by btcsmartads** [forkdelta/tokenbase#1501]
**Token address:**
0x9a9ae6884c65725c8f5378dbb6d3900bff36da53

**Issuer's official website:**
https://www.saveinvest.io

**Description:** 
SAVE Token offers a Buy Back System for cryptocurrency investments. It attracts new skeptical investors to the crypto market.

**A link to the official contract address confirmation:** 
https://saveinvest.io/#faq

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.youtube.com/watch?v=z8sQQeHluNM
2. https://bitcoinexchangeguide.com/save-token-ico/
3. https://www.listico.io/ico-calendar/save-crypto-coin-ico

**Comment by freeatnet** [comment]
Thank you for your request, @btcsmartads! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
