### ISSUE TITLE
Update BLN - BULLEON token

### ISSUE THREAD

**Issue by bobbypaintsstuf** [forkdelta/tokenbase#1502]
BLN - BULLEON token has issued a FORK announcement it will become BUL 

contract address -

0x7b1309c1522afd4e66c31e1e6d0ec1319e1eba5e

ForkDelta current listing link-

https://forkdelta.github.io/#!/trade/BLN-ETH

official announcement link  of FORK

https://medium.com/@Bulleon_net/bulleon-bln-erc20-token-fork-bb676853670

among the info - it says -

 if you own the old BLN token, you are required to take no further action. Anyone who has the old BLN token will receive 1:1 in relation to the new BUL token. In addition, if you have our erstwhile BLN token in your wallet, it will be automatically upgraded to our new BUL token.

The blockchain snapshot will occur at 5737100 block, from which we will divulge all BLN owners of that block and send new BUL tokens to these addresses.

NB: After the block 5737100 is mined, the old BLN token will no longer command any value! Similarly, after the 5737100 block mined, you can destroy the old BLN tokens by sending them to 0x0000000000000000000000000000000000000000

looks like https://etherscan.io/address/0x0775c81a273b355e6a5b76e240bf708701f00279 will be the new contract address

**Comment by freeatnet** [comment]
Thanks @bobbypaintsstuf!
