### ISSUE TITLE
Add ZEWT (ZEWT)

### ISSUE THREAD

**Issue by Zeew-source** [forkdelta/tokenbase#1503]
**Token address:**
https://etherscan.io/token/0x83bf7c56cc8175ba8f3554b1aa12461c760b8b94

**Issuer's official website:**
http://ico.zeew.eu

**Description:** ZEWT is token for Zeew platform, on-demand delivery platform built on top of ethereum blockchain, ZEWT is the only currently accepted to use zeew platform.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x83bf7c56cc8175ba8f3554b1aa12461c760b8b94
Code here: https://github.com/Zeew-source/ZEWT-TOKEN/blob/master/zewt-token-code.txt

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

**Comment by freeatnet** [comment]
Thank you for your request, @Zeew-source! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
