### ISSUE TITLE
BOLD Token transition to a Mineable Coin - Please Delist

### ISSUE THREAD

**Issue by theboldtoken** [forkdelta/tokenbase#1505]
**What token should be updated?**
Name: BOLD
Contract address: 0x7cdEC53Fe4770729dac314756c10E2F37b8d2B2f
Website: https://www.boldtoken.io

**What about the token should be updated?**

BOLD has transitioned to a mineable (Cryptonote) coin. We are currently carrying out a swap process, which wil close on August 3 2018. Please officialy delist this token from your exchange on August 3 2018.
For reference, please see the new BOLD coin Bitcointalk page: https://bitcointalk.org/index.php?topic=4587224
The "old" BOLD token Bitcointalk page: https://bitcointalk.org/index.php?topic=2386305.0
The swap information page: https://www.boldtoken.io/swap.php
The new BOLD coin official website: https://www.boldprivate.network

If possible, please announce to your users.

Please let me know if you have any questions.
Thanks.

**Comment by freeatnet** [comment]
Thanks @theboldtoken! Will update in the next batch.
