### ISSUE TITLE
We want to list our coin PRESTO(PRST)

### ISSUE THREAD

**Issue by jubin3424** [forkdelta/tokenbase#1507]
1. Contract address: 0x9f05670b96ecb6e2303e98572712f2edffd28b6c
2. Website: presto-platform.io
3. Projects:  PRESTO platform automatically generates a secure and efficient smart contract by getting the basic information of the token that the development team wants. 
4. https://presto-platform.io/whatsnew/1
5. 
link1: https://www.youtube.com/watch?v=dqpxqPgior8
link2: http://conference.etnews.com/conf_info.html?uid=91
link3: http://www.blockchainnews.co.kr/news/view.php?idx=1786
link4: http://www.decenter.kr/NewsView/1S214YD7AX/GZ02
link5: http://www.etnews.com/20180622000269
link6: https://news.joins.com/article/22611086

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
