### ISSUE TITLE
Modi Coin

### ISSUE THREAD

**Issue by Modi-coin** [forkdelta/tokenbase#1508]
EtherScan Token Contract :- https://etherscan.io/token/0xd96d8590f5ae4e4b73715b63cfb3c4bd21c37db0

Website :- https://modicoin.net

Description:- MODI COIN is the Digital Currency that will power the Global Payment System. MODI COIN (MODI) is an ERC20 token built on top of the Etherium Blockchain and is a new digital currency that enables instant payments to anyone, anywhere in the world. 

BCT Ann:- https://bitcointalk.org/index.php?topic=4756581

Kindly confirm once listed

Thanks

**Comment by freeatnet** [comment]
Please make sure your request follows the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md

**Comment by Modi-coin** [comment]
I hope the info submitted was as per your format except the reviews. We don't have any reviews yet .
