### ISSUE TITLE
Add Europium (Eu)

### ISSUE THREAD

**Issue by crvanderhorst** [forkdelta/tokenbase#1509]
**Token address:**

0xaB7e4aE99D7bfff4de8322aB915e9066857227F0

**Issuer's official website:**

http://www.europium.eu.com

**Description:** 

Exclusive, Ultra-Rare Ethereum ERC20 Token. Scarcity Token for the Subcreation and Development of Inherent Value ERC Tokens.

**A link to the official contract address confirmation:** 

https://etherscan.io/tx/0x3d9278e31c49254977474ef0aff31e334dad63e75c41151a4378375c7f837343

**Comment by freeatnet** [comment]
Thank you for your request, @crvanderhorst! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by crvanderhorst** [comment]
Nearly 1 year since add request.  I understand the long list, but this is a very valid effort awaiting addition.  Thank you!

**Comment by crvanderhorst** [comment]
This request has been active for nearly 2 years and ignored.  I understand the inability to service all requests, but this should be activated by now.
