### ISSUE TITLE
Add Lupecoin (LUPX)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1510]
**Token address:**
0x49c67ae22c334d0123dd6dbdc44f5302e130a88b

**Issuer's official website:**
https://www.lupecoin.org/

**Description:** 
Lupecoin is a meme coin in the same spirit as dogecoin. It's an ERC20 token airdropped to anyone who asked during the airdrio period. We are building dApps and other fun stuff around the project. It's main goal is for tipping and having fun in the crypto space. 

**A link to the official contract address confirmation:** 
All details can be found on this page https://www.lupecoin.org/about-lupecoin

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://medium.com/@lupecoinproject
https://bitcointalk.org/index.php?topic=4612542
https://www.reddit.com/r/LupeCoin/

1. https://t.me/LupeCoinChat
2. https://www.reddit.com/r/LupeCoin/
3. https://twitter.com/LupecoinProject

**Comment by freeatnet** [comment]
Thank you for your request, @debaas0! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
