### ISSUE TITLE
Add Cashpayz Token (CPC)

### ISSUE THREAD

**Issue by rehmat78** [forkdelta/tokenbase#1511]
**Token address:**
0x6abb492d778903be5fb8922e076ca5e337e29062

**Issuer's official website:**
https://cashpayzcoin.com

**Description:** 
A Cryptocurrency based payment solution for future

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x6abb492d778903be5fb8922e076ca5e337e29062

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. Twitter - https://twitter.com/CashpayzCoin
2. Facebook - https://www.facebook.com/cashpayzcoin/
3. Telegram - https://t.me/cashpayzcoin
4. Youtube - https://www.youtube.com/channel/UC2MzZVZYIgDeZKyetfY6-XA
5. LinkedIn - https://www.linkedin.com/in/cashpayz-coin-73a850168/
6. Slack - https://cashpayzcoin.slack.com/
7. Medium - https://medium.com/@cashpayzcoin
8. Reddit - https://www.reddit.com/u/cashpayzcoin

**Comment by freeatnet** [comment]
Thank you for your request, @rehmat78! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
