### ISSUE TITLE
Add OCCULT CASH (OCCULT)

### ISSUE THREAD

**Issue by OccultCash** [forkdelta/tokenbase#1512]
**Token address:**
0xb0FB0E71316358C7736E96a5bEEc22f1362EB062
**Issuer's official website:**
https://www.occult.cash/
**Description:**
The Cryptocurrency For the Occultists, By the Occultists, Of the Occultists.
**A link to the official contract address confirmation:**
https://www.occult.cash/#specifications
**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://bitcoingarden.org/forum/index.php?topic=42614.msg303160#msg303160
https://allcryptotalk.com/index.php?/topic/17731-announcement-occult-cast-occult/
https://cryptocurrencytalk.com/topic/107751-announcement-occult-cast-occult/
https://forum.bitcoin.com/alternative-cryptocurrencies-altcoins/occult-cast-occult-t93001.html
https://www.emoneyspace.com/forum/index.php/topic,456202.0.html
https://www.carigold.com/portal/forums/showthread.php?t=682678
https://exchangecurrencyzone.com/threads/announcement-occult-cast-occult.275171/
https://ogflip.com/Thread-ANNOUNCEMENT-Occult-Cast-OCCULT
https://btcblogs.com/index.php?topic=151.new#new
http://talkptc.com/index.php?topic=68720.0
http://cryptocoinfans.com/index.php?topic=451.0
https://cryptocashhub.com/forum/viewtopic.php?f=4&t=4643
https://www.mystellar.org/thread-25596.html
https://www.bitcointalk.club/viewtopic.php?f=43&t=21488
https://forum.bit.news/eng/index.php?/topic/1679-announcement-occult-cast-occult/
https://www.altcoinstalks.com/index.php?topic=35604.0
http://www.jackobian.com/threads/announcement-occult-cast-occult.97117/
https://www.dash.org/forum/threads/announcement-occult-cast-occult.39751/
https://mastersofcrypto.com/forum/threads/announcement-occult-cast-occult.29081/
https://forum.bits.media/index.php?/topic/125680-announcement-occult-cast-occult/
https://cryptotalksworld.org/index.php?topic=1659.new#new
https://topgoldforum.com/topic/329034-announcement-occult-cast-occult/
https://crypto-chat.org/threads/announcement-occult-cast-occult.156/
https://allcryptotalk.com/index.php?/topic/17732-announcement-occult-cast-occult/
https://thecryptocurrencyforums.com/community/threads/announcement-occult-cast-occult.2162/
https://www.cointalks.org/forum/announcements/new-coins/858-announcement-occult-cast-occult
https://forum.cryptoinfo.net/viewtopic.php?f=14&t=1209
http://crypto.country/forum/Thread-ANNOUNCEMENT-Occult-Cast-OCCULT
http://forumforu.net/Thread-ANNOUNCEMENT-Occult-Cast-OCCULT
https://www.altcointradingforum.com/forum/main-forum/1472-announcement-occult-cast-occult
https://forumbitcoin.co.id/threads/announcement-occult-cast-occult.71825/
https://cryptoforum.cc/viewtopic.php?f=34&t=223
https://cryptoheresy.com/viewtopic.php?f=20&t=18191
http://www.digitalmoneytalk.com/topic/56177-announcement-occult-cast-occult/

**Comment by freeatnet** [comment]
Thank you for your request, @OccultCash! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
