### ISSUE TITLE
Add Bitcoin Public (Btcp)

### ISSUE THREAD

**Issue by bitcoinpublic** [forkdelta/tokenbase#1516]
Token Name: Bitcoin Public
Symbol: Btcp
Decimal: 8
Total supply: 5,000,000,000
Contract address: https://etherscan.io/address/0xB448B4363F551AFB8561e49110aE0480889c49dC

about the token
FIRST INTEGRATED ECOMMERCE TOKEN PAYMENT GATEWAY PLUGINS

Our Official Website: http://bitcoinpublic.ml
our Road map: http://bitcoinpublic.ml/road-map/
Our Whitepaper: http://bitcoinpublic.ml/whitepaper

social media channel    

twitter: https://twitter.com/bitcoinpublic
telegram channel : https://t.me/bitcoin_public

**Comment by freeatnet** [comment]
Thank you for your request, @bitcoinpublic! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
