### ISSUE TITLE
Add SiaCashCoin (SCC)

### ISSUE THREAD

**Issue by SiaCashCoin** [forkdelta/tokenbase#1519]
Contract address: 0x74fd51a98a4a1ecbef8cc43be801cce630e260bd

Issuer's official website: https://www.SiaCashCoin.com

Description: 
In this day and age, technology envelopes us all, and the impact it has on our lives is growing at an ever increasing rate. At the core of this ongoing digital revolution is one thing: Data. While replacing your old phone or computer is about as easy as buying a new pair of shoes, the one thing that is impossible to replace is data. Whether it is baby pictures of your children, the college thesis you have been working on all semester, or your tax documents for your home business...these things are unreproducible in the event of hard-drive corruption, loss, or theft by hackers. While some solutions exist for the above problems, such as buying extra storage devices and managing the copies yourself or spending long amounts of time finding a quality storage provider, none will be as easy or as simple as the solutions SiaCashCoin will provide.

Official contract address confirmation: 
You need to go to https://siacashcoin.com/#contact and click on " SiaCashCoin At Etherscan"

https://etherscan.io/address/0x74fd51a98a4a1ecbef8cc43be801cce630e260bd#code

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://steemit.com/siacashcoin/@princeola/siacashcoin-the-revolutionized-cloud-storage-3528d1769ab04
https://www.youtube.com/watch?v=2szmAHjKcew&t=14s

**Comment by freeatnet** [comment]
Thank you for your request, @SiaCashCoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by SiaCashCoin** [comment]
https://coinmarketcap.com/currencies/siacashcoin/
https://www.coingecko.com/en/coins/siacashcoin
https://www.livecoinwatch.com/price/SiaCashCoin-_SCC
