### ISSUE TITLE
Add Exsulcoin XUL

### ISSUE THREAD

**Issue by exsulcoin** [forkdelta/tokenbase#1520]
**Token address:** 0x8580610f907e808aaf77b555cb9970894c57c53e

**Issuer's official website:** https://exsulcoin.com/

**Description:** Exsulcoin is a for-profit company delivering high-quality education to the world’s most disadvantaged people. Our blockchain-based Exsul education app is currently being used in the Kutupalong and Balukhali Rohingya refugee camps in Cox’s Bazar, Bangladesh. The ExsulCoin blockchain will help refugees learn, refine skills, find employment, and share their work records with other people. The founders of ExsulCoin, James Song and Cat Song, are deeply passionate about aiding refugees.

**A link to the official contract address confirmation:** https://etherscan.io/token/0x8580610f907e808aaf77b555cb9970894c57c53e

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

**1.** http://news.trust.org/item/20180503120421-oa2qn/

**2.** https://cryptoslate.com/how-blockchain-technology-is-helping-the-rohingya-crisis/

**3.** https://www.scmp.com/week-asia/business/article/2153156/fighting-cancer-singapore-eating-plastic-indonesia-southeast-asia

**4.** https://www.citylab.com/solutions/2018/02/when-technology-tackles-the-global-refugee-crisis/551909/

**Comment by freeatnet** [comment]
Thank you for your request, @exsulcoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
