### ISSUE TITLE
Add Tuurnt (TRT)

### ISSUE THREAD

**Issue by dannygkass** [forkdelta/tokenbase#1521]
Contract address:
0xee278a5a5a18fb31bbb4cbe3d4b2490d81cde907

Official website:
https://tuurnt.io

Tuurnt came	after realizing there	was a voidin the	event industry.	Nowadays, people can	make money from driving an	 Uber,	 or	 can	 rent	 out	 their homes	 on Airbnb,	 but what if someone	
doesn’t	own	a car	or	a	home?	That’s when	Tuurnt	app	comes into play. With the blockchain
technology,	Tuurnt	gives	 its	 users the ability	 to create an	event	 in minutes!	 Just like Uber	 or	
Airbnb,	you	get	paid	to	be	the	host.	We	are	an	app	that	connects	partygoers	with	hosts.On	one	
side	 we	 want	 to	 empower	 individuals	 to	 list	 their	 events	 and	 gain	 additional	 income.On	 the	
other,	we	want	to	give	our	community	a	unique	experience	to	book	events	from	abroad	or	local	
host,	 allowing	 them	 to	 collaborate	 and	 have	 fun.With	 the	 introduction	 of	 our	 ERC-20	 utility	
token	 called	Tuurnt	Token	 "TRT",	 hosts	and	 partygoers	are	able	 to	 trade	 services	 in	a	 secure	
payment system	 without	 having	 to	 deal	 with centralized	 middlemen.In	 addition	 to trading services, Tuurnt will have a reward system that recompense partygoers for attending parties and hosts will have bonus tokens when they reach a certain number of positive reviews milestones. Our reason for doing this,is to create a	 closed self-sustainable ecosystem thatsupports user growthand event creation while being decentralized on the blockchain.

Tuurnt lets people pay you to party
https://techcrunch.com/2017/11/01/tuurnt-lets-people-pay-you-to-party/

**Comment by freeatnet** [comment]
Thank you for your request, @dannygkass! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
