### ISSUE TITLE
Add GSTAR Token (GSTAR)

### ISSUE THREAD

**Issue by terence-gstar** [forkdelta/tokenbase#1522]
**Token address:**
0xE64DE17aC4c1AdA2902c652464bb38d44d95d3F7

**Issuer's official website:**
https://gstar.ai

**Description:** 
Bringing algorithmic trading capabilities to the masses, empowering them to trade on level ground with professionals.
The GSTAR Token allows the community to access and use services within the GStar Ecosystem.

**A link to the official contract address confirmation:** 
https://gstar.ai/
(Scroll to near the bottom of the page)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://youtu.be/8Bh9cxblp-U
2. http://elpicudo.com/gstar-objectives-tokens-secrets-ecosystem-and-their-fields-of-participation/
3. https://steemit.com/gstar/@den360/gstar-ai

**Comment by freeatnet** [comment]
Thank you for your request, @terence-gstar! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
