### ISSUE TITLE
Add MinerToken (MIT)

### ISSUE THREAD

**Issue by AllForMiner** [forkdelta/tokenbase#1523]
Token name
MinerToken(MIT)

**Token address:**
0xc45c684c404b2af48ca53229afdc56eb06139808

**Issuer's official website:**
https://forminerpro.com/en

**Description:**   
AllForMiner offers a trading platform where any seller can put their goods for sale. All payments on the trading platform will be made for MIT(MinerToken) tokens, without a fee and are protected by a refund guarantee. 

**A link to the official contract address confirmation:** 
https://etherscan.io/address/0xc45c684c404b2af48ca53229afdc56eb06139808

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://www.linkedin.com/pulse/ico-allforminer-service-platform-cryptocurrency-miners-trafimau/
2. https://youtu.be/nbMxjCH0h_k
3.https://golos.io/ico/@noxlord93/allforminer-is-a-decentralized-service-platform-for-crypto-currency

**Comment by freeatnet** [comment]
Thank you for your request, @AllForMiner ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
