### ISSUE TITLE
Add Presto Token (PRST)

### ISSUE THREAD

**Issue by jubin3424** [forkdelta/tokenbase#1525]
**Token address:**
 0x9f05670b96ecb6e2303e98572712f2edffd28b6c

**Issuer's official website:**
https://presto-platform.io/

**Description:** 
PRESTO automatically generates a secure and efficient smart contract by getting the basic information of the token that the development team wants. 

**A link to the official contract address confirmation:** 
https://presto-platform.io/whatsnew/1

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. http://conference.etnews.com/conf_info.html?uid=91
2. http://www.blockchainnews.co.kr/news/view.php?idx=1786
3. http://www.decenter.kr/NewsView/1S214YD7AX/GZ02
4. http://www.etnews.com/20180622000269
5. https://news.joins.com/article/22611086

**Comment by freeatnet** [comment]
Thank you for your request, @jubin3424! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
