### ISSUE TITLE
Satan Coin ERC20 Token Request

### ISSUE THREAD

**Issue by SatanCoin666** [forkdelta/tokenbase#153]
The contract address.
0xCCcA48874780f9c42b162c9617bC6324c5142C22

A link to the token issuer's official website.
https://satancoin.info/

A couple sentences for token description.
Satan Coin has ascended from the depths of hell to wreak havoc on mortal coins such as Bitcoin/Jesus Coin. With a limited supply of 666, 9 circles of funding, and an ICO from Friday the 13th to Halloween, Satan Coin is obviously the devil's favorite.

A link to an official page confirming the contract address.
https://satancoin.info/funding/

A link to a third-party review or discussion of the token, like an established ICO review blog.
https://themerkle.com/what-is-satancoin/
https://www.coinschedule.com/icos/e1276/satan-coin-ico.html

**Comment by Kryptoniq** [comment]
Verified: 0xCCcA48874780f9c42b162c9617bC6324c5142C22.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
