### ISSUE TITLE
Add AmigoCoin (AMGC)

### ISSUE THREAD

**Issue by AmigoCoinToken** [forkdelta/tokenbase#1530]
**Token address:**
0x41385664aAd657990000004D3906d1572A6bb4c6

**Issuer's official website:**
https://amigocoin.co.uk

**Description:** 

AmigoCoin Cryptocurrency - London Based - Invest in Sold 18ct  Blocks of Gold 12.4kg 

**A link to the official contract address confirmation:** 

https://amigocoin.co.uk/wallet/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.reddit.com/user/AmigoCoin
2 .https://www.facebook.com/amigocoin.co.uk/

**Comment by freeatnet** [comment]
Thank you for your request, @AmigoCoinToken ! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
