### ISSUE TITLE
SPHTX swap token already 

### ISSUE THREAD

**Issue by addoul** [forkdelta/tokenbase#1531]
SPHTX should be better delisted from forkdelta

**What token should be updated?**
https://forkdelta.github.io/#!/trade/SPHTX-ETH

**What about the token should be updated?**
https://www.sophiatx.com/mainnet-announcement-register-for-token-swap/

**Comment by freeatnet** [comment]
Thanks @addoul!

**Comment by rpetrice** [comment]
can you please delist SPHTX ERC-20 token contract ? it is no longer an token running on Ethereum and should NOT be traded.
https://etherscan.io/token/0x3833dda0aeb6947b98ce454d89366cba8cc55528
