### ISSUE TITLE
Add Know Token (KN)

### ISSUE THREAD

**Issue by ntatgss** [forkdelta/tokenbase#1532]
**Token address:**
0xbfd18F20423694a69e35d65cB9c9D74396CC2c2d

**Issuer's official website:**
https://knownetwork.io/

**Description:** 
A new blockchain platform with 2 layers. A next generation blockchain designed for real world transactions. Solving the Cryptocurrency Trust problems. Fast and Transparent.
Know Token will be the utility crypto unit on top of Knowchain until it is swapped to Know Native on Knowchain.

**A link to the official contract address confirmation:** 
https://knownetwork.io/#tokenSale

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.trackico.io/ico/knowchain/
2. https://icobench.com/ico/knowchain/ratings

**Comment by freeatnet** [comment]
Thank you for your request, @ntatgss! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by ntatgss** [comment]
Hi ForkDelta team,

Can I get the update of the process?
