### ISSUE TITLE
Add GULD ERC20 (GULD)

### ISSUE THREAD

**Issue by vcdreyfus** [forkdelta/tokenbase#1534]
**Token address:**
0x9847345de8b614c956146bbea549336d9c8d26b6

**Issuer's official website:**
https://www.guld.io

**Description:** 

Guld is a decentralized internet platform, which allows individuals to take control of their digital identity by controlling all of their digital data using a unified PGP keyring and an advanced blocktree data structure. Development lead by Bitcoin and Crypto Veteran Ira Miller. 

GULD is a utility token. It can be used to register user, group and device accounts to the guld p2p network, this is how you reserve a name in the Guld Name Service (gns). Additionally GULD can be exchanged for GG tokens to be used in Guld Games, or used as-is within the Guld network.

Guld and Ethereum are now able to interact in a number of ways, including cross-chain transactions, identity verification, and publishing.

**A link to the official contract address confirmation:**
https://guld.io/#about

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://steemit.com/crypto/@hilarski/guld-launches-guld-legal-and-guld-erc20
2. https://steemit.com/cryptocurrency/@hilarski/tonight-is-the-launch-party-for-guldcoin-by-ira-miller
3. https://www.youtube.com/watch?v=fH7mFrrvB-Y
4. https://youtu.be/F4RgJl6KRxk

**Comment by freeatnet** [comment]
Thank you for your request, @vcdreyfus! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
