### ISSUE TITLE
Add SmartCityCoinTestNet (SCCTN)

### ISSUE THREAD

**Issue by SmartPeterGT** [forkdelta/tokenbase#1535]
Dear Support, 

we would like to list SmartCityCoinTestNet (SCCTN)

**The contract address:** 0x5fA34CE3D7D05e858b50bB38afa91C8b1a045688
**A link to the token issuer's official website:** https://www.smartcitycointest.net/
**1-3 sentences for the token's description: at least one on the token issuer (eg., the product they are building) and one on the token role:**
The token is issued by Smart City AG, that also runs https://www.smartcityshop.net/ where tokens can already be used to purchase the smart city hardware.
The Smart City Coin Test Net is a utility token aimed to be used within the European Smart City Community. 
Our main goal is to provide Smart House Hardware and Services for the Members of our Community, enabling them to start monitoring their usage in real-time. We also present the business opportunity to all community members they will be able to collect SCCTN tokens in exchange for their energy data.  We are incorporating the blockchain technology and SCCTN Utility Token to provide transparency, traceability, and safety of the entire network and community.

**A link to an official page confirming the above contract address:**  https://www.smartcitycointest.net/scctn/

**Contact email for listing:** peter.faleskini@smartcitycointest.net
**Contact email for general inquiry:** info@smartcitycointest.net

**Comment by freeatnet** [comment]
Thank you for your request, @SmartPeterGT! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
