### ISSUE TITLE
Token Listing [Morpheus Network] [MRPH]

### ISSUE THREAD

**Issue by Sparkt666** [forkdelta/tokenbase#1537]
Morpheus Network
MRPH
Contract: | 0x7b0c06043468469967dba22d1af33d77d44056c8
Decimals: | 4

Official website: https://morpheus.network/
https://morpheus.network/whitepaper/
https://morpheus.network/team/
https://morpheus.network/roadmap/

The Morpheus. Network was designed in consultation with some of the world’s largest shipping, customs & banking firms to create a full-service, global, automated, open supply chain platform with an integrated cryptocurrency payment system utilizing blockchain technology.

https://cointelegraph.com/press-releases/swift-gpi-award-winner-partners-with-morpheus-network-the-worlds-top-global-trade-blockchain-solution

https://medium.com/@themorpheus
https://www.reddit.com/r/MorpheusNetwork/
https://twitter.com/morphcrypto
https://www.facebook.com/themorpheusnetwork/

Contact Email for listing: sparkt666@gmail.com

Thanks, Sparkt.

**Comment by freeatnet** [comment]
Duplicate for #1231.
