### ISSUE TITLE
MOLD (MLD) Token listing request 

### ISSUE THREAD

**Issue by T-V-N** [forkdelta/tokenbase#154]
The contract address.
0x52E30201f31283dc5F7928b4198896083F604416

A link to the token issuer's official website.
https://moldcoin.jp/index.html

A couple sentences for token description.
MOLD is a fair and secure distributed gaming platform which supports the development of new games and simplifies the trading of items, weapons, armors, and other valuable data.

A link to an official page confirming the contract address.
https://moldcoin.jp/index.html

A link to a third-party review or discussion of the token, like an established ICO review blog.
https://bitcoinexchangeguide.com/mold-coin/
https://dewone.zendesk.com/hc/zh-cn/articles/115004867593--D网-上币公示-100047-MOLD-MLD-

**Comment by Kryptoniq** [comment]
Verified 0x52E30201f31283dc5F7928b4198896083F604416.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
