### ISSUE TITLE
Add QuantumPay (QPAY)

### ISSUE THREAD

**Issue by quantumpay** [forkdelta/tokenbase#1541]
Token: QuantumPay
Symbol: QPAY
Decimals: 8
Contract address: 0xcd607fdd69931675f50ea43d3488785367322b4e

Quantum Pay is a Decentralized and Computerized Banker Engine who serves as a financial services platform. As a facility successively on blockchain machinery, Quantum Pay uses digital currency as a little charge doorway to investment, lending, funding and banking, spreading the influence of monetary organizations beyond their existing outlet groundwork to the number of people who are unbanked in the world.

Etherscan:
https://etherscan.io/token/0xcd607fdd69931675f50ea43d3488785367322b4e

whitepaper:
https://quantumpay.co/QUANTUMPAYWP.pdf

Web page
https://quantumpay.co

Confirming smart contract owned posted in webpage
https://quantumpay.co

Github source code
https://github.com/quantumpay/Quantumpay

Social media
Facebook: https://web.facebook.com/QuantumPay/
Telegram: https://t.me/quantumpayQPAY
Twitter: https://twitter.com/quantum_pay
Instagram: https://www.instagram.com/quantum_pay/
Medium: https://medium.com/@quantumpay
SubReddit: https://www.reddit.com/r/quantumpayco/
Reddit: https://www.reddit.com/user/Quantum_Pay/

Bitcointalk Discussion
https://bitcointalk.org/index.php?topic=4623071.0

**Comment by freeatnet** [comment]
Thank you for your request, @quantumpay! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
