### ISSUE TITLE
Add GFC e-auction platform for Agri-commodities (GFC)

### ISSUE THREAD

**Issue by btcsmartads** [forkdelta/tokenbase#1542]
**Token address:**
0x4c2e198CF5Ee4Ca4d6e9e0C1B2b954f9101c7FC1

**Issuer's official website:**
http://www.greekfoodcorridors.com

**Description:** 
Development and implementation of Next Generation e-Auction infrastructure in Greece for Fruit & Vegetables and Olive Oil, and sync with a Commodity Exchange market for Futures contracts based on cryptocurrency. GFC e-auction in Greece: Transforming the way the Agri-market operates in Greece.

**A link to the official contract address confirmation:** 
http://www.greekfoodcorridors.com/#token_gfc

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcoinexchangeguide.com/greek-food-corridors-ico-gfc-token/
2. https://coininfo.news/interview-with-dimitri-haritos-the-president-ceo-of-greek-food-corridors/
3. https://coininfo.news/video-greek-food-corridors-e-auction/
4. http://www.hortidaily.com/article/43012/Greece-New-electronic-auction-allows-growers-to-leave-out-the-middle-man

**Comment by freeatnet** [comment]
Thank you for your request, @btcsmartads! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
