### ISSUE TITLE
Add Greenblockcoin (GBK)

### ISSUE THREAD

**Issue by greenblockcoin** [forkdelta/tokenbase#1544]
**Token address:** https://etherscan.io/token/0x9c417A6B1D2E38e4D1EFe7b981F2B80Bb77cB16B

**Issuer's official website:** https://greenblockcoin.io

**Description:** 
Greenblock is a blockchain based data ecosystem for the global hemp & cannabis industry.
The blockchain will include personal virtual assistance for the management of hemp and cannabis related businesses, as well as provide traceability for each plant, from seed to finished product.
https://greenblockcoin.io/whitepaper/

**A link to the official contract address confirmation:**  https://greenblockcoin.io - on our website, scrolling down the page till "Financial" section, the contract address will be right below it.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://steemit.com/dmania/@ioele75/greenblock-the-new-era-of-cannabis-industry
2. https://bitcoinexchangeguide.com/greenblock-ico-gbk-token/

Thank you very much in advance. If you guys have any questions or need more info please let us know.
Or you can contact me at vasylgolub@yahoo.it

**Comment by freeatnet** [comment]
Thank you for your request, @greenblockcoin! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by greenblockcoin** [comment]
Thank you again. We'll be waiting for your response.
