### ISSUE TITLE
Add QuadCore Chain (QUAD)

### ISSUE THREAD

**Issue by QuadCoreChain** [forkdelta/tokenbase#1545]
**Token address:** 0xe0e705c9bff67188a79dc5f59f0b2675031a6055

**Issuer's official website:** https://www.quadcorechain.com/

**Description:** 

QuadCoreChain is designed to be a smart contract, crypto currency platform, decentralizing Live Streaming of Video. The platform ecosystem is to create favorable conditions within the platform for streamers so that they would able to transfer their fan base from the existing streaming platforms, attracting a seed audience to the platform.

**A link to the official contract address confirmation:** 

https://www.quadcorechain.com/#about

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://medium.com/@drbountyofficial/article-01-quad-6fbf530a6880
2. https://twitter.com/KollolKabir/status/1026140974341222400

**Comment by freeatnet** [comment]
Thank you for your request, @QuadCoreChain! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by QuadCoreChain** [comment]
Thank You for Accepting QUAD Token for Review
Hope We Got Good News from Forkdelta team soon.

Best Regards
QuadCoreChain Team
