### ISSUE TITLE
Add RADION (RADIO)

### ISSUE THREAD

**Issue by amakary** [forkdelta/tokenbase#1547]
Hello Team 
Could you please consider to have our RADIO token listed in your exchange?

--- RADION Info ---

- The contract address: 
0x395A200Ab37e622Ad721f6c0D2fa913b522c84Cf
-----------------
- A link to the token issuer's official website: 
https://etherscan.io/token/0x395a200ab37e622ad721f6c0d2fa913b522c84cf
-----------------
- Token's description: 
RADION is the first record label with blockchain technology. Our system works as music discovery and streaming platform! We have our own Network Distribution to benefit artists, musicians, and bands. RADION empower people to discover, vote, share, and circulate music.
-----------------
- Official Website is: https://radion.fm
-----------------
- Links to third-party reviews or discussion of the token or the token issuer of at least two distinct kinds, 
We will review the information and make the decision based on trustworthiness of the token.
https://www.youtube.com/watch?v=jqY0-kQA6nI
https://cryptoradar.org/ico/radio-ico/
https://www.icoalert.com/?q=radion&is_v=1
-----------------

If you have any questions please email us at : support@radion.fm 
Best

**Comment by freeatnet** [comment]
Thank you for your request, @amakary! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by amakary** [comment]
Thank you very much. I'll look forward to it.
Best
