### ISSUE TITLE
Add AIRDROPSMART (ASMT)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1549]
**Token address:**
https://etherscan.io/token/0x85134746e91b384cff6609505a3f24d5842b20a7

**Issuer's official website:**
https://www.airdropsmart.io

**Description:** 

Airdropsmart is a project to boost social networks.
People need to buy ASMT tokens utilities to use the plateform!

**A link to the official contract address confirmation:** 

https://www.airdropsmart.io ==> linked on the image roadmap

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://cryptototem.com/airdropsmart-asmt-ico/
https://www.reddit.com/user/Olga727/comments/93sm19/airdropsmart_io_airdrop_round_2/
https://www.youtube.com/watch?v=qO-zZm6JXk8

1. 
2.
Website Project : https://www.airdropsmart.io
Airdrop: https://airdrop.airdropsmart.io
Telegram Discussion: https://t.me/Airdropsmart_io
Twitter: https://twitter.com/Airdropsmart_io
Facebook Page: https://www.facebook.com/airdropsmart.io/
Medium Page: https://medium.com/@Airdropsmart_io
Linkedin Article: https://www.linkedin.com/pulse/airdriosmartio-voiloo-voiloo?trk=portfolio_article-card_title
Youtube Channel: https://www.youtube.com/c/airdropsmart

**Comment by freeatnet** [comment]
Thank you for your request, @voiloo! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by voiloo** [comment]
Hello,

I start the distribution of the ERC-20 ASMT tokens, i need an exchange, could you consider my token please ?

https://etherscan.io/token/0x85134746e91b384cff6609505a3f24d5842b20a7?a=0x79a9758b3cbb3550e10be51cbacdccec80794b93

Best Regards
