### ISSUE TITLE
Please list our token on your exchange. Thanks

### ISSUE THREAD

**Issue by ethercarbon** [forkdelta/tokenbase#155]
Please we would like to list our token on your exchange.
Contract address is: 0xb41b531359330d76bbcb0f1a24f94ff6bff30dc1
Token web site is: www.ne5g.io
Sincerely,

Frank W Lin
www.ne5g.io

**Comment by Finestra** [comment]
@ethercarbon there are some missing information in your issue.
You will need to include the following information in your issue:

- A couple of sentences for token description.
- A link to an official page confirming the contract address.
- A link to a third-party review or discussion of the token, like an established ICO review blog.

**Comment by ethercarbon** [comment]
A couple sentences for token description.
CNet5G is an ERC20 Ethereum token, with a symbol of NE5G, that is for the project of fast internet connection and building a local high-speed business circle. Holders will share the revenue of the project based on their holdings of the token.

A link to an official page confirming the contract address.
http://www.ne5g.io/index.html

A link to a third-party review or discussion of the token, like an established ICO review blog.
http://www.londonstockexchange.com/exchange/news/market-news/market-news-detail/other/13499844.html

Thanks
Frank W Lin

**Comment by Kryptoniq** [comment]
Verified 0xb41b531359330d76bbcb0f1a24f94ff6bff30dc1.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
