### ISSUE TITLE
Add Ubricoin (UBN)

### ISSUE THREAD

**Issue by peterkabi** [forkdelta/tokenbase#1550]
**0xCBeAbD17C4545e6Ae5a3B40D49c8c1B896688d85**

**https://ubricoin.ubrica.com**

**We will use Ubricoin to support design, development and implementation of Ubrica project. Ubrica project involves building world class capability for high quality life-science and health-production (LSHP) in the world. We will build a model physical project in Kenya. Ubrica project in Kenya will create a node for highly advanced biomedical research and development, and highest quality health care services.** 

**https://ubricoin.ubrica.com/buy-ubricoin/** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.youtube.com/watch?v=awJvsB4beyM&t=446s
2.https://www.youtube.com/watch?v=yTz1rLs-3lM&t=13s

**Comment by freeatnet** [comment]
Thank you for your request, @peterkabi! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
