### ISSUE TITLE
Add GoatCash (GOAT)

### ISSUE THREAD

**Issue by goatcash** [forkdelta/tokenbase#1551]
Hello Team
Could you please consider to have our GOAT token listed in your exchange?

--- Goat Cash Info ---

The contract address:
0x9f452e458b024e82d6e3ff50a07b8de74c988523
A link to the token issuer's official website:
https://etherscan.io/token/0x9f452e458b024e82d6e3ff50a07b8de74c988523
Token's description:
Artificial Goat Intelligence (AGI), is an advanced goat learning algorithm that's been learning about goats for years. Inspired by Jiang-Yang's "Not Hotdog" world changing technology.

Goat Quality Indicator (GQI), is a standard unit of measure associated with the quality of a goat. Based on multiple heuristics a score is applied, the higher, the greater the goat quality the greater the airdrop reward.

GOATbot, our tireless virtual goat that works its socks-off to deliver the rewards that you all deserve.

⭐Airdrop ⭐

GOAT tokens will be distributed via our AGI (Artificial Goat Intelligence) dApp, which uses advanced "Not Goat, Is Goat" technology. It validates goats and the associated GQI. The higher the GQI score the greater the token distribution. 

Goat Gestation (staking) periods are taken into account as well. Gestated tokens will get additional airdrops if they are held for a specified amount of time.

Submission of goats can be via our dApp or via other channels, such as Telegram and Twitter.

⭐IRL Goatdrop ⭐

Goats are hilarious animals and they give us many hours of enjoyment. They also provide much needed sources of food and income for less fortunate communities in the world. We're striving to team up with NGOs (non-profit organization) to donate goats to the less fortunate in the world. The smart contract has an air gapped Goat Fund that will be utilised to fund these IRL Goatdrops.
Official Website is: https://goat.cash
BitcoinTalk: https://bitcointalk.org/index.php?topic=4845277
If you have any questions please email us at : hello@goat.cash

Best

**Comment by freeatnet** [comment]
Thank you for your request, @goatcash! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
