### ISSUE TITLE
Add Catholic Coin (CTC)

### ISSUE THREAD

**Issue by catholiccoins** [forkdelta/tokenbase#1552]
**Token address:**
0xB6eC8C3a347f66a3d7C4F39D6DD68A422E69E81d

**Issuer's official website:**
https://catholiccoins.org/

**Description:** 

Founded in 2018 for Catholic investors, our foundation is a non-profit built upon the bedrock of charitable giving and digital currencies.

Leveraging blockchain technology in accomplishing various charity-driven projects that support good causes and emancipate humanitarian initiatives.

**A link to the official contract address confirmation:** 

https://catholiccoins.org/wallet/index.html
-> click "verifed etherscan" button to go to token contract or find token contract address

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://cryptodemystified.in/catholic-coin-review-and-analysis/

2. http://www.nbc12.com/story/38561426/introducing-catholic-coins-an-ethereum-decentralized-cryptocurrency-that-fosters-global-charitable-donations

3. http://www.digitaljournal.com/pr/3859289

4. http://markets.financialcontent.com/stocks/news/read/36635342

5. http://www.ussharemarkets.com/story/172866/catholiccoins-the-leading-and-the-best-cryptocurrency-charity-platform-that-uses-blockchain-technology-to-accomplish-humanitarian-initiatives.html

6. http://markets.buffalonews.com/buffnews/news/read/36635342/

7. http://www.fox8live.com/story/38590975/catholic-coins-fostering-charitable-donations-using-cryptocurrency

8. http://www.fox19.com/story/38590975/catholic-coins-fostering-charitable-donations-using-cryptocurrency

9. http://www.telemundolubbock.com/story/38590975/catholic-coins-fostering-charitable-donations-using-cryptocurrency

**Comment by freeatnet** [comment]
Thank you for your request, @catholiccoins! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by catholiccoins** [comment]
Hello 
any updates on this?
thanks for your time
Regards
