### ISSUE TITLE
Add Dicet (CET)

### ISSUE THREAD

**Issue by knivd** [forkdelta/tokenbase#1553]
Name: Dicet
Ticket: CET
Decimals: 18
Contract: https://etherscan.io/token/0xf660ca1e228e7be1fa8b4f5583145e31147fb577

The Dicet is a utility token acting a unit representative bridge between the native DICE ecosystem and the blockchain. DICE is a cryptocurrency with specific properties and designed for everyday use and fundraising through targeted crowdmining.

Website: https://dice.money

**Comment by freeatnet** [comment]
Thank you for your request, @knivd! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
