### ISSUE TITLE
0x8bb78ceb6aa8950d5e263e6adad9d62e9322000a

### ISSUE THREAD

**Issue by mikolas22** [forkdelta/tokenbase#1554]
**Token address:**

**Issuer's official website:**

**Description:** 

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by freeatnet** [comment]
Please follow the format and fill out the details when requesting addition of a new token. Thanks!
