### ISSUE TITLE
Add Dragonglass (DGS)

### ISSUE THREAD

**Issue by mikolas22** [forkdelta/tokenbase#1555]
**Token address:** 0x8bb78ceb6aa8950d5e263e6adad9d62e9322000a

**Issuer's official website:**https://dragonglass.com/

**Description:** Donation https://etherscan.io/address/0x3a2aedc3b54a99e429ae36637681d4560ce5c05b#tokentxns

**A link to the official contract address confirmation:** https://twitter.com/dragonglasscom

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**https://bitcointalk.org/index.php?topic=2934765

1. 
2

**Comment by freeatnet** [comment]
Thank you for your request, @mikolas22! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
@mikolas22 Please include a link to the official contract address confirmation. Contract address confirmation MUST be on or linked from the official website and MUST be visible publicly. If the confirmation is not visible immediately, include an explanation of how to find it.
