### ISSUE TITLE
Add Scaltinof (SCAL)

### ISSUE THREAD

**Issue by Scaltinof** [forkdelta/tokenbase#1556]
Hello,

Token address:

https://etherscan.io/token/0x296ec7b2b224ea122f8f8f9be2a824df092fc82c

Issuer's official website:

https://scaltinof.com/

Description:0x296ec7b2b224ea122f8f8f9be2a824df092fc82c

Scaltinof is based on ERC20/ERC223, which is the token made by the Japan.
Scaltinof, conceived in the June of 2018, is the alternative cryptocurrency developed in Japan. It is based on the popular SCALII art character, Aramaki Scaltinof.

A link to the official contract address confirmation:

https://etherscan.io/token/0x296ec7b2b224ea122f8f8f9be2a824df092fc82c

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://twitter.com/Scaltinofcoin?lang=en
https://discord.gg/UamJbRx
https://www.facebook.com/Scaltinof-184656725578059/
https://scaltinof.com/blog/

-----------------------

TokenName:Scaltinof
TokenSymbol:SCAL
Decimals:8

E-mail:info@scaltinof.com

Thank you.

**Comment by freeatnet** [comment]
Thank you for your request, @Scaltinof! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Scaltinof** [comment]
I am looking forward to listing.Thank you.
