### ISSUE TITLE
Add CryptoAngel (ANGEL)

### ISSUE THREAD

**Issue by Vl4d4n7** [forkdelta/tokenbase#1557]
**Token address:**
www.crypto-angel.com

**Issuer's official website:**
www.crypto-angel.com

**Description:** 

A blockchain based AI life assistant, designed to enhance human thinking, planning, and decision-making process.
ANGEL Token will be used to reward Developers (individuals who will create the models and will receive compensation for how their models perform and how much they help the users.) and End users (those who actually use the models for goal reaching and will pay if the model helps them achieve their goals) And lastly, miners (those who help the processing of the models and will be paid for their work as well) 

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xe7fad78cf9034b36b6a7dc2951e5acf8d28e4dc7

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://www.allcrypto.com/analysis/crypto-angel-is-the-virtual-life-assistant-powered-by-a-i/
2. https://bitcoinexchangeguide.com/crypto-angel-ico/

**Comment by freeatnet** [comment]
Thank you for your request, @Vl4d4n7! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
