### ISSUE TITLE
Add K Systems LTD Token (KSYS)

### ISSUE THREAD

**Issue by molternative** [forkdelta/tokenbase#1559]
**The contract address:** 0x47ac345d3aF5631cff14c8942a9c31d23f0319d9

**A link to an official page confirming the above contract address:**
https://ico.ksystems.io/token-sale/ (it is written in the FAQ section)

**Link to our Website:** https://ico.ksystems.io/

**Smart contract information:** https://etherscan.io/address/0x47ac345d3af5631cff14c8942a9c31d23f0319d9

**Token name:** K Systems LTD Token
**Token symbol:** KSYS
**Token decimals:** 18

**The White Paper:** https://ksystems.io/DOCS/WhitePapers/KSYS_White_Paper_EN.pdf

**Short Description.**
K Systems LTD develops decentralized applications (dApps) based of the Ethereum Blockchain and InterPlanetary File System (IPFS). Our AS/EN 9100 compliant dApps help Aerospace and Automotive industries achieving the maximum quality standards and help startups creating their launch platforms. Our K-Economy is powered by the KSYS Token. Also, all of the K Systems LTD products and services are only purchasable with KSYS Tokens.

**Logo (150x150):** https://ico.ksystems.io/wp-content/uploads/2018/03/token-150x150.png

**Links third-party review or discussion of at least two kinds:**

ANN Thread: https://bitcointalk.org/index.php?topic=4767652.0

Some of Bitcointalk comments:

- https://bitcointalk.org/index.php?topic=4767652.msg43284371#msg43284371

- https://bitcointalk.org/index.php?topic=4767652.msg43263925#msg43263925

- https://bitcointalk.org/index.php?topic=4767652.msg43245320#msg43245320

ICO Trackers:

- https://foxico.io/project/ksystems

- https://foundico.com/ico/ksys-token.html

 (some info is outdated, but the team is verified)

**Social Media:**
Telegram - https://t.me/ksystemsGroup
Twitter: https://twitter.com/ksystemsio
Instagram: https://www.instagram.com/k.sys.ltd
Facebook: https://www.facebook.com/ksystemslondon/
LinkedIn: https://www.linkedin.com/company/k-systems-ltd/

**Optional questions:**
Q - Do you represent the token issuer or are you simply an interested member of the community?
A - I am a part of the project’s team.

Q - How was this token distributed?
A - Early supporters, team members and bounty rewards.

Q - Is there more information on the token issuer that is separate from the token? Example: Information about a parent company.
A - The info about K Systems LTD is available on our main page https://ico.ksystems.io/

**Comment by freeatnet** [comment]
Thank you for your request, @molternative! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
