### ISSUE TITLE
Add Golix Token (GLX)

### ISSUE THREAD

**Issue by tkembo** [forkdelta/tokenbase#1562]
**Token address:**
0xe430dce57cb6e3afc6216c710870bed0680d018a

**Issuer's official website:**
https://golix.com

**Description:** 
Golix is Africa's biggest cryptocurrency exchange. It's already live and available in 7 African countries.

**A link to the official contract address confirmation:** 
https://golix.com/contract_address

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://edition.cnn.com/2017/10/31/africa/zimbabwe-bitcoin-surge/index.html
2. https://www.gsb.stanford.edu/faculty-research/case-studies/bitfinance-revolutionizing-zimbabwes-fragile-economy-bitcoin

**Comment by freeatnet** [comment]
Thank you for your request, @tkembo! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
