### ISSUE TITLE
LENDELTA token - Listing Request

### ISSUE THREAD

**Issue by LENDELTA** [forkdelta/tokenbase#1563]
**Token address:**
0x61ded342e74b0a463f1d15cf399b97d265893ca5

**Issuer's official website:**
https://lendelta.co/

**Description:** 
Lendelta is a working intelligent trading platform. It is a self-managing financial system with P2P transaction based on open source platform, developed as Ethereum token ERC20 and running on the Ethereum blockchain. All the team members behind LENDELTA have a dream to make DLTA the first AI Trading Bot of its kind.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x61ded342e74b0a463f1d15cf399b97d265893ca5

https://wizard.poa.network/crowdsale?addr=0x61dED342E74B0a463F1D15cf399B97D265893Ca5&networkID=1

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.globalfromasia.com/investments/lendelta-ico-review/
2. https://bitcoinexchangeguide.com/lendelta-ico-dlta-token/

**Comment by freeatnet** [comment]
Thank you for your request, @LENDELTA! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
