### ISSUE TITLE
Block fake ABL token trading

### ISSUE THREAD

**Issue by jaewanLee** [forkdelta/tokenbase#1564]
hi i'm PRManager & developer in Airbloc(ABL)
the abl token which is listed now int forkDelta, is not official one.
the official contract is 0xf8b358b3397a8ea5464f8cc753645d42e14b79EA

would you please remove that token or fix contract address.
all of the user who buy abl in forkdelta are buying scam coin, not abl.

if you want any support or check something
plz email to ian_hodge@airbloc.org

**Comment by freeatnet** [comment]
@jaewanLee Hi there! Could you please provide a link to the token that has raised this concern? Thanks!

**Comment by jaewanLee** [comment]
hi, thanks for reply
here is the link on forkdelta.
https://forkdelta.github.io/#!/trade/0x764859b7991b5af66efa6a6211064724974e0aa5-ETH

This is the address of the fake Airbloc Protocol’s smart contract that was used by the scammer.
https://etherscan.io/address/0x764859b7991b5af66efa6a6211064724974e0aa5

below is the reason why that smart contract is scammer.
(1) Only has 57 transactions
(2) Tap into “Code” section and you’ll find that the original source code has not been revealed or verified
(3) “Token Tracker” section points to some random token that only shares the same name without valid symbol image

This is the address of real Airbloc Protocol’s smart contract.
https://etherscan.io/address/0xf8b358b3397a8ea5464f8cc753645d42e14b79ea

(1) Tap into “Code” section and you can check the real source code verified by Etherscan, uploaded by our team
(2) The “Token Tracker” points to the token with the right symbol image

and you can contact with Airbloc official team with email(contact@airbloc.org) or their official website (airbloc.org)
 
please take care this issue seriously for defending investor from the scam.
Warmest
ian.

**Comment by freeatnet** [comment]
@jaewanLee Thanks for the details!

Airbloc contract address confirmation in a blog post linked from the official site: https://medium.com/airbloc/fake-abl-tokens-and-scam-protection-guide-4118eecd6bfc ((archived copy)[http://archive.li/Ll0My]) (plus, features the same scam contract address).

I have removed the order book for the fake token.

Please let me know if there are any additional concerns.

**Comment by therealMikkoK** [comment]
Just noticed the real token is missing from FD. Should the team make a pull request for the actual ABL token? @freeatnet

**Comment by jaewanLee** [comment]
@freeatnet oh great!!
Thank you for your quick response
it will be great helps to us and investor
thank you for your consideration and response again!

**Comment by freeatnet** [comment]
@jaewanLee you can help us by creating a request via https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md :)
