### ISSUE TITLE
Add Fantasy Sports Coin (FNTC)

### ISSUE THREAD

**Issue by FNTCSports** [forkdelta/tokenbase#1565]
1. Contract Address: 0x3ff283f4b333f0c046dea47938a413a2bae56bf5
https://etherscan.io/token/0x3ff283f4b333f0c046dea47938a413a2bae56bf5

2. [www.fntcsports.com](www.fntcsports.com)

3. Fantasy Sports Coin [FNTC] is a universal payment gate for fantasy sports platforms and a universal cryptocurrency for the sports sector. FNTC is used on the FNTC Fantasy platform to collect, store, and transfer all league funds and winnings. 

4. https://etherscan.io/token/0x3ff283f4b333f0c046dea47938a413a2bae56bf5

5. https://finance.yahoo.com/news/fntc-sports-bringing-playbook-fantasy-090000930.html

https://stocktwits.com/symbol/FNTC.X

Email: info@fntcsports.com

We look forward to speaking with you about your listing process.

**Comment by freeatnet** [comment]
Thank you for your request, @FNTCSports! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
