### ISSUE TITLE
Add DIECI (DCI)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1566]
**Token address:**
https://etherscan.io/address/0x6dacc728189c83659a69870d6e53cd271d66072d

**Issuer's official website:**
https://dieci.network/#

**Description:** 
DIECI is a next generation Blockchain platform that uses a neural consensus algorithm to increase scalability linearly. It is planned to have cross-compatibility between different chains such as Bitcoin and Ethereum. DIECI is made by the HonorDev team whom have developed other breakthrough products such as HonorDrive IPFS.

**A link to the official contract address confirmation:** 
https://dieci.network/#
On the front page or ERC20 tab

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://cryptoreviewing.wordpress.com/2018/08/11/dieci-is-the-next-ethereum/
http://reviewingico.blogspot.com/2018/08/dieci-reviewing-ico-1.html

1. http://reddit.com/r/dieci
2. t.me/DieciChain

**Comment by freeatnet** [comment]
Thank you for your request, @honordrive! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
