### ISSUE TITLE
Add Contractium (CTU)

### ISSUE THREAD

**Issue by contractium** [forkdelta/tokenbase#1567]
Dear Forkdelta,

My name is Hung, co-founder & CEO of Contractium.io.
We would like to list CTU on forkdelta exchange.
Please help us with this.

**Here is a brief of our information:**

1. One sentence description

Contractium helps users deploy smart contract and issue tokens on blockchains easily without technical knowledge & skills

2. Full description:
a)What
We create Contractium (Contractium.io), a decentralized software that based on Ethereum smart contract.
Contractium helps general users create smart contract easily, securely and trustless to work together, without technical skills.
Contractium helps business users issue tokens easily on blockchain network, firstly on Ethereum network, without technical skills.
b) Mission:
	•	Help contracter & contractee sign the commercial smart contract easily & trustfully. 
	•	Make commercial smart contract easy & secured. 
	•	Help users earn extra money with their online consumption. 
c) Vision:
	•	Internet users' smart contract application. 
	•	Eliminating print contract. 
	•	Replacing online traditional rewards/bonus system. 
3. Official links:
Website: https://contractium.io/

ICO page: https://ico.contractium.io/
Whitepaper: http://bit.ly/2M7yUry  
Telegram: https://t.me/contractium

Facebook: https://www.facebook.com/contractium.io

Twitter: https://twitter.com/contractium

Gihub: https://github.com/contractium

Youtube channel: https://www.youtube.com/channel/UCdNLXQrp7sn6lNeqOYOz_wQ

Youtube clip for private sales: https://youtu.be/zT59_Yr6vVI  

Linkedin: https://www.linkedin.com/company/contractium-io/

Medium: https://medium.com/@contractium.io 

[ANN bitcointalk] https://bitcointalk.org/index.php?topic=4613530

Product 1 (primary): https://tokenize.contractium.io/

Product 2: https://mvp.contractium.io/

Bounty campaign URL: https://dashboard.contractium.io/user/bounty

Bounty bitcointalk: https://bitcointalk.org/index.php?topic=4602899.msg41549850#msg41549850 

Airdrop campain URL: https://contractium.io/airdrop.html 

Smart contract address: https://etherscan.io/address/0x943aca8ed65fbf188a7d369cfc2bee0ae435ee1b

Thank you Forkdelta.

**Comment by freeatnet** [comment]
Thank you for your request, @contractium! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
