### ISSUE TITLE
Add Ve Gold Z1 (VGLZ1)

### ISSUE THREAD

**Issue by bapickett** [forkdelta/tokenbase#1568]
SYMBOL: VGLZ1
Contract: 0xd1ec43b9d44338a4e74f3f41cd1b86254cbaa874

**Token address:**
https://etherscan.io/token/0xd1ec43b9d44338a4e74f3f41cd1b86254cbaa874

https://veritas.veritaseum.com/

VGLZ1 is a sub-token of VERI (VERITASEUM) Ecosystem
VGLZ1 is a digital token asset representing 1oz physical fine .999 gold that can be exchanged and then redeemed via the Veritaseum website, or VeADIR Dapp after KYC is provided.

Overview:
https://veritas.veritaseum.com/index.php/component/edocman/veassets-peer-to-peer-blockchain-based-physical-asset-ownership-in-bearer-form/viewdocument?Itemid=

Contact address:
brettpickett@gmail.com
masiah@veritaseum.com
eleanor.reid@veritaseum.com

Review:
https://youtu.be/Wj95AXS_6DU

Social Media Channel
1. https://twitter.com/ReggieMiddleton
2. https://t.me/joinchat/G_22OhA7UgN6b-7hTSFSTA
3. https://veritas.veritaseum.com/ve-blog

**Comment by therealMikkoK** [comment]
@bobbypaintsstuf you can self-assign to this

**Comment by therealMikkoK** [comment]
The presentation in the request contains all pertinant information. I see no reason to halt the token.
R1 👍
Needs another opinion, due to possible conflict of interest.

**Comment by freeatnet** [comment]
Closed by #1687.
