### ISSUE TITLE
Add Epintoken (EPTK)

### ISSUE THREAD

**Issue by Epintoken** [forkdelta/tokenbase#1569]
**Token address:**
[https://etherscan.io/token/0xa91ff20bd37d9275498aa468351c14ff2c290a99
](https://etherscan.io/token/0xa91ff20bd37d9275498aa468351c14ff2c290a99
)
**Issuer's official website:**
[https://epintoken.com](https://epintoken.com)

**Description:** 

EPTK is decentralized  platform operating on Blockchain.
EpinToken (EPTK) is erc20 based Token.  It is used to simplify the EPIN buying process and game goods trading Experience with blockchain technology.

**A link to the official contract address confirmation:** 

[https://epintoken.com/#token-details](https://epintoken.com/#token-details)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://medium.com/@brindhamenaka/epintoken-contract-migration-b7894bb4cb3f
2. https://cryptodigestnews.com/bounty-program-epintoken-airdrop-84cec3ea14b8

 Social Media: 
Twitter:  https://twitter.com/EpinToken
Telegram: https://t.me/EpinToken
Reddit: https://www.reddit.com/user/EpinToken

Contact : Info@epintoken.com

**Comment by freeatnet** [comment]
Thank you for your request, @Epintoken! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by Epintoken** [comment]
How much time does it takes.. Kindly please list ASAP.

**Comment by freeatnet** [comment]
@Epintoken Is there a reason you need expedited review?

**Comment by Epintoken** [comment]
on Aug 20th going to lunch 2 more exchanges at same time

**Comment by freeatnet** [comment]
@Epintoken Sorry, August 20th will not be workable from our side.

**Comment by Epintoken** [comment]
Sir any update please.

**Comment by Epintoken** [comment]
Hi sir we have updated our solidity Contract Coda. and Made lots of changes, New Updates. Kindly review and list our token on your platform this is the biggest step for our Program.

**Comment by Epintoken** [comment]
New Contract Details has been updated. and also our Contract successfully verified by Etherscan.io
