### ISSUE TITLE
BitFlux [FLX] Listing Request

### ISSUE THREAD

**Issue by Psychovisual** [forkdelta/tokenbase#157]
We are the BitFlux Team Developers and we believe that decentralized rewards and platforms for content is the future of content creation as a whole. Our vision is that of a community taking content creation into their own hands and decentralizing rewards using blockchain technology.

As the Internet is an ever evolving web of creativity and self-expression we feel that these
platforms should be evolving along with it. Not restricting or overbearing as so many platforms
are doing these days.

On top of the lack of freedom of expression and creativity, content creators are seeing more
and more of their hard fought earnings being stolen away from them by big companies who
seek only to make more profit from off them while offering nothing in return

On every content creation and streaming platform there is a value that is transferred between users, called likes, follows or subscribers. Whether its a stream, blog or video. Likes are a form of recognition that show the content creators they have done a good job and they become an incentive for creating new content. However, since there are an unlimited amount of likes, you can never run out of them, therefore they have no real value and users give away likes for free on low quality content. BitFlux is a limited supply and freely transferable token that creates value for appreciation of content. If you wish to gift a content creator you would have to consider whether the content is worth the value but on the other hand you can give out as much as you have available so it gives real value to the rating of content. What is special about our project is that it will have a ranking system to show which content creators have been gifted the most Tokens. We have already airdropped 30 million tokens to our community. On top of that we are distributing 40% of the total supply directly to content creators through partnerships or bounties. This will not only market the token to a huge audience but also help create links within the community and help strengthen it as a whole.

BitFlux is a Utility token designed to attribute value to the appreciation of content on the web through a decentralized reward system for content creators and viewers.

Contract Address : 0x70b147e01e9285e7ce68b9ba437fe3a9190e756a
Official Website : https://fluxproject.xyz/
Whitepaper: https://fluxproject.xyz/gallery/whitepaper_2.1_eng.pdf

Link to Verified Token On Etherscan : https://etherscan.io/token/0x70b147e01e9285e7ce68b9ba437fe3a9190e756a?a=0x6b6a6e24bee0256d3facf5d37e63f885881826ed

BitCoinTalk Ann Thread : https://bitcointalk.org/index.php?topic=2704680.0
Independent Review : http://somethingdecent.co.uk/crypto/airdrop-alerts/airdrop-alert-bitflux-flx/

Twitter:  https://twitter.com/flux_project
Reddit: https://www.reddit.com/r/FLUXProject/
Telegram: t.me/fluxproject

Your Decentralized platform is the perfect medium for our project and we are actively promoting your platform to our community and supporters.

We look forward to our long and prosperous partnership

Kind Regards,
BitFlux Team
---
addr: '0x70b147e01e9285e7ce68b9ba437fe3a9190e756a'
decimals: 18
description: >-
  Decentralized rewards for content creators on the web.
  
  BitFlux is a utility token designed to attribute value to the appreciation of content on the web through a decentralized reward system for content creators and viewers.
name: BitFlux
symbol: FLX

**Comment by Kryptoniq** [comment]
Contract address confirmed 0x70b147e01e9285e7ce68b9ba437fe3a9190e756a.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
