### ISSUE TITLE
Token listing

### ISSUE THREAD

**Issue by fadeless99** [forkdelta/tokenbase#1571]
Hello great support, please I'll like to request for the official addition of CyberChain (Cyber) to be listed on the exchange. Here's the etherscan address https://etherscan.io/token/0x17e16d30a05324b44cf78df847137fa1220448f8. And if there's anything you wish to ask, please mail me through Walegivers@gmail.com or you should send message directly to the Cyber direct twitter account https://twitter.com/Cyber_token. Thanks in anticipation

**Comment by freeatnet** [comment]
Closing in favour of #1572.
