### ISSUE TITLE
Add CyberChain (Cyber)

### ISSUE THREAD

**Issue by fadeless99** [forkdelta/tokenbase#1572]
**Token address:**
0x17e16D30a05324B44CF78Df847137Fa1220448f8

**Issuer's official website:** 
https://cyberchainnetwork.com

**Description:** 
CyberChain is a platform Decentralized security system in internet connection

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x17e16d30a05324b44cf78df847137fa1220448f8

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?action=profile;u=1548756;sa=summary
2. https://www.facebook.com/adewale.sodiq

**Comment by freeatnet** [comment]
Thank you for your request, @fadeless99! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
