### ISSUE TITLE
Add Topscoin (TPC)

### ISSUE THREAD

**Issue by moneylinks** [forkdelta/tokenbase#1573]
yes joined
**Token address:**
0x414b23b9deb0da531384c5db2ac5a99ee2e07a57
**Issuer's official website:**
https://topscoin.net

**Description:** 
Topscoin  (TPC)  is an ico token which Is built in Ethereum. Investors can use services to divide their investments between various services like P2P loans, crowdfunding, etc. The first version of the TPC allows startups to launch and manage crowdfunding and ICO campaigns.
**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x414b23b9deb0da531384c5db2ac5a99ee2e07a57

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. none
2.none

**Comment by freeatnet** [comment]
Thank you for your request, @moneylinks! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
