### ISSUE TITLE
Add Etherisc (DIP)

### ISSUE THREAD

**Issue by henark** [forkdelta/tokenbase#1574]
Token address:
https://etherscan.io/token/0xc719d010b63e5bbf2c0551872cd5316ed26acd83

Issuer's official website:
https://etherisc.com/

Etherisc (DIP) is building a platform for decentralized insurance applications. With visionaries
like you, we can create a platform full of opportunities across the industry’s value chain.
Corporates, large and small, not-for-profit groups and insurtech startups can all come
together to provide better products and services.

A link to the official contract address confirmation:
https://etherscan.io/address/0xc719d010b63e5bbf2c0551872cd5316ed26acd83

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://www.smithandcrown.com/sale/etherisc/   
https://icobench.com/ico/etherisc

**Comment by freeatnet** [comment]
Thank you for your request, @henark! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
