### ISSUE TITLE
Countinghouse Fund token listing (CHT)

### ISSUE THREAD

**Issue by Mike-Countinghouse** [forkdelta/tokenbase#1575]
**Token address:**
0x799d214d7143b766cdd4979cd0280939288ba931

**Issuer's official website:**
www.countinghousefund.com

**Description:** 
Countinghouse Fund uses algorithmic trading software originally developed for their successful Foreign Exchange fund on the crypto-exchanges, forcing profit through market volatility. Countinghouse is a closed-ended fund that uses tokens as unit holdings. 

**A link to the official contract address confirmation:** 
www.countinghousefund.com/ico

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  www.countinghousefund/ico has hundreds of reviews including listing sites, youtube reviewers etc
2.

**Comment by freeatnet** [comment]
Thank you for your request, @Mike-Countinghouse! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by freeatnet** [comment]
More information may be available in #1592.

**Comment by Mike-Countinghouse** [comment]
We've got a lot of volume using just our contract address: https://forkdelta.app/#!/trade/0x799d214d7143b766cdd4979cd0280939288ba931-ETH

We'd love to see our CHT listed properly soon on your platform.

**Comment by Chris-CHT** [comment]
Following up to see if we can provide any further information to progress the review?
