### ISSUE TITLE
Listing CNet5G token

### ISSUE THREAD

**Issue by ethercarbon** [forkdelta/tokenbase#158]
Dear Sir or Madam, please help list our token on your exchange. Thanks

The contract address: 0xb41b531359330d76Bbcb0f1a24F94FF6Bff30Dc1

A link to the token issuer's official website. 
www.ne5g.io

A couple sentences for token description. 
CNet5G is an ERC20 Ethereum token, with a symbol of NE5G, that is for the project of fast internet connection and building a local high-speed business circle. Holders will share the revenue of the project based on their holdings of the token.

A link to an official page confirming the contract address.  
http://www.ne5g.io/index.html

A link to a third-party review or discussion of the token, like an established ICO review blog.
http://www.londonstockexchange.com/exchange/news/market-news/market-news-detail/other/13499844.html

Thanks
Frank W Lin

**Comment by Kryptoniq** [comment]
Duplicate #155.
