### ISSUE TITLE
Add Cashpayz Token (CPC)

### ISSUE THREAD

**Issue by rehmat78** [forkdelta/tokenbase#1583]
Name of the token:
Cashpayz Token

Symbol of the token:
CPC

The contract address:
0x6aBb492D778903be5fb8922e076cA5e337E29062
The official website:
https://cashpayzcoin.com

The description for the token:

Cashpayz online crypto processing will instantly allow everyone to use cryptocurrencies for all types of payments. The growth of our industry is projected to develop exponentially. This is where the money is today and this is where more money will be tomorrow.
https://etherscan.io/token/0x6abb492d778903be5fb8922e076ca5e337e29062

Social Media link of the token:
Bitcointalk - https://bitcointalk.org/index.php?topic=4684425.new
Github source - https://github.com/CashPayz/smart-contract
Twitter - https://twitter.com/CashpayzCoin
Facebook - https://www.facebook.com/cashpayzcoin/
Telegram - https://t.me/cashpayzcoin
Youtube - https://www.youtube.com/channel/UC2MzZVZYIgDeZKyetfY6-XA
LinkedIn - https://www.linkedin.com/in/cashpayz-coin-73a850168/
Slack - https://cashpayzcoin.slack.com/
Medium - https://medium.com/@cashpayzcoin
Reddit - https://www.reddit.com/u/cashpayzcoin

Thanks.

**Comment by rehmat78** [comment]
Erc20 based profitable 
cashpayz token

**Comment by freeatnet** [comment]
Thank you for your request, @rehmat78! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- All communication regarding your request will be posted here. We will not ask you to move conversation to email or a messenger. You can always see all replies on this page.
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.
