### ISSUE TITLE
Add Global Crypto Alliance CALL (CALL)

### ISSUE THREAD

**Issue by irdd** [forkdelta/tokenbase#1586]
**Token address:**

0x886785c4e5a161259c41cbcd45cd42513a95320a

Ticker: CALL

**Issuer's official website:**

https://gcalliance.io

**Description:** 

The Global Crypto Alliance (GCA) is an international decentralized institution formed by teams of professionals in diverse areas of blockchain computing, cryptocurrencies and business development. It aims to address several major issues in the fast growing blockchain industry by developing services and technology utilizing blockchain. GCA has developed the first ERC777 token standard used for payment for services provided by each department.

**A link to the official contract address confirmation:** 

etherscan: https://etherscan.io/token/0x886785c4e5a161259c41cbcd45cd42513a95320a

(Available link also via GCA website on first page)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

0. https://info.binance.com/en/currencies/global-crypto-alliance

1. https://medium.com/global-crypto-alliance

2. https://bitcointalk.org/index.php?topic=4869498.msg43859776#msg43859776

3. Twitter: bit.ly/GCAtwitter

4. TG: bit.ly/GCAtg

5. TG (NEWS): t.me/gcanews

6. FB: bit.ly/GCAface

7. Bitcointalk: bit.ly/GCAbitc

8. Discord: bit.ly/GCAdis

9. Medium: bit.ly/GCAmedi

10. REDDIT: bit.ly/GCAredd

11. SteemIt: bit.ly/GCAsteem

12. ETHScan: bit.ly/GCAether

Global Crypto Alliance 
Listing manager

**Comment by freeatnet** [comment]
Thank you for your request, @irdd!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1586.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1586.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
