### ISSUE TITLE
Add Yooba Token (YOO)

### ISSUE THREAD

**Issue by fly31318** [forkdelta/tokenbase#1587]
The token is trading on forkdelta. https://forkdelta.app/#!/trade/0x1d4105534da120da243281cfc3f26aaf038e2d6f-ETH
But that just some guys used contract address to make that.Not a formal form of forkdelta.We want YOO list in the drop-down list.
### Token address:
0x1d4105534da120da243281cfc3f26aaf038e2d6f
### Issuer's official website:
https://yooba.org
### Yooba description
1.Yooba is committed to allowing all consumers to conduct global consumption security, privacy, freedom, and convenience through one account; and is committed to establishing a global,
decentralized, transparent, fair, and dynamic business platform.
2.Yooba Token (YOO) is used as Yooba System's internal commodity trading medium.

### A link to the official contract address confirmation
https://etherscan.io/token/0x1d4105534da120da243281cfc3f26aaf038e2d6f

The official address has been confirmed by Etherscan.

### At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://steemit.com/airdrop/@jibupune/yooba-project-announces-that-airdrop-stage-3-global-is-alive-and-yooba-hiring-people-around-the-world
https://www.youtube.com/watch?v=zQeqP7b0mvg
https://icoholder.com/en/yooba-23121

**Comment by fly31318** [comment]
We want YOO list in the drop-down list soon.Thanks.

**Comment by freeatnet** [comment]
Thank you for your request, @fly31318 !

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1587.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1587.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
