### ISSUE TITLE
Add Yield Coin (YLD)

### ISSUE THREAD

**Issue by tenshimatt** [forkdelta/tokenbase#1588]
**Token address:**
0x7f927f984177323c4ac49e6b1d398e40cd1a78f6

**Issuer's official website:**
www.myyield.io

**Description:** 
Yield Coin is a multi purpose token which is accepted at businesses in our network. One main project is a social media platform that provides Education for trading, crypto and investments. We will use our token to remunerate people for improving their understanding of how to manage their finances 

**A link to the official contract address confirmation:** 

https://etherscan.io/address/0x7f927f984177323c4ac49e6b1d398e40cd1a78f6

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://foundico.com/ico/yield-coin.html
2. https://irishtechnews.ie/ow-yield-coin-can-create-other-businesses-blockchain-technology-samuel-leach-at-biisummit-march-19th/
3. https://icomarks.com/ico/yield-coin
4. https://www.coingecko.com/en/coins/yield-coin
5. https://www.icodata.io/coin/yield-coin
6. https://www.coindesk.com/just-one-cryptocurrency-bucked-the-market-downtrend-this-week/
7. https://cryptoslate.com/coins/yield-coin/
8. https://bitcoinexchangeguide.com/yield-coin-yld-ico/
9. https://www.express.co.uk/finance/city/991813/Bitcoin-price-ripple-cryptocurrency-ethereum-BTC-to-USD-XRP-news
10. https://www.express.co.uk/finance/city/996713/Bitcoin-price-live-BTC-news-boost-cryptocurrency-ETF-Ethereum-Ripple

**Comment by freeatnet** [comment]
Thank you for your request, @tenshimatt!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1588.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1588.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by tenshimatt** [comment]
Thanks a lot for the feedback, all our information is in the correct format..

Looking forward to being part of the Fork Delta community!

**Comment by tenshimatt** [comment]
Hi guys - any feedback on this please? Thanks

**Comment by tenshimatt** [comment]
Just checking in.. Please can some one reply.. We're reallykeen to get on to Fork Delta! :)

**Comment by tenshimatt** [comment]
Hi guys - I see you are listing tokens again.. Good to hear :) We would love to be listed.. Just following up. Thanks
