### ISSUE TITLE
Add ARCCoin (AAA)

### ISSUE THREAD

**Issue by charliefletcher** [forkdelta/tokenbase#1589]
0xe39c277f81d347af8aa8c8b8b20061b7dc78bc64

https://www.aaareserve.com/

AAA reserve coin is an ERC20 compliant asset-backed cryptocurrency - collateralised by cash, gilts and AAA-rated credit investments. Proceeds from the issuance of AAA coins are placed into Arc Fiduciary Ltd - a ring-fenced Jersey-registered company - and invested into cash, gilts and fixed income; across multiple fiat currencies to support the value of AAA coins. 
It has a variety of use cases: Fiat to crypto bridge, ICO medium (allowing ICOs to accept fiat), International Transfers, crypto-based lending/ derivatives market and a safe haven currency (Due to AAAs composition making it the first real value stable coin, where inflation from the G10 countries over the past 10 years is tracked plus a premium and over the medium to long term the nominal value of the coin is manipulated via investment return to perform at and slightly above inflation. Making it a better than fiat store of value)

hello@aaareserve.com is the publically available email address but more efficient to contact us through my personal one at charlie.fletcher@aareserve.com 

There aren't many third party reviews of AAA Reserve but I have linked some articles on the coin bellow, more can be found on our website on the news link https://www.aaareserve.com/press-and-blog
http://www.funds-europe.com/jersey-report-2018/crypto-qa-shaping-the-future-of-cryptocurrency
https://www.disruptordaily.com/disruption-by-blockchain-part-84-shyaam-namas-aaa-reserve/
https://jerseyeveningpost.com/news/business/2018/01/19/new-cryptocurrency-on-the-market-thanks-to-island-firms/
https://www.cryptoninjas.net/2017/12/14/arc-cambridge-research-fellow-dr-garrick-hileman-launches-new-stablecoin/

The website is also in the process of getting updated with new links, information and layout on some pages.

**Comment by freeatnet** [comment]
Please file a new issue by filling out the form of the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md Thanks!
