### ISSUE TITLE
Please List our token : LitecoinCash (LCASH)

### ISSUE THREAD

**Issue by allanKerler** [forkdelta/tokenbase#159]
Hello,
We wish to be officially listed on https://forkdelta.github.io/.
Contract Adress link: https://etherscan.io/token/0x7747aeb32d89e527e5ebbf646871ca79805989ad
Symbol: Lcash
Decimal: 8
Website: https://litecoincash.io

Paragraph description of LitecoinCash:
LitecoinCash was built to help increase the adoption of cryptocurrency amongst average people. It was made to help increase the day-to-day transactions made with cryptocurrencies and help bring cryptocurrency into the mainstream, capitalist free market. LitecoinCash has the goal of becoming one of the top three cryptocurrencies that can be used for the sole purpose of being a reliable, trustless and fair medium of exchange. LitecoinCash wants to make everything fair and evenly distributed: It is this honest ethos and simple goal that will enable LitecoinCash to last for the longterm and be successfully sustained by the community.
Regards,

LitecoinCash dev team
website: https://litecoincash.io
twitter: https://twitter.com/litecoin_cash
GitHub: https://github.com/LeeAmni/ltccash
Telegram: https://t.me/joinchat/C_riohF3hiUga5m5R2PX5w
BitcoinTalk: https://bitcointalk.org/index.php?topic=2325408.0

**Comment by Kryptoniq** [comment]
Please provide a link to a review or discussion about the token.

**Comment by allanKerler** [comment]
https://bitcointalk.org/index.php?topic=2325408.0

**Comment by Kryptoniq** [comment]
Verified 0x7747aeb32d89e527e5ebbf646871ca79805989ad.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
