### ISSUE TITLE
Add CryptoSoul (SOUL)

### ISSUE THREAD

**Issue by cryptosoulgame** [forkdelta/tokenbase#1590]
**Token address:**
0xbb1f24c0c1554b9990222f036b0aad6ee4caec29

**Issuer's official website:**
https://cryptosoul.io/

**Description:** 
CryptoSoul is a free-to-play battle royal game with MOBA elements.
In CryptoSoul, we use a new economic game model focused on the player’s earnings. For the game achievements, the player earns tokens which have real value.
Big Idea 
Transforming gaming from the model “Player Spends” to the model “Player Earns”
https://cryptosoul.io/whitepaper/en
**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xbb1f24c0c1554b9990222f036b0aad6ee4caec29

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://t.me/CryptoSoulGame
https://t.me/CryptoSoulENG
https://twitter.com/CryptoSoul_
https://www.instagram.com/cryptosoul_/

**Comment by freeatnet** [comment]
Thank you for your request, @cryptosoulgame!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1590.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1590.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by cryptosoulgame** [comment]
Token address:
0xbb1f24c0c1554b9990222f036b0aad6ee4caec29

Issuer's official website:
https://cryptosoul.io/

Description: 
CryptoSoul is a free-to-play battle royal game with MOBA elements.
In CryptoSoul, we use a new economic game model focused on the player’s earnings. For the game achievements, the player earns tokens which have real value.
Big Idea
Transforming gaming from the model “Player Spends” to the model “Player Earns”
https://cryptosoul.io/whitepaper/en

A link to the official contract address confirmation: 
https://etherscan.io/token/0xbb1f24c0c1554b9990222f036b0aad6ee4caec29

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.youtube.com/watch?v=jYeJcONjAu8

2. https://www.youtube.com/watch?v=jYeJcONjAu8

3. https://www.youtube.com/watch?v=Cll8-HH3fGg&t=273s

4. https://www.youtube.com/watch?v=n2lWL3eLUAY
