### ISSUE TITLE
Add Tradetex (TDX)

### ISSUE THREAD

**Issue by btcsmartads** [forkdelta/tokenbase#1591]
**Token address:**
0x9ef3502c076804c92727f114aa366d6e4dfa9415

**Issuer's official website:**
https://tradetex.io

**Description:** 
Vision – To Make Trading a commission-Free Business so that maximum benefits can be reached to Buyers & Sellers.
Concept that we are using makes Tradetex Exchange unique from others
As here we are offering commission free Trading for traders so that maximum benefits can be reached to Buyers & Sellers.
and secondly Tradetex is First ever ICO in history of ICO’s with buyback, Means if  investor doesn't like Tradetex Portal then they can give TDX back to the company at fixed price even during ICO. 

**A link to the official contract address confirmation:** 
https://tradetex.io/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icobuffer.com/projects/tradetex#nav-reviews
2. https://www.youtube.com/watch?v=uCXgD1IOw6o
3. https://steemit.com/ico/@apritiadahenti/a-brief-review-of-tradetex
4. https://coinworldstory.com/tradetex/

**Comment by freeatnet** [comment]
Thank you for your request, @btcsmartads!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1591.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1591.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by btcsmartads** [comment]
**Token address:**
0x9ef3502c076804c92727f114aa366d6e4dfa9415

**Issuer's official website:**
https://tradetex.io

**Description:** 
Vision – To Make Trading a commission-Free Business so that maximum benefits can be reached to Buyers & Sellers.
Concept that we are using makes Tradetex Exchange unique from others
As here we are offering commission free Trading for traders so that maximum benefits can be reached to Buyers & Sellers.
and secondly Tradetex is First ever ICO in history of ICO’s with buyback, Means if investor doesn't like Tradetex Portal then they can give TDX back to the company at fixed price even during ICO.

A link to the official contract address confirmation: 
https://tradetex.io/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.youtube.com/watch?v=uCXgD1IOw6o
2. https://www.youtube.com/watch?v=jZ0Sx3P8vg8
3. https://d.tube/#!/v/pavlovsdoggies/a3d9em5c
4. https://www.bitchute.com/video/JxkpvrBDfqYq/
