### ISSUE TITLE
Add Labtorum (LTR)

### ISSUE THREAD

**Issue by labtorum** [forkdelta/tokenbase#1594]
**Token address:** 0x1bD4E709a076Fb71ea1014293a739f2b19CA565D
**Token symbol:** LTR
**Token decimals:** 8
**Token supply:** 3,000,000,000

**Issuer's official website:** https://www.labtorum.com/

**Description:** Labtorum is an ERC20 wallet application that provides information about profit on trading, so that users can get profit while trading. With the user experience that we currently apply to the application view to facilitate the creation, recovery, import / export wallet and transaction in this application.

**A link to the official contract address confirmation:** https://etherscan.io/token/0x1bd4e709a076fb71ea1014293a739f2b19ca565d 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.labtorum.com/mvp.apk
2. https://www.labtorum.com/mvp-0.1.1.apk
3. https://bitcointalk.org/index.php?topic=4684801.0
4. https://bitcointalk.org/index.php?topic=4684731.0
5. https://bitcointalk.org/index.php?topic=4800073.0

**Social Media link:**

1. https://www.facebook.com/labtorum
2. https://twitter.com/labtorum
3. https://t.me/official_labtorum_global

**ICO Review Link:**

1. https://icobench.com/ico/labtorum
2. https://foundico.com/ico/labtorum.html
3. https://icobazaar.com/v2/labtorum
4. https://icopulse.com/ico/labtorum
5. https://icoslot.com/en/ico/labtorum/
6. https://coinspectator.com/news/605247/our-labtorum-airdrop-is-now-startedvisit-httpslabtorumcomcomplete-all-task

**Comment by labtorum** [comment]
Pull request on #1593

**Comment by freeatnet** [comment]
Thank you for your request, @labtorum!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1594.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1594.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
