### ISSUE TITLE
Add ZAN Coin (ZAN)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1596]
**Token address:**
0xBeF51888aF40D73Db76A7716c98BDfE979040f8d

**Issuer's official website:**
https://zancoin.tech

**Description:** 
ZAN is IT Consulting Token Paying dividends based on company sales. The Company is building security extensions and analytics software. With 2 working products already we are gogin forward for a third one.

**A link to the official contract address confirmation:** 
https://zancoin.tech/#token

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.youtube.com/watch?v=DJmPJnreqF8&t=3s
2. https://www.youtube.com/watch?v=QPO2BbakdGo&t=698s

**Comment by freeatnet** [comment]
Thank you for your request, @tedboyar!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1596.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1596.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
