### ISSUE TITLE
Add Telex (TLX)

### ISSUE THREAD

**Issue by marinela91** [forkdelta/tokenbase#1597]
**Token address:**
0xb3616550abc8af79c7a5902def9efa3bc9a95200

**Issuer's official website:**
https://telexai.com

**Description:** 
We're creating a world where sending digital currency is as easy as having a conversation with a friend. By using TeleX AI one can trade and invest faster, safer and with a more simplified and convenient user experience. All one has to do is open a chat with TeleX AI and enjoy wallet and exchange functionalities through an instant-messaging application interface. Telex (TLX) is an ERC20 token that is used to pay fees for the services offered by TeleX AI.

**A link to the official contract address confirmation:** 
https://telexai.com/#token

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://cointelegraph.com/news/siri-for-crypto-a-chatbot-that-helps-with-trades-and-transactions
2. https://www.fxempire.com/news/article/interview-with-can-soysal-telex-ai-451953
3. https://medium.com/@gordob/telex-ai-due-diligence-bac330cbb1a3
4. https://www.coingecko.com/en/coins/telex

**Comment by marinela91** [comment]
Can anyone take a look at our request? Thank you in advance.

**Comment by freeatnet** [comment]
Thank you for your request, @marinela91!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1597.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1597.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
