### ISSUE TITLE
Add DMD Pangea Token (DMPNG)

### ISSUE THREAD

**Issue by DMDclub** [forkdelta/tokenbase#1598]
**Token address:**
0xD3A42c0A1D1103e98D668A953cb26dBCde9844c1

**Issuer's official website:**
www.DMDclub.com

**Description:** 
Domus Monetae Digitalis (DMD) is a producer of digital highly collectible tokens. Pangea Token (DMPNG) is a limited edition token meant to symbolize our roots and unity.

**A link to the official contract address confirmation:** 
https://etherscan.io/address/0xD3A42c0A1D1103e98D668A953cb26dBCde9844c1#code

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.youtube.com/watch?v=GPQVOljaggU&t=158s
2. https://www.reddit.com/user/dmdsky/comments/8ejy25/dmd_cryptocollectibles_a_new_trend_of_collectible/
3. https://bitcointalk.org/index.php?topic=3366169.0

**Comment by freeatnet** [comment]
Thank you for your request, @DMDclub!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1598.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1598.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
