### ISSUE TITLE
Add Ethereum Unlimited (ETHU)

### ISSUE THREAD

**Issue by remmarpidong** [forkdelta/tokenbase#1599]
**Token address:**
0x39E5BD6AE0f2aA9240D2ae7fBF49e36F05dd339F

**Issuer's official website:**
https://ethereumunlimited.net/

**Description:** 
Ethereum Unlimited is ERC20 And PoSTokenStandard Smart Contracts.
PoSTokenStandard allows you to earn more token by just holding your ETHU token and sell it when you need it. No special wallet needed to earn ETHU token.

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by freeatnet** [comment]
Thank you for your request, @remmarpidong!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1599.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1599.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
