### ISSUE TITLE
Add Status Security (STS)

### ISSUE THREAD

**Issue by STSToken** [forkdelta/tokenbase#1600]
**Token address:**
0x2193b9f2b5e5051e41c32c71b25587d6a6f045c8

**Issuer's official website:**
https://ststoken.com/

**Description:**
-Status Security (STS) Token combines exchanges, brokers, traders and investors into a decentralized secure, stable and transparent network. This revolutionary digital currency is focused on more than just security and efficiency, it uses peer-to-peer technology to provide worldwide availability and stability to the often volatile crypto-based financial market. Operating within the fast-paced and secured Ethereum blockchain, STS not only recognizes early adopters and long-term holders but will also be the first to deploy a Status-Based Incentive Programme (SBIP) into the worldwide market.

**A link to the official contract address confirmation:** 
-You can find the link on the News Board of https://ststoken.com/
https://twitter.com/ststoken/status/1031826289349382146?s=21
-STS Token contract address is also included in STS Twitter account profile (https://twitter.com/ststoken)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://www.blockasia.io/status-security-volatile-sts-crypto/
2. https://icoholder.com/en/status-security-token-24815

**Comment by freeatnet** [comment]
Thank you for your request, @STSToken!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1600.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1600.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by STSToken** [comment]
Is there any update regarding our application? Should you need additional information, please let us know.

All the best!
