### ISSUE TITLE
Add ThoreCash (TCH)

### ISSUE THREAD

**Issue by mumvn2** [forkdelta/tokenbase#1603]
**Token address:**

0x9972a0f24194447e73a7e8b6cd26a52e02ddfad5
**Issuer's official website:**

https://www.thorecash.com/
**Description:** 
Thorecash makes crypto-lending and investments accessible to the masses, cuts the red-tape. Thore platform simply aims to interconnect the $1 billion Crypto assest fractured across the world of crypto.

**A link to the official contract address confirmation:** 
https://coinlib.io/coin/TCH/ThoreCash
https://coinmarketcap.com/currencies/thore-cash/
**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://twitter.com/Thr_official
2.https://t.me/ThoreGroup

**Comment by mumvn2** [comment]
pls review the request.

**Comment by freeatnet** [comment]
Thank you for your request, @mumvn2!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1603.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1603.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
