### ISSUE TITLE
Add Token Changer (TOC)

### ISSUE THREAD

**Issue by Zibalion** [forkdelta/tokenbase#1605]
**Token address:** 0x853f93eDe7F5414b28b8b9c0DEC55B501C913f0f

**Issuer's official website:** www.tokenchanger.io

**Description:** TOC is a reward token for users of the Token Changer platform. Token Changer build financial dApps. 

**A link to the official contract address confirmation:https://etherscan.io/address/0x853f93eDe7F5414b28b8b9c0DEC55B501C913f0f -> https://tokenchanger.io/o2m/tc/toc/toc.html** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://cryptocoin.news/icos/token-changer-ico-review-building-hosting-dapps-for-financial-markets-8825/ 
2. https://icoshrimp.com/token-changer-to-offer-an-exchange-in-tokens-and-other-financial-services/
3. http://www.coinroundup.com/SPUhZ/WeSOZ/token-changer-aiming-to-build-first-platform-for-distributed-financial-applications-dapps/
4. https://www.youtube.com/watch?v=mUu6GrhRylg
**
<!--
Reviews must include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by freeatnet** [comment]
Thank you for your request, @Zibalion!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1605.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1605.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
