### ISSUE TITLE
Add PONTEM (PXM)

### ISSUE THREAD

**Issue by roioceguera** [forkdelta/tokenbase#1606]
1.- 0x33e127da2426822408b1d41344146de02ee48670
2.- there is not a website yet, because is a token for company's use at this moment.
3.- This token was created for an intern payments for our own company as an easier way to transfer value from one place to another, and we are implementing the token to all our supply chain as payment method for our providers, we are not an ICO at this moment, but we need the token to be listed on an exchange to exchange the tokens for ethereums that is easier to exchange it for FIAT money.
We are using the blockchain to have an easier accounting, that way the accounting apartment can know how much value is tranfered to our other locations 
4.- I actually don't understand the 4th point 
5.- we don't have a third-party reviews or discussion of the token, we are not looking to be an ICO as i said above.

If you want to know more about me, the token issuer I'm totally willing to give more information.
Hopefully our project is considered to be listed, and you help us to keep the private projects for blockchain implementations keep going  and not just be used as an ICOs

**Comment by freeatnet** [comment]
Please file a new issue by filling out the form of the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md Thanks!
