### ISSUE TITLE
Add Exaking (EXA)

### ISSUE THREAD

**Issue by philcom1** [forkdelta/tokenbase#1607]
**1. Token address:**
0x290D0CfBA0eEe0BDD504bE68CD4bf3cED75A6B43

**2. Issuer's official website:**
https://www.exaking.com/

**3. Description:**
Exaking is a free peer-to-peer cryptocurrency exchange and social network for crypto-enthusiasts. Over 1000 cryptos can be traded on the platform and it's possible to buy and sell with fiat money. The token, also called Exaking (EXA) is used as payment method by advertisers on the platform.  

**4. A link to the official contract address confirmation:** 
https://www.exaking.com/coin

**5. At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://icoholder.com/en/exaking-ico-20553
https://bitscreener.com/news/exaking-making-the-crypto-trading-free-anonymous-secure-social-and-accessible-for-everyone
https://www.coinschedule.com/ico/exaking

**Comment by freeatnet** [comment]
Thank you for your request, @philcom1!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1607.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1607.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
