### ISSUE TITLE
token listing

### ISSUE THREAD

**Issue by seanyspots** [forkdelta/tokenbase#1609]
Token name PURE CARBON
    Token ticker code PURC
    Decimal positions 18 
    Square logo of at least 100 x 100 px (preferably transparent so it works with our dark theme also)
    Link to contract on etherscan.io 0x97255bc2b5cf5280ae9bbd07f85d6d663e2030a8
    Website of token https://purecarbon.io
    
    Twitter  https://twitter.com/CarbonProtocol
    Git Hub https://github.com/Pure-Carbon/PureCarbon-Smart-Contract

   https://github.com/seanyspots 
https://www.instagram.com/purecarbonprotocol/

http://www.joinfindi.org I’m one of the initial 20 members 

https://icobench.com/u/purecarbon

https://steemit.com/financial/@seanyc/pure-carbon-is-proud-to-announce-it-is-one-of-the-20-initial-members-of-findi

Sean Connors 
Pure Carbon Inc.  
177 Huntington Ave Suite#1703-72295
Boston Ma, 02115 
seanconnorsnyc11@gmail.com 
https://twitter.com/CarbonProtocoI
Community partner of @HydrogenAPI 
https://twitter.com/HydrogenAPI/status/1030475365695860738 

http://www.joinfindi.org     Initial FINDI Member

**Comment by freeatnet** [comment]
Please file a new issue following the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
