### ISSUE TITLE
Please List our token : extoall (EXO)

### ISSUE THREAD

**Issue by extoall** [forkdelta/tokenbase#161]
Hello,
We wish to be officially listed on https://forkdelta.github.io/.
Contract Adress link: 0x0566c17dc2a9efcaa2f63e04cf06a69e8fc77f60
Symbol: EXO
Decimal: 0
Website: https://extoall.me

Paragraph description of EXO:
extoall.me is the fastest and most private accountless exchange to trade your favorite cryptocurrencies.
Regards,

EXO dev team
Website: https://extoall.me

**Comment by Kryptoniq** [comment]
1. Provide an official link verifying the contract address.
2. Provide a link to a third-party review or discussion of the token.

**Comment by extoall** [comment]
official link verifying the contract address : https://extoall.me/about.htm

**Comment by Kryptoniq** [comment]
0x0566c17dc2a9efcaa2f63e04cf06a69e8fc77f60, https://extoall.me

**Comment by Kryptoniq** [comment]
Provide a link to a third-party review or discussion of the Token. eg bitcointalk or an ICO review website.

**Comment by extoall** [comment]
link of discussion : https://bitcointalk.org/index.php?topic=3008932

**Comment by Kryptoniq** [comment]
I found two contract addresses on your website. Please get rid of one.

**Comment by extoall** [comment]
please check again pls : Contract Adress : 0x0566c17dc2a9efcaa2f63e04cf06a69e8fc77f60

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews and information.

**Comment by freeatnet** [comment]
Contrast and compare https://flyp.me/ and https://extoall.me/ (archived: http://archive.li/r2oh6)
