### ISSUE TITLE
Can you list GLITTER token?

### ISSUE THREAD

**Issue by dennishlewis** [forkdelta/tokenbase#1610]
Hello,
I would kindly like to request that you list our new ERC20 token GLITTER on forkdelta.
The smart contract address is: 0x679a89d4bfb3d77f84e13fb065c48b1252240bee
More information can be found here: https://icosuccess.com/glitter/
The purpose of GLITTER is to facilitate world class blockchain marketing services at a substantial discount.
Thank you very much!
Yours,
Dennis

**Comment by freeatnet** [comment]
Please file a new issue following the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
