### ISSUE TITLE
Add Xenchain XENC Token (XENC)

### ISSUE THREAD

**Issue by sweetpotatoz** [forkdelta/tokenbase#1611]
**Token address:**
0x4cfe597e2922790353a093a1de4f6b47a4bb3f44

**Issuer's official website:**
https://xenchain.io

**Description:** 

>   Xenchain accelerates and strengthen identity verification processes by using e-KYC technology
>   that requires facial recognition, making manual document authentication a thing of the past.
>   We creates and distributes XENCs to utilize the decentralized network of blockchain technology
>   and enhancing personal data security by controlling where the data is stored and who has access
>   to that information.

**A link to the official contract address confirmation:** 
https://xenchain.io (click on XENC token address)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  http://fintechnews.sg/20937/blockchain/xenchain-digital-identity-kyc/
2.  https://www.youtube.com/watch?v=aLZ-hHURs9Q

**Comment by freeatnet** [comment]
Thank you for your request, @sweetpotatoz!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1611.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1611.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
