### ISSUE TITLE
furt coin

### ISSUE THREAD

**Issue by furtcoin** [forkdelta/tokenbase#1613]
**Token address:** www.furtcoin.com

**Issuer's official website:** www.furtcoin.com

**Description:** 
Our platform, Furt platform was created out of the desire and passion to liberate you as a football fan from the disrespect and ill treatment meted by unscrupulous club leaders and governing bodies. With our platform, Furt Platform, we will continue to try our best to sanitize the mess that unscrupulous club owners, members of governing bodies have created because of their greed for money.

**A link to the official contract address confirmation:** 
0xf563549daf64f684858e863e2731f19633d1acb1

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:** https://bitcointalk.org/index.php?action=profile
https://www.coinschedule.com/ico/furtcoin#event5095

1. www.facebook.com/furtcoin

2.www.twitter.com/furtcoin

**Comment by freeatnet** [comment]
Hey @furtcoin! 0xf563549daf64f684858e863e2731f19633d1acb1 does not appear to be a token contract. Was there another address you meant to specify?
