### ISSUE TITLE
Tratin (TRAT) token

### ISSUE THREAD

**Issue by tratinproject** [forkdelta/tokenbase#1614]
<div class="ad"><img
src="http://tratin.io/wp-content/uploads/2018/08/874.png" height="96" width="96"
alt=""></a></div>

Hi Zack, please listed Tratin token on ForkDelta exchange. 
<br>Blockchain: Ethereum

Type: ERC20

Token name： Tratin

Token abbreviation：TRAT

Token decimals: 8

Total supply： 144,287,391,827

Token contract: 0x3eb55d5b22ee0f9b03d59b4994c5ae7fe811be92

Token explorer: https://etherscan.io/token/0x3eb55d5b22ee0f9b03d59b4994c5ae7fe811be92

Website： http://tratin.io/

Whitepaper: http://tratin.io/whitepaper/

Bitcointalk： https://bitcointalk.org/index.php?topic=4943791.msg44553220#msg44553220

Twitter：https://twitter.com/tratintoken

Telegram: https://t.me/tratin

**Comment by tratinproject** [comment]
<div class="ad"><img
src="http://tratin.io/wp-content/uploads/2018/08/874.png" height="96" width="96"
alt=""></a></div>Hi Zack, please listed <b>Tratin</b> token

**Comment by freeatnet** [comment]
Closing duplicates #1641, #1632, #1614, #1655. Please file a single issue following the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
