### ISSUE TITLE
Add Frasindo Rent (FRAS)

### ISSUE THREAD

**Issue by san2ok** [forkdelta/tokenbase#1617]
**Token address:**
0xC60000ba92B436BC165fd48D803BcE95A099AB67

**Issuer's official website:**
https://www.frasindo.com

**Description:** 
FRAS is an Online Taxi Supplier which aim as a Self-sustainable Blockchain & Start-Up Incubator, it have routine income.
Members can suggest ideas, which then get voted by the community, and if enough votes are received, the developers team at Frasindo will make it happen by appointing them as project leaders. We will then provide all business needs, regular funding, legality, and, shared-offices. It will then be acquisitioned as a subsidiary/Child-project of FRAS, which makes this risk free, hassle free and doesn’t require any expertise by the original contributors. (The acquisition-ed child-projects will add giveaway 10% of its coin along with its benefits to FRAS Members).

**A link to the official contract address confirmation:** 
https://www.frasindo.com/resources
(listed on the ASSET ID/CONTRACT, below list of exchange market)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://ethereumworldnews.com/indonesia-based-car-rental-company-frasindo-join-cryptocurrency-world-launch-frascoin-carcoin/
2. https://frasindo.com/shop/testify
3. https://bitcointalk.org/index.php?topic=2661040.msg27512502#msg27512502
4. https://www.frasindo.com/media/interview-with-fras-coin-founder-official-uber-grab-gocar-passive-income/

**Comment by freeatnet** [comment]
Thank you for your request, @san2ok!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1617.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1617.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by therealMikkoK** [comment]
![image](https://user-images.githubusercontent.com/42318985/46919107-f5e84a80-cfe2-11e8-994d-e1e9e7378cfe.png)
Admin of the official TG group openly tells they are participating in market manipulation.
Don't pass Go.
