### ISSUE TITLE
Add 3DES Token (3DES)

### ISSUE THREAD

**Issue by 3desproject** [forkdelta/tokenbase#1618]
**Token address:**
0x115E7B7eCdd9792d6995CB426B2Ef4D6119682A7

**Issuer's official website:**
https://3des.network/

**Description:**
3DES is decentralized computing capacities exchange for slicing tasks. We have issued a futures token and will swap all existing tokens to this.

**A link to the official contract address confirmation:**
https://3des.network/static/smartcontract.txt

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://cointelegraph.com/press-releases/3des-blockchain-for-the-sake-of-3d-printing-not-the-blockchain-itself
https://invest4all.ru/obzory-i-otchyoty/obzory-kraudsejlov-ico/3des-ico-kraudsejl-sistemy-optimizatsii-oblachnoj-3d-pechati
https://www.youtube.com/watch?v=8M6RpQVAqDM
https://www.youtube.com/watch?v=BlhoL5_2sio

**Comment by freeatnet** [comment]
Thank you for your request, @3desproject !

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1618.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1618.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by therealMikkoK** [comment]
Everything seems to be OK at first glance, smart contract can be found on etherscan and is held in over 310 wallets.
