### ISSUE TITLE
Add Board Coin (BRDC)

### ISSUE THREAD

**Issue by syedakbar11** [forkdelta/tokenbase#1619]
Hello,
Please add our token Board Coin ( BRDC ) find bellow info for our token

**Token address:**  0x3B36Cd56e286241386D3A043B0cff1a7187283b9

**Issuer's official website:**  boadrcoin.trade
Link to contract address http://www.boardcoin.trade/2018/08/27/contract-address/

**Description:** Board Coin is a decentralized currency governed by ecosystem on the blockchain and serves as global payment system. Companies,individuals and business partners can send and receive funds globally using BRDC digital currency as of payments.
BoardCoin is Application Based cryptocurrency Build By People Build For People Where Everyone Can Earn BRDC Tokens Just For Using It.

Thanks

**Comment by freeatnet** [comment]
Thank you for your request, @syedakbar11!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1619.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1619.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by syedakbar11** [comment]
Sorry we changed contract address so, now what to do?
Thanks
Regards

**Comment by freeatnet** [comment]
@syedakbar11 You can update it in the request above (the "Edit" option is located in the "..." menu, top-right corner of the comment box).

**Comment by syedakbar11** [comment]
how much time it will get to list?

**Comment by freeatnet** [comment]
@syedakbar11 You can expect a response from us within 6-8 weeks.

**Comment by syedakbar11** [comment]
Ok thanks mate
