### ISSUE TITLE
Listing Request - Bitpark (BTA)

### ISSUE THREAD

**Issue by bitparkbid** [forkdelta/tokenbase#162]
addr: '0x38c04D415f6740C7700185533a64b5f44cbF684C'
decimals: 18
description: BITPARK (BTA) are utilized when giving compensation during the insurance screening process, and users can pool together their money with BitCoin or with unique tokens — known for their stable exchange rate.
Name: Bitpark
TOKEN: BTA

Token: BTA
Name: Bitpark
Contract Address: 0x38c04D415f6740C7700185533a64b5f44cbF684C
Website: https://bitpark.bid/
Bitcointalk : https://bitcointalk.org/index.php?topic=2993187
telegram: https://t.me/joinchat/AAAAAEcOG-zP_HGhG_Hujw

**Comment by Kryptoniq** [comment]
Verified 0x38c04D415f6740C7700185533a64b5f44cbF684C.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
