### ISSUE TITLE
Add AVIN COIN (AVNC)

### ISSUE THREAD

**Issue by avincoin** [forkdelta/tokenbase#1621]
Contract address: 0x49953be8f2eaf45e20963815115fbb2de786f0da

Smart contract information: https://etherscan.io/token/0x49953be8f2eaf45e20963815115fbb2de786f0da
Token name: AVIN COIN
Token symbol: AVNC
Token decimals: 18
Smart contract has verified:
https://etherscan.io/address/0x49953be8f2eaf45e20963815115fbb2de786f0da#code
Issuer's official website: https://avincoin.com
Official contract address confirmation:
https://etherscan.io/address/0x49953be8f2eaf45e20963815115fbb2de786f0da#readContract
A link to a third-party review or discussion of the token:
https://bitcoingarden.org/forum/index.php?topic=44522.0
Social media:
Twitter: https://twitter.com/avincoin
Description:
You can see our roadmap and updated visions on the official Avin Coin website where this service will be implemented. We plan to build a retail store system. Our store will use AVNC as a payment medium. Store system will be expanded, global marketing.
We want to thank you for your time and me and my community look forward to seeing AVNC on FORK DELTA

**Comment by freeatnet** [comment]
Thank you for your request, @avincoin!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1621.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1621.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by avincoin** [comment]
Thank you very much.
