### ISSUE TITLE
Add Globfone Coin (GFC)

### ISSUE THREAD

**Issue by GlobfoneToken** [forkdelta/tokenbase#1622]
**Token address:**
0x6667A56d8fCB35448eE8514936e6D6c4CcC86E97

**Issuer's official website:**
https://www.globfone.net

**Description:** 
Globfone allows you to send text messages (SMS) to your friends and  family anywhere in the world for FREE. Also, the receiver does not need  to have the Globfone App installed on their phone. You can also send and  receive Globfone direct chat messages on Globfone. Globfone SMS  Messenger is a part of Free Online Phone Project. 

**A link to the official contract address confirmation:** 

https://etherscan.io/token/0x6667a56d8fcb35448ee8514936e6d6c4ccc86e97

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://bitcointalk.org/index.php?topic=4834277.msg43617955#msg43617955

t.me/GlobfoneXommunity
twitter.com/GlobfoneToken

1. twitter.com/GlobfoneToken
2. facebook.com/Globfone
3. t.me/GlobfoneCommunity
4. Youtube.com/Globfone

**Comment by Gimay27** [comment]
WOW!

**Comment by freeatnet** [comment]
Thank you for your request, @GlobfoneToken!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1622.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1622.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
