### ISSUE TITLE
Add OwnData (OWN)

### ISSUE THREAD

**Issue by mustafakemal16** [forkdelta/tokenbase#1623]
**Token address:**

0x170b275ced089fffaebfe927f445a350ed9160dc

**Issuer's official website:**
https://owndata.network

**Description:** 
Website owners earn money as tokens by using our platform to share your data. Owndata is a crypto marketplace for data sellers and buyers.Owndata provides sophisticated tools for sharing and managing the data with the targeted platform / user base.

**A link to the official contract address confirmation:** 
https://owndata.network/#coin

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcoinexchangeguide.com/owndata-ico/
2. https://help.hotbit.io/hc/en-us/articles/360006643173-Hotbit-launches-OWN-Owndata-Network-

**Comment by freeatnet** [comment]
Thank you for your request, @mustafakemal16!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1623.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1623.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
