### ISSUE TITLE
Listing Crowddreaming.net

### ISSUE THREAD

**Issue by CrowdDreaming** [forkdelta/tokenbase#1624]
Dear Sir or Madam

My name is Alejandro Fernández, I am the founder of Crowddreaming token and part of its developer team.
I would like to apply for listing the token in your exchange. is it possible?

Summary about some details:

Social media channels:

Twitter: https://twitter.com/CrowdDreaming
Telegram: https://t.me/crowddreaming_official
Reddit: https://www.reddit.com/user/CrowdDreaming
Whitepaper: http://www.crowddreaming.net/downloads/CDD-Whitepaper_EN.pdf
Website: http://www.crowddreaming.net/
Dev on Telegram: @CDD_dev
email: info@crowddreaming.net

Specifications

Name: CrowdDreaming
Contract: 0x085558b7561b51ffb0a4dabe7459d359c05b58cc
Symbol: CDD
Decimals: 8
Total Supply: 200,000,000 CDD
Protocol: ERC20 on Ethereum network
Wallet compatibility: Myetherwallet (recommended for holding), Metamask (recommended for trading) and more.
Code verification: Green mark on Etherscan
Link of verification: https://etherscan.io/address/0x085558b7561b51ffb0a4dabe7459d359c05b58cc#code

If you require further information, please do not hesitate to contact me.

I look forward to receiving your reply

Yours faithfully
Alejandro Fernandez
Dev Manager of CrowdDreaming

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
