### ISSUE TITLE
Add CreaEther (CETH)

### ISSUE THREAD

**Issue by CreaEther** [forkdelta/tokenbase#1625]
**Token address:**
0x3d166dd13dfdca66879bdd45dc224d07c8855cdb

**Issuer's official website:**
https://ceth.store

**Description:** 

The first Unique Automated Platform to offer Coin/Token Creation and Products Services

Products and services include all the required functionality and standard which ensures compatibility with the rest of the Cryptocurrency Environment and Network.
And Also all the Products and Services are Guaranty Premium. 

https://etherscan.io/token/0x3d166dd13dfdca66879bdd45dc224d07c8855cdb

**A link to the official contract address confirmation:** 

https://ceth.store Footer

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. www.cheddur.com/coins/creaether
2.https://coinlib.io/coin/CETH/CreaEther
3.https://bitcointalk.org/index.php?topic=4759867.msg44810423#msg44810423

**Comment by freeatnet** [comment]
Thank you for your request, @CreaEther!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1625.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1625.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by CreaEther** [comment]
Is there any news about the listing? 
Our team is ready to start announcement.

https://twitter.com/CreaEther/status/1043678828051066881

**Comment by CreaEther** [comment]
Join our Discord to see the CETH community. https://discord.gg/Zb3MMMU

**Comment by CreaEther** [comment]
https://www.cheddur.com/coins/creaether/reviews

**Comment by CreaEther** [comment]
Bitcointalk : https://bitcointalk.org/index.php?topic=4759867

**Comment by CreaEther** [comment]
Any update ??

**Comment by CreaEther** [comment]
New CETH Updated Contract with the Supply Reduce by 1000 %

https://etherscan.io/token/0x7c0a3f749ed88a10015d553dfdadd8bdcdb784fa

**Comment by CreaEther** [comment]
Can we expect a listing soon?

t.me/CETHTOKEN
