### ISSUE TITLE
Add Sharpay (S)

### ISSUE THREAD

**Issue by SANGILYOON** [forkdelta/tokenbase#1626]
https://t.me/sharpay_io

**Token address:** 0x96B0bF939D9460095C15251F71Fda11e41DcBddB

**Issuer's official website:** https://sharpay.io

**Description:**  The sharpay is the share and multi-share button for sites with blockchain-based rewards for content promotion for users. Multisharing is an opportunity to share the content in several networks in one click. Users receive rewards for the act of sharing or for the visits of other users via the shared links (depends on site settings). All that means the conversion growth for sites and comfortable sharing for users.

The sharpay button can look like anything, for example, it can be designed like on this page or customized for the any webdesign you wish. The sharpay button can be any color and shape, it can have any logos of connected social networks. The main feature of the button is the code, which is activated when you click on the button. Also, we can use your own design and match it with our code.

**A link to the official contract address confirmation:**  https://sale.sharpay.io/cabinet/home

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icoholder.com/en/sharpay-17207
2. https://cryptovest.com/reviews/sharpay-ico-review-social-mining-that-stands-out/
3. https://medium.com/@greenware63/sharpay-ico-review-a-revolutionary-idea-for-increasing-website-traffic-ed0bd727a4d5

**Comment by freeatnet** [comment]
Thank you for your request, @SANGILYOON!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1626.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1626.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
