### ISSUE TITLE
REQUEST TO LIST PENCHANT TOKEN

### ISSUE THREAD

**Issue by PenchantOfficial** [forkdelta/tokenbase#1627]
Penchant token is a virtual currency designed to work as a medium of appreciation towards people of natural skills or in better sense ( talented or gifted individuals). A token created for the purpose of a social community where skills or talent can be really appreciated.

Penchant token is a decentralized cryptocurrency built with solidity and ERC20 protocol offering the entire cryptocurrency community a seamless and secured mode of transactions for investors within the Penchant environment.

Token Information:

Name: Penchant Token

Symbol: PENT

Decimal: 8

Total Supply: 15Billion

Contract address:
 0x591BE9E4B46A5C5759413E79Ee09df430BdD3A1a

MyEtherWallet Supported

EtherScan: https://etherscan.io/token/0x591BE9E4B46A5C5759413E79Ee09df430BdD3A1a

ICO: There was no ICO but crowdsale 

Token Distribution

Airdrop and Marketing -(10%), Future Development-(15%)
Team-(5%), Crowdsale (70%).

Website: https://penchant.network/#home

Whitepaper: 
https://penchant.network/assets/images/Penchant%20Token.pdf

Twitter: https://twitter.com/PenchantProject?s=08

Telegram:https://t.me/penchantofficial

Logo: 
https://penchant.network/assets/images/logo.png

Download Logo Link: https://image.ibb.co/gUAYNp/IMG_20180816_200350.jpg

Contact: support@penchant.network

Sincerely

Thanks in anticipation

The Penchant  Project Team

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
