### ISSUE TITLE
Add OLD CAPITAL (OCALL), Capital GAS (CALLG)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1629]
This is a request to add a new token to tokenbase

**Token address:**
Old Capital (OCALL): [0x2c02c801a3324b371ad285c64af372ff1e23f460](https://etherscan.io/token/0x2c02c801a3324b371ad285c64af372ff1e23f460)
Capital GAS (CALLG): [0x6c28f85eb1dbc7651ce02f7af1f29890ad084b94](https://etherscan.io/token/0x6c28f85eb1dbc7651ce02f7af1f29890ad084b94)

**Issuer's official website:**
[https://www.mycapitalco.in](https://www.mycapitalco.in)

**Description:** 
Capital Technologies & Research will develop a decentralized private communication system where users can easily enjoy their private communications. 
- **Old Capital (OCALL)** is going to be used for encrypted user session establishment.
- **Capital GAS (CALLG)** is the fuel of the network.

You can check the link between our [website domain](https://www.mycapitalco.in) and both ERC-20 tokens in Etherscan Token information as following:
- [**Old Capital (OCALL)**](https://etherscan.io/token/0x2c02c801a3324b371ad285c64af372ff1e23f460)
- [**Capital GAS (CALLG)**](https://etherscan.io/token/0x6c28f85eb1dbc7651ce02f7af1f29890ad084b94)

**Third-party reviews:**
1. [Switzerland Posts](http://switzerlandposts.com/capital-technologies-research-will-revolutionise-our-means-of-communication)
2. [YouTube Review Turkish](https://www.youtube.com/watch?v=74gay660o1w)
3. [YouTube Review Russian](https://www.youtube.com/watch?v=jDAwQdlz7NU)
4. [YouTube Review Vietnamese](https://www.youtube.com/watch?v=IFYK7nXb9bw)
5. [Korean user review](http://currencytechs.info/capital-token/)
6. [Japanese user review](http://cryptonewsletters.info/capital-ico/)
7. [French user review](http://icofrance.top/capital-ico/)
8. [English user review](http://ethereumtoken.co/ico-news/capital-technologies/)

**ICO Trackers:**
1. [TrackICO](https://www.trackico.io/ico/capital-technologies-research/)
2. [FindICO](https://findico.io/ico/capital-technologies-research)
3. [ICOHolder](https://icoholder.com/en/capital-technologies-research-23237)
4. [ICOMarks](https://icomarks.com/ico/capital-technologies-amp-research)
5. [ICOBench](https://icobench.com/ico/capital-technologies-amp-research)

**Pull request:**
[#1628](https://github.com/forkdelta/tokenbase/pull/1628)

**Comment by capital-technologies** [comment]
@freeatnet Can you take a look over our request? Thanks in advance!

**Comment by capital-technologies** [comment]
@bluedex [#10](https://github.com/bluedex/bluedex.github.io/pull/10)

**Comment by capital-technologies** [comment]
This is a request to add a new token to tokenbase

**Comment by freeatnet** [comment]
Thank you for your request, @capital-technologies!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1629.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1629.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by capital-technologies** [comment]
[Ethereum ERC-20 Capital (CALL)](https://etherscan.io/token/0x2c02c801a3324b371ad285c64af372ff1e23f460) has forked into a new **[PoW blockchain](http://call.explorer.mycapitalco.in)**, balances will be migrated by each user using our dedicated portal. More information will be provided after the ICO end (29th of September 2018). We would like to have the ERC-20 Capital (CALL) listed as **Old Capital (OCALL)** to prevent user confusion between each asset.
P.S. After each swap, tokens will be burned, so nobody could swap it's balanced twice.
Best regards!
