### ISSUE TITLE
Request to list ERC20 ETH Token : GMX - Global Monetary Xfer

### ISSUE THREAD

**Issue by DigitalNomadCoin** [forkdelta/tokenbase#163]
website : https://digitalnomadcoin.webnode.be/your-own-coin/
email : digitalnomadcoin@outlook.com
telegram :@digitalnomadcoin
twitter : @DigitalNomadCoi

Global Transparent Monetary X-fer

The first ETHICAL cryptocurrency for TRANSPARENT financial flows for NGO's

What Ripple is for the banks, is GMX for the Non-Governmental Organisations.

GMX will provide a Trusted Blockchain Directory (TBD) in which an NGO can set up the wallet address of every partner they work with. This TBD will not only contain the wallet address but also all data needed to fully identify the owner of this wallet (company name, registration number, physicall address, website, email, telephone,...)

The NGO's will also publish their part of the TBD in their annual accounts and on there website. As such every stakeholder can check that the information in the TBD is correct.

Every interested stakeholder will be able to follow in real-time via the TBD the main financial flows between the NGO and their international affiliates/partners. As such, there will no longer be blind spots on the aid allocation map.

We will provide for the general public an application with a drop-down list of all NGO's that participate in the GMX initiative. Once a specific NGO is selected, we will provide a real time and graphical overview of all financial flows from the NGO to their partners worldwide.

**Comment by Kryptoniq** [comment]
1. Provide contract address
2. Provide link to a review or discussion about the token.

**Comment by DigitalNomadCoin** [comment]
contract address : https://etherscan.io/address/0xd28807d7ef028af6728d12ccd621b2242da2a64f

Link to discussion : https://bitcointalk.org/index.php?topic=2966939.0

website : https://digitalnomadcoin.webnode.be/your-own-coin/

telegram : @digitalnomadcoin

twitter : @DigitalNomadCoi


[https://digitalnomadcoin.webnode.be/_files/200000012-3e3373f297/700/GMXlogo.png]<https://digitalnomadcoin.webnode.be/your-own-coin/>

GMX - Global transparent Monetary Xfers::Digitalnomadcoin<https://digitalnomadcoin.webnode.be/your-own-coin/>
GMX - Global Monetary Transfer
digitalnomadcoin.webnode.be




Verzonden vanuit Outlook<http://aka.ms/weboutlook>
________________________________
Van: Krypton <notifications@github.com>
Verzonden: donderdag 22 februari 2018 23:38
Aan: forkdelta/tokenbase
CC: DigitalNomadCoin; Author
Onderwerp: Re: [forkdelta/tokenbase] Request to list ERC20 ETH Token : GMX - Global Monetary Xfer (#163)


  1.  Provide contract address
  2.  Provide link to a review or discussion about the token.

**Comment by Kryptoniq** [comment]
0xd28807d7ef028af6728d12ccd621b2242da2a64f, https://digitalnomadcoin.webnode.be

**Comment by freeatnet** [comment]
* No third-party reviews.
* Website link pointing to token.store isn't actually functional, opens ERC20 token trading instead.

**Comment by DigitalNomadCoin** [comment]
this is the functioning link to token.store  : https://token.store/trade/GMX
more than 8 million GMX tokens have been sold via Token.store the last 4 days ...

**Comment by freeatnet** [comment]
@DigitalNomadCoin Has your project been discussed anywhere in the press or by a blog? I would like to know more about it.

**Comment by DigitalNomadCoin** [comment]
We did not yet get external reviews : we have submitted press releases, presented ourselves on bitcointalk, .. But as a new token it is difficult to get attention... Sales via token.store go well (although this is a very small Exchange), hopefully we get scored on coinmarketcap.com some day to get real interest in the possibilities of our approach

**Comment by DigitalNomadCoin** [comment]
We also have a “paling” Domain name : www.digitalnomadcoin.org

**Comment by DigitalNomadCoin** [comment]
You mentionned that you could not verify the team. My linkedin is at https://www.linkedin.com/in/benbervoets/

I am Ben (Benjamin) Bervoets, co-founder of GMX

Team Members of GMX want to stay as much anonymous as possible : here in Belgium we are taxed on every cryptocurrency we have in our wallet, so in the early phase of the project (with still many tokens in the wallet of the project team) this is financially an extreme risk ...

Kind Regards,

Ben Bervoets

Verzonden vanuit Outlook<http://aka.ms/weboutlook>
________________________________
Van: Arseniy Ivanov <notifications@github.com>
Verzonden: zondag 25 februari 2018 13:32
Aan: forkdelta/tokenbase
CC: DigitalNomadCoin; Mention
Onderwerp: Re: [forkdelta/tokenbase] Request to list ERC20 ETH Token : GMX - Global Monetary Xfer (#163)


@DigitalNomadCoin<https://github.com/digitalnomadcoin> Has your project been discussed anywhere in the press or by a blog? I would like to know more about it.

**Comment by DigitalNomadCoin** [comment]
@freeatnet  did you receive the linkedin info I did sent via seperate mail to freeatnet ?
tx

Ben

**Comment by freeatnet** [comment]
@DigitalNomadCoin Sorry, all communication of points supporting a token listing must be public. At the moment, we do not have enough information about your project. Two main points are:

* There is no public discussion of the project and no independent 3rd-party reviews. While you provided an announcement on BitcoinTalk, there are no responses to it.
* In so far as current trading activity, I can see 8 trades made on token store; however, 7 of those trades were executed by the same account.

Perhaps consider asking a crypto-related blog to review your project/token?

**Comment by DigitalNomadCoin** [comment]
Our GMX Token is now available also via Etherdelta (https://etherdelta.com/#0xd28807d7ef028af6728d12ccd621b2242da2a64f-ETH). 
So if our request for listing does not qualify for Forkdelta, our request can be closed.
