### ISSUE TITLE
Add Erachain Blockchain Platform token (ERCH)

### ISSUE THREAD

**Issue by icreator** [forkdelta/tokenbase#1630]
Dear Forkdelta team!

My name is Dmitry Ermolaev, I'm the founder of the Blockchain Platform Erachain.
Our project is successfully developing, at the moment, two business cases are completely ready, which we are already starting to implement: one for Internet commerce, the second for logistics. In this regard, we made an important strategic decision to bring our token to the stock exchange.

Information about us
Website: http://erachain.org/
White paper: http://erachain.org/assets/docs/WP_ENG.pdf
Bitcointalk: https://bitcointalk.org/index.php?topic=4516484.0
Reddit: https://www.reddit.com/user/Erachain
Telegram: https://t.me/erachain
GitHub: https://github.com/erachain

App Store https://itunes.apple.com/ru/app/erachain-wallet/id1358380425
Google Play https://play.google.com/store/apps/details?id=org.erachain.wallet

Token Information
Full Name: Erachain
Contract: 0x2300d50a447992e934816d3cd415157999202352
Symbol: ERCH
Decimals: 8
Total Supply: 10,000,000 ERCH
Protocol: ERC20 on Ethereum network
Explorer: https://etherscan.io/address/0x2300d50a447992e934816d3cd415157999202352#code

We hope for a positive decision!

Best regards, Dmitry Ermolaev.
Erachain Blockchain Platform Founder

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
