### ISSUE TITLE
Remove MIC from list

### ISSUE THREAD

**Issue by mindexcoin** [forkdelta/tokenbase#1631]
Hello, we want remove Mindexcoin from Forkdelta.

The contract is: 0x3a1237d38d0fb94513f85d61679cad7f38507242

How many time to remove?

**Comment by bobbypaintsstuf** [comment]
Hi 👋 i will presume you are the same person who was just in the ForkDelta telegram chat room seeking a way to delist a coin ? 

From your conversations In that chat room it looks like  your saying that your coin is held back by lower volume exchanges so you want to remove it from all decentralised exchanges ( or other low volume ones ) making it an internal private transaction until the price is much higher before applying to bigger exchanges 

Is that correct Sir ?

**Comment by mindexcoin** [comment]
Correct, because of these volume failures the currency devalued a lot and all trades were discouraged. That is why we are restructuring every currency.

**Comment by mindexcoin** [comment]
Hello, anyone can help us in this process?
