### ISSUE TITLE
BTNT Listing Request

### ISSUE THREAD

**Issue by Syncretistic** [forkdelta/tokenbase#1633]
Hi there,

We'd like to list the BitNautic Token (BTNT) on ForkDelta.

We are building a platform for the naval logistics industry, to match the needs of shippers and carriers. More info on the official website [here](https://bitnautic.io/?utm_source=forkdelta). 
The token is classified as hybrid, as it serves both as utility for access to the platform and as payment for services between platform users.

Token address: 0xd9964e1306dda055f5284c52048712c35ddb61fd

Address verification: https://bitnautic.io/token-details.html

Third party reviews:

https://icobench.com/ico/bitnautic

https://bitcoinexchangeguide.com/bitnautic-btnt-ico/

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!

**Comment by Syncretistic** [comment]
> Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!

Hi, I am trying to file the request but the submit button is greyed out. Anyway, this is it.



**Token address:**

0xd9964e1306dda055f5284c52048712c35ddb61fd

**Issuer's official website:**

https://bitnautic.io

**Description:** 

We are building a platform for the naval logistics industry, to match the needs of shippers and carriers.
The token is classified as hybrid, as it serves both as utility for access to the platform and as payment for services between platform users.

**A link to the official contract address confirmation:** 

https://bitnautic.io/token-details.html

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**


1. https://bitcoinexchangeguide.com/bitnautic-btnt-ico/
2. https://www.youtube.com/watch?v=UwDdM5sjwiY

**Comment by freeatnet** [comment]
Appears that got posted as #1676.
