### ISSUE TITLE
Add token EIB (EIB)

### ISSUE THREAD

**Issue by eibexchange** [forkdelta/tokenbase#1634]
The EIB is developed based on the Ethereum code ERC20/ERC223 and EIB runs on an Ethereum. It will be developed as a blockchain era bank.

Token Information :
Name : EIB
Symbol : EIB
Decimal : 18
Supply : 30.000.000.000
Contract : 0x2f2540218770da363dd3320b107f38fbeaf62472
Trace : https://etherscan.io/token/0x2f2540218770da363dd3320b107f38fbeaf62472

Our Website : https://www.eib.ai/
Contact us : support@eib.ai
Facebook : https://www.facebook.com/eib.exchange
Twitter : https://twitter.com/eib_Exchange
Telegram : https://t.me/EIB_exchange
Medium : https://medium.com/@eib.ai
Whitepaper: https://eib.ai/asset/download/eib.ai.whitepaper.v.1.1.pdf
https://app.stocks.exchange/en/basic-trade/pair/ETH/EIB/1D
https://mercatox.com/exchange/EIB/ETH
https://mercatox.com/exchange/EIB/BTC

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
