### ISSUE TITLE
Add Rainbow Token (RNBT)

### ISSUE THREAD

**Issue by RainbowTokenofficial** [forkdelta/tokenbase#1637]
**Token address:**
0x88F2837B1C29938E35f1152779437Db7Be96e4B7

**Issuer's official website:**
www.rainbowtoken.ml

**Description:** 
We just started our project, but have awesome plans for the future! We are utilizing blockchain for smarter water management in areas that currently have difficulties with this.

**A link to the official contract address confirmation:** 
https://etherscan.io/tx/0x9333e6a24bba91458b13968a6b1195e7b2fdd0fc99419f10ddd4d987a0800f9e

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=5011853.0.https://icobench.com/ico/rainbow-token

**Comment by RainbowTokenofficial** [comment]
Token address: 0x88F2837B1C29938E35f1152779437Db7Be96e4B7

Issuer's official website: www.rainbowtoken.ga

Description:
We just started our project, but have awesome plans for the future! We are utilizing blockchain for smarter water management in areas that currently have difficulties with this. 

A link to the official contract address confirmation: https://etherscan.io/tx/0x9333e6a24bba91458b13968a6b1195e7b2fdd0fc99419f10ddd4d987a0800f9e

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=4993594.msg45041039#msg45041039

2. https://mobile.twitter.com/token_rainbow

**Comment by freeatnet** [comment]
Thank you for your request, @RainbowTokenofficial!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1637.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1637.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by RainbowTokenofficial** [comment]
New address is http://rainbowtoken.ml!

New email is Contact@rainbowtoken.ml!

**Comment by RainbowTokenofficial** [comment]
Also bitcointalk link was invalid!

https://bitcointalk.org/index.php?topic=5011853.0

IS CORRECT!

Thank you :)
