### ISSUE TITLE
Add Self Storage Coin (STOR)

### ISSUE THREAD

**Issue by SelfStorageCoin** [forkdelta/tokenbase#1638]
**Token address:**
0xa3ceac0aac5c5d868973e546ce4731ba90e873c2

**Issuer's official website:**
http://www.selfstoragecoin.com

**Description:** 

Self Storage Coin is a P2P ERC20 Utility token for the transfer of value in the Self Storage industry.  Self Storage is one of the most stable and predictable cash flowing businesses in all of commercial Real Estate.

**A link to the official contract address confirmation:** 

http://www.selfstoragecoin.com/quick-start  then click on Etherscan link just below Getting Started with STOR

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.insideselfstorage.com/revenue-management/introduction-using-cryptocurrencies-self-storage
2.https://www.minds.com/blog/view/832911381418606592

And if any other info is needed please contact me directly:
Charles Anderson
Founder
Self Storage Coin
contact@selfstoragecoin.com

**Comment by SelfStorageCoin** [comment]
By the way we are already on Bluedex but don't see much activity there.  And more actively trade on Exrates.
CA

**Comment by freeatnet** [comment]
Thank you for your request, @SelfStorageCoin!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1638.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1638.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by SelfStorageCoin** [comment]
Thank you.  I checked the format in the initial request and it seems to be correct as you suggested.  Look forward to any follow up and happy to answer any questions you might have.
Thanks,
Charles Anderson
Founder
Self Storage Coin

**Comment by SelfStorageCoin** [comment]
Token address:
0xa3ceac0aac5c5d868973e546ce4731ba90e873c2

Issuer's official website:
http://www.selfstoragecoin.com

Description:

Self Storage Coin is a P2P ERC20 Utility token for the transfer of value in the Self Storage industry. Self Storage is one of the most stable and predictable cash flowing businesses in all of commercial Real Estate.

A link to the official contract address confirmation:

http://www.selfstoragecoin.com/quick-start then click on Etherscan link just below Getting Started with STOR

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

https://www.insideselfstorage.com/revenue-management/introduction-using-cryptocurrencies-self-storage
2.https://www.minds.com/blog/view/832911381418606592
And if any other info is needed please contact me directly:
Charles Anderson
Founder
Self Storage Coin
contact@selfstoragecoin.com
