### ISSUE TITLE
Request to update SHNZ to SHNZ2

### ISSUE THREAD

**Issue by ShizzleNizzle** [forkdelta/tokenbase#1639]
We have a new smart contract.  See medium post: https://medium.com/@info_92781/new-smart-contract-for-shnz-289c0f33748a

**What token should be updated?**

For: https://forkdelta.app/#!/trade/SHNZ-ETH

**What about the token should be updated?**

Please update token contract address. We have a new smart contract: 0x7c70c1093653ca3aa47ac5d8f934125a0aaa1645

Please update symbol from SHNZ to SHNZ2

Please update token description to:
The goal of Shizzle Nizzle is to build a platform for buyers and sellers that creates fun and creative profitability. We are building a crypto-metaverse social, game, and market land. Maximum supply 100,000,000,000 SHNZ2.

**Comment by ShizzleNizzle** [comment]
Hi. Any time-frame for when this will be updated? @v1nc3ntlaw @freeatnet @activescott @mishfit @tomaszbec

**Comment by mishfit** [comment]
While I have made pull requests to forkdelta before, I'm not actually an active contributor. You might want to create a pull request to add a new token file (whose name is based on the new address).

I did a quick search and it looks like your old token is this file:
https://github.com/forkdelta/tokenbase/blob/master/tokens/0x8b0c9f462c239c963d8760105cbc935c63d85680.yaml

You'll want to add a new file with the new address (as a PR).

**Comment by ShizzleNizzle** [comment]
@mishfit thanks. I will leave this an an open issue. The instructions I received were to file token update as an issue: https://github.com/forkdelta/tokenbase/issues/new/choose

**Comment by freeatnet** [comment]
Thanks @ShizzleNizzle!

**Comment by ShizzleNizzle** [comment]
Hi @freeatnet. Any idea for timeline for when this will be able to make it into "In Review"? Shizzle Nizzle owners are asking... Thanks!

**Comment by ShizzleNizzle** [comment]
Etherscan has verified the links: https://etherscan.io/token/0x7c70c1093653ca3aa47ac5d8f934125a0aaa1645

**Comment by ShizzleNizzle** [comment]
@freeatnet any update for when this can be updated as it's been two months since request was opened. Thanks!

**Comment by ShizzleNizzle** [comment]
@freeatnet could you please provide an update for when SHNZ ticker will be updated to new token SHNZ2 on ForkDelta? We opened the request on Sept 3, 2018. It's been 159 days.

**Comment by ShizzleNizzle** [comment]
@therealMikkoK could you please change the priority on this to high? Thanks.

**Comment by ShizzleNizzle** [comment]
You can see etherscan's message regarding old token SHNZ here: https://etherscan.io/token/0x8b0c9f462c239c963d8760105cbc935c63d85680

New token SHNZ2: https://etherscan.io/address/0x7c70c1093653ca3aa47ac5d8f934125a0aaa1645

Announcement is here: https://medium.com/@info_92781/new-smart-contract-for-shnz-289c0f33748a
