### ISSUE TITLE
Add CryptoAds Token (CRAD)

### ISSUE THREAD

**Issue by oleksiivinogradov** [forkdelta/tokenbase#1640]
**Token address:**
0x3637fcD710B99d2B643aF653d60b762d6C310A8B

**Issuer's official website:**
https://cryptoads.cfc.io

**Description:** 
"CryptoAds Marketplace is a powerful decentralized marketing and advertising platform built on Ethereum Blockchain. CFC Company developed a cloud based software system for internal use and B2C sector; and now it’s time for expanding into the growing B2B marketplace. The platform is completely transparent and provides secure solutions for brands, digital advertisers, marketers, content publishers and everyday Internet users, who receive the opportunity to trade directly without the need for centralized ad exchanges. CryptoAds Marketplace will give to advertisers an opportunity to place a variety of ad units (native video, live-casting ads, 360 ads, “in the round”, vertical video, in-app, and walls) at an unlimited number of traffic sources with AI and Blockchain technologies and without having to worry about proper execution.
CryptoAds model is already implemented inside CFC.io project (launched in 2005) with 7M registered users and profit-generating returns. This project will be base to growing platform worldwide."

**A link to the official contract address confirmation:** 

https://cryptoads.cfc.io

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

http://3g.163.com/dy/article/DHRHCA85051188EC.html
http://3g.163.com/news/article/DIB1SD6A042790IF.html
http://3g.163.com/news/article/DIB1SD6A042790IF.html
http://app.thebesttool.net/url/763a1272-f245-4356-b59b-1a2df6d4bfdd
http://chain.chinabyte.com/0/14515500.shtml
http://chain.chinabyte.com/news/428/14503928.shtml
http://chain.ikanchai.com/2018/0515/213263.shtml
http://chain.ikanchai.com/2018/0629/221707.shtml
http://chain.ikanchai.com/2018/0712/223691.shtml
http://cj.sina.com.cn/articles/view/2449908934/9206a4c6001008unr?from=finance&sudaref=www.ejianmedia.com&display=0&retcode=
http://cj.sina.com.cn/articles/view/2449908934/9206a4c6001008unr?from=finance&sudaref=www.ejianmedia.com&display=0&retcode=
http://coinews.io/ru/category/1-kripto/article/2359-icobox-%D1%96-cfc-uklali-dogov%D1%96r-pro-vih%D1%96d-na-ico-marketingovo-reklamno%D1%97-platformi-cryptoads
http://cryptocoinportal.jp/market-watch/icomarket-11/
http://cryptocoinportal.jp/market-watch/icomarket-19/
http://cryptocoinportal.jp/market-watch/icomarket-30/
http://cryptocoinportal.jp/market-watch/icomarket-33/
http://cryptocoinportal.jp/market-watch/icomarket-9/
http://games.qq.com/a/20180521/023981.htm
http://ln.qq.com/a/20180521/023515.htm
http://t.cj.sina.com.cn/articles/view/2286037382/88422986020007cq9?cref=cj
http://www.etnews.com/20180628000409
http://www.getnews.co.kr/news/articleView.html?idxno=68650
http://www.getnews.co.kr/news/articleView.html?idxno=71118
http://www.kinews.net/news/articleView.html?idxno=118847
http://www.kinews.net/news/articleView.html?idxno=200120
http://www.newsworks.co.kr/news/articleView.html?idxno=200185
http://www.sohu.com/a/231628397_100112552
https://3g.k.sohu.com/t/n273743760?showType=&sf_a=qq&gotoId=273743760&gotoId=273743760
https://arabbit.net/%D8%AA%D8%B9%D8%B1%D9%91%D9%81-%D8%B9%D9%84%D9%89-%D9%85%D9%86%D8%B5%D8%A9-cryptoads-%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%86%D8%A7%D8%AA-%D8%A7%D9%84%D8%B1%D9%82%D9%85%D9%8A%D8%A9/
https://arabbit.net/%D8%AD%D9%85%D9%84%D8%A9-%D8%A7%D9%84%D8%AA%D9%85%D9%88%D9%8A%D9%84-%D8%A7%D9%84%D8%AC%D9%85%D8%A7%D8%B9%D9%8A-%D8%A7%D9%84%D8%B9%D8%A7%D9%85%D8%A9-%D9%84%D9%80-cryptoads/
https://arabbit.net/%D9%85%D9%86%D8%B5%D8%A9-cryptoads-%D8%A7%D9%84%D9%84%D8%A7%D9%85%D8%B1%D9%83%D8%B2%D9%8A%D8%A9-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%86%D8%A7%D8%AA/
https://arabbit.net/cryptoads-%D9%87%D8%AF%D9%81%D9%87%D8%A7-%D9%88ico-%D8%AE%D8%A7%D8%B5%D8%AA%D9%87%D8%A7/
https://arabbit.net/cryptoads-%D9%88%D8%A8%D9%84%D9%88%D9%83-%D8%AA%D8%B4%D9%8A%D9%86-%D9%88%D8%A7%D9%84%D8%B9%D9%85%D9%84%D8%A7%D8%AA-%D8%A7%D9%84%D8%B1%D9%82%D9%85%D9%8A%D8%A9/
https://arbolet.net/clanek/5842-icobox-a-cfc-oznamily-partnerstvi-pro-nadchazejici-ico-cryptoads-decentralizovany-digitalni-reklamni-trh
https://bitcoin-live.de/cryptoads-laesst-die-user-waehlen-welche-anzeigen-sie-fuer-praemien-schauen-wollen/
https://bitcoin-live.de/cryptoads-team-unterstuetzt-von-telecoms-und-blockchain-professional-advisors/
https://bitcoin-live.de/icobox-und-cfc-geben-partnerschaft-fuer-ico-von-cryptoads-bekannt-einem-dezentralisierten-marktplatz-fuer-digitale-werbung/
https://bittox.com/2018/05/07/icobox-cfc-partnership-ico-of-cryptoads/
https://coin-hero.de/cryptoads-arbeitet-mit-etherzero-zusammen-um-ein-neues-zeitalter-der-werbung-und-markenverbreitung-einzulaeuten/
https://coin-hero.de/cryptoads-public-crowdsale-startet-mit-ankuendigung-eines-neuen-hardware-wallet/
https://coin-hero.de/oleksii-vinogradov-gruender-von-cryptoads-intermediaere-in-der-online-werbebranche-erhoehen-den-preis-um-bis-zu-1-000-aber-blockchain-kann-dies-aendern/
https://coinspot.io/company/aleksej-vinogradov-cryptoads-chem-vyshe-status-polzovatelya-tem-dorozhe-ego-reklamnye-predlozheniya/
https://coinspot.io/company/platforma-cryptoads-rassmatrivaet-etherzero-kak-strategicheskogo-partnera-dlya-cifrovogo-prodvizheniya-brendov/
https://criptotendencia.com/2018/05/04/entrevista-a-oleksii-vinogradov-fundador-y-presidente-de-cryptoads/
https://criptotendencia.com/2018/06/28/la-crowdsale-publica-de-cryptoads-comienza-con-un-anuncio-de-la-nueva-billetera-fisica/
https://cryptocanucks.com/ico/Cryptoads+Marketplace
https://cryptonews.pl/cryptoads-laczy-sie-z-etherzero-aby-zapewnic-nowy-rozdzial-w-reklamach-i-dystrybucji-markek/
https://cryptonews.pl/cryptoads-ma-na-celu-umozliwienie-uzytkownikom-wybieranie-reklam-do-ogladania/
https://cryptonews.pl/icobox-i-cfc-oglaszaja-partnerstwo-dla-ico-of-cryptoads-zdecentralizowanego-rynku-reklamy-cyfrowej/
https://cryptonews.pl/oleksii-winogradov-zalozyciel-i-prezes-cryptoads/
https://cryptonews.pl/publiczny-crowdsale-firmy-cryptoads-rozpoczyna-sie-od-ogloszenia-nowego-portfela/
https://cryptonews.pl/zespol-cryptoads-jest-wspierany-przez-telecom-i-profesjonalnych-doradcow-blockchain/
https://cryptovest.com/news/interviews/interview-with-cryptoads-ceo-and-founder-oleksii-vinogradov/
https://dp.ru/a/2018/04/25/Rossijskaja_BitClave_zapus
https://en.insider.pro/calendars/ICO/cryptoads-marketplace/
https://icolink.com/ico-cryptoads.html
https://icorating.com/analytics/basic/cryptoads-basic-review/
https://journalducoin.com/ico/cryptoads-sassocie-a-etherzero-afin-doffrir-nouvelle-ere-de-distribution-de-publicite-dimage-de-marque/
https://k.sina.cn/article_2371735174_8d5dce86001006do3.html?from=news&subch=zx&http=fromhttp
https://koinbulteni.com/cryptoads-ile-etherzero-arasinda-reklamcilarin-hoslanacagi-bir-ortaklik-kuruldu-18237.html
https://kriptoparahaber.com/cryptoads-ekibi-telekom-ve-blockchain-profesyonellerinden-destek-aliyor.html
https://kriptoparahaber.com/dijital-reklam-pazarinin-sorunlari-cryptoads-ile-tarih-oluyor.html
https://kryptomagazin.cz/cryptoads-vyberte-si-reklamu-a-sledujte-ji-za-odmeny/
https://kryptomagazin.cz/nove-ico-hodla-zrevolucionizovat-marketing-inzerci/
https://kryptomagazin.sk/cryptoadds-spojili-sily-so-spolocnostou-etherzero/
https://kryptomagazin.sk/cryptoads-bude-rozdavat-nove-hardware-penazenky/
https://kryptomagazin.sk/cryptoads-reklamna-platforma-spusti-predaj-tokenov/
https://portaldobitcoin.com/cryptoads-se-junta-com-etherzero-para-entregar-a-nova-era-da-distribuicao-de-anuncios/
https://portaldobitcoin.com/oleksii-vinogradov-fundador-e-presidente-da-cryptoads-quanto-maior-o-status-do-usuario-melhor-a-publicidade-que-ele-recebera/
https://profitgid.ru/cryptoads-predstavil-novyj-apparatnyj-koshelek-v-xode-starta-publichnoj-prodazhi-tokenov.html
https://sangus.org/ico/1468
https://tokenroster.com/projects/136
https://uzmancoin.com/cryptoads-online-reklam/
https://uzmancoin.com/cryptoads-satis/
https://uzmancoin.com/cryptoads-sona/
https://wiserico.com/ico/cryptoads
https://www.canardcoincoin.com/cryptoads-utilisateurs-choisir-publicites-regarder-obtenir-recompenses/
https://www.canardcoincoin.com/ico-cryptoads-publicite-numerique-decentralise-avec-icobox/
https://www.canardcoincoin.com/lequipe-de-cryptoads-une-belle-brochette-de-conseiller-pro-dans-les-telecommunications-et-la-blockchain/
https://www.coingecko.com/en/ico/cryptoads-marketplace
https://www.coinhills.com/ico/view/cryptoads-marketplace/
https://www.coinstaker.com/cryptoads-team-backed-by-telecoms-and-blockchain-professional-advisors/
https://www.criptomoedasfacil.com/cryptoads-e-apoiada-por-consultores-profissionais-de-telecomunicacoes-e-blockchain/
https://www.criptomoedasfacil.com/icobox-e-cfc-anunciam-parceria-para-iancar-token-que-promove-publicidade-digital-descentralizada/
https://www.criptomoedasfacil.com/venda-publica-da-cryptoads-comeca-com-o-anuncio-de-uma-nova-carteira-de-hardware/
https://www.criptomonedaseico.com/noticias/la-crowdsale-publica-de-cryptoads-comienza-con-un-anuncio-de-la-nueva-billetera-fisica/
https://www.criptonoticias.com/mercado-valores/tecnologia-blockchain-puesta-servicio-publicidad-cryptoads/
https://www.crypto-france.com/cryptoads-demarrage-vente-publique-hardware-wallet/
https://www.crypto-france.com/oleksii-vinogradov-cryptoads-publicite-en-ligne/
https://www.cryptoninjas.net/2018/04/18/icobox-and-cfc-announce-partnership-for-ico-of-cryptoads/
https://www.diariobitcoin.com/index.php/2018/04/20/icobox-y-cfc-se-asocian-para-ico-de-cryptoads-el-mercado-de-publicidad-digital-descentralizada/
https://www.diariobitcoin.com/index.php/2018/05/13/equipo-de-cryptoads-es-apoyado-por-asesores-profesionales-en-telecomunicaciones-y-blockchain/
https://www.diariobitcoin.com/index.php/2018/05/20/cryptoads-se-asocia-con-etherzero-para-ofrecer-una-nueva-era-de-publicidad-y-distribucion-de-marcas/
https://www.enigma.co.jp/media/page-24091/
https://www.filippomartin.com/icobox-e-cfc-annunciano-una-partnership-per-la-ico-cryptoads/
https://www.fxempire.com/crypto/ico/cryptoads
https://www.icoglory.com/ico/cryptoads
https://www.ilbitcoin.news/cryptoads-consentira-agli-utenti-di-scegliere-quali-annunci-guardare/
https://www.investinblockchain.com/cryptoads-etherzero-partnership/
https://www.money.it/cryptoads-annuncia-nuovo-portafoglio-hardware
https://www.money.it/CryptoAds-EtherZero-la-partnership-e-strategica
https://www.money.it/CryptoAds-il-team-e-esclusivo
https://www.money.it/La-blockchain-al-centro-pubblicita-online
https://www.newsbtc.com/2018/06/27/cryptoads-public-crowdsale-kicks-off-announcement-new-hardware-wallet/
https://www.sohu.com/a/232311019_251917
https://www.sohu.com/a/232320758_100042068
https://www.toutiao.com/i6557849850933674509/
https://www.youtube.com/watch?v=_S4RQG5CpKI&feature=youtu.be
https://www.youtube.com/watch?v=-ulGTtA_72o
https://www.youtube.com/watch?v=8rG2tTxq-tc&feature=youtu.be
https://www.youtube.com/watch?v=aki_Mjb0HoM&feature=youtu.be
https://www.youtube.com/watch?v=d9VS_FTwlRQ&feature=youtu.be
https://www.youtube.com/watch?v=EKoxzeKwUts
https://www.youtube.com/watch?v=fuoc_A3qhOg
https://www.youtube.com/watch?v=fYenByIa1gI
https://www.youtube.com/watch?v=ikc0k5c8i2w&feature=youtu.be
https://www.youtube.com/watch?v=P5rsl5MYu0c
https://www.youtube.com/watch?v=PVL2AFzOn9k&feature=youtu.be
https://www.youtube.com/watch?v=rPdlYxdq-d4
https://www.youtube.com/watch?v=RSY1yspZUtk
https://www.youtube.com/watch?v=ww2icEc74vs
https://youtu.be/ikc0k5c8i2w
https://youtu.be/syP1fqqzvW4?t=34m3s

**Comment by freeatnet** [comment]
Thank you for your request, @oleksiivinogradov!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1640.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1640.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
