### ISSUE TITLE
Tratin token

### ISSUE THREAD

**Issue by tratinproject** [forkdelta/tokenbase#1641]
<!-- 
<div class="ad"><img
src="http://tratin.io/wp-content/uploads/2018/08/874.png" height="96" width="96"
alt=""></a></div>

Hi there, please listed Tratin token on ForkDelta exchange. 
<br>Blockchain: Ethereum

Token contract: 0x3eb55d5b22ee0f9b03d59b4994c5ae7fe811be92

Token explorer: https://etherscan.io/token/0x3eb55d5b22ee0f9b03d59b4994c5ae7fe811be92

Website： http://tratin.io/

Type: ERC20

Token name： Tratin

Token abbreviation：TRAT

Token decimals: 8

Total supply： 144,287,391,827

Whitepaper: http://tratin.io/whitepaper/

Bitcointalk： https://bitcointalk.org/index.php?topic=4943791.msg44553220#msg44553220

Twitter：https://twitter.com/tratintoken

Telegram: https://t.me/tratin

GitHub: https://github.com/tratinproject/Tratin

Contact: tom@tratin.io

**Comment by tratinproject** [comment]
<div class="ad"><img
src="http://tratin.io/wp-content/uploads/2018/08/874.png" height="96" width="96"
alt=""></a></div>

Hi there, please listed Tratin token on ForkDelta exchange. 
<br>Blockchain: Ethereum

Token contract: 0x3eb55d5b22ee0f9b03d59b4994c5ae7fe811be92

Token explorer: https://etherscan.io/token/0x3eb55d5b22ee0f9b03d59b4994c5ae7fe811be92

Website： http://tratin.io/

Type: ERC20

Token name： Tratin

Token abbreviation：TRAT

Token decimals: 8

Total supply： 144,287,391,827

Whitepaper: http://tratin.io/whitepaper/

Bitcointalk： https://bitcointalk.org/index.php?topic=4943791.msg44553220#msg44553220

Twitter：https://twitter.com/tratintoken

Telegram: https://t.me/tratin

Contact: tom@tratin.io

**Comment by tratinproject** [comment]
Description:
Tratin (TRAT) protocol is operating on Ethereum ERC20 platform focusing on an open source peer-to-peer and business-to-customer cryptocurrency that offers secure, instant, decentralized and private transactions with unit value fungibility and Escrow function. With Tratin, users are able to do business where it is prohibitive before, such as high crime rates and frauds. The main objective is for daily usage with low fees and hassle free secured transaction. The whole idea of Tratin is to allow users to transfer payment to various sort of receivers, near instantaneously thus avoiding the normal “gate keeper” institutions that restrict access with fees, charges for currency exchanges and processing delays.

**Comment by freeatnet** [comment]
Closing duplicates #1641, #1632, #1614, #1655. Please file a single issue following the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
