### ISSUE TITLE
add mameCoin (MAME)

### ISSUE THREAD

**Issue by mameloper** [forkdelta/tokenbase#1642]
**Token address:**
0xABccaAdd77078A67622dFD5f74066ce4581c0a99

**Issuer's official website:**
https://mamecoin.jp/

**Description:**
Donations are now more accessible with cryptocurrencies. mameCoin will build up donation platform with blockchain.

**A link to the official contract address confirmation:**
https://mamecoin.jp/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://coinzmoney.com/8687
http://kedaman.net/mamecoin_japan
https://www.mamenews.net/?p=38
http://blog.livedoor.jp/kumokumowatawata/archives/11230465.html
https://matome.naver.jp/odai/2153430634646176201
https://togetter.com/li/1257439
https://kaishayameruzo.com/archives/6497
https://yurupura.com/blog/mamecoin-rain/
https://alis.to/yoshiyuki46/articles/KBXeAD9lmWvB
https://connect-material.com/mamecoin-worldairdrop/
http://www.caprico-log.com/entry/2018/09/03/070000

**Comment by freeatnet** [comment]
Thank you for your request, @mameloper!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1642.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1642.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
