### ISSUE TITLE
Add VGAMES (VGS)

### ISSUE THREAD

**Issue by Fiftycent187** [forkdelta/tokenbase#1643]
**0x4C9d5672Ae33522240532206Ab45508116daF263**

**http://dog.vgdapp.com**

**This is an ERC20 token which aims to harness dApp functionalities to cross breed dogs digitally** 

**https://etherscan.io/token/0x4C9d5672Ae33522240532206Ab45508116daF263** 

**https://m.weibo.cn/6360369679/GaIRUFDIk?&jumpfrom=weibocom  https://bitcointalk.org/index.php?topic=3336329.0   https://www.altcoinstalks.com/index.php?topic=15548.0**

1. 
2.

**Comment by freeatnet** [comment]
Thank you for your request, @Fiftycent187 !

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1643.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1643.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by Fiftycent187** [comment]
Thank you team, Awaiting listing.
