### ISSUE TITLE
Please add Tratin (TRAT)

### ISSUE THREAD

**Issue by brassalgoten** [forkdelta/tokenbase#1644]
The contract address.

https://etherscan.io/token/0x3eb55d5b22ee0f9b03d59b4994c5ae7fe811be92

A link to the token issuer's official website.

http://tratin.io

1-3 sentences for the token's description: at least one on the token issuer (eg., the product they are building) and one on token role.

Tratin is working towards mass-adoption of the use of the currency in real-life applications. From encouraging local busineses to accept Tratin as a method of payment, we are also looking to impliment our currency into many already heavily used ecommerce scripts. And on the user level being able to share money, wire money, or just send a gift to a friend, TRAT will make this possible! 

A link to an official page confirming the above contract address: this needs to be on the official domain of the token issuer.

http://tratin.io

**Comment by freeatnet** [comment]
Thank you for your request, @brassalgoten!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1644.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1644.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by tratinproject** [comment]
At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=4943791.msg44553220#msg44553220
2. https://t.me/tratin
