### ISSUE TITLE
Add FasTrader (FTD)

### ISSUE THREAD

**Issue by fastrader** [forkdelta/tokenbase#1645]
**Token address:**
https://etherscan.io/token/0xadc4c7037aa071b8e2b229debf645f9f70448234

**Issuer's official website:**
https://www.fastrader.io

**Description:** 

FasTrader is a tool developed by experts with artificial intelligence that analyzes the opportunities in the trade of cryptocurrency - an easy-to-use tool that helps people earn small profits from 1% to 2% daily. 

**A link to the official contract address confirmation:** 

https://imgur.com/sFL6aZf

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.coindiary.net/fastrader-%E2%80%8Bhuman-artificial-intelligence-for-crypto-trading/
2. https://findico.io/airdrops/Fastrader-ftd

**Comment by freeatnet** [comment]
Thank you for your request, @fastrader!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1645.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1645.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
