### ISSUE TITLE
Add SURETY Token (SURE)

### ISSUE THREAD

**Issue by kevin17108** [forkdelta/tokenbase#1646]
**Token address:** 0x95382ac82e886a367bac9e1e23beabe569bcfed8

**Issuer's official website:** https://hearti.io/suretyai/

**Description:** Smart Micro-Insurance for the Unbanked on Blockchain.

**A link to the official contract address confirmation:** https://ico.surety.ai/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://www.insurancebusinessmag.com/asia/features/interviews/turning-trials-into-technologyassisted-insurance-93225.aspx
2. http://www.nationmultimedia.com/detail/Corporate/30346818

**Comment by kevin17108** [comment]
We published our token info with company website in Etherscan:

https://etherscan.io/token/0x95382ac82e886a367bac9e1e23beabe569bcfed8

**Comment by freeatnet** [comment]
Thank you for your request, @kevin17108!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1646.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1646.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by kevin17108** [comment]
Hi, could you please let me know when will my token be listed?

**Comment by kevin17108** [comment]
We didn't include the token address in our website due to the design of our website. We did put full of our token info with the link to our website in both coingecko and etherscan

https://www.coingecko.com/en/coins/surety-token

https://etherscan.io/token/0x95382ac82e886a367bac9e1e23beabe569bcfed8
