### ISSUE TITLE
BitCoin ONE

### ISSUE THREAD

**Issue by BitCoinONE1** [forkdelta/tokenbase#165]
Name: BitCoin ONE
Ticker: BTCONE
Decimals: 18
Type: ERC20 Token

Social:

E-mail: contact@bitcoinone.io
Twitter: https://twitter.com/THEBITCOINONE
Bitcointalk:
https://bitcointalk.org/index.php?topic=3024070
Medium:
https://medium.com/@karldark/bitcoin-one-the-unparalleled-means-of-crypto-payment-e9b67641fad6
Telegram: https://t.me/TheBitCoinONE
Discord: https://discord.gg/uxpaTfV

Contract address:

0x87f5e8c3425218837f3cb67db941af0c01323e56

A link to the token issuer's official website.

https://www.bitcoinone.io

A couple sentences for token description.

BitCoin ONE is going to be a payment solution and is going to be a part of our own developed blockchain and be a part of this ecosystem.
BitCoin ONE Launch Q1 and new Blockchain Q3 2018.

A link to an official page confirming the contract address.

https://etherscan.io/token/0x87f5e8c3425218837f3cb67db941af0c01323e56

A link to a third-party review or discussion of the token, like an established ICO review blog.

Thanks in advance and if any questions please reach out

Thanks

Luke Dev

**Comment by Kryptoniq** [comment]
Please provide an official link (not Etherscan) verifying the contract address. E.G  on the website or whitepaper.

**Comment by BitCoinONE1** [comment]
Hi again

Thanks for fast feedback

Contract address appears on page 5 in our Whitepaper

You can view it without downloading on the site.

https://www.bitcoinone.io/whitepaper/

Thanks again

Luke

**Comment by Kryptoniq** [comment]
Everything looks good.
Verified 0x87f5e8c3425218837f3cb67db941af0c01323e56.

**Comment by Kryptoniq** [comment]
Bitcointalk page has been removed.

**Comment by BitCoinONE1** [comment]
Hi

Thanks for heads up.

Yeah we have just seen, one of our developer were updating and then it 
was removed suddently, we are working on fixing this.

We are interested in listing in first week of march.

If you have any questions please reach out

Have a great day

/ Luke

**Comment by BitCoinONE1** [comment]
https://bitcointalk.org/index.php?topic=3024070.0

Thanks

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has no reviews.

**Comment by BitCoinONE1** [comment]
Hi Kryston.

If you look at our whitepaper you will find relevant information further our very active twitter account.

We will update our Bitcointalk also what goes to right graffic / signatur and so on for next step.

We will also start updating our github account soon what goes to development, both on mobile swift iOS and java Android - so please follow a long.

You actually have some good repositories on your account :-).

/* 
You are free to contact me or George on our telegram / discord if you have any questions.
Have a great day 
Thanks & have a great day  Luke 
*/

**Comment by Kryptoniq** [comment]
We'll come to this once you get sufficient reviews on your bitcointalk announcement thread or any other public review of your token.

**Comment by BitCoinONE1** [comment]
Hi Krypton

A lot of activity and also building a strong community - also if you look at twitter and telegram.

Just have a look at comments and more in these links:

We are doing pretty good what goes to reviews, further are we launching a presentation video during the next couple of days.
We will further do meetups to cast some interest to the project.

https://feedback.altcoinexchange.com/suggestions/6228/bitcoin-one-the-new-payment-solution

https://nextexchange.featureupvote.com/suggestions/6226/bitcoin-one-the-new-payment-solution

https://request.coinpulse.io/suggestions/6227/bitcoin-one-the-new-payment-solution

https://lescovex.featureupvote.com/suggestions/6187/bitcoin-one-new-blockchain-payment-solution

https://cryptosocial.world/post/10587_bitcoin-one-the-unparalleled-means-of-crypto-payment-bitcoin-is-the-first-and-un.html

https://medium.com/@karldark/bitcoin-one-the-unparalleled-means-of-crypto-payment-e9b67641fad6

Thanks

/ Luke

**Comment by BitCoinONE1** [comment]
and some more action on our bitcointalk profile - follow along 👍

**Comment by BitCoinONE1** [comment]
Hi Krypton

Now we and the community are more active on bitcointalk as well.

Please have a look.

https://bitcointalk.org/index.php?topic=3024070

Thanks in advance 

/ Luke.

**Comment by Kryptoniq** [comment]
Yet to find constructive reviews, only generic comments.

**Comment by BitCoinONE1** [comment]
Hi again

Added to exchange today and 2 more in this week.

We are active on bitcointalk and more fora.

We have medium coverage, there is really not so much to review at this stage.

1. It is a basic ERC 20 token.

But how we stand out to many of the listed tokens I see get further is that we are building our own APP to be launched - so we have actually a product coming out with a use case.

Further, if you look at our twitter you can see some screenshots of our work and also what we are doing + we are doing community votes + actively attending mobile and blockchain summits.

Thanks

/ Luke

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x87f5e8c3425218837f3cb67db941af0c01323e56, https://www.bitcoinone.io

**Comment by BitCoinONE1** [comment]
Thanks for update - we are ready 👍

**Comment by freeatnet** [comment]
[BitCoinONE whitepaper](https://www.bitcoinone.io/wp-content/uploads/2018/02/Whitepaper-BitCoinONE.pdf) "The Project" section appears to be copied from BITDARK [BitcoinTalk thread](https://webcache.googleusercontent.com/search?q=cache:PE_iIIMjvZsJ:https://bitcointalk.org/index.php%3Ftopic%3D2890962.660+&cd=4&hl=en&ct=clnk&gl=ru) (Feb 11, 2018), which itself seems to be based on thecypherfunks.com (see: [Feb 16, 2014 BitcoinTalk thread](https://bitcointalk.org/index.php?topic=469407.0)).

We have a definitive stance against plagiarism, and will not be listing your token at this time.

If you believe this judgement was made in error, you can post an appeal in this thread. In your appeal, you must include objective facts that support validity of your project, e.g., delivered product, notable references by impartial sources, or specific steps you have taken to remedy the issue above.

**Comment by BitCoinONE1** [comment]
Hi again

Thank you for reading the whitepaper and helping out.

We have removed the 2 lines in the 11 pages whitepaper, that you have found problematic. 

You are welcome to do a google search of the whole whitepaper and I am quite 
sure you will not find more than some words you can find other places.

We have made this whitepaper and anyone is welcome to do a search.

Money for digital age and a lot of the buzz words are really standard in the scene 
and we are so certain that we have made this ourselves that we have 10 translators 
atm translating it. 

If anyone in here finds pieces in this whitepaper they can find other places.

Must be more than 1 line will there be a bounty.


Thanks in advance

/ Luke

**Comment by BitCoinONE1** [comment]
https://www.bitcoinone.io/whitepaper

**Comment by BitCoinONE1** [comment]
Update 

Yes I see some of the words as you mentioned has BitDark which is on your exchange 
and this is similar to the words being used in 2014 as well.

**Comment by Kryptoniq** [comment]
@BitcoinONE1 For clarifications; BitDark is not officially listed on ForkDelta.

**Comment by BitCoinONE1** [comment]
Ok Noted.

// Have a great day
