### ISSUE TITLE
Add KriosCoin (KRI)

### ISSUE THREAD

**Issue by NGUYENVQHUNG** [forkdelta/tokenbase#1650]
Token address: 0xeef8102A0D46D508f171d7323BcEffc592835F13

Issuer's official website: https://www.krios.io/

Description: Krios is an affiliate network & campaign management platform that incorporates blockchain technologies to help connect businesses seeking promotional and affiliation activities with influencers who have relevant demographics and professionals who offer relevant services.

A link to the official contract address confirmation: https://etherscan.io/address/0xeef8102a0d46d508f171d7323bceffc592835f13#code

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer: 
1. https://bitcointalk.org/index.php?topic=2334680.0
2. https://twitter.com/krios_io

**Comment by freeatnet** [comment]
Thank you for your request, @NGUYENVQHUNG !

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1650.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1650.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
