### ISSUE TITLE
Add ElevenOfTwelve (11of12)

### ISSUE THREAD

**Issue by d-bayer** [forkdelta/tokenbase#1651]
Token address: 0xa01d9BAfA60fbd1967bacF74B76c7e464d0F7c92

Issuer's official website: http://www.11of12.com/

Our goal is to offer the once very successful Facebook game 11of12 as a WEB application, Android and iPhone app. 11of12 is a mathematical game based on the "Travelling Salesman Problem". We are planning, to offer more games with educational background. 11of12 is not a game of hazard because the best solution is not determined by chance. The best players will get paid out 11of12 Coins as prize money. A participation fee of 11of12 coins is required. The programm code of the app will not be public, but the coin can be traded freely. 

TIMELINE PAST: 

• At the beginning of 2015, we developed the Facebook game 11of12. 
• The 11of12 coin was distributed by an ICO in the second half of 2017 over a period of six months. 
• We deactivated the game 11of12 due to changes in privacy policies in early 2018 on Facebook. 

TIMELINE FUTURE: 

• December 2018: The game 11of12 will be available as a WEB-APP. 
• April 2019: The game 11of12 will be available in the PLAY-Store. 
• August 2019: The game 11of12 will be available in the APP-Store. 
• And more projects will follow.

Official contract address confirmation:
http://www.11of12.com/

Contract code:
https://etherscan.io/address/0xa01d9BAfA60fbd1967bacF74B76c7e464d0F7c92#code

Tokenholderchart:
https://etherscan.io/token/tokenholderchart/0xa01d9BAfA60fbd1967bacF74B76c7e464d0F7c92

Thank you!
David

**Comment by freeatnet** [comment]
Thank you for your request, @d-bayer!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1651.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1651.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by d-bayer** [comment]
The game 11of12 is available as a WEB-APP now!

http://www.11of12.com/app

A partition fee will be required in the near future. So hurry up to earn coins right now.
