### ISSUE TITLE
Kindly add TSU tsunami to the trading

### ISSUE THREAD

**Issue by tsunami106** [forkdelta/tokenbase#1652]
Tsunami is a community project a promising coin that is ready to breach the gap between the poor and the rich and famous people born in the society it is also and Ethereum base network and in future has the plan of creating it own blockchain technology and with the ace to make digital currency a fast and reliable on also set to help liberate the needy and the poor join it will also help reach out to the less privilege it a token worth spending on
-->
1. We will like you to add TSU to the trading pair 
2.TSU
0x50A7Da1bd921ac68D0978C00c1D66637c968159c
http://www.tsunamicharityfoundation.com

https://t.me/joinchat/HsbDpFIUCakERbcZEE28LA

https://www.facebook.com/Tsunamicharityfoundation.io

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
