### ISSUE TITLE
Add VENUS (VENUS)

### ISSUE THREAD

**Issue by NGUYENVQHUNG** [forkdelta/tokenbase#1653]
Token address: 0xEbeD4fF9fe34413db8fC8294556BBD1528a4DAca

Issuer's official website: https://venusenergy.io/

Description: The VenusEnergy team supports the idea of pure world and seeks to propagate the use of renewable energy sources in daily activities. The increase of Bitcoin demand will also result in the increase of the scope of mining works, while using renewable energy sources in performing the works leads to saving nature, whereas the work is done in the same efficient manner. The result of VenusEnergy project is mining platform where electricity is made from renewable energy sources.

A link to the official contract address confirmation:  https://etherscan.io/address/0xebed4ff9fe34413db8fc8294556bbd1528a4daca#code

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://www.reddit.com/user/VenusEnergy/
2. https://medium.com/@venusenergy/

**Comment by freeatnet** [comment]
Thank you for your request, @NGUYENVQHUNG!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1653.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1653.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
