### ISSUE TITLE
Hi Team!

### ISSUE THREAD

**Issue by GYMRewards** [forkdelta/tokenbase#1654]
We Have launched out GYM Rewards App. It allow people to earn tokens while exercising. How can we officially add the token? 

The app will support ERC GYM Token and EOS GYM Rewards Token.

https://forkdelta.github.io/#!/trade/0x92d3e963aa94d909869940a8d15fa16ccbc6655e-ETH

https://gymrewards.io

**Comment by freeatnet** [comment]
Closed by #1656.
