### ISSUE TITLE
Please read this

### ISSUE THREAD

**Issue by tratinproject** [forkdelta/tokenbase#1655]
<div class="ad"><img
src="http://tratin.io/wp-content/uploads/2018/08/874.png" height="96" width="96"
alt=""></a></div>

Hi there, please listed Tratin token on ForkDelta exchange. 
<br>The contract address.

https://etherscan.io/token/0x3eb55d5b22ee0f9b03d59b4994c5ae7fe811be92

A link to the token issuer's official website.

http://tratin.io

1-3 sentences for the token's description: at least one on the token issuer (eg., the product they are building) and one on token role.

Tratin is working towards mass-adoption of the use of the currency in real-life applications. From encouraging local busineses to accept Tratin as a method of payment, we are also looking to impliment our currency into many already heavily used ecommerce scripts. And on the user level being able to share money, wire money, or just send a gift to a friend, TRAT will make this possible!

A link to an official page confirming the above contract address: this needs to be on the official domain of the token issuer.

http://tratin.io

Contact: tom@tratin.io

**Comment by freeatnet** [comment]
Closing duplicates #1641, #1632, #1614, #1655. Please file a single issue following the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
