### ISSUE TITLE
Add GYM Rewards (GYM)

### ISSUE THREAD

**Issue by GYMRewards** [forkdelta/tokenbase#1656]
**Token address:**
https://etherscan.io/token/0x92d3e963aa94d909869940a8d15fa16ccbc6655e

**Issuer's official website:**
https://gymrewards.io 

**Description:** 
GYM Rewards allows for users to earn cryptocurrency via our Proof of Exercise Token. Mine with your body!

**A link to the official contract address confirmation:** 
https://etherscan.io/address/0x92d3e963aa94d909869940a8d15fa16ccbc6655e

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

https://www.youtube.com/results?search_query=GYM+Rewards+Token
https://bitcointalk.org/index.php?topic=3053926

1. Telegram: https://t.me/gymrewards
2. Twitter: https://twitter.com/GymRewards
3. Facebook: https://www.facebook.com/gymrewards.io/

**Comment by freeatnet** [comment]
Thank you for your request, @GYMRewards!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1656.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1656.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by GYMRewards** [comment]
Thank you!
