### ISSUE TITLE
Add LOOMIA TILE (TILE)

### ISSUE THREAD

**Issue by rodriguezmarco8** [forkdelta/tokenbase#1658]
**Token address:**
0x25f735b108b4273fb0aceb87599ed8bba10065de

**Issuer's official website:**
https://loomia.com

**Description:** 
Loomia is a smart textiles company that aims to disrupt the clothing and fashion industries. Their secret is their Tile tag and Smart fabric technology that does cool things like change colors, warm up and collect valuable information on  usage habits and conditions that the users can then sell to big brands.
Loomia put users in charge of their information and offers the possibility to sell it to industry brands for a reward. Information that can be sold includes for example how many times an outfit has been worn in a period of time, how often it is washed, what's the temperature, etc.

The $TILE token operates in the ethereum blockchain and it is the currency for brands to pay users for sharing their smart clothes information. 

Loomia tech is ready for mass production and 
 will be launching the first Loomia-powered wearables with a surprise BIG brand in Fall 2018.

The Loomia app will be released soon in September 2018.

TILE token distribution to private sale and airdrop participants on August 30. There was no public sale.

The TILE token is currently on IDEX and integration with Bancor is confirmed.

**A link to the official contract address confirmation:** 

https://etherscan.io/token/0x25f735b108b4273fb0aceb87599ed8bba10065de

Contract address was announced on Loomia's official telegram announcements group:
https://t.me/LOOMIA_OFFICIAL_ANN/37

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.google.ca/amp/s/www.forbes.com/sites/rachelarthur/2017/09/08/data-from-your-clothing-could-soon-earn-you-digital-currency-thanks-to-this-blockchain-integration/amp/
2.
https://www.wired.co.uk/article/smart-materials-loomia-clothes-sensors

**Comment by freeatnet** [comment]
Thank you for your request, @rodriguezmarco8!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1658.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1658.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
