### ISSUE TITLE
Listing Request - CARLOS MATOS TOKEN (HEY)

### ISSUE THREAD

**Issue by Picapica2201** [forkdelta/tokenbase#166]
addr: '0x278f5d89c85a4ac8aaa39e08444212cbb2546fd2'
decimals: 18
description: Carlos Matos Coin (HEY) its a revolutionary coin who is changing the world as we know it.
Name: Carlos Matos Token.
TOKEN: HEY

Token: HEY
Name: Carlos Matos Token.
Contract Address: 0x278f5d89c85a4ac8aaa39e08444212cbb2546fd2
Website: https://boards.4chan.org/biz/
BITCOINTALK: https://bitcointalk.org/index.php?topic=2994076.0
Twitter: https://twitter.com/MatosCoin

**Comment by Kryptoniq** [comment]
Please provide a link to the official website confirming the contract address.

**Comment by Kryptoniq** [comment]
#207
