### ISSUE TITLE
Forza [FOZ] Request listing

### ISSUE THREAD

**Issue by Forza10** [forkdelta/tokenbase#1660]
hello forkdelta
im request token listing
Name    : Forza
Ticker    :FOZ
Contract : 0xef5e8fc138f08ade0a6d419699fd34f4720e6a38
Decinimal : 18
etherscan : https://etherscan.io/address/0xef5e8fc138f08ade0a6d419699fd34f4720e6a38
Website : http://foz.cash
Whitepaper include at website
im request listing for sell promosale stage 2 

thanks
Forza Team

**Comment by Forza10** [comment]
Forza Smartcontract update

hello forkdelta
im request token listing
Name : Forza
Ticker :FOZ
Contract : 0xd4C182C9889B90b777d31dc5C1B0b5C30CB30f7f
Decinimal : 18
etherscan : https://etherscan.io/address/0xd4C182C9889B90b777d31dc5C1B0b5C30CB30f7f
Website : http://foz.cash
Whitepaper include at website
im request listing for sell promosale stage 2

thanks
Forza Team

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
