### ISSUE TITLE
Applying for listing of Vixcore token(VXCR1) on Forkdelta

### ISSUE THREAD

**Issue by mandongjun** [forkdelta/tokenbase#1662]
Contract address: 0x5aB415906AC77E20618fAb6aC1d56D331813f9D9
Issuer's official website: https://vixcore.com/

Official contract address confirmation: https://vixcore.com/

A link to a third-party review or discussion of the token: 
https://bitcointalk.org/index.php?topic=4801850.0
https://steemit.com/crypto/@jezmacher/vixcore-crowdsale-and-selfdrop

Description: VXCR, an ERC20 token built on the Ethereum blockchain, will be the unit of exchange within our affiliated network of betting platforms.
Initially it will be available for use within the existing, operational platforms, alongside traditional currencies, to ensure immediate utility for token holders.

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
