### ISSUE TITLE
Requesting BitonlineStore Token on ForkDelta exchange

### ISSUE THREAD

**Issue by EquinoxToken** [forkdelta/tokenbase#1663]
Hi there, please listed BOST token on ForkDelta exchange.

The contract address.

https://etherscan.io/token/0x133043ce2cc38cdb32a13a245e82fba9e13b743a

A link to the token issuer's official website.

http://bitonlinestore.com

Contact: suport@bitonlinestore.com

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
