### ISSUE TITLE
Request to Listing  [ICH] - ICOStart Token

### ISSUE THREAD

**Issue by ICOStart** [forkdelta/tokenbase#1664]
Hi,
# Listing Request # 
name: ICOStart Token 
symbol: ICH
addr: '0x330839EF82D34801bd96e75a4Ee778ac56Fa1ED8'
decimals: 18
links:
- Email: info@icostart.ch
- Telegram: https://t.me/ICOStartOfficials
- Facebook: https://www.facebook.com/icostart/
- Twitter: https://twitter.com/IcoStart_ch
- Medium: https://medium.com/@icostart.ch
- GitHub: https://github.com/ICOStart/ICOStart
- BitCoinTalk: https://bitcointalk.org/index.php?topic=3104087
- Website: https://icostart.ch/
- Whitepaper: https://icostart.ch/wp-content/uploads/2018/07/WhitePaper_web.pdf
Review : 
https://icomarks.com/ico/icostart
https://icostock24.com/projects/icostart/
https://www.fxempire.com/crypto/ico/icostart
https://bitcoinexchangeguide.com/icostart-ico-ich-token/
https://icobench.com/ico/icostart

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
