### ISSUE TITLE
Add Oxytoken ( OXY )

### ISSUE THREAD

**Issue by oxytoken** [forkdelta/tokenbase#1665]
Name : OxyToken
Symbol : OXY
Token: ERC20
Decimals : 8
total suplay : 20,000,000,000
Contract address: 0x581c9BA7A3dE3944E051c585C273974EE4570502
Etherscan: https://etherscan.io/token/0x581c9ba7a3de3944e051c585c273974ee4570502
Issuer's official website: http://oxycoinnetwork.com/

Link to bitcointalk: https://bitcointalk.org/index.php?topic=5023770.msg45333807#msg45333807
Link to Twitter: https://twitter.com/oxy_coin
Link to Discord: https://discord.gg/R2336av
Code : https://github.com/oxytoken/oxy/blob/master/oxytoken.sol
Description:

Oxy Tokens are Crypto Currencies used in the Oxy network. The Oxy network includes exchanges, payment systems, and various online transactions. Guarantee comfort, efficiency and security in every transaction. It is very profitable to be saved as a digital asset in the future. Oxy Token development on various platforms continuously. 

Email: support@oxycoinnetwork.com

Thank you

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
