### ISSUE TITLE
ClassyCoin Token Swap 

### ISSUE THREAD

**Issue by jaybejaybe** [forkdelta/tokenbase#1666]
Hello, we’re conducting token swap and would like to update ClassyCoin to new Token. 

New token contract information

Name: CLASSY 
Symbol: CLASSY 
Decimal: 18
Total Supply: 100M

Contract address:
https://etherscan.io/address/0x8cc3b3e4f62070afb2f0dfece7228376626c1b0c

ClassyCoin Token Swap. 

ClassyCoin Token swap will occur between September 10th – October 10th (GMT+8).
If your ClassyCoin is held in a exchange, you must withdraw it to your wallet and send to swap contract address to receive new CLASSY Token to avoid any loss. If you miss this deadline, you can always visit swap contract at anytime to perform the swap. 

Swap ratio is 1:1

Please follow this instructions to send your ClassyCoin to swap contract for swap to new CLASSY Token.

Token Swap Instruction 

1. Go to https://www.myetherwallet.com/#contracts
2. Place contract address: 0x30CC0e266cF33B8eaC6A99cBD98E39b890cfD69b
3. Place Contract ABI from https://etherscan.io/address/0x30CC0e266cF33B8eaC6A99cBD98E39b890cfD69b#code
4. Click Access
5. Select balanceOf
6. Place your wallet address
7. Press read
8. Copy your balance
9. On function list change balanceOf to approveAndCall
10. Place the swap contract address as spender: 0x4bd14C9B1f4d3027B54Aa8e4BcF8ad217ca5e75a
11. Paste your balance on the value section
12. Connect to Metamask
13. WRITE
14. Confirm your transaction

**Comment by therealMikkoK** [comment]
@freeatnet What can I do to take this forward?
