### ISSUE TITLE
Request to Listing [RIGS] - RIGS OIL TOKEN

### ISSUE THREAD

**Issue by rigsoiltoken** [forkdelta/tokenbase#1667]
**Name**: RIGS OIL TOKEN
**Symbol**: RIGS
**Decimals**: 8
**Total Supply**: 12,000,000,000
**Contract Address**: 0x69b0adec3cb113132c970f3440302df81962d7f6
![rigs logo](https://user-images.githubusercontent.com/40638477/45325282-09197d80-b540-11e8-8fd6-127745d5451a.png)

**Email**: admin@rigsoiltoken.xyz
**Website**: [http://rigsoiltoken.xyz/](http://rigsoiltoken.xyz/)
**Explorer**:https://ethplorer.io
**BitcoinTalk**:https://bitcointalk.org/index.php?topic=4555216.0
**Reddit**: https://www.reddit.com/r/u_RIGSOILTOKEN/
**Medium**: https://medium.com/@rigsoiltoken

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
