### ISSUE TITLE
Requet token isting VOIPtoken

### ISSUE THREAD

**Issue by voiptoken** [forkdelta/tokenbase#1668]
Name: Voiptoken
Symbol: VOIP
Decimals: 8
Total Supply: 20,000,000,000
Contract Address: 0x3da034753b42bda1bcfa682f29685e2fd6729016
https://etherscan.io/token/0x3da034753b42bda1bcfa682f29685e2fd6729016?

Email: info@voipfutures.com
Website: http://voipfutures.com
Explorer:https://ethplorer.io

**Comment by freeatnet** [comment]
Please file a request using the required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!
