### ISSUE TITLE
Request to add BOB token

### ISSUE THREAD

**Issue by pash7ka** [forkdelta/tokenbase#1669]
**Token address:**
0xDF347911910b6c9A4286bA8E2EE5ea4a39eB2134

**Issuer's official website:**
https://www.bobsrepair.com

**Description:** 
Using Blockchain to eliminate review fraud and provide lower pricing in the home repair industry through a decentralized platform.
The BOB token is primarily a utility token that allows users to access and use a network of
skilled trade workers as well as a smart-contract-based escrow service for home repair, new
construction, and other service jobs. 

**A link to the official contract address confirmation:** 
https://www.bobsrepair.com/tokensale/#token-sale

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icobench.com/ico/bob-s-repair
2. https://tokentops.com/ico/bobs-repair/#section-review-block
3. https://coinmarketcap.com/currencies/bobs-repair/
4. https://www.coingecko.com/en/coins/bobs-repair

**Comment by therealMikkoK** [comment]
token traded on two exchanges, where one exchange produces daily volume exceeding 100.000 USD daily.

**Comment by therealMikkoK** [comment]
@pash7ka 
Thank you for the application.
Please consider using an outside reviewer for your token. A news bulletin or an opinion piece is not the kind of review we're thinking of.
