### ISSUE TITLE
Request to list Nova Token (NVT)

### ISSUE THREAD

**Issue by NovaBlitz** [forkdelta/tokenbase#167]
**The contract address**
https://etherscan.io/address/0x09d8b66c48424324b25754a873e290cae5dca439

**A link to the token issuer's official website**
https://novablitz.com/

**A couple sentences for token description**
The Nova Token enables the creation, sale, and trading of collectible tokenized cards across any digital trading card game. The Nova Token can also be used to enter in-game tournaments and pay for other in-game purchases.  This allows the Nova Token to completely replace fiat currencies in any game that implements it.  Game developers that are integrated into the Nova Token platform benefit because they earn a share of Nova Token revenue.

**A link to an official page confirming the contract address**
https://novablitz.com/nova-token-information

**A link to a third-party review or discussion of the token, like an established ICO review blog**
https://icorating.com/analytics/basic/nova-blitz-basic-review/
https://icobench.com/ico/nova-blitz/ratings

**Comment by Kryptoniq** [comment]
Verified 0x09d8b66c48424324b25754a873e290cae5dca439.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
