### ISSUE TITLE
Add Relex Life (RLXI)

### ISSUE THREAD

**Issue by jtoncic** [forkdelta/tokenbase#1672]
Hi, I'm writing to request a listing for Relex Life. 

Relex Life is a cryptocurrency solution for crowdfunding the R&D of new health and wellness products, with our first partnership focusing on a patented inhalable technology. 

Website: https://life.relex.io/
White Paper: https://life.relex.io/assets/pdf/Relex%20Life%20Working%20Paper.pdf

Token Details:
Total Supply: 1,000,000,000 (1 billion) RLXI Tokens
Contract Address: 0xd0a024e4b057024f941051dc19220a3bab4b5d45
Decimals: 18

RLXI is an ERC-20 compliant token running on the Ethereum network. It is intended to be a
utility token creating connection between manufacturers and various customer constituencies to
improve their transaction.

The currency is distinguished by its method of introduction. It had no ICO and no token sales. It
was introduced as an air drop to be granted to all RLX holders who were holding their tokens in
wallets, and not in exchanges. Additionally, the team's reserve supply of RLX tokens was not
duplicated to RLXI, cutting the total number of tokens in half (from 2 billion RLX tokens to 1
billion RLXI tokens). Exchange-held tokens were retained by the team.

**Comment by therealMikkoK** [comment]
@jtoncic 
Thank you for your application.

In looking in to your White Paper, I noticed this claim
"Relex Life's first offering – a pharmacopeia of nutrients, supplements, and pharmaceuticals that
can be made inhalable – is just the cornerstone of where Relex Life plans to go."
I didn't know people can absorb any vitamins through inhalation, can you link to a study as a favor?

Can you describe what problem does the token solve?
Please explain the token holders earning logic.

I also wish to remind you, we do not ask for or require any compensation for the possible listing of your token. Any requests to that nature can be safely disregarded.

Keep an eye out for this post, as here is where we ask questions and give answers to yours.

**Comment by jtoncic** [comment]
Hi Mikko,


Thank you for your response. As for how it's done, please see this patent held by our partner: https://patents.google.com/patent/WO2017024033A1/en


Blockchain cryptocurrency (RLXI) in this case acts as a funding mechanism for R&D, and it also can be used to secure distribution lines, and it is also used solely as a currency to buy products from the Aura Inhale web store.


Cryptocurrency makes cross-border funding easier, and it also secures people's investment into the new compounds developed with this technology.


JASON TONCIC

CMO | Relex

1814 East Route 70 | Suite 337 | Cherry Hill, NJ 08003

T +1 732-221-9788 XXX

j.toncic@relex.io

Follow Relex:  relex.io<http://relex.io/> | Telegram<https://t.me/relex_core> | Twitter<https://twitter.com/RelexTalk> | Medium<https://medium.com/@j.toncic> | Facebook<https://www.facebook.com/RelexTalk> 


________________________________

**Comment by therealMikkoK** [comment]
@jtoncic do you have any token review from an independent party?
What does the token do, the elevator pitch?
With this token I can...?

**Comment by jtoncic** [comment]
For more information, you can see our professional explainer video: https://www.youtube.com/watch?v=gC6DlmXEakE


Relex Life is a token used to fund the development of inhalable nutrients, supplements, vitamins, and pharmaceuticals. It is the only such platform that exists in the world. The work is done under our partner, Aura Inhale. They have secured the patent to this process, which you can find here:

https://patents.google.com/patent/WO2017024033A1/en

Blockchain cryptocurrency (RLXI) in this case acts as a funding mechanism for R&D, and it also can be used to secure distribution lines, and it is also used as a currency to buy products from the Aura Inhale web store.

Our website can be found here: https://life.relex.io/

Our Working Paper can be found here: https://life.relex.io/assets/pdf/Relex%20Life%20Working%20Paper.pdf

The platform is already fully functional. For example, if you had an idea for a new inhalable supplement, like inhalable Vitamin-D, you could develop it using our platform.

Thank you for your time.


Best,


JASON TONCIC

CMO | Relex

1814 East Route 70 | Suite 337 | Cherry Hill, NJ 08003

T +1 732-221-9788 XXX

j.toncic@relex.io

Follow Relex:  relex.io<http://relex.io/> | Telegram<https://t.me/relex_core> | Twitter<https://twitter.com/RelexTalk> | Medium<https://medium.com/@j.toncic> | Facebook<https://www.facebook.com/RelexTalk> 




JASON TONCIC

CMO | Relex

1814 East Route 70 | Suite 337 | Cherry Hill, NJ 08003

T +1 732-221-9788 XXX

j.toncic@relex.io

Follow Relex:  relex.io<http://relex.io/> | Telegram<https://t.me/relex_core> | Twitter<https://twitter.com/RelexTalk> | Medium<https://medium.com/@j.toncic> | Facebook<https://www.facebook.com/RelexTalk> 


________________________________

**Comment by therealMikkoK** [comment]
@freeatnet no obvious reason to hold the listing. I say let's proceed.

**Comment by jtoncic** [comment]
Hello, thank you for your help thus far. Just seeing if we could take the final listing step.


Thanks,


JASON TONCIC

CMO | Relex

4000 S. Faber Place Drive | Suite 300 | Charleston, SC

T +1 732-221-9788 XXX

j.toncic@relex.io

Follow Relex:  relex.io<http://relex.io/> | Telegram<https://t.me/relex_core> | Twitter<https://twitter.com/RelexTalk> | Medium<https://medium.com/@j.toncic> | Facebook<https://www.facebook.com/RelexTalk> 


________________________________

**Comment by jtoncic** [comment]
Hi, we at the Relex Life team have been waiting for this listing to be finalized. Is there any additional hold up that we can help address?

The first inhalable created with funding provided by Relex Life has since been completed. the "Stop Smoking" device is now a working product and is being distributed as samples to original backers. 

We are hoping to create more inhalables soon, and this listing would help individuals be able to participate. 

Thank you,
Jason Toncic

**Comment by jtoncic** [comment]
@freeatnet @therealMikkoK
