### ISSUE TITLE
Add ABC - Anti Bureaucracy Coin (ABC)

### ISSUE THREAD

**Issue by eddieoz** [forkdelta/tokenbase#1673]
**Token address:**
0xAfd75caff5c1d402cbF3692e289775438dF6a9F0

**Issuer's official website:**
https://originalmy.com

**Description:** 
Since 2015, OriginalMy is the first brazilian company using many blockchain protocols for certifying identities, signatures on contracts and digital documents. 
Anti Bureaucracy Coin comes to help fighting all kind of bureaucracy. It will be used for accessing the platform services and in the future it will work as a reward for the decentralized network of personal data validators, as a reward for the customers who deliver their personal data too.

**A link to the official contract address confirmation:** 
Address: https://github.com/OriginalMy/originalmy-dapp-addresses/blob/master/contract-addresses.js
About: https://originalmy.com/abc

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcoinexchangeguide.com/originalmy/
2. https://www.rvo.nl/sites/default/files/2018/02/brazils-beginning-blockchain-business.pdf
3. http://tiinside.com.br/tiinside/home/internet/10/09/2018/foxbit-e-abfintechs-elegem-diretoria-por-meio-de-plataforma-blockchain/
4. https://www.criptomoedasfacil.com/candidato-a-presidencia-diz-que-implantara-governo-digital-no-brasil/
5. http://www.digitaljournal.com/pr/3898604
6. https://epocanegocios.globo.com/Mercado/noticia/2017/11/original-my-planeja-ico-ainda-este-ano.html
7. https://reason.com/reasontv/2016/11/29/bitcoin-blockchain-brazil-venezuela

**Comment by therealMikkoK** [comment]
@ @freeatnet 
not yet seen the WP, but social media seems very responsible and there are actual projects using the token.
First impression positive.

**Comment by eddieoz** [comment]
Hello,

Pls, reconsider listing the ABC on forkdelta.

Regards,
Edilson
