### ISSUE TITLE
Add SpectrumNetwork (SPEC)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1674]
**Token address:** 0x259059f137cb9b8f60ae27bd199d97abb69e539b

**Issuer's official website:** https://www.the-spectrumnetwork.com

**Description:** SPEC token leverages on blockchain technology to decentralize geospatial data visualization via our hybrid API infrastructure which harnesses the interoperability of geospatial technology and blockchain to tokenize the earth. SpectrumNetwork is designed in accordance with the ERC20 ethereum algorithm, to harness the dApp functionalities whist consisting of spatial signatures and a proof-of-location algorithm. To bridge a recurring gap between geospatial data management and cost reduction.

**A link to the official contract address confirmation:** https://etherscan.io/address/0x259059f137cb9b8f60ae27bd199d97abb69e539b. Our contract address is publicly displayed on our website dashboard. 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://icobench.com/ico/spectrum-network
2. https://icoholder.com/en/spectrumnetwork-inc-23941
3. https://findico.io/ico/spectrum-network/
4. https://www.trackico.io/ico/spectrum-network/
5. https://icorating.com/ico/spectrumnetwork-spec/
6. https://mifengcha.com/ico/spectrum-network
7. https://icopulse.com/ico/spectrum-network
8. https://bitcointalk.org/index.php?topic=4637194.msg45530978#msg45530978
9. https://www.altcoinstalks.com/index.php?topic=36985.msg260710#msg260710**

**Comment by freeatnet** [comment]
Thank you for your request, @SpectrumNetwork!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1674.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1674.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by SpectrumNetwork** [comment]
Hello Freeatnet,

Thank you for your answer. This is an official acknowledgedment of your response. We thank you for the caution warning. We will heed.
Kindly we wish to state that we have followed the required format. If there are any other requirements needed of us, we will be glad to provide it.
Thank you
Fong Chan
SpectrumNetwork

**Comment by SpectrumNetwork** [comment]
Hi @freeatnet,
Hope you are well? Wish to enquire if there has been any update.
Thank you.

Andrew Collin
SpectrumNetwork

**Comment by SpectrumNetwork** [comment]
Hi @freeatnet, kindly we would like to make an update to our existing information. Our twitter account has therefore changed from https://twitter.com/SpectrumToken to https://twitter.com/SpectrumToken1. The former was suspended for unsolicited reasons. Thank you as you make this change.

Regards,
Fong Chan.

**Comment by SpectrumNetwork** [comment]
@freeatnet hi,

Any news yet on this? 

Thank you and best regards.

Andrew Collin
SpectrumNetwork
