### ISSUE TITLE
Add ICOStart Token (ICH)

### ISSUE THREAD

**Issue by ICOStart** [forkdelta/tokenbase#1678]
Token address:
0x330839EF82D34801bd96e75a4Ee778ac56Fa1ED8

Issuer's official website:
https://icostart.ch

Description: 
ICOStart is an ICO SaaS platform that will help startups and companies to develop their ICO projects.
ICOStart's company is Swiss Crowd SA, active in crowdfunding in Southern Switzerland since 2003.
ICOStart token will be used to pay for our services on the platform and outside the platform for consulting. 

A link to the official contract address confirmation:
https://icostart.ch/ 

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://bitcoinexchangeguide.com/icostart-ico-ich-token/
2. https://www.cryptominando.it/2018/05/16/icostart-ico-semplice-veloce/  <!-- complete review in italian language (Italy and Switzerland are the main target of our services)
google translator preview: https://translate.google.com/translate?sl=it&tl=en&js=y&prev=_t&hl=it&ie=UTF-8&u=https%3A%2F%2Fwww.cryptominando.it%2F2018%2F05%2F16%2Ficostart-ico-semplice-veloce%2F&edit-text=  --!>

**Comment by freeatnet** [comment]
Thank you for your request, @ICOStart!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1678.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1678.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
