### ISSUE TITLE
Add OxyToken (OXY)

### ISSUE THREAD

**Issue by oxytoken** [forkdelta/tokenbase#1679]
---
addr: '0x581c9BA7A3dE3944E051c585C273974EE4570502'
decimals: 8
links:
- Email: support@oxycoinnetwork.com
- Telegram: https://t.me/oxynetwork
- Twitter: https://twitter.com/oxy_coin
- Website: http://oxycoinnetwork.com
- Discord: https://discord.gg/R2336av
- Whitepaper: http://oxycoinnetwork.com/whitepaper/whitepaperoxy.pdf
Description: Customer convenience, efficiency and security in transactions
name: OxyToken
symbol: OXY

**Comment by freeatnet** [comment]
Please file using required format: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md. Thanks!

**Comment by oxytoken** [comment]
**Token address:
0x581c9ba7a3de3944e051c585c273974ee4570502**


**Issuer's official website:
http://oxycoinnetwork.com**


**Description:
Oxy Tokens are Crypto Currencies used in the Oxy network. The Oxy network includes exchanges, payment systems, and various online transactions. Guarantee comfort, efficiency and security in every transaction. It is very profitable to be saved as a digital asset in the future. Oxy Token development on various platforms continuously** 


**A link to the official contract address confirmation:
https://etherscan.io/address/0x581c9ba7a3de3944e051c585c273974ee4570502** 


**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icoholder.com/en/oxy-network-25570
2.https://bitcointalk.org/index.php?topic=5023770.msg45333807#msg45333807
