### ISSUE TITLE
Please List token : exsulcoin (XUL)

### ISSUE THREAD

**Issue by exsulcoinga** [forkdelta/tokenbase#168]
Hello,
We wish to be officially listed on https://forkdelta.github.io/.
Contract Adress : 0x382a71ecb288da8701428406a36ffa5d8f072d55
Token Name : exsulcoin
Symbol: XUL
Decimal: 0
Website: https://exsulcoin.ga/

Paragraph description of XUL: People who own ExsulCoin can use their tokens to help build refugee-led projects. In addition, refugees can use ExsulCoins to pay for tutoring, mentorship, or nanowork tasks.

XUL dev team
Website: https://exsulcoin.ga/
Whitepaper : https://exsulcoin.ga/exsul-coin-whitepaper-print.pdf

**Comment by Kryptoniq** [comment]
Provide link to a third party review or discussion about the token.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/190
