### ISSUE TITLE
Forza [FOZ]

### ISSUE THREAD

**Issue by Forza10** [forkdelta/tokenbase#1680]
**Token address:**

**Issuer's official website:**

**Description:** 

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://twitter.com/ForzaFoz
2. https://www.facebook.com/ForzaToken

**Comment by freeatnet** [comment]
Please file by filling out required information. Thanks!

See: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
