### ISSUE TITLE
List erc20 token Agent Not Needed ( ANN )

### ISSUE THREAD

**Issue by agentnotneeded** [forkdelta/tokenbase#1682]
Hi can you list our token, ANN token is the currency of the property platform Agent Not Needed. We have built a property platform that allows anyone to buy, sell or rent property without an estate agent.

ANN is used to pay fees, advertise or buy leads on the platform.

the contract address is https://etherscan.io/token/0xe0e73e8fc3a0fa161695be1d75e1bc3e558957c4

the token website is http://tokensale.agentnotneeded.com

Contract displayed at top of main page

discussions:
https://www.youtube.com/watch?v=LUm0lJ8LLcE
https://www.youtube.com/watch?v=uE5PoXrEhPo
http://www.propertyindustryeye.com/another-new-portal-thats-open-to-all-claims-to-have-the-agents-worried/
https://icobench.com/ico/agent-not-needed
https://icomarks.com/ico/agent-not-needed

Thanks

**Comment by freeatnet** [comment]
Hey there! Thanks for bringing this up. In fact, your token has been reviewed and approved: https://github.com/forkdelta/tokenbase/issues/1082. We'll let you know in the original thread a couple days before it goes live.
