### ISSUE TITLE
Add TzLibre pre-launch token (TZL)

### ISSUE THREAD

**Issue by tzlibre** [forkdelta/tokenbase#1685]
**Token address:**
0x6b91bc206eed0a8474f071339d1fd7ed7156f856

**Issuer's official website:**
https://tzlibre.github.io

**Description:** 
TzLibre is an implementation of the Tezos protocol, based on a fork of KYC-Tezos. Unlike KYC-Tezos, TzLibre is permissionless (no KYC), hard-capped (max 763,306,929.68 TZL), trustless (on-chain governance is constrained), and has no premine (no free tokens for the project founders).
TZL ERC20 is a pre-launch token: TZL ERC20 tokens will be converted into native TZL tokens when TzLibre launches its mainnet.

**A link to the official contract address confirmation:** 

The token contract address can be found [in our FAQ](https://tzlibre.github.io/faq.html#other), and in our [description page](https://tzlibre.github.io/project.html#what) under the "Pre-launch token" paragraph.

Additionally, clicking on the top-left corner of our homepage leads directly to the [ForkDelta TZL/ETH pair](https://forkdelta.app/#!/trade/0x6b91bc206eed0a8474f071339d1fd7ed7156f856-ETH). TZL __has already been traded for more than 3 months on ForkDelta__ without an official ticker.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

Swissinfo fintech blog (see May 28th post): https://www.swissinfo.ch/eng/liveblog/fintech-analysis
CoinDesk mention: https://www.coindesk.com/delays-damned-tezos-blockchain-enters-beta/
Reuters release: https://www.reuters.com/brandfeatures/venture-capital/article?id=38757

**Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.**

1. [Twitter](https://twitter.com/tzlibre)
2. [Telegram](https://www.telegram.me/tzlibre)
3. [Reddit](https://www.reddit.com/r/tzlibre/)

**Comment by freeatnet** [comment]
Thank you for your request, @tzlibre!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1685.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1685.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
