### ISSUE TITLE
Add Erachain Blockchain Platform token (ERCH)

### ISSUE THREAD

**Issue by icreator** [forkdelta/tokenbase#1688]
Hello, 

0x2300d50a447992e934816d3cd415157999202352

 www.erachain.org

The platform is based on verified users with KYC identification.
Token information: 
Symbol: ERCH
Decimals: 8
Total Supply: 10,000,000 ERCH
Protocol: ERC20 on Ethereum network

https://etherscan.io/address/0x2300d50a447992e934816d3cd415157999202352#code

https://techcrunch.com/2017/11/23/in-israel-a-blockchain-and-crypto-hyper-cluster-is-just-getting-started/

https://www.youtube.com/watch?v=X_Mm8k3SaTA  

Best regards, Dmitry Ermolaev.

**Comment by freeatnet** [comment]
Thank you for your request, @icreator!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1688.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1688.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
