### ISSUE TITLE
Add EVA TOKEN (EVA)

### ISSUE THREAD

**Issue by mcmich** [forkdelta/tokenbase#1689]
**Token address:** 

https://ethplorer.io/address/0x632a9dc767860d3ba86f2ac6575bac51402b9afa

**Issuer's official website:** 

https://www.evatoken.org

**Description:** 

Eva Token (EVA) is an ECR20 based token which focus on building a network of users in the agricultural industry –more specifically, aimed at introducing electronic (cryptocurrency) mode of payment in agricultural firms and industries globally.

**A link to the official contract address confirmation:**  
https://evatoken.org

https://ethplorer.io/address/0x632a9dc767860d3ba86f2ac6575bac51402b9afa

We shall be adding our direct link to the site if demanded but we have all details on the website and white paper. It is already added

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
 
 https://bitcointalk.org/index.php?topic=5016216

https://bitcointalk.org/index.php?topic=5016216.msg45707675
https://bitcointalk.org/index.php?topic=5016216.msg45254931

1. https://twitter.com/evatoken

2. https://t.me/evatoken1

3. https://t.me/evatokenann

**Comment by freeatnet** [comment]
Thank you for your request, @mcmich!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1689.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1689.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by mcmich** [comment]
Thank you. We shall update it now.
