### ISSUE TITLE
Please list JapaneseAVCoin 

### ISSUE THREAD

**Issue by JapaneseAVCoin** [forkdelta/tokenbase#169]
addr: 0x6B0611c65b53e72429D799eD512D0da123AC0Fb9
decimals: 8
description: JapaneseAVCoin is a decentralized digital currency for adult content intellectual property protection. And it will be the only token to be used on our adult content exchange platform for our second phase plan.

links: 
website: http://www.jav.cash
twitter: https://www.twitter.com/JapaneseAVCoin
reddit: https://www.reddit.com/user/JapapneseAVCoin
bitcointalk: https://bitcointalk.org/index.php?topic=2942484
telegram: https://t.me/javcoin      
medium: https://medium.com/@write2guoj/jav-token-a-fresh-perspective-for-adult-content-b39859f268bd

name: JapaneseAVCoin
symbol: JAV

**Comment by Kryptoniq** [comment]
Verified 0x6B0611c65b53e72429D799eD512D0da123AC0Fb9.

**Comment by Kryptoniq** [comment]
No third-party review or discussion of the token.

**Comment by JapaneseAVCoin** [comment]
A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2942484

**Comment by JapaneseAVCoin** [comment]
index.php?topic=2938786

**Comment by JapaneseAVCoin** [comment]
or https://bitcointalk.org/index.php?topic=2938786

**Comment by JapaneseAVCoin** [comment]
REDDIT: https://www.reddit.com/user/JapaneseAVCoin

**Comment by JapaneseAVCoin** [comment]
Telegram: https://t.me/javcoin

**Comment by JapaneseAVCoin** [comment]
https://bitcointalk.org/index.php?topic=2942484

**Comment by JapaneseAVCoin** [comment]
@Kryptoniq @freeatnet https://bitcointalk.org/index.php?topic=2942484

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x6b0611c65b53e72429d799ed512d0da123ac0fb9, http://www.jav.cash

**Comment by freeatnet** [comment]
@JapaneseAVCoin Thank you for your request! JapaneseAVCoin has been listed: https://forkdelta.github.io/#!/trade/JAV-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
