### ISSUE TITLE
Add Conventment (CNVT)

### ISSUE THREAD

**Issue by Conventment** [forkdelta/tokenbase#1691]
**Token address: 0x7d9564DaB2C58F163d0125892d25cF58D4494De5**

**Issuer's official website: https://conventment.com**

**Description:**  Conventment is an IoT-based security and logistics platform built for the legal cannabis industry. Built with scalability and productivity in mind, Conventment aims to create a connected platform for the future of the cannabis industry. Conventment utilizes technologies such as Python, Ethereum DLT, low-cost sensors (RFID/NFC) & customized IoT middleware (currently based on Zerynth) in order to achieve an error-free way of record-keeping and give businesses a streamlined platform to conduct their operations with zero downtime. 

**A link to the official contract address confirmation:** https://www.conventment.com/contact (bottom of page)

**2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://vprzrs.com/conventment-review-taking-advantage-of-the-legal-cannabis-industrys-growth/
2. https://denverweed.com/conventments-upcoming-b2b-iot-platform-potential-streamline-colorados-cannabis-industry/

**Comment by freeatnet** [comment]
Thank you for your request, @Conventment!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1691.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1691.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
