### ISSUE TITLE
Add ImmVRse Token (IMVR)

### ISSUE THREAD

**Issue by immvrse** [forkdelta/tokenbase#1692]
**Token address:**
0x7878424E994D8a2B8E329D31096922B7CeAbe660

**Issuer's official website:**
https://immvr.se (Primary)
https://immvrse.network (Secondary Domain)

**Description:** 
ImmVRse is decentralised app allowing VR content creators to showcase their talent to companies around the world, get hired and paid using ImmVRse tokens. Content creators using IMVR tokens will be at the center of the ecosystem. All transactions within the ecosystem will be validated and encrypted using Ethereum’s smart contract function, as a result of which it will run without the need of an arbitrary third party or a financial controller. ImmVRse has been listed DDEX on 21 September and will be listed on second DEX Token Store before 28 September.

**A link to the official contract address confirmation:** 
https://immvr.se
https://immvr.se/faq/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://icobench.com/ico/immvrse
https://hacked.com/ico-analysis-immvrse/
https://t.me/immvrse

**Comment by freeatnet** [comment]
Thank you for your request, @immvrse!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1692.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1692.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
