### ISSUE TITLE
Add OxyToken (OXY)

### ISSUE THREAD

**Issue by oxytoken** [forkdelta/tokenbase#1693]
**Token address:
0x581c9ba7a3de3944e051c585c273974ee4570502**

**Issuer's official website:http://oxycoinnetwork.com**

**Description:
Oxy Tokens are Crypto Currencies used in the Oxy network. The Oxy network includes exchanges, payment systems, and various online transactions** 

**A link to the official contract address confirmation:
https://etherscan.io/token/0x581c9ba7a3de3944e051c585c273974ee4570502** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.https://www.altcoinstalks.com/index.php?action=profile;area=showposts;u=38513
2.https://bitcointalk.org/index.php?topic=5023770.msg45333807#msg45333807

**Comment by freeatnet** [comment]
Thank you for your request, @oxytoken!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1693.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1693.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
