### ISSUE TITLE
Add Ve Gold G1 (VGLG1)

### ISSUE THREAD

**Issue by bapickett** [forkdelta/tokenbase#1695]
SYMBOL: VGLG1
Contract: 0x3a371d4fff12931ff784c18df7ea6741b0fa971f

Token address:
https://etherscan.io/token/0x3a371d4fff12931ff784c18df7ea6741b0fa971f

https://veritas.veritaseum.com/

VGLG1 is a sub-token of VERI (VERITASEUM) Ecosystem
VGLG1 is a digital token asset representing 1gram physical fine .999 gold that can be exchanged and then redeemed via the Veritaseum website, or VeADIR Dapp after KYC is provided.

Overview:
https://veritas.veritaseum.com/index.php/component/edocman/veassets-peer-to-peer-blockchain-based-physical-asset-ownership-in-bearer-form/viewdocument?Itemid=

Contact address:
brettpickett@gmail.com
masiah@veritaseum.com
eleanor.reid@veritaseum.com

Review:
https://youtu.be/Wj95AXS_6DU

Social Media Channel

https://twitter.com/ReggieMiddleton
https://t.me/joinchat/G_22OhA7UgN6b-7hTSFSTA
https://veritas.veritaseum.com/ve-blog

**Comment by freeatnet** [comment]
Thank you for your request, @bapickett!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1695.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1695.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by therealMikkoK** [comment]
@freeatnet can you run your robot on this too? I can do it manually as well. I know there is a coordinated buy spree coming to test the KYC process, and the speed of purchase in a heavy(ier) web traffic. Test is happening tomorrow. (fri)
