### ISSUE TITLE
Add SCAVO Token (SCAVO)

### ISSUE THREAD

**Issue by e-scavo** [forkdelta/tokenbase#1696]
**Token address:**
0xA62cE5F4175bA550440171ef809197eE21002D64

**Issuer's official website:**
https://scavo.farm

**Description:** 
Our company is based on the model of the SCAVO Token to finance the construction of sustainable large-scale crypto mining farms in Argentina.
The SCAVO Token entitles the owner to receive the profits/utilies obtaines from the mining operations and third party operations as well.

**A link to the official contract address confirmation:** 
https://scavo.farm
The information is on Token Metrics section. https://scavo.farm/#!#token

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by freeatnet** [comment]
Thank you for your request, @e-scavo!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1696.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1696.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by e-scavo** [comment]
> Thank you for your request, @e-scavo!
> 
> **For your safety, please note the following:**
> 
> * All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at #1696.
> * Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
> * **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
> * We will not ask you to move conversation to email or a messenger.
> * We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.
> 
> Next steps:
> 
> * Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
> * Keep an eye on this issue. We will post all follow-up and additional questions here, at #1696.
> * You will receive a notification once your request has been reviewed for completeness and accepted.
> * You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Hi.
Is there anything else that we have to do to get listed?.
Thanks in advance.
