### ISSUE TITLE
Add PureCarbon (PURC)

### ISSUE THREAD

**Issue by seanyspots** [forkdelta/tokenbase#1697]
**Token address:**

https://etherscan.io/token/0x97255bc2b5cf5280ae9bbd07f85d6d663e2030a8 

**Issuer’s official website:**
https://purecarbon.io

**Description:** 
    Pure Carbon Protocol tokens objective is to provide the incentives needed to drive are crypto-economic protocol which is implemented within an Ethereum smart contract. On top of our network Pure Carbon and other network participants can build and operate service such as the Carbon Rewards System which will Utilize blockchain technology to assist retailers that offer gift cards, loyalty programs, and reward customers by using digital assets.
This process will be less expensive and more secure by using blockchain’s unique verification protocols. This process will allow brands to utilize their “Brand Name Value’’ and transfer that into digital rewards for customers. It’s a win win situation for both parties one receives the benefits of a partnership and the other a secure rewards token for customers that will be tradable on different blockchain platforms.
**A link to the official contract address confirmation:** 

https://etherscan.io/token/0x97255bc2b5cf5280ae9bbd07f85d6d663e2030a8

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. http://www.joinfindi.org

2. https://twitter.com/HydrogenAPI/status/1038780671718830080 Hydro Community Partner

**Comment by freeatnet** [comment]
Thank you for your request, @seanyspots!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1697.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1697.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
