### ISSUE TITLE
Application 

### ISSUE THREAD

**Issue by adam993** [forkdelta/tokenbase#1698]

**Comment by freeatnet** [comment]
Previous edit as follows:
 
> Token address:
> 0xa101E27f06A97985B925E244111b61560Ecd97DB
> 
> Issuer's official website:
> https://www.bitto.tech/
> 
> Description: 
> Bitto Exchange LTD is a UK based company aimed to provide revolutionary features in a crypto-exchange. Live Exchange is planned to launch by the end of September 2018. Token will be used as a currency to lower the exchange's fees, as a PoS method, and a trading asset.
> 
> A link to the official contract address confirmation: 
> https://www.bitto.tech/other/sites/addbitto/index.html
> https://www.bitto.tech/other/sites/addbitto/forkdelta-confirmation.html

**Comment by adam993** [comment]
@freeatnet did you close this issue because of the content before edit or because it was blank after the edit? 
I accidentally removed everything.

**Comment by freeatnet** [comment]
@adam993 Yes, closed it because of empty contents. If you wish to continue with the request, please open a new issue.

**Comment by adam993** [comment]
@freeatnet  I've opened new issue here: 
https://github.com/forkdelta/tokenbase/issues/1809

Thanks again!
