### ISSUE TITLE
Rbit token Listing Request

### ISSUE THREAD

**Issue by rhovittoken** [forkdelta/tokenbase#170]
The contract address : 0x096F4002747bde03416Dc979E8a9bAb48CF8ED85

A link to the token issuer's official website : https://rhovit.club

Token Name : rhovit
Symbol: Rbit
Decimal: 18

A couple sentences for token description : 
Rbit are mined by Users completing "Value" transactions on the RHOVIT platform. A value transaction is anytime a Coin or Rbit is given or earned. For every set amount of value transactions, 1 Rbit is mined and then distributed on a weekly basis, with a max amount of Rbit able to be mined each week.

**Comment by Kryptoniq** [comment]
Provide link to a third-party review or discussion about the token.

**Comment by rhovittoken** [comment]
Provide link discussion : https://t.me/rhovitclub
thanks you very much

**Comment by rhovittoken** [comment]
WhitePaper : https://rhovit.club/wp-content/uploads/2017/10/Rhovit-Rbit_WhitePaper_100117_printRez.pdf

**Comment by Kryptoniq** [comment]
A third-party review or discussion such as bitcointalk or ICO rating websites.

**Comment by rhovittoken** [comment]
discussion : https://bitcointalk.org/index.php?topic=3012209

**Comment by Kryptoniq** [comment]
0x096f4002747bde03416dc979e8a9bab48cf8ed85, https://rhovit.club

**Comment by freeatnet** [comment]
* https://www.crunchbase.com/organization/rhovit and https://icomarks.com/ico/rhovit point to a different project by the same name
* rhovit.club is provided, while reputable sources list rhovit.com or rhovit.info as the project's website.
* There is are no sources confirming rhovit.club's association with rhovit project.
* Insufficient information to trust contract address provided by sources linked to rhovit.club.
