### ISSUE TITLE
Add EXOLOVER (EXO)

### ISSUE THREAD

**Issue by ExoLover2018** [forkdelta/tokenbase#1701]
**Token address:**https://etherscan.io/token/0xe58e751aba3b9406367b5f3cbc39c2fa9b519789#tokenInfo

**Issuer's official website:**www.exolover.io

**Description:** EXO is a utility token allows users to get the ExoLover Platform functionality. ExoLover Platform specially designed for getting people connected for sex activities and fun. EXO token uses for connections and when used it unlock the access to the content.

**A link to the official contract address confirmation:** https://github.com/exolover

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https:
1. https://howtotoken.com/career/for-the-sex-technology-business-blockchain-is-more/
2. https://bitcoinafrica.io/2018/07/04/australian-startup-exolover-launching-crowdsale-revolutionise-sex-tech-industry/
3. https://www.youtube.com/watch?v=qfM36Vltq3c&t=27s

**Comment by freeatnet** [comment]
Thank you for your request, @ExoLover2018!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1701.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1701.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
