### ISSUE TITLE
Add deex (deex)

### ISSUE THREAD

**Issue by kornoholio** [forkdelta/tokenbase#1702]
**Token address:**
0xc16CF13922C18DE7842374F9Baace4489f1D24AF

**Issuer's official website:**
www.deex.one

**Description:** 
DEEX is the native token of DEEX Exchange (Decentralized Exchange built on Bitshares). DEEX token is used to access trading on the platform.

**A link to the official contract address confirmation:**  an official confirmation of smart contract can be seen on our ICO web page (link: https://www.deex.com) under Presale+ ICO results field

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icobench.com/ico/deex/ratings
2. https://tokenguru.net/ico/deex-review/

**Comment by freeatnet** [comment]
Thank you for your request, @kornoholio!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1702.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1702.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
