### ISSUE TITLE
Add Bitether (BTR)

### ISSUE THREAD

**Issue by fahimaltinordu** [forkdelta/tokenbase#1703]
**Token address:**
https://bitether.org/
Token Information :
Name : Bitether
Symbol : BTR
Decimal : 18
Supply : 550,000,000
Per ETH : 200.000
Contract : 0x499a6b77bc25c26bcf8265e2102b1b3dd1617024
Trace : https://etherscan.io/token/0x499a6b77bc25c26bcf8265e2102b1b3dd1617024

**Issuer's official website:**
https://bitether.org/

**Description:** 

BITETHER (BTR); Your Digital Network; BITETHER (BTR) IS DIGITAL CASH YOU CAN SPEND ANYWHERE
Use Bitether to make payments online using our secure platform hosted by thousands of users around the world.BTR provides users with a low cost and rapid solution for digital payments. 

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x499a6b77bc25c26bcf8265e2102b1b3dd1617024

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

Facebook: https://www.facebook.com/socialbitether/
Twitter: https://twitter.com/Socialbitether
Telegram: https://web.telegram.org/#/im?p=@bitether
Medium: https://medium.com/@bitetherBTR
Instagram: https://www.instagram.com/socialbitether/

**Comment by freeatnet** [comment]
Thank you for your request, @fahimaltinordu!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1703.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1703.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by fahimaltinordu** [comment]
Thank you Dear @freeatnet 
We are anticipating your positive response.
