### ISSUE TITLE
Add BCR Token 

### ISSUE THREAD

**Issue by BCRDevMain** [forkdelta/tokenbase#171]
1. 0x633a8f8e557702039463f9f2eb20b7936fff8c05
2. http://bitcoinroyal.io
3. Quick about BCR: The Royal Platform-Cryptocurrency is an amazing technology, but it's difficult to use especially for first time investors. Our team is developing a platform that will take the pain out of using your currency. We are building a suite of trading tools, an easy to use wallet, and a lightnight fast currency all beautifully displayed within our user friendly interface.
4. https://etherscan.io/token/0x633a8f8e557702039463f9f2eb20b7936fff8c05
5. https://bitcointalk.org/index.php?topic=2579787.0

https://medium.com/@bitcoinroyal.info/bitcoin-royal-bcr-developed-one-of-the-next-leading-cryptocurrency-platforms-e842c602a29a

https://mobile.twitter.com/bitcoinroyal?lang=en

**Comment by BCRDevMain** [comment]
We rebranded to BitRoyal recently, would like to start our rebranding on a decentralized exchange to further our community

**Comment by Kryptoniq** [comment]
Verified 0x633a8f8e557702039463f9f2eb20b7936fff8c05.

**Comment by BCRDevMain** [comment]
Is anything else needed for our listing?

**Comment by Kryptoniq** [comment]
@BCRDevMain please be patient. Token listing is first in first out. It will get to your turn.

**Comment by BCRDevMain** [comment]
No problem just wanted to make sure we were all set. Thanks again.

**Comment by Kryptoniq** [comment]
Sure, you are set. Thank you.

**Comment by freeatnet** [comment]
@BCRDevMain Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/BCR-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate), either in Ether or in your token. Your donations keep the project running and are always appreciated.
