### ISSUE TITLE
Add Minds (MINDS)

### ISSUE THREAD

**Issue by MindsGaming** [forkdelta/tokenbase#1710]
[Minds-Token-Request.pdf](https://github.com/forkdelta/tokenbase/files/2398567/Minds-Token-Request.pdf)

Token address: 0xb26631c6dda06ad89b93c71400d25692de89c068

Issuer's official website: https://minds.com/token

Description: Minds Token is used for views on the social media site https://minds.com/ where
1 Minds Token = 1,000 views

A link to the official contract address confirmation: 
https://etherscan.io/token/0xb26631c6dda06ad89b93c71400d25692de89c068

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.) https://www.minds.com/MindsGaming/blog/supplying-a-demand-minds-token-stability-mindsgaming-891076675758399488

2.) https://riot.im/app/#/room/#mcosi.open-source.zone:matrix.org

3.) https://www.minds.com/blog/view/875109440196468736

  **Submission Request For “Minds Token”**

Token Name:

**Minds Token**

Contract address:

**0xb26631c6dda06ad89b93c71400d25692de89c068**

A link to the token issuer's official website. This MUST be in HTTPS.

[](https://minds.com/token)

1-3 sentences for the token's description:

**Minds Token is used for views on the social media site https://minds.com/ where
1 Minds Token = 1,000 views**

###A link to an official page confirming the above contract address. This needs to be on the
official domain of the token issuer. Etherscan does not count as a confirmation.

https://www.minds.com/wallet/tokens/101

**https://etherscan.io/token/0xb26631c6dda06ad89b93c71400d25692de89c068**

Links third-party review or discussion of at least two kinds. This can include, but is not limited
to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites,
established company partnerships, etc.

https://riot.im/app/#/room/#mcosi.open-source.zone:matrix.org

https://www.minds.com/blog/view/875109440196468736

Well-defined channels of communication with the token issuer must be published on the
website. This includes, but is not limited to: public social media, some form of instant messaging
(Telegram, Discord), email.

**You can reach the COO of Minds.com directly by messaging him on Minds.com @jack or email
jack@minds.com or contact info@minds.com for other ways to contact Minds INC**

###We are paying attention to the issue or pull request we have posted ;0

Optional questions:

Do you represent the token issuer or are you simply an interested member of the community?

**I am an active community member and long time supporter.**

###How was this token distributed? (ICO, Airdrop, etc.)

You gain tokens based off interactions of registered users. You
can buy them on directly from the network on https://minds.com/token

WhitePaper:

https://cdn-assets.minds.com/front/dist/assets/documents/Whitepaper-v0.3.pdf

Strong social media presence:

https://minds.com/ 

Current Site Traffic ranking for Minds.com

https://www.alexa.com/siteinfo/minds.com

Team member information on website

**Provided on White-paper**

Community Request written by @MindsGaming

* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.
-->
1. https://minds.com/minds
2. https://github.com/minds

**Comment by MindsGaming** [comment]
> :

I have upload a PDF with the format above in "required format" as well as updated the request to present this format first.

**Comment by CrackerHax** [comment]
Please add this token

**Comment by CrackerHax** [comment]
bump

**Comment by CrackerHax** [comment]
bump

**Comment by MindsGaming** [comment]
Was worth a shot
