### ISSUE TITLE
listing ELD on forkdelta exchange

### ISSUE THREAD

**Issue by electrumdark** [forkdelta/tokenbase#1712]
**Token address:** 0xaaf7d4cd097317d68174215395eb02c2cca81e31

**Issuer's official website:** 
https://electrumdark.com

**Description:** Electrum Dark is a working real-world cryptocurrency powering a fully-functional decentralized marketplace that allows you to buy and sell goods and services easily, securely, and anonymously,Say goodbye to the old way of doing ecommerce.
You can buy and sell anything with no fees using a completely free technology.

**A link to the official contract address confirmation:** https://electrumdark.com  

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
https://steemit.com/cryptocurrency/@tomosan/electrum-dark-nowa-kryptowaluta-i-zdecentralizowany-market-wymiany-dobor-dzialajacy-w-oparciu-o-tokeny
https://bitcointalk.org/index.php?topic=2491104.0
https://medium.com/@damostica63/electrumdark-token-the-future-of-decentralized-markets-2f526a0cce48
https://medium.com/@amroeneesa/electrumdark-adalah-platform-yang-dibuat-untuk-pembeli-dan-penjual-di-seluruh-dunia-d80200011743
https://www.youtube.com/watch?v=7RO-OE3NLJs
https://twitter.com/electrumdark
https://t.me/joinchat/G0Rs1Q9L3t2-6aEGYaOv2A

**Comment by freeatnet** [comment]
#336

**Comment by electrumdark** [comment]
can you explain what is the issue exactly ?

**Comment by freeatnet** [comment]
@electrumdark As mentioned in #336, you [published](https://web.archive.org/web/20180919141115/https://electrumdark.com/wp-content/uploads/2018/01/whitepaper.pdf) a whitepaper plagirized from Storiqua.

**Comment by electrumdark** [comment]
eld vision, and what we are trying to do in the future is way different from storiqa vision, in addition to this fact , we are working at the moment on whitepaper v2 , we already informed our community and investors about that, as a dev of eld project , I strongly believe that eld has a great potential in future , and we deserve a chance to get listed on your exchange , I will make sure to provide you our new wp and prove that we have no connection with storiqa by any means, please take that into consideration freeatnet

**Comment by freeatnet** [comment]
@electrumdark The important point there is that you published a stolen whitepaper.
