### ISSUE TITLE
Add ConferenceCoin (CC)

### ISSUE THREAD

**Issue by ConfCo** [forkdelta/tokenbase#1713]
**Token address:**
0x90cceb7275fc14c6b22c7c7b5aac689b34d9f43a

**Issuer's official website:**
http://confco.io/

**Description:** 

We will create an online platform, the CoinCo Platform, a place for global blockchain community, an instrument that will facilitate communication and knowledge sharing. ConferenceCoin will serve as a currency facilitating all the transactions happening on the Platform.

**A link to the official contract address confirmation:** 
http://confco.io/index.php/tokenaddress/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icoholder.com/en/conferencecoin-23541 - Samson Owiti's review is on the righ side
2. https://bitscreener.com/news/altcoin-that-makes-financing-and-management-easy-reliable-and-cheap
3. https://bitcoinexchangeguide.com/conferencecoin-ico/

**Comment by freeatnet** [comment]
Thank you for your request, @ConfCo!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1713.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1713.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by ConfCo** [comment]
Because it has been week since I posted application, I would like to gently ask about adding ConferenceCoin on ForkDelta. When can I count on getting review or feedback concerning he token?
