### ISSUE TITLE
Add BitDraw (BTDW)

### ISSUE THREAD

**Issue by BitDrawOfficial** [forkdelta/tokenbase#1714]
**Token address:**
0xec270e8f52b492dd0c2dcd43fc6f868e78f49f18

**Issuer's official website:**
http://bitdraw.online/

**Description:** 
BitDraw.online will be smart lottery platform created for the $103 billion lottery industry which will replace traditional lottery methods using disruptive technology while providing 100% anonymity for consumers
The lottery industry is one of the biggest in the world. Despite the impressive figures, banks and financial institutions have road-blocked businesses and individuals in the industry making payments expensive and insecure.

**A link to the official contract address confirmation:** 
0x1c0cf832441d6993e0eb0ac0780b8114bedf4285
Visit https://www.bitdraw.online and click buy now

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://foundico.com/ico/bitdraw.html
2.  https://icomarks.com/ico/bitdraw
3.  https://bitcointalk.org/index.php?topic=4958392

**Comment by freeatnet** [comment]
Thank you for your request, @BitDrawOfficial!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1714.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1714.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by BitDrawOfficial** [comment]
Any update on our request ?
