### ISSUE TITLE
Add BitonlineStore (BOST)

### ISSUE THREAD

**Issue by EquinoxToken** [forkdelta/tokenbase#1715]
**Token address:**
0x133043ce2cc38cdb32a13a245e82fba9e13b743a

**Issuer's official website:**
http://bitonlinestore.com

**Description:** 

Bitonline Store (BOST) is a global shop marketplace for buying and selling real world goods for cryptocurrency payment.

The Future Of Blokchain Technology Payment.

**A link to the official contract address confirmation:** 

0xc810750c4feca8a74a157090c1ba1e7b203ae609

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. Facebook : https://www.facebook.com/BitonlineStores/
2. Twitter : https://twitter.com/BitonlineS
3.  Tellegram Group : https://t.me/joinchat/HcYnBRHNG9oEzm43h4mVlQ
4. White Paper : http://bitonlinestore.com/wp-content/uploads/2018/09/BOST-WhitePaper-V1.pdf

**Comment by freeatnet** [comment]
Thank you for your request, @EquinoxToken!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1715.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1715.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by EquinoxToken** [comment]
ok tanks
