### ISSUE TITLE
ADD GoGold (GGX)

### ISSUE THREAD

**Issue by SovCoinXs** [forkdelta/tokenbase#1716]

**Comment by freeatnet** [comment]
FYI: User @SovCoinXs removed the request material, but originally posted the following:

> Token address:
> https://etherscan.io/token/0x62aaebd66b17fd494e6c1d5f7c59e395b99b0088
> 
> Issuer's official website:
> https://gogold.io
> 
> Description:
> 
> GoGold Store (GGX) is a global Gold Bullion shop marketplace for buying and selling real world Gold in exchange of cryptocurrency payment.
> 
> The Gold Blockchain Technology Payment.
> 
> A link to the official contract address confirmation:
> 
> 0x62aaebd66b17fd494e6c1d5f7c59e395b99b0088
> 
> At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
> 
> Facebook : https://www.facebook.com/gogoldio/
> Twitter : https://twitter.com/gogoldio
> Discord: https://discord.gg/9RhYPQe

This implies @SovCoinXs is
