### ISSUE TITLE
Add GoGold (GGX)

### ISSUE THREAD

**Issue by gogold1** [forkdelta/tokenbase#1717]
Token address: https://etherscan.io/token/0x62aaebd66b17fd494e6c1d5f7c59e395b99b0088

Issuer's official website: https://gogold.io

Description:

GoGold Store (GGX) is a global Gold Bullion shop marketplace for buying and selling real world Gold in exchange of cryptocurrency payment.

The Gold Blockchain Technology Payment.

A link to the official contract address confirmation:
0x62aaebd66b17fd494e6c1d5f7c59e395b99b0088

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
Facebook : https://www.facebook.com/gogoldio/ Twitter : https://twitter.com/gogoldio Discord: https://discord.gg/9RhYPQe

**Comment by freeatnet** [comment]
Note #1716.

**Comment by freeatnet** [comment]
Thank you for your request, @gogold1!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1717.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1717.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by gogold1** [comment]
Thank you for your update!
