### ISSUE TITLE
Add AltEstate token (ALT)

### ISSUE THREAD

**Issue by Xseeddd** [forkdelta/tokenbase#1719]
**Token address:**

0x419b8ed155180a8c9c64145e76dad49c0a4efb97

**Issuer's official website:**

https://alt.estate/

**Description:** 

Alt.Estate Group is a financial technology company offering a new solution for real estate tokenization: the Protocol (covers the technology, corporate structure and legal compliance aspects of tokenization) and the Platform (the marketplace for primary sales and secondary trading of tokenized assets, it allows users to trade real estate in fractions with higher liquidity and lower costs).

ALT token is the fuel of the Protocol and the Platform; all the fees (tokenization,
transaction, management, etc.) are paid exclusively with ALT tokens; ALT token is a means of payment within the Platform and a store of value; ALT tokens give voting rights on decisions through a special mechanism decentralizing Platform governance.

**A link to the official contract address confirmation:** 

https://alt.estate/upload/files/how-to-add-tokens.pdf

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icobench.com/ico/alt-estate
2. https://bitcoinist.com/alt-estate-allows-everyone-invest-real-estate/
3. https://www.newsbtc.com/2018/05/28/blockchain-real-estate-protocol-launches-in-japan-usa-and-eu/

**Comment by therealMikkoK** [comment]
@Xseeddd on the timeline you have a working product now, is it?
Also, I tried to find information about your corporate structure, and found nothing.
What is your corporate structure, and in which jurisdiction?
The token holders don't have a say on the projects, do they?
