### ISSUE TITLE
Revenge Coin Listing

### ISSUE THREAD

**Issue by snoroozi** [forkdelta/tokenbase#1720]
Request for revenge coin listing REVG

Contract 0x6363178ca9f101ec978a9a1ffc1301385ff2aa97
[Revenge Coin White Paper.pdf](https://github.com/forkdelta/tokenbase/files/2403721/Revenge.Coin.White.Paper.pdf)

**Comment by freeatnet** [comment]
Please file by filling out required information. Thanks!
https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
