### ISSUE TITLE
Add Dontoshi Token (DTD) of DonToshi.com Exchange

### ISSUE THREAD

**Issue by walerikus** [forkdelta/tokenbase#1722]
**Token address:**
0x7b9f3f8d3c8631246409e4993294d464ffa9ce2e

**Issuer's official website:**
https://www.dontoshi.com

**Description:** 
DTD is a token for Dontoshi.com exchange like BNB for Binance. 

**A link to the official contract address confirmation:** 
https://www.dontoshi.com/support/about-us/ information about token smart contract will be added soon, the website is being updated

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. Exchange launched this month, it is still not popular, we will search for the third-party sources to make a review upon a project. 
2. https://bitcointalk.org/index.php?topic=5034112.new#new

**Comment by walerikus** [comment]
Hello dear partners, 
Do you need any additional information regarding the project.

**Comment by walerikus** [comment]
DTD is a part of ibtc project which has a good activity recently in trading volume, it was two times in top 10 traded tokens in the last week

**Comment by walerikus** [comment]
DonToshi Exchange is a part of iBTC project, which launched in October 2017 and in December of 2018 iBTC foundation started developing the Dontoshi Exchange

iBTC is a Lending Platform where you can lend a deposit in USD and earn a ~10% of monthly interest in USD being converted onto BTC on withdrawal.

iBTC token max supply is 21.000.000 https://etherscan.io/token/0x0784dbabb6c6834bddfb7cfee116ba049e5dafab
Current price is ~0.01$

iBTC BitcoinTalk https://bitcointalk.org/index.php?topic=2251334.0
iBTC website http://ibtctoken.com/
iBTC telegram https://t.me/ibtctoken
iBTC twitter https://twitter.com/ibtctoken
iBTC is also a part of ecosystem where it will be used for payments.

You can track iBTC price on CoinMarketCap https://coinmarketcap.com/currencies/ibtc/ and CoinGecko https://www.coingecko.com/en/coins/ibtc, also it is supported by different apps like CoinStats, BitUniverse and BlockFolio

You can trade iBTC on supported exchanges
https://mercatox.com/exchange/IBTC/BTC
https://mercatox.com/exchange/IBTC/ETH
https://forkdelta.app/#!/trade/IBTC-ETH
https://www.dontoshi.com/exchange.php?buy=IBTC&from=BTC

iBTC foundation developed own Cryptocurrency Exchange Dontoshi.com that Launched in September 2018.

DonToshi Exchange has a native token DTD which will be used to reduce trading fees for holders, to get reward for holding DTD sharing Exchange Income, it will also be used for payments and trading. Both iBTC token and DTD are introduced on Dontoshi Exchange.

Dontoshi Exchange website https://www.dontoshi.com
Dontoshi Exchange telegram https://t.me/dontoshiexchange
Dontoshi Exchange telegram news https://t.me/dontoshi
Dontoshi Exchange twitter https://twitter.com/Dontoshiex

You can sign up now on Dontoshi.com Exchange to get a reward of 500 DTD and also get 50 DTD for referrals.

If you would like to represent a cryptocurrency project on Dontoshi Exchange, please feel free to apply for a listing here https://www.dontoshi.com/submit-coin

Dontoshi Exchange will be focusing to reach a wide range of cryptocurrency projects providing liquidity for crypto digital assets.

**Comment by therealMikkoK** [comment]
@walerikus the team is completely anonymous on the website. What corporate structure do you have, and in what jurisdiction?

**Comment by walerikus** [comment]
Here you can find smart contract address on the website about page https://www.dontoshi.com/support/about-us/

**Comment by walerikus** [comment]
We have not got a license yet, but want to get one in Malta. The team is anonymous at the time and once the project gets a license they will reveal themselves.

**Comment by therealMikkoK** [comment]
@walerikus Don't you think that would be more appropriate time to launch your token, when you have a licence to operate somewhere?

**Comment by walerikus** [comment]
2:44 PM, November 10, 2018, Mikko K <notifications@github.com>:@walerikus Don't you think that would be more appropriate time to launch your token, when you have a licence to operate somewhere?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

-- Sent from Yandex.Mail for mobile

**Comment by walerikus** [comment]
Yes, it would be good to obtain a license, but in the country where the main dev is from, there is no regulation with crypto, so he is looking for solutions with licence

**Comment by walerikus** [comment]
Hello, do you still consider the listing?

**Comment by freeatnet** [comment]
@walerikus I can't seem to find any recent activity around this token. You?
