### ISSUE TITLE
Listing Request

### ISSUE THREAD

**Issue by Refuge-Coin** [forkdelta/tokenbase#1723]
Please list our token "**RefugeCoin**" ticker "**RFG**".
 Contract address: 0x488678c730b9117f017d719624084894eb54700a
 Official website: [](https://refugecoin.com)/
 The migratory problem is a global phenomenon.Over $ 1 trillion dollars are invested in managing and 
 resolving it. Οur engagement has to do with the management. Panagiotis Diamantopoulos Co- Founder
[](  https://www.linkedin.com/in/panagiotis-diamantopoulos-50a32232/
) [](https://etherscan.io/token/0x488678c730b9117f017d719624084894eb54700a)
[]( https://bitcoiner.today/en/icos-social-refugecoin-change-the-world-now/
[]() https://foundico.com/ico/refugecoin.html
[]() https://icoholder.com/en/refugecoin-ico-18815
[]() https://foxico.io/project/refugecoin
[]() https://tokendrops.com/airdrop-detail/refugecoin/112
)
[](https://info.binance.com/en/currencies/refugecoin)

Thanks in advance
Panagiotis Diamantopoulos
Co-Founder

**Comment by freeatnet** [comment]
Please file by filling out required information. Thanks!
https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
