### ISSUE TITLE
NAS mainnet token swap

### ISSUE THREAD

**Issue by wudirruby** [forkdelta/tokenbase#1727]
To whom is may concern,

We are from nebulas team, we have noticed that Forkedelta has listed our ERC20 token NAS in the exchange. We are writing to inform that we are about to launch our mainnet token swap and will no longer support the ERC20 after the end of token swap. Further details will be disclosed in our official announcement (nebulas.io) . Please kindly switch the trading pair to our mainnet token or stop the trading of ERC20 token before the token swap ends. 

For any further enquiries, please reach to us at contact@nebulas.io
Best Regards
Nebulas team

**Comment by freeatnet** [comment]
Thanks @wudirruby.

@therealMikkoK could you please vet this?

**Comment by therealMikkoK** [comment]
@freeatnet 
*Timing follows plan.
* Main Net git page: https://github.com/nebulasio/go-nebulas/tree/master
This is a go
