### ISSUE TITLE
Add RefugeCoin (RFG)

### ISSUE THREAD

**Issue by Refuge-Coin** [forkdelta/tokenbase#1728]
Contract address:
0x488678c730b9117f017d719624084894eb54700a

Issuer's official website: https://refugecoin.com/

Description:
We believe in the blockchain technology. We also believe that with this technology we can provide the answer to this big problem. Keeping all this in mind we developed a special kind of cryptocurrency called "RefugeCoin" that would suit all the refugees' plans needs. 

Smart contract information: https://etherscan.io/token/0x488678c730b9117f017d719624084894eb54700a

https://bitcoiner.today/en/icos-social-refugecoin-change-the-world-now/

https://duxton.ru/crowdsale/refugecoin/

**Comment by freeatnet** [comment]
Thank you for your request, @Refuge-Coin!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1728.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1728.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by thboud** [comment]
Hi **ForkDelta Team**,

- Is there any update to the listing of our token regarding the review needed from your side?

I am sure you have tons of tokens to list but we'd like to get ours listed as soon as possible.
Is it possible to give us a time estimate from when the review will be done to when we will enter your exchange?

**Sincerely,
Theodore Boudros _(Co-Founder & CTO @ RefugeCoin)_**
