### ISSUE TITLE
Blockfreelancer tokens listing proposals 

### ISSUE THREAD

**Issue by Blockfreelancer** [forkdelta/tokenbase#1729]
Token name:Blockfreelancer
Symbols: BFC
Decimals :  18
Total supply : 100000000 BFC
contract address :  
0xdb2f7e432eb2266f35052cf3ce5924f76e8acf8e

Logo : BFC logo https://imgur.com/gallery/o2jjnfZ

**Comment by freeatnet** [comment]
Please file a request by filling out required information. Thanks!
https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
