### ISSUE TITLE
CHP Token Listing Request

### ISSUE THREAD

**Issue by PauliusMik** [forkdelta/tokenbase#173]
Name : Chips
Decimals : 18
Symbol : CHP
Total supply : 354 786 434
Contract address : 0xf3db7560e820834658b590c96234c333cd3d5e5e
Link to contract from official website: https://coinpoker.com/#faq

Token Description: CHP token was created to play poker online. Coinpoker is the first platform where it is already accepted. The long term vision of CHP token is to become a gambling token to be used for gambling purposes.

**Additional information:**

Website : https://coinpoker.com/
BitcoinTalk announcement : https://bitcointalk.org/index.php?topic=2078449
Twitter : https://twitter.com/CoinPoker_OFF
Telegram : https://t.me/officialcoinpoker
Medium : https://medium.com/@CoinPoker
Facebook : https://www.facebook.com/CoinPokerOfficial/
E-mail : info@coinpoker.com
Explorer : https://etherscan.io/token/0xf3db7560e820834658b590c96234c333cd3d5e5e
Third party reviews: https://icobench.com/ico/coinpoker

**Comment by JonathonDunford** [comment]
verified: 0xf3db7560e820834658b590c96234c333cd3d5e5e

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
