### ISSUE TITLE
Add Wixlar (WIX)

### ISSUE THREAD

**Issue by wixlar** [forkdelta/tokenbase#1731]
**Token address:**
https://etherscan.io/token/0x7ba19b7f7d106a9a1e0985397b94f38eee0b555e

**Issuer's official website:**
https://wixlar.com

**Description:** 
Wixlar, the only Digital Currency offering more than 12 Services to the public as well as its own TV Broadcasting Channel 24/7 on https://wixlar.com/wixlar-tv
Sponsors and participates in Major Events, more info available at https://wixlar.com/articles/

**A link to the official contract address confirmation:** 
Down in the page at https://wixlar.com/2017/08/15/intro-wixlar-coins/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://irishtechnews.ie/wixlar-group-ramp-up-exchange-listings-and-blockchain-projects-for-2018/
2. http://www.itdaily.kr/news/articleView.html?idxno=88062
3. https://www.boannews.com/media/view.asp?idx=67581
4. https://bctech.io/marketplace/2052/wixlar-crypto-freelancing-platform/
5. https://ccn.tokyo/2018/06/01/wixlar-group-and-partners-are-changing-the-cryptocurrency-market-through-a-new-whole-eco-system/
6. https://www.xblogs.info/2018/06/wixlar-group-ramp-up-exchange-listings-and-blockchain-projects-for-2018/

**Comment by wixlar** [comment]
Token Name: Wixlar
Tokeny Symbol: WIX
Decimals: 2
Contract Address: 0x7ba19b7f7d106a9a1e0985397b94f38eee0b555e

**Comment by freeatnet** [comment]
Thank you for your request, @wixlar!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1731.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1731.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by wixlar** [comment]
Thanks you and looking forward for your next reply

**Comment by wixlar** [comment]
Dear ForkDelta,
We are looking forward for your reply.
Thanks in advance,
Wixlar Group

**Comment by wixlar** [comment]
Hello ForkDelta :)

**Comment by wixlar** [comment]
Wixlar on CoinMarketCap: https://coinmarketcap.com/currencies/wixlar/

**Comment by wixlar** [comment]
ForkDelta, any news !
