### ISSUE TITLE
Kindly add TSU tsunami to the trading

### ISSUE THREAD

**Issue by tsunami106** [forkdelta/tokenbase#1732]
TSU

Tsunami 

10,000,000,000

18

https://etherscan.io/address/0x50A7Da1bd921ac68D0978C00c1D66637c968159c

Tsunami telegram group:
https://t.me/joinchat/HsbDpFIUCakERbcZEE28LA

http://www.tsunamicharityfoundation.com

**Comment by freeatnet** [comment]
Please follow the required template: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md
