### ISSUE TITLE
Add BLOCKFREELANCER (BFC)

### ISSUE THREAD

**Issue by Blockfreelancer** [forkdelta/tokenbase#1733]
**Token address:**
0xdb2f7e432eb2266f35052cf3ce5924f76e8acf8e

**Issuer's official website:**
https://blockfreelancer.com

**Description:** 
The No1. Decentralized marketplace for freelancers and recruiters 

**A link to the official contract address confirmation:** 
https://etherscan.io/address/0xdb2f7e432eb2266f35052cf3ce5924f76e8acf8e
( Also publicly displayed on our official website blockfreelancer.com )

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://cryptopotato.com/ico/blockfreelancer/   .

2.  https://ethereumworldnews.com/blockfreelancer-is-the-no1-decentralized-marketplace-for-freelancers-and-recruiters/

3.  https://www.coinschedule.com/ico/blockfreelancer#event4955

4.  https://www.icocalendar.today/ico-directory/blockfreelancer-ico

**Comment by freeatnet** [comment]
Thank you for your request, @Blockfreelancer!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at https://github.com/forkdelta/tokenbase/issues/1733.
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at https://github.com/forkdelta/tokenbase/issues/1733.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.
