### ISSUE TITLE
Add STELZ token (Stealth Project)

### ISSUE THREAD

**Issue by btcsmartads** [forkdelta/tokenbase#1734]
**Token address:**
0xdbfb606363be0032c69f373eaa2d84820edb167d

**Issuer's official website:**
http://stealthwallet.pro

**Description:** 
STEALTH PROJECT - a unique project with the new level of network anonymity.
It is a decentralized network ecosystem of a new generation based on the blockchain
paradigm and employing state-of-the-art technologies in cryptography and information
security. 
1.Multi-cryptocurrency STEALTH WALLET is developed with strong emphasis on
anonymity. It will offer a built-in mixer and users will be able to earn passive income while using it.
2.Self-sufficient anonymous and autonomous network infrastructure is built, similar to Tor.
3.Web content is created, available only from within the STEALTH PROJECT network.

**A link to the official contract address confirmation:** 
http://stealthwallet.pro

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://zen.yandex.ru/media/id/5b1968188cb59ab8873e82d8/stealth-project-ico-review-5b72b16622899a00a95e4385
2. https://steemit.com/dprince2281/@dprince2281/stealthcrypto-project-ico-review-2018?sort=new
3. https://www.youtube.com/watch?v=l7iLkZhma2k
4. https://coinmarketdaddy.com/currencies/reviews/token/stealth-project/stelz/review-detail/cryptocurrency-wallet-with-a-built-in-coin-mixer

**Comment by freeatnet** [comment]
Thank you for your request, @btcsmartads!

**For your safety, please note the following:**
- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at [https://github.com/forkdelta/tokenbase/issues/1734](https://github.com/forkdelta/tokenbase/issues/1734).
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens.  If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

Next steps:
- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at [https://github.com/forkdelta/tokenbase/issues/1734](https://github.com/forkdelta/tokenbase/issues/1734).
- You can expect to hear back from us within 8 weeks.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by btcsmartads** [comment]
**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://coinpredictor.io/icos/stealth-project
2. http://mainbloq.io/stealth-project/
3. https://www.youtube.com/watch?v=xHCiak8Rxp4
4. https://www.youtube.com/watch?v=FinOulc08Rc
5. https://www.youtube.com/watch?v=FLa-rwc80p8
6. https://www.youtube.com/watch?v=Y_-Cf8GekuY
7. https://www.youtube.com/watch?v=ASCUG3US9Fg
