### ISSUE TITLE
Add BitStash (STASH)

### ISSUE THREAD

**Issue by bitstashco** [forkdelta/tokenbase#1741]
**Token address:**
0xf19903d8e5b7d604b62d2a210b39ba9e1e1f93ef

**Issuer's official website:**
https://bitstash.co/

**Description:** 
BitStash is a Peer-to-Peer E-Commerce Marketplace where buyers can find products to purchase with STASH and vendors or sellers can sell their products for STASH. STASH Tokens are used to facilitate all transactions on the marketplace including vendor fees, advertising, and other related transactions.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0xf19903d8e5b7d604b62d2a210b39ba9e1e1f93ef

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://etherscan.io/token/0xf19903d8e5b7d604b62d2a210b39ba9e1e1f93ef#comments
2. CCN - https://www.youtube.com/watch?v=26WVCGIS8CA
3. https://bitcoinexchangeguide.com/bitstash-marketplace-ico-stash-token/

**Comment by bitstashco** [comment]
BitStash and the STASH token have been added to IDEX. Please include on ForkDelta for our team to apply for CoinMarketCap. 

https://idex.market/eth/stash

Regards, BitStash Marketplace.

**Comment by bitstashco** [comment]
Unacceptable.

**Comment by freeatnet** [comment]
@bitstashco lol settle down there. Your own link, https://bitcoinexchangeguide.com/bitstash-marketplace-ico-stash-token/, now points to a page that lists your project as a scam. I also can't find anything that you have actually created in the past two years.
