### ISSUE TITLE
List DES direcservi

### ISSUE THREAD

**Issue by Direcservi** [forkdelta/tokenbase#1743]
**What token should be updated?**
https://beta.forkdelta.app/#!/trade/0x6dda10298966aacf4c3b64b56d0d322feab5db1f-ETH, DES,https://etherscan.io/address/0x6dda10298966aacf4c3b64b56d0d322feab5db1f

**What about the token should be updated?**
DES: https://www.direcservi.info/
web company: https://www.direcservi.es/
Twitter: https://twitter.com/Direcservi 
Medium: https://medium.com/@direcservi
Linkedin: https://www.linkedin.com/in/direcservi
https://github.com/Direcservi
bitcointalk:https://bitcointalk.org/index.php?topic=5033212

**Comment by Direcservi** [comment]
Trank

**Comment by freeatnet** [comment]
Hi there! Looks like DES 0x6dda10298966aacf4c3b64b56d0d322feab5db1f is not a token currently know to ForkDelta. Please use the following template: [Request a new token to be added](https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md).

Pro-tip: put your data outside of `<!-- … -->`.
