### ISSUE TITLE
Direcservi

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1744]
**Token address:**https://etherscan.io/address/0x6dda10298966aacf4c3b64b56d0d322feab5db1f

**Issuer's official website:**https://www.direcservi.info/

**Description:**Company Hosting international 

**A link to the official contract address confirmation:https://etherscan.io/address/0x6dda10298966aacf4c3b64b56d0d322feab5db1f** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:https://bitcointalk.org/index.php?topic=5033212,https://twitter.com/Direcservi**

1. Sitio web DES direcservi: https://www.direcservi.info/
2. Sitio web Empresa: https://www.direcservi.es/
3. Twitter: https://twitter.com/Direcservi 
4. Medium: https://medium.com/@direcservi
5.Linkedin: https://www.linkedin.com/in/direcservi
6.https://bitcointalk.org/index.php?topic=5033212
7.https://beta.forkdelta.app/#!/trade/0x6dda10298966aacf4c3b64b56d0d322feab5db1f-ETH
8.https://github.com/Direcservi
9.https://etherscan.io/address/0x6dda10298966aacf4c3b64b56d0d322feab5db1f
10.Contrato 0x6DDa10298966aacf4c3B64B56D0d322feAb5DB1F

**Comment by Direcservi** [comment]
https://etherscan.io/address/0x6dda10298966aacf4c3b64b56d0d322feab5db1f
 Contract  0x6DDa10298966aacf4c3B64B56D0d322feAb5DB1F
