### ISSUE TITLE
List Kitchan Network (KCN)

### ISSUE THREAD

**Issue by kitchannetwork** [forkdelta/tokenbase#175]
Please listed new Token KCN : 

1 .  0x7816773556a09D06670A734CAf5FA22562427b0c
2.   https://kitchan.network/
3.   Kitchan Network is a profit sharing digital currency trading platform. Provides a variety of investment tools including spot transaction, margin trading and financing trading, as well as graphical programming tools and quantitative trading module. 
4 .  Link to contract from official website :  https://kitchan.network/
      https://etherscan.io/token/0x7816773556a09d06670a734caf5fa22562427b0c
5.   Bitcointalk :  https://bitcointalk.org/index.php?topic=2218979

Name : Kitchan Network 
Code : KCN 
Decimals: 18

Twitter : https://twitter.com/KitchanNetwork
E-mail  : kitchannetwork@gmail.com
GitHub : https://github.com/KitchanNetwork

Thanks You So Much !

**Comment by Kryptoniq** [comment]
Verified  0x7816773556a09D06670A734CAf5FA22562427b0c.

**Comment by freeatnet** [comment]
Technical:
* 0x7816773556a09D06670A734CAf5FA22562427b0c is not a valid ERC20 token at the moment: total supply = 0.

Background:
* Unable to verify any of the team members.
* BitcoinTalk user [points out](https://bitcointalk.org/index.php?topic=2218979.msg22510367#msg22510367) that a previous version of the website contained a team member photo lifted off the web.
* Team member profiles, namely for "Teddy DodHey, Co-Founder / CTO," "Paolo Grey, Legal department," and "Daniel Kauchild, Media and Mass communication" are lifted off other sources, such as https://alismedia.jp/ and https://sonm.com/team/
