### ISSUE TITLE
GYM Rewards Token Listing Request

### ISSUE THREAD

**Issue by GYMRewards** [forkdelta/tokenbase#1755]
My Request was closed for my lack of response, my apologies. I have submitted the requested information.
Can we just reopen it? or do I have to start the process again?

#869

**Token address:**

**Issuer's official website:**

**Description:** 

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by freeatnet** [comment]
Reopened #869.
