### ISSUE TITLE
eByte eSports Cryptocurrency (Listing request)

### ISSUE THREAD

**Issue by Timsn2017** [forkdelta/tokenbase#1761]
**Token address:**
0x0e2d93f7d50844a5203eb3dc9c5860f970ba5664

**Issuer's official website:**
https://www.ebyte.sale/en/

**Description:** 
In the eSports market, most of the available financial growth potential is unused. With eSports and Blockchain, eByte connects two of the most growing markets while including the mainstream of eSports. The eByte project is developing a consortium blockchain to establish the first international eSports ecosystem specifically designed for the whole eSports community. The new cryptocurrency will enable fans to support their favorite teams and players with donations. Like the Ethereum blockchain, developers will be able to use the eByte blockchain as a third party development platform focussed on good usability and optimized for gaming projects as well as eSports solutions.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x0e2d93f7d50844a5203eb3dc9c5860f970ba5664
The eByte token creation was about 20 days ago by our ICO advisor. We therefore have no links provided in Etherscan to our website etc.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.ebyte.sale/files/eByte-penta-sports-ann.pdf (Cooperation between eByte and one of the biggest german eSports clubs)
2. http://esports-marketing-blog.com/wiko-and-ebyte-announce-partnership/ (Cooperation between eByte and a french mobile phone supplier)
3. https://www.ewave-esports.de/ebyte-die-neue-waehrung-im-esport/ (Article from a german eSports partner of the project)
4. https://www.kaydee-world.com/kaydee-ceo-andreas-schaetzke-new-advisor-at-ebyte-3/

**Comment by Timsn2017** [comment]
Hello ForkDelta Team!

Im the co-founder of the project. I saw that there is already a token with the ticker EBYTE live on Forkdelta :) But thats a completely different different project and has nothing to do with the eByte eSports Cryptocurrency. Will that be a problem or can we name the forkdelta ticker with any name?

Thanks in advance,
Tim Lindlar

**Comment by freeatnet** [comment]
@Timsn2017 Sorry about the delay. You should select an alternative ticker (you can update your original request or post your choice in a new comment). Thanks for the thoughtful question!

**Comment by Timsn2017** [comment]
Hey :) Thanks for the response. The alternative ticker could be: "eByte Token".
Thank you very much!

**Comment by Timsn2017** [comment]
**Project Update:**
New Cooperation between GBBGamingTv.de & the eByte project!
https://twitter.com/eByteCommunity/status/1069234310333562882

**Comment by Timsn2017** [comment]
Project Update:
Another new Cooperation. eByte partnering with e-sports.rocks!
https://twitter.com/eByteCommunity/status/1069958716697522176

**Comment by Timsn2017** [comment]
**Project Update:**
Cooperation with W12.io!
https://twitter.com/eByteCommunity/status/1063402556167282688

**Comment by Timsn2017** [comment]
eByte now tradeable on Probitex!

**Comment by Timsn2017** [comment]
ICO on W12 has started!
