### ISSUE TITLE
HODLER.TECH token (HDL)

### ISSUE THREAD

**Issue by HODLERTECH** [forkdelta/tokenbase#177]
Hello.
For 7 days we will start our ICO with the new hardware wallet. Could you add our token on Forkdelta?
Information about the token:
1. The contract address: 0x95C4be8534d69C248C0623c4C9a7A2a001c17337  
2. Official token website: https://hodler.tech
3.The ultimate Hardware Wallet with the most advanced level of security, designed for easy payments with over 350 cryptocurrency.
4. https://hodler.tech/f/ICOdetails.html#tkndetails    and https://ethplorer.io/address/0x95c4be8534d69c248c0623c4c9a7a2a001c17337
5. We will start the bitcointalk thread for 30 Feb 2018.

Many thanks in advance and best regards.
Tobiasz Horodko CEO of the HODLER.TECH LTD company

**Comment by Kryptoniq** [comment]
1. I can't find a link to your your website confirming your contract.
2. You didn't include a link to a third-party review or discussion of the token, like an established ICO review blog. 

Make sure you fulfill all requirements before creating an issue.

**Comment by Kryptoniq** [comment]
1. I can't find an official link confirming the contract address.
2. You didn't include a link to a third-party review or discussion about the token.

**Comment by HODLERTECH** [comment]
Hello.
Link confirming the contract address:
https://hodler.tech/ICOdetails.html#tkndetails
https://etherscan.io/token/0x95c4be8534d69c248c0623c4c9a7a2a001c17337?a=0x066bd67279683a5c7f36ff384e6d8e9c0631efdf
Link to discussion on bitcointalk:
https://bitcointalk.org/index.php?topic=3070336.msg31633163#msg31633163



...............................................................................................................................................
Best regards - Tobiasz Horodko

HODLER.TECH OÜ
Street: Peterburi tee 53-101
Postal code: 11415
City: Tallinn
Country: Estonia (European Union)
REG NO: 14419613
Type of business entity: Limited Liability Company
Phone / Whatsapp / Telegram: +48513133144
Website: www.hodler.tech
Email:
CEO: contact@hodler.tech
Support: support@hodler.tech
Feedback: feedback@hodler.tech

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x95c4be8534d69c248c0623c4c9a7a2a001c17337, http://www.hodler.tech/

**Comment by HODLERTECH** [comment]
Thank you so much, we appreciate it.

...............................................................................................................................................
Best regards - Tobiasz Horodko

HODLER.TECH OÜ
Street: Peterburi tee 53-101
Postal code: 11415
City: Tallinn
Country: Estonia (European Union)
REG NO: 14419613
Type of business entity: Limited Liability Company
Phone / Whatsapp / Telegram: +48513133144
Website: www.hodler.tech
Email:
CEO: contact@hodler.tech
Support: support@hodler.tech
Feedback: feedback@hodler.tech

**Comment by JonathonDunford** [comment]
Thank you for your request! HODLER.TECH has been listed: https://forkdelta.github.io/#!/trade/HDL-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by HODLERTECH** [comment]
Thank you very much. Of course we will donate your project.

...............................................................................................................................................
Best regards - Tobiasz Horodko

HODLER.TECH OÜ
Street: Peterburi tee 53-101
Postal code: 11415
City: Tallinn
Country: Estonia (European Union)
REG NO: 14419613
Type of business entity: Limited Liability Company
Phone / Whatsapp / Telegram: +48513133144
Website: www.hodler.tech
Email:
CEO: contact@hodler.tech
Support: support@hodler.tech
Feedback: feedback@hodler.tech
