### ISSUE TITLE
European Crypto Bank: ECB TOKEN

### ISSUE THREAD

**Issue by European-crypto-bank** [forkdelta/tokenbase#178]
Hello Forkdelta Team,

We would like our Token listed on your exchange. You will find below all details.
If you need more information don't hesitate to email us at info@europeancryptobank.io

Regards
European Crypto Bank

The contract address:  0x69786859bc92e0ca82fcfe1bffc502b7bea6a069

A link to the token issuer's official website: https://www.europeancryptobank.io

A couple sentences for token description:
The ECB Token is a swap to 2 differents Token which will be choosen by each Token Holder at the end of the ICO
All ECB Tokens selected by the Token Holder at the end of the ICO will be tradable.
 
The Token S is for our Tax Services, Tax Support and Litigations
Token S  will give 5% of new Tokens S of the global amount to all Tokens holders each year.
Token S is anonymous, respecting the professional secrecy of lawyers in the world.

The Token I is only for Financial Services (Exchange and Trading Plaform, Wealth Management, Financial Analysis) and will be buy-backed by the Company every year. ECB will buy back some Tokens I with 6% of our annual turnover in buying them on the Market. They will be locked in our Reserve. Token I is not anonymous.

A link to an official page confirming the contract address: https://www.europeancryptobank.io
A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2824525

**Comment by Kryptoniq** [comment]
Verified 0x69786859bc92e0ca82fcfe1bffc502b7bea6a069.

**Comment by freeatnet** [comment]
@European-crypto-bank Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/ECB-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate), either in Ether or in your token. Your donations keep the project running and are always appreciated.

**Comment by European-crypto-bank** [comment]
Hello Arseniy,

Sorry but is it possible to stop the cotation of ECB token?

Regards
Mikael


<https://europeancryptobank.io>
*Mikael MISARD*
Head of Development

www.europeancryptobank.io
mm@europeancryptobank.io
____________________________

Fr : +33 183802305
It : +39 0287368363
Uk : +44 2080892334
Mob: + 33 613034513


2018-02-26 13:35 GMT+01:00 Arseniy Ivanov <notifications@github.com>:
