### ISSUE TITLE
Primebank Coin (PMC) listing request to forkdelta

### ISSUE THREAD

**Issue by primebankcoin** [forkdelta/tokenbase#1791]
**Token address:**    0xf069d9f8e394f23878e6beccbdef41c4a957b662

**Issuer's official website:** https://primebankcoin.com

**Description:** 

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://t.me/primebankcoin, https://t.me/primebankcoingroup
2.https://twitter.com/primebankcoin
admin@primebankcoin.com
abdullahalmarouf849@gmail.com

**Comment by primebankcoin** [comment]
Please  list this token,  Primebank Coin

**Comment by siyamix** [comment]
Good
