### ISSUE TITLE
Please list MissCoin

### ISSUE THREAD

**Issue by misscoinga** [forkdelta/tokenbase#180]
Contract address : 0x21E5E0a1433A7626605db64B69A47e6Eb8480ffB
Contract Name:	MissCoin
Symbol: MISS
Decimal: 18
Official website : https://misscoin.ga/
Logo : https://misscoin.ga/logo-light.png

Description : 
MissCoin's core is based on blockchain technology. The MISS aka Decentralized Account System featuring user autonomy built on the Ethereum, provides hassle-free user experience in information authorization across service providers - by only requiring user to provide the signature with his/her private key, rather than traditional experience to register and log in with password under each centralized service provider.

**Comment by Kryptoniq** [comment]
Include a link to a third-party review or discussion of the token, like an established ICO review blog.

**Comment by misscoinga** [comment]
link third-party review : https://bitcointalk.org/index.php?topic=3002507

**Comment by Kryptoniq** [comment]
0x21E5E0a1433A7626605db64B69A47e6Eb8480ffB, https://misscoin.ga/

**Comment by freeatnet** [comment]
* Copy of ugChain whitepaper (v. 2.5)
* I particularly enjoyed https://misscoin.ga/ugChain-idea.png
* Also enjoyed social media links pointing to ugChain Facebook and rhovit.club (see #170) Telegram channel.
