### ISSUE TITLE
SECURIX.IO (SRXIO)

### ISSUE THREAD

**Issue by andytebs** [forkdelta/tokenbase#1805]
**Token address:**
0xb444264c33eF3c8F9Ba46DF194826C22D54d0D12

**Issuer's official website:** https://securix.io

**Description:**
Securix's goal is to make Blockchain and cryptographic technology simple and accessible to a broader audience. A product that is simple and understandable. It is as simple as buying our SRXIO token and enjoying a passive monthly output share.

Securix is a blockchain company specializing in mining cryptocurrency. With their mining location in the Netherlands, they are capable of housing 24,000 mining units, the company can mine up to 24.5 Bitcoin per day.
 
Securix purchases green energy directly from solar and wind generators via the decentralized energy trading platform, EAN-2-EAN. This environmentally-conscious initiative allows the company to circumvent costly third party service providers while simultaneously developing a sustainable mining operation.

In an effort to enhance investor ROI, Securix offers a monthly 45% gross revenue share to holders of its SRXIO token. Investors who purchase the company's SRXIO token are investing in real, tangible assets. Furthermore, the company will reinvest or buy back tokens from the market, increasing both the token value and monthly output—thereby improving the likelihood of the SRXIO token trading higher than its initial price upon getting listed on exchanges.
 
Securix is also developing a proprietary wallet called the Mega Vault Wallet. In addition to storing investors'​ SRXIO tokens, it gives users the ability to achieve status, earn badges, and win prizes.
 
Securix's founders are seasoned professionals with years of experience as senior executives of Fintech Capital B.V.  The company has already started on its roadmap to what it anticipates will be a very successful business opportunity.

**A link to the official contract address confirmation:** https://etherscan.io/address/0xb444264c33ef3c8f9ba46df194826c22d54d0d12

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=4744419.240
2. https://medium.com/@securixio
3. https://www.linkedin.com/company/securix-io/

**Comment by SRXIO** [comment]
> **Token address:**
> 0xb444264c33eF3c8F9Ba46DF194826C22D54d0D12
> 
> **Issuer's official website:** https://securix.io
> 
> **Description:**
> Securix's goal is to make Blockchain and cryptographic technology simple and accessible to a broader audience. A product that is simple and understandable. It is as simple as buying our SRXIO token and enjoying a passive monthly output share.
> 
> Securix is a blockchain company specializing in mining cryptocurrency. With their mining location in the Netherlands, they are capable of housing 24,000 mining units, the company can mine up to 24.5 Bitcoin per day.
> 
> Securix purchases green energy directly from solar and wind generators via the decentralized energy trading platform, EAN-2-EAN. This environmentally-conscious initiative allows the company to circumvent costly third party service providers while simultaneously developing a sustainable mining operation.
> 
> In an effort to enhance investor ROI, Securix offers a monthly 45% gross revenue share to holders of its SRXIO token. Investors who purchase the company's SRXIO token are investing in real, tangible assets. Furthermore, the company will reinvest or buy back tokens from the market, increasing both the token value and monthly output—thereby improving the likelihood of the SRXIO token trading higher than its initial price upon getting listed on exchanges.
> 
> Securix is also developing a proprietary wallet called the Mega Vault Wallet. In addition to storing investors'​ SRXIO tokens, it gives users the ability to achieve status, earn badges, and win prizes.
> 
> Securix's founders are seasoned professionals with years of experience as senior executives of Fintech Capital B.V. The company has already started on its roadmap to what it anticipates will be a very successful business opportunity.
> 
> **A link to the official contract address confirmation:** https://etherscan.io/address/0xb444264c33ef3c8f9ba46df194826c22d54d0d12
> 
> **At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
> 
> 1. https://bitcointalk.org/index.php?topic=4744419.240
> 2. https://medium.com/@securixio
> 3. https://www.linkedin.com/company/securix-io/

This person has nothing to do with Securix.io, please ignore every request...

The Securix Team

**Comment by andytebs** [comment]
Issue is now closed.
