### ISSUE TITLE
Rubius (RUBY) -- Token Listing

### ISSUE THREAD

**Issue by Rubius-Inc** [forkdelta/tokenbase#1808]
**Token address:**
0x38F8F98738b2d64F3FFB0fDA7A60031f45A8C997

**Issuer's official website:**
https://rubius.io

**Description:** 
The Rubius (RUBY) cryptocurrency will power a suite of trustless financial tools produced by Rubius Inc., a US-based FinTech startup. The company plans to develop a payment application, an exchange, and many more consumer-friendly financial products.

**A link to the official contract address confirmation:** 
https://rubius.io/forkdelta.pdf

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icobench.com/ico/rubius
2. https://www.youtube.com/watch?v=XO9z_Oz8eBU

**Comment by ericscheier** [comment]
Hello, this project is no longer active and they are not distributing tokens or developing any platform per their ICO documents.

**Comment by ericscheier** [comment]
Untrue, and I can provide direct quotes from the director to this effect as needed. My name is being used without my permission as advertising on this project and the principles have defrauded investors of $1-2m.

**Comment by Rubius-Inc** [comment]
First of all, We stopped using your name when you were fired, Eric. Secondly, the Rubius coins or RUBYs are not an investment, they are utility tokens. None of the people who purchased the coins have made any complaints, and if they do, we are happy to refund any purchases.

**Comment by ericscheier** [comment]
I was never fired and am awaiting payment for my services. I will be filing
a complaint with the SEC next.
