### ISSUE TITLE
Bitto Exchange Utility Token

### ISSUE THREAD

**Issue by adam993** [forkdelta/tokenbase#1809]
---
name: Add a New Token
about: Request addition of a new token to tokenbase

---

**Token address:**
0xa101E27f06A97985B925E244111b61560Ecd97DB

**Issuer's official website:**
https://www.bitto.tech/
http://www.bittoexchange.com

**Description:** 
Bitto Exchange LTD is a UK based company aimed to provide revolutionary features in a crypto-exchange. Live Exchange is planned to launch by the end of September 2018. Token will be used as a currency to lower the exchange's fees, as a PoS method, and a trading asset.

**A link to the official contract address confirmation:** 
https://www.bitto.tech/other/sites/addbitto/index.html
https://www.bitto.tech/other/sites/addbitto/forkdelta-confirmation.html

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.coinspeaker.com/2018/01/26/next-big-thing-cryptocurrency-exchange-bitto-ico/ 
2. https://hugopress.com/bittoico-sales-continues-after-the-end-of-pre-sale-and-stage-1-phases/6230007
3. https://www.newsbtc.com/2018/01/30/signal-trading-puts-bitto-ahead-pack-crypto-exchange-space/
4. https://globalcoinreport.com/heres-bitto-next-big-thing-cryptocurrency-exchange-space/
5. https://nulltx.com/is-bitto-the-next-possible-kucoin-binance/
6. https://www.ccn.com/one-cryptocurrency-exchange-bitto-set-revolutionize-industry-launches-ico/
7. https://coinjournal.net/pr-release/bitto-exchange-launches-token-ico/
8. https://thebitcoinnews.com/bitto-exchange-revolutionize-cryptocurrency-trading/
9. https://www.youtube.com/watch?v=fnfBq0LlMQk
10. https://icowatchlist.com/blog/ico-focus-interview-nic-chin-bitto-exchange/
11. https://www.youtube.com/watch?v=-bRlFkC7hW0

**Comment by nicuk** [comment]
cant wait for BITTO to be up :)

**Comment by Sircheat1** [comment]
Can we add Bitto already, our community can't wait to trade...   Plssssss
