### ISSUE TITLE
Add TWNKL Token to Defaults

### ISSUE THREAD

**Issue by stephenhodgkiss** [forkdelta/tokenbase#181]
1. The contract address. 
0xfbd0d1c77b501796a35d86cf91d65d9778eee695 
2. A link to the token issuer's official website. 
https://www.rainbowcurrency.com/ 
3. A couple sentences for token description. 
Rainbow Currency Foundation is a Non-Profit Corporation, registered in Nevada, USA. It has been built to make global and local payment processes safer, cheaper, and easier.
4. A link to an official page confirming the contract address. 
https://www.rainbowcurrency.com/ 
5. A link to a third-party review or discussion of the token, like an established ICO review blog. 
https://bitcointalk.org/index.php?topic=2735483 

Facebook: https://www.facebook.com/RainbowCurrency/ 
Twitter: https://twitter.com/RainbowCurrency 
Reddit: https://www.reddit.com/r/RainbowCurrency/ 

ERC20 Smart Contract: https://etherscan.io/address/0xfbd0d1c77b501796a35d86cf91d65d9778eee695 
Token Symbol: TWNKL
Decimals: 3

**Comment by Kryptoniq** [comment]
Verified 0xfbd0d1c77b501796a35d86cf91d65d9778eee695.

**Comment by freeatnet** [comment]
@stephenhodgkiss Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/TWNKL-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by stephenhodgkiss** [comment]
@freeatnet - thank you for your assistance and including it so quickly.

**Comment by stephenhodgkiss** [comment]
@freeatnet Hi there, what is the procedure for delisting our token?

**Comment by stephenhodgkiss** [comment]
@freeatnet - I see this project for delisting: -

https://github.com/forkdelta/tokenbase/projects/5#card-8845572

Let me know your thoughts please. Thanks.
