### ISSUE TITLE
Listing for KWHCoin 

### ISSUE THREAD

**Issue by lphillips27** [forkdelta/tokenbase#1828]
**Token address:**
https://etherscan.io/address/0xebc7cd2684dd96619841c7994343c5a8bda94b10

**Issuer's official website:**
https://kwhcoin.com

**Description:** 
KWHCoin is a blockchain-based community, ecosystem and cryptocurrency backed by units of clean, renewable energy. Physical units of kWh energy are leveraged from multiple sources including smart meters, sensor readings and green button data. This measurable output is tokenized on the blockchain to create KWH tokens. Our main difference between competing energy tokens is our goal to improve the lives of the 1.2 billion people across the globe without reliable energy access. KWHCoin will achieve this by building a platform that allows anybody in the world to buy or sell renewable energy resources through The Grid—a blockchain-based renewable energy platform.

**A link to the official contract address confirmation:**  https://kwhcoin.com/#/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.facebook.com/KWHCoin/ 
2.https://t.me/KWHCoinCommunityChannel

**Comment by tamikamccall** [comment]
Hello,

Following up on request to list KWHCOIN. 
I have updated information and ask that you review for consideration for listing.  Please contact tleverette.mccall@kwhcoin.com if you have any further questions.  Thanks 

Token address:
0xebc7cd2684dd96619841c7994343c5a8bda94b10
Issuer's official website:
https://kwhcoin.com

Description: 
KWHCoin is a blockchain-based community, ecosystem and cryptocurrency backed by units of clean, renewable energy. Physical units of kWh energy are leveraged from multiple sources including smart meters, sensor readings and green button data. This measurable output is tokenized on the blockchain to create KWH tokens. Our main difference between competing energy tokens is our goal to improve the lives of the 1.2 billion people across the globe without reliable energy access. KWHCoin will achieve this by building a platform that allows anybody in the world to buy or sell renewable energy resources through The Grid—a blockchain-based renewable energy platform.

A link to the official contract address confirmation: https://etherscan.io/address/0xebc7cd2684dd96619841c7994343c5a8bda94b10 

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://youtu.be/qdt2G5Lzlmg
https://youtu.be/4b8prfS6sHY
[KWHCoin-White-Paper-Revised-(English).pdf](https://github.com/forkdelta/tokenbase/files/2962237/KWHCoin-White-Paper-Revised-.English.pdf)
