### ISSUE TITLE
Please list Dragonglass token (DGS)

### ISSUE THREAD

**Issue by quasiphilosophic** [forkdelta/tokenbase#184]
Contract address : 0x6aEDbF8dFF31437220dF351950Ba2a3362168d1b
Contract Name: Dragonglass
Symbol: DGS
Decimal: 8
Official website : https://dragonglass.com

Description:
Dragonglass is the world’s first gamified crypto-mining experience. Mining Dragonglass cryptocurrency is as easy and fun as playing a mobile game. It provides user-friendly and affordable cryptocurrency mining solution to everyone. Besides being simple and engaging, Dragonglass is also powerful: by using a unique mining technology, it is thousands of times more efficient than traditional cryptocurrency mining. Dragonglass is a mineable cryptocurrency and utility token. It is an ERC-20 standard digital token based on the Ethereum blockchain. The main features of Dragonglass are its ease of use, affordability and mining efficiency.

Third-party review:
https://www.techadvisor.co.uk/new-product/game/dragonglass-3671997/

**Comment by Kryptoniq** [comment]
Verified 0x6aEDbF8dFF31437220dF351950Ba2a3362168d1b.

**Comment by freeatnet** [comment]
@quasiphilosophic Thanks for your request! Dragonglass token has been listed: https://forkdelta.github.io/#!/trade/DGS-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
