### ISSUE TITLE
ADD VeSILVER Token (VSLZ1)

### ISSUE THREAD

**Issue by bapickett** [forkdelta/tokenbase#1840]
SYMBOL: VSLZ1
Contract: 0x8372f8b42689806eacd6ee55103efa9f339a6727

Token address:
https://etherscan.io/token/0x8372f8b42689806eacd6ee55103efa9f339a6727

https://veritas.veritaseum.com/

VSLZ1 is a sub-token of VERI (VERITASEUM) Ecosystem
VSLZ1 is a digital token asset representing 1toz .999 physical fine silver generic bar that can be exchanged and then redeemed via the Veritaseum website, or VeADIR Dapp after KYC is provided.

Overview:
https://veritas.veritaseum.com/index.php/component/edocman/veassets-peer-to-peer-blockchain-based-physical-asset-ownership-in-bearer-form/viewdocument?Itemid=

Contact address:
brettpickett@gmail.com
masiah@veritaseum.com
eleanor.reid@veritaseum.com

Review:
https://youtu.be/Wj95AXS_6DU

Social Media Channel

https://twitter.com/ReggieMiddleton
https://t.me/joinchat/G_22OhA7UgN6b-7hTSFSTA
https://veritas.veritaseum.com/ve-blog

**Comment by therealMikkoK** [comment]
Closed this issue, and opened it following the template. new issue number is #1841
