### ISSUE TITLE
ADD VeSILVER Token (VSLZ1)

### ISSUE THREAD

**Issue by therealMikkoK** [forkdelta/tokenbase#1841]
**0x8372f8b42689806eacd6ee55103efa9f339a6727**

**https://veritas.veritaseum.com/**

**VSLZ1 is a sub-token of VERI (VERITASEUM) Ecosystem
VSLZ1 is a digital token asset representing 1toz .999 physical fine silver generic bar that can be exchanged and then redeemed via the Veritaseum website, or VeADIR Dapp after KYC is provided. -->

**https://veritas.veritaseum.com/index.php/component/edocman/veassets-peer-to-peer-blockchain-based-physical-asset-ownership-in-bearer-form/viewdocument?Itemid= -->

**https://youtu.be/Wj95AXS_6DU**
<!--
As this is a subtoken of the Veritaseums VERI paltform, no such research is made on this particular token. It operates under the same principles as VERI token does.

**Comment by therealMikkoK** [comment]
There is another token issued, this time Palladium. I suggest these go in the same token file as the applications are well made, they're fast to look over. issue #1860

**Comment by aplha-coin** [comment]
Hello @therealMikkoK @freeatnet @indriks @v1nc3ntlaw @mishfit 
why you are ignoring me ?? 
https://github.com/forkdelta/tokenbase/issues/1839
