### ISSUE TITLE
Add Internet of Medical Things (IoMT)

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1843]
**Token address:**
0xe5F3C6d2B47CBE2cF936b9521466Bac2422EBEf8

**Issuer's official website:**
https://iomt.io/

**Description:** 
IoMT is a platform for Remote Health Monitoring/patient monitoring. The token IoMT (ERC20) works as  'digital fuel' of the platform, the utility token is to unlock certain features and hire hosted encrypted video/chat solutions. Our platform will support multiple wearables and medical devices.

**A link to the official contract address confirmation:** 
https://iomt.io/iomt-token/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. http://www.dailyfitnessbuzz.com/valuable-reasons-to-use-iomt-for-your-healthcare/ (Article about our project)
2. http://goodhealthdoctor.com/medical-devices-in-home-eases-living-standards/ (Article about our project)
3. https://www.forbes.com/sites/bernardmarr/2018/01/25/why-the-internet-of-medical-things-iomt-will-start-to-transform-healthcare-in-2018/#6a7a65274a3c (Market potential)
4. https://www.youtube.com/watch?v=NwTO2_s4TN8 (Market potential)

**Comment by IoMTPlatform** [comment]
We are initially working and releasing two products: IoMT Dashboard and Encrypted video / chat (30 min hosted solution). This will enable full remote monitoring capability, we will extend our catalog depending on the requests we get.

Connect your home medical devices such as fitness wearables, smart heart rate monitors, blood pressure cuffs, glucometers, asthma inhalers, thermometers, and pill bottles. We call this the "Internet of Medical Things" (IoMT) and distribute the information to a database, then you can share the information with your relatives and healthcare personnel. Make you in charge of your health report and connecting your devices to report to our database. Make it publicly available on our platform then anyone can remotely monitor your health and set up alerts on deviating patterns.

References:
http://iomt.io/
http://iomt.io/products/
http://iomt.io/lightpaper/
http://iomt.io/iomt-token/
http://iomt.io/#team
http://iomt.io/roadmap/
http://iomt.io/faq/
http://iomt.io/contact/
https://www.facebook.com/InternetofMedicalThings/

**Comment by IoMTPlatform** [comment]
@freeatnet @therealMikkoK @kryptoniq let me know if i need you need additional information in this inquire. Looking forward to your reply, will check in daily.
