### ISSUE TITLE
DATO Token listing

### ISSUE THREAD

**Issue by datoasia** [forkdelta/tokenbase#185]
Hello!

We would like to list our token.

short description: First targeted advertisement database on blockchain
Total supply: 18 333 333 DATO
name: DATO Token
ticker: DATO
contract: 0xc9f05e276d9148c7728f63205cc0180cb21a60ff
decimals: 18
url: dato.asia
contact email: admin@dato.asia
BitcoinTalk announcement :https://bitcointalk.org/index.php?topic=2839784.0
Twitter: https://twitter.com/DATO53474167
Telegram: https://t.me/joinchat/HsI8eErvWpJWUBYZ0DFV8g
github: https://github.com/datoasia

we are already listed at stocks.exchange.

Regards,
DATO Team

**Comment by Kryptoniq** [comment]
Verified 0xc9f05e276d9148c7728f63205cc0180cb21a60ff.

**Comment by datoasia** [comment]
thanks for verifying. When our token will be added?

**Comment by freeatnet** [comment]
@datoasia Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/DATO-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate), either in Ether or in your token. Your donations keep the project running and are always appreciated.
