### ISSUE TITLE
List new token DataTrading token (DTT)

### ISSUE THREAD

**Issue by data-trading** [forkdelta/tokenbase#186]
The contract address:  
0x049a5bf874f241d94232137ef728a9c7dd0d7550

A link to the token issuer's official website: 
https://data-trading.com

A couple sentences for token description: 
DataTrading is a platform based on artificial intelligence for analytics and forecasting of exchange markets with open development modules, accessible to each member of the community

A link to an official page confirming the contract address: 
https://token.data-trading.com

A link to a third-party review or discussion of the token, like an established ICO review blog:
https://bitcointalk.org/index.php?topic=2306909.msg23405463
https://medium.com/@juarezweiss/datatrading-alerta-ico-d6f10b73bb15

Transaction hash:
https://etherscan.io/tx/0x234bb8ee686c3c7661757c86775ea38865a6a984a39856cd257670501281f090

**Comment by Kryptoniq** [comment]
Verified 0x049a5bf874f241d94232137ef728a9c7dd0d7550.

**Comment by Kryptoniq** [comment]
According to ICOHolder.com, the team members are unverified and the overall project  rating is 2.57 (High risk) .

**Comment by freeatnet** [comment]
@Kryptoniq Link please?

**Comment by Kryptoniq** [comment]
@freeatnet https://icoholder.com/en/data-trading-16775

**Comment by freeatnet** [comment]
@Kryptoniq It looks like icoholder requires the team link their linkedin accounts on the website to remove the "unverified" badge. I think given that there's other coverage of the project on various resources[1][2][3] and if there are no other red flags, we can list this token.

[1]: https://bitsify.net/ico-list/data-trading-ai-advisors-novice-traders/
[2]: http://cryptoconsulting.info/2017/news/new-level-of-trade-forecating-with-datatrading/
[3]: https://cointelegraph.com/press-releases/datatrading-makes-trade-forecasting-by-artificial-intelligence-open-for-everyone

**Comment by Kryptoniq** [comment]
0x049a5bf874f241d94232137ef728a9c7dd0d7550, https://data-trading.com/

**Comment by freeatnet** [comment]
@data-trading Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/DTT-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
