### ISSUE TITLE
ADD Token KRC

### ISSUE THREAD

**Issue by lxxvs** [forkdelta/tokenbase#1865]
**Token address:**
0x40e230d349daf337d01b765765c3fa0cd0cb930a

**Issuer's official website:**
https://kurecoinhub.io

**Description:** 
Kurecoin is from Kure Holdings, a renowned parent company and parent company to 16 companies. Kurecoin blockchain will create the foundational house of other cryptocurrencies from Africa along with its unique exchange for trading

**A link to the official contract address confirmation:**  https://kurecoinhub.io

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://t.me/joinchat/HHhrukaomo9NuyLeqARBCg
2. https://bitcointalk.org/index.php?topic=3478671.0
3. https://twitter.com/KureCoinHub
4. https://www.reddit.com/user/kurecoinhub

**Comment by Semipyatnov** [comment]
upd please!

**Comment by Sunnairo** [comment]
Update

**Comment by Sunnairo** [comment]
This is over 8 weeks now. Very sad
