### ISSUE TITLE
kindly add trextoken TXT

### ISSUE THREAD

**Issue by trextoken** [forkdelta/tokenbase#1874]
**Token address:**0x4b44f450bc3bFB60DC1a0690cBA028e1193CaE4f

**Issuer's official website:**https://www.trextokens.com

trextoken is set to solve music chain

<!--http://www.tsunamicharityfoundation.com/

Note:https://bitcointalk.org/index.php?topic=5037135.new#new

**Comment by esiaminy** [comment]
Hi

**Comment by trextoken** [comment]
hello
