### ISSUE TITLE
Listing token on Forkdelta

### ISSUE THREAD

**Issue by YlifeToken** [forkdelta/tokenbase#1878]
Telegram chat @Taissadom

**Token address:**
0x97bC20fDa3E38C1874Db91283b4557bbCdeBAc46

**Issuer's official website:**
https://www.ylifetoken.com

**Description:** YLife was founded by a group of football fans and cryptocurrency. The team are committed to developing YLifeToken with football supporters, developers and companies that can together build a fair competition. Being a loyal fan of YLife will enable you to enter their weekly competitions and giveaways. Recently we came across a football ICO and it seems YLife are focusing on a different area of the game. YLifeToken provide transparency for payment whilst maintaining high standards and consucting business ethically in Football which is in compliance with laws, rules and regulations that apply to users.

**A link to the official contract address confirmation:** 
https://www.ylifetoken.com/#token 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://t.me/YLIFEOFFICIAL
2. https://twitter./YLIFEOFFICIAL
3. https://Facebook.com/YLIFEOFFICIAL
4. https://icoholder.com/en/ylifetoken-26057
5. https://tokensmarketplace.com/market/entertainment-tokens/game-e-sport-entertainment-tokens/ylifetoken/

**Comment by ozanaksoy123** [comment]
Telegram chat @Bitcoingold3000
Token address:
0x1d464ac5e046e5fe280c9588edf8eb681b07008f

Issuer's official website:
https://gmbplatform.io

Description: 
5 Features of GMB platform
1. Mikkschain (combine Software with Hardware that overcome the scalability limits of existing blockchains) 
2. POPS Consensus protocol (Proof of Power Specification & Stake) 
3. Dual-Cryptocurrency system with DEX
watch here 👇👇
http://bitly.kr/iY33
4. Objective Smart Contract (provide easy to use smart contract using Block languege) 
Watch here 👇👇
http://bitly.kr/h8jH
5. TravelSpace (dAPP)
Watch here 👇👇
http://bitly.kr/fPmW

A link to the official contract address confirmation: 

https://gmbplatform.io/#faq-section

How do I check my GMB Token Payment?

Details of the GMB Token payment can be found in the “GMB Wallet” on the Login page. You can register for your custom token in your Personal Wallet to confirm whether the GMB token was paid or not. You are able to check some Personal Wallets, such as imToken, without custom token registration.

The information needed to register your custom token is shown below. 
- Name (Token Name): GMB 
- Token Contract Address: 0x1d464ac5e046e5fe280c9588edf8eb681b07008f 
- Token Symbol: GMB 
- Decimals Places: 18

At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. Twitter
https://twitter.com/GMBplatform
2. Youtube 
https://www.youtube.com/channel/UCR0B2sEqaPDRozeZtOdPvUg
3. Medium 
https://medium.com/@GMBplatform
4. Naver Blog 
https://blog.naver.com/gmbplatform
5.Github
https://github.com/GMBPlatform
6. Website
www.gmbplatform.io
7.Coingecko
https://www.coingecko.com/en/ico/gmb
8.İcoholder
https://icoholder.com/en/gmb-26280

Please Unlock the Forkdelta GMB Token ... Thanks Forkdelta Team ...
