### ISSUE TITLE
Bullishruncrpto listing issue

### ISSUE THREAD

**Issue by BullishRunCrypto** [forkdelta/tokenbase#188]
Contract Address: 0x6ECCcf7EbC3497a9334F4fE957A7D5FA933C5bCc

Website: https://bullishruncrypto.co

Token Description: BullishRunCrypto is an Ethereum-based token and it is more than about cryptocurrency. It's the currency that guarantees price stability by direct control of the supply using smart contracts.BullishRunCrypto is committed to develop fully qualified and professional global blockchain community by cooperating with the other blockchain communities, third party services, developers and companies.

Etherscan Verification: https://etherscan.io/token/0x6ecccf7ebc3497a9334f4fe957a7d5fa933c5bcc?a=0xb5096dd3df123901a1c8d6d956b8b5cb0eb86fe4

Token discussion thread:
https://bitcointalk.org/index.php?topic=2483955.new#new

**Comment by Kryptoniq** [comment]
Verified 0x6ECCcf7EbC3497a9334F4fE957A7D5FA933C5bCc.

**Comment by BullishRunCrypto** [comment]
Please list us as soon as possible. We have a strong community eager to see BULLISH listed on Forkdelta decentalised exchange. Thank you.

**Comment by freeatnet** [comment]
@BullishRunCrypto Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/BULLISH-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
