### ISSUE TITLE
Pablo Token

### ISSUE THREAD

**Issue by xbountychuck** [forkdelta/tokenbase#189]
Please we would like to list this token on the exchange.

PABLO COIN:  
It’s a cryptocurrency that was made for people like me and you! A coin that represents the California lifestyle, where people boss up in the sunshine, cruise in drop tops and party like a rock star. Pablo in itself is a LIFESTYLE, a cryptocurrency for the hustlers!

www.lordchain.org

Coin: PABLO COIN

Symbol: BLO

Contract Address: https://etherscan.io/address/0x959529102cfde07b1196bd27adedc196d75f84f6

Social Media:
   www.Twitter.com/lordchain           Twitter Handle:  @Lordchain
   
  TELEGRAM (5k plus members) :         t.me/lordchain

Youtube:    https://youtu.be/wiJhSHOmiSk

**LINK TO OFFICIAL PAGE OF VERIFY ADDRESS. 
www.lordchain.org   ** must register to see the address
https://t.me/lordchain/19292

www.lordchain.org

News & Media with partnerships in apparel and the proliferation of MMJ Industry:

http://yourcannalife.com/pablo-coin-blo-is-coming/
https://3nbdesign.com/blogs/news/lordchain-dropped
https://3nbdesign.com/blogs/news/big-news
http://markets.financialcontent.com/stocks/news/read/35700755

**Comment by Kryptoniq** [comment]
AFAIK ethereum smart contract address can not be DDOSED.
There is no official link verifying the smart contract address.

**Comment by xbountychuck** [comment]
@Kryptoniq If you register on lordchain.org it will show the address on the site.

**Comment by xbountychuck** [comment]
https://bitcointalk.org/index.php?topic=2947521.new#new

**Comment by Kryptoniq** [comment]
Verified 0x959529102cFdE07B1196bd27ADEdc196d75F84F6.

**Comment by freeatnet** [comment]
@xbountychuck Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/BLO-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
