### ISSUE TITLE
Listing Fivebalance Token

### ISSUE THREAD

**Issue by fivebalanceID** [forkdelta/tokenbase#1895]
—The contract address. : 
🔸 https://etherscan.io/address/0x568F9F32969E29B5cE1a4545bE5398e8Cc7C4401

— A link to the token issuer's official website. : 
🔸 https://fivebalance.com

— the token's description. : 
🔸 Five Balance Token is the world’s first digital asset for human resource development. Cryptocurrency is designed to give rewards for every individual who are struggling to fix their problems or trying to improve the quality of their 5F (Fit, Financial, Family, Flair, and Faith).

— A link to an official page confirming the above contract address. This needs to be on the official domain of the token issuer. Etherscan does not count as a confirmation. : 
🔸 https://fivebalance.com

— Links third-party review or discussion of at least two kinds. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc. :
🔸 Medium : https://medium.com/@fivebalance
🔸 Bitcointalk : https://bitcointalk.org/index.php?topic=5033585
🔸 ICO Holder : https://icoholder.com/en/fivebalance-26011
🔸 ICOGeecker : https://www.icogeeker.com/ico/five-balance/

— Well-defined channels of communication with the token issuer must be published on the website. This includes, but is not limited to: public social media, some form of instant messaging (Telegram, Discord), email.
🔸 YouTube Channel : https://www.youtube.com/channel/UCWjlUPRBIqhY-iZ8I_EngxA
🔸 Twitter : https://twitter.com/fivebalanceID
🔸 Telegram Global Group : https://t.me/fivebalance
🔸 Email : community@fivebalance.com

**Comment by Willy-Sonderegger** [comment]
To many mails
