### ISSUE TITLE
Please List These World of Ether Tokens

### ISSUE THREAD

**Issue by tyranitarny** [forkdelta/tokenbase#1904]
**Token address:**
Token 1: 
Name: WOE_SUN 
Address: 0x3b16fce6a0f30081a30cecb362d46a7ecd7cd59e 

Token 2:
 Name: WOE_OCEAN
 Address: 0x3febc242b27e0c06be6efd23ae384f3c1391f6e5 

Token 3: 
Name: WOE_LIFE 
Address: 0x9b9106e47de69bbc5ebd1c4fa0e362b061853627

Token 4:
 Name: WOE_DEATH 
Address: 0xec5aafb3e14425fe48aa34e74a0336dc8274c105

Token 5: 
Name: WOE_ASTRAL
 Address: 0xe4d983d37061e0bbbafae1f2d429633ad9da22be

**Issuer's official website:**
https://worldofether.com/

**Description:** 

World of Ether description:
A decentralized collectible dueling game on the Ethereum blockchain.

Collect monsters. Breed them to make more. Sell and sire them for ETH. Battle them for experience. Level your player up to breed rarer and more powerful monsters. Use ERC20 in-game power ups to fuel monsters.

Token 1:
Name: WOE_SUN
Description: Redeem for one breed.

Token 2:
Name: WOE_OCEAN
Description: Change the gender of an Etherian. Can be used more than once.

Token 3:
Name: WOE_LIFE
Description: Reduce the age of an Etherian by one while also allowing it to breed immediately.

Token 4:
Name: WOE_DEATH
Description: Sacrifice 3 Etherians to get an egg, with the Etherian inside the egg not being decided upon until the player is ready.

Token 5:
Name: WOE_ASTRAL
Description: Increase the rarity of a breed by one. Limited.

**A link to the official contract address confirmation:** 

The website for these is https://worldofether.com/crystals, however the sale is closed and buy buttons greyed out. The only way to get these ERC20 crystals now is in-game. All the addresses are on our stateofthedapps page https://www.stateofthedapps.com/dapps/world-of-ether , but since this is a 3rd party site, you can also email me directly for confirmation: edward at worldofether dot com

Token 1: 
Name: WOE_SUN 
Address: https://etherscan.io/token/0x3b16fce6a0f30081a30cecb362d46a7ecd7cd59e 

Token 2:
 Name: WOE_OCEAN
 Address: https://etherscan.io/token/0x3febc242b27e0c06be6efd23ae384f3c1391f6e5 

Token 3: 
Name: WOE_LIFE 
Address: https://etherscan.io/token/0x9b9106e47de69bbc5ebd1c4fa0e362b061853627

Token 4:
 Name: WOE_DEATH 
Address: https://etherscan.io/token/0xec5aafb3e14425fe48aa34e74a0336dc8274c105

Token 5: 
Name: WOE_ASTRAL
 Address: https://etherscan.io/token/0xe4d983d37061e0bbbafae1f2d429633ad9da22be

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://cryptocurrencynews.com/world-of-ether-coming-soon/
2. https://www.youtube.com/watch?v=AV3vpdgZDZg
3. https://cryptoclarified.com/2018/03/12/world-of-ether-the-road-to-launch/
4. https://news4c.com/world-of-ether-reveals-first-gameplay-spoiler-its-beautiful/

**Comment by kluebirby** [comment]
Any way to help get these tokens listed? I also came here to request them being listed and see there's already an open ticket
