### ISSUE TITLE
Request to add eGO tokens to forkdelta

### ISSUE THREAD

**Issue by sunsetblues** [forkdelta/tokenbase#192]
contract address: 0x18cabd1e7db6c52406719cb72859ea2c2eea75d6
official website link: http://www.goguides.org/ego.html
token description: GoGuides eGO ERC20 collectable tokens and rewards program. 
link to contract address: https://etherscan.io/address/0x18cabd1e7db6c52406719cb72859ea2c2eea75d6
third-party review or discussion: no ico https://bitcointalk.org/index.php?topic=2607207.msg26532656#msg26532656 and media for eGO https://twitter.com/Robert_M_Barger/media
addr: '0x18cabd1e7db6c52406719cb72859ea2c2eea75d6'
decimals: 18 
name: GoGuides
symbol: eGO
I'm not anonymous PM me on twitter with any questions: https://twitter.com/Robert_M_Barger

**Comment by Kryptoniq** [comment]
I'd advise you add SSL to your site.

**Comment by Kryptoniq** [comment]
0x18cabd1e7db6c52406719cb72859ea2c2eea75d6, http://www.goguides.org/

**Comment by Kryptoniq** [comment]
1. No roadmap
2. Token has no long term goal or project.
Sorry, your token can't be listed.

**Comment by freeatnet** [comment]
@sunsetblues Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/eGO-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
