### ISSUE TITLE
ATRL Token listing 

### ISSUE THREAD

**Issue by stvenbaby** [forkdelta/tokenbase#194]
Hello!

We would like to list our token.

Short description: Atrl is an end-to-end technology solution that captures and provides previously inaccessible data to retailers and other "brick-and-mortar" businesses through its proprietary blockchain and real-time sensor technology.
Total supply: 80 000 000 ATRL
name: ATRL Token
Symbol: ATRL
Contract address: 0x7f5b40c7681e6780b415e4ec3155deea9f0fb329
Decimals: 18
Website: https://www.atrltoken.com/
Contact email: zhongwei2080@gmail.com
BitcoinTalk announcement :https://bitcointalk.org/index.php?topic=3020684
Twitter: https://twitter.com/Atrl_token
Telegram: https://t.me/Atrl_Token
Etherscan Verification: https://etherscan.io/address/0x7f5b40c7681e6780b415e4ec3155deea9f0fb329#code

Regards,
Atrl Team

**Comment by Kryptoniq** [comment]
Please provide an official link that verifies your contract address. E.G on your website or whitepaper.

**Comment by stvenbaby** [comment]
Confirmation of contract address:
https://www.atrltoken.com/token-sale.html  (white paper is on the way)

**Comment by stvenbaby** [comment]
@Kryptoniq 

Confirmation of contract address:
https://www.atrltoken.com/token-sale.html (white paper is on the way)

**Comment by Kryptoniq** [comment]
0x7f5b40c7681e6780b415e4ec3155deea9f0fb329, https://www.atrltoken.com/

**Comment by freeatnet** [comment]
Cannot find any 3rd-party review of the token.

**Comment by stvenbaby** [comment]
@Kryptoniq @freeatnet 
3rd-party review of the token:
https://bitcointalk.org/index.php?topic=3020684

**Comment by freeatnet** [comment]
@stvenbaby Your website states the project has been featured in a number of high-profile media outlets.

![image](https://user-images.githubusercontent.com/138289/36657965-acc4477c-1adf-11e8-8917-59117e546cad.png)

A couple of those would do, can you provide the links?

**Comment by freeatnet** [comment]
@stvenbaby Actually, I just realized the website is a copy of nucleus.vision, including your roadmap, vision, etc. We will not be listing your token.
