### ISSUE TITLE
Listing Sexy Token (SEXY) on ForkDelta

### ISSUE THREAD

**Issue by SexyToken** [forkdelta/tokenbase#195]
Hi, we would like to list our token on ForkDelta. Our details are below. 

Name: Sexy Token
Symbol: SEXY
Decimals: 18

1) Contract Address: 0x98f5e9b7f0e33956c0443e81bf7deb8b5b1ed545

2) Official Website: https://sexytoken.co

3) Token Description: SEXY is a fun ERC20 token designed to give users a unique way of expressing themselves via tipping on the blockchain. Our token is aimed at the many adult industries
that operate online. Users can tip online workers and let anyone around the world know how sexy they are. 

4) Official page confirming the contract address: https://etherscan.io/token/0x98f5e9b7f0e33956c0443e81bf7deb8b5b1ed545
https://sexytoken.co

5) A link to a third-party discussion of the token: https://bitcointalk.org/index.php?topic=2602612.0

We appreciate your time and look forward to being listed on the ForkDelta platform.

Thank you

**Comment by Kryptoniq** [comment]
0x98f5e9b7f0e33956c0443e81bf7deb8b5b1ed545, https://sexytoken.co

**Comment by SexyToken** [comment]
Hi Kryptoniq, Thanks for verifying our information. How do we proceed with listing? Cheers

**Comment by freeatnet** [comment]
@SexyToken Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/SEXY-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
