### ISSUE TITLE
Re: Removal of Legal Token (LGL) by smartone.legal  tag #1924

### ISSUE THREAD

**Issue by u15776** [forkdelta/tokenbase#1954]
**What token should be updated?**

LGL

**What about the token should be updated?**

Dear Forkdelta Team,

We realized that you stopped the trading of our LGL token. We have been working hard over the last months to create the Swiss LEGAL Standard for ICOs for which the LEGAL token will be used and we have just signed the contract with Horizon Globex, which you find below (https://www.horizon-globex.com/investors/ohg-history/). Also a second webpage for the LEGAL standard and a new telegram chat will be started in the next days (the old telegram chat is full of spam). The old ICO webpage is www.smartone.legal

[LEGAL Standard Contract.pdf](https://github.com/forkdelta/tokenbase/files/2545734/LEGAL.Standard.Contract.pdf)

A preview of the LEGAL Standard can be found here: 
https://github.com/HorizonGlobex/smartone/blob/master/SmartOneStandard5000Preview.pdf

Please keep the LGL listed. You will see much more trading of it in short time. The members of the LEGAL Standard will have to accept 10% of revenues for their services in LGL.

Thank you

Reto Stiffler

reto@smartone.legal
+41796164340

Zurich, Switzerland

**Comment by freeatnet** [comment]
@u15776 Thank you for reaching out. I see some roadmap items that are now in the past, such "KYC Automation" and "Open source crowdfunding platform". Has smartone.legal published updates on those items?

**Comment by freeatnet** [comment]
(This issue is related to #1924)

**Comment by u15776** [comment]
Dear Arseniy,

Please find enclosed the description of the KYC app and the crowdfunding platform. The SmartOne foundation cannot operate by themselves (under Swiss/Liechtenstein law), but only via service providers such as the following 4 companies:

Horizon Globex (Zug Switzerland): software provider 
https://www.horizon-globex.com/investors/ohg-history/
https://www.horizon-globex.com/investors/ohg-history/
Crypto Consulting AG (Zurich, Switzerland): ICO services (Reto Stiffler, myself, is partner of CCA and founder of SmartOne foundation)
https://cryptoconsultingag.ch/
https://cryptoconsultingag.ch/
Ganten Group (Vaduz, Liechtenstein): trustee services (Klaus Stark is partner at GG and founder of SmartOne foundation)
http://www.gantengroup.com/en/home
http://www.gantengroup.com/en/home
NGS (Zurich, Switzerland): lawyers
http://ngs-legal.ch/drupal/en/lawyers

These companies will be the first members of the LEGAL Standard for ICOs and STOs, which will be ready by the end of the year. 
https://github.com/HorizonGlobex/smartone

As a member, the companies must accept 10% of their revenues in LGL tokens.

New members pay a fee of 50,000 LGL tokens to join the LEGAL Standard.

This will ensure a constant demand for LGL tokens. 

The founders didn`t get a single dime for their work, but only LGL tokens. They are fully incentivized to make it a success. One week before you stopped trading for LGL, the new github account with a preview of the LEGAL Standard was created and the order book at Forkdelta was filled up to start creating liquidity for the membership scheme. 

Hopefully, this convinces you to restart trading of the LGL.


Please do not hesitate to contact me again, if you need more information.


Kind regards,

Reto

+41 79 616 43 40

**Comment by freeatnet** [comment]
@u15776 I'm afraid the documents attached didn't make it through.

**Comment by freeatnet** [comment]
Resolved in favor of keeping LGL recognized.
