### ISSUE TITLE
Token Listing Request: URSIUM TOKEN

### ISSUE THREAD

**Issue by wgextra** [forkdelta/tokenbase#198]
Hello!

We would like you to list our token on ForkDelta.
Please review the detailed info below.

Best regards,

URSIUM team

---
addr: '0x7971c7b520204216f158cbc669a7ffe088402592'
decimals: 18
description: Token designed for easy and secure value transfers among individuals in Tokyo, Japan
name: URSIUM
symbol: URS
links:
- Website: https://www.ursium.net/
- Telegram: https://t.me/ursium

**Comment by Kryptoniq** [comment]
1. Provide an official link that verifies your contract address. On your website or whitepaper.
2. Provide a link to a third-party review or discussion about the token.

**Comment by JonathonDunford** [comment]
@wgextra 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.
