### ISSUE TITLE
Suspicious Email to make payment for listing!!

### ISSUE THREAD

**Issue by truegoldtoken** [forkdelta/tokenbase#1981]
I just received an email saying our listing was approved and that we have to make 1BTC payment:

Hello

@FTKA16!

your request to list "TrueGold (TXAU)" is APPROVED.
Further Steps:

Payment
Integration
Test deposits / withdrawals
Creating trading pair
Our listing fee : 1 BTC
If you accept this price - make a payment to this wallet address : 1629Xa4JAhYWvsrrdiMNHL3Zm65ubh7rP3
The listing in 01 Day

After payment, please, provide hash.

Regards,
therealMikkoK
Forkdelta Exchange >
<img width="1063" alt="screenshot 2018-11-10 at 9 48 22 am" src="https://user-images.githubusercontent.com/44690853/48297061-e0c7e400-e4da-11e8-88b3-5b40b493fa98.png">
<img width="958" alt="screenshot 2018-11-10 at 9 55 42 am" src="https://user-images.githubusercontent.com/44690853/48297067-ea514c00-e4da-11e8-9526-a41ef6dba590.png">

**Comment by satoricore** [comment]
Ohh yea this is suspicious indeed!! 
But for what i see from your screenshot it looks like it comes from the official forkdelta account email! 
Any admin here to try to clarify whats going on? or just ignoring this issue?

**Comment by satoricore** [comment]
Whats even more strange is that most listing requests are being left unanswered for the past 2 weeks by the forkdelta admins, why is that!!!??

**Comment by satoricore** [comment]
Anyone else getting such emails?? If yes please post here as this may be connected!

**Comment by freeatnet** [comment]
There is no payment for Tooenbase listings. It is free. If your receive any messages asking for payment, ignore them.

**Comment by therealMikkoK** [comment]
yes, don't ever pay me anything for listings! Stay frosty everyone!
