### ISSUE TITLE
Update Kurecoin smart contract and Symbol

### ISSUE THREAD

**Issue by Sunnairo** [forkdelta/tokenbase#1985]
**What token should be updated?**

Kurecoin (KRC7)

https://etherscan.io/token/0x40e230d349daf337d01b765765c3fa0cd0cb930a

https://kurecoinhub.com 
https://kurecoinhub.io

**What about the token should be updated?**

Smart contract and token symbol

https://kurecoinhub.com/blog/kurecoin/kurecoin-token-swap/

**Comment by Sunnairo** [comment]
Update please

**Comment by Sunnairo** [comment]
This is 2 weeks already. Update please

**Comment by freeatnet** [comment]
#1865.
