### ISSUE TITLE
Naviaddress NaviToken ( NAVI )

### ISSUE THREAD

**Issue by MioGreen** [forkdelta/tokenbase#1987]
**Token address:**
0x588047365df5ba589f923604aac23d673555c623

**Issuer's official website:**
https://naviaddress.com/

**Description:** 
Naviaddress is a smart digital address for any places and objects. It combines a postal address, coordinates, digitized and searchable data about your object or location. Using Naviaddress Platform
simplifies last-mile navigation. Naviaddress gives an opportunity to transform a language-specific address and place description into digitized and searchable information about your object or location.

**A link to the official contract address confirmation:** 
https://naviaddress.com/token-holders

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://e27.co/postal-addresses-pain-blockchain-tech-can-change-20180214/
2. https://www.the-blockchain.com/2018/03/13/naviaddress-global-digital-address-platform-launches-in-beta/
3. https://www.techbullion.com/naviaddress-gives-everything-digital-address/
4. http://www.forbes.ru/tehnologii/346329-ne-dom-i-ne-ulica-na-chem-budut-zarabatyvat-sozdateli-novoy-adresnoy-sistemy (RU)

**Comment by Bidex-Exchange** [comment]
http://bidex.tech/#!/trade/NAVI-ETH
