### ISSUE TITLE
Listing Request: ETERBASE (XBASE) Token 

### ISSUE THREAD

**Issue by EterbaseRA** [forkdelta/tokenbase#1989]
**Token address:**

0x49a1cbb5d28cdedd55b7daa627f658fbd8cf1d23

**Issuer's official website:**

https://www.eterbase.com/

**Description:** 

ETERBASE is a cryptocurrency exchange platform with a focus on multi-asset support and regulatory compliance. There is clearly an underserved market for a reliable cryptocurrency exchange with a robust operational and technological infrastructure on par with the large banks and Wall Street firms. ETERBASE is engaged in the process of a fully compliant platform that offers a broad range of B2C and B2B cryptocurrency-specialized solutions. These include a high-frequency trading platform capable of real-time spot trading and margin trading, over-the-counter trading, and high frequency server hosting with a direct-market access and incentive system for market makers.

**A link to the official contract address confirmation:** 

https://www.eterbase.com/terms-and-conditions

Under: 2. XBASE SALE

THE MAXIMUM TOTAL AMOUNT OF XBASE TO BE ISSUED IS **1,000,000,000** _(direct link to contract here)_. NO MORE XBASE WILL BE ISSUED AFTER THE END OF THE XBASE SALE, AS DESCRIBED IN THE PRECEDING PARAGRAPH. OWNERSHIP OF XBASE DURING THE XBASE TOKEN SALE CARRIES NO RIGHTS EXPRESS OR IMPLIED. PURCHASES OF XBASE ARE NON-REFUNDABLE.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icobench.com/ico/eterbase
2. https://www.coinschedule.com/ico/eterbase-token
3. https://icomarks.com/ico/eterbase
4. https://icoholder.com/en/eterbase-23714
5. https://icolink.com/ico-eterbase.html

**Comment by Bidex-Exchange** [comment]
http://bidex.tech/#!/trade/XBASE-ETH
