### ISSUE TITLE
Listing Cerium Token on ForkDelta

### ISSUE THREAD

**Issue by CeriumToken** [forkdelta/tokenbase#199]
![logoheader-01-01](https://user-images.githubusercontent.com/36761802/36590543-4933f362-188f-11e8-8f7b-536ec9c9c553.png)

Hi,

I am Bozdag Mahsum, the owner of Cerium Token. We wish to list our token on ForkDelta.
We are a growing community, already 2100 fallowers on twitter and more than 200 members on telegram.
Cerium is an Ethereum based Token and we aim to become Global Exchange Token. We are aiming big markets and we are working hard on our project.

Token Name: **Cerium Token**
Ticker: **Cerium**
Maximum Total supply: **10 billion Cerium** (perfect number)

Cerium Token Website: www.ceriumtoken.com
Our Official Twitter Page: https://twitter.com/CeriumToken
Cerium Contract Adress: **0x8183dc52ce1cff90eba453c4a450f3d2d98f0ee3**
Explorer: etherscan.io: https://etherscan.io/token/0x8183dc52ce1cff90eba453c4a450f3d2d98f0ee3
Cerium contact: contact@ceriumtoken.com 

We have contacted to Etherscan and sent them all informations to update Cerium Token on Etherscan.

Regards.

Edit: Announcements: 
CryptocurrencyTalk: https://cryptocurrencytalk.com/topic/95682-ann-cerium-token-global-exchange-token
BitcoinTalk: https://bitcointalk.org/index.php?topic=2896296.0
Telegram: https://t.me/joinchat/GWZJ60DEG5MTcKbb7YzKCg

**Comment by Kryptoniq** [comment]
0x8183dc52ce1cff90eba453c4a450f3d2d98f0ee3, https://www.ceriumtoken.com/

**Comment by CeriumToken** [comment]
Hey, now I have to pull request to “submit a request” for listing our Token on Fork Delta?

**Comment by Kryptoniq** [comment]
No. You don't have to make a pull request. Your token will be listed.

**Comment by CeriumToken** [comment]
Hey, thank you for your quick answer and your help. We will make sure to reward ForkDelta very soon.

**Comment by freeatnet** [comment]
@CeriumToken Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/Cerium-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
