### ISSUE TITLE
Yum token

### ISSUE THREAD

**Issue by jjungsubdream** [forkdelta/tokenbase#1993]
**Token address:**

0x7f4404db6a3f4d3cfb41d5920d81d44d64759235
--

**Issuer's official website:**
https://www.yumerium.com/store

**Description:** 
The Blockchain-based, Incentivised, Open Gaming Platform.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x7f4404db6a3f4d3cfb41d5920d81d44d64759235

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://t.me/joinchat/H5o7EE7ncnHvSXJJYWSLYg
2.https://www.facebook.com/pg/Yumeriumtoken/
3. https://twitter.com/yumeriumtoken?lang=en

**Comment by Bidex-Exchange** [comment]
http://bidex.tech/#!/trade/YUM-ETH
