### ISSUE TITLE
Add Influ Token

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#1997]
**Token address:**
0x85c77c93b730bc4f568aff15f98cea8bd7230e1c

**Issuer's official website:**

**Description:** 
A decentralized social currency for Influencers, Companies & Consumers.
InfluWay Ecosystem consists of Influ Token which is divided for two purposes on our decentralized platform called InfluWay and it will also give our users all the flexibility and convenience cryptocurrencies offer.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x85c77c93b730bc4f568aff15f98cea8bd7230e1c

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://medium.com/@influtoken
2. https://icobench.com/ico/influ

**Comment by Bidex-Exchange** [comment]
http://bidex.tech/#!/trade/INTOS-ETH
