### ISSUE TITLE
MeeTip Token Listing

### ISSUE THREAD

**Issue by outmysphere** [forkdelta/tokenbase#200]
Hello Dev,

We would like to list our token on ForkDelta.

MeeTip is a cryptocurrency that will be used into OutMySphere in order to offer drinks to your soulmate or to your friends and tip the employee of your choice.
OutMySphere is a mobile app allowing to know instantly the crowd in bars, restaurants, nightclubs, coffees, casinos and fitness gyms. With this app, you will see who is in each establishment and you will be able to interact with them. 

Name: MeeTip
Symbol: MTIP
Decimals: 18
Address: 0x57a3dc224dccc0526954ff60ca6badd19c274d88
Etherscan verification: https://etherscan.io/address/0x57a3dc224dccc0526954ff60ca6badd19c274d88#code
Website (can verify the address): https://www.meetip.io/

Some articles : 
https://bitcoiner.today/en/icos-meetip-the-cryptocurrency-of-meetings-of-interest-to-the-match-group-tinder-tm/
http://altcoinalerts.com/meetip-outmysphere-international-development/
https://www.coinspeaker.com/2017/11/04/invest-meetips-promising-ico/

**Comment by Kryptoniq** [comment]
0x57a3dc224dccc0526954ff60ca6badd19c274d88, https://www.meetip.io/

**Comment by freeatnet** [comment]
@outmysphere Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/MTIP-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
