### ISSUE TITLE
Epocum (EPM) Token listing

### ISSUE THREAD

**Issue by epocum** [forkdelta/tokenbase#201]
---
addr: '0xc5594d84b996a68326d89fb35e4b89b3323ef37d'
decimals: 18
description: >-
  The first digital economy based on websites connectivity
  
  Epocum offers a platform oriented to guarantee security and transparency for the next generation of 
  digital remuneration based on websites connectivity. 

name: Epocum
symbol: EPM
links:
- Bitcointalk: https://bitcointalk.org/index.php?topic=2858364.0
- Email: mailto:administration@epocum.com
- Telegram: https://telegram.me/epocum
- Twitter: https://twitter.com/epocum
- Facebook: https://www.facebook.com/epocum
- Website: https://www.epocum.com/
- Blog: https://medium.com/@epocum
- Reddit: https://www.reddit.com/r/Epocum
- Github: https://github.com/epocum

Address verification link:
- https://www.epocum.com/details

Pubblications on high quality media:
- https://hackernoon.com/epocum-the-future-of-websites-digital-remuneration-1bbe4927fb78
- https://blog.goodaudience.com/smart-sharing-contracts-a-new-standard-for-the-next-generation-advertising-industries-517ea10f9016
- https://cryptocurrencyhub.io/introducing-epocum-and-smart-sharing-contracts-1f91a73f0730

**Comment by Kryptoniq** [comment]
0xc5594d84b996a68326d89fb35e4b89b3323ef37d, https://www.epocum.com/

**Comment by freeatnet** [comment]
@epocum Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/EPM-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
