### ISSUE TITLE
request listings for ETK Tokens

### ISSUE THREAD

**Issue by eternetwork** [forkdelta/tokenbase#2015]
<! - listing requests: ETK token tool for service payments (ETK). ->

<! - Contract address: 0xFd27B9eeEfe2d27e41e29Cd85F51517b41040971 https://etherscan.io/address/0xfd27b9eeefe2d27e41e29cd85f51517b41040971. ->

<! - publisher's official website: https: //eternetwork.net. ->

<! - confirm the official contract address: https: //eternetwork.net, open the site and scroll down a little and you will see "our contract to add to the token costume." . ->

<! - link to reviews or third party discussions about https: // bitcointalk: bitcointalk.org/index.php?topic=5070735.msg47976471#msg47976471
Medium: Medium.com/akengates12. ->

<! - description: eternetwork is an advertising for new project platform that allows ETK as a community transcription tool for service payments and more. ->

<! - social media links
Twitter: https://twitter.com/eternetwork
Telegram: t.me/etknetwork
Medium: medium.com/akengates12. ->

**Comment by freeatnet** [comment]
Wrong issue type.
