### ISSUE TITLE
Request to Add ZRS TOKEN

### ISSUE THREAD

**Issue by ZIRCASH** [forkdelta/tokenbase#2018]
**Token address:** https://etherscan.io/token/0x302eb72befc8af539432ec32c39423525412748f

**Issuer's official website:** https://zircash.io

**Description:**   About Zircash-:Cryptocurrency is a digital currency which can be used to transfer assets from person to person in a decentralized way. We are known to the most common names like Bitcoin or Ethereum but apart from these, there are many others in the major bull market.

In this era where technology is taking turns every now and then, maintaining the momentum we are introducing ‘ZIRCASH’

“Your gateway to the world of crypto finance”

Zircash provides a platform that allows the investors to choose a manager for his/her portfolio and can safely trade with cryptocurrencies.

What make Zircash popular among the others in the same race are the special features it holds:

· Decentralized secure network.
· Based on smart contracts.
· Re-invest of your own tokens.
· 5% referral bonus.
· Self execution of funds.

**A link to the official contract address confirmation:** https://etherscan.io/address/0x302eb72befc8af539432ec32c39423525412748f

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:** https://bitcointalk.org/index.php?topic=5046923.20
https://play.google.com/store/apps/details?id=com.zircash.zircashwallet
https://etherscan.io/address/0x302eb72befc8af539432ec32c39423525412748f#events

1. https://medium.com/zircash
2.https://twitter.com/Zircash_ZRS
3. https://t.me/zircash

**Comment by Bidex-Exchange** [comment]
http://bidex.tech/#!/trade/ZRS-ETH
