### ISSUE TITLE
Miner One (MIO Token)

### ISSUE THREAD

**Issue by writtenbetween** [forkdelta/tokenbase#2024]
**Token address:** 0x141044ccC363d6E8D92dD8983422775913e304eC

**Issuer's official website:** https://minerone.io

**Description:** Miner One is a cutting-edge, crowdfunded bitcoin mining operation built and managed by a team of data centre industry experts on behalf of the Miner One Community.
Miner One Community Members are those who contributed to building the mining facilities by purchasing MIO Tokens during the Miner One Crowdsale and include those who have subsequently obtained MIO Tokens from their original holders. MIO Tokens entitle holders to a monthly share in Miner One output.

**A link to the official contract address confirmation:** https://minerone.io/token-info/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
1. https://icobench.com/ico/miner-one
2. https://www.youtube.com/watch?v=EwRFmLqFH8E
3. https://www.youtube.com/watch?v=fS965clKGC0

**Comment by Bidex-Exchange** [comment]
http://bidex.tech/#!/trade/MIO-ETH
