### ISSUE TITLE
Tigereum Token

### ISSUE THREAD

**Issue by gabrieladeniji** [forkdelta/tokenbase#203]
---
addr: '0xeee2d00eb7deb8dd6924187f5aa3496b7d06e62a'
decimals: 18
description: Send crypto to friends and family in an instant message
links:
  - Bitcointalk: https://bitcointalk.org/index.php?topic=2331649.0
  - Blog: https://www.trackico.io/ico/tigereum/
  - CoinMarketCap: https://coinmarketcap.com/currencies/tigereum
  - Facebook: https://web.facebook.com/tigereum
  - Reddit: https://www.reddit.com/user/Tigereum
  - Twitter: https://twitter.com/tigereumtokens
  - Website: https://www.tigereum.io/
  - Whitepaper: https://docs.wixstatic.com/ugd/970dc6_15842e85a6874c79810d6dbfd60867d0.pdf

name: Tigereum
symbol: TIG

**Comment by Kryptoniq** [comment]
Duplicate #202
