### ISSUE TITLE
Euro Token Listing

### ISSUE THREAD

**Issue by EuroToken** [forkdelta/tokenbase#204]
Hello ForkDelta Team, 
Our details are listing below.

1. 0xf144a4c4aab893598f5a08ad7804d3d106613242
2. https://eurodigital.co
3. Euro Token is a Revolutionary Digital Money System built on the Ethereum blockchain that gives the everyday person more control over their financial future. Initial funding will go towards development of a Web and Android wallet for use with the Euro Card and Euro Marketplace. 
4. https://eurodigital.co
https://etherscan.io/address/0x99b0517953b05833371edccf981b023768bf49bd
5. https://bitcointalk.org/index.php?topic=3005197

Token Information:
Name: EURO
Symbol: EURO
Decimals: 18 
Total Supply: 21,000,000 
Platform: Ethereum 
Token Address: 0xf144a4c4aab893598f5a08ad7804d3d106613242 
Token Explorer: https://etherscan.io/token/0xf144a4c4aab893598f5a08ad7804d3d106613242 
Purchase Tokens: https://etherdelta.com/#0xf144a4c4aab893598f5a08ad7804d3d106613242-ETH
Website: https://eurodigital.co

Kind Regards

Euro Team
support@eurodigital.co
eurodigitaltoken@gmail.com

**Comment by Kryptoniq** [comment]
#196
