### ISSUE TITLE
Request Alvalor Token

### ISSUE THREAD

**Issue by Alexbrem** [forkdelta/tokenbase#205]
Alvalor Token

The Alvalor team is dedicated to building a scalable blockchain. This is realised by focusing on moving complexity to second layer channels and building a simple and efficient base layer.
Being close to launching the first prototype, you can follow the progress on our github: https://github.com/alvalor/

The TVAL token serves as the initial distribution once the native alvalor blockchain goes live.

Details:

addr: '0x24cebc1548e698feffb5553b8ac8043b51069faa'
decimals: 12
description: A blockchain protocol stack designed for scalable & flexible blockchain applications.  
name: Alvalor
symbol: TVAL

Website: https://www.avalor.org
Medium: https://medium.com/alvalor

Contract confirmation:
Proof 1: Twitter description: https://twitter.com/alvalorproject
Proof 2: section "How can I see the tokens in my wallet?" in the FAQ of the official airdrop website here: https://drop.alvalor.org

Independent discussions: 
https://bitcointalk.org/index.php?topic=1964747.0

**Comment by Kryptoniq** [comment]
0x24cebc1548e698feffb5553b8ac8043b51069faa, https://www.avalor.org

**Comment by freeatnet** [comment]
@Alexbrem Thank you for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/TVAL-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
