### ISSUE TITLE
THOR Token Listing

### ISSUE THREAD

**Issue by thor-valhalla** [forkdelta/tokenbase#206]
Hi,
We would like to list our token.

Short description:  Learning Platform, Influencers Connectors & Payment Cards for Cryptocurrencies. We want to close the gap between the real world and Blockchain environment, SIMPLIFYING CRYPTOCURRENCIES.

Total supply: 100 000 THOR
name: THOR
ticker: THR
Contract: 0x6816dF892602c7E6b741f03FEf9c7eC57061A73f
Decimals: 18

Url: www.valhalla-thor.com
Contact email: info@valhalla-thor.com
BitcoinTalk announcement : https://bitcointalk.org/index.php?topic=3005830.new#new
Twitter: https://twitter.com/THR_VALHALLA
Telegram: https://telegram.me/thorcoin
Github: https://github.com/thor-valhalla/valhalla-thor
Etherscan: https://etherscan.io/address/0x6816df892602c7e6b741f03fef9c7ec57061a73f

Regards,
THOR Team

**Comment by Kryptoniq** [comment]
Please provide an official link that verifies the  contract address. E.G on the website or whitepaper.

**Comment by thor-valhalla** [comment]
Hi, Here you have the link that verifies the contract address.
Below "SUPPLY DISTRIBUTION"
https://www.valhalla-thor.com/tokens-1

Thanks,
THOR Team

**Comment by thor-valhalla** [comment]
Hi, Here you have the link that verifies the contract address.
Below "SUPPLY DISTRIBUTION"

https://www.valhalla-thor.com/tokens-1

Thanks,
THOR Team

**Comment by freeatnet** [comment]
Insufficient information: no public discussion or independent 3rd party review linked.

**Comment by thor-valhalla** [comment]
Hy Arseniy Ivanov
Public discussions:
- Reddit https://www.reddit.com/user/THOR-Cryptocurrency/
- Bitcointalk https://bitcointalk.org/index.php?topic=3005830.new#new

You need anything else?
We are also setting up a discord channel.
Thanks!
Thor Team

**Comment by freeatnet** [comment]
@thor-valhalla There is not enough, well, public discussion in your "public discussion" sources. I can currently see no comments on your reddit posts and 2 comments only on your bitcointalk announcement.

**Comment by thor-valhalla** [comment]
Yes, we just started. And we are just creating the community. We can
contact you guys again, when the discord is set up, or the community starts
to growth.
Thanks for your time.
We really appreciate it.
Thor Team
