### ISSUE TITLE
Listing Carlos Matos Coin (Carlos Matos Token $HEY)

### ISSUE THREAD

**Issue by Picapica2201** [forkdelta/tokenbase#207]
addr: '0x278f5d89c85a4ac8aaa39e08444212cbb2546fd2'
decimals: 18
description: Carlos Matos Coin (HEY) its a revolutionary coin who is changing the world as we know it.
Name: Carlos Matos Token.
TOKEN: HEY

Token: HEY
Name: Carlos Matos Token.
Contract Address: 0x278f5d89c85a4ac8aaa39e08444212cbb2546fd2
Website: http://carlosco.in/
BITCOINTALK: https://bitcointalk.org/index.php?topic=2994076.0
Twitter: https://twitter.com/MatosCoin

**Comment by Kryptoniq** [comment]
0x278f5d89c85a4ac8aaa39e08444212cbb2546fd2,  https://carlosco.in/

**Comment by Kryptoniq** [comment]
Your project has no roadmap or goals other than speculations.
Sorry, your token  can't be listed.

**Comment by freeatnet** [comment]
@Picapica2201 Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/HEY-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
