### ISSUE TITLE
Request for Listing Grim Reaper Token , Symbol "GR"

### ISSUE THREAD

**Issue by grimreapernetwork** [forkdelta/tokenbase#208]
Dear Sir/Madam,

We request ForkDelta to list our Grim Reaper Token with details below

address : 0x50D14578E0cAF771f92d4D72FF423cFf7234277d
Decimal: 0
description: Reaper on Blockchain
Name: GrimReaperToken
Symbol: GR
 Type - ERC 20
website: http://www.grimreaper.network/
mail id: grimreaper.network@gmail.com and mr.death@grimreaper.network
whitpaper: http://www.grimreaper.network/wp-content/uploads/2018/02/Grim-Reaper-Project-v0.3-1.pdf
Token link: https://etherscan.io/address/0x50d14578e0caf771f92d4d72ff423cff7234277d
Token contract address on website:- http://www.grimreaper.network/details/
Twitter link to verify contract address:- https://twitter.com/MR_DEATH_REAPER/status/970020546070110208
Token Brief - 
Grim Reaper is a Reaper on the Blockchain project. With the advent of blockchains like Bitcoin, Ethereum, NEO and in future more capable names like Ripple, Cardano, Icon, Wanchain, Matrix AI, ArcBlock etc etc, we believe blockchain based solution incorporating anonymity, faster transactions, security and lowest possible overhead costs is the way forward.
Links:

Medium: https://medium.com/@grimreaper.network
Twitter - https://twitter.com/MR_DEATH_REAPER
bitcointalk: https://bitcointalk.org/index.php?topic=3006547
Github Address - https://github.com/grimreapernetwork/

Regards,
Team GrimReaperToken

**Comment by Kryptoniq** [comment]
1. Provide an official link that verifies the contract address.
2. Provide a link to a third-party review or discussion about the token.

**Comment by grimreapernetwork** [comment]
verified: 0x50D14578E0cAF771f92d4D72FF423cFf7234277d

**Comment by grimreapernetwork** [comment]
address : 0x50D14578E0cAF771f92d4D72FF423cFf7234277d
Decimal: 0
description: Reaper on Blockchain
Name: GrimReaperToken
Symbol: GR

Links: 

Medium: https://medium.com/@grimreaper.network
Twitter - https://twitter.com/MR_DEATH_REAPER
bitcointalk: https://bitcointalk.org/index.php?topic=3006547

**Comment by Kryptoniq** [comment]
1. The contract address cannot be found on your website.
2. The bitcointalk announcement thread has only one comment.

**Comment by grimreapernetwork** [comment]
Token contract address and link in website:- http://www.grimreaper.network/details/

**Comment by grimreapernetwork** [comment]
Twitter link to verify contract address:- https://twitter.com/MR_DEATH_REAPER/status/970020546070110208

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient comments / reviews.

**Comment by grimreapernetwork** [comment]
how many are needed

**Comment by Kryptoniq** [comment]
Hi, we need constructive third-party  reviews of the token.
