### ISSUE TITLE
LISTING OF TOKEN

### ISSUE THREAD

**Issue by JOINMATRIX** [forkdelta/tokenbase#210]
NAME: MATRIX
SYMBOL: ONE
TOKEN ADDRESS: 0x871A71438029549A836c042D3Bd0e88cA6c88388
WEBSITE: www.joinmatrix.net
SUPPLY: 100,000,000,000,000

Description: MATRIX is a token that allows investors to join a society where events and meetings be held all over the world to discuss cryptocurrency and its applications and uses in many other industries. We hope to be able to bring investors together to create a very strong cryptocurrency community.

**Comment by Kryptoniq** [comment]
Provide link to a third-party review or discussion about the token.

**Comment by JOINMATRIX** [comment]
https://bitcointalk.org/index.php?topic=3006405.new#new

**Comment by JOINMATRIX** [comment]
Apologies for missing that!

Thanks

**Comment by JOINMATRIX** [comment]
Any Other information you need please let me know!
Thanks

**Comment by Kryptoniq** [comment]
The information provided on your Bitcointalk announcement thread  is Insufficient.

**Comment by Kryptoniq** [comment]
I will have to close this issue as per new listing guidelines.
No update for the past 12 days.
