### ISSUE TITLE
Add DockToken

### ISSUE THREAD

**Issue by smh020** [forkdelta/tokenbase#212]
You will need to include the following information in the issue:

The contract address.
0x940d73c91db9f82440702f6cc8323a8c60583777
A link to the token issuer's official website.
https://dock.io/
A couple sentences for token description.
dock.io is a decentralized data exchange protocol built entirely on blockchain, transforming the $200 billion professional industry.
A link to an official page confirming the contract address.
https://etherscan.io/address/0xe5dada80aa6477e85d09747f2842f7993d0df71c
https://icobench.com/ico/dock-io
https://icodrops.com/dock-io/

**Comment by Kryptoniq** [comment]
Please provide an official link that verifies the contract address. It should be on the website or whitepaper.

**Comment by smh020** [comment]
https://medium.com/@alexabatinic12/how-to-add-docktokens-to-myetherwallet-6c16edbd8df8

**Comment by Kryptoniq** [comment]
It should be on the website or whitepaper.

**Comment by JonathonDunford** [comment]
@smh020 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.
