### ISSUE TITLE
Add REMME token

### ISSUE THREAD

**Issue by smh020** [forkdelta/tokenbase#213]
You will need to include the following information in the issue:

The contract address.
0x83984d6142934bb535793a82adb0a46ef0f66b6d
A link to the token issuer's official website.
https://remme.io/
A couple sentences for token description.
No more passwords — no more break-ins. REMME implements foolproof user authentication to protect from cyber attacks while eliminating passwords.
A link to an official page confirming the contract address.
https://ethplorer.io/address/0x83984d6142934bb535793a82adb0a46ef0f66b6d
A link to a third-party review or discussion of the token, like an established ICO review blog.
https://icobench.com/ico/remme
https://icodrops.com/remme/

**Comment by Kryptoniq** [comment]
Please provide an official link that verifies the contract address. It should be on the website or whitepaper.

**Comment by tradedbytony** [comment]
On their official website, https://remme.io, they have their twitter account linked as https://twitter.com/remme_io. If you go to https://twitter.com/remme_io/status/963628130035552258 you will see that their official Twitter account acknowledged 0x83984d6142934bb535793A82ADB0a46EF0F66B6d as their contract address and having 4 decimals.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x83984d6142934bb535793A82ADB0a46EF0F66B6d, https://remme.io

**Comment by freeatnet** [comment]
@smh020 Thank you for your request! REMME token has been listed: https://forkdelta.github.io/#!/trade/REM-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
