### ISSUE TITLE
Token Listing: BitSong Token

### ISSUE THREAD

**Issue by bitsongofficial** [forkdelta/tokenbase#2134]
**Token address:**
https://etherscan.io/token/0x05079687d35b93538cbd59fe5596380cae9054a9

**Issuer's official website:**
https://bitsong.io

**Description:** 
BitSong is a new music streaming platforms, which will be built using the Blockchain Technologies and the IPFS distribuited filesystem.

**A link to the official contract address confirmation:** 
https://bitsong.io (Token Distribution)

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.ilsole24ore.com/art/tecnologie/2018-06-08/dalla-musica-salvadanaio-bambini-ecco-cosa-sta-nascendo-mondo-blockchain-160634.shtml?uuid=AEghqv2E&fromSearch
2. https://cryptonomist.ch/it/2018/06/25/bitsong-2/
3. https://www.coinschedule.com/ico/bitsong
4. https://www.youtube.com/channel/UCBVRgebGoly_zSPp7NWvhJQ
5. https://icoslot.com/en/ico/bitsong/
6. https://www.coinhills.com/ico/view/bitsong/
7. https://coincodex.com/ico/bitsong/
8. https://www.coingecko.com/en/ico/bitsong

**Comment by BitSongOfficial** [comment]
Any news guys?

**Comment by BitSongOfficial** [comment]
up
