### ISSUE TITLE
Add CREDITS

### ISSUE THREAD

**Issue by smh020** [forkdelta/tokenbase#214]
You will need to include the following information in the issue:

The contract address.
0x46b9ad944d1059450da1163511069c718f699d31
A link to the token issuer's official website.
https://credits.com/en
A couple sentences for token description.
Blockchain platform CREDITS for creation and management of financial services on the basis of the blockchain/ledger - credits.com.
A link to an official page confirming the contract address.
https://etherscan.io/token/0x46b9ad944d1059450da1163511069c718f699d31
https://ethplorer.io/address/0x46b9ad944d1059450da1163511069c718f699d31
A link to a third-party review or discussion of the token, like an established ICO review blog.
https://medium.com/@info_19130/credits-com-ico-revolutionizing-the-blockchain-8a1f647c3cb8
https://icobench.com/ico/credits
https://icodrops.com/credits/

**Comment by Kryptoniq** [comment]
0x46b9ad944d1059450da1163511069c718f699d31, https://credits.com/en

**Comment by freeatnet** [comment]
@smh020 Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/CREDITS-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
