### ISSUE TITLE
Add RED MWAT

### ISSUE THREAD

**Issue by smh020** [forkdelta/tokenbase#215]
You will need to include the following information in the issue:

The contract address.
0x6425c6be902d692ae2db752b3c268afadb099d3b
A link to the token issuer's official website.
https://restartenergy.io/
A couple sentences for token description.
The official website of RED MWAT Token, the world's first Ethereum token able to virtually store electrical energy.
A link to an official page confirming the contract address.
https://etherscan.io/address/0x6425c6be902d692ae2db752b3c268afadb099d3b
A link to a third-party review or discussion of the token, like an established ICO review blog.
https://restartenergy.io/
https://icobench.com/ico/restart-energy
https://icodrops.com/restart-energy/

**Comment by Kryptoniq** [comment]
0x6425c6be902d692ae2db752b3c268afadb099d3b, https://restartenergy.io/

**Comment by freeatnet** [comment]
@smh020 Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/MWAT-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
