### ISSUE TITLE
Add Ethereumred ETHR

### ISSUE THREAD

**Issue by ethereumdz** [forkdelta/tokenbase#216]
addr: ''0x67335D5fCbD1e5319823Af8Eb179Faa1bd8D6fAd''
decimals: 8
description: Ethereum RED (ETHR) its a revolutionary coin who is changing the world as we know it.
Name: Ehereum RED.
TOKEN: ETHR

Token: ETHR
Name: Ethereum RED.
Contract Address: 0x67335D5fCbD1e5319823Af8Eb179Faa1bd8D6fAd
Website: http://ethereumred.io/
BITCOINTALK: 
https://bitcointalk.org/index.php?topic=2966951.0
Twirrer: Twitter.com/ethereumred
Telegram : t.me/ethereumred
Email: info@ethereumred.io

**Comment by Kryptoniq** [comment]
0x67335D5fCbD1e5319823Af8Eb179Faa1bd8D6fAd, http://ethereumred.io/

**Comment by ethereumdz** [comment]
Thank you very much for the support when the currency is inserted please

**Comment by Kryptoniq** [comment]
Team members are possible case of identity theft.
A Google photo search of the images of your team members comes from different sources.

**Comment by Kryptoniq** [comment]
Sorry, we can't list your token.

**Comment by ethereumdz** [comment]
Existing identity documents for people

**Comment by ethereumdz** [comment]
existing
