### ISSUE TITLE
Listing of TWNKL at Forkdelta

### ISSUE THREAD

**Issue by ShareSmart** [forkdelta/tokenbase#218]
Contract address:
0xfbd0d1c77B501796A35D86cF91d65D9778EeE695
Token: TWNKL
Decimals: 3

Issuer's official website:
https://rainbowcurrency.com/

Official contract address confirmation (MUST be linked from official website):
[Click Here for Token Address]

A link to a third-party review or discussion of the token, like an established ICO review blog: 
Bitcointalk: https://bitcointalk.org/index.php?topic=2735483
Facebook: https://www.facebook.com/RainbowCurrency
Twitter: https://twitter.com/RainbowCurrency
Reddit: https://www.reddit.com/r/RainbowCurrency/
Telegram: https://t.me/joinchat/IGdYD0UEDO7YmEWg3VZWww
Email: foundation@rainbowcurrency.com

Description:
The Rainbow Currency is different! It has been created by more than 3,200 Internet users from 157 different countries. For the first time ever, a cryptocurrency is launched by the people for the people, controlled and represented by a global non-profit foundation. This is your chance to join the movement.

**Comment by Kryptoniq** [comment]
#181

**Comment by ShareSmart** [comment]
Thank you for the reply.

What Stephen had applied made the Token to be available at MyEtherWallet
Default Token.
What I am requesting for is to list it in the dropdown at ForkDelta.
But, as I can see his request #181 is still open.
So, When can we expect TWNKL to be listed in the dropdown at ForkDelta.

Many Thanks,
ShareSmart
