### ISSUE TITLE
Add Virtual Cash (VCA) token

### ISSUE THREAD

**Issue by jaguar666** [forkdelta/tokenbase#219]
Token Name: Virtual Cash
Token Symbol: VCA
Decimals: 8

Contract address: 0x0beE5Ca8dDa2C0b8EdD1C4369F7CC35d243E547f

Issuer's official website: http://www.virtualcash.shop

Official contract address confirmation (MUST be linked from official website): 
http://www.virtualcash.shop/crowdsale/en/#crowdsale
http://www.virtualcash.shop/files/VCA-whitepaper-en.pdf

A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2821367

Description: VirtualCash (VCA) is a virtual money integrated in Ethereum blockchain that will serve as the main payment method for our e-commerce online store and for VCA conversion to Paypal and WesternUnion.

To find out more about Virtual Cash (VCA)
   Facebook: https://www.facebook.com/VCA.VirtualCash/
   Twitter: https://twitter.com/VCA_VirtualCash
   Telegram: https://t.me/virtualcash
   Discord: https://discord.gg/TkE2QUq
   Email Address: info@virtualcash.shop

**Comment by Kryptoniq** [comment]
0x0bee5ca8dda2c0b8edd1c4369f7cc35d243e547f, http://www.virtualcash.shop

**Comment by freeatnet** [comment]
@jaguar666 Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/VCA-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
