### ISSUE TITLE
Adding Our Token to Your Exchange (Ethereum Premium)

### ISSUE THREAD

**Issue by ethereumpremium** [forkdelta/tokenbase#220]
Dear Sir/Madam,

We would like to add our recently established token to your exchange. We have attached the required information, as requested on your website. We are looking forward to hearing from you.

Description:
addr: 0xb4F5438c3C2A682da351Ab6b57edC8530efD67bE
decimals: 4
name: Ethereum Premium
symbol: ETHPR
Token Tracker: https://etherscan.io/token/0xb4f5438c3c2a682da351ab6b57edc8530efd67be
Token Info: http://www.ethereumpremium.com/token.html
description: Manage payments, inter- and intra-company money transfers without third-parties.

Bitcointalk: https://bitcointalk.org/index.php?topic=2656057
Github: https://github.com/ethereumpremium

Official Website and Team: http://www.ethereumpremium.com/
WhitePaper: http://www.ethereumpremium.com/Ethereum_Premium_Whitepaper_1.pdf

Twitter: https://twitter.com/ethereumpremium
Facebook: https://www.facebook.com/Ethereum-Premium-346375329105093/

Kind Regards,
The Ethereum Premium Team

**Comment by Kryptoniq** [comment]
0xb4f5438c3c2a682da351ab6b57edc8530efd67be, https://www.ethereumpremium.com/

**Comment by freeatnet** [comment]
@ethereumpremium Thank you for your request! Ethereum Premium has been listed: https://forkdelta.github.io/#!/trade/ETHPR-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
