### ISSUE TITLE
ATRL Token listing

### ISSUE THREAD

**Issue by stvenbaby** [forkdelta/tokenbase#221]
Hello!

We would like to list our token.

Short description: Atrl is an end-to-end technology solution that captures and provides previously inaccessible data to retailers and other "brick-and-mortar" businesses through its proprietary blockchain and real-time sensor technology.
Total supply: 80 000 000 ATRL
name: ATRL Token
Symbol: ATRL
Contract address: 0x7f5b40c7681e6780b415e4ec3155deea9f0fb329
Decimals: 18
Website: https://www.atrltoken.com/
Contact email: zhongwei2080@gmail.com
BitcoinTalk announcement :https://bitcointalk.org/index.php?topic=2991956.new#new
Twitter: https://twitter.com/Atrl_token
Telegram: https://t.me/Atrl_Token
Etherscan Verification: https://etherscan.io/address/0x7f5b40c7681e6780b415e4ec3155deea9f0fb329#code
Confirmation of contract address:
https://www.atrltoken.com/token-sale.html  (white paper is on the way)

Regards,
Atrl Team

**Comment by Kryptoniq** [comment]
#194
