### ISSUE TITLE
Listing request - REN

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#222]
Website: https://republicprotocol.com
Whitepaper: https://republicprotocol.github.io/whitepaper/republic-whitepaper.pdf
Description: Republic Protocol is an open-source decentralized dark pool exchange. It facilitates cross-chain atomic trades on a hidden order book over the Ethereum and Bitcoin networks.

Contract address: https://etherscan.io/token/0x408e41876cCCDC0F92210600ef50372656052a38
Symbol: REN
Full Name: Republic Token
Decimals: 18
Type: ERC20

Link to confirm contract can be found on their official Medium post: https://medium.com/republicprotocol/how-to-participate-in-republic-protocol-crowdsale-1935c9438c65 (republicprotocol.eth = 0x408e41876cCCDC0F92210600ef50372656052a38).
Link(s) to a third-party review: 
https://crushcrypto.com/republic-protocol-ico-review
https://medium.com/research-center/republic-protocol-ren-ico-analysis-a-decentralized-dark-pool-for-cryptocurrency-assets-e20bc125d3bf

**Comment by Kryptoniq** [comment]
0x408e41876cccdc0f92210600ef50372656052a38, https://republicprotocol.com/

**Comment by freeatnet** [comment]
@tradedbytony  Thanks for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/REN-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
