### ISSUE TITLE
List Token Ethereum Trust (Etht)

### ISSUE THREAD

**Issue by ethertrustlabs** [forkdelta/tokenbase#223]
Contract address: 0xbeb4e73fadb43810670d698a79dd492a109f59a6

Issuer's official website: https://ethereumtrust.site/

Official contract address confirmation (MUST be linked from official website):

A link to a third-party review or discussion of the token, like an established ICO review blog: 

Ethereum Trust tokens are one of its kind tokens that will truly revolutionize the blockchain era. Ethereum Trust aims to rate every possible blockchain project at present which will provide a  proper rating information to various entities related to a project. Further, we wish to start a pure decentralised atomic swap with Ethereum Trust tokens as the base market. Thus, for every Ethereum Trust token users will be able to swap them with the most highly rated cryptocurrencies starting from November 2018.

Description:

Every Blockchain project has its own relevance, community, platform, utility and future vision. Ethereum Trust Score will define these over a numerical rating so that it is easy for everyone to identify the actual value associated with the project. It is a huge task and we will make it possible for everybody.

**Comment by ethertrustlabs** [comment]
Dear Team,

This token is actually a proof of work. Please visit the website once and help us in joining your excellence of work at forkdelta.

**Comment by Kryptoniq** [comment]
Provide a link to a third-party review or discussion of the token, like an established ICO review blog.

**Comment by JonathonDunford** [comment]
@ethertrustlabs 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.
