### ISSUE TITLE
SOC Token listing

### ISSUE THREAD

**Issue by stocktestnet** [forkdelta/tokenbase#225]
Hello!

We would like to list our token.
Description :
SOC is determined to change people’s lives while meeting the needs and demands inherent in the travel industry. Through dedicated grants and development, SOC will work to allow for an easier, more humane experience for travellers worldwide. And, through grants provided to fund software development, PR and Marketing will help people to change their lives while they are part of changing the world.  

name: stocktest
Symbol: SOC
Contract address: 0x58e450be10f5659c685ec5e62703c25f3b9f5105
Decimals: 0
Website: http://stocktest.net/
BitcoinTalk announcement :https://bitcointalk.org/index.php?topic=3011216
Etherscan Verification: https://etherscan.io/address/0x58e450be10f5659c685ec5e62703c25f3b9f5105#code
Confirmation of contract address: http://stocktest.net/soc-token-rc20/

Regards,

**Comment by Kryptoniq** [comment]
0x58e450be10f5659c685ec5e62703c25f3b9f5105, https://stocktest.net/

**Comment by freeatnet** [comment]
* No public discussion of the token.
* The main website appears to be aggregating articles from around the internet with no proper attribution.
* 0 token holders currently.
