### ISSUE TITLE
Add Game Fanz ( GFN )

### ISSUE THREAD

**Issue by GameFanz** [forkdelta/tokenbase#2255]
**Token address:**
0x3930e4ddb4d24ef2f4cb54c1f009a3694b708428

**Issuer's official website:**
https://gamefanz.io

**Description:** 
Game Fanz is A Glorious Platform for Gamers in the World .
Game Fanz has set a target to participate in the revolution of gaming industry by providing the gamers with more thrills and excitement. To make sure that development of the games meets the specified timeline. Game Fanz is issuing GFN utility tokens. The tokens are ERC-20 based upon Ethereum Blockchain.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x3930e4ddb4d24ef2f4cb54c1f009a3694b708428

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://icobench.com/ico/game-fanz
2. https://www.coinjinja.com/ico/game-fanz
3. https://www.coingecko.com/en/ico/game-fanz
4. https://foundico.com/ico/game-fanz.html
5. https://icomarks.com/ico/game-fanz
6. https://icopulse.com/ico/game-fanz
7. https://cryptototem.com/game-fanz-ico/

**Comment by GameFanz** [comment]
@freeatnet

**Comment by freeatnet** [comment]
Thank you for your request, @GameFanz!

**For your safety, please note the following:**

- All communication regarding your request will be posted publicly in this request. You can check the entire history for the request here, at [`https://github.com/forkdelta/tokenbase/issues/2255`](https://github.com/forkdelta/tokenbase/issues/2255).
- Users affiliated with ForkDelta project will have a "Member" badge on their comment. You may also see comments from other users.
- **There is no payment, it's free!** There is no charge for adding or updating tokens. If you receive any messages asking for payment, do not respond to them.
- We will not ask you to move conversation to email or a messenger.
- We do not provide Tokenbase support over email or direct messages. If you have questions or concerns, please post them here.

**Next steps:**

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here, at [`https://github.com/forkdelta/tokenbase/issues/2255`](https://github.com/forkdelta/tokenbase/issues/2255).
- You can expect to hear back from us within 8 weeks.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

**Comment by freeatnet** [comment]
@GameFanz Looks like you accidentally removed the line the bot uses to identify token requests. Otherwise request looks correctly formatted though. Reopened.

**Comment by GameFanz** [comment]
and now what should i do sir ?

**Comment by freeatnet** [comment]
@GameFanz We'll post here when there are any updates. Keep an eye open for notifications from GitHub and always make sure to read the updates on this page, `https://github.com/forkdelta/tokenbase/issues/2255`.

**Comment by GameFanz** [comment]
ok sir , no need edit or something sir ? 

thanks for your response
