### ISSUE TITLE
Kindly requesting for ssente token (ssn) listing

### ISSUE THREAD

**Issue by ssente** [forkdelta/tokenbase#226]
Contract address:
0x6b14c373c24556165002a00cba4174fd96fe28f0

Issuer's official website:
www.ssente.site
Official contract address confirmation (MUST be linked from official website):
https://etherscan.io/token/0x6b14c373c24556165002a00cba4174fd96fe28f0

A link to a third-party review or discussion of the token, like an established ICO review blog: 

https://bitcointalk.org/index.php?topic=2442762.msg25014716#msg25014716

Description:

Ssente (Ugandan word meaning "MONEY") token is a decentralised African-made ERC20 token introduced as an alternative to money and other online money transfer system for the unbanked population of the country to have access to online financial services to allow individuals to make fast,less costly and secure transactions between parties involved as well as East African countries and countries around the world on ETHEREUM NETWORK.
It's mainly concerned to ease transaction (sending and recieving) of money between EAST AFRICAN COUNTRIES (uganda,kenya,Tanzania,Rwanda,and Burundi) and countries around the world that can later be change to real cash.

**Comment by ssente** [comment]
Name: ssente
Symbol: ssn
Decimals: 8

Thanks

**Comment by Kryptoniq** [comment]
0x6b14c373c24556165002a00cba4174fd96fe28f0, http://ssente.site

**Comment by freeatnet** [comment]
@ssente Thank you for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/ssn-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
