### ISSUE TITLE
sexhdsolo listing request

### ISSUE THREAD

**Issue by sexhdsolo** [forkdelta/tokenbase#227]
We would like to list our token.
Description : Sex dating service based on a blockchain . We pose as sex dating service by mutual sympathy and sex-related communications mainly, which are legal in most countries' jurisdictions.

Contract address: 0x754a024bd98c79532e570af47e21695a861d2be3
name: sexhdsolo
Symbol: SEX
Decimals: 0
Website: http://sexhdsolo.com/
BitcoinTalk announcement :https://bitcointalk.org/index.php?topic=3011333
Confirmation of contract address: http://sexhdsolo.com

Regards,

**Comment by freeatnet** [comment]
* Website directly copied from sexservice.io.
* Links to media announcements also point to the sexservice.io project.
* Whitepaper copy-pasted from sexservice.io with clear signs of replacing sexservice.io with sexhdsolo.com.

Will not list.
