### ISSUE TITLE
Listing Application - ALPHA

### ISSUE THREAD

**Issue by heelloToken** [forkdelta/tokenbase#228]
Contract address:
https://etherscan.io/token/0x3eb21f4678b352fcd8facf06b642c6720e04961b#balances

Issuer's official website:
https://www.alpha-platform.com/

Official contract address confirmation (MUST be linked from official website):
https://www.alpha-platform.com/

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://t.me/joinchat/Grun2Q8kXI45yOKS3yyl7A

Description:
This is a token of education in the blockchain and wallet safety education. With the growing trend of the blockchain, related education has become very important

**Comment by freeatnet** [comment]
Thanks for your request, @heelloToken.

The basics of the request are done right; however, I would recommend two adjustments:
1. The link to your Telegram chat does not qualify as a third-party review from an established source. It must be at minimum be a bitcointalk discussion, or a reputable token review website.
2. Expand the description of your token. In particular, explain what value the token carries and how it is used by your platform.

**Comment by JonathonDunford** [comment]
@heelloToken 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.
