### ISSUE TITLE
Lisiting Garuda Token ( GAD )

### ISSUE THREAD

**Issue by garudatoken** [forkdelta/tokenbase#2288]
**Token address:**

**Issuer's official website:**

**Description:** 

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by adzbtc17** [comment]
Garuda Token Good Project

**Comment by santoso4** [comment]
Good project with many member
