### ISSUE TITLE
Request to list ULTRA (ERC20 ETH Token)

### ISSUE THREAD

**Issue by DigitalNomadCoin** [forkdelta/tokenbase#230]
Contract address: **0x9d19930Fb230873206d16682cfFA8C0FAd4d871B**

Issuer's official website: https://ultracoin.webnode.be/

Official contract address confirmation (MUST be linked from official website): https://ultracoin.webnode.be/eth-contract/

A link to a third-party review or discussion of the token, like an established ICO review blog:  https://bitcointalk.org/index.php?topic=3013364.0
--

Description:

The ULTRA Coin stands for extreme profitability !

We want to contribute to redistribute the wealth on earth, by giving everyone the possibility to invest in extreme profitable projects

How will the ULTRA Coin bring wealth to you ? We will invest the profits of the ULTRA Coin via the automated cryptocurrency trade robots of the "The Bitcoin Code", a bitcoin currency investment company  partially owned by Elon Musk (Tesla).

How does the Bitcoin Code work ? It is a series of very advanced robots using Artificial Intelligence (AI) Software to scan all sources of information about cryptocurrencies : facebook, twitter, telegram, newspapers, ... It processes all info published about cryptocurrencies, and decides which cryptocurrencies will rise. The robots then automatically purchase this cryptocurrencies before the rise takes place on the exchanges, and make as such an important profit.

How will YOU profit from the benefits that WE make via the Bitcoin Code investments ?

The ULTRA coins is launched on the Exchanges in March 2018. We will bring 100 % of the coins to the Exchanges, allowing you to buy this coin at very low prices.

We will invest the money raised by the ULTRA Coin via the trading robots of the Bitcoin Code. We will do this during 2 years.

In March 2020 we will start a buy back of 30 % of all ULTRA Coins on the market. We will do that at 200 % of the normal price of an ULTRA coin (as noted in Coinmarketcap.com on March 1st, 2020).

**Comment by Kryptoniq** [comment]
0x9d19930fb230873206d16682cffa8c0fad4d871b, https://ultracoin.webnode.be/

**Comment by Kryptoniq** [comment]
1. It appears you are using a free subdomain hosting website.
2. No roadmap or project goals.
Sorry, your token can't be listed.
