### ISSUE TITLE
ERC20 Token Listing 

### ISSUE THREAD

**Issue by Assetbasefoundation** [forkdelta/tokenbase#231]
addr: '0x0FcF5C6b20577d48bA209e077975b9F2EaC55798'

decimals: 5
description: The AssetBase Foundation is a decentralized control foundation that hold the physical metal that backs every token. AssetBase has moved on to the next phase of the project. All tokens are ERC20 ethereum tokens. If you have any questions feel free to contact me at Josh@AssetBase.io

Name: SILVER.
TOKEN: SVB

Token: SVB
Name: Silver,
Contract Address: 0x0FcF5C6b20577d48bA209e077975b9F2EaC55798
Website: https://foundation.assetbase.io/
Twitter: https://twitter.com/RealAssetBase
 FaceBook: https://www.facebook.com/AssetBase.io
Code on Website: https://assetbase.store/#1516732555874-f3f1f12d-5330 
(Look under coin code)
Third Party Rating: https://www.trackico.io/ico/assetbase/#tab-overview
Our project it rated a 4.8 out of 5. 

Token Details: 
Every Silver (SVB) token is backed by one gram of silver.

**Comment by Kryptoniq** [comment]
1. Only one website link is needed.
2. Provide  link to a third-party review or discussion about the token.

**Comment by Assetbasefoundation** [comment]
Website: Foundation.assetbase.io
Third Party Rating: https://www.trackico.io/ico/assetbase/#tab-overview

Our project it rated a 4.8 out of 5.

**Comment by Kryptoniq** [comment]
#234
