### ISSUE TITLE
Please,listed on ForkDelta (utopic coin)

### ISSUE THREAD

**Issue by utopiccoin** [forkdelta/tokenbase#233]
Token Name: Utopic Coin
Token Symbol: UTPC
Decimals: 5

Contract address: 0x69Fbf8707a3F6b30B438D694fe333e27c287BffC

Issuer's official website: https://utopiccoin.com

Official contract address confirmation (MUST be linked from official website): https://etherscan.io/token/0x69Fbf8707a3F6b30B438D694fe333e27c287BffC |  https://utopiccoin.com (we replaced our contract address in our website footer ,please look )

A link to a third-party review or discussion of the token, like an established ICO review blog:  https://bitcointalk.org/index.php?topic=2936144.0 , https://bitcointalk.org/index.php?topic=2965812.msg30464561#msg30464561 ,  Telegram : https://t.me/utopiccoin

Description:Utopic is a token focused on creating and supporting business opportunities and projects in and around the cryptocurrency world. Utopic will help create business opportunities and projects. Part of the money earned from business opportunities and projects will be divided among investors. Whether it be an already-existing projects or a basic idea in its early conception, Utopic welcomes any opportunity to assist and be involved. Utopic is a basic idea in an existing project or new project.Invest in a cryptocurrency that is built to increase in value over time and also gives you the opportunity to build wealth. Vault your spiritual life to new levels and enjoy the benefits that come from living a fulfilling life. Earn additional income without changing your daily routine by being active in the Utopic Coin community.Each token gives its owner the right to receive profit according to the declared conditions.We will prepare Project Management Training Programs. We have very talented project managers. Leadership: An Important Project Manager Attribute:Because teams need strong leaders, the most successful project managers are also decisive, inspiring leaders. When these essential skills are lacking, morale and productivity can drop, along with sales and profits.Our strong project managers have enough knowledge in these areas:1)Math and analysis 2)Coordination 3)Technical ability 4)Organization 5)Delegation 6)Communication

Email : support@utopiccoin.com
Telegram : https://t.me/utopiccoin
Twitter : https://twitter.com/utopiccoin

**Comment by Kryptoniq** [comment]
0x69fbf8707a3f6b30b438d694fe333e27c287bffc, https://utopiccoin.com

**Comment by utopiccoin** [comment]
Thanks for the supports !
When will it be added to the list on ForkDelta?

**Comment by freeatnet** [comment]
* Insufficient public discussion of the token or project, no links to independent reviews from credible sources.
* Website features team photos lifted wholly from the website template (see http://kaki-langit.com/) and no verifiable information about the team.
