### ISSUE TITLE
List UBITCASH

### ISSUE THREAD

**Issue by Blockchainappfactory** [forkdelta/tokenbase#2339]
**Token address:0xd750430fb81dc53a23ad225cdc82d7e4c22b0cfb**

**Issuer's official website:www.ubitcash.org**

**Description: Ubit cash is blockchain-based smart contract (ERC20) built on the most powerful blockchain technology named “Ethereum”,
it's ghost protocol allows faster transaction times and capable to grow and adapt to the needs of the community.** 

**A link to the official contract address confirmation:https://etherscan.io/token/0xd750430fb81dc53a23ad225cdc82d7e4c22b0cfb** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://ubitcash.org/ubitcash-whitepaper.pdf
https://www.linkedin.com/company/ubit-cash/about/**

1. https://twitter.com/ubitcash1
2. https://t.me/ubitcash1

**Comment by munir007** [comment]
acccept this coin
