### ISSUE TITLE
ERC20 Token AssetBase 

### ISSUE THREAD

**Issue by Assetbasefoundation** [forkdelta/tokenbase#234]
addr: '0x0FcF5C6b20577d48bA209e077975b9F2EaC55798'

decimals: 5
description: The AssetBase Foundation is a decentralized control foundation that hold the physical metal that backs every token. AssetBase has moved on to the next phase of the project. All tokens are ERC20 ethereum tokens. If you have any questions feel free to contact me at Josh@AssetBase.io

Name: SILVER.
TOKEN: SVB

Token: SVB
Name: Silver,
Contract Address: 0x0FcF5C6b20577d48bA209e077975b9F2EaC55798
Website: https://foundation.assetbase.io/
Twitter: https://twitter.com/RealAssetBase
FaceBook: https://www.facebook.com/AssetBase.io
Code on Website: https://assetbase.store/#1516732555874-f3f1f12d-5330
(Look under coin code)
Third Party Rating: https://www.trackico.io/ico/assetbase/#tab-overview
Our project it rated a 4.8 out of 5.
https://bitcointalk.org/index.php?topic=2943055.0

Token Details:
Every Silver (SVB) token is backed by one gram of silver.

**Comment by Kryptoniq** [comment]
0x0fcf5c6b20577d48ba209e077975b9f2eac55798, https://foundation.assetbase.io/

**Comment by Kryptoniq** [comment]
Please make the contract address available on the main website (https://foundation.assetbase.io/).

**Comment by Assetbasefoundation** [comment]
Hi, Done, Here is the Link:

https://foundation.assetbase.io/silvercontract/

**Comment by Kryptoniq** [comment]
0x0fcf5c6b20577d48ba209e077975b9f2eac55798, https://foundation.assetbase.io/

**Comment by Assetbasefoundation** [comment]
Thanks, When will it be added to the list on ForkDelta?

**Comment by freeatnet** [comment]
@Assetbasefoundation Thank you for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/SVB-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by Assetbasefoundation** [comment]
Thanks, we will be donating and also we will promote ForkDelta as much as we can!
