### ISSUE TITLE
New Contract iBTC token

### ISSUE THREAD

**Issue by walerikus** [forkdelta/tokenbase#2340]
Update to a new smart contract and replace the old one https://etherscan.io/token/0xb7c4a82936194fee52a4e3d4cec3415f74507532

**What token should be updated?** IBTC

https://etherscan.io/token/0x0784dbabb6c6834bddfb7cfee116ba049e5dafab

**What about the token should be updated?** Smart Contract Address

https://coinmarketcap.com/currencies/ibtc/
https://twitter.com/ibtctoken
https://t.me/ibtctoken

https://www.ibtctoken.com/

**Comment by freeatnet** [comment]
@walerikus I can't seem to find any official mention of the swap. Could you add a link for that?

**Comment by walerikus** [comment]
https://mercatox.com/news/ibtc-new
You can also see that coinmarketcap already updated the information and explorer links show the new smart contracts

**Comment by walerikus** [comment]
Hello, we are still waiting for an update of the new ibtc smart contract.
