### ISSUE TITLE
Please list DNO

### ISSUE THREAD

**Issue by rdenke** [forkdelta/tokenbase#235]
Contract address: 0x10B35b348Fd49966f2BaF81df35A511c18bD1f80

Issuer's official website:  Denario.io

Official contract address confirmation (MUST be linked from official website):
https://denaro.io/docs/Denaro_smart_contract.pdf

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2833302.0

Description: 
Denaro seamless payment ecosystem bridges the divide between cryptocurrencies and the mainstream market. The platform enables companies and individuals to send, spend, store, and exchange cryptos and fiat through secure web wallets, physical debit cards, merchant payment terminals, and IBAN.

**Comment by Kryptoniq** [comment]
0x10b35b348fd49966f2baf81df35a511c18bd1f80, https://denaro.io/

**Comment by freeatnet** [comment]
@rdenke Thank you for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/DNO-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
