### ISSUE TITLE
ADD TOKEN: FUTEREUM CENTURIAN (FUTC)

### ISSUE THREAD

**Issue by futereum** [forkdelta/tokenbase#2357]
**Token address: 0xf880d3c6dcda42a7b2f6640703c5748557865b35**

**Issuer's official website: https://futereum.com**

**Description: Futereum Network is a synthetic blockchain application composed of five mineable smart contracts in up to 13 ERC20 tokens. Futereum Centurian receives deposits of FUTR, FUTX, BNB, OMG, BNT, AE, MKR, BAT, ZRX, BYT and PRE as players play the four other Futereum contracts. A FUTC holder can claim a proportionate share of all tokens that are stored in the FUTC smart contract at any time. Once claimed, only newly 'unclaimed' deposits will be made available for the FUTC holder to claim.** 

**A link to the official contract address confirmation: https://etherscan.io/address/0xf880d3c6dcda42a7b2f6640703c5748557865b35#code** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer: https://coinrivet.com/futereum-synthetic-utility-in-ethereum/ and https://www.youtube.com/watch?v=_6I4N8KJmVY and https://bitcoinexchangeguide.com/futereum-futr/ and https://www.coinrivet.com/is-bnb-really-an-erc-20-token/ and https://www.cryptoninjas.net/2018/01/12/futereum-foundation-launches-eth-blockchain-futures-futr/**

1. https://discordapp.com/invite/JWv9eQp
2. https://twitter.com/futereum1
3. https://www.facebook.com/futereum1
4. https://www.youtube.com/channel/UCbdz6gGat1srAY9UqmZhwfQ
5. https://bitcointalk.org/index.php?topic=5117862.0

**Comment by futereum** [comment]
See: https://www.stateofthedapps.com/dapps/futereum-bitcoin for associated contract

**Comment by SwanLakeBallet** [comment]
The Futereum Network gives you a head-up to see the Next Generation Financial System which the members can own their digital assets on a blockchain-based synthetic system. The system with software written in Ethereum-based ERC-20 tokens. 

Part of those assets (FUTC) will help their owners claiming a proportionate share of all tokens that are stored in the FUTC smart contract at any time.

Players who would like to yield steady income are encouraged to exchange some units of FUTC. However, it would also be the duties of all players to provide full support to the community to maintain the sustainability of the whole Network in order to the it maximise the performance for all.

**Comment by hanshanshanshanshans** [comment]
Think of the synthchain as the hooverdam. Futc gives you a share in all electricity (fees) it generates, for all eternity, over and over again. You basically co-own the project! Game changer guys...

**Comment by cryptoprefect** [comment]
If you missed the chance as a pioneer of Bitcoin, it's your turn to experience the excitement. You should enjoy this enhanced version very much!

**Comment by futereum** [comment]
More press: https://thecurrencyjournal.com/2019/01/04/daniel-mark-harrison-watch-us-this-is-going-to-go-wild/ and https://medium.com/@futereum/how-futereum-will-to-change-the-world-168d0853dc8d

**Comment by futereum** [comment]
Connected contract: https://www.dapp.com/dapp/futereum-bitcoin

**Comment by futereum** [comment]
Also in the press here: https://www.legalgamblingandthelaw.com/news/futereum-to-answer-skeptics-questioning-inherent-value-in-cryptos/

**Comment by cryptoprefect** [comment]
Why to recommend? The design of different smart contracts inside the network for different functions helps to cater for different players' needs. You can predict the return in some contracts even though they are not listed in any exchanges yet. However, the Synthchain can help all the contracts within the network to synchronize the value each other. Fantastic!

**Comment by cryptoprefect** [comment]
The design is complicated, but the entry to participate is simple. If I am a beginner, I think I will try FUTX first which can predict the return easily.

**Comment by SwanLakeBallet** [comment]
No doubt that I am an experienced FUTX miner a year ago to wait to see the performance / execution of the software. For sure, I am planning for a strategy to enter into the game again soon.

**Comment by futereum** [comment]
More recent press and review of token FUTC: https://thecurrencyjournal.com/2019/03/21/why-futereum-is-the-future-of-cryptocurrency-economics/

**Comment by futereum** [comment]
Yet MORE press on the amazing Futereum dev team finding a fault with BNB (which can be mined with FUTC now thanks to our fix!): https://www.ccn.com/bnb-official-coin-of-binance-may-not-be-an-erc20-token

**Comment by Savasana** [comment]
Anticipated to see Futereum Centurian listed in any exchange soon!

**Comment by cryptoprefect** [comment]
Wow! So excited to see all levels up! Simply taking a bite and we see how it tastes!

**Comment by Savasana** [comment]
Good job! FUTC is listed on exchange (Cryptaldash)!

**Comment by futereum** [comment]
FUTC is indeed trading on CryptalDash now, against DASH CRD BTC ETH USDT. Healthy spread of base pairs!

**Comment by futereum** [comment]
Will we hear back from you guys?

**Comment by mouragio** [comment]
Yes, and was all the info provided in a good manner to proceed? please advice.
