### ISSUE TITLE
Please list CLT

### ISSUE THREAD

**Issue by rdenke** [forkdelta/tokenbase#236]
Contract address: 0x2001f2A0Cf801EcFda622f6C28fb6E10d803D969

Issuer's official website:  https://coinloan.io/

Official contract address confirmation (MUST be linked from official website):
https://tokensale.coinloan.io/

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2103691.0

Description: 
CoinLoan is a licensed fiat lending
platform that secures and guarantees
loans with cryptoassets so you can
hold onto your crypto instead of
selling them when you need cash.

**Comment by Kryptoniq** [comment]
0x2001f2a0cf801ecfda622f6c28fb6e10d803d969, https://coinloan.io/

**Comment by freeatnet** [comment]
@rdenke Thank you for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/CLT-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
