### ISSUE TITLE
ENTRC token update

### ISSUE THREAD

**Issue by bitstine** [forkdelta/tokenbase#2367]
Hello.. We would like to update our token contract address, please.
**What token should be updated?**

ENTRC 
Old: 0xaf55f3b7dc65c8f9577cf00c8c5ca7b6e8cc4433 
New address: 0xd9d01d4cb824219a8f482a0fad479cb971fd0628
**What about the token should be updated?**

https://entercoin.net --> FAQ - Coin Specific tab 

Best regards,
Shadi

**Comment by shadiayoub** [comment]
Hello... 
We applied for the update 27 days ago.. Any news please? 
Or anything we can provide to make the process faster? 
Regards
