### ISSUE TITLE
Listing request - ABT

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#237]
Website: https://www.arcblock.io
Whitepaper: https://www.arcblock.io/file/whitepaper/WhitePaperEnV2_en-US.pdf?v=4
Description: ArcBlock, the world’s first blockchain ecosystem for building and deploying decentralized applications.

Contract address: https://etherscan.io/token/0xb98d4c97425d9908e66e53a6fdf673acca0be986
Symbol: ABT
Full Name: ArcBlock
Decimals: 18

Link to confirm contract can be found on their official Twitter post: https://twitter.com/ArcBlock_io/status/967441203431174144

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2699379
https://venturebeat.com/2018/01/03/arcblock-the-worlds-first-blockchain-ecosystem-for-decentralized-applications-is-building-the-foundation-for-blockchain-3-0
https://steemit.com/arcblock/@dive-into-crypto/arcblock-ico-review-10-reasons-why-the-world-s-first-blockchain-ecosystem-arcblock-is-promising

**Comment by Kryptoniq** [comment]
Contract address should be linked on the official website.

**Comment by freeatnet** [comment]
@Kryptoniq https://twitter.com/ArcBlock_io/status/967441203431174144 looks good to me, twitter linked from official website.

**Comment by Kryptoniq** [comment]
0xb98d4c97425d9908e66e53a6fdf673acca0be986, https://www.arcblock.io/

**Comment by freeatnet** [comment]
@tradedbytony Thank you for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/ABT-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
