### ISSUE TITLE
Add a New Token - AMC (Alphamarket Coin)

### ISSUE THREAD

**Issue by alphamarket-amc** [forkdelta/tokenbase#2375]
**Token address:**
0xc26aA9AD649C5Def6d7f94fc46667F70210fE565

**Issuer's official website:**
https://tokensale.alphamarket.online/en/l/

**Description:** 
AlphaMarket is a crypto-trading platform, enabling buyers and sellers from
around the world to find each other and make safe transactions in the Blockchain
environment. Free placement of goods, the possibility of multi-cryptocurrency
transactions, promotions, bonuses, cashback and many other useful options
will be available to the platform users. The fast-growing market and the rapidly
rising demand from buyers and sellers make AlphaMarket an extremely popular
product in the market of cryptocurrencies.

**A link to the official contract address confirmation:** 
https://github.com/alphamarket-online
https://tokensale.alphamarket.online/en/l/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.trackico.io/ico/alphamarket/
2. https://youtu.be/TDA_Oetr-ic
3. https://invest4all.ru/obzory-i-otchyoty/obzory-kraudsejlov-ico/alphamarket-e-commerce-epohi-blockchain
4. https://icodeadline.com/topics/5370
5. https://golos.io/alphamarket/@danilfromtorzok/kriptomagazin-alphamarker

**Comment by Realido** [comment]
That's a great project!
