### ISSUE TITLE
Add ASU token

### ISSUE THREAD

**Issue by yasudem** [forkdelta/tokenbase#238]
We would like to list our token.
Description : Yasudem is the first custom-tailored decentralized token for cybersecurity professionals. It is based on Ethereum platform.

Contract address: 0x53e222554de8d71b51909060d002b35a72a4d3a6
name: yasudem
Symbol: ASU
Decimals: 18
Website: http://yasudem.com/
BitcoinTalk announcement : https://bitcointalk.org/index.php?topic=3015852
Confirmation of contract address: http://yasudem.com/

Regards,

**Comment by Kryptoniq** [comment]
1. Only one token holder.
2. Bitcointalk thread created today.

**Comment by freeatnet** [comment]
@Kryptoniq Most importantly, the website is a wholesale copy of https://hacken.io, including the logo.
