### ISSUE TITLE
SOMIDAX (SMDX) token listing request

### ISSUE THREAD

**Issue by somidax** [forkdelta/tokenbase#239]
Contract address: 0x7e8539d1e5cb91d63e46b8e188403b3f262a949b

Issuer's official website:  http://somidax.net

Official contract address confirmation (MUST be linked from official website): https://tradewallet.somidax.net/p2p-tradable-digital-asset/

A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2459782.0

Description:
SOMIDAX is offering a decentralized social interactive marketplace service platform that utilizes blockchain technology to create a new business model for social P2P interaction as well as buying and selling of products and service.

**Comment by Kryptoniq** [comment]
0x7e8539d1e5cb91d63e46b8e188403b3f262a949b, https://somidax.net

**Comment by Kryptoniq** [comment]
#245

**Comment by somidax** [comment]
what a wait,good job guys! @Kryptoniq
