### ISSUE TITLE
Horse (HR) token

### ISSUE THREAD

**Issue by Samael6661** [forkdelta/tokenbase#241]
Contract address: 0x7ba4ad8e9ac025dccca2ad43530c98af671c5bbe

Issuer's official website: http://horsetoken.ukit.me/

Official contract address confirmation (MUST be linked from official website):

Total supply : 100,000,000,000 
Decimals : 1
Contract address : 0x7ba4ad8e9ac025dccca2ad43530c98af671c5bbe
SYMBOL : HR 

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=3017009.msg31022797#msg31022797

Description:
Horse (HR) token is the erc-20 token,which was created for make happy traders with low cost transaction fee.Horse (HR) will be valuable as he going to first exchange.

**Comment by Kryptoniq** [comment]
1. You are using a free hosting subdomain.
2. Your token has no long term goal or roadmap.
3. Your bitcointalk account has -8 negative trust.
Sorry, we can't list your token.
