### ISSUE TITLE
FGD Token Listing Request

### ISSUE THREAD

**Issue by fairgrounds-dapp** [forkdelta/tokenbase#242]
Contract address: 0xce831af117375e6286eb3c46d696ee3dbf4f4f50

Issuer's official website: https://fairgrounds.bet

Official contract address confirmation (MUST be linked from official website): https://fairgrounds.bet/#/about

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2908959.0

Description:
A token which provides owners a proportional distribution of profits based on the Fairgrounds suite of chance-based games.

**Comment by Kryptoniq** [comment]
0xce831af117375e6286eb3c46d696ee3dbf4f4f50, https://fairgrounds.bet

**Comment by freeatnet** [comment]
@fairgrounds-dapp Thank you for your request! Your token has been listed: https://forkdelta.github.io/#!/trade/FGD-ETH. We will announce it on our channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
