### ISSUE TITLE
add GRG token

### ISSUE THREAD

**Issue by gabririgo** [forkdelta/tokenbase#2452]
**Token address:**
0x4FbB350052Bca5417566f188eB2EBCE5b19BC964

**Issuer's official website:**
https://rigoblock.com

**Description:** 
The Rigo Token is the utility token for governance and incentives of the RigoBlock protocol, a protocol to create and operate token pools, special purpose smart contracts which facilitate the organization of tokens and the interaction with decentralized exchanges.

**A link to the official contract address confirmation:** 
https://etherscan.io/token/0x4fbb350052bca5417566f188eb2ebce5b19bc964

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://blog.goodaudience.com/decentralized-asset-management-a-utopian-dream-db7302d73fd3
2. https://golos.io/ico/@sabrina89/ico-review-rigoblock-platform

**Comment by gabririgo** [comment]
can you please advise on this request? Many thanks

**Comment by freeatnet** [comment]
@gabririgo Oops. Is this request still relevant?

**Comment by gabririgo** [comment]
> @gabririgo Oops. Is this request still relevant?

@freeatnet not sure, if you're happy to have GRG added, it's highly appreciated. However, since the issue had been stale for so long, I thought I might just close it. It's fine to have it closed.
