### ISSUE TITLE
Add Xeonbit Token - XNS

### ISSUE THREAD

**Issue by Coinsman** [forkdelta/tokenbase#2458]
**Token address:** 0x79c71d3436f39ce382d0f58f1b011d88100b9d91

**Issuer's official website:** https://xeonbit.com

**Description:**  The Blockchain Solution For Global Payments Xeonbit is the private digital currency for secure payment network fully decentralized without any central authorities.

**A link to the official contract address confirmation:**  https://etherscan.io/token/0x79c71d3436f39ce382d0f58f1b011d88100b9d91

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**
* https://cointelegraph.com/press-releases/xeonbit-announces-application-to-list-asset-xeonbit-token-xns-and-submit-proposal-listing-on-binance-dex

* https://cointelegraph.com/news/platform-allows-users-to-send-and-receive-cryptocurrency-with-gadget-of-their-choice

* https://bitcointalk.org/index.php?topic=5067655.0

* https://community.binance.org/topic/47/reinstated-proposal-for-listing-xeonbittoken-xns-on-binance-dex/3

**Comment by rdxeonbit** [comment]
Hello Forkdelta, Is there any update about the Xeonbit Token (XNS) will be added. Thanks
