### ISSUE TITLE
Ripple Cash Listing request

### ISSUE THREAD

**Issue by RippleCash** [forkdelta/tokenbase#246]
Contract address: 0x6f0a7aa19425752ff39d9f568c9d930ef30997ed

Issuer's official website: www.ripple-cash.technology

Official contract address confirmation (MUST be linked from official website): https://www.ripple-cash.technology/about-us

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=3005702.msg30910270#msg30910270

Description:
Ripple Cash is a global, decentralized cryptocurrency designed with the sole intention of making it a frontline cryptocurrency which can be used in real world for making day-to-day transactions. Ripple Cash is designed to be the next generation payment system. This is a real-time, instant, secure and scalable payment system built on top of Ethereum network.
Github link: https://github.com/Ripple-Cash/RPCH/blob/master/RPCH_ERC20_Contract.txt

**Comment by Kryptoniq** [comment]
1. Insufficient information and reviews in your bitcointalk announcement.
2. Only one token holder.
Sorry, we can't list your token.
