### ISSUE TITLE
Listing request - GAT

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#247]
Website: https://www.gatcoin.io
Whitepaper: https://www.gatcoin.io/wp-content/uploads/2018/01/180104-GATCOIN-Whitepaper-ENG.pdf
Description: The future currency of digital shopping. We provide customer reward solutions for mainstream enterprises based off the Ethereum blockchain.

Contract address: https://etherscan.io/token/0x687174f8c49ceb7729d925c3a961507ea4ac7b28
Symbol: GAT
Full Name: GATCOIN
Decimals: 18

Link to confirm contract: https://www.gatcoin.io/view (close to the end of the page)

Third-party comment(s) on the token:
https://hacked.com/ico-analysis-gatcoin
https://bitcoinexchangeguide.com/gatcoin

**Comment by Kryptoniq** [comment]
0x687174f8c49ceb7729d925c3a961507ea4ac7b28, https://www.gatcoin.io/

**Comment by freeatnet** [comment]
@tradedbytony Thank you for your request! ArtisTurba has been listed: https://forkdelta.github.io/#!/trade/ARTIS-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
