### ISSUE TITLE
VerifyUnion - UC Coin Listing Request

### ISSUE THREAD

**Issue by Imperialdigital** [forkdelta/tokenbase#248]
Contract address: 0xB236E2477B8ed34B203B60e2b88884ee5b31a3c3

Issuer's official website: https://www.verifyunion.io/ 

Official contract address confirmation (MUST be linked from official website): https://verifyunion.io/smartcontract 

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://www.entrepreneur.com/article/308558 ( 11th Entry)

Description:

VerifyUnion is a decentralized Digital Identification and Trust Verification platform. VerifyUnion provides total ownership of the data being shared through the network to the customer/end user, protecting user privacy and securing their identity.

**Comment by Kryptoniq** [comment]
0xb236e2477b8ed34b203b60e2b88884ee5b31a3c3, https://www.verifyunion.io/

**Comment by Imperialdigital** [comment]
Hi, So how long it will take to list the token now?

**Comment by Imperialdigital** [comment]
Hi

When will UCN be listed?

Kind Regards

**Comment by freeatnet** [comment]
@Imperialdigital Thank you for your request! UC Coin has been listed: https://forkdelta.github.io/#!/trade/UCN-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by Imperialdigital** [comment]
Thanks guys, we happy to donate UCN for the team,'

Are you guys open to running joint competitions.

Lastly will you also announce this
