### ISSUE TITLE
listing Token: IPN token

### ISSUE THREAD

**Issue by iProtocolNetwork** [forkdelta/tokenbase#2481]
1.0x1f652BeD061fB52670fa3C43581989bD96B66AC9
2.https://iprotocol.network
3. iProtocol Network is a decentralized Blockchain based one stop web, mobile and desktop application system for the general users worldwide.
4.https://iprotocol.network please find (How to Buy IPN Token ) section.Just Before advisory board section.
5.https://icomarks.com/ieo/iprotocol-network
https://www.trackico.io/ico/iprotocol-network/
please contact support@iprotocol.network

**Comment by freeatnet** [comment]
Wrong template.
