### ISSUE TITLE
Add Token: XRT Robonomics

### ISSUE THREAD

**Issue by akru** [forkdelta/tokenbase#2489]
**Token address:**

 `0x7dE91B204C1C737bcEe6F000AAA6569Cf7061cb7`

**Issuer's official website:**

https://robonomics.network/en/

**Description:** 

Ethereum network infrastructure for cyber-physical systems' integration into Smart Cities and Industry 4.0

**A link to the official contract address confirmation:** 

https://etherscan.io/address/0x7dE91B204C1C737bcEe6F000AAA6569Cf7061cb7#contracts

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://blog.aira.life/robonomics-1-0-lts-60e783d3b84
2. https://blog.aira.life/the-results-of-the-airalab-team-work-in-2018-b7c2995669c
3. https://github.com/airalab/robonomics_contracts/blob/master/audit.md
4. https://bitcointalk.org/index.php?topic=4184662.0

(#2487)

**Comment by freeatnet** [comment]
@akru Is this token still a thing?

**Comment by akru** [comment]
@freeatnet sure, but this exchange looks a bit difficult to list it
