### ISSUE TITLE
JCC/Money Tree token

### ISSUE THREAD

**Issue by CryMoarz** [forkdelta/tokenbase#250]
Contract address: 0x55a0dd2f1b1d8034894c99507b6439eca479cf62

Issuer's official website: https://www.moneytree.pw

Official contract address confirmation (MUST be linked from official website): https://www.moneytree.pw main page, as well as their twitter, discord and telegram and announcement threads https://twitter.com/MoneyTreeJCC

A link to a third-party review or discussion of the token, like an established ICO review blog: 
Does ann count? They have an old ann for an airdrop and their new ann is https://bitcointalk.org/index.php?topic=2964762.0

Description:
Copied from their website:
"Money Tree is an ethereum game dapp that has many fantastic features. You grow a tree from a seed and harvest its fruit (various erc20+ tokens). It makes use of a fully player-run economy and auction house system."

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.

**Comment by freeatnet** [comment]
@CryMoarz Thank you for your request! REMME token has been listed: https://forkdelta.github.io/#!/trade/REM-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
