### ISSUE TITLE
Request Addition Token Charity CRY

### ISSUE THREAD

**Issue by CharityCRY** [forkdelta/tokenbase#2516]
**Token address:**
0x6bea3e5ccb205fbd3a0e0de74c2357d93f4e65bd

**Issuer's official website:**
http://charityou.com/

**Description:** 
Many social and environmental events that we will do in the future. Anybody can come to participate in the event as an cry token community and trade using cry token on exchanges. Cry is created by the people, for the people. We feel the need to help where we can, yet also understand the importance of thoroughly vetting our actions. 

Every event that occurs will be displayed in the progress attached. With the hope that the contributors can monitor the progress of each events

**A link to the official contract address confirmation:** 
https://etherscan.io/address/0x6bea3e5ccb205fbd3a0e0de74c2357d93f4e65bd

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://twitter.com/CharityCRY
2. https://bitcointalk.org/index.php?topic=5147533.msg51224846#msg51224846
3. https://www.reddit.com/user/CharityCRY
4. https://github.com/CharityCRY
5. https://t.me/charityCRY
5. http://charityou.com/wp-content/uploads/2019/05/Charity-CRY-Whitepaper.pdf

**Comment by zullherman7** [comment]
Great Project

**Comment by Alexbarwadi** [comment]
I recommend CRY as a good token

**Comment by vporton** [comment]
Request canceled.
