### ISSUE TITLE
Issue with the cV token

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#252]
If you look for cV (carVertical) is nowhere to be found among the C letter tokens, yet the token exists and is listed ALL the way at the bottom of the token list and it can be found below the ZCS token.

I'm guessing ForkDelta doesn't deal with lower cases very well. Any chance to get cV, and possibly other future tokens that start with a lower case, to display in the proper location?

**Comment by freeatnet** [comment]
@tradedbytony Yeah, looks like we'll end up switching to a case-insensitive sort. (This problem is also mentioned in #140)
