### ISSUE TITLE
cryptoWorld

### ISSUE THREAD

**Issue by makingcryptogreat** [forkdelta/tokenbase#253]
Contract address:
0x1edaae241aa62e0f91491f133dcc3a7e729c73f0 
Issuer's official website:
http://cryptoworld-com.stackstaging.com/index.html
Official contract address confirmation (MUST be linked from official website):
https://etherscan.io/tx/0x696ac8cbd0fda57ba0c14d4bc320c309ab5ae7c674c3b6b466f02cd216f7b91f
name: cryptoworld
ticker: cwd
decimal: 18

Description:
This token is to promote and reward the education of cryptocurrencies

**Comment by Kryptoniq** [comment]
Invalid token https://etherscan.io/token/0x1edaae241aa62e0f91491f133dcc3a7e729c73f0.
Sorry, we can't list your token.
