### ISSUE TITLE
Listing request - GNT

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#254]
Website: https://golem.network
Whitepaper: https://golem.network/doc/Golemwhitepaper.pdf
Description: Airbnb for computers. Rent your CPU/GPUs, get paid in cryptocurrency.

Contract address: https://etherscan.io/token/0xa74476443119A942dE498590Fe1f2454d7D4aC0d or simply https://etherscan.io/token/Golem
Symbol: GNT
Full Name: Golem
Decimals: 18

Link to confirm contract: https://blog.golemproject.net/golem-crowdfunding-contract-deployed-start-block-is-2607800-fcd1bb458d. Also, MEW's official twitter post in regards to GNT's contract: https://twitter.com/myetherwallet/status/796879382635646976

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=1655002
https://www.forbes.com/sites/laurashin/2017/07/10/how-crypto-tokens-work-a-close-look-at-golem
https://bitcoinexchangeguide.com/golem-network

**NOTE**: ForkDelta currently has 2, what I assume are placeholders, for GNT. One is called GNTW and the other GNTM. Both of those contracts with less than 100 txs each. I don't know what those things are supposed to be, but they should be deleted and replaced with this final contract.

**Comment by freeatnet** [comment]
GNT is not an ERC20 token, unfortunately, so we can't support it (see [previous discussion](https://www.reddit.com/r/ForkDelta/comments/7pwrxq/any_chance_of_adding_golem_gnt/)). GNTW is the wrapped and compatible version.
