### ISSUE TITLE
Listing DAPPT token

### ISSUE THREAD

**Issue by Johnlemon11** [forkdelta/tokenbase#2548]
**Token address:**
https://etherscan.io/dapp/0x386cabc0b14a507a4e024dea15554342865b20de

**Issuer's official website:**
https://www.dapp.com

**Description:** 
Dapp.com is an analytics-driven App Store for Decentralized Apps that allows everyone to discover, analyze and use all dapps easily. As a unified entry point for the future of decentralized apps, Dapp.com facilitate the growth of decentralized applications through a range of functions and products including the Dapp Store Wallet (DSW) and Multi-Blockchain Identity Network (MIN). DAPPT is a utility token that circulates within dapp.com's ecosystem for the access to the product and services. 

**A link to the official contract address confirmation:** 
https://www.dapp.com

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://medium.com/@dbcryptoteam/dapp-com-research-report-f01d42e9b678
2. https://cryptocalibur.com/dapp-com-review/

**Comment by freeatnet** [comment]
https://token.dapp.com/
