### ISSUE TITLE
Request Token Listing: Tokenomy (TEN)

### ISSUE THREAD

**Issue by oscardarmawan** [forkdelta/tokenbase#257]
Contract address:  0xdd16ec0f66e54d453e6756713e533355989040e4

Issuer's official website: Tokenomy.com

Official contract address confirmation (MUST be linked from official website): Tokenomy.com

A link to a third-party review or discussion of the token, like an established ICO review blog: https://www.crowdfundinsider.com/2018/02/127965-waves-says-going-big-southeast-asian-ico-market-tokenomy-partnership/

Description:  
Tokenomy ( TEN ) is platform that allows transform any products into tokens for crowdfunding, loyalty points, donation or other needs. Tokenomy’s mission is to provide access to anyone who wants to be connected with alternative funding networks and global innovation. Tokenomy is supported by largest South East Asia Cryptocurrency Exchange - Bitcoin.co.id that have more than 1 million users registered.

**Comment by Kryptoniq** [comment]
0xdd16ec0f66e54d453e6756713e533355989040e4, https://tokenomy.com

**Comment by freeatnet** [comment]
@oscardarmawan Thank you for your request! Tokenomy has been listed: https://forkdelta.github.io/#!/trade/TEN-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
