### ISSUE TITLE
ZION Token

### ISSUE THREAD

**Issue by onikonov** [forkdelta/tokenbase#258]
Contract address:0x574feb17d3B31c07B69Ce88478eA45A0846c06a7
Symbol: ZION
Full Name: ZION Token
Decimals: 4
Issuer's official website:http://ziontoken.tk

Official contract address confirmation (MUST be linked from official website):http://ziontoken.tk end of the site

A link to a third-party review or discussion of the token, like an established ICO review blog: 

Description: Token for helping others

**Comment by Kryptoniq** [comment]
1. No link to a third-party review or discussion of the token.
2. Description is too short
3. Only 3 token holders.
Sorry, we can't list you.
