### ISSUE TITLE
Meridian (MDN)

### ISSUE THREAD

**Issue by MeridianMDN** [forkdelta/tokenbase#259]
Contract address: 0x550879F1778b575DDC8EB2095fBC9f4783b5f2F6

Issuer's official website: https://mymdn.io

Official contract address confirmation (MUST be linked from official website): https://mymdn.io/terms/ 

A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2157860

Description: Built to rearrange Peer to Peer lending for the better, Meridian (MDN) is an ERC20 based digital asset that is designed to be used in combination with Bitcoin.  

Introduction Film: https://goo.gl/ixAzTx
Explainer Video: https://goo.gl/n7rkVf
Founder Interview: https://goo.gl/Xueeo3

Meridian Whitepaper: https://goo.gl/jqE7Me
Platform Demo: https://goo.gl/zgd8F6
Twitter: https://twitter.com/meridianmdn

Press: 
https://insidebitcoins.com/news/networks-new-corporations/73351
https://bitcoinwarrior.net/2017/09/the-blockchain-and-digital-collateral/
https://www.ccn.com/using-digital-assets-secure-bitcoin-loan/

Many thanks,

The Meridian Team
support@mymdn.io

**Comment by Kryptoniq** [comment]
0x550879f1778b575ddc8eb2095fbc9f4783b5f2f6, https://mymdn.io/

**Comment by freeatnet** [comment]
@MeridianMDN Thank you for your request! Meridian has been listed: https://forkdelta.github.io/#!/trade/MDN-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
