### ISSUE TITLE
Add Ethereumred ETHR

### ISSUE THREAD

**Issue by ethereumdz** [forkdelta/tokenbase#260]
addr: ''0x67335D5fCbD1e5319823Af8Eb179Faa1bd8D6fAd''
decimals: 8
description: Ethereum RED (ETHR) its a revolutionary coin who is changing the world as we know it.
Name: Ehereum RED.
TOKEN: ETHR

Token: ETHR
Name: Ethereum RED.
Contract Address: 0x67335D5fCbD1e5319823Af8Eb179Faa1bd8D6fAd
Website: http://ethereumred.io/
BITCOINTALK:
https://bitcointalk.org/index.php?topic=2966951.0
Twirrer: Twitter.com/ethereumred
Telegram : t.me/ethereumred
Email: info@ethereumred.io

**Comment by freeatnet** [comment]
@ethereumdz Your request satisfies the requirement for contract address proof and public discussion. However, as mentioned in #216, it is concerning that a reverse-search on your team photos yield multiple uses under different names. Perhaps, an update to team photos is in order? :)

Archived current state of page: http://archive.li/99Pp8
