### ISSUE TITLE
CoinTour Listing

### ISSUE THREAD

**Issue by CoinTourTeam** [forkdelta/tokenbase#261]
Contract address: 0x31705AA4933C106f3d15F64dF0eb70d8d37FC36E

Issuer's official website: http://www.cointour.net/

Official contract address confirmation (MUST be linked from official website): https://etherscan.io/token/0x31705aa4933c106f3d15f64df0eb70d8d37fc36e

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2450279.0

Description:
Our project can help you as quickly as possible and easily plan your vacation in advance. We are planning to connect the tourism industry to the blockchain in order to simplify travel, reduce their cost and make them safer.
We provide services to our customers, so we always focus on a special attitude to the service. The advantages of this project are security, transparency, speed and decentralization. Paying coins CoinTour (COT), you do not have to worry about high commissions when exchanging for cash, using an ATM or credit card.
We are doing everything possible to be proud of our services, and we also hope that COT will not only change people's notions of travel, but the world as a whole

**Comment by Kryptoniq** [comment]
0x31705aa4933c106f3d15f64df0eb70d8d37fc36e, http://www.cointour.net/

**Comment by CoinTourTeam** [comment]
Good day!
Received e-mail from you and want to ask about CoinTour listing. Do we have 
to give you any additional information?
Best regards
CoinTour team

**Comment by freeatnet** [comment]
@CoinTourTeam Do you currently deliver travel-related services?

**Comment by freeatnet** [comment]
@CoinTourTeam Thank you for your request! Coin Tour has been listed: https://forkdelta.github.io/#!/trade/COT-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
