### ISSUE TITLE
Delist Original Crypto Coin (OCC)

### ISSUE THREAD

**Issue by OriginalFoundit** [forkdelta/tokenbase#2610]
We are launching our own Blockchain and swapping from OCC to TUSC. Please remove OCC from your dex.

**Comment by freeatnet** [comment]
@OriginalFoundit We have stopped the orderbook for OCC. This means that users will still be able to access https://forkdelta.app/#!/trade/OCC-ETH to view their balance and withdraw tokens, but the orderbook will not longer accept or transmit (display) any orders.
