### ISSUE TITLE
Listing Request - ARTIS

### ISSUE THREAD

**Issue by ArtisTurba** [forkdelta/tokenbase#263]
Contract address: 0x082e13494f12ebb7206fbf67e22a6e1975a1a669

Issuer's official website: https://artisturba.com

Official contract address confirmation (MUST be linked from official website): https://artisturba.com found under the Artis section

A link to a third-party review or discussion of the token, like an established ICO review blog: 
+ https://myrtsblog.wordpress.com/2018/02/04/artis-turba-review-a-simplified-way-to-trade-cryptocurrencies-like-a-pro/
+ https://icobench.com/ico/artis-turba/ratings
+ https://www.trackico.io/ico/artis-turba/

Description: ARTIS is a token designed for the upcoming Artis Turba cryptocurrency exchange. Artis Turba aims to simply the trading process by providing an intuitive User Interface along with Buy, Sell and Hold signals generated from our own unique algorithm that reads trends and cycles. Furthermore the ARTIS Affiliate Reward Program or AARP will reward ARTIS holders by sharing revenue generated on the Artis Turba exchange pro rata to the ARTIS they hold.

**Comment by Kryptoniq** [comment]
0x082e13494f12ebb7206fbf67e22a6e1975a1a669, https://artisturba.com

**Comment by freeatnet** [comment]
@ArtisTurba Thank you for your request! ArtisTurba has been listed: https://forkdelta.github.io/#!/trade/ARTIS-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by ArtisTurba** [comment]
Thank you Arseniy and ForkDelta for the listing!! We look forward to
trading on your exchange and the founders have found it good to donate to
your project and it will be done in due time :)

Best Regards,
Artis Turba Team

artisturba.com  |  info@artisturba.com  |  Twitter
<https://twitter.com/artisturba>  |  Facebook
<https://facebook.com/artisturba>  |  Telegram <https://t.me/artisturba>
|
