### ISSUE TITLE
Request ERC20 Token PDT 

### ISSUE THREAD

**Issue by Assetbasefoundation** [forkdelta/tokenbase#264]
addr: '0xC212AAD6e325fb55A96757ff28a201AD128fA795'

Description: The AssetBase Foundation is a decentralized control foundation that holds the physical metal that backs it's tokens. AssetBase has moved on to the next phase of the project. All tokens are ERC20 Ethereum tokens. The PDT tokens are the AssetBase utility tokens, owning these tokens can get you Rewards, Discounts, and access to the virtual council. 

Name: Prime Donor Token.
TOKEN: PDT
Decimals: 5
Token: PDT
Name: Prime Donor Token,
Contract Address: 0xC212AAD6e325fb55A96757ff28a201AD128fA795
Website: https://foundation.assetbase.io/
Twitter: https://twitter.com/RealAssetBase
FaceBook: https://www.facebook.com/AssetBase.io
Code on Website: https://foundation.assetbase.io/silvercontract/
(It's the first code you see, not the second)
Third Party Rating: https://www.trackico.io/ico/assetbase/#tab-overview
Our project it rated a 4.8 out of 5.
https://bitcointalk.org/index.php?topic=2943055.0

Token Details:
PDT are the AssetBase utility tokens, owning these tokens can get you Rewards, Discounts, and Access to the AssetBase Foundation's virtual council. AssetBase gives 100% of transfer rewards to qualified PDT holders. Learn more at Foundation.AssetBase.io

**Comment by Kryptoniq** [comment]
#234  @freeatnet.

**Comment by freeatnet** [comment]
@Kryptoniq sorry, I think I missed this one. Did you need help here?

**Comment by Kryptoniq** [comment]
@Assetbasefoundation there are only 6 PDT token holders.
