### ISSUE TITLE
Asterion Space

### ISSUE THREAD

**Issue by Asterionspace** [forkdelta/tokenbase#265]
Contract address:

0x93713bf12ba1bb55edf94298a302a8fc9d118086
--
Name: Asterion World Token ( ATR )

Issuer's official website: https://www.asterion.space

Official contract address confirmation (MUST be linked from official website): https://www.asterion.space/faq

https://etherscan.io/token/0x93713bf12ba1bb55edf94298a302a8fc9d118086

A link to a third-party review or discussion of the token, like an established ICO review blog: 

https://asterionworld.slack.com

https://t.me/Asterionspace

https://bitcointalk.org/index.php?topic=1996941.0

Description:

Executive Summary
At Asterion Space, our vision and mission are to do something new and inventive today. We are creating and realizing a new strategy for the trajectory of humankind. The Asterion Space is for everyone who wants to be part of something new, something revolutionary. We accept all innovators with open arms. Here, we believe that Civilization has reached a collective understanding of the value of human capital, as well as the creative power of personality in the development of a new society.
 
At Asterion Space we believe that change cannot be achieved by fighting existing reality but by creating a newer, more efficient model. This understanding will be reflected in the new, post-industrial community basis of the future.
 
Asterion Space is an open-source initiative to build a virtual reality world. It uses blockchain technology to claim and transfer virtual land, keeping a permanent record of ownership and will enable to create virtual communities in the near future. A public Virtual Reality world should be ruled by open standards, shielded from the agenda of any central organization.
 
A public virtual reality world should be ruled by open standards, shielded from the agenda of any central organization. In Asterion, users are landowners and have full control over the content of their land. To make this possible, Asterion uses blockchain technology as a permanent, immutable record of ownership.
 
Blockchain Technology
Blockchain is the world's leading software platform for digital assets. Offering the largest production blockchain platform in the world, we are using new technology to build a radically better financial system. Our software has powered over 100m transactions and empowered users in 140 countries across the globe to transact quickly and without costly intermediaries. We also offer tools for developers and real-time transaction data for users to analyze the burgeoning digital economy.

Asterion Governance , Asterion Foundation

Asterion decentralized governance, will be mainly responsible for facilitating decision process within the Asterion Community.

With absence of central authority or a omnipotent group of developers or owners, the decision process within Asterion Community must be moderated through distributed mechanism.
Asterion is a platform, realized and deployed with a Smart Contract, that enables each owner of Asterion to vote in the process.

Asterion Tokens holders can contribute in this process. Prerequisite for voting is Proof of Trust, voluntary lock of part or whole balance of owned ATR Tokens. This way voters show their trust in the Token and the Community, before they participate in the voting process.
The core idea is to give a community a decentralized power to decide about all important issues in fair and safe manner.

Second aim of Asterion decentralized governance, is to enable raising funds for development of our virtual world and promotional purposes.

**Comment by Kryptoniq** [comment]
Your correct bitcointalk announcement link is https://bitcointalk.org/index.php?topic=1996941.0

**Comment by Asterionspace** [comment]
https://bitcointalk.org/index.php?topic=1996941.0

**Comment by Kryptoniq** [comment]
0x93713bf12ba1bb55edf94298a302a8fc9d118086, https://www.asterion.space/

**Comment by Asterionspace** [comment]
What next? We have a everything done. pls, let me know. THX AG

**Comment by Asterionspace** [comment]
Hello,

pls let me know what next steps for add coin to etherdelta and forkdelta. GitHub is done. Information complete.

Thank you.

**Comment by freeatnet** [comment]
@Asterionspace Thank you for your request! CodeCoin has been listed: https://forkdelta.github.io/#!/trade/CODECOIN-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
