### ISSUE TITLE
Debitum list request

### ISSUE THREAD

**Issue by leodavinci1** [forkdelta/tokenbase#267]
Contract address: 0x151202c9c18e495656f372281f493eb7698961d5

Issuer's official website: https://debitum.network

Official contract address confirmation (MUST be linked from official website):

A link to a third-party review or discussion of the token, like an established ICO review blog: https://www.youtube.com/watch?v=v_r2-LoQqi8 ico is discussed in this video

Description: Leveraging Blockchain technology to secure and distribute fiat investments to the SME world

**Comment by Kryptoniq** [comment]
Please provide an official link that verifies the contract address.

**Comment by Kryptoniq** [comment]
#299
