### ISSUE TITLE
withdraw CLR token failed

### ISSUE THREAD

**Issue by Salmawati1** [forkdelta/tokenbase#2677]
please check why the CLR token failed to withdraw, the token contrack address: 0x2396fbc0e2e3ae4b7206ebdb5706e2a5920349cb
Website: https://color-platform.org

![Screenshot_2019-08-31-02-34-12-26](https://user-images.githubusercontent.com/36433237/64045081-ff4ab900-cb9a-11e9-8647-56da3050f870.png)

**Comment by freeatnet** [comment]
@salmawati1 please post transaction hash in text form here as well

**Comment by Salmawati1** [comment]
0x1c491d00483f39f60afecff00a908692c879544dbaf5de50b7f7f12128a55c1e

Pada tanggal Sab, 31 Agt 2019 15.42, Arseniy Ivanov <
notifications@github.com> menulis:

**Comment by freeatnet** [comment]
@Salmawati1 Thanks! I can't seem to find anything immediately problematic. I've reached out to Color Coin team for a second pair of eyes on this.
