### ISSUE TITLE
Request to add ALPHA

### ISSUE THREAD

**Issue by alpha865** [forkdelta/tokenbase#268]
Contract address:  https://etherscan.io/token/0x3eb21f4678b352fcd8facf06b642c6720e04961b

Issuer's official website:  https://www.alpha-platform.com/

Official contract address confirmation (MUST be linked from official website):  https://www.alpha-platform.com/

A link to a third-party review or discussion of the token, like an established ICO review blog:   https://bitcointalk.org/index.php?topic=3025355.0

Description:

Alpha is an ERC20 token that can be earned on the Alpha platform.  Cryptocurrency users looking to learn about cryptocurrency, complete courses and are rewarded with Alpha tokens.  The Alpha platform is designed to teach people the basics, how to stay secure, how to trade and the vision behind the blockchain revolution.  Users will leave the courses fully equipped to interact with cryptocurrency.

**Comment by Kryptoniq** [comment]
0x3eb21f4678b352fcd8facf06b642c6720e04961b, https://www.alpha-platform.com/

**Comment by freeatnet** [comment]
@alpha865 Thank you for your request! CodeCoin has been listed: https://forkdelta.github.io/#!/trade/CODECOIN-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
