### ISSUE TITLE
DEZOS (DOS Token) Listing request

### ISSUE THREAD

**Issue by henrygregory** [forkdelta/tokenbase#2683]
**Token address:**
0xd68fbc1bde2d9ee90a19340685ba43bc3477f49e

**Issuer's official website:**
https://dezos.io

**Description:** 
The Dezos Blockchain solution is the key to secure data storage, the indexing of valuables, the creation of individualised insurance services and support in all ownership transfer processes. Dezos has a preventive effect and creates identity in things. The DOS token is used to verify all user transactions and thus grants access to the services.

**A link to the official contract address confirmation:** 
You can find the official address in the footer section of our official website https://dezos.io

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.wallstreet-online.de/nachricht/10575587-revolution-blockchain-sicherheit-persoenlichen-sachen/all
2. https://gallery.technet.microsoft.com/Smartphone-gestohlen-DEZOS-a94773f1
3. https://coin-hero.de/news/allgemein/dezos-revolutioniert-lost-found-management-weltweit-durch-kryptotechnik/
4. https://www.cryptologie.de/news/dezos-das-startup-moechte-die-art-vermoegensgegenstaende-zu-deklarieren-revolutionieren

**Comment by renehauri** [comment]
Hello,
Any news on this?

Thanks a lot.

Best regards
