### ISSUE TITLE
CODECOIN Listing Request

### ISSUE THREAD

**Issue by CodingMarket** [forkdelta/tokenbase#270]
Contract address: 0x9adaba9ffda15e3a043c907d390f645147eb532a

Issuer's official website: https://www.codecoinico.com/

Official contract address confirmation (MUST be linked from official website): https://www.codecoinico.com/

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://www.youtube.com/watch?v=zFpHWkrhsK4

Description:
Codingmarket is a decentralized coding service marketplace where people can buy coding services from other users, using cryptocurrencies and Codingmarket's native token - CodeCoin. 

 

There are millions of people have the idea of creating something on the internet, but lack the skills of coding. There are thousands of untrusted websites out there and most of them just ignore customers after receiving the payment and scam them of their money. 

 

Therefore, we are aimed at providing a trustless platform whereby users can request coding services from coders that can prove their works and skills through a public forum like GitHub.

Also, I noticed that there's already an existing token called CODE and our symbol happens to be CODE too. So we would like to use CODECOIN, which is the same as our token name, as our token symbol

**Comment by Kryptoniq** [comment]
Symbol: CODECOIN 

0x9adaba9ffda15e3a043c907d390f645147eb532a, https://www.codecoinico.com/

**Comment by freeatnet** [comment]
@CodingMarket Thank you for your request! CodeCoin has been listed: https://forkdelta.github.io/#!/trade/CODECOIN-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
