### ISSUE TITLE
LRC token contract upgrade

### ISSUE THREAD

**Issue by mfinestone** [forkdelta/tokenbase#2711]
**What token should be updated?**
LRC

https://etherscan.io/token/0xbbbbca6a901c926f240b89eacb641d8aec7aeafd

**What about the token should be updated?**

The token contract address has been updated in May of 2019. The correct LRC token address can be seen just above. The incorrect (deprecated) LRC token - which is still the one recognized by ForkDelta - can be seen here: please note Etherscan pointing towards/warning about the upgrade: https://etherscan.io/token/0xef68e7c694f40c8202821edf525de3782458639f

For a blog post explaining the upgrade, please see here: https://medium.com/loopring-protocol/lrc-token-contract-upgrade-scheduled-on-may-8th-2019-beijing-time-7cd6095ed4eb

Thanks very much in advance.

**Comment by mfinestone** [comment]
Hello Team. Any update on this? Just wouldn't want anyone else buying the incorrect token and being left empty handed. Please let me know if anything else is needed. Thanks

**Comment by freeatnet** [comment]
@freeatnet reminder
