### ISSUE TITLE
Listing ORIUM Token

### ISSUE THREAD

**Issue by OriumOfficial** [forkdelta/tokenbase#272]
Contract address:
0xd51e852630DeBC24E9e1041a03d80A0107F8Ef0C

Issuer's official website:
https://oriumcoin.com

Official contract address confirmation (MUST be linked from official website):
From official website to twitter channel:
https://twitter.com/OriumOfficial?s=07

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2851374

Description: [ABOUT ORIUM]
ORIUM is a decentralized and fair Ethereum-based online mobile game peer-to-peer, without a house edge.Able to play one player against other players instead of against a
 centralized game house.In order to place a bet, there must be another player willing to 
place same bet on the game room.For that  it is possible the player can adjust amount to bet or choose the game room suit for everyone.There can be public game room and 
private game room. Private game room is design for those who want to play each other who are close friend ,relatives and family.ORIUM ecosystem mobile game is purely depand on only random number generation,allowing players with more fairness playing experiences.Protocol features of matching bet will make more happy gaming and entertaining.

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has no reviews.

**Comment by JonathonDunford** [comment]
@OriumOfficial 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.

**Comment by OriumOfficial** [comment]
Hi Admin

Our bitcointalk thread has already review and active.Please process and
review of our ORIUM Token listing.

https://bitcointalk.org/index.php?topic=2851374

Thanks.
ORIUM
