### ISSUE TITLE
VAYLA Token VYA

### ISSUE THREAD

**Issue by VAYLAtoken** [forkdelta/tokenbase#2723]
Not needed anymore.

**Comment by Infinivi** [comment]
Buying your tokens with Credit Card on our exchange and growing your community 


——
Listing your Token on our new exchange :


New DEX launched ‪the 10th of December 2019‬

‪Https://Infinivi.io‬

We could initiate the listing of your token within 48hrs.

A great opportunity : Users can buy your crypto straight with Credit Card. This is absolutely new for a DEX.


Providing volume for your token :
We wish you could bring first volumes on your own token with a minimum of 100ETH to be automatically (with a dedicated bot where you have the only access) traded per pairs chosen.

Let me know if you wish to proceed. We will never ask for anything else.

We are only asking you to bring volumes for your own chosen pairs on a unique and dedicated bot for you only. We won’t have any access to it.


Best regards
Anthony
