### ISSUE TITLE
Listing of EU coin

### ISSUE THREAD

**Issue by kiara1968** [forkdelta/tokenbase#273]
Contract address: 

0x40caa728bb4bafa56f38a58623a12fbe6c90209d

Issuer's official website: eu-coin.net

Official contract address confirmation (MUST be linked from official website):
https://etherscan.io/address/0x40caa728bb4bafa56f38a58623a12fbe6c90209d

https://ethplorer.io/address/0x40caa728bb4bafa56f38a58623a12fbe6c90209d

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2768309.0

Description: The EUCoin will raise funds to make investments in ecological and humanitarian projects in the EU and its influence area. All projects where the institutions fail to deliver. Let's create a better world together, without political or economical motives, but with humanitarian and ecological purposes.

![eucoin0001](https://user-images.githubusercontent.com/34685888/36699726-d8702148-1b4d-11e8-874d-b95d1bd07e32.png)

**Comment by Kryptoniq** [comment]
I can't find your contract address on your website.

**Comment by kiara1968** [comment]
Hello

This has been added in the News part of the Get EU coin page (http://eu-coin.net/index.php?do=getcoin)

**Comment by kiara1968** [comment]
I have created the file, see pull request #371

**Comment by Kryptoniq** [comment]
#371
