### ISSUE TITLE
Paybchain Token Listing

### ISSUE THREAD

**Issue by Ibagaza** [forkdelta/tokenbase#2730]
**Token address:** 0x9D494A823Fc3E852f8fF92f36A05662A46de0381
--

**Issuer's official website:** https://paybchain.foundation/

**Description:** 

Paybchain blockchain is a decentralized operating system which can support industrial-scale decentralized applications. We are giving a preview to the future with Distributed Autonomous Organizations (DAO), complementary to EOSIO. With the new era of Web 3.0 technologies, organizations are now composed of both centralized business organizations managed by people and distributed automated platforms. Paybchain is fully decentralized without any central authorities.

**A link to the official contract address confirmation:** 

https://etherscan.io/token/0x9D494A823Fc3E852f8fF92f36A05662A46de0381

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://alexandriaviola.blogspot.com/2019/09/about-paybchain.html
2. https://www.forbes.com/sites/yoavvilner/2018/07/09/where-blockchain-meets-the-small-medium-and-large-businesses/

**Comment by Infinivi** [comment]
Buying your tokens with Credit Card on our exchange and growing your community 


——
Listing your Token on our new exchange :


New DEX launched ‪the 10th of December 2019‬

‪Https://Infinivi.io‬

We could initiate the listing of your token within 48hrs.

A great opportunity : Users can buy your crypto straight with Credit Card. This is absolutely new for a DEX.


Providing volume for your token :
We wish you could bring first volumes on your own token with a minimum of 100ETH to be automatically (with a dedicated bot where you have the only access) traded per pairs chosen.

Let me know if you wish to proceed. We will never ask for anything else.

We are only asking you to bring volumes for your own chosen pairs on a unique and dedicated bot for you only. We won’t have any access to it.


Best regards
Anthony
