### ISSUE TITLE
Please delist RHOC immediately: https://blog.rchain.coop/blog/2019/05/03/mitigating-the-barcelona-attack/

### ISSUE THREAD

**Issue by coininterview** [forkdelta/tokenbase#2735]
**What token should be updated?**
 
Please delist the RHOC from fork delta. This is Christian Peirson from the RChain Cooperative. Scammers are dumping millions of our tokens on your exchange.

We are very close to launching our main net. We will be resolving the issue at the time we create our new genesis block on RChain's Main net. Until then the RHOC is simply a placeholder token, we want all trading of the RHOC to stop so please delist RHOC immediately. 

RHOC Contract  address: https://etherscan.io/address/0x168296bb09e24a88805cb9c33356536b980d3fc5

**What about the token should be updated?**

http://rchain.coop/
https://blog.rchain.coop/blog/2019/05/03/mitigating-the-barcelona-attack/

**Comment by freeatnet** [comment]
Thanks for raising this with us!

I've added the RHOC (0x168296bb09e24a88805cb9c33356536b980d3fc5) to the stop list. This means that ForkDelta servers will no longer display, accept, or transmit orders for RHOC. The page is still up, and users will still be able to withdraw (or deposit, if they so desire) the token. Please note that this affects ForkDelta and systems that mirror ForkDelta, some similar DEXes have their custom order books and may continue displaying or accepting orders for RHOC.

Let me know if you have any questions or concerns.
