### ISSUE TITLE
Delist request: RHOC

### ISSUE THREAD

**Issue by dimworm** [forkdelta/tokenbase#2736]
**What token should be updated?**

Token address: 0x168296bb09e24a88805cb9c33356536b980d3fc5
symbol: RHOC

**What about the token should be updated?**

https://blog.rchain.coop/blog/2019/11/21/the-latest-on-rhoc-trading/

**Comment by freeatnet** [comment]
Thanks for raising this with us! Please see https://github.com/forkdelta/tokenbase/issues/2735#issuecomment-557054872.
