### ISSUE TITLE
TLGM

### ISSUE THREAD

**Issue by muhtasimabir** [forkdelta/tokenbase#2740]
**Token address:**

**Issuer's official website:**

**Description:** 

**A link to the official contract address confirmation:** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by Infinivi** [comment]
New DEX for a free listing - Limited offer

——-
Dear Sir or Madam,

We are supporting the launch of a new exchange on january 2020. 

We would like to propose you a free listing of your token on a pair « against » our own token. For free. 

If you request to trade against others currencies, we will check the performances after a first period of 30days. 

Let me know if any interests cause we are launching with a large promotional and marketing budget. 

It could be very good for all our token. 


Yours
Anthony
Send your request at Winances.com@gmail.com

**Comment by Infinivi** [comment]
> **Token address:**
> 
> **Issuer's official website:**
> 
> **Description:**
> 
> **A link to the official contract address confirmation:**
> 
> **At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

Listing your Token for free on our new exchange :


New DEX launched the 10th of December 2019

Https://Infinivi.io

We could initiate the free listing of your token.

We wish you could bring first volumes on your own token with a minimum of 100ETH to be automatically (with a dedicated bot where you have the only access) traded per pairs chosen.

Let me know if you wish to proceed. We will never ask for any listing fees. 

We are only asking you to bring volumes for your own chosen pairs on a unique and dedicated bot for you only. We won’t have any access to it.

Best regards
Anthony
