### ISSUE TITLE
Cereneum - Trustless, time-based Interest [Token Listing Request]

### ISSUE THREAD

**Issue by The-WRITTEN-SIGN** [forkdelta/tokenbase#2741]
**Token address:**
0xd9d4a7ca154fe137c808f7eedbe24b639b7af5a6

**Issuer's official website:**
https://www.cereneum.com/

**Description:** 
Launched on 6 June 2019, Cereneum is a time-based interest-bearing cryptocurrency for gamers. It features a cryptographic certificate of interest (CCOI) on the blockchain. Interest is paid to stakers who earn interest by staking Cereneum for set periods of time. Cereneum was distributed by airdrops to the following PoW cryptocurrencies: Bitcoin, Bitcoin Cash, Bitcoin SV, Ethereum, and Litecoin. It was launched by an anonymous team.

**A link to the official contract address confirmation:** 

https://www.cereneum.com/tutorial_addcer.html

You find the address at point 4 of the guide.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. Ivan on Tech - Cereneum Review https://youtu.be/vpNGCxuOFUU
2. DataDash Covers Cereneum, beginning at 18:34 https://youtu.be/mzCEGfg2lwM?t=1115
3. Town of Salem Announcement about Cereneum Partnership https://www.blankmediagames.com/partnership/

**Comment by Infinivi** [comment]
New DEX for a free listing - Limited offer

——-
Dear Sir or Madam,

We are supporting the launch of a new exchange on january 2020. 

We would like to propose you a free listing of your token on a pair « against » our own token. For free. 

If you request to trade against others currencies, we will check the performances after a first period of 30days. 

Let me know if any interests cause we are launching with a large promotional and marketing budget. 

It could be very good for all our token. 


Yours
Anthony
Send your request at Winances.com@gmail.com
