### ISSUE TITLE
Huptex

### ISSUE THREAD

**Issue by huptex** [forkdelta/tokenbase#2742]
**Token address:**
0x8b847669b2e5dd5101736e41da8ec38653065aeb

**Issuer's official website:**
https://huptex.io/

**Description:** 
HTX Ethernet side chain settlement relay network We will promote the landing of ethereum DAPP as an important infrastructure，Global Shared order pool, covering exchange exchange, leverage, all kinds of defi business, and all kinds of data matching business.

**A link to the official contract address confirmation:** 
https://huptex.io/

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. 
2.

**Comment by Infinivi** [comment]
New DEX for a free listing - Limited offer

——-
Dear Sir or Madam,

We are supporting the launch of a new exchange on january 2020. 

We would like to propose you a free listing of your token on a pair « against » our own token. For free. 

If you request to trade against others currencies, we will check the performances after a first period of 30days. 

Let me know if any interests cause we are launching with a large promotional and marketing budget. 

It could be very good for all our token. 


Yours
Anthony
Send your request at Winances.com@gmail.com
