### ISSUE TITLE
Request to list TAGZ5 Token

### ISSUE THREAD

**Issue by tagzgroup** [forkdelta/tokenbase#2747]
name: TAGZ5
symbol: TAGZ5
addr: 0x4d0425e47ee2d16b94c036715dfcb52a0cebc4dc
decimals: 8
description: TAGZ5 was forked from the original TAGZ token and designed to hold its value by tracking the Altcoin market.
website: http://tagz5.com
telegram: https://t.me/tagzexchange
coinmarketcap: https://coinmarketcap.com/currencies/tagz5/

**Comment by Infinivi** [comment]
Buying your tokens with Credit Card on our exchange and growing your community 


——
Listing your Token on our new exchange :


New DEX launched the 10th of December 2019

Https://Infinivi.io

We could initiate the listing of your token within 48hrs.

A great opportunity : Users can buy your crypto straight with Credit Card. This is absolutely new for a DEX.


Providing volume for your token :
We wish you could bring first volumes on your own token with a minimum of 100ETH to be automatically (with a dedicated bot where you have the only access) traded per pairs chosen.

Let me know if you wish to proceed. We will never ask for anything else.

We are only asking you to bring volumes for your own chosen pairs on a unique and dedicated bot for you only. We won’t have any access to it.


Best regards
Anthony
