### ISSUE TITLE
HEX token 

### ISSUE THREAD

**Issue by bitcoincidence2** [forkdelta/tokenbase#2748]
**Token address: 0x2b591e99afe9f32eaa6214f7b7629768c40eeb39**

**Issuer's official website:  https://hex.win/**

**Description:  Smart contract that transforms ETH into HEX token (also BTC value at date of snapshot). Staking simulates CD and creates profits from the unstaked pool. Quite popular project as the founder, Richard Heart, is quite known in the Kryptospace** 

**A link to the official contract address confirmation:  https://etherscan.io/token/0x2b591e99afe9f32eaa6214f7b7629768c40eeb39** 

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.blockchaincenter.net/hex/
2.https://www.castlecrypto.gg/bitcoin-hex-review/

**Comment by bitcoincidence2** [comment]
Important addition: I am in no way (except for some airdropped HEX tokens) to that project and i know about it's flaws but i just think it should be listed in forkdelta because it's popular.

**Comment by togoshige** [comment]
Hex Security Audit
https://hex.win/docs/HEX%20Security%20Audit%20by%20CoinFabrik.pdf 

Hex Financial/Economics Audit
https://hex.win/docs/HEX%20Economics%20Audit%20by%20CoinFabrik.pdf
