### ISSUE TITLE
Foxex Token Listing

### ISSUE THREAD

**Issue by foxextoken** [forkdelta/tokenbase#275]
Contract address: **0xf3c53c72e99035dea6211c3d3b53bfcc41a968b1**

Issuer's official website: **foxex.io**

Official contract address confirmation (MUST be linked from official website): **foxex.io**

A link to a third-party review or discussion of the token, like an established ICO review blog: 
**https://bitcointalk.org/index.php?topic=2810651.0**

Description: **Dedicated app for Foxex token, many outstanding features and unique design.**

**Comment by Kryptoniq** [comment]
1. The contract address cannot be found on the website
2. The bitcointalk announcement thread has insufficient information
