### ISSUE TITLE
HEX crypto

### ISSUE THREAD

**Issue by sknesebeck** [forkdelta/tokenbase#2750]
**Token address: 0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39

**Issuer's official website: hex.win

**Description:**  Hex. The first high interest blockchain certificate of deposit. Free for Bitcoin holders. Hex is designed to increase in value faster than anything else in history.

**A link to the official contract address confirmation:**  The official HEX address is 0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://www.castlecrypto.gg/bitcoin-hex-review/
2. https://nodesofvalue.com/hex-review/
3. https://icospotters.com/blog/what-is-bitcoinhex

**Comment by togoshige** [comment]
Hex Security Audit
https://hex.win/docs/HEX%20Security%20Audit%20by%20CoinFabrik.pdf 

Hex Financial/Economics Audit
https://hex.win/docs/HEX%20Economics%20Audit%20by%20CoinFabrik.pdf
