### ISSUE TITLE
LIRA listing request.

### ISSUE THREAD

**Issue by stefanogrilli** [forkdelta/tokenbase#276]
Contract address: 0xcf76f32EBE10139E4370127D5789Cdb0750d460D

Issuer's official website: www.lira.site

Official contract address confirmation (MUST be linked from official website): https://twitter.com/LIRA_ERC20/status/968265628887986182  (official Twitter account is linked in official LIRA homepage)

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2350353.0

Description: Lira National Supplementary Cryptocurrency Lira is an erc-20 token version of cryptocurrency based on Ethereum blockchain. Complementary currencies are 'systems of agreement' within a community. 
They promote long term planning by encouraging participants to invest in related productive activities. 
They encourage exchange and cooperation through the circulation of the commodity which is usually given an ethical value and ideal. Lira is a tribute to the Italian Lira that has been in disuse for about 10 years. Lira aims to celebrate Italy's past. 

![lira](https://user-images.githubusercontent.com/13124026/36701861-22a694e8-1b55-11e8-94fe-e0602a25ce09.jpg)

**Comment by Kryptoniq** [comment]
0xcf76f32ebe10139e4370127d5789cdb0750d460d, http://www.lira.site/

**Comment by freeatnet** [comment]
@stefanogrilli Thank you for your request! LIRA has been listed: https://forkdelta.github.io/#!/trade/LIRA-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by stefanogrilli** [comment]
Thank you so much.

Stefano Grilli
ᐧ

2018-02-28 22:00 GMT+01:00 Arseniy Ivanov <notifications@github.com>:
