### ISSUE TITLE
Update Zloadr ZDR Contract Address / Listing

### ISSUE THREAD

**Issue by zloadr** [forkdelta/tokenbase#2767]
**What token should be updated?**

ZDR / Zloadr

**What about the token should be updated?**

Contract Address

New ZDR contract address: 0xbdfa65533074b0b23ebc18c7190be79fa74b30c2
Old ZDR contract address: 0x71f1bc89f38b241f3ebf0d5a013fa2850c63a1d4

Here is the link to etherscan showing information relating to the change: https://etherscan.io/token/0xbdfa65533074b0b23ebc18c7190be79fa74b30c2

**Comment by zloadr** [comment]
Hi, it's been 2 weeks and we have heard nothing back. Pls could you let us know when we can expect our token to be updated.

Kind regards,

Zloadr Team

**Comment by zloadr** [comment]
Hi, any update?

**Comment by freeatnet** [comment]
@zloadr I don't actually see any public information on the token swap. Is there a link to a blog post, a tweet, anything?

**Comment by zloadr** [comment]
We did post it via our medium and twitter accounts back in August, but those accounts have been since deleted. You can find it pinned at the top of our Facebook account here: https://www.facebook.com/zloadrmedia/

**Comment by freeatnet** [comment]
@zloadr Will you be able to sign a message with `0x71f1bc89f38b241f3ebf0d5a013fa2850c63a1d4` owner account, `0x583b829dcdb5b31d4e446d23f3eea3559d3358f7`?

**Comment by zloadr** [comment]
Yes we will be able to.

**Comment by zloadr** [comment]
Will you be providing us with a message to sign or we do that ourselves?

**Comment by zloadr** [comment]
Can we move forward with the signing?

**Comment by samenrico** [comment]
Sorry for the delay. Didn't understand how to sign the address. It has been done now.

{
  "address": "0x583b829dcdb5b31d4e446d23f3eea3559d3358f7",
  "msg": "This address belongs 0x71f1bc89f38b241f3ebf0d5a013fa2850c63a1d4 Zloadr",
  "sig": "0xd054b0aeb9af1006ce478b845e5fd77a3191229f1c18543b486700d7d4dc91f72c9c41b51317071e9bf48a9f2f9b0460b885f0e8a94763e53c0d9ca66f9467af1c",
  "version": "2"
}

**Comment by samenrico** [comment]
{
  "address": "0x583b829dcdb5b31d4e446d23f3eea3559d3358f7",
  "msg": "This is the old ZDR address = 0x71f1bc89f38b241f3ebf0d5a013fa2850c63a1d4 - This is the new ZDR address = 0xbdfa65533074b0b23ebc18c7190be79fa74b30c2",
  "sig": "0x1a3f13a236e77e8e070d2e2ffccbde0657dc84c7c4817eed32d81947786b2b7127e978c16c88460aeb1a977f3734ba7da8b452694cfe6124e8f7f63503fc835d1c",
  "version": "2"
}

**Comment by samenrico** [comment]
When will you be updating our contract address as we have done everything asked from us?

**Comment by jebhera** [comment]
Download our official wallet from our site jeyenn.com for free 45000JNN airdrop. Email us back here with your jeyenncoin wallet address and we will send it to you

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zloadr** [comment]
All that has been asked has been done, please can our current contract address be updated?

**Comment by zloadr** [comment]
Contract address updated with CoinMarketCap 

https://coinmarketcap.com/currencies/zloadr/

Pls stop your users from buying and selling the old ZDR as it is no longer valid and not accepted within the Zloadr application.

**Comment by samenrico** [comment]
Hi, still waiting for our contract address to be updated. 

Thanks...
