### ISSUE TITLE
Bitcoin Advantage Mobile payments token listing

### ISSUE THREAD

**Issue by bitcoinadvantage** [forkdelta/tokenbase#277]
Contract address: 0x0b9e9c56ec900fbea85546444458d3c31ab60572
Decimals: 8
Symbol: BITAD
Total supply: 21 000 000

Issuer's official website: http://www.bitad.io/

Official contract address confirmation (MUST be linked from official website): http://www.bitad.io/

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=3028295.0

twitter: https://twitter.com/bitcoin_ad

email: info@bitad.io

Description: Bitcoin Advantage: mobile payments, all you need is a mobile number!

**Comment by Kryptoniq** [comment]
1. Your bitcointalk announcement thread has insufficient information.
2. There is only one token holder. 
3. Your website is inaccessible, we cannot make further verifications.

**Comment by JonathonDunford** [comment]
@bitcoinadvantage 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.
