### ISSUE TITLE
Listing PYRO Network (PYRO)

### ISSUE THREAD

**Issue by pyrodotnetwork** [forkdelta/tokenbase#2775]
**Token address:**
https://etherscan.io/token/0x14409b0fc5c7f87b5dad20754fe22d29a3de8217

**Issuer's official website:**
https://pyro.network

**Description:** 

The PYRO.NETWORK is a series of projects including but not limited to a social network, digital advertising network and blockchain gaming dApp platform which will utilize PYRO.

PYRO is an ERC20 deflationary token with a 5% burn rate on each transfer along with staking capabilities. For users that stake or “freeze" their PYRO, they will receive an amount of PYRO proportion to the amount of tokens frozen. From the 5% of PYRO that is burned, 2.5% is distributed among HODLers.

**A link to the official contract address confirmation:** 

Contract address is on the front page of our website.

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://steemit.com/deflationary/@mclaudiu/https-pyro-network-telegram-contest
2. https://www.youtube.com/watch?v=ory2SIky-Q4&t=191s
3. https://bitcointalk.org/index.php?topic=5215017.msg53541026#msg53541026
4. https://bitcointalk.org/index.php?topic=5215017.msg53542192#msg53542192

**Comment by pyrodotnetwork** [comment]
CoinGecko listing: https://www.coingecko.com/en/coins/pyro-network
CoinMarketCap listing: https://coinmarketcap.com/currencies/pyro-network/

**Comment by pyrodotnetwork** [comment]
@freeatnet any update for us?

**Comment by jebhera** [comment]
Download our official wallet from our site jeyenn.com for free 45000JNN airdrop. Email us back here with your jeyenncoin wallet address and we will send it to you

Sent from ProtonMail mobile

-------- Original Message --------
