### ISSUE TITLE
New ERC20 token listing - Ezydime

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#278]
Contract address: 0x553E18218Be0B07DE569Fe71b4258074C0E1D313

Issuer's official website: https://ezydime.com

Official contract address confirmation (MUST be linked from official website): https://ezydime.com/forms

A link to a third-party review or discussion of the token, like an established ICO review blog:  https://coinmarketalert.com/page/press-releases/ezydimecom-001-cent-token-pre-sale-commences-14-february-2018-437

Description: Ezydime is the official currency of the world's first crypto credit card, the Ezycard! Ezydime already has a large following after a successful ICO Pre-Sale and is currently listed on the Karsha Exchange.

**Comment by Ezydime** [comment]
Dear Krypton

Thanks for your swift response, please find attached out social networks.
-Reddit: https://www.reddit.com/user/Ezydime
-Insta: https://www.instagram.com/ezydime_/
-Telegram: https:??t.me/ezydimceo
-Facebook: https://www.facebook.com/Ezydime-1607654615982175/
-Twitter : twitter.com/EzydimeCEO

Im sure you will find all is in order.

Kind Regards
Blake Langelaar
Ceo Ezydime

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Ezydime** [comment]
Good Morning Krypton,

There really isn’t much public review, but after almost a month we have received nil bad feedback from our clients.

Kind Regards
Blake Langelaar
CEO Ezydime

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Kryptoniq** [comment]
Alternatively, you can provide a bitcointalk announcement thread link with reviews.

**Comment by JonathonDunford** [comment]
@Ezydime 

Reminder.

**Comment by Kryptoniq** [comment]
I will have to close this issue as per new listing guidelines.
No update for the past 22 days.
