### ISSUE TITLE
Listing Verified Ticker KOPI Token 

### ISSUE THREAD

**Issue by kopi-token** [forkdelta/tokenbase#2786]
**Token address:**
0x8CBC6d8E11a9cb59922278321E0E61Dfabc0D9F4

**Issuer's official website:**
https://www.kopiblockchain.io

**Description:** 
KOPI BLOCKCHAIN is the digitalization  of commodity coffee using blockchain technology,KOPI BLOCKCHAIN will facilitate transparency and reliability of (honest coffee) through the system from upstream to downstream that can be tracked to improve efficiency and quality coffee

**A link to the official contract address confirmation:** 
https://kopiblockchain.io/?page_id=1389
kopi erc contract : 0x8cbc6d8e11a9cb59922278321e0e61dfabc0d9f4

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://medium.com/@blockchainkopi/kopi-digitalization-coffee-commodities-on-the-blockchain-technology-d42bc3db372a?sk=caae08eb3502330ea930028233bdc453

**Comment by elhajary** [comment]
Good project backed up with coffee commodity[](https://info-menarik1.blogspot.com/2020/01/kopi-blockchain-digitalisasi-komoditas.html)  using blockchain technology

**Comment by elhajary** [comment]
[ Good project backed up with coffee commodity using blockchain technology](https://info-menarik1.blogspot.com/2020/01/kopi-blockchain-digitalisasi-komoditas.html)
