### ISSUE TITLE
Request to add OCTUS to your Exchange

### ISSUE THREAD

**Issue by octusnetwork** [forkdelta/tokenbase#279]
Contract address: **0x7e9d365c0c97fe5fcadcc1b513af974b768c5867**

https://ethplorer.io/address/0x7e9d365c0c97fe5fcadcc1b513af974b768c5867#transfers=6&tab=tab-holders&pageSize=100

Issuer's official website: http://octus.network/

Official contract address confirmation (MUST be linked from official website): http://octus.network/#token

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2912137

Description:

Octus (OTC) is the first and true cryptographic project for the massive and automated distribution of cryptocurrencies and tokens of the most popular and known blockchains such as Bitcoin, Ethereum, Bitshares, NEO, NEM, Waves, among others. 

Being a decentralized tool, that anyone can use it for the purpose of distributing cryptocurrencies to a list of wallets of their own choice, in an automated, controlled and secure way.

**Comment by JonathonDunford** [comment]
@octusnetwork 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.

**Comment by octusnetwork** [comment]
Sorry for the delay, we have been working hard to fill your requirements, our forum has been strengthened, we have received the support of all crypto https://bitcointalk.org/index.php?topic=2912137.0, on twitter we surpassed the 2000 followers, now we just need to distribute the airdrop and make the sale public, our project is already translated into traditional Chinese and soon they will know about the in the blockchain international conference held in Hangzhou International Exhibition Centre (the place of 2016 G20 Hangzhou summit): http://8btc.com/thread-131143-1-1.html. It is one of the most important blockchain conferences in China.

**Website**: http://octus.network
**Foro Bitcointalk**: https://bitcointalk.org/index.php?topic=2912137.0
**Twitter**: https://twitter.com/octusnetwork
**Weibo**: https://weibo.com/octus?is_hot=1

**Comment by JonathonDunford** [comment]
Reopened because of response from dev. 

@Kryptoniq take a second look.

**Comment by Kryptoniq** [comment]
According to Etherscan, there zero token holders, coupled with lots of failed (reverted) transaction.

**Comment by octusnetwork** [comment]
if we are doing a test with airdrops's software and we have had those results, but already this week all that will change, we will have hundreds of holders, as of Wednesday of the other week everything will change.

**Comment by octusnetwork** [comment]
Greetings wonderful DeltaFork team, we have already distributed part of the tokens to our holders, we need distribute more tokens to more holders, but that will be in the course of the week.

Contract address: 0x7e9d365c0c97fe5fcadcc1b513af974b768c5867

https://ethplorer.io/address/0x7e9d365c0c97fe5fcadcc1b513af974b768c5867#transfers=6&tab=tab-holders&pageSize=100.

Greetings waiting for an answer from you

**Comment by octusnetwork** [comment]
Greetings wonderful ForkDelta team, we have already distributed part of the tokens to our holders, we need distribute more tokens to more holders, but that will be in the course of the week.
Contract address: 0x7e9d365c0c97fe5fcadcc1b513af974b768c5867
https://etherscan.io/address/0x7e9d365c0c97fe5fcadcc1b513af974b768c5867
Website: https://octus.network
Bitcointalk Forum: https://bitcointalk.org/index.php?topic=2912137.0
Twitter: https://twitter.com/octusnetwork
Weibo: https://weibo.com/octus?is_hot=1
Greetings waiting for an answer from you

**Comment by octusnetwork** [comment]
This is our response.

we have already distributed part of the tokens to our holders, we need distribute more tokens to more holders, but that will be in the course of the week.

Contract address: 0x7e9d365c0c97fe5fcadcc1b513af974b768c5867

https://etherscan.io/address/0x7e9d365c0c97fe5fcadcc1b513af974b768c5867

Bitcointalk Forum: https://bitcointalk.org/index.php?topic=2912137.0

Twitter: https://twitter.com/octusnetwork

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x7e9d365c0c97fe5fcadcc1b513af974b768c5867, http://octus.network/

**Comment by octusnetwork** [comment]
Ok thanks

**Comment by octusnetwork** [comment]
What happen, When we will be in your exchange, we are in altilly.com and etherfly.com right now

**Comment by octusnetwork** [comment]
This is a new smart contract.

0x81a40ca2dd6a1dba572c9f6d2adde3eac7b98572

https://etherscan.io/address/0xfe7a8896fd510fc64777ba44f0230ad5e064c6f3#writeContract
