### ISSUE TITLE
AUREUS NUMMUS GOLD

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#2796]
Dear Madame / Dear Sir:

Please find below our application for listing on forkdelta. 

Thank you.
Kind regards, Sebastian + Yenifer + Jacob
 
**Token address:** 0x130914E1B240a7F4c5D460B7d3a2Fd3846b576fa

**Issuer's official website: www.an.gold

**Description:** 
The Aureus Nummus Gold (symbol: ANG) is a digital currency based on 1:1 allocated physical gold or gold equivalent. allocated gold means that for each 100,000 ANG that go into public circulation exactly 1 ounce gold bullion is put into a trust account. Holders /Investors of ANG may exchange their ANGs anytime back into gold.
 

**A link to the official contract address confirmation:**  Contract address is publicly visible on www.an.gold.  Follow this link: https://an.gold/portfolio/the-aureus-nummus-facts-numbers/

Confirmation of contract: https://etherscan.io/token/0x130914E1B240a7F4c5D460B7d3a2Fd3846b576fa

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  https://medium.com/@westerngeophysical/aureus-nummus-gold-b5be23f0afb4

2. https://www.reddit.com/user/CurrencyReview/comments/f56nv0/the_aureus_nummus_gold_quite_the_advancement_in/
--
 GENERAL PRESENTATION CAN BE FOUND HERE:
https://an.gold/wp-content/uploads/2019/08/AN_presentation_wd.pdf

SOME KEY FEATURES OF THE AUREUS NUMMUS GOLD:
- Freely tradable payment and savings instrument.
- Easy hassle-free purchase of tokens.
- Gold is collectively owned by token holders.
- Token holders can exchange anytime their tokens back into gold as they please.
- ANG is not mineable, forever fixed supply, -> no inflation.
- Value of ANG is tied by software to the price of bullion, ANGs can be exchanged into gold and vice versa on a forever fixed exchange rate of 100,000 ANGs= 1 oz gold bullion, independent from any value fluctuations on secondary markets. -> enhanced price stability.
- Technical development (first phase) and 15-language website complete.
We have spent more than 460,000 CAD of our own funds and one and half years of work in development and completion of phase 1.

NEXT STEPS FOR US AHEAD:

Here is what we have planned:

- We have a 850,000 CAD budget in private insider funds for a social media campaign, we intend to hire a full time professional social media expert, based out of Canada or the US, who will do nothing else than social media and raising the public awareness of the Aureus Nummus.  Road shows are a bit tricky regarding  securities law, we are still looking into that, but we believe that social media will be the key opinion maker. We have a team in India headed by Mr. Rakesh Patil who is working on producing text snippets, stories, articles and other written pieces, that will be fed after a quality control check in Canada into the social media environment by the social media manager.
Another key is to provide easy liquidity to token holders. We are registered with FINTRAC and FINCEN and have made our homework regarding the legal bounds within which we may move.
We will exchange anytime the Aureus Nummus token back into gold at the permanently fixed exchange rate of 100,000 ANGs = 1 ounce of gold bullion (independent of any price fluctuations on the secondary market).  We believe that liquidity is the key factor for distribution as investors are too often stuck with cryptotokens without being able to quickly exchange them into other means of payment like fiat or commodity.  For that reason the proceeds of the sale of the tokens will go into a trust account and not used for company expenditures. 
- Point number 2 requires with increasing volume also more public scrutiny and transparency. For which reason we are working on a stock exchange listing of the company Aureus Nummus Management Corporation. The stock exchange listing will also provide pay back of our expenses on the social media campaign and add additional funds for more social media marketing. 
- In the wake of the stock exchange listing we plan on issuing our own debit card in cooperation with Mastercard. That part is quite work intense as a couple of regulatory registrations would have to be completed, hence the decision to piggy back the debit card on to the stock exchange listing in order to streamline the regulatory workload.
We hope that this provides more clarity.

Thank you very much for your time.

Cheers, SEBASTIAN, YENIFER, JACOB
jtf@an.gold

**Comment by jebhera** [comment]
Download our official wallet from our site jeyenn.com for free 45000JNN airdrop. Email us back here with your jeyenncoin wallet address and we will send it to you

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Aureus-Nummus** [comment]
SORRY BUT YOUR COMMENT REFERS TO WHAT EXACTLY?

> Download our official wallet from our site jeyenn.com for free 45000JNN airdrop. Email us back here with your jeyenncoin wallet address and we will send it to you Sent from ProtonMail mobile
> […](#)
> -------- Original Message --------
>
