### ISSUE TITLE
New Coin Submission for WHALECOIN

### ISSUE THREAD

**Issue by GitHerDoneSon** [forkdelta/tokenbase#2797]
**Token address:**

0xc774f7c75d75a165233f97d97330af3a7c693fec

**Issuer's official website:**

https://whitewhalecoin.com/

**Description:** 

WHALECOINs purpose is a store of value. With only 100 coins in existence its value comes from it's extreme scarcity.

**A link to the official contract address confirmation:** 

https://etherscan.io/token/0x18c1ec370653063f1b6f28E7c5b313265165eF14

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1.  Project is only a couple months old, we are working on getting the word out now.
2.  Project is only a couple months old, we are working on getting the word out now.

**Comment by jebhera** [comment]
Download our official wallet from our site jeyenn.com for free 45000JNN airdrop. Email us back here with your jeyenncoin wallet address and we will send it to you

Sent from ProtonMail mobile

-------- Original Message --------
