### ISSUE TITLE
List Populous XBRL (PXT)

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#28]
As per https://twitter.com/deano358/status/957377596823515136.

> The PXT Token is going to be used for that exact value exchange. Monetzing data.
> 
> The Populous ecosystem will be able to provide existing financial systems incredible value on the transfer of data and micro-services that we see companies paying a huge premium for at the moment.
> 
> Companies will have to use said PXT Token in order for them to take advantage of things such as Credit reports and Analysis, or to fully utilise our API.

— https://medium.com/bitpopulous/populous-update-brace-yourselves-the-beta-is-coming-9926ef1acc9f

**Comment by deano233** [comment]
champion!
will be only exchange to list it or the first atleast!

**Comment by deano233** [comment]
also may have to list it as XBRL as PXT appears to be taken by some other unrelated coin, upto you guys how to name it.

cheers again this is great.

**Comment by deano233** [comment]
let us know when its listed you champions!

doing great work

**Comment by freeatnet** [comment]
Contract address: https://etherscan.io/address/0xc14830e53aa344e8c14603a91229a0b925b0b262

Source: https://twitter.com/bitpopulous/status/947465562552184832?lang=en

**Comment by freeatnet** [comment]
@deano233 It's up!
