### ISSUE TITLE
Kindly requesting for eeuro (eeu) listing

### ISSUE THREAD

**Issue by e-euro** [forkdelta/tokenbase#280]
Contract address:
0x6827a2fac3b4be1ba1f22d5802bb13c1ed7af405
Issuer's official website:
https://www.e-euro.trade
Official contract address confirmation (MUST be linked from official website):
https://etherscan.io/token/0x6827a2fac3b4be1ba1f22d5802bb13c1ed7af405

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=3029325.new#new

Description:

EEU IS A TOKEN INSPIRED BY EURO AND BRINGING ERC20 BASED TOKEN AS AN 
ALTERNATIVE TO EURO BASED ON ETHEREUM SMART CONTRACTS. OUR FULL ECOSYSTEM IS A REVOLUTIONARY ON-BLOCKCHAIN SOLUTION TO BRING EURO INTO BLOCKCHAIN TECHNOLOGY 
AND PROVISION OF A USEFUL BLOCKCHAIN SERVICE TO ENABLE ANONYMOUS TRANSACTION 
AND EASY TRACKING OF TRANSACTION ON THE NETWORK THROUGH ETHEREUM BLOCK EXPLORER

Token details

Token name- EEURO
Symbol - Eeu
Decimal - 8
Total Supply - 2,000,000 Eeu

Thank you

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread  has few reviews.

**Comment by e-euro** [comment]
Hello ,hope u are doing fine
Sorry for the inconvenience.
Please recheck for the review 

https://bitcointalk.org/index.php?topic=3029325

Thanks
