### ISSUE TITLE
listing a token

### ISSUE THREAD

**Issue by jhonpierre** [forkdelta/tokenbase#2817]
The contract address. : 0x9947a675cb4d4a19e020e1dd035955c0150b1e5e

website : https://covid19coin.xyz/

description :   Covgrow is a blockchain-based open source crowdfunding platform. Unlike other virtual worlds and social networks. Covgrow is not controlled by a centralized organization. There is no single agent with the power to modify the rules of the system. Covgrow use Covcoin, an ERC20 token based on the Ethereum technology.

**Comment by lomeliDev** [comment]
scam
