### ISSUE TITLE
Remove the EDO/ETH pair and add the PNT/ETH pair from forkdelta

### ISSUE THREAD

**Issue by gio1983** [forkdelta/tokenbase#2838]
Dear Decentralized Exchange ForkDelta,

Eidoo team appreciated being on Decentralized Exchange ForkDelta!
We appreciate a lot your hard work every day and efforts on the ForkDelta project!
We kindly ask you to remove the EDO pair from your platform considering that we are going to upgrade it replacing with a new ERC777 token called pNetwork Token (PNT).

The following info on this text will guide you through the details.

Information about OLD Contract address;
Old Contract address:
0xced4e93198734ddaff8492d525bd258d49eb388e

Symbol: EDO

Link to official explorer EtherScan: https://etherscan.io/address/0xced4e93198734ddaff8492d525bd258d49eb388e

It would be great if you could remove the old pair and add the new one (PNT).
NEW Contract address:
0x89ab32156e46f46d02ade3fecbe5fc4243b9aaed

Name: pNetwork Token

Symbol: PNT

Link to official explorer EtherScan: https://etherscan.io/address/0x89ab32156e46f46d02ade3fecbe5fc4243b9aaed#code

Issuer's official website:
https://p.network/

About our PNT token:
https://p.network/learn
https://p.network/docs/Token%20economy%20upgrade%20-%20DRAFT%20%28rev%205%29.pdf

Official contract address confirmation on the official website:
https://en.cryptonomist.ch/blog/eidoo/the-edo-to-pnt-upgrade-what-you-need-to-know-updated/

A link to a third-party review or discussion of the token:
https://www.binance.com/en/support/articles/4a5f8ba82c1c4e4fa10235bf2a48a666
https://www.bitfinex.com/posts/474

We already reached out to etherscan for the correct data to be displayed and for the token address to be verified. They will get back to us within a few days

Warm regards

**Comment by freeatnet** [comment]
@gio1983 I've stopped the market for `0xced4e93198734ddaff8492d525bd258d49eb388e`, meaning people ForkDelta servers will no longer accept or transmit orders for this token (users will, however, be able to withdraw tokens as needed). I'd like to verify that the new token is compatible. Please deposit and withdraw some PNT tokens using https://forkdelta.app/#!/trade/0x89ab32156e46f46d02ade3fecbe5fc4243b9aaed-ETH and post the transaction hashes here.

---
Notes: New contract address `0x89ab32156e46f46d02ade3fecbe5fc4243b9aaed` confirmed from https://en.cryptonomist.ch/blog/eidoo/the-edo-to-pnt-upgrade-what-you-need-to-know-updated/ (http://archive.is/hYl2F).
