### ISSUE TITLE
Add FinTab (FNTB) token

### ISSUE THREAD

**Issue by GrigoryMaltsev** [forkdelta/tokenbase#285]
Contract address: '0xbD4B60a138b3fce3584EA01f50c0908c18f9677A'
decimals: 8
name: FinTab
symbol: FNTB

Issuer's official website: https://fintab.io/

Official contract address confirmation (MUST be linked from official website): https://etherscan.io/address/0xbd4b60a138b3fce3584ea01f50c0908c18f9677a

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2193271

Description:
FinTab - the accounting system for cryptocurrency portfolios. FinTab helps to analyze the financial state of portfolio, the yield on a particular currency, and the whole portfolio. For funds, traders and investors. 

The role of FNTB tokens:
The FNTB token is a payment in the FinTab system and provides the following options:
- Access to the notification system in the service beta.fintab.io (before the “Pro” account release).
- Payment for “Pro” account in FinTab system.
- Payment for “Manage” account in FinTab system.
- Other services and features listed in the WhitePaper.

links:
- Email: mailto:info@fintab.io
- Telegram: https://t.me/fintab_chat_en
- Twitter: https://twitter.com/fintab_io
- Facebook: https://www.facebook.com/fintabservice
- Whitepaper: https://drive.google.com/file/d/1IawIwe0zJmhytA6PIs9S8wEo7gP6nyRL/view

notice: We would extremely happy if you add us on your exchange!

**Comment by Kryptoniq** [comment]
0xbd4b60a138b3fce3584ea01f50c0908c18f9677a, https://fintab.io/

**Comment by freeatnet** [comment]
@grigorymaltsev Thank you for your request! FinTab has been listed: https://forkdelta.github.io/#!/trade/FNTB-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by GrigoryMaltsev** [comment]
Thank you!
