### ISSUE TITLE
$IRA (PEERBANKS) Token

### ISSUE THREAD

**Issue by CryptVanWinkle** [forkdelta/tokenbase#286]
Contract address: 
0xcb73cef85b5d50a23a580919e72818fd2264c0f5
Issuer's official website:
https://peerbanks.org/

Official contract address confirmation (MUST be linked from official website): ??

 3P5JFuAHKWm65AGsCNXNNDvnPiB7MkUwEg4

A link to a third-party review or discussion of the token, like an established ICO review blog: 

https://icobench.com/ico/peerbanks

Description:
“Important asset, that works so that IRAs Companies can use it for handle Retirement accounts.”

**Comment by CryptVanWinkle** [comment]
I don’t understand what that means.

**Comment by CryptVanWinkle** [comment]
https://peerbanks.org/on-crowdsales/

**Comment by Kryptoniq** [comment]
Thanks for the link. Your contract address isn't there. Kindly make your contract address available on your website.

**Comment by CryptVanWinkle** [comment]
I don’t work for Peerbanks, I just bought a few tokens.

**Comment by Kryptoniq** [comment]
I'm closing this issue as per new listing guidelines.
No update for the past 15 days.
