### ISSUE TITLE
Coin Listing Request for Polaris Token (XPR)

### ISSUE THREAD

**Issue by nabilamrani** [forkdelta/tokenbase#287]
Contract address: 0x54a3f499f3e9ec22cbdec21bd38619561475da75

Issuer's official website: https://polarisxpr.com/

Official contract address confirmation (MUST be linked from official website): https://polarisxpr.com/#about

A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2738392.0

Description: Our token represents a share in a mining farm that we operate, and it is backed by the buy-back & burn process of XPR from the Polaris mining farm using its profits following the business model highlighted in our white paper:

https://polarisxpr.com/Polaris-White-Paper.pdf

We will be very happy if we get listed in ForkDelta. My name is Nabil Amrani & I'm part of the team behind this project. We're here if we need to do more to have XPR listed in your exchange.

Thank you very much!

**Comment by Kryptoniq** [comment]
Is PolarisXPR associated with https://cicerohome.io/ ?

**Comment by nabilamrani** [comment]
Hello! Cicero is a different project with a different token sale and different goals. We have been assisting and supporting Cicero & advising Eddie Harrison who is running it. But Polaris XPR & Cicero are two different projects.

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews.

**Comment by nabilamrani** [comment]
Hello! We didn't realize that having a decent number of reviews in the bitcointalk announcement is important. We talked to our community and we believe that we have enough reviews now. We will be very happy if XPR gets listed in ForkDelta and we're here if we need to do anything. Thank you for your time!

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x54a3f499f3e9ec22cbdec21bd38619561475da75, https://polarisxpr.com/

**Comment by nabilamrani** [comment]
Thank you very much! we truly appreciate the listing & we're looking forward to it!

**Comment by nabilamrani** [comment]
Hello dear. We would like to cancel/delay this listing request please. We had some issues with the current token contract address and as we are in the first days of our project we decided to change the contract address to a new one. We hope we will get listed with our new token address in ForkDelta by updating the info or re-applying, but for now since the token was not listed yet, we would like you to cancel this listing request and we will re-apply with the new contract address as soon as possible. We hope this doesn't cause any inconvenience for you and we are very sorry if it does. We are very happy to have been accepted in your exchange for listing, and we are looking forward to update/re-apply with the new token contract address. Thank you!

**Comment by freeatnet** [comment]
@nabilamrani Alright.
