### ISSUE TITLE
Please List SME Banking Platform (SME). Required details are included.

### ISSUE THREAD

**Issue by Ehiefua** [forkdelta/tokenbase#288]
Contract address: 0xdfe7351c291bc0e49079c62212587244e1c666ba

Issuer's official website: https://www.smeplatform.co/

Official contract address confirmation (MUST be linked from official website): https://www.smeplatform.co/token

A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2689091.0

Description: SME Banking Platform is designed to empower micro, small businesses and entrepreneurs in Sub-Saharan Africa with the financial services and digital technology they require to start and grow their businesses. The SME tokens powers especially the Remittance and Loyalty ecosystems

**Comment by Kryptoniq** [comment]
0xdfe7351c291bc0e49079c62212587244e1c666ba, https://www.smeplatform.co/

**Comment by Ehiefua** [comment]
Thank you. I will wait for your response.

**Comment by Ehiefua** [comment]
Hi. So what's next? We will be listed? Kindly say when please.
Thank you.

**Comment by freeatnet** [comment]
@Ehiefua Thank you for your request! SME has been listed: https://forkdelta.github.io/#!/trade/SME-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by Ehiefua** [comment]
Thank you for the listing. I will definitely consider donating.
Thank you
