### ISSUE TITLE
[Listing] NOKU Master Token 

### ISSUE THREAD

**Issue by ariahoshi** [forkdelta/tokenbase#290]
**Contract address:** 0x1fc52f1abade452dd4674477d4711951700b3d27

**Issuer's official website:** http://noku.io/

Official contract address confirmation (MUST be linked from official website):
https://www.noku.io/noku-token-contract-address/

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcoinexchangeguide.com/noku/
https://coinspectator.com/events/icos/noku-1820
https://www.coingecko.com/en/ico/noku

**Description:**
>- Noku is a multi-level project, it includes our NOKU platform, Web and mobile wallet and our “buy back” tokens: 
**_Tokens (ERC20) released so far are:_**
- NOKU (Master Token)
- EURN
The way our tokens work is:
- NOKU MASTER TOKEN is a one-time utility token. It can be pre-purchased with a cash discount, or exchanged in the market and can be used once in the Noku Platform. This means that when a Noku token is spent on the Noku Platform, Noku Company will not sell back it to the market. Noku fees are published on a monthly basis and may be calculated as a percentage of a transaction, as a fixed value or as a monthly fee. Noku services can be paid only with Noku Master Token.
- EURN is a token that is 1:1 with Euro fiat money, meaning that 1 EURN is always going to be 1 EURO (fiat)

**Links:**

- Github: https://github.com/noku-wallet/wallet
- Medium: https://medium.com/nokugroup
- Telegram: https://t.me/nokuofficial
- Twitter: https://twitter.com/NokuTeam
- BitcoinTalk: https://bitcointalk.org/index.php?topic=2518812.0
- Facebook: https://www.facebook.com/Noku-317917408638309/
- Linkedin: https://www.linkedin.com/company/27133020/
- Website: http://noku.io/
- Wallet: http://wallet.noku.io/
- Whitepaper: https://www.noku.io/Noku-White_Paper_Draft_0-9-5.pdf

addr: '0x1fc52f1abade452dd4674477d4711951700b3d27'
decimals: 18 
name: Noku Master Token
symbol: NOKU

**Comment by Kryptoniq** [comment]
0x1fc52f1abade452dd4674477d4711951700b3d27, https://noku.io/

**Comment by freeatnet** [comment]
@ariahoshi Thank you for your request! NOKU has been listed: https://forkdelta.github.io/#!/trade/NOKU-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
