### ISSUE TITLE
SmartOne Foundation: LEGAL Token Listing (Switzerland/ Liechtenstein)

### ISSUE THREAD

**Issue by u15776** [forkdelta/tokenbase#291]
Reto Stiffler
reto@smartone.legal
Zurich / Switzerland

Contract address:

0xe691b7ff3c9fddb8c2437412208ee4816aba7258
LEGAL
LGL
18

Issuer's official website:

https://smartone.legal/

Official contract address confirmation (MUST be linked from official website):

https://newsroom.smartone.legal/release-of-the-legal-token-f51b82ebf99f
(see at the bottom: "how to get your LEGAL token")

A link to a third-party review or discussion of the token, like an established ICO review blog: 

https://www.smithandcrown.com/sale/smartone-token-sale-regulatory-compliance-legal-services-automated-smart-contracts/

Description:

We provide legal services for the crypto community. Please see Smith and Crown article above.
The regulator (FMA Liechtenstein) approved our ICO which took place in November 2017.

**Comment by Kryptoniq** [comment]
Your website https://smartone.legal is not accessible at the moment.

**Comment by u15776** [comment]
Dear Krypton,

Thank you for coming back to us.
We had to switch the servers before the end of the month. The page was down for 1 day and is now live again.
Please go ahead with the listing process and let me know if you need more information.

Kind regards,

Reto



Reto Stiffler

Research & Development, Co-Founder

E: reto.stiffler@smartone.legal mailto:reto.stiffler@smartone.legal

W: https://smartone.legal

-------------------------------------------

SmartOne Foundation

Marktgass 11

9490 Vaduz

Liechtenstein

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xe691b7ff3c9fddb8c2437412208ee4816aba7258, https://smartone.legal

**Comment by freeatnet** [comment]
@u15776 Thank you for your request! REMME token has been listed: https://forkdelta.github.io/#!/trade/REM-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by u15776** [comment]
Dear Arseniy,

You are talking about REMME token. Ours is the LEGAL token (LGL). Could you please explain?

Thank you

Reto

**Comment by freeatnet** [comment]
@u15776 Sorry about that, issue numbers got mixed up. LGL is indeed listed, comment is updated.

**Comment by u15776** [comment]
Dear Forkdelta Team,

We realized that you stopped the trading of our LGL token. We have been working hard over the last months to create a Swiss standard for ICOs for which the LEGAL token will be used. Next week the contract with the software provider Horizon Globex (https://www.horizon-globex.com/investors/ohg-history/) will be signed and afterwards there will be lots of news. Also a second webpage and a new telegram chat will be started (the old telegram chat is full of spam).
Currently, the old webpage (smartone.legal) is password protected, but will be live again soon.

We ask you to keep the LGL listed. You will see much more trading of it in short time.


Thank you


Reto Stiffler

+41796164340

Zurich, Switzerland
