### ISSUE TITLE
MethNetwork

### ISSUE THREAD

**Issue by systerium** [forkdelta/tokenbase#292]
Contract address: 0xb39e9b7edf793611b615faa6e546ed68a23f7006

Issuer's official website: http://meth.pe.hu/

Official contract address confirmation (MUST be linked from official website): http://meth.pe.hu/#asset

A link to a third-party review or discussion of the token, like an established ICO review blog: https://t.me/methnetwork

Description:  The mETH token represents a license. Individuals need these tokens to create, run and interact with mETH Networks projects. mETH Network is a group of individuals dedicated to build trustworthy new blockchain community. We are aiming a self funded community by distributing the asset to the individuals supports the contribution process

**Comment by Kryptoniq** [comment]
1. Your team members are fake (case of identity theft).
2. No third-party review or discussion of the token.
Sorry, we can't list you.

**Comment by Kryptoniq** [comment]
For reference: All the team members photos were stolen from kraneshares.com (https://kraneshares.com/jonathan-shelon).
