### ISSUE TITLE
Diamonds are Forever 

### ISSUE THREAD

**Issue by daftoken** [forkdelta/tokenbase#2926]
**Token address:**

0x8fb1a59ca2d57b51e5971a85277efe72c4492983

**Issuer's official website:**
HTTPS://Daftoken.io 

**Description:** 

**A link to the official contract address confirmation:** 

https://bscscan.com/token/0x8fb1a59ca2d57b51e5971a85277efe72c4492983

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://coinsniper.net/coin/19151?__cf_chl_f_tk=Mx.gKiSPICuYpENlZjz1UBbvV94otGSs60zOZwN5gWI-1642283819-0-gaNycGzNB9E
2. https://nomics.com/assets/daf3-diamonds-are-forever

**Comment by zeroturningback** [comment]
Like to see this one approved
