### ISSUE TITLE
Blockhive - Hive tokens

### ISSUE THREAD

**Issue by shawnmrk** [forkdelta/tokenbase#293]
**Contract address:**

0x895f5d0b8456b980786656a33f21642807d1471c

**Issuer's official website:**

https://blockhive.ee/

**Official contract address confirmation (MUST be linked from official website):**

Theres none on the website, but it can veiw my contract through the ILP interface.

https://etherscan.io/token/0x895f5d0b8456b980786656a33f21642807d1471c?a=0x97ed9bb45e886a41ef4ec804d87a1b1d7cfdb4f3

**Heres my contract from the ILP interface:**

1. Loan
1.1. The Creditor shall grant a loan to Blockhive in an amount in EUR to be determined at the time when the Creditor transfers the loan amount to Blockhive (Principal Amount). Principal Amount shall be paid by the Creditor in ETH. Payments may only be made by the Creditor from the Creditor ETH contract address provided in this Contract. Payments from any other contract addresses or wallets will be disregarded by Blockhive and such payments will not be refunded. The conversion rate of Principal Amount to ETH shall be the ETH/EUR exchange rate applicable at https://coinmarketcap.com at the time when the Creditor’s ETH transaction receives the 12th confirmation in Ethereum network. In case the Creditor becomes a creditor of Blockhive through assignment of the claim, the Principal Amount shall be calculated in EUR, but the amount of the claim assigned to the Creditor.
1.2. Principal Amount shall be recorded on a database managed by Blockhive. The current balance of Principal Amount as well as history of the Principal Amount can be accessed here: https://ilp.blockhive.ee/contractHistory?address=0x97ED9BB45E886A41Ef4ec804D87A1B1d7cfDb4f3.
1.3. The Principal Amount shall be repaid to the Creditor by Blockhive in one payment on the day of expiry or termination of this Contract (Repayment Date). Principal Amount shall be calculated in EUR, but paid by Blockhive in ETH to the Creditor ETH contract address provided in this Contract. The conversion rate of Principal Amount to ETH shall be the ETH/EUR exchange rate applicable at https://coinmarketcap.com at the time of payment.
1.4. Blockhive shall pay to the Creditor interest amounting to 20% of the operating profit of Blockhive as provided in the final annual accounts of Blockhive for the fiscal year immediately preceding the interest payment year.
1.5. Interest will be paid to the Creditor at the beginning of each year until Repayment Date. The interest payment date shall be announced by Blockhive at least 2 (two) weeks in advance. Loan interest shall be paid by Blockhive in ETH to the Creditor ETH contract address provided in this Contract. The conversion rate of interest to ETH shall be the ETH/EUR exchange rate applicable at https://coinmarketcap.com at the time of payment.

2. Assignment of Contract
2.1. Creditor may assign its claim against Blockhive at any time either in full or in part provided that the third party to whom the claim is assigned (Assignee) agrees to be bound by the terms and conditions included in this Contract and any terms and conditions applicable to the Tokens and the Assignee signs a loan contract on these terms with Blockhive.
2.2. With the assignment of the claim all accessory rights (including any unpaid interest accrued prior to the assignment) are transferred to the Assignee.
2.3. After the Principal Amount is fixed, tokens (Tokens) are issued to the Creditor in an amount corresponding to the Principal Amount.
2.4. Tokens are cryptographic devices that constitute the agreed form of certificate that the Creditor issues to an Assignee to certify that the Creditor’s claim is assigned in full or in part. Every token represents 0.045 EUR of the Principal Amount. The Parties agree that if an Assignee notifies Blockhive about the assignement of the Creditor’s claim and provides Tokens to ETH contract address notified to Blockhive, Blockhive shall assume that the Creditor has assigned the claim to this Assignee holding the Tokens in an amount corresponding to the number of Tokens held.
2.5. Blockhive shall make information about the assignment of the claim available to all creditors who have provided loans to Blockhive under the same terms. Other creditors shall be entitled to acquire all offered claim, free and clear of any encumbrances, under the terms of the assignment of the claim, by delivering to Blockhive an irrevocable notice within 7 days from the day Blockhive has made information about the assignment of the claim available to creditors (Notice).
2.6. Creditors who have duly submitted Notices shall be entitled to acquire a part of the claim pro rata to their share of the total amount of loan given to Blockhive.
2.7. The assignment of the claim is deemed to have occurred in respect of Blockhive from the moment that the Assignee notifies Blockhive about the assignment, provides Tokens to ETH contract address notified to Blockhive and signs a loan contract with Blockhive regardless of whether the claim has actually been assigned to the Assignee. From the moment that the assignment occurs, Blockhive shall regard the Assignee as the new creditor and the Creditor shall cease to be a creditor with regard to the assigned part of the Principal Amount.

3. Term and Termination
3.1. This Contract comes into effect upon signing by both parties and is valid until 25th January 2028. The Contract will be automatically extended for another 10 (ten) year period unless a notice is given at least 3 (three) month prior to the expiry date by one of the Parties to the other Party indicating a wish to terminate the Contract. The Contract period may be extended several times.
3.2. This Contract may be terminated only on the grounds provided in this Contract.
3.3. Blockhive shall have the right to terminate this Contract with immediate effect if another creditor uses his/her priority right and that other creditor becomes a creditor of Blockhive instead of the Creditor.
3.4. This Contract terminates automatically if the Creditor has fully assigned his/her claim against Blockhive and the Assignee has concluded a loan contract with Blockhive.

4. Entire Agreement, Governing Law and Jurisdiction
4.1. This Contract constitutes the entire agreement between the Parties and supersedes and extinguishes all previous drafts, agreements, arrangements and understandings between them, whether written or oral, relating to this subject matter.
4.2. This Contract is governed by Estonian law.
4.3. Any dispute arising from this Contract shall be settled in Harju Maakohus, Tallinn, Estonia.

**A link to a third-party review or discussion of the token, like an established ICO review blog:** 
https://icobench.com/ico/blockhive

Description:
blockhive creates practical and innovative solutions for businesses in the form of partnership, helping them unlock new markets and untapped opportunities as part of our ambition to create a win-win outcome. We also incubate projects that have the potential to benefit from blockchain technology.

**Comment by Kryptoniq** [comment]
Please provide an official link that verifies the contract address.

**Comment by shawnmrk** [comment]
https://blog.blockhive.ee/how-we-have-failed-and-how-we-are-getting-back-up-f6fc1fb1f7af

Link to etherscan is highlighted!

[image1.png]

Sendt fra min iPhone

Den 28. feb. 2018 kl. 08.38 skrev Krypton <notifications@github.com<mailto:notifications@github.com>>:


Please provide an official link that verifies the contract address.

**Comment by shawnmrk** [comment]
https://blog.blockhive.ee/how-we-have-failed-and-how-we-are-getting-back-up-f6fc1fb1f7af

Found under “For disclosure“
Here are the details of Hive tokens

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x895f5d0b8456b980786656a33f21642807d1471c, https://blockhive.ee/

**Comment by freeatnet** [comment]
@shawnmrk Thank you for your request! Hive token has been listed: https://forkdelta.github.io/#!/trade/HIVE-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by shawnmrk** [comment]
https://etherscan.io/tx/0xde33ee6808d0db53875cdc15a79bf142e6152ce60abd4e07b0684a05870e864d

I get errors every time i try to deposit hive tokens to Forkdeltas smart contract. Even tried with a transaction cost off 20$

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

________________________________
Fra: Arseniy Ivanov <notifications@github.com>
Sendt: Tuesday, March 6, 2018 5:38:20 PM
Til: forkdelta/tokenbase
Cc: shawnmrk; Mention
Emne: Re: [forkdelta/tokenbase] Blockhive - Hive tokens (#293)


@shawnmrk<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshawnmrk&data=02%7C01%7C%7C0d3e01e6c2924438cf5608d58380ce95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636559511595785475&sdata=XUTUPHv3WwERdRxj8kf0rA8RbZekkXc%2BbAxm9ZgzrlI%3D&reserved=0> Thank you for your request! Hive token has been listed: https://forkdelta.github.io/#!/trade/HIVE-ETH<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforkdelta.github.io%2F%23!%2Ftrade%2FHIVE-ETH&data=02%7C01%7C%7C0d3e01e6c2924438cf5608d58380ce95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636559511595785475&sdata=QhCyFvXj1KUE0Nda%2F2EEy9MjFxcNuSYBVgXoHPfBTmA%3D&reserved=0>

If you like our project, please consider donating<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforkdelta.github.io%2Fabout%2F%23donate&data=02%7C01%7C%7C0d3e01e6c2924438cf5608d58380ce95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636559511595785475&sdata=FvKbG8W9F4%2B%2F%2FuBpPEDyB4X0iq%2BFVhEpSPsFjzO6RzA%3D&reserved=0>. Your donations keep the project running and are always appreciated.

**Comment by freeatnet** [comment]
@shawnmrk Damn. Looks like HIVE uses an incompatible ERC223 implementation. Unfortunately, with the token source code not published, there was no way to check ahead of time.

**Comment by shawnmrk** [comment]
Yeah, that kinda sucks. I guess you can delist it then 😃

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows 10

________________________________
Fra: Arseniy Ivanov <notifications@github.com>
Sendt: Tuesday, March 6, 2018 7:32:50 PM
Til: forkdelta/tokenbase
Cc: shawnmrk; Mention
Emne: Re: [forkdelta/tokenbase] Blockhive - Hive tokens (#293)


@shawnmrk<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshawnmrk&data=02%7C01%7C%7C31bc0735cde84c0f828608d58390ab97%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636559579730150316&sdata=RMUEaJae%2FM1BBmjj5Jn%2F6Q4MfFse0L1v3LOBLjyetIs%3D&reserved=0> Damn. Looks like HIVE uses an incompatible ERC223 implementation. Unfortunately, with the token source code not published, there was no way to check ahead of time.
