### ISSUE TITLE
$GXVC Geneviève VC 

### ISSUE THREAD

**Issue by punctumm** [forkdelta/tokenbase#294]
![kbmrvgkq_400x400 1](https://user-images.githubusercontent.com/7884959/36728542-5d95adfc-1bc1-11e8-95e2-ff99a9d06887.jpg)

Contract address: 0x22F0AF8D78851b72EE799e05F54A77001586B18A

Issuer's official website: https://genevieveco.io

Official contract address confirmation (MUST be linked from official website): https://genevieveco.io/#token

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://cryptocoinconnection.com/genevieve-review.pdf
https://icomarks.com/ico/genevieve-vc1518213868

Description:
Access to funding for small enterprises in less economically developed and newly industrialized countries is extremely limited. GXVC is a venture capital cryptocurrency that offers exposure of equity to its token holders. Token sale proceeds are injected as seed capital into small businesses. Investment ventures are selected democratically from shortlist by token holders by way of Geneviève’s DAO. Investment returns are proportionally distributed quarterly to all token holders as dividends.

**Comment by Kryptoniq** [comment]
0x22f0af8d78851b72ee799e05f54a77001586b18a, https://genevieveco.io/

**Comment by Kryptoniq** [comment]
0x22f0af8d78851b72ee799e05f54a77001586b18a, https://genevieveco.io/

**Comment by freeatnet** [comment]
@punctumm Thank you for your request! Genevieve VC has been listed: https://forkdelta.github.io/#!/trade/GXVC-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
