### ISSUE TITLE
Please List 888 Lucky Charm Tokens (888). Required details are included

### ISSUE THREAD

**Issue by 888-Token** [forkdelta/tokenbase#295]
Request to add the 888 token to your Exchange

   1 The contract address.
Contract Address: 0x87d9bF506B434e9973cb0e6183DA7A50A16796b2

   2 A link to the token issuer's official website.
Website: https://888token.xyz

   3 A couple sentences for token description.
888 Lucky Charm Tokens | limited to 888M Tokens
The 888 Lucky Charm Tokens is one of the first Ethereum (Fully ERC20 compatible) tokens created by the Minereum Token Service. 

   4 A link to an official page confirming the contract address.
https://etherdelta.com/#0x87d9bf506b434e9973cb0e6183da7a50a16796b2-ETH

	Email: info@888token.xyz
	Twitter: https://twitter.com/888_token
	Website: https://888token.xyz
	Reddit: https://www.reddit.com/user/888-token/
	Github: https://github.com/888-Token/888Token
	name: 888 Lucky Charm Tokens
	symbol: 888
	decimals: 18

**Comment by Kryptoniq** [comment]
Provide a link to a third-party review or discussion of the token.

**Comment by JonathonDunford** [comment]
@888-Token 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.
