### ISSUE TITLE
Please list OceanSafe Token

### ISSUE THREAD

**Issue by oceansafe** [forkdelta/tokenbase#296]
-->

Contract address: 

Contract address: 0x827d41446a2cb012d3011b94f525d6c46b32866d
Symbol: OSC
Decimals: 9
Total Supply: 25 000 000 OSC

Issuer's official website: oceansafe.io

Official contract address confirmation (MUST be linked from official website): oceansafe.io

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2403245.0

Description: Crypto advertisement on blockchain

<!--

**Comment by Kryptoniq** [comment]
1. Only two token holders.
2. Insufficient reviews on your bitcointalk announcement thread.

**Comment by JonathonDunford** [comment]
@oceansafe 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.
