### ISSUE TITLE
Listing request - Electronic Platinum [EPL] 

### ISSUE THREAD

**Issue by Cryptofeverrr** [forkdelta/tokenbase#298]
**Contract address**: 0xa4ef5964F146D2526c51Fc40CaA244E45Edce136

https://etherscan.io/token/0xa4ef5964f146d2526c51fc40caa244e45edce136
https://ethplorer.io/address/0xa4ef5964f146d2526c51fc40caa244e45edce136

**Issuer's official website**: [www.electronicplatinum.io](url)

**Official contract address confirmation**:
www.electronicplatinum.io/ First page 'Introduction' You can check the contract adress.

**A link to a third-party review** :  "Forbes France"
https://www.forbes.fr/finance/blockchain-et-or-un-alliage-parfait/
"At the end of the article"

**Description**:

**Symbol** : EPL
**TOKEN CONTRACT ADDRESS**:  0xa4ef5964F146D2526c51Fc40CaA244E45Edce136
**Décimales** : 8
**Total Supply** : 20 000 000

**Abstract**

                  “ Reduce the boundaries between the real and the virtual ”

 
The aim of this project is to implement a technological revolution, which will create a bridge between the real economy and the new economy, often mistakenly called a ‘virtual economy’. Indeed, what is identified as ‘virtual’ is already present in our daily lives. EPL's main objective is to value platinum in our currency, the metal in which we have as much confidence as gold, if not more.
 
Combined with the Blockchain technology, platinum will allow all owners of EPL to keep a foot in the real world while taking advantage of the cryptocurrency market. This assurance of the concrete material and the possibility to pay our purchases with it is at the heart of our project. 

After extensive analysis and research, we have unequivocally opted for platinum. Unlike gold and silver, platinum does not suffer from demand-related variations. As an indication, it can be noted that this volume of variance is equivalent to 10% of the demand for silver and 1% of the demand for gold.

Its low exposure makes it an asset as strong as it is stable, and above all, particularly underestimated by the general public. Its strong potential (giving back power to this unique metal in the world) is a lever as safe as it is concrete. This metal will not oxidize, it is considered essential in times of war and peace, and it will be exhausted by 2064.
 
Blockchain technology allows us to make this metal accessible and usable. This is why we created EPL: to generate an alliance between a very precious metal and the guarantee of foolproof stability (crash, illusory variations, etc.) with a very real stock. 100% Swiss.

**Comment by Kryptoniq** [comment]
Please, provide link to a more detailed review or discussion of the token.

**Comment by Cryptofeverrr** [comment]
Hello Kryptoniq! 
Here is a link for an article about EPL that was published the 10th of january : [](http://buntosam.blogspot.fr/2018/01/electronic-platinum-epl.html )
And here you can find our official BitcoinTalk thread and the discussion around EPL. : [](https://bitcointalk.org/index.php?topic=2723915.0)

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xa4ef5964f146d2526c51fc40caa244e45edce136, https://www.electronicplatinum.io

**Comment by freeatnet** [comment]
@Cryptofeverrr Thank you for your request! ELECTRONIC PLATINUM has been listed: https://forkdelta.github.io/#!/trade/EPL-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
