### ISSUE TITLE
Please List Debitum (DEB)

### ISSUE THREAD

**Issue by rdenke** [forkdelta/tokenbase#299]
Contract address: 0x151202c9c18e495656f372281f493eb7698961d5

Issuer's official website: https://debitum.network/

Official contract address confirmation (MUST be linked from official website): https://blog.debitum.network/quick-information-important-know-crowdsale/

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2321064.0

Description:
Debitum Network will be an ecosystem where participants from all around the world will perform separate steps of the financing process. Debitum's purpose is to provide access to the lucrative SME capital market for everyone. Today, investments in SME debt are profitable, relatively safe, and yet not easy to get engaged into. Debitum Network will directly face and solve this problem.

**Comment by freeatnet** [comment]
@rdenke Unfortunately, Debitum DEB is not compatible with the current trading contract. We're working to resolve this issue.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/smart_contract
