### ISSUE TITLE
Add Ants Reloaded (ANTS) token

### ISSUE THREAD

**Issue by AntsReloaded** [forkdelta/tokenbase#300]
ANTS RELOADED 
SYMBOL: ANTS
DECIMALS: 8

 
Contract address: https://etherscan.io/address/0x1cCc29f9CEd9d1a5cE81a7262EAC8FcD7ecA5788
https://ethplorer.io/address/0x1ccc29f9ced9d1a5ce81a7262eac8fcd7eca5788

Issuer's official website: https://www.antsreloaded.com/

Official contract address confirmation (MUST be linked from official website): https://www.antsreloaded.com/ (How can  i add ANTS token to my wallet)

A link to a third-party review or discussion of the token, like an established ICO review blog: 
https://bitcointalk.org/index.php?topic=2792318.0

Description:
ANTS RELOADED is the first decentralized and transparent payment system for gaming consoles managed by an Ethereum smart contract.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.

**Comment by freeatnet** [comment]
@AntsReloaded Thank you for your request! ANTS Reloaded has been listed: https://forkdelta.github.io/#!/trade/ANTS-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
