### ISSUE TITLE
Lendconnect

### ISSUE THREAD

**Issue by paynonymous** [forkdelta/tokenbase#301]
Contract address: https://etherscan.io/address/0x4558a75e47f11c0f4bb8ff6c736deeac62febb15

Issuer's official website: lendconnect.io

Official contract address confirmation (MUST be linked from official website):

A link to a third-party review or discussion of the token, like an established ICO review blog: 

Description:
LENDCONNECT LCT HAS ITS OWN LENDING AND TRADE PLATFORM IT IS COMMING ONLINE 2 MARCH 2018

**Comment by paynonymous** [comment]
T.me/lendconnectofficial

Telegram group

**Comment by Kryptoniq** [comment]
1. The website lendconnect.io belongs to the real lendconnect. 
2. The token address you provided   is fake and has only two token holders. The real Lendconnect has over 1,865 token. 
This simply means you are trying to defraud others. 
Sorry, we can't list you.

**Comment by Kryptoniq** [comment]
The real lendconnect contract address; https://etherscan.io/token/0x05c7065d644096a4e4c3fe24af86e36de021074b.
