### ISSUE TITLE
Ethereum soft

### ISSUE THREAD

**Issue by paynonymous** [forkdelta/tokenbase#302]
Contract address:https://etherscan.io/token/0x4461778cc8bc26abb611ff9cdb2c8248ba128caf

Issuer's official website: www.ethereumsoft.co

Official contract address confirmation (MUST be linked from official website): www.ethereumsoft.co

A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2617352.0

Description:
Ethereum soft is based on ethereum blockchain and is much faster and safer than other erc20 coins

**Comment by paynonymous** [comment]
Pleas add them i love this coin

**Comment by Kryptoniq** [comment]
The website and social media handles are gone.
My research on the bitcointalk thread shows that the project ended being a scam (https://bitcointalk.org/index.php?topic=2617352.900).

**Comment by Kryptoniq** [comment]
You created a deceptive issue on #301.
Now this.
@freeatnet can you please ban this user from this repo? He is creating fraudulent/deceptive  issues.

**Comment by freeatnet** [comment]
@Kryptoniq Done. Good digging!
