### ISSUE TITLE
Request for listing new token ( PAL)

### ISSUE THREAD

**Issue by patidarmanoj10** [forkdelta/tokenbase#304]
Contract address: 0x562952c749d05dca4cd004489a153c7ee7e58240

Issuer's official website: https://www.pally.co/

Official contract address confirmation (MUST be linked from official website): https://etherscan.io/token/0x562952c749d05dca4cd004489a153c7ee7e58240
https://bitcointalk.org/index.php?topic=2100229

A link to a third-party review or discussion of the token, like an established ICO review blog:  https://medium.com/@Pally 
https://bitcointalk.org/index.php?topic=2100229

Description:
Pally is the first decentralised social travel ecosystem in the world. Our technology enables travellers to create friendships and access authentic experiences in new cities through local people - using direct peer-to-peer payment

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.

**Comment by freeatnet** [comment]
(THIS IS A TEST)

[![](https://api.gh-polls.com/poll/01C85RR0N34CBTHGJRGJC9EZYW/List%20PallyCoin%20(PAL))](https://api.gh-polls.com/poll/01C85RR0N34CBTHGJRGJC9EZYW/List%20PallyCoin%20(PAL)/vote)
[![](https://api.gh-polls.com/poll/01C85RR0N34CBTHGJRGJC9EZYW/Do%20not%20list%20PallyCoin%20(PAL))](https://api.gh-polls.com/poll/01C85RR0N34CBTHGJRGJC9EZYW/Do%20not%20list%20PallyCoin%20(PAL)/vote)

**Comment by JonathonDunford** [comment]
Moved to: https://github.com/forkdelta/tokenbase/pull/378
