### ISSUE TITLE
Listing request - EDU

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#306]
Website: https://tokensale.liveedu.tv
Whitepaper: https://tokensale.liveedu.tv/static/docs/LiveEdu-white-paper.pdf
Description: The decentralized Learning Platform.

Contract address: https://etherscan.io/token/0x5b26c5d0772e5bbac8b3182ae9a13f9bb2d03765
Symbol: EDU
Full Name: Education
Decimals: 8

Link to confirm contract: https://tokensale.liveedu.tv/en/faq/faq-questions (right below the big red banner saying "warning")

Third-party comment(s) on the token:
https://bitcointalk.to/index.php?topic=2310239
https://hackernoon.com/liveedu-ico-review-66ffaf1bfe51

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.

**Comment by freeatnet** [comment]
Thank you for your request! Education has been listed: https://forkdelta.github.io/#!/trade/EDU-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
