### ISSUE TITLE
Listing request - BLZ

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#307]
Website: http://bluzelle.com 
Whitepaper: https://bluzelle.com/wp-content/uploads/2017/10/bluzelle-whitepaper-english1-4.pdf
Description: Bluzelle is a decentralized, on-demand, scalable database service for dApps.

Contract address: https://etherscan.io/token/0x5732046a883704404f284ce41ffadd5b007fd668
Symbol: BLZ
Full Name: Bluzelle
Decimals: 18

Link to confirm contract: https://www.huobi.pro/assetintro/#blz (Huobi was listed as an official exchange on their official blog: https://blog.bluzelle.com/new-exchange-listing-blz-on-huobi-a3622b7b9dde, therefore the contract address which Huobi lists on that token can be trusted)

Third-party comment(s) on the token:
https://cryptobriefing.com/bluezelle-ico-review-blz-token-analysis
https://bitcointalk.org/index.php?topic=2345293

**Comment by freeatnet** [comment]
@tradedbytony Nice choice of contract address confirmation! 👏

**Comment by tradedbytony** [comment]
Sometimes I have to get creative with the confirmation link. Many tokens don't link it in their sites so I have to search high and low for a proper way to verify their contract :D

**Comment by freeatnet** [comment]
Thank you for your request! Bluzelle Token has been listed: https://forkdelta.github.io/#!/trade/BLZ-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
