### ISSUE TITLE
Listing Request - BitcoinBlue

### ISSUE THREAD

**Issue by tonnyleonardo** [forkdelta/tokenbase#308]
Contract address: 0x8D6e79F25302dEE4CAAf9187fb1434C4a1465c3a

Issuer's official website: www.btcblue.org

Official contract address confirmation (MUST be linked from official website): btcblue.org

A link to a third-party review or discussion of the token, like an established ICO review blog: https://medium.com/@cryptosendd/bitcoin-blue-the-new-peer-to-peer-for-universal-transaction-f6d1176bbde7 , https://bitcointalk.org/index.php?topic=3010716

Description: Bitcoin Blue : The New Peer to Peer for Universal Transaction

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x8d6e79f25302dee4caaf9187fb1434c4a1465c3a, https://www.btcblue.org/

**Comment by freeatnet** [comment]
@tonnyleonardo Thank you for your request! BITCOINBLUE has been listed: https://forkdelta.github.io/#!/trade/BTCBLUE-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
