### ISSUE TITLE
List FND

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#309]
Contract address: 0x4df47b4969b2911c966506e3592c41389493953b

Issuer's official website: https://fundrequest.io/

Official contract address confirmation (MUST be linked from official website): 
 https://github.com/FundRequest/contracts#mainnet

A link to a third-party review or discussion of the token, like an established ICO review blog: 
* https://icodrops.com/fundrequest/
* https://github.com/ico-check/ico-check/issues/45

Description:

> FundRequest is an integrated platform to fund open source projects, thus financially incentivizing the open source community. The platform allows developers to fix bugs or to program additional features for an existing application. 
> 
> FundRequest will be developed on the Ethereum Blockchain, and aims to leverage upon a decentralized ecosystem as it reduces both operational and regulatory burdens and protects against organisational corruption such as fraud and embezzlement. FundRequest creates smart contracts to incentivize developers to solve a problem in the open source community.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.

**Comment by freeatnet** [comment]
Thank you for your request! Bluzelle Token has been listed: https://forkdelta.github.io/#!/trade/BLZ-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
