### ISSUE TITLE
Please list in token

### ISSUE THREAD

**Issue by necony** [forkdelta/tokenbase#310]
Contract address:0x7dFa96685B542D96a9be2d4a191950Fbeb11c5BB

Issuer's official website:https://www.webbot-cryptocurrency-japan-necony.com/02-services

Official contract address confirmation:https://ethplorer.io/address/0x7dfa96685b542d96a9be2d4a191950fbeb11c5bb

A link to a third-party review or discussion of the token:Not yet. However, there is a community in the discord.
It's is・・・https://discord.gg/fFpp3M

Description:This is a Japanese community token.
There are almost 1,500 holders already, and it has already been listed on the exchange called CREX 20.

**Comment by Kryptoniq** [comment]
1. Make the contract address available on the website. 
2. Provide a link to a third-party review or discussion of the token. E.G bitcointalk thread.

**Comment by necony** [comment]
thank you for your reply.

1.https://www.webbot-cryptocurrency-japan-necony.com/02-services
2.https://bitcointalk.org/index.php?topic=3041382.0
   https://discord.gg/fFpp3M

please list in...

Thank you!

2018-03-01 1:54 GMT+09:00 Krypton <notifications@github.com>:

**Comment by Kryptoniq** [comment]
Hi, your bitcointalk announcement thread is currently unavailable.

**Comment by necony** [comment]
Ok.
I m sorry.
I make new thread.
thank you!

2018-03-10 21:27 GMT+09:00 Krypton <notifications@github.com>:

**Comment by necony** [comment]
Sorry I made you wait.
I have created it now.
Please confirm it is.

https://bitcointalk.org/index.php?topic=3097782.0

2018-03-10 21:29 GMT+09:00 にーねこ <kusousagi.yobun.mg@gmail.com>:

**Comment by Kryptoniq** [comment]
I will have to close this issue as per new listing guidelines.
No update for the past 12 days.
