### ISSUE TITLE
Token Listing - Better Betting (BETR)

### ISSUE THREAD

**Issue by Saborknight** [forkdelta/tokenbase#311]
Contract address: 0x763186eB8d4856D536eD4478302971214FEbc6A9

Issuer's official website: https://betterbetting.org/

Official contract address confirmation: https://betterbetting.org/ - Just below the fold, to the right of the first youtube embed video is the Contract address. I hope this is satisfactory? I wasn't quite sure what you meant by this.

A link to a third-party review or discussion of the token: https://calvinayre.com/2018/02/26/press-releases/betterbetting-announces-betr-token-listing-hitbtc-exchange/

Description:
BETR is the betting crypto-currency that will establish truly decentralised sports betting on the internet.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x763186eB8d4856D536eD4478302971214FEbc6A9,  https://betterbetting.org/

**Comment by freeatnet** [comment]
@Saborknight Thank you for your request! Better Betting has been listed: https://forkdelta.github.io/#!/trade/BETR-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by Saborknight** [comment]
Many thanks to the two of you for this, and your being very responsive! We shall be announcing this through our media networks shortly, as well as on our website.
