### ISSUE TITLE
Listing request - BEE

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#314]
Website: https://www.beetoken.com
Whitepaper: https://s3-us-west-2.amazonaws.com/beenest-public/whitepaper/bee_whitepaper_v3.pdf
Description: A decentralized marketplace where hosts make additional income, guests find unique accommodations and mediators resolve disputes quickly and easily.

Contract address: https://etherscan.io/token/0x4d8fc1453a0f359e99c9675954e656d80d996fbf
Symbol: BEE
Full Name: Bee
Decimals: 18

Link to confirm contract: https://medium.com/@thebeetoken/how-to-view-bee-token-on-mew-and-metamask-6ba25d327862

Third-party comment(s) on the token:
http://cryptodaytrader.io/ico-review-bee-token-airbnb-competitor
https://cryptocoin.news/icos/bee-token-the-decentralized-sharing-network-5768

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x4d8fc1453a0f359e99c9675954e656d80d996fbf, https://www.beetoken.com/

**Comment by freeatnet** [comment]
Thank you for your request! Bee Token has been listed: https://forkdelta.github.io/#!/trade/BEE-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
