### ISSUE TITLE
LYM token listing request (Lympo.io)

### ISSUE THREAD

**Issue by shuushh** [forkdelta/tokenbase#315]
Contract address: 0x57aD67aCf9bF015E4820Fbd66EA1A21BED8852eC

Issuer's official website: www.lympo.io

Official contract address confirmation: https://lympo.io/how-to-get-tokens/add-lyms-eth-wallet/

A link to a third-party review or discussion of the token: https://icobench.com/ico/lympo ; https://globalhalo.com/2018/02/14/lympo-ico-review-lym-investment-analysis/ ; https://bitcointalk.org/index.php?topic=2655965

Description:
Lympo.io is a healthy lifestyle ecosystem powered by user-generated user-controlled sports and wellness data. Lympo users will be able to connect their favourite health apps and wearables to their Lympo digital fitness wallet and earn LYM tokens for being healthy through challenges organised by fitness trainers, gyms, sports events, employees or health insurers. LYM tokens can be further used to buy other healthy lifestyle goods and services.
Furthermore, Lympo users will be able to monetize their valuable data giving access to it to a number of stakeholders in the ecosystem: gyms, sports apparel producers, health insurances, data driven companies. Access permissions stored on blockchain will offer a unique service to companies in the world of tightening data protection rules. Putting this valuable data in the hands of users producing it will allow a seamless precious data flow for the benefit of all healthy lifestyle stakeholders. In the future, the tokens will also be used to invest in the most promising companies in the industry which aim to utilize the data of Lympo users.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x57ad67acf9bf015e4820fbd66ea1a21bed8852ec, http://www.lympo.io/

**Comment by freeatnet** [comment]
@shuushh Thank you for your request! ELECTRONIC PLATINUM has been listed: https://forkdelta.github.io/#!/trade/EPL-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by freeatnet** [comment]
@shuushh Thank you for your request! Lympo tokens has been listed: https://forkdelta.github.io/#!/trade/LYM-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
