### ISSUE TITLE
Listing request - LYM [closing because this token has been cleared with issue #315]

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#316]
Website: https://lympo.io
Whitepaper: https://lympo.io/wp-content/uploads/2017/12/whitepaper.pdf?v5
Description: Monetizing sports and health data via Blockchain.

Contract address: https://etherscan.io/token/0x57ad67acf9bf015e4820fbd66ea1a21bed8852ec
Symbol: LYM
Full Name: Lympo
Decimals: 18

Link to confirm contract: https://lympo.io/how-to-get-tokens/view-lym-tokens-metamask/

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2655965
https://bitcoinexchangeguide.com/lympo

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x57ad67acf9bf015e4820fbd66ea1a21bed8852ec, https://lympo.io

**Comment by tradedbytony** [comment]
Closing this one because Issue #315 is regarding this very same token and it was cleared for listing as well.
