### ISSUE TITLE
Listing OLXA on ForkDelta

### ISSUE THREAD

**Issue by OlxaCoin** [forkdelta/tokenbase#318]
1) The contract address: https://etherscan.io/token/0x5925f67d2767d937f47141dac24166b469558222#readContract

2) A link to the token issuer's official website: https://www.OlxaCoin.com

3) A couple sentences for token description: OLXA is a CryptoAsset backed up with Crowd-Projects and Advanced Services such as letter of crypto-credit, OLXA eShop with no cooking and no order history, OLXA i-Advertising Platform with Profit Sharing, and many more.
 
4) A link to an official page confirming the contract address: 
https://www.olxacoin.com/olxa-etherdelta/
5) A link to a third-party review or discussion of the token, like an established ICO review blog:
https://foundico.com/ico/olxa-coin.html

e-mail: info@olxacoin.com

A link to a third-party review or discussion of the token:

Description:

**Comment by Kryptoniq** [comment]
https://foundico.com/ico/olxa-coin.html brings a 404 error page.

**Comment by OlxaCoin** [comment]
it is working , please check again: https://foundico.com/ico/olxa-coin.html

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.

0x5925f67d2767d937f47141dac24166b469558222,  https://www.OlxaCoin.com

**Comment by OlxaCoin** [comment]
We cannot see our token yet on ForkDelta.com ?
where is OLXA there ?

**Comment by freeatnet** [comment]
@OlxaCoin Thank you for your request! ELECTRONIC PLATINUM has been listed: https://forkdelta.github.io/#!/trade/EPL-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by freeatnet** [comment]
@OlxaCoin Thank you for your request! OLXA has been listed: https://forkdelta.github.io/#!/trade/OLXA-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
