### ISSUE TITLE
XNK (Ink Protocol)

### ISSUE THREAD

**Issue by aevitas1** [forkdelta/tokenbase#319]
Contract address: 0xbc86727e770de68b1060c91f6bb6945c73e10388

Issuer's official website: https://paywithink.com/

Official contract address confirmation: https://medium.com/@PayWithInk/xnk-token-distribution-and-ink-protocol-smart-contract-f8ba3da1e985 (you reach this medium.com link when you click on "blog" on the top of the website).

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2410199.0 this is all I could find as all action is in telegram :/ Not super active, but the token has released 12 hours ago.

Description:

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xbc86727e770de68b1060c91f6bb6945c73e10388,  https://paywithink.com/

**Comment by freeatnet** [comment]
@aevitas1 Thank you for your request! Ink Protocol has been listed: https://forkdelta.github.io/#!/trade/XNK-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
