### ISSUE TITLE
ENTRP Token Listing

### ISSUE THREAD

**Issue by seahound** [forkdelta/tokenbase#32]
Here is information about the Hut34 Entropy Token (ENTRP)

Token contract address: 0x5BC7e5f0Ab8b2E10D2D0a3F21739FCe62459aeF3
name: Hut34 Entropy Token
symbol: ENTRP
decimal: 18
token description: Hut34's Entropy Token powers a blockchain based protocol facilitating an open ecosystem of chatbots, A.I. and IoT services. Allowing the open exchange and monetization of data, information and digital services. services where developers can easily connect and route queries, receive resolution of these queries, add utility to their end users, and be fairly rewarded for this. 

Official Website: https://hut34.io
Email: mailto: admin@hut34.io
Telegram: https://t.me/hut34
Twitter: https://twitter.com/@hut34project
Medium: https://medium.com/@hut34project
Email: mailto: admin@hut34.io

**Comment by freeatnet** [comment]
Contract address verification: official website: https://hut34.io/

@seahound if you plan on listing any other tokens, it'd be good to get the above included explicitly in the request ;)
