### ISSUE TITLE
Please List Bold (BOLD)

### ISSUE THREAD

**Issue by enkrypter** [forkdelta/tokenbase#320]
Contract address: 0x7cdEC53Fe4770729dac314756c10E2F37b8d2B2f

Issuer's official website: https://www.boldtoken.io

Official contract address confirmation (MUST be linked from official website): https://www.boldtoken.io (Contract address is BOLDLY displayed on official website home page)

A link to a third-party review or discussion of the token, like an established ICO review blog: https://bitcointalk.org/index.php?topic=2386305.0

Description:

Powered by the Ethereum network, Bold is an ERC-20 token built solely and purposely with a vision that it becomes a widely-accepted medium of exchange, as well as a safe and straightforward store of value over time. Its limited supply and concept of Bold Rewards ultimately promotes a growth in its value over time.

Name: Bold

Symbol: BOLD

Etherscan: https://etherscan.io/token/0x7cdEC53Fe4770729dac314756c10E2F37b8d2B2f

Twitter: https://twitter.com/theboldtoken

Facebook: https://www.facebook.com/theboldtoken

Stocks.Exchange: https://stocks.exchange/trade/BOLD/BTC

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.

0x7cdEC53Fe4770729dac314756c10E2F37b8d2B2f,  https://www.boldtoken.io

**Comment by freeatnet** [comment]
@enkrypter Thank you for your request! Bold has been listed: https://forkdelta.github.io/#!/trade/BOLD-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by enkrypter** [comment]
Many thanks for this!

Much appreciated - looking forward to the official Twitter announcement soon!

Team BOLD
