### ISSUE TITLE
LOCI coin add request

### ISSUE THREAD

**Issue by LazerPotatoe** [forkdelta/tokenbase#321]
Contract address:
0x9c23d67aea7b95d80942e3836bcdf7e708a747c2

Issuer's official website:
https://locipro.com/

Official contract address confirmation:
(go to website, click on LociCoin header link, click on Guide button on right-side)
https://locipro.com/wp-content/uploads/2018/01/Custom-Token-Instructions.pdf

A link to a third-party review or discussion of the token:
Coin Interview
https://www.youtube.com/watch?v=pWOW9xoIOqU
BitcoinTalk
https://bitcointalk.org/index.php?topic=2171217.0

Description:
A plaform for patent discovery, ownership and staking

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x9c23d67aea7b95d80942e3836bcdf7e708a747c2, https://locipro.com/

**Comment by freeatnet** [comment]
@LazerPotatoe Thank you for your request! LOCIcoin has been listed: https://forkdelta.github.io/#!/trade/LOCI-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
