### ISSUE TITLE
ERC223 token question

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#323]
Sometimes some tokens just can't be traded yet because the ICO is still ongoing and the tokens are locked. Once the ICO ends they usually activate the tokens for trading. This is most noticeable in some tokens which are not tradable yet in ForkDelta and you see a big buy wall and no one selling yet.

And then there are the ERC223 tokens. For instance, GXVC (https://forkdelta.github.io/#!/trade/GXVC-ETH) is an ERC223 token as stated on the company's website. ERC223 is backwards compatible with ERC20, but in some rare cases, there's a problem. If you look at https://github.com/ethereum/EIPs/issues/223#issuecomment-349643402 you'll see that "If the contract is a strict exchange contract, the transfer will fail, but no money lost." As someone in Reddit wrote "When you call [depositToken] it will call transferFrom from the token contract, and ERC223 tokens check the recipient is a contract and tries to call [tokenFallback]. Since the recipient is the EtherDelta contract it tries to call [tokenFallback] which doesn't exists, so the default fallback is called instead, which throws immediately." 

Since ForkDelta uses ED's contracts, wouldn't that mean that tokens such as GXVC and other ERC223 tokens to be untradable here?

**Comment by daniel-jozsef** [comment]
https://youtu.be/VATdaP-8r3A?t=1m18s

:D

**Comment by freeatnet** [comment]
@tradedbytony Thanks for the review and the question! While we have previously successfully worked with ERC223 tokens, there's been a recent wave of tokens that featuring an incompatible implementation; most notably, Debitum, Hydro, and now GXVC (we listed it before having a chance to check out compatibility, unfortunately).

We're carefully weighing the pros and cons of switching to an own contract with ERC223 support (we don't foresee ED team upgrading their contract any time soon) and will keep the community posted.

**Comment by tradedbytony** [comment]
Hopefully, the GXVC token can be de-listed so it doesn't cause much confusion. Perhaps when ED (if ever) fixes their contract to add ERC223 support then it could be listed again.
