### ISSUE TITLE
TOKEN LISTING APPLICATION - StarterCoin (STAC)

### ISSUE THREAD

**Issue by Zach-STAC** [forkdelta/tokenbase#324]
StarterCoin (STAC)

**Contract address:** 0x9a005c9a89bd72a4bd27721e7a09a3c11d2b03c4

**Issuer's official website:** https://coinstarter.com/

**Official contract address confirmation:** https://coinstarter.com/token

**A link to a third-party review or discussion of the token:**

ICO REVIEW: https://www.icotokennews.com/icos/coinstarter/

Bitcointalk ANN Post: https://bitcointalk.org/index.php?topic=2777787

**Description:**

CoinStarter is a platform where users can launch a crowdfunding or coin based fundraising campaign in minutes.  Users and backers will be able to participate in ICO, preICO or support other crowdfunding campaigns on the platform. It is a first of its kind blockchain platform to help entrepreneurs, innovators and creators bring their ideas to life. From the launch of your campaign to the distribution of coins, we make every step easy and intuitive.

Sincerely, 

Zach F.

System Administrator
Coinstarter
Zach@coinstarter.com

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
 0x9a005c9a89bd72a4bd27721e7a09a3c11d2b03c4, https://coinstarter.com/

**Comment by freeatnet** [comment]
@Zach-STAC Thank you for your request! StarterCoin has been listed: https://forkdelta.github.io/#!/trade/STAC-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
