### ISSUE TITLE
Listing (BSK) Brisk Pass

### ISSUE THREAD

**Issue by briskpass** [forkdelta/tokenbase#325]
addr: '0xe3d631a5fc2aa15d8f051e5ecc8b7979312c4aef'
decimals: 18
description: >-
Brisk Pass is a GLOBAL transportation access pass with integrated cryptocurrency wallet called Brisk Wallet utilizing its own exclusive cryptocurrency called BriskCoin to pay for services and/or transfer funds.
links:

Telegram: https://t.me/briskpass
Twitter: https://twitter.com/briskpass
Facebook: https://www.facebook.com/briskpassico
Website: https://www.briskpass.com/
Github: https://github.com/briskpass
Bitcointalk: https://bitcointalk.org/index.php?topic=2331020.0
Steemit: https://steemit.com/ico/@cryptooffuture/top-10-upcoming-icos-2017-q4
Medium: https://medium.com/@sivagauthamreddy/is-there-any-ico-in-november-that-is-going-to-have-an-impact-on-the-market-56e78f273d1d
Bitcoiner: https://bitcoiner.today/en/icos-brisk-pass-decentralizing-transportation/
Whitepaper: https://www.briskpass.com/briskpass-whitepaper.pdf
logo: https://www.briskpass.com/logo132.png
name: BriskPass
symbol: BSK

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xe3d631a5fc2aa15d8f051e5ecc8b7979312c4aef, https://www.briskpass.com/

**Comment by freeatnet** [comment]
Unfortunately, we have found significant and unresolved concerns regarding your project. In particular, I have come across [this review](https://steemit.com/cryptocurrency/@viennablues/the-ultimate-scam-ico-template-briskpass-review), and agree with two specific concerns:

* Though the team is listed, all Xing profiles were created on the same day.
* The place of business listed does not point to a valid address.
* I was unable to obtain verification that Brisk Pass GmbH exists.

Unfortunately, this precludes us from listing your token.

**Comment by briskpass** [comment]
Thank you very much for approaching us regarding your concerns. With regards to the “ONE” article that called our ICO a scam there are few points to consider that deemed the article fake & scam it self.

1. The article was written in October 2017 before our ICO started and we have delivered everything that was promised that the article said we won’t.
2. The article was written by a person who was a part of the team that tried steeling our idea and making it into their own ICO.
3. The writer of the article blackmailed us by asking us to send him BTC so he can put the article down as you can see in his article the BTC & ETH addresses are mentioned. His address is registered in Estonia a small place where probably people like him are making money by blackmailing corporates.
4. No one spends the whole day writing an article and many days researching without thinking of getting something in return.
5. We have his address and phone number and we have reported him to authorities.

We had our ICO run successfully and Brisk Pass is delivering everything promised and everything mentioned in the article (that was written in October) Is simply a lie and carry a personal agenda to blackmail brisk pass.

We are delivering as much as any other ICO have delivered and probably more.

The whole crypto world is build on anonymity so is every single ICO if you would really follow linkedin profiles of most of the ICOs and coins in top 200 you will find out that after the first 30 coins the profiles of people does not match the job they have the title for. 95% of alt coins are shit coins.

What matters is delivery and we are working hard to do that, our app is under beta testing and ready to launch right after few listings.

I hope you understand the profits you ll make on commissions with our coin and list our coin because:

1. We currently have 350,000,000 BSK tokens in circulation with over 3500 contributors waiting to trade.
2. We are also looking into doing 50% of coin burn in near future and further airdrops to increase future trade possibilities.
3. We have a solid marketing plan for promoting BSK on social media if we are listed on exchanges we will mention them in our campaign as trading platforms.
4. We are launching our App within one month of listing.
5. We have solid following on twitter facebook & telegram (Approximate 4500members each platform)

We are as ligit as Cardano or Electronium that dropped 80% in last 2 months only difference is we have better plans to promote our coin.

Thank You.

Julia.

**Comment by freeatnet** [comment]
Your response does not resolve the concerns regarding your company: you lay blame at the author of the article, stating

> 1. The article was written in October 2017 before our ICO started and we have delivered everything that was promised that the article said we won’t.
> 2. The article was written by a person who was a part of the team that tried steeling our idea and making it into their own ICO.
> 3. The writer of the article blackmailed us by asking us to send him BTC so he can put the article down as you can see in his article the BTC & ETH addresses are mentioned. His address is registered in Estonia a small place where probably people like him are making money by blackmailing corporates.
> 4. No one spends the whole day writing an article and many days researching without thinking of getting something in return.

This does not resolve the issues of fake profiles. Your claim of 

>  every single ICO if you would really follow linkedin profiles of most of the ICOs and coins in top 200 you will find out that after the first 30 coins the profiles of people does not match the job they have the title for

is irrelevant, given that primary concern is lack of verifiable information about your team.

We are also unable to verify your claim of "app is under beta testing and ready to launch right after few listings".

You may apply for listing again if the circumstances of your project change significantly.
