### ISSUE TITLE
SpaceKIM 

### ISSUE THREAD

**Issue by KimGoSpace** [forkdelta/tokenbase#328]
Contract address: https://etherscan.io/address/0x0fe31fb2fe9ae7e84ee9e570c3463f25ee50d31b

Issuer's official website: https://spacekim.io/

Official contract address confirmation:  https://spacekim.io/participate.html

You can see the contract address when you choose Ethereum 

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2718426
https://thebitcoin.pub/t/rocket-spacekim-ico-bigger-than-doge-doge/23063/20
https://youtu.be/Fg3Ycir6Mzs?t=15m39s 15:30 timecode

Description:

SpaceKim is a revolutionary North Korean space program conceived and created by the Sun of the Socialist Future Kim Jong-Un himself. This ICO is a historical chance for numerous Juche adherents all around the world to hasten the pace of the Holy Revolution by funding our groundbreaking lunar mission. The ICO is based on ERC-20 standard token. Needless to say, North Koreans always pay their debts. That is why we are going to issue 37.9 million KIM tokens, each of which is stands for ownership of 1km2 of moon land, and distribute that land via SpaceKim app we will release in the future.

**Comment by Kryptoniq** [comment]
There are no token details on your smart contract https://etherscan.io/token/0x0fe31fb2fe9ae7e84ee9e570c3463f25ee50d31b.

**Comment by Kryptoniq** [comment]
The Team members and advisors; too good to be true.
https://web.archive.org/web/20180301222248/https://spacekim.io
@freeatnet

**Comment by freeatnet** [comment]
@KimGoSpace High quality execution of the joke. Unfortunately, we have recently exhausted our limit of meme tokens. Please try again soon.

P.S. Token address https://etherscan.io/address/0x80fa08fc8da9db6dac8cd05d8741a2e7f20f39da if we come back to this.

**Comment by KimGoSpace** [comment]
@freeatnet Hey! What about giving SpaceKIM another chance?

**Comment by adrianmcli** [comment]
Would love to see what the cap on meme tokens is.
