### ISSUE TITLE
DocTailor DOCT Token Listing

### ISSUE THREAD

**Issue by DominicB13** [forkdelta/tokenbase#329]
Contract address:
https://etherscan.io/token/0xef9598E5edA6Be42EE45485671f202cE8a524648
Issuer's official website:
https://ww.doctailor.com
Official contract address confirmation:

Name: Dominic Brown
Role: COO
Email: dominicpsbrown@gmail.com
Reason for email not linked to the official website: Email server is down. Link to website sends you to professional LinkedIn which is here: https://www.linkedin.com/in/dominic-brown-94a4a6a5/

A link to a third-party review or discussion of the token:

ICO Bench Review: icobench.com/ico/doctailor
FoxICO Review:https://foxico.io/project/doctailor

Description:
DocTailor is a smart legal contract agreement platform, we utilize smart contract and blockchain technology to bridge the gap between the crypto economy and centralized business.
 
DocTailor's focus is to become a leading foundation to aid the crypto community in its aim to complete more business transactions with the assistance of the creation of legal contracts.

DocTailor is developed for B2B B2C P2P legal agreements, these contracts that are created allow our users to create legal contracts more efficiently in terms of cost and speed. 

As more senior executives become more open to using blockchain technology, DocTailor's need in the market will continue to rise by its demand in the community. 

DocTailor has just begun its ICO process and our prospects are looking very strong this is a reflection of our great team and amazing product.  DocTailor has a community of over 10,000 currently (and growing)  over a short period of time and I think that considering  DoocTailr's DOCT token on your exchange
![download](https://user-images.githubusercontent.com/32267070/36848792-31d4f818-1d5a-11e8-9248-d94f4521c152.png)
![logo](https://user-images.githubusercontent.com/32267070/36848793-31f9911e-1d5a-11e8-9e5b-e24de98feedb.png)

**Comment by Kryptoniq** [comment]
1. There are only 5 token holders.
2. Website is inaccessible ATM.

**Comment by Kryptoniq** [comment]
There are only 5 token holders ATM.

**Comment by Kryptoniq** [comment]
I'm closing this issue as per new listing guidelines.
No update for the past 15 days.

**Comment by samenrico** [comment]
@Philipinho @freeatnet We have updated the requested information here. Pls, list DOCT as soon as possible as it has been over 1 year since we applied. Thanks! 

New application: https://github.com/forkdelta/tokenbase/issues/2446
