### ISSUE TITLE
Token List Request: exominium.com

### ISSUE THREAD

**Issue by ExominiumCV** [forkdelta/tokenbase#330]
Contract address: 0x1c4D6b44353E01dAbA7B49c15B5Dfa8F9095214b

Issuer's official website: http://exominium.com/

Official contract address confirmation:
https://github.com/ExominiumCV/contract-ExoMinium/blob/master/smart%20Contract

A link to a third-party review or discussion of the token:

Description: ExoMinium will be a blockchain based e-commerce platform which will enable transactions between buyers and sellers leveraging the cryptocurrency payment networks.

In addition to the e-commerce platform, ExoMinium will introduce the concept of HEPT (Hodler’s Earning Per Token) which is explained in detail in HEPT section.

Along with that as ExoMinium is a global, decentralized eCommerce platform, focused on the provision of web services, ExoMinium will also provide you with the lending power of currency for the purchase of your Need with the crypto line of credit (CLOC).

**Comment by Kryptoniq** [comment]
1. 50 tokens; 3 holders.
2. No token review or discussion link.

**Comment by BDB-VK** [comment]
Token Offering:
• All tokens will be created during the initial period
• The number of tokens is limited to 50 Million in total
• Total tokens for sale are 51%

**Comment by freeatnet** [comment]
What's the difference between #330 and #393?

**Comment by Kryptoniq** [comment]
#393
