### ISSUE TITLE
Please list THETA

### ISSUE THREAD

**Issue by rdenke** [forkdelta/tokenbase#333]
Contract address: 0x3883f5e181fccaF8410FA61e12b59BAd963fb645

Issuer's official website: https://www.thetatoken.org/

Official contract address confirmation:   Token already trading at Huobi.  https://www.huobi.pro/theta_eth/exchange/   (Etherscan link under Coin Basics Section).

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2451089.0

Description:
Theta is a blockchain and token that will be used to power a Decentralized Streaming Network (DSN). The Theta Token functions as an incentive mechanism that encourages users to share their unused memory and bandwidth, serving as video caching and relay nodes for the DSN. Theta will be an open-source project that will be shared with industry and community participants, and our long-term vision is to have all video platforms participate in the network by building decentralized apps (D.apps) on top of the Theta protocol.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x3883f5e181fccaF8410FA61e12b59BAd963fb645, https://www.thetatoken.org/

**Comment by freeatnet** [comment]
@rdenke Thank you for your request! Theta Token has been listed: https://forkdelta.github.io/#!/trade/THETA-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
