### ISSUE TITLE
DOCT Token Listing Request

### ISSUE THREAD

**Issue by zloadr** [forkdelta/tokenbase#334]
Contract address: 0xef9598E5edA6Be42EE45485671f202cE8a524648

Issuer's official website: http://www.doctailor.com

Official contract address confirmation: http://www.doctailor.com

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2887286.0

Description:

DocTailor is a unique self customizing smart legal contract platform, that allows, lawyers, individuals and organizations to send and create legal tailor-made smart contracts and agreements on the blockchain without developer experience.

**Comment by Kryptoniq** [comment]
#329
