### ISSUE TITLE
WorldHotelOrganization - WHO

### ISSUE THREAD

**Issue by WorldHotelOrganization** [forkdelta/tokenbase#335]
Contract address: 0x9ceC06600AC633819a448fa73e40FF6032151c3d

Issuer's official website: http://www.worldhotelorganization.com/

Official contract address confirmation: https://www.reddit.com/user/WhoToken   ----
You need to sign in the website and then look at the "token" tab. Our contract address is not visible for visitors. It can be seen for only the members.

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2851420

Our token was reviewed and discussed by a cryptocurrency news website. Moreover, our token is being listed on investing.com. You can check on the ICOs part. And we are also waiing for being added on some exchanges in order to being added on price index section on investing.com automatically, which is very effective and efficient platform for comments of third parties. It has up-to-date information.
- https://www.investing.com/crypto/ico-calendar
- https://www.kriptoturk.org/world-hotel-organization-who-nedir/

Description: 

Dearly ForkDelta 

We as the creators of WHO would like to the WHO token be added in your Exchange market. To recieve your positive return to our request, we want to explain why you should add our token in your Exchange market.
WHO was designed to be used as a payment instrument for the entire stream of booking payment processing in the hotel industry. Payment processing for the hotel industry has become increasingly complex with the advance of technology and rising demand from customers in today’s digital world. We are aware of the challenges that both travellers and hotel owners face due to cross-border payment. In these regards, WHO was created for a solution to these problems, such as complexity of hotel payment processing, the challenge of handling prices in different currencies, currency fluctuations, double booking, security and speed, in the hotel industry. In this direction, we combine digital currency technology with a reliable and useful environment of THE RE-PAY SYSTEM that will be valid for the first time in the world. The primary aim of the project is to ensure the use of WHO while online booking, and while direct booking at next steps. So, we aim to use advantages of the block chain technology in the payment processing for travel/hotel industry.
“WHO RE-PAY SYSTEM” is a revolutionary system guaranteeing that WHO purchased through the ICO, exchanges and also earned by the bounty/airdrop campaigns can be always bought back to us in case people wish to sell. This system ensures WHO cannot remain unsold, which makes WHO value always alive. As WHO is an international payment system for tourism industry it has to maintain it’s value. A cryptocurrency which has established an edge with its safety and speed features has its value maintained and guaranteed by us. We aim to make WHO a trading platform at the cutting edge of the currently developing altcoin market where safety is a must. It is visible that many alternative investment options are unclear as to how they are evolving, and this leads to a problem amongst investors. So, there is no doubt that this system will increase the demand for buying WHO in your Exchange market.
To sum up, WHO is more than a decentralized cryptocurrency, and it is more than an Ethereum based token. WHO brings a real revolution to the cryptocurrency world with its RE-PAY SYSTEM to be implemented for THE FIRST time in the world. It is designed to be used as a payment instrument for the entire stream of booking payment processing in the hotel industry, which is a very profitable industry. So, what do we have?  A revolutionary token in one of the most profitable industries in the world. That is why you should add the WHO token in your market.
Please let us know if you need any additional information. We look forward to hearing from you. Thank you very much for your consideration of our request.

Sincerely,

WHO TEAM

E-mail: info@worldhotelorganization.com
Telegram: https://t.me/whorg
Twitter: https://twitter.com/whoplatform
Website: http://www.worldhotelorganization.com/
Github: https://github.com/WorldHotelOrganization/TheCode/
Reddit: https://www.reddit.com/user/WhoToken
Medium:https://medium.com/worldhotelorganization
Slack: https://worldhotelorg.slack.com
Whitepaper: http://www.worldhotelorganization.com/who_white_paper.pdf
Logo:http://www.worldhotelorganization.com/who-28x28.png
Name: WorldHotelOrganization
Symbol: WHO

**Comment by Kryptoniq** [comment]
#352
