### ISSUE TITLE
electrum dark listing request 

### ISSUE THREAD

**Issue by electrumdark** [forkdelta/tokenbase#336]
Contract address:  0xaaf7d4cd097317d68174215395eb02c2cca81e31

Issuer's official website: electrumdark.com

Official contract address confirmation: 0xaaf7d4cd097317d68174215395eb02c2cca81e31  ( visible on our website )(https://ibb.co/h98PHc )

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2491104.msg25511729#msg25511729

Description: Electrum Dark is a working real-world token powering a fully-functional decentralized marketplace that allows you to buy and sell goods and services easily, securely, and anonymously,Say goodbye to the old way of doing ecommerce.
You can buy and sell anything with no fees using a completely free technology.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xaaf7d4cd097317d68174215395eb02c2cca81e31, https://electrumdark.com

**Comment by freeatnet** [comment]
* Whitepaper is a copypaste of the [Storiqa whitepaper](https://crowdsale.storiqa.com/static/docs/TS-white-paper-EN.pdf).
* No verifiable team.

Unfortunately, we cannot list your token.
