### ISSUE TITLE
electrum dark listing

### ISSUE THREAD

**Issue by electrumdark** [forkdelta/tokenbase#337]
1. addr: '0xaaf7d4cd097317d68174215395eb02c2cca81e31'
2. decimals: 18
3. description: >-
4.   Electrum Dark is a working real-world token powering a fully-functional decentralized marketplace that allows you to buy and sell goods and services easily, securely, and anonymously,Say goodbye to the old way of doing ecommerce.
5. links:

7. - Github: https://github.com/electrumdark/Electrum-dark-token
8. - Reddit: https://www.reddit.com/user/electrumdarktoken/
9. - Telegram: https://t.me/joinchat/G0Rs1Q9L3t2-6aEGYaOv2A
10. - Twitter: https://twitter.com/electrumdark
11. - Website: https://electrumdark.com
12. - Whitepaper: https://electrumdark.com/wp-content/uploads/2018/01/whitepaper.pdf
13. name: electrum dark
14. symbol: ELD

**Comment by Kryptoniq** [comment]
#336
