### ISSUE TITLE
Listing request - RFR

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#338]
Website: https://refereum.com
Whitepaper: https://token.refereum.com/RefereumWhitepaper.pdf
Description: Refereum is the first referral marketplace for games. Helping streamers, gamers, and developers.

Contract address: https://etherscan.io/token/0xd0929d411954c47438dc1d871dd6081f5c5e149c
Symbol: RFR
Full Name: Refereum
Decimals: 4

Link to confirm contract: https://help.refereum.com/rfr-tokens/how-do-i-add-the-rfr-token-to-my-wallet

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2205251
https://cointelegraph.com/press-releases/refereum-transforms-game-marketing-and-engagement-advised-by-twitch-and-unity

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xd0929d411954c47438dc1d871dd6081f5c5e149c, https://refereum.com/

**Comment by freeatnet** [comment]
@tradedbytony Thank you for your request! Refereum has been listed: https://forkdelta.github.io/#!/trade/RFR-ETH We will announce it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by freeatnet** [comment]
@tradedbytony On a more personal note, I appreciate your continuous token listing suggestions! :)
