### ISSUE TITLE
Request to list Rezox Token on ForkDelta

### ISSUE THREAD

**Issue by mombacoin** [forkdelta/tokenbase#341]
Contract address: 0xc7a4eb66f982cde71d872398e4d1fc5fc586cb9e

Issuer's official website: www.rezox.network

Official contract address confirmation: Can be found at main page here: www.rezox.network
The address is 0xc7a4eb66f982cde71d872398e4d1fc5fc586cb9e

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2912627

Description: Rezox Token, is a semi-mineable Token thats based on the Ethereum network.
Our goal is to promote low-end computers and make them be able to mine and get our Tokens and take part in the Blockchain revulotion.

More information:
Decimals: 8
links:
- Telegram: https://t.me/rezoxtoken
Name: Rezox
Symbol: REZ

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xc7a4eb66f982cde71d872398e4d1fc5fc586cb9e, http://www.rezox.network/

**Comment by JonathonDunford** [comment]
Thank you for your request! Rezox has been listed: https://forkdelta.github.io/#!/trade/REZ-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
