### ISSUE TITLE
Request to list GUESS Token on ForkDelta

### ISSUE THREAD

**Issue by peerguess** [forkdelta/tokenbase#342]
Contract address: 0xbdcfbf5c4d91abc0bc9709c7286d00063c0e6f22

name : GUESS
symbol : GUESS

Issuer's official website: https://peerguess.com/

Official contract address confirmation:
https://peerguess.com/

A link to a third-party review or discussion of the token:
 https://bitcointalk.org/index.php?topic=2199333.0 

Description:

Peerguess is a free, one-stop-shop cryptocurrency
price ticker application where the users will also guess
future prices to earn gems, learn about community
tendencies and have access to the sophisticated data
to improve your intuition. With collaboration at the
heart of the system, peerguess will provide “market
sentiment” data to both its users and business
partners.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xbdcfbf5c4d91abc0bc9709c7286d00063c0e6f22, https://peerguess.com/

**Comment by JonathonDunford** [comment]
Thank you for your request! GUESS has been listed: https://forkdelta.github.io/#!/trade/GUESS-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
