### ISSUE TITLE
UPDATED: THX Spectraal Token on your Exchange THX. Looking Forward

### ISSUE THREAD

**Issue by msdong** [forkdelta/tokenbase#343]
Contract address: 0xa3114b268ff4327525fbc0dd5c48e0b4304d07b9

Issuer's official website: in a few days www.spectraaltoken.com or www.spectraaltoken.de

Official contract address confirmation:
https://etherscan.io/token/0xa3114b268ff4327525fbc0dd5c48e0b4304d07b9?a=0xec07f0383759a92e565a69302c0757c1df48dd7a

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3043516.new#new

https://twitter.com/spectraaltoken

Description: Spectraal was created only for Speculations bcause all small and medium investors wants to make fast money nothin more. Only 10% of Investors are interesting about the Project behind a Coin or ICO and we all know that 80% and more Projects didnt need a TOKEN/COIN for payments

Spectraal Token

ERC 20
Wallet : MYW, MM or other ERC20 Wallets
Symbol: SPECT
Max Supply: 300 m - 500 m

**Comment by Kryptoniq** [comment]
1. Only 4 token holders
2.  spectraaltoken.com and spectraaltoken.de are inaccessible.
3. Insuficient info on your bitcointalk announcement thread.

**Comment by msdong** [comment]
only 4 tokenholders cause we didnt start yet with airdrops in a few days we start airdrops we dont have any ico

our websites are in work in few days we are online

bitcointalk is just started more to come....
in few days we send further infos and updates

**Comment by msdong** [comment]
our token hodlers grows:
https://etherscan.io/address/0xa3114b268ff4327525fbc0dd5c48e0b4304d07b9

more airdrops coming.....twitter grows also and telegram :-)

our website has an update: www.spectraaltoken.com
https://twitter.com/spectraaltoken
https://t.me/joinchat/HcgY6Uk4Ezjdvu42tipW4A

**Comment by msdong** [comment]
Spectraal Token is now a registered Trademark.

https://twitter.com/spectraaltoken/status/973065073030770688

**Comment by tradedbytony** [comment]
Open PR at #536

**Comment by msdong** [comment]
4:16      error    syntax error: expected chomping or indentation indicators, but found 'S'
can anybody help me?

whats wrong with my .yaml?


---
addr: '0xa3114b268ff4327525fbc0dd5c48e0b4304d07b9'
decimals: 0
description: >-
links:
- Email: mailto:support@spectraaltoken.com
- Telegram: https://t.me/joinchat/HcgY6Uk4Ezjdvu42tipW4A
- Twitter: https://twitter.com/spectraaltoken
- Website: http://www.spectraaltoken.com/
name: SPECTRAAL
symbol: SPECT

**Comment by msdong** [comment]
UPDATE: We have 218 k Twitter Impressions in only 8 Days. Our Community and Traders who are willing to Trade on your Exchange growing very very fast.

https://twitter.com/spectraaltoken
Thx
Regards 
Andreas Stammer 
![bildschirmfoto vom 2018-03-15 06-16-17](https://user-images.githubusercontent.com/242173/37446762-da2d660c-281e-11e8-82d3-6a78990ba280.png)
www.spectraaltoken.com
--

**Comment by msdong** [comment]
any help about this error?? thx

**Comment by JonathonDunford** [comment]
Move the conversation to: https://github.com/forkdelta/tokenbase/pull/536

Also, if you open up one more issue or PR, you will be banned from this repository. Stop the spam.
