### ISSUE TITLE
Deep Gold listing request

### ISSUE THREAD

**Issue by DeepGold** [forkdelta/tokenbase#344]
Contract address:
0x983877018633c0940B183Cd38d1b58bEE34F7301
Issuer's official website:
www.deep.gold
Official contract address confirmation:

deep.gold purchase form
A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2277831.0

Description:
The Deep is a true one-rank P2P world, which means complete decentralization and distributed storage of the entire territory and its contents. All owned buildings are encrypted and repeatedly duplicated by storage on other users' computers, using blockchain-based technologies and error correction codes.

**Comment by Kryptoniq** [comment]
Please, make your contract address available on your website.

**Comment by DeepGold** [comment]
Contract adress added in TOKEN DETAILS section.


Deep Team

www.deep.gold

________________________________

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x983877018633c0940b183cd38d1b58bee34f7301, http://www.deep.gold/

**Comment by JonathonDunford** [comment]
@DeepGold 

Apparently we already have/had you listed: https://forkdelta.github.io/#!/trade/DEEP-ETH

Feel free to announce it to your users. :)
