### ISSUE TITLE
RevizorCoin (RR) listing request

### ISSUE THREAD

**Issue by YuliyaZh** [forkdelta/tokenbase#345]
Contract address: 0x5fB6a842Ea587fa8d0486589742Ce68Ef24834A4

Issuer's official website: [https://revizor-coin.io/](url)

Official contract address confirmation: [https://revizor-coin.io/#about](url)

A link to a third-party review or discussion of the token: [https://bitcointalk.org/index.php?topic=2645567.0](url)

Description: 
Revizor is an innovative project in the field of regulation of the crypto-currency market, the main task of which is to create software tools that would filter a wide range of assets by absorbing unpromising tokens. 

_________________________________________________________________________
addr: 0x5fb6a842ea587fa8d0486589742ce68ef24834a4
decimals: 18
links:
- Email: rvr@revizor-coin.io
- Telegram: [https://t.me/revizorcoin](url)
- Twitter: [https://twitter.com/RevizorCoin_RR?lang=ru](url)
- Website: [revizor-coin.io](url)
- Whitepaper: [https://revizor-coin.io/WHITE_PAPER_ENG.pdf](url)
name: Revizor Coin
symbol: RR

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x5fB6a842Ea587fa8d0486589742Ce68Ef24834A4,  https://revizor-coin.io/

**Comment by JonathonDunford** [comment]
Thank you for your request! Revizor Coin has been listed: https://forkdelta.github.io/#!/trade/RR-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by YuliyaZh** [comment]
I have a question. As I understand later it will be message about RR listing on ForkDelta twitter?
