### ISSUE TITLE
Request for listing Leverage Platform [LVP]

### ISSUE THREAD

**Issue by LeveragePlatform** [forkdelta/tokenbase#346]
Contract address: 0x125e655ab4186a6c62f4ec6c8b7967d2e5b3d25e

Issuer's official website: https://leverageico.com

Official contract address confirmation: https://leverageico.com/#sale 

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2949207

Description: Leverage is a decentralized platform that allows people to store and invest their wealth in a decentralized cryptocurrency, and earn a substantial interest on investment. The Leverage Platform (LVP for short) features a genuine, trustworthy and traceable lending platform with complete data sharing and absolute information transparency.

**Comment by Kryptoniq** [comment]
There are only 7 token holders.

**Comment by LeveragePlatform** [comment]
yes that is correct.

**Comment by Kryptoniq** [comment]
I'm closing this issue as per new listing guidelines.
No update for the past 14 days and the  issue is yet to be addressed by the team.

**Comment by LeveragePlatform** [comment]
We have re-issued a request for listing

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x125e655ab4186a6c62f4ec6c8b7967d2e5b3d25e, https://leverageico.com/

**Comment by LeveragePlatform** [comment]
@Kryptoniq @freeatnet 

Thank you for the update. We would like to know if we there is anything else we can do to speed up the process. If not, we will be patient to hear from you.

**Comment by LeveragePlatform** [comment]
@Kryptoniq @freeatnet

It has been March 2nd when we opened this Issue. It was market as 'information complete' 22 days ago with the message that we would be listed in the next few days. Could you please inform us on the date of listing?

**Comment by freeatnet** [comment]
@LeveragePlatform Sorry for the delay. I'm having trouble finding third-party reviews for your platform (I've seen one from [coin observer](https://coinobserver.io/leverage-ico-helps-connect-cryptocurrency-lenders-borrowers/), that's about it). Could you put up some more links to third-party reviews / coverage?
