### ISSUE TITLE
Request to add LaLa token on forkdelta

### ISSUE THREAD

**Issue by Ezaz077** [forkdelta/tokenbase#347]
Contract address: 0xfd107b473ab90e8fbd89872144a3dc92c40fa8c9
Symbol: LALA
Decimals: 18

Issuer's official website: https://lalaworld.io

Official contract address confirmation: 
https://blog.lalaworld.io/add-lala-token-step-wise-guide/

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2268691.0

Description:
LALA World (“LALA”) is all about migrants and their unbanked families. Its an ECOSYSTEM enabled by the LALA Wallet as a PLATFORM, a single sign-on platform revolving around their issues and problems. Employment issues, digital ID’s, communities build up, government and NGO partnerships, health issues, and of course, a new financial ecosystem for the huge underbanked population by capitalizing the Blockchain revolution to bridge the gap between cash, digital world.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xfd107b473ab90e8fbd89872144a3dc92c40fa8c9, https://lalaworld.io

**Comment by JonathonDunford** [comment]
Thank you for your request! LALA has been listed: https://forkdelta.github.io/#!/trade/LALA-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
