### ISSUE TITLE
Request to add NGC

### ISSUE THREAD

**Issue by nicholas-qi-cognizant** [forkdelta/tokenbase#349]
Contract address: 0x97e0d16620a781b5fbd51054c67e955ab5d51a34

Issuer's official website: https://nextgenius.com.au

Official contract address confirmation: https://nextgenius.com.au

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3055808

Description:

We are trying to solve the problem of limited transaction medium for any individual startup company;
while all the startups can earn the Token of 20,000 - 1,000,000 on the first time they submit the proposals.

Email: info@nextgenius.com.au
Telegram: https://t.me/next_genius
Twitter: https://twitter.com/NextGeniusAU
name: NextGenius COIN
symbol: NGC

**Comment by Kryptoniq** [comment]
1. The NGC ticker is already in use by NAGACOIN. 
2. The website https://nextgenius.com.au is inaccessible at the moment. 
3. Your bitcointalk announcement thread has insufficient information.

**Comment by fintie** [comment]
1. We can use NGCOIN instead.
2. Please check http://NextGenius.com.au
3. May I ask what is missing for that announcement?

Thsnks

**Comment by fintie** [comment]
@Kryptoniq Can you please help review it? Thanks

**Comment by Kryptoniq** [comment]
There not enough information and comments on your announcement thread.

**Comment by fintie** [comment]
@Kryptoniq as we announced the release on Chinese social media: wechat, we've already received around 100 wallet and transactions:
https://etherscan.io/address/0x97e0d16620a781b5fbd51054c67e955ab5d51a34
Will it be all right?
It might just take a few days as we just announce on bitcoin talk. Thanks for understanding.

**Comment by Kryptoniq** [comment]
In addition, endeavor to verify your smart contract on etherscan.

**Comment by freeatnet** [comment]
@fintie @nicholas-qi-cognizant Is there any public reviews, discussion of this token? I am unable to find any third-party discussion or mentions of it.

**Comment by Kryptoniq** [comment]
I will have to close this issue as per new listing guidelines.
No update for the past 18 days.

**Comment by fintie** [comment]
Hi, as we are receiving more and more mentions over WeChat & some non English platform, will it still be all right?

Meanwhile, can you please check our https://bitcointalk.org/index.php?topic=3055808
To see if it is eligible now.
Thanks
