### ISSUE TITLE
Listing AAC

### ISSUE THREAD

**Issue by BoomBustBlog** [forkdelta/tokenbase#350]
Contract address: 0x330874F472AB95B623D813459b9Cb8EbE52d75BD

Issuer's official website: https://acuteangle.com/

Official contract address confirmation: https://ethplorer.io/address/0x330874f472ab95b623d813459b9cb8ebe52d75bd#pageSize=100

A link to a third-party review or discussion of the token:

Description:

**Comment by Kryptoniq** [comment]
1. No announcement thread or discussion of the token
2. Only one token holder
3. No description.
4. No reference to contract address on your website

**Comment by Kryptoniq** [comment]
I'm closing this issue as per new listing guidelines.
No update for the past 13 days.
