### ISSUE TITLE
IBT Token Listing Request

### ISSUE THREAD

**Issue by icocalendartoday** [forkdelta/tokenbase#351]
Contract address: 0x791425156956e39f2ab8ab06b79de189c18e95e5 or icobaytoken.eth

Issuer's official website: https://icobay.net/crowdsale/ico

Official contract address confirmation:
It is available here: https://icobay.net/crowdsale/ico exactly under the Token supply & funds usage section.

A link to a third-party review or discussion of the token:
https://cryptocurrencies.space/icobay-net-announces-the-launch-of-the-largest-icos-directory-rating-platforms-group/

Description:
IBT token is an ERC-20 utility token. IBT token will be used to buy services within the ICOBay group of sites.
Investing in IBT tokens, like any other form of investment, includes risks. However if the IBT tokens you own don’t reach at a specific period of time the particular value you have expected, they will always have a value within the ICOBay group of sites meaning you will be able to buy services within our group of platforms using your IBT tokens.

**Comment by icocalendartoday** [comment]
addr: 0x791425156956e39f2ab8ab06b79de189c18e95e5
decimals: 18

links:

Email: sales@icobay.net
Facebook: https://www.facebook.com/icobaygroup/
Medium: https://medium.com/@icocalendartoday
Website: https://icobay.net/crowdsale/ico
Whitepaper: https://drive.google.com/file/d/1wJ9kCsbVqsd7n6v56A6bRDCXPI9Stnzl/view
name: IcoBay
symbol: IBT

**Comment by icocalendartoday** [comment]
Please also note we haven't run an ICO - it is explained in the page here: https://icobay.net/crowdsale/ico

**Comment by Kryptoniq** [comment]
There only 7 token holders ATM.

**Comment by icocalendartoday** [comment]
That's very correct. As explained all over the site, we are not running an ICO or raising funds for it. Tokens have been sent out only to the team. We are already listed on https://ddex.io/trade/IBT-ETH
The tokens are mintable and we haven't generated more saving them for exchanges like yours as most require to send tokens for the order book creation.

**Comment by freeatnet** [comment]
@Kryptoniq bump?

**Comment by Kryptoniq** [comment]
Hi, since your tokens are only held by the team, we can't list you now. We need more token holders.

**Comment by Kryptoniq** [comment]
I will have to close this issue as per new listing guidelines.
No update for the past 18 days.
