### ISSUE TITLE
Hell Coin

### ISSUE THREAD

**Issue by HELLCOINtoken** [forkdelta/tokenbase#353]
Contract address: 0x8e4Bf12e472739ab62Eb404c758423CA499Cf94D

Issuer's official website: http://hellcoin.network/

Official contract address confirmation: http://hellcoin.network/ (it is present at the bottom of homepage)

A link to a third-party review or discussion of the token: 
http://cryptocoindaddy.com/what-is-hell-coin/
http://mytechpartner.com/what-the-hell-is-hell-coin/

Description: Meet Hell Coin, Satan's own cryptocurrency

**Comment by Kryptoniq** [comment]
Both review websites are down ATM.

**Comment by HELLCOINtoken** [comment]
They seem to up from my side. Can you try again?

**Comment by HELLCOINtoken** [comment]
I hope everything is in order now?

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x8e4bf12e472739ab62eb404c758423ca499cf94d, http://hellcoin.network/

**Comment by freeatnet** [comment]
@HELLCOINtoken Thank you for your request! HELL COIN has been listed: https://forkdelta.github.io/#!/trade/HELL-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
