### ISSUE TITLE
CS ticker assigned to unknown contract with reference to credits.com

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#356]
Wrong listing: https://github.com/forkdelta/tokenbase/blob/4d831d607b45461043743389eab6cc643cff604c/tokens/0x12a35383ca24ceb44cdcbbecbeb7baccb5f3754a.yaml

Correct listing: https://github.com/forkdelta/tokenbase/blob/aced1e308c3b44cf8bfd89cb5b16411afcf53163/tokens/0x46b9ad944d1059450da1163511069c718f699d31.yaml

I propose we remove the incorrect listing and assign ticker CS to the correct credits.com token.

**Comment by Kryptoniq** [comment]
The supposed wrong Credits' contract `0x12a35383cA24ceb44cdcBBecbEb7baCcB5F37` happens to be created  244 days ago `https://etherscan.io/tx/0xdffaaa5a6c3713a6bbe173e7daeca85abec500cb545ea00973b409afc8f33381`.

It was created before the current  Credits' project - 22 days ago- `https://etherscan.io/tx/0xe20a326a4bf2e57c70372ed8f78771248cc240705030e778327b49018bd9a0ae`.

**Comment by mrmm** [comment]
I have made some research about this contract, it seems it is a "scam" [this](https://medium.com/@Ligareaux/c%C3%B3mo-comprar-credits-gu%C3%ADa-paso-a-paso-c23f57e47e23) medium post from Nov 15, 2017 medium explains how to add the token to MEW with the wrong contract address. 
I think it should be removed from the tokenbase and attribute the CS ticker to the right contract.
Cheers.

**Comment by freeatnet** [comment]
@Kryptoniq Your comment about previous contract having been created 244 days ago made me think it's a little too old to be a pure scam.

So I went digging a little deeper and — hooray — found a pretty broken but not yet disappeared [page on credits.com](https://credits.com/en/Home/NewsItem/56) that links to a Google Doc that [mentions the old contract address](https://docs.google.com/document/d/1aMZ66ySU7ZG3643OeCQwYwr5LDinBz48NAWIMPCLvBs/edit).

So it looks like CS is indeed the old credits.com token. Perhaps, we should move it to CSOLD ticker, and properly assign CS to the new token.

**Comment by mrmm** [comment]
@freeatnet The page is little bit broken xD.
But the orders are little bit odd, (1.000 CS  @ 1.000000000 CS/ETH). I think there is none using this token.
To keep track CSOLD would be best solution.
