### ISSUE TITLE
MunichToken

### ISSUE THREAD

**Issue by CoinBrothers** [forkdelta/tokenbase#357]
Contract address: 0x0afc375f602443777cf3d2604de34145776cbd9b

Issuer's official website: www.munichtoken.tk (homepage in progress)

Official contract address confirmation: https://etherscan.io/token/0x0afc375f602443777cf3d2604de34145776cbd9b?a=0xfccc6cfb68331d861c3e92d7e722f5867d3e4f76

A link to a third-party review or discussion of the token: https://web.telegram.org/#/im?p=g308412602

Description: Introduction of MunichToken as new cashback program for Munich city. The target is to incentivize customers to bought offline in Munich and to support regional retailers in this way.

**Comment by Kryptoniq** [comment]
1. There are only 2 token .
2. The website is under. 
3. No link to a third-party review or discussion of the token.
Kindly try again when you fulfill the requirements.

**Comment by freeatnet** [comment]
@CoinBrothers Thanks for your request! Unfortunately, we are unable to list MunichToken based on the information you provided at this time. Once you are able to provide more information, we'll be happy to reopen your request.
