### ISSUE TITLE
Request to List BitSense Token on ForkDelta

### ISSUE THREAD

**Issue by BitSenseProject** [forkdelta/tokenbase#358]
Contract address: 0xd8B980aD351894b8a4CF94856ead06c4586D763F

Issuer's official website: https://www.bitsense.club

Official contract address confirmation:
https://www.bitsense.club

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3013099.msg30976832#msg30976832

Description:

BitSense Token is erc20 token based on the Ethereum network. It is the native currency of the BitSense platform. It acts as means of exchange of goods and services and as the central point between members and advertisers. BitSense is a decentralized platform for advertisers, businesses and members. My vision of BitSense is to create a simple ecosystem for everyday users who will be able to earn cryptocurrency/fiat by simply watching daily ads or doing simple tasks. Money they will earn will come from the people advertising their business.

Twitter: https://twitter.com/bitsenseproject
Facebook: https://www.facebook.com/bitsenseproject

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xd8b980ad351894b8a4cf94856ead06c4586d763f, https://www.bitsense.club/

**Comment by BitSenseProject** [comment]
Thanks

**Comment by BitSenseProject** [comment]
Hello. My token still is not listed...

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by freeatnet** [comment]
Hmm. http://archive.li/AdMEM

**Comment by freeatnet** [comment]
@BitSenseProject We have discovered significant issues with your project. Specifically:
* Team photos are stock photos
* There is no other information about team member that we can verify
* There is no whitepaper or roadmap for the project
* There are no third-party reviews and there is no meaningful public discussion of the project

Based on these criteria, we are unable to list BitSense token at this time. If you believe you can provide additional information that would address these concerns, you may post it here.
