### ISSUE TITLE
Listing request - TOMO

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#361]
Website: https://www.tomocoin.io
Whitepaper: https://drive.google.com/file/d/1xrtNX9y_ayyx7UKWYzIWOqley3jUUIWH/view
Description: We're building an efficient blockchain infrastructure for decentralized applications, token issuance and integration.

Contract address: https://etherscan.io/token/0x8b353021189375591723e7384262f45709a3c3dc
Symbol: TOMO
Full Name: Tomocoin
Decimals: 18

Link to confirm contract: https://twitter.com/TomoCoin_io/status/969457886798557184 (this is their official Twitter account, which is linked on their official website. You can also scroll all the way down to their official website and you'll find this tweet there too.)

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2021785
https://cryptobriefing.com/tomocoin-ico-review-tmc-token-analysis

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x8b353021189375591723e7384262f45709a3c3dc, https://www.tomocoin.io/.

**Comment by JonathonDunford** [comment]
Tomocoin has been listed: https://forkdelta.github.io/#!/trade/TOMO-ETH
