### ISSUE TITLE
Listing request - DADI

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#362]
Website: https://dadi.cloud
Whitepaper: https://dadi.cloud/public/files/dadi.white-paper.pdf
Description: A new era of cloud computing services, powered by blockchain technology.

Contract address: https://etherscan.io/token/0xfb2f26f266fb2805a387230f2aa0a331b4d96fba
Symbol: DADI
Full Name: DADI
Decimals: 18

Link to confirm contract: https://steemit.com/dadi/@myblockchainhub/dadi-ico-pre-sale-and-public-sale-consolidated-info (go all the way to the bottom and you'll see they list the ethplorer address there which confirms this as the token address). Also, a DADI team member confirmed this address on Reddit: https://www.reddit.com/r/DADI/comments/7xywp5/right_on_cue_weve_started_token_distribution_for/dudt85y

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2349363
https://icoranker.com/ico/dadi

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xfb2f26f266fb2805a387230f2aa0a331b4d96fba, https://dadi.cloud

**Comment by JonathonDunford** [comment]
DADI has been listed: https://forkdelta.github.io/#!/trade/DADI-ETH
