### ISSUE TITLE
Bioether (BIO) listing

### ISSUE THREAD

**Issue by Xant490** [forkdelta/tokenbase#363]
The contract address : 0x9b06fb515b68089518a4f857a8bcfb16cc97346e
A link to the token issuer's official website : https://bioether.wixsite.com/token
A couple sentences for token description : Bioether (BIO) is made for easy transfers through ethereum network,and this is ERC-20 ethereum token.
A link to an official page confirming the contract address : https://etherscan.io/address/0x9b06fb515b68089518a4f857a8bcfb16cc97346e
A link to a third-party review or discussion of the token, like an established ICO review blog : https://bitcointalk.org/index.php?topic=2293988.0

**Comment by Kryptoniq** [comment]
The website's name does not correspond  with the name of the token.

**Comment by Xant490** [comment]
https://bioether.wixsite.com/token

**Comment by Kryptoniq** [comment]
Bitcointalk announcement thread was last active in November 2017. It is obvious to me that you created the wix site.
Sorry, we can't list your token.

**Comment by Xant490** [comment]
Go fuck yourself morona and pederasta
