### ISSUE TITLE
Please list Ascoin

### ISSUE THREAD

**Issue by zacklif** [forkdelta/tokenbase#364]
Contract address:
https://etherscan.io/token/0x582851ace6a6f7f4259de01fa412afcafeb199a9

Issuer's official website:
http://ascoin.io/

Official contract address confirmation:
http://ascoin.io/

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2991617.0

Description:
Ascoin is a token used in purchases via Braund Card’s prepaid card.
By using Ascoin you get bonuses and discounts on your prepaid card purchases.

**Comment by Kryptoniq** [comment]
1. Your bitcointalk announcement thread has insufficient information.
2. There is only one token holder.

**Comment by zacklif** [comment]
1. Please let me know what is the missing information? What else you'd like to know?
2. Since there is no need to raise money, the token is not distributed via ICO, but we'd like our first customers to be able to trade it on exchange. how many token holders are needed in order to get listed?

**Comment by Kryptoniq** [comment]
1. I've already listed the reasons.
2. We can't disclose.

**Comment by zacklif** [comment]
In your response you've only mentioned there is insufficient information
It would help us very much to understand what's missing, so we'll be able to complete the information

I believe you're referring to another thread regarding the reasons you already listed
Could you please send me the link for those reasons you already listed?

Thanks,
Zack

**Comment by Kryptoniq** [comment]
Hi,
As stated, your bitcointalk announcement thread is incomplete. It contains only 31 words.
There are only 5 token holders ATM.

**Comment by Kryptoniq** [comment]
I will have to close this issue as per new listing guidelines.
No update for the past 15 days.
