### ISSUE TITLE
Cibus World Token Listing Request

### ISSUE THREAD

**Issue by arinddas** [forkdelta/tokenbase#365]
**Contract address:**
0xBBCA7197c4BF733d8fD38751733864B70851CB87

**Issuer's official website:**
https://www.cibus.world

**Official contract address confirmation:**

Contract Address information is displayed publicly in our website landing page. 3 - 4 sections scrolling b below.
website: https://www.cibus.world

**A link to a third-party review or discussion of the token:**

Reddit: https://www.reddit.com/user/cibusworld/
BitcoinTalk: https://bitcointalk.org/index.php?topic=2713416.new#new
Github: https://github.com/cibusworld  
Linkedin: https://www.linkedin.com/company/18429022

**Description:**

Please find the details below:

Total registered users all of them has tokens with them : 78k

Active Telegram users: 17.9k +

Token Listing confirmation:

**Etherdelta: Token/Symbol listing in the drop down combo box confirmed.
5iquant (Chinese exchange): Token listing confirmed**

**Project Short Description:**

CIBUS has eight main functionalities. CIBUS Trace is the food tracking and traceability function that allows food products and dietary supplements to be traced through the supply chain. The information is stored on blockchain and hence will be incorruptible. CIBUS Social is an incentivized social networking platform for global collaboration on food and related areas of interest. CIBUS trade and CIBUS Retail are trading platforms for businesses and consumers respectively. The employ incorruptible vendor rating mechanisms and are facilitated by smart-contracts.
CIBUS AD is an inbuilt analytics and content evaluation tool that allows businesses to create highly targeted advertisements. It also ensures that CIBUS users get the most relevant advertisement. CIBUS escrow is a standard five stage escrow services that is created using smart contracts. CIBUS Affiliate is a performance based market affiliation program and CIBUS logistics is a multi modal, global transport solution that tracks the conditions of transit using smart contracts.
CIBUS tokens are one of the medium of trasnaction within the CIBUS eco-system.

**White paper link:** https://drive.google.com/file/d/1KrPfMOiahljZNWj0Oo-8TunwJrs-Wr-d/view

Duration of ICO: February 28th, 2018 to March 28th, 2018

ICO Website Link: https://www.cibus.world

Total Supply : 100 million Cibus Tokens

Price: 1000 CBT = 1 ETH

Token Address:

0xBBCA7197c4BF733d8fD38751733864B70851CB87

**Token Traker Etherscan Link:**

https://etherscan.io/token/0xbbca7197c4bf733d8fd38751733864b70851cb87

**Token Contract Source Code (Verified by Etrherscan):**
https://etherscan.io/address/0xbbca7197c4bf733d8fd38751733864b70851cb87#code

**Token Contract Audit Report:**

https://github.com/cibusworld/ICO/blob/master/CIBUS Token Contract Audit Report.pdf

Token Contract Testing Details:

https://github.com/cibusworld/ICO/blob/master/CIBUS TOKEN Testing Details.pdf

**Adviser Profiles**
	
NITIN MALHOTRA - https://www.linkedin.com/in/nitin-malhotra-07434094/

SAURAV TOMAR - https://www.linkedin.com/in/sauravtom/

MICHIO JIBIKI - https://www.linkedin.com/in/michio-jibiki-54408451/

INDRANIL SAMADDAR - https://www.linkedin.com/in/indranil-samaddar-9911647/

DIPANKAR BOSE - https://www.linkedin.com/in/dipankar-bose-92908715/

MART GITANA GASGONIA - https://www.linkedin.com/in/mart-gitana-5a2833158/

ZAHID IMRAN - https://www.linkedin.com/in/zahid-imran-86031557/

**Cibus Team**
	
ARINDAM BISWAS - https://in.linkedin.com/pub/arindam-biswas/1/613/555
UPASANA NATH - https://www.linkedin.com/in/upasana-nath-9b131b12a/
JHIMLI MUKHERJEE - https://www.linkedin.com/in/jhimli/
NAGA PRADEEP . V - https://www.linkedin.com/in/nagapradeep/
ARBIND PRASAD - https://www.linkedin.com/in/arbind-prasad-bb20431b/
SOUMEN PAUL - https://www.linkedin.com/in/soumen-paul-4130441b/
AKHIL OJHA - https://www.linkedin.com/in/akhil-ojha-74a07317/
KENNETH MBEH - https://www.linkedin.com/in/kenneth-mbeh-96099b42/
MALACHI VICTOR - https://www.linkedin.com/in/malachi-victor-b63b628b/
JATIN KAPADIA - https://www.linkedin.com/in/jatin-kapadia-59a75914/
RAM MALAPATI - https://www.linkedin.com/in/rammalapati/
SHAJID MAHMOOD - https://www.linkedin.com/in/shajid-mahmood-6b71bb150/

**List Of ICO listing sites where Cibus World is listed:**

1. https://icobench.com/ico/cibus   - Rating 4.0 as on 01-03-2018
2. https://www.coinmarketplus.com/token/cibus-2/
3. http://icotick.com/
4. https://icolink.com/data-analytics-ico-list/ad/cibus,505.html
5. https://www.icoalert.com/?q=cibus&is_v=1
6. https://www.coinhills.com/ico/view/cibus/

**Social Sites:**
https://www.reddit.com/user/cibusworld/
https://t.me/cibus_world
https://bitcointalk.org/index.php?topic=2713416.new#new
https://twitter.com/cibusworld
https://medium.com/cibusworld
https://facebook.com/cibus-1812771722347122/

Hoping a positive response from your side.

**Comment by Kryptoniq** [comment]
There is only one token holder.

**Comment by arinddas** [comment]
Thanks for the reply. 
Duration of ICO is February 28th, 2018 to March 28th, 2018. 
**After the ICO is complete, then the tokens will be distributed.** 

You can see the official information at https://www.cibus.world

We hope that you will consider us.

**Comment by Kryptoniq** [comment]
I'm closing this issue as per new listing guidelines.
Only one token holder ATM and no update for the past 11 days.
