### ISSUE TITLE
NEXT PAYMENT GOLDEN LISTING FORKDELTA

### ISSUE THREAD

**Issue by febieki23** [forkdelta/tokenbase#367]
Contract address: 

0xfc7b16a373c2ca3770a6c1b234852eeefdce892a
--

Issuer's official website: nxo.store

Official contract address confirmation:

0xfc7b16a373c2ca3770a6c1b234852eeefdce892a
--

A link to a third-party review or discussion of the token:

Description:
We invite you to participate in our Bounty Campaign and help the NXO project to build a wide and strong community.

" NXO is multipurpose coin NXO is not just for coins for trading only, but for payments as well. 
We will load goods from the refreshments of some Famous Online Shop Sites, even those that are difficult to buy when not using a credit card. 
NXO will ease Payment with NXO without need Paypal or maybe card credit. 
NXO will choose The Best Seller On A Large site like Amazon,alibaba, and other. 
We will also load home products to be loaded and shipped to all over the world justone click cekout goods will be ready to be sent

**Comment by Kryptoniq** [comment]
1. Make the contract address available on your website. 
2. Provide a link to a third-party review or discussion of the token.

**Comment by tradedbytony** [comment]
Open PR at #475
