### ISSUE TITLE
Updated the contract details of HAO

### ISSUE THREAD

**Issue by hentaisolo** [forkdelta/tokenbase#368]
The old contract : 0xc9b89f6b5301f554b9adc6d4a871c3279820de40 - Token Symbol : HAO & Decimals : 18

Official website: http://hentaisolo.com

Updated the contract details of HAO :
New contract : 0x733172c38a6956206c9d4a902fd8a045c7f822f0
Token Symbol : HAO
Decimals : 0

**Comment by Kryptoniq** [comment]
Please kindly provide link to an official announcement of change of contract address / swap.

**Comment by hentaisolo** [comment]
Please check link confirm pls : http://hentaisolo.com
It is noticeable on the homepage.
Thanks

**Comment by freeatnet** [comment]
Closing due to #567.
