### ISSUE TITLE
Listing request - Blocklancer

### ISSUE THREAD

**Issue by michael-kaiser** [forkdelta/tokenbase#370]
Contract address: 0x63e634330A20150DbB61B15648bC73855d6CCF07

Issuer's official website: www.blocklancer.net

Official contract address confirmation:

The address can be found here: https://blocklancer.net/tokensale/buy

A link to a third-party review or discussion of the token:

Bitcointalk: https://bitcointalk.org/index.php?topic=1974481.0
ICOBench: https://icobench.com/ico/blocklancer
ICOBazaar: https://icobazaar.com/v2/blocklancer/

Description:
Blocklancer is a Distributed Autonomous Job Marketplace (DAJ) operating on the Ethereum Blockchain. Blocklancer is our collaborative vision of an entirely self-regulatory platform for finding clients/projects and ensuring jobs are completed efficiently and fairly. Blocklancer is changing the way freelancing works for both the freelancer and the customer, concentrating on building a trustworthy platform all stakeholders can rely on. Blocklancer does this by minimalizing fees and introducing a decentralized tribunal system to guarantee every dispute case is settled fairly and that no one loses out — we can finally wave goodbye to fraud in freelancing.

**Comment by Kryptoniq** [comment]
Custom Ticker: Lancer 
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x63e634330a20150dbb61b15648bc73855d6ccf07, http://www.blocklancer.net/

**Comment by michael-kaiser** [comment]
Thank you!

**Comment by JonathonDunford** [comment]
@michael-kaiser 

Thank you for your request! Lancer Token has been listed: https://forkdelta.github.io/#!/trade/LANCER-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
