### ISSUE TITLE
Listing request - WIZ

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#372]
Website: https://crowdwiz.io
Whitepaper: https://crowdwiz.io/docs/whitepaper-en-1507561917.pdf
Description: The WizFund platform is a liberated ecosystem of investors, bringing flexibility and freedom through advanced technology. Every member has the right to vote and take the decision where and how the fund should invest. Token-holders are free to invest in newly-created funds or establish WizFunds of their own. A software wizard will guide you through the process. 

Contract address: https://etherscan.io/token/0x2f9b6779c37df5707249eeb3734bbfc94763fbe2
Symbol: WIZ
Full Name: CrowdWizToken
Decimals: 18

Link to confirm contract: https://medium.com/@Crowdwiz.io/how-to-claim-wiz-tokens-to-your-erc-20-compatible-wallet-2c20de5e0298

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2175726
https://venturebeat.com/2017/09/13/blockchain-startup-crowdwiz-puts-a-decentralized-spin-on-fund-management

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x2f9b6779c37df5707249eeb3734bbfc94763fbe2, https://crowdwiz.io/

**Comment by JonathonDunford** [comment]
CrowdWizToken has been listed: https://forkdelta.github.io/#!/trade/WIZ-ETH
