### ISSUE TITLE
Listing request - CND

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#373]
Website: https://cindicator.com
Whitepaper: https://cindicator.com/Cindicator_WhitePaper_en.pdf
Description: Your personal Cryptocurrency Market measurement tool for spotting time-limited market opportunities.

Contract address: https://etherscan.io/token/0xd4c435f5b09f855c3317c8524cb1f586e42795fa
Symbol: CND
Full Name: Cindicator
Decimals: 18

Link to confirm contract: https://cindicator.com/add-metamask.pdf

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2062875
https://crushcrypto.com/analysis-of-cindicator
https://bitcoinexchangeguide.com/cindicator

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xd4c435f5b09f855c3317c8524cb1f586e42795fa, https://cindicator.com/

**Comment by JonathonDunford** [comment]
Cindicator Token has been listed: https://forkdelta.github.io/#!/trade/CND-ETH
