### ISSUE TITLE
Listing request - LGO

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#375]
Website: https://legolas.exchange
Whitepaper: https://legolas.exchange/static//public/legolas-whitepaper-en.pdf?v=13
Description: Legolas Exchange creates a new decentralized blockchain protocol that guarantees full transparency and prevents front-running and market manipulation.

Contract address: https://etherscan.io/token/0x123ab195dd38b1b40510d467a6a359b201af056f
Symbol: LGO
Full Name: LGO Token
Decimals: 8

Link to confirm contract: https://twitter.com/LegolasExchange/status/969888161848586241 (their official Twitter account)

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2383397
https://cointelegraph.com/news/big-investors-coming-a-new-decentralized-exchange-makes-plans-to-lure-them-all

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
https://etherscan.io/token/0x123ab195dd38b1b40510d467a6a359b201af056f, https://legolas.exchange

**Comment by JonathonDunford** [comment]
LGO Token has been listed: https://forkdelta.github.io/#!/trade/LGO-ETH
