### ISSUE TITLE
Listing request - UST

### ISSUE THREAD

**Issue by Semipyatnov** [forkdelta/tokenbase#380]
USERVICE TOKEN

Contract address: 
0xf62baa1997f04f165edd100d78241e07617f6ce6
Symbol: UST
Full Name: Uservice Token
Decimals: 18

Issuer's official website:
https://www.usrv.io

Official contract address confirmation:
We released our token contract adress here:  https://t.me/userviceico/10420

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2432730
https://icorating.com/analytics/basic/uservice-basic-review/

Whitepaper: https://usrv.io/en-US/whitepaper.pdf

Description:

Our token is utility token based on ERC20 protocol. UST token will allow people to buy car repair services, buy cars, advertisment on our platform (Uservice platform) e.t.c. with more than 13.000 autorepairservices all over the world. 
Uservice platform - is a blockchain platform that will unite all players of the automotive industry and will help them to make their business processes more effective.
For more information visit - www.usrv.io

**Comment by Semipyatnov** [comment]
Also we will make a donation for fast listing.

**Comment by Kryptoniq** [comment]
Hi, can you make your contract  address available on your website?
