### ISSUE TITLE
Listing request - GTO

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#381]
Website: https://gifto.io
Whitepaper: https://www.gifto.io/GIFTO_Whitepaper_V2.0_20171204.pdf
Description: The Decentralized Universal Gifting Protocol for Global Content Creators. 

Contract address: https://etherscan.io/token/0xc5bbae50781be1669306b9e001eff57a2957b09d
Symbol: GTO
Full Name: Gifto
Decimals: 5

Link to confirm contract: https://support.otcbtc.com/hc/zh-cn/articles/360001269412-%E4%BB%80%E4%B9%88%E6%98%AFGTO- (OTCBTC was listed as an official exchange by Gifto and the announcement can be found at https://twitter.com/gifto_io/status/968440073963298816, therefore the contract that OTCBTC shows can be trusted). And this contract is also the same as https://bibox.zendesk.com/hc/en-us/articles/360000364913-GIFTO-GTO- which is another official exchange (official announcement at https://twitter.com/gifto_io/status/957997131775791104).

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2356301
https://icobench.com/ico/gifto

**Comment by lattedesu** [comment]
+1, please add this

Thanks!

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xc5bbae50781be1669306b9e001eff57a2957b09d, https://gifto.io/
