### ISSUE TITLE
 my requset I want to list my token NRC

### ISSUE THREAD

**Issue by humairk** [forkdelta/tokenbase#382]
Website: https://thenitrocoin.org
Issuer's official website:https://thenitrocoin.org
Contract address: https://etherscan.io/token/0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
Contract address: 0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
Full Name: Nitrocoin
Symbol: NRC
Decimals: 0

reddit links : https://www.reddit.com/user/nitrocoinNRC/
Link to confirm contract: https://twitter.com/NitrocoinNRC
facebook Link: https://www.facebook.com/nitrocoinNRC/
Third-party comment(s) on the token:new join bitcointalk.org; https://bitcointalk.org/index.php?topic=3105174.
Whitepaper: https://thenitrocoin.org/whitepaper/NRC_WAIT_P.pdf

Description: The Decentralized Coin pegged to stock market in nitrocoin by fund

**Comment by Kryptoniq** [comment]
Hi, we only need one website address.
Also, provide a link to a third-party review or discussion of the token.

**Comment by humairk** [comment]
Website: https://thenitrocoin.org
Whitepaper: https://thenitrocoin.org/whitepaper/NRC_WAIT_P.pdf
Description: The Decentralized Coin pegged to stock market in nitrocoin by fund

Contract address: https://etherscan.io/token/0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
Symbol: NRC
Full Name: Nitrocoin
Decimals: 0

Link to confirm contract: https://support.thenitrocoin.org/test/
 which is another official  announcement at https://twitter.com/NitrocoinNRC

Third-party comment(s) on the token:
new join bitcointalk.org; https://bitcointalk.org/index.php
https://t.me/joinchat/AAAAAEh18IxJp-_TmSRV4A

**Comment by humairk** [comment]
Website: https://thenitrocoin.org
Whitepaper: https://thenitrocoin.org/whitepaper/NRC_WAIT_P.pdf

Issuer's official website:https://beta.proofdashboard.com/users/16852/assets/11313

Description: The Decentralized Coin pegged to stock market in nitrocoin by fund

Contract address: https://etherscan.io/token/0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
Symbol: NRC
Full Name: Nitrocoin
Decimals: 0

Link to confirm contract: https://support.thenitrocoin.org/test/
which is another official announcement at https://twitter.com/NitrocoinNRC

Third-party comment(s) on the token:
new join bitcointalk.org; https://bitcointalk.org/index.php
https://t.me/joinchat/AAAAAEh18IxJp-_TmSRV4A

**Comment by tradedbytony** [comment]
Massive spam: #498, #480, #437, #382, #499 and #482 are all about this NRC token.
