### ISSUE TITLE
listing of Flash Token

### ISSUE THREAD

**Issue by Webinvestart** [forkdelta/tokenbase#383]
Contract address:
https://ethplorer.io/address/0x25c8ca98fe9d59ceef5e0175abae40d4caa60af9
Issuer's official website:
https://flashtoken.io
Official contract address confirmation:

https://github.com/flashtoken
https://ethplorer.io/address/0x25c8ca98fe9d59ceef5e0175abae40d4caa60af9
A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2574672.140
https://t.me/flashcommunityru

Description:

ticker is FTOKEN

**Comment by Webinvestart** [comment]
Please add ticke FTOKEN to
https://forkdelta.github.io/#!/trade/0x25c8ca98fe9d59ceef5e0175abae40d4caa60af9-ETH

**Comment by Kryptoniq** [comment]
Hi, please make the contract address available on the website.

**Comment by Webinvestart** [comment]
Hello already done look it please in flashtoken.io

**Comment by Webinvestart** [comment]
Hello already done look it please in flashtoken.io
![unnamed](https://user-images.githubusercontent.com/37086443/37026855-b63e00c4-2140-11e8-8e2d-7070a1f44cd1.png)

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x25c8ca98fe9d59ceef5e0175abae40d4caa60af9, https://flashtoken.io

**Comment by Webinvestart** [comment]
Hello tell please when we wait change ticker?

**Comment by JonathonDunford** [comment]
@Webinvestart 


Thank you for your request! Flash Token has been listed: https://forkdelta.github.io/#!/trade/FTOKEN-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
