### ISSUE TITLE
Broken CS balances after today's change

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#384]
You guys changed from CREDITS to CS, replacing the old CS with this new one, but seems like the order book got broken in the process.

The sell orders on https://forkdelta.github.io/#!/trade/CS-ETH haven't updated and all the obviously much-lower-than-they-should-be ones don't exist. Not sure about the buy orders but worth taking a lot at as well.

**Comment by Kryptoniq** [comment]
@freeatnet cc.

**Comment by freeatnet** [comment]
@tradedbytony Sorry for the delayed response. Just to make sure: if you clear browser cache and reload the page, does the issue still appear?

**Comment by tradedbytony** [comment]
@freeatnet yep. Tried on chrome (desktop/mobile) and Brave and still those 2 super lower entries still show up there. There more of them but most have gone away now except those 2. And of course when you try to buy them it says they aren't there and that you gotta wait for the order book to update.

**Comment by freeatnet** [comment]
@tradedbytony Ah. Ok, I'll force-refresh the orderbook. That said, backend and frontend communicate in terms of contract addresses, so renaming things wouldn't leave orders behind. The orders were most likely legitimate (perhaps posted by slightly confused users — the confusion is our fault).

Thanks for reporting this issue!

**Comment by tradedbytony** [comment]
Thanks for the refresh! That did the trick.

**Comment by JonathonDunford** [comment]
@tradedbytony 

Not sure this is the right place, but can't find another way to contact you. Can you reach out to me on Discord? BigBrother.
