### ISSUE TITLE
Digitex Futures (DGTX) token listing

### ISSUE THREAD

**Issue by alchocron** [forkdelta/tokenbase#385]
Contract address: 0x1c83501478f1320977047008496dacbd60bb15ef

Issuer's official website: https://digitexfutures.com/

Official contract address confirmation:
N/A

A link to a third-party review or discussion of the token: https://www.reddit.com/r/DigitexFutures/

Description: 
Digitex is a commission-free futures exchange with its own native cryptocurrency, the DGTX token.
Traders speculate on the price of Bitcoin against the US dollar, but their trading profits and losses are paid out in DGTX tokens. This means that traders need DGTX tokens to enter a trade, and this creates demand for DGTX tokens from traders.
Digitex covers the cost of running the exchange by creating a small number of new tokens each year instead of charging transaction fees on trades. Commission-free futures markets on a stable, fast and secure trading platform will attract large numbers of traders who must buy DGTX tokens to participate, creating increased demand for DGTX tokens that offsets the small inflationary cost of creating new tokens.

**Comment by Kryptoniq** [comment]
1. Provide an official link that verifies the contract address.
2. Provide a link to a third-party review or discussion of the token.

**Comment by alchocron** [comment]
Hello all;

Please find answer to your questions.

1. https://etherscan.io/address/0x1c83501478f1320977047008496dacbd60bb15ef
2. https://cryptoslate.com/coins/digitex/

Please let me know if anything further is required.
thanks


Alberto Chocron
p. 305.335.6540
e. alberto@chocronben.com<mailto:alberto@chocronben.com>

**Comment by Kryptoniq** [comment]
Hi, Etherscan is excluded. The contract should be on the project's website or any official handle belonging to the project.

**Comment by alchocron** [comment]
Hello;

Does this satisfied your request?

https://digitexfutures.com/#smartdec

thank you and looking forward to earing from you soon

Alberto C

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x1c83501478f1320977047008496dacbd60bb15ef,  https://digitexfutures.com/

**Comment by alchocron** [comment]
Thank you, please let us know when available.

**Comment by freeatnet** [comment]
@alchocron Thank you for your request! DigitexFutures has been listed: https://forkdelta.github.io/#!/trade/DGTX-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
