### ISSUE TITLE
Please list Handelion (HION)

### ISSUE THREAD

**Issue by rdenke** [forkdelta/tokenbase#386]
Contract address: 0xa089273724e07644da9739a708e544800d925115

Issuer's official website: https://handelion.io/

Official contract address confirmation: https://handelion.io/faq/  (click on How to get HION tokens using bitcoin...)

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2251472

Description: 
Handelion is an open blockchain ecosystem for co-funded trade. Smart cooperation algorithms enclosed in digital contract functionality allow any business to benefit from it:

    investors fund small and medium enterprises to buy goods from manufacturers,
    buyers get financial leverage,
    manufacturers sell goods with full prepayment,
    logistics companies receive payments promptly and efficiently use the infrastructure.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xa089273724e07644da9739a708e544800d925115, https://handelion.io/

**Comment by freeatnet** [comment]
Thank you for your request! HION Token by Handelion has been listed: https://forkdelta.github.io/#!/trade/HION-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
