### ISSUE TITLE
Meridian (MDN) - Contract Update

### ISSUE THREAD

**Issue by MeridianMDN** [forkdelta/tokenbase#388]
We have issued a new contract.

Old address: 0x550879F1778b575DDC8EB2095fBC9f4783b5f2F6

New Address: 0x1a61250a2bea646478184730d25648811bd429fe
Announcement of change: https://bitcointalk.org/index.php?topic=2157860.msg31653641#msg31653641
Website: https://mymdn.io/terms/

Many thanks

**Comment by Kryptoniq** [comment]
The information provided has been confirmed to be accurate.
The contract address will be updated in the next few days.
Thank you.
0x1a61250a2bea646478184730d25648811bd429fe,  https://mymdn.io

**Comment by JonathonDunford** [comment]
@MeridianMDN 

New token address has been listed as MDN: https://forkdelta.github.io/#!/trade/MDN-ETH
Legacy address has been left as MDNOLD

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
