### ISSUE TITLE
Add Dragon (DRG) Token

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#39]
Moving from https://github.com/forkdelta/forkdelta.github.io/pull/52

> Dragon Coin, or DRG, is an ERC20 / Ethereum Utility token to participate at Casinos using Dragon's Blockchain facilities managed by Dragon parter junkets. DRG tokens are exchanged for DGC (Dragon Global Chips), a cryptocurrency gaming chip, at Casinos allowing both players and Casinos to take advatange of the added transparency & security of the Blockchain.

* Issued by https://drgtoken.io
* https://etherscan.io/token/0x814f67fa286f7572b041d041b1d99b432c9155ee
* 401 holders
* 607 transactions
* Publicly announced on https://icodrops.com/drg-token/
* Has notable mentions [1]
* Contract address 0x814f67fa286f7572b041d041b1d99b432c9155ee confirmed on Twitter[2]

[1]: https://www.reuters.com/article/us-bitcoin-macau-ico/dragon-bets-on-blockchain-to-cut-costs-for-asias-gambling-business-idUSKBN1E10DO
[2]: https://twitter.com/DragonCoin/status/957912803578392577

**Comment by soliditeam** [comment]
Has this been added?

**Comment by freeatnet** [comment]
@soliditeam It's up

**Comment by soliditeam** [comment]
Thanks man, but https://etherdelta.com/#DRG-ETH doesnt work :)

**Comment by freeatnet** [comment]
@soliditeam We aren't etherdelta.
