### ISSUE TITLE
List LGO Legolas Token

### ISSUE THREAD

**Issue by cliftrader** [forkdelta/tokenbase#390]
Contract address: '0x123ab195dd38b1b40510d467a6a359b201af056f'

Issuer's official website: https://legolas.exchange/

Official contract address confirmation:
https://github.com/legolasexchange
https://support.legolas.exchange/hc/en-us/articles/360000038511-Will-the-code-be-pushed-onto-GitHub-

A link to a third-party review or discussion of the token:
https://icorating.com/analytics/indepth/legolas-exchange-rating-review/

Description:
 THE FIRST DEMONSTRABLY FAIR PREMIUM EXCHANGE.
Legolas Exchange incorporates a decentralized ledger within its proprietary centralized 
platform in order to neutralize front-running and guarantee the unalterability, 
temporality, and transparency of the order book.

Legolas Exchange's unique hybrid model and strategic partnerships provide a fair and 
secure trading environment in which every type of transaction, intra-chain, cross-
chain, and crypto/fiat, is executable.

Thus, unlike fully decentralized exchanges, Legolas can cover 100% market share with 
full transparency and security.

**Comment by tradedbytony** [comment]
It's already been requested and cleared for listing. Issue #375

**Comment by Kryptoniq** [comment]
#375
