### ISSUE TITLE
Humble Request and Payment Process done for Listing Token/Coin Information

### ISSUE THREAD

**Issue by Aniket0512** [forkdelta/tokenbase#391]
Contract address: 0x9d2F8e290114e09f9b1da8d8aDe8AB96270217b4

Issuer's official website:  https://amazingcoin.net

Official contract address confirmation: https://etherscan.io/tx/0x7c7c2e622cf75394abc4cf32944be8c4d2ce13b958b6d9737c08da35c307eb99

https://ethplorer.io/address/0x9d2f8e290114e09f9b1da8d8ade8ab96270217b4#pageSize=100&transfers=2

A link to a third-party review or discussion of the token:

5. Link to blog (optional):http://amazingcoin.blogspot.in (http://amazingcoin.blogspot.in/)

6. Link to Facebook (optional):https://www.facebook.com/amazingcoin.net

7. Link to twitter (optional):https://twitter.com/CoinAmazing

8. Link to bitcointalk (optional):https://bitcointalk.org/index.php?topic=2292487

9. Link to github (optional): https://github.com/amzcoin/amz

10. Link to Youtube (optional): https://www.youtube.com/channel/UCpGdExPH38D4Df_WsW4TLKA/featured

11. Link to whitepaper (optional):https://amazingcoin.net/AMZ-WP.pdf

Description:
AmazingCoin is Blockchain based decentralized multi cryptocurrency payment gateway. It makes worldwide transactions between consumers, merchants, businesses, distributors, and community by leveraging the power of blockchain technology. Use AmazingCoin to send, receive & make payments without middleman using stable, secure and fast Blockchain network.

Thank You
Ankit 
Mail: Amazingcoin2017@gmail.com

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x9d2f8e290114e09f9b1da8d8ade8ab96270217b4, https://amazingcoin.net/

**Comment by Aniket0512** [comment]
Thanks

I,m waiting .

**Comment by Aniket0512** [comment]
Plz sir,
Add AmazingCoin Waiting me

**Comment by JonathonDunford** [comment]
@Aniket0512 

Can you please provide some sort of third party verification of the project. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc.

**Comment by freeatnet** [comment]
This piece of code on the website got me wondering <sup> [1] </sup>

```
<script async="" type="text/javascript" src="./What is Bitstrades lending platform _ Bitstrades_files/v2">
```

Lo and behold, the original: https://bitstrades.com/

[1]: http://archive.li/W3g1E

**Comment by Kryptoniq** [comment]
Oops. Thanks for detecting this @freeatnet.
