### ISSUE TITLE
Please list Stashpay (STP)

### ISSUE THREAD

**Issue by rdenke** [forkdelta/tokenbase#392]
Contract address: 0xecd570bBf74761b960Fa04Cc10fe2c4e86FfDA36

Issuer's official website: https://stashpay.io/

Official contract address confirmation:  https://twitter.com/stashpay/status/951637472387121157

A link to a third-party review or discussion of the token: https://bitcointalk.to/index.php?topic=2114814

Description:
Stash is a next generation open source digital currency for the real world. A key advantage of Stash is that it solves numerous problems being encountered by other cryptocurrencies. Stash does this by bringing together many ground-breaking blockchain technologies while using the gold standard in cryptocurrency privacy.

In addition to comprising critical features for an efficiently functioning open decentralized autonomous network such as self-governance and self-funding, Stash also incorporates instantaneous transactions (StashSwift), increased network capacity, low transaction fees and state-of-the-art zero-knowledge cryptography.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xecd570bbf74761b960fa04cc10fe2c4e86ffda36, https://stashpay.io/

**Comment by JonathonDunford** [comment]
Thank you for your request! STASHPAY has been listed: https://forkdelta.github.io/#!/trade/STP-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated. 

@rdenke
