### ISSUE TITLE
Coin Listing: exominium.com

### ISSUE THREAD

**Issue by ExominiumCV** [forkdelta/tokenbase#393]
Contract address: 0x8c9d3968c6d4ba87b343d8a949238375371c1e9b

Issuer's official website: http://exominium.com/

Official contract address confirmation:
<The contract address is mentioned in the highlight sect of the given page (http://exominium.com/?fca_lpc_skip=579 )& GitHub (https://github.com/ExoMinium/sol/blob/master/Smart%20contract%20v1.5.txt)>

A link to a third-party review or discussion of the token:

Description:

**Comment by ExominiumCV** [comment]
Details: 
+---
+addr: '0x8c9d3968c6d4ba87b343d8a949238375371c1e9b'
+decimals: 6
+links:
+- Blog: http://exominium.com/blog/
+- Github: https://github.com/ExoMinium
+- Email: cvee.k@exominium.com; info@exominium.com
+- Twitter: https://twitter.com/exominium
+- Website: https://exominium.com/
+- Whitepaper: http://exominium.com/wp-content/uploads/2018/03/Lite-Paper-V1.1.1.pdf
+name: ExoMinium
+symbol: EXO

**Comment by Kryptoniq** [comment]
1. Provide a link to link to a third-party a third-party review or discussion of the token.
2. Provide a description.

**Comment by Kryptoniq** [comment]
I will have to close this issue as per new listing guidelines.
No update for the past 17 days.
