### ISSUE TITLE
Fork of a listed coin under consideration

### ISSUE THREAD

**Issue by Bytesize87** [forkdelta/tokenbase#394]
Dear Forkdelta Team, 

On behalf of the new Zlancer ZCG team, I wanted to give you a heads-up about a strong possibility that we will implement a fork in the upcoming few weeks with an increased coin supply, given that the project needs to take a new direction and the lack of funds to support the development. You can check the background on the ZCG Telegram group, the old development has been passed on to 3 motivated members of the community, from which I am part of. 

We would like to inquire about 3 points: 

1) whether you support the forking process and will enlist the new token on your platform?

2)  what information you would require from us once we have taken the decision to fork? 

3) how much time we can approximately expect to get the forked coin enlisted from the moment we confirm that request?

Many thanks in advance and kind regards; 
Abdelaziz, for the ZCG community.

**Comment by freeatnet** [comment]
Hey @Bytesize87!

Assuming that the fork be in the form of a new ERC20 contract, you can request an update to either delist or deprecate the old token, or simply add the new token. In either case, we will need a link to an official announcement of the change from the previously listed official source. You can expect the update within 5 days of the request.

Hope that answers your questions!
