### ISSUE TITLE
Enlistment of token Cikka

### ISSUE THREAD

**Issue by thegodgital** [forkdelta/tokenbase#395]
Contract address: 0x6be5744e45292144d6814ffbedcb6aad1bb287e4

Issuer's official website: http://cikkaa.com

Official contract address confirmation:

A link to a third-party review or discussion of the token:

Description:
Cikka Coin, or CiC, is an ERC20 / Ethereum Utility token used to participate in The Go Dgital block chain ecosystem. It is a decentralized Ad Exchange designed to disrupt and replace the traditional digital advertising models by providing a transparent, focused solutions for advertisers to collaborate with Ad publishers and reach to the best potential clients.

**Comment by Kryptoniq** [comment]
1. There are only 2 token holders
2. Contract address cannot be found on the website
3. No link to a third-party review or discussion of the token.

**Comment by thegodgital** [comment]
Number of token holders will increase very soon. Contract address has already been added in our website. As far as discussion in third-party review is concerned, it will be taken care.
