### ISSUE TITLE
NeckCoin Listing

### ISSUE THREAD

**Issue by NeckCoin** [forkdelta/tokenbase#396]
Contract address: 0xc67e01f0b416b884a2896fae3401e86d605ba47e

Issuer's official website: https://twitter.com/NeckCoin
                                      main site is in development

Official contract address confirmation: https://twitter.com/NeckCoin/status/966353902625996804
A link to a third-party review or discussion of the token: https://lescovex.featureupvote.com/suggestions/5756/neck

Description:

Neck Network is a social media platform aimed at crypto currency investors and enthusiasts to connect with like minded people while earning the platform currency (NECK Coin) for completing milestones, milestones that are designed to help the site grow and add value to its content.

**Comment by Kryptoniq** [comment]
Please read and understand the token Listing instructions. 
https://www.reddit.com/r/ForkDelta/comments/7tntnz/how_to_get_an_erc20_token_listed_on_forkdelta/

**Comment by NeckCoin** [comment]
i have  read and i do understand, i don't see what the problem was? can you
tell me the specific problem so i can correct it?
thanks

**Comment by Kryptoniq** [comment]
1. Your website can not be Twitter
2. You did not provide a link to a third-party review or discussion, rather,  you provided a link to an exchange voting of your token.

**Comment by NeckCoin** [comment]
Ok sorry, will these work

1. http://www.neckcoinico.com
2. https://bitcointalk.org/index.php?topic=3089365.new#new

Thanks
