### ISSUE TITLE
TOKEN LISTING

### ISSUE THREAD

**Issue by JOINMATRIX** [forkdelta/tokenbase#399]
NAME: MATRIX
SYMBOL: ONE
TOKEN ADDRESS: 0x871A71438029549A836c042D3Bd0e88cA6c88388
WEBSITE: www.joinmatrix.net
SUPPLY: 100,000,000,000,000
FORUM: https://bitcointalk.org/index.php?topic=3006405.new#new

Description: MATRIX is a token that allows investors to join a society where events and meetings be held all over the world to discuss cryptocurrency and its applications and uses in many other industries. We hope to be able to bring investors together to create a very strong cryptocurrency community.

**Comment by Kryptoniq** [comment]
#210
