### ISSUE TITLE
LISTING REQUEST - THUG COIN 

### ISSUE THREAD

**Issue by THUGCOIN** [forkdelta/tokenbase#400]
1. Description:

THUG COIN 

Connecting thugs and your gang on the blockchain

Using the breakthrough technology of anonymous cryptocurrencies and the blockchain ledger. Real thugs themselves developed THUG Coin as the official cryptocurrency of the thug life around the world. THUG Coin acquires its uniqueness by providing thugs at every end of the globe with worldwide access to other thugs and gangs faster than the speed of light. Do not be fooled… This cryptocurrency is serious sh*t!

Quick facts:

- almost 50K members on Telegram
- over 5K hodlers on etherscan already

2. Contract address:

CONTRACT: 0xfe7B915A0bAA0E79f85c5553266513F7C1c03Ed0
DECIMALS: 18
TOKEN SYMBOL: THUG

3. Issuer's official website:

https://thugcoin.cash/

4. Official contract address confirmation:

Open our website (https://thugcoin.cash/) and you see the contract address icon on your screen. Moreover the contract address can be found in the FAQ section of the website.

5. A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=3077297

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xfe7b915a0baa0e79f85c5553266513f7c1c03ed0, https://thugcoin.cash/

**Comment by JonathonDunford** [comment]
Thank you for your request! THUG Coin has been listed: https://forkdelta.github.io/#!/trade/THUG-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
