### ISSUE TITLE
List SEED "CryptoSeed" Token

### ISSUE THREAD

**Issue by cryptoecology** [forkdelta/tokenbase#402]
Contract address: 0xff1d7f58e90c307a79F66201182Ea4E16854d822

Issuer's official website: http://www.cryptoecology.net

Official contract address confirmation:

http://www.cryptoecology.net/index.php/cryptoseed

A link to a third-party review or discussion of the token:
https://www.facebook.com/groups/1973144009572862/

Description:

A new concept of cryptocurrencies has been born. CryptoSeed wants to become the means of payment for ecotechnological innovation.
The financing support of future projects that will make tomorrow a more sustainable present.

Twitter: @Cryptoseedtoken

Thanks!!!!!

**Comment by Kryptoniq** [comment]
Please provide a link to a third-party review or discussion of the token. Facebook does not qualify.

**Comment by cryptoecology** [comment]
https://bitcointalk.org/index.php?topic=3082702
Its ok?

**Comment by cryptoecology** [comment]
Everything is correct? Do you need something else?
Thanks and best regards.
Paul

**Comment by Kryptoniq** [comment]
There are no comments/reviews  on your bitcointalk announcement thread.

**Comment by Kryptoniq** [comment]
I will have to close this issue as per new listing guidelines.
No update for the past 14 days.
