### ISSUE TITLE
RPCH listing request

### ISSUE THREAD

**Issue by RippleCash** [forkdelta/tokenbase#405]
Contract address: 0x6f0a7aa19425752ff39d9f568c9d930ef30997ed

Issuer's official website: www.ripple-cash.technology

Official contract address confirmation (MUST be linked from official website): https://www.ripple-cash.technology/about-us

A link to a third-party review or discussion of the token, like an established ICO review blog:
https://twitter.com/cash_ripple
https://t.me/ripplecash
https://bitcointalk.org/index.php?topic=3077127.msg31723923#msg31723923 

Description:
Ripple Cash is a global, decentralized cryptocurrency designed with the sole intention of making it a frontline cryptocurrency which can be used in real world for making day-to-day transactions. Ripple Cash is designed to be the next generation payment system. This is a real-time, instant, secure and scalable payment system built on top of Ethereum network.
Github link: https://github.com/Ripple-Cash/RPCH/blob/master/RPCH_ERC20_Contract.txt

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread is shilled and populated by brand new accounts.
Your listing request will be reviewed on a latter date.

**Comment by Kryptoniq** [comment]
I'm closing this issue as per new listing guidelines.
No update for the past 10 days.
