### ISSUE TITLE
Requesting Tokenereum to be added

### ISSUE THREAD

**Issue by tokenereum** [forkdelta/tokenbase#406]
Contract address: 
0x6ED3EFe43df09313C6DE6059B9a443c4fd1Ca535

Issuer's official website: 
https://www.tokenereum.com/

Official contract address confirmation: 
https://www.tokenereum.com/

A link to a third-party review or discussion of the token: 
https://bitcointalk.org/index.php?topic=2375587.0

Description:
Tokenereum is not just another token, it is an initiative to build a strong ERC20/23 community and ERC20/23 Marketplace to bridge all ERC20/23 Tokens to be adapted by businesses and users.

**Comment by Kryptoniq** [comment]
Hi, the project seems to be abandoned in November 2017. Can you clarify on this?

**Comment by tokenereum** [comment]
The project was never abandoned :)
The team was gearing up for a overwhelming launch.

**Comment by Kryptoniq** [comment]
If you insist the project wasn't abandoned, why are the social channels dormant?
Your Telegram group is only but filled with spams.

**Comment by Kryptoniq** [comment]
I will have to close this issue as per new listing guidelines.
No update from the team.
