### ISSUE TITLE
Qualiti Platform

### ISSUE THREAD

**Issue by qualitiplatform** [forkdelta/tokenbase#407]
Contract address: 0x594af62d909456fd735021674a7f9e3d0d0498dc

Issuer's official website: http://qualiti.co

Official contract address confirmation:
http://qualiti.co

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3074046.msg31752346#msg31752346
https://medium.com/@qualitiplatform/

Description:

Qualiti Platform is a directory and marketplace built on the Ethereum blockchain to find local and accurate information on businesses. The driving force for Qualiti would be by the local community and information from local municipals. Businesses can claim their profile to gain traffic and promote their business. Start-ups and establish businesses can reach and connect with one another on our platform to grow their business.

**Comment by Kryptoniq** [comment]
1. There are only 4 token holders.
2. Your bitcointalk announcement thread has insufficient reviews.

**Comment by qualitiplatform** [comment]
Hi,

Where are in the process of sending out the token to addresses. Right now
there is over 90 token holders and we will send more over the weekend.


thanks

**Comment by Kryptoniq** [comment]
Interesting. Your bitcointalk announcement thread has 55 pages filled with comments from newbie accounts within 4 days.
@JonathonDunford cc.

**Comment by qualitiplatform** [comment]
After being added to another exchange a few days ago. The exchange
announcement on Twitter which lead to our bitcoin talk page exploding with
comments. We haven't been able to go through it all to respond any
cocerning questions about our platform our focus has been focusing on our
roadmap. So we plan to answer all questions and issue out more tokens this
weekend. And move forward developing our platform.

So we will like to know if forkdelta willing to work with us or not.We
would like to work and buld relationships with people who wants to work
with us.



Thanks for your time.

**Comment by Kryptoniq** [comment]
I can't find any constructive review on the thread. Only generic replies.

**Comment by qualitiplatform** [comment]
That's disappointing to hear. We cannot control what people say on a
thread. That's not our job, our job is to create a platform for B2Bs to
grow and with the help of making sure the data is accurate you can earn
tokens, and that's what we will continue to do. We have gone through many
pages and answer questions about the platform. So if there's not enough
"constructive reviews" for you to consider us for your platform then its
wasn't meant to be.


Thanks.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x594af62d909456fd735021674a7f9e3d0d0498dc, http://qualiti.co/

**Comment by qualitiplatform** [comment]
Hi,


Thanks forkdelta

**Comment by qualitiplatform** [comment]
Hi,

I wanted to get a brief update from your team on when Qtl will be available
on forkdelta.

Thanks.

**Comment by freeatnet** [comment]
@qualitiplatform Is there a secondary review for your project somewhere? There's just too little _quality_ information about the project.
