### ISSUE TITLE
Requesting WednesdayCoin to be Listed

### ISSUE THREAD

**Issue by aelchim** [forkdelta/tokenbase#408]
Contract address: 0x7848ae8f19671dc05966dafbefbbbb0308bdfabd

Issuer's official website: https://wednesdaycoin.io

Official contract address confirmation: http://wednesdaycoin.io/#about

A link to a third-party review or discussion of the token: https://redd.it/7snqpj
That is the original announcement for the coin and a lot of discussion around the contract occurred there.

Description:
WednesdayCoin is an ERC20 token that can only be sent on Wednesdays. By using the timestamp of the block we can restrict the transfer of the token to a specific day. Since the timestamp is a unix timestamp the timezone is UTC, so this token and only be sent on Wednesday UTC.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x7848ae8f19671dc05966dafbefbbbb0308bdfabd, https://wednesdaycoin.io

**Comment by freeatnet** [comment]
Thank you for your request! Wednesday Coin has been listed: https://forkdelta.github.io/#!/trade/WED-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by aelchim** [comment]
Awesome, thank you!

**Comment by aelchim** [comment]
Hi, thanks for listing WednesdayCoin. We checked it out on forkdelta and noticed that buy and sell orders are going through. We are wondering how that is working from WednesdayCoin perspective since we are restricting the transfer and transfer from method to Wednesdays. We see the amounts updated on forkdelta but not on the blockchain(seems like it’s using approve and approveAndCall). Any help understanding this will be great. Thanks

**Comment by freeatnet** [comment]
@aelchim User balances on the trading contract are managed by the the trading smart contract, so users can trade any day, any time. However, withdrawing from the contract would follow your token's requirements.

**Comment by aelchim** [comment]
Awesome, thanks for the quick response - does that apply for deposits as well?

**Comment by freeatnet** [comment]
Deposits require transfer address-to-address, so that'd only be available on Wednesdays, I assume
