### ISSUE TITLE
Listing USRV Token

### ISSUE THREAD

**Issue by drtiger9** [forkdelta/tokenbase#409]
Contract address: 0xf62baa1997f04f165edd100d78241e07617f6ce6

Issuer's official website: https://usrv.io/

Official contract address confirmation: https://usrv.io/en-US/manual.pdf

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2432730

Description: A single global decentralized blockchain platform for auto service centers on the base of working project.

**Comment by Semipyatnov** [comment]
Maybe UST Token, no?

**Comment by drtiger9** [comment]
Yes.

**Comment by Kryptoniq** [comment]
Hi, I can't find the contract  address on the document you provided.

**Comment by Kryptoniq** [comment]
Duplicate #380
