### ISSUE TITLE
BTCL listing

### ISSUE THREAD

**Issue by BTC-lite** [forkdelta/tokenbase#41]
1. 0x5acd19b9c91e596b1f062f18e3d02da7ed8d1e50
2. http://btclite.org/
3. https://medium.com/@BTClite/how-to-add-btc-lite-btcl-to-mist-and-myetherwallet-a23e78a2e494
4. https://bitcointalk.org/index.php?topic=2471229.0

Mentioned on [1](http://cryptocoindaddy.com/btc-lite-brings-faster-cheaper-transactions/)

**Comment by freeatnet** [comment]
Great work on the listing!

As a side note, you should definitely get HTTPS working on your site.
