### ISSUE TITLE
Listing TORQ Coin - Already listed on yobit.net

### ISSUE THREAD

**Issue by TORQCoin** [forkdelta/tokenbase#412]
Contract address: 
0x1c65c261cb89178b02cf2aee20058b992787d770

Symbol: TORQ

Decimal: 18

Explorer:
https://etherscan.io/token/0x1c65c261cb89178b02cf2aee20058b992787d770

Issuer's official website: 
https://www.torqcoin.io/

Official contract address confirmation: 
https://www.torqcoin.io/

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2653527.0

Description:
TORQ provides solution in mining industry. Currently there is no direct way of transforming crypto currencies like Bitcoin, Ethereum etc to any physical assets. TORQ is building innovation in mining industry which will help users to transform their digital assets to physical assets, which will have more demand and increasing market value.

# Listed on Yobit.net
[Yobit TORQ/BTC](https://yobit.net/en/trade/TORQ/BTC)
[Yobit TORQ/ETH](https://yobit.net/en/trade/TORQ/ETH)
We are listed on yobit.net and trading since weeks now. Also discussion is going-on to get listed on other exchanges. Meanwhile we are looking to get listed on forkdelta to give multiple trading options to our potential investors.

You can check trade details here as well:
https://www.coingecko.com/en/coins/torq-coin/trading_exchanges
https://coinlib.io/coin/TORQ/TORQ+Coin
https://bitgur.com/coin/TORQ
https://coincodex.com/crypto/torq/

Please list!

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x1c65c261cb89178b02cf2aee20058b992787d770, https://www.torqcoin.io/

**Comment by TORQCoin** [comment]
@Kryptoniq I can see other tokens are being listed.

Can I know what is estimated waiting time for TORQ to get listed ?

Thank you!

**Comment by freeatnet** [comment]
Bump.

**Comment by TORQCoin** [comment]
@tradedbytony in which order of request do you list tokens to FD ?

I can see many tokens got listed which has requested just few days back. Our request is pending since 23 days after mark as "Information Complete".

Thank you!

**Comment by freeatnet** [comment]
@TORQCoin I've been going through the approved listing requests in the past few days, I go "least recently updated first" (label changes and discussion restart recency).

**Comment by TORQCoin** [comment]
@freeatnet I'm sorry, since I replied to this issue multiple time it pushed it back to last. 

Please consider this request as an exception.

**Comment by freeatnet** [comment]
@TORQCoin Thank you for your request! TORQ Coin has been listed: https://forkdelta.github.io/#!/trade/TORQ-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
