### ISSUE TITLE
Add ticker FTOKEN

### ISSUE THREAD

**Issue by Webinvestart** [forkdelta/tokenbase#413]
Contract address:
https://ethplorer.io/address/0x25c8ca98fe9d59ceef5e0175abae40d4caa60af9

Issuer's official website:
https://flashtoken.io
Official contract address confirmation:

https://flashtoken.io
https://github.com/flashtoken
https://ethplorer.io/address/0x25c8ca98fe9d59ceef5e0175abae40d4caa60af9

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2574672.140
https://t.me/flashcommunityru

Description:

Please add ticker FTOKEN to
https://forkdelta.github.io/#!/trade/0x25c8ca98fe9d59ceef5e0175abae40d4caa60af9-ETH

**Comment by Kryptoniq** [comment]
Duplicate #383.
