### ISSUE TITLE
ZerroXBToken Project 0xbt

### ISSUE THREAD

**Issue by ZerroXBToken** [forkdelta/tokenbase#415]
Contract address: [0xcd0a53685b594a543181e6203433766648a8cd43](url=https://etherscan.io/address/0xcd0a53685b594a543181e6203433766648a8cd43)

Symbol: ZXBT
Full Name: ZerroXBToken Project 0xbt
Decimals: 3
Please list the token with full name ZerroXBToken

Issuer's official website: https://zxbt.0xbt.net

Official contract address confirmation:
https://www.0xbt.net/about
https://github.com/ZerroXBToken/zxbt

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2799398.0

Description:
The ZXBT token has an original function. Sending tokens can be accompanied with the message or signature for identification. If desired, the sending of tokens can be used as a messenger. Example TxHash: https://etherscan.io/tx/0xef522ca5e4c87054ece549aba22f1f5d52f9de93383ace7c9625468ccd82202e View transaction TxHash: clicking Convert To Ascii.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xcd0a53685b594a543181e6203433766648a8cd43, https://zxbt.0xbt.net/

**Comment by ZerroXBToken** [comment]
https://bitcointalk.org/index.php?topic=2934103.0

**Comment by freeatnet** [comment]
@ZerroXBToken Thank you for your request! ZerroXBToken Project 0xbt has been listed: https://forkdelta.github.io/#!/trade/ZXBT-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by ZerroXBToken** [comment]
Please remove the "ZXBT" token from the list due to the rebranding and release of the new, more advanced token. We are planning to publish a new project in the coming days.
We want to remove the token "ZXBT", because of possible speculation after the announcement of the new project.
Thank you in advance for your understanding of the situation.

**Comment by freeatnet** [comment]
@ZerroXBToken Please file a request here: https://github.com/forkdelta/tokenbase/issues/new?template=update-token-information.md
