### ISSUE TITLE
Listing request - BANCA

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#417]
Website: https://www.banca.world
Whitepaper: https://www.banca.world/A_UpLoad/upload_file/20180227/20180227142957_6430.pdf
Description: A Cryptocurrency Investment Bank Community Based on AI and Big Data.

Contract address: https://etherscan.io/token/0x998b3B82bC9dBA173990Be7afb772788B5aCB8Bd
Symbol: BANCA
Full Name: BANCA
Decimals: 18

Link to confirm contract: https://twitter.com/Banca_Official/status/970599052592033793 (which is their official Twitter account as it is linked in their official website)

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2725461
https://icoreview.community/banca-review/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x998b3b82bc9dba173990be7afb772788b5acb8bd, https://www.banca.world/
