### ISSUE TITLE
Listing request - SOC

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#418]
Website: https://www.allsportschain.com
Whitepaper: https://www.allsportschain.com/paper/all_sports_blockchain_open_platform_white_paper_zh-tw.pdf
Description: With the increasing popularity of blockchain technology, All Sports public blockchain hopes to fill in the blank of blockchain application in sports industry through blockchain technology, which is a sun-rising industry all over the world. What we want to create is a decentralized, globalized, infiltrated into sports industry chain, shared by both parties and value co-created.

Contract address: https://etherscan.io/token/0x2d0e95bd4795d7ace0da3c0ff7b706a5970eb9d3
Symbol: SOC
Full Name: All Sports Coin
Decimals: 18

Link to confirm contract: https://www.huobi.pro/soc_eth/exchange (Huobi is listed as an official exchange on SOC's website, therefore the contract shown in Huobi can be trusted)

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2948086

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x2d0e95bd4795d7ace0da3c0ff7b706a5970eb9d3, https://www.allsportschain.com/
