### ISSUE TITLE
Listing request - BGG

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#419]
Website: https://goldgate.io
Whitepaper: https://goldgate.io/Whitepaper_Goldgate_English-v12.pdf?v=1.2
Description: GOLDGATE Platform is a new revolution in the digital technology where users and businesses gather to seek great income stability in a fluctuating environment. It is the new generation of gold-back cryptoassets.

Contract address: https://etherscan.io/token/0x33803edf44a71b9579f54cd429b53b06c0eeab83
Symbol: BGG
Full Name: GoldGate
Decimals: 8

Link to confirm contract: This one took a bit of imagination to get it verified. https://webcache.googleusercontent.com/search?q=cache:XsbWzeSXrQUJ:https://goldgate.io/verify-registration/tPf8bGyc3RtXEtD+&cd=10&hl=pt-BR&ct=clnk&gl=br&lr=lang_en%7Clang_pt is the Cached version of their OFFICIAL website (you can see it's the cached version of goldgate.io). At some point, Google was able to log in their website and take a snapshot of it. You can see that 0x33803EdF44A71B9579f54cd429B53B06c0EeAb83 is listed as their contract there.

Third-party comment on the token:
https://bitcointalk.org/index.php?topic=2459301

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x33803edf44a71b9579f54cd429b53b06c0eeab83, https://goldgate.io/
