### ISSUE TITLE
Listing of XES

### ISSUE THREAD

**Issue by ProxeusApp** [forkdelta/tokenbase#423]
Contract address: 0xa017ac5fac5941f95010b12570b812c974469c2c
Symbol: XES
Decimals: 18

We also have some Socmed-channels I can provide:
Twitter: https://twitter.com/proxeusapp
Facebook: https://www.facebook.com/proxeusapp/
Reddit: https://www.reddit.com/r/proxeus/
Telegram: https://t.me/joinchat/Gj6qYUpY1XHgHGnQa9msvA

We are currently traded on: https://ex.singularx.com/exchange/XES/ETH

Issuer's official website: proxeus.com

Official contract address confirmation: on the homepage on proxeus.com in the banner at the bottom.

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2903956.new#new

Description: PROXEUS is a utility token which can be used to design, publish and distribute workflows and documents  which are registered on smart contracts. By making it possible to design a Dapp without having to program a single line of code PROXEUS aims to become the Wordpress for the blockchain.

**Comment by futuretekag** [comment]
I am adding some information here as I was using a template and only saw that there is more info required:
Contract address: 0xa017ac5fac5941f95010b12570b812c974469c2c
Symbol: XES
Decimals: 18

We also have some Socmed-channels I can provide:
Twitter: https://twitter.com/proxeusapp
Facebook: https://www.facebook.com/proxeusapp/
Reddit: https://www.reddit.com/r/proxeus/
Telegram: https://t.me/joinchat/Gj6qYUpY1XHgHGnQa9msvA

We are currently traded on: https://ex.singularx.com/exchange/XES/ETH

Sorry for the trouble

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xa017ac5fac5941f95010b12570b812c974469c2c, https://proxeus.com

**Comment by freeatnet** [comment]
Thank you for your request! Proxeus has been listed: https://forkdelta.github.io/#!/trade/XES-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
