### ISSUE TITLE
HunterCoin Token Listing

### ISSUE THREAD

**Issue by HunterCoinToken** [forkdelta/tokenbase#424]
Contract address: 0x87c8d6da29c030aae4d8ecb77b2f488f529de1f5

Issuer's official website: https://huntercoin.000webhostapp.com/

Official contract address confirmation: https://huntercoin.000webhostapp.com/

A link to a third-party review or discussion of the token: https://medium.com/@htctoken/what-is-huntercoin-29bcb2930195

Description:
"HunterCoin token is an Ethereum-based ERC-20 Token that focuses on being a faster and cheaper currency"

**Comment by HunterCoinToken** [comment]
tokenbase/tokens/0x87c8d6da29c030aae4d8ecb77b2f488f529de1f5.yaml
@freeatnet  @Kryptoniq

**Comment by Kryptoniq** [comment]
A quick question; what stops you from getting a domain?

**Comment by Kryptoniq** [comment]
There is already a HunterCoin project which started in 2014
https://coinmarketcap.com/currencies/huntercoin/
http://huntercoin.org/https://www.huntercoin.info/blockExplorer
https://bitcointalk.org/index.php?topic=435170.0

Sorry we can't list you.
