### ISSUE TITLE
Listing request for Shivers (SHVR)

### ISSUE THREAD

**Issue by ShiversToken** [forkdelta/tokenbase#429]
Contract address: https://etherscan.io/address/0xd5f788ca0de8f17cbde1d1e35aa8f005a87fa00b

Issuer's official website: http://shivers.io

Official contract address confirmation: https://shivers.io/whitepaper.pdf (last page)

A link to a third-party review or discussion of the token: https://bitcoinexchangeguide.com/shivers-shvr-ico/

Description: Shivers is a cryptocurrency developed to facilitate the production and distribution of horror films via blockchain technology. Our partners include legendary filmmakers, such as the creators of the box office hit "The Blair Witch Project" and large communities such as "Infamous Horror" and their 1.7 Million followers.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xd5f788ca0de8f17cbde1d1e35aa8f005a87fa00b, http://shivers.io

**Comment by freeatnet** [comment]
@Kryptoniq The website seems to list mcafee as an advisor, but I couldn't find anything to corroborate that. Have you seen anything to confirm that?

**Comment by Kryptoniq** [comment]
@freeatnet yup. McAfee did endorse them on twitter. I saw the tweet.

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 9th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Shivers has been listed: https://forkdelta.github.io/#!/trade/SHVR-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
