### ISSUE TITLE
[On Hold] SLRM Listing

### ISSUE THREAD

**Issue by Solareum** [forkdelta/tokenbase#43]
Solareum is a currency that runs on the Ethereum Blockchain and is the FIRST AND FOREMOST COIN to be backed by the Solar and Renewable Industry it serves. SOLAREUM offers Discounts on Solar Panels, Renewable Items, EXCLUSIVE Solar Heating, and all things solar with a personal touch. The core concept of the SOLAREUM Token changes the world in making energy pay you, instead of you paying for your energy! SOLAREUM’s tool will be a marketplace unlike any other to the effect of “Amazon of Solar & Renewables" utilizing blockchain & megadata to allow any solar company and end user to be able to connect on a human level for Real-Time Accurate Proposals.

- 0x56ee8c9bd1d445a3324ad83e86d8be309db8f85d
- https://www.solareum.club/
- https://etherscan.io/token/0x56ee8c9bd1d445a3324ad83e86d8be309db8f85d
- https://www.coinannouncer.com/solareum-has-brought-solar-energy-on-blockchain/

**Comment by freeatnet** [comment]
@Solareum we need a link from an official source that mentions the contract address. Thanks!

**Comment by Solareum** [comment]
@freeatnet 
- Link Contract Address: https://etherscan.io/address/0x56ee8c9bd1d445a3324ad83e86d8be309db8f85d
- https://icotracker.net/project/solareum_
- https://iconow.net/ico-880/

**Comment by freeatnet** [comment]
@Solareum Please provide a link to a page on solareum.club that states 0x56ee8c9bd1d445a3324ad83e86d8be309db8f85d is the contract address of the solareum token.

**Comment by Solareum** [comment]
@freeatnet 
We added the contract address on the solareum.club webpage. https://www.solareum.club/

**Comment by Solareum** [comment]
@freeatnet 
Can Solareum be listed on February 15 2018?

**Comment by freeatnet** [comment]
@Solareum Sure thing.

**Comment by Solareum** [comment]
Good Day @freeatnet 

The Solareum team would like to know what time on February 15th 2018 will Solareum be listed in your exchange?

Thank you,
Solareum

**Comment by Solareum** [comment]
Hello @freeatnet,

Following up again. What time is SOLAREUM being listed on the exchange for tomorrow, Feb 15?

**Comment by JonathonDunford** [comment]
@Solareum I am working on it right now. We've been slammed with updates to get the backend out and running so trading was working.

**Comment by JonathonDunford** [comment]
Once #85 goes through, this token will be added to tokenbase (and subsequently ForkDelta).

**Comment by JonathonDunford** [comment]
Will be added to FD once https://github.com/forkdelta/forkdelta.github.io/pull/60 goes through.

**Comment by Solareum** [comment]
Thank you Team!


Solareum Team

[1513645709387_solareum_whitel_1x1_140.jpg]

SOLAREUM<https://solareum.club/>

[1513645887445_facebook.png] Facebook<https://www.facebook.com/Solareum-300189880473588/>

[1513645914838_twitter.png] Twitter<https://twitter.com/SOLAREUMclub>

[1513645932797_instagram.png] Instagram<https://www.instagram.com/solareumclub/>

[1513645944053_youtube.png] Youtube<https://www.youtube.com/channel/UCANPdxr0u2FS2tBM_Sm1lMQ>

[1513645955510_linkedin.png] Linkedin<https://www.linkedin.com/company/solareum/>

On Feb 15, 2018, at 8:12 PM, BigBrother <notifications@github.com<mailto:notifications@github.com>> wrote:


Will be added to FD once forkdelta/forkdelta.github.io#60<https://github.com/forkdelta/forkdelta.github.io/pull/60> goes through.

**Comment by JonathonDunford** [comment]
https://forkdelta.github.io/#!/trade/SLRM-ETH

**Comment by Solareum** [comment]
Team Thanks!

We do see 155,000,000 SLRM and only 60,000,000 are made? Is there any specific reasoning for it?


Solareum Team

[1513645709387_solareum_whitel_1x1_140.jpg]

SOLAREUM<https://solareum.club/>

[1513645887445_facebook.png] Facebook<https://www.facebook.com/Solareum-300189880473588/>

[1513645914838_twitter.png] Twitter<https://twitter.com/SOLAREUMclub>

[1513645932797_instagram.png] Instagram<https://www.instagram.com/solareumclub/>

[1513645944053_youtube.png] Youtube<https://www.youtube.com/channel/UCANPdxr0u2FS2tBM_Sm1lMQ>

[1513645955510_linkedin.png] Linkedin<https://www.linkedin.com/company/solareum/>

On Feb 16, 2018, at 10:41 AM, BigBrother <notifications@github.com<mailto:notifications@github.com>> wrote:


https://forkdelta.github.io/#!/trade/SLRM-ETH

**Comment by Solareum** [comment]
Thanks All,

We do see a couple discrepancies.

Our coin only has 60,000,000 @ .70 in production but we 155,000,000. Could anyone explain where this number came from? Thank you in advance and we hope you are having a great day!


Solareum Team

[1513645709387_solareum_whitel_1x1_140.jpg]

SOLAREUM<https://solareum.club/>

[1513645887445_facebook.png] Facebook<https://www.facebook.com/Solareum-300189880473588/>

[1513645914838_twitter.png] Twitter<https://twitter.com/SOLAREUMclub>

[1513645932797_instagram.png] Instagram<https://www.instagram.com/solareumclub/>

[1513645944053_youtube.png] Youtube<https://www.youtube.com/channel/UCANPdxr0u2FS2tBM_Sm1lMQ>

[1513645955510_linkedin.png] Linkedin<https://www.linkedin.com/company/solareum/>

On Feb 16, 2018, at 10:41 AM, BigBrother <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #43<https://github.com/forkdelta/tokenbase/issues/43>.

**Comment by Solareum** [comment]
@freeatnet 
@JonathonDunford 

Our coin only has 60,000,000 @ .70 in production but we 155,000,000. Could anyone explain where this number came from? Thank you in advance and we hope you are having a great day!

**Comment by Solareum** [comment]
Following up on Below:

Thanks All,

We do see a couple discrepancies.

Our coin only has 60,000,000 @ .70 in production but we 155,000,000. Could anyone explain where this number came from? Thank you in advance and we hope you are having a great day!


Solareum Team

[1513645709387_solareum_whitel_1x1_140.jpg]

SOLAREUM<https://solareum.club/>

[1513645887445_facebook.png] Facebook<https://www.facebook.com/Solareum-300189880473588/>

[1513645914838_twitter.png] Twitter<https://twitter.com/SOLAREUMclub>

[1513645932797_instagram.png] Instagram<https://www.instagram.com/solareumclub/>

[1513645944053_youtube.png] Youtube<https://www.youtube.com/channel/UCANPdxr0u2FS2tBM_Sm1lMQ>

[1513645955510_linkedin.png] Linkedin<https://www.linkedin.com/company/solareum/>

On Feb 16, 2018, at 10:41 AM, BigBrother <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #43<https://github.com/forkdelta/tokenbase/issues/43>.

**Comment by Solareum** [comment]
@freeatnet
@JonathonDunford

Hi Team, 

Following up again - Can we please alter this to reflect that Our coin only has 60,000,000 @ .70. We need the .70 value to be present ASAP. Please let us know if there is anything we can do to expedite this process.

**Comment by Solareum** [comment]
Good Afternoon @freeatnet
@JonathonDunford

Following Up again in regards to our previous request. The information currently provided is false. Please update for our coin to reflect 60,000,000 at .70. We need the .70 to be present ASAP. Again, please let us know if there is anything we can do to expedite this process. 

Thank you.

**Comment by Solareum** [comment]
@freeatnet
@JonathonDunford

Good Morning Team, 

Can you please provide a date in which the above request will be completed? Thank you.

**Comment by JonathonDunford** [comment]
@Solareum We don't have any control over that...

Our platform shows actual trades and order book data.

**Comment by Solareum** [comment]
Good Day @JonathonDunford 

We see the actual trades and order book data, however there is no price chart. Does the chart get generate automatically?

Do we need ETH for gas fee to make a deposit on SLRM? We are testing out your platform, to help customers in using forkdelta.

**Comment by JonathonDunford** [comment]
It's automatic.

Yes. take a look at the FAQs on our about page.
