### ISSUE TITLE
Listing request - ZAP

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#431]
Website: https://zap.store
Whitepaper: https://zap.store/whitepaper.pdf
Description: The Zap Store allows users to create, publish and subscribe to smart contract and Decentralized Application compatible data feeds.

Contract address: https://etherscan.io/token/0x6781a0f84c7e9e846dcb84a9a5bd49333067b104
Symbol: ZAP
Full Name: ZAP TOKEN
Decimals: 18

Link to confirm contract: https://media.zapproject.org/how-to-use-myetherwallet-to-purchase-zap-d919d0f29160 (if you go to their official website and click on Blog which is located on the top right, you'll see that https://media.zapproject.org is their official blog address)

Third-party comment(s) on the token:
https://bitcointalk.org/index.php?topic=2286111
http://cryptobutlers.com/zapstore

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
https://zap.store, 0x6781a0f84c7e9e846dcb84a9a5bd49333067b104
