### ISSUE TITLE
List request for ET Tokens

### ISSUE THREAD

**Issue by ewallet-token** [forkdelta/tokenbase#432]
Contract address: 0x9375f79b3c186e9cc380f9d5890110e21bf0f04d
Issuer's official website: https://ewallet-token.com
Official contract address confirmation: https://ewallet-token.com/contract/
A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3140680.0

Description:
E-Wallet Token Platform - provides a hassle-free way of making payments or rather we say your time saver. Whether it’s your credit card, utility, insurance, school or any other bill, you don’t have to travel anywhere. Pay your bills at any time of the day, right from the comfort of your home. You can save all your billing dates and accounts at one place.

**Comment by ewallet-token** [comment]
---
addr: ' 0x9375f79b3c186e9cc380f9d5890110e21bf0f04d'
decimals: 18
description: >-
  Provides a hassle free way of making payments or rather we say your time saver
  E-WALLET Token is a ERC20 token smart contract come with a number of functions to allow 
  users to find out the balances of accounts as well as to transfer them from one account to another.

links:
- Email: support@ewallet-token.com
- Facebook: https://www.facebook.com/E-Wallet-174129063347615/
- Telegram: https://t.me/ewallet_token
- Blog: https://medium.com/e-wallet-token/e-wallet-token-3cbb95e87dd
- Reddit: https://redd.it/7qx1si
- Twitter: https://twitter.com/eWallet_Token
- Website: https://ewallet-token.com/
name: E-WALLET
symbol: ET

@freeatnet  @Kryptoniq

**Comment by freeatnet** [comment]
@ewallet-token Stop spamming your request.

**Comment by Kryptoniq** [comment]
From your website
https://ewallet-token.com/contract/
```E-WALLET Token – is a ERC20 token contracts come with a number of functions to allow users to find out the balances of accounts as well as to transfer them from one account to another.```

From Jim McDonald's Medium post
https://medium.com/@jgm.orinoco/understanding-erc-20-token-contracts-a809a7310aa5

```ERC-20 token contracts come with a number of functions to allow users to find out the balances of accounts as well as to transfer them from one account to another```

All ERC20 tokens perform this function but  you blatantly copied McDonald's post as the use and description of your token
.

**Comment by tradedbytony** [comment]
Open PR at #433

**Comment by ewallet-token** [comment]
we use this as the definition of ERC20 
_"ERC20 token smart contract comes with a number of functions to allow 
  users to find out the balances of accounts as well as to transfer them from one account to another"_

but the description of our token is _" Provides a hassle-free way of making payments or rather we say your time saver"_ and we just add _"E-WALLET Token – is an ERC20 token contract come with a number of functions to allow users to find out the balances of accounts as well as to transfer them from one account to another"_ to define what is E-Wallet Token under erc20 contract.

but on our website, our token definition is  _" Provides a hassle-free way of making payments or rather we say your time saver"_  https://ewallet-token.com/

**Comment by JonathonDunford** [comment]
@ewallet-token Blatant plagiarization is not allowed.

That link is not a third party review as it is written by you.

Please provide:
- A bitcointalk announcement
- Some sort of third party verification of the project. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc.

**Comment by ewallet-token** [comment]
@JonathonDunford thank you for updating our token missing requirement to get list.
were now working on our token third-party review and discussion. we will update our token information soon as we're done on our token third-party blogs.

**Comment by freeatnet** [comment]
Some notes:

* Website archived: https://web.archive.org/web/20180316102606/https://ewallet-token.com/
* Other projects that describe themselves exactly the same way: [Ethereum Lite (ELITE)](https://web.archive.org/web/20171207230430/http://www.ethereumlite.org) (website defunct), [bitcoinpure (BTCP)](https://bitcointalk.org/index.php?topic=2402409.0) and more.
* About section is largely plagerized: 
    > ET Mobile Application
    > is feature exclusively for customers who have registered and established a My Account Profile, and eliminate the need to enter in account information when making your payment. Once you have registered and created E-Wallet profiles, you can make payments faster and with less typing.
    
    from [officialpayments.com](https://www.officialpayments.com/hp_faq_acct_ewallet.jsp)
    
    > Base Functionality
   > it offers secure enrollment of the user (Application Download, Identity check) and secure provisioning of credentials (e.g., User ID and Password for wallet access).

    from ["The Evolution of Digital and Mobile Wallets" (pdf)](http://www.paymentscardsandmobile.com/wp-content/uploads/2016/10/The-Evolution-of-Digital-and-Mobile-Wallets.pdf)

* Team photos are literally the [default photos](https://demo.themeisle.com/hestia-pro/hook-locations/) that came with the WordPress theme.
* Team member social links point to respective platforms' root URLs.
* "Tell us what you think" is, again, just the template's text fillers.
* There are random meaningless logos just below that.
* The rest of the pages on the website are stub pages.

**Comment by ewallet-token** [comment]
> Team photos are literally the default photos that came with the WordPress theme.
> 
> Team member social links point to respective platforms' root URLs.
> 
> "Tell us what you think" is, again, just the template's text fillers.
> 
> There are random meaningless logos just below that.
> 
> The rest of the pages on the website are stub pages.

@freeatnet 
Our website is under reconstruction since the day you check it until now, that's why some default templates to be seen. we apologized for that issue when the reconstruction of on website is done all feature on the site is originally from E-Wallet.

**Comment by ewallet-token** [comment]
Contract address:  0x9375f79b3c186e9cc380f9d5890110e21bf0f04d
Issuer's official website: https://ewallet-token.com
Official contract address confirmation: https://ewallet-token.com/contract/
A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3140680.0

Description:
E-Wallet Token Platform - provides a hassle-free way of making payments or rather we say your time saver. Whether it’s your credit card, utility, insurance, school or any other bill, you don’t have to travel anywhere. Pay your bills at any time of the day, right from the comfort of your home. You can save all your billing dates and accounts at one place.

**Comment by freeatnet** [comment]
No substantial improvements ([archived wesbite](https://web.archive.org/web/20180320155143/https://ewallet-token.com/)). Still copy-paste, now featuring generic "Fast", "Secure", "Cheap" benefits and lacking any team information or roadmap.

> Why E-Wallet is the best
> E-Wallet save your time, everytime you make a payment. **The payment information from your Primary account is conveniently pre-filled during the payment process, and you can quickly select another payment account if you have more than one set up.**

is still copied straight from https://www.officialpayments.com/fed/hp_faq_acct_ewallet.jsp#4.

Sorry, we cannot list you based on provided information. You may request listing again after April 21st, 2018. Your request will need to present substantial improvements to the project and project presentation.

**Comment by ewallet-token** [comment]
@freeatnet @Kryptoniq @tradedbytony @JonathonDunford  hi sir, please list our tokens in your exchanges.

**Comment by freeatnet** [comment]
@ewallet-token No. See above.

**Comment by freeatnet** [comment]
/remind me to unlock this thread April 21
