### ISSUE TITLE
Listing Request - SAM

### ISSUE THREAD

**Issue by Samfins** [forkdelta/tokenbase#434]
Website: https://samfins.com/
Whitepaper: https://samfins.com/download/Whitepaper.pdf
Description: A decentralized exchange and Universal wallet with built in  Machine Learning based prediction market

Contract address: https://ethplorer.io/address/0x8bab3ca6e929a5d5d1eefd5de68ecf3264fa742d
Symbol: SAM
Full Name: SAMFins 
Decimals: 18

Link to confirm contract: https://medium.com/@samfins.platform/how-to-view-sam-tokens-on-mew-and-metamask-68e94cd2675f

BitcoinTalk Announcement Link:
https://bitcointalk.org/index.php?topic=2519570.0

Third-party comment(s) on the token:
https://iconow.net/ico-862/
https://icobench.com/ico/samfins/ratings

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
Hi, your contract address is not verified on etherscan.
https://etherscan.io/address/0x8bab3ca6e929a5d5d1eefd5de68ecf3264fa742d#code
