### ISSUE TITLE
Request to add WIT token on forkdelta

### ISSUE THREAD

**Issue by witchaindev** [forkdelta/tokenbase#435]
Contract address: 0xe13ef257cf4d5df928ca11d230427c037666d466

Issuer's official website: http://witchain.org/

Official contract address confirmation: 
http://witchain.org
https://etherscan.io/token/0xe13ef257cf4d5df928ca11d230427c037666d466

A link to a third-party review or discussion of the token:
website: http://www.witchain.org/
Telegram：https://t.me/witchain      4500
twitter:  https://twitter.com/witchaindev   3500
bitcointalk:  https://bitcointalk.org/index.php?topic=2848994
Email：admin@witchain.org

Description:
WITChain Makes Your Token and Manages Its Value.You Have Value Token in Decentralized Cryptocurrency Economy,We Provide Digital Token Development and Value Management Service for Individual and Enterprise.

Contract address: 0xe13ef257cf4d5df928ca11d230427c037666d466
Symbol: WIT
Decimals: 6
https://etherscan.io/token/0xe13ef257cf4d5df928ca11d230427c037666d466

Thank You

WIT dev

**Comment by witchaindev** [comment]
WITchain donated 0.8ETH to support the development of FORDELTA
https://etherscan.io/tx/0x52a839640a8b34c680456e8e0264d80cc71f47f276b1cfb8e724646275fcbc85

From:0xdb232b5eada73a0cbb6971cb1464192d6afcf87e
To:0x3a2aedc3b54a99e429ae36637681d4560ce5c05b 
Value: 0.8 Ether ($607.70)

Thank You

**Comment by witchaindev** [comment]
---
addr: '0xe13ef257cf4d5df928ca11d230427c037666d466'
decimals: 6
description: >-
  WITChain Makes Your Token and Manages Its Value.You Have Value Token in Decentralized Cryptocurrency Economy,We Provide Digital Token Development and Value Management Service for Individual and Enterprise.

links:
- Email: admin@witchain.org
- Telegram: https://t.me/witchain
- Twitter: https://twitter.com/witchaindev
- Website: http://www.witchain.org/
name: WIT
symbol: WIT

https://etherscan.io/token/0xe13ef257cf4d5df928ca11d230427c037666d466

**Comment by JonathonDunford** [comment]
@witchaindev @Kryptoniq 

Do you have a whitepaper?
Do you have a third party review?
There hasn't been any activity on your Bitcointalk. What is the reason for this?

**Comment by Kryptoniq** [comment]
@Witchaindev _ping_

**Comment by witchaindev** [comment]
Do you have a whitepaper?
http://witchain.org/wit/witchainEN.pdf
Do you have a third party review?
http://witchain.org/wit/pl2.jpg
http://witchain.org/index.htm
There hasn't been any activity on your Bitcointalk. What is the reason for this?
https://bitcointalk.org/index.php?topic=3073474.0

**Comment by tradedbytony** [comment]
A recent duplicate has been made at #513

**Comment by witchaindev** [comment]
Do you have a whitepaper?
http://witchain.org/wit/witchainEN.pdf
Do you have a third party review?
http://witchain.org/wit/pl2.jpg
http://witchain.org/index.htm
There hasn't been any activity on your Bitcointalk. What is the reason for this?
https://bitcointalk.org/index.php?topic=3073474.0

**Comment by witchaindev** [comment]
Do you have a whitepaper?
http://witchain.org/wit/witchainEN.pdf
Do you have a third party review?
http://witchain.org/wit/pl2.jpg
http://witchain.org/index.htm
There hasn't been any activity on your Bitcointalk. What is the reason for this?
https://bitcointalk.org/index.php?topic=3073474.0
