### ISSUE TITLE
Listing... (NRC) token 

### ISSUE THREAD

**Issue by humairk** [forkdelta/tokenbase#437]
Website: https://thenitrocoin.org
Issuer's official website:https://thenitrocoin.org
Contract address: https://etherscan.io/token/0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
Contract address: 0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
Full Name: Nitrocoin
Symbol: NRC
Decimals: 0

reddit links : https://www.reddit.com/user/nitrocoinNRC/
Link to confirm contract: https://twitter.com/NitrocoinNRC
facebook Link: https://www.facebook.com/nitrocoinNRC/
Third-party comment(s) on the token:new join bitcointalk.org; https://bitcointalk.org/index.php?topic=3105174.
Whitepaper: https://thenitrocoin.org/whitepaper/NRC_WAIT_P.pdf

Description: The Decentralized Coin pegged to stock market in nitrocoin by fund

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by tradedbytony** [comment]
Massive spam: #498, #480, #437, #382, #499 and #482 are all about this NRC token.

**Comment by Kryptoniq** [comment]
1. Your bitcointalk thread has insufficient information.
2. Your co-founder "Johsan Hater" is fake. The image used is that of a Brazilian man called Rafael.

Archive: https://web.archive.org/web/20180313001211/https://thenitrocoin.org/

https://www.ecenglish.com/en/social/blog/montreal/2015/06/29/rafael-pileggi-calegarini-from-brazil-my-accommodation-in-my-homestay-was-really-good

Sorry, we can't list you.
