### ISSUE TITLE
Listing request - VETRA

### ISSUE THREAD

**Issue by VetraCommunity** [forkdelta/tokenbase#438]
Contract address : https://etherscan.io/address/0x7dcdbd2c6548774d301811658ddcb0e75eca9881
Total Supply: 18.000.000
Symbol: VETRA
Token Decimals: 18

Issuer's official website: https://vetra.info
Whitepaper : https://vetra.info/Whitepaper_Vetra.pdf
Forum : https://vetracommunity.info/
Facebook : https://www.facebook.com/VetraCommunityInfo/
Twitter : https://twitter.com/VetraOfficial
Telegram Group : https://t.me/VetraCommunity

Official contract address confirmation: https://vetra.info/presale You Can See The Contract Address On Page Below In The How To Join Presale Tittle On Smartcontract tiitle you can see 0x7dcdbd2c6548774d301811658ddcb0e75eca9881 Address Of Smartcontract

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3070452.0

Description : Crypto Payment Platform & The Trading Platform Token
Driven By Community

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by VetraCommunity** [comment]
---
addr: '0x7dcdbd2c6548774d301811658ddcb0e75eca9881'
decimals: 18
links:
-Forum: https://vetracommunity.info/
-Website: https://vetra.info
-Email: mailto:support@vetra.info
-Whitepaper : https://vetra.info/Whitepaper_Vetra.pdf
-Facebook : https://www.facebook.com/VetraCommunityInfo/
-Twitter : https://twitter.com/VetraOfficial
-Telegram Group : https://t.me/VetraCommunity
-Bitcointalk: https://bitcointalk.org/index.php?topic=3070452.0
name: VETRA
symbol: VETRA

**Comment by VetraCommunity** [comment]
@freeatnet @Kryptoniq

**Comment by freeatnet** [comment]
@vetracommunity Thanks for your submission. We will get to it as soon as we can. Personal mentions are not necessary, requests are processed on first come, first served basis. Thanks for understanding.

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has no constructive review / comment.
It is flooded with
```
#Proof of Authentication
Vetra Community Username: _inserts name_
Bitcointalk Username:  _inserts name_
Twitter handle: _inserts name_
Telegram handle: _inserts name_
Facebook handle: _inserts name_
```

**Comment by tradedbytony** [comment]
Every single "token holder" only have this token in their wallets or txs between these wallets moving this token. Not to mention, only 28 token holders. And their bitcointalk thread is iffy.

**Comment by tradedbytony** [comment]
An open PR can be found at 491
