### ISSUE TITLE
EthBay 

### ISSUE THREAD

**Issue by Etherbay** [forkdelta/tokenbase#439]
Contract address:
 0XB9EAA527AB86767CB6C955EDEB612DBB423DD798

Issuer's official website: http://etherbay.info

Official contract address confirmation: http://etherbay.info/#Wallets

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2947621.0

Description:
An online trading platform, that uses cryptocurrencies as a payment method.

**Comment by Etherbay** [comment]
---  # Mandatory "start of the document" marker
addr: 0XB9EAA527AB86767CB6C955EDEB612DBB423DD798
decimals: 8
name: Etherbay
symbol: EBX

**Comment by Etherbay** [comment]
addr: '0XB9EAA527AB86767CB6C955EDEB612DBB423DD798'
decimals: 8
links:
- Email: etherbay@etherbay.info
- Telegram: https://t.me/etherbay
- Website: http://etherbay.info
- Facebook: https://www.facebook.com/etherbay/
- Whitepaper: http://etherbay.info/Whitepaper/Whitepaper.pdf
name: EthBay
symbol: EBX

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
1. Bitcointalk announcement thread has insufficient reviews / comments.
2. Contract address is not verified on etherscan.
3. Only 1 token holder.

**Comment by tradedbytony** [comment]
Open PR found at #477

**Comment by tradedbytony** [comment]
Two different tokens have requested to have the EBX ticker (#439 and #533 ).
