### ISSUE TITLE
Intention to delist: MMASportsTech (MMA)

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#440]
On February 3rd, user @etherbeats requested listing of MMASportsTech Token (MMA). The token was listed on February 22nd. I believe that I have discovered issues significantly affecting trustworthiness of the project; therefore, I propose to de-list the token.

Reasons: plagiarized project description and whitepaper, stock photos in team member information.

## Plagiarized descriptions
Project website:
> MMASportsTech is a decentralized gambling platform made by Mixed Martial Arts fans and Tech Geeks. We strive to create the platform as a decentralized application (Dapp) which will offer the service of Fantasy MMA and settling bets. The open and borderless nature of blockchain and the Ethereum Network will allow players from all over the world to connect and create the largest Fantasy MMA liquidity pool seen to date.

https://icomarks.com/ico/acebusters
> Acebusters is a decentralized poker platform made by obsessive poker and cryptography fans. We strive to create Acebusters as a decentralized application (Dapp) which will offer the service of dealing cards and settling bets. The open and borderless nature of blockchain will allow players from all over the world to connect and create the largest poker liquidity pool seen to date.

Project website:
> What is the MMA Token and why is it necessary?
> We are inviting you to bet on the house. Our MMA token is an ERC-20 standards-compliant token. The MMA Token grants its holders special rights and privileges within the MMASportsTech platform; including the right to profit your proportional share of the house bankroll generated via our fighter pick'em game.

https://etheroll.wordpress.com/2017/05/15/etheroll-dice-tokens-unlocked-may-15-on-etherdelta-exchange-learn-more-here/
> What is ÐICE?
> We are inviting you to bet on the house. Our ÐICE token is an ERC-20 standards-compliant token, and a default token within MyEtherWallet and Parity.
> ÐICE grants its holders special rights and privileges within the Etheroll platform; including the right to profit your proportional share of the house bankroll generates via our dice game with its built-in 1% house edge. For example, if you own 10% of all tokens, you have rights to 10% of the profit the bankroll generates, every 12 weeks.

## Whitepaper
MMASportsTech's [whitepaper](http://archive.li/gUvgw) is largely plagiarized from [Etheroll whitepaper](https://crowdfund.etheroll.com/etheroll-whitepaper.pdf), including  "Opportunity" and "About us" sections.

## Team
* "Jimmy Smith -- Blockchain and Solidity consultant": Stock image ["young man smiling"](https://www.shutterstock.com/video/clip-2170574-stock-footage-attractive-young-man-smiling-at-camera-ia-happy-indoors.html)
* "David Grifin -- Lead Developer": photo from [here](https://barbearia.org/barba-cerrada/)

Archive copy of MMASportsTech website: http://archive.li/ToglE, whitepaper: http://archive.li/gUvgw

**Comment by JonathonDunford** [comment]
I'd say we can move forward with the delisting. At least until they address these plagiarization concerns.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/450

**Comment by freeatnet** [comment]
This needs to be put up for community discussion.

**Comment by freeatnet** [comment]
This needs to be put up for community discussion. @etherbeats should be given an opportunity to respond to this, too.
