### ISSUE TITLE
MEDCASH Listing

### ISSUE THREAD

**Issue by medxchange1** [forkdelta/tokenbase#441]
Contract address: 0x047BE01729131132D47e54c95cA1F3E14044DFBf

Issuer's official website: https://www.medxchange.io/ 

Official contract address confirmation:
https://www.medxchange.io/medcash
(middle paragraph)

A link to a third-party review or discussion of the token:
BitcoinTalk.org thread in the works.

Description:

MedXchange is a blockchain-based system to democratize the USD 340 billion global medical device industry. The platform will: (i) disintermediate the medical device and supplies ecosystem and make it more efficient; (ii) facilitate and secure the global exchange of medical devices, supplies and payments; and (iii) lower patient/customer or insurance cost. Transactions on the MedXchange system will exclusively be facilitated by our MedCash (MEDCASH) token. MedCash (MEDCASH) will also be what funds the miners and data silos. The currency can also be used to activate smart contracts or trade for keys. Also, hospitals, clinics and GPOs (Group Purchasing Organizations) will be able to deploy their supplier contracts on MedXchange as self-executing smart contracts. The project is backed by pre-agreed use cases, including a novel, lifesaving technology that targets a multimillion patient / end user population globally, potentially representing billions of system transactions annually. Other use cases are expected to board the system quickly.

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
1. Only 4 token holders.
2. No link to a review or discussion of the token
3. Total supply of token is 2.

**Comment by medxchange1** [comment]
Sorry, totally incorrect.
1. Total actual issuances on the block shows 4 yes. But entitled holders
are increasing daily as signups come in. We *just opened for early signup
of pre-ICO. Also, it shows we are not gratuitously handing out tokens. We
are keeping it tight to make sure we create a strong platform for price
growth. Nobody going to dump anything here. We've seen that movie a hundred
times. This is how you do it correctly. There are seasoned investment
bankers on our team.
2. See attached for description of token. This is all over our website.
3. Totally incorrect - there are 200 million tokens issued. See screenshot
attached. Click over to the smartcontract. (You might be looking at a
number with 18 decimals)

Thanks.

**Comment by Kryptoniq** [comment]
1. There are only  5 token holders as stated initially. 
2. No third-party review or discussion of the token 
3. I insist, there are only 2 tokens. You probably messed up the decimals.
![img_20180317_083316_995](https://user-images.githubusercontent.com/16838612/37552927-6d518a94-29be-11e8-9bcc-d6cc83a69a05.jpg)

**Comment by medxchange1** [comment]
Not sure what your role is here. But I INSIST - you are incorrect. Again, look at the smart contract. The smart contract controls everything? Not the way the decimals show up. That is immaterial.

**Comment by Kryptoniq** [comment]
Hi there, there is no point dragging this issue over and over again. 
Please,  show me a proof that your total supply is 200 million and not 2.
Thank you.

**Comment by medxchange1** [comment]
Ok, fair enough. Here is a complete transaction history and audit trail.

(1) Contract creation. 

(a) Here is the *verified contract source code showing initial supply created (of 200 million):
![contract-source-code](https://user-images.githubusercontent.com/35881074/37806390-af5241b0-2e0d-11e8-8f82-de81e59ab4a1.png)

(b) Here is the *verified smart contract showing the 200 million tokens. It also shows the current balance of 199953030 tokens (we will come back to this number again later once we reconcile)
--




![smart-contract-totsupply-and-bal](https://user-images.githubusercontent.com/35881074/37806435-f9c4bd68-2e0d-11e8-99a1-5e101488770f.png)

(2) Here is the first transfer of 100 tokens (already more than 2 of course, and anyway you have to move the decimal to the right 8 places)

![trf1-100](https://user-images.githubusercontent.com/35881074/37806516-670d38fa-2e0e-11e8-8da5-ee4deabb0c80.png)

(3) Here is the second transfer of 900 tokens 

![trf2-900](https://user-images.githubusercontent.com/35881074/37806527-7b4b3eca-2e0e-11e8-8071-dd117f655159.png)

(4) Here is the 3rd transfer of 1000 tokens 

![trf3-1000](https://user-images.githubusercontent.com/35881074/37806539-8e358694-2e0e-11e8-833f-9aebc67843d3.png)

(5) Here is the 4th transfer of 2970 tokens

![trf4-2970](https://user-images.githubusercontent.com/35881074/37806563-b564a204-2e0e-11e8-8d8a-ab643d69e7ff.png)

(6) Here is the 5th transfer of 42000 tokens

![trf5-42000](https://user-images.githubusercontent.com/35881074/37806571-c57a9680-2e0e-11e8-9107-436f8b894236.png)

(7) Finally, here is the reconciliation of all the above transactions that shows the current balance back to  199,953,030 tokens, which jibes with 2(b) above.

![reconciliation](https://user-images.githubusercontent.com/35881074/37806672-3ece8e06-2e0f-11e8-931e-b2ee492dea61.png)


Thanks.

**Comment by remedcu** [comment]
The above proves that you have no idea about your token smart contract. If you have written it yourself, then I would suggest you to learn a bit more. If someone else wrote it for you, you have hired someone stupid who just copy pasted it from somewhere else.

These are some points you should understand:

1. When you specify your token supply inside smart contract, then you specify total supply you want followed by X no. of zeroes. Where X is your decimal number.

So, if your total token supply is 50 and your decimal number is 4. Then you specify the total token supply as: 500000

So, what you have done here is 2 followed by 8 zeroes, which means your total token supply is just 2

2. When you specify your symbol inside smart contract, use " (double quotes) instead of ' (single quotes)

So, right now your symbol name is bigger than your token name.

As per your smart contract, the symbol name is: "0x4d45444341534800000000000000000000000000000000000000000000000000"

-------------

There is no way you can correct the total supply as well as the symbol as you have no minting function to increase the no. of total token supply.

You need to create a new smart contract for the same and update it everywhere, And next time you apply to list, do include the announcement for the smart contract update as well.

**Comment by Kryptoniq** [comment]
@remedcu thank you.
@Medcash just as i said earlier; You messed up the decimals.
Wrong: `totalSupply = 200000000;` should be be `totalSupply = 20000000000000000;` notice the 8 decimal at the suffix.
BTW: 0.00042 doesn't translate to 42000.
Your symbol is also invalid. 
I hope you accept the corrections and create a new contract 😊 . Thank you.

**Comment by medxchange1** [comment]
Ok fine. So why is the symbol invalid? Too long?

**Comment by medxchange1** [comment]
or bcs of the single/double quote issue?

**Comment by Kryptoniq** [comment]
My bad. The Symbol is okay.
I mistook the 'owner' line for `symbl

**Comment by remedcu** [comment]
Hey @Kryptoniq I think even the symbol is also not right due to use of bytes32 instead of string

**Comment by Kryptoniq** [comment]
@remedcu Yep. It should be `string`.
@Medxchange1 I'd advise you to use the Open Zeppelin framework.
