### ISSUE TITLE
Intention to delist: XBV

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#442]
Reason for delisting:

No bitcointalk or third party review.
Lots of other projects/sites/links utilizing a similar name:

- https://www.linkedin.com/company/blockventures/
- https://blockventure.io/en/
- https://www.blockventures.com/

----

Reason against delisting:

Videos made specifically for XBV.
Open communication from dev in original GH PR.
Exchange link was changed after listing. Shows somewhat active devs.

----

Other:

Couldn't find a way to verify team members, although the images weren't plagiarized AFAIK
Couldn't verify address: 2943 Col. Jardines del Bosque 44520 Guadalajara, Jalisco, Mexico

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/450

**Comment by freeatnet** [comment]
It also seems they've taken steps to trademark their logo: https://www.trademarkia.com/blockventures-87714877.html

I'll circle back to this with more info as soon as I can gather it.

**Comment by Kryptoniq** [comment]
@freeatnet the logos doesn't look alike.

**Comment by Kryptoniq** [comment]
I found another "Block Venture Project"  on bitcointalk https://bitcointalk.org/index.php?topic=2567923.0. 
I couldn't find this particular "Block Ventures"  online.

**Comment by KimuraTrap** [comment]
So I have a friend who was mislead in his first encounter with any crypto exchange or dealings. I've been doing research on this "crypto" and have been seeing a lot of discrepancies with the information, several name changes, and just straight up shady behavior. Anyone have any new news on these guys?

Ps. I'm a barber in California and it justso happens that the "owner" or partner in this crypto frequents the barbershop I work at. His name is Al something-or-other. On top of his shady behavior and misinformation he gave me the address the his newest site for the coin. 

https://xbv.io/index.html

Any information on the subject would be greatly appreciated!

Happy hunting!

PsPs. Why has XBV been brought up for delisting in the first place?

Thanks!

**Comment by brockmitchell** [comment]
Hey guys, i was just doing a bit of research online and ran across this thread. I actually personally know Al Rosario who is mentioned above by the barber- i also know another founding member named Scott Magers. Al has major ties to buisnessmen and other players in Guadalajara and they have begun the growth there with intent to expand globally to support the coin and their network. 

The original name for the coin was supposed to be BVC- i believe beaver coin snatched that tag prior to Block Ventures being able to secure it this is why you may find a name change recording. ANTSHARES did this as well and became NEO- this is not an unprecedented occurence.

the crypto world has exploded with illegitimate xoins and companies so its wise to be cautious BUT this company it totally legitimate and the employees listed are real people- two of which i know personally and others ive spoken to on the phone. Not only is this company real but I recommend purchasing some tokens while theyre still affordable. I believe this company has taken the steps and path to achieve success.

**Comment by freeatnet** [comment]
@KimuraTrap @brockmitchell Thanks for your feedback! We can consider this issue resolved, I believe.
