### ISSUE TITLE
Intention to delist: CSN

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#443]
Website is "suspended" now
Twitter activity looked legit up until getting listed.

Asked for clarification in TG group.

**Comment by JonathonDunford** [comment]
@freeatnet Thoughts?

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/450

**Comment by CrescentNetwork** [comment]
The website hosting issue has been resolved by now. Our website https://crescenttoken.com is functioning normally. I would request the respective official to relist CSN on the Forkdelta exchange.
