### ISSUE TITLE
Intent to Delist: VRTY

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#444]
__Reasoning for delist:__

There is no third party review or verification.
Most social links are broken.
Facebook and LinkedIn link to a different company: https://www.facebook.com/certified.bz
There is no team information on website.
Super low volume (0 in past 24h)

-----

__Reasoning against delist:__

They have an address listed, but I was unable to verify.
Certified Biz could be their parent company.
CertifiedBiz Facebook did post a link to VerityChain website.
No suspicious behavior from contract creator address: https://etherscan.io/txs?a=0x87e960f996e789ca2c8415fc449e4720adbe0497

----

__Other info:__

35 token holders

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/450

**Comment by JonathonDunford** [comment]
CSN rep got in touch with us. Looks good to go.

**Comment by JonathonDunford** [comment]
Need second opinions on this one as well.

**Comment by tradedbytony** [comment]
Check out the address for https://www.research-park.org. Does it look familiar? Unless Florida University's R&D department developed their own token, something's off.
