### ISSUE TITLE
Need a second opinion on delisting: JBC

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#446]
The token is named "Japan Brand Coin" but uses "blockchainneo" in every piece of marketing material and description. This could be an attempt to make people think it is in fact the project NEO.

There is no Bitcointalk announcement I could find.

Site says "Made in Japan", but their address is in Singapore.

Their website speaks of a prominent company called "J.Group" and "J.Six Corporation", but I can find no records of either company online.

No team members section.

----

__Other things to consider:__

Analytics shows that this coin has been a large contributor of Japanese traffic to ForkDelta.

I can't confirm or deny if it's a scam. Website doesn't have very much information to look for.

Their Facebook provides a physical address.

Etherscan shows over 4,000 token holders.

----

@freeatnet @Kryptoniq  Thoughts?

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/450

**Comment by freeatnet** [comment]
@JonathonDunford Can you please back up your claim "ame user trading 40 ETH back and forth"?

**Comment by JonathonDunford** [comment]
@freeatnet Unfortunately happened a while ago and doesn't show in trades now. Will remove that point from consideration.

**Comment by Kryptoniq** [comment]
The "blockchaiNeo" got me thinking.
It isn't even on the Neo platform.
Probably for deception.
