### ISSUE TITLE
Intention to delist: BZX

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#447]
User reported this was the same person behind the fake XUL

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/450

**Comment by JonathonDunford** [comment]
Telegram links 404
Medium links 404
How do I buy PDF 404s

This was the XUL scam coin (WARNING SCAM): https://etherscan.io/address/0x382a71ecb288da8701428406a36ffa5d8f072d55

This is the scam XUL coin contract creator:
https://etherscan.io/address/0x8611084aecbb953b2c76838a30168388bda51783

This is the BZX coin contract:
https://etherscan.io/address/0x70838403ecc194b73e50b70a177b2ef413a2f421

The contract creator address is exactly the same.

https://etherscan.io/address/0x8611084aecbb953b2c76838a30168388bda51783

That address appears to be actually in use as there are real transactions, not just contract creations like you would see from a third party.

**Comment by freeatnet** [comment]
I am in favour of delisting tokens associated with known scams.
