### ISSUE TITLE
Intention to delist: BTCP

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#449]
Bitcointalk comments are spam.
Contract creator came out of address with other spam.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/450

**Comment by JonathonDunford** [comment]
Contract creator: https://etherscan.io/address/0x92c5d6898abbd58e388aa94c816d4d17387a8859

I reached out to the BTCP dev and he stated the contract was created by a third party service which would explain why there are 900+ contracts from that address.

Barring that, Bitcointalk comment spam is hard to verify and shouldn't be grounds for delisting IMO.

Activity verified on Twitter and in Telegram.

Going to close this issue.

**Comment by luizlopes123** [comment]
thanks forkdelta we are not spam and we work seriously
BITCOIN PURE and tokem honest and within the parameters of the etherio network

Thank you again for the trust
forck delta
https://btcpure.xyz/
https://bitcointalk.org/index.php?topic=2612489
https://twitter.com/btcpure
admin@btcpure.xyz
