### ISSUE TITLE
Add FOODcoin to your listing please!

### ISSUE THREAD

**Issue by bigcball** [forkdelta/tokenbase#45]
The contract address. **0x2a093BcF0C98Ef744Bb6F69D74f2F85605324290**
A link to the token issuer's official website. **https://www.foodcoin.io/**
A link to an official page confirming the contract address. **https://www.foodcoin.io/contract-help**
A link to a third-party review or discussion of the token, like an established ICO review blog. 
https://www.youtube.com/watch?v=QMdAEhPkNbA
https://www.icoranker.com/ico/foodcoin/

**Comment by freeatnet** [comment]
Good work on the request, @bigcball!

**Comment by bigcball** [comment]
Thanks! I would have liked to have provided the proper coding, but i'm not familiar with it. Once it is properly formatted, would you mind sharing it back? I'd then be able to understand it better and provide things formatted already.
