### ISSUE TITLE
Listing Request - CVH

### ISSUE THREAD

**Issue by CVHCoin** [forkdelta/tokenbase#451]
Contract address: 0x52db8ebf894036ec997da693c5fa237a4fb69d10

Issuer's official website: http://cvh.io/

Official contract address confirmation: http://cvh.io/article.php?gid=261

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2550990.new

Description: Curriculum Vitae Chain is the first blockchain application in recruiting sector in Asia, and CVH is the token used in it.

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews / comments.
Kindy provide link to any other third-party review of the token.
Thank you.
