### ISSUE TITLE
Delist "E" tokens. [Pump & Dumps] [Abandoned Tokens] 

### ISSUE THREAD

**Issue by FlamesOGK** [forkdelta/tokenbase#454]
After “eBitcoin” being the first “E” coin on EtherDelta, a bunch of other “E” tokens were being listed like crazy on EtherDelta, some beings scams because they were there just for the pump and dump. Heres a reason why these tokens should be delisted and why.

Also, I feel that some of these tokens are just the same people creating them. The idea behind them are the same for most tokens, same people just different name. Also, I think that EtherDelta made some of these tokens for themselves to get money out of because most of these didnt even meet the requirements EtherDelta were asking for, most have no websites/social media and contracts arent even verified on EtherScan.

Most of these tokens will have the same issues because of the same people just creating the tokens so the issues will be the same. I also think that with no Coinmarketcap listing after months shows how inactive these "teams" where with these tokens. 

- This is a useless token thats up in your site. [ELTC,ELTC2,ELTC3]
https://gyazo.com/510fa68f310f8bc3108bbbfa5aa501cb
They never cameback.
I'd show you their CMC pump and dump but they also delisted from there.

- This is what you guys are introducing to your investors [NEOG]
https://gyazo.com/a7bf5aa5ae414bba2a7a8cacfc00f484

- This is ELITE's EtherScan, "EthereumLite" [ELITE]
https://gyazo.com/4d798ad46786caf08d3195fa3a902b0c
You see all the etokens they own?
Isnt is suspicious?
Why would all devs just send to "ELITE"  all these other E tokens...
They are all scams ranned by the same people.

- [ECASH] hasnt been working since October last year.
https://gyazo.com/f683f5668a5766deb018eb2f88bcdf9e
The dev confirmed that he sold the token to investors. From there the token just disappeared
Made gains on YoBit this year, they got listed cause they paid them to list them last year.

(THE LIST GOES ON, IF YOU MAKE RESEARCH ON THESE TOKENS YOU WILL KNOW WHAT IM TALKING ABOUT)

 List:
- Bitcoinereum [Team left after the pump and dump (currently no team)] (Bad for investors, they dont know they are investing on an abandoned project should be delisted ASAP). 
- BTCBlue [Team left after the pump and dump (currently no team)] [This token claims that they will have a token sale this month, but theres already tokens in circulation in ForkDelta (scam?)]
- BTCE [Team left after the pump and dump (currently no team)] [no social media, and has low volume]
- BTCRed [No website, abandoned project, shitcoin claims the token is used when “You are feeling red”] [Website not working, no social media]
- EBCC [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [Inactive on Social Media since November 2017]
- EBCH [Low volume] [Social media hasnt been update since February 2018] [Seems like a scam, team picture dont seem real.] [Token has no real use]
- EBCHB [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No social media]
- EBCSH [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No social media]
- EBTG [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No links in EtherScan after half a year] [No social media]
- EBYTE [No Coinmarketcap after months of listing] [No social links on etherscan, token doesnt have any use, low volume]
- ECASH [Team left after the pump and dump (currently no team)] [Pump & Dump] [Social media hasnt been updated since October 2017] 
- EDASH [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No tokens circulating] [No EtherScan links] [No social media links]
- EDOGE [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [Website doesnt work/no social media]
- EETHER [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No website/no social media]
- EGAS [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [Social media last updated December 2017]
- ELITE [Team left after the pump and dump (currently no team)] [Pump & Dump] [Claimed Hack/Lost Token Access]
- ELTC [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No website/social media links] [Not showing up on EtherScan]
- ELTC2 [Team left after the pump and dump (currently no team)] [Pump & Dump] [No Website/Social Media] [No Coinmarketcap after months of listing] [Claimed Hack/Lost Token Access]
- ELTC3 [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No website/no social media links]
- ELYTE [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No website/no social media]
- ENEO [Team left after the pump and dump (currently no team)] [Pump & Dump] [No tokens in circulation] [No website/no social media] ETHB [Abandoned, low volume] [No Coinmarketcap after months of listing] [No websites/no social media]
- EUSD [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No website/social media]
- EXMR [Team left after the pump and dump (currently no team)] [Pump & Dump] [No Coinmarketcap after months of listing] [Airdropped tokens, and now doing an “ICO” (scam?)] 
- EXRP [Team left after the pump and dump (currently no team)] [Pump & Dump] [No Coinmarketcap after months of listing] [No website/social media]
- EXRP2 [Team left after the pump and dump (currently no team)] [Pump & Dump] [No Coinmarketcap after months of listing] [No website/social media]
- EZEC [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No links on EtherScan] [No website/no social media]
- EZEC2 [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No links on EtherScan] [No website/no social media]
- IBTG [Team left after the pump and dump (currently no team)] [No Coinmarketcap after months of listing] [No links on EtherScan] [No website/no social media]
- IETH [low volume][No Coinmarketcap after months of listing] LCASH [Abandoned, low volume] [No Coinmarketcap after months of listing] [Hasnt been active on social media since November 2017]
- LTCRED [Team left after the pump and dump (currently no team)] [Pump & Dump] [No Coinmarketcap after months of listing] [All it does is thank people on Twitter for following] [No real use for the token] 
- LTG [Team left after the pump and dump (currently no team)] [Pump & Dump] [No website, last updated social media was November 2017]
- NEOG [Team left after the pump and dump (currently no team)] [Pump & Dump] [Claimed Hack/Lost Token Access] [Website not working] [Dumped tokens on all investors] [Website isnt working
- EBTCS [Low volume][No Coinmarketcap after months of listing]

**Comment by JonathonDunford** [comment]
@FlamesOGK I don't think just low volume and no CMC is grounds for delisting.

How are the projects abandoned?

Please go into more detail on each one as we will have to put it up for community discussion.
