### ISSUE TITLE
Adding An ERC20 Token - FinTech Coins (FTC)

### ISSUE THREAD

**Issue by fintechcoinsftc** [forkdelta/tokenbase#455]
Contract address: 0xe6f74dcfa0E20883008d8C16b6d9a329189D0C30

Issuer's official website: https://ftccoins.org

Official contract address confirmation: https://ftccoins.org/en/faq

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2238018.msg22576838#msg22576838

Description: FinTech Coins (FTC) believes that everyone should be able to access cryptocurrencies. That’s why we have transformed complex technology into a straightforward user-friendly product. We have created a unique and comprehensive ecosystem, where users and merchants can connect and transact effortlessly together. 
With blockchain technology comes a need for high levels of security. At FTC, our systems guarantee security and privacy for our large network of users. We ensure that our agents, affiliates, traders and investors are protected within our secure infrastructure.

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews and your ticker "FTC" is already in use by Feathercoin. 
In addition, I can't find your contract on the website.
