### ISSUE TITLE
List CGCOIN tokens

### ISSUE THREAD

**Issue by crowdgenie** [forkdelta/tokenbase#456]
Contract address: 0x2d9765a94ff22e0ca3afc3e3f4b116de2b67582a

Issuer's official website: http://genieico.net/

Official contract address confirmation:
https://medium.com/@genieico/genie-ico-contract-and-token-information-f31aa7a7d59

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2434698.0
https://www.youtube.com/watch?v=Z2Sn9dU-se8&index=4&list=PL2bOogx1dP7pOwt6Ul3DfyclOyNQyR58_

Description:
What is Genie ICO about?
“Business Loans Asset Exchange”: Build a private capital hub for Asia Pacific built on smart contracts to make the flow of funds among lenders, and between Lenders and Borrowers more efficient, cheaper and safer. This will include: 

1) Digital Passport: Blockchain based identity management for users 
2) Tokenized lending platform: Enable lending and borrowing without borders. 
3) Business Loans Asset Exchange: Allow lenders to sell invested business loans in fraction, enhance investment liquidity

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
Hi there, any reason why there are only three tokenholders while your ICO is already completed?

**Comment by tradedbytony** [comment]
Open issue at #456 and open PRs at #557, #556 and #555.

**Comment by crowdgenie** [comment]
Hi,

There are 1500+ token holders. Token transfers were made on 12th March

May I please know if we can be listed? I have already submitted the pull request.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x2d9765a94ff22e0ca3afc3e3f4b116de2b67582a, http://genieico.net/

**Comment by crowdgenie** [comment]
Is there any update on this yet?

**Comment by AnonyMouseCoder** [comment]
I got tokens, waiting to get listed.

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 9th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! CGCOINS has been listed: https://forkdelta.github.io/#!/trade/CGC-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
