### ISSUE TITLE
Listing request - Capital Token

### ISSUE THREAD

**Issue by suvorovpro** [forkdelta/tokenbase#458]
Contract address: 0x84A8222618acd4Ac60547B6e89cc2C72A12a49DD
https://etherscan.io/token/0x84A8222618acd4Ac60547B6e89cc2C72A12a49DD
Symbol: CAPT
Full Name: Capital Token
Decimals: 18

Issuer's official website: http://capitaltoken.io/

WP - http://portfolio.capitaltoken.io/web/whitepaper_rus.pdf

Official contract address confirmation: http://capitaltoken.io/#rec44298167

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3024746.0

https://forum.bits.media/index.php?/topic/75580-📈-💰-ann-capital-token-capt-инвестиционный-токен/

Our project is designed for Russian-speaking users, so we do not have any materials in English
Наш проект рассчитан на жителей СНГ и русскоговорящих пользователей и не имеет материалов на Английском языке.

Description: Capital Token is an investment token with a mechanism for raising prices and values. In essence, it is an investment fund based on the principles of openness and transparency.

Capital Token - это инвестиционный токен с механизмом повышения цены и ценности. По сути своей являясь инвестиционным фондом основанным на принципах открытости и прозрачности.

**Comment by suvorovpro** [comment]
---
addr: '0x84A8222618acd4Ac60547B6e89cc2C72A12a49DD'
decimals: 18
description: >-
 Capital Token is an investment token with a mechanism for raising prices and values. In essence, it is an investment fund based on the principles of openness and transparency.
links:
- Telegram: https://t.me/capital_token
- Website: http://capitaltoken.io/
- Blog: http://capt.fund/
- YouTube: https://www.youtube.com/channel/UCcWbER52yhdS4YAtQEZXv7A
- Whitepaper: http://portfolio.capitaltoken.io/web/whitepaper_rus.pdf
name: Capital Token
symbol: CAPT

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x84a8222618acd4ac60547b6e89cc2c72a12a49dd, http://capitaltoken.io/
