### ISSUE TITLE
NEXT PAYMENT GOLDEN (NEW LISTING)

### ISSUE THREAD

**Issue by febieki23** [forkdelta/tokenbase#459]
Contract address: 0xfc7b16a373c2ca3770a6c1b234852eeefdce892a
--

Issuer's official website: nxo.store

Official contract address confirmation:  0xfc7b16a373c2ca3770a6c1b234852eeefdce892a
--
ANN Bitcointalk (disccusion) : https://bitcointalk.org/index.php?topic=3091796.new#new

A link to a third-party review or discussion of the token:

Description:
NXO is multipurpose coin NXO is not just for coins for trading only, but for payments as well. 
We will load goods from the refreshments of some Famous Online Shop Sites, even those that are difficult to buy when not using a credit card. 
NXO will ease Payment with NXO without need Paypal or maybe card credit. 
NXO will choose The Best Seller On A Large site like Amazon,alibaba, and other. 
We will also load home products to be loaded and shipped to all over the world justone click cekout goods will be ready to be sent. 

Name: NEXT PAYMENT GOLDEN
Symbol: NXO
Decimal: 0
Contract Address: 0xfc7b16a373c2ca3770a6c1b234852eeefdce892a
Initial Supply: 9,500,00 NXO
Supply: 10,000,000 NXO

About NXO: https://www.youtube.com/watch?v=lDGkYqvXOoc&feature=youtu.be 
Website: http://nxo.store/
Our Team: http://nxo.store/ourteam
WhitePaper: https://nxo.store/images/whitepaper/WhitePaper.pdf
ANN: https://bitcointalk.org/index.php?topic=3091796.new#new

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient comments / reviews.

**Comment by febieki23** [comment]
how many comments should be met, we are not too focused on bitcointalk but
in real sales, bitcointalk is not a real benchmark

**Comment by tradedbytony** [comment]
Open PR at #475
