### ISSUE TITLE
CashBag.io Token Listing Request

### ISSUE THREAD

**Issue by jonatforge** [forkdelta/tokenbase#461]
Contract address:   
![image](https://user-images.githubusercontent.com/19273560/37204216-c2f0ab00-2398-11e8-81de-49d5f44a5317.png)

Issuer's official website:  http://cashbag.io  / https://tokensale.cashbag.co   / https://cashbag.co

Official contract address confirmation:
![image](https://user-images.githubusercontent.com/19273560/37204267-e52bfe7c-2398-11e8-9202-787439cc122a.png)

The contract address is visible once the user has registered & logged in on https://tokensale.cashbag.co
https://twitter.com/CashBagco/status/972060171689132032 

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2311052

Description:

CashBag - The blockchain platform for instant settlement and micropayments of cash back rewards.
We're an existing business with a unique cryptocurrency value add.

We've eliminated the cost & time it takes to get cash back payments into consumers wallets.
Bank fees make it impossible to do micro-payments. Processing fees eat up all the value!
By building our settlement engine to interface with the Ethereum blockchain we've created an instant settlement platform that not only cut our own costs, but it enabled us to settle micro-payments and keep an immutable record!

**Comment by jonatforge** [comment]
apologies, swapped around the submission info, just updated it!  Would really appreciate it if you'd add our token to forkdelta.

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by tradedbytony** [comment]
Same request as #505

**Comment by Kryptoniq** [comment]
Has PR #505.
