### ISSUE TITLE
Please list in token

### ISSUE THREAD

**Issue by necony** [forkdelta/tokenbase#462]
Contract address:0x7dFa96685B542D96a9be2d4a191950Fbeb11c5BB

Issuer's official website:https://www.webbot-cryptocurrency-japan-necony.com/02-services

Official contract address confirmation:https://ethplorer.io/address/0x7dfa96685b542d96a9be2d4a191950fbeb11c5bb

A link to a third-party review or discussion of the token:Not yet. However, there is a community in the discord.
It's is・・・https://bitcointalk.org/index.php?topic=3041382.0

Description:This is a Japanese community token.
There are almost 1,500 holders already, and it has already been listed on the exchange called CREX 20.

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
We have a pending issue here #310.

**Comment by necony** [comment]
thank you for your reply.
I have already replied, which ones are not allowed?
If there is a correction part, it cures.

2018-03-10 21:11 GMT+09:00 Krypton <notifications@github.com>:
