### ISSUE TITLE
Listing Request: COGNX

### ISSUE THREAD

**Issue by cognx** [forkdelta/tokenbase#464]
Contract address: 0x74fe5f01f6f82e6feddacad6c0f09cf6933c43de
Symbol: COGNX
Full Name: COGNX
Decimals: 18

Website: http://www.cognx.co.in
Whitepaper: http://www.cognx.co.in/doc/whitepaper.pdf
Description: CognX project use cutting edge cognitive technologies to predict how specific crypto currencies will perform in the near future

Link to confirm contract: http://www.cognx.co.in in the "TOKEN DETAILS" section

more in depth details:
medium: https://medium.com/@cognx
twitter: https://twitter.com/COGNX_COIN
telegram:https://t.me/cognx

Third-party comment(s) on the token: https://bitcointalk.org/index.php?topic=2437063.0

Opened the pull request #494

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
#494
