### ISSUE TITLE
Want to listed Apus Token on Forkdelta

### ISSUE THREAD

**Issue by liamhoang** [forkdelta/tokenbase#465]
**The contract address:** 0xbeB100a5970f75abB77031cc1832B4C934A0C1bE
**A link to the token issuer's official website:** https://apustoken.com/
**A couple sentences for token description:** We are A decentralized and open-source cross Ethereum platform dedicated to enhancing the gaming experience on the blockchain for all users.
**A link to an official page confirming the contract address:** https://apustoken.com/
**A link to a third-party review or discussion of the token, like an established crypto review blog or a BitcoinTalk thread with significant discussion of project's purpose and merits from highly-ranked users:** https://bitcointalk.org/index.php?topic=2468758.0

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
There are only 4 token holders at the moment.

**Comment by tokendelta** [comment]
Hello sir, tokens will be distributed free as airdrop and bounty in the next few days. We are filtering out valid registry entries.
