### ISSUE TITLE
Ethereum Gold ETG

### ISSUE THREAD

**Issue by EthereumGoldETG** [forkdelta/tokenbase#467]
Contract address: 0x28c8d01ff633ea9cd8fc6a451d7457889e698de6

Issuer's official website: https://www.ethereumgold.info
WP : https://ethereumgold.info/Golden-Paper-ETG.pdf

Official contract address confirmation:  You'll find information including contract here : https://www.ethereumgold.info

A link to a third-party review or discussion of the token: https://t.me/joinchat/GzPNJhCuW5Lw862j_qJy3g

Description: The Future Of Payments Between Companies
https://medium.com/@amandaETG/the-revolution-of-ethereum-gold-etg-ce8b8316db09
Telegram : https://t.me/joinchat/GzPNJhCuW5Lw862j_qJy3g
Twitter : https://twitter.com/ethereumgoldetg

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x28c8d01ff633ea9cd8fc6a451d7457889e698de6, https://www.ethereumgold.info

**Comment by EthereumGoldETG** [comment]
Hi team Forkdelta please we want to update our token information and listing our new token like a swap if you can or as new token : 

contract : 0xa96f31f1c187c28980176c3a27ba7069f48abde4
max supply : 6 000 000 000 ETGP
decimals : 8
Symbol : ETGP

Issuer's official website: https://www.etgproject.org
Read our Golden Paper  : https://etgproject.org/Golden-Paper-ETG.pdf

Official contract address confirmation: You'll find information including contract here : https://www.etgproject.org

A link to a third-party review or discussion of the token: 
Contact me at Telegram here : @EthereumGold 

Description: Decentralize Payments Of Companies
Ethereum Gold Project will facilitate the transactions between companies and communities using ethereum blockchain .

Medium : https://medium.com/@amandaETG/the-revolution-of-ethereum-gold-etg-ce8b8316db09
Telegram : https://t.me/joinchat/GzPNJhCuW5Lw862j_qJy3g
Twitter : https://twitter.com/ethereumgoldetg

Team ETGP ,
Best regards .
