### ISSUE TITLE
Adding Lendroid Token (Released 00:00 GMT on 3/10)

### ISSUE THREAD

**Issue by cheeselord1** [forkdelta/tokenbase#468]
Contract address: 0x4de2573e27E648607B50e1Cfff921A33E4A34405

Issuer's official website: https://lendroid.com/

Official contract address confirmation:
https://blog.lendroid.com/this-is-the-genesis-of-the-lendroid-support-token-46124fcf3a13

A link to a third-party review or discussion of the token:
http://thetokeninvestor.com/lendroid-review/
https://steemit.com/lendroid/@thevoltsone/lendroid-ico-a-detailed-study
https://bitcointalk.to/index.php?topic=2479903.0

Description:
Lendroid is a non-rent seeking protocol partnering with 0x Project Relayers that enables Margin Trading and short selling of ERC20 tokens without having to give custody of funds to a centralized service.

Note: Lendroid tokens become transferrable at 00:00 GMT on 3/10

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible. Pull Request will be faster than Issue I think. You can then close this issue here.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x4de2573e27e648607b50e1cfff921a33e4a34405, https://lendroid.com/
