### ISSUE TITLE
Bogda Logistics

### ISSUE THREAD

**Issue by TippyCanoes** [forkdelta/tokenbase#469]
Contract address:  0xe178b1183eec75ee999436e379fadb1099f00baa

Issuer's official website:  https://bogda-token.webnode.com/

Official contract address confirmation:

A link to a third-party review or discussion of the token:

Description: Started off as a Meme token off of 4chan. Has turned into a project that is looking to become a platform for smaller, lesser known tokens/coins.  Project is in its infancy but is moving along quickly.

**Comment by Kryptoniq** [comment]
1. Your website online contains an image. 
2. You did not  provide a link to a third-party review or discussion of the token.
