### ISSUE TITLE
Listing request: Hydrogen Platform HYDRO

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#472]
Contract address: 0xebbdf302c940c6bfd49c6b165f457fdb324649bc

Issuer's official website: https://www.hydrogenplatform.com

Official contract address confirmation: https://www.hydrogenplatform.com/docs/hydro/v1/ (see "Resources" -> "Hydro Contract Address")

A link to a third-party review or discussion of the token: 
https://www.crunchbase.com/organization/hydrogen
https://www.bloomberg.com/research/stocks/private/snapshot.asp?privcapId=548107682
https://bitcointalk.org/index.php?topic=2778123.0

Description:

> Hydro enables developers to seamlessly deploy blockchain in their existing applications, without the need to create expensive infrastructure.

**Comment by freeatnet** [comment]
cc @matthewrkane, maybe

**Comment by freeatnet** [comment]
Closed until the contract bug is resolved.

**Comment by freeatnet** [comment]
Contract bug resolved

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xebbdf302c940c6bfd49c6b165f457fdb324649bc, https://www.hydrogenplatform.com/
