### ISSUE TITLE
Formalize Listing Requirements

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#473]
It has become evident that we need to make our listing requirements more clear and robust in order to prevent the possibility of malicious tokens entering the system. We also need a formal document on GitHub that outlines the requirements for a proper token listing going forward.

**Benefits:**
This lowers the likelihood of malicious tokens entering the system.
This increases the openness of our procedure and opens it up for community feedback.
This formalizes a procedure, so people understand the requirements of a proper listing request.
This makes it easier on token developers to give us the proper information required for a submission.

**Why the required data:**
- A website will give much needed information about the token, team, and provide a source for verifying information given in the issue submission.
- Chrome will require all websites be HTTPS by June 2018.
- A description helps inform users about the token.
- We need a link to verify that the submitted contract address is the correct address for the project and not an imposter address.
- Public forums for discussion on the project allow the community to weigh in on the token's credence. This strengthens the case for the project's liveliness.
- Third party verification is another step that makes it easier to validate/verify the token issuer is serious about the project.
- We need to make sure the token issuer is reachable.

----

## For Token Submissions

Anybody can request a token to be listed on ForkDelta, not just the token developers. However, the token submissions must strictly adhere to the following rules.

#### Absolutely required:

- The contract address.
- A link to the token issuer's official website. __This MUST be in HTTPS.__
- 1-3 sentences for the token's description.
- A link to an official page confirming the above contract address. This needs to be on the official domain of the token issuer. Etherscan does not count as a confirmation.
- Links third-party review or discussion of at least two kinds. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc.
- Well-defined channels of communication with the token issuer must be published on the website. This includes, but is not limited to: public social media, some form of instant messaging (Telegram, Discord), email.

You must pay attention to the issue or pull request you post. We will post comments and make updates on it, some of which will need your attention.

#### Optional questions:

- Do you represent the token issuer or are you simply an interested member of the community?
- How was this token distributed? (ICO, Airdrop, etc.)
- Is there more information on the token issuer that is separate from the token? Example: Information about a parent company.

#### Strongly encouraged:
- Presence of a whitepaper or a project roadmap.
- A link to a third-party review of the token like an ICO ranking website or a blog.
- CoinMarketCap listing
- Strong social media presence
- More than 30 token holders
- Team member information on website

#### Strongly discouraged:
- Piggybacking off of other coins in your token names. For example: "BitcoinEther"
- Using free domains (like WIX, Weebly, etc)

#### Absolutely not allowed:
- Same ticker as already listed project on ForkDelta
- Same ticker or name as prominent project
- Any form of plagiarization including, but not limited to: pictures, names, descriptions
- Affiliation with any other verified scams
- Falsified links

#### Exceptions
There may be very rare cases where prominent ICOs do not adhere to our requirements, but have a large amount of users and are legitimate projects. We reserve the right to waive requirements in those rare cases.

**Comment by tradedbytony** [comment]
I'm a bit confused now. Over a week ago I asked about ERC223 and it seemed like they weren't gonna be listed anymore (issue #323) but now I see a "Make sure the token has proper ERC20 or ERC223 support." Does that mean ForkDelta has switched contracts so you guys can now list ERC223 tokens?

Some ERC223 contracts, such as the ones listed in issue #323 don't work, or at least didn't, with FD. Did that now change?

Thanks in advance.

**Comment by Kryptoniq** [comment]
I think we are good to go with these set of rules.

**Comment by JonathonDunford** [comment]
@tradedbytony ERC223 contracts that utilize proper whitelisting _should_ work with the current contract.

However, we have a new contract in development (https://github.com/forkdelta/smart_contract) that will have full support for ERC223.

**Comment by freeatnet** [comment]
I think we should split these requirements up into projects claiming to plan or have had an ICO (aka crowdsale) vs projects with no ICO.

Projects with claimed ICOs must provide sufficient evidence of that ICO happening: they must be reviewed by _trusted_ ICO blogs or ranking websites (trusted: hacked.com, icoalert.com, icobench.com, icodrop.com; not trusted: icoholder.com), plus potentially receive a passing (TBD what that is specifically) review from a community audit like [icocheck](https://icocheck.io/). I'm open to requiring a whitepaper from projects with an ICO.

For other projects, a simple project mission statement will suffice. The project mission statement must be articulated and demonstrate what goals the project is trying to achieve. This should allow experimental tokens onto the platform. We can also ban specific project missions (e.g., where the main purpose of the project is creating a "fast and safe payment cryptocurrency" or a "store of value" token).

@JonathonDunford In other notes, could you please move the procedure to a separate issue? We should focus this issue on listing requirements and open it up to community discussion by posting it on our social media channels.

**Comment by freeatnet** [comment]
@JonathonDunford Could you please move the procedure to a separate issue? We should focus this issue on listing requirements and open it up to community discussion by posting it on our social media channels.

Plus, could you elaborate on what brings about this change proposal and why you think those requirements for token submissions make sense?

**Comment by JonathonDunford** [comment]
@freeatnet 

Edited and moved: https://github.com/forkdelta/tokenbase/issues/495

Please take a look at both and see if there is anything I missed.

**Comment by JonathonDunford** [comment]
From https://github.com/forkdelta/tokenbase/issues/495

----

@tradedbytony :

If I may add, would it be possible to request for the token wanting to be listed to have their own website rather than a free website? For instance, there are some tokens such as https://forkdelta.github.io/#!/trade/EM-ETH which don't even own their own site (not to mention, that token doesn't even have properly set up links, such as Twitter, and use the default Wix ones).If they can't even afford to spend a few bucks for their own domains, perhaps they aren't worth listing. That's just my humble opinion.
--

@JonathonDunford :

@tradedbytony We have actually discussed that in Discord and it is a good point.The only reasoning against that that we can find is the fact that even our own website is hosted on a "free domain" and utilizes github.io for hosting. I'm not entirely sold either way, but I lean towards requiring a domain name as I think it lends more validity/credence to the project.Should there also be social media requirements?
--

**Comment by tradedbytony** [comment]
Also, if I'm getting this right, there's going to have a change to the template for when we open a new issue. For instance, right now when we open an issue it shows "A link to a third-party review **or** discussion of the token" which makes us choose between a third-party review OR bitcointalk, while the proposed changes here suggest we'll need them BOTH. Therefore, I suggest changing the default template to indicate this change.

**Comment by tradedbytony** [comment]
Also, if I'm getting this right, there's going to have a change to the template for when we open a new issue. For instance, right now when we open an issue it shows "A link to a third-party review **or** discussion of the token" which makes us choose between a third-party review OR bitcointalk, while this proposed change suggests we'll need them BOTH. Therefore, I suggest changing the default template to indicate this change.

**Comment by freeatnet** [comment]
I think this is on the right track.

I hear @tradedbytony's concern about requiring BitcoinTalk threads. On the one hand, in my own experience of working on our listings, projects' BitcoinTalk threads weren't always a reliable source for community discussion and were susceptible to developers gaming the system via "leave a good BitcoinTalk comment" bounties. On the other hand, some projects might forgo a BitcoinTalk thread entirely because of their own priorities (e.g., they have an active marketing campaign otherwise and a BitcoinTalk thread is simply too low-yield). I propose replacing a BitcoinTalk thread requirement with the following:
1. Require third-party review or discussion links of at least two kinds. This increases breadth of opinions, strengthens the case for the project's liveliness.
2. To make sure the token issuer is reachable, require well-defined channels of communication with the token issuer to be published on the website: public social media is ideal, but I would also settle for an IM contact or email.

I'm a little concerned about requiring a whitepaper. Specifically, a number of projects that went through our listing process had whitepapers that talked at length about what blockchain or Ethereum smart contracts are, but had little information about the project, vision, team, or milestones. Instead of requiring a whitepaper, I would set requirements in terms of information we want to see published.

A few things we might want to explore further:
* Asking the submitter if they represent the token issuer or are simply an interested member of the community :)
* Distinction between tokens initially distributed via ICO/crowdsale and those distributed through other means.
* Token use details: category(-ies?) and brief description of token properties (e.g., whether the token is a utility token, dividend-yielding token). Additionally, whether the token issuer is explicitly interested in the token being listed on an exchange.
* Token issuer details: business name, website (if different from token website), possibly a brief description of the entity. This could be helpful when one issuer has multiple projects/tokens.


P.S. I'd like to drop the lowercase address requirement. It's a technical detail, which we might change based any time at our discretion.

**Comment by freeatnet** [comment]
@JonathonDunford I think we should publish this discussion to our SM channels, what do you think?

**Comment by Kryptoniq** [comment]
Minimum token holders should be at least 30 because a contract creator can easily send tokens to 10 different wallets and then request for listing. 
If a token wants to be listed, they should make sure they have done an initial distribution before creating an issue.

**Comment by tradedbytony** [comment]
I agree with raising the minimum amount of token holders. It's way too easy to just raise it to 10 by oneself. Not saying one person couldn't do 30 by themselves but at least make them work for it, not to mention if there's only like 30-40 token holders and if the vast majority of those holders has nothing in their wallet, not even ETH, other than that one token it'd be pretty obvious something isn't right.

**Comment by freeatnet** [comment]
@Kryptoniq @tradedbytony Can you share what you're looking for when you want to introduce a minimum number of holders requirement?

**Comment by JonathonDunford** [comment]
The only reason why I don't think 30 token holders should be an absolute requirement is that it's very possible a company may choose to perform their ICO on ForkDelta.

**Comment by JonathonDunford** [comment]
I have updated the original comment to reflect commentary up to this point.

**Comment by Bilibit** [comment]
Sounds good and balance now for future listings.

**Comment by walerikus** [comment]
I think it would be great to put some marketing staff, like required amount of retwits to review a new application

**Comment by rartokens** [comment]
My 2 cents only.
FD and the original ED are known for simple listing process and it has been the trademark the exchange. If the requirements are getting tighter and it might end with no difference with the other exchanges (if that is the goal). My opinion is not to become too tight and not too lose.

on the other hand, ie Binance DEX, will be listing almost any coin. https://www.bloomberg.com/news/articles/2018-03-13/crypto-exchange-binance-launches-decentralized-trading-network

I hope you will achieve balance in this effort.

**Comment by remedcu** [comment]
I think that sums up everything.

**Comment by JackAsparrow** [comment]
How about allowing any coin to join Forkdelta without prior approval from the FD team. Instead maybe try putting a STAR symbol or something by all the officially verified tokens and putting a "Warning  the token you are about to trade has not been verified by the ForkDelta team and may potentially be a scam or have other malicious intent"...???? 

Or can create a main page where all the tokens listed have been officially verified already and add a 2nd/separate page for unverified tokens. Then put up a BIG warning sign stating that said tokens  on the 2nd page have not been verified or deemed trust worthy by the community/FD team and may be of malicious intent. It is not recommended that you trade any of these tokens. etc etc.

**Comment by BTC-lite** [comment]
HTTPS should be made mandatory only if an ICO is being carried out or user data is taken/stored. Otherwise it's useless. 

Just my 2 cents.

**Comment by freeatnet** [comment]
@JackAsparrow you will still be able to trade any token by contract address, these are the requirements to get on that official list

**Comment by freeatnet** [comment]
@btc-lite Requiring HTTPS for all is in line with industry best practices: https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html?m=1

**Comment by Kryptoniq** [comment]
@rartokens it will be fatal if we just list any token without due diligence. It will negatively affect the ecosystem. We care about people's funds. 
ForkDelta don't want to be known as the exchange for "scams" and "frauds".

**Comment by somidax** [comment]
From our point of view, safety is non negotiable. so HTTPS should be a must for all in line with industry best standard ISO/IEC 27001 @BTC-lite @freeatnet

**Comment by Kryptoniq** [comment]
@JonathonDunford, @freeatnet
Pertaining the proposed 30 minimum-holders;
If a token wants to carry out their ICO on FD, it should be stated.
Most tokens are "Airdrop tokens". 
Scam teams can end up selling  worthless tokens to people on FD, without an actually future plan, then move to the next scam.
What is the essence of 10 token holders for a token with over 100 million supply? It means 99.99% of the tokens belongs to the team.

**Comment by JackAsparrow** [comment]
@freeatnet Ah I see. Thanks for the clarification.

**Comment by needscoin** [comment]
@JonathonDunford, just read out all the required information. Now it'll be easy for our team to get prepare to submit an issue for @NeedsCoin. After finalizing our Whitepaper we'll apply too. Can you please explain of these point:

"A link to an official page confirming the above contract address. This needs to be on the official domain of the token issuer. Etherscan does not count as a confirmation."

>> Can we use this: https://etherscan.io/token/0x9344b383b1d59b5ce3468b234dab43c7190ba735 or https://etherscan.io/address/0x9344b383b1d59b5ce3468b234dab43c7190ba735

"Links third-party review or discussion of at least two kinds. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc."

>> Can we submit our Bitcointalk [ANN]: https://bitcointalk.org/index.php?topic=4862385 or should we improve it

We are working hard for our token so that we can achieve our milestone not just by selling tokens but really building applications for our crypto community.

Will be happy if you reply. Thanks for taking time and read this out.

**Comment by Vasilii79** [comment]
The working platform that provides users with Bounty Stakes Trading service (first in the world) can not get listed since June 2018 on Forkdelta. Please look at this issue 1332: https://github.com/forkdelta/tokenbase/issues/1332
