### ISSUE TITLE
Listing request - CHSB

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#474]
Contract address: 0xba9d4199fab4f26efe3551d490e3821486f135ba
Website: https://swissborg.com/en/
Whitepaper: https://swissborg.com/files/swissborg-technical-whitepaper.pdf
Description: We are the first wealth management platform for cryptos based on the blockchain, made in Switzerland by a team of financial experts. CHSB token holders become community members and are rewarded for participating in referendums to decide the future of SwissBorg.

Link to confirm contract: https://medium.com/swissborg/chsb-features-and-proof-of-meritocracy-eb93e237a882

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2161736

Third-party review of the token: https://cryptosis.io/swissborg-ico-review-latest-fintech-ico

Etherscan: https://etherscan.io/token/0xba9d4199fab4f26efe3551d490e3821486f135ba
Symbol: CHSB
Full Name: SwissBorg
Decimals: 8

EXTRA NOTES:
ICO hit the 50,000,000 CHF hardcap, which equates to about 52.5 million dollars.

**Comment by remedcu** [comment]
If you have a developer, then please read the [README](https://github.com/forkdelta/tokenbase/blob/master/README.md) and create the yaml file and make a pull request, and they will add it as soon as possible.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xba9d4199fab4f26efe3551d490e3821486f135ba,  https://swissborg.com/en/

**Comment by freeatnet** [comment]
@tradedbytony Thank you for your request! SwissBorg Token has been listed: https://forkdelta.github.io/#!/trade/CHSB-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
