### ISSUE TITLE
Hallo Request NRC Token For Listing

### ISSUE THREAD

**Issue by humairk** [forkdelta/tokenbase#480]
Website: https://thenitrocoin.org
Issuer's official website:https://thenitrocoin.org
Contract address: https://etherscan.io/token/0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
Contract address: 0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
Full Name: Nitrocoin
Symbol: NRC
Decimals: 0

reddit links : https://www.reddit.com/user/nitrocoinNRC/
Link to confirm contract: https://twitter.com/NitrocoinNRC
facebook Link: https://www.facebook.com/nitrocoinNRC/
Third-party comment(s) on the token:new join bitcointalk.org; https://bitcointalk.org/index.php?topic=3105174.
Whitepaper: https://thenitrocoin.org/whitepaper/NRC_WAIT_P.pdf

Description: The Decentralized Coin pegged to stock market in nitrocoin by fund

**Comment by tradedbytony** [comment]
Already submitted at #499
