### ISSUE TITLE
Listing request - GLA

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#481]
Contract address: 0x71d01db8d6a2fbea7f8d434599c237980c234e4c
Website: https://gladius.io
Whitepaper: https://gladius.io/pdf/gladius-whitepaper.pdf
Description: Gladius is the decentralized solution to protect against DDoS attacks by allowing you to connect to protection pools near you to provide better protection and accelerate your content. With an easy to use interface as well as powerful insight tools, Gladius enables anyone to protect and accelerate their website.

Link to confirm contract: https://medium.com/@gladiusio/gladius-token-sale-official-summary-e3e93f4b0bd2

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2217711

Third-party review of the token: https://finance.yahoo.com/news/gladius-io-offers-revolutionary-approach-200000302.html

Etherscan: https://etherscan.io/token/0x71d01db8d6a2fbea7f8d434599c237980c234e4c
Symbol: GLA
Full Name: Gladius
Decimals: 8

EXTRA NOTES:
ICO raised nearly 24k ETH, which is about 17.5 million dollars at the time I'm writing this.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x71d01db8d6a2fbea7f8d434599c237980c234e4c, https://gladius.io
