### ISSUE TITLE
Lendingblock token listing application  

### ISSUE THREAD

**Issue by jjfrizell** [forkdelta/tokenbase#484]
Contract address: 0xf9b60A9BFB3eA7152AD948eDac574E38B767Bd3f
Token address: 0x0947b0e6d821378805c9598291385ce7c791a6b2

Issuer's official website: https://lendingblock.com/ 

Official contract address confirmation:
https://lendingblock.com/ - token address at the very bottom of the page

A link to a third-party review or discussion of the token:
https://www.youtube.com/watch?v=4sBqqmidc5w&t=155s - ICO review by Crypto Gurus
https://picoloresearch.com/40/lendingblock-lnd - ICO review by Picolo Research 

Description:

LND is the native token of the Lendingblock platform, and as such is the sole medium through which interest payments are paid on loans.

The Lendingblock platform enables cross-chain lending and borrowing for the crypto economy, creating a parallel system to capital markets securities lending. The platform utilises a combination of on-chain and off-chain segments to provide fast matching services, while maintaining high levels of security and transparency.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x0947b0e6d821378805c9598291385ce7c791a6b2, https://lendingblock.com/

**Comment by jjfrizell** [comment]
Hi,

Thanks so much for listing our token! Sadly i have just found out from our
team that we may need to leave token listing until after our token is
transferable (late April), due to the legal issue of early listing possibly
leading to our token being listed as a security token (which it  is not).
Would it be possible to put the listing of LND on hold for now?

Kind regards,
Jj

**Comment by freeatnet** [comment]
@jjfrizell Sure thing. Do you have a date for when the tokens become transferrable?

**Comment by jjfrizell** [comment]
Hi,

Yes the tokens will become transferrable on the 29th April. If we could list then, or just before then that’d be great

Thanks!
Jj

**Comment by freeatnet** [comment]
/remind me to get back to this April 27

**Comment by jjfrizell** [comment]
Hi,

We sold our main-sale out in 3 days meaning that LND is becoming
transferable sooner than was originally thought. LND is becoming
transferable today, and will start trading on iDex today

We'd appreciate LND being listed anytime from now

Many thanks,
Jj

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be live on **Wednesday, June 6th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
