### ISSUE TITLE
Add LifToken

### ISSUE THREAD

**Issue by AugustoL** [forkdelta/tokenbase#485]
Contract address: 0xeb9951021698b42e4399f9cbb6267aa35f82d59d
https://etherscan.io/token/0xeb9951021698b42e4399f9cbb6267aa35f82d59d

Issuer's official website: https://windingtree.com

Official contract address confirmation: https://lif.windingtree.com or ENS domain: lif.windingtree.ens

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=1946065

Description:
The Líf token facilitates transactions on the Winding Tree platform.
Líf is used by travel companies to distribute inventory and make transactions without intermediaries.

PR: https://github.com/forkdelta/tokenbase/pull/483

**Comment by AugustoL** [comment]
The script that check the .yaml files makes the call to .decimals() while in our token (Based in StandardToken from zeppelin-solidity) uses .DECIMALS(), therefore the check of the decimals fail on the tests.

**Comment by tradedbytony** [comment]
Same request as #483

**Comment by jandetlefsen** [comment]
i'm interested to trade this token, can anything been done to fix this to make it pass the tests?

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xeb9951021698b42e4399f9cbb6267aa35f82d59d, https://windingtree.com/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on **Monday, April 30th, 2018**. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by AugustoL** [comment]
Awsm, thx @freeatnet

**Comment by freeatnet** [comment]
Thank you for your request! Líf has been listed: https://forkdelta.github.io/#!/trade/LIF-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by AugustoL** [comment]
Awsm, thx @freeatnet . Looking foreard for the announcement.
