### ISSUE TITLE
eduCash - EDXC

### ISSUE THREAD

**Issue by JordanOviedo95** [forkdelta/tokenbase#486]
Contract address: 0x6b78D47BFd2B391F2f34F31A128487e6768Ab4F6

Issuer's official website: https://www.educashcurrency.org/

Official contract address confirmation:
https://www.educashcurrency.org/

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3100716.msg32022923#msg32022923

Description:

eduCash is a community funded project and decentralized currency that thinks about the future of people, financing their studies and personal projects thanks to the blockchain technology.

**Comment by Kryptoniq** [comment]
1. The contents on your original post on bitcoin has been erased by you.
Please Kindly state your reasons for doing so. 
Link: https://bitcointalk.org/index.php?topic=3100716.msg32022923#msg32022923
Archive: https://web.archive.org/web/20180314211829/https://bitcointalk.org/index.php?topic=3100716.msg32022923

2. There are only two token holders.
