### ISSUE TITLE
LISTING REQUEST - HIT

### ISSUE THREAD

**Issue by VladWulf** [forkdelta/tokenbase#488]
Contract address: **0x24021d38DB53A938446eCB0a31B1267764d9d63D**

Issuer's official website: https://www.hodlit.network/

Official contract address confirmation, available on the website: https://www.hodlit.network/

A link to a third-party review or discussion of the token: 
- http://somethingdecent.co.uk/crypto/crypto-chronicles/the-current-crypto-bloodbath-highlights-a-need-for-cryptos-like-hodlit/
- http://www.t.me/Hodlit_Network

Description: 
- https://www.linkedin.com/pulse/hodl-incentive-token-future-fundraising-real-projects-vladimir-agaev/
- "HODLit  is an Avant-Garde project, a token incentivising an economic behaviour.
It promotes an alternative  to scammy ICOs with a revolutionary concept: an ICD [Initial Coin Distribution] coupled with the Proof of HODL.
Inherently, HODLit incentivises smooth organic Ether price growth, limits extreme volatility and fights the crypto blood baths. 
The uniqueness of HODLit is that it’s at the core of a network, the HODLit Network.
The HODLit network empowers projects  using an ICD based on the Proof of HODL. 
Those projects will distribute their tokens only the the owners of HODLit pro-rata their HODLit ownership.
Hodlit already counts 4 Projects that will be released and operational in the year 2018.
Every project joining HODLit Network will amplify its potential"

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x24021d38db53a938446ecb0a31b1267764d9d63d, https://www.hodlit.network/

**Comment by VladWulf** [comment]
Thank you for the message.
Do you have an estimation for when it will be listed?

**Comment by Fiska09** [comment]
Hi! Do you have more information about our listing? thanks!

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 9th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! HODL INCENTIVE TOKEN has been listed: https://forkdelta.github.io/#!/trade/HIT-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
