### ISSUE TITLE
Token Listing: FaithCoin (FAITH)

### ISSUE THREAD

**Issue by MyFaithCoin** [forkdelta/tokenbase#49]
Hi and Good Day
Please add our token FaithCoin to your platform. 

> **What is FaithCoin?**
> EtherFaith is the only secure ERC20 token embedded with prayer and bible verses. Words of God written in a token smart contract.
> 
> **Why we created FaithCoin?**
> FaithCoin aims to be introduced to people of faith as the main coin to be used in trading and online transactions while spreading the words of God in all and every transactions done.
> FaithCoin is design and intended to empower cryptocurrency users and boost their trust in trading using our coin. It is embedded with bible verses that will remind them of God’s words. Every transaction done is like passing through God’s message to everyone while experiencing a convenient way of trading without unnecessary cost and delays. We would like to bring peace of mind to our investors and traders, making FaithCoin as a gateway to do online transactions that are parallel to their moral compass.

Token Information
* Token: Standard ERC20 Token with Safemath
* Explorer: https://etherscan.io/token/0xe531642e9bb5d027e9c20e03284287b97919a9a5
* Token Contract Address: 0xE531642e9bb5d027E9C20E03284287B97919a9a5
* Symbol: FAITH
* Decimals: 8

Distribution
* Token Holders: 2661 
* Number of transfers: 3924

Links
* Website: https://myfaithcoin.info/
* Telegram: https://t.me/FaithCoin
* Announcement: https://bitcointalk.org/index.php?topic=2664744.0
* Dev Email: dev.faithcoin@gmail.com

Thanks in advance, more power and God Bless
FaithCoin Team

**Comment by freeatnet** [comment]
Contract address confirmation: https://myfaithcoin.info/, "Token Info" section.
