### ISSUE TITLE
Change Element (EM) token to EMOLD

### ISSUE THREAD

**Issue by Miroza666** [forkdelta/tokenbase#492]
Change Element token (EM) to EMOLD,add new token EM with contract address : 0xa0945daf5313e7878763598a7975e8a86c45b129
Contract address:
0xa0945daf5313e7878763598a7975e8a86c45b129
Issuer's official website : same as in already listed issue Element (EM)

Official contract address confirmation:

https://artbik555.wixsite.com/element

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2408354.msg24629174#msg24629174

Description:

Old Element token (EM) will be changed to EMOLD, new EM (Element) token have all specifications as EMOLD : 
Decimals : 1
Total Supply : 100
Symbol : EM
Name : Element

**Comment by tradedbytony** [comment]
Open PR at #453

**Comment by Kryptoniq** [comment]
@freeatnet, @JonathonDunford I think it is time to delist this Element  scam token.
Remembered "All morons must die in hell,including you,sir" by  pederast? · Issue #244 (don't know what happened to the issue. No longer exists.) 
Same person created the "HorseToken" that was rejected. @freeatnet banned him from this repo and he has come again  with a new user to request for contract change.

**Comment by tradedbytony** [comment]
This is the token I made a reference to in the Formalized Listing Requirements issue. As I said it in there, this token doesn't "even own their own site (not to mention, that token doesn't even have properly set up links, such as Twitter, and use the default Wix ones). If they can't even afford to spend a few bucks for their own domains, perhaps they aren't worth listing. That's just my humble opinion."

It screams of scam.

**Comment by Miroza666** [comment]
Change contract address to new,old contract need add OLD to name of token.

**Comment by freeatnet** [comment]
@Kryptoniq Let's file a formal delist and proceed from there. I don't see any redeeming qualities of this token / project.

**Comment by Miroza666** [comment]
Will be delist or update of contract address?

**Comment by Kryptoniq** [comment]
**will open a delist issue soon.
