### ISSUE TITLE
KahnChat KCH Token Listing Request

### ISSUE THREAD

**Issue by kahnchat** [forkdelta/tokenbase#493]
Contract address:
0x9409b1e54D5154B39bDCdE3A6f85d463028435C3

Issuer's official website:
https://www.kahnchat.com

Official contract address confirmation:

https://www.kahnchat.com

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2644550

Description:
This is a completely social networking solution and chatting app through which you can connect with friends and family members, send text messages, files and more, send money online, pay bills, post on user walls, share your story and discuss through comments, create and follow brand pages. The app is suitable for people of all ages.

One-App
KahnChat has been to include the features of all the popular mobile payment apps out there into one highly sophisticated and secure application that you can use to perform online transactions, make payments, voice and video chat, transfer files, send text messages and much more.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x9409b1e54d5154b39bdcde3a6f85d463028435c3, https://www.kahnchat.com/

**Comment by kahnchat** [comment]
Hi,

Yes, the company registration is correct.

Regards

David Kan

**Comment by freeatnet** [comment]
@kahnchat Thank you for your request! KahnChat has been listed: https://forkdelta.github.io/#!/trade/KCH-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by kahnchat** [comment]
Hi,

Would you accept donation of my tokens? If you do, please provide me an ETH address so I can transfer the tokens to you.

Regards

David

**Comment by freeatnet** [comment]
@kahnchat we would. The address is linked above.

**Comment by kahnchat** [comment]
Hi,

Not sure where is the your address is. Can you paste the ETH address in the email to avoid me sending to wrong address.

Regards

**Comment by kahnchat** [comment]
Hi,

Thank you.

500 KCH was transferred to your ETH address
https://etherscan.io/tx/0xc6a2ba722aa0755a7a44d0af973aa74be887a3355f20b4609ced2d3e07228b59 <https://etherscan.io/tx/0xc6a2ba722aa0755a7a44d0af973aa74be887a3355f20b4609ced2d3e07228b59>

Regards

David
