### ISSUE TITLE
Request new ERC20 Token listing : IVI - INOOVI Token

### ISSUE THREAD

**Issue by Otimoworld** [forkdelta/tokenbase#496]
Request to list IVI - INOOVI Token

Name : INOOVI
Symbol : IVI
Contract Adrss : 0xf33bb6b3aa8b1c5c0f67edfe2bb3c4d4a4f2e882
Decimals : 18
Descritpion : This token is linked to all Football Clubs in the world using it to negociate FOOTBALL PLAYERS HUGE AMOUNTS OF TRANSFERS. Great deals just before Football World Cup 2018 in Russia.
Website : https://inoovi.io
Bitcointalk : https://bitcointalk.org/index.php?topic=2787192.0
White paper in English : https://inoovi.io/en/white-paper/

**Comment by Kryptoniq** [comment]
1. Your contract address source  code  is not verified on etherscan.io
2. There are only 7 token holders.
3. Your total supply is 1 Quadrillion (1,000,000,000,000,000)?.?.? 
4. How can we confirm that the athletes listed on your website endorsed your project?

**Comment by Otimoworld** [comment]
1. How can I make it verify please?

2. Yes, I am l’angine the accounts for everyone yet. I will give away the tokens at the end of the ICO, on the 30th of March, after a large public campaign starting tomorrow for 12 days.

3. Yes, total supply is huge. I know.


4. Actually, only athletes and some partners are members : around 300 peoples.
 
I can give personal email adress and phone numbers of all them with no problems if you wish to control.

I have many more but I could not display all of them.

Our CEO is an heavyweight business man very well known and experienced all over the world.

Thank you so much.
We wish to be listed with you as soon as possible please.

We have so much project to develop also.


Yours
Loïc LACAM

**Comment by Kryptoniq** [comment]
Specified issues  are yet to be  addressed.

**Comment by Otimoworld** [comment]
Dear Sir or Madam,

In order to fix issues, we have created a new Contract adress and a Contract Code for our new IVI ERC20 Token :


1. contract adress :

0xF92Fe6eE0e47eCCdDc738D4f4140e926e7818812


2. contract code 

0x6060604052600436106100e6576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806306fdde03146100eb578063095ea7b31461017957806318160ddd146101d357806323b872dd146101fc578063313ce5671461027557806342966c68146102a457806365ce47fb146102df57806370a082311461030e57806379cc67901461035b5780638a3db05f146103b557806395d89b4114610443578063a9059cbb146104d1578063bc77b91914610513578063cae9ca51146105a1578063dc9c6e151461063e578063dd62ed3e14610667575b600080fd5b34156100f657600080fd5b6100fe6106d3565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561013e578082015181840152602081019050610123565b50505050905090810190601f16801561016b5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b341561018457600080fd5b6101b9600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610771565b604051808215151515815260200191505060405180910390f35b34156101de57600080fd5b6101e66107fe565b6040518082815260200191505060405180910390f35b341561020757600080fd5b61025b600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610804565b604051808215151515815260200191505060405180910390f35b341561028057600080fd5b610288610931565b604051808260ff1660ff16815260200191505060405180910390f35b34156102af57600080fd5b6102c56004808035906020019091905050610944565b604051808215151515815260200191505060405180910390f35b34156102ea57600080fd5b6102f2610a48565b604051808260ff1660ff16815260200191505060405180910390f35b341561031957600080fd5b610345600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610a4d565b6040518082815260200191505060405180910390f35b341561036657600080fd5b61039b600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610a65565b604051808215151515815260200191505060405180910390f35b34156103c057600080fd5b6103c8610c7f565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156104085780820151818401526020810190506103ed565b50505050905090810190601f1680156104355780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b341561044e57600080fd5b610456610cb8565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561049657808201518184015260208101905061047b565b50505050905090810190601f1680156104c35780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34156104dc57600080fd5b610511600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610d56565b005b341561051e57600080fd5b610526610d65565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561056657808201518184015260208101905061054b565b50505050905090810190601f1680156105935780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34156105ac57600080fd5b610624600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803590602001909190803590602001908201803590602001908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505091905050610d9e565b604051808215151515815260200191505060405180910390f35b341561064957600080fd5b610651610f18565b6040518082815260200191505060405180910390f35b341561067257600080fd5b6106bd600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610f21565b6040518082815260200191505060405180910390f35b60008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156107695780601f1061073e57610100808354040283529160200191610769565b820191906000526020600020905b81548152906001019060200180831161074c57829003601f168201915b505050505081565b600081600560003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055506001905092915050565b60035481565b6000600560008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054821115151561089157600080fd5b81600560008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282540392505081905550610926848484610f46565b600190509392505050565b600260009054906101000a900460ff1681565b600081600460003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020541015151561099457600080fd5b81600460003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282540392505081905550816003600082825403925050819055503373ffffffffffffffffffffffffffffffffffffffff167fcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca5836040518082815260200191505060405180910390a260019050919050565b601281565b60046020528060005260406000206000915090505481565b600081600460008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205410151515610ab557600080fd5b600560008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020548211151515610b4057600080fd5b81600460008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254039250508190555081600560008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282540392505081905550816003600082825403925050819055508273ffffffffffffffffffffffffffffffffffffffff167fcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca5836040518082815260200191505060405180910390a26001905092915050565b6040805190810160405280600681526020017f494e4f4f5649000000000000000000000000000000000000000000000000000081525081565b60018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610d4e5780601f10610d2357610100808354040283529160200191610d4e565b820191906000526020600020905b815481529060010190602001808311610d3157829003601f168201915b505050505081565b610d61338383610f46565b5050565b6040805190810160405280600381526020017f495649000000000000000000000000000000000000000000000000000000000081525081565b600080849050610dae8585610771565b15610f0f578073ffffffffffffffffffffffffffffffffffffffff16638f4ffcb1338630876040518563ffffffff167c0100000000000000000000000000000000000000000000000000000000028152600401808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018481526020018373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200180602001828103825283818151815260200191508051906020019080838360005b83811015610ea8578082015181840152602081019050610e8d565b50505050905090810190601f168015610ed55780820380516001836020036101000a031916815260200191505b5095505050505050600060405180830381600087803b1515610ef657600080fd5b5af11515610f0357600080fd5b50505060019150610f10565b5b509392505050565b64e8d4a5100081565b6005602052816000526040600020602052806000526040600020600091509150505481565b6000808373ffffffffffffffffffffffffffffffffffffffff1614151515610f6d57600080fd5b81600460008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205410151515610fbb57600080fd5b600460008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205482600460008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020540111151561104957600080fd5b600460008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054600460008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205401905081600460008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000828254039250508190555081600460008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825401925050819055508273ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040518082815260200191505060405180910390a380600460008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054600460008773ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020540114151561125657fe5b505050505600a165627a7a72305820f278ee2de6d46def1248e4611f144889784c83c1b31ff3897fcb4e902c6c9a0f0029



Please help us to be listed a soon as possible on Etherdelta and Forkdelta please.

Thank you Sir or Madam

**Comment by Kryptoniq** [comment]
Hello, what is the actual new contract ? I see tons of figures on your post.

**Comment by Otimoworld** [comment]
1. Contract adress :

0xF92Fe6eE0e47eCCdDc738D4f4140e926e7818812


2. May we have a phone talk please? 

3. We are really ready to work and become a great ERC20 tokens with all our team and everyone on the football planet.


Thank you so much

**Comment by Otimoworld** [comment]
We keep on being in touch with high Football players team and players ready to play World Cup Football in Russia this year.

We are talking with FIFA the world agency for Football regulation.

We need to be listed ASAP please Sir or Madam.

Our business is huge for all sports fans. We need to go on market with you please.

Thank you
Anthony



Planet Football Breaking News
IVI New Crypto Currency

1. IVI is offering large tokens packages to football club
2. The clubs allocate them as they wish in addition to all their financial transactions all year round : transfers, match bonuses, salaries, gifts to their best supporters, etc ...
3. Clubs move the token between them and all players.
4. The token goes public soon.
5. The more the clubs move it the more it becomes important, the more it develops, the more its price increases.
6. Clubs cash profits every year, at the end of each season.


Thank you

**Comment by Otimoworld** [comment]
Dear Sir,

We finally succeed to make this contract Verified :
Contract Address  0xd582ec4ed8da08fb519b38950276a6a16f33c020


Please accept to list us as soon as possible.


Thank you Sir

**Comment by Infinivi** [comment]
New DEX for a free listing - Limited offer

——-
Dear Sir or Madam,

We are supporting the launch of a new exchange on january 2020. 

We would like to propose you a free listing of your token on a pair « against » our own token. For free. 

If you request to trade against others currencies, we will check the performances after a first period of 30days. 

Let me know if any interests cause we are launching with a large promotional and marketing budget. 

It could be very good for all our token. 


Yours
Anthony
Send your request at Winances.com@gmail.com
