### ISSUE TITLE
JBC listing

### ISSUE THREAD

**Issue by h1ga1ewkd** [forkdelta/tokenbase#50]
Hi, please add JBC to the list of the forkdelta.
I will send the information below.
Thanks,

- address: '0x3635e381c67252405c1c0e550973155832d5e490'
- decimals: 18
- name: JAPAN BRAND COIN
- symbol: JBC

- etherscan: https://etherscan.io/token/0x3635e381c67252405c1c0e550973155832d5e490
- Website: https://jgroups.co.jp/en/
- facebook: https://www.facebook.com/jgroup.inc/
- whitepaper: https://jgroups.co.jp/pdf/J.GROUP_JBCoin_whitepaper_ENG_ver1.01.pdf

**Comment by JonathonDunford** [comment]
Please provide a link to a page on your website / whitepaper / ICO announcement that verifies your contract address.

**Comment by h1ga1ewkd** [comment]
Thank you for your reply.
Sorry, link was broken.

- address: '0x3635e381c67252405c1c0e550973155832d5e490'
- decimals: 18
- name: JAPAN BRAND COIN
- symbol: JBC
- etherscan: https://etherscan.io/token/0x3635e381c67252405c1c0e550973155832d5e490
- Website: https://blockchainneo.net
- facebook: https://www.facebook.com/blockchainneo/
- whitepaper: https://blockchainneo.net/pdf/JBcoin_whitepaper_ENG_ver1.02.pdf

Please move to the etherscan of JBC token and verify from Official Links.
On the Official Links, you can see the link I wrote above.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/commit/cf6f3057a19ef986f917009bc611ae712c4f64a6
