### ISSUE TITLE
Request ERC20 token listing: SMINT

### ISSUE THREAD

**Issue by cryptocurs** [forkdelta/tokenbase#500]
Contract address: 0xDBA0521FbA14C9601812A5E58173DDa953257787
Official website: [https://smint.club/](https://smint.club/)
Description: SMINT is Second MINeable Token working on the Ethereum platform. To mine bitcoin you need to spend electricity. To mine SMINT you need to spend some gas. The basic principle: the more you have, the more you will get.
Official page with contract address: [https://smint.club/](https://smint.club/)
Discussion: [https://bitcointalk.org/index.php?topic=2777989](https://bitcointalk.org/index.php?topic=2777989)
Link to confirm contract: https://gitter.im/mineable/mint2g

**Comment by Kryptoniq** [comment]
1. There are only 8 token holders. 
2. Your bitcointalk announcement thread has insufficient reviews and comments. 
My concern: Your wallet page "https://smint.club/wallet/" ask users to for their private key to access their wallet. How can i be sure that my private key will not be transmitted by any means? Is it open source?

**Comment by cryptocurs** [comment]
No, it is not open source, but there is easy way. You can generate new private key in wallet, then send your Ether (small amount) and tokens to this new address and use safely.

**Comment by cryptocurs** [comment]
Better add our DMINT token - with safe wallet with source code (github).
[](https://github.com/forkdelta/tokenbase/issues/602)
