### ISSUE TITLE
Listing request - DOCK

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#503]
Contract address: 0xe5dada80aa6477e85d09747f2842f7993d0df71c
Website: https://dock.io
Whitepaper: https://dock.io/whitepaper
Description: dock.io is a decentralized data exchange protocol that lets people connect their profiles, reputations and experiences across the web with privacy and security.

Link to confirm contract: https://twitter.com/dock_io/status/969788794139389954

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2769614

Third-party review of the token: https://icorating.com/analytics/indepth/dockio-rating-review

Etherscan: https://etherscan.io/token/0xe5dada80aa6477e85d09747f2842f7993d0df71c
Symbol: DOCK
Full Name: Dock
Decimals: 18

EXTRA NOTES:
This ICO raised a total of $20,140,818.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xe5dada80aa6477e85d09747f2842f7993d0df71c, https://dock.io/

**Comment by freeatnet** [comment]
@tradedbytony Thank you for your request! DockToken has been listed: https://forkdelta.github.io/#!/trade/DOCK-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
