### ISSUE TITLE
ANIMATIX Token Listing

### ISSUE THREAD

**Issue by animatixtrade** [forkdelta/tokenbase#504]
Hello, below you can find the required information needed for listing ANIMATIX on ForkDelta

Contract address: 
0x0CD161EF9EB19A95FeFA69C36f9cf552c19e6B8F

Token Symbol: AMX

Decimals: 18

Issuer's official website: https://www.animatix.trade

Official contract address confirmation: https://www.animatix.trade

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3094442

Whitepaper can be found in 4 languages

English: https://www.animatix.trade/animatix_whitepaper.pdf

Japanese: https://www.animatix.trade/animatix_whitepaper_japanese.pdf

Russian: https://www.animatix.trade/animatix_whitepaper_russian.pdf

Indonesian: https://www.animatix.trade/animatix_whitepaper_indonesia.PDF

Description: Animatix Trade is a decentralized platform which will carry out peer-peer freelance animation services using blockchain technology. The Animatix platform gives animation creators a decentralized platform to sell their services to a wide range of people without the interference of a third party but P2P trading instead.

Twitter: https://www.twitter.com/AnimatixTrade

Telegram: https://t.me/animatixtrade

**Comment by animatixtrade** [comment]
Whitepaper can be found here in 4 languages

English: https://www.animatix.trade/animatix_whitepaper.pdf

Japanese: https://www.animatix.trade/animatix_whitepaper_japanese.pdf


Russian: https://www.animatix.trade/animatix_whitepaper_russian.pdf


Indonesian: https://www.animatix.trade/animatix_whitepaper_indonesia.PDF

**Comment by tradedbytony** [comment]
Same request as #510

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x0cd161ef9eb19a95fefa69c36f9cf552c19e6b8f, https://www.animatix.trade/

**Comment by animatixtrade** [comment]
Thanks

**Comment by animatixtrade** [comment]
Hello, any update?

**Comment by animatixtrade** [comment]
Hello??

**Comment by freeatnet** [comment]
@animatixtrade Sorry for the delay. I'm having trouble finding any other third-party reviews of your platform, would you happen to have any other links available?

**Comment by animatixtrade** [comment]
Just bitcointalk, Twitter and Telegram. And all links are above.

**Comment by animatixtrade** [comment]
We decided to have limited discussion platforms due to high responsibility

**Comment by animatixtrade** [comment]
You can verify our platforms above

**Comment by freeatnet** [comment]
@animatixtrade Unfortunately, that thread does not contain significant discussion of the project. We cannot list this token based on the information provided.

**Comment by animatixtrade** [comment]
What other information do you need?

**Comment by freeatnet** [comment]
@animatixtrade A third-party review of your project / token other than the bitcointalk thread.
