### ISSUE TITLE
Neck Coin Listing Request

### ISSUE THREAD

**Issue by NeckCoin** [forkdelta/tokenbase#506]
Contract address: **0xc67e01f0b416b884a2896fae3401e86d605ba47e**

Issuer's official website: http://neckcoinico.com/

Official contract address confirmation: http://neckcoinico.com/
 **scroll down to the ABOUT NECKCOIN section**

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3089365

Description:
NeckCoin is a ERC20 token based on the etherium blockchain 
Contract address - 0xc67e01f0b416b884a2896fae3401e86d605ba47e
NeckCoin is used as part of a reward system on the NeckNetwork where users can earn rewards for being active and popular members of the community. Users can then list the coins they earn on an exchange to create a passive income.

**Comment by Kryptoniq** [comment]
1. Your bitcointalk announcement thread has insufficient comments /reviews.
2. Your contract address is not verified on etherscan.io.

**Comment by NeckCoin** [comment]
Thanks for the feedback, we will work on these issues straight away.

Is there a target amount of comments or pages that is needed on the forum?

**Comment by NeckCoin** [comment]
We have verified the contract.

Is there a target amount of comments or pages that is needed on the forum?

Thanks

**Comment by Kryptoniq** [comment]
We need real reviews.
Can you provide a link to an ICO review of Neckcoin?

**Comment by NeckCoin** [comment]
We have applied to be reviewed on a couple of ICO site but most of them are
just looking to make a quick buck and don't even care about the project as
long as they get paid.

Could we come to a deal regarding our ICO that starts on 1st April?
We could hold it solely on your site and then any buyers would have to come
to you?

We are currently holding a pre-sale on our website buy we could divert any
users from there to you.

We plan to hold 3 sales each of 2,000,000,000 coins.

1st-30th April 0.00007 USD
1st-31st May  0.00009 USD
1st-30th June 0.00010 USD

Would something like this be of interest to You? We could both benefit from
this.

Looking forward to your reply.
