### ISSUE TITLE
Listing request IquiCoin

### ISSUE THREAD

**Issue by iquicoin** [forkdelta/tokenbase#507]
Contract address: 0x6c5afe79938b816a20be5e434475eecb78515260

Issuer's official website: https://iquicoin.io/

Link to confirm contract:  
https://twitter.com/IquiCoin/status/973261024454471685

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3094574.msg31947323#msg31947323

Description:
addr: '0xe0c90e793a2c4eb2058dcfc54725388820115175'
decimals: 18
description: IQUICOIN The first Cryptocurrency used the blockchain in the cloud storage services. 
name: IquiCoin
symbol: IQI

links:
- Email: mailto:support@iquicoin.io
- Telegram: https://telegram.me/iquicoin
- Twitter: https://twitter.com/IquiCoin
- Website: https://iquicoin.io/
- Whitepaper: https://iquicoin.io/wth.pdf

**Comment by Kryptoniq** [comment]
Hi, thanks for your listing request but there are some things that doesn't look right.

The photo attached to "Chris Kloor", your 
Blockchain Engineer happens to be taken from http://haradok.info/rus/новости/общество/3932/. The photo is that of Vitaly Bambur, a psychologist. 

The photo attached to "Logino Gupta", your 
Digital Marketer happens to be taken from a Twitter profile belonging to Kyle Vergara. 
https://twitter.com/kylevergara2. 
 
https://www.iquicoin.io/
Archive: http://archive.is/Cx4dL

**Comment by iquicoin** [comment]
Thanks for the feedback, we will work on these issues straight away.

**Comment by iquicoin** [comment]
Contract address: 0x6c5afe79938b816a20be5e434475eecb78515260

Issuer's official website: https://iquicoin.io/

Link to confirm contract:
https://twitter.com/IquiCoin/status/973261024454471685

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3094574.msg31947323#msg31947323

Description:
addr: '0xe0c90e793a2c4eb2058dcfc54725388820115175'
decimals: 18
description: IQUICOIN The first Cryptocurrency used the blockchain in the cloud storage services.
name: IquiCoin
symbol: IQI

links:

Email: mailto:support@iquicoin.io
Telegram: https://telegram.me/iquicoin
Twitter: https://twitter.com/IquiCoin
Website: https://iquicoin.io/
Whitepaper: https://iquicoin.io/wth.pdf

**Comment by iquicoin** [comment]
team 
Luque Ruben : https://www.linkedin.com/authwall?trk=ripf&trkInfo=AQEvsRgqJgebmwAAAWJZlbBIVzx1O4pfV7p89FpYDWHD6XI2QLh_RUo8DAuqp4Fkzebjra-xo-pAzcBj4yrvfPboQOXa3WJPSmPfWzIB6Nqa3c_VR8NNNtPeA_C1URLsc-_Qf-Q=&originalReferer=https://www.iquicoin.io/&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fluque-ruben%2F

CHRIS KLOOR : https://twitter.com/chris_kloor

Logino Gupta : https://twitter.com/logino_gupta

Danielle Sureanu : https://plus.google.com/u/0/117440755942037850497

**Comment by Kryptoniq** [comment]
Team

Fake 
Luque Ruben

Real: Jose Geraldes
Photo stolen from: http://www.advert153.co.za/join-zukul-new.html 

Fake 
Chris Kloor
https://twitter.com/chris_kloor
http://archive.is/4otkt

Real: André 
Photo stolen from: http://www.martinsenmarketing.com/author/andre/

Fake 
Danielle Sureanu
https://plus.google.com/u/0/117440755942037850497
http://archive.is/byCBH

Real: Yadira Barbosa
Photo stolen from: https://plus.google.com/+YadiraBarbosa

We hate lies. We hate identify theft. 
This is the second time you are trying to fool us. 
I'm left with no option than to reject your listing request
.
If you want to contest this decision, kindly provide real and verifiable identities  of your team members. 

Current website archive: http://archive.is/0uMSX

**Comment by iquicoin** [comment]
Hi forekdelta team
We are sorry for what happened in the inclusion to add iquicoin in your site ... We have included wrong names not for fraud .. but the team  do not want put their names on the site right now ... Please understand this .... i want to ask if it is possible to add coin Without placing the names of team?

**Comment by iquicoin** [comment]
I want to contest this decision
This is my real team im sorry.

team
Luque Ruben : https://www.facebook.com/okba.cab.568

CHRIS KLOOR : https://twitter.com/chris_kloor

Logino Gupta : https://twitter.com/GuptaLogino

Christine Joy Gallego : https://twitter.com/Christi04984673
