### ISSUE TITLE
Paytailor Token Listing

### ISSUE THREAD

**Issue by Cyzerx** [forkdelta/tokenbase#508]
Hello, below you can find the required information needed for listing Paytailor on ForkDelta

**Token Symbol:** PAYT
**Decimals:** 6
**Contract address:** 0xFddE51FDFcA83be086d6da0ba303Fc68Db15c5f4

**Whitepaper**
English: https://www.paytailor.com/en/whitepaper.pdf

France: https://drive.google.com/file/d/1J-nK8lFAq7K8lxuRo8M3-d3X2MX99XGh/view

Indonesian: https://drive.google.com/file/d/1JyCEQjb0s3pwGukHXATd_-T7mjCFjrIC/view

https://drive.google.com/file/d/1-dqcNoUeYa7XLanC-tqvcE7VPQubXcPl/view

**Issuer's official website:** https://www.paytailor.com/en/

**Official contract address confirmation:** https://www.paytailor.com/en/ico

**A link to a third-party review or discussion of the token:**
https://www.investitin.com/paytailor/
https://bitcointalk.org/index.php?topic=2357086.0

**Description:** Paytailor is a software that enables payments between the merchant and the customer with existing devices and bank accounts. Paytailor combines payment methods, big data, NFC, location and social aspects of nowadays technological capability. The solution is very flexible, enabling payments app to app, browser to app and IoT payments.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.

0xfdde51fdfca83be086d6da0ba303fc68db15c5f4, https://www.paytailor.com/en/

**Comment by Cyzerx** [comment]
Don't list this token yet into exchange. Until we have juristic confirmation. Thank you

**Comment by Cyzerx** [comment]
Is it possible to re-open this topic?

**Comment by Cyzerx** [comment]
@freeatnet Is it still possible to list our token?

**Comment by freeatnet** [comment]
@cyzerx absolutely

**Comment by Cyzerx** [comment]
@freeatnet How long does it usually take to list token?

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 9th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Paytailor has been listed: https://forkdelta.github.io/#!/trade/PAYT-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
