### ISSUE TITLE
Honey Mining Token listing request

### ISSUE THREAD

**Issue by unspike** [forkdelta/tokenbase#511]
Contract address:  0xb8a88034bcf46e26c6bae1269ff2d051e2dee65c

Issuer's official website: https://hmt.io

Official contract address confirmation: https://hmt.io
A link to a third-party review or discussion of the token:  https://bitcointalk.org/index.php?topic=2935455.msg30162965#msg30162965

Description: We've made this token as analogue of shares (IPO) of our mining-farm company, holders (users) have possibility to withdraw their income via smart-contract monthly.

**Comment by tradedbytony** [comment]
ICO for a cloud mining operation? Well, now I've seen everything. No KYC/AML either so I'm sure that'll end up well. Also, it drives me crazy when people use backward slash instead of forward slash.

Anyway, for the official contract you can't just quote etherscan. Has to be on the site, which in a way it does have it in there. If someone scrolls down and click on "How to buy" it'll take you to a link (http://telegra.ph/HOW-to-create-ETH-wallet--BUY-HM-Tokens-HMT-02-03) where it shows that 0xb8a88034bcf46e26c6bae1269ff2d051e2dee65c is the token address and 0xB6D5414a1550B70d3A1280081b115FdDc4A465D2 is the contract address.

**Comment by unspike** [comment]
@tradedbytony Hi, thx for feedback.
yes its similar with cloud-mining, but not at all. 
About KYC/AML : our project located on Russia, in our country goverment doesn't finished needed laws for ICO and crypto, btw we will to work as transparents as possible and will try to make it accrording the law.
About contract : you can see it here : https://etherscan.io/tx/0x1cfc2ec37b7527e71ccf4f6a25afc8fb0593a607a7458e1b795468862b810fb8
this is creation transaction. 
Contract : https://etherscan.io/address/0xb6d5414a1550b70d3a1280081b115fddc4a465d2
Token : https://etherscan.io/token/0xb8a88034bcf46e26c6bae1269ff2d051e2dee65c
SubContract: https://etherscan.io/address/0xb8a88034bcf46e26c6bae1269ff2d051e2dee65c#code

> Anyway, for the official contract you can't just quote etherscan. Has to be on the site, which in a way it does have it in there.
we need to put direct link on main site ? or more detailed contract info ?

**Comment by Kryptoniq** [comment]
Hi @unspike, yes, make the contract address available on the website.

**Comment by unspike** [comment]
Update : CONTRACT INFORMATION added on https://hmt.io/

**Comment by unspike** [comment]
pfff WHAT ?!)

**Comment by unspike** [comment]
@tradedbytony @Kryptoniq

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews and comments. Please provide  link to a third-party review or discussion of the token.

**Comment by unspike** [comment]
@Kryptoniq don't have something like that.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xb8a88034bcf46e26c6bae1269ff2d051e2dee65c, https://hmt.io

**Comment by unspike** [comment]
Oh great. thx.

**Comment by unspike** [comment]
@Kryptoniq 2 weeks enought for 'next few days' ?)
