### ISSUE TITLE
Winding Tree / Lif Token add request

### ISSUE THREAD

**Issue by LazerPotatoe** [forkdelta/tokenbase#512]
Contract address:
0xeb9951021698b42e4399f9cbb6267aa35f82d59d

Issuer's official website:
https://windingtree.com/

Official contract address confirmation:
Click on the blue button labeled "learn more about Lif token".
It is at the bottom-right corner of the page.

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=1946065
https://www.youtube.com/watch?v=q-KQwLjKmqI&t=338s

Description:
Winding Tree is a blockchain-based decentralized open-source travel distribution platform. We make travel cheaper for the end user, while making it more profitable for suppliers.

Thanks!

**Comment by LazerPotatoe** [comment]
sorry -- just noticed that someone already submitted this 2 days ago.

**Comment by tradedbytony** [comment]
Same token request as #483, #485

**Comment by Kryptoniq** [comment]
#485
