### ISSUE TITLE
Applying for listing ANYCOIN(symbol:ANY) 

### ISSUE THREAD

**Issue by ANYCOIN-LIFE** [forkdelta/tokenbase#514]
Contract address: 0xdF67cf04f1F268e431BFEcf2c76843afB8e536C1

Issuer's official website: https://www.anycoin.life

Official contract address confirmation: https://www.anycoin.life/guides.php#what-contract-address

A link to a third-party review or discussion of the token: 
https://github.com/ANYCOIN-LIFE
https://www.reddit.com/user/ANYCOIN_LIFE
https://bitcointalk.org/index.php?action=profile;u=1728853;sa=showPosts

Description: ANYCOIN, unique platform of funding system & method using cryptocurrency

General Description
1. ECOSYSTEM of ANYCOIN
Things9 Co., Ltd., developed ANYCOIN to support investment to mid-size businesses and startups by the following process,
- choosing a company through an objective, special verification process;
- proceeding with a special ICO for the project of the company;
- investors study information on the ICO company through the platform and invest in the company;
- give raised funds to the ICO company;
- the ICO company provides ICO coins/tokens to the investors;
- periodically, steadily, and objectively analyzing the achievements of the ICO company and providing the results of analysis to the investors.

Our Business platform assures technical/economic reliability for ICO investment, leading to an increase in value of ICO coins, wider use of ICO tokens, and a strong risk hedge for investors with the results of reliving ICO investors of concerns and worries, increasing reliability, and reconsidering cryptocurrency and ICO more favorably. Therefore, positive effects are expected for fundraising via use of ICOs.
This would give birth to a new ecosystem bridging companies and investors through ICOs.

2. Progress of 1st ICO for Developing  entertainment business
- Title : Sur-ple ICO
- Date : Nov. 15, 2017 ~ Dec. 15, 2017
- Total supply : 30,100,000 ANYCOIN
- Official web site : https://www.sur-ple-ico.com (you can download ico whitepaper here)

3. WhitePaper of ANYCOIN
- https://www.anycoin.life/download/All_ICO_tokens_lead_to_ANYCOIN_ENG_things9.pdf

4. Our Block Explorer
You can find our Block Explorer informations belows;
- Since 2018 : https://etherscan.io/address/0xdF67cf04f1F268e431BFEcf2c76843afB8e536C1
- Before 2018 : https://etherscan.io/address/0x42b974424f0066c2446810369f2eAe0D49D3136E

5. Solutions we developed already
- ANYPAY : at Google Play Store & App Store
- ANYPOS : at Googlr Play Store
- ANYMINING : at Google Play Store

6. You can find us more at belows (English & Korean)
- Twitter : https://twitter.com/ANYCOIN_LIFE
- Facebook : https://www.facebook.com/ANYCOIN.LIFE
- LinkedIn : https://www.linkedin.com/in/anycoin-life-889885154
- Instagram :https://www.instagram.com/anycoin.things9
- Reddit : https://www.reddit.com/user/ANYCOIN_LIFE
- Youtube : https://www.youtube.com/channel/UCVCOTVmokHNSinOWx7Y

We hope that ANYCOIN through listing on ForkDelta should be helpful to many mid-size businesses who need investments.
It's the our Vision and It is the proud of us.

Thank you.

JongBum Lim 
CEO
E_mail : ceo@anycoin.life

**Comment by Kryptoniq** [comment]
Hi, please provide a link to a third-party review or discussion of the token.
Your contract address is not verified on etherscan.io and it  seems the token does not follow the  ERC20  standard because the transfers are using execute(address _to, uint256 _value, bytes _data) instead of the transfer(); function.

**Comment by ANYCOIN-LIFE** [comment]
Hi, Kryptoniq~!!
Our contract address is 0xdF67cf04f1F268e431BFEcf2c76843afB8e536C1 written on applying, and it is verified ordinarily. [](https://etherscan.io/address/0xdf67cf04f1f268e431bfecf2c76843afb8e536c1)

And Our token follow the ERC20 standard using transfer() function.
[](https://etherscan.io/tx/0x3428eefb2166b09e7c797a8735ee21be35324d11e51d6e6725b6ef4274e1c85a)

**Comment by ANYCOIN-LIFE** [comment]
Hi, Kryptoniq~!!
Our contract address is 0xdF67cf04f1F268e431BFEcf2c76843afB8e536C1 written on applying, and it is verified ordinarily as below.
https://etherscan.io/address/0xdf67cf04f1f268e431bfecf2c76843afb8e536c1

And, our coin follows the ERC20 standard using transfer() function.
You can find this here. https://etherscan.io/tx/0x3428eefb2166b09e7c797a8735ee21be35324d11e51d6e6725b6ef4274e1c85a
