### ISSUE TITLE
Gamity (GMTY) Token listing

### ISSUE THREAD

**Issue by GMTY** [forkdelta/tokenbase#515]
Contract address: https://etherscan.io/address/0xdaf44abc11eba1a7b0332ce5cce2ba0b2a9f727b#code
Issuer's official website: http://gamity.io
Official contract address confirmation: http://gamity.io (link on the top menu)
A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2155746.0

Description:
Hello, friends!
My name is Anver; I’m a founder of the Gamity project (www.gamity.io).

Today our team is developing a platform for work processes gamification worldwide. In Russia, we already have our own factory where we’ve successfully implemented gamification, for this we received the prize from Ethereum founder Vitalik Buterin on the world’s biggest hackathon in 2017! Vitalik was very complimentary about our project and chose it from 200 others as the most promising. During the conversation, Vitalik noticed a strong potential of our team, compared Gamity to Ethereum and said, that we are in for a great future with our project!

We do not intend to stop there! We continue to work on Gamity: one of our main achievements is the formation of the Russia’s first gamification & blockchain technology department in the most multinational university of the world – Peoples Friendship University of Russia.

Gamity has a great possibility for progress. According to statistics, 87% of people around the world are not enthusiastic about their job. All sorts of employees spend their working hours on computer games, social networks and other stuff, because of lack of involvement. So, using the gamification, we make any job exciting and full of fun, and we also give a just reward for ANY accomplished task! The success of our approach is clearly displayed at the first test site of MECONS plant.

Video gaming industry volume is about 100 billion dollars. Gamity can be used at factories, plants and any other business.
Blockchain solves the problem of trust. It will be much easier to integrate decentralized gamification for other plants and enterprises. With the blockchain we can scale Gamity to the whole world.

Factories and enterprises that will implement Gamity will need Gamity Tokens for the functioning of the gamification system. They will buy tokens from owners or on exchanges at any price. Gamity Token (GMTY) is a standard ERC20-token compatible to main Ethereum wallets.

**Comment by Kryptoniq** [comment]
Hi, thank you for your request but there are only 8 token holders at the moment.
