### ISSUE TITLE
LoserToken www.losertoken.com

### ISSUE THREAD

**Issue by LoserToken** [forkdelta/tokenbase#516]
Contract address: 0x687CD8745fd93b744723Bdc5621f67fE380AB27D

Issuer's official website: https://losertoken.com/

Official contract address confirmation: https://losertoken.com/ (bottom)

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3077779.new

Created for the pleasure of telling people they suck !
Description: All you need is the Ethereum address of the loser. You sent them one or more Loser tokens and eternal shame will be theirs. They can send the token around but the blockchain will always remember your message.

**Comment by Kryptoniq** [comment]
Hi, your contract address source code is not verified on etherscan.io.
Your bitcointalk announcement thread has insufficient reviews and comments.
