### ISSUE TITLE
XDCE - XinFin token listing on fork delta

### ISSUE THREAD

**Issue by kartikeya95** [forkdelta/tokenbase#517]
Contract address: 0x41ab1b6fcbb2fa9dced81acbdec13ea6315f2bf2

Issuer's official website: https://www.xinfin.io/

Official contract address confirmation: https://www.xinfin.io/buy-now.html (Please scroll to the bottom)

A link to a third-party review or discussion of the token: https://icobench.com/ico/xinfin

Description: XDC tokens are on built on XDC01 protocol which is first of its kind hybrid blockchain. To boost liquidity of XDC tokens and support large number of business use cases, XinFin is introducing an ERC20 token.

**Comment by tradedbytony** [comment]
Open issue at #517 and open PR at #553.

**Comment by Kryptoniq** [comment]
#553
