### ISSUE TITLE
Add RockToken (RKT) to ForkDelta

### ISSUE THREAD

**Issue by adamoadams** [forkdelta/tokenbase#521]
Contract address: 0x106aa49295b525fcf959aa75ec3f7dcbf5352f1c

Issuer's official website: [https://gbx.gi/](https://gbx.gi/)

Official contract address confirmation: [https://gbx.gi/docs/View-RKT-Balance-Guide-v1.7.pdf](https://gbx.gi/docs/View-RKT-Balance-Guide-v1.7.pdf) (scroll to page 3 of the PDF)

A link to a third-party review or discussion of the token: [https://bitcointalk.org/index.php?topic=2684176.0](https://bitcointalk.org/index.php?topic=2684176.0)

Description: The Rock Token (RKT) is an ERC-20 compliant utility token for use within the GBX/GSX ecosystem. Its primary use will be as a preferred medium of exchange. It will also be used to pay for fees within the full-service ecosystem, used for sponsor/issuer staking, and early access and possible discounts for future token sales on the platform. Please refer to part G of the Whitepaper for more detailed description.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x106aa49295b525fcf959aa75ec3f7dcbf5352f1c, https://gbx.gi/

**Comment by freeatnet** [comment]
@adamoadams Thank you for your request! Rock Token has been listed: https://forkdelta.github.io/#!/trade/RKT-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
