### ISSUE TITLE
Listing request - SWM

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#522]
Contract address: 0x9e88613418cf03dca54d6a2cf6ad934a78c7a17a
Website: https://www.swarm.fund
Whitepaper: https://swarmfund.blob.core.windows.net/swarmassets/swarm-whitepaper-v081.pdf
Description: Swarm Fund is the blockchain for private equity. It’s a fully decentralized capital market place that democratizes investing by using the power of the blockchain to open up high-return, alternative investment classes to smaller investors through asset-backed funds using cryptocurrency tokens. It makes traditionally exclusive investment opportunities, such as private equity and hedge funds, inclusive for the Swarm by pooling together smaller investments into larger, institutional-sized blocks.

Link to confirm contract: https://www.swarm.fund/faq/index.html (click on "How do I add the SWM token to MyEtherWallet?")

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2159615

Third-party review of the token: https://www.forbes.com/sites/giovannirodriguez/2017/08/16/can-swarm-fund-help-the-cryptocurrency-market-finally-enter-the-mainstream

Etherscan: https://etherscan.io/token/0x9e88613418cf03dca54d6a2cf6ad934a78c7a17a
Symbol: SWM
Full Name: Swarm Fund
Decimals: 18

EXTRA NOTES:
The ICO has raised 5.5 million dollars.

**Comment by animatixtrade** [comment]
Are you a team member of Forkdelta? How long does it take to get listed?

**Comment by tradedbytony** [comment]
I'm like a mascot at best :D 

Anywhere between 1 to 2 weeks, usually. I see your open request has been approved already, so the hard part is over. Just wait a week or two and you'll be good to go.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x9e88613418cf03dca54d6a2cf6ad934a78c7a17a, https://www.swarm.fund/

**Comment by AnonyMouseCoder** [comment]
I brought SWM tokens. 
Hoping to see SWM on forkdelta for trade. :D
