### ISSUE TITLE
Request for Token listing: BUBO

### ISSUE THREAD

**Issue by OregonGuy** [forkdelta/tokenbase#524]
Contract address: 0xccbf21ba6ef00802ab06637896b799f7101f54a2

Issuer's official website: https://budbo.io/

Official contract address confirmation: https://budbo.io/ (Top Center Left)

A link to a third-party review or discussion of the token: 
https://bitcointalk.org/index.php?topic=2657697.msg27086453#msg27086453
https://medium.com/budbo
https://www.reddit.com/r/Budbo/

Description:
Budbo is a revolutionary suite of products already transforming the cannabis industry. In November 2016 we designed a mobile application from the perfect perspective: the medical cannabis patient. With a “Tinder-like” functionality, users and patients discovered the ease of being able to quickly swipe through and discover thousands of locally available cannabis products. Budbo lets you find new strains and marijuana concentrates from nearby local dispensaries. Powered by Ethereum, we're building Budbo v2.0 that will revolutionize the Cannabis Industry by making the medical testing of cannabis potency verified and immutable as the product is moved from lab to dispensary, and causing the shift of historically illicit marijuana industry to a legal economy.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xccbf21ba6ef00802ab06637896b799f7101f54a2, https://budbo.io/

**Comment by OregonGuy** [comment]
Thank you!

**Comment by tradedbytony** [comment]
Don't close it. It'll be closed when it's listed.

**Comment by OregonGuy** [comment]
Are tokens that are this old of an issue still being listed? At the time their wasn't many, been waiting guys don't forget Bubo.

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 9th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Uservice Token has been listed: https://forkdelta.github.io/#!/trade/UST-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
