### ISSUE TITLE
Uservice (UST)

### ISSUE THREAD

**Issue by revned0005** [forkdelta/tokenbase#525]
Contract address: 0xf62baa1997f04f165edd100d78241e07617f6ce6

Issuer's official website: https://usrv.io/

Official contract address confirmation: https://t.me/userviceico

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2432730

Description: A single global transparent and decentralized blockchain platform for car service and maintenance. Our blockchain platform will connect car owners, dealerships, insurance companies, auto service centers, manufacturers, and parts suppliers as well as manufacturers on one platform. By joining them on a single platform, they get a chance to cooperate with one another, which will increase the possibility of transparency and effectiveness of their business processes. 

Uservice project is aiming to bring innovative solution to gathering and storing your car history on its secure and transparent blockchain platform for further optimization while connecting all industry players for easy access and workflow.

**Comment by tradedbytony** [comment]
You can't link a TG group for contract confirmation, however, you do have the contract all the way at the bottom of your website which is the best way to confirm it. Therefore, the contract has been confirmed and the token cleared for listing.

Hang tight and you'll be notified when the token is listed.

0xf62baa1997f04f165edd100d78241e07617f6ce6, https://usrv.io

**Comment by revned0005** [comment]
amy update about listing?

**Comment by Semipyatnov** [comment]
Hey, when the token will be listed?

**Comment by revned0005** [comment]
when will it be listed?

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 9th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Uservice Token has been listed: https://forkdelta.github.io/#!/trade/UST-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
