### ISSUE TITLE
Listing request: HACHIROKU (AE86)

### ISSUE THREAD

**Issue by hachirokucash** [forkdelta/tokenbase#526]
Contract address: 0x3e4ba4163d718d9dcc9e97c6e1cca31d290c47b1

Issuer's official website: https://hachiroku.cash/

Official contract address confirmation: Visible on the official website under the wallet instructions.

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2429017.0

Description: We like to request our community token to be officially listed. We are already using ForkDelta as the main exchange on our website.

**Comment by Kryptoniq** [comment]
Hi, that's not a description. We need a description of what your token does.
Your bitcointalk announcement thread has insufficient reviews / comments.
