### ISSUE TITLE
Request For Listing: Etherbyte (EBX)

### ISSUE THREAD

**Issue by FlamesOGK** [forkdelta/tokenbase#527]
Contract address: 0xba4725e435a287e28783886fcbcb339436a6ae66

Issuer's official website: etherbyte.co

Official contract address confirmation:
Contract Address on the website [Scroll Down] https://www.etherbyte.co/etherbyte-1

Whitepaper V0.1:
https://docs.wixstatic.com/ugd/4f0d88_637ed7928c2e4e05b0efa6a516344433.pdf

A link to a third-party review or discussion of the token:
[Announcement] https://bitcointalk.org/index.php?action=profile;u=1674912;sa=showPosts
[Third Party Review] https://bitcointalk.org/index.php?topic=2739657.msg28013367#msg28013367

Description:
Etherbyte will become the leading form of peer to peer payments in everyday life.

**Comment by tradedbytony** [comment]
Open PR at #528 and #529

**Comment by Kryptoniq** [comment]
#528
