### ISSUE TITLE
WLMT(Win LastMile Token) Listing

### ISSUE THREAD

**Issue by mgkao** [forkdelta/tokenbase#530]
Contract address:
0x60EAFe7f42da9FE2a56FEF0Fbfeeabc0dEeE631B

Issuer's official website:
https://winlastmile.org/

Official contract address confirmation:

https://winlastmile.org/ETHADD/

A link to a third-party review or discussion of the token:

http://cryptocurrency.tw/viewtopic.php?f=15&t=3239

Description:
Win Last Mile (WLMT) aims to provide better services to the elder and disable people, with a focus on Asian countries, starting from China and Taiwan.  Our team includes experts specialized in blockchain, social welfare, health-care, policy research and asset management. The team is led by Bishop Kao who is currently ministering three churches as well as their underlining foundations.

**Comment by Kryptoniq** [comment]
There are no comments on your announcement  thread.
BTW, are you doing an Airdrop or ICO? I can see you're requesting 0.001 eth /100 tokens.
Aren't Airdrops supposed to be free?

**Comment by mgkao** [comment]
Thank you for your suggestion.
Our ICO will start in May 1st , before that we are testing our ICO system.
So we start an pre-ICO from now on.
It's Like Airdrop because you can just sent 0.001 eth & get 100 tokens.
