### ISSUE TITLE
Request RNT Token Listed on Forkdelta

### ISSUE THREAD

**Issue by Brucecarl** [forkdelta/tokenbase#531]
Contract address:
0xff603f43946a3a28df5e6a73172555d8c8b02386
Issuer's official website:
https://www.oneroot.io/en
Official contract address confirmation:

https://www.oneroot.io/en/tokens

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=3121006
https://www.reddit.com/r/OneRoot/comments/7t23rj/oneroot_is_now_on_reddit/
https://medium.com/@oneroot

Description:
ONEROOT Project brings together the tangible and intangible resources inside and outside the industry. In the process of optimizing and integrating resources, ONEROOT extends the idea of a shared economy and separates the right to use and the ownership of resources, and proposes the concept of a distributed business engine. With the help of blockchain technology, the co-builders can digitize the right to use resources, including software, hardware, manpower, etc., and establish transparent value exchange and cooperation rules, which greatly improve the resource utilization efficiency. In addition, participants have established a new cooperative relationship based on equal cooperation and common development, which has significant advantages compared with the traditional business model dominated by centralized entities.

**Comment by Kryptoniq** [comment]
CMC: https://coinmarketcap.com/currencies/oneroot-network/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xff603f43946a3a28df5e6a73172555d8c8b02386, https://www.oneroot.io/en

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 9th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! OneRoot Network Token has been listed: https://forkdelta.github.io/#!/trade/RNT-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
