### ISSUE TITLE
Spectraal Token on your Exchange THX

### ISSUE THREAD

**Issue by msdong** [forkdelta/tokenbase#534]
Contract address: 0xa3114b268ff4327525fbc0dd5c48e0b4304d07b9

Issuer's official website: www.spectraaltoken.com

Official contract address confirmation: https://etherscan.io/token/0xa3114b268ff4327525fbc0dd5c48e0b4304d07b9?a=0xec07f0383759a92e565a69302c0757c1df48dd7a

A link to a third-party review or discussion of the token: https://twitter.com/spectraaltoken

https://bitcointalk.org/index.php?topic=3061751.0 (more discussion u can find on our twitter or telegram)

Telegram: https://t.me/joinchat/HcgY6Uk4Ezjdvu42tipW4A

https://feedback.altcoinexchange.com/suggestions/6163/add-spectraal-coin-spect-thx

Description:The Idea behind the Social Airdrop Token Spectraal is our Vision to bring the Topic "Crypto Coins" to Beginners, small and medium Investors for "PURE" Trading. Supply and Demand. Traditional Crypto Trading without "WHALES" Back to the "TRADING" ROOTS. Everybody gets the same Chances with our Spectraal Coin. We Favor Decentralized Exchanges.

We didnt have an ICO Crowdsale because we step into a new way "Concept" of Token Distribution. 
ICO will be banned near Future from Goverments Worldwide. Thats why we go a new Way to Distribute our Token Idea.  You can get our Tokens only via Airdrop or later only on Exchanges.
We would be very Happy if you can List our Token to your Exchange and Support our Idea of a Social Airdrop Community Token for Crypto Beginners, small and medium Investors.. Thank you.
Looking Forward to your fast reply.
Best Regards
Mr. Andreas Stammer (Germany)
Dev Team and CEO
![spect](https://user-images.githubusercontent.com/242173/37386650-a3002c8e-2759-11e8-8648-8b1f9d0f9af3.jpg)

**Comment by Kryptoniq** [comment]
#343

**Comment by msdong** [comment]
https://github.com/pulls
https://github.com/forkdelta/tokenbase/pull/536

Krypton <notifications@github.com> schrieb am Mi., 14. März 2018 um
08:35 Uhr:
