### ISSUE TITLE
ETL EthereumLotteryToken

### ISSUE THREAD

**Issue by ELTtoken** [forkdelta/tokenbase#535]
Contract address: 0xcd0a97fb02d690079433b73eb1ceecc3e107e7a2

Issuer's official website: https://www.ethereumlotterytoken.com/

Official contract address confirmation: 0xcd0a97fb02d690079433b73eb1ceecc3e107e7a2

A link to a third-party review or discussion of the token:

Description: a lottery provided by the community for the community, 
safe and team with vision.

**Comment by tradedbytony** [comment]
#548
