### ISSUE TITLE
Tigereum Token (TIG)

### ISSUE THREAD

**Issue by gabrieladeniji** [forkdelta/tokenbase#537]
Official contract address confirmation:
https://www.tigereum.io/tokens
Contract address: 0xeee2d00eb7deb8dd6924187f5aa3496b7d06e62a

addr: '0xeee2d00eb7deb8dd6924187f5aa3496b7d06e62a'
decimals: 18
description: Send crypto to friends and family in an instant message
links:
  - Bitcointalk: https://bitcointalk.org/index.php?topic=2331649.0
  - Blog: https://www.trackico.io/ico/tigereum/
  - CoinMarketCap: https://coinmarketcap.com/currencies/tigereum
  - Facebook: https://web.facebook.com/tigereum
  - Reddit: https://www.reddit.com/user/Tigereum
  - Twitter: https://twitter.com/tigereumtokens
  - Website: https://www.tigereum.io/
  - Whitepaper: https://docs.wixstatic.com/ugd/970dc6_15842e85a6874c79810d6dbfd60867d0.pdf

name: Tigereum Token (TIG)
symbol: TIG

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xeee2d00eb7deb8dd6924187f5aa3496b7d06e62a, https://www.tigereum.io/

**Comment by gabrieladeniji** [comment]
Thanks

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 10th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (in the token list and in the ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Tigereum has been listed: https://forkdelta.github.io/#!/trade/TIG-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
