### ISSUE TITLE
Add request - DD Token (DDT)

### ISSUE THREAD

**Issue by dedtoken** [forkdelta/tokenbase#538]
Contract address: 0x412d7462c72eaa8fa5068f4dc5082270eb89014f

Issuer's official website: https://www.dedtoken.info/

Official contract address confirmation:
You can find address confirmation in the middle of our web page by clicking on "DDT TOKEN INFO" or by clicking "FAQ" on the page top left.

A link to a third-party review or discussion of the token:
Bitcointalk: https://bitcointalk.org/index.php?topic=2785122.0

Other links:
- Twitter: https://twitter.com/DedToken
- Facebook: https://www.facebook.com/DD-Token-966866836786773
- Reddit: https://www.reddit.com/user/dedtoken/
- Website: https://www.dedtoken.info/
- Website platform: http://www.ddplatform.net/
- Whitepaper: https://www.dedtoken.info/DDT_Whitepaper.pdf

Description: 
This token will allow people to trade every kind of
products and services divided by category and country on our all-made-in-Italy, revolutionary platform ddplatform.net.
The platform we are creating, will have a cashback system that
will save a percentage of DDT for those who buy.

**Comment by dedtoken** [comment]
---
addr: '0x412d7462c72eaa8fa5068f4dc5082270eb89014f'
decimals: 9
description: >-
	This token will allow people to trade every kind of
	products and services divided by category and country on our all-made-in-Italy, revolutionary 
        platform ddplatform.net.
	The platform we are creating, will have a cashback system that
	will save a percentage of DDT for those who buy.
links:
	- Twitter: https://twitter.com/DedToken
	- Facebook: https://www.facebook.com/DD-Token-966866836786773
	- Reddit: https://www.reddit.com/user/dedtoken/
	- Website: https://www.dedtoken.info/
	- Website platform: http://www.ddplatform.net/
	- Whitepaper: https://www.dedtoken.info/DDT_Whitepaper.pdf
name: DD Token
symbol: DDT

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient comments /reviews.

**Comment by dedtoken** [comment]
Hello, 
thank you for your reply. We want to upgrade all the needed information but could you suggest to us what kind of information do we need to provide you?

We look forward for your kind reply,

Thank you,
