### ISSUE TITLE
Token Listing: Mixed Martial Arts (MMA)

### ISSUE THREAD

**Issue by etherbeats** [forkdelta/tokenbase#54]
Contract Address: [0x40b04166871d9956f5f261d76d349da8d07f82c3](https://etherscan.io/address/0x40b04166871d9956f5f261d76d349da8d07f82c3)
Official Website: [mmasportstech.com](mmasportstech.com)
Verification of Contract Address: [mmasportstech.com](mmasportstech.com)(Shown on the homepage under the ABOUT US, MEDIA, and FAQs sections.)
Forum Discussion: https://bitcointalk.org/index.php?topic=2685920.0
Twitter: https://twitter.com/MMASportsTech?lang=en
Telegram: https://t.me/mmasportstech

**Comment by JonathonDunford** [comment]
Address verified on website.

**Comment by JonathonDunford** [comment]
Tokens now require a description to get listed. Do you have a description for this token?

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
