### ISSUE TITLE
SportyCo (SPF) listing

### ISSUE THREAD

**Issue by 7jaka7** [forkdelta/tokenbase#540]
Contract address: 0x85089389c14bd9c77fc2b8f0c3d1dc3363bf06ef

Issuer's official website: https://sportyco.io/index.html

Official contract address confirmation: https://sportyco.io/index.html#spftoken

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2211728.0

Description: SportyCo is a decentralized sports investment & funding ecosystem.
We will introduce a brand new industry of sports crowd micro-financing while providing athletes, clubs and sports organizations with macro-funding on their respective end.

**Comment by 7jaka7** [comment]
I didn't know if it is good to include links to social channels in the listing request. I will paste them here:
Bitcointalk: 
https://bitcointalk.org/index.php?topic=2211728.0
Blog: 
https://news.sportyco.io/
CoinMarketCap: 
https://coinmarketcap.com/currencies/sportyco 
Email: 
info@sportyco.io
Facebook: 
https://www.facebook.com/SportyCo.io
Github: 
https://github.com/sportyfi/SportyFiSmartContracts
Reddit: 
https://www.reddit.com/r/SportyCo/
Telegram: 
https://t.me/SportyCo_official
Twitter: 
https://twitter.com/sportyco_io
Website: 
https://sportyco.io (platform on https://sportyco.net/)
Whitepaper: 
https://sportyco.io/SPORTYFI-Whitepaper.pdf
YouTube: 
https://www.youtube.com/channel/UCASh3Qp4dMiGKOKOOgZ6JsQ/videos

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x85089389c14bd9c77fc2b8f0c3d1dc3363bf06ef, https://sportyco.io/

**Comment by freeatnet** [comment]
@7jaka7 Thank you for your request! SPFToken has been listed: https://forkdelta.github.io/#!/trade/SPF-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
