### ISSUE TITLE
LAN30 token adding request

### ISSUE THREAD

**Issue by lanitaio** [forkdelta/tokenbase#541]
Contract address: 0xc874bc86d544b005a5d3082db8cb5adda9a82c68 

Issuer's official website: 
www.lanita.io
http://lanita.io/whitepaper_en.pdf

Official contract address confirmation:
https://ethplorer.io/address/0xc874bc86d544b005a5d3082db8cb5adda9a82c68

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3122230.0

Description:

Lanita is ERC-20 token that has 100% exposition to the top 30 cryptocurrencies. We belive Lanita token is the best instrument for portfolio investments - with one click you purchase top 30 cryptocurrencies by market capitaization. We have big expirience in classic trading (futures, stocks etc).

**Comment by Kryptoniq** [comment]
There are only 5 token holders ATM and your bitcointalk announcement thread has no comment.
