### ISSUE TITLE
listing request (NRC)

### ISSUE THREAD

**Issue by humairk** [forkdelta/tokenbase#543]
Contract address: 0x4248d5edc7a30fd1954c4e4c0262dc6ee5606d99
Token address: 0x1eca6ef43a7561b5ccffaa81a26d28cf6f3b8f6c

Full Name: Nitrocoin

Symbol: NRC

Decimals: 0

Issuer's official website:  https://thenitrocoin.org

Official contract address confirmation:
 https://thenitrocoin.org - token address at the very bottom of the page

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3105174.

 https://thenitrocoin.org - ICO review by

Link to confirm contract: https://twitter.com/NitrocoinNRC

facebook Link: https://www.facebook.com/nitrocoinNRC/

Description:
The Decentralized Coin pegged to stock market in nitro coin by fund based platform

**Comment by tradedbytony** [comment]
Issues brought up by @Kryptoniq on #437 are still present. This token also tried to list several times before: #437, #498, #480, #437, #382, #499 and #482.

Not saying it's a scam, but it's a scam.

**Comment by Kryptoniq** [comment]
@freeatnet please, can we get this user banned from this repo?
User did not attend to #437 red flags but went ahead to create a new issue.

**Comment by freeatnet** [comment]
@Kryptoniq User blocked.
