### ISSUE TITLE
Listing request - VUZZBEE Token

### ISSUE THREAD

**Issue by vuzzbee** [forkdelta/tokenbase#544]
Contract address:
0x59a563d147b3cd059dc6acb570b506df9f04eb82

Issuer's official website:
https://vuzzbee.com/

Official contract address confirmation:
https://twitter.com/VuzzBee/status/962611244703330304

A link to a third-party review or discussion of the token:
https://cryptocurrencytalk.com/topic/98255-annreferral-program-pre-sale-live-vuzzbee-worlds-first-blockchain-link-sharing-reward-system/

Description:
VuzzBee is a decentralized link-sharing website which allows users to view and share a variety of content such as articles, images, videos and links -- and earn rewards! Whether you are a content creator or a content consumer, you will be rewarded for interacting with the website. Think of VuzzBee as “Reddit” but with a reward system that goes beyond just points.
In using VuzzBee, creators benefit by being rewarded for their own content and at the same time enabling them to give their supporters and fans the chance to earn. 

Links

Web: https://vuzzbee.com/

Twitter: https://twitter.com/vuzzbee

Telegram: https://t.me/vuzzbee

Reddit: https://reddit.com/r/vuzzbee

Mail: info@vuzzbee.com

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x59a563d147b3cd059dc6acb570b506df9f04eb82, https://vuzzbee.com/

**Comment by vuzzbee** [comment]
hello sir,
thanks for approving our token ,
we are currently in our pre-sale, can you delayed our listing so that we can complete our ico?

**Comment by freeatnet** [comment]
@vuzzbee When does the ICO end / when is the token unlocked?

**Comment by vuzzbee** [comment]
hello sir,
can we list our token now?

**Comment by vuzzbee** [comment]
we are ready to list our token to your exchange kindly advice

**Comment by freeatnet** [comment]
@vuzzbee Given that a bit of time has passed, we'll need to look over the details again. Please update the request to the following format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by freeatnet** [comment]
Continued in #1300.
