### ISSUE TITLE
Add World Coin Network ERC20 Token (WCN)

### ISSUE THREAD

**Issue by WorldCoinNetwork** [forkdelta/tokenbase#547]
Contract address:
https://etherscan.io/token/0x452199df2379c309ac4ae73f7b30c10ccce508bc

Issuer's official website:
https://worldcoin.cash/

Email: daniel@worldcoin.cash

Link to Whitepaper*:  https://worldcoin.cash/assets/V8-%20WCN-%20White%20Paper%20+%20Lending.pdf

You Tube Video:    https://youtu.be/FUqsAm36_hQ

Link to Facebook:     https://www.facebook.com/worldcoin.cash/

Link to Twitter:      https://twitter.com/WorldCoin_Cash

Link to BitcoinTalk:   https://bitcointalk.org/index.php?topic=2877436.new#new

Link to Reddit:        https://www.reddit.com/user/WorIdcoincash

Link to Github:    https://github.com/WorldCoinNetwork

Link to Telegram:      https://t.me/WorldCoincash

Link to Medium:     https://medium.com/worldcoin

Link to Linkedin:   https://www.linkedin.com/company/world-coin-network/

Official contract address confirmation:
Crowdsale Address:    0x8f936fe0faf0604c9c0ef2406bde0a65365515d6

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2877436.new#new
https://icolink.com/finance-ico-list/ad/world-coin-network,576.html
https://www.icoalert.com/?q=&is_v=1

Description:
“The Future of Middle Eastern Crypto Currency”

World Coin Network aims to bring a stable Middle Eastern Crypto Currency to help facilitate trade and foster a culture of innovators and builders through a four pronged approach – 

1)	Digital Currency Stability
2)	Regional Partner Coins
3)	Sharia Lending Platform
4)	Charity Community Enrichment 

World Coin Network (WCN) will help leapfrog the 85% of the unbanked Middle East into a new digital era of wealth management, crypto currency and stable banking instruments.  Empowering the Middle East, facilitating trade and job creation are our main goals.  World Coin Network, is a financial services business that will help banks integrate the World Coin Network tokens and infrastructure into current systems.

Middle East Financial Problems:

85% of the 700 million people living in the Middle East are unbanked, with no access to credit, credit/debt cards, or formal banking. This hinders economic progress and continues the cycle of poverty. We have taken a four pronged approach to help create the first Crypto Currency to tackle the problems faced by millions of people.

World Coin Network (WCN) will help leapfrog the 85% of the unbanked Middle East into a new digital era of wealth management, crypto currency and stable banking instruments. We will do this by partnering with money changers in the region and have them also sell WCN coins. We have partnered with over 30 exchanges in Pakistan, and branching out to other regional areas in the Middle East.

Seamless Lending Platform will facilitate trade and foster a culture of Builders and Dreamers. Our Sharia compliant lending platform will loan 50,000 - 100,000 loans a year at 0% interest, and cultivate a community of WCN holders and users. Micro loans from 100 to 1,000 WCN tokens will be handed out. These loans can change people’s lives and increase the quality of life for an entire family. As customers repay the loans we will also provide them and the business with credit rating scores, thus enabling them to participate in global commerce.

Regional partner coins will help spread digital currency across the Middle East and rapidly expand the reach of World Coin tokens.  Our plan is to fork and create partner coins, like Iraq Coin or Afghan Coin to also utilize the World Coin Network and adhere to regional financial laws.

Keeping with our ideals of creating a stable and prosperous Middle East, we will be allocating a portion of our profits for Zakat (charitable tradition). We will be donating 20% of our transaction fees to non-profit educational charities in the Middle East

Management Team:

MOHAMMED MAQBOOL-  https://www.linkedin.com/in/maqbool-mohammad-0b0b077a/
CO-FOUNDER
 
DANIEL ASHE -  https://www.linkedin.com/in/daniel-a-773598156/
CO-FOUNDER & CMO
 
ZUBIN MOWLAVI-  https://www.linkedin.com/in/zubinmowlavi/
ADVISOR
 
PAVEL RUBIN-  https://www.linkedin.com/in/pash7ka/
BLOCKCHAIN DEVELOPER
 
MOHAMMED ALHASSAN-  https://www.linkedin.com/in/mohalhassan/
ADVISOR
 
ALEXANDER MISUNO-  https://www.linkedin.com/in/alexander-misuno/
MOBILE DEVELOPER
 
PHILLIP MCCARTY-  https://www.linkedin.com/in/alexander-misuno/
UX DESIGNER
 
BOJAN JOSIC-  https://www.linkedin.com/in/boyanjosic/
ADVISOR
 
JOSH BIGELOW-  https://www.linkedin.com/in/joshbigelow/
ADVISOR
 
ROB RUKSTALIS-  https://www.linkedin.com/in/robrukstalis/
ADVISOR

**Comment by Kryptoniq** [comment]
Your smart contract code  isn't verified on etherscan.io. Please do that.

**Comment by WorldCoinNetwork** [comment]
smart contract was added to etherscan, not sure why its not showing up on your side

**Comment by WorldCoinNetwork** [comment]
We added smart contract to etherscan, not sure why its not showing up on your end.
please email me a screen shot, so we can have our tech team work on it

thank you
Daniel A
daniel@worldcoin.cash

**Comment by Kryptoniq** [comment]
Your smart contract source code is not verified on etherscan.io.
https://etherscan.io/address/0x452199df2379c309ac4ae73f7b30c10ccce508bc#code

**Comment by WorldCoinNetwork** [comment]
Ok, do you know how we can verify on etherscan, or maybe you can help us out with this?

**Comment by Kryptoniq** [comment]
@WorldCoinNetwork  please join our Discord server so that we can find a possible solution 
https://discord.gg/5ueUUbV.

**Comment by WorldCoinNetwork** [comment]
Sorry about the confusion, we are now verified on Etherscan.

Can you let me know

Thanks

**Comment by WorldCoinNetwork** [comment]
If this process is to difficult, we can donate an ETH to help list our coin. let us know

**Comment by WorldCoinNetwork** [comment]
how can we help expedite this process, please let us know

**Comment by freeatnet** [comment]
@WorldCoinNetwork Can you please update your request to the following format: [https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md](https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md)?

There is no need to include team information (that information should be on the website) or social links. Thanks!
