### ISSUE TITLE
Listing to start.

### ISSUE THREAD

**Issue by ELTtoken** [forkdelta/tokenbase#548]
Contract address: 0xcd0a97fb02d690079433b73eb1ceecc3e107e7a2

Issuer's official website: https://www.ethereumlotterytoken.com/

Official contract address confirmation:

A link to a third-party review or discussion of the token:

Description: https://twitter.com/ERC20_ELT
- https://www.facebook.com/Ethereumlotterytoken-409595299485385/

Dear,
Our team will provide an lottery.
all tokens of users will go in the lottery /weekly
The random picking software of the addresses deposited the token to us will pick winners.
We want to provide a fun and fair way to test your luck.

We will have an price set for the tokens, 

We hope we will listed here on Forkdelta.

Regards.

ELT Team.

**Comment by tradedbytony** [comment]
A few issues:

1. A single token holder
2. Smart contract not verified
3. You need a third-party discussion (eg: a bitcointalk thread]

On a personal note, the pre-sale page shows "addres" rather than "address"
