### ISSUE TITLE
Honus Wagner: Symbol HANS

### ISSUE THREAD

**Issue by Zidag** [forkdelta/tokenbase#559]
Contract address: 0x3a0e978668974ff5b76ea4b19f20b28e5ba167f2

Issuer's official website: https://honuswagner.io/

Official contract address confirmation:  There is a link on the website to view the smart contract.  If that's not enough I can make it more visable.

A link to a third-party review or discussion of the token:  This is new.  I didn't want to create a buzz yet since I am afraid of someone else stealing this idea.  Once it gets listed I will start the discussion in the baseball crypto community.

Description:

**Comment by tradedbytony** [comment]
There's a single token holder. I wish you good luck on the ICO but right now, according to the listing guidelines, you just don't have enough token holders for us to list you. Maybe later, once the ICO finishes you could try requesting again. Best of luck.

Closing.
