### ISSUE TITLE
Submitting Verdot Token

### ISSUE THREAD

**Issue by ghost** [forkdelta/tokenbase#56]
Verdot 

Verdot Currency aims to align itself with vineyards across the globe integrating blockchain technology via QR code

Contract Address: | 0x85bae89dcf0598fb835e2e015b72c3c67a65896a
https://twitter.com/verdotcurrency
https://github.com/verdot
https://bitcointalk.org/index.php?topic=2846898.0

Please let us know what else we can do to get this token listed.

Thank you!!

**Comment by JonathonDunford** [comment]
Do you have a website or a whitepaper or an ANN or some sort of official source of information that we can verify the contract address and the token?

**Comment by JonathonDunford** [comment]
This issue will be closed per listing guidelines. No response from submitter for over 10 days.
