### ISSUE TITLE
Intention to delist: normikaivo NAO

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#566]
Reason:
* Contract creator is an [individual wallet](https://etherscan.io/address/0x8611084aecbb953b2c76838a30168388bda51783) with affiliation with known scams (see 018d3c7, #447): 0x8611084aecbb953b2c76838a30168388bda51783

Chain:
* User @normikaivo requests change of contract address for NAO at #348.
* [Previously established](https://github.com/forkdelta/tokenbase/blob/4d831d607b45461043743389eab6cc643cff604c/tokens/0xc6b014274d7406641711fb8889f93f4f11dec810.yaml) official website http://normikaivo.net ([archived](http://archive.is/zrn9D)) confirms new contract address 0xd71e21055f4b0ff413f5fa826b79c511a10bae6c.
* New contract address was [created](https://etherscan.io/tx/0x6502582db3935bfd561a3ffea193646e622e143b3caed5ddd5dc72bbe8224382) by the same address as the creator of known scam coins.

**Comment by tradedbytony** [comment]
The same contract creator has the following tokens under that wallet address:
BZX (https://etherscan.io/token/0x70838403ecc194b73e50b70a177b2ef413a2f421)
BNK (https://etherscan.io/token/0xf3836bc7415dfb67b4bf8427e37705b1a81e1173)
ZUL (https://etherscan.io/token/0x382a71ecb288da8701428406a36ffa5d8f072d55)
ESZ (https://etherscan.io/token/0x5fe56bfa37217bd8a2879c15c85ed7a894edf5a6)
NAO (https://etherscan.io/token/0xd71e21055f4b0ff413f5fa826b79c511a10bae6c)

I don't think you'd find anyone willing to back that one up.
