### ISSUE TITLE
Intention to delist: HAO

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/tokenbase#567]
Mirror copy of #566.

Reason:
* Contract creator is an [individual wallet](https://etherscan.io/address/0x0f248b3cf74deb4648b7242e17e06c0c306865fb) with affiliation with known scam attempts (see #170, #180): 0x0f248b3cf74deb4648b7242e17e06c0c306865fb

Chain:
* User @hentaisolo requests change of contract address for HAO at #368.
* [Previously established](https://github.com/forkdelta/tokenbase/blob/4d831d607b45461043743389eab6cc643cff604c/tokens/0xc9b89f6b5301f554b9adc6d4a871c3279820de40.yaml) official website http://hentaisolo.com ([archived](http://archive.li/jrcYG)) confirms new contract address 0x733172c38a6956206c9d4a902fd8a045c7f822f0.
* New contract address was [created](https://etherscan.io/tx/0xf6879510389ae51931bca249e0d3bf625439a8f44ee4884ead35be44cd9ec1b3) by the same address as the creator of known scam attempts; additionally, the same address created was engaged in other scams: https://etherscan.io/address/0x4bf3e4d2378a1256cbe1cd1c2a8bc9857b811282

**Comment by tradedbytony** [comment]
I like how even Etherscan has a warning now when you go to that address you linked: "Warning! There are reports that this address was used in a Phishing scam. Please exercise caution when interacting with this address. The website, augmentors[dot]trade was offline and Etherdelta had unlisted the token #DTB."
