### ISSUE TITLE
listing of EPT tokens

### ISSUE THREAD

**Issue by pgdiop** [forkdelta/tokenbase#568]
Contract address: **0xd73c51ce805c86046577b7b4e5cb2dde14d72a36**

Issuer's official website: www.e-pocket.com.au 

Official contract address confirmation: 0x449684cec6727d7240ecc6f29a0ebff9c5b27e59 ( https://e-pocket.com.au/how-to-buy-ept-tokens.html)

A link to a third-party review or discussion of the token: 

Please find below our social media channels links:
 
Telegram: https://t.me/joinchat/GoJF_g_J-FyO6Nhnl5JmXg
 
Reddit: https://www.reddit.com/user/e-Pocket/
 
Facebook: https://www.facebook.com/epocket.com.au/
 
Twitter: https://twitter.com/?logged_out=1&lang=en( @ePocket_AUS)
 
LinkedIn: https://www.linkedin.com/company/18384212/admin/updates/
 
YouTube: https://www.youtube.com/channel/UCnM8pKcdAZk9HDldfqIZjmw
 
Instagram: https://www.instagram.com/epocketaus/

Description:
Hi There

e-Pocket is an Australian Fintech company developing an integrated peer-to-peer mobile payment platform and system for individuals and businesses, designed to simplify the way people pay, buy and sell goods and services with fiat or crypto currencies.  Our aim is to build a worldwide marketplace on top of our robust and secure payment infrastructure for an even greater economic connection among people across the globe. This, we believe will help create more opportunities for those who have a lot to offer but do not have access to a platform that can help ... We want to widen the sphere of trust and expand the world market for the benefit of all. This is our ultimate goal...
We have completed our ICO on 22nd February 2018, reaching our soft cap. We would like to list our EPT tokens at US .40 cents on your exchange.

Our token EPT is an ERC-20 token with an initial supply of 32 millions released tokens out of 64 millions maximum tokens.

The e-pocket ICO page was: https://www.e-pocket.com.au/ico.html

Our website is:  www.e-pocket.com.au

Github link:  https://github.com/Aniket-Engg/epocket

Please let me know if you have any further enquiries.

Thanks in advance

Kind Regards,

Papa Diop
Director and COO
e-Pocket (International)
m: +61 430 632 344 | e: papa.diop@e-pocket.com.au
www.e-pocket.com.au

**Comment by Kryptoniq** [comment]
Hi there,  provide a link to a third-party review or discussion of the token and also, verify your smart contract source code on etherscan.io.

**Comment by Kryptoniq** [comment]
The smart contract source code has still not been verified on etherscan.io.

**Comment by pgdiop** [comment]
Hi There

We are having issue chasing the freelancer who built our smart contract. The smart contract has definitely been verified as per following https://etherscan.io/address/0xd73c51ce805c86046577b7b4e5cb2dde14d72a36#code

Thanks in advance.

**Comment by bakersemail** [comment]
Hi ForkDelta team,

The contract address needed to change and have tokens redistributed. Contract address is verified at: https://etherscan.io/address/0x8ecb1ca966b6804b129d3c0f9771e079cbf48efe#code

And community engaged in Telegram channel 30/05/2018 10:59:35am:

> Papa Gorgui Diopadmin
> Dear Investors,
> A quick update on EPT tokens ...
> Due to some protocol requirements regarding the integration of EPT tokens to e-Pocket wallets, we had to redeploy our smart contract system in order to achieve the level of integration we wanted. Following successful redeployment, we are now ready to commence working towards this integration.
> Furthermore, we will proceed with our first Airdrop of 250 EPT that will be allocated to each investor for the inconvenience of deleting previous tokens and linking up the new tokens' contract address.
> Investors won't need to do anything as the new EPT and Airdrop will be allocated to the address you sent us previously. 
> 1. If you are used to viewing your EPT balance through the Token Balances menu in myEtherWallet (as per below), please find a link to a tutorial on how to remove the EPT balance linked to the old address, and how to add the new contract address link.
> 
> 
> 
>  
> 
> 
> 
> 2. If you view your EPT tokens from other Ethereum platforms or hard wallet, you should be able to disable the EPT balance linked to the old contract address, named e-Pocket Token (EPT) and keep the one pertaining to the new contract address e-Pocket (EPT)
> 
> 
> 
> If you have any further enquiries, please email us at info@e-pocket.com.au 
> The e-Pocket Team
> www.e-pocket.com.au
