### ISSUE TITLE
Listing request - HAV

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#569]
Website: https://havven.io
Whitepaper: https://havven.io/uploads/havven_whitepaper.pdf
Description: Havven is a decentralised payment network and stablecoin. It allows anyone to transact using a stable cryptocurrency.

Link to confirm contract: https://blog.havven.io/token-distribution-announcement-7bb11258f851

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2702470

Third-party review of the token: https://cryptobriefing.com/havven-ico-review-hvv-token-analysis

Etherscan: https://etherscan.io/token/0xf244176246168f24e3187f7288edbca29267739b
Symbol: HAV
Full Name: Havven
Decimals: 18

EXTRA NOTES:
The ICO reached the hard cap of 30,000,000.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xf244176246168f24e3187f7288edbca29267739b, https://havven.io/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 10th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (in the token list and in the ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Havven has been listed: https://forkdelta.github.io/#!/trade/HAV-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
