### ISSUE TITLE
MoviToken - MOVI on ForkDelta

### ISSUE THREAD

**Issue by MoviTokenCHRIS** [forkdelta/tokenbase#57]
The contract address.
https://etherscan.io/address/0x623b925b0a57a24ea8de301f2e3e692ce903f0c3

    A link to the token issuer's official website.
http://movitoken.com/

    A link to an official page confirming the contract address.
http://movitoken.com/ (at the bottom)

    A link to a third-party review or discussion of the token, like an established ICO review blog.
https://bitcointalk.org/index.php?topic=2680192.0

addr: '0x623B925b0A57a24EA8dE301F2E3E692cE903f0c3'
decimals: 0
description: Community currency for the independent film community
name: MoviToken
symbol: MOVI

**Comment by JonathonDunford** [comment]
Once #85 goes through, this token will be added to tokenbase (and subsequently ForkDelta).

**Comment by JonathonDunford** [comment]
Will be added to FD once https://github.com/forkdelta/forkdelta.github.io/pull/60 goes through.

**Comment by JonathonDunford** [comment]
https://forkdelta.github.io/#!/trade/MOVI-ETH
