### ISSUE TITLE
Listing request - FTX

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#570]
Website: https://www.fintrux.com
Whitepaper: https://uploads-ssl.webflow.com/59f19167ffa06300013b3a69/5a8a97fc54ea7a000146ac08_Endor_Protocol_WP.pdf
Description: The Global P2P Lending ecosystem powered by Ethereum and no-code development.

Link to confirm contract: https://medium.com/fintrux/adding-ftx-token-to-myetherwallet-metamask-wallet-da6f185d0201

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2286042

Third-party review of the token: https://www.icotokennews.com/icos/fintrux

Etherscan: https://etherscan.io/token/0xd559f20296FF4895da39b5bd9ADd54b442596a61
Symbol: FTX
Full Name: FintruX
Decimals: 18

EXTRA NOTES:
This ICO raised 25,000,000.

**Comment by Kryptoniq** [comment]
@tradedbytony the token's etherscan.io page looks messed up.
Total Supply shows 100,000,000,000,000,000,000,000,000 N/A and other unusual figures on the token holder's balances.

**Comment by tradedbytony** [comment]
If you go to https://webcache.googleusercontent.com/search?q=cache:vMiFReyB_uUJ:https://medium.com/fintrux/adding-ftx-token-to-myetherwallet-metamask-wallet-da6f185d0201+&cd=4&hl=pt-BR&ct=clnk&gl=br&lr=lang_en%7Clang_pt you'll see that the address they gave people was the one I listed in my original request here (0x0ef6d1808b129f77cc5fb3ef864acc06aa52fa3d) but if you go for the live page for the SAME link, the contract has been updated to 0xd559f20296FF4895da39b5bd9ADd54b442596a61. Not sure why they changed it, but when I pasted it here first it was for the one they had originally posted (which was cached by Google) before they did that change. Honestly, this is a bit of an odd behavior from a 25 mil ICO, but what do I know.

 So their new (?) contract is 0xd559f20296FF4895da39b5bd9ADd54b442596a61

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
https://www.fintrux.com/, 0xd559f20296FF4895da39b5bd9ADd54b442596a61

**Comment by freeatnet** [comment]
Thank you for your request! The token will be live on **Wednesday, June 6th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
