### ISSUE TITLE
QBIT token listing request - www.qubitica.net

### ISSUE THREAD

**Issue by dantak2000** [forkdelta/tokenbase#573]
Contract address:
https://etherscan.io/token/0xCb5ea3c190d8f82DEADF7ce5Af855dDbf33e3962

Issuer's official website: www.qubitica.net

Official contract address confirmation:
https://etherscan.io/token/0xCb5ea3c190d8f82DEADF7ce5Af855dDbf33e3962
https://www.qubitica.net/qbit/

A link to a third-party review or discussion of the token:
As we made no ICO and we are a platform for developers most of the discussion is in our own communicator.

Description:
QUBITICA is a platform for developers and users of Ethereum based solutions. Ethereum offers an approach to add information to the blockchain, e.g. Contracts that we view as future-oriented. These types of contracts, whether Ethereum-based or not, will be called Smart Contracts. 

To anticipate it. The long-term goal of QUBITICA is to become a major supplier of Smart Contract solutions. Maybe we already are, but the market is still not developed so much that this would be a significant qualification right now. However, the developments in Blockchain will grow disproportionately, which is why it is the right time to find an intelligent solution to handle these tasks. 

We need to make the token tradeable on an exchange to give our many developers a good oportunity to exchange the token against other currencies that is online 24/7.

https://www.qubitica.net/whitepaper/

**Comment by tradedbytony** [comment]
Thank you for your interest in listing at ForkDelta. Unfortunately, you do not have enough token holders and as per the listing guidelines, we cannot list you at this time. When you have more participants in your project, you could attempt to list again at a later date. Best of luck.

Closing.
