### ISSUE TITLE
LIST REQUEST XVG

### ISSUE THREAD

**Issue by ivanbg8585** [forkdelta/tokenbase#574]
Contract address:
https://etherscan.io/token/0xbb865190a1ce0bc067a64384056f09a3c97e0f6e

Issuer's official website:
https://twitter.com/vergecurrency

Official contract address confirmation:
Source link https://github.com/vergecurrency/
Block explorer https://verge-blockchain.info/
Website https://vergecurrency.com/
A link to a third-party review or discussion of the token:

Description:
will be the Future of Privacy

https://vergecurrency.com/assets/Verge-Anonymity-Centric-CryptoCurrency.pdf
Coin symbol XVG

Coin name
Verge Currency
Total coins
16555000000
Algo
Scrypt, x17, groestl, blake2s, and lyra2rev2
Type
Verge is 100% POW (Proof of Work)
Block time
30 seconds

Txfee -

Bitcointalk link
https://bitcointalk.org/index.php?topic=1365894

**Comment by Kryptoniq** [comment]
This is an outright scam impersonating the the real Verge Currency.

**Comment by ivanbg8585** [comment]
u are sick if scam why 250k followers idiot







 >-------- Оригинално писмо --------

 >От: Krypton notifications@github.com

 >Относно: Re: [forkdelta/tokenbase] LIST REQUEST XVG (#574)

 >До: forkdelta/tokenbase  

 >Изпратено на: 16.03.2018 14:58



 
 
  
This is an outright scam impersonating the the real Verge Currency.
