### ISSUE TITLE
LIST XVG

### ISSUE THREAD

**Issue by ivanbg8585** [forkdelta/tokenbase#576]
NO ERC20 TOKEN IS COIN
Issuer's official website:
https://twitter.com/vergecurrency
Official contract address confirmation:
Source link https://github.com/vergecurrency/
Block explorer https://verge-blockchain.info/
Website https://vergecurrency.com/
A link to a third-party review or discussion of the token:
Description:
will be the Future of Privacy
https://vergecurrency.com/assets/Verge-Anonymity-Centric-CryptoCurrency.pdf
Coin symbol XVG
Coin name
Verge Currency
Total coins
16555000000
Algo
Scrypt, x17, groestl, blake2s, and lyra2rev2
Type
Verge is 100% POW (Proof of Work)
Block time
30 seconds
Txfee -
Bitcointalk link
https://bitcointalk.org/index.php?topic=1365894

**Comment by Kryptoniq** [comment]
Damned. @freeatnet please, can you ban this scammer from this repo?
#574

**Comment by ivanbg8585** [comment]
stfu u are my bitch .... community mother fucker u never will have so sick community








 >-------- Оригинално писмо --------

 >От: Krypton notifications@github.com

 >Относно: Re: [forkdelta/tokenbase] LIST XVG (#576)

 >До: forkdelta/tokenbase  

 >Изпратено на: 16.03.2018 16:21



 
 
  
Damned.  @freeatnet  please, can you ban this scammer from this repo?
  #574
