### ISSUE TITLE
(CDM) CryptoDime - Future's Virtual Present

### ISSUE THREAD

**Issue by Cryptodime** [forkdelta/tokenbase#577]
Contract address: 
https://etherscan.io/token/0x6287f59eb93c85b02b0d7ce11b5df51823275eb5

Issuer's official website: 
https://www.cryptodime.io

Official contract address confirmation: 
https://www.cryptodime.io/buy-cdm
https://www.cryptodime.io/promotion

The smart contract address has been linked in the above two pages.

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3103006

Description:
CryptoDime provides an opportunity for investors looking for the simplest way to get into the decentralised economy.

**Comment by tradedbytony** [comment]
Thank you for your interest in listing at ForkDelta. Unfortunately, you do not have enough token holders and as per the listing guidelines, we cannot list you at this time. When the ICO phase approaches its end and you have a higher participation in your ICO, you could attempt to list again at a later date. Best of luck.

Closing.
