### ISSUE TITLE
Listing request - YEED

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#578]
Website: https://yggdrash.io
Whitepaper: http://cdn.yggdrash.io/docs/Yggdrash_WhitePaper_En.pdf
Description: YGGDRASH is a trust-based multi-dimensional blockchains (branches) built with a vision “Digitize everything into reality” and to connect everything and any blockchain networks.

Link to confirm contract: https://medium.com/@yggdrash/how-to-add-a-custom-token-to-myetherwallet-yeed-token-b272276d3187

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=3061492

Third-party review of the token: https://hacked.com/ico-analysis-yggdrash, https://cryptobriefing.com/yggdrash-ico-review-yeed-token

Etherscan: https://etherscan.io/token/0x6f7a4bac3315b5082f793161a22e26666d22717f
Symbol: YEED
Full Name: YGGDRASH
Decimals: 18

EXTRA NOTES:
This ICO raised 40.000.000.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x6f7a4bac3315b5082f793161a22e26666d22717f, https://yggdrash.io/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! YGGDRASH has been listed: https://forkdelta.github.io/#!/trade/YEED-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by freeatnet** [comment]
@tradedbytony come back I miss your requests
