### ISSUE TITLE
Listing request - BUNNY

### ISSUE THREAD

**Issue by BunnyToken** [forkdelta/tokenbase#582]
Contract address: 0x755eb14d2feff2939eb3026f5cad9d03775b9ff4

Issuer's official website: https://bunnytoken.com/

Official contract address confirmation:

https://bunnytoken.com/
click on 'i' icon to the right of "BUNNY Smart Contract Address"

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=3046746

Description:
BunnyToken is ERC20 token for $103 billion entertainment industry

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x755eb14d2feff2939eb3026f5cad9d03775b9ff4, https://bunnytoken.com/

**Comment by BunnyToken** [comment]
Hello. Thank you very much. But we are still in presale stage. Our initial token sale will finish 25th of May. We would like to be listed on 26th or 27th of May

**Comment by freeatnet** [comment]
/remind me to get back May 24

**Comment by BunnyToken** [comment]
Hello! please list us. Out coin sale is finished, now we want to be traded on ForkDelta.


Contract address: 0x755eb14d2feff2939eb3026f5cad9d03775b9ff4

Issuer's official website: https://bunnytoken.com/

Official contract address confirmation:

https://bunnytoken.com/
click on 'i' icon to the right of "BUNNY Smart Contract Address"

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=3046746

Description:
BunnyToken is ERC20 token for $103 billion entertainment industry

**Comment by freeatnet** [comment]
@BunnyToken Can't seem to find contract address confirmation. Could you update the link, please?

**Comment by freeatnet** [comment]
@BunnyToken never mind, found under "What is the BunnyToken smart contract address?" on https://bunnytoken.com/faq.

**Comment by freeatnet** [comment]
@Kryptoniq A couple of links:
1. http://kusetukset.blogspot.com/2018/03/bunny-token-scam.html
2. http://cryptonewsreview.com/tons-of-bunny-tokens-allegedly-fake-staff-removed-from-website/

Gonna pull this out of the PR for the time being.

**Comment by freeatnet** [comment]
@BunnyToken Can you please explain the situation above?
