### ISSUE TITLE
Ophelia Blockchain - Listing Request

### ISSUE THREAD

**Issue by OpheliaDeutschland** [forkdelta/tokenbase#584]
Hi forkdelta Team,  
First of all we want to say: great job on what you are doing.   
We are requesting the listing of our token  "PHELI" on your Exchange. 
Here are the provided Informations, we hope they are accurate: 

Token Contract address:
0x4Df42D7317561F1540934f17c9aac68D6A21024E    
Token Name: PHELI  
Decimals: 18 

Token Issuers Website (Desktop Version):  
https://opheliacrypto.wixsite.com/ophelia 

Token short Description: 
PHELI is a token that will extend the usability of the Ophelia platform for the end user.

Official contract address confirmation:
https://opheliacrypto.wixsite.com/ophelia/ophelia-pheli-token

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3173897.msg32850793#msg32850793
We are also working on an partnership with a german cryptocurrency online newspaper.

Roadmap: 
https://opheliacrypto.wixsite.com/ophelia/deadlines 

Description:
The Ophelia project has set itself the goal of integrating blockchain and cryptocurrencies far away from pure speculation in peoples everyday lives. First we  will build a platform where you find work and can get paid in cryptocurrency. After we have achieved that, we will work to develop a software and possibly also hardware that allows workers to get paid legally in cryptocurrency. We will establish a company under german law, as well as advertise and organize two events in september and december in Berlin to make Ophelia known and get media attention. It is important for us to work strictly according german and european law. 
Team: 
Nero/Nils (Founder): 22 years old german lawyer 
Evator/Fritz (Co-Founder): 18 years old german computer scientist

Official Email: Opheliacrypto@protonmail.ch  

Thank you very much.  
Greetings from Berlin/Germany, 
Nero/Nils and Evator/Fritz form Ophelia Blockchain

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient no comments /reviews.
Your website needs work. The homepage leads a to wix error page.

**Comment by OpheliaDeutschland** [comment]
Ok thank you. Can we adjust that and you will review it here againor do we have to submit a new listing request?
