### ISSUE TITLE
BRV Listing Request

### ISSUE THREAD

**Issue by J4nJ** [forkdelta/tokenbase#585]
Contract address:
0x3B7D2a283f5e76b5978c20c4BF578DEfDEfa53ea

Issuer's official website:
bravocoin.io

Official contract address confirmation:
http://bravocoin.io/

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3106444

Description:
[Copypasted]
"Bravo Coin™ is a breakthrough in Blockchain technology working to better manage commercial transactions within the Sports & Entertainment industry. It achieves this by providing users a safer and more cost effective method of exchanging fiat currencies for goods and services – globally."

**Comment by tradedbytony** [comment]
Thank you for your interest in listing at ForkDelta. Unfortunately, you do not have enough token holders and as per the listing guidelines, we cannot list you at this time. When the ICO phase approaches its end and you have a higher participation in your ICO, you could attempt to list again at a later date. Best of luck.

Closing.

**Comment by J4nJ** [comment]
Thanks for the Reply though, faster than i expected it! :3

2018-03-20 22:30 GMT+01:00 tradedbytony <notifications@github.com>:
