### ISSUE TITLE
Request for listing Banyan Network.

### ISSUE THREAD

**Issue by FYIcryptoz** [forkdelta/tokenbase#586]
Contract address: 0x35a69642857083ba2f30bfab735dacc7f0bac969

Issuer's official website: https://www.banyanbbt.org/

Official contract address confirmation: http://blog.banyanbbt.org/2018/03/09/bibox-lists-bbntoken-bbn/
https://bibox.zendesk.com/hc/en-us/articles/360001454553--Event-BBN-World-Premiere-on-Bibox-3-500-000BBN-to-Giveaway-

A link to a third-party review or discussion of the token: https://medium.com/@FYIcryptoz/interview-with-banyan-network-ceo-david-zhou-483c0c9a045f

Description: Banyan Network is a fusion of big data network based on blockchain technology called Data Fusion Value Chain Network (DVN). It is also the world’s first distributed ecosystem of data economies raised and built by team experts in the field of data analytics. Banyan Network covers data collection, cleansing, integration, and applications. Our goal is to focus on blockchain enabled trusted data connection, third-party data integration and governance, data applications and open market development, building a positive interactive value-linked network of data benefits by establishing standards, providing channels, and issuing tokens.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x35a69642857083BA2F30bfaB735dacC7F0bac969, https://www.banyanbbt.org/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! BBNToken has been listed: https://forkdelta.github.io/#!/trade/BBN-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
