### ISSUE TITLE
Listing request - IPL

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#587]
Website: https://insurepal.io
Whitepaper: https://insurepal.io/InsurePal_whitepaper.pdf
Description: InsurePal is a next generation of peer-to-peer insurance based on social proof endorsements, fully harnessing the power of blockchain innovation.

Link to confirm contract: https://medium.com/insurepal-blog/how-to-add-ipl-custom-token-to-mew-fd8240eb62e4

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2495721

Third-party review of the token: https://hacked.com/ico-analysis-insurepal
https://bitcoinexchangeguide.com/insurepal

Etherscan: https://etherscan.io/token/0x64cdf819d3e75ac8ec217b3496d7ce167be42e80
Symbol: IPL
Full Name: InsurePal
Decimals: 18

EXTRA NOTES:
The ICO raised 18.000.000.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x64cdf819d3e75ac8ec217b3496d7ce167be42e80, https://insurepal.io/

**Comment by AnonyMouseCoder** [comment]
Waiting to see IPL on forkdelta. 

Cheers guys! :D

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! InsurePal token has been listed: https://forkdelta.github.io/#!/trade/IPL-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
