### ISSUE TITLE
Listing request - STQ

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#588]
Website: https://storiqa.com
Whitepaper: https://crowdsale.storiqa.com/static/docs/TS-white-paper-EN.pdf
Description: Storiqa is a platform created for buyers and sellers all over the world. With an easy-to use online store builder, any seller is able to create their own storefront to sell their goods, while making use of the platform’s wide range of features for a minimal fee.

Link to confirm contract: https://storiqa.zendesk.com/hc/en-us/articles/115002019012-How-to-add-STQ-using-myetherwallet-com (if you click on FAQ on their main website you'll be directed to their Zendesk site)

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2233274

Third-party review: https://cointelegraph.com/news/storiqa-to-let-anyone-build-an-online-marketplace-using-blockchain

Etherscan: https://etherscan.io/token/0x5c3a228510d246b78a3765c20221cbf3082b44a4
Symbol: STQ
Full Name: Storiqa
Decimals: 18

EXTRA NOTES:
The ICO raised a total of 25.000.000.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x5c3a228510d246b78a3765c20221cbf3082b44a4, https://storiqa.com/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Storiqa Token has been listed: https://forkdelta.github.io/#!/trade/STQ-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
