### ISSUE TITLE
Listing Request: Jesus Coin (JC)

### ISSUE THREAD

**Issue by vexatuvex** [forkdelta/tokenbase#590]
Contract address: 0xe2d82dc7da0e6f882e96846451f4fabcc8f90528
Decimals: 18
Symbol: JC

Issuer's official website: https://jesuscoin.network

Official contract address confirmation: https://jesuscoin.network or https://github.com/jesusico/jesuscoin
You can see it at the bottom of the website.

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2171006.0

Description: Using the cryptographic breakthrough of the blockchain ledger and anonymous cryptocurrencies, Jesus Coin has been developed as the currency of God’s Son. Unlike morally bereft cryptocurrencies, Jesus Coin has the unique advantage of providing global access to Jesus that’s safer and faster than every before.

**Comment by vexatuvex** [comment]
Second Description: Using the cryptographic breakthrough of the blockchain ledger and anonymous cryptocurrencies, Jesus Coin has been developed as the currency of God’s Son. Unlike morally bereft cryptocurrencies, Jesus Coin has the unique advantage of providing global access to Jesus that’s safer and faster than every before.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xe2d82dc7da0e6f882e96846451f4fabcc8f90528, https://jesuscoin.network/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Jesus Coin has been listed: https://forkdelta.github.io/#!/trade/JC-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
