### ISSUE TITLE
Update Contract of LOVE Token

### ISSUE THREAD

**Issue by remedcu** [forkdelta/tokenbase#591]
#332 Pull Request

Contract address: 0xb510788cbb9aea54221d3dc8cce2dff629a1dbf7

Issuer's official website: https://lovetoken.info

Official contract address confirmation: Front page in the website
ANN Thread: https://bitcointalk.org/index.php?topic=3118263
Contract Update Announcement: https://bitcointalk.org/index.php?topic=3118263.msg32307679#msg32307679
Etherscan: https://etherscan.io/token/0xb510788cbb9aea54221d3dc8cce2dff629a1dbf7

A link to a third-party review or discussion of the token:
https://icobench.com/ico/love-token
https://www.trackico.io/ico/love-token/

The issue has been labelled as Missing Information, but contains all the required information. Please check the same and label correctly and update it please. The PR has been started more than 2 weeks before.

**Comment by tradedbytony** [comment]
@JonathonDunford and @Kryptoniq already made their observations regarding this on #332.

Please keep all discussion on #332.
