### ISSUE TITLE
List Issue

### ISSUE THREAD

**Issue by NitroCoinTeam** [forkdelta/tokenbase#593]
Why My Token Is Not List On Forkdelta Explain #592

**Comment by tradedbytony** [comment]
Your "founders" apparently change at will. First, the founders were Michael Veliyam and Johsan Hater, but now they are John Vincent and Allan Wells. Please see https://web.archive.org/web/20180313001211/https://thenitrocoin.org/#page7 which shows very different people from the current https://thenitrocoin.org/#page7.

The issues brought up by @Kryptoniq on #437 are still present.

@freeatnet already banned the other account from trying to make these requests. Making new accounts to make these submissions won't get you listed.

You swang and you missed. Strike three. Move on.
