### ISSUE TITLE
List request for ET Tokens. [Open Issue #432 is now [UPDATED]

### ISSUE THREAD

**Issue by ewallet-token** [forkdelta/tokenbase#595]
Hello Forkdelta.

Please review our request for listing E-Wallet the open issue #432 is now updated. all information and requirement to list our token are now provided.

**Comment by tradedbytony** [comment]
@freeatnet on #432 already told you not spam request making new threads and yet we are. When/if you address @Kryptoniq and @JonathonDunford's concerns on that thread, someone will get back to you on it. Don't make additional threads, please. I'll be closing this one too.

All further discussion will stay on #432.
