### ISSUE TITLE
Request for Listing Leverage Platform (LVP)

### ISSUE THREAD

**Issue by LeveragePlatform** [forkdelta/tokenbase#596]
Contract address: 0x125e655ab4186a6c62f4ec6c8b7967d2e5b3d25e

Issuer's official website: https://leverageico.com

Official contract address confirmation: https://leverageico.com/#sale 

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2949207

Description: Leverage is a decentralized platform that allows people to store and invest their wealth in a decentralized cryptocurrency, and earn a substantial interest on investment. The Leverage Platform (LVP for short) features a genuine, trustworthy and traceable lending platform with complete data sharing and absolute information transparency.

**Comment by tradedbytony** [comment]
The issue brought up on #346 by @Kryptoniq is still present. There's simply not enough token holders.

You say you got the pre-sale going, and while I wish you all the best I have to wonder why would you want to list it while in pre-sale phase. At least wait until the main sale is somewhat close to being over and you have some more participants/token holders before trying to list again.

Closing.
