### ISSUE TITLE
Listing Request - BoutsPro (BOUTS)

### ISSUE THREAD

**Issue by boutspro** [forkdelta/tokenbase#598]
Contract address: 0x139d9397274bb9e2c29a9aa8aa0b5874d30d62e3
Symbol: BOUTS
Full Name: BoutsPro
Decimals: 18

Issuer's official website: https://www.bouts.pro

Official contract address confirmation:  https://www.bouts.pro

A link to a third-party review or discussion of the token: https://icobench.com/ico/boutspro ,  https://bitcointalk.org/index.php?topic=3052864.0

Description: BoutsPro: A global "Karate" Sports Organization. “BOUTSPRO WORLD” IS THE GLOBAL UMBRELLA STRUCTURE THAT EMPOWERS OVER 190 MILLION KARATE COMMUNITY AND DEVELOPS VERY ROBUST ECO-SYSTEM FOR ALL FORMS OF KARATE – TRADITIONAL, SPORTS & CONTACT KARATE.

Our Links

Website: https://www.bouts.pro
Bitcointalk [ANN] Thread: https://bitcointalk.org/index.php?topic=3052864.0
Bitcointalk Bounty thread: https://bitcointalk.org/index.php?topic=3055902
Facebook: https://www.facebook.com/boutspro
Twitter: https://twitter.com/boutspro
Youtube: https://www.youtube.com/c/BoutsPro
Reddit: https://www.reddit.com/r/bouts_pro
Telegram Channel: https://t.me/boutspro
Telegram Group: https://t.me/boutspro1
Github: https://github.com/Bouts-Pro
White paper: https://www.bouts.pro/whitepaper

Crowd-sale Contract Address: 0x903c7af702000b58baee44366815119fd39b2e3d
BoutsPro Smart Contract Address: 0x139d9397274bb9e2c29a9aa8aa0b5874d30d62e3

Blockchain Explorer: https://etherscan.io/token/0x139d9397274bb9e2c29a9aa8aa0b5874d30d62e3

Email: contact@bouts.pro

**Comment by tradedbytony** [comment]
Only 1 needed. Closing duplicates: #600 and #601.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x139d9397274bb9e2c29a9aa8aa0b5874d30d62e3, https://www.bouts.pro

**Comment by Kryptoniq** [comment]
Hi @boutspro, only the crowd sale contract  is available on the website.

**Comment by boutspro** [comment]
Yes, there is only crowd-sale contract address visible on landing page. Just below that, "Click here" link contains the token contract address. (On the same page, two addresses can make confusion to contributors). The token contract address is also placed : https://www.bouts.pro/ico-guideline/
(Last paragraph - Find token in your wallet)

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x139d9397274bb9e2c29a9aa8aa0b5874d30d62e3, https://www.bouts.pro/

**Comment by david769** [comment]
Hoping to get listed soon. Our team is eagerly waiting to trade on forkdelta.

Thanks.

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 9th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! BoutsPro has been listed: https://forkdelta.github.io/#!/trade/BOUTS-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
