### ISSUE TITLE
Listing request - SHC

### ISSUE THREAD

**Issue by spencermorgan** [forkdelta/tokenbase#599]
Contract address:  0xb33d73a8aecb5a87173a27503507547752ed9310

Issuer's official website:  http://www.shopcoin-offical.com/

Official contract address confirmation(The page 19):  http://www.shopcoin-offical.com/Whitepaper/white-paper.pdf

A link to a third-party review or discussion of the token:  https://bitcointalk.org/index.php?topic=3152272.0

Description: ShopCoin is a global decentralized shopping and services platform,SHC platform is created to provide a secure and decentralized platform where sellers and buyers are able to meet and transact at lower costs without the need for middlemen.

**Comment by tradedbytony** [comment]
Thank you for your interest in listing at ForkDelta. Unfortunately, you do not have enough token holders and as per the listing guidelines, we cannot list you at this time. Plus, your Bitcointalk thread doesn't have much activity. When the pre-sale/ICO phase approaches its end and you have a higher participation in your project, you could attempt to list again at a later date. Best of luck.

Closing.

**Comment by spencermorgan** [comment]
Can we apply for a reply from here to list our tokens afer our token sale?

**Comment by spencermorgan** [comment]
Thanks ,hope all goes well with you too
