### ISSUE TITLE
Token Listing: Bizacoin Token

### ISSUE THREAD

**Issue by Bizacoin** [forkdelta/tokenbase#60]
> The contract address:
https://etherscan.io/token/0x983f7cc12d0b5d512b0f91f51a4aa478ac4def46

> A link to the token issuer's official website:
https://www.bizavest.info/

> A link to an official page confirming the contract address:
https://www.bizavest.info/ (Scroll down to Token Specification section)

> A link to a third-party review or discussion of the token, like an established ICO review blog:
https://bitcointalk.org/index.php?topic=2490619.0

addr: '0x983f7cc12d0b5d512b0f91f51a4aa478ac4def46'
decimals: 0
description: Community currency for the Bizavest Data Analytics Platform
name: Bizacoin
symbol: Bizc

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/commit/cf6f3057a19ef986f917009bc611ae712c4f64a6
