### ISSUE TITLE
Listing Request - BoutsPro (BOUTS)

### ISSUE THREAD

**Issue by boutspro** [forkdelta/tokenbase#600]
Contract address: 0x139d9397274bb9e2c29a9aa8aa0b5874d30d62e3
Symbol: BOUTS
Full Name: BoutsPro
Decimals: 18

Issuer's official website: https://www.bouts.pro

Official contract address confirmation:  https://www.bouts.pro

A link to a third-party review or discussion of the token: https://icobench.com/ico/boutspro ,  https://bitcointalk.org/index.php?topic=3052864.0

Description: BoutsPro: A global "Karate" Sports Organization. “BOUTSPRO WORLD” IS THE GLOBAL UMBRELLA STRUCTURE THAT EMPOWERS OVER 190 MILLION KARATE COMMUNITY AND DEVELOPS VERY ROBUST ECO-SYSTEM FOR ALL FORMS OF KARATE – TRADITIONAL, SPORTS & CONTACT KARATE.

Our Links

Website: https://www.bouts.pro
Bitcointalk [ANN] Thread: https://bitcointalk.org/index.php?topic=3052864.0
Bitcointalk Bounty thread: https://bitcointalk.org/index.php?topic=3055902
Facebook: https://www.facebook.com/boutspro
Twitter: https://twitter.com/boutspro
Youtube: https://www.youtube.com/c/BoutsPro
Reddit: https://www.reddit.com/r/bouts_pro
Telegram Channel: https://t.me/boutspro
Telegram Group: https://t.me/boutspro1
Github: https://github.com/Bouts-Pro
White paper: https://www.bouts.pro/whitepaper

Crowd-sale Contract Address: 0x903c7af702000b58baee44366815119fd39b2e3d
BoutsPro Smart Contract Address: 0x139d9397274bb9e2c29a9aa8aa0b5874d30d62e3
Blockchain Explorer: https://etherscan.io/token/0x139d9397274bb9e2c29a9aa8aa0b5874d30d62e3

Email: contact@bouts.pro

**Comment by tradedbytony** [comment]
Only 1 needed. Closing duplicates: #600 and #601.
