### ISSUE TITLE
Request ERC20 token listing: DMINT

### ISSUE THREAD

**Issue by cryptocurs** [forkdelta/tokenbase#602]
Token name: DMINT
Contract address: 0x51c6a6Ef1352578Ff01B078313E6779B88BDcb1E
Decimals: 18
Official website: https://dmint.xyz/
Description: DMINT is Distributed MINeable Token working on the Ethereum platform. To mine bitcoin you need to spend electricity. To mine DMINT you need to spend some gas. The basic principle: the more you have, the more you will get. DMINT can be added to any Ethereum Wallet because it is standard ERC20 token.
Official page with contract address: https://dmint.xyz/
Discussion: https://bitcointalk.org/index.php?topic=3139476
Link to confirm contract: https://twitter.com/dmint18
Medium: https://medium.com/@smint2018/distributed-mint-we-build-an-ideal-world-70f13f4f1e36
Online wallet: https://cryptocurs.github.io/dmint/
Source code of online wallet: https://github.com/cryptocurs/cryptocurs.github.io/tree/master/dmint

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x51c6a6ef1352578ff01b078313e6779b88bdcb1e, https://dmint.xyz/

**Comment by cryptocurs** [comment]
Thanks!

**Comment by cryptocurs** [comment]
Still waiting :)

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! DMINT has been listed: https://forkdelta.github.io/#!/trade/DMINT-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
