### ISSUE TITLE
Anonymizer Ethereum (ATH)

### ISSUE THREAD

**Issue by AnonymizerEthereum** [forkdelta/tokenbase#603]
Contract address: 0xc1eC40b714281519ea367eB06429d1701Ed18b5f

Issuer's official website: https://satoshi.team/

Official contract address confirmation: https://satoshi.team/

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3022988.0
https://t.me/SatoshiTeamOfficial
https://twitter.com/SatoshiTeam
This community will conduct a swap of SPS tokens on ATH. We created this smart contract as a marketing move: Token Holders: | 189626 addresses
https://etherscan.io/token/0xd9a72fec8683db0666769d841d6d127f350b4418#balances

Description: Anonymizer Ethereum (ATH) uses advanced cryptographic techniques, namely zero-knowledge proofs, to guarantee the validity of transactions without revealing additional information about them. 
The ether or tokens do not get out of your control and are on your balance in a smart contract. Only you have access to managing these balances!
In our wallet, you can add any ERC-20 token or Ether for anonymous transactions. If you are the creator of the token, and you want to add your token to the list of tokens with the symbol, send an email to admin@satoshi.team

**Comment by AnonymizerEthereum** [comment]
This is confirmation that I am the owner of a smart contract (transaction from the address of the creator to your address for donations) https://etherscan.io/tx/0xf10602b68e7784f74d2689d0e2190159be78ec9c6ec8fe2fe4e32adfb5ec9351

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xc1eC40b714281519ea367eB06429d1701Ed18b5f, https://satoshi.team/

**Comment by Nataliamarker** [comment]
When ATH token will be listed. it's been 14 days.

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Ethereum Anonymizer has been listed: https://forkdelta.github.io/#!/trade/ATH-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
