### ISSUE TITLE
SATT coin listing request

### ISSUE THREAD

**Issue by johnrazmus** [forkdelta/tokenbase#604]
Contract address:
https://etherscan.io/address/0x315840be65f5ac80aee75d58e30a70a66e813320

Issuer's official website: 
https://satt.io

Official contract address confirmation: 
http://satt.io/coin

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3118142

Description:
Short for "See all the Things" this app helps do the technical analysis data gathering work for you and put it in a pretty wallboard to sit on a TV / monitor.

The goal is to provide you with meaningful data 24/7 to help offset some of the mundane work that goes into making important trading decisions in the cryptocurrency space.

SATT coins are used to unlock advanced technical analysis data and features at https://satt.io/app.  Any stakeholder of the coins is granted live streamed data, with non-holders given cached data for demonstrative purposes only.

Some of the app feature highlights:
- Gathers all pairings from popular top exchanges (currently Bittrex, Binance, and Gdax)
- Highlights significant events like price spikes / tanks
- Highlights new coin listings
- Ranks pairings by our custom cumulative TA "score"
- Pairings are searchable & sortable by most available metrics
- Easy links to pairing pages on their 3rd-party exchanges for quick access
- Multiple views for detecting important things worth caring about
- Embedded TradingView charts for easy candle viewing
- Coming soon features include personalized notifications, arbitrage detection, parameter customization and so much more.

**Comment by tradedbytony** [comment]
Hi there.

Thank you for your interest in having the token listed in ForkDelta, but as per the listing guidelines, you don't have enough token holders at the present moment. Therefore, we cannot list you at this time.

**Comment by johnrazmus** [comment]
We have performed an airdrop to help distribute and increase the number of SATT coin holders and increase awareness of the platform & it's token. Does this satisfy the requested disbursement guidelines for listing?

**Comment by tradedbytony** [comment]
There are hardly any comments on the Bitcointalk thread. 

Are there no social media presence? There's a Twitter account linked on Etherscan but nowhere to be found on the actual website.

When there's a bit more action on the Bitcointalk thread and you address the social media links on the website, feel free to open a new issue.
