### ISSUE TITLE
Coin Listing Request for Polaris Token (XPR)

### ISSUE THREAD

**Issue by nabilamrani** [forkdelta/tokenbase#605]
Contract address: 0x54a3f499f3e9ec22cbdec21bd38619561475da75

Issuer's official website: https://polarisxpr.com/

Official contract address confirmation: https://polarisxpr.com/#about

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2738392.0

Description: Our token represents a share in a mining farm that we operate, and it is backed by the buy-back & burn process of XPR from the Polaris mining farm using its profits following the business model highlighted in our white paper:

https://polarisxpr.com/Polaris-White-Paper.pdf

We will be very happy if we get listed in ForkDelta. My name is Nabil Amrani & I'm part of the team behind this project. We're here if we need to do more to have XPR listed in your exchange.

Thank you very much!

**Comment by Kryptoniq** [comment]
#287
