### ISSUE TITLE
TOKEN LIST REQUEST - MGT (MINGO TOKEN)

### ISSUE THREAD

**Issue by TDBlockchain** [forkdelta/tokenbase#606]
Contract address:  0x17c432e543952f950e8cB05dD5107eFe6864d1de

Issuer's official website: https://mingocoin.com/

Official contract address confirmation:

A link to a third-party review or discussion of the token:

Description:

**Comment by Kryptoniq** [comment]
Please, follow the instructions here https://www.reddit.com/r/ForkDelta/comments/7tntnz/how_to_get_an_erc20_token_listed_on_forkdelta/
