### ISSUE TITLE
Add new FUCK Token and change old

### ISSUE THREAD

**Issue by shwifteey** [forkdelta/tokenbase#607]
Hello, here is the listing information for the new FUCK Token contract address.  It would be great if you could change the current FUCK to FUCKOLD2.  I am sorry for the inconvenience.

Contract address: 0x65be44c747988fbf606207698c944df4442efe19
Symbol: FUCK
Decimals: 4

Issuer's official website:  https://fucktoken.com
Whitepaper: https://fucktoken.com/download/FUCKToken_Whitepaper_V1.pdf

Official contract address confirmation: https://fucktoken.com (on the front page)

also on Reddit explaining the reasoning: https://www.reddit.com/r/FuckToken/comments/85ddq4/important_fuck_token_has_forked_3182018/

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=1945661.0

Description:
In today’s society, we have an epidemic where millions of people have no fucks to give. With our ERC-20 FUCK token we have solved the “lack of FUCKs” problem. Tip your friends 0.001 FUCKs, or 1 FUCK, it doesn’t matter how many FUCKs you give. All that matters is you are contributing something to society.

**Comment by shwifteey** [comment]
The new address is reflected on etherscan.

New: https://etherscan.io/token/0x65be44c747988fbf606207698c944df4442efe19
Old: https://etherscan.io/token/0xab16e0d25c06cb376259cc18c1de4aca57605589

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be updating the token in the next few days, you'll receive an update when we do.
0x65be44c747988fbf606207698c944df4442efe19, https://fucktoken.com/

**Comment by JonathonDunford** [comment]
@shwifteey 

This update should be live any minute now. :)
