### ISSUE TITLE
Delist request: EM

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#608]
As stated in #492 this token isn't legit for a variety of reasons.

As mentioned by @Kryptoniq:
- the user has previously attempted to even list another scam token, unsuccessfully.
- been banned by @freeatnet at one point

As I mentioned in #495 in regards to this token:
- this token is on a free WiX site, using the default WiX social media links (they didn't even bother making some fake social media for it)

Also worth noting that they have just 2 token holders.

Rather than comply with the contract change request in #492, I hereby ask for this token to be delisted instead.

**Comment by Miroza666** [comment]
I may change from wix to normal site.It may decide token problem?

**Comment by freeatnet** [comment]
I'm for it.

**Comment by Miroza666** [comment]
I need to change site from wix to normal,after that you can change contract address?
Thanks.

**Comment by Miroza666** [comment]
Web site updated : https://elementerc.tech/
Where also I need change?

**Comment by Miroza666** [comment]
Website changed,added whitepaper,documentation and other information.

**Comment by freeatnet** [comment]
@Miroza666 Please list here precisely what requirements are satisfied.

**Comment by Miroza666** [comment]
1.Whitepaper added - available on site
2.Documentation to use added - available on site
3.Soon will be do free airdrop.
4.Team member written on site.

**Comment by Miroza666** [comment]
If requirements satisfied,may you change contract address?
