### ISSUE TITLE
Listing request - OST

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#609]
Website: https://ost.com
Whitepaper: https://drive.google.com/file/d/0B4f0lcszU8fnRmZKNWhUc1FoaUU/view
Description: Any app can launch branded tokens on open scalable side-chains, powered by Simple Token, a protocol for consumer-app tokenization and an ERC-20 utility token.

Link to confirm contract: https://sale.simpletoken.org (Click on "After Guide Sale" which will open a file on Google Drive and in it you'll find the confirmation)

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2266379

Third-party review: https://hacked.com/ico-analysis-simple-token
https://icorating.com/analytics/basic/simple-token-project-reviewtoken

Etherscan: https://etherscan.io/token/0x2c4e8f2d746113d0696ce89b35f0d8bf88e0aeca
Symbol: OST
Full Name: Simple Token
Decimals: 18

EXTRA NOTES:
The ICO raised over 46,828 ETH (over $ 21.000.000 at the time it ended).
Even though, technically, the token's symbol is ST, it is listed as OST on Binance, CoinMarketCap, etc. No one uses ST when it comes to listing this token.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x2c4e8f2d746113d0696ce89b35f0d8bf88e0aeca, https://ost.com/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Simple Token has been listed: https://forkdelta.github.io/#!/trade/ST-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
