### ISSUE TITLE
Request ERC20 token listing: NAC

### ISSUE THREAD

**Issue by thanhrenabio** [forkdelta/tokenbase#612]
Contract address: 0x8d80de8a78198396329dfa769ad54d24bf90e7aa
Official website: https://nami.trade
Description: Nami.Trade is a decentralized trading exchange that will revolutionize trading forex, commodities, indexes, bonds and cryptocurrencies. Capitalizing on advanced Blockchain technology, nami.trade is a transparent, decentralized, anonymous, and fully automated trading exchange to reduce trading fees by 100 times compared to other traditional exchanges. Nami.trade is the flagship product to improve connectivity and sustainability of the ecosystem within Nami Corporation.
Official page with contract address: https://nami.trade/buy
Discussion: https://bitcointalk.org/index.php?topic=2933106.0

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x8d80de8a78198396329dfa769ad54d24bf90e7aa, https://nami.trade/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Nami ICO has been listed: https://forkdelta.github.io/#!/trade/NAC-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
