### ISSUE TITLE
TOKEN CSFT

### ISSUE THREAD

**Issue by mars130** [forkdelta/tokenbase#613]
Contract address: 0x57b88d3ce3ba5937dcc1c48f35f8132d1c744dc0

Issuer's official website: https://cryptosafe.fund/landing

Official contract address confirmation: vsgnezdilov@gmail.com

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2956591  and https://www.reddit.com/r/cryptosafefund/

Description:
Coins of the investment fund, which takes investments in trust management. Coins have already been published on the KKCOIN exchange:
https://www.kkcoin.com/trade?symbol=CSFT_ETH

**Comment by Kryptoniq** [comment]
Make your contract address available on the website.
Your bitcointalk announcement thread has insufficient reviews and comments.
Please, provide a valid description of your project.

**Comment by mars130** [comment]
We added a link to Etherscan on our official website, as well as a link to Github all this is placed in the basement of the site.

Detailed description of the token:
CSFT is a crypto-currency fund token that trades on the exchange and brings a monthly income to all the owners of the tokens. Investments in the fund occurs through the purchase of data tokens and the initialization of their wallet on the official website, on which the income is accrued.

**Comment by Kryptoniq** [comment]
Please provide link to a third-party review or discussion of the token.

**Comment by mars130** [comment]
https://bitcointalk.org/index.php?topic=2956591.40
https://bitcointalk.org/index.php?topic=3223523
https://www.reddit.com/r/cryptosafefund/

**Comment by freeatnet** [comment]
@Kryptoniq ping

**Comment by Kryptoniq** [comment]
There are only 21 token holders 97% of the tokens belongs to the team.
What is your method of token distribution?
