### ISSUE TITLE
Add ESports Token (ERT)

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#614]
Website: https://esports.com
Whitepaper: http://www.esports.com/doc/ESPORTS.COM_Whitepaper.pdf
Description: We're creating the biggest esports portal in the world! We are gamers and we know what gamers want!

Link to confirm contract: http://www.esports.com/ert-info.html

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2095143

Etherscan: https://etherscan.io/token/0xe29c5b523590165795bbd7d52369c2895b18841f
Symbol: ERT
Full Name: ESports Token
Decimals: 18

EXTRA NOTES:
The ICO raised 5.800.000.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xe29c5b523590165795bbd7d52369c2895b18841f, https://esports.com/
