### ISSUE TITLE
Mankind First

### ISSUE THREAD

**Issue by raymaker** [forkdelta/tokenbase#615]
Please list Mankind First
Contract address:
0x95aBb152ed410cc4b6DffB3eD41D01015bdbb5D2
Decimal:  18
Symbol: MK 
Issuer's official website:
http://mankindfirst.com/

Official contract address confirmation:
http://mankindfirst.com/#About
(press second button on the left)

A link to a third-party review or discussion of the token:
https://twitter.com/mankindfirst1 (23K)
https://bitcointalk.org/index.php?topic=2729585.msg27940833#msg27940833
http://mankindfirst.com/assets/img/logo.png
Description:
A platform that will utilise blockchain technology to work beside any politics, race and religion, constantly gearing towards a common goal of empowering humanity and supporting mankind.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x95abb152ed410cc4b6dffb3ed41d01015bdbb5d2, http://mankindfirst.com/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by raymaker** [comment]
Hello
thank you very much.
Kind Regards
Sen
    Am Montag, 9. April 2018, 14:15:56 MESZ hat Arseniy Ivanov <notifications@github.com> Folgendes geschrieben:  
 
 
Thank you for your request! Your token will be listed on April 11th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Mankind has been listed: https://forkdelta.github.io/#!/trade/MK-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
