### ISSUE TITLE
Listing request - UP

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#617]
Website: https://uptoken.org
Whitepaper: https://uptoken.org/UpToken-whitepaper.pdf
Description: Coinme is building the largest crypto ATM network in the world. As the first licensed Bitcoin ATM company in the United States, Coinme’s proven track record and human-first approach have brought thousands of fresh faces into this growing community.
This is truly a unique partnership. When a customer uses a Coinme ATM, Coinme will reward the customer with UpToken (digital “1% cash back”). Coinme will purchase the UpToken Reward from the crypto community.
UpToken is designed to rapidly build a crypto ATM network where we all rise together.

Link to confirm contract: https://github.com/coinme/uptoken

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2199751

Third-party review: https://www.forbes.com/sites/laurashin/2017/09/21/heres-the-man-who-created-icos-and-this-is-the-new-token-hes-backing
https://bitcoinexchangeguide.com/coinme

Etherscan: https://etherscan.io/token/0x6ba460ab75cd2c56343b3517ffeba60748654d26
Symbol: UP
Full Name: UPToken
Decimals: 8

EXTRA NOTES:
The ICO raised 18.900.000.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x6ba460ab75cd2c56343b3517ffeba60748654d26, https://uptoken.org/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be live on **Wednesday, June 6th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
