### ISSUE TITLE
Update of our Ticker Symbol Please from RCT to RCPT

### ISSUE THREAD

**Issue by nickjuntilla** [forkdelta/tokenbase#618]
Hi, I'm from ReceiptCoin.  We've been trading on EtherDelta for a few months, but were given a ticker symbol that was not correct. Can we update our Ticker symbol from RCT to RCPT.  We've agreed that should be our official global exchange symbol to not collide with anyone else. We have a history of transactions and volume though. Is it possible to keep that history? Thanks!

Nick
CEO ReceiptCoin

Contract address: 0xd6e49800dECb64C0e195F791348C1e87a5864FD7

Issuer's official website: https://www.receiptcoin.io

Official contract address confirmation: https://receiptcoin.io/faq

A link to a third-party review or discussion of the token: https://icobench.com/ico/receiptcoin

Description: ReceiptCoin is building a universal blockchain receipt standard as will as APIs and apps to use them. Our Receiptchain app is a marketplace for second hand goods, tracking, tickets, and personal inventory.

**Comment by Kryptoniq** [comment]
Please, provide a link to an announcement confirming  the change of ticker  from any of your official social media  handles.

**Comment by nickjuntilla** [comment]
This is our official twitter. You can also see I am the primary commiter to the receiptcoin githhub https://github.com/receiptcoin

https://twitter.com/receiptcoin/status/977619935462547456

Thank you!

**Comment by nickjuntilla** [comment]
@Kryptoniq Hello? I have provided the information you requested. Please respond.

**Comment by freeatnet** [comment]
@nickjuntilla Sorry for the delay. We can certainly arrange this change.

**Comment by nickjuntilla** [comment]
@freeatnet Awesome. We're really looking forward to it!

**Comment by nickjuntilla** [comment]
Any word on this?

**Comment by nickjuntilla** [comment]
@freeatnet @Kryptoniq Hey I just updated that we are trying to get our ticker symbol updated from RCT to RCPT on bitcointalks. Had to take it down off of twitter for legal reasons, but we would still really like our symbol updated if possible? https://bitcointalk.org/index.php?topic=2954429.msg30318521#msg30318521

**Comment by freeatnet** [comment]
@nickjuntilla Signature checks out, thank you. (see: https://etherscan.io/verifySig/1166)

**Comment by freeatnet** [comment]
@nickjuntilla Does https://github.com/forkdelta/tokenbase/pull/1223/files look right to you?

**Comment by nickjuntilla** [comment]
@freeatnet Yeah that looks great. Thanks.
