### ISSUE TITLE
Token Listing : IRONCOIN

### ISSUE THREAD

**Issue by IRONBANKOFBRAAVOS** [forkdelta/tokenbase#62]
Contract Address: 0x1f21d8395655fb262251897df7cb3c9358bec6a2
Symbol: IRC
Decimals: 8

Official Site URL: http://www.ironcoin.ga/ 

Official page confirming the contract address : http://www.ironcoin.ga/ 

bitcointalk : https://bitcointalk.org/index.php?topic=2858369.msg29339396#msg29339396

reddit : https://www.reddit.com/r/MYIRONCOIN/

twitter : https://twitter.com/myironcoin/

github : https://github.com/IRONBANKOFBRAAVOS/IronCoin

Description : IRONCOIN is the token of the Iron Bank of Braavos. It's arguably the most powerful financial institution in the Known World.

If you have any questions, don't hesitate to contact me.

Thanks

**Comment by JonathonDunford** [comment]
Once #85 goes through, this token will be added to tokenbase (and subsequently ForkDelta).

**Comment by JonathonDunford** [comment]
Will be added to FD once https://github.com/forkdelta/forkdelta.github.io/pull/60 goes through.

**Comment by JonathonDunford** [comment]
https://forkdelta.github.io/#!/trade/IRC-ETH
