### ISSUE TITLE
Formalize removal process of OLD tokens

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#620]
We need to have some sort of procedure for removing all of the OLD tokens.

I propose that when we make announcements about contract changes, we state that the token is preserved under TICKER_OLD for 2 weeks. After 2 weeks, TICKER_OLD will be removed.

When TICKER_OLD is removed, we can make a second announcement about its removal.

**Comment by tradedbytony** [comment]
#452 talks about this. You're not alone in wanting them out.

2 weeks should be plenty of time to get them out for good after the initial announcement. I'm all for it. The less I have to scroll down, the better.
