### ISSUE TITLE
New Token CIB Listing

### ISSUE THREAD

**Issue by coinsurreblock** [forkdelta/tokenbase#623]
Contract address: 0xb8DfAcFA7580378D8656EbE390fA933F234F2324

Issuer's official website: http://coinsureblock.tk

Official contract address confirmation:
https://github.com/coinsurreblock/ERC-20-Smart-contract/blob/master/coinsureblock-erc20.sol

A link to a third-party review or discussion of the token:
<https://bitcointalk.org/index.php?topic=3102996.msg32038084#msg32038084>

Description:

CoInsureBlock (Token Symbol : CIB) ’is a next generation of peer-to-peer insurance based on social proof endorsements, fully harnessing the power of blockchain innovation. It aims to become the world’s first insurance service offering trust to members of the crypto community when transacting products and services.

**Comment by tradedbytony** [comment]
Where do I even start?

3 token holders. White paper is a copy and paste job. Nameless team. Speaking of team, every single person in your "team" is in uifaces.com and other stock photos sites.

You swang and you missed. Good try, but no.

Closing.
