### ISSUE TITLE
listing our coin

### ISSUE THREAD

**Issue by rutheneum** [forkdelta/tokenbase#624]
Contract address:

Issuer's official website:

Official contract address confirmation:

A link to a third-party review or discussion of the token:

Description:

**Comment by rutheneum** [comment]
https://www,rutheneum.com
https://wallet.rutheneum.com

**Comment by tradedbytony** [comment]
Some red flags right off the bat.

First, completely malformed request here.

Second, your entire team is fake. Your "Head of Community" who you claim to be a guy called M. Ruther is actually an academic scholar called Wagner Hoffmann. Your "Community Manager" who you claim to be T. Moskrivina is actually a woman called Barbara Phelps. And the list goes on.

Third, your company address is a virtual address which anyone can acquire for $69/month.

I'm sorry, but we'll have to pass on your request.

Closing this.
