### ISSUE TITLE
Flowing Hair (FGH)

### ISSUE THREAD

**Issue by FlowingHair** [forkdelta/tokenbase#625]
**Contract address:**
0x3ec03cD2763A729339AFf9927BE679c76325D1bf

**Issuer's official website:**
www.flowinghair.info

**Official contract address confirmation:**
https://etherscan.io/address/0x3ec03cd2763a729339aff9927be679c76325d1bf
www.flowinghair.info

**A link to a third-party review or discussion of the token:**
https://twitter.com/FlowingHairFGH

**Description:**
Flowing Hair (FGH) is an Ethereum-based Token for use in mainstream digital wallets.

**Comment by FlowingHair** [comment]
**Flowing Hair (FGH) is available on ForkDelta at :**
https://forkdelta.github.io/#!/trade/0x3ec03cd2763a729339aff9927be679c76325d1bf-ETH

**Comment by tradedbytony** [comment]
Thank you for your interest in listing at ForkDelta. Unfortunately, you do not have enough token holders and as per the listing guidelines, we cannot list you at this time. When the pre-sale/ICO phase approaches its end and you have a higher participation in your project, you could attempt to list again at a later date. Also, the project lacks a white paper, clear purpose, social media, a bitcointalk thread, a proper third-party review (you can't list your twitter as a valid review).

Best of luck.

Closing.
