### ISSUE TITLE
Listing request - DAN

### ISSUE THREAD

**Issue by josephbedminster** [forkdelta/tokenbase#626]
Contract address:
0x9b70740e708a083c6ff38df52297020f5dfaa5ee

Issuer's official website:
https://daneel.io

Official contract address confirmation:
https://daneel.io/contract
https://medium.com/@daneel_project/dan-tokens-distribution-is-coming-soon-get-ready-c49432027599

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2376203

Description:
Daneel assists you in your daily crypto investment
Daneel is a personal assistant using IBM Watson technology, one of the most efficient artificial intelligence platforms on the market. Daneel has your back, supporting you by offering daily assistance in the world of cryptocurrency. He will be able to : 
- Understand you and interact with you,
- Keep you informed in real-time, with quality and reliable information,
- Identify and capture the different emotions of the market.

Etherscan:
https://etherscan.io/token/0x9b70740e708a083c6ff38df52297020f5dfaa5ee

Symbol: DAN
Full Name: Daneel
Decimals: 10

Notes:
This ICO raised 2M USD.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x9b70740e708a083c6ff38df52297020f5dfaa5ee, https://daneel.io/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on **Monday, April 30th, 2018**. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Daneel has been listed: https://forkdelta.github.io/#!/trade/DAN-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
