### ISSUE TITLE
Listing Request - Vega

### ISSUE THREAD

**Issue by VegaAISolutions** [forkdelta/tokenbase#628]
Contract address:
0xca48AC42C9Cd4eE98813af8945A1024868ee62de

Issuer's official website:
https://vegais.com

Official contract address confirmation:
Click on Token/Contract from the website https://vegais.com

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2422153.0

Description:
addr: '0xca48AC42C9Cd4eE98813af8945A1024868ee62de'
decimals: 18
description: >-
 Vega Intelligent Solutions is creating the Vega AI interacting with users through communication systems
 leveraging machine learning into our every day lives. Our applications are intended for traders on
 various markets, working towards changing the world of investment tools and portfolio management utilities.
links:
- Bitcointalk: https://bitcointalk.org/index.php?topic=2422153.0
- Email: mailto:contact@vegais.com
- Facebook: https://www.facebook.com/VegaAISolutions/
- Telegram: https://t.me/vegais
- Discord: https://discord.gg/V7ejpEg
- Twitter: https://twitter.com/VegaAISolutions
- Website: https://vegais.com/
- Whitepaper: https://vegais.com/whitepaper
- YouTube: https://www.youtube.com/channel/UCh0VfuCPgW88Y-N1vyNjinA
- GitHub: https://github.com/VegaAISolutions/VegaAI
- Blog: https://medium.com/@VegaAISolutions
- Reddit: https://www.reddit.com/r/VEGAis/
name: Vega
symbol: VEGA

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xca48AC42C9Cd4eE98813af8945A1024868ee62de, https://vegais.com/

**Comment by VegaAISolutions** [comment]
Thank you we truly appreciate the listing! Looking forward to it!

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on **Monday, April 30th, 2018**. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Vega has been listed: https://forkdelta.github.io/#!/trade/VEGA-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated
