### ISSUE TITLE
Add Notice to SXDT @ Request of Devs

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/tokenbase#629]
"Attention to U.S citizens: Securities and Exchange Commission (SEC) regulations in U.S are very strict regarding trading securities. The underlying asset is considered a security. U.S citizens are prohibited from trading this asset. Spectre runs strict KYC and will withhold dividends to those claiming dividends who are from restricted regions such as the U.S."

**Comment by Kryptoniq** [comment]
Safe to close.
