### ISSUE TITLE
REKT Token

### ISSUE THREAD

**Issue by cognitivejuan** [forkdelta/tokenbase#63]
Address: 0xCbC99B988301df3BCCFC1DcA3706019C336F47f6
Site: RektEx.com
Coin Site: coin.rektex.com
Bitcointalk: https://bitcointalk.org/index.php?topic=2759524.msg29870996#msg29870996

Thank you for your consideration. Please contact me at eric@exknox.com if you have any questions.

**Comment by JonathonDunford** [comment]
Contract address correct. We need a description though.

**Comment by Rektex** [comment]
Can you do it like this?
<blockquote>
  <p>Rekt Coin for the RektEx Forum.</p>
  <footer><a href="http://rektex.com/" target="_blank">RektEx.com</a></footer>
</blockquote>

**Comment by Rektex** [comment]
Just 'Rekt Coin for the RektEx Forum' can you make the link '<a href="http://rektex.com/" target="_blank">RektEx.com'?

**Comment by JonathonDunford** [comment]
I'll add that description. Custom formatting for links currently isn't in the system.

**Comment by Rektex** [comment]
Thank you

**Comment by JonathonDunford** [comment]
@Rektex 

tokens/0xcbc99b988301df3bccfc1dca3706019c336f47f6.yaml:
  6) Failure/Error: ReadTimeout: HTTPSConnectionPool(host='api.myetherapi.com', port=443): Read timed out. (read timeout=10)
        in test_contract_erc20_totalSupply: token contract must support totalSupply

Your token must be ERC20 compliant before we can list you.
