### ISSUE TITLE
DigiDex listing

### ISSUE THREAD

**Issue by DigiDextoken** [forkdelta/tokenbase#631]
Contract address:
0x03b23d3b7d1ff984debfd36855b381f8d27cce38
Issuer's official website:
www.digidextoken.io
Official contract address confirmation:

www.digidextoken.io

Bottom of page
A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=3092321.0

Description:
The DigiDextoken will enable real time point of sale (POS)
transactions directly from users’ private cryptocurrency
wallets. We predict the ability to make purchases in-store and
online using cryptocurrencies will speed
up mass adoption of the technology.

**Comment by DigiDextoken** [comment]
Ticker is DGX

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x03b23d3b7d1ff984debfd36855b381f8d27cce38, http://www.digidextoken.io/

**Comment by freeatnet** [comment]
A few issues with this one.
* ICO-only website, no pointers to the project website.
* No team information
* No legal information
* Project description and whitepaper are wholesale copies of [STK whitepaper](https://stktoken.com/STK_whitepaper_en.pdf), including and not limited to Introduction (originally, "Abstract"), Main Problem (originally, "Problem Statement"), and "HOW DOES THIS WORK IN PRACTICE?" sections.

Based on these findings, we will not be listing this token. If you believe that this decision was made in error, you may post objective facts supporting the validity of your project below.

--- 
Project assets reviewed:
* [Website](https://digidextoken.io) ([archived copy](http://archive.is/95hRn))
* [Whitepaper](https://www.docdroid.net/juAYq03/whitepaper.pdf)
* [ICOBench profile](https://icobench.com/ico/digidex) ([archived copy](http://archive.is/DAxe9))
