### ISSUE TITLE
Add Token Please

### ISSUE THREAD

**Issue by TokensWorldCoin** [forkdelta/tokenbase#640]
Contract address: 0x4C3891C5140bbD0Cddd3643ceD0d14A50c3F6271

Issuer's official website: 

https://tokensworld.io/

Social:
https://www.facebook.com/tokensworld.io/
https://twitter.com/TokensWorldCoin/
https://www.reddit.com/user/TokensWorldCoin/
https://bitcointalk.org/index.php?action=profile;u=1960099

Symbol: TWO
Name: Tokens World Coin
Web Oficial: https://tokensworld.io/
Decimals: 18
Total Supply:  50,000,000

WORLD DIRECTORY OF NEW TOKENS ERC20 BASED ON ETHEREUM, AND CRYPTOCURREN

Our directory "does not charge for listing the new tokens" solutita acquire our token to be indexed and then can save or sell them, our token will generate support to grow the directory and give new icos on social networking, the directory supports our cryptocurrency to create a virtuous circle and grow this fascinating world of cryptocurrencies

Official contract address confirmation:

A link to a third-party review or discussion of the token:

Description:

WORLD DIRECTORY OF NEW TOKENS ERC20 BASED ON ETHEREUM, AND CRYPTOCURREN

Our directory "does not charge for listing the new tokens" solutita acquire our token to be indexed and then can save or sell them, our token will generate support to grow the directory and give new icos on social networking, the directory supports our cryptocurrency to create a virtuous circle and grow this fascinating world of cryptocurrencies

**Comment by tradedbytony** [comment]
Thank you for your interest in listing at ForkDelta. Unfortunately, we cannot list you at this time. You currently only have 2 token holders, there's no white paper, there's no team, no clear purpose, nothing going on at bitcointalk and the social media activity is dead. When you have a higher level of participation in your project, you could attempt to list again at a later date. Best of luck.

Closing.
