### ISSUE TITLE
List ePRX Token

### ISSUE THREAD

**Issue by vicwebdesign** [forkdelta/tokenbase#641]
Contract address: 0x147b51d82a6038607895e11c4191431335b257e3
Symbol: ePRX
Full Name: eProxy
Decimals: 8

Website: https://www.proxycard.io
Whitepaper: https://www.proxycard.io/whitepaper.pdf

**Description:** 
Proxy has developed "Proxy Wallet", which features bio-metric security and is a NFC-enabled physical wallet, The proxy wallet will be the center of the Proxy merchant services ecosystem. The Proxy Ecosystem will consist of a marketplace, a chat messenger, and crypo-currency merchant services.

The Proxy wallet will enable you to safely store and spend crypto currencies at merchants that accept blockchain payments. 

The ePRX token can be used by merchants to pay their merchant fees. Merchants will have the incentive to accept blockchain payments because merchants fees range from 0.5%-1.0% while visa networks is 1.5%-3.0%.

The Proxy Wallet is currently available for download at the Google Play store, it will be available soon in the Apple Store:
https://play.google.com/store/apps/details?id=io.proxycard.proxy

Video of Proxy Wallet: https://youtu.be/Dljzr4-fcbs

In the News:
https://www.ccn.com/proxy-card-launch-proxy-wallet-partnership-ebitcoin-foundation/
https://coinidol.com/proxy-wallet-launches-today/
https://www.crypto-news.net/ebitcoin-multiple-payment-solution/

Link to confirm contract: https://etherscan.io/token/0x147b51d82a6038607895e11c4191431335b257e3

more in depth details:
medium: https://blog.proxycard.io/
twitter: https://twitter.com/Proxy_Card
telegram: https://t.me/proxycard

Third-party comment(s) on the token: https://bitcointalk.org/index.php?topic=2206814

Proxy is a partner in the eBitcoin Ecosystem: https://www.ebitcoin.org/our-ecosystem/

**Comment by jayman2989** [comment]
Confirmed by myself, CEO & Lead Android Dev @ Proxy. Can confirm with @proxycard.io email if need be.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x147b51d82a6038607895e11c4191431335b257e3, https://www.proxycard.io/

**Comment by freeatnet** [comment]
@jayman2989 Your website is currently not loading with a JS error in Chrome.

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on **Monday, April 30th, 2018**. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by jayman2989** [comment]
Great, thank you. Funny timing with that JS error!

**Comment by freeatnet** [comment]
Thank you for your request! eProxy has been listed: https://forkdelta.github.io/#!/trade/ePRX-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
