### ISSUE TITLE
Add SKRP

### ISSUE THREAD

**Issue by Ado808** [forkdelta/tokenbase#642]
Contract address: 0xfdFE8b7aB6CF1bD1E3d14538Ef40686296C42052

Issuer's official website: https://skraps.io/

Official contract address confirmation:
https://dashboard.skraps.io you can click on 'token contract' without need of registering

A link to a third-party review or discussion of the token:
https://icobench.com/ico/skraps
https://icobazaar.com/v2/skraps
https://www.reuters.com/brandfeatures/venture-capital/article?id=29125 (not sure if this counts as review)
Audit: https://cryptocoinconnection.com/skraps_audit.pdf

Description: Invest spare fiat and cryptocurrency change into diversified crypto-related portfolios. Skraps is the first company to offer micro investing to the world of cryptocurrencies. The Skraps platform allows users to round up spare change from everyday fiat and cryptocurrency related purchases and invest the difference into diversified portfolios of cryptocurrencies and crypto assets. Customers can get started in 3 easy steps: Connect your debit/credit card or cryptocurrency wallet, spend like normal, and watch your spare change grow.

Notice: Tokens are frozen till April 1st 23:59:59 PST 

Links:
Web: skraps.io
Twitter: https://twitter.com/SKRAPS_IO
facebook: https://www.facebook.com/SKRAPSAPP/
telegram: https://t.me/SkrapsOfficial
Email: info@skraps.io

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xfdfe8b7ab6cf1bd1e3d14538ef40686296c42052, https://skraps.io/

**Comment by freeatnet** [comment]
/remind me to list this on April 1

**Comment by Ado808** [comment]
Reminder was removed when I edited the post and added exact time of token unlocking.So I'm reminding you this way.

**Comment by freeatnet** [comment]
@Ado808 Thank you for your request! Skraps has been listed: https://forkdelta.github.io/#!/trade/SKRP-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by Ado808** [comment]
Thanks for listing! I have sent link for donating to their telegram channel.I hope I don't get banned lol
