### ISSUE TITLE
ActiveToken Listing

### ISSUE THREAD

**Issue by andylam110** [forkdelta/tokenbase#643]
Contract address:  0x65ae58320217a07ea4d1ffaf4005a99197592a8c
--

Issuer's official website: https://www.activetoke.com/

Official contract address confirmation: https://www.activetoke.com/ address is on the website front page

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3152925.msg32590804#msg32590804
https://bitcointalk.org/index.php?topic=3164586.msg32717337#msg32717337

Description: Our idea of ActiveToken (ATE), is an entrepreneurial decentralized currency in which sets to

create a revolution in the social media marketing industry. Usages for this token has already began implementing new features & investors are starting to take notice from this beneficial peer-to-peer blockchain technology! You hear the saying "There's always an end to the finish line." With ActiveToken, our progress to completing our goals on the road-map won't end. Our project will be beneficial long-term as we achieve & open many new doors & opportunities for investors of ActiveToken. Please read the guidelines before investing! We've already been accepted to four exchanges & that news will be anonymous until further notice. Through ActiveToken, we will change the social media marketing industry. Invest today!

our email is activetokenbiz@gmail.com

**Comment by andylam110** [comment]
telegram news  https://t.me/activetoken
telegram group chat  https://t.me/joinchat/FCa8uxCOACPzOvPX6lARvQ
twitter  https://twitter.com/ActiveToken
video promo  https://www.youtube.com/watch?v=QGttJCqUQiM

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews and comments.
You claim to have raised  $67k but there are only 10 token holders. Please, elaborate.  
Your smart contract source code has not been verified on etherscan.io.
