### ISSUE TITLE
Listing VRTY Token on ForkDelta

### ISSUE THREAD

**Issue by Verity-Project** [forkdelta/tokenbase#65]
Hello!

I hope you are doing well. I would like to list my company's utility token called VRTY on ForkDelta. I would be very appreciative if you could assist me with this.

1. Contract address: 0x87e960f996E789CA2c8415fC449e4720ADBE0497
2. Official site: http://www.veritychain.io/
3. Verified contract address: https://etherscan.io/address/0x87e960f996e789ca2c8415fc449e4720adbe0497
4. 3rd party review board? I'm sorry, we are just releasing our token and haven't made any efforts to host a peer-review or seek discussions. The main purpose of introducing our token was to offer a more accurate payment method for clients contracting our services. Although there are more benefits to the token, such as authentication of marketing claims through our blockchain verification protocol.

If you need any more information, please do not hesitate to contact me! I'm very open to questions if you have them as I would like to get my company's token listed on ForkDelta.

Thank you,
Adam

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/commit/cf6f3057a19ef986f917009bc611ae712c4f64a6
