### ISSUE TITLE
Listing MNL token please

### ISSUE THREAD

**Issue by drtiger9** [forkdelta/tokenbase#650]
Contract address: 0x0d62dc6cd8c81dca8caadccf01ffe7c1f31d9402

Issuer's official website: moonlite.io

Official contract address confirmation: https://sale.moonlite.io/add-mnl-token

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2712054.0

Description:
The MoonLite Project will operate several industrial scale data centers in the Crypto-Currency Mining industry, and plans to begin by mining predominantly Bitcoin, DASH, Litecoin, and Ethereum using 100% sustainable, green energy. 100% of the energy we consume is generated using Hydro, Geo-Thermal, and Wind sources. The MoonLite Project will base its first mining operation in data center capital of the world, Iceland, where the average tariff for the industrial connections are 0.043 USD per kWh. Our data centers enjoy a contractual supply of the cleanest energy available, and at a multi-year fixed rate, and additionally do not need to provide extensive cooling infrastructure due to the cool Icelandic climate.

**Comment by Kryptoniq** [comment]
Your contract address is not verified on etherscan.io. 
https://etherscan.io/address/0x0d62dc6cd8c81dca8caadccf01ffe7c1f31d9402#code
