### ISSUE TITLE
Saifu token listing

### ISSUE THREAD

**Issue by daryashakh** [forkdelta/tokenbase#653]
Name: Saifu
Symbol: SFU
Contract adress: 0x82ba2b46483266068f340d538dab41394d01c782
decimals: 18
Issuer's official website: https://ico.saifu.ai
Official contract address confirmation: https://ico.saifu.ai - scroll and go to  "get to know Saifu better", there - "smart contract" field which is linked to etherscan.io
https://github.com/Saifu-ai/SFU - just in case here is link to github repository with smart contract
A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2472594.0
Description: Saifu creates one account for all currencies & cryptocurrencies for business and individuals

**Comment by daryashakh** [comment]
No need for listing. Thank you!

**Comment by Kryptoniq** [comment]
Hey @Daryashakh, what do you mean by
"No need for listing"?
