### ISSUE TITLE
new Token: CCBrother Project

### ISSUE THREAD

**Issue by brothercoin** [forkdelta/tokenbase#656]
Contract address: 0x0445aE32D33066A29e4573Bf15D4a2a9690ab754
Decimals: 18
Name: CCBrother
Dymbol: CBR
Official contract address confirmation:
https://etherscan.io/address/0x0445ae32d33066a29e4573bf15d4a2a9690ab754

Description:
 CCBrother project is want to become Goldman Sachs and Wind in the field of cryptocurrency.we have developed a APP,which Combined more than 30+ exchanges together、Hedging、Information Distribution、Automatic Translation、IM、Blockchain Project Rating and so on. Our vision is "One APP is Enough To Play CryptoCurrency".
Issuer's official website: http://www.ccbrother.org/
A link to a third-party review or discussion of the token: https://t.me/ccbrother
 Github：https://github.com/brothercoin 
APP Demo：https://www.pgyer.com/tKEo

**Comment by zxqcvp** [comment]
蛤蛤

**Comment by zxqcvp** [comment]
![image](https://user-images.githubusercontent.com/27429763/37810662-68181080-2e90-11e8-9d26-6a3aa9568131.png)
@I

**Comment by Kryptoniq** [comment]
1. Make the contract address available on the website.
2. Provide link to a third-party review or discussion of the token.

**Comment by brothercoin** [comment]
contract address is：
0x0445aE32D33066A29e4573Bf15D4a2a9690ab754
third-party review or discussio： Telegram  1.5K members
https://telegram.me/ccbrother


在 2018年4月7日，23:06，Krypton <notifications@github.com<mailto:notifications@github.com>> 写道：


  1.  Make the contract address available on the website.
  2.  Provide link to a third-party review or discussion of the token.

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
