### ISSUE TITLE
BlitzPredict (XBP)

### ISSUE THREAD

**Issue by Walleting-Services** [forkdelta/tokenbase#659]
Contract address:  0x28dee01D53FED0Edf5f6E310BF8Ef9311513Ae40

Issuer's official website: https://www.blitzpredict.io/

Official contract address confirmation:
https://www.blitzpredict.io/faq

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2557256

Description:
BlitzPredict is a global platform applying fintech solutions to provide function and liquidity to users of blockchain prediction markets and sportsbooks.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x28dee01d53fed0edf5f6e310bf8ef9311513ae40, https://www.blitzpredict.io/

**Comment by freeatnet** [comment]
Thank you for your request! The token will be live on **Wednesday, June 6th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
