### ISSUE TITLE
Token Listing PeraBit

### ISSUE THREAD

**Issue by perabitdev** [forkdelta/tokenbase#66]
Contract Address: 0x82917e1775149548eb7883c99b34f7cb0abfb756
Symbol: PBIT
Decimals: 8
Etherscan: https://etherscan.io/token/0x82917e1775149548eb7883c99b34f7cb0abfb756

Token Holder: 1292
Transfers: 1360

Telegram: https://t.me/PeraBit
Discord: https://discord.gg/38p2Sut
Official Thread: https://bitcointalk.org/index.php?topic=2846825.0

Discription. PeraBit is a token distribution protocol. It is created to help new project developers to distribute their token effectively using a smart contract.

Thanks and more power.

Hydar 
PeraBit Dev

**Comment by freeatnet** [comment]
Contract address verification: Whitepaper, https://drive.google.com/file/d/19HxrILx3S7RJ72bq2uAHWbRFU5UAybO7/view

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/commit/cf6f3057a19ef986f917009bc611ae712c4f64a6
