### ISSUE TITLE
please add Nano Coin

### ISSUE THREAD

**Issue by nanocointeam** [forkdelta/tokenbase#661]
Contract address: 0x9401089f3e8d11d7e4dea76c1755e6b75489884a

Issuer's official website: https://nanocoin.name

Official contract address confirmation: https://nanocoin.name

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3126150.0

Description: Nano Coin is the only secured ERC20 token built from the ground-up to facilitate payments and transfers without sacrificing your security.

**Comment by Kryptoniq** [comment]
First of all, RaiBlocks has rebranded and is now known as "Nano".
Your bitcointalk announcement thread has insufficient information and reviews. 
There are only 5 token holders. 

Plagiarism 

Nano Coin 
`Nano Coin is the only secured ERC20 token built from the ground-up to facilitate payments and transfers without sacrificing your security.`

Ethereum Blue 
`BLUE is the only secured ERC20 token built from the ground-up to facilitate payments and transfers without sacrificing your security.`

**Comment by Kryptoniq** [comment]
Sorry, we can't list your token.
