### ISSUE TITLE
Webcoin(WEB) Token Listing Request

### ISSUE THREAD

**Issue by webcoinico** [forkdelta/tokenbase#662]
Hi Team,

We are about to launch a PRE-ICO and ICO rounds for our upcoming ICO Stage 2 Webcoin project. During stage 1(which ended on 31 Dec, 2017) we raised over $400,000 in both crypto and fiat(USD & Euro).

Our ERC20 utility token - Webcoin is now verified by both Ethereum explorers:
https://etherscan.io/token/0x840fe75abfadc0f2d54037829571b2782e919ce4#balances
https://ethplorer.io/address/0x840fe75abfadc0f2d54037829571b2782e919ce4#pageSize=100

We already have over 100 investors from stage 1 and we have already closed deals with other reputable exchanges, like yours, to list us on their exchanges upon the end of our ICO stage 2 crowdsale.

Here's our final whitepaper text version: https://docs.google.com/document/d/1NsgCF4AcgbRqmgmZJ_3dxNHhmqSHQr_H8-jFuXju3LI/edit?usp=sharing

The final version will look much prettier very soon after we add all graphics, pictures and images of our advisors and team members.

Our new crowdsale site is yet to be ready(currently re-designing it - should be ready by the end of the month or the beginning of April). A draft version of it is available here - https://webcoin.netlify.com/#/
Bare in mind it is a work in progress and will look 100x better when it is fully ready.

We have a great number of crypto advisors some very popular in the field and we are yet to approach many others.

**_Now, we also want to get the OKAY from your exchange for listing our token upon the end of our ICO(final date will be confirmed, but we plan to end the ICO at the end of July, 2018 and start trading the token on exchanges immediately in August)._**
 
Here's the Webcoin token specifics:
Name of the token: Webcoin
Symbol of the token : WEB
Precision (decimals) : 18
Token address: 0x840fe75abfadc0f2d54037829571b2782e919ce4
Algorithm: ethash 
Number of blocks: 5265492
Dev Language: solidity
Block time: 1521202649
Type: ERC20
secp256k1 ver: Yes
Source link(github): https://github.com/webcoinico/Webcoin-Digital-Marketing-2.0
Explorer: https://etherscan.io/address/0x840fe75abfadc0f2d54037829571b2782e919ce4 

Our communities:
Facebook: https://www.facebook.com/Webcoinico
LinkedIn company profile: https://www.linkedin.com/company/Webcoin/ 
Twitter: https://twitter.com/Webcointoday 
Private Facebook group: https://www.facebook.com/groups/190746651671111/ 
Medium: https://medium.com/@Webcoinstoday 
Telegram: https://t.me/Webcoin 
Github: https://github.com/webcoinico/Webcoin-Digital-Marketing-2.0
Flock: https://Webcoin.flock.com/ 

We look forward to hearing back from you at the soonest.

**Comment by icocalendartoday** [comment]
Why is it closed?

**Comment by icocalendartoday** [comment]
When do we get a reply from you guys or you just close tickets with no response as you wish?

**Comment by Kryptoniq** [comment]
@icocalendartoday this issue was never closed. Duplicates were closed. Please wait for our review.

**Comment by icocalendartoday** [comment]
Sure, just want to see that you don't close requests automatically as we do get so far immediately after we open request. ICO ended in the end of May, we are on 7 exchanges already, so we hope we hear soon from you.

**Comment by icocalendartoday** [comment]
Any update?

**Comment by freeatnet** [comment]
@webcoinico @icocalendartoday Please make sure your request follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
