### ISSUE TITLE
NVC - nVision Cash Listing request

### ISSUE THREAD

**Issue by nvisioncash** [forkdelta/tokenbase#663]
Contract address: 0x643e7c00f3e3e67a635cfbbea615fba047af4f42

Issuer's official website: http://nvisioncash.com/

Official contract address confirmation: 0x643e7c00f3e3e67a635cfbbea615fba047af4f42

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=3182220.0

Description:

nVision Cash ( NVC )Token  is an ERC20 token built on top of the Etherium Blockchain and is a new digital currency that enables instant payments to anyone, anywhere in the world. It empowers the Global Retail Industry

**Comment by tradedbytony** [comment]
Only having 4 token holders would be a temporary disqualifier, but as I dug more into this token I found other stuff. I really hope no one falls for this scam.

Your Software Developer called "Wang Ru" is actually a dermatologist called Hugh M. Gloster (https://www.doximity.com/pub/hugh-gloster-md and http://web.archive.org/web/20130405070755/https://www.uc.edu/provost/committees/community-advisory-board.html).

Good try, but no.

Closing.

**Comment by nvisioncash** [comment]
There is no pic of our team members on our site so we have no idea what the hell you are talking about. We have anonymous team so no one by that name in our team . 
Stop ur baseless allegations. We have decided not to list in your platform

**Comment by nvisioncash** [comment]
Maybe u checked some other site lol

**Comment by tradedbytony** [comment]
I saved the previous site for posterity on Archive before it could be changed because I knew it would be. The saved version is at http://archive.is/UzaE8.

The "updated" site might be without photos but the old one had them.

**Comment by nvisioncash** [comment]
Test Test Test

**Comment by nvisioncash** [comment]
Closed test issue
