### ISSUE TITLE
Request to add OCTUS Network to your Exchange

### ISSUE THREAD

**Issue by octusnetwork** [forkdelta/tokenbase#664]
**Contract address**: 0x7e9d365c0c97fe5fcadcc1b513af974b768c5867
https://ethplorer.io/address/0x7e9d365c0c97fe5fcadcc1b513af974b768c5867#transfers=6&tab=tab-holders&pageSize=100

**Issuer's official website**: http://octus.network/
Official contract address confirmation (MUST be linked from official website): http://octus.network/#token

A link to a third-party review or discussion of the token, like an established ICO review blog:
https://bitcointalk.org/index.php?topic=2912137

**Description**:
Octus (OTC) is the first and true cryptographic project for the massive and automated distribution of cryptocurrencies and tokens of the most popular and known blockchains such as Bitcoin, Ethereum, Bitshares, NEO, NEM, Waves, among others.
Being a decentralized tool, that anyone can use it for the purpose of distributing cryptocurrencies to a list of wallets of their own choice, in an automated, controlled and secure way.

**Website**: https://octus.network
**Bitcointalk Forum**: https://bitcointalk.org/index.php?topic=2912137.0
**Twitter**: https://twitter.com/octusnetwork
**Weibo**: https://weibo.com/octus?is_hot=1

**Comment by tradedbytony** [comment]
There's already an open issue at #279.

Closing.

**Comment by octusnetwork** [comment]
OK.

**Comment by octusnetwork** [comment]
What happen with issue #279 ?

**Comment by octusnetwork** [comment]
We can give up to 75,000 tokens for the campaign
