### ISSUE TITLE
InoCoin

### ISSUE THREAD

**Issue by InoCoin** [forkdelta/tokenbase#665]
**Contract address:**

 0xc9859fccc876e6b4b3c749c5d29ea04f48acb74f

**Issuer's official website:**

 https://inocoin.eu/

**Official contract address confirmation:**

https://inocoin.eu/#about

**A link to a third-party review or discussion of the token:**

https://bitcointalk.org/index.php?topic=3160994.20

**White Papers :**

https://inocoin.eu/wp.pdf

Description:

Ino Coin – the global platform for funding and provision of know-how to young blockchain projects. The currency backed by a mix of people with perfect technical and commercial skills. People, who will share advice and provide constant direction for young teams in addition to providing funds. A unique decentralized system for joint decision making between the lead team, project representatives and all investors and owners of the currency. Sharing of knowledge, ideas and shares through InoCoin.

**Comment by InoCoin** [comment]
Hello, guys ! 

Are there any news about what are further steps?

**Comment by InoCoin** [comment]
Hello, 

@Kryptoniq and @freeatnet we are waiting from 27 days to get listed. And before 12 days we get your approval. Our all community is expecting the listing. Can you give us a bit more information, how much we need to wait and is there any way to rush the process a bit?

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on **Monday, April 30th, 2018**. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! Ino Coin has been listed: https://forkdelta.github.io/#!/trade/INO-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
