### ISSUE TITLE
Topinvestmentcoin 

### ISSUE THREAD

**Issue by Topinvestmentcoin** [forkdelta/tokenbase#667]
Contract address:0xa5db1d6f7a0d5bccc17d0bfd39d7af32d5e5edc6

Issuer's official website:https://www.topinvestmentcoin.online

Official contract address confirmation:
https://www.topinvestmentcoin.online

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3123082.0#new

WHITE PAPER:
http://www.topinvestmentcoin.online/gallery/whitepaper.pdf

Description: Topinvestmentcoin (TICO) is designed to implement an Ethereum blockchain-based token to execute a decentralized investment in a digital currency called Topinvestmentcoin. Project is a proposed system that uses the blockchain technology and leverages smart contract techniques using Ethereum’s core innovation including security and immutability. With Topinvestmentcoin you will have access to marketplace to ask&bid including the investment platform which earns you 3% interest monthly income, for every investor. It’s NOT Pyramid/HYIP, all payments are made from special fund.

**Comment by tradedbytony** [comment]
I see you're using TextNow as your free US phone number and TextNow is useless. They'll change your number in a few weeks. Also, found the photo of the CEO on a dating site, so good luck with that.

You have a single token holder. Your bitcointalk thread doesn't have enough reviews and your social media is pretty much dead at the moment.

When the pre-sale/ICO phase approaches its end and if you have a higher participation in your project, you could attempt to list again at a later date. Best of luck.

Closing.
