### ISSUE TITLE
Request for ODIN to be listed on Fork Delta

### ISSUE THREAD

**Issue by odinreport** [forkdelta/tokenbase#668]
Contract address:

**0x12fA6Cc43227aD0F1256804Dbc24480404799080**

Issuer's official website:

**https://www.odinreport.com**

Official contract address confirmation:

**https://www.odinreport.com. (Please scroll to the bottom of the homepage, where you will find a link to the contract address.)**

A link to a third-party review or discussion of the token:

**Link to our Bitcointalk ANN thread, initiated by a team member's account**: 

**https://bitcointalk.org/index.php?topic=3074703**

Description:

**"The Odin Report is a tokenized, membership only trading group. In order to receive our bi-weekly reports, members must maintain a minimum balance of 1 ODIN. Our utility token (ODIN) governs membership to the group, and the model is democratic. Membership is retained in perpetuity, and no monthly fees are charged."**

**... P.s. - thank you for your work with Fork Delta. We are encouraged by people like yourselves.**

**Comment by odinreport** [comment]
Additional information you may find helpful:

Link to Twitter: www.twitter.com/odinreport

Link to Telegram channel (news updates): www.t.me/odinreport

Link to Telegram group (general discussion, etc): www.t.me/theodinreport

... thanks again.

**Comment by odinreport** [comment]
@tradedbytony, I realize you are quite busy (evidenced by your activity, and the sheer number of open requests). In general, how long does it take to list after an issue is filed? Hope this finds you well. Thank you for your time.

**Comment by tradedbytony** [comment]
It really depends. Sometimes a week, sometimes two. Then account for another 1-2 weeks to have it listed if it the requests gets the all clear from Kryptoniq. Right now we're a bit behind because there's a lot going on behind the scenes with the change to the contract and improvements to UI and other stuff. All requests WILL be looked at though. Just gotta hang tight for a bit longer.

**Comment by odinreport** [comment]
Totally understood. Appreciate your hard work, and making it easy for us regular people to list tokens :)

**Comment by odinreport** [comment]
Hey @tradedbytony, I see the team is very busy. You said feedback can take as long as two weeks. Do you think ODIN will be approved soon (provided all the necessary details are there)? Thanks my friend. Hope you're weekend is going well.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x12fa6cc43227ad0f1256804dbc24480404799080, https://www.odinreport.com/

**Comment by odinreport** [comment]
Hey, I know you're all very busy. Just writing to ask if you have any update regarding when ODIN will be tradable. Thanks again.
