### ISSUE TITLE
FINS - FinShi Capital tokens

### ISSUE THREAD

**Issue by finshi** [forkdelta/tokenbase#669]
Contract address: https://etherscan.io/token/0x4805e471dd86dc0e3cbe44305391e37e491b579e#readContract

Issuer's official website: http://finshi.capital

Official contract address confirmation: https://twitter.com/FinshiCapital/status/977251563327639552

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=1968914 

Symbol: FINS
Full Name: FinShi Capital Tokens
Decimals: 4

Description: FinShi Capital - first cryptocurrency venture fund. The owner of the token is an investor in the Fund. The token according to the Ethereum contract is a proof of you being a shareholder in proportion to the Fund’s portfolio companies. We invest only in promising and reliable ICO projects. Also the token gives you the right to receive 80% of the profits of the Fund

**Comment by Kryptoniq** [comment]
https://icobench.com/ico/finshi-capital

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x4805e471dd86dc0e3cbe44305391e37e491b579e, http://finshi.capital/
