### ISSUE TITLE
Listing request IquiCoin

### ISSUE THREAD

**Issue by iquicoin** [forkdelta/tokenbase#675]
Contract address: 0x6c5afe79938b816a20be5e434475eecb78515260

Issuer's official website: https://iquicoin.io/

Link to confirm contract:
https://twitter.com/IquiCoin/status/973261024454471685

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3094574.msg31947323#msg31947323

Description:
addr: '0xe0c90e793a2c4eb2058dcfc54725388820115175'
decimals: 18
description: IQUICOIN The first Cryptocurrency used the blockchain in the cloud storage services.
name: IquiCoin
symbol: IQI

links:

Email: mailto:support@iquicoin.io
Telegram: https://telegram.me/iquicoin
Twitter: https://twitter.com/IquiCoin
Website: https://iquicoin.io/
Whitepaper: https://iquicoin.io/wth.pdf

**Comment by tradedbytony** [comment]
Please don't make multiple requests when there's an open issue at #507. Keep all further comments and requests at #507.

Closing this.

**Comment by iquicoin** [comment]
How to add a new requests in #507.
