### ISSUE TITLE
New Token Listing: Elemental/ELEM

### ISSUE THREAD

**Issue by ElementalCoin** [forkdelta/tokenbase#680]
Contract address: 0xaDa00d9468c54A17564E33058BDD9451f75462Ad
Symbol: ELEM
Full Name: Elemental
Decimals: 10

Issuer's official website: https://elemco.in

Official contract address confirmation:
https://elemco.in/whitepaper

A link to a third-party review or discussion of the token:
https://icoinfo.space/index.php/2018/03/24/elemental/

Description:
Elemental is the first investment platform in the cryptocurrency space built on the pillars of integrity, sustainability, and freedom. We offer our investors a zero lock-ups policy on their investments. We do not hold investor funds hostage for any period of time. Our investment platform has a seven-day buffering period in order for the platform to offer consistent, reasonable returns. We use a combination of real trading as well as trading via our proprietary bot, Genesis, in order to secure profits for our investors. Our referral program is one level deep and only offers commissions from the internal exchange as a perpetual reward. We want to prove that anonymity and cryptocurrency can live harmoniously and Elemental can serve as a space used for the betterment of our members.

Social Media:
https://Twitter.com/ElementalCoin
https://Instagram.com/elemco.in
https://www.facebook.com/Elemental-elemcoin-1814266662201185/
https://bitcointalk.org/index.php?topic=3118727.0

**Comment by ElementalCoin** [comment]
A respectful bump. Please review, admins.

**Comment by ElementalCoin** [comment]
Sorry for the illegal bump, Kryptoniq. It just seemed like we got overlooked!

**Comment by ElementalCoin** [comment]
We are now listed on DDEX!

**Comment by Kryptoniq** [comment]
What is the use case of Elemental token?

**Comment by ElementalCoin** [comment]
Elemental tokens will be used as a store of value as well as an investment vehicle for their owners. Elemental tokens can be used in investment packages, earning daily interest for their owners after a seven day holding period. They can be utilized to play lottery and other mini-games on elemco.in, the former opening on the 5th of May, 2018.  Once our mining farm is set up (estimated Q2 2018) investors will be able to use ELEM to purchase stake in the hashing power to add to their earnings from the platform.

**Comment by ElementalCoin** [comment]
Whitepaper updated ----> elemco.in/whitepaper

**Comment by btcisgod** [comment]
Question, Is this the same Elemental found on https://icoinfo.space/index.php/2018/03/24/elemental/ ?

**Comment by ElementalCoin** [comment]
Yes, it is!

**Comment by freeatnet** [comment]
Please update your request to the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
