### ISSUE TITLE
Listing request: ePRX

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#690]
Website: https://www.proxycard.io
Whitepaper: Only available through a Medium blog (https://blog.proxycard.io/whitepaper-ccbd4ac034c9O) rather than in a PDF format.
Description: An all-in-one platform for your coin, community, and more. We believe we can bring crypto to the masses without sacrificing the strength of the blockchain.

Link to confirm contract: https://www.proxycard.io (about halfway through you'll see a big "Meet ePRX" which confirms the contract).

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2206814

Etherscan: https://etherscan.io/token/0x147b51d82a6038607895e11c4191431335b257e3
Symbol: ePRX
Full Name: eProxy
Decimals: 8

**Comment by Kryptoniq** [comment]
Yep, we've got this #641.

**Comment by tradedbytony** [comment]
Sometimes I forget sometimes other people actually request tokens which don't have low volume lol Good catch :D
