### ISSUE TITLE
Listing Token - Bilibit(BLB)

### ISSUE THREAD

**Issue by Bilibit** [forkdelta/tokenbase#71]
Token: Bilibit
Symbol: BLB
Decimals: 18
Contract address: 0x9b11b1b271a224a271619f3419b1b080fdec5b4a

Bilibit (BLB) is a ERC20 Token and Philippines first decentralized community-driven crypto ecosystem intended to help people in ecommerce using fast, easy and safe BLB Token.

Etherscan:
https://etherscan.io/token/0x9b11b1b271a224a271619f3419b1b080fdec5b4a

Web page
https://www.bilibit.io

Confirming smart contract owned posted in webpage
https://www.bilibit.io

Github source code
https://github.com/Bilibit/Bilibit

Social media
https://t.me/BilibitCommunity
https://twitter.com/BilibitCoin
https://facebook.com/BilibitCommunity
https://medium.com/@Bilibitph

Bitcointalk Discussion
https://bitcointalk.org/index.php?topic=2894146.0

 Looking forward
-Dev Adriane

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/commit/cf6f3057a19ef986f917009bc611ae712c4f64a6
