### ISSUE TITLE
Add token ALTTEX Token (ALTX)

### ISSUE THREAD

**Issue by alexmazanyi** [forkdelta/tokenbase#710]
Contract address: 0xa894d71506a7b12a5c60bfde6be87bd3178c08f0

Issuer's official website: alttex.io

Official contract address confirmation: https://github.com/alttex/Smart-Contract

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2699474.0  or  https://www.reddit.com/user/ALTTEX

Description: The ALTTEX Token (ALTX) is a utility token. This means that ALTTEX application will provide users with future access to its digital products or services. ALTXs are sold during our ICO launch. After the deployment of the ALTTEX application, purchasers of ALTXs can infuse it back into the ALTTEX ecosystem. ALTX uses the DPoS consensus algorithm, and will be recirculated back into the ecosystem following the successful launch of the full-fledged ALTTEX mobile application.

**Comment by alexmazanyi** [comment]
We don't need listing our token right now. Only "Hold" mode. Can you provide it?

**Comment by alexmazanyi** [comment]
We want to start trading in May or June. Now we have a lot of work with encrease our community. And we're working above our apps. We have a lot of participants whole the world. Can we just add to your exchange and in May or June we can start to trade? Not tomorrow, not in a week. That's okay? Thanks

**Comment by alexmazanyi** [comment]
Can you reply me?

**Comment by Kryptoniq** [comment]
The contract  address you provided is for crowdsale.
And yes, we can list your token in May/June as you wish.

**Comment by alexmazanyi** [comment]
0xa894d71506a7b12a5c60bfde6be87bd3178c08f0 - our smart contract
Can you list our token (only list) in order to we and our community see our token on your exchange but no trading. We want to start trade in May or June but list - now. That's okay?

**Comment by alexmazanyi** [comment]
Hello! Can you reply me?

**Comment by freeatnet** [comment]
@alexmazanyi Unfortunately, there is no way to list the token for preview purposes only.

**Comment by alexmazanyi** [comment]
Hello! We came to your exchange
https://forkdelta.github.io/#!/trade/0xb1ed41dc1fe9b723a31137afdd1201d17917fe91-ETH
and there are orders of our token, although we have not started anything
yet! You said that we will start the listing when it will be convenient for
us. What does the name Alttex on your exchange mean? Please explain what is
happening.

2018-04-08 22:45 GMT+03:00 Arseniy Ivanov <notifications@github.com>:

**Comment by freeatnet** [comment]
@alexmazanyi Do I understand correctly that 0xb1ed41dc1fe9b723a31137afdd1201d17917fe91 is not your token's address?

**Comment by alexmazanyi** [comment]
That's okay. This is our address. I asked you about trading of our token on
your exchange? Why we are in order list if we didn't start to trade yet. I
sent you the link about that.

2018-05-13 14:05 GMT+03:00 Arseniy Ivanov <notifications@github.com>:

**Comment by freeatnet** [comment]
@alexmazanyi Users can trade any token by entering the token address without having it be approved. That is the case here. Getting included in tokenbase adds more visibility and provides the user with a safer experience.

**Comment by alexmazanyi** [comment]
So, you don't need any deposit? Or we can send you amount of ALTX and
you'll put an order so that people could buy, but not sell.

2018-05-13 16:31 GMT+03:00 Arseniy Ivanov <notifications@github.com>:
