### ISSUE TITLE
Listing Cryptomus Token

### ISSUE THREAD

**Issue by Nizzy2** [forkdelta/tokenbase#711]
Contract address: 0x4e5ccae7499c6d78f90d4b7a2081e2ea042a9965

Issuer's official website: https://www.cryptomus.com

Official contract address confirmation:  https://www.cryptomus.com/tokensale/

A link to a third-party review or discussion of the token:  https://twitter.com/Cryptomus

Description:  Cryptomus is a virtual trading platform which offers prediction market tools. We have more than 2800 followers on Twitter and 1800 users on our Telegram group. CPS Token is a utility token needed to access paid services on our Platform. 

Token symbol : CPS
Decimal : 18

**Comment by freeatnet** [comment]
Please update your request to the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
