### ISSUE TITLE
Listing request - LDC

### ISSUE THREAD

**Issue by tradedbytony** [forkdelta/tokenbase#712]
Website: https://www.leadcoin.network
Whitepaper: https://drive.google.com/file/d/1YlZhHsvHuD0K0XRDz_W1M6xdhLvSZPcx/view
Description: LeadCoin is a decentralized lead sharing network that empowers businesses to sell their unused leads and buy hot leads from other businesses. Sellers automatically share their unused leads in real-time. LeadCoin’s matching algorithm then analyzes and matches leads to buyers. Leads who didn’t match one business, are now the perfect match for another, helping businesses connect with new customers instantly.

Link to confirm contract: On https://blog.leadcoin.network/leadcoins-ldc-token-is-on-coinmarketcap.html they announced that they've been listed on CMC, including screenshots, which means the contract shown on CMC is valid.

Bitcointalk announcement: https://bitcointalk.org/index.php?topic=2728016

Etherscan: https://etherscan.io/token/0x5102791ca02fc3595398400bfe0e33d7b6c82267
Symbol: LDC
Full Name: LEADCOIN
Decimals: 18

EXTRA NOTES:
The ICO raised 50.000.000.

**Comment by freeatnet** [comment]
0x5102791ca02fc3595398400bfe0e33d7b6c82267,https://www.leadcoin.network/

**Comment by freeatnet** [comment]
@tradedbytony Thank you for your request! Your token will be live on **Tuesday, June 26th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
