### ISSUE TITLE
Please add Winding Tree token (LIF)

### ISSUE THREAD

**Issue by shalabolic** [forkdelta/tokenbase#720]
Contract address: 0xeb9951021698b42e4399f9cbb6267aa35f82d59d

Issuer's official website: https://windingtree.com/

Official contract address confirmation:

https://lif.windingtree.com/

A link to a third-party review or discussion of the token:

https://bitcoinexchangeguide.com/winding-tree-lif/

https://www.coindesk.com/ready-takeoff-lufthansa-strikes-deal-blockchain-ico-startup/

Description:

Winding Tree is a blockchain-based distribution platform for the travel industry. Today the travel industry is highly concentrated on the distribution front due to core inefficiencies of the internet. The need of a trusted party on the internet allowed intermediaries to concentrate the sector and raise the barrier of entry for new startups. In travel, consumer facing intermediaries often source their inventory from other B2B intermediaries causing double marginalization and inflating the prices.
Winding Tree is building a decentralized alternative, to the current concentrated travel distribution landscape, where anyone can access inventory directly from the suppliers. The travel industry is particularly suitable for a decentralized marketplace as the suppliers are experts in what the blockchain cannot provide: customer service, and arbitration.

**Comment by Kryptoniq** [comment]
#485
