### ISSUE TITLE
Listing of Crescent Network(CSN) token

### ISSUE THREAD

**Issue by CrescentNetwork** [forkdelta/tokenbase#73]
Hello!
We would like to apply for the listing of our **[Crescent Network](CSN)** token on the Forkdelta exchange. Below are the details of our application.

>**What is Crescent Network?**
> _Crescent Network (CSN) is the world's first multi-use Proof-of Stake token built on Ethereum platform (Incorporating ERC20 and POSToken Standard) which is backed by a physical mining facility_.
> 

### **Token Information**

Token: ERC20 Token and POSToken Standard 
Explorer: https://etherscan.io/token/0x6576963107077cce5ec879978c03ec6bb300cc89
Token Contract Address: 0x6576963107077cce5ec879978c03ec6bb300cc89
Symbol: CSN
Decimals: 8

### **Official Links**

- **Website:** https://crescenttoken.com
- **Contract address on Website:** https://crescenttoken.com/about-us/
- **Announcement:** https://bitcointalk.org/index.php?topic=2791455.0
- **Email:** admin@crescenttoken.com
- **Twitter:** https://twitter.com/CrescentToken
- **Telegram:** https://t.me/CrescentToken

Regards,
Crescent Network

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/commit/cf6f3057a19ef986f917009bc611ae712c4f64a6
