### ISSUE TITLE
Adding Rave Token to ForkDelta

### ISSUE THREAD

**Issue by IsaiahN** [forkdelta/tokenbase#74]
I am apart of a team of developers creating a new crypto e-commerce marketplace called Ravelous where people can buy and sell goods for cryptocurrency.

We are applying to have our ERC-20 token listed on Forkdelta.

Project Name: Ravelous
Token Name: RAVE

Smart Contract: 
https://etherscan.io/token/0x6a09e1b7cc5cb52ffdfc585a8df51ced7063915c

Bitcoin Talk ANN: 
https://bitcointalk.org/index.php?topic=2676153.0

Website:
http://ravelous.com
Social Media:
Twitter: https://twitter.com/ravelousmarket
Facebook: https://www.facebook.com/ravelousmarket
Reddit: https://www.reddit.com/r/ravelous/
Telegram: https://t.me/ravelous

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/commit/cf6f3057a19ef986f917009bc611ae712c4f64a6
