### ISSUE TITLE
adding LAN30 token to exchange

### ISSUE THREAD

**Issue by lanitaio** [forkdelta/tokenbase#748]
Contract address: 0xc874bc86d544b005a5d3082db8cb5adda9a82c68

[white_paper-2_eng_new.pdf](https://github.com/forkdelta/tokenbase/files/1848482/white_paper-2_eng_new.pdf)
Issuer's official website: www.lanita.io

Official contract address confirmation:
www.lanita.io
A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3122230.msg32275887#msg32275887

Description:
Lanita is ERC-20 token that has 100% exposition to the top 30 cryptocurrencies. We belive Lanita token is the best instrument for portfolio investments - with one click you purchase top 30 cryptocurrencies by market capitaization.

**Comment by Kryptoniq** [comment]
There are only 5 token holders and your bitcointalk announcement thread has no reviews /comments.
