### ISSUE TITLE
CROM

### ISSUE THREAD

**Issue by 2smpl2** [forkdelta/tokenbase#75]
1. Contract address: 0xff4385c58cc0aa2adb56e05b50fc9f7e7b213511
2. Website: https://www.cromhub.com/
3. Official page: https://etherscan.io/token/0xff4385c58cc0aa2adb56e05b50fc9f7e7b213511
4. 3rd part review https://medium.com/@CROMhub/affiliate-marketing-has-a-problem-and-blockchain-technology-can-solve-it-7b5340aecaf8

**Comment by freeatnet** [comment]
@2smpl2 I was unable to find a contract address confirmation on the website; please add one (please see ["How do I find a contract address verification?"](https://www.reddit.com/r/ForkDelta/comments/7tntnz/how_to_get_an_erc20_token_listed_on_forkdelta/) for details)

**Comment by Kryptoniq** [comment]
@2smpl2 reminder...

**Comment by JonathonDunford** [comment]
This issue will be closed per listing guidelines. No response from submitter for over 10 days.

**Comment by 2smpl2** [comment]
@freeatnet @Kryptoniq Sorry for the delay guys. I got the answer from the owners, see #6 of the FAQ: https://www.cromhub.com/faq/

@JonathonDunford Please could we have this reopened?

**Comment by tradedbytony** [comment]
A new request has been made at #497

**Comment by JonathonDunford** [comment]
Closed. Discussion moved to #497
