### ISSUE TITLE
Requesting to be Listed

### ISSUE THREAD

**Issue by pmcoinclub** [forkdelta/tokenbase#750]
Contract address:
**0xff46586fe46b814eb86e60320e1b0a29b78d4757**

Issuer's official website:
**https://pmcoin.club**

Official contract address confirmation:
**https://pmcoin.club/token/**

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3118761.0

Description:
PMCoin is a dwi-function token system based on Ethereum blockchain which is backed by decentralized strategic investment platform designed based on a unique investment model to enable all individual investor to participate in a centralized pool fund to make strategic investments in any cryptocurrency project, and to promote contribution of educational materials and learning in cryptocurreny atmosphere.

**Comment by Kryptoniq** [comment]
Hi, there are only 7 token holders ATM.
