### ISSUE TITLE
Listing request for ALL.ME token

### ISSUE THREAD

**Issue by ignatyan** [forkdelta/tokenbase#76]
Hello! We want to place our  tokens on exchange. 

Token Name: ALL.ME
Symbol: ME

1. Contract address - 0x2444973040210cccaad6010c64763d1abe06d8d0
2. Official website - https://all.me/en
3. https://etherscan.io/address/0x2444973040210cccaad6010c64763d1abe06d8d0
4. https://bitcointalk.org/index.php?topic=2657895.0

**About project:**
The social network of blockchain era, that combines the benefits of BitCoin, and gives its users an opportunity to get rewarded. 

Every Allabout.me user’s account is their ad platform, and all their followers become each user’s own advertising audience.
An ad is displayed on behalf of the user and not directly on behalf of the client, as in all the usual social networking sites.
Users get a reward up to 50% of the ad cost paid by the client per view.
Absolutely all the processes are fully automated and require no further action from the user.

Regards,
Allabout.me team

**Comment by JonathonDunford** [comment]
@ignatyan 

I don't see a place in any of those links where your contract address is verified.

**Comment by JonathonDunford** [comment]
Also, can you write up a description that is shorter? 2-3 sentences.

**Comment by JonathonDunford** [comment]
@ignatyan I see you changed the title.

Can you please answer my questions?

**Comment by Kryptoniq** [comment]
@JonathonDunford should be complete right? I found the contract address on the website's help documents.

**Comment by JonathonDunford** [comment]
@Kryptoniq What address was verified?

**Comment by Kryptoniq** [comment]
The contract address (0x2444973040210cccaad6010c64763d1abe06d8d0) is somewhere on the website.

**Comment by JonathonDunford** [comment]
If you're sure, you can mark it as complete @Kryptoniq

**Comment by Kryptoniq** [comment]
Yep,  it's on "How to find your ME tokens" document.

**Comment by Kryptoniq** [comment]
0x2444973040210cccaad6010c64763d1abe06d8d0, https://all.me/en

**Comment by freeatnet** [comment]
@ignatyan The address provided, 0x2444973040210cccaad6010c64763d1abe06d8d0, seems to be the contribution contract address, not the token contract adderss. We need the latter. Is the actual token contract address https://etherscan.io/token/0x76574c7b61b07ba14eace42e60cc73a08038da85?

**Comment by JonathonDunford** [comment]
@ignatyan 

This issue will be closed per listing guidelines.
There has been no response from submitter for over 10 days.
If you are the submitter and would like this issue reopened, comment here with the missing information.
