### ISSUE TITLE
Please, Please Fork Delta, add our Token: ITL ItalianLira

### ISSUE THREAD

**Issue by Roby1964** [forkdelta/tokenbase#77]
Hello! Fork Delta / EtherDelta we would be very pleased if you add our token on exchange.

Token Name: ITALIAN LIRA
Symbol: ITL

TOTAL COINS:
100,000,000,000

EXPLORER:
https://etherscan.io/token/0x122A86b5DFF2D085AfB49600b4cd7375D0d94A5f

CONTRACT ADDRESS:
https://etherscan.io/address/0x122A86b5DFF2D085AfB49600b4cd7375D0d94A5f

CONTRACT SOURCE CODE VERIFIED
https://etherscan.io/address/0x122A86b5DFF2D085AfB49600b4cd7375D0d94A5f#code

READ SMART CONTRACT
https://etherscan.io/address/0x122A86b5DFF2D085AfB49600b4cd7375D0d94A5f#readContract

FORUM
https://bitcoingarden.org/forum/index.php?topic=28519.0
https://bitcointalk.org/index.php?topic=2940301.0

WEBSITE:
https://www.italianlira.ws/

About project:
please read on our website:
https://www.italianlira.ws/

Thank you so much for your time
Have a nice day

Best regards
Bob

**Comment by JonathonDunford** [comment]
Contract address verified. Can you please provide a description?

**Comment by Roby1964** [comment]
ITL is a multi-wallet system integrated into debit cards, ITL is developing wireless P.O.S. terminals based on blockchain.
Further information on the website:
https://www.italianlira.ws/

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
