### ISSUE TITLE
TEAM Token listing on ForkDelta

### ISSUE THREAD

**Issue by tokenstars** [forkdelta/tokenbase#770]
Contract address: 0x1c79ab32C66aCAa1e9E81952B8AAa581B43e54E7

Issuer's official website: https://tokenstars.com/en/team

Official contract address confirmation: https://tokenstars.com/upload/files/how_to_add_TEAM_tokens.pdf

A link to a third-party review or discussion of the token: https://www.reddit.com/r/TokenStars/
https://www.youtube.com/watch?v=qSqgpHKSXUA

Description:  TokenStars - the first celebrity management platform on blockchain.
TEAM token provides unique opportunities for sports&showbiz fans to connect with their favorite celebrities and allows stars to monetize their marketing potential.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x1c79ab32C66aCAa1e9E81952B8AAa581B43e54E7, https://tokenstars.com

**Comment by aplysak** [comment]
What should be the further steps?
When the token will be listed?

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on **Monday, April 30th, 2018**. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! TEAM has been listed: https://forkdelta.github.io/#!/trade/TEAM-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
