### ISSUE TITLE
Hello. You can stop trading on your stock exchange. Our smart contract was hacked. We were hacked. Our contract is 0x329bca83b582006ca1fe2c1cf8bbd94ad0e6033a (https://forkdelta.github.io/#!/trade/0x329bca83b582006ca1fe2c1cf8bbd94ad0e6033a-ETH)

### ISSUE THREAD

**Issue by UnitLife** [forkdelta/tokenbase#790]
Contract address:

Issuer's official website:

Official contract address confirmation:

A link to a third-party review or discussion of the token:

Description:

**Comment by Kryptoniq** [comment]
Please create a proper and understandable issue.
