### ISSUE TITLE
Listing coins HOME

### ISSUE THREAD

**Issue by UnitLife** [forkdelta/tokenbase#791]
Contract address: 0x5c7c8c2c5c90b8c3e9319ab1d9bebebd280841b7

Issuer's official website: http://home-loans.io/

Official contract address confirmation: https://github.com/iumag/Home-Loans/blob/master/homeloans.sol
Link from the official website: http://home-loans.io/

A link to a third-party review or discussion of the token: 
Bitcointalk (ENG): https://bitcointalk.org/index.php?topic=2479111.0 
Bitcointalk (RUS): https://bitcointalk.org/index.php?topic=2475699.0

Description: 150 000 000 HOME

**Comment by Kryptoniq** [comment]
#792
