### ISSUE TITLE
HARDFORK PoWEth -> PoWAdv

### ISSUE THREAD

**Issue by powether** [forkdelta/tokenbase#794]
Announcement: https://bitcointalk.org/index.php?topic=2975189.msg30568161#msg30568161

Old address: https://etherscan.io/address/0x2ee6d1a3ba4e80a61bdfb48a90d40a5cef455326

New Contract address: https://etherscan.io/address/0x1a136ae98b49b92841562b6574d1f3f5b0044e4c

Issuer's official website: http://powadv.org/

Description: PoWEth Token distribution became stopped when difficulty reach an ~infinite value. PoWAdv continue the distribution and reward POWA token 1:1 for every POWE holder.

**Comment by freeatnet** [comment]
@powether Is PoWAdv run by the same team?

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
