### ISSUE TITLE
I want to contest this decision iquicoin

### ISSUE THREAD

**Issue by iquicoin** [forkdelta/tokenbase#795]
I want to contest this decision
This is my real team im sorry.

team
Luque Ruben : https://www.facebook.com/okba.cab.568

CHRIS KLOOR : https://twitter.com/chris_kloor

Logino Gupta : https://twitter.com/GuptaLogino

Christine Joy Gallego : https://twitter.com/Christi04984673

**Comment by freeatnet** [comment]
The appeal should be posted in the original request; in this case, #507.

**Comment by iquicoin** [comment]
ok thanks
