### ISSUE TITLE
LIVE token listing request.

### ISSUE THREAD

**Issue by mush33room** [forkdelta/tokenbase#796]
Contract address: 0x24a77c1f17c547105e14813e517be06b0040aa76

Issuer's official website: https://livestars.io

Official contract address confirmation: https://livestars.io/token-info You can see token contract details as an answer to the first question "What are the token details?".

A link to a third-party review or discussion of the token:
You may find legal opinion here: https://livestars.io/legal_opinion.pdf
Some reviews may be found here: 
https://icobench.com/ico/live-stars
https://cointelegraph.com/news/startup-wants-to-bring-blockchain-remake-for-webcam-sex-industry
https://www.coinspeaker.com/2018/02/07/win-win-webcam-industry-live-stars-introduce-blockchain-power/

Description:
Live Stars is creating the new generation webcam platform that implements blockchain technology. The platform has a transparent structure and it offers a multitude of advantages against the projects currently existing on the market. The main goals of our project are to create a platform with an automated system, eliminate the existing webcam industry problems, and organize the work of the Live Stars project. 

UPD: Contract address confirmation link updated due to website redesign.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x24a77c1f17c547105e14813e517be06b0040aa76, https://livestars.io/

**Comment by freeatnet** [comment]
If you're a regular of tokenbase, you may have had a moment of deja-vu with "Martins Heidenbergs". That's because his photo was misappropriated by a scam project trying to get a listing before: https://github.com/forkdelta/tokenbase/issues/284#issuecomment-369221611

**Comment by mush33room** [comment]
Hello,

Could you please provide an estimate on when token is going to be listed? We'd like to make an announcement for our community.
Thank you in advance.

**Comment by freeatnet** [comment]
Thank you for your request! The token you requested will be live on **Wednesday, June 6th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
