### ISSUE TITLE
 KMCC token listing request

### ISSUE THREAD

**Issue by dwgoforit** [forkdelta/tokenbase#797]
Contract address:0x0D6DD9f68d24EC1d5fE2174f3EC8DAB52B52BaF5

Issuer's official website:https://www.kmcc.io

Official contract address confirmation: https://www.kmcc.io/KMCC/index.html

A link to a third-party review or discussion of the token: https://www.kmcc.io/KMCC-WHITEPAPER-PR.pdf

Description: KMCC helps customers collect fiat, crypto-currencies and merchandise assets. This means that the user Provides an integrated system to manage all their property and assets without the risk of being restricted.

**Comment by Kryptoniq** [comment]
1. Provide link to a third-party review or discussion of the token
2. Your website is not yet ready. Lots of "Lorem ipsum".

**Comment by dwgoforit** [comment]
Dear ForkDelta team,
Thank you for your response.

We are aware of that we are required to respond within 10 days, 
but we need 3 more business days in order to complete this task.

KMCC very wants to register for the Fork Delta, and we will do our best to meet the standards.

**Comment by Kryptoniq** [comment]
We can come back to this issue when you fix your website.
