### ISSUE TITLE
Can i retrieve a token sending to wrong address

### ISSUE THREAD

**Issue by firdausRSP** [forkdelta/tokenbase#799]
Hello team, today i make a mistake. Recently i want to trading EVN token. I thought it was EvenCoin on ForkDelta. Ive been waiting for more than two hours but the token was not receive. Finally i realize that it was an Envion token EVN. Is there anyone can help me? sorry for my bad english. Thanks in advance.

**Comment by firdausRSP** [comment]
Hi Arseniy. Thanks for the quick respond. I try it out and will let u know.
Thank u.

**Comment by firdausRSP** [comment]
Hi Arseniy. Thanks for ur guidance. U made my day ! Just see my EVN
balance. Thanks again. Kudos !

**Comment by firdausRSP** [comment]
Hi arseniy, just want to know how can i wthdraw my EVN (EvenCoin)? I tried
but system refused it. In my opinion, ForkDelta dont have a wallet for
specified token. Is there have another way to withdraw it?

**Comment by freeatnet** [comment]
@firdausRSP ForkDelta does not host _any_ wallets on its own. Could you please get a screenshot of the error you're seeing?

**Comment by firdausRSP** [comment]
Hi arseniy. Thanks for your reply. Actually my issue is solve. Thanks again.
