### ISSUE TITLE
How long before a listing goes live?

### ISSUE THREAD

**Issue by stealthmachines** [forkdelta/tokenbase#80]
Hello,
Asked about this on Reddit so apologize if this is a redundant request, however we have many investors who are asking us questions and we just would like to know definitely if we are still going to get listed here or if we should make other plans.  And if we are to be listed still, at what time will we be listed?  We were told about a week ago that it would go live within a day and have not heard back since.  Thank you in advance for resolving this issue on behalf of Charg Coin (CHG).

**Comment by stealthmachines** [comment]
Saw that you had merged it but that it still wasn't live.  Thanks for getting us this far!!  Am I needing to do anything now on my end to make sure it goes through or is it just a waiting game at this point for the next update to populate?  Thanks very very much for your time!!

**Comment by JonathonDunford** [comment]
It's live now!
