### ISSUE TITLE
[HUSH] Coin Listing

### ISSUE THREAD

**Issue by UrgeyBergy** [forkdelta/tokenbase#803]
Please take a look at adding HUSH to ForkDelta $Hush is a private implementation of the "Zerocash" protocol forked from $Zcash. With a very strong development team, and enticing roadmap, this coin is definitely worth consideration for adding to your platform. Below is some information, feel free to reply directly to this comment if you need anything from me, don't hesitate!

Website: https://myhush.org/
Facebook: https://www.facebook.com/MyHushTeam/
Twitter: https://twitter.com/MyHushTeam
Telegram: https://t.me/MyHush
BitcoinTalk: https://bitcointalk.org/index.php?topic=1688024.0
Explorer: https://explorer.myhush.org/
Source/GitHub: https://github.com/MyHush
Wallet: https://myhush.org/#tools-section

Thank you ForkDelta!

**Comment by Kryptoniq** [comment]
Sorry, but we can only list ERC20 Tokens.
