### ISSUE TITLE
Litecoin Cash LTCH

### ISSUE THREAD

**Issue by litecoincashteam** [forkdelta/tokenbase#806]
Contract address: 0x22945dec52d5fcbf5b305e84b55d13f6b7968fb0

Issuer's official website: https://litecoin-cash.io

Official contract address confirmation: dev@litecoin-cash.io
https://etherscan.io/token/0x22945dec52d5fcbf5b305e84b55d13f6b7968fb0#readContract

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3044316.new#new

Description:
The Protection Of Privacy

**Comment by Kryptoniq** [comment]
Sorry, we have already listed an ERC20 Token "Litecoin Cash" project that started in October  2017.
BTW, there is a Litecoin hardfork called "Litecoin Cash".
I'm sorry, we can't list your token.

**Comment by litecoincashteam** [comment]
list it in on LTCH please

2018-03-27 20:48 GMT+01:00 Krypton <notifications@github.com>:

**Comment by litecoincashteam** [comment]
I changed it to LTCH

2018-03-27 20:57 GMT+01:00 Krypton <notifications@github.com>:

**Comment by litecoincashteam** [comment]
Hello admin forkdelta
I am ceo of litecoin cash and I want to add my token in your website please
so help me to do that faster ;

Website : https://litecoin-cash.io
Twitter : https://twitter.com/LtchCash
Telegram : https://t.me/joinchat/IA_rG0fLymVEUVZMPyLxTw
Whitepaper : https://litecoin-cash.io/Whitepaper.pdf

regards

2018-03-27 20:58 GMT+01:00 Litecoin Cash <litecoincashteam@gmail.com>:
