### ISSUE TITLE
Listing AmberTime Coin - AMTC

### ISSUE THREAD

**Issue by whemix** [forkdelta/tokenbase#809]
**Token Contract address:** [0x84936cf7630aa3e27dd9aff968b140d5aee49f5a](https://etherscan.io/address/0x84936cf7630aa3e27dd9aff968b140d5aee49f5a)

***Contribution Contract Address:*** [0xb53a656bd0bbde2b272aa002a2f1a8d6137fce31](https://etherscan.io/address/0xb53a656bd0bbde2b272aa002a2f1a8d6137fce31)

**Issuer's official website:** https://ambertime.org

**Official contract address confirmation:** http://ambertime.org/en/english-home#faq

**A link to a third-party review or discussion of the token:**
 - [Ethplorer](https://ethplorer.io/address/0x84936cf7630aa3e27dd9aff968b140d5aee49f5a)
- Merged Pull Request MyEtherWallet: [MyEtherWallet/ethereum-lists#546
](https://github.com/MyEtherWallet/ethereum-lists/pull/546)
- Bitcointalk thread: https://bitcointalk.org/index.php?topic=3166694
- Github: https://github.com/ambertime
- Etherscan: https://etherscan.io/address/0x84936cf7630aa3e27dd9aff968b140d5aee49f5a
- Compiled Media Coverage: https://ambertime.org/en/news*
- Blog: http://ambertime.com
- Whitepaper: http://ambertime.org/en/english-home#white-paper
- Email: info@ambertime.org
- Listed in following exchanges: [HHT.ONE](https://hht.one/index.html) and [BTCBL.COM](https://btcbl.com/index.php?s=/User/Trade/index/btype/amtc_cc)

_*Note: Majority of the press coverage and literature are in Chinese as the launch is initially aimed at China Domestic Market._

**Description:**
AmberTime is an open blockchain that allows "certified history" to be stored in it.

AmberTime blockchain application class products are open to schools of all levels,
educational and training institutions, examinations and assessment institutions,
qualification certification institutions, travel organizations, and travel product
platforms around the world.

Not only that it means the way people receive their education and the way they travel
will go through a revolutionary change, it also means people’s life-long educational
history and travel footprints will be permanently and safely stored as a very important
data capital.

**Comment by whemix** [comment]
Related Pull Request #805

**Comment by whemix** [comment]
added Github reference - https://github.com/maroonstudios/ambertokensale

**Comment by whemix** [comment]
@Kryptoniq @freeatnet for your review and comment, thank you!

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x84936cf7630aa3e27dd9aff968b140d5aee49f5a, https://ambertime.org/

**Comment by whemix** [comment]
@Kryptoniq - cool, thank you and acknowledged!

**Comment by whemix** [comment]
@freeatnet - just to highlight there was a pull request for this that was closed.  

Maybe it can be opened it again if it can facilitate easier merge / commit.

Thank you for your consideration.

Related Pull Request : https://github.com/forkdelta/tokenbase/pull/805

**Comment by whemix** [comment]
Updated link for news and media coverage

**Comment by whemix** [comment]
Updated official contract address confirmation link to http://ambertime.org/en/english-home#faq

**Comment by whemix** [comment]
@Kryptoniq @freeatnet - I recently updated the links due to minor website revamp.  Hope we can see listing soon :)

**Comment by freeatnet** [comment]
https://ambertime.org/ is "under construction".

**Comment by whemix** [comment]
@freeatnet @kryptoniq we had a major revamp in our website that required us to take town the page during the weekend as we progress our development. We encountered some glitches and took longer than expected.

The new website is now up and https://ambertime.org/ is online. 

Please let us know if there are anything else we can do to assist with the listing.

Thank you for your support this far.
