### ISSUE TITLE
Listing request of Adelphoi (ADL)

### ISSUE THREAD

**Issue by R0bini0** [forkdelta/tokenbase#811]
Hello Team!

We would love to list our Adelphoi Coin "ADL" to your Exchange.

Adelphoi coin (ADL)
ERC 20
Wallet : MEW or other ERC20 Wallets
Symbol: ADL
Max Supply: 100m
Decimals: 18

Website: www.adel.io

TWITTER: https://twitter.com/adelphoi_io

BitcoinTalk: https://bitcointalk.org/index.php?topic=2135312.0

Telegram: https://t.me/Adelphoi

Slack Public: https://adel-signup.herokuapp.com/

https://etherscan.io/address/0x660e71483785f66133548B10f6926dC332b06e61

Adel is a technology incubator for blockchain innovation. Our community collaborates on ideas, and uses the AdelWiki™ to collectively create business plans. Members vote on projects and can become profit participates when they are launched. Expertise within the community brings mentoring, learning, and employment opportunities. Successful projects are re-invested for further growth, or issued as rewards to members. Adel is blockchain agnostic...

Thanks in advance for your help!

**Comment by R0bini0** [comment]
Token address confirmation: see footer of our website: https://adel.io

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x660e71483785f66133548b10f6926dc332b06e61, https://adel.io/

**Comment by R0bini0** [comment]
Thanks so much!!

**Comment by R0bini0** [comment]
Hi, what date batch do you think ADL will be added? Thnx

**Comment by R0bini0** [comment]
?
