### ISSUE TITLE
Doicoin (DOI)

### ISSUE THREAD

**Issue by Doicoin** [forkdelta/tokenbase#816]
Contract address:
0x6b896cb1a3a3216f4056aa84051532124c65b142
Issuer's official website:
https://www.doiself.de/
Official contract address confirmation:
https://etherscan.io/verifySig/217

A link to a third-party review or discussion of the token:
https://gist.github.com/Doicoin/0a97332c5f67ae9a5a2abea99b102198

Description:
The main purpose of the DOI is to create a complex economy that generates a real increase in value through external service providers. Important here is the Win / Win / Win / Win situation between Doiself.de & its employees, the external service provider, the member and all DOI holders.

**Comment by Kryptoniq** [comment]
Please make the contract address available on the website and also, provide a valid link to a third-party review or discussion of the token.

**Comment by Doicoin** [comment]
Twitter:
https://twitter.com/Doiself1

BitcoinTalk:
https://bitcointalk.org/index.php?topic=3197703.new#new

EtherDelta:
https://etherdelta.com/#0x6b896cb1a3a3216f4056aa84051532124c65b142-ETH

Etherscan:
https://etherscan.io/token/0x6b896cb1a3a3216f4056aa84051532124c65b142

Github:
https://gist.github.com/Doicoin/0a97332c5f67ae9a5a2abea99b102198

**Comment by Kryptoniq** [comment]
Please make the contract address available on the website.

**Comment by Doicoin** [comment]
reworked Home:
https://www.doiself.de/doicoin/

Etherscan:
https://etherscan.io/token/0x6b896cb1a3a3216f4056aa84051532124c65b142

Bitcointalk:
https://bitcointalk.org/index.php?topic=3197703.new#new

Github:
https://gist.github.com/Doicoin/0a97332c5f67ae9a5a2abea99b102198

Twitter:
https://twitter.com/Doiself1

EtherDelta:
https://etherdelta.com/#0x6b896cb1a3a3216f4056aa84051532124c65b142-ETH

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
