### ISSUE TITLE
Listing request Dether - DTH

### ISSUE THREAD

**Issue by ileghlam** [forkdelta/tokenbase#819]
Hello Team,

Contract address: 0x5adc961d6ac3f7062d2ea45fefb8d8167d44b190

Bitcointalk: https://bitcointalk.org/index.php?topic=2620895.new#new
Blog: https://medium.com/@DETHER
CoinMarketCap: https://coinmarketcap.com/currencies/dether/
Email: mailto:hello@dether.io
Facebook: https://www.facebook.com/dether.io/
Reddit: https://www.reddit.com/r/Dether/
Telegram: https://t.me/joinchat/GkdUjUQ4jx_Apxmz2km4ww
Twitter: https://twitter.com/dether_io
Website: https://dether.io/
Whitepaper: https://dether.io/static/media/whitepaper.8ee59eae.pdf
YouTube: https://www.youtube.com/channel/UCXkA5w4KdpnBMeIsu62ZS8w
 Github: https://github.com/dethertech

Dether provides a P2P decentralized ether network that enables anyone one Earth to buy and sell crypto with cash whithout any bank account and spend it at physical stories.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x5adc961d6ac3f7062d2ea45fefb8d8167d44b190, https://dether.io/

**Comment by freeatnet** [comment]
Token address confirmation can be found on the website, "DTH TOKEN" section.

**Comment by freeatnet** [comment]
@ileghlam Thank you for your request! Your token will be live on **Tuesday, June 26th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
