### ISSUE TITLE
add BITCOINPURE (BTCP)

### ISSUE THREAD

**Issue by luizlopes123** [forkdelta/tokenbase#82]
https://github.com/luizlopes123
https://etherscan.io/token/0x559201fa75902cdc4055e40f0c90e3d702049987
Community-Focused ERC-20 Token for Payments
I come to present our project and ask to add our token in the etherdelta for commerce
Token ERC20 focused on community for payments
BTCP is a new ERC20 smart contract token. The Tokens will be sold to our community to be used for credit in applications that can be build on the blockchain. BTCP is a decentralized and democratic token that gives all the power to our community. This token will be free to keep, trade, use for voting and as a credit in online applications. BTCP this token since it will be a high value asset in the future.
Focus
bitcoinpure is an Ethereum-based ERC-20 Token that focuses on being a faster and cheaper currency than Bitcoin, Litecoin and other cryptocurrencies, It is the first Ethereum token intended for use as a currency and acceptance by merchants. We care about our community, and we will work hard to make bitcoinpure community the best and strongest it can be, which will eventually lead to acceptance of bitcoinpure by shop merchants as a currency. We have a clear goal in mind and a long road ahead and we will describe everything in the upcoming whitepaper and roadmap.
Why not just use Ether? Ether itself isn't meant to be used as currency, but rather to pay for smart contract execution and the Ethereum community is not trying to work with merchants in any way, resulting in almost zero acceptance of ether as an actual currency. bitcoinpure will focus on being the best coin for payments and will try to work with merchants directly to accept it as a currency. Being based on Ethereum gives us big advantages, such as lightning fast transaction speed, low transaction cost and integration with Ethereum Smart Contracts.
ENDEREÇO DO CONTRATO (S): 0x559201fa75902cdc4055e40f0c90e3d702049987
SYMBOL token: BTCP
Type: ERC20
DECIMALS: 18
Fornecimento total: 10,000,000 BTCP
http://btcpure.xyz/
https://twitter.com/btcpure
https://t.me/joinchat/GpTwZRGiIXJ_nN26KjmkuA
http://btcpure.xyz/#white-paper
http://btcpure.xyz/#roadmap
http://btcpure.xyz/#about
https://bitcointalk.org/index.php?topic=2432611
https://github.com/luizlopes123
admin@btcpure.xyz
We would extremly happy if you add us on your exchange. BTC

donation of 200,000 BTCP TO HELP THE FORKDELTA PROJECT

https://etherscan.io/tx/0x392d513494db13d936db1024fc1df3159e4cce4515b47cf7165abe339e5e8ef9

**Comment by JonathonDunford** [comment]
0x559201fa75902cdc4055e40f0c90e3d702049987 contract address verified.

Can you please provide a shorter description? 1-3 sentences.

@luizlopes123

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/pull/72
