### ISSUE TITLE
Hyperion Token Listing Request

### ISSUE THREAD

**Issue by HyperionToken** [forkdelta/tokenbase#822]
Contract address: 0x5816047DeA1872F0DbC037b7223A7ed78Ba7f2c1

Issuer's official website: https://hyperiontokens.com/

Official contract address confirmation: https://hyperiontokens.com/
Contract address is listed on the home page of our website under token specifications. 

 

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3213171.msg33397687#msg33397687

Description: 
Hyperion is a Decentralized Autonomous Organization (DAO) created and operated on the Hyperion platform by one or multiple human or autonomous agent owners or a mixture of both, which will share a common purpose to achieve specific, declared goals for the platform. Hyperion is a token that will have utility on the Hyperion platform.  This makes HYPR a utility token by default. Also, HYPR will serve as a governance token and recapitalization resource for the entire Hyperion platform. 
As a utility token, HYPR will be required for paying the fees that are accrued on the Hyperion platform. Only HYPR tokens can be used to pay these fees, and when paid the HYPR will put back into circulation. This means that there will also be an innate demand for HYPR tokens so that users can pay those fees. Hyperion as governance token, will be used by its holders to vote on project direction, and risk management of the Hyperion Platform. Hyperion will enable anyone to leverage their Ethereum assets on the Hyperion Platform.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x5816047dea1872f0dbc037b7223a7ed78ba7f2c1, https://hyperiontokens.com/

**Comment by HyperionToken** [comment]
Thank you , We are looking forward to seeing Hyperion listed on ForkDelta.

**Comment by freeatnet** [comment]
@HyperionToken The original website submitted is dead. Would you like to update the link?
