### ISSUE TITLE
ADN (ADN) Linsting

### ISSUE THREAD

**Issue by TOKTOKnet** [forkdelta/tokenbase#825]
ToktokICO is certification for token listing

Contract address: 0x6e8e46ec6635ad21be4fdf1412ac4bde8e7bf39c

Issuer's official website: https://adn-project.org/

Official contract address confirmation: https://bitcointalk.org/index.php?topic=3193462

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3193462

Description : ADN is a cryptocurrency that opens the oppotunity to mining by smartphone.
ADN is fully decentralized and open to all. Anyone can take part in the forefront and mine ADN from his smartphone.

**Comment by TOKTOKnet** [comment]
http://adn-project.org/erc20

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
