### ISSUE TITLE
add WITchain  token on forkdelta

### ISSUE THREAD

**Issue by witchaindev** [forkdelta/tokenbase#826]
Contract address: 0xe13ef257cf4d5df928ca11d230427c037666d466

Issuer's official website: http://witchain.org/

Official contract address confirmation:
http://witchain.org
https://etherscan.io/token/0xe13ef257cf4d5df928ca11d230427c037666d466

A link to a third-party review or discussion of the token:
website: http://www.witchain.org/
Telegram：https://t.me/witchain 8000
twitter: https://twitter.com/witchaindev 5000
bitcointalk: https://bitcointalk.org/index.php?topic=2848994
Email：admin@witchain.org

Description:
WITchain Makes Your Token and Manages Its Value.You Have Value Token in Decentralized Cryptocurrency Economy,We Provide Digital Token Development and Value Management Service for Individual and Enterprise.
Token economy ecosystem.
Contract address: 0xe13ef257cf4d5df928ca11d230427c037666d466
Symbol: WIT
Decimals: 6
https://etherscan.io/token/0xe13ef257cf4d5df928ca11d230427c037666d466

Thank You

WIT dev

WITchain donated 0.8ETH to support the development of FORDELTA
https://etherscan.io/tx/0x52a839640a8b34c680456e8e0264d80cc71f47f276b1cfb8e724646275fcbc85

From:0xdb232b5eada73a0cbb6971cb1464192d6afcf87e
To:0x3a2aedc3b54a99e429ae36637681d4560ce5c05b

Do you have a whitepaper?
http://witchain.org/wit/witchainEN.pdf
Do you have a third party review?
http://witchain.org/wit/pl2.jpg
http://witchain.org/index.htm
There hasn't been any activity on your Bitcointalk. What is the reason for this?
https://bitcointalk.org/index.php?topic=3073474.0

**Comment by Kryptoniq** [comment]
10k token holders.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xe13ef257cf4d5df928ca11d230427c037666d466, http://witchain.org/

**Comment by witchaindev** [comment]
THANKS

**Comment by freeatnet** [comment]
@witchain Please update your website to use HTTPS.

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on **Monday, April 30th, 2018**. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by freeatnet** [comment]
Thank you for your request! WIT has been listed: https://forkdelta.github.io/#!/trade/WIT-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.
