### ISSUE TITLE
Request listing LTCP token on Forkdelta

### ISSUE THREAD

**Issue by manou18** [forkdelta/tokenbase#827]
Contract address: 0x70e2135d1499c6b6b3e876722c3e17c129dfa8ba

Issuer's official website: https://litecoinplatineum.info/

Description:
Litecoin Platineum LTCP is a community-driven crypto ecosystem where the best of Litecoin and Ethereum meet. LTCP Team will focus his investment in pet industry like vet care , pets' purchases , services, pets' food and pets' tech.
Name : Litecoin Platineum
Symbol : LTCP
Token Decimals : 0
Total supply : 16 M

Official contract address confirmation: https://litecoinplatineum.info/smart-contract

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3219500.msg33484517#msg33484517

**Comment by Kryptoniq** [comment]
What's the use case of LTCP?

**Comment by manou18** [comment]
Pet food market was worth around US$ 89 Billion in 2016 growing at a CAGR of around 5% during 2009-2016. So our project will focus on signing contracts with great online pet's stores to make LTCP their main paid cryptocurrency, also a ℅ of our income will be used for helping abandoned pets.

**Comment by Kryptoniq** [comment]
ATM, there are only 11 token holders. Please do let us know when you are done with initial distribution.

**Comment by manou18** [comment]
Our ICO has just started we will distribute our coin when it finishes. also additional bounty token holders will be paid later on. Thanks for your question feel free to ask us extra ones if you need  more clarifications.

**Comment by manou18** [comment]
@Kryptoniq
we will distribute our tokens when the ICO finishes.

**Comment by manou18** [comment]
@kryptoniq
 information is updated, we are pleased to announce that our ico is over we started to distribute LTCP to participants.

**Comment by freeatnet** [comment]
Please update your request to the following the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
