### ISSUE TITLE
(CDM) CryptoDime - Future's Virtual Present

### ISSUE THREAD

**Issue by Cryptodime** [forkdelta/tokenbase#828]
Contract address:
https://etherscan.io/token/0x6287f59eb93c85b02b0d7ce11b5df51823275eb5

Issuer's official website:
https://www.cryptodime.io

Official contract address confirmation:
https://www.cryptodime.io/buy-cdm
(The smart contract address has been linked in the above mentioned page.)

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3103006

Description:
CryptoDime provides an opportunity for investors looking for the simplest way to get into the decentralised economy.

Facebook: https://www.facebook.com/cryptodime
Twitter: https://twitter.com/cdmtoken
Telegram: https://t.me/cdmtoken

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient information and reviews.

**Comment by Kryptoniq** [comment]
https://icobench.com/ico/cryptodime

https://icomarks.com/ico/cryptodime

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x6287f59eb93c85b02b0d7ce11b5df51823275eb5, https://www.cryptodime.io

**Comment by Cryptodime** [comment]
Thank you so much.

**Comment by Cryptodime** [comment]
How long does it take to list the token? Thanks!
