### ISSUE TITLE
Adding BITE tokens to Forkdelta

### ISSUE THREAD

**Issue by JohnJohnsson** [forkdelta/tokenbase#829]
Contract address: 0xf7Dca20054469a1d548b20859a100B9EC6ff1f61

Issuer's official website: www.bitcoineos.fun

Official contract address confirmation:

http://bitcoineos.fun/token/

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2947655.0

Description:
BitcoinEOS (BITE) is blockchain that will be launched in summer 2018. It will be based on EOS.IO software. BITE ERC20 tokens are used to distribute native blockchain tokens (BITE) before mainnet launch.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xf7dca20054469a1d548b20859a100b9ec6ff1f61, http://www.bitcoineos.fun/

**Comment by freeatnet** [comment]
@JohnJohnsson When is the mainnet launch and what happens to the ERC20 token once that happens?
