### ISSUE TITLE
Token Listing info CryptoX

### ISSUE THREAD

**Issue by Crypto-x10** [forkdelta/tokenbase#83]
0x7058f2ae7c1cfda824c39004253c27e2f6d0f1f9

www.crypto-x.io

https://crypto-x.io/shes-alive/ - To confirm token contract

http://icochecker.com/ico-past/
https://sangus.org/ico/1152

**Comment by JonathonDunford** [comment]
0x7058f2ae7c1cfda824c39004253c27e2f6d0f1f9 address verified.

Can you please add a short description of your token? 1-3 sentences.

@Crypto-x10

**Comment by Crypto-x10** [comment]
Crypto-X (CWX) is the world's first masternode 2.0 style token on
Ethereum Blockchain, HODL and earn tokens with ease. No need  for
expensive mining equipment or complicated setups for staking, you can
hodl CWX in any ERC20 wallet and receive CXR (CryptoXRewards) for
supporting the network!

On 2018-02-18 11:01, BigBrother wrote:

> 0x7058f2ae7c1cfda824c39004253c27e2f6d0f1f9 address verified. 
> 
> Can you please add a short description of your token? 1-3 sentences. 
> 
> @Crypto-x10 [1] 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/crypto-x10
[2]
https://github.com/forkdelta/tokenbase/issues/83#issuecomment-366522109
[3]

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
