### ISSUE TITLE
Adding BITE2 to Forkdelta

### ISSUE THREAD

**Issue by JohnJohnsson** [forkdelta/tokenbase#830]
Contract address: 0x1530df3e1C69501d4Ecb7E58eB045b90DE158873

Issuer's official website: www.bitcoineos.fun

Official contract address confirmation:

http://bitcoineos.fun/token/

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2947655.0

Description:
BitcoinEOS (BITE) is blockchain that will be launched in summer 2018. It will be based on EOS.IO software. BITE2 ERC20 tokens are used to distribute native blockchain tokens (BITE) before mainnet launch.

**Comment by freeatnet** [comment]
See #829.
