### ISSUE TITLE
Add JOYSO to forkdelta (JOY)

### ISSUE THREAD

**Issue by MrZeke** [forkdelta/tokenbase#833]
Contract address:   **0xDDe12a12A6f67156e0DA672be05c374e1B0a3e57**

Issuer's official website:   https://joyso.io/

Official contract address confirmation:  https://joyso.io/ .      
**_(Click on "How to display JOY in wallet?" and you will see the contact address)_**

A link to a third-party review or discussion of the token:    https://bitcointalk.org/index.php?topic=2802940.0

Description:  **JOYSO is a hybrid-decentralized exchange (HEX)**

**Comment by Kryptoniq** [comment]
https://icomarks.com/ico/joyso
https://icobench.com/ico/joyso
https://tokenmarket.net/blockchain/ethereum/assets/joyso/
https://www.icotokennews.com/icos/joyso/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xdde12a12a6f67156e0da672be05c374e1b0a3e57, https://joyso.io/

**Comment by MrZeke** [comment]
Thanks @Kryptoniq

**Comment by MrZeke** [comment]
@Kryptoniq can you give me an update on this ?  when can we expect this token will be listed ?  thanks.

**Comment by taka206** [comment]
@Kryptoniq  looking forward to your update, too. Thanks.

**Comment by jychenotcbtc** [comment]
@Kryptoniq Hello sir, how's the process going? thx

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by JYChen0129** [comment]
Please check the following informations are OK or not. Thx @freeatnet 

**Token address:**
0xDDe12a12A6f67156e0DA672be05c374e1B0a3e57


**Issuer's official website:**
https://joyso.io

**Description:** 
JOYSO features a hybrid design for token trading, combining the fast and fully featured advantages of a centralized exchange and the improved security and privacy of a decentralized exchange.

JOY is a utility token as it provides discounted transaction fees to the users. The token allows the user to access a 50% discount on transaction fees. 


**A link to the official contract address confirmation:** https://joyso.io/trade/en/markets;token=JOY


**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitsonline.com/interview-joyso-ethereum-exchange/
2.http://markets.businessinsider.com/news/stocks/world-s-first-cold-storage-exchange-coolbitx-joyso-partner-to-end-exchange-hacksdelivering-the-most-secure-mobile-cryptocurrency-exchange-1027199270
3.https://globenewswire.com/news-release/2018/06/19/1526478/0/en/World-s-First-Cold-Storage-Exchange-CoolBitX-JOYSO-Partner-to-End-Exchange-Hacks.html
4.https://www.icotokennews.com/icos/joyso/

**Comment by MrZeke** [comment]
Hello @freeatnet If you look back up this thread you can see this listing was approved back on april 9th. "We'll be listing the token in the next few days, you'll receive an update when we do."

can you please tell me if there is something more we need to do for this listing ?  

thanks in advance.
