### ISSUE TITLE
ARIN List Request

### ISSUE THREAD

**Issue by Arin12** [forkdelta/tokenbase#835]
Contract address:       
      0xca6e1c4bce9f720e15c72d81d280734086fd7bd4

Issuer's official website:    
     http://artificialintelligence.ezyro.com/?i=1 

Official contract address confirmation:   
  Confirmation link is on the site.
  http://artificialintelligence.ezyro.com/?i=1

A link to a third-party review or discussion of the token:
   https://bitcointalk.org/index.php?topic=3220742.new#new 

Description:
  A.I. helping people out on day to day basis, while utilizing the latest tools.

**Comment by Kryptoniq** [comment]
1. Using a free subdomain
2. Only 4 token holders
3. Unverified smart contract code
5. Bitcointalk thread isn't an announcement

Sorry, we can't list your token at this time.
