### ISSUE TITLE
Authoreon

### ISSUE THREAD

**Issue by authoreon** [forkdelta/tokenbase#837]
Dear Forkdelta Team

Please consider listing our token Authoreon. We raised $1.5m in our crowdsale and we will have our first product release on April 16th. Marketing will also start with that date. 

Contract address:
0x5B7093Fe2491DFB058c94BcD62A1CD4D822F884C

Issuer's official website:
https://www.authoreon.io

Official contract address confirmation:
https://www.authoreon.io/aun-token-details/

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2125495

Description:
Decentralizing Authorization, Authentication, Verification & Certification for consumers, corporations, governments & organizations

Authoreon tokens are used to access certain functionalities of the platform including registering a new asset, transferring an asset, and a variety of other authorization features. The Authoreon Token does not represent or confer any ownership right or stake, share or security or equivalent rights.

Please let us know if you have any questions. 

Thank you
Best regards
The Authoreon Team

**Comment by bobbypaintsstuf** [comment]
@freeatnet
