### ISSUE TITLE
XY Oracle (XYO) request

### ISSUE THREAD

**Issue by walerikus** [forkdelta/tokenbase#839]
Contract address: 0x55296f69f40ea6d20e478533c15a6b08b654e758

Issuer's official website: https://xyo.network

Official contract address confirmation: https://get.xyo.network

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3040825.0
https://forkdelta.github.io/#!/trade/0x55296f69f40ea6d20e478533c15a6b08b654e758-ETH

Description: The XYO Network has four primary components, Sentinels, Bridges, Archivists, and Diviners. These four components enable geo-focused, consensus-building and trustless verification of location data. This means that when you write a smart contract that specifies for an object to appear at a specific XY-coordinate, if it appears there, you will know that it was at that location with absolute certainty. This is all done without risk of spoofing the location signaling device(s) verified by thousands of Sentinels in the XY Oracle Network with the longest Proof of Origin chain (thus yielding greater confidence in the heuristics). Location data is used every day across the world. Societies and economies are becoming increasingly reliant on the certainty and security of location heuristics. Self-driving vehicles, package-delivering drones and smart cities will likely call for an increased reliance upon trustless location data. The adoption of the technologies of tomorrow centers on their ability to trust location heuristics they receive from an off-chain resource.

**Comment by Kryptoniq** [comment]
https://icobench.com/ico/xyo-network
https://icomarks.com/ico/xyo-network

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x55296f69f40ea6d20e478533c15a6b08b654e758, https://xyo.network/

**Comment by freeatnet** [comment]
Thank you for your request! The token you requested will be live on **Wednesday, June 6th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
