### ISSUE TITLE
Listing of 0xBitcoin (0xBTC)

### ISSUE THREAD

**Issue by TimeTravelersApprentice** [forkdelta/tokenbase#84]
Hello, this is a formal request to officially list 0xBTC on ForkDelta.

1. The contract address.
0xB6eD7644C69416d67B522e20bC294A9a9B405B31
2. A link to the token issuer's official website.
https://0xbitcoin.org/
3. A link to an official page confirming the contract address.
https://etherscan.io/address/0xb6ed7644c69416d67b522e20bc294a9a9b405b31
4. A link to a third-party review or discussion of the token, like an established ICO review blog.
https://www.trustnodes.com/2018/02/16/first-pow-bitcoin-like-token-launches-ethereum
https://www.reddit.com/r/ethereum/comments/7xuyuz/impressive_development_bitcoin_has_been/

Please see discussion here:
https://medium.com/@admazzola/the-case-for-the-mineable-erc20-token-78cbb4c34331
https://www.reddit.com/r/0xbitcoin/
https://www.reddit.com/r/Tokenmining/
https://github.com/0xbitcoin/0xbitcoin-miner

**Comment by JonathonDunford** [comment]
Address can be verified here: https://medium.com/@admazzola/the-case-for-the-mineable-erc20-token-78cbb4c34331

If you'd like a specific description or to add some other links, please edit your original post. Otherwise, we will get to this shortly.

**Comment by TimeTravelersApprentice** [comment]
Thank you. I added a thread in which there is heavy discussion by the Ethereum community, including Nick Johnson. 

If you view the r/tokenmining and r/0xbitcoin subreddits, you will see that the open source PoW miner is working properly. 

Thanks again for the quick response!

**Comment by TimeTravelersApprentice** [comment]
Thanks! Sounds good

**Comment by TimeTravelersApprentice** [comment]
Jonathan, can you add it as "0xBitcoin" rather than 0xBitcoin Token? The "ken" in token gets cut off and makes it look weird. If 0xBitcoin is too long, please just use 0xBTC.

Thanks!

**Comment by TimeTravelersApprentice** [comment]
Hi Jonathan,

Any word on this?

Thanks!

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/pull/72
