### ISSUE TITLE
PYX token listing request

### ISSUE THREAD

**Issue by taufik0911** [forkdelta/tokenbase#840]
Contract address: 0x6A5A304D8b0675D74665A3162353b1F5440B23d1

Issuer's official website: https://www.ipyx.io/

Official contract address confirmation: https://www.ipyx.io/#about-us

A link to a third-party review or discussion of the token:
https://www.icomarks.com/ico/priorityex
https://www.coinmarketplus.com/token/priorityex-preico/
https://www.coingecko.com/en/ico/priorityex
https://bitcoinexchangeguide.com/priorityex-pyx-ico/
https://neironix.io/ico-rating/priorityex
https://www.zloadr.com/ico/23614/priorityex-ico.html
https://icobench.com/ico/priorityex

Description: PriorityEx provides cryptocurrency trading and profit sharing opportunity for traders and investors. Aiming to become onestop service that solve the existing problems of cryptocurrency exchanges. PriorityEx puts the need of the customer first, before everything else. For far too long, exchanges have only focused on their daily turnover without any regard for the quality of customer care.

**Comment by Kryptoniq** [comment]
We only need one website URL.

**Comment by taufik0911** [comment]
Official website : https://ipyx.io

**Comment by Kryptoniq** [comment]
Can you provide a link to your bitcointalk announcement thread?
