### ISSUE TITLE
HLTC

### ISSUE THREAD

**Issue by HeavyLitecoin** [forkdelta/tokenbase#841]
Contract address:0xCF5a08AF322E52BEe93861341f7bD90eb3d65aa3

Issuer's official website:http://heavylitecoin.cf/

Official contract address confirmation:0xaCaD93Eaf7509161Fe61C2173ce143fD469e5Cf8

A link to a third-party review or discussion of the token:https://bitcointalk.org/index.php?topic=3237646

Description:

https://etherscan.io/token/0xcf5a08af322e52bee93861341f7bd90eb3d65aa3

Total Supply: | 100,000,000 HLTC
-- | --

**Comment by HeavyLitecoin** [comment]
https://etherscan.io/token/0xcf5a08af322e52bee93861341f7bd90eb3d65aa3

**Comment by Kryptoniq** [comment]
If you are really serous and you want investors to invest in HLTC, what stops your from getting a TLD?

* No description of the project on your website 
* Only 9 token holders
* Bitcointalk announcement thread has insufficient reviews

Sorry, we can't list your token at this time.

**Comment by freeatnet** [comment]
Next time this project may be reviewed: 1 month from now (May 14, 2018).

**Comment by HeavyLitecoin** [comment]
Everything fixed now

Heavylitecoin.com

ETH  CONTRACT
 

0XCF5A08AF322E52BEE93861341F7BD90EB3D65AA3

Explorer

https://etherscan.io/token/0xcf5a08af322e52bee93861341f7bd90eb3d65aa3


Bitcointalk

https://bitcointalk.org/index.php?topic=3237646

Thank you :)
