### ISSUE TITLE
Add Mithril to forkdelta (MITH)

### ISSUE THREAD

**Issue by HuangJi** [forkdelta/tokenbase#843]
Contract address: 0x3893b9422cd5d70a81edeffe3d5a1c6a978310bb

Issuer's official website: https://mith.io/

Official contract address confirmation: https://coinmarketcap.com/currencies/mithril/

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3108554.msg33342008#msg33342008
https://medium.com/mithriltoken
https://twitter.com/mithriltoken
https://www.reddit.com/r/MithrilToken/
https://www.facebook.com/MithrilToken/

Description: MITH is an ERC-20 social media token on the Ethereum Blockchain. Mithril will be integrated into new and existing social media networks to reward content creators for contributions to the network - we call this Social Mining.

**Comment by HuangJi** [comment]
**Coinmarketcap ALREADY!**

**Comment by bun919tw** [comment]
To the moon!!!

**Comment by Joshua6300018** [comment]
VERY STRONG PROJECT!!!!!

**Comment by zhouer** [comment]
Promising token, Android and iOS Apps are online already.

**Comment by KC300** [comment]
Diao

**Comment by jeremyHD** [comment]
Wonderful project! To the moon 🚀

**Comment by geniousisme** [comment]
HODL for MITH!!!

**Comment by LucienLee** [comment]
Strong Team!

**Comment by lulalachen** [comment]
worship!

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x3893b9422cd5d70a81edeffe3d5a1c6a978310bb, https://mith.io/

**Comment by freeatnet** [comment]
@HuangJi Have you tried depositing Mithrill tokens to ForkDelta?

**Comment by freeatnet** [comment]
@Kryptoniq Putting a delay on this until we have an example of a successful deposit / withdrawal. For all the noise about adding this project, there's surprising silence in getting that confirmed.
