### ISSUE TITLE
Listing Ramen Coin on ForkDelta

### ISSUE THREAD

**Issue by ramencoin** [forkdelta/tokenbase#848]
Contract address: 0x6feb3a071a2732378521c53d024b67ad068ec921

Issuer's official website: https://ramencoin.me

Official contract address confirmation: https://ramencoin.me (on front page of our official site)

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3171591.

Description: Ramen Coin is the first and only cryptocurrency design for Ramen enthusiasts. Not only do we cater to those who enjoy Ramen, we also support the anime community. Our token is very unique and our plan is to dominate the Ramen and Anime market as the official niche cryptocurrency.

Aside from being unique in that aspect, Ramen Coin also aims to fight hunger globally by using the potential value of our cryptocurrency to provide Ramen and other healthy alternatives to people around the world that suffer from starvation.

**Comment by Kryptoniq** [comment]
@ramencoin it seems this is not an ERC-20 compatible token.
