### ISSUE TITLE
Listing request: LEX Coin (LEXC)

### ISSUE THREAD

**Issue by drlecks** [forkdelta/tokenbase#849]
LEX Coin (LEXC)

Contract address:
0x0729377becbd653b9f14fbf2956cfd317bf2afdd

Issuer's official website:
http://lex.powdercode.com/

Official contract address confirmation:
http://lex.powdercode.com/ (just scrolling a bit)

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3245025

Description:
Besides all other tokens that pretend (or claim, at least) to change the world, achieve immortality, cure hunger and stop the climate change; we don't make untrustworthy promises. LEX Coin is just a simple token working on top of the Ethereum network aimed to move closer the blockchain and distributed economies to small teams.

You have a project and need an ICO? Have an unusual market idea and need a special currency? Running a web-app and need for a way to receive payments and donations? You may be looking for LEX Coin and it's upcoming environment.

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has no reviews. Please provide link to a third-party review or discussion of the token.

**Comment by drlecks** [comment]
The Bitcoin talk thread was quite new then. Now is a discussion.
https://bitcointalk.org/index.php?topic=3245025

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
