### ISSUE TITLE
Listing ORIUM TOKEN(Updated)

### ISSUE THREAD

**Issue by OriumOfficial** [forkdelta/tokenbase#850]
Contract address: 
0xd51e852630DeBC24E9e1041a03d80A0107F8Ef0C

Issuer's official website: 
https://oriumcoin.com

Official contract address confirmation: 
From official website to twitter channel:
https://twitter.com/OriumOfficial?s=07

A link to a third-party review or discussion of the token: 
https://bitcointalk.org/index.php?topic=2851374

Description:[ABOUT ORIUM]
ORIUM is a decentralized and fair Ethereum-based online mobile game peer-to-peer, without a house edge.Able to play one player against other players instead of against a
centralized game house.In order to place a bet, there must be another player willing to
place same bet on the game room.For that it is possible the player can adjust amount to bet or choose the game room suit for everyone.There can be public game room and
private game room. Private game room is design for those who want to play each other who are close friend ,relatives and family.ORIUM ecosystem mobile game is purely depand on only random number generation,allowing players with more fairness playing experiences.Protocol features of matching bet will make more happy gaming and entertaining.

**Comment by OriumOfficial** [comment]
Admin 

Please follow up ORIUM listing process.

Thanks.

**Comment by Kryptoniq** [comment]
This is a copy of Ethbet with a few tweaks. 
Orium
```ORIUM is a decentralized and fair Ethereum-based online mobile game peer-to-peer, without a house edge. Able to play one player against other players instead of against a
centralized game house. In order to place a bet, there must be another player willing to
place same bet on the game room.``` http://archive.is/0sDDE

Ethbet
```Ethbet is a decentralized, peer-to-peer, and provably-fair Ethereum-based dicing game without a mandatory house edge. Ethbet is able to offer bets without a house edge because players bet directly 
against other players instead of against a centralized house. The disadvantage of this is that in order to 
place a bet, there must be another party willing to place the same bet. For this reason it is possible that 
a player must wait for their desired bet to take place, especially if it is very large.```
https://ethbet.io/whitepaper.pdf

We have a a stance against Plagiarism and won't be able to list this token at this time. 
If you think this is an error kindly make your appeal on this same issue.
Your appeal must include strong  objections that validates your project.
