### ISSUE TITLE
Listing request: FuelCoin (FUE)

### ISSUE THREAD

**Issue by fuelcoin** [forkdelta/tokenbase#852]
FuelCoin (FUE)

Contract address: 
0xe56CBf0845F1215A1Bf41275d0c952984Ec993f1

Issuer's official website:
https://fuelcoin.io/

Official contract address confirmation:
https://fuelcoin.io/ (on footer)

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3245027.0

Description:
FuelCoin is a full cycle tool based on blockchain targeted to make the interaction between the driver and the fueling station perfect.

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient information. Please provide link to a third-party review of the token.
There are only 2 two token holders.
