### ISSUE TITLE
Listing Request : Bitrace Token (BRF)

### ISSUE THREAD

**Issue by BITRACE** [forkdelta/tokenbase#853]
**Contract address:** 
0x86616f32078cac9B70C6f1C45C28FA668D68fc2D

**Issuer's official website:** 
https://www.bitrace-token.com/

**Official contract address confirmation:** 
https://www.bitrace-token.com/token-address

**A link to a third-party review or discussion of the token:** 
https://bitcointalk.org/index.php?topic=2678267.0

**Description:**
BITRACE token is the official cryptocurrency to be used within the Formula 1 City.
The Formula 1 City  in Tunisia will be the first City that will accept all Cryptocurrencies for the purchase of products and services of the city which include 300 Villas, 600 Apartments, 3 Hotels, commercial facilities and new Formula 1 Course of 300 ha on the Beach - front land of Tunisia.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x86616f32078cac9b70c6f1c45c28fa668d68fc2d, https://www.bitrace-token.com/

**Comment by BITRACE** [comment]
Hi,
Please any update regarding Trace Token Listing.
Bitrace Email Address : info@bitracetoken.com
Regards.

**Comment by freeatnet** [comment]
@BITRACE Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases or sponsored articles do not constitute third-party review.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

Thanks!
