### ISSUE TITLE
Add DashClassic (DSC)

### ISSUE THREAD

**Issue by Dshclassic** [forkdelta/tokenbase#854]
Contract address: 0x910534d325a9766f6fca73154e259d39f1c9dae1

Issuer's official website: https://dashclassic.io/

Official contract address confirmation: 0x910534d325a9766f6fca73154e259d39f1c9dae1

A link to a third-party review or discussion of the token: 
Bitcointalk: https://bitcointalk.org/index.php?topic=3119704
Telegram: https://t.me/dshclassicgroup

Description: DashClassic is one of the tokens that uses P2P systems to transact between senders and recipients, with technologies that use smart contract ethereum to make DashClassic very fast and secure when making transactions, our team focus on creating DashClassic as a new payment method in the future, without there is a third party governing and all finances will be fully held to the user.

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
