### ISSUE TITLE
Please list Leverage Platform (LVP) on ForkDelta

### ISSUE THREAD

**Issue by LeveragePlatform** [forkdelta/tokenbase#855]
Contract address: 0x125e655ab4186a6c62f4ec6c8b7967d2e5b3d25e

Issuer's official website: https://leverageico.com

Official contract address confirmation: https://leverageico.com/#sale 

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2949207

Description: Leverage is a decentralized platform that allows people to store and invest their wealth in a decentralized cryptocurrency, and earn a substantial interest on investment. The Leverage Platform (LVP for short) features a genuine, trustworthy and traceable lending platform with complete data sharing and absolute information transparency.

**Comment by Kryptoniq** [comment]
We can continue here #346.
