### ISSUE TITLE
Listing Request :STWY Token

### ISSUE THREAD

**Issue by Storweey** [forkdelta/tokenbase#856]
Contract address:0x8a8c71f032362fca2994f75d854f911ec381ac5a
Name of Token: StorweeyToken
Symbol: STWY
Decimals : 18

Issuer's official website: www.storweey.net

Official contract address confirmation:https://twitter.com/storweey/status/981290486953644034

A link to a third-party review or discussion of the token:Bitcointalk ANN https://bitcointalk.org/index.php?topic=3190782.0

Facebook page https://www.facebook.com/Storweey
Twitter https://twitter.com/storweey
Telegram Group https://t.me/storweey
Whitepaper https://www.storweey.net/whitepaper
Email info@storweey.net
 

Description:Storweey is an online E-Commerce platform which will be built using blockchain technology. Decentralized,Secure,Peer-to-Peer transactions,supply-chain management and marketplace built by blockchain technology with the help of smart contracts.Storweey enables the crypto community to trade products and services in major Cryptocurrencies.Our mission is to disrupt the existing market for retail E-commerce by providing an innovative and highly effective Retail platform. We will provide the Online retail market with a secure, trustworthy and efficient platform, which will be beneficial for all parties –from the Manufacturers, Sellers to their clients.

**Comment by Storweey** [comment]
Currently we have 6,000 plus Token holders since we made Airdrop

**Comment by Kryptoniq** [comment]
There are only 4 token holders. Please kindly make an initial token distribution before we can consider your token for listing. Thank you.
