### ISSUE TITLE
Sun Star Token Listing

### ISSUE THREAD

**Issue by cryptoexp** [forkdelta/tokenbase#858]
Contract address: 0xb2d8dec4e0f5b2bfd508b40e8bbb8ff12503276d

Issuer's official website: https://sunstartoken.com/

Official contract address confirmation: https://ethplorer.io/address/0xb2d8dec4e0f5b2bfd508b40e8bbb8ff12503276d
https://sunstartoken.com/

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3250695

Description: Introduction of our project must incepted from Roger Ver quote that Bitcoin is the most important invention in the history of the world since the Internet’. Cryptocurrency had brought blockchain into our life. Processes of blockchain technologies discovering in new areas occurs from day to fay. Great work let us introduce you a SUNSTAR Token – universal payment unit for online blockchain games. The most famous project is CryptoKitties nowadays. In the world there is no single game currency, each game has its own. We are going to fix it. SUNSTAR Token will be used as a payment tool in various cryptogames that are now gaining strong popularity.

**Comment by Kryptoniq** [comment]
There are only 9 token holders.
Your bitcointalk announcement thread has no reviews. Kindly provide link to a third-party review or discussion of the token. Thank you.
