### ISSUE TITLE
Mooner (xMNR) Token

### ISSUE THREAD

**Issue by rv-msilva1** [forkdelta/tokenbase#859]
Contract address: 0x9ab0846fd44f467f7496bc2aa13eab5203c72a50

Issuer's official website: http://mooners.org/

Official contract address confirmation: http://mooners.org/

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3254032.0

Description: Mooners is a market analytics platform built for the masses, we aim to use machine learning to find market patterns and advise investors about possible market opportunities and market analyses with an easy to use platform

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient reviews. Please provide link a link to a third-party review or discussion of the token.
