### ISSUE TITLE
please add new token to the site : RAX Token

### ISSUE THREAD

**Issue by raxtoken** [forkdelta/tokenbase#86]
contract address : 0x468d58d6a52249844a166d0ef045dbdd7ce0c751
symbol = RAX
name = RAX Token
decimals = 18

Website 1: http://raxtoken.com/
Website 2: http://rartokens.com/

Bitcointalk link 1: https://bitcointalk.org/index.php?topic=2929027.0
Bitcointalk link 2:  https://bitcointalk.org/index.php?topic=2917280.0

**Comment by raztoken** [comment]
a pull resquest has been created:  https://github.com/forkdelta/tokenbase/pull/107

**Comment by JonathonDunford** [comment]
Discussion moved to #107
