### ISSUE TITLE
Martcoin request to be listed

### ISSUE THREAD

**Issue by adamthyer** [forkdelta/tokenbase#860]
Contract address: 0xfdcc07Ab60660de533b5Ad26e1457b565a9D59Bd

Issuer's official website: www.martcoin.io

Official contract address confirmation: https://martcoin.io/contract-address.html

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3115065.0

Description: Martcoin is a cryptocurrency for global betting. 
World Cup 2018 is coming. The betting market will be extremely boom. Martcoin help every bet on over the world become legal on the M365.bet platform.
Only 5,800,000 coins are issued, as the demand for betting increases, it will lead to the rise Martcoin prices. Making great profit for both investors and gamblers.

**Comment by Kryptoniq** [comment]
There are only 5 token holders ATM. Please do an initial distribution before we can consider your token for listing. Thank you.
