### ISSUE TITLE
ETHMONEY (EMY)

### ISSUE THREAD

**Issue by mytechtalk** [forkdelta/tokenbase#861]
Contract address:0xc0c45cbb1dce225cf620c36807a1cdecb85feda5

Issuer's official website: ETHMONEY.IO

Official contract address confirmation: https://etherscan.io/token/0xc0c45cbb1dce225cf620c36807a1cdecb85feda5

A link to a third-party review or discussion of the token: https://etherscan.io/token/0xc0c45cbb1dce225cf620c36807a1cdecb85feda5

Description:
ETHMONEY is a new blockchain platform that is designed to scale in an open,
  permission-less distributed network securely. The core feature that makes
  EMY scalable is sharding — dividing the network into several smaller
  component networks (called shards) capable of processing transactions
  in parallel

**Comment by Kryptoniq** [comment]
The website ethmoney.io is down.
There are only 3 token holders.
No link to a third-party review or discussion of the token.
