### ISSUE TITLE
Add ShiftCash (SCASH)

### ISSUE THREAD

**Issue by mastem-test** [forkdelta/tokenbase#862]
Contract address: 0xa55fc2f935e5decd52685e28c9f1e94528f86c70

Issuer's official website:https://shift.cash

Official contract address confirmation: the contract address can be seen on the official website https://shift.cash FAQ section under the question "How can I see my Tokens"

A link to a third-party review or discussion of the token:https://bitcointalk.org/index.php?topic=2592700.0

Description: The SHIFT.cash project is part of the global financial technology market. We help creditors, investors and borrowers to maximize the benefits of working with each other without geographical barriers and minimize risks of investments.

The basis of our platform is blockchain technology, collateral assets tokenization and extensive experience of our experts in the field of secured loans.

- More secure than ordinary Peer-to-Peer
- More scale than ordinary Car Title loans business

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xa55fc2f935e5decd52685e28c9f1e94528f86c70, https://shift.cash/

**Comment by mastem-test** [comment]
Thank you very much.

hope to see our token on your exchange soon.

**Comment by mastem-test** [comment]
Dear Krypton,

I will like to remind you that we are still waiting for us to be listed on
your exchange.

kindly inform us if you need more information about our project.

thank you.

regards,
Shift cash team

On Wed, Apr 25, 2018 at 5:07 AM, Felipe Gonzalas <felipegonzalas90@gmail.com

**Comment by mastem-test** [comment]
Dear ForDelta Team,

I will like to remind you that we are still waiting for us to be listed on
your exchange.

Please, kindly let us hear from you.

thank you.

regards,
Shift cash team
