### ISSUE TITLE
Add Token Request GrowGuild Token (GGCT)

### ISSUE THREAD

**Issue by GGCDMBit** [forkdelta/tokenbase#863]
Contract address: 0xf93c70f6c8106845d810d2da521fa4e20cb4c611

Issuer's official website: https://growguildcoin.com

Official contract address confirmation:

https://growguildcoin.com

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2139636.40

Description:
Grow Guild is a project to support the legalization of marijuana completely. Our aim is towards
Implementing a complete coverage solution to maintian privacy as government regulations are damaging and causing imbalance in a market that has been controlled by corruption over the last 100 years.

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
