### ISSUE TITLE
Marcelo MRL

### ISSUE THREAD

**Issue by MarceloMRL** [forkdelta/tokenbase#864]
Contract address: 0x82125AFe01819Dff1535D0D6276d57045291B6c0

Issuer's official website: https://www.marcelo-mrl.com/

Official contract address confirmation:
https://www.marcelo-mrl.com/

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3055623.msg31671878#msg31671878

Description:

---
addr: '0x82125AFe01819Dff1535D0D6276d57045291B6c0'
decimals: 18
links:
- Email: info@marcelo-mrl.com
- Telegram: https://t.me/joinchat/IGyNLA9UybLEpfDZYX5xpQ
- Twitter: https://twitter.com/Mrl_io
- Website: https://www.marcelo-mrl.com/
- Whitepaper: https://docs.wixstatic.com/ugd/3e9a6a_710135a79a5342fabf7174602ec1bf9d.pdf
description: >-
  Smart Cryptocurrency Mining Technology
  
 
name: Marcelo
symbol: MRL

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do. 0x82125AFe01819Dff1535D0D6276d57045291B6c0, https://www.marcelo-mrl.com/

**Comment by MarceloMRL** [comment]
Can you let me know when you will list MRL ? Our ICO ended and we want list our token in next 30 days.
Thanks
