### ISSUE TITLE
AUC token listing

### ISSUE THREAD

**Issue by danielduartef** [forkdelta/tokenbase#867]
Contract address: 0xc12d099be31567add4e4e4d0d45691c3f58f5663

Issuer's official website: https://auctus.org/

Official contract address confirmation: https://blog.auctus.org/presale-auc-tokens-distributed-40138f4c6801 (the token address is not visible on the website but is mentioned on the official blog, at the beginning of the above post)

A link to a third-party review or discussion of the token: 
https://hackernoon.com/real-world-applications-of-cryptocurrencies-retirement-plans-d640a2c98ec3
https://blog.icoalert.com/auctus-auc-ico-alert-report-a3fea792a2e9
https://icorating.com/ico/auctus-auc/

Description:
The Auctus Platform is a global smart contract-powered retirement and goal-based saving platform with specialized portfolio management services for traditional equity and bond investments, as well as cryptocurrency investments. The AUC token is a utility token designed to function as the platform currency and to provide a result-oriented fee structure on our decentralized marketplace.

**Comment by Kryptoniq** [comment]
https://coinmarketcap.com/currencies/auctus/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xc12d099be31567add4e4e4d0d45691c3f58f5663, https://auctus.org/

**Comment by freeatnet** [comment]
@danielduartef Thank you for your request! Your token will be live on **Tuesday, June 26th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
