### ISSUE TITLE
Add Crystal Reign Shard (CRS)

### ISSUE THREAD

**Issue by zoomington** [forkdelta/tokenbase#868]
Contract address: 0x65302D3a313CF7B0bc7badBF0b9B07a4f176ed10

Issuer's official website: http://crystalreign.io

Official contract address confirmation: On the official site, and the whitepaper: http://crystalreign.io/crwhitepaper.pdf

A link to a third-party review or discussion of the token: https://cryptobitgames.com/crystal-reign-grand-strategy-mmo-built-ethereum/

Description: CRS is the ERC20 token and ingame currency for the upcoming mmo stratergy game Crystal Reign.

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
