### ISSUE TITLE
Listing Request: GYM Rewards(GYM)

### ISSUE THREAD

**Issue by AldrichVelasco** [forkdelta/tokenbase#869]
Contract address: 0x92d3e963aa94d909869940a8d15fa16ccbc6655e

Issuer's official website: https://gymrewards.io

Official contract address confirmation: https://gymrewards.io, go to the site and scroll down a little bit and you will see the "How to add contract to myetherwallet after buying tokens."

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3053926

Description: Decentralized Proof of Exercise Blockchain with innovative mobile app that allows you to mine GYM cryptocurrency with your body.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x92d3e963aa94d909869940a8d15fa16ccbc6655e, https://gymrewards.io/

**Comment by freeatnet** [comment]
@AldrichVelasco Please provide at least 2 links to third-party reviews of the token, the project/product, or the token issuer. Reviews must have original third-party research and include review of project vision, team, milestones, or existing product.

Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO reviews, third party reporting on established company partnerships, specific comments in BitcoinTalk threads.
Note:
* We are looking for substance in reviews. BitcoinTalk announcements and ICO aggregator pages are NOT an acceptable source. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* Press releases or sponsored articles do not constitute third-party review.
* Project's social media channels (Reddit, Twitter, Facebook, Telegram and others) are not acceptable.

**Comment by GYMRewards** [comment]
Can we please reopen this one? I have responded above.

**Comment by GYMRewards** [comment]
Excellent, let me know if you need anything else.

**Comment by GYMRewards** [comment]
Hi Guys, any expected day of listing? do you list periodically or random?

**Comment by GYMRewards** [comment]
I hate to be impatient :) but last time a drop the ball and got my ticket closed for not responding. Are we close to listing?

**Comment by GYMRewards** [comment]
Hi Guys, any updates for this ticket?

**Comment by GYMRewards** [comment]
Looking forward to our listing!

**Comment by GYMRewards** [comment]
Any updates? it has been a long time in Open Status.
