### ISSUE TITLE
please add new token to the site : AVY Token

### ISSUE THREAD

**Issue by avytoken** [forkdelta/tokenbase#87]
contract address : 0x289925d08b07e73dd0dd02d1407c877942215082
symbol = AVY
name = AVY Token
decimals = 18

Website 1: http://avytoken.com/
Website 2: http://rartokens.com/

Bitcointalk link 1: https://bitcointalk.org/index.php?topic=2929066.0
Bitcointalk link 1:  https://bitcointalk.org/index.php?topic=2917280.0

**Comment by rartokens** [comment]
pull request has been created : https://github.com/forkdelta/tokenbase/pull/108

**Comment by JonathonDunford** [comment]
Discussion moved to #108
