### ISSUE TITLE
Listing Request : CloudMoolah (MOO) Token 

### ISSUE THREAD

**Issue by CloudMoolah** [forkdelta/tokenbase#871]
Token Name : CloudMoolah
Ticker: MOO	
Token type: ERC20	
ICO Token Price: 1 MOO = 0.30 USD	
Total Tokens: 300,000,000

Contract address: 0x8F207f9b97Cf0AFc292A384D6c19A2A084aCdE5e

Issuer's official website: https://www.cloudmoolah.io/

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2819734

Description: Mobile gaming Steam Store for Southeast Asia, with an inbuilt Kickstarter for game developers and virtual items marketplace.  Unlocking global game payments and distribution.

**Comment by Kryptoniq** [comment]
Please make the contract address available on your website.
