### ISSUE TITLE
KRS

### ISSUE THREAD

**Issue by adrienDH** [forkdelta/tokenbase#874]
Contract address: 0xdfb410994b66778bd6cc2c82e8ffe4f7b2870006

Issuer's official website: https://kinguin.io/

Official contract address confirmation: 

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3082466.0Would

**Comment by Kryptoniq** [comment]
1.  Provide a project description.
2. Please make the contract address available on your website.
3. Your bitcointalk announcement thread has insufficient reviews. Kindly provide link(s) to a third party review of your token.
