### ISSUE TITLE
Ethereum AI Listing

### ISSUE THREAD

**Issue by ethAITOKEN** [forkdelta/tokenbase#875]
Contract address: 0x8d659ea48305eaa375121d8dc15ecb15c2fec4c4

Issuer's official website: http://etherai.xyz

Official contract address confirmation: http://etherai.xyz (Its is written immediately below the the Token Name on the Homepage)

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3253818

Description: Ethereum AI (ETHAI) Is a decentralized Discussion Platform for Artificial Inteligence and Robotic enthsiasts which gives them the opportunity to earn for what they love.
The discussion platform gives its users the opportunity to earn while discussing and talking about what they love, Artificial Intelligence and Robotic.

**Comment by ethAITOKEN** [comment]
contract scan: http://etherscan.io/token/0x8d659ea48305eaa375121d8dc15ecb15c2fec4c4
Token Name: Ethereum AI
Token Code: ETHAI
Decimal: 18

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
