### ISSUE TITLE
Token listing

### ISSUE THREAD

**Issue by distoken** [forkdelta/tokenbase#876]
Contract address: 0xcea5be202e170dc9b63a931036718c634a9babbd

Issuer's official website: https://bitcoinnew.org/

Official contract address confirmation:  https://etherscan.io/address/0xcea5be202e170dc9b63a931036718c634a9babbd#code

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=610673.0

Description:

Bitcoin New Cryptocurrency, P2P Worldwide payments.

**Comment by Kryptoniq** [comment]
Bitcointalk link leads to a dormant  2014 thread of BitcoinNew "coin".
Website doesn't provide information about what the project is all about. Just another ERC20 token. 
Website Archive http://archive.is/qLh5v.

Sorry, we can't list your token at this time.
If you believe this decision was made in error, kindly contest the decision on this issue by providing objective facts that supports the validity of your project.
