### ISSUE TITLE
Listing of OBIZCOIN token

### ISSUE THREAD

**Issue by Obizcoin** [forkdelta/tokenbase#877]
Contract address:
0x5781B54d7C663D69e0Df47C9066f88f4995CE4BA
--

Issuer's official website: www.obizcoin.io

Official contract address confirmation:
since the ICO has end, we have removed the contract address from the official site. 

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2426724.0
https://icobench.com/ico/obizcoin/ratings
https://cryptocoin.news/icos/obizcoin-ico-review-smart-ai-powered-business-bots-running-on-the-blockchain-5458/
https://steemit.com/crypto/@dan90/obizcoin-ico-review
https://bitcoinexchangeguide.com/obizcoin/
https://iconow.net/ico-859/

Description:

OBIZCOIN is developing a Smart Business Process Automation BOT based on Artificial Intelligence and Blockchain technology. In startups and SME’s, because of limited resources, multiple job profiles are handled by those involved in the top management. They have to involve in all the processes of the organization like Sales processes, BD processes, Purchase processes, Logistics processes, HR processes, Accounts processes and so on. Handling too many things at the same time makes it difficult for them to achieve excellence in any business process. They are left with no time for evaluation or monitoring of the actual performances. Also lack of domain expertise lead them to take wrong decisions, thereby posing risk to their venture’s survival in the long run. This is where OBIZCOIN comes in picture.

Our model comes from our parent company YRC where we've been successfully implementing business process consulting services to numerous clients. What is changing is the advancement in technology. We are merging two of the most promising technologies in the world AI and Blockhain and trying to deliver our proven solutions through BOT.

**Comment by freeatnet** [comment]
https://twitter.com/Aurora_dao/status/965673219268202497 looks like it was available on IDEX at some point, but was removed later. @Obizcoin any further information on that?
