### ISSUE TITLE
please add new token to the site : RAZ Token

### ISSUE THREAD

**Issue by raztoken** [forkdelta/tokenbase#88]
contract address : 0xe99a76d5fb19bc419d72f355050045fad88e060f
symbol = RAZ
name = RAZ Token
decimals = 18

Website 1: http://raztoken.com/
Website 2: http://rartokens.com/

Bitcointalk link 1: https://bitcointalk.org/index.php?topic=2929084.0
Bitcointalk link 1:  https://bitcointalk.org/index.php?topic=2917280.0

**Comment by rartokens** [comment]
pull request has been created : https://github.com/forkdelta/tokenbase/pull/109

**Comment by JonathonDunford** [comment]
Discussion moved to #109
