### ISSUE TITLE
This is a scam token of Monetize

### ISSUE THREAD

**Issue by CryptoCutter** [forkdelta/tokenbase#880]
https://forkdelta.github.io/#!/trade/0x7e3e515adbc496d1ee05fcf64fa2a1cc58419d24-ETH  its a fake version of MNZ that a scammer has been using to sell forgery tokens, take it down.

**Comment by Kryptoniq** [comment]
Hi @CryptoCutter, at the moment, we can't stop trading of the token due to the decentralized nature of ForkDelta. We advise investors to always trade tokens officially listed on ForkDelta. Thank you.
