### ISSUE TITLE
Element (EM) listing

### ISSUE THREAD

**Issue by Miroza666** [forkdelta/tokenbase#881]
I want list Element token (EM),old Element already listed in forkdelta,you need rename him to old.

Contract address: 0xa0945daf5313e7878763598a7975e8a86c45b129

Issuer's official website: https://elementerc.tech/

Whitepaper and documentation also available on site

Official contract address confirmation :

Contract address of Element token visible on official web site,and on etherscan
Decimals :1
Total supply :100
Contract address : 0xa0945daf5313e7878763598a7975e8a86c45b129
Total tokens : 10

Link to bitcointalk topic:

https://bitcointalk.org/index.php?topic=2408354.msg24629174#msg24629174

Description:

Element created on ethereum blockchain,for trading and holding by people who use ethereum

blockchain and for they efforts.

**Comment by Kryptoniq** [comment]
#492
