### ISSUE TITLE
Rentberry [BERRY] Listing

### ISSUE THREAD

**Issue by 00johnston00** [forkdelta/tokenbase#882]
Contract address:
0x6aeb95f06cda84ca345c2de0f3b7f96923a44f4c

Issuer's official website:
https://ico.rentberry.com/

Official contract address confirmation:

https://github.com/Rentberry/BerryToken

A link to a third-party review or discussion of the token:

https://bitcointalk.org/index.php?topic=2448767.0
https://icobench.com/ico/rentberry
https://cryptorated.com/ico-reviews/rentberry/
https://icoranker.com/ico/rentberry/

Description:
Distribution occurred April 6, 2018.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x6aeb95f06cda84ca345c2de0f3b7f96923a44f4c, https://rentberry.com/

**Comment by GlobalLotteryToken** [comment]
@Kryptoniq  
Dear Kryptoniq,
Do you want to take a look at my request please?

My request  : https://github.com/forkdelta/tokenbase/issues/890

thank you for your time!

kind regards

**Comment by freeatnet** [comment]
Thank you for your request! The token you requested will be live on **Wednesday, June 6th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by GlobalLotteryToken** [comment]
The GLT GlobalLotteryToken wil be listed June 6 right?.

Thankyou.

Kind regards.

GLT-ceo

Op ma 4 jun. 2018 13:54 schreef Arseniy Ivanov <notifications@github.com>:

**Comment by freeatnet** [comment]
@GlobalLotteryToken no, this comment is on a request for Rentberry. You will receive a similar comment on your request before your token is live. Please keep the discussion for your request in your own thread.

**Comment by GlobalLotteryToken** [comment]
Dear what wat is the best to get mine live ?
Is ie all good like this ,?

Greetings.

Kind regards.

GLT-ceo

Op ma 4 jun. 2018 17:15 schreef Arseniy Ivanov <notifications@github.com>:

**Comment by GlobalLotteryToken** [comment]
Dear thankyou.

Kind regards.

GLT-ceo.

Op ma 4 jun. 2018 17:24 schreef Arseniy Ivanov <notifications@github.com>:
