### ISSUE TITLE
Please ADD Charity Token To your Tokenbase

### ISSUE THREAD

**Issue by CharityTokenOnline** [forkdelta/tokenbase#884]
Contract address: 0x0a2eaa1101BFec3844d9F79Dd4E5B2F2D5B1fD4D
Token symbol: CHT
Decimals: 4

Issuer's official website: https://charitytokenonline.com

Official contract address confirmation:
 Please scroll down to the bottom of the page to see the contract address.

A link to a third-party review or discussion of the token:
 https://bitcointalk.org/index.php?topic=3161657.0

Description: Our vision is to become the most used digital currency for donations around the World. Our hope is for everyone to give back because it teaches us to find compassion within ourselves and to stay attached to values that are linked to the common good.

**Comment by CharityTokenOnline** [comment]
Please ADD Charity Token

**Comment by CharityTokenOnline** [comment]
How long do you think it will take to add the token?

**Comment by CharityTokenOnline** [comment]
Please advise....

**Comment by Kryptoniq** [comment]
Your bitcoin announcement thread has insufficient reviews.
Do you  have a roadmap?

**Comment by CharityTokenOnline** [comment]
So the roadmap is in the ANN. It is the 3rd image I believe. You can also see it here https://bitcointalk.org/index.php?topic=3277952.0. You can also see reviews on twitter https://twitter.com/charity_token. Also telegrams https://t.me/charitytoken. Was our roadmap not clear in the ANN? 

How many reviews do we need to be “sufficient?”

Thanks Kryptoniq for your help.

**Comment by CharityTokenOnline** [comment]
![charity01 1](https://user-images.githubusercontent.com/37805287/39494078-9fde851a-4d5a-11e8-8ee9-daedc322ee3a.png)

Attached is the roadmap.

**Comment by Kryptoniq** [comment]
Please provide link to a third-party review of your token other than bitcointalk.org.

**Comment by CharityTokenOnline** [comment]
https://www.youtube.com/watch?v=qzZeR6cvlJo

https://www.youtube.com/watch?v=JGdhcuOVoG4

What else would you like to see?

**Comment by CharityTokenOnline** [comment]
What is the status update?

**Comment by CharityTokenOnline** [comment]
Is there any update?
		
		

		website: charitytokenonline.comemail: info@charitytokenonline.comtwitter: https://twitter.com/Charity_TokenTelegram: https://t.me/CharityToken 
	




On Wed, May 16, 2018 at 10:04 AM -0500, "Krypton" <notifications@github.com> wrote:












Please provide link to a third-party review of your token other than bitcointalk.org.

**Comment by freeatnet** [comment]
@CharityTokenOnline Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by freeatnet** [comment]
@CharityTokenOnline I assure you I am quite serious.

**Comment by CharityTokenOnline** [comment]
The token was submitted months ago and we have already done these things. Now you want us to resubmit the same information? Please advise..
		
		

		Get Outlook for iOS
	




On Wed, Jun 13, 2018 at 7:27 AM -0500, "Arseniy Ivanov" <notifications@github.com> wrote:












@CharityTokenOnline I assure you I am quite serious.

**Comment by freeatnet** [comment]
@CharityTokenOnline Actually, in this particular case, I'll let that one go. There is no information on the team, how exactly Charity Token will work, no information on business registration, no third-party reviews.

We will not be listing Charity Token. I wish you luck with your project.

**Comment by CharityTokenOnline** [comment]
So you read nothing in 3 month? Letting it go is fine. We forgot about your exchange weeks ago.
		
		

		Get Outlook for iOS
	




On Wed, Jun 13, 2018 at 7:36 AM -0500, "Arseniy Ivanov" <notifications@github.com> wrote:












@CharityTokenOnline Actually, in this particular case, I'll let that one go. There is no information on the team, how exactly Charity Token will work, no information on business registration, no third-party reviews.


We will not be listing Charity Token. I wish you luck with your project.

**Comment by CharityTokenOnline** [comment]
How many reviews do you need?

Try this one....

https://bitcointalk.org/index.php?topic=3277952.0

Also the roadmap is there. It’s the 3rd image. Did you fail to see it?
