### ISSUE TITLE
BBI List Request

### ISSUE THREAD

**Issue by CardeDeveloper** [forkdelta/tokenbase#885]
Contract address: 0x37d40510a2f5bc98aa7a0f7bf4b3453bcfb90ac1

Issuer's official website: https://belugapay.com/

Official contract address confirmation:
https://belugapay.com/#smartcontract-address-container

you can find the smart contract address at the end of the website in the footer.

Etherscan: https://etherscan.io/token/0x37d40510a2f5bc98aa7a0f7bf4b3453bcfb90ac1

email: support@belugapay.com

personal email: oscar@belugapay.com

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2270648.0

Description:

Beluga Pay is a mobile point of sale system that will accept crypto, credit and debit. Beluga acquired an exclusive, perpetual, global license to Espiral Technologies S.A. de C.V. and their team, to expand its payment technology to new regions. Beluga will replicate their successful model in developing countries with adequate technology (smartphones), high levels of unbanked citizens and where larger, incumbent companies have not converted merchants to modern payment methods. Micro and Small businesses transact over $6.5 trillion USD annually, yet less than 10% of these merchants accept digital payments. Beluga will deliver an innovative range of products to make merchants lives easier. Their native cryptocurrency BBI, will solve real-world merchant problems and provide unique incentives. BBI token-holders receive .5% of all transaction fees and BBI can be used as gas for near-instant merchant deposits (currently card payments can take up to 2-3 working days to process.) Each BBI token can be used as membership for 1 month of Beluga Pro which offers advanced analytics and faster settlement speed than non-BBI-Gas deposits. Loyalty points will be accrued by users of the platform and can be redeemed for travel, entertainment, goods and services.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x37d40510a2f5bc98aa7a0f7bf4b3453bcfb90ac1, https://belugapay.com/

**Comment by freeatnet** [comment]
Updated contract confirmation: https://medium.com/@BelugaPay/how-to-use-myetherwallet-add-our-bbi-custom-token-2038a36f0f02

**Comment by freeatnet** [comment]
@CardeDeveloper Thank you for your request! Your token will be live on **Tuesday, June 26th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
