### ISSUE TITLE
Iqeon/IQN token listing

### ISSUE THREAD

**Issue by HamsterofDeath** [forkdelta/tokenbase#886]
Contract address: 0x0db8d8b76bc361bacbb72e2c491e06085a97ab31

Issuer's official website: https://iqeon.io

Official contract address confirmation:
At the bottom of this page: https://iqeon.io is a list of social media links. 
One of them is this telegram chat: https://t.me/IQeonICO
The channel has a sticky message that mentions the contract address.

A link to a third-party review or discussion of the token:
https://www.icotokennews.com/icos/iqeon/
https://bitcointalk.org/index.php?topic=2479328.0

Description:
IQeon represents an infrastructure that will allow the integration of games, applications and services based on intelligent competitions between users, as well as applications and services for motivation.

IQeon is the first platform where players can earn money thanks to their intelligence and achievements. This will be realized due to the use of domestic currency in the ecosystem, which can at any time be converted to cryptocurrency – IQeon tokens issued on the basis of Ethereum blockchain.

**Comment by d-hav** [comment]
As IQN token holder and a participant of many other projects - I hope ForkDelta will list it as soon as possible.

**Comment by AlexKib** [comment]
Added to Coingecko
https://www.coingecko.com/en/coins/iqeon#panel

**Comment by TTATPuOT** [comment]
This one is going to be big with total of 5M, just needs more exposure, add it, please asap.

**Comment by Banan2255** [comment]
Cheked them out, they are at IDEX already, plus they have Delta and Blockfolio trackers on them ... Should be added to FD I think?

**Comment by edgato73** [comment]
Please add IQeon

**Comment by Onomatotato** [comment]
Please add IQN to Forkdelta, a little exposure will go a looong way. This has scope

**Comment by Lestat51** [comment]
I have read a lof white papers of dapps for the industry game and IQeon (IQN) was by far the most complete ecossystem for games. The project is very ambitious and the team is great. It would be very nice to trade IQN on Forkdelta

**Comment by AlexKib** [comment]
Added to Coinlib:
https://coinlib.io/coin/IQN/iQeon

**Comment by freeatnet** [comment]
@HamsterofDeath @AlexKib @Lestat51 Can you get IQeon to add their contract address on the website? The FAQ section would be a great place for that.

**Comment by Onomatotato** [comment]
@freeatnet They're on the case

**Comment by AlexKib** [comment]
![contract](https://user-images.githubusercontent.com/13474326/39966377-63885228-56b3-11e8-8f9e-91cd4115b4a4.jpg)
They added it

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x0db8d8b76bc361bacbb72e2c491e06085a97ab31, https://iqeon.io/

**Comment by freeatnet** [comment]
@HamsterofDeath Thank you for your request! Your token will be live on **Tuesday, June 26th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
