### ISSUE TITLE
PetsCoin (P3T)

### ISSUE THREAD

**Issue by phusphus435** [forkdelta/tokenbase#888]
Contract address: 0x1266e24384701b094767d635a81a1001a3e54c36

Issuer's official website: https://petscoin.online/

Official contract address confirmation: https://petscoin.online/

A link to a third-party review or discussion of the token: https://twitter.com/CoinPets 
http://t.me/pets_coin

Description:
PETSCOIN AN ETHEREUM BLOCKCHAIN BASED TOKEN SUPPORTING. As an ERC-20 token, Pets Coin utilizes the full power of the Ethereum Blockchain for fast Pets-to-Pets transactions.

**Comment by phusphus435** [comment]
Hello Team what happen why my coin not yet response i have more then 4K token holder i have great social community but my coin still here not seen please update my record thank you.

**Comment by phusphus435** [comment]
Hello Where are you team ?? why not response my token?

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by jablud** [comment]
mantap gan
