### ISSUE TITLE
Adding empowr (EMPR)

### ISSUE THREAD

**Issue by empowrofficial** [forkdelta/tokenbase#889]
**Contract address:** https://etherscan.io/address/0xe7d7b37e72510309db27c460378f957b1b04bd5d

**Issuer's official website:** www.empowr.com

**Official contract address confirmation:** http://blogs.empowr.com/p?6tx59-preparing-for-the-empowr-coin (Smart contract is located at the top of this recent blog post announcement)

**A link to a third-party review or discussion of the token:** https://bitcointalk.org/index.php?topic=3170283.new#new

**Description:** 

BACKGROUND ON PROJECT:
--------------------------------- 
+ empowr is a collaboration between technologists and top university professors from Berkeley and M.I.T. that have been quietly developing a democratic social network
+ We’re uniquely enabling the “sharing of everything” IE: Not sharing your car or spare bedroom but millions of other products that go underutilized
+ empowr’s many patented inventions include virtual currency, transactions over mobile devices, third-party apps in social networks and transactions within apps
+ The product (http://www.empowr.com/) is in open alpha with 500,000 active alpha test users already conducting millions of dollars in transactions monthly
 
 
QUICK LINKS:
------------------------------ 
1) Whitepaper and business summary (PDF): https://rebrand.ly/whitepaper  
2) Concept (video): https://rebrand.ly/EFF   
3) Business model (video): https://rebrand.ly/bizmodel  
4) Innovations in creating & retaining demand for virtual currency (video): https://rebrand.ly/cryptovalue  
5) Management & Advisors: https://rebrand.ly/advisors 
6) Project history (video): https://rebrand.ly/emphistory 
7) empowr and the biggest scam of all (blog): https://rebrand.ly/blogpost 
8) Why empowr was built (book): https://rebrand.ly/empbook

**Comment by empowrofficial** [comment]
@freeatnet We have a launch event planned for this Sunday, April 15th and are hoping to have our coin live on Fork Delta by then. Is there a way for us to expedite this process? Thank you for your help!

**Comment by freeatnet** [comment]
@empowrofficial that's a question for @Kryptoniq :)

**Comment by empowrofficial** [comment]
@Kryptoniq We have a launch event planned for this Sunday, April 15th and are hoping to have our coin live on Fork Delta by then. Is there a way for us to expedite this process? Thank you for your help!

**Comment by empowrofficial** [comment]
@Kryptoniq I can see you have a lot of coins being requested to be listed, so I understand how busy you are. 

We have an established community with 800,000 users and 6.1 million visits per month. We're doing a very large airdrop on Sunday, April 15th (see article below) and the time is running tight for us to decide which exchange to direct our users to go to. We'd prefer it be your exchange, but we need at least a few days to get setup prior to Sunday so time is running out for us.

Please let us know what we can do to expedite this process, including making a payment and we will be happy to follow through. Thank you!

For reference regarding the airdrop: https://www.crowdfundinsider.com/2018/03/130610-free-ico-social-media-site-empowr-says-500-million-coins-to-be-airdropped-before-april-15th/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xe7d7b37e72510309db27c460378f957b1b04bd5d, http://www.empowr.com/

**Comment by empowrofficial** [comment]
@Kryptoniq Any update on this? You had said a few days until we would be listed and it's been a week.

We're trying to plan a launch event for our 800,000 users so that they know to move their trading over to Fork Delta from our current exchange, but until we are actually on the exchange it makes it difficult to do that.

Your help and expediency would be greatly appreciated. Thank you!

**Comment by empowrofficial** [comment]
@freeatnet @Kryptoniq Just wanted to follow up again as we're trying to plan a launch event around our coin being added to the exchange, but it's been nearly 3 weeks since we've been approved and still haven't had the coin added. Any help you can provide would be extremely appreciated. Thank you!

**Comment by empowrofficial** [comment]
@freeatnet @Kryptoniq Any update on being added? If you could please do so, we would greatly appreciate it.

**Comment by empowrofficial** [comment]
@freeatnet We already have tens of thousands of dollars worth of trading per day on Token.Store (https://www.coingecko.com/en/price_charts/empowr-coin/usd) and expect this amount to go above $100k per day once we get the approval from you. Your help in getting us listed would be appreciated.

**Comment by empowrofficial** [comment]
@freeatnet @Kryptoniq Any update on being added? 

We see you adding coins every day that have little volume and no product - whereas we have a fully functioning product with 800K users and $100K in trading volume per day.

What more do you need from us to get us listed?
