### ISSUE TITLE
Seeking Official Listing For Alpha

### ISSUE THREAD

**Issue by crypt04dvisor** [forkdelta/tokenbase#89]
Token Name: Alpha
Ticker: A
Contract Address: 0xFFc63b9146967A1ba33066fB057EE3722221aCf0
Decimals: 18
Website: [https://Alphatoken.net](https://alphatoken.net)
Link to Contract Address page: [https://alphatoken.net/token-information](https://alphatoken.net/token-information)
Etherscan token page:[https://etherscan.io/token/0xffc63b9146967a1ba33066fb057ee3722221acf0?a=0x86d7ac5d0b2063e7ba618cfa6b1f3e3e3145be18](https://etherscan.io/token/0xffc63b9146967a1ba33066fb057ee3722221acf0?a=0x86d7ac5d0b2063e7ba618cfa6b1f3e3e3145be18)
Twitter: [https://twitter.com/Alpha_Token](https://twitter.com/Alpha_Token)
Telegram: [https://t.me/Alpha_Token_Official_News](https://t.me/Alpha_Token_Official_News)
Bitcointalk: [https://bitcointalk.org/index.php?topic=2813619.msg28791230#msg28791230](https://bitcointalk.org/index.php?topic=2813619.msg28791230#msg28791230)
Coincodex: [https://coincodex.com/ico/alpha/](https://coincodex.com/ico/alpha/)

Thanks for your consideration.

**Comment by JonathonDunford** [comment]
@crypt04dvisor 

Contract address verified: 0xffc63b9146967a1ba33066fb057ee3722221acf0

Can you please provide a short description of your token? 1-3 sentences.

**Comment by crypt04dvisor** [comment]
Using the powerful Ethereum Network, Alpha Investing is offering a unique suite of products and services for navigating the Crypto-Currency Markets. From their Decentralized Investor Marketplace, to their Crypto Coin Fund(Named Coinbag), Alpha is your best choice for investing in the future of crypto.

**Comment by crypt04dvisor** [comment]
If you need anything else just let me know.

**Comment by crypt04dvisor** [comment]
I sent it on Github but here it is again for you.Using the powerful
Ethereum Network, Alpha Investing is offering a unique suite of products
and services for navigating the Crypto-Currency Markets. From their
Decentralized Investor Marketplace, to their Crypto Coin Fund(Named
Coinbag), Alpha is your best choice for investing in the future of crypto.

**Comment by crypt04dvisor** [comment]
@JonathonDunford

Is there a further process to get into the DEX? or is it now just a matter of time?

My apologies if we seem impatient but the community is asking a lot of questions and I would like to inform them accurately

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183

**Comment by crypt04dvisor** [comment]
Thanks! We are offering anyone who buys from our token sale the option to
contribute any % amount of their contribution to Forkdelta. We truly
appreciate the project and look forward to it's success. If we cannot get
ETH for you, we will donate some of our own tokens to the donation wallet.

Best Regards,

-Drew

-Alpha Investing Team-
