### ISSUE TITLE
Listing request to start project.

### ISSUE THREAD

**Issue by GlobalLotteryToken** [forkdelta/tokenbase#890]
Contract address:0x9B545759939D497cf8A61635aC82067cEc329Ed6

Issuer's official website:https://www.ethereumlotterytoken.com/

Official contract address confirmation:0x28a0c8c9c72ac2146a813e6a5afc224285ce5f274351ff2b0bcc5a7b73f52a7a

A link to a third-party review or discussion of the token:
https://twitter.com/GLT_Team , https://bitcointalk.org/index.php?topic=3310769.msg34565173#msg34565173 , https://www.facebook.com/GlobalLotteryToken/,https://twitter.com/GLT_Bounty

Description: Providing an Global Lottery for the Rich and for the Poor.
Secured on the ethereum protocol.
Long term project.
![35 35globallotterytoken](https://user-images.githubusercontent.com/38164567/38704519-e55b6b52-3ea6-11e8-94ce-6b9984aec817.jpg)
![c973f277-0315-4222-87e9-3d46a24ab5e8](https://user-images.githubusercontent.com/38164567/38704524-e897296e-3ea6-11e8-9a53-6baefaa6f0cf.png)
[GlobalLotteryToken.pdf](https://github.com/forkdelta/tokenbase/files/1905036/GlobalLotteryToken.pdf)

**Comment by freeatnet** [comment]
Please amend your request as required. Specifically, your request is missing:
1. **A link to the official contract address confirmation:** Contract address confirmation MUST be linked from the official website and MUST be visible publicly. It CANNOT be an Etherscan.io link. If the confirmation is not visible immediately, include an explanation of how to find it.
2. **At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:** Links should be of at least two disctinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments from high ranked users in BitcoinTalk.
Note:
* We are looking for substance in reviews. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels do not count as third-party discussion).
