### ISSUE TITLE
List token IVE

### ISSUE THREAD

**Issue by inversioncoin** [forkdelta/tokenbase#893]
Contract address: 0x3158b698A83c03CB5b1395068d431e37063c1d2E

Issuer's official website: https://inversioncoin.online/

Official contract address confirmation: https://inversioncoin.online/

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3269627.0

Description:  InversionCoin is a community to talk about different forms of online investment. The community has its own cryptocurrency called IVE.

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
