### ISSUE TITLE
Euphoria token listing.

### ISSUE THREAD

**Issue by EuphoriaStore** [forkdelta/tokenbase#895]
Hello, below you can find the required information needed for listing Euphoria on ForkDelta

Contract address:
0x875089A734213cA39f0d93c2BbB8209827ec5e9f

Token Symbol: EPH

Decimals: 8

Issuer's official website: https://www.euphoriastore.io

Official contract address confirmation: https://www.euphoriastore.io

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3856889.msg37423086#msg37423086

Whitepaper: https://docs.wixstatic.com/ugd/4968ce_c1eccf54bb1b4686815f5d29ba3770de.pdf

Description: Euphoria is a trading platform that allows to put up for sale products owned by users, create your own online store and make payments using cryptocurrencies.

Twitter: https://twitter.com/EuphoriaEPH
Facebook: https://www.facebook.com/Euphoria-426154047822688/
Telegram: https://t.me/joinchat/HUrTahHCG0aYDaPfMxZ01w

**Comment by akshitbhandari** [comment]
Very great project...!!!

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
