### ISSUE TITLE
Lisitng- Privelege Coin(XPV)

### ISSUE THREAD

**Issue by privelegemonarchy** [forkdelta/tokenbase#898]
Contract address:
0x8CCeE73d552c87c36432d3B222098BB58B0f7bFd

Issuer's official website:
https://kingdomofprivelege.com
Official contract address confirmation:
0x8CCeE73d552c87c36432d3B222098BB58B0f7bFd-
https://etherscan.io/address/0x8ccee73d552c87c36432d3b222098bb58b0f7bfd
It's on the home page:https://kingdomofprivelege.com

A link to a third-party review or discussion of the token:
https://www.icochart.net/tokensale/privelege-coin
https://icomarks.com/ico/privelege-coin
https://bitcointalk.org/index.php?topic=2848863.0
https://coinclarity.com/ico-events/privelege-coin/
https://cryptocurrencytalk.com/bitcoin/annico-kingdom-of-privelege-supported-by-all-wallets-and-applications-related-to-this-popular-cryptocurrency-r204/
https://bitcointalk.org/index.php?topic=3313079.0;all

Description:
Name: Privelege Coin
Token symbol: XPV
Token ICO public sales: 2,5 billion tokens available
ICO ends on 10 April
Minimum purchase: 99 USD
Join sale:https://kingdomofprivelege.com
 - Token price: 1 XPV = 0.25 USD
Blockchain: Ethereum
Country: USA
Accepted currencies: ETH, USD, BTC
Whitepaper:https://kingdomofprivelege.com/wp-content/uploads/2018/01/WhitePapers_ver_10.pdf

#Description
Privelege Coin is not only a cryptocurrency is also the official means of payment in the Kingdom of Privelege with which you can pay for services and goods from our citizens – from Medical consultations to cloths.
Privelege Coin primarily acts as a member share in the micronation, which allows the owners of the largest number of the cryptocurrency to sit on the advisory board and thereby guide the development of the micronation.
In the future after raising money from Privelege Coin cryptocurrency, Privelege is planning to buy its own Island to create a Tax-Free Haven.

Social links:
Facebook: https://www.facebook.com/privelegemonarchy/
Twitter: https://twitter.com/XPVMonarchy
Telegram:https://t.me/XPVmonarchy
Instagram:https://www.instagram.com/kingdom.of.privelege/

What are the funds raised going to be used for?
Project development and expansion (70%), with 30% around retaining a law firm, marketing, and non-development related expenses

Why are you doing ICO instead of selling your tokens directly?
An ICO provides us with viable runway to develop a successful business while keeping the project community backed.

What is the token role in your project?
The token is very important in our project. Our Idea and goal are to make a micro-state Tax-Heaven. On our island, the official payment method will be Privelege Coin.  Our goal is to buy an island and then to create a tourist sports resort and a place that is ecologically friendly, but this is not all - the overriding task is to set up on this island a sovereign micronation, an oasis of normality and tranquility for all of you.
Of course, there will be only one currency on the island - Privelege Coin - thanks to that the treatment we will be able to count on its steady growth as it will be based on something existing. Want to spend a vacation with your family on a tropical island? Token is built on Ethereum Blockchain which guarantees the stability and guarantees access to the latest development opportunities

Like every cryptocurrency, We want to earn money during our ICO sale. After ICO I want to make an announcement about how the ICO went; on what cryptocurrency markets we will be. In secret Privelege Coin will be on 4 or 5 exchanges ( depends if polish exchange will agree).Entry into selected crypto exchanges will take place in April So first ways to make money are ICO and markets. Secondly, our Island will be a Tax-Free heaven, so ON THE ISLAND:
For companies operating on the Privelege island taxes will be minimal and their settlement will take place in Privelege Coin - why? That our cryptocurrency would be in the constant rotation and hence its value would grow.
Of course, we can opt out of taxes and set the initial 'one-time registration fee', but from the economic side, it will not make a difference (because the fee is based on forecasts). Co-creating the country, I have the convenience of determining the amount of taxes and their rules so that they are beneficial for everyone.

Do you have hard cap and soft cap?
The minimum amount that allows us to meet the assumptions is 2500 BTC, the upper limit is 10,000 BTC -
SMALL SUMMING - If we fail to collect enough, we will vote  (every Owner of Privelege Coin)  - to buy a tiny island or land in the Dominican Republic?There will be proposals related to tourism and  Privelege autonomy - of course. Whatever the choice, the concept based on payments only and remains unchanged. 
LARGE TOTAL - If we could get a surplus above the assumed maximum, these funds will be spent on developing the island’s infrastructure. 

How many tokens do you plan to create? And how many from them will you sell during ICO?
The tokens are already created.The sale will show us the level of interest of the Privelege Coin, will determine which island we can buy and will allow you to calculate the maximum annual issue - if you exceed the 50-year surplus, Privelege Coin will be burned down and its value will increase. Currently, the total number of coins created is valued at 3 billion and the price of a single coin is 25 cents. For sale is 2,5 billion Privelege Coins.

What will happen if you will raise less money than you expect?
If we fail to collect enough, we will vote  (every Owner of Privelege Coin)  - to buy a tiny island or land in the Dominican Republic?  There will be proposals related to tourism and  Privelege autonomy - of course  Whatever the choice, the concept based on payments only and remains unchanged. 

Why do you think the token price will raise?
Yes, our price will raise because, 
The pre-sale will show us the level of interest of the Privelege Coin, will determine which island we can buy and will allow you to calculate the maximum annual issue - if you exceed the 50-year surplus, Privelege Coin will be burned down and its value will increase. 
TAXES AND THEIR LACK
ON THE ISLAND:
For companies operating on the island of Kingdom, taxes will be minimal and their settlement will take place Privelege Coin - why? That our cryptocurrency would be in constant rotation and hence its value would grow.
Of course, we can opt out of taxes and set the initial 'one-time registration fee', but from the economic side, it will not make a difference (because the fee is based on forecasts). Co-creating the country, I have the convenience of determining the amount of taxes and their rules so that they are beneficial for everyone.

When will your token be on any of the exchanges?
 I have been in contact with several cryptocurrency exchanges for some time.
12.04 that's  two days after the end of ICO a conference will take place, in which we will discuss how the ICO has done, on what stocks we will be, what island we will buy. 
Our cryptocurrency will enter the cryptocurrencies exchanges at the end of April and the beginning of May

When will the tokens be tradable?
After ICO

**Comment by privelegemonarchy** [comment]
When will you review our project?

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
