### ISSUE TITLE
Orion Token ORN -  listing

### ISSUE THREAD

**Issue by Habibi10** [forkdelta/tokenbase#899]
Contract address: 0xa024010430aa9d46537a4a574a88ea99ab87d5d8

Issuer's official website: www.oriontoken.com

Official contract address confirmation: www.oriontoken.com
 **Scroll down to "ICO structure"**

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3172415.msg32822156#msg32822156

Description:
Orion Project can be imagined as: „NO FEE Amazon including ORN and other cryptocurrency, exchange and lending“
![image](https://user-images.githubusercontent.com/35846492/38495777-26a96aea-3bfb-11e8-9843-99972085ab5e.png)

Orion project is creating passive income & solving trading difficulties for ordinary people with unique concept called "Circle of Prosperity"

It can be used as a cryptocurrency that stores a wealth of investors in a decentralized platform or traded for goods and services through merchant program.

Orion token is a new cryptocurrency that provides investors with a platform where they can earn money by leveraging these advantages in the cryptocurrency industry. Orion token has developed a trading AI that can execute volatility and arbitrage transactions at high speed. This allows it to monitor different exchanges continuously looking for profitable price differences. Once they are identified, they are assessed to determine whether they meet the risk threshold and then the trade is executed instantaneously. Guaranteed 0.6% Daily interest, Averaging 1%-3.5% Daily

The other feature of the platform is program "Barter & Merchant"

Orion Barter includes support services for its end-users to trade their unwanted or surplus products and services with each other in ORN with Orion Barter — a free bartering service that supports cryptocurrency and provides a bartering service for global community. Orion Barter will provide escrow service until the buyer receives and confirms their goods or services are in order.[/left] Merchants! Yes you! you can attract new customers with the groundbreaking marketing platform that is setting a new standard for merchant support Millions of new shoppers will be looking for merchants just like you to purchase your valuable products and services with Orion Token Attract new customers that may not even know you exist

This way we have enabled unique strategy to increase and stabilize the value of ORN and From your daily interest profit you are able to REINVEST 30% SHOP 30% CASHOUT 40%

Prosperous Community

Orion brings cryptocurrency to life in communities with Lending, Barter and Merchant platform

Imagine a trust fund that ensures your budgetary needs through daily interest so you, your family or organization can do what it does best ... serve the members and beneficiaries of the community without thinking about funding anymore. Orion provides a very unique opportunity for any community or individual to create a lifetime funding source from investors that keep lending and spending month after month. They never stop and neither will the funding for your precious projects as we have daily trading profits delivered to you through interest. Every visit to a restaurant, store, salon or dry cleaners could put more money in your pocket as the value of ORN will increase. More barter & merchants, More ORN exchange, More prosperity for all.

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
