### ISSUE TITLE
Add GlowEther (GTH) to forkdelta 

### ISSUE THREAD

**Issue by gunawangne** [forkdelta/tokenbase#904]
Contract address: 0xb8523ebe9426485e5d4b9ae64c541080390d7c40

Issuer's official website: https://glowether.com

Official contract address confirmation: https://glowether.com/#about

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3167429

Description: Building Community and Education in a Sustainable Way to Improve People's Live

**Comment by Kryptoniq** [comment]
1. Your website is an ICO only website
2. Your whitepaper is lengthy but it doesn't describe your.
Sorry, we won't be listing your token at this time.
Thank you.
