### ISSUE TITLE
NeckCoin, Token listing request.

### ISSUE THREAD

**Issue by NeckCoin** [forkdelta/tokenbase#905]
**Token address:**
0xc67e01f0b416b884a2896fae3401e86d605ba47e

**Issuer's official website:**
http://neckcoinforum.com

**Description:** 
We are a social network that rewards users for hitting milestones.
Well sell advertising space on the network and only accept Neck Coin as payment.

**A link to the official contract address confirmation:** 
http://neckcoinico.com

**At least 2 links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

1. https://bitcointalk.org/index.php?topic=3089365
2. https://cryptonext.com/ico/neck-coin

**Comment by NeckCoin** [comment]
I know how busy you guys are...and I am not trying to rush things but is there an ETA I can give to our community for listing please?
Thanks in advance.

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by NeckCoin** [comment]
Done

**Comment by freeatnet** [comment]
@NeckCoin I couldn't find any substantial review of your project in the third-party links you provided. Reviews must include review of project vision, team, milestones, or existing product.

**Comment by NeckCoin** [comment]
Ok well our main social network platform launches on the 1st July so hopefully we can get some reviews on our fully up and running product.

**Comment by NeckCoin** [comment]
FYI our social network platform is now live https://necknetwork.com/ users can earn and spend NECK

**Comment by NeckCoin** [comment]
Reviews/write ups


https://medium.com/@mdbelal183/neck-coin-ccc1fbe7d07d

https://medium.com/@obiebere/so-many-people-might-have-seen-this-and-overlooked-b8393413e05f

https://cryptonext.com/ico/neck-coin
