### ISSUE TITLE
Intelligent Trading Rename

### ISSUE THREAD

**Issue by jcmg18** [forkdelta/tokenbase#907]
This is JC from Intelligent Trading Foundation, formerly Intelligent Trading Technologies. 

We recently changed our name and a few of our social profiles. However, our token ticker “ITT” is still the same. 

Would I be possible to update our information on your website?

Here are all of our updated links:
Website: http://intelligenttrading.org/
Facebook: https://www.facebook.com/IntelligentTradingFoundation
Twitter: https://twitter.com/tryITF
Github: https://github.com/intelligenttrading
Reddit: https://www.reddit.com/r/intelligenttrading/
Telegram Group: https://t.me/intelligenttrading
Telegram Bot Beta: https://t.me/intelligenttradingbot — @intelligenttradingbot
Medium: https://blog.intelligenttrading.org/

**Comment by freeatnet** [comment]
Hey JC, we can definitely update the links and the token name.

Ref: intelligenttrading.org -> https://blog.intelligenttrading.org/ -> https://blog.intelligenttrading.org/intelligent-trading-technologies-itt-is-now-intelligent-trading-foundation-itf-b17b03b52ddd

**Comment by freeatnet** [comment]
@jcmg18 You should really consider adding HTTPS to your website.
