### ISSUE TITLE
Netkoin (NTK) Listing request

### ISSUE THREAD

**Issue by matthewabg** [forkdelta/tokenbase#908]
Contract address: 0x5d4d57cd06fa7fe99e26fdc481b468f77f05073c

Issuer's official website: www.netkoin.com

Official contract address confirmation: www.netkoin.com Contract address can be found on the bottom of the page near contact us section.

A link to a third-party review or discussion of the token: https://twitter.com/netkoin

Description: Location based advertising powered by blockchain technology.

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
