### ISSUE TITLE
Uquid Coin Listing Request

### ISSUE THREAD

**Issue by uquid** [forkdelta/tokenbase#909]
Contract address: 0xd01db73e047855efb414e6202098c4be4cd2423b

Issuer's official website: https://uquidcoin.com

Official contract address confirmation:
https://uquidcoin.com/?faqs=1

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2161156.0
http://bitcoinist.com/cryptocurrency-payment-platform-uquid-raises-17-8-million-successful-ico/

Description:

UQC is a decentralized virtual currency based on the ERC20 - token, one of Ethereum Technological trends.  The goal of this blockchain asset is to supplement the development of UQUID Ecosystem. In this virtual revolution, coin holders will have the benefit of instantly and effortlessly cashing out their coins

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.

---

Relevant reviews:
* https://www.abitgreedy.com/uquid/
* User discussion of crypto debit cards, including Uquid: https://bitcointalk.org/index.php?topic=1588857.0

0xd01db73e047855efb414e6202098c4be4cd2423b,https://uquidcoin.com
