### ISSUE TITLE
Ophelia Pheli 

### ISSUE THREAD

**Issue by OpheliaDeutschland** [forkdelta/tokenbase#913]
Hi forkdelta team, 
We are requesting the listing of our Ophelia Token on your Exchange. 

Contract address: https://etherscan.io/address/0x4df42d7317561f1540934f17c9aac68d6a21024e
Issuer's official website: https://www.opheliapheli.com
Official contract address confirmation: https://www.opheliapheli.com/ophelia-pheli-token
A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3173897.new#new

Description:
Ophelia is working on integrating cryptocurrencies into people's lives, even those that have not yet had anything to do with them. Our pre-whitepaper release is on 28-05-2018.  

Greets from Berlin, 
Nils, Fritz, Nolwen 
and Jan Paul

**Comment by Kryptoniq** [comment]
#584
