### ISSUE TITLE
Token Listing Request - IGNX

### ISSUE THREAD

**Issue by IgniteRATINGS** [forkdelta/tokenbase#914]
Contract address: 0xaFd8F91c4d7c2E3240F4154A1c596048035Eb63C

Issuer's official website: https://igniteratings.com

Official contract address confirmation: https://igniteratings.com/ignx-conversion/ - THE CONTRACT ADDRESS IS VISIBLE IN THE BOTTOM RIGHT CORNER OF THE PAGE

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=2308252.0

Description: IGNX can be converted for IGNT, the platform utility token needed to access the Ignite RATINGS platform, at a fixed ratio of 100:1. Ignite RATINGS is the world's first truly decentralised investment intelligence and ratings platform, powered entirely by swarm theory and the wisdom of the crowd. IGNT holders may participate in the rating of digital assets and, potentially, earn monetary rewards for their interactions - see the Ignite website and white paper for more details.

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
