### ISSUE TITLE
Listing SnapToken (SNPT)

### ISSUE THREAD

**Issue by ChelseaDan** [forkdelta/tokenbase#921]
Contract address: https://etherscan.io/address/0x722180f08646a73f744f33ed66fd3c990dc6a78b

Issuer's official website: https://www.snapcity.io/

Description: Geo-location game where users can complete challenges around the world to earn SnapTokens. These SnapTokens can then be used to create challenges for user's friends or the general public. App is already live on Google Play Store and Apple App Store and is fully GDPR compliant.

Official contract address confirmation: https://www.snapcity.io in the 'token sale' section.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1.  https://youtu.be/eW3txYVvMc8 minute 4:28
2. https://youtu.be/rIlJRMsSfhw minute 7:00
3. https://www.techbullion.com/interview-with-ceo-of-snapcity-on-snpt-token-sale/

Thanks! As for the donations, we'd be unlikely to be able to offer too much in the form of Ether at this stage, but I'd be interested in discussing whether there is anything we can help with in development terms. If you have telegram, please contact us at @SnapCityICO, or email dan@snapcity.io

Daniel

**Comment by ChelseaDan** [comment]
Sorry to be pushy, but is there any update here? Cheers guys!

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x722180f08646a73f744f33ed66fd3c990dc6a78b, https://www.snapcity.io/
