### ISSUE TITLE
MNL not showing on drop-down 

### ISSUE THREAD

**Issue by Moonlite-ICO** [forkdelta/tokenbase#924]
Good day, 

I hope you can assist us. 

Our token has been listed on FD <MoonLite (MNL)> and there are active trades going on: https://forkdelta.github.io/#!/trade/0x0d62dc6cd8c81dca8caadccf01ffe7c1f31d9402-ETH 

I however do not see the MNL symbol listed on the drop-down list in the top left side of FD. 

Could you kindly assist please? 

E Krige 
MoonLite Project

**Comment by freeatnet** [comment]
Users are trading MoonLite by adding it as a custom token; it is not currently on the official tokens list. You must [file a request](https://github.com/forkdelta/tokenbase/issues/new) have it added.
