### ISSUE TITLE
Eticket4 (ET4) Token Listing

### ISSUE THREAD

**Issue by AndyPandyGeek** [forkdelta/tokenbase#925]
Contract address: 0x80238d9451f86dcf12bff21af9e8deadcf915bff

Issuer's official website: https://et4.io

Description: Eticket4 is a secondary market ticketing platform operating since 2016 and registered in BVI. Eticket4 has been selling tickets for major events in Russia, FIFA World Cup in particular. ET4 are used for ticket brokers to gain access to advanced analytical tools, for ticket buyers to purchase tickets and receive tokenback, for event organizers to issue tickets and control the secondary ticket market.

Official contract address confirmation: please find the token contract address in the footer at http://et4.io, below Token Purchase Agreement

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://medium.com/@cryptoTweeg/e-ticket-4-ico-why-i-like-it-b72a72b6f122
2. https://digrate.com/uploads/investment_overview/Eticket4_ER_eng.pdf
3. https://www.youtube.com/watch?v=Loa1PQGQrAA

**Comment by Enflow-io** [comment]
How fast can we list the token? Thx a lot!

**Comment by Enflow-io** [comment]
Pull request:
https://github.com/forkdelta/tokenbase/pull/962

**Comment by freeatnet** [comment]
@AndyPandyGeek @Enflow-io Can you nudge the token issuer to fix HTTPS on their website?

**Comment by Enflow-io** [comment]
@freeatnet Hello, HTTPS fixed.

**Comment by Enflow-io** [comment]
@freeatnet Is everything fine, how long it takes to list the token? Thx a lot!

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.

---
Contract verification: https://et4.io/ at the bottom of the page.

0x80238d9451f86dcf12bff21af9e8deadcf915bff,https://et4.io/

**Comment by freeatnet** [comment]
@Enflow-io Can you fix the incomplete cert chain issue (see: https://www.ssllabs.com/ssltest/analyze.html?d=et4.io)? Thanks.
