### ISSUE TITLE
TobaCoin(TBC) token list requesting.

### ISSUE THREAD

**Issue by kodaq2017** [forkdelta/tokenbase#926]
Hello Forkdelta.

I want to requesting a token listing.

---------------

Contract address:
0x566c0239c48ff87ca943f04f1330e8193f7cfb9c

Official website:
http://tobacoin.net/

Official contract address confirmation:
http://tobacoin.net/
You can find in Token information section.

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=3308588.0
https://cryotobtc.blogspot.kr/2018/04/nowadaysits-too-much-unexpected-we-can.html

Description:
Cryptocurrency combining the direct financing through the online banks and the blockchain technology

**Comment by Kryptoniq** [comment]
Verify your contract source code on etherscan (https://etherscan.io/address/0x566c0239c48ff87ca943f04f1330e8193f7cfb9c#code)
