### ISSUE TITLE
Exceed (EXC) Token Listing Request

### ISSUE THREAD

**Issue by ExceedToken** [forkdelta/tokenbase#928]
Contract address: 0x1eAe15d9f4FA16f5278D02d2f8bDA8b0dcd31f71

Issuer's official website: https://www.exceed-io.com/

Description: Exceed IO is a decentralized data management platform secured by blockchain technology. The Exceed Token ecosystem facilitates and incentivizes collective data aggregation to create a safe and efficient information marketplace. EXC will provide a transparent and secure payment and reward system within the platform. 

Official contract address confirmation: If you navigate to the token section of our official website at exceed-io.com, you will see a clear bold selection that details our official token contract address. Our source code is also verified on etherscan and can be found here: https://etherscan.io/address/0x1eae15d9f4fa16f5278d02d2f8bda8b0dcd31f71

**Comment by freeatnet** [comment]
Please include at least two links to third-party reviews or discussion of the token, the project/product, or the token issuer. Links should be of at least two distinct kinds, including, but is not limited to: articles in the media, independent blog posts, ICO ranking websites, third party reporting on established company partnerships, YouTube videos, comments from high ranked users in BitcoinTalk.
Note:
* We are looking for substance in reviews. Reviews like "Interesting project, good luck", "to the moon" are NOT acceptable.
* These reviews cannot be on a resource controlled by the project (ie., project's subreddits or Telegram channels do not count as third-party discussion).

**Comment by Kryptoniq** [comment]
No response from token issuer for  the past 18 days.
