### ISSUE TITLE
SILENT NOTARY

### ISSUE THREAD

**Issue by psbalaji3** [forkdelta/tokenbase#932]
Contract address:0x2859021ee7f2cb10162e67f33af2d22764b31aff

Issuer's official website: https://silentnotary.com/

Description: <We use a basic feature of distributed ledger technology – immutable timestamped records – to Register, Secure and Certify digital events and documents

We give our customers a choice of decentralized platforms for any specific case.

Our ultimate user interfaces open up new opportunities in different markets: B2B, B2G, B2C, IoT. Almost all interfaces are already developed and ready for use: Mobile applications for iOS and Android, integration with Messengers (Telegram, FB and Slack), Web interface, notary-by-email, API.

Our Foundation provides legal services in a field of distributed ledger technologies.>

Official contract address confirmation: 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://github.com/SilentNotary/ICO-SN
2. https://www.facebook.com/SilentNotary
3.https://www.reddit.com/r/SilentNotary/
4.https://twitter.com/SilentNotary

**Comment by Kryptoniq** [comment]
#969

**Comment by Kryptoniq** [comment]
https://www.newsbtc.com/press-releases/silentnotary-com-make-debut/
http://www.the-blockchain.com/2017/08/02/silentnotary-blockchain-based-notary-chatbot-serves-first-clients/
http://www.abnewswire.com/pressreleases/silentnotary-ico-introduces-byteball-in-legal-field_193719.html

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x2859021ee7f2cb10162e67f33af2d22764b31aff, https://silentnotary.com/

**Comment by Domian1980** [comment]
Thank you for the good news!
We would like to ask you to start listing on May 2nd or later, if it is OK
for you.
We will start the updated web-site on May 1st to support our community, it
is better to start listing after that, not before.
Thank you in advance!

Best regards,
Dmitrii Grafskii
SilentNotary Team

2018-04-27 15:32 GMT+03:00 Krypton <notifications@github.com>:

**Comment by Domian1980** [comment]
Hello!
Can you please inform about the expected date of listing for SNTR token?
We would like to inform our community.

Best regards,
Dmitrii Grafskii
SilentNotary Team

**Comment by freeatnet** [comment]
@psbalaji3 Thank you for your request! Your token will be live on **Tuesday, June 26th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
