### ISSUE TITLE
ERC20X (E10) an index of the top 10 native ERC20 tokens

### ISSUE THREAD

**Issue by drixta** [forkdelta/tokenbase#934]
**Contract address:** TBD
Since the final composition of the contract is dependent on the marketcap of the
top 10 tokens, the final contract address is TBD. A test version is live on the
mainnet and can be found here: 
https://etherscan.io/address/0xe0366f8857B1466452B89C0EE03246F860A0eF01

**Issuer's official website:**
https://erc20x.io

Username: `admin`, Password: `cryptofin123`

**Description:** ERC20 X is a collection of the top 10 native ERC20 tokens weighted
by marketcap. ERC20 X is built using the bskt technology (https://cryptofinlabs.github.io/) and created by the same team. ERC20 X is meant to be an index token to help ERC20 users diversify their portfolio.

**Official contract address confirmation:** http://www.erc20x.io/method

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

This has been an open source project so not much discussion has been created pre-launch

https://www.reddit.com/r/ethtrader/comments/879r9m/bskt_a_smart_contract_for_creating_decentralized/

**Comment by Kryptoniq** [comment]
- Your website is inaccessible ATM
- No third party review
- No token contract.

We can come back to this issue when you have these in place.
