### ISSUE TITLE
Listing of Bitether(BTR)

### ISSUE THREAD

**Issue by GNRG** [forkdelta/tokenbase#936]
Contract address: 0x499a6b77bc25c26bcf8265e2102b1b3dd1617024

Issuer's official website: https://bitether.org

Description: 
![image](https://user-images.githubusercontent.com/37828194/38765341-4f71cbd0-3fdd-11e8-9b30-4c8b19caaf8a.png)

Official contract address confirmation: 

0x499a6b77bc25c26bcf8265e2102b1b3dd1617024

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. 
![image](https://user-images.githubusercontent.com/37828194/38765351-6dca62ae-3fdd-11e8-817c-795a334a27e2.png)

2. 
![image](https://user-images.githubusercontent.com/37828194/38765354-819ad5de-3fdd-11e8-92eb-766139f6c849.png)

**Comment by Kryptoniq** [comment]
Please make your description as plain text.

**Comment by GNRG** [comment]
Hi There,
Sorry for late reply because i am on canada tour for promoting my crypto
currency.
Please tell me your requirement for listing,  i am ready to provide all
information..

Waiting for your favourable reply

Thanks & Regards,
Imrankhan Nagori
Founder - Bitether

**Comment by Kryptoniq** [comment]
@GNRG as stated, please make your description text only.
