### ISSUE TITLE
Listing Request XGG Token 

### ISSUE THREAD

**Issue by GoingGems** [forkdelta/tokenbase#937]
Contract address:0xf6b6aa0ef0f5edc2c1c5d925477f97eaf66303e7

Issuer's official website: https://www.going-gems.com/

Description: 
Opportunities
Look for opportunities of Cryptocurrency Market. There's much of ICO are scam and lot of Investor's money are stolen. We make differences way to get profit from Cryptocurrency by take a Airdrop of our token for free for everyone. Our project is based Game who can purchase in Apps by XGG Token.

Official contract address confirmation: https://www.going-gems.com/#xggtoken

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://t.me/joinchat/InmKbxAEykUl0aLt_f2F8A

2. https://bitcointalk.org/index.php?topic=3332098 

email : support@going-gems.com
twitter ; https://twitter.com/GoingGems

**Comment by GoingGems** [comment]
Etherscan view =  https://etherscan.io/address/0xf6b6aa0ef0f5edc2c1c5d925477f97eaf66303e7

**Comment by GoingGems** [comment]
How to get listed on forkdelta guys ???

**Comment by GoingGems** [comment]
[XGG Whitepaper.pdf](https://github.com/forkdelta/tokenbase/files/1932952/XGG.Whitepaper.pdf)

**Comment by GoingGems** [comment]
Hello , how about our token listing request ??

**Comment by Kryptoniq** [comment]
Your dev support Angela Parker happens to be Liz Wheeler (https://twitter.com/liz_wheeler)
We have a strong stance against impersonation and will not be listing your token.
If you believe this decision was made in error kindly contest the decision on this issue by providing verifiable identity of all your  team members.
Website: https://www.going-gems.com/ 
Archive: http://archive.is/qTV7F
