### ISSUE TITLE
Please list our token in your website

### ISSUE THREAD

**Issue by remedcu** [forkdelta/tokenbase#94]
LOVE TOKEN

Contract address : 0xe6eFd46EB6CDd73A7fe1e760Fa0c25a299755a4B
Symbol = LOVE
Name = LOVE Token
Decimals = 8

Website 1: https://lovetoken.gq/

Bitcointalk Announcement link: https://bitcointalk.org/index.php?topic=2942750
Bitcointalk Bounty link: https://bitcointalk.org/index.php?topic=2955807

Github: https://github.com/LoveTokenAirdrop

Telegram Channel: https://t.me/lovetokenchat 
Twitter: https://twitter.com/lovetokencrypto

**Comment by JonathonDunford** [comment]
Listed.
