### ISSUE TITLE
Add ShipCoin (SHIP)

### ISSUE THREAD

**Issue by mhyytine** [forkdelta/tokenbase#941]
Contract address: 0xe25b0bba01dc5630312b6a21927e578061a13f55

Issuer's official website: https://shipchain.io/

Description: Shipchain is a freight management ecosystem that aims to integrate blockchain contracts into the global freight economy and interface with existing freight management software. Tokens are used for tracking freight and rewarding users.

Official contract address confirmation: https://shipchain.io/ Etherscan link to tracker on bottom of the page.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. ChartGuys' YT Review: https://www.youtube.com/watch?v=tVd7BzFRrqI
2. Cryptonomatron Review: https://www.youtube.com/watch?v=uzhGsMB01ow

**Comment by freeatnet** [comment]
@mhyytine Thank you for your request! Your token will be live on **Tuesday, June 26th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.
