### ISSUE TITLE
Add New Coin Blockchain

### ISSUE THREAD

**Issue by rezaqzawity** [forkdelta/tokenbase#943]
test test test

**Comment by rezaqzawity** [comment]
Contract Address 0x87aB3132951815419cE7dB546aa28Ca1183D571e
Name: Blockchain
Symbol: BC
Decimal: 18
Total supply: 3 000 000 000
Blockchain is a ERC20 Token based on ethereum blockchain

**Comment by Kryptoniq** [comment]
The third-party links you provided  are for blockchain.info which belongs to Blockchain Luxembourg S.A.
I perceive some form of deception in your token.
Please let me know how blockchain.io is affiliated with blockchain.info.
