### ISSUE TITLE
HINT Token listing request

### ISSUE THREAD

**Issue by hintcoin** [forkdelta/tokenbase#944]
Dear Team,

Requesting to list HINT Token

Name: Hint
Symbol: HINT
Decimals: 18
Contract address: 0xAC9E0035dC040671E5646dc9b8896d7D78C48F85
Etherscan Link: https://etherscan.io/address/0xac9e0035dc040671e5646dc9b8896d7d78c48f85

Issuer's official website:  https://www.hint.to

White paper Link: https://hint.to/wp-content/uploads/2018/01/Hint_Wp_latest.pdf

Description: 

HINT is a mobile app, AI-chatbot, and smart AI-commerce technology for voice assistants on top of intelligent HINT network: – a distributed, privacy enabled data analytics platform using blockchain technology.

Our mission is to build an AI-commerce platform using blockchain technology to revolutionise everyday shopping experience.

Official contract address confirmation: Please kindly check the contract address in the footer section on our official website https://www.hint.to home page.

Website footer link:  https://hint.to/#footer

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=2832282.0
2. https://coin5s.com/content/hint-ico-present%E2%80%99s-new-era-smart-shopping-world-crypto-market
3. https://steemit.com/blockchain/@nugezmils/hint-platform-for-shoppers
4. https://icoholder.com/en/hint-18009
5. https://longcatchain.com/ico/hintto
6. https://www.youtube.com/watch?v=PFjXxiUl_sY
7. https://www.youtube.com/watch?v=jsBpJVS4xx8
8. https://youtu.be/uTnHy4wj1FY
9. https://medium.com/@huyenthai3467762/hint-ico-will-change-online-shopping-system-by-using-blockchain-technology-a861a499ed9d

Contact email: ask@hint.to

Thank you in advance.

**Comment by hintcoin** [comment]
Hi there, Could you please look into my request? Cheers

**Comment by hintcoin** [comment]
Hey guys, @freeatnet @Kryptoniq  

Could you please kindly review and give us some update? Let us know if you require any more information. 

Thanks, Mak

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xac9e0035dc040671e5646dc9b8896d7d78c48f85, https://hint.to/

**Comment by hintcoin** [comment]
Hi @Kryptoniq thank you for the great news! cheers

**Comment by hintcoin** [comment]
Hi @Kryptoniq @freeatnet It's been a long wait for us, could you please reconsider our pull request? #987
