### ISSUE TITLE
Please add new token Blockchain (BC)

### ISSUE THREAD

**Issue by rezaqzawity** [forkdelta/tokenbase#946]
I'm listing a token. 

Contract address: 0x87aB3132951815419cE7dB546aa28Ca1183D571e

Issuer's official website:  https://blockchain.io

Description: 

Token is needed to achieve the following important issues:
The cryptocurrency exchange of trust for individual and institutional traders and investors.
Encrypted cold storage and cryptographic proof of reserves.
Fair-exchange protocols to eliminate the counter-party risk.
Total supply is 3 billion the token is cheap, everybody can buy it. Please let me know when anything else is needed

Official contract address confirmation: 

https://ethplorer.io/address/0x87ab3132951815419ce7db546aa28ca1183d571e

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

 
1.  https://medium.com/blockchainio

2. https://twitter.com/blockchainio

**Comment by Kryptoniq** [comment]
#938 #943
Thanks for spamming the tokenbase.
You didn't attend to my queries but choose to open close issues as you please.
Sorry, we can't list your token at this time.
