### ISSUE TITLE
GMV listing request

### ISSUE THREAD

**Issue by wisdomabioye** [forkdelta/tokenbase#947]
Contract address: 0x594120039687ddaab50c4ab03bada20eb4b218f6

Issuer's official website: http://greenmovement.network
Twitter: https://twitter.com/gmvtoken
Telegram: https://t.me/gmvchat
Bitcointalk: https://bitcointalk.org/index.php?topic=2943620

Description:

Green Movement is an ethereum blockchain based token created to support a 
sustainable environment. The purpose of the token include the following:
• Creating a sustainable environment
• Creating awareness about eco­friendly activities
• Financing afforestation and re­afforestation to reduce global warming 
and normalize greenhouse gases
• Ensuring a low­-carbon future through disposal and recycling of waste

Official contract address confirmation: http://greenmovement.network/#application

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.youtube.com/watch?v=RPZBhGrMkAM&feature=youtu.be
2. https://medium.com/@beebeehem/gmv-the-green-movement-is-the-first-decentralized-platform-to-incorporate-and-promote-agro-fa96320d0cdf
3. https://www.youtube.com/watch?v=t5jjqExzGkY&feature=youtu.be
4. https://steemit.com/blockchain/@samcofy/reasons-why-you-might-want-to-support-green-movement

**Comment by wisdomabioye** [comment]
Kindly give us update on our listing request. Thank you.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x594120039687ddaab50c4ab03bada20eb4b218f6,  http://greenmovement.network/

**Comment by wisdomabioye** [comment]
Thank you.

**Comment by wisdomabioye** [comment]
Green Movement community said "it is so difficult to trade GMV through contract address, please list GMV officially on ForkDelta". 
We can't wait to get listed officially on ForkDelta. Thanks in anticipation.
