### ISSUE TITLE
Listing a coin Telegram (GRAM)

### ISSUE THREAD

**Issue by Listingatoken** [forkdelta/tokenbase#948]
I'm requesting to list a coin

Contract address: 0x96DCc593D10c57010Fb401D1491d46687F846AdC

Issuer's official website: https://telegram.org/

Description: 

Launching in 2018, this cryptocurrency will be based on multi-blockchain Proof-of-Stake system - TON (Telegram Open Network, after 2021 The Open Network) - designed to host a new generation of cryptocurrencies and decentralized applications. 

Official contract address confirmation: 
https://ethplorer.io/address/0x96dcc593d10c57010fb401d1491d46687f846adc#tab=tab-holders
https://icodrops.com/telegram-ico-ton/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=2710410.0

2.https://www.reddit.com/r/omise_go/comments/7oif3j/telegram_ico_telegram_open_network_ton_built_on/

3. https://www.reddit.com/r/telegramico/

**Comment by Kryptoniq** [comment]
Thanks for your request but we do not list scam tokens.
