### ISSUE TITLE
Listing Element token (EM)

### ISSUE THREAD

**Issue by Samael6661** [forkdelta/tokenbase#95]
1.0xee688d34c1cc02fc81b2f3f05c489e05d4c0b6ba 
2.https://artbik555.wixsite.com/element
3.https://etherscan.io/token/0xee688d34c1cc02fc81b2f3f05c489e05d4c0b6ba

4.https://bitcointalk.org/index.php?topic=2408354.msg24629174#msg24629174

Thanks,I hope Element will be listed soon.

**Comment by JonathonDunford** [comment]
Contract address verified: 0xee688d34C1CC02fC81B2F3f05c489e05D4c0B6Ba

Can you please provide a short description? 1-3 sentences.

@Samael6661

**Comment by Samael6661** [comment]
Element token made as one of the most low supply tokens.It is designed to realize imaginations of traders, doing ethereum blockchain more fuller and better.Element is erc-20 token,having property as an element, in this case as blockchain element.EM(Element) have 10 token total supply.

**Comment by JonathonDunford** [comment]
What would the ticker name be? ELEMENT?

**Comment by Samael6661** [comment]
Yes,ELEMENT.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/tokenbase/pull/183
