### ISSUE TITLE
Requesting to be Listed ZENY(ZNY)

### ISSUE THREAD

**Issue by emerose777** [forkdelta/tokenbase#950]
Description: -->Token issuer is EMEROSE LLC.Japan.
We won't sell coin at our site. When profits are obtained by selling coin,50% of the purchased ZENY tokens are contributed for a social welfare organization or a charitable work organization.We certainly upload a contribution certificate to official site.ZENY is ICO(ed) on a grand scale is a differentness token.Airdrop, an introduction commission affiliate, etc. do not exist, but we aim at eliminating possibilities, such as an ICO dishonesty, as much as possible. 

Official contract address confirmation:
http://emerose.biz/ 
emerose@emerose.biz
You can find link to our site from 
https://etherscan.io/token/0x42c54a24B157E0039cFBA0927E1982d562ba6573
Discussion is performed in Japanese. 
http://emerose.biz/thread/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
-->We are Japanese and thought to this head scratcher. I asked the intimate president of two companies for writing. 
1.http://liberty-hd.co.jp/about-zeny-token/ 
2.http://b-liberty.com/zny/ 
From the administrator of Etherdelta, since there was no reply, I wrote this. When ZENY appears in a list, although we are dribs-and-drabses, we are going to contribute for Forkdelta. 
Thank you.

**Comment by Kryptoniq** [comment]
- There are only 2 token holders ATM.
- Provide link to a reputable third-party review or discussion of your token.
