### ISSUE TITLE
CTN Tokens

### ISSUE THREAD

**Issue by cryptonewsID** [forkdelta/tokenbase#956]
Contract address:  0x776b9d69519fc786e103e39f1576df88b66b93ee

Issuer's official website: https://cryptonews.co.id

Description: <CTN tokens are Tokens Asset of the website cryptonews.co.id and cryptonews indonesia company]>

Official contract address confirmation: <https://cryptonews.co.id/airdrop-ctn-token-dari-cryptonews-co-id/>

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.  https://cryptonews.co.id/airdrop-ctn-token-dari-cryptonews-co-id/
2.  https://bitcointalk.org/index.php?topic=3326430.new#new

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient information. Please create a proper announcement thread.
http://archive.is/LjWB7

Your website says less of what your token does, project timelines and utility. Please provide more info.
