### ISSUE TITLE
Listing Lina Token on Forkdelta

### ISSUE THREAD

**Issue by tamvuthach** [forkdelta/tokenbase#957]
Dear Forkdelta

I am writing on behalf of Lina project. We are a project registered in Zug, Switzerland ( https://www.zefix.ch/de/search/entity/list/firm/1333792 ). Our development team reside in New Zealand (country of our founder mr Mitchell Pham https://www.linkedin.com/in/mitchellpham/ ) and Vietnam (Core Development Team)

We would like to list our token on Forkdelta. Below are our information:

Contract address: 0xc05d14442a510de4d3d71a3d316585aa0ce32b50

**Issuer's official websit**e: https://lina.review

**Description**: Our project's aim is to tokenize the review industry. Qualified reviewers – called "Helpers" – can be chosen by a panel or by community vote – can earn LINA token for the review and rating work. Advertisers and Merchants can place advertising or create review campaigns using LINA tokens. Part of those LINA tokens will be used to pay Helpers. Our Lina token is ERC20 so it's the same with other ERC20 token and we will connect it to our own blockchain using a "bridge" called Lina Bridge. More detail can be found in our whitepaper: https://lina.review/lina_whitepaper.pdf

**Official contract address confirmation**: https://lina.review - the information is presented at the top banner.

**Links to third-party reviews or discussion of the token, the project/product, or the token issuer:**

The audit of our contract from Blockchainlabs.nz (https://www.blockchainlabs.nz/): https://github.com/BlockchainLabsNZ/LINA-TokenERC20/tree/master/audit

Our Youtube Channel: https://www.youtube.com/channel/UChKiD9OneIjgJvxOR8vCinQ

Below are our appearances on media: 
 
Vietnamese National TV Channel VTV1: 
  http://vtv.vn/video/tai-chinh-kinh-doanh-sang-28-3-2018-289449.htm (Start from minute 3:15) https://www.youtube.com/watch?v=grDWdjkcjQI (cut-out version) 

Vietnamese Government TV: 
  http://quochoitv.vn/Videos/dong-chay-cua-tien/2018/3/dong-chay-cua-tien-ngay-07-032018/170770 (Start from minute 3:57) 

Vietnamese National TV Channel VTV6:  

  http://vtv.vn/video/ban-tin-the-he-so-06-4-2018-291345.htm (Start from minute 8:15) –https://www.youtube.com/watch?v=JrD5ZPyYOH0&feature=youtu.be (cut-out version) 
 
Other Online News: 

International Media: 
http://www.makelemonade.nz/2018/01/11/nz-tech-stars-lead-world-first-blockchain-launch/ https://itbrief.co.nz/story/new-zealands-tech-leaders-get-behind-global-blockchain-platform/  https://idealog.co.nz/tech/2018/01/meet-lina-blockchain-powered-platform-poised-disrupt-onlineratings-and-review-industry  
 
Vietnamese Media: 
 
http://nhipcaudautu.vn/doanh-nghiep/blockchain-cho-diem-bung-no-3322857/ http://cafef.vn/nganh-cong-nghiep-trieu-do-dat-buoc-tien-moi-nho-blockchain20180312173049336.chn 
http://vietnamnet.vn/vn/cong-nghe/tin-cong-nghe/soi-dong-tuan-le-blockchain-viet-nam435299.html 
http://thoibao.today/paper/soi-dong-tuan-le-blockchain-viet-nam-2881886

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.
