### ISSUE TITLE
Token Listing Request: SGD

### ISSUE THREAD

**Issue by secretgod** [forkdelta/tokenbase#958]
Contract address: 0x4416FCE5Df8AA1336ba1D2D4cD71D213a01940A7

Issuer's official website:
1. clearnet: secretgod.io   
2. tor: qwskfsgyqylbbucv.onion  

Description: Secret God is a decentralized private society. The token may be redeemed for membership. Membership includes voting rights, future revenue share, and access to events and other initiatives.

Official contract address confirmation: secretgod.io

Links to third-party reviews or discussion of the token, the project/product, or the token issuer: 

1. https://bitcointalk.org/index.php?topic=2850523.0
2. https://secretgod.io/assets/protocol_12march.pdf

**Comment by Kryptoniq** [comment]
You said your ICO was successful. If I may ask, how much did you raise and why is there only one token holder?
Your bitcointalk announcement thread is filled with scam accusations. Kindly provide a link to a trusted third-party review of your token.
Thank you.

**Comment by secretgod** [comment]
Hello,

Thank you for your response. There is only one holder currently because the tokens have not been distributed. We hope to distribute to sale participants and bounty hunters with ForkDelta exchange support. The sale raised over USD$5M.

You ask a very fair question. The accusation on Bitcointalk stems from a single user who attempted to extort the project shortly after the launch. We refused. We learned after the fact the user is well-known on the board for precisely such schemes. There is a link on the thread that details the modus operandi of this user (or group of them) in the past. We suspect it is one of the larger ICO underwriting cartels, but this is neither here nor there. It would be unfortunate if the action of this known fraudster keeps this project from trading on FD without official support.

In any event, we understand the risk you take in listing the SGD token. ForkDelta has a pristine reputation and in no way does Secret God intend to do it harm. Yours is the sort of project that makes the community better for all.

Thank you, of course, for your consideration. Please let us know if you might require tokens for a listing, as a portion has been set aside for such fees.

SG team

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Kryptoniq** [comment]
There is only one token holder ATM. Please provide valid  proof that your ICO raised $5m.
Your bitcointalk announcement thread doesn't qualify for a review, kindly provide link to a third-party review of your project.

**Comment by secretgod** [comment]
Hello,

Your attention and consideration has been much appreciated. The vast majority of funds were raised via XMR, and even if technically possible to prove the origin of those funds, we would not do so. We can share our XLs showing public ETH addresses that will receive distributions on the blockchain (some correlate with public bounty threads). Would it change your position if we were to simply re-apply once the distribution takes place so you may see the distribution on chain?

Thank you.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Kryptoniq** [comment]
We don't want to see your fancy wallets but it isn't stated anywhere that you raised $5m. 
As stated, please provide a link to an independent third-party review of your project.
