### ISSUE TITLE
New cryptocurrency CRYPTON

### ISSUE THREAD

**Issue by cryptoncoin** [forkdelta/tokenbase#959]
Hi!								

Please consider a new cryptocurrency CRYPTON for adding to your exchange.								

Name - Crypton								

Ticker - CRN								

Project summary and goal - CRYPTON exists like baseline for new special smart contracts. New smart contracts are written on JavaScript and works on VMs, that overlays the blockchain.								

Pros and cons with similar projects:								

BLOCKCHAIN ISSUES								

Current Blockchains are broken and we can't rely on them in enterprise systems.								

- Slow transactions								

- Low network bandwidth								

- Expensive commission								

- Limitations and security of smart contracts								

CRYPTON SOLUTIONS								

Crypton is a backbone for real world and internet services, it enables companies to explore new b2b or b2c models by making every resource to be traded on an open market in real time, with extremely low fees.								

- Low commission								

- POW concept								

- Faster speed								

- Larger number of transactions								

- A new type of smart contracts

								

Official website - http://crncoin.io								

SNS - https://www.reddit.com/user/Cryptoncoin, https://t.me/cryptoncoin, https://twitter.com/coincrypton, https://bitcointalk.org/index.php?topic=3332228.new#new								

Blockchain (or other platform) explorer - http://explorer.crncoin.io/blocks								

Whitepaper - http://crncoin.io/white-paper.html								

Fundraising - Crypton is not ICO. It's a new cryptocurrency.								

Pre-mining - 0,5% from Total Supply								

Roadmap and current state - http://crncoin.io/#Crypton-Dev								

Regards,								

Crypton's Founder - Vic Tomilov

**Comment by cryptoncoin** [comment]
crypton.coin.io@gmail.com

**Comment by Kryptoniq** [comment]
ForkDelta is a decentralized cryptocurrency exchange for ERC20 Tokens.
