### ISSUE TITLE
LISTING OF TRUST (TEC)

### ISSUE THREAD

**Issue by TRUSTETHERCOIN** [forkdelta/tokenbase#96]
Dear ForkDelta,

I would like to formally introduce myself as the owner of TRUST.  

TRUST is a ERC20 smart contract built on the Ethereum blockchain.
 
TRUST incorporates all the benefits of a cryptocurrency, such as decentralisation and low barriers to entry for participants, combined with tangible real estate investments.
​
This gives rise to the TRUST ethos – “Crypto-currency, real-world assets”.
​
The token’s tie to hard assets will not only help to promote stability of the token but also provide a reliable return for token holders. Equally as important is the increase in the inherent value of the token due to the capital appreciation of the property and reinvestment of capital. 

The project will purchase and subsequently develop and/or let residential and commercial real estate. This income will be used to provide bonuses on a six-monthly basis for token holders and act as a source of continuous cash flow for future investments, as well as enable the project to benefit from the capital appreciation of the assets held

In essence, TRUST is a property investment portal for the digital age, run for the benefit of the projects supporters (token holders) and not large commercial institutions.

Currently, banks dictate the terms of buying real estate through the use of mortgage products. ​

Buy to Let mortgages often require a large deposit and fees for the investor purchasing the property, with the costs being passed onto the consumer in the form of high rental fees.

TRUST aims to decentralise the housing market by purchasing real estate outright and offering affordable rental fees to the consumer. 

TRUST itself is decentralised as 100% of the token supply will be held buy token holders following the four stages of distribution detailed in the whitepaper.

The total supply of TRUST is 100,000,000

The official website is www.TrustEtherCoin.com

The Token Address is 
0xb63Ab8E276E081b9079c3ae520C58061FA4Acb45

I look forward to hearing from you regarding our listing. 

If you have any further questions please let me know.

Kind Regards,

Rhys Thomas (Founder of TRUST)

**Comment by TRUSTETHERCOIN** [comment]
Hello, Please also see our announcement on bitcointalk. 

https://bitcointalk.org/index.php?topic=2963414.new#new

**Comment by JonathonDunford** [comment]
Contract address verified: 0xb63Ab8E276E081b9079c3ae520C58061FA4Acb45

Can you please provide a short description of the token? 1-3 sentences.

@TRUSTETHERCOIN

**Comment by TRUSTETHERCOIN** [comment]
Hello, Thank you and i apologise for overloading with information previously.

TRUST is a ERC20 smart contract built on the Ethereum blockchain. TRUST incorporates all the benefits of a cryptocurrency, combined with tangible real estate investments. The capital raised from our initial distribution will be used to purchase investment real estate which will provide 6 monthly bonuses for TRUST token holders. 
​
Thank you
TRUST

**Comment by TRUSTETHERCOIN** [comment]
Hello Thank you for getting back to me.

TRUST is a ERC20 smart contract built on the Ethereum blockchain. TRUST
incorporates all the benefits of a cryptocurrency, combined with tangible
real estate investments. The capital raised from our initial distribution
will be used to purchase investment real estate which will provide 6
monthly bonuses for TRUST token holders.

Thanks,
TRUST

**Comment by JonathonDunford** [comment]
Looks good! Will get to it soon.

**Comment by TRUSTETHERCOIN** [comment]
Thank you very much!

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/pull/72
