### ISSUE TITLE
List NODE Token

### ISSUE THREAD

**Issue by nodepower** [forkdelta/tokenbase#960]
Please, consider listing the NODE Token on the exchange. Find below all the required information:

Token address: 
0xac956c72c262e5405a84dac655d5f3bea7ae9534

Issuer's official website: 
https://nodepower.io/

Description: 
Node is a revolutionary high-tech start-up, which disrupts a market niche of wireless transmission devices for both private and commercial use. NODE Token is a classical utility token, whereby the token holders are able to exchange NODE Tokens for a purchase of Node devices with a 25% discount. 

Official contract address confirmation: 
https://nodepower.io/?token

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
https://www.ccn.com/node-intelligent-technology-wireless-energy/
https://steemit.com/crypto/@dan90/node-power-ico-review-a-cryptocurrency-for-wireless-technology
https://bitcoinexchangeguide.com/node-ico/
https://www.youtube.com/watch?v=Dx_duF2C8Is
https://www.trackico.io/ico/node/
https://icobench.com/ico/node
http://wiserico.com/ico/node
https://foundico.com/ico/node.html
https://coinlauncher.io/node-ico

**Comment by nodepower** [comment]
We have made our contract address public. 
Please, check this link: https://nodepower.io/?token

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by nodepower** [comment]
@freeatnet We have initially stated all the information according to the form that you sent. Please, recheck it or tell us exactly what is missing, because we have checked it and did not find any missing information.

**Comment by nodepower** [comment]
@freeatnet Hi! We have updated some links in our form. Please, check.

**Comment by nodepower** [comment]
@freeatnet Hi! Are there any updates? Please, let us know, because we are waiting for more than 4 months already

**Comment by nodepower** [comment]
@freeatnet Hi! In terms of these media sources, we were listed there as a project before the launch of our ICO. The reason for placing a general link was because we do not have a separate page devoted to our project's profile, but we made screenshots from these websites so you can see the proof:

ICO Alert: http://joxi.ru/bmo19ljcxyqJYA
Smith&Crown: http://joxi.ru/Vm6aWBWsxND4Nr

**Comment by therealMikkoK** [comment]
R1 👎
Whitepaper consists of price details of physical products not yet manufactured.
WP talks of ICO, application of ITO; a non-issue within itself, but neither suit this case which is clearly more suited to an IPO or a Venture Capital deal.
@nodepower 
@freeatnet

**Comment by freeatnet** [comment]
Not terribly clear on where NODE is on Smith & Crown or ICO Alert.

![image](https://user-images.githubusercontent.com/138289/44210117-4de30c00-a16e-11e8-9385-75c28bf5eabe.png)
from https://www.smithandcrown.com/sale/

Google knows of no mentions of NODE "intelligent technology for wireless energy" on ICO Alert, either.

@nodepower please post links to pages where your project is mentioned.
