### ISSUE TITLE
Add Necony (NCN)

### ISSUE THREAD

**Issue by necony** [forkdelta/tokenbase#961]
NECONY TOKEN

Contract address : 0x7dFa96685B542D96a9be2d4a191950Fbeb11c5BB
Symbol = NCN
Name = NECONY
Decimals = 8

Website 1: https://www.necony-project.com/
Website 2:https://nagecoin.com/     ←NCN chip system
Bitcointalk Announcement link: https://bitcointalk.org/index.php?topic=3287957

discode: https://discord.gg/SWEuyWp
Twitter: https://twitter.com/nekocatspretty
Exchange:https://crex24.com/exchange/NCN-BTC

**Comment by freeatnet** [comment]
Please update your request to the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Thanks!
