### ISSUE TITLE
USER SUPPORT Please Help recover/explain where my PXBRL tokens have gone??

### ISSUE THREAD

**Issue by ryeben7** [forkdelta/tokenbase#964]
I am missing 7400 PXBRL...
The two transactions were for (7400) 7200 and 200 PXBRL tokens which I wanted to withdraw from my Forkdelta account to my Nano ledger wallet. However the PXBRL tokens are no longer showing on Forkdelta, or showing on my Nano. I have been on Delta balances to check https://deltabalances.github.io/recent.html#0x4b8bd304366Da6A5bbA04c5BC192CEb412AC9A1F
I have also followed the transactions 0xb33874a3b41e77d2e3934821917ca31d785f2f775170abc3d60f90b35e876380 0xe6c0f9677f3cf9347eb4cb564a5c9c3888687c07ddc313276d6de48a9e4c8bbf
I traced the funds (attempted to) and they look to have been sent to: 0x4b8bd304366da6a5bba04c5bc192ceb412ac9a1f (which is my fork delta account)
it then went to the address 0xa4da7e3f5a4baf3712576fa1193b990f02e3ffe3 and then appears to go to 0x8d12a197cb00d4747a1fe03395095ce2a5cc6819 ???
Can someone from the team/forkdelta please help explain what happened, where my tokens are and why?? 
Please Help recover/explain where my PXBRL tokens have gone?? (User Support)

**Comment by ryeben7** [comment]
Please point me in the right direction to contact someone that may be able to help if this is not the correct place, many thanks. Ryan

**Comment by Kryptoniq** [comment]
Hi @Ryeben7 please join our Discord server for support https://discord.gg/RZVN9cG.
Thank you.
