### ISSUE TITLE
Moria Token

### ISSUE THREAD

**Issue by MoriaTokens** [forkdelta/tokenbase#965]
Contract address: 0x8e81332db0d491005d26c9f889dc7eadd7ca18f0

Issuer's official website: https://moriatoken.com

Description: 
The Moria platform democratizes investing in what has traditionally been an exclusive club for the rich and well-connected. Through Moria, any investor with access to Bitcoin or Ethereum can own a stake in a proven gold mine. The best part is the volatility has been taken out of the picture. The value of the ether you receive is based upon the value that is put in, making this an exceptional investment with potential for upside in trading the token as well as cash flow from holding the token.

Official contract address confirmation: 
https://moriatoken.com will have the address placed on the site just waiting on the devs to make the change thank you

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://themerkle.com/gs-mining-company-launches-the-moria-token-ico/
2. https://www.icoexaminer.com/ico-news/moria-ico-literal-gold-mine/
![moria-logo from website](https://user-images.githubusercontent.com/38541785/39017300-e5fc7f2a-43f0-11e8-8a4a-d5ce0a79bbbe.png)

**Comment by MoriaTokens** [comment]
The token address can be seen on the homepage under the contract dropdown menu when clicking address 
https://moriatoken.com

**Comment by Kryptoniq** [comment]
Please verify your contract source code on etherscan.io
https://etherscan.io/address/0x8e81332db0d491005d26c9f889dc7eadd7ca18f0#code
