### ISSUE TITLE
DGZ Token Listing

### ISSUE THREAD

**Issue by akozlov-dogezer** [forkdelta/tokenbase#966]
Hello,
could you please list our DGZ token on ForkDelta. Required information:

Contract Address: 0x84178d97a442cab8b584917cbab6342ab9a1e137

Issuer's official website: https://dogezer.com/

Description: Dogezer is a platform, which integrates all of the necessary tools for people to work together on innovative projects, with the ability to use project-specific tokens to reward results and incentivize collaboration. DGZ Token is a token which can be used to pay platform fees - effectively a "License" to use the platform.

Official contract address confirmation: https://dogezer.com/#dgz, note the address in first bullet in that section.

Links to third-party reviews (a few samples):
1. https://icorating.com/analytics/basic/dogezer-progect-rating-overview/
2. https://www.youtube.com/watch?v=1E34-74Shs4
3. https://ambcrypto.com/next-revolution-ethereum-bitcoin-dogezer/

Our Own Links:
Alpha Version - https://dogezer.io
BTT - https://bitcointalk.org/index.php?topic=2100916
Telegram - https://t.me/dogezer
github (only ITO smartcontracts) - https://github.com/akozlov-dogezer
Medium Blog - https://medium.com/@dogezercom
Facebook - https://www.facebook.com/dgzcom/
Twitter - https://twitter.com/dogezerCom
YouTube - https://www.youtube.com/channel/UCxaU9UXzG7VvjHhnlmmSmJA
Email - community@dogezer.com

Note: Some trading is already happening on forkdelta - https://forkdelta.github.io/#!/trade/0x84178d97a442cab8b584917cbab6342ab9a1e137-ETH

With kind regards
Dogezer Team

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x84178d97a442cab8b584917cbab6342ab9a1e137, https://dogezer.com/

**Comment by Kryptoniq** [comment]
Hi @Akozlov-dogezer, I'm sorry,  It was an error. Thanks for pointing out.

**Comment by akozlov-dogezer** [comment]
Hi Guys,
anything we can do to make this to happen? It is 50+ days after it have been said that everything is good with the info and it will get listed.
