### ISSUE TITLE
Simple rename/update of the ticker name/symbol of ERC20 token 

### ISSUE THREAD

**Issue by Belance** [forkdelta/tokenbase#967]
Dear Exchange IDEX! 

We appreciate a lot your hard work everyday and efforts on the IDEX project!

It would be great if you could just change the current symbol of ERC20 to ERC20 OLD ( as symbol in old/current contract address ). We are sorry for the inconvenience.

We already discussed this in another issue number #808 and moderator said to open new issue. So we did. And we was waiting for the answer on issue #808  almost a month, and I hope here you will consider request faster. Thanks !  

The following info on this text will guide you through the details.

Information about current OLD Contract address: 

Contract address:
0x26D5Bd2dfEDa983ECD6c39899e69DAE6431Dffbb

Symbol: ERC

Link to official explorer EtherScan: https://etherscan.io/address/0x26d5bd2dfeda983ecd6c39899e69dae6431dffbb

LINK ON Fork Delta: https://forkdelta.github.io/#!/trade/ERC20-ETH

Official contract address confirmation on the official website: 
http://belance.io/erc20.html

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2304875

It would be great if you could just change the current symbol of ERC20 to ERC20 OLD ( as symbol in old/current contract address ). We are sorry for the inconvenience.

Warm regards,
ERC20 team 
belance.io

**Comment by Kryptoniq** [comment]
Sorry, for clarification. 
Do you just want the ERC20 symbol to be changed to ERC20_OLD on FD?

**Comment by Belance** [comment]
@Kryptoniq hello, yes please. Thank you.

**Comment by Belance** [comment]
@Kryptoniq ping

**Comment by Belance** [comment]
@kryptoniq ping

**Comment by Belance** [comment]
Guys can you please finish renaming ?

**Comment by freeatnet** [comment]
We're not IDEX ;)
@Belance Any particular reason your website does not support HTTPS?

**Comment by Belance** [comment]
@freeatnet sorry
yes, we applied to receive SSL OV certificate ( green certificate ) . since we officially registered our company we will receive it. So by following things i dont see the reason to support HTTPS since we will receive green certificate asap.

**Comment by freeatnet** [comment]
@belance sounds good. Let me know when it's enabled, please. We can proceed with renaming the old token, but all new entries must support HTTPS.

**Comment by Belance** [comment]
@freeatnet hi again ) I have a good news ) we support now HTTPS while waiting for SSL OV certificate.  So can we proceed with renaming the old token ?))) thanks

**Comment by freeatnet** [comment]
@Belance https://belance.io/erc20.html -> 404 Not Found :(

**Comment by Belance** [comment]
@freeatnet fixed

**Comment by freeatnet** [comment]
Review notes:
- [Old token's](https://github.com/forkdelta/tokenbase/blob/4d831d607b45461043743389eab6cc643cff604c/tokens/0x26d5bd2dfeda983ecd6c39899e69dae6431dffbb.yaml) [website](http://erc20.space) redirects to https://belance.io.
- https://belance.io/erc20.html states the contract address is **0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA**.

Based on this, 0x26d5bd2dfeda983ecd6c39899e69dae6431dffbb will be renamed to ERC20_OLD, and 0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA will be assigned ERC20.

**Comment by freeatnet** [comment]
@Belance Is there an announcement of token swap or similar?

**Comment by Belance** [comment]
@freeatnet regarding your fiatt message 

“Review notes:

Old token's website redirects to https://belance.io.
https://belance.io/erc20.html states the contract address is 0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA.
Based on this, 0x26d5bd2dfeda983ecd6c39899e69dae6431dffbb will be renamed to ERC20_OLD, and 0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA will be assigned ERC20.
 
”

**Comment by Belance** [comment]
@freeatnet regarding your second message “  Is there an announcement of token swap or similar? “

Yes we have for all holders and members in our telegram channel and chat. 

Thanks !

**Comment by Belance** [comment]
@freeatnet hello )) any news regarding  rename of the old token ?
From ERC20 to ERC20_OLD ? 

We waiting for this with all 7+ holders for 2 month already :-) 

By the way announcement can be like this 

“ ERC20 (belance.io) is performing a token swap. You can find the old token at https://forkdelta.github.io/#!/trade/ERC20_OLD-ETH. 

The new token is at https://forkdelta.github.io/#!/trade/ERC20-ETH. “ 

Or something like this )) or you can make only renaming first! 

Please @freeatnet reply, thanks !

**Comment by Belance** [comment]
@freeatnet ) guys ! 

Can you please at least make renaming first ?) 

Because we waiting, holders are waiting, CoinMarketCap is waiting for 2 month : 

 “ Hi,

Thank you for the helpful clarification. Please reply to this ticket when Forkdelta updates the ticker and we will update the market currently listed on our site. “

it’s message from CoinMarketCap.

What you need more for renaming?

Best regards,

**Comment by Belance** [comment]
@freeatnet @Kryptoniq ping guys !

**Comment by freeatnet** [comment]
@Belance Sorry for the delay. The change will be rolled out on **Tuesday, June 26th**.
