### ISSUE TITLE
TOKEN LISTING REQUEST: ERC20 token 

### ISSUE THREAD

**Issue by Belance** [forkdelta/tokenbase#968]
Dear Exchange IDEX! 

We appreciate a lot your hard work everyday and efforts on the IDEX project!

And we kindly asking you to list our token! 

We already discussed this in another issue number #808 and moderator said to open new issue. So we did. And we was waiting for the answer on issue #808 almost a month, and I hope here you will consider request faster. Thanks !

The following info on this text will guide you through the details.

Name: ERC20

Symbol: ERC20

Link to official explorer EtherScan: https://etherscan.io/address/0xc3761eb917cd790b30dad99f6cc5b4ff93c4f9ea#readContract

Contract Address:
0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA

Issuer's official website:
http://belance.io

About our ERC20 blockchain platform Belance: 
http://belance.io/aboutbelance.html

Official contract address confirmation on the official website: 
http://belance.io/erc20.html

A link to a third-party review or discussion of the token:
https://bitcointalk.org/index.php?topic=2304875

Description:

What is the idea behind Belance?

Belance is a large unique superior blockchain superior platform which combines many opportunities and connects everyone in the blockchain world. Whether you're building your new project or searching for something unique, Belance is the first platform where there are unlimited opportunities to connect and discuss with others regarding the cryptocurrency and blockchain industry. Also connect with professionals to help your own project by hiring a specialist to complete a specific task within your project. Promote and advertise your own skills and specialities to clients. Ask questions on any topic related to the blockchain or become a blockchain blogger. Belance is a one stop place for everything for everyone who is interested in or connected to the blockchain world.

Warm regards,
ERC20 team 
belance.io

**Comment by Kryptoniq** [comment]
There are only 5 token holders at the moment.
