### ISSUE TITLE
SilentNotary token (SNTR) for listing

### ISSUE THREAD

**Issue by Domian1980** [forkdelta/tokenbase#969]
Contract address: 0x2859021eE7F2Cb10162E67F33Af2D22764B31aFf

Issuer's official website: https://silentnotary.com/

Description: SilentNotary is World's First Hybrid Blockchain Notary that uses the Blockchain as a service to: TimeStamp, Certify the Existence of Evidence, and Securely store data for Businesses, Governments, Consumers, and for the IoT. The next big thing in the world of fast-moving decision making and evidence creation saving time, energy, and money.
SNTR token is an utility-token, a fuel for notary smart-contract. Some examples of use (but not limited with):
• evaluation of the insurance object (cars and real estate, etc.), and fixing the circumstances of the insured event,
• evaluation of loan collateral (cars, real estate, etc.),
• record the result of completed work (for example, in construction - to create reports to the bank),
• register violations during the inspection (B2G) - control of land use, housing, technical, construction inspections,
• expand notarial public functions by notarizing a digital document (SilentNotary data) to create conclusive evidence.

Official contract address confirmation: https://silentnotary.com/index.html#tokensale
https://silentnotary.com/index.html#white

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.newsbtc.com/press-releases/silentnotary-com-make-debut/
2. http://www.the-blockchain.com/2017/08/02/silentnotary-blockchain-based-notary-chatbot-serves-first-clients/
3. http://www.abnewswire.com/pressreleases/silentnotary-ico-introduces-byteball-in-legal-field_193719.html
[SilentNotary_whitepaper.pdf](https://github.com/forkdelta/tokenbase/files/1931001/SilentNotary_whitepaper.pdf)

**Comment by Kryptoniq** [comment]
#932
