### ISSUE TITLE
Listing BitcoinToken (BTK)

### ISSUE THREAD

**Issue by bitcoin-token** [forkdelta/tokenbase#97]
Contract Address: 0xdb8646f5b487b5dd979fac618350e85018f557d4
Official Website: https://btk.community  (contract address is on our homepage at top)
Review: https://www.cryptoinsider.us/bitcointoken-easily-transferable-easily-tradable/

---  # Mandatory "start of the document" marker
addr: '0xdb8646f5b487b5dd979fac618350e85018f557d4'  # token contract address, in single quotes
decimals: 18 # Token decimals
description: BitcoinToken (BTK) is a digital currency. It uses peer-to-peer technology to operate with no central authority or banks; managing transactions are carried out collectively by the network. BitcoinToken is ERC20-compliant so that it and can be easily tradable on decentralized exchanges. Bitcointoken is open source, community driven, de-centralized, no large pre-mine. Developers are all volunteers. The entire supply of the token will be airdropped over the first release period. Therefore the community will own the token and dictate its future and direction.
Links:
- Telegram: https://t.me/joinchat/HLlnQw9SOw6HzYIehZOCMw
- Reddit: https://www.reddit.com/r/BitcoinToken/
- Twitter: http://www.twitter.com/bitcoin_token
- Website: https://btk.community
name: BitcoinToken  # Required
symbol: BTK  # Required: Token symbol

**Comment by JonathonDunford** [comment]
Address verified: 0xdb8646f5b487b5dd979fac618350e85018f557d4

Looks good.

**Comment by JonathonDunford** [comment]
In a little bit. I will let you know.

**Comment by bitcoin-token** [comment]
ok great!  our community will be excited about this and we will make formal announcements to help spread the word about Fork Delta.  The big bonus is many people are used to the EtherDelta setup so it will be easy to use your platform!

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/pull/72

**Comment by JonathonDunford** [comment]
Awesome! Glad to have you and your community on board. :)
