### ISSUE TITLE
BBI

### ISSUE THREAD

**Issue by the1arty** [forkdelta/tokenbase#970]
Contract address: 0x37d40510a2f5bc98aa7a0f7bf4b3453bcfb90ac1

Issuer's official website: https://belugapay.com/

Description: 

Beluga Pay has created a mobile point of sale system that will provide merchants with a range of tools to make their lives easier and will accept crypto, credit and debit.

Beluga has a live product that is currently being used by over 200 merchants, existing VISA and Mastercard processing certification and a partnership with Mexico’s largest domestic bank, Banorte.

Currently when a merchant accepts a payment with a credit or debit card it can take up to 2-3 working days for the payment to be received. BBI tokens can be used as gas to allow for near-instant merchant deposits. Receiving funds instantly can be a lifeline for small businesses who will be able to pay their staff, buy more stock and cover other vital expenses.

Official contract address confirmation:  https://etherscan.io/token/0x37d40510a2f5bc98aa7a0f7bf4b3453bcfb90ac1

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://themerkle.com/the-next-unicorn-ico-15-bonus-pre-sale-live-what-is-beluga-pay/
2. https://news4c.com/mexico-is-revolutionizing-the-cryptocurrency-market-with-beluga-pay/

**Comment by Kryptoniq** [comment]
https://coinmarketcap.com/currencies/belugapay/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x37d40510a2f5bc98aa7a0f7bf4b3453bcfb90ac1, https://belugapay.com/

**Comment by freeatnet** [comment]
Hi @the1arty! Thank you for your request. I'm closing this request in favour of an earlier request to add BBI: #885. You can track when it's fulfilled there.

Thanks again!

**Comment by the1arty** [comment]
Hello,

thank you, much appreciated!
