### ISSUE TITLE
Listing Token: Decentralized Faucet(DCET)

### ISSUE THREAD

**Issue by DaucetProjects** [forkdelta/tokenbase#971]
Token Name: Decentralized Faucet
Symbol: DCET
Decimals: 0
Contract address: 0xaf7002581c95e18f0803136aff93a9040956b068

Daucet is the First Decentralized Faucet Platform sitting on top of the Ethereum Blockchain. Daucet is ERC-20 Token with a symbol of DCET short called for DAUCET.

Etherscan:
https://etherscan.io/token/0xaf7002581c95e18f0803136aff93a9040956b068

Web page
https://www.daucet.info

Confirming smart contract owned posted in webpage
https://www.daucet.info

Github source code
https://github.com/DaucetProjects/Daucet

Social media
https://t.me/DaucetCommunity
https://twitter.com/DaucetProject
https://facebook.com/daucetproject

Bitcointalk Discussion
https://bitcointalk.org/index.php?topic=3356099

Moving Up!
-Dev zGreen

**Comment by DaucetProjects** [comment]
How fast can we list on forkdelta? Thanks!!

**Comment by DaucetProjects** [comment]
Any updates??

**Comment by Kryptoniq** [comment]
1. 2 Billion tokens but only 12 token holders
2. Your bitcointalk announcement thread has insufficient reviews. Please provide link to a third-party review of your token.

**Comment by DaucetProjects** [comment]
1. We are now going to distribute tokens to the airdrops participants and that is almost 4k participants.

2. We discuss our projects and more at our Telegram Community Chat https://t.me/DaucetCommunity
