### ISSUE TITLE
Add FLOT

### ISSUE THREAD

**Issue by matronator** [forkdelta/tokenbase#972]
Contract address: 0x049399a6B048D52971F7D122aE21A1532722285F
Name: Fire Lotto
Symbol: FLOT
Decimals: 18
Type: ERC-20

Issuer's official website: https://firelotto.io
Second website (the lottery): https://firelotto.com

Description: FireLotto is a crypto lottery on the Ethereum blockchain. The lottery currently features three games with automated drawings every 24 hours. Holders of FLOT will receive a commission from each ticket sold in every drawing.

Official contract address confirmation: https://twitter.com/FireLottery/status/985401373461221377
Second link: https://medium.com/@FireLottery/how-to-add-flot-tokens-to-your-wallet-4694db5d42f4

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://icobench.com/ico/fire-lotto
2. https://bitcointalk.org/index.php?topic=2579275.0
3. https://icoholder.com/en/fire-lotto-ico-17316

Contacts/Social media:
Facebook: https://www.facebook.com/firelotto
Twitter: https://twitter.com/FireLottery
Telegram: https://t.me/firelotto
GitHub: https://github.com/firelotto/firelotto
E-mail: info@firelotto.com

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x049399a6b048d52971f7d122ae21a1532722285f, https://firelotto.io/
