### ISSUE TITLE
FTX token listing

### ISSUE THREAD

**Issue by Viviraj** [forkdelta/tokenbase#973]
Contract address:
https://ethplorer.io/address/0xd559f20296ff4895da39b5bd9add54b442596a61

Issuer's official website:
https://www.fintrux.com/index.aspx

Description: 
Fintrux is a P-P lending platform which helps in reducing the credit risk by credit enhancements. MVP is available. FTX tokens is a utility tokens which is used to pay fees in the platform

Official contract address confirmation: 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://icobench.com/ico/fintrux
2. https://bitcointalk.org/index.php?topic=2286042
3. https://icodrops.com/fintrux/
4. https://medium.com/fintrux/fintrux-partners-with-sentinel-chain-b262819047af

**Comment by Kryptoniq** [comment]
#570
