### ISSUE TITLE
Ziggurat token listing

### ISSUE THREAD

**Issue by EcexExchange** [forkdelta/tokenbase#974]
Contract address:   

0xe760a89967d8c7fa638eebfc15a77ba107674021
--
Issuer's official website: 

https://ecex.exchange/

Description: 

Ziggurat token is utility token meant to buy services from Ecex.Exchange Trading Platform. The token issuer is PlanetZiggurat OÜ owner of Ecex.Exchange Trading Platform.

Name: Ziggurat Token
symbol: ZIG

Official contract address confirmation:   

https://ico.ecex.exchange/ziggurat-ico-quick-facts/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.  https://www.youtube.com/watch?v=a4lLNOaNuoY
2. https://bitcoinexchangeguide.com/ecex-exchange-ico-zig-token/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0xe760a89967d8c7fa638eebfc15a77ba107674021, https://ecex.exchange/
