### ISSUE TITLE
Blackfolio - BLACK

### ISSUE THREAD

**Issue by pixinc** [forkdelta/tokenbase#975]
Contract address: 0xe59000e2b24b90e02d2d4d7fea0eca438a3a66c6

Issuer's official website: https://www.blackfol.io/

Description: Blackfol.io is building a cross exchanges API to combine the total assets owned by a user. and get a performance view of trading mooves. It also allow users to build strategies and execute orders from multiple exchanges.

Official contract address confirmation: Website FAQ => https://www.blackfol.io/#FAQ

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.facebook.com/Pritz777/activity/1835120166781618
2. https://www.facebook.com/pg/blackfolioOfficial/reviews/?ref=page_internal

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

Specifically, the third-party links provided do not contain substantial review of the project, its plans, team, milestones, or existing product.
