### ISSUE TITLE
Listing Request: BelugaPay (BBI)

### ISSUE THREAD

**Issue by vexatuvex** [forkdelta/tokenbase#976]
Contract address: 0x37D40510a2F5Bc98AA7a0f7BF4b3453Bcfb90Ac1
Name: BelugaPay
Decimals: 18
Symbol: BBI

Issuer's official website: https://belugapay.com

Description: BelugaPay enables merchants to accept VISA, Mastercard and all major cryptocurrencies.

Official contract address confirmation: https://belugapay.com
You can see it at the bottom of the website (in the yellow bar).

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
Bitcointalk: https://bitcointalk.org/index.php?topic=2270648.0
Medium: https://medium.com/@BelugaPay
Twitter: https://twitter.com/belugapay
Facebook: https://www.facebook.com/BelugaPay
Telegram: https://t.me/belugapay

**Comment by Kryptoniq** [comment]
#970
