### ISSUE TITLE
Token Listing

### ISSUE THREAD

**Issue by mastem-test** [forkdelta/tokenbase#977]
Contract address: 0xA55fC2f935e5deCd52685e28c9f1e94528F86c70

Issuer's official website: https://shift.cash

Description: SHIFT.cash - the first car title lending platform based on smart contracts

Official contract address confirmation: the contract address is available on the FAQ section of our website stipulation how investors can add custom tokens.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
youtube: https://youtu.be/LY7bPzI34FE
ICO bench: https://icobench.com/ico/shift-cash
Found ICO: https://foundico.com/ico/shiftcash.html
1. 
2.

**Comment by Kryptoniq** [comment]
#862
