### ISSUE TITLE
Go Help Fund listing request

### ISSUE THREAD

**Issue by batrinuvlad** [forkdelta/tokenbase#978]
Contract address: https://etherscan.io/token/0xbbc2045d335cb224228f1850b29173d9d7d7b989

Issuer's official website: https://gohelpfund.com

Description: GoHelpFund is a humanitarian fundraising platform built in order to provide transparency for humanitarian donations and to attract new supporters in the fundraising ecosystem. The token will be used as the main currency of the platform. Users can donate via other cryptocurrency or FIAT, which will be converted to HELP token.

Official contract address confirmation: https://tokensale.gohelpfund.com/home -> Token Tracker section in the top area.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://cointelegraph.com/news/romanian-startup-targets-400-bln-charity-fundraising-market-with-new-platform
2. https://themerkle.com/go-help-fund-connecting-people-with-blockchain-technology/
3. https://icomarks.com/ico/gohelpfund
4. https://icoholder.com/en/gohelpfund-17275
5. http://bitcoinist.com/go-help-fund-making-world-better-place-live/
6. https://bitcointalk.org/index.php?topic=2160815.0

**Comment by Kryptoniq** [comment]
According to Etherscan, there are 0 token holders. Please kindly make an initial distribution before we can consider your request. Thank you.
