### ISSUE TITLE
ETHER QUALITY TOKEN

### ISSUE THREAD

**Issue by ryodoo** [forkdelta/tokenbase#979]
Contract address:
0xdd2e1cdce3b4e0ed01700aa19fcedbdd7bb6d37c

Issuer's official website:
http://etherquality.org/

Description: There are no limitations, it works everywhere. You can send “ETQ” just as easily as an e-mail, and it is almost just as fast. It does not matter what hidden part of the world you are in, you can send and receive “ETQ” in seconds. There are no banks to slow down your transactions, so they are completed almost immediately, even on the weekends.

Official contract address confirmation: http://etherquality.org/#Wallets

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://bitcointalk.org/index.php?topic=3372190.new#new
2.

**Comment by Kryptoniq** [comment]
Your bitcointalk announcement thread has insufficient information.
There are only 8 token holders.
Your project description is what any other ERC20 token can do and doesn't describe what your project is all about.
Sorry, we can't list your token at this time.

**Comment by ryodoo** [comment]
First, we thank you for your responsiveness to our request to add our Ether Quality token. We are a company called Winproex we adopted the system of the direct sale of our service through an MLM network. what makes every prediction service pack purchase in the cryptocurrency market automatically generates a sum of Ether Quality for example if a member buys a Service Discover pack with 150 Dollars it is offered the service plus 150 Ether Quality. So Dear Forkdelta moderator we have not done an Aidrop to have a large number of the wallet holders addresses we only rely on our registered network productivity. please review our request with all these new elements explained in our message.
Our sincere greetings
please see https://bitcointalk.org/index.php?topic=3372190.new#new we have change the description
