### ISSUE TITLE
new token request

### ISSUE THREAD

**Issue by 666Charity** [forkdelta/tokenbase#983]
Contract address:

0xa5f047d05413d2f76baba7920b148fa4e4a68269

Issuer's official website:

http://666.systems

Description: 

666 Is a Atheist Driven Charity Token that is a ERC20 Smart Contract Token. This Tokens earnings will be used for Atheism Causes. 

The 666 Token will be used in Smart Contracts and for Revenue Building to contribute to Atheist Charities. 

Official contract address confirmation: 

https://666.systems/666-eth-smart-contract

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. i would like to donate ethereum to list my coin, 2 ethereum
2.

**Comment by Kryptoniq** [comment]
1. Smart contract source code not verified on etherscan.io
2. Only one token holder
3. No link to a third-party review or discussion of the token

**Comment by 666Charity** [comment]
thank you, ill fix these issues, new coin so im building as i go, ty

Jason Day
Owner
A 24/7 Endeavor
265 Dillon Ridge Rd
Ste C402-102
Dillon, Co 80435

On Apr 24, 2018, at 12:17 AM, Krypton <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Smart contract source code not verified on etherscan.io<http://etherscan.io>
  2.  Only one token holder
  3.  No link to a third-party review or discussion of the token
