### ISSUE TITLE
TOKEN LISTING REQUEST: QBIT

### ISSUE THREAD

**Issue by dantak2000** [forkdelta/tokenbase#984]
Contract address: 0xCb5ea3c190d8f82DEADF7ce5Af855dDbf33e3962

Issuer's official website: https://www.qubitica.net

Description: QUBITICA is a platform for users and developers of Blockchain technology

Official contract address confirmation: https://www.qubitica.net/qbit/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
1. https://www.reddit.com/r/Qubitica/
2. https://www.facebook.com/Qubitica/
3. https://twitter.com/Qubitica
4. https://www.linkedin.com/in/daniel-takriti-22a9a394/

**Comment by Kryptoniq** [comment]
Please provide a link to a third-party review or discussion of the token.

**Comment by dantak2000** [comment]
Most of our token holders are developers and users of the website. They may discuss on all channels under 1-4 and 

https://www.qubitica.net/news/

See channels. 

We also have some bigger token holders as they are related companies who work with us. 

You can also see there my linkedIn profile to see that the whole project is made public to many trustful pepole.

https://www.linkedin.com/in/daniel-takriti-22a9a394/

Altogether the discussion about the token is low as we keep contact to the token holders via account, newslettter and email. We made no ICO and there was no big announcment, etc..

But the channels for discussions are open for everyone, of course.

Best
Daniel Takriti
