### ISSUE TITLE
PLAAK Token Listing

### ISSUE THREAD

**Issue by rahulvyas1** [forkdelta/tokenbase#990]
Contract address: 0x96fc0229b1aab013000909143f079ab096d55317

Issuer's official website: https://www.plaak.com

Description: 

The PLAAK Ecosystem is one stop solution for all blockchain based apps- The Freelance Application, Exchange application, One-Login( Business solution with Biometrics), Payroll, Health, all are inter connected closely integrated and PLK would be the preferred mode of transfer of funds.

Official contract address confirmation: 
https://www.plaak.com/tokensalepage.php 
Please visit the bottom section of this page to find the contract address.

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1.  https://www.nasdaq.com/press-release/plaak-is-australias-blockchain-20180418-01023
2. https://icobench.com/ico/plaak/ratings#ratings
3. https://www.morningstar.com/news/access-wire/ASW_Accesswire_496547MSN/plaak-is-australia39s-blockchain.html
4. https://andra.com.au/latest-news/local-news/3352-world-first-crypto-sponsorship-deal-for-van-dyk-racing.html
5. http://bitcoinist.com/plaak-launches-highly-anticipated-ico-backed-first-decentralized-freelance-market-app-service-providers-tradies-professionals-etc-consumers-will-include-multi-web-pa/

**Comment by rahulvyas1** [comment]
Please email at rahulvyas@plaak.com for any issues.
Thanks

**Comment by Kryptoniq** [comment]
Please verify your contract's source code on etherscan.io

**Comment by rahulvyas1** [comment]
https://etherscan.io/address/0x96fc0229b1aab013000909143f079ab096d55317

Here. Please confirm

**Comment by Kryptoniq** [comment]
Contract source code still not verified.
