### ISSUE TITLE
Token Listing PurpleCoin - PPC

### ISSUE THREAD

**Issue by acfmichelsen** [forkdelta/tokenbase#991]
Contract address: 0x809faaf63ee61b9133102b4fbe560219b534b6e4
decimals: 18
Name: PurpleCoin
TOKEN: PPC
Description (short): PurpleThrone is a music streaming service and digital label geared towards independent artists.  

Issuer's official website: https://purplethrone.com/

Description: 

PurpleThrone is a music streaming service and digital label which is integrating PurpleCoin, a digital asset, to facilitate in app commerce and issue artist royalties.  PurpleThrone has improved how millennials discover, support, share and interact with new music by enabling direct micro-payments to musicians and localized leader boards.  PurpleThrone allows fans to be influencers, create unique playlists and find communities that suits their unique individual personalities. PurpleThrone receives a  percentage of all “tips” fans contribute to artists. PurpleThrone also acts as a broker by taking a commission from every venue or studio that books artists in the PurpleThrone ecosystem.

Official contract address confirmation:  please find the token contract address on the website token sales page https://purplethrone.com/token-sales/

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://tokenmarket.net/blockchain/ethereum/assets/purple-throne/
2. http://smarturl.it/purpleroompodcast
3. https://itunes.apple.com/us/app/purplethrone/id1190778495?mt=8
4. https://coinlauncher.io/purple-throne-ico

**Comment by freeatnet** [comment]
PurpleThrone's [ICO Terms and Conditions](https://purplethrone.com/ico-terms-and-conditions/) ([archived](http://archive.is/lYUAz)) are a copy-paste of X8's Terms and Conditions — including their business number (CHE-443.293.723). So there's that.

**Comment by freeatnet** [comment]
@acfmichelsen Could you provide any third-party **reviews** of the project or token? Reviews should include discussion of the company, project, vision, white paper, business model, project goals or timeline, or existing product.

**Comment by acfmichelsen** [comment]
Hi Arseniy,
Just realized that the emails didn't go through as they were too large for
the mailbox surprisingly. Anyways, here's the links below requested.

**Comment by freeatnet** [comment]
@acfmichelsen That's one review I can see (in the gdoc, appears sourced from [this blog post](https://medium.com/@kerryctx/purplethrone-the-new-digital-music-medium-e48638703a9e) ([archived](http://archive.is/JCxhA))).

I've also confirmed that PurpleThrone has no association with the business number mentioned on their Terms of ICO; business name in St Kitts & Nevis is unverified. Has PurpleThrone published any business registrations or undergone any ICO fact check?
