### ISSUE TITLE
Listing request for Pindex (PDI)

### ISSUE THREAD

**Issue by erikmollink** [forkdelta/tokenbase#992]
Contract address: 0xC50948bac01116F246259070Ea6084C04649efDF

Issuer's official website: https://pindex.uci.global

Description: 
Pindex (PDI) is a utility token for the Pindify marketplace platform for providers of music, art & media.
The token can be used to pay for subscriptions to the platform, and facilitates financial transaction between providers and services that we work with. The platform itself, including apps for android and ios is already live as an MVP at https://www.pindify.com/marketplace, has a solid roadmap and dedicated team of currently 45 members.

Official contract address confirmation: https://pindex.uci.global/#getting-started

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://www.youtube.com/watch?v=Ed52ggDsJDs&t=910s
2. https://bitcoinexchangeguide.com/pindify/
3. https://foxico.io/project/pindextokenico
4. https://www.ico-check.com/pindify
5. https://icoholder.com/en/pindex-3526

**Comment by Kryptoniq** [comment]
Please verify your contract address on etherscan.io .https://etherscan.io/address/0xC50948bac01116F246259070Ea6084C04649efDF#code.

**Comment by erikmollink** [comment]
We are having difficulties with contract verification. Contract was created via Mist last year October. When we use the original sourcecode, parameters and compiler version, we get a bytecode difference. Trying to work it out.

**Comment by erikmollink** [comment]
Contract address has been verified

**Comment by freeatnet** [comment]
@erikmollink Thank you for your request! Unfortunately, out of the third-party review links you provided, only one (bitcoinexchangeguide.com) contains any original discussion of the token. Could you find another review, please?

**Comment by erikmollink** [comment]
https://crypto24h.io/pindify-ico-review/
https://www.youtube.com/watch?v=-_O3x1lJM9c
https://www.youtube.com/watch?v=RW6oLOlmUIU&t=6s
https://www.youtube.com/watch?v=k4vzLBYZAvw

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.

**Comment by erikmollink** [comment]
Great! Thanks.

**Comment by erikmollink** [comment]
One question left: how long does it normally take from this stage until token is live? Days? Weeks?

**Comment by erikmollink** [comment]
@freeatnet Do you know how long it normally takes before the token is live?

**Comment by erikmollink** [comment]
Any update?
