### ISSUE TITLE
Request for listed MGT token 

### ISSUE THREAD

**Issue by MEGATRON-MGT** [forkdelta/tokenbase#995]
Contract address: 0x966d9db7293eb7bd82971cb07838e5679dadc50f

Issuer's official website: https://megatron.io

Description: Megatron is the next generation blockchain driven decentralized cryptocurrency that runs on most secure open source Ethereum blockchain technology. It connects worldwide Ethereum miners , entrepreneurs and the crowd Together.

Megatron will work specially for the miners, traders & investors community worldwide to ensure a safe and flexible business environment. Our goal is to make the digital currency’s capital markets more transparent, open and connected by developing ethereum miners community and mining tools obtainable.

Official contract address confirmation:  Please visit our website: https://megatron.io 
you will find contract address on "Token Specifications" section. 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. On Bitcointalk: https://bitcointalk.org/index.php?topic=3133601.0
2. Facebook page review : https://www.facebook.com/megatron.io
3. YouTube review: https://www.youtube.com/watch?v=NezYv361lHk

**Comment by Kryptoniq** [comment]
Scam. Team members are photoshopped images.
Allegations and proofs: https://bitcointalk.org/index.php?topic=3199428.0
http://archive.is/iXWJT

Sorry, we can't list your token.
