### ISSUE TITLE
MunchCoin

### ISSUE THREAD

**Issue by MunchCoin** [forkdelta/tokenbase#996]
Contract address: **0x26b7d545de1c04af88dd2a5f3f4c8f58108c55a2**

Issuer's official website: **https://munchcoin.co/**

Description: 

**The MunchCoin Project is the first blockchain based food rewards system! We aim to build the biggest universal rewards system for privately owned food businesses. Our MunchCoin token will act as the reward for when a consumer purchases some type of food at one of these businesses when they are certified by us.**

Official contract address confirmation: 

**Go to our homepage and click on the "BlockExplorer" tab from there.**

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. **Here are a few videos made by other people about us!
https://www.youtube.com/results?search_query=MUNCHCOIN**

2. **Here is some discussion on our bitcointalk of "Sr.member" and "Legendary" commenting on how we work.
https://bitcointalk.org/index.php?topic=2970537.0**

**Comment by MunchCoin** [comment]
Forgot to mention, the ticker would be **$MNCH**

**Comment by Kryptoniq** [comment]
I couldn't find any constructive review on your bitcointalk announcement thread. Please provide link to a third-party review of your token other than bitcointalk.

**Comment by MunchCoin** [comment]
The youtube link should suffice, there are multiple reviews of our project on there.
**https://www.youtube.com/watch?v=6Q1fvxYQCrc
https://www.youtube.com/watch?v=0YX-zT7kjcs
https://www.youtube.com/watch?v=0AQqrwoBydI**

 Here is also an article written by one of our community members in Japanese. **http://i486.mods.jp/ichild/?p=2313**

Not to mention we already have real-world application, you can check it out on our website here! **https://munchcoin.co/certified-eateries**
We are growing as we speak!

**Comment by MunchCoin** [comment]
It's not easy getting reviews since we did not have an ICO. Most ICOs get their reviews from ICO review websites as you know.

**Comment by freeatnet** [comment]
@MunchCoin You mention some locations here: https://munchcoin.co/certified-eateries — but I can't seem to find any references to the partnerships on the establishments' resources. Links to the certified eateries linking to you would go a long way!

**Comment by MunchCoin** [comment]
The pictures themselves show their physical storefronts with our certification sticker on their windows/door which should show that they approve of our association with them! 

Although we will  definitely take your advice and get in contact with these eateries and any future ones in incorporating our link on their website or resources!

Is there anyway with getting in contact with you guys any sooner than last time though? We understand you guys have alot of applications to deal with but we also would like to be listed ( if you'd allow) in a timely manner, our community is very anxious!

Thank you!

**Comment by MunchCoin** [comment]
Any updates?

**Comment by MunchCoin** [comment]
Bump

**Comment by MunchCoin** [comment]
@freeatnet @Philipinho 
Can we have some help please? we applied almost a year ago, thanks :)

- MunchCoin Support

**Comment by Philipinho** [comment]
Hi @MunchCoin, I'm no longer part of ForkDelta.
