### ISSUE TITLE
FTB token listing

### ISSUE THREAD

**Issue by XMangoo** [forkdelta/tokenbase#998]
Contract address:
https://etherscan.io/token/0x71c25dd74a8bf4fb393cb06623aa43a5376d1431

Issuer's official website:
https://feitebi.org/

Description: 
The feitebi token is used to be as gas on social media and cross chain exchange strategies.

Official contract address confirmation: 
Email: shanghai2k10@hotmail.com
homepage: http://feitebi.org/
GitHub: https://github.com/feitebi

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:
Currently, the token already listed on ceo.bi exchange, which have thousands users.

**Comment by Kryptoniq** [comment]
Do you own these websites ? { http://bitdash.net - http://feitebi.org - https://feitebi.com/index.en.html}.

**Comment by XMangoo** [comment]
Yes, thanks a lot!

**Comment by XMangoo** [comment]
We're ready now, thanks!

**Comment by freeatnet** [comment]
Please update your request to the following required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md
