### ISSUE TITLE
Request for a token listing

### ISSUE THREAD

**Issue by IPStock** [forkdelta/tokenbase#999]
Contract address: we do not have contract address, yet. 

Issuer's official website:  https://ico.ipstock.com/

Description:  IPStock uses a disruptive blockchain technology to create ecosystem for Visual Digital Content Assets management, licensing and trading. IPStock shall issue IPS token to be the only payment instrument within the created ecosystem, allowing thousands of its participants to sell, purchase, rent, upgrade Visual Digital Content, as well as request and get special services (e.g. analytics).  

Official contract address confirmation:  As we do not have contract address yet - we cannot provide its confirmation. 

Links to third-party reviews or discussion of the token, the project/product, or the token issuer:

1. https://wheretoinvest.money/ipstock-ico-review/   
2. https://wheretoinvest.money/ipstock-ico-review/  
3. https://www.save-yourmoney.ru/news/ico-ipstock-vizualizirovannyj-tsifrovoj-reestr-kontenta-na-blokchejn/    
4. https://golos.io/ru--blokcheijn/@lordstein/ipstock-ico-reviews-ru-or-video-obzor    http://telegra.ph/IPStock-facts-03-12  
5. https://youtu.be/fshruPEiTLI 
6. https://m.youtube.com/watch?v=o41ptdGmZEc    7.https://steemit.com/cryptocurrency/@cryptocontender/5-reasons-why-ipstock-could-sink-shutterstock

**Comment by Kryptoniq** [comment]
You mean you dont't have a contract address? Come back when you are ready.
Thank you.
